### ISSUE TITLE
PageController.page crashes on a null check exception before it has content dimension

### ISSUE THREAD

**Issue by adaigle** [flutter/flutter#87817]
When accessing the `page` property of `PageController` before the controller is attached and has a valid content dimensions, it throws a `TypeError` for a "Null check operator used on a null value".
This appears as the wrong exception given that this assert is supposed to validate the dimension:
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/page_view.dart#L388

Two suggested improvements:
1) Fix the assert above to check the actual nullable values instead of the null-checked getters `minScrollExtent`/`maxScrollExtent` (i.e.: the private member `_minScrollExtent`/`_maxScrollExtent`) or perhaps rely on `hasContentDimensions`.

2) Consider returning a null page when there is no content dimension or expose a way to check whether accessing the page is acceptable through the `PageController` API. At this point, it is a combination of checking:
```dart
pageController.hasClient && pageController.position.hasContentDimension && pageController.page != null
```

**Comment by maheshmnj** [comment]
Hi @adaigle, 
Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) to better address the issue.

Thank you

**Comment by adaigle** [comment]
Thanks @maheshmnj, here's the info you requested:

<details><summary>flutter doctor -v</summary>
<p>

```
[✓] Flutter (Channel dev, 2.5.0-5.0.pre, on macOS 11.5.1 20G80 darwin-x64, locale en-CA)
    • Flutter version 2.5.0-5.0.pre at /Users/daiglea/homebrew/Caskroom/flutter/2.2.3/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0f465e5b2a (5 days ago), 2021-08-04 18:59:50 -0400
    • Engine revision a0d89b1a54
    • Dart version 2.14.0 (build 2.14.0-377.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/daiglea/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio with Blaze.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio with Blaze.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2020.3.4)
    • IntelliJ at /Applications/IntelliJ CE (stable).app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • Pixel 4a (mobile) • 0A211JEC216725 • android-arm64  • Android 11 (API 30)
    • Chrome (web)      • chrome         • web-javascript • Google Chrome 92.0.4515.131

• No issues found!
```
</p>
</details>

<details><summary>Minimal example</summary>
<p>

```dart
import 'package:flutter/material.dart';

void main() {
  // Notice that the error is "Unexpected null value" and not the assert message.
  FlutterError.onError = (detail) => debugPrint('FlutterError caught: ${detail.exception.toString()}');
  
  runApp(MaterialApp(
    home: MyList(),
   ));
} 

class MyList extends StatefulWidget {
  @override
  State<MyList> createState() => _MyListState();
}

class _MyListState extends State<MyList> {
  late PageController _controller;
  
  @override
  void initState() {
    super.initState();
    _controller = PageController(initialPage: 1);
  }
  
  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }
  
  @override
  Widget build(BuildContext context) =>
    PageView.builder(
      controller: _controller,
      itemCount: 3,
      itemBuilder: (context, index) => Focus(
        // Use _controller.page anywhere before the initial attachment. For example here:
        autofocus: index == _controller.page,
        
        // Safe access by checking hasContentDimensions beforehand:
        // autofocus: index == 
        //  (_controller.hasClients && _controller.position.hasContentDimensions
        //    ? _controller.page : _controller.initialPage),
        child: Center(
          child: Text('Delegate #$index'),
        ),
      ),
    );
}
```
</p>
</details>

<details><summary>flutter run --verbose</summary>
<p>

```
[  +79 ms] Syncing files to device Pixel 4a...
[   +1 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +2 ms] <- recompile package:projects/main.dart 98da6b3b-5e4d-49dd-ac24-8e8ec01a75bd
[        ] <- 98da6b3b-5e4d-49dd-ac24-8e8ec01a75bd
[  +51 ms] Updating files.
[        ] DevFS: Sync finished
[        ] Syncing files to device Pixel 4a... (completed in 56ms)
[        ] Synced 0.0MB.
[   +1 ms] <- accept
[   +4 ms] Connected to _flutterView/0xb40000741f9e2750.
[   +3 ms] Flutter run key commands.
[   +1 ms] r Hot reload. 🔥🔥🔥
[        ] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] 💪 Running with sound null safety 💪
[        ] An Observatory debugger and profiler on Pixel 4a is available at: http://127.0.0.1:50608/IwenigMWRLw=/
[+1042 ms] 
                    ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
                    The following _CastError was thrown building:
                    Null check operator used on a null value
                    
                    When the exception was thrown, this was the stack:
                    #0      ScrollPosition.minScrollExtent (package:flutter/src/widgets/scroll_position.dart:139:49)
                    #1      _PagePosition.page (package:flutter/src/widgets/page_view.dart:388:22)
                    #2      PageController.page (package:flutter/src/widgets/page_view.dart:181:21)
                    #3      _MyListState.build.<anonymous closure> (package:projects/main.dart:39:43)
                    #4      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:456:22)
                    #5      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:1214:28)
                    #6      SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1227:55)
                    #7      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2573:19)
                    #8      SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1220:12)
                    #9      RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure>
(package:flutter/src/rendering/sliver_multi_box_adaptor.dart:349:23)
                    #10     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1968:59)
                    #11     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:916:15)
                    #12     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1968:14)
                    #13     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:338:5)
                    #14     RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:422:5)
                    #15     RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:205:12)
                    #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
                    #17     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:137:12)
                    #18     _RenderSliverFractionalPadding.performLayout (package:flutter/src/widgets/sliver_fill.dart:167:11)
                    #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
                    #20     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:510:13)
                    #21     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1580:12)
                    #22     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1489:20)
                    #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
                    #24     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
                    #26     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
                    #28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
                    #30     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
                    #32     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
                    #34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
                    #36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
                    #38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #39     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:545:11)
                    #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
                    #41     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #42     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
                    #43     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #44     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
                    #45     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #46     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
                    #47     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #48     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
                    #49     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #50     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
                    #51     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #52     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
                    #53     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #54     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
                    #55     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #56     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
                    #57     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #58     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
                    #59     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #60     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3422:13)
                    #61     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
                    #62     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #63     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
                    #64     _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:745:15)
                    #65     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
                    #66     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #67     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
                    #68     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #69     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
                    #70     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #71     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
                    #72     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #73     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:545:11)
                    #74     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
                    #75     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #76     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
                    #77     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #78     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
                    #79     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #80     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
                    #81     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #82     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
                    #83     RenderView.performLayout (package:flutter/src/rendering/view.dart:165:14)
                    #84     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1713:7)
                    #85     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:885:18)
                    #86     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:453:19)
                    #87     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
                    #88     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
                    #89     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
                    #90     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1080:9)
                    #91     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:863:7)
                    (elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
                    ════════════════════════════════════════════════════════════════════════════════════════════════════
```
</p>
</details>

The stacktrace above points directly to the null check running within the `assert` statement linked in the issue description. The evaluation of the assert crash rather than having the assert properly trigger with the correct exception type.

The proposed PR fixes this _and_ allows calling `controller.page` in release and returns `null` while the controller is not attached.

**Comment by maheshmnj** [comment]
reproducible on the latest stable and the master channel.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-arm, locale en-GB)
    • Flutter version 2.2.3 at /Users/mahesh/Documents/flutter
    • Framework revision f4abaa0735 (6 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.4 20F71 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 92.0.4515.131

• No issues found!
```

```
[✓] Flutter (Channel master, 2.5.0-6.0.pre.21, on macOS 11.4 20F71 darwin-arm, locale en-GB)
    • Flutter version 2.5.0-6.0.pre.21 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 40e8620a27 (4 days ago), 2021-08-06 09:14:50 +0430
    • Engine revision 431ac604da
    • Dart version 2.14.0 (build 2.14.0-383.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.4 20F71 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 92.0.4515.131

• No issues found!
```
</details>

**Comment by nt4f04uNd** [comment]
The associated PR has landed, can this be closed?

**Comment by adaigle** [comment]
Yes, thanks. Issue resolved.
