### ISSUE TITLE
Error launching application on Linux.

### ISSUE THREAD

**Issue by KristijanZic** [flutter/flutter#87825]
## Steps to Reproduce

1. create a new flutter project and try launching it in debug mode on Ubuntu 20.04 (Linux).
2. Observe the error:
 ```
Launching lib/main.dart on Linux in debug mode...
Building Linux application...
Error waiting for a debug connection: The log reader stopped unexpectedly.
Error launching application on Linux.
 ```

## Logs

<details>
<summary>Logs</summary>

```
$ flutter --verbose run -d linux
[  +55 ms] executing: uname -m
[  +27 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +4 ms] executing: [/home/aresminos/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +5 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] f18b9281c2280c2646aa3d4348715ed5bb9446c8
[        ] executing: [/home/aresminos/snap/flutter/common/flutter/] git tag --points-at f18b9281c2280c2646aa3d4348715ed5bb9446c8
[  +14 ms] Exit code 0 from: git tag --points-at f18b9281c2280c2646aa3d4348715ed5bb9446c8
[        ] 2.4.0-4.2.pre
[  +16 ms] executing: [/home/aresminos/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/home/aresminos/snap/flutter/common/flutter/] git ls-remote --get-url origin
[   +6 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +80 ms] executing: [/home/aresminos/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[  +47 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +56 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +65 ms] Skipping pub get: version match.
[  +91 ms] Generating
/home/aresminos/Projects/AndroidStudioProjects/test_desktop_debug/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +92 ms] Initializing file store
[   +7 ms] Skipping target: gen_localizations
[   +5 ms] Skipping target: gen_dart_plugin_registrant
[        ] Skipping target: _composite
[   +1 ms] complete
[   +5 ms] Launching lib/main.dart on Linux in debug mode...
[   +5 ms] /home/aresminos/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/aresminos/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/aresminos/snap/flutter/common/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names
--experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill /tmp/flutter_tools.AZRPSJ/flutter_tool.WWYHZX/app.dill --packages
/home/aresminos/Projects/AndroidStudioProjects/test_desktop_debug/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts
--track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build/c075001b96339384a97db4862b8ab8db.cache.dill.track.dill
--enable-experiment=alternative-invalidation-strategy
[  +21 ms] Building Linux application...
[  +19 ms] <- compile package:test_desktop_debug/main.dart
[   +2 ms] executing: [build/linux/x64/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DFLUTTER_TARGET_PLATFORM=linux-x64
/home/aresminos/Projects/AndroidStudioProjects/test_desktop_debug/linux
[  +45 ms] -- Configuring done
[   +1 ms] -- Generating done
[        ] -- Build files have been written to: /home/aresminos/Projects/AndroidStudioProjects/test_desktop_debug/build/linux/x64/debug
[   +6 ms] executing: ninja -C build/linux/x64/debug install
[   +9 ms] ninja: Entering directory `build/linux/x64/debug'
[+2104 ms] [1/5] Generating /home/aresminos/Projects/AndroidStudioProjects/test_desktop_debug/linux/flutter/ephemeral/libflutter_linux_gtk.so,
/home/aresminos/Projects/AndroidStudioProjects/test_desktop_debug/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h,
/home/aresminos/Projects/AndroidStudioProjects/test_desktop_debug/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h,
/home/aresminos/Projects/AndroidStudioProjects/test_desktop_debug/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h,
/home/aresminos/Projects/AndroidStudioProjects/test_desktop_debug/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h,
/home/aresminos/Projects/AndroidStudioProjects/test_desktop_debug/linux/flutter/ephemeral/flutter_linux/fl_engine.h,
/home/aresminos/Projects/AndroidStudioProjects/test_desktop_debug/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h,
/home/aresminos/Projects/AndroidStudioProjects/test_desktop_debug/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h,
/home/aresminos/Projects/AndroidStudioProjects/test_desktop_debug/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h,
/home/aresminos/Projects/AndroidStudioProjects/test_desktop_debug/linux/flutter/ephemeral/flutter_linux/fl_method_call.h,
/home/aresminos/Projects/AndroidStudioProjects/test_desktop_debug/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h,
/home/aresminos/Projects/AndroidStudioProjects/test_desktop_debug/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h,
/home/aresminos/Projects/AndroidStudioProjects/test_desktop_debug/linux/flutter/ephemeral/flutter_linux/fl_method_response.h,
/home/aresminos/Projects/AndroidStudioProjects/test_desktop_debug/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h,
/home/aresminos/Projects/AndroidStudioProjects/test_desktop_debug/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h,
/home/aresminos/Projects/AndroidStudioProjects/test_desktop_debug/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h,
/home/aresminos/Projects/AndroidStudioProjects/test_desktop_debug/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h,
/home/aresminos/Projects/AndroidStudioProjects/test_desktop_debug/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h,
/home/aresminos/Projects/AndroidStudioProjects/test_desktop_debug/linux/flutter/ephemeral/flutter_linux/fl_value.h,
/home/aresminos/Projects/AndroidStudioProjects/test_desktop_debug/linux/flutter/ephemeral/flutter_linux/fl_view.h,
/home/aresminos/Projects/AndroidStudioProjects/test_desktop_debug/linux/flutter/ephemeral/flutter_linux/flutter_linux.h, _phony_
[   +3 ms] [  +58 ms] executing: uname -m
[        ] [  +32 ms] Exit code 0 from: uname -m
[        ] [        ] x86_64
[        ] [   +5 ms] executing: [/home/aresminos/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [   +4 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] f18b9281c2280c2646aa3d4348715ed5bb9446c8
[        ] [        ] executing: [/home/aresminos/snap/flutter/common/flutter/] git tag --points-at f18b9281c2280c2646aa3d4348715ed5bb9446c8
[        ] [  +13 ms] Exit code 0 from: git tag --points-at f18b9281c2280c2646aa3d4348715ed5bb9446c8
[        ] [        ] 2.4.0-4.2.pre
[        ] [  +14 ms] executing: [/home/aresminos/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/beta
[        ] [        ] executing: [/home/aresminos/snap/flutter/common/flutter/] git ls-remote --get-url origin
[        ] [   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +61 ms] executing: [/home/aresminos/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[        ] [   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] beta
[        ] [  +42 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [  +88 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [  +36 ms] Initializing file store
[        ] [   +5 ms] Done initializing file store
[        ] [  +35 ms] Skipping target: gen_localizations
[        ] [  +12 ms] Skipping target: gen_dart_plugin_registrant
[        ] [ +386 ms] Skipping target: unpack_linux
[        ] [ +331 ms] Skipping target: kernel_snapshot
[        ] [ +210 ms] Skipping target: debug_bundle_linux-x64_assets
[        ] [        ] Persisting file store
[        ] [   +8 ms] Done persisting file store
[        ] [   +4 ms] build succeeded.
[        ] [   +8 ms] "flutter assemble" took 1,148ms.
[        ] [ +176 ms] ensureAnalyticsSent: 172ms
[        ] [   +4 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 0
[ +361 ms] [2/5] Building CXX object CMakeFiles/test_desktop_debug.dir/flutter/generated_plugin_registrant.cc.o
[  +70 ms] [3/5] Building CXX object CMakeFiles/test_desktop_debug.dir/my_application.cc.o
[  +96 ms] [4/5] Linking CXX executable intermediates_do_not_run/test_desktop_debug
[        ] [4/5] Install the project...
[  +11 ms] -- Install configuration: "Debug"
[   +8 ms] -- Installing: /home/aresminos/Projects/AndroidStudioProjects/test_desktop_debug/build/linux/x64/debug/bundle/test_desktop_debug
[        ] -- Set runtime path of "/home/aresminos/Projects/AndroidStudioProjects/test_desktop_debug/build/linux/x64/debug/bundle/test_desktop_debug" to
"$ORIGIN/lib"
[        ] -- Installing: /home/aresminos/Projects/AndroidStudioProjects/test_desktop_debug/build/linux/x64/debug/bundle/data/icudtl.dat
[        ] -- Installing: /home/aresminos/Projects/AndroidStudioProjects/test_desktop_debug/build/linux/x64/debug/bundle/lib/libflutter_linux_gtk.so
[  +34 ms] -- Installing: /home/aresminos/Projects/AndroidStudioProjects/test_desktop_debug/build/linux/x64/debug/bundle/data/flutter_assets
[        ] -- Installing: /home/aresminos/Projects/AndroidStudioProjects/test_desktop_debug/build/linux/x64/debug/bundle/data/flutter_assets/AssetManifest.json
[        ] -- Installing: /home/aresminos/Projects/AndroidStudioProjects/test_desktop_debug/build/linux/x64/debug/bundle/data/flutter_assets/NOTICES.Z
[        ] -- Installing: /home/aresminos/Projects/AndroidStudioProjects/test_desktop_debug/build/linux/x64/debug/bundle/data/flutter_assets/version.json
[        ] -- Installing: /home/aresminos/Projects/AndroidStudioProjects/test_desktop_debug/build/linux/x64/debug/bundle/data/flutter_assets/packages
[        ] -- Installing:
/home/aresminos/Projects/AndroidStudioProjects/test_desktop_debug/build/linux/x64/debug/bundle/data/flutter_assets/packages/cupertino_icons
[        ] -- Installing:
/home/aresminos/Projects/AndroidStudioProjects/test_desktop_debug/build/linux/x64/debug/bundle/data/flutter_assets/packages/cupertino_icons/assets
[        ] -- Installing:
/home/aresminos/Projects/AndroidStudioProjects/test_desktop_debug/build/linux/x64/debug/bundle/data/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.
ttf
[        ] -- Installing: /home/aresminos/Projects/AndroidStudioProjects/test_desktop_debug/build/linux/x64/debug/bundle/data/flutter_assets/fonts
[        ] -- Installing:
/home/aresminos/Projects/AndroidStudioProjects/test_desktop_debug/build/linux/x64/debug/bundle/data/flutter_assets/fonts/MaterialIcons-Regular.otf
[        ] -- Installing: /home/aresminos/Projects/AndroidStudioProjects/test_desktop_debug/build/linux/x64/debug/bundle/data/flutter_assets/kernel_blob.bin
[  +37 ms] -- Installing: /home/aresminos/Projects/AndroidStudioProjects/test_desktop_debug/build/linux/x64/debug/bundle/data/flutter_assets/FontManifest.json
[  +11 ms] Building Linux application... (completed in 2,827ms)
[ +340 ms] Error waiting for a debug connection: The log reader stopped unexpectedly.
[   +3 ms] Error launching application on Linux.
[+3796 ms] "flutter run" took 7,355ms.
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:671:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1126:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>
           
           
[  +44 ms] ensureAnalyticsSent: 42ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

```

```
$ flutter doctor -v
[✓] Flutter (Channel beta, 2.4.0-4.2.pre, on Ubuntu 20.04.2 LTS 5.11.0-25-generic, locale en_US.UTF-8)
    • Flutter version 2.4.0-4.2.pre at /home/aresminos/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f18b9281c2 (2 weeks ago), 2021-07-22 14:08:30 -0700
    • Engine revision 844c29f42a
    • Dart version 2.14.0 (build 2.14.0-301.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/aresminos/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /snap/android-studio/current/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /snap/android-studio/114/android-studio
    • Flutter plugin version 59.0.2
    • Dart plugin version 203.8292
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Android Studio (version 4.2)
    • Android Studio at /snap/android-studio/113/android-studio
    • Flutter plugin version 58.0.1
    • Dart plugin version 202.8531
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] Android Studio
    • Android Studio at /snap/android-studio/current/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /snap/android-studio/current/android-studio
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.2 LTS 5.11.0-25-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.114

• No issues found!

```

</details>

**Comment by TahaTesser** [comment]
Hi @KristijanZic 
This seems like an issue with Flutter snap, see https://github.com/flutter/flutter/issues/73611#issuecomment-809237806
For issues related to Flutter snap, please file it [here](https://github.com/canonical/flutter-snap/issues) 
Thank you
