### ISSUE TITLE
[flutter_markdown] MarkdownBody tries to render the object as an image

### ISSUE THREAD

**Issue by omatt** [flutter/flutter#87857]
## Steps to Reproduce

1. Add [flutter_markdown: ^0.6.4](https://pub.dev/packages/flutter_markdown) to your app.
2. Add this Widget:

```dart
MarkdownBody(`'![](https://github-readme-stats.vercel.app/api/top-langs/?username=omatt&layout=compact)]'`)
```

3. Run the app either on mobile or web

<details>
<summary><b>Error Logs</b></summary>

```
======== Exception caught by image resource service ================================================
The following ImageCodecException was thrown resolving an image codec:
Failed to load network image.
Image URL: https://github-readme-stats.vercel.app/api/top-langs/?username=omatt&layout=compact
Trying to load an image from another domain? Find answers at:
https://flutter.dev/docs/development/platform-integration/web-images

When the exception was thrown, this was the stack: 
Image provider: NetworkImage("https://github-readme-stats.vercel.app/api/top-langs/?username=omatt&layout=compact", scale: 1)
Image key: NetworkImage("https://github-readme-stats.vercel.app/api/top-langs/?username=omatt&layout=compact", scale: 1)
====================================================================================================
```

</details>

**Expected results:** 

It should be able to render the Widget as

[![Top Languages](https://github-readme-stats.vercel.app/api/top-langs/?username=omatt&layout=compact)](https://github.com/omatt)

**Actual results:** 

<img width="646" alt="Screen Shot 2021-08-07 at 10 23 06 PM" src="https://user-images.githubusercontent.com/4143153/128603383-e9d414ed-f9e1-4449-8c50-f6c70a9ace1d.png">

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.1 20G80 darwin-x64, locale en)
    • Flutter version 2.2.3
    • Framework revision f4abaa0735 (5 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • iPhone Xs (mobile) • 82CF4677-9933-4698-AD5C-823D6E93F283 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 92.0.4515.131

! Doctor found issues in 1 category.

```

</details>

**Comment by omatt** [comment]
I found a workaround by rendering the URL as a page using HtmlElementView, following this [guide](https://stackoverflow.com/a/58154078/2497859).

**Comment by darshankawar** [comment]
@omatt 
Can you provide a complete minimal code sample ?
Thanks.

**Comment by omatt** [comment]
Here you go

```dart
import 'package:flutter/material.dart';
import 'package:flutter_markdown/flutter_markdown.dart';

void main() {
  runApp(
    MaterialApp(
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    ),
  );
}
class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key}) : super(key: key);
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Markdown Sample'),
      ),
      body: Center(
        child: MarkdownBody(data: '![](https://github-readme-stats.vercel.app/api/top-langs/?username=omatt&layout=compact)]'),
      ),
    );
  }
}
```
Maybe rendering pages using`![](stringURL)` like in GitHub isn't something flutter_markdown supports.

**Comment by darshankawar** [comment]
```
======== Exception caught by image resource service ================================================
The following _Exception was thrown resolving an image codec:
Exception: Invalid image data

When the exception was thrown, this was the stack: 
#0      _futurize (dart:ui/painting.dart:5326:5)
#1      ImageDescriptor.encoded (dart:ui/painting.dart:5194:12)
#2      instantiateImageCodec (dart:ui/painting.dart:2048:60)
<asynchronous suspension>
Image provider: NetworkImage("https://github-readme-stats.vercel.app/api/top-langs/?username=omatt&layout=compact", scale: 1.0)
Image key: NetworkImage("https://github-readme-stats.vercel.app/api/top-langs/?username=omatt&layout=compact", scale: 1.0)
====================================================================================================

```

Keeping it open for further insights from the team.

<details>
<summary> flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.2.3 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision f4abaa0735 (4 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dhs/Library/Android/sdk
    • Java binary at: /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.    

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • SM G975F (mobile) • RZ8M802WY0X • android-arm64 • Android 10 (API 29)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 91.0.4472.114

• No issues found!





```

</details>

**Comment by jason-simmons** [comment]
That URL is producing an SVG document, not a bitmap image.

Try rendering it with https://pub.dev/packages/flutter_svg

**Comment by darshankawar** [comment]
@omatt 
Try above solution and confirm.

**Comment by omatt** [comment]
flutter_svg doesn't seem to support the SVG script from the url. Here's what I've tried.

```dart
SvgPicture.network(
  url,
  placeholderBuilder: (BuildContext context) => Container(
      padding: const EdgeInsets.all(30.0),
      child: const CircularProgressIndicator(),
  ),
),
```

### Error logs
<details>
  <summary>Logs</summary>

```
======== Exception caught by SVG ===================================================================
The following UnimplementedError was thrown in parseSvgElement:
The <style> element is not implemented in this library.

Style elements are not supported by this library and the requested SVG may not render as intended.

If possible, ensure the SVG uses inline styles and/or attributes (which are supported), or use a preprocessing utility such as svgcleaner to inline the styles for you.


Picture key: NetworkPicture("https://github-readme-stats.vercel.app/api/top-langs/?username=omatt&layout=compact", headers: null, colorFilter: null)
====================================================================================================

======== Exception caught by SVG ===================================================================
The following FormatException was thrown resolving a single-frame picture stream:
Invalid double
99%

When the exception was thrown, this was the stack: 
#0      double.parse (dart:core-patch/double_patch.dart:111:28)
#1      parseDouble (package:flutter_svg/src/utilities/numbers.dart:15:17)
#2      _Paths.rect (package:flutter_svg/src/svg/parser_state.dart:655:22)
#3      SvgParserState.addShape (package:flutter_svg/src/svg/parser_state.dart:874:31)
#4      SvgParserState.startElement (package:flutter_svg/src/svg/parser_state.dart:902:12)
...
Picture provider: NetworkPicture("https://github-readme-stats.vercel.app/api/top-langs/?username=omatt&layout=compact", headers: null, colorFilter: null)
Picture key: NetworkPicture("https://github-readme-stats.vercel.app/api/top-langs/?username=omatt&layout=compact", headers: null, colorFilter: null)
====================================================================================================
```
</details>

```dart
SvgPicture.string(
  url,
  placeholderBuilder: (BuildContext context) => Container(
     padding: const EdgeInsets.all(30.0),
     child: const CircularProgressIndicator(),
  ),
),
```

### Error logs
<details>
  <summary>Logs</summary>

```
======== Exception caught by SVG ===================================================================
The following StateError was thrown resolving a single-frame picture stream:
Bad state: Invalid SVG data

When the exception was thrown, this was the stack: 
#0      SvgParserState.parse (package:flutter_svg/src/svg/parser_state.dart:823:7)
#1      SvgParser.parse (package:flutter_svg/parser.dart:25:24)
#2      Svg.fromSvgString (package:flutter_svg/svg.dart:119:25)
#3      Svg.svgPictureStringDecoder (package:flutter_svg/svg.dart:80:36)
#4      SvgPicture.svgStringDecoder.<anonymous closure> (package:flutter_svg/svg.dart:571:15)
...
====================================================================================================
```
</details>

```dart
DrawableRoot? drawableRoot;

Future<void> svgRoot(String url) async {
  var drawable = await svg.fromSvgString(url, 'key$url');
  setState(() {
    drawableRoot = drawable;
  });
}

@override
Widget build(BuildContext context) {
  svgRoot(url);
  ...
  CustomPaint(
    painter: SvgPainter(svgRoot: drawableRoot),
  ),
  ...
}

class SvgPainter extends CustomPainter {
  DrawableRoot? svgRoot;
  SvgPainter({required DrawableRoot? svgRoot}) : svgRoot = svgRoot;
  @override
  void paint(Canvas canvas, Size size) {

    if(svgRoot != null){
      /// Otherwise, if you want to draw it to a canvas:
      /// Optional, but probably normally desirable: scale the canvas dimensions to
      /// the SVG's viewbox
      // svgRoot!.scaleCanvasToViewBox(canvas, size);

      /// Optional, but probably normally desireable: ensure the SVG isn't rendered
      /// outside of the viewbox bounds
      svgRoot!.clipCanvasToViewBox(canvas);
      svgRoot!.draw(canvas,Rect.fromLTRB(size.height, size.width, size.height, size.width));
    }
  }

  @override
  bool shouldRepaint(CustomPainter oldDelegate) => false;
}
```

### Error logs
<details>
<summary>Logs</summary>

```
E/flutter (25904): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Bad state: Invalid SVG data
E/flutter (25904): #0      SvgParserState.parse (package:flutter_svg/src/svg/parser_state.dart:823:7)
E/flutter (25904): #1      SvgParser.parse (package:flutter_svg/parser.dart:25:24)
E/flutter (25904): #2      Svg.fromSvgString (package:flutter_svg/svg.dart:119:25)
E/flutter (25904): #3      _MyHomePageState.svgRoot (package:samplemarkdown/main.dart:32:30)
E/flutter (25904): #4      _MyHomePageState.build (package:samplemarkdown/main.dart:40:5)
E/flutter (25904): #5      StatefulElement.build (package:flutter/src/widgets/framework.dart:4691:27)
E/flutter (25904): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4574:15)
E/flutter (25904): #7      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4746:11)
E/flutter (25904): #8      Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
E/flutter (25904): #9      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4553:5)
E/flutter (25904): #10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4737:11)
E/flutter (25904): #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4548:5)
E/flutter (25904): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3611:14)
E/flutter (25904): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:3363:18)
E/flutter (25904): #14     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6083:14)
E/flutter (25904): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3611:14)
E/flutter (25904): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:3363:18)
E/flutter (25904): #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
E/flutter (25904): #18     Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
E/flutter (25904): #19     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4553:5)
E/flutter (25904): #20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4548:5)
E/flutter (25904): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3611:14)
E/flutter (25904): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:3363:18)
E/flutter (25904): #23     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6083:14)
E/flutter (25904): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3611:14)
E/flutter (25904): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:3363:18)
E/flutter (25904): #26     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6083:14)
E/flutter (25904): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3611:14)
E/flutter (25904): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:3363:18)
E/flutter (25904): #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
E/flutter (25904): #30     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4746:11)
E/flutter (25904): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
E/flutter (25904): #32     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4553:5)
E/flutter (25904): #33     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4737:11)
E/flutter (25904): #34     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4548:5)
E/flutter (25904): #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3611:14)
E/flutter (25904): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:3363:18)
E/flutter (25904): #37     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6083:14)
E/flutter (25904): #38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3611:14)
E/flutter (25904): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:3363:18)
E/flutter (25904): #40     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6083:14)
E/flutter (25904): #41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3611:14)
E/flutter (25904): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:3363:18)
E/flutter (25904): #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
E/flutter (25904): #44     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4746:11)
E/flutter (25904): #45     Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
E/flutter (25904): #46     ComponentElement._firstBuild (package:flutter/src/widgets/framework.d
E/flutter (25904): [ERROR:flutter/shell/common/shell.cc(103)] Dart Unhandled Exception: Bad state: Invalid SVG data, stack trace: #0      SvgParserState.parse (package:flutter_svg/src/svg/parser_state.dart:823:7)
E/flutter (25904): #1      SvgParser.parse (package:flutter_svg/parser.dart:25:24)
E/flutter (25904): #2      Svg.fromSvgString (package:flutter_svg/svg.dart:119:25)
E/flutter (25904): #3      _MyHomePageState.svgRoot (package:samplemarkdown/main.dart:32:30)
E/flutter (25904): #4      _MyHomePageState.build (package:samplemarkdown/main.dart:40:5)
E/flutter (25904): #5      StatefulElement.build (package:flutter/src/widgets/framework.dart:4691:27)
E/flutter (25904): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4574:15)
E/flutter (25904): #7      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4746:11)
E/flutter (25904): #8      Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
E/flutter (25904): #9      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2582:33)
E/flutter (25904): #10     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:875:21)
E/flutter (25904): #11     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:328:5)
E/flutter (25904): #12     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
E/flutter (25904): #13     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
E/flutter (25904): #14     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:865:7)
E/flutter (25904): #15     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter (25904): #16     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)
E/flutter (25904): #17     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426:5)
E/flutter (25904): #18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
E/flutter (25904): 
```
</details>

### Minimal Repro
<details>

<summary>Sample code</summary>

```dart
import 'dart:ui';

import 'package:flutter/material.dart';
import 'package:flutter_markdown/flutter_markdown.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:flutter_svg/svg.dart';

void main() {
  runApp(
    MaterialApp(
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    ),
  );
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key}) : super(key: key);
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final url =
      'https://github-readme-stats.vercel.app/api/top-langs/?username=omatt&layout=compact';

  DrawableRoot? drawableRoot;

  Future<void> svgRoot(String url) async {
    var drawable = await svg.fromSvgString(url, 'key$url');
    setState(() {
      drawableRoot = drawable;
    });
  }

  @override
  Widget build(BuildContext context) {
    svgRoot(url);
    return Scaffold(
      appBar: AppBar(
        title: Text('Markdown Sample'),
      ),
      body: Center(
        child: Column(
          children: [
            // MarkdownBody(data: '![]($url)]'),
            // SvgPicture.network(
            //   url,
            //   placeholderBuilder: (BuildContext context) => Container(
            //       padding: const EdgeInsets.all(30.0),
            //       child: const CircularProgressIndicator()),
            // ),
            // SvgPicture.string(
            //   url,
            //   placeholderBuilder: (BuildContext context) => Container(
            //     padding: const EdgeInsets.all(30.0),
            //     child: const CircularProgressIndicator(),
            //   ),
            // ),
            CustomPaint(
              painter: SvgPainter(svgRoot: drawableRoot),
            ),
          ],
        ),
      ),
    );
  }
}

class SvgPainter extends CustomPainter {
  DrawableRoot? svgRoot;
  SvgPainter({required DrawableRoot? svgRoot}) : svgRoot = svgRoot;
  @override
  void paint(Canvas canvas, Size size) {

    if(svgRoot != null){
      /// Otherwise, if you want to draw it to a canvas:
      /// Optional, but probably normally desirable: scale the canvas dimensions to
      /// the SVG's viewbox
      // svgRoot!.scaleCanvasToViewBox(canvas, size);

      /// Optional, but probably normally desireable: ensure the SVG isn't rendered
      /// outside of the viewbox bounds
      svgRoot!.clipCanvasToViewBox(canvas);
      svgRoot!.draw(canvas,Rect.fromLTRB(size.height, size.width, size.height, size.width));
    }
  }

  @override
  bool shouldRepaint(CustomPainter oldDelegate) => false;
}
```
</details>

**Comment by jason-simmons** [comment]
flutter_svg does not support `<style>` (see https://github.com/dnfield/flutter_svg/issues/105)

You may need to transform the SVG to remove the use of the style tag.

**Comment by omatt** [comment]
Thanks it seems like both `flutter_markdown` and `flutter_svg` is unable top support the SVG from the URL. As a workaround, it's easier to display the SVG from the URL with `HtmlElementView` since `WebView` doesn't have support for web.
