### ISSUE TITLE
[tool_crash] _CastError: (#0      describeLocale (package:flutter_tools/src/localizations/localizations_utils.dart:221:49))

### ISSUE THREAD

**Issue by MuhammadZain7** [flutter/flutter#87851]
## Command
```
flutter --no-color pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_CastError: (#0      describeLocale (package:flutter_tools/src/localizations/localizations_utils.dart:221:49))
```
#0      describeLocale (package:flutter_tools/src/localizations/localizations_utils.dart:221:49)
#1      LocalizationsGenerator._generateBaseClassFile (package:flutter_tools/src/localizations/gen_l10n.dart:1026:34)
#2      LocalizationsGenerator._generateCode (package:flutter_tools/src/localizations/gen_l10n.dart:1115:46)
#3      LocalizationsGenerator.writeOutputFiles (package:flutter_tools/src/localizations/gen_l10n.dart:1182:5)
#4      generateLocalizations (package:flutter_tools/src/localizations/gen_l10n.dart:72:9)
#5      GenerateLocalizationsTarget.build (package:flutter_tools/src/build_system/targets/localizations.dart:61:5)
#6      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:828:27)
<asynchronous suspension>
#7      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:595:16)
<asynchronous suspension>
#8      generateLocalizationsSyntheticPackage (package:flutter_tools/src/dart/generate_synthetic_packages.dart:60:30)
<asynchronous suspension>
#9      PackagesGetCommand._runPubGet (package:flutter_tools/src/commands/packages.dart:125:7)
<asynchronous suspension>
#10     PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:166:5)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
```
```
[✓] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1110], locale en-US)
    • Flutter version 2.2.3 at C:\flutter
    • Framework revision f4abaa0735 (5 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:/Users/zraja/AppData/Local/Android/Sdk
    • Platform android-30, build-tools 31.0.0
    • ANDROID_HOME = C:/Users/zraja/AppData/Local/Android/Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.58.2)
    • VS Code at C:\Users\zraja\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[✓] Connected device (3 available)
    • MED LX9 (mobile) • 9CEBB20C25202456 • android-arm    • Android 10 (API 29)
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 92.0.4515.131
    • Edge (web)       • edge             • web-javascript • Microsoft Edge 92.0.902.62

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f4abaa0735eba4dfd8f33f73363911d63931fe03
### Plugins
camera-0.8.1+7
device_info-2.0.2
firebase_auth-3.0.1
firebase_auth_web-3.0.0
firebase_core-1.4.0
firebase_core_web-1.1.0
flutter_image_compress-1.0.0
flutter_keyboard_visibility-5.0.3
flutter_keyboard_visibility_web-2.0.0
flutter_plugin_android_lifecycle-2.0.2
fluttertoast-8.0.7
google_sign_in-5.0.7
google_sign_in_web-0.10.0+1
image_picker-0.8.2
image_picker_for_web-2.1.2
libphonenumber-2.0.1
libphonenumber_plugin-0.2.3
libphonenumber_web-0.2.0+1
path_provider-2.0.2
path_provider_linux-2.0.2
path_provider_macos-2.0.2
path_provider_windows-2.0.3
photo_manager-1.2.9
shared_preferences-2.0.6
shared_preferences_linux-2.0.2
shared_preferences_macos-2.0.2
shared_preferences_web-2.0.1
shared_preferences_windows-2.0.2
sqflite-2.0.0+3
url_launcher-6.0.9
url_launcher_linux-2.0.1
url_launcher_macos-2.0.1
url_launcher_web-2.0.2
url_launcher_windows-2.0.1
video_player-2.1.12
video_player_web-2.0.2

**Comment by darshankawar** [comment]
I don't see an already open issue, so labeling as applicable for further insights from the team.

**Comment by darshankawar** [comment]
/cc @christopherfujino 

Saw a similar issue on latest stable.

**Comment by AlexV525** [comment]
When a wrong language code is provided in arb files (e.g. `jp` for Japanese instead of `ja`), the `flutter gen-l10n` will fail to run with the `describeLocale`. It's not a tool's fault, but we can provide a better exception report.
