### ISSUE TITLE
Debugger error when debugging Flutter Web app with a class with a static function

### ISSUE THREAD

**Issue by obeobe** [flutter/flutter#87856]
## Steps to Reproduce

When debugging a Flutter Web app, Android Studio's debugger shows an exception and prevents from examining variables when stepping into a function of a class that has a static function that returns an instance of the class, if the class' file name begins with a capital letter.

It's trivial to reproduce.

Create two classes, in two files:

*Dbg.dart*
```
class Dbg {
  static Dbg instance() { return Dbg(); }
  void test() {
    int a = 2; // <--- put breakpoint here
  }
}
```

*main.dart*
```
import 'Dbg.dart';

void main() {
  Dbg dbg = Dbg();
  dbg.test();
}
```

Put a breakpoint on the `int a = 2;` line, and run in debug mode (on a browser).

**Expected results:**
Once paused on the breakpoint, the debugger's Variables tool shows the in-scope variables.

**Actual results:**
Once paused on the breakpoint, the debugger's Variables tool shows an exception text.
Following is a screenshot, showing what it looks like, and the complete exception text:
![image](https://user-images.githubusercontent.com/1394039/128603005-97b1bbbc-3b2b-4a78-9983-40f82dbb2829.png)

Note: if I rename `Dbg.dart` to `dbg.dart` - the problem goes away.

Note 2: if I comment out the `static Dbg instance() { return Dbg(); }` line - the problem also goes away.

<details>
  <summary>Logs</summary>

`flutter analyze` just complains about the unused local variable `a`.

`flutter doctor -v`:
```
[✓] Flutter (Channel stable, 2.2.2, on Linux, locale en_US.UTF-8)
    • Flutter version 2.2.2 at /home/user/flutter
    • Framework revision d79295af24 (8 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/user/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /home/user/Downloads/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = chromium

[✓] Android Studio (version 4.2)
    • Android Studio at /home/user/Downloads/android-studio
    • Flutter plugin version 58.0.1
    • Dart plugin version 202.8488
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2)
    • IntelliJ at /snap/intellij-idea-ultimate/current
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Chromium 86.0.4240.75 snap

! Doctor found issues in 1 category.
```

</details>

**Comment by maheshmnj** [comment]
Hi @obeobe, Thanks for filing the issue I could see this working fine on the latest stable channel. 

![image](https://user-images.githubusercontent.com/31410839/128713821-4fa4c36c-595e-4a26-8c4d-3fdb2ca5f562.png)

<details>
<summary>code sample</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
    dbg.test();
  }
  Dbg dbg = Dbg();

  @override
  Widget build(BuildContext context) {
  
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}


class Dbg {
  static Dbg instance() { return Dbg(); }
  void test() {
    int a = 2; // <--- put breakpoint here
  }
}
```
</details>

Can you please try upgrading to latest stable channel by running 

```
flutter upgrade 
flutter clean
```
And see if this fixes the issue.

Thank you.

**Comment by obeobe** [comment]
Hi @maheshmnj .

The problem still reproduces for me, after upgrading.
I upgraded per your instructions (to: [✓] Flutter (Channel stable, 2.2.3, on Linux, locale en_US.UTF-8)).

Please note that I am using Chromium (on Ubuntu 20.04). Maybe it's related?

Thanks!

**Comment by maheshmnj** [comment]
Thanks for the clarification @obeobe, I am able to reproduce the issue on the latest stable and the master channel

<details>
<summary>code sample</summary>

`Dbg.dart`

```
class Dbg {
  static Dbg instance() { return Dbg(); }
  void test() {
    int a = 2; // <--- put breakpoint here
  }
}
```

`main.dart`

```
import 'package:counter/Dbg.dart';
import 'package:flutter/material.dart';

void main() {
Dbg dbg = Dbg();
dbg.test();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {

    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```
</details>

<details>
<summary>console log</summary>

```console
getObject: Unexpected error from chrome devtools:
text: Uncaught
exception:
  description: TypeError: Cannot read property 'name' of undefined
    at <anonymous>:9:25
    at <anonymous>:43:7
    at Dbg.Dbg.new.test (http://localhost:50974/packages/counter/Dbg.dart.lib.js:17:15)
    at main$ (http://localhost:50974/packages/counter/main.dart.lib.js:466:9)
    at main (http://localhost:50974/web_entrypoint.dart.lib.js:33:29)
    at main.next (<anonymous>)
    at http://localhost:50974/dart_sdk.js:37403:33
    at _RootZone.runUnary (http://localhost:50974/dart_sdk.js:37274:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:50974/dart_sdk.js:32530:29)
    at handleValueCallback (http://localhost:50974/dart_sdk.js:33057:49)
    at Function._propagateToListeners (http://localhost:50974/dart_sdk.js:33095:17)
    at _Future.new.[_completeWithValue] (http://localhost:50974/dart_sdk.js:32943:23)
    at http://localhost:50974/dart_sdk.js:32194:46
    at _RootZone.runUnary (http://localhost:50974/dart_sdk.js:37274:59)
    at _FutureListener.then.handleValue (http://localhost:50974/dart_sdk.js:32530:29)
    at handleValueCallback (http://localhost:50974/dart_sdk.js:33057:49)
    at Function._propagateToListeners (http://localhost:50974/dart_sdk.js:33095:17)
    at _Future.new.[_completeWithValue] (http://localhost:50974/dart_sdk.js:32943:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:50974/dart_sdk.js:32964:35)
    at Object._microtaskLoop (http://localhost:50974/dart_sdk.js:37526:13)
    at _startMicrotaskLoop (http://localhost:50974/dart_sdk.js:37532:13)
    at http://localhost:50974/dart_sdk.js:33303:9
  type: object
  value: null
attempted JS eval: `    (function() {
         var sdkUtils = require('dart_sdk').dart;
   var library = sdkUtils.getLibrary('package:counter/Dbg.dart');
   if (!library) throw 'cannot find library for package:counter/Dbg.dart';
  
      var result = {};
      var clazz = library["Dbg$"];
      var descriptor = {
          'name': clazz.name,
          'dartName': sdkUtils.typeName(clazz)
        };
      // TODO(jakemac): static methods once ddc supports them
      var methods = sdkUtils.getMethods(clazz);
      var methodNames = methods ? Object.keys(methods) : [];
      descriptor['methods'] = {};
      for (var name of methodNames) {
        var method = methods[name];
        descriptor['methods'][name] = {
          // TODO(jakemac): how can we get actual const info?
          "isConst": false,
          "isStatic": false,
        }
      }
      // TODO(jakemac): static fields once ddc supports them
      var fields = sdkUtils.getFields(clazz);
      var fieldNames = fields ? Object.keys(fields) : [];
      descriptor['fields'] = {};
      for (var name of fieldNames) {
        var field = fields[name];
        var libraryUri = Object.getOwnPropertySymbols(fields[name]["type"])
        .find(x => x.description == "libraryUri");
        descriptor['fields'][name] = {
          // TODO(jakemac): how can we get actual const info?
          "isConst": false,
          "isFinal": field.isFinal,
          "isStatic": false,
          "classRefName": fields[name]["type"]["name"],
          "classRefDartName": sdkUtils.typeName(fields[name]["type"]),
          "classRefLibraryId" : field["type"][libraryUri],
        }
      }
      return descriptor;
    })()
    `
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-arm, locale en-GB)
    • Flutter version 2.2.3 at /Users/mahesh/Documents/flutter
    • Framework revision f4abaa0735 (6 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.4 20F71 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 92.0.4515.131

• No issues found!```

```
[✓] Flutter (Channel master, 2.5.0-6.0.pre.21, on macOS 11.4 20F71 darwin-arm, locale en-GB)
    • Flutter version 2.5.0-6.0.pre.21 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 40e8620a27 (4 days ago), 2021-08-06 09:14:50 +0430
    • Engine revision 431ac604da
    • Dart version 2.14.0 (build 2.14.0-383.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.4 20F71 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 92.0.4515.131

• No issues found!
```
</details>

**Comment by maheshmnj** [comment]
Thanks for the clarification @obeobe, I am able to reproduce the issue on the latest stable and the master channel

<details>
<summary>code sample</summary>

`Dbg.dart`

```
class Dbg {
  static Dbg instance() { return Dbg(); }
  void test() {
    int a = 2; // <--- put breakpoint here
  }
}
```

`main.dart`

```
import 'package:counter/Dbg.dart';
import 'package:flutter/material.dart';

void main() {
Dbg dbg = Dbg();
dbg.test();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {

    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```
</details>

<details>
<summary>console log</summary>

```console
getObject: Unexpected error from chrome devtools:
text: Uncaught
exception:
  description: TypeError: Cannot read property 'name' of undefined
    at <anonymous>:9:25
    at <anonymous>:43:7
    at Dbg.Dbg.new.test (http://localhost:50974/packages/counter/Dbg.dart.lib.js:17:15)
    at main$ (http://localhost:50974/packages/counter/main.dart.lib.js:466:9)
    at main (http://localhost:50974/web_entrypoint.dart.lib.js:33:29)
    at main.next (<anonymous>)
    at http://localhost:50974/dart_sdk.js:37403:33
    at _RootZone.runUnary (http://localhost:50974/dart_sdk.js:37274:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:50974/dart_sdk.js:32530:29)
    at handleValueCallback (http://localhost:50974/dart_sdk.js:33057:49)
    at Function._propagateToListeners (http://localhost:50974/dart_sdk.js:33095:17)
    at _Future.new.[_completeWithValue] (http://localhost:50974/dart_sdk.js:32943:23)
    at http://localhost:50974/dart_sdk.js:32194:46
    at _RootZone.runUnary (http://localhost:50974/dart_sdk.js:37274:59)
    at _FutureListener.then.handleValue (http://localhost:50974/dart_sdk.js:32530:29)
    at handleValueCallback (http://localhost:50974/dart_sdk.js:33057:49)
    at Function._propagateToListeners (http://localhost:50974/dart_sdk.js:33095:17)
    at _Future.new.[_completeWithValue] (http://localhost:50974/dart_sdk.js:32943:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:50974/dart_sdk.js:32964:35)
    at Object._microtaskLoop (http://localhost:50974/dart_sdk.js:37526:13)
    at _startMicrotaskLoop (http://localhost:50974/dart_sdk.js:37532:13)
    at http://localhost:50974/dart_sdk.js:33303:9
  type: object
  value: null
attempted JS eval: `    (function() {
         var sdkUtils = require('dart_sdk').dart;
   var library = sdkUtils.getLibrary('package:counter/Dbg.dart');
   if (!library) throw 'cannot find library for package:counter/Dbg.dart';
  
      var result = {};
      var clazz = library["Dbg$"];
      var descriptor = {
          'name': clazz.name,
          'dartName': sdkUtils.typeName(clazz)
        };
      // TODO(jakemac): static methods once ddc supports them
      var methods = sdkUtils.getMethods(clazz);
      var methodNames = methods ? Object.keys(methods) : [];
      descriptor['methods'] = {};
      for (var name of methodNames) {
        var method = methods[name];
        descriptor['methods'][name] = {
          // TODO(jakemac): how can we get actual const info?
          "isConst": false,
          "isStatic": false,
        }
      }
      // TODO(jakemac): static fields once ddc supports them
      var fields = sdkUtils.getFields(clazz);
      var fieldNames = fields ? Object.keys(fields) : [];
      descriptor['fields'] = {};
      for (var name of fieldNames) {
        var field = fields[name];
        var libraryUri = Object.getOwnPropertySymbols(fields[name]["type"])
        .find(x => x.description == "libraryUri");
        descriptor['fields'][name] = {
          // TODO(jakemac): how can we get actual const info?
          "isConst": false,
          "isFinal": field.isFinal,
          "isStatic": false,
          "classRefName": fields[name]["type"]["name"],
          "classRefDartName": sdkUtils.typeName(fields[name]["type"]),
          "classRefLibraryId" : field["type"][libraryUri],
        }
      }
      return descriptor;
    })()
    `
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-arm, locale en-GB)
    • Flutter version 2.2.3 at /Users/mahesh/Documents/flutter
    • Framework revision f4abaa0735 (6 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.4 20F71 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 92.0.4515.131

• No issues found!```

```
[✓] Flutter (Channel master, 2.5.0-6.0.pre.21, on macOS 11.4 20F71 darwin-arm, locale en-GB)
    • Flutter version 2.5.0-6.0.pre.21 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 40e8620a27 (4 days ago), 2021-08-06 09:14:50 +0430
    • Engine revision 431ac604da
    • Dart version 2.14.0 (build 2.14.0-383.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.4 20F71 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 92.0.4515.131

• No issues found!
```
</details>

**Comment by zanderso** [comment]
I like to ask you to double check that the file name starting with a capital letter is really required. Does this really not repro when the filename starts with a lowercase latter?

**Comment by obeobe** [comment]
@zanderso yes, it's required. For me it doesn't reproduce if I rename the file to `dbg.dart`.

**Comment by maheshmnj** [comment]
Can confirm the issue is not reproduced with file named as `dbg.dart` (with lowercase letters).

**Comment by nshahan** [comment]
@annagrin I think it's likely the case. I'm guessing DDC will use `Dbg` as the name of the library so the class definition itself will use the name `Dbg$`. That class definition will be accessible as `Dwg.Dwg` though and that is now it will be used throughout the application.

This sounds like another issue that will be solved with our work on debugger symbols. The current implementation is probably assuming the name used in the class definition will be the same in Dart and JavaScript. That is more likely to be true when the names follow the guidance in Effective Dart https://dart.dev/guides/language/effective-dart/style#do-name-libraries-and-source-files-using-lowercase_with_underscores. That way the names of the library and class would not clash.
