### ISSUE TITLE
Make `dart:ui/Path` class not extendable on all platforms

### ISSUE THREAD

**Issue by chgibb** [flutter/flutter#87861]
## Steps to Reproduce

- Run `flutter create bug`.
- Add a class to `lib/main.dart` that extends `Path` from `dart:ui`. Something like the following:
```dart
class MyPath extends Path {

}
```

**Expected results:** 
Running `flutter run` or `flutter build` for Android, iOS or desktop completes with no errors.

**Actual results:** 
Running `flutter run -d chrome` or `flutter build web` results in the following:

<details>
  <summary>Logs</summary>

```
Target dart2js failed: Exception: lib/main.dart:3:7:                    
Error: The non-abstract class 'MyPath' is missing implementations for these members:
 - Path.addArc
 - Path.addOval
 - Path.addPath
 - Path.addPolygon
 - Path.addRRect
 - Path.addRect
 - Path.arcTo
 - Path.arcToPoint
 - Path.close
 - Path.computeMetrics
 - Path.conicTo
 - Path.contains
 - Path.cubicTo
 - Path.extendWithPath
 - Path.fillType
 - Path.fillType=
 - Path.getBounds
 - Path.lineTo
 - Path.moveTo
 - Path.quadraticBezierTo
 - Path.relativeArcToPoint
 - Path.relativeConicTo
 - Path.relativeCubicTo
 - Path.relativeLineTo
 - Path.relativeMoveTo
 - Path.relativeQuadraticBezierTo
 - Path.reset
 - Path.shift
 - Path.transform
class MyPath extends Path {
      ^^^^^^
../../../Downloads/flutter/bin/cache/flutter_web_sdk/lib/ui/src/ui/path.dart:52:8:
Info: 'Path.addArc' is defined here.
  void addArc(Rect oval, double startAngle, double sweepAngle);
       ^^^^^^
../../../Downloads/flutter/bin/cache/flutter_web_sdk/lib/ui/src/ui/path.dart:51:8:
Info: 'Path.addOval' is defined here.
  void addOval(Rect oval);
       ^^^^^^^
../../../Downloads/flutter/bin/cache/flutter_web_sdk/lib/ui/src/ui/path.dart:55:8:
Info: 'Path.addPath' is defined here.
  void addPath(Path path, Offset offset, {Float64List? matrix4});
       ^^^^^^^
../../../Downloads/flutter/bin/cache/flutter_web_sdk/lib/ui/src/ui/path.dart:53:8:
Info: 'Path.addPolygon' is defined here.
  void addPolygon(List<Offset> points, bool close);
       ^^^^^^^^^^
../../../Downloads/flutter/bin/cache/flutter_web_sdk/lib/ui/src/ui/path.dart:54:8:
Info: 'Path.addRRect' is defined here.
  void addRRect(RRect rrect);
       ^^^^^^^^
../../../Downloads/flutter/bin/cache/flutter_web_sdk/lib/ui/src/ui/path.dart:50:8:
Info: 'Path.addRect' is defined here.
  void addRect(Rect rect);
       ^^^^^^^
../../../Downloads/flutter/bin/cache/flutter_web_sdk/lib/ui/src/ui/path.dart:35:8:
Info: 'Path.arcTo' is defined here.
  void arcTo(Rect rect, double startAngle, double sweepAngle, bool forceMoveTo);
       ^^^^^
../../../Downloads/flutter/bin/cache/flutter_web_sdk/lib/ui/src/ui/path.dart:36:8:
Info: 'Path.arcToPoint' is defined here.
  void arcToPoint(
       ^^^^^^^^^^
../../../Downloads/flutter/bin/cache/flutter_web_sdk/lib/ui/src/ui/path.dart:57:8:
Info: 'Path.close' is defined here.
  void close();
       ^^^^^
../../../Downloads/flutter/bin/cache/flutter_web_sdk/lib/ui/src/ui/path.dart:73:15:
Info: 'Path.computeMetrics' is defined here.
  PathMetrics computeMetrics({bool forceClosed = false});
              ^^^^^^^^^^^^^^
../../../Downloads/flutter/bin/cache/flutter_web_sdk/lib/ui/src/ui/path.dart:33:8:
Info: 'Path.conicTo' is defined here.
  void conicTo(double x1, double y1, double x2, double y2, double w);
       ^^^^^^^
../../../Downloads/flutter/bin/cache/flutter_web_sdk/lib/ui/src/ui/path.dart:59:8:
Info: 'Path.contains' is defined here.
  bool contains(Offset point);
       ^^^^^^^^
../../../Downloads/flutter/bin/cache/flutter_web_sdk/lib/ui/src/ui/path.dart:31:8:
Info: 'Path.cubicTo' is defined here.
  void cubicTo(double x1, double y1, double x2, double y2, double x3, double y3);
       ^^^^^^^
../../../Downloads/flutter/bin/cache/flutter_web_sdk/lib/ui/src/ui/path.dart:56:8:
Info: 'Path.extendWithPath' is defined here.
  void extendWithPath(Path path, Offset offset, {Float64List? matrix4});
       ^^^^^^^^^^^^^^
../../../Downloads/flutter/bin/cache/flutter_web_sdk/lib/ui/src/ui/path.dart:23:20:
Info: 'Path.fillType' is defined here.
  PathFillType get fillType;
                   ^^^^^^^^
../../../Downloads/flutter/bin/cache/flutter_web_sdk/lib/ui/src/ui/path.dart:24:7:
Info: 'Path.fillType=' is defined here.
  set fillType(PathFillType value);
      ^^^^^^^^
../../../Downloads/flutter/bin/cache/flutter_web_sdk/lib/ui/src/ui/path.dart:63:8:
Info: 'Path.getBounds' is defined here.
  Rect getBounds();
       ^^^^^^^^^
../../../Downloads/flutter/bin/cache/flutter_web_sdk/lib/ui/src/ui/path.dart:27:8:
Info: 'Path.lineTo' is defined here.
  void lineTo(double x, double y);
       ^^^^^^
../../../Downloads/flutter/bin/cache/flutter_web_sdk/lib/ui/src/ui/path.dart:25:8:
Info: 'Path.moveTo' is defined here.
  void moveTo(double x, double y);
       ^^^^^^
../../../Downloads/flutter/bin/cache/flutter_web_sdk/lib/ui/src/ui/path.dart:29:8:
Info: 'Path.quadraticBezierTo' is defined here.
  void quadraticBezierTo(double x1, double y1, double x2, double y2);
       ^^^^^^^^^^^^^^^^^
../../../Downloads/flutter/bin/cache/flutter_web_sdk/lib/ui/src/ui/path.dart:43:8:
Info: 'Path.relativeArcToPoint' is defined here.
  void relativeArcToPoint(
       ^^^^^^^^^^^^^^^^^^
../../../Downloads/flutter/bin/cache/flutter_web_sdk/lib/ui/src/ui/path.dart:34:8:
Info: 'Path.relativeConicTo' is defined here.
  void relativeConicTo(double x1, double y1, double x2, double y2, double w);
       ^^^^^^^^^^^^^^^
../../../Downloads/flutter/bin/cache/flutter_web_sdk/lib/ui/src/ui/path.dart:32:8:
Info: 'Path.relativeCubicTo' is defined here.
  void relativeCubicTo(double x1, double y1, double x2, double y2, double x3, double y3);
       ^^^^^^^^^^^^^^^
../../../Downloads/flutter/bin/cache/flutter_web_sdk/lib/ui/src/ui/path.dart:28:8:
Info: 'Path.relativeLineTo' is defined here.
  void relativeLineTo(double dx, double dy);
       ^^^^^^^^^^^^^^
../../../Downloads/flutter/bin/cache/flutter_web_sdk/lib/ui/src/ui/path.dart:26:8:
Info: 'Path.relativeMoveTo' is defined here.
  void relativeMoveTo(double dx, double dy);
       ^^^^^^^^^^^^^^
../../../Downloads/flutter/bin/cache/flutter_web_sdk/lib/ui/src/ui/path.dart:30:8:
Info: 'Path.relativeQuadraticBezierTo' is defined here.
  void relativeQuadraticBezierTo(double x1, double y1, double x2, double y2);
       ^^^^^^^^^^^^^^^^^^^^^^^^^
../../../Downloads/flutter/bin/cache/flutter_web_sdk/lib/ui/src/ui/path.dart:58:8:
Info: 'Path.reset' is defined here.
  void reset();
       ^^^^^
../../../Downloads/flutter/bin/cache/flutter_web_sdk/lib/ui/src/ui/path.dart:60:8:
Info: 'Path.shift' is defined here.
  Path shift(Offset offset);
       ^^^^^
../../../Downloads/flutter/bin/cache/flutter_web_sdk/lib/ui/src/ui/path.dart:61:8:
Info: 'Path.transform' is defined here.
  Path transform(Float64List matrix4);
       ^^^^^^^^^
lib/main.dart:3:7:
Error: The superclass, 'Path', has no unnamed constructor that takes no arguments.
class MyPath extends Path {
      ^
Error: Compilation failed.


Compiling lib/main.dart for the Web...                              7.0s
Exception: Failed to compile application for the Web.
```

```
```

```
$ flutter doctor -v
[✓] Flutter (Channel stable, 2.0.6, on Mac OS X 10.15.5 19F101 darwin-x64, locale en-CA)
    • Flutter version 2.0.6 at /Users/chgibb/Downloads/flutter
    • Framework revision 1d9032c7e1 (3 months ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc2)
    • Android SDK at /Users/chgibb/Library/Android/sdk
    • Platform android-30, build-tools 31.0.0-rc2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ! CocoaPods 1.9.0 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.5 19F101 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 92.0.4515.131

! Doctor found issues in 1 category.
```

</details>

It appears that the `Path` class for Flutter web is abstract and has no generative constructor:
https://github.com/flutter/engine/blob/master/lib/web_ui/lib/src/ui/path.dart#L10

This is in stark contrast to the `Path` class exposed to Flutter applications building for every other target:
https://github.com/flutter/engine/blob/master/lib/ui/painting.dart#L2280

Applications which `extend` `Path` are therefore unable to compile under Flutter web.

**Comment by TahaTesser** [comment]
Hi @chgibb 
Thanks for filing the issue, I can't find any example where `ui.Path` is extended rather than implemented 

For example, here it is extended, I also searched other classes
https://github.com/flutter/engine/blob/master/lib/web_ui/lib/src/engine/html/path/path.dart

Most often use case of this class is to get a type of path such ` ui.Path()..addRRect(rrect);` and path.dart has private constructor

The thrown says indicate the issue with a super constructor, on non-web, there is no such issue 

This is easily reproducible with just this
```dart
import 'dart:ui' as ui;

main() {}

abstract class MyPath extends ui.Path {}
```

<details> 
<summary>logs</summary> 
	
```consol
file:///Users/tahatesser/Code/flutter_master/bin/cache/flutter_web_sdk/kernel/flutter_ddc_
sdk_sound.dill --sound-null-safety
[  +18 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[ +309 ms] lib/main.dart:5:16: Error: The superclass, 'Path', has no unnamed constructor
that takes
                    no arguments.
[   +2 ms] abstract class MyPath extends ui.Path {}
[        ]                ^
[ +227 ms] Unhandled exception:
[        ] NoSuchMethodError: The getter 'name' was called on null.
[        ] Receiver: null
[        ] Tried calling: name
[        ] #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:63:5)
[        ] #1      ProgramCompiler._emitSuperConstructorCallIfNeeded
           (package:dev_compiler/src/kernel/compiler.dart:1638:14)
[        ] #2      ProgramCompiler._emitConstructorBody
           (package:dev_compiler/src/kernel/compiler.dart:1592:19)
[        ] #3      ProgramCompiler._emitConstructor.<anonymous closure>.<anonymous
closure>
           (package:dev_compiler/src/kernel/compiler.dart:1548:19)
[        ] #4      ProgramCompiler._superDisallowed
           (package:dev_compiler/src/kernel/compiler.dart:3545:24)
[        ] #5      ProgramCompiler._emitConstructor.<anonymous closure>
           (package:dev_compiler/src/kernel/compiler.dart:1547:15)
[        ] #6      ProgramCompiler._withLetScope
           (package:dev_compiler/src/kernel/compiler.dart:2307:25)
[        ] #7      ProgramCompiler._withCurrentFunction
           (package:dev_compiler/src/kernel/compiler.dart:3535:18)
[        ] #8      ProgramCompiler._emitConstructor
           (package:dev_compiler/src/kernel/compiler.dart:1545:16)
[        ] #9      ProgramCompiler._defineConstructors
           (package:dev_compiler/src/kernel/compiler.dart:1187:38)
[        ] #10     ProgramCompiler._emitClassDeclaration
           (package:dev_compiler/src/kernel/compiler.dart:698:19)
[        ] #11     ProgramCompiler._emitClass
(package:dev_compiler/src/kernel/compiler.dart:621:21)
[        ] #12     List.forEach (dart:core-patch/growable_array.dart:403:8)
[        ] #13     ProgramCompiler._emitLibrary
           (package:dev_compiler/src/kernel/compiler.dart:570:23)
[        ] #14     List.forEach (dart:core-patch/growable_array.dart:403:8)
[        ] #15     ProgramCompiler.emitModule
(package:dev_compiler/src/kernel/compiler.dart:430:15)
[        ] #16     JavaScriptBundler.compile
           (package:frontend_server/src/javascript_bundle.dart:152:33)
[        ] #17     FrontendCompiler.writeJavascriptBundle
           (package:frontend_server/frontend_server.dart:649:47)
[        ] <asynchronous suspension>
[        ] #18     FrontendCompiler.compile
(package:frontend_server/frontend_server.dart:557:9)
[        ] <asynchronous suspension>
[        ] #19     listenAndCompile.<anonymous closure>
           (package:frontend_server/frontend_server.dart:1132:11)
[        ] <asynchronous suspension>
[  +57 ms] "flutter run" took 1,895ms.
[   +5 ms] the Dart compiler exited unexpectedly.
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      DefaultResidentCompiler._compile.<anonymous closure>
           (package:flutter_tools/src/compile.dart:767:13)
           #2      _rootRun (dart:async/zone.dart:1420:47)
           #3      _CustomZone.run (dart:async/zone.dart:1328:19)
           #4      _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
           #5      _BufferingStreamSubscription._sendDone.sendDone
           (dart:async/stream_impl.dart:394:13)
           #6      _BufferingStreamSubscription._sendDone
(dart:async/stream_impl.dart:404:7)
           #7      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #8      _SinkTransformerStreamSubscription._close
           (dart:async/stream_transformers.dart:87:11)
           #9      _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
           #10     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
           #11     _LineSplitterSink.close (dart:convert/line_splitter.dart:135:11)
           #12     _SinkTransformerStreamSubscription._handleDone
           (dart:async/stream_transformers.dart:132:24)
           #13     _rootRun (dart:async/zone.dart:1420:47)
           #14     _CustomZone.run (dart:async/zone.dart:1328:19)
           #15     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
           #16     _BufferingStreamSubscription._sendDone.sendDone
           (dart:async/stream_impl.dart:394:13)
           #17     _BufferingStreamSubscription._sendDone
(dart:async/stream_impl.dart:404:7)
           #18     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #19     _SinkTransformerStreamSubscription._close
           (dart:async/stream_transformers.dart:87:11)
           #20     _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
           #21     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
           #22     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:305:20)
           #23     _ConverterStreamEventSink.close
(dart:convert/chunked_conversion.dart:81:18)
           #24     _SinkTransformerStreamSubscription._handleDone
           (dart:async/stream_transformers.dart:132:24)
           #25     _rootRun (dart:async/zone.dart:1420:47)
           #26     _CustomZone.run (dart:async/zone.dart:1328:19)
           #27     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
           #28     _BufferingStreamSubscription._sendDone.sendDone
           (dart:async/stream_impl.dart:394:13)
           #29     _BufferingStreamSubscription._sendDone
(dart:async/stream_impl.dart:404:7)
           #30     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #31     _SyncStreamControllerDispatch._sendDone
(dart:async/stream_controller.dart:741:19)
           #32     _StreamController._closeUnchecked
(dart:async/stream_controller.dart:596:7)
           #33     _StreamController.close (dart:async/stream_controller.dart:589:5)
           #34     _Socket._onData (dart:io-patch/socket_patch.dart:2173:21)
           #35     _rootRunUnary (dart:async/zone.dart:1444:13)
           #36     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
           #37     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
           #38     _BufferingStreamSubscription._sendData
(dart:async/stream_impl.dart:341:11)
           #39     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
           #40     _SyncStreamControllerDispatch._sendData
(dart:async/stream_controller.dart:733:19)
           #41     _StreamController._add (dart:async/stream_controller.dart:607:7)
           #42     _StreamController.add (dart:async/stream_controller.dart:554:5)
           #43     new _RawSocket.<anonymous closure>
(dart:io-patch/socket_patch.dart:1709:35)
           #44     _NativeSocket.issueReadEvent.issue
(dart:io-patch/socket_patch.dart:1206:18)
           #45     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
           #46     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
           #47     _runPendingImmediateCallback
(dart:isolate-patch/isolate_patch.dart:120:13)
           #48     _RawReceivePortImpl._handleMessage
(dart:isolate-patch/isolate_patch.dart:185:5)
           
           
[   +7 ms] Waiting for connection from debug service on Chrome... (completed in 746ms)
[        ] Synced 0.0MB.
[        ] Failed to compile application.
[  +30 ms] ensureAnalyticsSent: 33ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
tahatesser@Tahas-MacBook-Pro triage % 
```
	
</details>


|  `stable`  | `master` |
| :---: |:---: |
|  ❌  |   ❌  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 12.0 21A5294g darwin-x64, locale en-GB)
    • Flutter version 2.2.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision f4abaa0735 (6 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/AndroidStudio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 13.0, Build version 13A5201i
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (4 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E            • ios            • iOS 15.0
    • iPhone 12 (mobile)   • 3C173470-A5A2-45F2-BF7B-79B8218E717C • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)      • macos                                • darwin-x64     • macOS 12.0 21A5294g darwin-x64
    • Chrome (web)         • chrome                               • web-javascript • Google Chrome 92.0.4515.131

! Doctor found issues in 1 category.

```

```console
```
		
</details>

✅: No Issue ❌: Issue reproduced

**Comment by TahaTesser** [comment]
cc: @yjbanov

**Comment by sigmundch** [comment]
I don't believe this to be a dependency:dart issue - the `Path` declaration in web_ui only has factory constructors which make this class sealed for extension. The fix would likely require changing [the implementation][1] of this class

[1]: https://github.com/flutter/engine/blob/master/lib/web_ui/lib/src/ui/path.dart#L9

**Comment by yjbanov** [comment]
This class is not meant extension as the engine relies on specific internal representation of the object. Have you considered wrapping it instead of extending?

**Comment by chgibb** [comment]
If that is the case, should it not be marked `@sealed`?

**Comment by yjbanov** [comment]
It should, but unfortunately `dart:*` libraries cannot use pub packages, so we cannot import `package:meta` from `dart:ui` to mark it sealed. I'll file a Dart SDK issue to include these annotations in the standard libraries. Then we'll be able to annotation engine classes too.

**Comment by sigmundch** [comment]
DBC - A suboptimal, but feasible middle ground solution here, could be to use the pattern you have in web_ui also in the public library. Then the `Path` class cannot be extended by default in all environments.

**Comment by yjbanov** [comment]
We can prevent extensions by making the constructor private and only expose a factory, but it will not prevent implementations. Maybe that's better than nothing.

**Comment by yjbanov** [comment]
Part of fixing this issue is to figure out how much this class has already been extended in the wild, because it would be a breaking change for non-web platforms.

**Comment by chinmaygarde** [comment]
The non-web implementation of path is working as intended. The workaround on both implementations is to use wrapping instead of extension.
