### ISSUE TITLE
[image_picker] Permission error for camera picker on OnePlus 3 with Android 9

### ISSUE THREAD

**Issue by mangei** [flutter/flutter#87896]
## Steps to Reproduce

1. use basic example: https://github.com/flutter/plugins/tree/master/packages/image_picker/image_picker/example (image_picker: 0.8.3+1, commit: acc3202466a8b4c0b1bcb91fc1ce520c7b021e44)
2. Run on OnePlus 3 (ONEPLUS A3003), Android 9
3. Try to pick an image with the camera within the app
4. It will open camera to pick the image
5. Take an image
6. Confirm the image
7. _Nothing more happens for the user_
8. when using the camera picker again you the the following exception: `PlatformException(already_active, Image picker is already active, null, null)`

**Expected results:**

Camera picker works on OnePlus 3 and I can reuse the picker again.

**Actual results:**

Permission error on OnePlus 3 (ONEPLUS A3003) with Android 9. The picker can not be used anymore after that, since it states in the logs, that is already in use. The app has to be restarted to use the picker again.

<details>
  <summary>Logs</summary>

```
[   +1 ms] W/Binder  ( 2662): java.lang.SecurityException: Permission Denial: writing com.android.providers.media.MediaProvider uri content://media/external/file from pid=2662, uid=10227 requires android.permission.WRITE_EXTERNAL_STORAGE, or grantUriPermission()
[   +1 ms] W/Binder  ( 2662):   at android.os.Parcel.createException(Parcel.java:1950)
[        ] W/Binder  ( 2662):   at android.os.Parcel.readException(Parcel.java:1918)
[        ] W/Binder  ( 2662):   at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
[        ] W/Binder  ( 2662):   at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
[        ] W/Binder  ( 2662):   at android.content.ContentProviderProxy.delete(ContentProviderNative.java:561)
[        ] W/Binder  ( 2662):   at android.content.ContentResolver.delete(ContentResolver.java:1813)
[        ] W/Binder  ( 2662):   at android.media.MediaScannerConnection$1.scanCompleted(MediaScannerConnection.java:83)
[        ] W/Binder  ( 2662):   at android.media.IMediaScannerListener$Stub.onTransact(IMediaScannerListener.java:61)
[        ] W/Binder  ( 2662):   at android.os.Binder.execTransact(Binder.java:752)
```

```
Analyzing example...
No issues found! (ran in 3.2s; 4 public members lack documentation)
```

```
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19043.1110], locale de-AT)
    • Flutter version 2.2.3 at C:\sdk\flutter
    • Framework revision f4abaa0735 (5 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\USER\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = C:\Users\USER\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2020.1.2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code, 64-bit edition (version 1.58.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.24.0

[√] Connected device (3 available)
    • ONEPLUS A3003 (mobile) • 5b6fb83b • android-arm64  • Android 9 (API 28)
    • Chrome (web)           • chrome   • web-javascript • Google Chrome 92.0.4515.131
    • Edge (web)             • edge     • web-javascript • Microsoft Edge 91.0.864.64

• No issues found!
```

</details>

**Comment by TahaTesser** [comment]
Hi @mangei 
I just tried on Oneplus 8 (Android 11) on the latest package, has no issue. Given you specified this device, is the issue only this particular device? Can you please reproduce the Android 9 emulator or another physical Android 9 device?

**Comment by mangei** [comment]
I checked some more phones.

Worked:
- Android 9 emulator
- Fairphone 3, Android 10
- OnePlus Nord, Android 11
- Samsung Galaxy S9 (SM-G960F), Android 10, One UI 2.1

Did not work:
- OnePlus 3, Android 8
- OnePlus 3, Android 9
... I couldn't find another non-working phone yet.

**Comment by TerehinAV** [comment]
Same problem on Meizu 16th android 8.1

**Comment by mangei** [comment]
@piuskamil which specific device do you have?

**Comment by ovib** [comment]
**Same issue on One Plus 3T (A3010) with Android 9**. Working on Xiaomi Redmi 4 with Android 6 and Xiaomi Mi A1 with Android 9.

**Comment by madura7** [comment]
I'm facing the same issue on my physical device. It crashes when picking from the gallery (tested device - Huawei Y6 ).
is there any solution for this issue?

**Comment by zengraf** [comment]
I have the same problem on **OnePlus 5 (A5000)** with **Android 9 (API 28)**, **OxygenOS 9.0.8**.

<details>
<summary>Logs</summary>

```
W/Binder  (32155): Caught a RuntimeException from the binder stub implementation.
W/Binder  (32155): java.lang.SecurityException: Permission Denial: writing com.android.providers.media.MediaProvider uri content://media/external/file from pid=32155, uid=10270 requires android.permission.WRITE_EXTERNAL_STORAGE, or grantUriPermission()
W/Binder  (32155):      at android.os.Parcel.createException(Parcel.java:1950)
W/Binder  (32155):      at android.os.Parcel.readException(Parcel.java:1918)
W/Binder  (32155):      at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
W/Binder  (32155):      at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
W/Binder  (32155):      at android.content.ContentProviderProxy.delete(ContentProviderNative.java:561)
W/Binder  (32155):      at android.content.ContentResolver.delete(ContentResolver.java:1813)
W/Binder  (32155):      at android.media.MediaScannerConnection$1.scanCompleted(MediaScannerConnection.java:83)
W/Binder  (32155):      at android.media.IMediaScannerListener$Stub.onTransact(IMediaScannerListener.java:61)
W/Binder  (32155):      at android.os.Binder.execTransact(Binder.java:752)
```

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.8.1, on Ubuntu 20.04 LTS 5.10.16.3-microsoft-standard-WSL2, locale C.UTF-8)
    • Flutter version 2.8.1 at /home/zengraf/.asdf/installs/flutter/2.8.1-stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (4 days ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/zengraf/android-sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = /home/zengraf/android-sdk
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+8-Ubuntu-0ubuntu1.20.04)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • ONEPLUS A5000 (mobile) • 192.168.1.209:5555 • android-arm64 • Android 9 (API 28)
```

</details>

**Comment by nandhakumargdr** [comment]
I have the same problem with `image_picker 0.8.4+4`. 

Alternatively, I'm using  `images_picker: ^1.2.10`. This is working.

But still, I would like to know the solution using `image_picker 0.8.4+4`.

**Comment by AliSattar95** [comment]
same issue

**Comment by HeyRonak** [comment]
did anyone solve this issue?

same issue on ONEPLUS A3003

**Comment by deeeznuds** [comment]
Same issue.
I tried to use the 'permission_handler' package to check permission on runtime, then the error was gone but the captured image is not returned from the 'image_picker' method of the image_picker package.
The issue is caused on OnePlus 5T, Android 8.1, the latest OS update.
Also, I tried to turn off additional settings of the camera like portrait mode, save location and etc, but this did not solve the issue.
Can't catch any log from this issue, but when I call 'pickImage' method again (after the first attempt), I get (already_active, Image picker is already active, null, null) error.
Please give any feedback on this issue.

**Comment by NikeshNayak** [comment]
I am facing issue of image picker issue on One Plus devices. did any one found the solution ?

**Comment by netease-george** [comment]
same issue on meizu 16s, Android 9

**Comment by s20797** [comment]
I have facing same issue on one plus android 9 
can any one find these solution

**Comment by JosephNK** [comment]
same issue

**Comment by markosole** [comment]
Same issue here as well OP 3T and only if I am using camera, snap the picture. How can I at least capture null and throw modal or other info?

**Comment by Qingx** [comment]
Same issue on MeiZu 16s, Android 9

**Comment by markosole** [comment]
@deeeznuds This isn't limitation of Android 9.  I have devices with Android 7, for instance Huaweit T3 tablet which works just fine. 

What I have tested so far, once storage access is allowed:
```xml
      <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
      <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
```

I can pick image from gallery just fine. So it's somewhere between that camera does not pass data back as callback. 
I wonder would be possible (it is but where, how..) to capture exception and use image selection as fallback? - At least return error, instead of just getting stuck somewhere in between.

**Comment by Andrekarma** [comment]
Any update on this issue?

**Comment by markosole** [comment]
No success so far, this is issue with core API and not plugins (from pub.dev) that are using it. A bit difficult to debug, as well. It's somethig for core team who knows Android inside-out as well.

**Comment by Lykeosovandara** [comment]
I make some change hope this help 
https://github.com/flutter/packages/pull/7516

**Comment by p-shapovalov** [comment]
> Starting in 3.29, Flutter on Android and iOS execute Dart code on the application’s main thread, and there is no longer a separate UI thread

I guess should be fixed now?

**Comment by NguyenDang4902** [comment]
Any update everyone? I tested on realme C30s, Oppo A17k and Samsung J7+ and only Samsung J7+ worked fine...

**Comment by moin-maniar** [comment]
@darshankawar, I am facing the same issue. did we get any solution on this. Please help...
