### ISSUE TITLE
libEGL  : call to OpenGL ES API with no current context (logged once per thread)

### ISSUE THREAD

**Issue by jiangxklongmao** [flutter/flutter#87937]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 
This is an occasional crash. I can't provide a reproduction path.
**Expected results:** 
I hope it can be used normally
**Actual results:** 
App crash
<details>
  <summary>

```
Thread 0 (crashed)
 0  libflutter.so + 0x31374c
 1  libflutter.so + 0x315d31
 2  libflutter.so + 0x315d41
 3  libflutter.so + 0x148de5
 4  libflutter.so + 0x28eedd
 5  libflutter.so + 0x28e891
 6  libflutter.so + 0x28e8b5
 7  libflutter.so + 0x148de5
 8  libflutter.so + 0x1e8817
 9  libflutter.so + 0x1e8cc7
10  libflutter.so + 0x1e8891
11  libflutter.so + 0x1e88a5
12  libflutter.so + 0x142f5f
13  libflutter.so + 0x1cf33f
14  libflutter.so + 0x1cf2cb
15  libflutter.so + 0x1cf479
16  libflutter.so + 0x2038f7
17  libflutter.so + 0x20390d
18  libflutter.so + 0x15b58b
19  libflutter.so + 0x15dfb3
```

</summary>

```
```

```
```

```
Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.6 19G73 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 2.2.3 at /Users/xingke/Documents/Project/Flutter
    • Framework revision f4abaa0735 (6 周前), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/xingke/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS
      development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • SM G9650 (mobile) • 314c494d4a4c3098 • android-arm64  • Android 8.0.0 (API
      26)
    • Chrome (web)      • chrome           • web-javascript • Google Chrome
      92.0.4515.131
```

</details>

**Comment by jiangxklongmao** [comment]
@flutter-symbolizer-bot

**Comment by jiangxklongmao** [comment]
@flutter-symbolizer-bot 
engine#241c87ad80
flutter#vf4abaa0735
release
arm|arm64
[https://github.com/flutter/flutter/issues/87937|this]

**Comment by TahaTesser** [comment]
@flutter-symbolizer-bot engine#241c87ad80 flutter#vf4abaa0735 release arm|arm64 https://github.com/flutter/flutter/issues/87937#issue-963754358

**Comment by TahaTesser** [comment]
Hi @jiangxklongmao 
Is this is on Android or iOS? Can you please provide your `flutter doctor -v`

**Comment by jiangxklongmao** [comment]
This is an Android problem。
`
 ~ flutter doctor -v
[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.6 19G73 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 2.2.3 at /Users/xingke/Documents/Project/Flutter
    • Framework revision f4abaa0735 (6 周前), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/xingke/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS
      development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • SM G9650 (mobile) • 314c494d4a4c3098 • android-arm64  • Android 8.0.0 (API
      26)
    • Chrome (web)      • chrome           • web-javascript • Google Chrome
      92.0.4515.131

! Doctor found issues in 2 categories.

`

**Comment by chinmaygarde** [comment]
@flutter-symbolizer-bot engine#241c87ad80 release arm

**Comment by chinmaygarde** [comment]
> Update the files as follows: ...

I think you missed the files you need us to update. Can you fill out the template please?

Can you also paste the entire crash report instead of just the thread trace please? The symbolizer bot need that additional information.

**Comment by jason-simmons** [comment]
I noticed that the `libEGL : call to OpenGL ES API with no current context (logged once per thread)` warning happens when you destroy the engine on Android (e.g. by pressing the back button)

This is related to the shared `AndroidContext` introduced in https://github.com/flutter/engine/pull/23798

That PR changed `AndroidContext` to be an object held through multiple `shared_ptr` instances.  The `AndroidContext` also holds a reference to a shared `GrDirectContext`.

With PR #23798 the `AndroidSurface` is now holding a reference to the `AndroidContext`, in addition to the reference held directly by the `PlatformViewAndroid`.  Both of those references are deleted on the platform thread.

When the last reference to the `AndroidContext` is deleted, the `AndroidContext` dtor calls `releaseResourcesAndAbandonContext` on the `GrDirectContext`.  `releaseResourcesAndAbandonContext` can call OpenGL ES APIs (specifically the call to `glFinish` in `GrGLGpu::finishOutstandingGpuWork`)

Therefore this call is causing GLES API calls to happen on the platform thread, which does not have a valid EGL context.  Even if `AndroidContext` removed the call to `releaseResourcesAndAbandonContext` there would still be a problem because the `GrDirectContext` dtor makes similar GLES calls to flush any pending work.

Prior to PR #23798 the `AndroidContext` was owned by the `PlatformViewAndroid` and it did not hold a reference to a shared `GrDirectContext`.  Instead, the `GrDirectContext` was created by the `GPUSurfaceGL`, which is handed off to the rasterizer.  The `GPUSurfaceGL` can then release the `GrDirectContext` on the rasterizer thread where it can activate the necessary EGL context.

I don't know if there is a clean way to solve this.
It looks like the `GrDirectContext` is supposed to be deleted on a thread with an EGL context (not the platform thread).  But the various references to the shared `AndroidContext` that owns the `GrDirectContext` are held by objects tied to the platform thread.

@xster @blasten @chinmaygarde

**Comment by jiangxklongmao** [comment]
This crash accounts for 90 percent of all crashes. 
### **I use the flutterEngineGroup to create engine and  used an external image texture to display the image.**

Logs:

`
Thread 0 (crashed)
 0  libflutter.so + 0x31374c
 1  libflutter.so + 0x315d31
 2  libflutter.so + 0x315d41
 3  libflutter.so + 0x148de5
 4  libflutter.so + 0x28eedd
 5  libflutter.so + 0x28e891
 6  libflutter.so + 0x28e8b5
 7  libflutter.so + 0x148de5
 8  libflutter.so + 0x1e8817
 9  libflutter.so + 0x1e8cc7
10  libflutter.so + 0x1e8891
11  libflutter.so + 0x1e88a5
12  libflutter.so + 0x142f5f
13  libflutter.so + 0x1cf33f
14  libflutter.so + 0x1cf2cb
15  libflutter.so + 0x1cf479
16  libflutter.so + 0x2038f7
17  libflutter.so + 0x20390d
18  libflutter.so + 0x15b58b
19  libflutter.so + 0x15dfb3








08-18 19:05:24.478  5561  5576 I chatty  : uid=10031(com.sina.weibo) FinalizerDaemon expire 56 lines
08-18 19:05:24.500  7301  7354 I chatty  : uid=10031(com.sina.weibo) CrRendererMain expire 4 lines
08-18 19:05:24.795  5561  7295 I chatty  : uid=10031(com.sina.weibo) pool-26-thread- expire 1 line
08-18 19:05:24.881  5561  5561 I chatty  : uid=10031(com.sina.weibo) expire 7 lines
08-18 19:05:24.974  5561  5561 V ActivityThread: callActivityOnCreate
08-18 19:05:24.998  5561  5561 D ActivityThread: add activity client record, r= ActivityRecord{9204cc4 token=android.os.BinderProxy@4f9e5ce {com.sina.weibo/com.sina.weibo.wboxsdk.page.acts.WBXPageActivity}} token= android.os.BinderProxy@4f9e5ce
08-18 19:05:25.081  5561  7360 I chatty  : uid=10031(com.sina.weibo) bridge.p-Thread expire 1 line
08-18 19:05:25.090  5561  5669 I chatty  : uid=10031(com.sina.weibo) RenderThread expire 2 lines
08-18 19:05:25.102  5561  7370 I chatty  : uid=10031(com.sina.weibo) expire 1 line
08-18 19:05:25.330  7301  7352 I chatty  : uid=10031 com.sina.weibo:sandboxed_process1 expire 1 line
08-18 19:05:25.472  5561  7336 I chatty  : uid=10031(com.sina.weibo) 1.raster expire 1 line
08-18 19:05:25.493  5561  5561 I chatty  : uid=10031(com.sina.weibo) expire 5 lines
08-18 19:05:25.494  5561  5669 I chatty  : uid=10031(com.sina.weibo) RenderThread expire 2 lines
08-18 19:05:25.617  5561  5561 E FlutterDynamicChannel: sendDomCommandEventToFlutter domCommands: [[s,203,analysisInfo,{lfid:profile_me,luicode:10000011,uiCode:10000381}]] pageId: 4
08-18 19:05:25.618  5561  5561 E FlutterDynamicChannel: sendDomCommandEventToFlutter domCommands: [[s,630,arg0,194.78MB]] pageId: 4
08-18 19:05:25.769  5561  7336 W libEGL  : EGLNativeWindowType 0x87c05808 disconnect failed
08-18 19:05:25.775  5561  5669 W libEGL  : EGLNativeWindowType 0x8f4bf988 disconnect failed
08-18 19:05:25.810  5561  5669 W libEGL  : EGLNativeWindowType 0x944e0588 disconnect failed
08-18 19:05:26.265  5561  5561 W Settings: Setting device_provisioned has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
08-18 19:05:26.266  5561  5561 V HiTouch_HiTouchSensor: User setup is finished.
08-18 19:05:26.330  7301  7352 I ServiceManager: Waiting for service 'huawei.android.security.IAppBehaviorDataAnalyzer' on '/dev/binder'...
08-18 19:05:26.351  5561  5561 E FlutterDynamicChannel: 方法：callJS  参数：{instanceId=4, data=[4, 29, onTap, {timeStamp=5345419, currentTarget=29, detail={}, type=onTap, target=29}], pageId=4}
08-18 19:05:26.351  5561  5561 E FlutterDynamicChannel: call wbbroadcase.send
08-18 19:05:26.399  5561  5561 I FlutterRender: onPageHide: 
08-18 19:05:26.410  5561  5561 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@b130e2e
08-18 19:05:26.424  5561  5561 V ActivityThread: callActivityOnCreate
08-18 19:05:26.449  5561  5561 E ThemeUtils: View class com.airbnb.lottie.LottieAnimationView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
08-18 19:05:26.487  5561  5561 D ActivityThread: add activity client record, r= ActivityRecord{a28b938 token=android.os.BinderProxy@b130e2e {com.sina.weibo/com.sina.weibo.account.AccountManagerActivity}} token= android.os.BinderProxy@b130e2e
08-18 19:05:26.592  5561  5669 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
08-18 19:05:26.602  5561  7398 D HiTouch_PressGestureDetector: onAttached, package=com.sina.weibo, windowType=2, mHiTouchRestricted=false
08-18 19:05:26.624  5561  7399 D HiTouch_PressGestureDetector: onAttached, package=com.sina.weibo, windowType=1, mHiTouchRestricted=false
08-18 19:05:26.638  5561  5669 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
08-18 19:05:26.686  5561  5669 D OpenGLRenderer: disableOutlineDraw is true
08-18 19:05:26.718  5561  5669 W libEGL  : EGLNativeWindowType 0x944e0588 disconnect failed
08-18 19:05:26.728  5561  5669 D OpenGLRenderer: disableOutlineDraw is true
08-18 19:05:26.992  5561  5669 W libEGL  : EGLNativeWindowType 0x9e076088 disconnect failed
08-18 19:05:27.020  5561  7336 W libEGL  : EGLNativeWindowType 0x962fe008 disconnect failed
08-18 19:05:27.055  5561  5669 W libEGL  : EGLNativeWindowType 0xa5f6f848 disconnect failed
08-18 19:05:27.152  5561  5561 W Settings: Setting device_provisioned has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
08-18 19:05:27.152  5561  5561 V HiTouch_HiTouchSensor: User setup is finished.
08-18 19:05:27.237  5561  5574 I com.sina.weibo: Background concurrent copying GC freed 368511(20MB) AllocSpace objects, 68(5964KB) LOS objects, 33% free, 46MB/70MB, paused 240us total 509.736ms
08-18 19:05:27.242  5561  5561 V AudioManager: querySoundEffectsEnabled...
08-18 19:05:27.250  5561  5576 W System  : A resource failed to call close. 
08-18 19:05:27.255  5561  5576 W System  : A resource failed to call close. 
08-18 19:05:27.289  5561  7411 D HiTouch_PressGestureDetector: onAttached, package=com.sina.weibo, windowType=2, mHiTouchRestricted=false
08-18 19:05:27.312  5561  5669 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
08-18 19:05:27.327  5561  5669 D OpenGLRenderer: disableOutlineDraw is true
08-18 19:05:27.332  7301  7352 I ServiceManager: Waiting for service 'huawei.android.security.IAppBehaviorDataAnalyzer' on '/dev/binder'...
08-18 19:05:27.376  5561  5895 W chromium: [WARNING:cookie_manager.cc(131)] Strict Secure Cookie policy does not allow setting a secure cookie for http://weibo.com/
08-18 19:05:27.377  5561  5895 I chatty  : uid=10031(com.sina.weibo) CookieMonsterCl identical 2 lines
08-18 19:05:27.377  5561  5895 W chromium: [WARNING:cookie_manager.cc(131)] Strict Secure Cookie policy does not allow setting a secure cookie for http://weibo.com/
08-18 19:05:27.380  5561  5895 W chromium: [WARNING:cookie_manager.cc(131)] Strict Secure Cookie policy does not allow setting a secure cookie for http://weibo.cn/
08-18 19:05:27.382  5561  5895 W chromium: [WARNING:cookie_manager.cc(131)] Strict Secure Cookie policy does not allow setting a secure cookie for http://weibo.cn/
08-18 19:05:27.424  5561  5561 D ReserveCache-wblive: action = sina.weibo.action.SWITCHUSERDONE
08-18 19:05:27.428  5561  7415 W SharedPreferencesImpl: Cannot read /data/user/0/com.sina.weibo/shared_prefs/pref_users_theme.xml
08-18 19:05:27.428  5561  7415 W SharedPreferencesImpl: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
08-18 19:05:27.428  5561  7415 W SharedPreferencesImpl: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1416)
08-18 19:05:27.428  5561  7415 W SharedPreferencesImpl: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:748)
08-18 19:05:27.428  5561  7415 W SharedPreferencesImpl: 	at android.app.SharedPreferencesImpl.loadFromDisk(SharedPreferencesImpl.java:157)
08-18 19:05:27.428  5561  7415 W SharedPreferencesImpl: 	at android.app.SharedPreferencesImpl.access$000(SharedPreferencesImpl.java:55)
08-18 19:05:27.428  5561  7415 W SharedPreferencesImpl: 	at android.app.SharedPreferencesImpl$1.run(SharedPreferencesImpl.java:126)
08-18 19:05:27.543  5561  5604 W System.err: java.nio.channels.OverlappingFileLockException
08-18 19:05:27.543  5561  5604 W System.err: 	at sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:255)
08-18 19:05:27.543  5561  5604 W System.err: 	at sun.nio.ch.SharedFileLockTable.add(FileLockTable.java:152)
08-18 19:05:27.543  5561  5604 W System.err: 	at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1174)
08-18 19:05:27.543  5561  5604 W System.err: 	at java.nio.channels.FileChannel.tryLock(FileChannel.java:1155)
08-18 19:05:27.543  5561  5604 W System.err: 	at com.sina.weibo.utils.ad.b(CacheManagerNew.java:1777)
08-18 19:05:27.543  5561  5604 W System.err: 	at com.sina.weibo.utils.ad.a(CacheManagerNew.java:618)
08-18 19:05:27.543  5561  5604 W System.err: 	at com.sina.weibo.utils.ad.a(CacheManagerNew.java:631)
08-18 19:05:27.543  5561  5604 W System.err: 	at com.sina.weibo.utils.b.b(AccountSdkCacheUtils.java:52)
08-18 19:05:27.543  5561  5604 W System.err: 	at com.sina.weibo.business.bi.a(UserInfoCenter.java:152)
08-18 19:05:27.543  5561  5604 W System.err: 	at com.sina.weibo.utils.dp$c.a(MemberUtils.java:365)
08-18 19:05:27.543  5561  5604 W System.err: 	at com.sina.weibo.utils.dp$c.doInBackground(MemberUtils.java:331)
08-18 19:05:27.543  5561  5604 W System.err: 	at com.sina.weibo.av.d$2.call(ExtendedAsyncTask.java:93)
08-18 19:05:27.543  5561  5604 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08-18 19:05:27.543  5561  5604 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-18 19:05:27.543  5561  5604 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-18 19:05:27.543  5561  5604 W System.err: 	at java.lang.Thread.run(Thread.java:929)
08-18 19:05:27.605  5561  7419 W SharedPreferencesImpl: Cannot read /data/user/0/com.sina.weibo/shared_prefs/dm_prefs5600126434.xml
08-18 19:05:27.605  5561  7419 W SharedPreferencesImpl: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
08-18 19:05:27.605  5561  7419 W SharedPreferencesImpl: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1416)
08-18 19:05:27.605  5561  7419 W SharedPreferencesImpl: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:748)
08-18 19:05:27.605  5561  7419 W SharedPreferencesImpl: 	at android.app.SharedPreferencesImpl.loadFromDisk(SharedPreferencesImpl.java:157)
08-18 19:05:27.605  5561  7419 W SharedPreferencesImpl: 	at android.app.SharedPreferencesImpl.access$000(SharedPreferencesImpl.java:55)
08-18 19:05:27.605  5561  7419 W SharedPreferencesImpl: 	at android.app.SharedPreferencesImpl$1.run(SharedPreferencesImpl.java:126)
08-18 19:05:28.109  5561  5561 W System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.concurrent.CopyOnWriteArrayList.isEmpty()' on a null object reference
08-18 19:05:28.109  5561  5561 W System.err: 	at com.sina.weibo.weiyou.utils.ao.e(WeiyouResourceUtils.java:755)
08-18 19:05:28.109  5561  5561 W System.err: 	at com.sina.weibo.weiyou.refactor.service.DMService.g(DMService.java:1119)
08-18 19:05:28.109  5561  5561 W System.err: 	at com.sina.weibo.weiyou.refactor.service.DMService$7.onReceive(DMService.java:1013)
08-18 19:05:28.109  5561  5561 W System.err: 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1631)
08-18 19:05:28.109  5561  5561 W System.err: 	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
08-18 19:05:28.109  5561  5561 W System.err: 	at android.os.Handler.handleCallback(Handler.java:888)
08-18 19:05:28.109  5561  5561 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:100)
08-18 19:05:28.109  5561  5561 W System.err: 	at android.os.Looper.loop(Looper.java:213)
08-18 19:05:28.109  5561  5561 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:8178)
08-18 19:05:28.109  5561  5561 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
08-18 19:05:28.109  5561  5561 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
08-18 19:05:28.109  5561  5561 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
08-18 19:05:28.215  5561  7479 W SharedPreferencesImpl: Cannot read /data/user/0/com.sina.weibo/shared_prefs/abserver_manager_pre_name5600126434.xml
08-18 19:05:28.215  5561  7479 W SharedPreferencesImpl: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
08-18 19:05:28.215  5561  7479 W SharedPreferencesImpl: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1416)
08-18 19:05:28.215  5561  7479 W SharedPreferencesImpl: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:748)
08-18 19:05:28.215  5561  7479 W SharedPreferencesImpl: 	at android.app.SharedPreferencesImpl.loadFromDisk(SharedPreferencesImpl.java:157)
08-18 19:05:28.215  5561  7479 W SharedPreferencesImpl: 	at android.app.SharedPreferencesImpl.access$000(SharedPreferencesImpl.java:55)
08-18 19:05:28.215  5561  7479 W SharedPreferencesImpl: 	at android.app.SharedPreferencesImpl$1.run(SharedPreferencesImpl.java:126)
08-18 19:05:28.334  5561  5669 W libEGL  : EGLNativeWindowType 0x8f012988 disconnect failed
08-18 19:05:28.334  7301  7352 I ServiceManager: Waiting for service 'huawei.android.security.IAppBehaviorDataAnalyzer' on '/dev/binder'...
08-18 19:05:28.356  5561  5561 E FlutterDynamicChannel: sendDomCommandEventToFlutter domCommands: [[s,630,arg0,214.39MB]] pageId: 2
08-18 19:05:28.356  5561  5561 E FlutterDynamicChannel: sendDomCommandEventToFlutter domCommands: [[s,630,arg0,214.39MB]] pageId: 4
08-18 19:05:28.521  5561  5574 I com.sina.weibo: Background young concurrent copying GC freed 355615(15MB) AllocSpace objects, 114(10MB) LOS objects, 26% free, 51MB/70MB, paused 616us total 353.348ms
08-18 19:05:28.522  5561  5576 W System  : A resource failed to call close. 
08-18 19:05:28.523  5561  5576 I chatty  : uid=10031(com.sina.weibo) FinalizerDaemon identical 30 lines
08-18 19:05:28.524  5561  5576 W System  : A resource failed to call close. 
08-18 19:05:28.573  5561  5561 I FlutterRender: onPageDestroy: 
08-18 19:05:28.582  5561  5561 D ActivityThread: Remove activity client record, r= ActivityRecord{318eb34 token=android.os.BinderProxy@1a1b772 {com.sina.weibo/com.sina.weibo.wboxsdk.page.acts.WBXPageActivity}} token= android.os.BinderProxy@1a1b772
08-18 19:05:28.593  5561  5895 W chromium: [WARNING:cookie_manager.cc(131)] Strict Secure Cookie policy does not allow setting a secure cookie for http://weibo.com/
08-18 19:05:28.593  5561  5561 I FlutterRender: onPageDestroy: 
08-18 19:05:28.598  5561  5895 W chromium: [WARNING:cookie_manager.cc(131)] Strict Secure Cookie policy does not allow setting a secure cookie for http://weibo.com/
08-18 19:05:28.601  5561  5895 W chromium: [WARNING:cookie_manager.cc(131)] Strict Secure Cookie policy does not allow setting a secure cookie for http://weibo.com/
08-18 19:05:28.607  5561  5895 W chromium: [WARNING:cookie_manager.cc(131)] Strict Secure Cookie policy does not allow setting a secure cookie for http://weibo.cn/
08-18 19:05:28.608  5561  5561 E libEGL  : call to OpenGL ES API with no current context (logged once per thread)
08-18 19:05:28.609  5561  5895 W chromium: [WARNING:cookie_manager.cc(131)] Strict Secure Cookie policy does not allow setting a secure cookie for http://weibo.cn/
08-18 19:05:28.611  5561  5895 W chromium: [WARNING:cookie_manager.cc(131)] Strict Secure Cookie policy does not allow setting a secure cookie for http://weibo.cn/
08-18 19:05:28.813  5561  5611 W Settings: Setting android_id has moved from android.provider.Settings.System to android.provider.Settings.Secure, returning read-only value.
08-18 19:05:29.300  7301  7301 D AwareBitmapCacher: handleInit disable com.sina.weibo:sandboxed_process1
08-18 19:05:29.335  7301  7352 W ServiceManager: Service huawei.android.security.IAppBehaviorDataAnalyzer didn't start. Returning NULL
08-18 19:05:29.335  7301  7352 E dboxed_process: [HOTFIX][ThreadDexHotfixMonitor]Bind hotfix monitor service fail!
08-18 19:05:29.535  5561  5574 I com.sina.weibo: Background concurrent copying GC freed 541175(18MB) AllocSpace objects, 148(10MB) LOS objects, 35% free, 44MB/68MB, paused 905us total 712.847ms
08-18 19:05:29.879  7499  7499 D skia    : HME hme_jpeg_dec version=JPEG_DEC_16.12.1, releasetime=09:46:52 Nov 18 2020
08-18 19:05:29.879  7499  7499 D skia    : HME SkHmeDecFunction1 constructor ok
08-18 19:05:30.208  7499  7499 E chromium: [0818/190530.202160:ERROR:elf_dynamic_array_reader.h(61)] tag not found
08-18 19:05:30.321  5561  5665 W Settings: Setting android_id has moved from android.provider.Settings.System to android.provider.Settings.Secure, returning read-only value.

`

**Comment by gaaclarke** [comment]
@jason-simmons Why can't we just move the call to ~AndroidContext to the raster thread?

```c++
AndroidSurface::~AndroidSurface() {
  threads_->RasterThread()->PostTask([android_context = std::move(android_context_)] {});
}
```

**Comment by jason-simmons** [comment]
Conceivably the `AndroidContextGL` destructor could queue a task to the raster thread that deletes the `GrDirectContext`.

Some issues with that:
* The AndroidContextGL destructor (called on the platform thread during PlatformView destruction) now has to interact with the raster thread and wait for the raster task to complete.  That adds more complexity to the shell shutdown sequence.
* The task in the AndroidContextGL destructor would need to create and destroy an EGL surface.  This is required because the raster thread needs a valid EGL context and surface so that the Skia GrDirectContext cleanup can issue OpenGL API calls.

**Comment by gaaclarke** [comment]
@jason-simmons For your second point, is the problem the added complexity or is there a significant performance problem?

**Comment by gaaclarke** [comment]
Here is a working change for @jason-simmons suggestion: https://github.com/gaaclarke/engine/commit/f51b3e40019885dbe3fe68a1dfd71345050d1b2e

Local testing seems good, it makes sense to me.  We could do some extra plumbing to cleanup with the last surface but that could be pretty massive so I like the pbuffer idea as long as there are no major performance concerns.

**Comment by jason-simmons** [comment]
I'm mostly concerned about the complexity (e.g. the potential risk of the surface creation API failing due to things like resource constraints).

Creating and destroying the pbuffer surface took a few hundred microseconds on a Moto G4.

**Comment by gaaclarke** [comment]
Alternatively, if you don't want to have a different threading model for `~Shell`, you could create an explicit step to do this cleanup and have it controlled by a shared_ptr that is kept next to the shared_ptr of the `AndroidContext`.

For example:
```c++
class AndroidContextCleanup {
 public:
  AndroidContextCleanup(std::shared_ptr<AndroidContext> context);
  ~AndroidContextCleanup() { context_->RasterCleanup(); }

 private:
  std::shared_ptr<AndroidContext> context_;
};
```

Then an extra step can be added to ~Shell
```c++
Shell::~Shell() {
  fml::TaskRunner::RunNowOrPostTask(
      task_runners_.GetRasterTaskRunner(),
      fml::MakeCopyable([this, rasterizer = std::move(rasterizer_), &gpu_latch,
                         platform_view = platform_view_.get()]() mutable {
        if (platform_view) {
          platform_view_->RasterCleanup();  // New step
        }
        rasterizer.reset();
        this->weak_factory_gpu_.reset();
        gpu_latch.Signal();
      }));
  gpu_latch.Wait();
```

`RasterCleanup` will eventually call `.reset()`:
```c++
void PlatformViewAndroid::RasterCleanup() {
  FML_DCHECK(android_context_cleanup_);
  android_context_cleanup_.reset();
}
```

and the context can be cleanedup:
```c++
void AndroidContextGL::RasterCleanup() {
    main_context->releaseResourcesAndAbandonContext();
}
```

This makes storage a bit more complicated since you have to keep a parallel object for the AndroidContext in the AndroidPlatformView, but the benefit is you don't have to have extra threading steps in `~Shell` (which I'm fine with but I know @jason-simmons had some concerns).

I tried it out, but I couldn't figure out the magic to make releaseResourcesAndAbandonContext work when called from there.

**Comment by jonahwilliams** [comment]
Closing as fixed
