### ISSUE TITLE
 RangeError (index): Invalid value: Valid value range is empty: 1. Error thrown Instance of 'ErrorDescription'.

### ISSUE THREAD

**Issue by ammaratef45** [flutter/flutter#87977]
I'm using flutter `2.0.4` and I got a similar error to #70612 (logs below)
The conversation there is locked so I've opened a new issue

```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: RangeError (index): Invalid value: Valid value range is empty: 1. Error thrown Instance of 'ErrorDescription'.
       at _GrowableList.[](_GrowableList.java)
       at _PrePairingDialogState.<fn>(_PrePairingDialogState.java:62)
       at _InkResponseState._handleTap(_InkResponseState.java:991)
       at GestureRecognizer.invokeCallback(GestureRecognizer.java:182)
       at TapGestureRecognizer.handleTapUp(TapGestureRecognizer.java:607)
       at BaseTapGestureRecognizer._checkUp(BaseTapGestureRecognizer.java:296)
       at BaseTapGestureRecognizer.handlePrimaryPointer(BaseTapGestureRecognizer.java:230)
       at PrimaryPointerGestureRecognizer.handleEvent(PrimaryPointerGestureRecognizer.java:475)
       at PointerRouter._dispatch(PointerRouter.java:93)
       at PointerRouter.<fn>(PointerRouter.java:138)
       at _LinkedHashMapMixin.forEach(_LinkedHashMapMixin.java)
       at PointerRouter._dispatchEventToRoutes(PointerRouter.java:136)
       at PointerRouter.route(PointerRouter.java:122)
       at GestureBinding.handleEvent(GestureBinding.java:381)
       at GestureBinding.dispatchEvent(GestureBinding.java:361)
       at RendererBinding.dispatchEvent(RendererBinding.java:278)
       at GestureBinding._handlePointerEventImmediately(GestureBinding.java:316)
       at GestureBinding.handlePointerEvent(GestureBinding.java:280)
       at GestureBinding._flushPointerEventQueue(GestureBinding.java:238)
       at GestureBinding._handlePointerDataPacket(GestureBinding.java:221)
```

### Output for`flutter doctor -v`

```
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.4 20F71 darwin-x64, locale
    en-US)
    • Flutter version 2.0.4 at /Users/ahussein/development/flutter
    • Framework revision b1395592de (4 months ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/ahussein/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/ahussein/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.131

• No issues found!
```

## Output for `flutter doctor -v`

```
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.4 20F71 darwin-x64, locale
    en-US)
    • Flutter version 2.0.4 at /Users/ahussein/development/flutter
    • Framework revision b1395592de (4 months ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/ahussein/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/ahussein/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.131

• No issues found!
```

**Comment by maheshmnj** [comment]
Hi @ammaratef45,
Thanks for filing the issue, Please provide the output of `flutter doctor -v` along with [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example), This helps to better investigate the issue.

Thank you.

**Comment by maheshmnj** [comment]
Can you share the complete log by running `flutter run -v`?

Thanks

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
