### ISSUE TITLE
“Invalid uncompressed block header” when unzipping a password-protected zip

### ISSUE THREAD

**Issue by yuwono95** [flutter/flutter#88017]
I'm trying to unzip a password-protected zip file in Flutter.  But got an error:

> Invalid uncompressed block header

I'm using Android Studio 2020.3.1 with flutter 2.2.3 and Dart 2.13.4 on Windows 10.

## Steps to Reproduce

1. Add the package:
`import 'package:archive/archive_io.dart';`

2. Add the extract function:
`...
extractFileToDisk(path + "/a.zip", path, password: "a_password");
...`

3.  Run "main.dart"

**Expected results:** 

Success.

**Actual results:** 

<details>
  <summary>Logs</summary>

```
Launching lib\main.dart on M2007J20CG in debug mode...
Running Gradle task 'assembleDebug'...
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Debug service listening on ws://127.0.0.1:56721/v3w3Ks2a1AY=/ws
Syncing files to device M2007J20CG...
W/m.audio_ibrahi( 1046): Accessing hidden method Lsun/misc/Unsafe;->getUnsafe()Lsun/misc/Unsafe; (greylist,core-platform-api, linking, allowed)
W/m.audio_ibrahi( 1046): Accessing hidden method Lsun/misc/Unsafe;->objectFieldOffset(Ljava/lang/reflect/Field;)J (greylist,core-platform-api, linking, allowed)
W/m.audio_ibrahi( 1046): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
W/m.audio_ibrahi( 1046): Accessing hidden method Landroid/media/AudioTrack;->getLatency()I (greylist, reflection, allowed)
I/flutter ( 1046): Directory: '/storage/emulated/0/Android/data/com.quraninsight.audio.ibrahim.audio_ibrahim/files'
I/ExoPlayerImpl( 1046): Init 20f09bc [ExoPlayerLib/2.13.1] [surya, M2007J20CG, Xiaomi, 29]
D/AudioManager( 1046): getStreamVolume isRestricted mode = 0
W/m.audio_ibrahi( 1046): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
W/VideoCapabilities( 1046): Unsupported mime image/vnd.android.heic
W/VideoCapabilities( 1046): Unrecognized profile/level 0/3 for video/mpeg2
W/VideoCapabilities( 1046): Unrecognized profile/level 0/3 for video/mpeg2
W/VideoCapabilities( 1046): Unsupported mime video/x-ms-wmv
I/OMXClient( 1046): IOmx service obtained
I/ACodec  ( 1046): codec does not support config priority (err -2147483648)
I/ACodec  ( 1046): codec does not support config priority (err -2147483648)
W/ExtendedACodec( 1046): Failed to get extension for extradata parameter
E/flutter ( 1046): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: FormatException: Invalid uncompressed block header
E/flutter ( 1046): #0      Inflate._parseUncompressedBlock (package:archive/src/zlib/inflate.dart:198:7)
E/flutter ( 1046): #1      Inflate._parseBlock (package:archive/src/zlib/inflate.dart:116:9)
E/flutter ( 1046): #2      Inflate._inflate (package:archive/src/zlib/inflate.dart:92:20)
E/flutter ( 1046): #3      new Inflate.buffer (package:archive/src/zlib/inflate.dart:22:5)
E/flutter ( 1046): #4      ArchiveFile.decompress (package:archive/src/archive_file.dart:76:28)
E/flutter ( 1046): #5      ArchiveFile.content (package:archive/src/archive_file.dart:67:7)
E/flutter ( 1046): #6      extractFileToDisk (package:archive/src/io/extract_archive_to_disk.dart:67:29)
E/flutter ( 1046): #7      _MyHomePageState.initState.extractFile (package:my_project/main.dart:116:9)
```

```
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1110], locale id-ID)
    • Flutter version 2.2.3 at C:\Users\yuwon\flutter
    • Framework revision f4abaa0735 (6 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\.......\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Connected device (3 available)
    • M2007J20CG (mobile) • c49fcf4e • android-arm64  • Android 10 (API 29)
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 92.0.4515.131
    • Edge (web)          • edge     • web-javascript • Microsoft Edge 92.0.902.67

• No issues found!
```

</details>

**Comment by TahaTesser** [comment]
Hi @yuwono95 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/brendan-duncan/archive/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`, a minimal reproducible code sample that does not use 3rd party plugins, your complete `flutter run -v` logs running the minimal code sample 
and I will reopen it.
Thank you
