### ISSUE TITLE
Linux ci yaml roller builder is failing

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#88041]
```
The recipe has crashed at point 'Uncaught exception'!

Traceback (most recent call last):
  File "/b/s/w/ir/kitchen-checkout/recipe_engine/recipe_engine/internal/engine.py", line 574, in run_steps
    raw_result = recipe_obj.run_steps(api, engine)
  File "/b/s/w/ir/kitchen-checkout/recipe_engine/recipe_engine/internal/recipe_deps.py", line 907, in run_steps
    properties_def, api=api)
  File "/b/s/w/ir/kitchen-checkout/recipe_engine/recipe_engine/internal/property_invoker.py", line 91, in invoke_with_properties
    arg_names, **additional_args)
  File "/b/s/w/ir/kitchen-checkout/recipe_engine/recipe_engine/internal/property_invoker.py", line 54, in _invoke_with_properties
    return callable_obj(*props, **additional_args)
  File "/b/s/w/ir/kitchen-checkout/flutter/recipes/infra/ci_yaml.py", line 87, in RunSteps
    jspb_step = api.step('generate jspb', cmd=['dart', generate_jspb_path, repo, commit_sha], stdout=api.raw_io.output_text(), stderr=api.raw_io.output_text())
  File "/b/s/w/ir/kitchen-checkout/recipe_engine/recipe_engine/recipe_api.py", line 664, in _inner
    return func(*a, **kw)
  File "/b/s/w/ir/kitchen-checkout/recipe_engine/recipe_modules/step/api.py", line 571, in __call__
    self._validate_cmd_list(cmd)
  File "/b/s/w/ir/kitchen-checkout/recipe_engine/recipe_modules/step/api.py", line 322, in _validate_cmd_list
    'cmd is %r' % (type(arg), cmd))
ValueError: Type <type 'NoneType'> is not permitted. cmd is ['dart', Path([START_DIR], 'cocoon', 'app_dart', 'bin', 'generate_jspb.dart'), 'engine', None]
```

https://ci.chromium.org/p/flutter/builders/prod/Linux%20ci_yaml%20engine%20roller/172

**Comment by CaseyHillers** [comment]
Closing this as the presubmit fix recipe has landed.
