### ISSUE TITLE
Cannot accept Flutter Android licenses

### ISSUE THREAD

**Issue by Patra3** [flutter/flutter#88053]
When I run `flutter doctor --android-licenses` in Powershell (either as system32 or normal user), it throws the error found in Logs below. This prevents me from accepting the licenses to progress with the installation.

## Steps to Reproduce

1. Run `flutter doctor --android-licenses`

## Logs

<details>
<summary>Logs</summary>

`Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
        ... 5 more`

```
```

```
```

</details>

**Comment by TahaTesser** [comment]
Hi @Patra3 
Make sure you've installed cmdtools, see https://github.com/flutter/flutter/issues/86184#issuecomment-878198713 and the try `flutter doctor --android-licenses`
