### ISSUE TITLE
[pigeon] enum null safety is not working

### ISSUE THREAD

**Issue by uOOOO** [flutter/flutter#88078]
## Steps to Reproduce

1. Write pigeon dart like this.
```dart
import 'package:pigeon/pigeon.dart';

enum Type { TYPE_A, TYPE_B }

class Goods {
  String? name;
  int? price;
  int? expiryDate;
  Type? type;
}

@HostApi()
abstract class StoreApi {
  void sell(Goods goods);
}
```
2. Generate pigeon files
3. Use pigeon generated Java classes like this but except enum value
```kotlin
fun sell(arg: Messages.Goods) {
    // Assume the enum value Type is null in Goods
    val goods = Goods(arg.name, arg.price, arg.expiryDate)
    JavaApi.sell(goods)
  }
```
4. Run app

**Expected results:** no exception occurred

**Actual results:** NPE occurred
```
PlatformException(NullPointerException, java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference, null, null)
```

I think there is no null check in Goods.fromMap.
```java
static Goods fromMap(Map<String, Object> map) {
    Goods fromMapResult = new Goods();
    Object name = map.get("name");
    fromMapResult.name = (String)name;
    Object price = map.get("price");
    fromMapResult.price = (price == null) ? null : ((price instanceof Integer) ? (Integer)price : (Long)price);
    Object expiryDate = map.get("expiryDate");
    fromMapResult.expiryDate = (expiryDate == null) ? null : ((expiryDate instanceof Integer) ? (Integer)expiryDate : (Long)expiryDate);
    Object type = map.get("type");
    fromMapResult.type = Type.values()[(int)type];
    return fromMapResult;
}
```

When I edited like this, no exception occurred.
```java
fromMapResult.type = Type.values()[(int)type]; 
=>
fromMapResult.type = type == null ? null : Type.values()[(int)type];
```

**Comment by TahaTesser** [comment]
Hi @uOOOO 
Can you please provide your `flutter doctor -v`

**Comment by uOOOO** [comment]
Hi @TahaTesser Here is the result.

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.1 20G80 darwin-x64, locale ko-KR)
    • Flutter version 2.2.3 at /Users/ooo/work/flutter
    • Framework revision f4abaa0735 (6 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/ooo/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio Arctic Fox.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio Arctic Fox.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 92.0.4515.131

• No issues found!
```

**Comment by TahaTesser** [comment]
HI @uOOOO 
I just tried your code, it throws the following errors
![image](https://user-images.githubusercontent.com/48603081/129273249-b1ab6d26-c3e1-45ec-afe5-5d1cedbfd2b6.png)

I see there is Goods constructor  in generated code that takes all three params 

```kt
package com.tahatesser.triage

import androidx.annotation.NonNull

import io.flutter.embedding.engine.plugins.FlutterPlugin
import io.flutter.plugin.common.MethodCall
import io.flutter.plugin.common.MethodChannel
import io.flutter.plugin.common.MethodChannel.MethodCallHandler
import io.flutter.plugin.common.MethodChannel.Result

/** TriagePlugin */
class TriagePlugin: FlutterPlugin, MethodCallHandler, Messages.StoreApi {
  /// The MethodChannel that will the communication between Flutter and native Android
  ///
  /// This local reference serves to register the plugin with the Flutter Engine and unregister it
  /// when the Flutter Engine is detached from the Activity
  private lateinit var channel : MethodChannel

  override fun onAttachedToEngine(@NonNull flutterPluginBinding: FlutterPlugin.FlutterPluginBinding) {
    channel = MethodChannel(flutterPluginBinding.binaryMessenger, "triage")
    channel.setMethodCallHandler(this)
  }

  override fun onMethodCall(@NonNull call: MethodCall, @NonNull result: Result) {
    if (call.method == "getPlatformVersion") {
      result.success("Android ${android.os.Build.VERSION.RELEASE}")
    } else {
      result.notImplemented()
    }
  }

  override fun onDetachedFromEngine(@NonNull binding: FlutterPlugin.FlutterPluginBinding) {
    channel.setMethodCallHandler(null)
  }

  override fun sell(arg: Messages.Goods?) {
    val goods = Messages.Goods(arg.name, arg.price, arg.expiryDate)
    JavaApi.sell(goods)
  }


}

```

**Comment by uOOOO** [comment]
@TahaTesser I'm sorry. I should have made a complete codes. Please check this sample app.

https://github.com/uOOOO/pigeon_plugin_example

There is a commented out line in example/lib/main.dart L49.

```dart
  Future<void> test() async {
    Goods goods = new Goods();
    // goods.type = Type.TYPE_A; <=
    await PigeonPlugin.sell(goods);
  }
```

If the line is commented out, you can see the error.

> E/flutter ( 9638): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(NullPointerException, java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference, null, null)
E/flutter ( 9638): #0      StoreApi.sell (package:pigeon_plugin/messages.dart:112:7)
E/flutter ( 9638): <asynchronous suspension>
E/flutter ( 9638): #1      PigeonPlugin.sell (package:pigeon_plugin/pigeon_plugin.dart:31:5)
E/flutter ( 9638): <asynchronous suspension>
E/flutter ( 9638): #2      _MyAppState.test (package:pigeon_plugin_example/main.dart:50:5)
E/flutter ( 9638): <asynchronous suspension>
E/flutter ( 9638):

**Comment by TahaTesser** [comment]
Hi @uOOOO 
Thank you so much for the complete code, I am able to reproduce it and making the changes you suggested, fixed the issue

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 12.0 21A5304g darwin-x64, locale en-GB)
    • Flutter version 2.2.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision f4abaa0735 (6 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Users/tahatesser/Code/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Temurin-11.0.12+7 (build 11.0.12+7)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 13.0, Build version 13A5212g
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2020.3)
    • Android Studio at /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7583922/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554                        • android-x86    • Android 11 (API 30) (emulator)
    • iPhone 12 (mobile)      • 7CC8A747-CD39-4C42-871C-2D1CCEAE2AE2 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)         • macos                                • darwin-x64     • macOS 12.0 21A5304g darwin-x64
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 92.0.4515.131

! Doctor found issues in 1 category.

```

</details>

thank you
