### ISSUE TITLE
[tool_crash] FileSystemException: readSync failed, OS Error: The operation completed successfully., errno = 0

### ISSUE THREAD

**Issue by jerickalmeda** [flutter/flutter#88097]
## Command
```
flutter build apk --split-per-abi --no-sound-null-safety
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: readSync failed, OS Error: The operation completed successfully.
, errno = 0
```
#0      _RandomAccessFile.readSync (dart:io/file_impl.dart:760:7)
#1      _File.readAsBytesSync (dart:io/file_impl.dart:552:23)
#2      ForwardingFile.readAsBytesSync (package:file/src/forwarding/forwarding_file.dart:88:43)
#3      ForwardingFile.readAsBytesSync (package:file/src/forwarding/forwarding_file.dart:88:43)
#4      _calculateSha (package:flutter_tools/src/android/gradle.dart:877:32)
#5      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:554:34)
<asynchronous suspension>
#6      AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:231:5)
<asynchronous suspension>
#7      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:105:5)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
<asynchronous suspension>
#14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.17763.2114], locale en-PH)
    • Flutter version 2.2.3 at C:\src\flutter
    • Framework revision f4abaa0735 (6 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\webdev-pc\AppData\Local\Android\Sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = C:\Users\webdev-pc\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\webdev-pc\AppData\Local\Android\tools\bin
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.58.2)
    • VS Code at C:\Users\webdev-pc\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Edge (web) • edge • web-javascript • Microsoft Edge 92.0.902.67

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f4abaa0735eba4dfd8f33f73363911d63931fe03
### Plugins
syncfusion_flutter_pdfviewer-19.2.49-beta
syncfusion_flutter_pdfviewer_macos-19.2.49-beta
syncfusion_flutter_pdfviewer_web-19.2.49-beta
video_player-2.1.12
video_player_web-2.0.2
wakelock-0.5.2
wakelock_macos-0.1.0+1
wakelock_web-0.2.0+1

**Comment by darshankawar** [comment]
There are below similar issues but with different `errno` , message and slightly different logs as well, so going ahead and labeling this issue.

https://github.com/flutter/flutter/issues/78236
https://github.com/flutter/flutter/issues/74846

**Comment by darshankawar** [comment]
@jerickalmeda 
Can you confirm if you are still experiencing this crash using latest stable version of the framework after running the given command ?

`flutter upgrade --force`
`flutter build apk --split-per-abi --no-sound-null-safety`
