### ISSUE TITLE
--dart-define when embedded in iOS with CocoaPods

### ISSUE THREAD

**Issue by mo5tone** [flutter/flutter#88092]
## Question
I'm integrating my Flutter module into my iOS project following the [Option-A](https://flutter.dev/docs/development/add-to-app/ios/project-setup#option-a---embed-with-cocoapods-and-the-flutter-sdk).

But I can not figure out **how to use `--dart-define` mentioned in [error-reporting](https://flutter.dev/docs/cookbook/maintenance/error-reporting) to define compile-time constants with the cocoapods**.

Do I still need something like `flutter build --dart-define=MY_FOO=BAR`? 

If yes, when and where should I execute the above command?

Do I miss any docs about this? Or just the [Option-A](https://flutter.dev/docs/development/add-to-app/ios/project-setup#option-a---embed-with-cocoapods-and-the-flutter-sdk) does not support `--dart-define`, I have to follow others options?

Maybe github issues not a place for **HOW TO** question, however I have post this on [stackoverflow](https://stackoverflow.com/questions/68630838/how-to-use-dart-define-when-my-flutter-module-embedded-in-ios-with-cocoapods), no answers yet.

## Log
```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.1 20G80 darwin-x64, locale en-CN)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.59.0)
[✓] Connected device (2 available)

! Doctor found issues in 2 categories.
```

**Comment by TahaTesser** [comment]
Hi @mo5tone 
I am not sure if it is possible Cocoapods as we are not building anything so but it does work in the iOS framework
Look at my reproduction here https://github.com/flutter/flutter/issues/76672#issuecomment-830116427

Labelling for documentation, if team decides it could be new feature, we can label it a new feature

**Comment by jmagman** [comment]
> If yes, when and where should I execute the above command?

You should run any `flutter` commands in your `flutter` module.  That will generate environment variables that are then used in your host app.

Does that work?

**Comment by mo5tone** [comment]
> > If yes, when and where should I execute the above command?
> 
> You should run any `flutter` commands in your `flutter` module. That will generate environment variables that are then used in your host app.
> 
> Does that work?

Not get your points very much.

Do you mean 

in my flutter module: 
```
flutter pub get
flutter build ios-framework --dart-define=MY_FOO=BAR --output=./flutter_output_dir/
```
then in my iOS project dir:
```
bundle exec pod install
```

Am I right?

However, I embedded flutter module with CocoaPods, so the output ios-framework does not make any sense to me.

**Comment by jmagman** [comment]
@mo5tone no, I'm not talking about `flutter build ios-framework`.

In your Flutter module you can `flutter run --dart-define=MY_FOO=BAR` or `flutter build ios --dart-define=MY_FOO=BAR`.    Then in your host project run `pod install`.

**Comment by TahaTesser** [comment]
Hi @jmagman 
Should this be documented in the following pages or some dedicated page that also includes related documentation?
[Integrate a Flutter module into your Android project](https://flutter.dev/docs/development/add-to-app/android/project-setup#option-b---depend-on-the-modules-source-code)
[Integrate a Flutter module into your iOS project](https://flutter.dev/docs/development/add-to-app/ios/project-setup)

**Comment by jmagman** [comment]
> Should this be documented in the following pages or some dedicated page that also includes related documentation?

That makes sense to me.

**Comment by mo5tone** [comment]
Hi @jmagman 
`flutter build ios --dart-define=MY_FOO=BAR` works for me.

But this will take time to run few tasks useless to me. e.g. `pod install` and `xcodebuild` in the Runner project. Will make impact on our CI.

At same time, it works well when just add `export "DART_DEFINES=MY_FOO%3DBAR"` into `my_flutter_module/.ios/Flutter/flutter_export_environment.sh`.

No useless tasks would execute.

So adding `export "DART_DEFINES=MY_FOO%3DBAR"` manually would make any hidden dangers? 

Would it keep working in future releases?

**Comment by jmagman** [comment]
`.ios/Flutter/flutter_export_environment.sh` will be recreated on every `flutter clean`, it's not intended to be checked into source control.

You're better off adding a `DART_DEFINES` Xcode build setting in your host app target.  https://stackoverflow.com/q/10854156

**Comment by mo5tone** [comment]
> `.ios/Flutter/flutter_export_environment.sh` will be recreated on every `flutter clean`, it's not intended to be checked into source control.
> 
> You're better off adding a `DART_DEFINES` Xcode build setting in your host app target. https://stackoverflow.com/q/10854156

thank you for saving my day

**Comment by jmagman** [comment]
We definitely need docs on this, it's undiscoverable.

**Comment by mo5tone** [comment]
> `.ios/Flutter/flutter_export_environment.sh` will be recreated on every `flutter clean`, it's not intended to be checked into source control.
> 
> You're better off adding a `DART_DEFINES` Xcode build setting in your host app target. https://stackoverflow.com/q/10854156

Hi @jmagman 

Errors occured after update my flutter SDK to 2.2.3

I set `DART_DEFINES = TVlfTkFNRT1tbzV0b25lCg==` in my xcconfig

Build failed in `[CP-User] Run Flutter Build my_flutter Script` with error message below:

<details>
<summary>Logs</summary>



```
♦ rm -rf -- /Users/5tone/Workspace/iOS/CAPP-iOS/flutter/.ios/Flutter/engine/Flutter.framework
♦ cp -r -- /Users/5tone/Library/Application Support/fvm/versions/2.2.3/bin/cache/artifacts/engine/ios/Flutter.xcframework /Users/5tone/Workspace/iOS/CAPP-iOS/flutter/.ios/Flutter/engine
♦ /Users/5tone/Library/Application Support/fvm/versions/2.2.3/bin/flutter --verbose assemble --no-version-check --output=/Users/5tone/Library/Developer/Xcode/DerivedData/capp-fncdifhuocolnebjcnwpvfscsxei/Build/Products/Debug-iphonesimulator/ -dTargetPlatform=ios -dTargetFile=lib/main.dart -dBuildMode=debug -dIosArchs=x86_64 -dSdkRoot=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk -dSplitDebugInfo= -dTreeShakeIcons=false -dTrackWidgetCreation=false -dDartObfuscation=false -dEnableBitcode= -dCodesignIdentity=- --ExtraGenSnapshotOptions= --DartDefines=TVlfTkFNRT1tbzV0b25lCg== --ExtraFrontEndOptions= debug_ios_bundle_flutter_assets
[ +102 ms] executing: sysctl hw.optional.arm64
[  +22 ms] Exit code 1 from: sysctl hw.optional.arm64
[   +1 ms] sysctl: unknown oid 'hw.optional.arm64'
[   +7 ms] executing: [/Users/5tone/Library/Application Support/fvm/versions/2.2.3/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +10 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] f4abaa0735eba4dfd8f33f73363911d63931fe03
[   +1 ms] executing: [/Users/5tone/Library/Application Support/fvm/versions/2.2.3/] git tag --points-at f4abaa0735eba4dfd8f33f73363911d63931fe03
[  +14 ms] Exit code 0 from: git tag --points-at f4abaa0735eba4dfd8f33f73363911d63931fe03
[        ] 2.2.3
[   +6 ms] executing: [/Users/5tone/Library/Application Support/fvm/versions/2.2.3/] git rev-parse --abbrev-ref --symbolic @{u}
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/5tone/Library/Application Support/fvm/versions/2.2.3/] git ls-remote --get-url origin
[   +6 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +84 ms] Unable to locate an Android SDK.
[   +9 ms] executing: [/Users/5tone/Library/Application Support/fvm/versions/2.2.3/] git rev-parse --abbrev-ref HEAD
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[   +5 ms] executing: sw_vers -productName
[  +16 ms] Exit code 0 from: sw_vers -productName
[        ] macOS
[        ] executing: sw_vers -productVersion
[  +15 ms] Exit code 0 from: sw_vers -productVersion
[        ] 11.5.2
[        ] executing: sw_vers -buildVersion
[  +13 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 20G95
[  +42 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +144 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +55 ms] Initializing file store
[  +50 ms] debug_unpack_ios: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents: /Users/5tone/Library/Application Support/fvm/versions/2.2.3/packages/flutter_tools/lib/src/build_system/targets/ios.dart,/Users/5tone/Library/Application Support/fvm/versions/2.2.3/bin/internal/engine.version}
[ +271 ms] Skipping lipo for non-fat file /Users/5tone/Library/Developer/Xcode/DerivedData/capp-fncdifhuocolnebjcnwpvfscsxei/Build/Products/Debug-iphonesimulator/Flutter.framework/Flutter
[ +553 ms] Skipping target: gen_localizations
[   +7 ms] debug_unpack_ios: Complete
[ +244 ms] kernel_snapshot: Starting due to {}
[  +26 ms] /Users/5tone/Library/Application Support/fvm/versions/2.2.3/bin/cache/dart-sdk/bin/dart --disable-dart-dev /Users/5tone/Library/Application Support/fvm/versions/2.2.3/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root /Users/5tone/Library/Application Support/fvm/versions/2.2.3/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --target=flutter --no-print-incremental-dependencies -DMY_NAME=mo5tone
            -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --no-link-platform --packages /Users/5tone/Workspace/iOS/CAPP-iOS/flutter/.dart_tool/package_config.json --output-dill /Users/5tone/Workspace/iOS/CAPP-iOS/flutter/.dart_tool/flutter_build/78945796d78b43f9b7bbc684038d89d2/app.dill --depfile /Users/5tone/Workspace/iOS/CAPP-iOS/flutter/.dart_tool/flutter_build/78945796d78b43f9b7bbc684038d89d2/kernel_snapshot.d package:capp_flutter/main.dart
[ +241 ms] Error: Error when reading '-DMY_NAME=mo5tone%0A': No such file or directory
[  +45 ms] -DMY_NAME=mo5tone%0A: Error: No 'main' method found.
[        ] Try adding a method named 'main' to your program.
[  +23 ms] Persisting file store
[   +3 ms] Done persisting file store
[   +4 ms] Target kernel_snapshot failed: Exception
           #0      KernelSnapshot.build (package:flutter_tools/src/build_system/targets/common.dart:291:7)
           <asynchronous suspension>
           #1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:828:9)
           <asynchronous suspension>
           #2      Future.wait.<anonymous closure> (dart:async/future.dart)
           <asynchronous suspension>
           #3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:766:32)
           <asynchronous suspension>
           #4      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:595:16)
           <asynchronous suspension>
           #5      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:318:32)
           <asynchronous suspension>
           #6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>

[  +11 ms] "flutter assemble" took 1,698ms.
[   +5 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:335:7)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[ +256 ms] ensureAnalyticsSent: 254ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
Command PhaseScriptExecution failed with a nonzero exit code
```



```
```

</details>

Everything goes well, when I switch back to 1.22.6 and set `DART_DEFINES = MY_NAME%3Dmo5tone` in xcconfig.

**Comment by mo5tone** [comment]
The reproducible demo: [dart-define-demo.zip](https://github.com/flutter/flutter/files/7112878/dart-define-demo.zip)

**Comment by mo5tone** [comment]
> > `.ios/Flutter/flutter_export_environment.sh` will be recreated on every `flutter clean`, it's not intended to be checked into source control.
> > You're better off adding a `DART_DEFINES` Xcode build setting in your host app target. https://stackoverflow.com/q/10854156
> 
> Hi @jmagman
> 
> Errors occured after update my flutter SDK to 2.2.3
> 
> I set `DART_DEFINES = TVlfTkFNRT1tbzV0b25lCg==` in my xcconfig
> 
> Build failed in `[CP-User] Run Flutter Build my_flutter Script` with error message below:
> 
> Logs
> Everything goes well, when I switch back to 1.22.6 and set `DART_DEFINES = MY_NAME%3Dmo5tone` in xcconfig.

Just figure out how to fix this weird error, record here for others meet same issues.

`openssl base64 -d <<< TVlfTkFNRT1tbzV0b25lCg==` and `openssl base64 -d <<< TVlfTkFNRT1tbzV0b25l` output same result except the first one end with a trailing newline.

After removing trailing newline, everything goes well.
