### ISSUE TITLE
[Win32]:Crash windows application when use accents in keyboard

### ISSUE THREAD

**Issue by marcoprodata** [flutter/flutter#88108]
## Steps to Reproduce

When use accents as áéâôãõ the windows application crash

**Comment by marcoprodata** [comment]
The problem persist:

Launching lib\main.dart on Windows in debug mode...
Connecting to VM Service at ws://127.0.0.1:62496/4YmUjznNKQo=/ws
[ERROR:flutter/shell/common/shell.cc(93)] Dart Unhandled Exception: FormatException: Overlong encoding (at offset 1), stack trace: #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1788:7)
#1      Utf8Decoder.convert (dart:convert/utf.dart:318:42)
#2      PlatformDispatcher._unpackKeyData (dart:ui/platform_dispatcher.dart:397:71)
#3      PlatformDispatcher._dispatchKeyData (dart:ui/platform_dispatcher.dart:378:7)
#4      _dispatchKeyData (dart:ui/hooks.dart:104:31)
Unable to parse JSON message:
The document is empty.

════════ Exception caught by services library ══════════════════════════════════
The following RangeError was thrown during a platform message callback:
Invalid value: Not in inclusive range 0..1114111: 2147483828

When the exception was thrown, this was the stack
#0      new String.fromCharCode (dart:core-patch/string_patch.dart:45:5)
#1      new RawKeyEvent.fromMessage
#2      KeyEventManager.handleRawKeyMessage
#3      BasicMessageChannel.setMessageHandler.<anonymous closure>
#4      BasicMessageChannel.setMessageHandler.<anonymous closure>
#5      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>
#6      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>
#7      _invoke2.<anonymous closure> (dart:ui/hooks.dart:205:15)
#11     _invoke2 (dart:ui/hooks.dart:204:10)
#12     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#13     _Channel.push (dart:ui/channel_buffers.dart:132:31)
#14     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#15     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:544:22)
#16     _dispatchPlatformMessage (dart:ui/hooks.dart:92:31)
(elided 3 frames from dart:async)
════════════════════════════════════════════════════════════════════════════════
Lost connection to device.
Exited (sigterm)
