### ISSUE TITLE
flutter test --coverage is sporadically failing on M1 "hell: rosetta error: unexpectedly got a signal in sigtramp" 

### ISSUE THREAD

**Issue by nohli** [flutter/flutter#88106]
Our tests on M1 are often failing.

It only happens when using `--coverage`.

Unfortunately, the code is not open source, so I can't paste samples.

## Steps to Reproduce

1. Run `flutter test --coverage`.
2. Try a few times, it doesn't fail every time (about 30%, and we have a lot of tests).

**Expected results:** 

Tests complete fine.

**Actual results:** 
```
hell: rosetta error: unexpectedly got a signal in sigtramp
unhandled error during test:
(removed path)
Shell subprocess crashed with unexpected exit code -5.
#0      FlutterTesterTestDevice.finished (package:flutter_tools/src/test/flutter_tester_device.dart:224:73)
<asynchronous suspension>
#1      StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart)
<asynchronous suspension>

unhandled error during finalization of test:
(removed path)
TestDeviceException(Shell subprocess crashed with unexpected exit code -5.)
#0      FlutterTesterTestDevice.finished (package:flutter_tools/src/test/flutter_tester_device.dart:224:5)
<asynchronous suspension>
#1      StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart)
<asynchronous suspension>
```

**Comment by maheshmnj** [comment]
Hi @nohli, Thanks for filing the issue, Please share the output of `flutter doctor -v`. I ran the counter app tests with the coverage multiple times and that seems to work fine (100% of the time), since the issue is intermittent it would be great if you could share a [minimal reproducible code sample.](https://stackoverflow.com/help/minimal-reproducible-example)

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-arm, locale en-GB)
    • Flutter version 2.2.3 at /Users/mahesh/Documents/flutter
    • Framework revision f4abaa0735 (4 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile)                       • android-arm64  • Android 11 (API 30)
    • iPhone 12 Pro Max (mobile) • 6A434744-B348-4FB3-AB10-131292174456 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 11.4 20F71 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 92.0.4515.107

• No issues found!
```

</details>


Thanks.

**Comment by nohli** [comment]
@maheshmnj added flutter doctor.

You mean some code plus the corresponding tests are necessary?

**Comment by maheshmnj** [comment]
Yes, please if you could share it that would be helpful to debug the issue.

**Comment by nohli** [comment]
Unfortunately, we can't disclose internal code.
Finding a minimal code sample to reproduce the issue hasn't been successful yet.

This issue happens on three different M1 MacBooks.

**Comment by maheshmnj** [comment]
Keeping this issue open for further investigation from the team.

**Comment by nohli** [comment]
@maheshmnj thank you.

More logs:

```
  Shell subprocess crashed with unexpected exit code -5.
  package:flutter_tools/src/test/flutter_tester_device.dart 224:73  FlutterTesterTestDevice.finished
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1279:19                                      _CustomZone.registerCallback
  dart:async/zone.dart 1201:22                                      _CustomZone.bindCallbackGuarded
  dart:async/zone.dart 1311:19                                      _CustomZone.scheduleMicrotask
  dart:async/future_impl.dart 605:11                                Future._asyncCompleteError
  dart:async/future_impl.dart 50:12                                 _AsyncCompleter._completeError
  dart:async/future_impl.dart 33:5                                  _Completer.completeError
  package:flutter_tools/src/test/flutter_platform.dart 645:17       _FlutterPlatformStreamSinkWrapper.close.<fn>
  dart:async/zone.dart 1362:47                                      _rootRunUnary
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1286:19                                      _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 45:22                           _asyncThenWrapperHelper
  package:flutter_tools/src/test/flutter_platform.dart 378:36       FlutterPlatform.loadChannel
  package:flutter_tools/src/test/flutter_platform.dart 342:44       FlutterPlatform.load
  package:test_core/src/runner/loader.dart 224:38                   Loader.loadFile.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1286:19                                      _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 45:22                           _asyncThenWrapperHelper
  package:test_core/src/runner/loader.dart                          Loader.loadFile.<fn>
  package:test_core/src/runner/load_suite.dart 97:31                new LoadSuite.<fn>.<fn>
  package:test_core/src/runner/load_suite.dart 96:17                new LoadSuite.<fn>.<fn>
  package:test_core/src/runner/load_suite.dart 107:8                new LoadSuite.<fn>
  package:test_api/src/backend/invoker.dart 231:15                  Invoker.waitForOutstandingCallbacks.<fn>
  package:test_api/src/backend/invoker.dart 228:14                  Invoker.waitForOutstandingCallbacks.<fn>
  dart:async/zone.dart 1354:13                                      _rootRun
  dart:async/zone.dart 1258:19                                      _CustomZone.run
  dart:async/zone.dart 1789:10                                      _runZoned
  dart:async/zone.dart 1711:10                                      runZoned
  package:test_api/src/backend/invoker.dart 228:5                   Invoker.waitForOutstandingCallbacks
  package:test_api/src/backend/invoker.dart 383:17                  Invoker._onRun.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1286:19                                      _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 45:22                           _asyncThenWrapperHelper
  package:test_api/src/backend/invoker.dart                         Invoker._onRun.<fn>.<fn>.<fn>
  dart:async/zone.dart 1354:13                                      _rootRun
  dart:async/zone.dart 1258:19                                      _CustomZone.run
  dart:async/zone.dart 1789:10                                      _runZoned
  dart:async/zone.dart 1711:10                                      runZoned
  package:test_api/src/backend/invoker.dart 370:9                   Invoker._onRun.<fn>.<fn>
  dart:async/zone.dart 1354:13                                      _rootRun
  dart:async/zone.dart 1258:19                                      _CustomZone.run
  dart:async/zone.dart 1789:10                                      _runZoned
  dart:async/zone.dart 1711:10                                      runZoned
  package:test_api/src/backend/invoker.dart 150:7                   Invoker.guard
  package:test_api/src/backend/invoker.dart 413:15                  Invoker._guardIfGuarded
  package:test_api/src/backend/invoker.dart 369:7                   Invoker._onRun.<fn>
  package:stack_trace/src/chain.dart 94:24                          Chain.capture.<fn>
  dart:async/zone.dart 1354:13                                      _rootRun
  dart:async/zone.dart 1258:19                                      _CustomZone.run
  dart:async/zone.dart 1789:10                                      _runZoned
  dart:async/zone.dart 1711:10                                      runZoned
  package:stack_trace/src/chain.dart 92:12                          Chain.capture
  package:test_api/src/backend/invoker.dart 368:11                  Invoker._onRun
  package:test_api/src/backend/live_test_controller.dart 153:11     LiveTestController.run
  dart:async/future.dart 198:37                                     new Future.microtask.<fn>
  dart:async/zone.dart 1346:47                                      _rootRun
  dart:async/zone.dart 1258:19                                      _CustomZone.run
  dart:async/zone.dart 1162:7                                       _CustomZone.runGuarded
  dart:async/zone.dart 1202:23                                      _CustomZone.bindCallbackGuarded.<fn>
  dart:async/zone.dart 1354:13                                      _rootRun
  dart:async/zone.dart 1258:19                                      _CustomZone.run
  dart:async/zone.dart 1162:7                                       _CustomZone.runGuarded
  dart:async/zone.dart 1202:23                                      _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 40:21                          _microtaskLoop
  dart:async/schedule_microtask.dart 49:5                           _startMicrotaskLoop
  dart:isolate-patch/isolate_patch.dart 120:13                      _runPendingImmediateCallback
  dart:isolate-patch/isolate_patch.dart 185:5                       _RawReceivePortImpl._handleMessage
```

**Comment by jeroen-meijer** [comment]
I'm having this issue as well, and is preventing me from running coverage on larger projects. 😞

Willing to provide any logs or data you need to debug the issue! 👍🏻
Tried it myself but to no avail, unfortunately.

**Comment by rmRizki** [comment]
Any solution for this issue?

**Comment by chinmaygarde** [comment]
cc @jmagman

**Comment by jmagman** [comment]
The exiting process is the engine output `flutter_tester` executable.  I'm not sure what "hell" is (in this context 😛 ) or what signal could be unexpected, or anything about what's happening in the bowels of `sigtramp`.  Hopefully Apple fixes whatever is going on here in a future update.

I suspect all we can do here is to add an ARM slice to `flutter_tester` so it doesn't use Rosetta. https://github.com/flutter/flutter/issues/84453.  

\cc @zanderso

**Comment by JigneshPatel23** [comment]
same issue here and I need to run tests with coverage multiple times to get success once in while by luck.. 

```
Shell subprocess crashed with unexpected exit code -5.
#0      FlutterTesterTestDevice.finished
(package:flutter_tools/src/test/flutter_tester_device.dart:224:73)
<asynchronous suspension>
#1      StackZoneSpecification._registerUnaryCallback.<anonymous closure>
(package:stack_trace/src/stack_zone_specification.dart)
<asynchronous suspension>
```

**Comment by kjawadDeveloper1** [comment]
Any update on it?

**Comment by kjawadDeveloper1** [comment]
Any update from Flutter team? I have to setup a linux server just to run my tests.

**Comment by semsturgut** [comment]
same here on m1 macbook pro

**Comment by komangsidhiartha** [comment]
In my case, the successful case is the one that intermittent 🤣 
the test was/is (still) mostly fail

just saying and imprint to the thread in case there are fix in the future

thank you.
