### ISSUE TITLE
[BUG] throws Unexpected null value when using Scrollbar isAlwaysShown: true

### ISSUE THREAD

**Issue by KristianBalaj** [flutter/flutter#88110]
The problem occurs in the following setup - using the Navigator and the Pages API, when the page with the isAlwaysShown Scrollbar is before any other page.
The page on its own in the stack is not throwing.

**Minimal working example:**

<details> 
<summary>code snippet</summary> 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(App());
}

class APage extends Page<void> {
  @override
  Route<void> createRoute(BuildContext context) => PageRouteBuilder(
        settings: this,
        pageBuilder: (_, __, ___) {
          final scrollCtrl = ScrollController();

          return Scrollbar(
            isAlwaysShown: true,
            controller: scrollCtrl,
            child: SingleChildScrollView(
              controller: scrollCtrl,
              child: Text('Hello there'),
            ),
          );
        },
      );
}

class BPage extends Page<void> {
  @override
  Route<void> createRoute(BuildContext context) => PageRouteBuilder(
        settings: this,
        pageBuilder: (_, __, ___) => Text('B'),
      );
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Navigator(
          pages: [APage(), BPage()],
          onPopPage: (route, dynamic result) {
            return false;
          },
        ),
      ),
    );
  }
}
```

</details>

**Exception:**

<details>
<summary>console</summary> 

```console
The following TypeErrorImpl was thrown during a scheduler callback:
Unexpected null value.

When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 236:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 518:63  nullCheck
packages/flutter/src/widgets/scroll_metrics.dart 150:49                           get maxScrollExtent
packages/flutter/src/widgets/scrollbar.dart 1206:16                               [_handleScrollNotification]
packages/flutter/src/widgets/notification_listener.dart 206:27                    [_dispatch]
...
```

</details>

<details> 
<summary>flutter doctor -v</summary> 

```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5 20G71 darwin-x64, locale en-GB)
    • Flutter version 2.2.3 at /Users/kristian/Documents/flutter
    • Framework revision f4abaa0735 (6 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/kristian/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-15.0.2.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 15.0.2+7-27)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
```

</details>

**Comment by darshankawar** [comment]
Thanks for the detailed report and code sample. I see the same behavior on latest stable.

<details>
<summary>console error log</summary>


```
======== Exception caught by scheduler library =====================================================
The following _CastError was thrown during a scheduler callback:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      FixedScrollMetrics.maxScrollExtent (package:flutter/src/widgets/scroll_metrics.dart:150:49)
#1      RawScrollbarState._handleScrollNotification (package:flutter/src/widgets/scrollbar.dart:1206:17)
#2      NotificationListener._dispatch (package:flutter/src/widgets/notification_listener.dart:206:42)
#3      Notification.visitAncestor (package:flutter/src/widgets/notification_listener.dart:122:20)
#4      ViewportNotificationMixin.visitAncestor (package:flutter/src/widgets/scroll_notification.dart:31:18)
...
====================================================================================================

```


</details>

<details>
<summary> flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.2.3 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision f4abaa0735 (4 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dhs/Library/Android/sdk
    • Java binary at: /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.    

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • SM G975F (mobile) • RZ8M802WY0X • android-arm64 • Android 10 (API 29)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 91.0.4472.114

• No issues found!





```

</details>

**Comment by xu-baolin** [comment]
This should be fixed on the master branch, we did not request the empty scroll event now.
I have test this on the master branch, it works well now.
 CC @Piinks

**Comment by Piinks** [comment]
I have run this sample code against the master branch, and have not seen the crash. I actually do not see anything when running this sample code. I believe it is fixed though as @xu-baolin mentioned we no longer request an empty scroll event due to recent changes.

**Comment by KristianBalaj** [comment]
Well, it's already solved then.
Looking forward for it to reach stable.

**Comment by Piinks** [comment]
Ok, I am going to close this issue then. Thank you!
