### ISSUE TITLE
ReorderableListView can't cope with dragging with two fingers simultaneously and breaks the app

### ISSUE THREAD

**Issue by wujek-srujek** [flutter/flutter#88191]
## Steps to Reproduce

Using the very basic code:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(SampleApp());
}

class SampleApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      darkTheme: ThemeData.dark(),
      themeMode: ThemeMode.dark,
      home: Scaffold(
        body: SafeArea(
          child: SampleList(),
        ),
      ),
    );
  }
}

class SampleList extends StatefulWidget {
  @override
  _SampleListState createState() => _SampleListState();
}

class _SampleListState extends State<SampleList> {
  final items = [
    'AAAAA',
    'BBBBB',
    'CCCCC',
  ];

  @override
  Widget build(BuildContext context) {
    return ReorderableListView.builder(
      itemCount: items.length,
      onReorder: (oldIndex, newIndex) {
        final movedItem = items.removeAt(oldIndex);
        final insertionIndex = newIndex > oldIndex ? newIndex - 1 : newIndex;
        items.insert(insertionIndex, movedItem);
        setState(() {});
      },
      itemBuilder: (context, index) {
        final item = items[index];

        return ListTile(
          key: ObjectKey(item),
          title: Text(item),
        );
      },
    );
  }
}
```
0. Reproducible 100% here on Android and iOS devices in release mode.
1. Run it using `flutter run --release` on a device. **This is very important, use the release mode.**
2. Drag and drop any item in the list using just one finger - all works fine.
3. Drag and drop any item in the list using two fingers on the same item - the UI breaks in different weird ways - sometimes items disappear, sometimes the list gets covered with a whitish overlay (easily visible in dark mode hence the sample app uses it), sometimes there is a huge gap between items after dropping, sometimes the app gets completely broken and cannot be used any more. Try a few times.

**Expected results:**

I expect the list not to break. I don't actually need the 'two finger drag' for anything, I just came across this issue by accident and I think it should break the app beyond recovery.

**Actual results:**

The UI breaks in different weird ways - sometimes items disappear, sometimes the list gets covered with a whitish overlay (easily visible in dark mode hence the sample app uses it), sometimes there is a huge gap between items after dropping, sometimes the app gets completely broken and cannot be used any more.

<details>
  <summary>Logs</summary>

When run in release mode on Pixel 3XL (I don't see any errors on iOS in release mode), this gets thrown:
```
I/flutter (22963): Null check operator used on a null value
I/flutter (22963): #0      SliverReorderableListState._dropCompleted (package:flutter/src/widgets/reorderable_list.dart:643)
I/flutter (22963): #1      _DragInfo._dropCompleted (package:flutter/src/widgets/reorderable_list.dart:1163)
I/flutter (22963): #2      _DragInfo.startDrag.<anonymous closure> (package:flutter/src/widgets/reorderable_list.dart:1134)
I/flutter (22963): #3      AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:199)
I/flutter (22963): #4      AnimationController._checkStatusChanged (package:flutter/src/animation/animation_controller.dart:812)
I/flutter (22963): #5      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:828)
I/flutter (22963): #6      Ticker._tick (package:flutter/src/scheduler/ticker.dart:238)
I/flutter (22963): #7      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144)
I/flutter (22963): #8      SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1058)
I/flutter (22963): #9      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397)
I/flutter (22963): #10     SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1056)
I/flutter (22963): #11     SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:977)
I/flutter (22963): #15     _invoke1 (dart:ui/hooks.dart:182)
I/flutter (22963): #16     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:237)
I/flutter (22963): #17     _beginFrame (dart:ui/hooks.dart:114)
I/flutter (22963): (elided 3 frames from dart:async)
```

When run in debug mode on Pixel 3XL or iPhone XS:
```
══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/reorderable_list.dart': Failed assertion: line 579 pos 12: '_dragInfo
== null': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack:
#2      SliverReorderableListState._dragStart (package:flutter/src/widgets/reorderable_list.dart:579:12)
#3      MultiDragGestureRecognizer._startDrag.<anonymous closure> (package:flutter/src/gestures/multidrag.dart:277:61)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#5      MultiDragGestureRecognizer._startDrag (package:flutter/src/gestures/multidrag.dart:277:14)
#6      MultiDragGestureRecognizer.acceptGesture.<anonymous closure> (package:flutter/src/gestures/multidrag.dart:267:48)
#7      _DelayedPointerState.accepted (package:flutter/src/gestures/multidrag.dart:496:14)
#8      MultiDragGestureRecognizer.acceptGesture (package:flutter/src/gestures/multidrag.dart:267:11)
#9      GestureArenaManager._resolveInFavorOf (package:flutter/src/gestures/arena.dart:264:12)
#10     GestureArenaManager._resolve (package:flutter/src/gestures/arena.dart:223:9)
#11     GestureArenaEntry.resolve (package:flutter/src/gestures/arena.dart:53:12)
#12     MultiDragPointerState.resolve (package:flutter/src/gestures/multidrag.dart:69:18)
#13     _DelayedPointerState._delayPassed (package:flutter/src/gestures/multidrag.dart:482:7)
(elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)

Handler: "onStart"
Recognizer:
  DelayedMultiDragGestureRecognizer#d4638
════════════════════════════════════════════════════════════════════════════════════════════════════
```

`flutter analyze` output:
```
Analyzing sample_app...                                                    
No issues found! (ran in 5.2s)
```

`flutter doctor` output:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 2.2.3, on macOS 11.5.2 20G95 darwin-x64, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[!] Android Studio (version 2020.3)
    ✗ Unable to find bundled Java version.
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
[✓] VS Code (version 1.59.0)
[✓] Connected device (4 available)

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment]
Thanks for detailed report and code sample. I see the same behavior on latest stable and master.

1. In release mode, trying to use two fingers to drag and drop results in screen going grey as below:

<img width="347" alt="Screenshot 2021-08-16 at 2 22 02 PM" src="https://user-images.githubusercontent.com/67046386/129537441-55ef552b-17ca-4e0a-8718-e42642c3ffbe.png">

2. In debug mode, trying to use two fingers to drag and drop results in below error log in the console:

<details>
<summary>console error log</summary>


```
══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/reorderable_list.dart': Failed assertion: line 625 pos 12: '_dragInfo
== null': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack:
#2      SliverReorderableListState._dragStart (package:flutter/src/widgets/reorderable_list.dart:625:12)
#3      MultiDragGestureRecognizer._startDrag.<anonymous closure> (package:flutter/src/gestures/multidrag.dart:295:61)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
#5      MultiDragGestureRecognizer._startDrag (package:flutter/src/gestures/multidrag.dart:295:14)
#6      MultiDragGestureRecognizer.acceptGesture.<anonymous closure> (package:flutter/src/gestures/multidrag.dart:285:48)
#7      _DelayedPointerState.accepted (package:flutter/src/gestures/multidrag.dart:547:14)
#8      MultiDragGestureRecognizer.acceptGesture (package:flutter/src/gestures/multidrag.dart:285:11)
#9      GestureArenaManager._resolveInFavorOf (package:flutter/src/gestures/arena.dart:264:12)
#10     GestureArenaManager._resolve (package:flutter/src/gestures/arena.dart:223:9)
#11     GestureArenaEntry.resolve (package:flutter/src/gestures/arena.dart:53:12)
#12     MultiDragPointerState.resolve (package:flutter/src/gestures/multidrag.dart:76:18)
#13     _DelayedPointerState._delayPassed (package:flutter/src/gestures/multidrag.dart:533:7)
(elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)

Handler: "onStart"
Recognizer:
  DelayedMultiDragGestureRecognizer#0e527
════════════════════════════════════════════════════════════════════════════════════════════════════



```


</details>

Above error is triggered as soon as two fingers are placed on the screen.

<details>
<summary> stable and master flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.2.3 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision f4abaa0735 (4 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dhs/Library/Android/sdk
    • Java binary at: /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.    

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • SM G975F (mobile) • RZ8M802WY0X • android-arm64 • Android 10 (API 29)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 91.0.4472.114

• No issues found!

[✓] Flutter (Channel master, 2.5.0-7.0.pre.83, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.5.0-7.0.pre.83 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 06be7e5392 (12 hours ago), 2021-08-15 14:37:02 -0400
    • Engine revision 1af0a20793
    • Dart version 2.15.0 (build 2.15.0-15.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dhs/Library/Android/sdk
    • Java binary at: /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.    

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • SM G975F (mobile) • RZ8M802WY0X • android-arm64 • Android 10 (API 29)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 91.0.4472.114






```

</details>
