### ISSUE TITLE
Android license status unknown should warn when the JDK version is incompatible

### ISSUE THREAD

**Issue by miyoyo** [flutter/flutter#88227]
On a fairly frequent basis, people come into the community flutter discord, and complain about this specific issue:

```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
        ... 5 more
```

This problem happens because the user's default Java install, or the Java install pointed to by JAVA_HOME, is not compatible with Android tooling.

Flutter doctor should detect the JDK that will be used, and, if incompatible, automatically inform users of this fact, and eventually recommend them troubleshooting steps, such as:
 - Point JAVA_HOME to the bundled JDK inside of Android Studio
 - Install JDK8, and update JAVA_HOME to point to it
 - Maybe a link to some JDK download, depending on the OS?

**Comment by reidbaker** [comment]
Updates since 2021, `flutter doctor -v` prints the version of java. We default to the version of java installed in android studio, there is a config you can set to modify the version of java flutter uses for your project, `flutter analyse --suggestions` can let you know about agp, java, and gradle compatibility, a pr is up for warning in flutter create when the installed java version does not match the templates https://github.com/flutter/flutter/issues/130515.
