### ISSUE TITLE
UTF8 encoding error when running against android physical devices

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#8822]
## Steps to Reproduce

*Note*: This only repros against a physical Android device, not against the emulator

1. Plug in a physical android device (I used a Nexus 5X)

2. Run these commands:
```
flutter create repro
cd repro
flutter run
```

=>

```
Launching lib/main.dart on Nexus 5X in debug mode...
Running 'gradle assembleDebug'...                        /Unhandled exception:
FormatException: Bad UTF-8 encoding 0xff (at offset 369)
#0      _Utf8Decoder.convert (dart:convert/utf.dart:565)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:333)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:329)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:92)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#5      _rootRunUnary (dart:async/zone.dart:1158)
#6      _CustomZone.runUnary (dart:async/zone.dart:1037)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:932)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#10     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#11     _StreamController._add (dart:async/stream_controller.dart:635)
#12     _StreamController.add (dart:async/stream_controller.dart:581)
#13     _Socket._onData (dart:io-patch/socket_patch.dart:1678)
#14     _rootRunUnary (dart:async/zone.dart:1162)
#15     _CustomZone.runUnary (dart:async/zone.dart:1037)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:932)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#19     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#20     _StreamController._add (dart:async/stream_controller.dart:635)
#21     _StreamController.add (dart:async/stream_controller.dart:581)
#22     _RawSocket._RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1245)
#23     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:779)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

## Logs

```
[        ] Building APK
[   +8 ms] Using gradle from /Applications/Android Studio.app/Contents/gradle/gradle-3.2/bin/gradle.
[   +1 ms] Running 'gradle assembleDebug'...
[        ] [android/] /Applications/Android Studio.app/Contents/gradle/gradle-3.2/bin/gradle -Ptarget=/Users/mit/tmp/repro5/lib/main.dart assembleDebug
Unhandled exception:
FormatException: Bad UTF-8 encoding 0xff (at offset 369)
```

**Comment by nanowang** [comment]
Verified same issue on Pixel.

```
Launching lib/main.dart on Pixel in release mode...
Running 'gradle assembleRelease'...                      /Unhandled exception:
FormatException: Bad UTF-8 encoding 0xff (at offset 4896)
#0      _Utf8Decoder.convert (dart:convert/utf.dart:565)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:333)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:329)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:92)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#5      _rootRunUnary (dart:async/zone.dart:1158)
#6      _CustomZone.runUnary (dart:async/zone.dart:1037)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:932)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#10     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#11     _StreamController._add (dart:async/stream_controller.dart:635)
#12     _StreamController.add (dart:async/stream_controller.dart:581)
#13     _Socket._onData (dart:io-patch/socket_patch.dart:1678)
#14     _rootRunUnary (dart:async/zone.dart:1162)
#15     _CustomZone.runUnary (dart:async/zone.dart:1037)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:932)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#19     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#20     _StreamController._add (dart:async/stream_controller.dart:635)
#21     _StreamController.add (dart:async/stream_controller.dart:581)
#22     _RawSocket._RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1245)
#23     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:779)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by mit-mit** [comment]
This appears to be fixed in todays build (which contains a new Dart SDK rolled yesterday).

**Comment by mit-mit** [comment]
@nanowang can you try to run `flutter upgrade` and see if that also fixes it for you?

**Comment by nanowang** [comment]
@mit-mit Yep, thanks!
