### ISSUE TITLE
Exception caught by animation libraryException caught by animation library

### ISSUE THREAD

**Issue by Myepick** [flutter/flutter#88238]
```
The following assertion was thrown while notifying listeners for AnimationController:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4210 pos 12: '_lifecycleState != _ElementLifecycle.defunct': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4210:12)
#3      State.setState (package:flutter/src/widgets/framework.dart:1108:15)
#4      TouchZoomTextViewState.initState.<anonymous closure> (package:kids_learn/Views/TouchZoomTextView.dart:51:7)
#5      AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:155:19)
#6      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:829:5)
...
The AnimationController notifying listeners was: AnimationController#6f6ca(⏮ 0.000; paused)
```

<details>
<summary>code sample</summary>

```
import 'package:flutter/material.dart';
import 'package:kids_learn/Utils/SizeConfing.dart';
import 'package:kids_learn/Utils/TTSPlayer.dart';
import 'package:vector_math/vector_math_64.dart' hide Colors;

class TouchZoomTextView extends StatefulWidget {
  String text;
  TTSPlayer player;
GlobalKey<TouchZoomTextViewState> key;
  TouchZoomTextView( { required this.text,  required this.key ,required this.player,}):super(key: key);

  @override
  State<StatefulWidget> createState() {
    return  TouchZoomTextViewState(text, player);
  }
}



class TouchZoomTextViewState extends State<TouchZoomTextView>
    with SingleTickerProviderStateMixin{
  MaterialColor? color;
  String text;
  TTSPlayer player;
  TouchZoomTextViewState(this.text, this.player);

  late Animation animation;
  late AnimationController animationController;


  @override
  void initState() {
    animationController = AnimationController(
        vsync: this, duration: Duration(milliseconds: 500));

    animation = Tween(begin: 1.0, end: 3.0)
        .animate(
        CurvedAnimation(
            parent: animationController,
            curve: Curves.linear));

    animation.addListener(() {
      if (animationController.isCompleted) {
        animationController.reverse();
      }
      setState(() {

      });
    });
    animationController.addListener(() {
      setState(() {
        if (animationController.isCompleted) {
          animationController.reverse();
        }
      });
    });
    super.initState();
  }


  @override
  Widget build(BuildContext context) {
    _setColor();
    return Center(
      child: InkWell(
        onTap: () {
          playSound();
        },
        child: Transform(
          transform: Matrix4.diagonal3(
              Vector3(animation.value, animation.value, animation.value)),

          child: FittedBox(
            child: Text(text,
                style: TextStyle(
                  fontSize: 9 * SizeConfig.textMultiplier,
                  fontWeight: FontWeight.w900,
                  color: color!.shade400,
                  fontFamily: "nor",
                  shadows: [
                    Shadow(
                      color: color!.shade900, //color.withAlpha(700),
                      offset: Offset(0, 0),
                      blurRadius: 1,
                    ),
                    Shadow(
                      color: color!.shade900, //color.withAlpha(700),
                      offset: Offset(-1, -1),
                      blurRadius: 1,
                    ),
                    Shadow(
                      color: color!.shade900, //color.withAlpha(700),
                      offset: Offset(1, 1),
                      blurRadius: 1,
                    ),
                  ],
                )),
          ),

      ),
      ),
    );
  }

  void _setColor() {
    switch (text.toLowerCase()) {
      case "a":
        color = Colors.red;
        break;
      case "b":
        color = Colors.blue;
        break;
      case "c":
        color = Colors.brown;
        break;
      case "d":
        color = Colors.purple;
        break;
      case "e":
        color = Colors.yellow;
        break;
      case "f":
        color = Colors.pink;
        break;

    //line2

      case "i":
        color = Colors.indigo;
        break;
      case "h":
        color = Colors.deepOrange;
        break;
      case "j":
        color = Colors.green;
        break;
      case "k":
        color = Colors.cyan;
        break;
      case "l":
        color = Colors.purple;
        break;
      case "g":
        color = Colors.amber;
        break;

//line 3

      case "m":
        color = Colors.blue;
        break;
      case "n":
        color = Colors.brown;
        break;
      case "o":
        color = Colors.green;
        break;
      case "p":
        color = Colors.blue;
        break;
      case "q":
        color = Colors.purple;
        break;
      case "r":
        color = Colors.yellow;
        break;

    ///4

      case "s":
        color = Colors.cyan;
        break;
      case "t":
        color = Colors.deepOrange;
        break;
      case "u":
        color = Colors.indigo;
        break;
      case "v":
        color = Colors.purple;
        break;
      case "w":
        color = Colors.pink;
        break;
      case "x":
        color = Colors.brown;
        break;

    ///5

      case "y":
        color = Colors.purple;
        break;
      case "z":
        color = Colors.blue;
        break;
    }
  }

  void playSound() {
    animationController.forward();
    player.speak(text.toLowerCase());

  }

  @override
  void dispose() {
   // _animationController.dispose();
    super.dispose();
  }


}


////////////////////////////////////////////

import 'dart:async';

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_tts/flutter_tts.dart';
import 'package:kids_learn/Utils/TTSPlayer.dart';
import 'package:kids_learn/Views/AnimatedRoundButton.dart';
import 'package:kids_learn/Views/PlayButtonShape.dart';
import 'package:kids_learn/Views/TouchZoomTextView.dart';

class AlfabatesReadActivity extends StatefulWidget {
  String abcd;

  AlfabatesReadActivity({Key? key, required this.abcd}) : super(key: key);

  @override
  _AlfabatesReadActivityState createState() =>
      _AlfabatesReadActivityState(abcd);
}

class _AlfabatesReadActivityState extends State<AlfabatesReadActivity> {
  bool isPlaying = false;
  TTSPlayer player = new TTSPlayer();
  late _AlfabatesReadActivityState activity;

  TouchZoomTextView? ta,
      tb,
      tc,
      td,
      te,
      tf,
      tg,
      th,
      ti,
      tj,
      tk,
      tl,
      tm,
      tn,
      to,
      tp,
      tq,
      tr,
      ts,
      tt,
      tu,
      tv,
      tw,
      tx,
      ty,
      tz;

  String abcd;

  _AlfabatesReadActivityState(this.abcd);

  @override
  Widget build(BuildContext context) {
    activity = this;

    return Scaffold(
        body: Container(
      padding: EdgeInsets.only(top: 20),
      decoration: BoxDecoration(
          image: DecorationImage(
        image: AssetImage(
          "lib/images/bg_sky_1.jpg",
        ),
        fit: BoxFit.fill,
      )),
      child: Column(
        mainAxisAlignment: MainAxisAlignment.start,
        crossAxisAlignment: CrossAxisAlignment.stretch,
        verticalDirection: VerticalDirection.up,
        children: [
          Expanded(
            child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceAround,
                children: [
                  CustomPaint(
                    size: Size(50, 50),
                    //You can Replace [WIDTH] with your desired width for Custom Paint and height will be calculated automatically
                    painter: PlayButtonShape(Colors.indigo),
                    child: Container(
                        height: 50,
                        width: 50,
                        alignment: Alignment.center,
                        child: Text(
                          "Back",
                          style: TextStyle(
                              color: Colors.white, fontWeight: FontWeight.bold),
                        )),
                    willChange: false,
                  ), // button back

                  ty = _getTextView(abcd.substring(24, 25)),
                  tz = _getTextView(abcd.substring(25, 26)),
                  InkWell(
                      onTap: () {
                        playSounds(0);
                      },
                      child: AnimatedRoundButton())
                  // button play
                ]),
          ),
          Expanded(
            child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceAround,
                crossAxisAlignment: CrossAxisAlignment.center,
                children: [
                  ts = _getTextView(abcd.substring(18, 19)),
                  tt = _getTextView(abcd.substring(19, 20)),
                  tu = _getTextView(abcd.substring(20, 21)),
                  tv = _getTextView(abcd.substring(21, 22)),
                  tw = _getTextView(abcd.substring(22, 23)),
                  tx = _getTextView(abcd.substring(23, 24)),
                ]),
          ),
          Expanded(
            child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceAround,
                children: [
                  tm = _getTextView(abcd.substring(12, 13)),
                  tn = _getTextView(abcd.substring(13, 14)),
                  to = _getTextView(abcd.substring(14, 15)),
                  tp = _getTextView(abcd.substring(15, 16)),
                  tq = _getTextView(abcd.substring(16, 17)),
                  tr = _getTextView(abcd.substring(17, 18)),
                ]),
          ),
          Expanded(
            child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceAround,
                children: [
                  tg = _getTextView(abcd.substring(6, 7)),
                  th = _getTextView(abcd.substring(7, 8)),
                  ti = _getTextView(abcd.substring(8, 9)),
                  tj = _getTextView(abcd.substring(9, 10)),
                  tk = _getTextView(abcd.substring(10, 11)),
                  tl = _getTextView(abcd.substring(11, 12)),
                ]),
          ),
          Expanded(
            child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceAround,
                children: [
                  ta = _getTextView(abcd.substring(0, 1)),
                  tb = _getTextView(abcd.substring(1, 2)),
                  tc = _getTextView(abcd.substring(2, 3)),
                  td = _getTextView(abcd.substring(3, 4)),
                  te = _getTextView(abcd.substring(4, 5)),
                  tf = _getTextView(abcd.substring(5, 6)),
                ]),
          ),
        ],
      ),
    ));
  }

  @override
  void dispose() {
    // TODO: implement dispose
    super.dispose();
    player.stop();
  }

  TouchZoomTextView _getTextView(String text) {
    return TouchZoomTextView(
        text: text,
        key: new GlobalKey<TouchZoomTextViewState>(),
        player: player);
  }

  bool isSoundPlaying = false;

  playSounds(int cu) {
    if (isSoundPlaying && cu == 0) {
      setState(() {
        isSoundPlaying = false;
      });
      player.stop();
      return;
    }

    setState(() {
      isSoundPlaying = true;
    });
    Timer(Duration(milliseconds: (700)), () {
      m(cu);
      playSounds(cu + 1);
    });
  }

  void m(current) {
    switch (current) {
      case 0:
        ta!.key.currentState!.playSound();
        break;
      case 1:
        tb!.key.currentState!.playSound();
        break;
      case 2:
        tc!.key.currentState!.playSound();
        break;
      case 3:
        td!.key.currentState!.playSound();
        break;
      case 4:
        te!.key.currentState!.playSound();
        break;
      case 5:
        tf!.key.currentState!.playSound();
        break;
      case 6:
        tg!.key.currentState!.playSound();
        break;
      case 7:
        th!.key.currentState!.playSound();
        break;
      case 8:
        ti!.key.currentState!.playSound();
        break;
      case 9:
        tj!.key.currentState!.playSound();
        break;
      case 10:
        tk!.key.currentState!.playSound();
        break;
      case 11:
        tl!.key.currentState!.playSound();
        break;
      case 12:
        tm!.key.currentState!.playSound();
        break;
      case 13:
        tn!.key.currentState!.playSound();
        break;
      case 14:
        to!.key.currentState!.playSound();
        break;
      case 15:
        tp!.key.currentState!.playSound();
        break;
      case 16:
        tq!.key.currentState!.playSound();
        break;
      case 17:
        tr!.key.currentState!.playSound();
        break;
      case 18:
        ts!.key.currentState!.playSound();
        break;
      case 19:
        tt!.key.currentState!.playSound();
        break;
      case 20:
        tu!.key.currentState!.playSound();
        break;
      case 21:
        tv!.key.currentState!.playSound();
        break;
      case 22:
        tw!.key.currentState!.playSound();
        break;
      case 23:
        tx!.key.currentState!.playSound();
        break;
      case 24:
        ty!.key.currentState!.playSound();
        break;
      case 25:
        tz!.key.currentState!.playSound();
        break;
    }
  }
}

//typedef ClikCallback = void Function(GestureDetector detector);




```

</details>

**Comment by darshankawar** [comment]
@Myepick 
Whenever you file an issue, please provide in formatted text as updated above, so it helps to read the issue properly.
Also, provide `flutter doctor -v` and a truncated but [complete minimal code sample](https://stackoverflow.com/help/minimal-reproducible-example) without any 3rd party plugins that we can directly use to verify this issue.
Thanks.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
