### ISSUE TITLE
[image_picker] Android App crash after taking picture with camera

### ISSUE THREAD

**Issue by aawhitfield** [flutter/flutter#88231]
## Steps to Reproduce

1. call ```await _picker.pickImage(source: ImageSource.camera)```
2. Take a photo with the camera 
3. Select OK to accept photo
4. App exits

**Expected results:** App should have continued execution.

**Actual results:** Back to the Android home screen
<details>
  <summary>Logs</summary>

```[  +52 ms] D/AndroidRuntime( 9728): Shutting down VM
[   +1 ms] E/AndroidRuntime( 9728): FATAL EXCEPTION: main
[   +1 ms] E/AndroidRuntime( 9728): Process: us.binarychaos.med_rpm, PID: 9728
[        ] E/AndroidRuntime( 9728): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2343, result=-1, data=null} to activity
{us.binarychaos.med_rpm/us.binarychaos.med_rpm.MainActivity}: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method
kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter data
[   +1 ms] E/AndroidRuntime( 9728):     at android.app.ActivityThread.deliverResults(ActivityThread.java:5506)
[   +2 ms] E/AndroidRuntime( 9728):     at android.app.ActivityThread.handleSendResult(ActivityThread.java:5547)
[        ] E/AndroidRuntime( 9728):     at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
[        ] E/AndroidRuntime( 9728):     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
[        ] E/AndroidRuntime( 9728):     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
[        ] E/AndroidRuntime( 9728):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
[        ] E/AndroidRuntime( 9728):     at android.os.Handler.dispatchMessage(Handler.java:106)
[        ] E/AndroidRuntime( 9728):     at android.os.Looper.loop(Looper.java:246)
[        ] E/AndroidRuntime( 9728):     at android.app.ActivityThread.main(ActivityThread.java:8512)
[        ] E/AndroidRuntime( 9728):     at java.lang.reflect.Method.invoke(Native Method)
[        ] E/AndroidRuntime( 9728):     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
[        ] E/AndroidRuntime( 9728):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
[        ] E/AndroidRuntime( 9728): Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method
kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter data
[   +2 ms] E/AndroidRuntime( 9728):     at net.petleo.flutter_health.FlutterHealthPlugin.onActivityResult(Unknown Source:2)
[   +3 ms] E/AndroidRuntime( 9728):     at
io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:741)
[   +2 ms] E/AndroidRuntime( 9728):     at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:426)
[  +17 ms] E/AndroidRuntime( 9728):     at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:684)
[   +1 ms] E/AndroidRuntime( 9728):     at io.flutter.embedding.android.FlutterFragment.onActivityResult(FlutterFragment.java:863)
[        ] E/AndroidRuntime( 9728):     at io.flutter.embedding.android.FlutterFragmentActivity.onActivityResult(FlutterFragmentActivity.java:532)
[        ] E/AndroidRuntime( 9728):     at android.app.Activity.dispatchActivityResult(Activity.java:8541)
[   +1 ms] E/AndroidRuntime( 9728):     at android.app.ActivityThread.deliverResults(ActivityThread.java:5499)
[        ] E/AndroidRuntime( 9728):     ... 11 more
[  +12 ms] I/Process ( 9728): Sending signal. PID: 9728 SIG: 9
[ +296 ms] Service protocol connection closed.
[   +1 ms] Lost connection to device.
[   +3 ms] executing: C:\Users\aawhi\AppData\Local\Android\sdk\platform-tools\adb.exe -s R5CN70WPTEK forward --list

```

```No errors found. Just a bunch of info warnings about packages that have not migrated to null safety.
```

```[√] Flutter (Channel beta, 2.4.0-4.2.pre, on Microsoft Windows [Version 10.0.22000.132], locale en-US)
    • Flutter version 2.4.0-4.2.pre at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f18b9281c2 (3 weeks ago), 2021-07-22 14:08:30 -0700
    • Engine revision 844c29f42a
    • Dart version 2.14.0 (build 2.14.0-301.2.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\aawhi\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.2.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.59.0)
    • VS Code at C:\Users\aawhi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[√] Connected device (4 available)
    • SM N986U (mobile)           • R5CN70WPTEK   • android-arm64  • Android 11 (API 30)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 92.0.4515.131
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 92.0.902.73

• No issues found!

```

</details>

**Comment by maheshmnj** [comment]
Hi @aawhitfield, I see you are not using the latest stable channel could you please try switching to the latest stable channel and see if this fixes the issue using the latest `image_picker: ^0.8.3+2`.

switch to stable
```
flutter channel stable
flutter upgrade
flutter clean
```
If you still face the issue please share the updated output of `flutter doctor -v` along with the crash log.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-arm, locale en-GB)
    • Flutter version 2.2.3 at /Users/mahesh/Documents/flutter
    • Framework revision f4abaa0735 (4 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile)                       • android-arm64  • Android 11 (API 30)
    • iPhone 12 Pro Max (mobile) • 6A434744-B348-4FB3-AB10-131292174456 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 11.4 20F71 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 92.0.4515.107

• No issues found!
```

</details>

**Comment by aawhitfield** [comment]
```
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.22000.132], locale en-US)
    • Flutter version 2.2.3 at C:\src\flutter
    • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\aawhi\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.59.0)
    • VS Code at C:\Users\aawhi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[√] Connected device (3 available)
    • SM N986U (mobile) • R5CN70WPTEK • android-arm64  • Android 11 (API 30)
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 92.0.4515.131
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 92.0.902.73

• No issues found!

```


And I don't know how to access any crash logs but the console printed this at the time of the crash:
```
I/CameraManagerGlobal( 8386): Camera 20 facing CAMERA_FACING_BACK state now CAMERA_STATE_IDLE for client com.sec.android.app.camera API Level 2
I/SurfaceView( 8386): onWindowVisibilityChanged(4) false io.flutter.embedding.android.FlutterSurfaceView{13f2c79 V.E...... ........ 0,0-1080,2190} of ViewRootImpl@3228c72[MainActivity]
I/SurfaceControl( 8386): assignNativeObject: nativeObject = 0 Surface(name=null)/@0x403597e / android.view.SurfaceControl.readFromParcel:1115 android.view.IWindowSession$Stub$Proxy.relayout:1777 android.view.ViewRootImpl.relayoutWindow:8953 android.view.ViewRootImpl.performTraversals:3312 android.view.ViewRootImpl.doTraversal:2575 android.view.ViewRootImpl$TraversalRunnable.run:9916 android.view.Choreographer$CallbackRecord.run:1010 android.view.Choreographer.doCallbacks:809 android.view.Choreographer.doFrame:744 android.view.Choreographer$FrameDisplayEventReceiver.run:995 
I/SurfaceControl( 8386): assignNativeObject: nativeObject = 0 Surface(name=null)/@0x46c756c / android.view.SurfaceControl.readFromParcel:1115 android.view.IWindowSession$Stub$Proxy.relayout:1787 android.view.ViewRootImpl.relayoutWindow:8953 android.view.ViewRootImpl.performTraversals:3312 android.view.ViewRootImpl.doTraversal:2575 android.view.ViewRootImpl$TraversalRunnable.run:9916 android.view.Choreographer$CallbackRecord.run:1010 android.view.Choreographer.doCallbacks:809 android.view.Choreographer.doFrame:744 android.view.Choreographer$FrameDisplayEventReceiver.run:995 
I/ViewRootImpl@3228c72[MainActivity]( 8386): Relayout returned: old=(0,0,1080,2316) new=(0,0,1080,2316) req=(1080,2316)4 dur=7 res=0x1 s={false 0} ch=false fn=-1
D/AndroidRuntime( 8386): Shutting down VM
E/AndroidRuntime( 8386): FATAL EXCEPTION: main
E/AndroidRuntime( 8386): Process: us.binarychaos.med_rpm, PID: 8386
E/AndroidRuntime( 8386): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2343, result=-1, data=null} to activity {us.binarychaos.med_rpm/us.binarychaos.med_rpm.MainActivity}: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter data
E/AndroidRuntime( 8386): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5506)
E/AndroidRuntime( 8386): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5547)
E/AndroidRuntime( 8386): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime( 8386): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime( 8386): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime( 8386): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
E/AndroidRuntime( 8386): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 8386): 	at android.os.Looper.loop(Looper.java:246)
E/AndroidRuntime( 8386): 	at android.app.ActivityThread.main(ActivityThread.java:8512)
E/AndroidRuntime( 8386): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8386): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/AndroidRuntime( 8386): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
E/AndroidRuntime( 8386): Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter data
E/AndroidRuntime( 8386): 	at net.petleo.flutter_health.FlutterHealthPlugin.onActivityResult(Unknown Source:2)
E/AndroidRuntime( 8386): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:739)
E/AndroidRuntime( 8386): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:426)
E/AndroidRuntime( 8386): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:677)
E/AndroidRuntime( 8386): 	at io.flutter.embedding.android.FlutterFragment.onActivityResult(FlutterFragment.java:769)
E/AndroidRuntime( 8386): 	at io.flutter.embedding.android.FlutterFragmentActivity.onActivityResult(FlutterFragmentActivity.java:509)
E/AndroidRuntime( 8386): 	at android.app.Activity.dispatchActivityResult(Activity.java:8541)
E/AndroidRuntime( 8386): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5499)
E/AndroidRuntime( 8386): 	... 11 more
I/Process ( 8386): Sending signal. PID: 8386 SIG: 9
Lost connection to device.

```

**Comment by maheshmnj** [comment]
@aawhitfield I tried on Xiaomi k20 Pro (Android 11) and I was able to take pictures via camera. 
Could you please share your [minimal reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) along with the output of `flutter run -v`, The logs will be pretty long, so please share it as a file instead of pasting it.
 
And also what version of the image_picker plugin are you having issue with?


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-arm, locale en-GB)
    • Flutter version 2.2.3 at /Users/mahesh/Documents/flutter
    • Framework revision f4abaa0735 (4 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile)                       • android-arm64  • Android 11 (API 30)
    • iPhone 12 Pro Max (mobile) • 6A434744-B348-4FB3-AB10-131292174456 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 11.4 20F71 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 92.0.4515.107

• No issues found!
```

</details>

**Comment by sulthanalihsan** [comment]
any update?

**Comment by maheshmnj** [comment]
@sulthanalihsan I can't reproduce the issue, I will need more info as on which android device or androd version is the crash happening and possibly a minimal and complete code sample along with the output of `flutter run -v` to diagnose the issue.

Thanks

**Comment by yeiale-98** [comment]
The same thing happens to me, I am using a Xiaomi Redmi Note 9s Android 10 and when taking the photo it returns to the beginning of the application.

I'm with the latest stable version of flutter and version 0.8.4 of **image_picker**

$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.19042.1165], locale es-CO)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.2)
[√] VS Code (version 1.60.0)
[√] Connected device (2 available)
