### ISSUE TITLE
extendBodyBehindAppBar confuses defaultTabController

### ISSUE THREAD

**Issue by sobrienpdx** [flutter/flutter#88315]
I have a defaultTabController that programmatically determines it's length. The scaffold that contains the defaultTabController has an app bar. When the app bar has extendBodyBehindAppBar = true the defaultTabController gets confused and gives me this error message: 

```
The following assertion was thrown building TabBar(dirty, dependencies: [_LocalizationsScope-[GlobalKey#336ca], _InheritedTheme, _TabControllerScope], state: _TabBarState#6dd4e):
Controller's length property (2) does not match the number of tabs (3) present in TabBar's tabs property.

When the exception was thrown, this was the stack: 
#0      _TabBarState.build.<anonymous closure> (package:flutter/src/material/tabs.dart:1147:9)
#1      _TabBarState.build (package:flutter/src/material/tabs.dart:1153:6)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4612:27)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4495:15)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4667:11)
```

If I directly print defaultTabController.length and number of tabs they seem fine. Also the program seems to be working fine... ?

**Comment by darshankawar** [comment]
@sobrienpdx 
Can you provide `flutter doctor -v` and a [complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can use that shows this behavior ?
Thanks.

**Comment by sobrienpdx** [comment]
@darshankawar yes, please find a repro here: https://github.com/sobrienpdx/repro_tabController_bug

If you comment out `extendBodyBehindAppBar = true` it works great, but otherwise it gives you errors

**Comment by darshankawar** [comment]
@sobrienpdx 
Thanks for the repo, although I see that you are using below 3rd party plugins in it:

```
flutter_mobx: ^2.0.0
  mobx: ^2.0.1
  provider: ^5.0.0
```

Does the behavior persist without using any of above plugin code ? If so, could you update the repo and provide only the core code with which the issue persist ?
Thanks.

**Comment by tirth-patel-nc** [comment]
# Triage Report

I was **not** able to reproduce the issue using the provided code sample on either the `stable (3.29.3)` or `master (3.32.0-1.0.pre.494)` channels.

https://github.com/user-attachments/assets/a5cb5b50-8041-4cdb-aefe-f4720d1a86d8

I didn’t see any errors in the debug console. 💯 

<details>
<summary>Code Sample (Same as OP)</summary>

```dart
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

class Repro {
  var tabIcons = [
    Icon(Icons.directions_car, color: Colors.black),
    Icon(Icons.directions_transit, color: Colors.black),
    Icon(Icons.directions_bike, color: Colors.black),
  ];
}

void main() {
  runApp(Provider<Repro>.value(value: Repro(), child: TabBarDemo()));
}

class TabBarDemo extends StatefulWidget {
  const TabBarDemo({super.key});

  @override
  State<TabBarDemo> createState() => _TabBarDemoState();
}

class _TabBarDemoState extends State<TabBarDemo> {
  @override
  Widget build(BuildContext context) {
    var repro = Provider.of<Repro>(context);
    return MaterialApp(
      home: DefaultTabController(
        length: repro.tabIcons.length,
        child: Scaffold(
          // extendBodyBehindAppBar: true, // comment this out and the error goes away
          appBar: AppBar(
            backgroundColor: Colors.transparent,
            title: const Text('Tabs Demo'),
          ),
          body: Container(
            decoration: BoxDecoration(
              color: Colors.white,
              image: DecorationImage(
                image: AssetImage("assets/images/blue_clouds.jpg"),
                fit: BoxFit.cover,
                colorFilter: ColorFilter.mode(
                  Colors.black.withOpacity(.18),
                  BlendMode.dstATop,
                ),
              ),
            ),
            child: Stack(
              children: [
                TabsForRepro(),
                Align(
                  alignment: Alignment.bottomRight,
                  child: Padding(
                    padding: const EdgeInsets.all(58.0),
                    child: ElevatedButton(
                      child: Padding(
                        padding: const EdgeInsets.all(18.0),
                        child: Text(
                          "Add/Subtract tab",
                          style: TextStyle(fontSize: 40),
                        ),
                      ),
                      onPressed: () {
                        setState(() {
                          repro.tabIcons.add(
                            Icon(Icons.plus_one, color: Colors.black),
                          );
                        });
                      },
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

class TabsForRepro extends StatefulWidget {
  const TabsForRepro({super.key});

  @override
  State<TabsForRepro> createState() => _TabsForReproState();
}

class _TabsForReproState extends State<TabsForRepro> {
  @override
  Widget build(BuildContext context) {
    var repro = Provider.of<Repro>(context);
    return TabBar(tabs: [for (var icon in repro.tabIcons) Tab(icon: icon)]);
  }
}
```

</details>

<details>
  <summary>stable (3.29.3) - flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.29.3, on macOS 15.4.1 24E263 darwin-arm64, locale
    en-IN) [970ms]
    • Flutter version 3.29.3 on channel stable at
      /Users/tirthpatel/Development/flutter_stable/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ea121f8859 (4 weeks ago), 2025-04-11 19:10:07 +0000
    • Engine revision cf56914b32
    • Dart version 3.7.2
    • DevTools version 2.42.3

[✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0)
    [855ms]
    • Android SDK at /Users/tirthpatel/Library/Android/sdk
    • Platform android-36, build-tools 36.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on
      this machine.
      To manually set the JDK path, use: `flutter config
      --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13355223-b631.42)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.3) [556ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16E140
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [9ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.3) [9ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13355223-b631.42)

[✓] VS Code (version 1.99.3) [8ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available) [5.5s]
    • macOS (desktop)                 • macos                 • darwin-arm64   •
      macOS 15.4.1 24E263 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         •
      macOS 15.4.1 24E263 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript •
      Google Chrome 135.0.7049.115

[✓] Network resources [559ms]
    • All expected network resources are available.

• No issues found!
```

</details>

<details>
  <summary>master (3.32.0-1.0.pre.494) - flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 3.32.0-1.0.pre.494, on macOS 15.4.1 24E263 darwin-arm64, locale en-IN) [1,351ms]
    • Flutter version 3.32.0-1.0.pre.494 on channel master at /Users/tirthpatel/Development/flutter_master/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4ac6f4d711 (3 hours ago), 2025-05-11 19:38:27 -0700
    • Engine revision 4ac6f4d711
    • Dart version 3.9.0 (build 3.9.0-100.2.beta)
    • DevTools version 2.46.0

[✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0) [771ms]
    • Android SDK at /Users/tirthpatel/Library/Android/sdk
    • Emulator version 35.4.9.0 (build_id 13025442) (CL:N/A)
    • Platform android-36, build-tools 36.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13355223-b631.42)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.3) [432ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16E140
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [7ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.3) [7ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13355223-b631.42)

[✓] VS Code (version 1.100.0) [6ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.110.0

[✓] Connected device (2 available) [5.5s]
    • macOS (desktop) • macos  • darwin-arm64   • macOS 15.4.1 24E263 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 136.0.7103.93

[✓] Network resources [473ms]
    • All expected network resources are available.

• No issues found!
```

</details>
