### ISSUE TITLE
Flutter application for VSCode is not working

### ISSUE THREAD

**Issue by PragGawande** [flutter/flutter#88335]
```console
TypeError: dart.global.window.CanvasKitInit is not a function
    at http://localhost:58951/dart_sdk.js:175453:55
    at _RootZone.runUnary (http://localhost:58951/dart_sdk.js:38500:59)
    at _FutureListener.then.handleValue (http://localhost:58951/dart_sdk.js:33700:29)
    at handleValueCallback (http://localhost:58951/dart_sdk.js:34252:49)
    at Function._propagateToListeners (http://localhost:58951/dart_sdk.js:34290:17)
    at _Future.new.[_completeWithValue] (http://localhost:58951/dart_sdk.js:34138:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:58951/dart_sdk.js:34159:35)
    at Object._microtaskLoop (http://localhost:58951/dart_sdk.js:38767:13)
    at _startMicrotaskLoop (http://localhost:58951/dart_sdk.js:38773:13)
    at http://localhost:58951/dart_sdk.js:34506:9
Application finished.
```
I have installed VS code and flutter SDK for windows. Everything is installed properly.
```console
Flutter 2.5.0-7.0.pre.90 • channel master • https://github.com/flutter/flutter.git
Framework • revision 3216e9f169 (12 hours ago) • 2021-08-16 13:42:04 -0400
Engine • revision 9d33093d6b
Tools • Dart 2.15.0 (build 2.15.0-15.0.dev)

```
```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 2.5.0-7.0.pre.90, on Microsoft Windows [Version 10.0.19042.1110], locale en-US)  
[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[√] Chrome - develop for the web
[!] Android Studio (not installed)
[√] VS Code (version 1.59.0)
[√] VS Code, 64-bit edition
[√] Connected device (2 available)
```
The same application is working on my colleague's machine. But it is not working in my system.
Is it machine specific. Do I need to install anything or if anything is missing.

**Comment by TahaTesser** [comment]
Hi @PragGawande 
Is the issue only reproducible in VS Code? Have you tried terminal command `flutter run -v`?

Based on the error message, it looks like you're running a web app in canvaskit, see https://github.com/flutter/flutter/issues/79963,
Are you able to run the app in HTML renderer? `flutter run -d chrome  --web-renderer html`?

Just to be sure, I just tried the web app on the latest master in VS Code and terminal, there is no issue

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel master, 2.5.0-7.0.pre.83, on Microsoft Windows [Version 10.0.22000.132], locale en-US)
    • Flutter version 2.5.0-7.0.pre.83 at C:\Users\Taha\Code\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 06be7e5392 (2 days ago), 2021-08-15 14:37:02 -0400
    • Engine revision 1af0a20793
    • Dart version 2.15.0 (build 2.15.0-15.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Taha\Code\android-sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\android-sdk
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31605.320
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.59.0)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[✓] Connected device (5 available)
    • IN2011 (mobile)         • c9d8ee0c • android-arm64   • Android 11 (API 30)
    • Windows (desktop)       • windows  • windows-x64     • Microsoft Windows [Version 10.0.22000.132]
    • Windows (UWP) (desktop) • winuwp   • windows-uwp-x64 •
    • Chrome (web)            • chrome   • web-javascript  • Google Chrome 92.0.4515.159
    • Edge (web)              • edge     • web-javascript  • Microsoft Edge 92.0.902.67

• No issues found!
```

</details>

Thank you

**Comment by PragGawande** [comment]
issue resolved
