### ISSUE TITLE
[tool_crash] FileSystemException: FileSystemException: Cannot open file, path = '/tmp/flutter_tools.ZYXKPV/flutter_tool.VNZIGL/app.dill.incremental.dill' (OS Error: No such file or directory, errno = 2)

### ISSUE THREAD

**Issue by ggdream** [flutter/flutter#88413]
## Steps to Reproduce
flutter run --machine --start-paused -d linux --dart-define=flutter.inspector.structuredErrors=true --web-allow-expose-url --devtools-server-address http://127.0.0.1:9100/ --target lib/main.dart

**Expected results:** 
Run successfully
**Actual results:** 
Crash
<details>
  <summary>Logs</summary>

## command

flutter run --machine --start-paused -d linux --dart-define=flutter.inspector.structuredErrors=true --web-allow-expose-url --devtools-server-address http://127.0.0.1:9100/ --target lib/main.dart

## exception

FileSystemException: FileSystemException: Cannot open file, path = '/tmp/flutter_tools.ZYXKPV/flutter_tool.VNZIGL/app.dill.incremental.dill' (OS Error: No such file or directory, errno = 2)

```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.openSync (dart:io/file_impl.dart:479:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:539:18)
#3      ForwardingFile.readAsBytesSync (package:file/src/forwarding/forwarding_file.dart:88:43)
#4      ForwardingFile.readAsBytesSync (package:file/src/forwarding/forwarding_file.dart:88:43)
#5      StdoutHandler.handler (package:flutter_tools/src/compile.dart:123:53)
#6      _rootRunUnary (dart:async/zone.dart:1362:47)
#7      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#10     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#11     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#12     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#13     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#14     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:155:13)
#15     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:130:5)
#16     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#17     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#18     _rootRunUnary (dart:async/zone.dart:1362:47)
#19     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#21     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#22     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#23     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#24     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#25     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#26     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#27     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:317:20)
#28     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)
#29     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#30     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#31     _rootRunUnary (dart:async/zone.dart:1362:47)
#32     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#33     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#34     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#35     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#36     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#37     _StreamController._add (dart:async/stream_controller.dart:607:7)
#38     _StreamController.add (dart:async/stream_controller.dart:554:5)
#39     _Socket._onData (dart:io-patch/socket_patch.dart:2160:41)
#40     _rootRunUnary (dart:async/zone.dart:1370:13)
#41     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#42     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#43     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#44     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#45     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#46     _StreamController._add (dart:async/stream_controller.dart:607:7)
#47     _StreamController.add (dart:async/stream_controller.dart:554:5)
#48     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1696:33)
#49     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1208:14)
#50     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#51     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#52     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
#53     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale zh_CN.UTF-8)
    • Flutter version 2.2.3 at /usr/local/flutter
    • Framework revision f4abaa0735 (7 周前), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/moca/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /home/moca/Android/Sdk
    • Java binary at: /home/moca/software/jetbrains/apps/AndroidStudio/ch-0/203.7583922/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/moca/software/jetbrains/apps/AndroidStudio/ch-0/203.7583922
    • Flutter plugin version 59.0.2
    • Dart plugin version 203.8292
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.59.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 92.0.4515.159

• No issues found!
```

</details>

**Comment by ggdream** [comment]
I'm sure that it can run well on Windows desktop and Android.

**Comment by TahaTesser** [comment]
HI @ggdream 
The issue doesn't reproduce on PopOS 21.04, this looks like tool cache issue

**Comment by ggdream** [comment]
> HI @ggdream
> The issue doesn't reproduce on PopOS 21.04, this looks like tool cache issue

Excuse me, what should I do to resolve it?
