### ISSUE TITLE
Two list views in a split_view leads to "The provided ScrollController is currently attached to more than one ScrollPosition."

### ISSUE THREAD

**Issue by domesticmouse** [flutter/flutter#88428]
Trying to put two `ListView`s side by side using a `split_view` causes issues in the Flutter animation library when I attempt to scroll either list. I see the following behaviour with both [`split_view`](https://pub.dev/packages/split_view) and [`multi_split_view`](https://pub.dev/packages/multi_split_view) so I'm guessing it's a flutter issue. 

<details> 
<summary>logs</summary> 
	
```console
══╡ EXCEPTION CAUGHT BY ANIMATION LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown while notifying status listeners for AnimationController:
The provided ScrollController is currently attached to more than one ScrollPosition.
The Scrollbar requires a single ScrollPosition in order to be painted.
When the scrollbar is interactive, the associated Scrollable widgets must have unique
ScrollControllers. The provided ScrollController must be unique to a Scrollable widget.

When the exception was thrown, this was the stack:
#0      RawScrollbarState._debugCheckHasValidScrollPosition.<anonymous closure>
(package:flutter/src/widgets/scrollbar.dart:1315:9)
#1      RawScrollbarState._debugCheckHasValidScrollPosition
(package:flutter/src/widgets/scrollbar.dart:1339:6)
#2      RawScrollbarState._validateInteractions (package:flutter/src/widgets/scrollbar.dart:1257:14)
#3      AnimationLocalStatusListenersMixin.notifyStatusListeners
(package:flutter/src/animation/listener_helpers.dart:233:19)
#4      AnimationController._checkStatusChanged
(package:flutter/src/animation/animation_controller.dart:814:7)
#5      AnimationController._startSimulation (package:flutter/src/animation/animation_controller.dart:748:5)
#6      AnimationController._animateToInternal
(package:flutter/src/animation/animation_controller.dart:611:12)
#7      AnimationController.forward (package:flutter/src/animation/animation_controller.dart:462:12)
#8      RawScrollbarState._handleScrollNotification (package:flutter/src/widgets/scrollbar.dart:1567:37)
#9      NotificationListener._dispatch (package:flutter/src/widgets/notification_listener.dart:206:42)
#10     Notification.visitAncestor (package:flutter/src/widgets/notification_listener.dart:122:20)
#11     ViewportNotificationMixin.visitAncestor (package:flutter/src/widgets/scroll_notification.dart:31:18)
#12     Element.visitAncestorElements (package:flutter/src/widgets/framework.dart:4133:39)
#13     Notification.dispatch (package:flutter/src/widgets/notification_listener.dart:138:13)
#14     ScrollActivity.dispatchScrollUpdateNotification
(package:flutter/src/widgets/scroll_activity.dart:94:92)
#15     ScrollPosition.didUpdateScrollPositionBy (package:flutter/src/widgets/scroll_position.dart:899:15)
#16     ScrollPositionWithSingleContext.pointerScroll
(package:flutter/src/widgets/scroll_position_with_single_context.dart:221:7)
#17     ScrollableState._handlePointerScroll (package:flutter/src/widgets/scrollable.dart:718:16)
#18     PointerSignalResolver.resolve (package:flutter/src/gestures/pointer_signal_resolver.dart:199:32)
#19     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:446:29)
#20     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:420:22)
#21     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:278:11)
#22     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
#23     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
#24     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#25     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#29     _invoke1 (dart:ui/hooks.dart:185:10)
#30     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
#31     _dispatchPointerDataPacket (dart:ui/hooks.dart:98:31)
(elided 3 frames from dart:async)

The AnimationController notifying status listeners was:
  AnimationController#349ad(▶ 0.000)
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: The provided ScrollController is currently attached to more than one
ScrollPosition.
```
	
</details>

<details> 
<summary>flutter doctor -v</summary> 
	
```console
$ flutter doctor -v
[✓] Flutter (Channel beta, 2.5.0-5.1.pre, on Debian GNU/Linux 10 (buster) 5.4.109-26094-g381754fbb430, locale
    en_US.UTF-8)
    • Flutter version 2.5.0-5.1.pre at /home/brett/flutter
    • Upstream repository https://github.com/flutter/flutter
    • Framework revision 65cf7de5f4 (7 days ago), 2021-08-11 15:48:01 -0700
    • Engine revision fbeb7e22bd
    • Dart version 2.14.0 (build 2.14.0-377.4.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/brett/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 7.0.1-8+deb10u2 (tags/RELEASE_701/final)
    • cmake version 3.13.4
    • ninja version 1.8.2
    • pkg-config version 0.29

[✓] Android Studio (version 4.0)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.59.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • Google Pixelbook (mobile) • emulator-5554 • android-x64 • Android 9 (API 28)
    • Linux (desktop)           • linux         • linux-x64   • Debian GNU/Linux 10 (buster)
      5.4.109-26094-g381754fbb430

! Doctor found issues in 1 category.
```

</details>

<details> 
<summary>pubspec.yaml</summary> 
	
```yaml
name: twin_list_view
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  split_view: ^3.1.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
```

</details>

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'package:split_view/split_view.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Dual ListView with SplitView',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const MyHomePage(title: 'Dual ListView with SplitView'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(title)),
      body: SplitView(
        viewMode: SplitViewMode.Horizontal,
        children: [
          ListView.builder(
            itemCount: 100,
            itemBuilder: (context, index) => ListTile(
              title: Text('left #$index'),
            ),
          ),
          ListView.builder(
            itemCount: 100,
            itemBuilder: (context, index) => ListTile(
              title: Text('right #$index'),
            ),
          ),
        ],
      ),
    );
  }
}
``` 

</details>

**Comment by domesticmouse** [comment]
Hey @Piinks, I'm curious if you have any ideas on this one? Thanks!

**Comment by TahaTesser** [comment]
Hi @domesticmouse 
Thanks for filing the issue, the issue is reproducible without using these third-party packages 

Simply needs this structure
![image](https://user-images.githubusercontent.com/48603081/129912545-7228e4be-f3da-491f-845e-43a04e29dea0.png)


<details> 
<summary>issue code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Dual ListView with SplitView',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const MyHomePage(title: 'Dual ListView with SplitView'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(title)),
      body: Row(
        children: [
          Container(
            height: MediaQuery.of(context).size.height,
            width: MediaQuery.of(context).size.width / 2,
            child: ListView.builder(
              itemCount: 100,
              itemBuilder: (context, index) => ListTile(
                title: Text('left #$index'),
              ),
            ),
          ),
          Container(
            height: MediaQuery.of(context).size.height,
            width: MediaQuery.of(context).size.width / 2,
            child: ListView.builder(
              itemCount: 100,
              itemBuilder: (context, index) => ListTile(
                title: Text('right #$index'),
              ),
            ),
          ),
        ],
      ),
    );
  }
}

``` 

</details>



### Working code

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Dual ListView with SplitView',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const MyHomePage(title: 'Dual ListView with SplitView'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(title)),
      body: Row(
        children: [
          Container(
            height: MediaQuery.of(context).size.height,
            width: MediaQuery.of(context).size.width / 2,
            child: ListView.builder(
              controller: ScrollController(),
              itemCount: 100,
              itemBuilder: (context, index) => ListTile(
                title: Text('left #$index'),
              ),
            ),
          ),
          Container(
            height: MediaQuery.of(context).size.height,
            width: MediaQuery.of(context).size.width / 2,
            child: ListView.builder(
              controller: ScrollController(),
              itemCount: 100,
              itemBuilder: (context, index) => ListTile(
                title: Text('right #$index'),
              ),
            ),
          ),
        ],
      ),
    );
  }
}
``` 

</details>

My understanding is that the default scroll controller is attached to both listview in the widget tree so we need to provide separate controls to not run into this error. Does this make sense? 



This was reported and solved in https://github.com/flutter/flutter/issues/8545

**Comment by Piinks** [comment]
Hey! @TahaTesser is correct.

This issue is coming from the scrollbar that is automatically applied to scrollable widgets on desktop. Typically, vertical scroll views automatically connect to the `PrimaryScrollController`, which is how this problem most-often presents itself. The scrollbar goes to paint using the `PrimaryScrollController`, and finds more than one scroll position attached to it. I think the error message reflects this.

I am not familiar with the implementation of [`split_view`](https://pub.dev/packages/split_view) and [`multi_split_view`](https://pub.dev/packages/multi_split_view), they may need to update their widgets to handle this. You may be able to avoid this by just disabling the auto desktop scrollbars in the meantime, `ScrollConfiguration.of(context).copyWith(scrollbars: false),` is one way to do it. [There is a full guide for this on the website](https://flutter.dev/docs/release/breaking-changes/default-desktop-scrollbars).

I do not think this is a framework issue, but let me know if you think there is anything else we can do here. Thanks!

**Comment by domesticmouse** [comment]
Near as I can tell from @TahaTesser's working code sample, all I need to do is add `controller: ScrollController()` to my `ListView`s and everything works. Well, testing my codelab sample code works as intended.

I'm a bit confused as to why I don't need to hold onto the `ScrollController` however. I feel like I should be converting my Widget that contains the ListView from stateless to stateful so I have a consistent `ScrollController`, and not a new one everytime my app's state changes.

I'm guessing the failure mode would be if state changed, forcing a new `ScrollController` into the tree, while the list is scrolling. Is this correct-ish? 

I'm trying to figure out how to explain this in a codelab, thus the desire to understand the pros and cons of constructing the `ScrollController` inline, vs holding onto a `ScrollController` via a `State` object.

**Comment by TahaTesser** [comment]
Labeling this for codelab as it is a blocker for explanation in a codelab and any potential API docs clarifications

**Comment by TahaTesser** [comment]
Ideally two ` ScrollController()` should be declared as a variable ` ScrollController _controller =  ScrollController()` in the widget class so they can be used for other scroll controller related stuff such as listener or something and pass them to the listviews in the app and of course, dispose all controllers in `dispose()`.

**Comment by domesticmouse** [comment]
@TahaTesser how's [this](https://github.com/flutter/codelabs/pull/154/commits/b03670bd52213712a527ac04f3e5585d1dc3cc3f) look?

**Comment by TahaTesser** [comment]
@domesticmouse 
Looks good to me, much better than passing the new `ScrollController` object directly to `ListView` that can't be used for anything, anywhere else in the class

**Comment by domesticmouse** [comment]
Thanks @TahaTesser!
