### ISSUE TITLE
[file_selector_web] Cannot stream chunks from large files (~2gb)

### ISSUE THREAD

**Issue by nwparker** [flutter/flutter#88465]
## Steps to Reproduce

**Step 1:**
Run the following code on the web:
Snippet (complete code attached below):
```dart
    final fileSize = await file.length();
    final chunkStarts = List.generate((fileSize/chunkSize.toDouble()).ceil(), (i) => i * chunkSize);

    for (var chunkStart in chunkStarts){
      final bytes = await file.openRead(chunkStart, min(fileSize, chunkStart + chunkSize)).single;
      print("Streamed ${bytes.length} bytes");
    }
```
<details>
 <summary>main.dart</summary>

```dart
import 'dart:math';

import 'package:file_selector/file_selector.dart';
import 'package:flutter/material.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  runApp(MaterialApp(home: OpenImagePage()));
}

/// Screen that shows an example of openFiles
class OpenImagePage extends StatelessWidget {
  void _openImageFile(BuildContext context) async {
    final XTypeGroup typeGroup = XTypeGroup(
      label: 'Video files',
      extensions: ['mp4'],
    );
    final XFile file = (await openFile(acceptedTypeGroups: [typeGroup]));
    print(file.name);
    print(file.path);

    print('Will attempt to iterate through stream in chunks');
    final chunkSize = 5000000;
    final fileSize = await file.length();
    print("File size: ${fileSize}");
    final chunkStarts = List.generate((fileSize/chunkSize.toDouble()).ceil(), (i) => i * chunkSize);

    var totalBytesStreamed = 0;
    for (var chunkStart in chunkStarts){
      final chunkEnd = min(fileSize, chunkStart + chunkSize);
      print("Opening chunk [$chunkStart, $chunkEnd]");
      final bytes = await file.openRead(chunkStart, min(fileSize, chunkStart + chunkSize)).single;
      print("Streamed ${bytes.length} bytes");
      totalBytesStreamed += bytes.length;
    }
    print("Total bytes streamed: $totalBytesStreamed");
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Open video file_selector"),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            ElevatedButton(
              style: ElevatedButton.styleFrom(
                primary: Colors.blue,
                onPrimary: Colors.white,
              ),
              child: const Text('Press to open a file'),
              onPressed: () => _openImageFile(context),
            ),
          ],
        ),
      ),
    );
  }
}

```
</details>

**Step 2:**
Open a large file mp4 (`2gb` or larger file)

**Expected results:**
All chunks can be streamed regardless of file size.

**Actual results:**
The code works on smaller files, but larger files produce the following "RangeError":
`Uncaught (in promise) Error: RangeError (end): Invalid value: Only valid value is 0: 5000000`

<details>
  <summary>Logs</summary>

```
> flutter run -d chrome --verbose --web-renderer html --web-hostname localhost --web-port 7357

[ +135 ms] executing: [C:\evo\apps\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +835 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 225a43d941ddd1753765fec3682011e9ddffb11d
[   +1 ms] executing: [C:\evo\apps\flutter/] git tag --points-at 225a43d941ddd1753765fec3682011e9ddffb11d
[ +322 ms] Exit code 0 from: git tag --points-at 225a43d941ddd1753765fec3682011e9ddffb11d
[        ] 2.5.0-6.0.pre
[  +18 ms] executing: [C:\evo\apps\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +37 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/dev
[        ] executing: [C:\evo\apps\flutter/] git ls-remote --get-url origin
[  +30 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +189 ms] executing: [C:\evo\apps\flutter/] git rev-parse --abbrev-ref HEAD
[  +38 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[ +145 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +218 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +191 ms] Skipping pub get: version match.
[   +2 ms] Found plugin file_selector at C:\Users\neil\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\file_selector-0.8.2\
[   +3 ms] Found plugin file_selector_web at C:\Users\neil\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\file_selector_web-0.8.1+1\
[   +2 ms] Generating C:\projects\lc3\er\flutter\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +348 ms] Launching lib\main.dart on Chrome in debug mode...
[ +226 ms] Updating assets
[ +744 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
[  +32 ms] Waiting for connection from debug service on Chrome...
[        ] Found plugin file_selector at C:\Users\neil\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\file_selector-0.8.2\
[   +1 ms] Found plugin file_selector_web at C:\Users\neil\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\file_selector_web-0.8.1+1\
[ +785 ms] <- reset
[  +34 ms] C:\evo\apps\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\evo\apps\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\evo\apps\flutter\bin\cache\flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -DLC_EVENT_DOT_DOMAIN=https://er-staging.web.app -DFLUTTER_WEB_AUTO_DETECT=false -DFLUTTER_WEB_USE_SKIA=false --output-dill C:\Users\neil\AppData\Local\Temp\flutter_tools.f4959f5e\flutter_tool.238c0e14\app.dill --libraries-spec file:///C:/evo/apps/flutter/bin/cache/flutter_web_sdk/libraries.json --packages C:\projects\lc3\er\flutter\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root C:\Users\neil\AppData\Local\Temp\flutter_tools.f4959f5e\flutter_tools.2dee180e --filesystem-scheme org-dartlang-app --initialize-from-dill build\41295e4f4bb0f57ff3d594f134282bfe.cache.dill.track.dill --platform file:///C:/evo/apps/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --no-sound-null-safety
[  +17 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+38169 ms] Waiting for connection from debug service on Chrome... (completed in 39.4s)
[   +1 ms] Synced 31.7MB.
[        ] <- accept
[        ] Caching compiled dill
[+1117 ms] [CHROME]:
[   +1 ms] [CHROME]:DevTools listening on ws://127.0.0.1:56482/devtools/browser/ca5b0fee-277b-4df8-a067-2f4a78dd0fe4
[ +833 ms] DwdsInjector: Received request for entrypoint at http://localhost:7357/main_module.bootstrap.js
[  +12 ms] MetadataProvider: Loading debug metadata...
[  +35 ms] MetadataProvider: Loaded debug metadata (no sound null safety)
[  +14 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:7357/main_module.bootstrap.js
[+3445 ms] ChromeProxyService: Initializing expression compiler for main_module.bootstrap.js with sound null safety: false
[ +178 ms] DevHandler: Debug service listening on ws://127.0.0.1:59694/LfAz_hv6DKw=/ws

[  +41 ms] This app is linked to the debug service: ws://127.0.0.1:59694/LfAz_hv6DKw=/ws
[  +16 ms] Debug service listening on ws://127.0.0.1:59694/LfAz_hv6DKw=/ws
[        ] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[   +4 ms]   To hot restart changes while running, press "r" or "R".
[        ] For a more detailed help message, press "h". To quit, press "q".
[   +1 ms] An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:59694/LfAz_hv6DKw=
[ +687 ms] DevTools activation throttled until 2021-08-19 00:19:19.716492.
[ +929 ms] The Flutter DevTools debugger and profiler on Chrome is available at: http://127.0.0.1:9109?uri=http://127.0.0.1:59694/LfAz_hv6DKw=
[+19232 ms] 2g.mp4
[        ] blob:http://localhost:7357/7a70f400-7f5a-4996-b3c7-db6cf35a4869
[        ] Will attempt to iterate through stream in chunks
[        ] File size: 2259764589
[        ] Opening chunk [0, 5000000]
[+11264 ms] Error: RangeError (end): Invalid value: Only valid value is 0: 5000000
                at Object.throw_ [as throw] (http://localhost:7357/dart_sdk.js:5400:11)
                at Object._checkValidRange (http://localhost:7357/dart_sdk.js:33343:17)
                at Uint8Array.[dartx.sublist] (http://localhost:7357/dart_sdk.js:32469:37)
                at html$.XFile.new.openRead (http://localhost:7357/packages/cross_file/src/types/html.dart.lib.js:131:39)
                at openRead.next (<anonymous>)
                at _AsyncStarImpl.new.runBody (http://localhost:7357/dart_sdk.js:33428:40)
                at _RootZone.runUnary (http://localhost:7357/dart_sdk.js:40515:58)
                at _FutureListener.thenAwait.handleValue (http://localhost:7357/dart_sdk.js:35444:29)
                at handleValueCallback (http://localhost:7357/dart_sdk.js:36029:49)
                at Function._propagateToListeners (http://localhost:7357/dart_sdk.js:36067:17)
                at _Future.new.[_completeWithValue] (http://localhost:7357/dart_sdk.js:35909:23)
                at async._AsyncCallbackEntry.new.callback (http://localhost:7357/dart_sdk.js:35932:35)
                at Object._microtaskLoop (http://localhost:7357/dart_sdk.js:40820:13)
                at _startMicrotaskLoop (http://localhost:7357/dart_sdk.js:40826:13)
                at http://localhost:7357/dart_sdk.js:36291:9
```

```
n/a
```

```
[√] Flutter (Channel dev, 2.5.0-6.0.pre, on Microsoft Windows [Version 10.0.19043.1165], locale en-US)
    • Flutter version 2.5.0-6.0.pre
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 225a43d941 (13 days ago), 2021-08-05 11:32:48 -0700
    • Engine revision 07ec4b82c7
    • Dart version 2.14.0 (build 2.14.0-383.0.dev)

[√] Chrome - develop for the web
    • Chrome

[√] Android Studio (version 4.1)
    • Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • Chrome (web)      • chrome               • web-javascript • Google Chrome 92.0.4515.159
    • Edge (web)        • edge                 • web-javascript • Microsoft Edge 92.0.902.73
```

</details>

---
This issue is similar to #76036

**Comment by TahaTesser** [comment]
Hi @nwparker 
I can reproduce the issue with 3.5GB video file, recorded from my phone, however this seems confirmed in https://github.com/flutter/flutter/issues/76036#issuecomment-893828596 too and the issue was closed
```console
[        ] Will attempt to iterate through stream in chunks
[   +1 ms] File size: 3680480680
[        ] Opening chunk [0, 5000000]
[+7051 ms] Error: RangeError (end): Invalid value: Only valid value is 0: 5000000
                        at Object.throw_ [as throw] (http://localhost:56404/dart_sdk.js:5348:11)
                        at Object._checkValidRange (http://localhost:56404/dart_sdk.js:31972:17)
                        at Uint8Array.[dartx.sublist] (http://localhost:56404/dart_sdk.js:31098:37)
                        at html$.XFile.new.openRead
(http://localhost:56404/packages/cross_file/src/types/html.dart.lib.js:131:39)
                        at openRead.next (<anonymous>)
                        at _AsyncStarImpl.new.runBody (http://localhost:56404/dart_sdk.js:32057:40)
                        at _RootZone.runUnary (http://localhost:56404/dart_sdk.js:39087:58)
                        at _FutureListener.thenAwait.handleValue (http://localhost:56404/dart_sdk.js:34073:29)
                        at handleValueCallback (http://localhost:56404/dart_sdk.js:34633:49)
                        at Function._propagateToListeners (http://localhost:56404/dart_sdk.js:34671:17)
                        at _Future.new.[_completeWithValue] (http://localhost:56404/dart_sdk.js:34513:23)
                        at async._AsyncCallbackEntry.new.callback (http://localhost:56404/dart_sdk.js:34536:35)
                        at Object._microtaskLoop (http://localhost:56404/dart_sdk.js:39374:13)
                        at _startMicrotaskLoop (http://localhost:56404/dart_sdk.js:39380:13)
                        at http://localhost:56404/dart_sdk.js:34887:9
```

smaller video files work fine
```
[+409354 ms] ForBiggerBlazes.mp4
[   +1 ms] blob:http://localhost:56404/c7c09b83-043a-4584-8ff5-6c40aaa4c7b1
[        ] Will attempt to iterate through stream in chunks
[   +1 ms] File size: 2498125
[        ] Opening chunk [0, 2498125]
[  +40 ms] Streamed 2498125 bytes
[   +1 ms] Total bytes streamed: 2498125
```

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.22000.132], locale en-US)
    • Flutter version 2.2.3 at C:\Users\Taha\Code\flutter_stable
    • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Taha\Code\android-sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\android-sdk
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31605.320
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.59.0)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[✓] Connected device (4 available)
    • IN2011 (mobile)   • c9d8ee0c • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows  • windows-x64    • Microsoft Windows [Version 10.0.22000.132]
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 92.0.4515.159
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 92.0.902.73

! Doctor found issues in 1 category.
```

</details>


Should such big files be streamed by this package or Is it a general web issue?
cc: @ditman

**Comment by nwparker** [comment]
@TahaTesser  -- I see the "waiting for customer response" label was added.
Does this mean I should supply additional information?

**Comment by TahaTesser** [comment]
@nwparker 
I have added a wait label as the original issue was closed even after it is not with > 2GB so I am not sure this issue is valid. 
I will label for @ditman to respond

**Comment by ditman** [comment]
@nwparker I'll try to rewrite the streaming implementation with something like this: https://stackoverflow.com/questions/14438187/javascript-filereader-parsing-long-file-in-chunks

**Comment by melewetwo** [comment]
any progress on this issue?

**Comment by ditman** [comment]
All right, I found a fundamental problem with the current implementation of `cross_file` (and as a side effect, on *how* it's being used by the plugins):

* **We discard the blob that is used to create the file** (in fact: we never show the blob to the XFile constructor, so we can't fix this issue "in one go")

This causes problems because it's *hard* to restore a Blob object from a blobUrl (it requires a fetch and uses 2x the memory! [interesting SO answer](https://stackoverflow.com/a/66998406)). For very large files, this goes over the limit of memory of the browser (I'll experiment some more, but this seems to be the case).

In order to robustly fix this, we need to do two things:

* [ ] Create a new `html.File` or `html.Blob` (possibly both) constructors for the `XFile` object, that are web-only.
  * [ ] For `dart:io` we could create a constructor that takes a `io.File` too.
* [ ] Ideally, deprecate the default `String path` constructor, pointing users to the new platform-dependent constructors.
* [ ] Reimplement the methods in XFile to use the new backing object(s).
  * [ ] This would allow us to implement slicing of the Blob in the web without much fuss, since the Blob is contained in the cross_file object.

Once the above is done, we need to:

* [ ] Revisit the plugins that use cross_file, and fix the initialization of the XFile object to use the new backing objects: `html.File/Blob` or `io.File`.

Consumers of the `XFile` objects wouldn't be affected by this, unless they're creating their own `XFile` objects (they'd need to migrate to the non-deprecated constructors). To mitigate this, the cross_file version can be bumped one major version when adding the new constructors.

**Comment by ditman** [comment]
Actually an intermediate solution using Blobs internally might be all right; tests are passing and I just streamed a 5GB file, so the fix might be doable in the web-only part of the code.

I'm cleaning up some more stuff and will prepare a PR with a Blob-backed XFile for the web.

**Comment by ditman** [comment]
My assessment above of not creating the XFile from the Blob is still true. With my current patch, accessing the bytes of the blob the first time takes a while because the browser needs to "re-load" it. We could make large files in the web slightly faster by initializing them with the raw Blob, instead of its documentUrl.

**Comment by ditman** [comment]
I have a WIP version of a Blob-backed XFile here:

https://github.com/ditman/flutter-packages/tree/blob-backed-xfile

But in my (manual) testing, my code is making Safari on macOS **reload the page** (with @nwparker's example app) when selecting a file larger than 1 or 1.5GB. (The rest of the browsers seem to handle bigger files better with it, though.)

Can somebody else give the above branch a try and see if it works better/worse for them? I don't have too many test cases!

**Comment by ditman** [comment]
I've posted a PR here, if anybody is interested, please take a look!

https://github.com/flutter/packages/pull/494

**Comment by ditman** [comment]
> In Chrome (desktop), it worked with a 10gb file. Although it did hang (loading forever on a 17gb file).

Very interesting data point! Let's see if some more bugs come about large files, and we'll try to find these extreme values! Thanks for testing with ludicrously large files! I ended up having to use `mkfile`, I couldn't download files that were large enough from anywhere :P

**Comment by nwparker** [comment]
> `cross_file: ^0.3.2` might alleviate this issue? Now XFile on the web is implemented with a backing Blob, instead of an Array of bytes.

Thanks for the work!

I think we'll have to bump this dep (in [File Selector](https://pub.dev/packages/file_selector)) to use the new cross_file version:
https://github.com/flutter/plugins/blob/master/packages/file_selector/file_selector_platform_interface/pubspec.yaml

**Comment by ditman** [comment]
@nwparker yes, we can force File Selector and other plugins to pick a newer (non buggy) version of cross_file. However, pub should be able to resolve 0.3.2 from a dependency written as ^0.3.0.

If apps are not picking up the latest version of the library (check your pubspec.lock file to see exactly what version is being used), I'd recommend doing `flutter pub upgrade` so pub ignores the lock file and grabs the latest available in pub.dev. That should upgrade cross_file to 0.3.2, without having to publish any other package.
