### ISSUE TITLE
Flutter apps are broken in Fuchsia

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#8850]
When running email_story, I get the stack dump below. This was caused by commit dce4bf8599ba5d96692d16eaeade15d0d142a410.

```
[03146.341] 12560.12589> [ERROR:dart_error.cc(16)] Unhandled exception:
[03146.341] 12560.12589> FormatException: Expected envelope List, got null
[03146.341] 12560.12589> #0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:126)
[03146.341] 12560.12589> #1      PlatformMethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:130)
[03146.341] 12560.12589> <asynchronous suspension>
[03146.341] 12560.12589> #2      SystemChrome.setApplicationSwitcherDescription (package:flutter/src/services/system_chrome.dart:120)
[03146.341] 12560.12589> <asynchronous suspension>
[03146.341] 12560.12589> #3      Title.build (package:flutter/src/widgets/title.dart:32)
[03146.341] 12560.12589> #4      StatelessElement.build (package:flutter/src/widgets/framework.dart:3120)
[03146.341] 12560.12589> #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3065)
[03146.341] 12560.12589> #6      Element.rebuild (package:flutter/src/widgets/framework.dart:2966)
[03146.341] 12560.12589> #7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3045)
[03146.341] 12560.12589> #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3040)
[03146.341] 12560.12589> #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2462)
[03146.341] 12560.12589> #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2265)
[03146.341] 12560.12589> #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3077)
[03146.341] 12560.12589> #12     Element.rebuild (package:flutter/src/widgets/framework.dart:2966)
[03146.341] 12560.12589> #13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3045)
[03146.341] 12560.12589> #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3040)
[03146.341] 12560.12589> #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2462)
[03146.341] 12560.12589> #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2265)
[03146.341] 12560.12589> #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3077)
[03146.341] 12560.12589> #18     Element.rebuild (package:flutter/src/widgets/framework.dart:2966)
[03146.341] 12560.12589> #19     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3045)
[03146.341] 12560.12589> #20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3040)
[03146.341] 12560.12589> #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2462)
[03146.341] 12560.12589> #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2265)
[03146.341] 12560.12589> #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3077)
[03146.341] 12560.12589> #24     Element.rebuild (package:flutter/src/widgets/framework.dart:2966)
[03146.341] 12560.12589> #25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3045)
[03146.341] 12560.12589> #26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3040)
[03146.341] 12560.12589> #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2462)
[03146.341] 12560.12589> #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2265)
[03146.341] 12560.12589> #29     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4006)
[03146.341] 12560.12589> #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2462)
[03146.341] 12560.12589> #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2265)
[03146.341] 12560.12589> #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3077)
[03146.341] 12560.12589> #33     Element.rebuild (package:flutter/src/widgets/framework.dart:2966)
[03146.341] 12560.12589> #34     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3045)
[03146.341] 12560.12589> #35     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3040)
[03146.341] 12560.12589> #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2462)
[03146.341] 12560.12589> #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2265)
[03146.341] 12560.12589> #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3077)
[03146.341] 12560.12589> #39     Element.rebuild (package:flutter/src/widgets/framework.dart:2966)
[03146.341] 12560.12589> #40     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3045)
[03146.341] 12560.12589> #41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3040)
[03146.341] 12560.12589> #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2462)
[03146.341] 12560.12589> #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2265)
[03146.341] 12560.12589> #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3077)
[03146.341] 12560.12589> #45     Element.rebuild (package:flutter/src/widgets/framework.dart:2966)
[03146.341] 12560.12589> #46     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3045)
[03146.341] 12560.12589> #47     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3183)
[03146.341] 12560.12589> #48     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3040)
[03146.341] 12560.12589> #49     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2462)
[03146.341] 12560.12589> #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2265)
[03146.341] 12560.12589> #51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3077)
[03146.341] 12560.12589> #52     Element.rebuild (package:flutter/src/widgets/framework.dart:2966)
[03146.341] 12560.12589> #53     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3045)
[03146.341] 12560.12589> #54     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3040)
[03146.341] 12560.12589> #55     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2462)
[03146.341] 12560.12589> #56     Element.updateChild (package:flutter/src/widgets/framework.dart:2265)
[03146.341] 12560.12589> #57     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3077)
[03146.341] 12560.12589> #58     Element.rebuild (package:flutter/src/widgets/framework.dart:2966)
[03146.341] 12560.12589> #59     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3045)
[03146.341] 12560.12589> #60     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3183)
[03146.341] 12560.12589> #61     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3040)
[03146.341] 12560.12589> #62     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2462)
[03146.341] 12560.12589> #63     Element.updateChild (package:flutter/src/widgets/framework.dart:2265)
[03146.341] 12560.12589> #64     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3077)
[03146.341] 12560.12589> #65     Element.rebuild (package:flutter/src/widgets/framework.dart:2966)
[03146.341] 12560.12589> #66     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3045)
[03146.341] 12560.12589> #67     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3040)
[03146.341] 12560.12589> #68     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2462)
[03146.341] 12560.12589> #69     Element.updateChild (package:flutter/src/widgets/framework.dart:2265)
[03146.341] 12560.12589> #70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3077)
[03146.341] 12560.12589> #71     Element.rebuild (package:flutter/src/widgets/framework.dart:2966)
[03146.341] 12560.12589> #72     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3045)
[03146.341] 12560.12589> #73     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3183)
[03146.341] 12560.12589> #74     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3040)
[03146.341] 12560.12589> #75     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2462)
[03146.341] 12560.12589> #76     Element.updateChild (package:flutter/src/widgets/framework.dart:2265)
[03146.341] 12560.12589> #77     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:567)
[03146.341] 12560.12589> #78     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:538)
[03146.341] 12560.12589> #79     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:484)
[03146.341] 12560.12589> #80     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:1833)
[03146.341] 12560.12589> #81     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:483)
[03146.341] 12560.12589> #82     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:384)
[03146.341] 12560.12589> #83     runApp (package:flutter/src/widgets/binding.dart:416)
[03146.341] 12560.12589> #84     main (file:///media/jimbe/mojossd/fuchsia/apps/modules/email/modules/service/lib/main.dart:88)
[03146.341] 12560.12589> <asynchronous suspension>
[03146.341] 12560.12589> #85     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
[03146.341] 12560.12589> #86     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by eseidelGoogle** [comment]
I believe there are instructions for migrating https://groups.google.com/forum/#!topic/flutter-dev/ZQMnAIikneY

**Comment by abarth** [comment]
@eseidelGoogle It's our code that needs to change.
