### ISSUE TITLE
[Android] Null check operator exception in ShortcutManager class

### ISSUE THREAD

**Issue by Faiyyaz** [flutter/flutter#88528]
Hi,

In one of my release app I got the below bug report from crashlytics for my app running on android tv.

```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Null check operator used on a null value. Error thrown Instance of 'ErrorDescription'.
       at ShortcutManager.handleKeypress(ShortcutManager.java:359)
       at _ShortcutsState._handleOnKey(_ShortcutsState.java:708)
       at FocusManager._handleRawKeyEvent(FocusManager.java:1678)
       at RawKeyboard._handleKeyEvent(RawKeyboard.java:682)
       at BasicMessageChannel.setMessageHandler.<fn>(setMessageHandler.java:73)
       at BasicMessageChannel.setMessageHandler.<fn>(setMessageHandler.java:72)
       at _DefaultBinaryMessenger.handlePlatformMessage(_DefaultBinaryMessenger.java:284)
```

Please help me with this issue. I had read somewhere that it was due to bluetooth keyboard rather than on screen keyboard.

**Comment by darshankawar** [comment]
@Faiyyaz 
Can you provide `flutter doctor -v` of the release app along with a reproducible code sample that may replicate the issue locally ?

There's a similar issue reported for iOS https://github.com/flutter/flutter/issues/80123

**Comment by Faiyyaz** [comment]
Okay I will try to update it ASAP. I would be able to update mostly by weekend only

**Comment by Faiyyaz** [comment]
```
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale en_IN)
    • Flutter version 2.2.3 at /home/faiyyaz/snap/flutter/common/flutter
    • Framework revision f4abaa0735 (9 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/faiyyaz/Android/Sdk
    • Platform android-S, build-tools 30.0.3
    • Java binary at: /snap/android-studio/114/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /snap/android-studio/113/android-studio
    • Flutter plugin version 58.0.1
    • Dart plugin version 202.8531
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] Android Studio (version 2020.3)
    • Android Studio at /snap/android-studio/114/android-studio
    • Flutter plugin version 59.0.2
    • Dart plugin version 203.8292
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /home/faiyyaz/Personal/idea-IC-203.7717.56
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.59.1)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.159

• No issues found!
```

I have just created an exact replica of the screen which is having the above issue & shared a zip file for your reference.

```
[shortcut.zip](https://github.com/flutter/flutter/files/7075020/shortcut.zip)
```

**Comment by darshankawar** [comment]
@Faiyyaz 
Thanks for the zip, I ran the code but what are the exact steps to replicate the issue ? Can you share the same ?

**Comment by Faiyyaz** [comment]
Sorry I don't have the step to replicate the issue since it was reported through crashlytics to me. Only thing I can say that it happened with one user as of now & that too was using android tv.

**Comment by darshankawar** [comment]
I am unable to replicate this issue using the sample code provided, but could be related to https://github.com/flutter/flutter/issues/80123#issuecomment-818138381

Keeping this issue open for further insights from the team.

/cc: @gspencergoog

**Comment by stuartmorgan** [comment]
The stack here is made up; the code in question is Dart code, not Java code. Crashlytics must be creating a synthetic Java stack trace from the Dart stack, for reporting through the existing mechanism.

Are you still seeing this being reported? The Dart code has changed quite a lot since then.
