### ISSUE TITLE
Failed assertion

### ISSUE THREAD

**Issue by stfn3000** [flutter/flutter#88550]
Hello, I received a bug and got the following message encouraging me to report here, so I am:

```console
======== Exception caught by widgets library =======================================================
The following assertion was thrown building Navigator-[GlobalObjectKey<NavigatorState> _WidgetsAppState#589fe](dirty, dependencies: [UnmanagedRestorationScope, HeroControllerScope], state: NavigatorState#548b9(tickers: tracking 4 tickers)):
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 5307 pos 12: '!_debugLocked': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  MaterialApp file:///D:/AndroidStudioProjectsAndAssets/projectapp/lib/main.dart:42:20
When the exception was thrown, this was the stack: 
#2      NavigatorState.build (package:flutter/src/widgets/navigator.dart:5307:12)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4691:27)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4574:15)
#5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4746:11)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
...
====================================================================================================

```

**Comment by bernaferrari** [comment]
Do you have a reproducible sample? And what is the `flutter doctor -v`?

**Comment by TahaTesser** [comment]
Hi @stfn3000 
Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you
