### ISSUE TITLE
First generation iPad Pro throw `animation_controller` exception

### ISSUE THREAD

**Issue by wliumelb** [flutter/flutter#88563]
## Steps to Reproduce

Run this in debug mode on an iPad, tap on the two tabs alternatively a few times, then an exception will be thrown.
```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

const List<Tab> tabs = <Tab>[
  Tab(text: 'One'),
  Tab(text: 'Two'),
];

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: DefaultTabController(
        length: tabs.length,
        child: Column(
          children: [
            TabBar(
              tabs: tabs,
              labelColor: Colors.blue,
              unselectedLabelColor: Colors.black,
            ),
            Expanded(
              child: TabBarView(
                children: [
                  SingleChildScrollView(
                    child: Column(
                      children: [for (var i = 0; i < 200; i++) ListTile(title: Text('Item $i'))],
                    ),
                  ),
                  SingleChildScrollView(
                    child: Column(
                      children: [for (var i = 0; i < 200; i++) ListTile(title: Text('Item $i'))],
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}

```

**Expected results:** 

No error

**Actual results:** 

```
══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 819 pos 12:
'elapsedInSeconds >= 0.0': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack:
#2      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:819:12)
#3      Ticker._tick (package:flutter/src/scheduler/ticker.dart:238:12)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#5      SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1058:11)
#6      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
#7      SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1056:17)
#8      SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:977:5)
#12     _invoke1 (dart:ui/hooks.dart:182:10)
#13     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:237:5)
#14     _beginFrame (dart:ui/hooks.dart:114:31)
(elided 5 frames from class _AssertionError and dart:async)

```
<details>
  <summary>Logs</summary>

```
flutter doctor -v
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-x64, locale en-AU)
    • Flutter version 2.2.3 at /Users/edwin/flutter
    • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/edwin/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • iPad (mobile)   • 89b781d176090f7077efd5e4a5d253c76c264a36 • ios            • iOS 13.6
    • macOS (desktop) • macos                                    • darwin-x64     • macOS 11.5.2 20G95 darwin-x64
    • Chrome (web)    • chrome                                   • web-javascript • Google Chrome 92.0.4515.159

• No issues found!
```

</details>

**Comment by wliumelb** [comment]
Might be relevant:

Sometimes this error is also thrown:
`<_UISystemGestureGateGestureRecognizer: 0x283ff0600>: Gesture: Failed to receive system gesture state notification before next touch`

This seems to be an iPad only issue. Could not produce the same error on an iPhone.

Also, the more complex the widgets under TabBarView, the easier for the error to show up.

**Comment by darshankawar** [comment]
@wliumelb 
Thanks for the report. I tried the code sample using latest master and stable on iPhone 6s(14.4.1) and on iPad simulator (14.3) and on both, I couldn't replicate the issue.


https://user-images.githubusercontent.com/67046386/130421856-720ca415-a420-453b-9b63-2c865db03947.mov

<details>
<summary> stable and master flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.2.3 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision f4abaa0735 (4 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dhs/Library/Android/sdk
    • Java binary at: /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.    

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • Darshan's iphone (mobile)                      •
      21150b119064aecc249dfcfe05e259197461ce23 • ios            • iOS 14.4.1
    • iPhone 12 Pro Max (mobile)                     •
      A5473606-0213-4FD8-BA16-553433949729     • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • iPad Pro (12.9-inch) (4th generation) (mobile) •
      AD9F1B85-B622-485E-97E8-E4AC866D5770     • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)                                • macos
      • darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)                                   • chrome
      • web-javascript • Google Chrome 92.0.4515.159

• No issues found!

[✓] Flutter (Channel master, 2.5.0-7.0.pre.187, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.5.0-7.0.pre.187 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 05bfbbfbec (4 hours ago), 2021-08-22 21:37:03 -0400
    • Engine revision 710af46d53
    • Dart version 2.15.0 (build 2.15.0-42.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dhs/Library/Android/sdk
    • Java binary at: /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.    

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • Darshan's iphone (mobile)                      •
      21150b119064aecc249dfcfe05e259197461ce23 • ios            • iOS 14.4.1
    • iPhone 12 Pro Max (mobile)                     •
      A5473606-0213-4FD8-BA16-553433949729     • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • iPad Pro (12.9-inch) (4th generation) (mobile) •
      AD9F1B85-B622-485E-97E8-E4AC866D5770     • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)                                • macos
      • darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)                                   • chrome
      • web-javascript • Google Chrome 92.0.4515.159





```

</details>

I see that you are on OS 13.6 which is an older one and could be specific to it ? Is there a way for you to verify the same on higher OS version and see if it replicates ?

Thanks.

**Comment by wliumelb** [comment]
@darshankawar 
Thanks for the reply. There is an earlier report of the issue on iPadOS 14.6 https://github.com/flutter/flutter/issues/85181
I'll update the os version and try again.

**Comment by darshankawar** [comment]
@wliumelb Yes I looked into that as well, but it got closed due to inactivity and couldn't confirm to be replicated.
Would also be good if you could provide exact steps to replicate.
Thanks.

**Comment by wliumelb** [comment]
@darshankawar 
I can confirm that this issue can still be consistently produced with the above code on my iPad Pro(12.9-inch, 2015 model) after updating to iPadOS 14.7

However, I could not produce the issue on my iPad Air 2 (2014 model), nor an iPad pro simulator. 

Seems like this issue affects only specific physical models.

**Comment by darshankawar** [comment]
@wliumelb Thanks for narrowing down the issue to physical models. 
Tagging @TahaTesser to verify this on a physical iPad.

**Comment by TahaTesser** [comment]
Hi @wliumelb 
Thank you for catching this issue. 

The issue is because of the high 120hz refresh rate on iPad Pro, it will only reproduce on a physical iPad with which has a 120hz display rather than a normal 60hz, my iPad is 60hz. You can't reproduce on a physical iPhone since all iPhones are still 60hz.

The simulator for iPad Pro is also only 60hz same as your MacBook, since it outputs what your system can. 
Due to the 120hz refresh rate, animations are affected, Apple 120hz is different from than normal Android high refresh rate but nevertheless, I tried Oneplus 8 90hz,  no issue.

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 12.0 21A5304g darwin-x64, locale
    en-GB)
    • Flutter version 2.2.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision f4abaa0735 (8 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Users/tahatesser/Code/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Temurin-11.0.12+7 (build
      11.0.12+7)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 13.0, Build version 13A5212g
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2020.3)
    • Android Studio at /Users/tahatesser/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7583922/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS
      15.0
    • macOS (desktop)      • macos                     • darwin-x64     • macOS
      12.0 21A5304g darwin-x64
    • Chrome (web)         • chrome                    • web-javascript • Google
      Chrome 92.0.4515.159

! Doctor found issues in 1 category.
```

</details>

**Comment by TahaTesser** [comment]
If you have either iPad Pro with ProMotion or iPhone 13 with ProMotion, this is worth reproducing since more Apple devices now have 120hz display. 
cc: @jmagman

**Comment by jmagman** [comment]
>. Run this in debug mode on an iPad, tap on the two tabs alternatively a few times, then an exception will be thrown.

I don't have a 1 gen iPad Pro, but I couldn't reproduce on my gen 3.

@wliumelb  When you reproduce it, what is the value of `elapsedInSeconds`?  You can set a breakpoint and check.

**Comment by FrankBlue** [comment]
there is same problem on 1 gen Ipad pro , iphone13 pro and ios simulator etc. 
modify packages/flutter/lib/src/scheduler/binding.dart, this issue disappear
```
  var __lastRawTimeStamp = Duration.zero;
  void _handleBeginFrame(Duration rawTimeStamp) {
    if (_warmUpFrame) {
      // "begin frame" and "draw frame" must strictly alternate. Therefore
      // _rescheduleAfterWarmUpFrame cannot possibly be true here as it is
      // reset by _handleDrawFrame.
      assert(!_rescheduleAfterWarmUpFrame);
      _rescheduleAfterWarmUpFrame = true;
      return;
    }
    if (_lastRawTimeStamp.compareTo(__lastRawTimeStamp) >= 0) {
      rawTimeStamp = _lastRawTimeStamp + Duration(milliseconds: 1);
    }
    // assert(rawTimeStamp.compareTo(__lastRawTimeStamp) >= 0);
    __lastRawTimeStamp = rawTimeStamp;
    handleBeginFrame(rawTimeStamp);
  }
```
It same like flutter engine produce non-incremental TimePoint.

 fvm flutter doctor -v 
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.8.1 at /Users/eric/.fvm/versions/2.8.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (10 days ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

Hope above helpful.

**Comment by FrankBlue** [comment]
there is same problem on 1 gen Ipad pro , iphone13 pro and ios simulator etc. 
modify [packages/flutter/lib/src/scheduler/binding.dart](url), this issue disappear
```dart
  var __lastRawTimeStamp = Duration.zero;
  void _handleBeginFrame(Duration rawTimeStamp) {
    if (_warmUpFrame) {
      // "begin frame" and "draw frame" must strictly alternate. Therefore
      // _rescheduleAfterWarmUpFrame cannot possibly be true here as it is
      // reset by _handleDrawFrame.
      assert(!_rescheduleAfterWarmUpFrame);
      _rescheduleAfterWarmUpFrame = true;
      return;
    }
    // assert(__lastRawTimeStamp.compareTo(rawTimeStamp) <= 0);
    if (__lastRawTimeStamp.compareTo(rawTimeStamp) > 0) {
      rawTimeStamp = __lastRawTimeStamp + Duration(milliseconds: 1);
    }
    __lastRawTimeStamp = rawTimeStamp;
    handleBeginFrame(rawTimeStamp);
  }

```
It same like flutter engine produces non-incremental TimePoint.

 fvm flutter doctor -v 
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.8.1 at /Users/eric/.fvm/versions/2.8.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (10 days ago), 2021-12-16
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

Hope above helpful.

**Comment by Doflatango** [comment]
I'm runing into this issue randomly now, any ideas? this happens both on Android device an Android simulator.
