### ISSUE TITLE
AnimatedSwitcher crashes with null child in Column or Row

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#88575]
## Steps to Reproduce

Run the code sample

**Expected results:** no crash

**Actual results:** crash

<details>
  <summary>Code sample</summary>

```dart
// Flutter code sample for AnimatedSwitcher
//
// This sample shows a counter that animates the scale of a text widget
// whenever the value changes.

import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

/// This is the main application widget.
class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: _title,
      home: MyStatefulWidget(),
    );
  }
}

/// This is the stateful widget that the main application instantiates.
class MyStatefulWidget extends StatefulWidget {
  const MyStatefulWidget({Key? key}) : super(key: key);

  @override
  State<MyStatefulWidget> createState() => _MyStatefulWidgetState();
}

/// This is the private State class that goes with MyStatefulWidget.
class _MyStatefulWidgetState extends State<MyStatefulWidget> {
  int _count = 0;

  @override
  Widget build(BuildContext context) {
    return Container(
      color: Colors.white,
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: <Widget>[
          AnimatedSwitcher(
            duration: const Duration(milliseconds: 500),
            transitionBuilder: (Widget child, Animation<double> animation) {
              return ScaleTransition(child: child, scale: animation);
            },
            child: _count % 2 == 0 ? null : Text(
              '$_count',
              // This key causes the AnimatedSwitcher to interpret this as a "new"
              // child each time the count changes, so that it will begin its animation
              // when the count changes.
              key: ValueKey<int>(_count),
              style: Theme.of(context).textTheme.headline4,
            ),
          ),
          ElevatedButton(
            child: const Text('Increment'),
            onPressed: () {
              setState(() {
                _count += 1;
              });
            },
          ),
        ],
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
════════ Exception caught by rendering library ═════════════════════════════════
The following assertion was thrown during performLayout():
'package:flutter/src/rendering/stack.dart': Failed assertion: line 541 pos 14: 'constraints.biggest.isFinite': is not true.
2

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was
AnimatedSwitcher AnimatedSwitcher:file:///C:/dev/projects/issues/lib/main.dart:44:11
When the exception was thrown, this was the stack
#2      RenderStack._computeSize
package:flutter/…/rendering/stack.dart:541
#3      RenderStack.performLayout
package:flutter/…/rendering/stack.dart:597
#4      RenderObject.layout
package:flutter/…/rendering/object.dart:1858
#5      ChildLayoutHelper.layoutChild
package:flutter/…/rendering/layout_helper.dart:56
#6      RenderFlex._computeSizes
package:flutter/…/rendering/flex.dart:829
#7      RenderFlex.performLayout
package:flutter/…/rendering/flex.dart:931
#8      RenderObject.layout
package:flutter/…/rendering/object.dart:1858
#9      RenderProxyBoxMixin.performLayout
package:flutter/…/rendering/proxy_box.dart:116
#10     RenderObject.layout
package:flutter/…/rendering/object.dart:1858
#11     RenderProxyBoxMixin.performLayout
package:flutter/…/rendering/proxy_box.dart:116
#12     RenderObject.layout
package:flutter/…/rendering/object.dart:1858
#13     RenderProxyBoxMixin.performLayout
package:flutter/…/rendering/proxy_box.dart:116
#14     RenderObject.layout
package:flutter/…/rendering/object.dart:1858
#15     RenderProxyBoxMixin.performLayout
package:flutter/…/rendering/proxy_box.dart:116
#16     RenderObject.layout
package:flutter/…/rendering/object.dart:1858
#17     RenderProxyBoxMixin.performLayout
package:flutter/…/rendering/proxy_box.dart:116
#18     RenderObject.layout
package:flutter/…/rendering/object.dart:1858
#19     RenderProxyBoxMixin.performLayout
package:flutter/…/rendering/proxy_box.dart:116
#20     RenderObject.layout
package:flutter/…/rendering/object.dart:1858
#21     RenderProxyBoxMixin.performLayout
package:flutter/…/rendering/proxy_box.dart:116
#22     RenderObject.layout
package:flutter/…/rendering/object.dart:1858
#23     RenderProxyBoxMixin.performLayout
package:flutter/…/rendering/proxy_box.dart:116
#24     RenderObject.layout
package:flutter/…/rendering/object.dart:1858
#25     RenderProxyBoxMixin.performLayout
package:flutter/…/rendering/proxy_box.dart:116
#26     RenderObject.layout
package:flutter/…/rendering/object.dart:1858
#27     RenderProxyBoxMixin.performLayout
package:flutter/…/rendering/proxy_box.dart:116
#28     RenderOffstage.performLayout
package:flutter/…/rendering/proxy_box.dart:3422
#29     RenderObject.layout
package:flutter/…/rendering/object.dart:1858
#30     RenderProxyBoxMixin.performLayout
package:flutter/…/rendering/proxy_box.dart:116
#31     RenderObject.layout
package:flutter/…/rendering/object.dart:1858
#32     _RenderTheatre.performLayout
package:flutter/…/widgets/overlay.dart:745
#33     RenderObject.layout
package:flutter/…/rendering/object.dart:1858
#34     RenderProxyBoxMixin.performLayout
package:flutter/…/rendering/proxy_box.dart:116
#35     RenderObject.layout
package:flutter/…/rendering/object.dart:1858
#36     RenderProxyBoxMixin.performLayout
package:flutter/…/rendering/proxy_box.dart:116
#37     RenderObject.layout
package:flutter/…/rendering/object.dart:1858
#38     RenderProxyBoxMixin.performLayout
package:flutter/…/rendering/proxy_box.dart:116
#39     RenderObject.layout
package:flutter/…/rendering/object.dart:1858
#40     RenderProxyBoxMixin.performLayout
package:flutter/…/rendering/proxy_box.dart:116
#41     RenderCustomPaint.performLayout
package:flutter/…/rendering/custom_paint.dart:545
#42     RenderObject.layout
package:flutter/…/rendering/object.dart:1858
#43     RenderProxyBoxMixin.performLayout
package:flutter/…/rendering/proxy_box.dart:116
#44     RenderObject.layout
package:flutter/…/rendering/object.dart:1858
#45     RenderProxyBoxMixin.performLayout
package:flutter/…/rendering/proxy_box.dart:116
#46     RenderObject.layout
package:flutter/…/rendering/object.dart:1858
#47     RenderProxyBoxMixin.performLayout
package:flutter/…/rendering/proxy_box.dart:116
#48     RenderObject.layout
package:flutter/…/rendering/object.dart:1858
#49     RenderProxyBoxMixin.performLayout
package:flutter/…/rendering/proxy_box.dart:116
#50     RenderObject.layout
package:flutter/…/rendering/object.dart:1858
#51     RenderView.performLayout
package:flutter/…/rendering/view.dart:165
#52     RenderObject._layoutWithoutResize
package:flutter/…/rendering/object.dart:1713
#53     PipelineOwner.flushLayout
package:flutter/…/rendering/object.dart:885
#54     RendererBinding.drawFrame
package:flutter/…/rendering/binding.dart:453
#55     WidgetsBinding.drawFrame
package:flutter/…/widgets/binding.dart:883
#56     RendererBinding._handlePersistentFrameCallback
package:flutter/…/rendering/binding.dart:319
#57     SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1143
#58     SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1080
#59     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure>
package:flutter/…/scheduler/binding.dart:863
(elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
The following RenderObject was being processed when the exception was fired: RenderStack#2a782 relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT
RenderObject: RenderStack#2a782 relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT
    parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
    constraints: BoxConstraints(0.0<=w<=392.7, 0.0<=h<=Infinity)
    size: MISSING
    alignment: Alignment.center
    textDirection: ltr
    fit: loose
════════════════════════════════════════════════════════════════════════════════
```

</details>

<details>
  <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 2.5.0-7.0.pre.83, on Microsoft Windows [Version 10.0.19041.1110], locale ru-RU)
    • Flutter version 2.5.0-7.0.pre.83 at C:\dev\src\flutter
    • Upstream repository git@github.com:nt4f04und/flutter.git
    • FLUTTER_GIT_URL = git@github.com:nt4f04und/flutter.git
    • Framework revision 06be7e5392 (4 hours ago), 2021-08-15 14:37:02 -0400
    • Engine revision 1af0a20793
    • Dart version 2.15.0 (build 2.15.0-15.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\danya\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.59.0)
    • VS Code at C:\Users\danya\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[√] Connected device (4 available)
    • Redmi Note 5 (mobile)   • 40c9f14       • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19041.1110]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 92.0.4515.131
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 92.0.902.67

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment]
Verified on latest master and stable and see the same behavior.

<details>
<summary>console error log</summary>


```
======== Exception caught by rendering library =====================================================
The following assertion was thrown during performLayout():
'package:flutter/src/rendering/stack.dart': Failed assertion: line 541 pos 14: 'constraints.biggest.isFinite': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  AnimatedSwitcher AnimatedSwitcher:file:///Users/dhs/Documents/NCFlutter/bug_test/lib/main.dart:39:11
When the exception was thrown, this was the stack: 
#2      RenderStack._computeSize (package:flutter/src/rendering/stack.dart:541:14)
#3      RenderStack.performLayout (package:flutter/src/rendering/stack.dart:597:12)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#5      ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
#6      RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:829:43)
#7      RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:931:32)
#8      RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#9      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#10     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#11     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#12     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#13     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#14     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#15     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#16     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#17     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
#18     RenderStack._computeSize (package:flutter/src/rendering/stack.dart:570:43)
#19     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:597:12)
#20     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#21     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#22     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#23     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#24     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#25     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#26     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#27     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#28     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#29     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#30     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#31     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#32     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#33     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#34     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3422:13)
#35     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#37     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#38     _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:745:15)
#39     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#40     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#41     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#42     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#43     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#44     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#45     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#46     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#47     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:545:11)
#48     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#49     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#50     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#51     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#52     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#53     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#54     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#55     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#56     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#57     RenderView.performLayout (package:flutter/src/rendering/view.dart:165:14)
#58     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1713:7)
#59     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:885:18)
#60     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:453:19)
#61     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#62     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
#63     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
#64     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1080:9)
#65     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:863:7)
(elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
The following RenderObject was being processed when the exception was fired: RenderStack#d600c relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT
...  parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
...  constraints: BoxConstraints(0.0<=w<=428.0, 0.0<=h<=Infinity)
...  size: MISSING
...  alignment: Alignment.center
...  textDirection: ltr
...  fit: loose
RenderObject: RenderStack#d600c relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT
  parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
  constraints: BoxConstraints(0.0<=w<=428.0, 0.0<=h<=Infinity)
  size: MISSING
  alignment: Alignment.center
  textDirection: ltr
  fit: loose
====================================================================================================



```


</details>

<details>
<summary> stable and master flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.2.3 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision f4abaa0735 (4 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dhs/Library/Android/sdk
    • Java binary at: /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.    

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • SM G975F (mobile) • RZ8M802WY0X • android-arm64 • Android 10 (API 29)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 91.0.4472.114

• No issues found!

[✓] Flutter (Channel master, 2.5.0-7.0.pre.187, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.5.0-7.0.pre.187 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 05bfbbfbec (4 hours ago), 2021-08-22 21:37:03 -0400
    • Engine revision 710af46d53
    • Dart version 2.15.0 (build 2.15.0-42.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dhs/Library/Android/sdk
    • Java binary at: /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.    

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • SM G975F (mobile) • RZ8M802WY0X • android-arm64 • Android 10 (API 29)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 91.0.4472.114






```

</details>

**Comment by bleroux** [comment]
This crash is related to unbounded constraints.
The error message should be improved to give more information.

The code sample could be fix in several ways, for instance :

<details>
<summary> By setting bounds with an `Expanded` parent</summary>

```dart
// Flutter code sample for AnimatedSwitcher
//
// This sample shows a counter that animates the scale of a text widget
// whenever the value changes.

import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

/// This is the main application widget.
class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: _title,
      home: MyStatefulWidget(),
    );
  }
}

/// This is the stateful widget that the main application instantiates.
class MyStatefulWidget extends StatefulWidget {
  const MyStatefulWidget({Key? key}) : super(key: key);

  @override
  State<MyStatefulWidget> createState() => _MyStatefulWidgetState();
}

/// This is the private State class that goes with MyStatefulWidget.
class _MyStatefulWidgetState extends State<MyStatefulWidget> {
  int _count = 0;

  @override
  Widget build(BuildContext context) {
    return Container(
      color: Colors.white,
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: <Widget>[
          Expanded(
            child: AnimatedSwitcher(
              duration: const Duration(milliseconds: 500),
              transitionBuilder: (Widget child, Animation<double> animation) {
                return ScaleTransition(child: child, scale: animation);
              },
              child: _count % 2 == 0 ? null : Text(
                '$_count',
                // This key causes the AnimatedSwitcher to interpret this as a "new"
                // child each time the count changes, so that it will begin its animation
                // when the count changes.
                key: ValueKey<int>(_count),
                style: Theme.of(context).textTheme.headline4,
              ),
            ),
          ),
          ElevatedButton(
            child: const Text('Increment'),
            onPressed: () {
              setState(() {
                _count += 1;
              });
            },
          ),
        ],
      ),
    );
  }
}
```
</details>

<details>
<summary> By adding an empty child to the `AnimatedSwitcher`</summary>

```dart
// Flutter code sample for AnimatedSwitcher
//
// This sample shows a counter that animates the scale of a text widget
// whenever the value changes.

import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

/// This is the main application widget.
class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: _title,
      home: MyStatefulWidget(),
    );
  }
}

/// This is the stateful widget that the main application instantiates.
class MyStatefulWidget extends StatefulWidget {
  const MyStatefulWidget({Key? key}) : super(key: key);

  @override
  State<MyStatefulWidget> createState() => _MyStatefulWidgetState();
}

/// This is the private State class that goes with MyStatefulWidget.
class _MyStatefulWidgetState extends State<MyStatefulWidget> {
  int _count = 0;

  @override
  Widget build(BuildContext context) {
    return Container(
      color: Colors.white,
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: <Widget>[
          AnimatedSwitcher(
            duration: const Duration(milliseconds: 500),
            transitionBuilder: (Widget child, Animation<double> animation) {
              return ScaleTransition(child: child, scale: animation);
            },
            child: _count % 2 == 0 ? const SizedBox.shrink() : Text(
              '$_count',
              // This key causes the AnimatedSwitcher to interpret this as a "new"
              // child each time the count changes, so that it will begin its animation
              // when the count changes.
              key: ValueKey<int>(_count),
              style: Theme.of(context).textTheme.headline4,
            ),
          ),
          ElevatedButton(
            child: const Text('Increment'),
            onPressed: () {
              setState(() {
                _count += 1;
              });
            },
          ),
        ],
      ),
    );
  }
}
```
</details>

**Comment by nt4f04uNd** [comment]
> This crash is related to unbounded constraints.

Wouldn it make sense for it to shrink itself automatically, as if we were passing `const SizedBox.shrink()` to the child?

**Comment by bleroux** [comment]
@nt4f04uNd
Yes it makes sense.
First I will publish a PR to improve the error message thrown when rendering an empty Stack with unbounded constraints.
And then I will try to make `AnimatedSwitcher` avoid this edge case.
