### ISSUE TITLE
While simulating different OS from live run it appears

### ISSUE THREAD

**Issue by iamworldian** [flutter/flutter#88597]
## command

flutter run

## exception

NoSuchMethodError: NoSuchMethodError: The getter 'isMacOSEnabled' was called on null.
Receiver: null
Tried calling: isMacOSEnabled

```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      nextPlatform (package:flutter_tools/src/resident_runner.dart:1703:24)
#2      ResidentWebRunner.debugTogglePlatform (package:flutter_tools/src/isolated/resident_web_runner.dart:309:31)
<asynchronous suspension>
#3      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1644:7)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale en_US.UTF-8)
    • Flutter version 2.2.3 at /home/iamworldian/Flutter/flutter_linux_2.2.3-stable/flutter
    • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/iamworldian/Android/Sdk/
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /home/iamworldian/Android/Sdk
    • ANDROID_SDK_ROOT = /home/iamworldian/Android/Sdk
    • Java binary at: /home/iamworldian/Downloads/android-studio-ide-202.7486908-linux/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /home/iamworldian/Downloads/android-studio-ide-202.7486908-linux/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] VS Code (version 1.59.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.25.0

[✓] Connected device (1 available)

**Comment by TahaTesser** [comment]
Hi @iamworldian 
"While simulating different OS from live run it appears"
Can you please explain what you're trying to achieve and describe the bug in detail

Can you please provide a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
