### ISSUE TITLE
video_player plugin is not working in iOS.

### ISSUE THREAD

**Issue by sptin** [flutter/flutter#88637]
I have written a Flutter app to show video. I use video_player plugin from https://pub.dev/packages/video_player. The app works well in Android simulator and Chrome browser but produced error when I run using iOS simulator.

What should I do to resolve the error??? Thank you.

Below is the output to the debug console: -

CocoaPods' output:
↳
      Preparing
    Analyzing dependencies
    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `video_player` from `.symlinks/plugins/video_player/ios`
    Resolving dependencies of `Podfile`

   MARKDOWN TEMPLATE――――――――――――――――――――――――――――――――――――――――――――
### Command
    ```
    /usr/local/bin/pod install --verbose
    ```
    ### Report
    * What did you do?
    * What did you expect to happen?
    * What happened instead?
    ### Stack
    ```
       CocoaPods : 1.10.2
            Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
        RubyGems : 3.0.3
            Host : macOS 11.4 (20F71)
           Xcode : 12.5.1 (12E507)
             Git : git version 2.30.1 (Apple Git-130)
    Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
    Repositories :
    ```
    ### Plugins
    ```
    cocoapods-deintegrate : 1.0.4
    cocoapods-plugins     : 1.0.0
    cocoapods-search      : 1.0.0
    cocoapods-trunk       : 1.5.0
    cocoapods-try         : 1.2.0
    ```
    ### Podfile
    ```ruby
    # Uncomment this line to define a global platform for your project
     platform :ios, '11'
    # CocoaPods analytics sends network stats synchronously affecting flutter build latency.
    ENV['COCOAPODS_DISABLE_STATS'] = 'true'
    project 'Runner', {
      'Debug' => :debug,
      'Profile' => :release,
      'Release' => :release,
    }
def flutter_root
      generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
      unless File.exist?(generated_xcode_build_settings_path)
        raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
      end
      File.foreach(generated_xcode_build_settings_path) do |line|
        matches = line.match(/FLUTTER_ROOT\=(.*)/)
        return matches[1].strip if matches
      end
      raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
    end
    require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)
    flutter_ios_podfile_setup
    target 'Runner' do
      use_frameworks!
      use_modular_headers!
      flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
    end
    post_install do |installer|
      installer.pods_project.targets.each do |target|
        flutter_additional_ios_build_settings(target)
      end
    end
    ```
    ### Error
    ```
    LoadError - dlopen(/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.3/lib/ffi_c.bundle, 9): no suitable image found.  Did find:
    	/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.3/lib/ffi_c.bundle: mach-o, but wrong architecture
    	/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.3/lib/ffi_c.bundle: mach-o, but wrong architecture - /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.3/lib/ffi_c.bundle
2
    /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.3/lib/ffi.rb:5:in `rescue in <top (required)>'
    /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.3/lib/ffi.rb:2:in `<top (required)>'
2
    /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    /Library/Ruby/Gems/2.6.0/gems/ethon-0.14.0/lib/ethon.rb:3:in `<top (required)>'
2
    /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    /Library/Ruby/Gems/2.6.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
2
    /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/sources_manager.rb:74:in `cdn_url?'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/sources_manager.rb:36:in `create_source_with_url'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/sources_manager.rb:21:in `find_or_create_source_with_url'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/installer/analyzer.rb:178:in `block in sources'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/installer/analyzer.rb:177:in `map'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/installer/analyzer.rb:177:in `sources'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/installer/analyzer.rb:1073:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/installer/analyzer.rb:1072:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/installer.rb:414:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/installer.rb:239:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/installer.rb:160:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'
    ```
   TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――
    [!] Oh no, an error occurred.
    Search for existing GitHub issues similar to yours: ........
    
Error output from CocoaPods:
↳
    Searching for inspections failed: undefined method `map' for nil:NilClass
Error running pod install
Error launching application on iPhone 11.
Exited (sigterm)

**Comment by zambetpentru** [comment]
Hi, 

To my knowledge the ios simulator is not supported,  there is an open issue detailing it.

**Comment by maheshmnj** [comment]
Hi @sptin, Thanks for filing the issue, Please share the output of `flutter doctor -v` along with the version of the video_player plugin that you are using and a [minimal reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) sample to better address the issue.

Thanks.

**Comment by sptin** [comment]
I am using Video Player version 2.1.14

I don't write any code, just trying it out using the code presented in pub.dev


Below please find the output from flutter doctor -v:
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-arm, locale en-CN)
    • Flutter version 2.2.3 at /Users/soonphei/Development/flutter
    • Framework revision f4abaa0735 (8 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/soonphei/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Community Edition (version 2021.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • iPhone 11 (mobile) • 5B2A6446-73FC-4218-879E-39216D0ABBAD • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 92.0.4515.159

**Comment by sptin** [comment]
I found that the plugin generated a generated_plugin_registrant.dart with the following context

//
// Generated file. Do not edit.
//

// ignore_for_file: lines_longer_than_80_chars

import 'package:shared_preferences_web/shared_preferences_web.dart';
import 'package:video_player_web/video_player_web.dart';

import 'package:flutter_web_plugins/flutter_web_plugins.dart';

// ignore: public_member_api_docs
void registerPlugins(Registrar registrar) {
  SharedPreferencesPlugin.registerWith(registrar);
  VideoPlayerPlugin.registerWith(registrar);
  registrar.registerMessageHandler();
}



When I open the project in Xcode, I got the following "Parse Issue" error in a file named GeneratedPluginRegistrant.m:

The error say "Module path_provider not found", it was referring the the following @import statement

....
#import "GeneratedPluginRegistrant.h"

#if __has_include(<path_provider/FLTPathProviderPlugin.h>)
#import <path_provider/FLTPathProviderPlugin.h>
#else
@import path_provider;
#endif
...
...

**Comment by maheshmnj** [comment]
@sptin,It looks like you are trying to launch the app in xcode, Does the ios app build fine when you run it directly from your IDE? 

to launch it from xcode make sure you are opening the `runner.xcworkspace`  please try this from the root of your project

```
flutter clean
flutter pub get
open ios/Runner.xcworkspace
run the app in xcode
```

**Comment by sptin** [comment]
@maheshmnj, thanks for your response. When I run in the IDE, Android (Simulator) and Chrome are fine but not iOS. I wanted to try it out on the physical device and therefore I try to deploy it to my iPhone using Xcode.

I was using the steps you mentioned above, but it build runner failed.

I am pretty sure that Video Player plugin is the one causing the error because I have tested the App with and without the plugin.

**Comment by maheshmnj** [comment]
@sptin To confirm the issue could you please try 

```
- create a new flutter project 
- add the video player plugin 
- update main.dart with video player sample
- run the app in xcode 
```

**Comment by sptin** [comment]
@maheshmnj, apologies. Could you please give me some guide on how to get a complete log? Thanks.

**Comment by maheshmnj** [comment]
@sptin when you build the app and it fails you should see some logs in the issue navigator on the left then tap on the issue to see the logs on the right (square box) and you could share that.



![Screenshot 2021-08-31 at 6 34 51 PM](https://user-images.githubusercontent.com/31410839/131507804-dd6b04e8-b155-411a-8f78-3992e1017de9.png)
*Example image attached*

**Comment by sptin** [comment]
Hahaha, sorry for such a silly question. Please see the attach image.

As you have advised, I created a brand new Flutter project with video_player sample in main.dart. Dependency has been added as well.

<img width="1008" alt="Screen Shot 2021-09-01 at 5 29 47 PM" src="https://user-images.githubusercontent.com/34881031/131648416-41b9ecd0-9173-4894-858e-719298aa7b4b.png">

**Comment by maheshmnj** [comment]
@sptin make sure you run pod install in ios folder.
Because when you run the app via editor flutter runs `pod install` for you but when you launch it through xcode you have to make sure pods are installed.
so close the xcode

```
cd your_project
cd ios
pod install
open Runner.xcworkspace
```
run the app in xcode.

**Comment by sptin** [comment]
@maheshmnj I run the pod install but found problem in Ruby interpreter. I check from the web and found that it was all caused by the incompatibility because I am using M1 process. Apple develop forum suggested to do the following which worked for me.

sudo arch -x86_64 gem install ffi
Then
arch -x86_64 pod install

Now my app can run on both physical device and iOS simulator. Many thanks for your helps and patient.

**Comment by sptin** [comment]
@maheshmnj I run the pod install but found problem in Ruby interpreter. I check from the web and found that it was all caused by the incompatibility because I am using M1 process. Apple develop forum suggested to do the following which worked for me.

sudo arch -x86_64 gem install ffi
Then
arch -x86_64 pod install

Now my app can run on both physical device and iOS simulator. Many thanks for your helps and patient.
