### ISSUE TITLE
[windows] desktop application freezes after extended period of computer sleep

### ISSUE THREAD

**Issue by Nealsoni00** [flutter/flutter#88649]
Only effected platform is `Windows`
## Issue

I install the flutter windows app exe onto a fresh windows computer. The app works fine as long as the computer is running. The computer goes to sleep after closing and when I open it up a few hours later, the window no longer responds to presses. After like 2 minutes of clicking on it, windows marks the window as (Not Responding). The memory usage of the window goes down to 2mb (instead of the initial 60-90mb). 

I have added Sentry to the project to catch all errors -- and no errors are logged to sentry at the time of the crash.

I have the same windows app installed on a desktop and when the desktop is put to sleep and awoken, there is no issue with the app not responding. The desktop is connected using ethernet. 

## Steps to Reproduce

1. I created a flutter windows project that has a few unique things:
- Uses [bitsdojo_window](https://github.com/bitsdojo/bitsdojo_window) for the windows window. 
- The app has a perpetual Websocket connection to a server to receive alerts using [`web_socket_channel`](https://pub.dev/packages/web_socket_channel). when the websocket disconnects, it attempts to reconnect every 15 seconds. This logic works properly when the computer's wifi is turned on and off. 
- The desktop app is also connected to a background application (scala) using a [`dart:io websocket`](https://api.dart.dev/stable/2.13.4/dart-io/WebSocket-class.html) connection. This logic follows a 10 second reconnect if not connected to socket. 
- I added a `runZonedGuarded()` around the runApp to catch all errors and prevent them from propagating up. Also added a ` FlutterError.onError` after `WidgetsFlutterBinding.ensureInitialized();` to catch all uncaught errors as well.
2. I build the app for production windows and packaged it into an MSI installer using Wix
3. Install and open application -- close the laptop and leave overnight (from testing seems like it needs 10 or so hours).

**Expected results:**
- The flutter windows application recovering from an extended period of suspension.  
- Either it recovered correctly OR the window closes on error and does not become unresponsive & hard to kill (if it could be closed easier that would be better)

**Actual results:**
- After an extended period of time (overnight) the app window becomes unresponsive and does not quit -- I have to go into activity monitor to quit it. 

## Ask
Any ideas on how to debug this issue, or experience dealing with similar issues would be greatly appreciated. The window suspending and not being able to close is an awful user experience since a naïve user can't do anything about it (ex: force quit the app). 

## Logs

Below are the file logs of the app becoming unresponsive on two computers:

**app becoming unresponsive on a laptop**
<details>
<summary>Flutter App Logs using `logger`</summary>

```

[2021-08-21 15:17:09.249576] [DEBUG ] ARGUMENTS [--port=8000]
[2021-08-21 15:17:09.251571] [DEBUG ] INITIALIZING APP STATE
[2021-08-21 15:17:09.251571] [DEBUG ] GETTING TOKEN FROM SECURE STORE
[2021-08-21 15:17:09.253565] [DEBUG ] HAS TOKEN? true
[2021-08-21 15:17:09.254564] [DEBUG ] GOT TOKEN FROM SECURE STORE
[2021-08-21 15:17:09.255559] [DEBUG ] Returning refresh token from dart client [REDACTED]
[2021-08-21 15:17:09.265533] [DEBUG ] [PORT] USING PASSED PORT: 8000
[2021-08-21 15:17:09.265533] [DEBUG ] [BACKGROUND-SOCKET] CONNECTING ws://localhost:8000/prepared
[2021-08-21 15:17:09.993587] [DEBUG ] [BACKGROUND-SOCKET] CONNECTED TO BACKGROUND SERVICE
[2021-08-21 15:17:10.263965] [VERBOS] [SECURE_STORE] SAVED [REFRESH, ACCESS] [REDACTED]
[2021-08-21 15:17:10.297841] [INFO  ] [GQL-OUTGOING] FetchAppData w/ NO LOCATION w/ [REDACTED]
[2021-08-21 15:17:10.328690] [VERBOS] [INITIAL_SCREEN] Setting user interface
[2021-08-21 15:17:10.338741] [DEBUG ] [BACKGROUND-SOCKET] SENT PAYLOAD! {type: token, value: [REDACTED], email: [REDACTED], name: [REDACTED], deviceId: [REDACTED], deviceType: desktop, environment: production}
[2021-08-21 15:17:10.489261] [DEBUG ] [API-SOCKET] connected
[2021-08-21 15:17:10.571042] [DEBUG ] [API-SOCKET] connected to Alert channel
[2021-08-21 15:17:38.611374] [VERBOS] [BACKGROUND-SOCKET] sent back pong
[2021-08-21 15:18:08.625201] [VERBOS] [BACKGROUND-SOCKET] sent back pong
[2021-08-21 15:18:11.624642] [INFO  ] LOCAL: false
[2021-08-21 15:18:38.641225] [VERBOS] [BACKGROUND-SOCKET] sent back pong
[2021-08-21 15:19:08.648202] [VERBOS] [BACKGROUND-SOCKET] sent back pong
[2021-08-21 15:19:38.655055] [VERBOS] [BACKGROUND-SOCKET] sent back pong
[2021-08-21 15:20:08.663898] [VERBOS] [BACKGROUND-SOCKET] sent back pong
[2021-08-21 15:20:38.678118] [VERBOS] [BACKGROUND-SOCKET] sent back pong
[2021-08-21 15:21:08.688904] [VERBOS] [BACKGROUND-SOCKET] sent back pong
[2021-08-21 15:21:38.688898] [VERBOS] [BACKGROUND-SOCKET] sent back pong
[2021-08-21 15:22:08.701040] [VERBOS] [BACKGROUND-SOCKET] sent back pong
[2021-08-21 15:22:38.703489] [VERBOS] [BACKGROUND-SOCKET] sent back pong
[2021-08-21 15:23:08.712246] [VERBOS] [BACKGROUND-SOCKET] sent back pong
[2021-08-21 15:23:38.725442] [VERBOS] [BACKGROUND-SOCKET] sent back pong
[2021-08-21 15:24:08.727909] [VERBOS] [BACKGROUND-SOCKET] sent back pong
[2021-08-21 15:24:38.747267] [VERBOS] [BACKGROUND-SOCKET] sent back pong
[2021-08-21 15:25:08.760976] [VERBOS] [BACKGROUND-SOCKET] sent back pong
[2021-08-21 15:25:38.766741] [VERBOS] [BACKGROUND-SOCKET] sent back pong
[2021-08-21 15:26:08.778345] [VERBOS] [BACKGROUND-SOCKET] sent back pong
[2021-08-21 15:26:38.778786] [VERBOS] [BACKGROUND-SOCKET] sent back pong
[2021-08-21 15:27:08.791363] [VERBOS] [BACKGROUND-SOCKET] sent back pong
[2021-08-21 15:27:38.802181] [VERBOS] [BACKGROUND-SOCKET] sent back pong
[2021-08-21 15:28:08.805848] [VERBOS] [BACKGROUND-SOCKET] sent back pong
[NO LOGS AFTER THIS TIME -- Assuming this is when the flutter app become unresponsive]

```
</details>

<details>
<summary>Background App (Scala) Logs for pinging flutter app to see if it's responsive</summary>

```

2021.08.21 15:17:08:394 [main      ] [INFO ]  [API-SOCKET].connect:49 - Connecting to ActionCable
2021.08.21 15:17:08:522 [scala-e...] [INFO ]  [API-SOCKET].verifyConnection:68 - Connecting to wss://api.preparedapp.com/cable?token=[REDACTED]...
2021.08.21 15:17:08:594 [scala-e...] [INFO ]  [API-SOCKET].verifyConnection:87 - Connection to ActionCable successfully established
2021.08.21 15:17:09:738 [scala-e...] [INFO ]  [BACKGROUND-SOCKET].Server.start:66 - Server started on HTTP localhost:8000
2021.08.21 15:17:09:891 [scala-e...] [INFO ]  [BACKGROUND-SOCKET].webSocketConnected:218 - WebSocket connection established!
2021.08.21 15:17:10:109 [EventLoop ] [INFO ]  [API-SOCKET].connected:93 - Connected
2021.08.21 15:17:10:130 [scala-e...] [INFO ]  [BACKGROUND-SOCKET].webSocketConnected:229 - WebSocket connection open!
2021.08.21 15:17:38:618 [XNIO-1 ...] [INFO ]  [BACKGROUND-SOCKET].processMessage:200 - Received PONG from Flutter client
2021.08.21 15:18:08:625 [XNIO-1 ...] [INFO ]  [BACKGROUND-SOCKET].processMessage:200 - Received PONG from Flutter client
2021.08.21 15:18:38:642 [XNIO-1 ...] [INFO ]  [BACKGROUND-SOCKET].processMessage:200 - Received PONG from Flutter client
2021.08.21 15:19:08:649 [XNIO-1 ...] [INFO ]  [BACKGROUND-SOCKET].processMessage:200 - Received PONG from Flutter client
2021.08.21 15:19:38:656 [XNIO-1 ...] [INFO ]  [BACKGROUND-SOCKET].processMessage:200 - Received PONG from Flutter client
2021.08.21 15:20:08:663 [XNIO-1 ...] [INFO ]  [BACKGROUND-SOCKET].processMessage:200 - Received PONG from Flutter client
2021.08.21 15:20:38:679 [XNIO-1 ...] [INFO ]  [BACKGROUND-SOCKET].processMessage:200 - Received PONG from Flutter client
2021.08.21 15:21:08:689 [XNIO-1 ...] [INFO ]  [BACKGROUND-SOCKET].processMessage:200 - Received PONG from Flutter client
2021.08.21 15:21:38:688 [XNIO-1 ...] [INFO ]  [BACKGROUND-SOCKET].processMessage:200 - Received PONG from Flutter client
2021.08.21 15:22:08:702 [XNIO-1 ...] [INFO ]  [BACKGROUND-SOCKET].processMessage:200 - Received PONG from Flutter client
2021.08.21 15:22:38:704 [XNIO-1 ...] [INFO ]  [BACKGROUND-SOCKET].processMessage:200 - Received PONG from Flutter client
2021.08.21 15:23:08:712 [XNIO-1 ...] [INFO ]  [BACKGROUND-SOCKET].processMessage:200 - Received PONG from Flutter client
2021.08.21 15:23:38:726 [XNIO-1 ...] [INFO ]  [BACKGROUND-SOCKET].processMessage:200 - Received PONG from Flutter client
2021.08.21 15:24:08:728 [XNIO-1 ...] [INFO ]  [BACKGROUND-SOCKET].processMessage:200 - Received PONG from Flutter client
2021.08.21 15:24:38:747 [XNIO-1 ...] [INFO ]  [BACKGROUND-SOCKET].processMessage:200 - Received PONG from Flutter client
2021.08.21 15:25:08:762 [XNIO-1 ...] [INFO ]  [BACKGROUND-SOCKET].processMessage:200 - Received PONG from Flutter client
2021.08.21 15:25:38:766 [XNIO-1 ...] [INFO ]  [BACKGROUND-SOCKET].processMessage:200 - Received PONG from Flutter client
2021.08.21 15:26:08:779 [XNIO-1 ...] [INFO ]  [BACKGROUND-SOCKET].processMessage:200 - Received PONG from Flutter client
2021.08.21 15:26:38:781 [XNIO-1 ...] [INFO ]  [BACKGROUND-SOCKET].processMessage:200 - Received PONG from Flutter client
2021.08.21 15:27:08:792 [XNIO-1 ...] [INFO ]  [BACKGROUND-SOCKET].processMessage:200 - Received PONG from Flutter client
2021.08.21 15:27:38:803 [XNIO-1 ...] [INFO ]  [BACKGROUND-SOCKET].processMessage:200 - Received PONG from Flutter client
2021.08.21 15:28:38:806 [scala-e...] [WARN ]  [BACKGROUND-SOCKET].delayedPing:100 - No response for 60.002 seconds. Closing connection...
2021.08.21 15:28:38:815 [scala-e...] [INFO ]  [BACKGROUND-SOCKET].disconnect:175 - Disconnecting WebSocket connection
2021.08.21 15:28:38:825 [scala-e...] [INFO ]  [BACKGROUND-SOCKET].webSocketConnected:235 - WebSocket connection closed!
2021.08.21 15:30:38:852 [XNIO-1 ...] [WARN ]  [BACKGROUND-SOCKET].webSocketConnected:223 - WebSocket error, closing connection!
2021.08.21 23:38:47:013 [EventLoop ] [ERROR]  [API-SOCKET].failed:115 - Failed!
com.hosopy.actioncable.ActionCableException: java.net.SocketTimeoutException: Read timed out
	at com.hosopy.actioncable.Consumer$1.onFailure(Consumer.java:44)
	at com.hosopy.actioncable.Connection$4$2.run(Connection.java:268)
	at com.hosopy.concurrent.EventLoop$2.run(EventLoop.java:69)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(null)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(null)
	at java.lang.Thread.run(null)
2021.08.21 23:38:47:057 [EventLoop ] [INFO ]  [API-SOCKET].connect:49 - Connecting to ActionCable
2021.08.21 23:39:08:013 [scala-e...] [INFO ]  [API-SOCKET].verifyConnection:68 - Connecting to wss://api.preparedapp.com/cable?token=[REDACTED]...
2021.08.21 23:39:08:013 [scala-e...] [INFO ]  [API-SOCKET].verifyConnection:87 - Connection to ActionCable successfully established
2021.08.21 23:39:08:364 [EventLoop ] [INFO ]  [API-SOCKET].connected:93 - Connected

```

</details>

**App becoming unresponsive on a desktop**

<details>
<summary>Flutter App Logs using `logger`</summary>

```

[2021-08-21 15:09:06.792631] [DEBUG ] ARGUMENTS [--port=8000]
[2021-08-21 15:09:06.793633] [DEBUG ] INITIALIZING APP STATE
[2021-08-21 15:09:06.793633] [DEBUG ] GETTING TOKEN FROM SECURE STORE
[2021-08-21 15:09:06.794631] [DEBUG ] HAS TOKEN? true
[2021-08-21 15:09:06.795632] [DEBUG ] GOT TOKEN FROM SECURE STORE
[2021-08-21 15:09:06.795632] [DEBUG ] Returning refresh token from dart client [REDACTED]
[2021-08-21 15:09:06.795632] [DEBUG ] GEOLOCATION API IS NOT ENABLED FOR PLATFORM
[2021-08-21 15:09:06.803630] [DEBUG ] [PORT] USING PASSED PORT: 8000
[2021-08-21 15:09:06.803630] [DEBUG ] [BACKGROUND-SOCKET] CONNECTING ws://localhost:8000/prepared
[2021-08-21 15:09:07.468962] [DEBUG ] [BACKGROUND-SOCKET] CONNECTED TO BACKGROUND SERVICE
[2021-08-21 15:09:07.774625] [VERBOS] [SECURE_STORE] SAVED [REFRESH, ACCESS] [REDACTED]
[2021-08-21 15:09:07.789619] [DEBUG ] NAME Neal-Windows-10-DESKTOP env neals
[2021-08-21 15:09:07.789619] [INFO  ] [GQL-OUTGOING] FetchAppData w/ NO LOCATION w/ [REDACTED]
[2021-08-21 15:09:07.790619] [VERBOS] [INITIAL_SCREEN] Setting user interface
[2021-08-21 15:09:07.790619] [INFO  ] [GQL-OUTGOING] UserDeviceInfo w/ NO LOCATION w/ [REDACTED]
[2021-08-21 15:09:07.794619] [DEBUG ] [BACKGROUND-SOCKET] SENT PAYLOAD! {type: token, value: [REDACTED], email: [REDACTED], name: [REDACTED], deviceId: [REDACTED], deviceType: desktop, environment: production}
[2021-08-21 15:09:07.931870] [DEBUG ] [API-SOCKET] connected
[2021-08-21 15:09:08.047457] [DEBUG ] [API-SOCKET] connected to Alert channel
[2021-08-21 15:09:10.261353] [INFO  ] [GQL-OUTGOING] FetchSchoolSafetyStats w/ NO LOCATION w/ [REDACTED]
[2021-08-21 15:09:11.546225] [INFO  ] [GQL-OUTGOING] FetchHeadcounts w/ NO LOCATION w/ [REDACTED]
[2021-08-21 15:09:11.547224] [INFO  ] [GQL-OUTGOING] FetchHeadcountNotSubmitted w/ NO LOCATION w/ [REDACTED]
[2021-08-21 15:09:36.511937] [VERBOS] [BACKGROUND-SOCKET] sent back pong
[2021-08-21 15:10:06.516896] [VERBOS] [BACKGROUND-SOCKET] sent back pong
[2021-08-21 15:10:09.108318] [INFO  ] [GQL-OUTGOING] FetchSchoolSafetyStats w/ NO LOCATION w/ [REDACTED]
[2021-08-21 15:10:36.528941] [VERBOS] [BACKGROUND-SOCKET] sent back pong
[2021-08-21 15:11:06.532243] [VERBOS] [BACKGROUND-SOCKET] sent back pong
[2021-08-21 15:11:36.533457] [VERBOS] [BACKGROUND-SOCKET] sent back pong
[2021-08-21 15:12:06.533505] [VERBOS] [BACKGROUND-SOCKET] sent back pong
[2021-08-21 15:12:36.533544] [VERBOS] [BACKGROUND-SOCKET] sent back pong
[2021-08-21 15:13:06.548474] [VERBOS] [BACKGROUND-SOCKET] sent back pong
[2021-08-21 15:13:36.561068] [VERBOS] [BACKGROUND-SOCKET] sent back pong
[2021-08-21 15:14:06.570735] [VERBOS] [BACKGROUND-SOCKET] sent back pong
[2021-08-21 15:14:36.583334] [VERBOS] [BACKGROUND-SOCKET] sent back pong
[2021-08-21 15:15:06.583580] [VERBOS] [BACKGROUND-SOCKET] sent back pong
[2021-08-21 15:15:36.591908] [VERBOS] [BACKGROUND-SOCKET] sent back pong
[2021-08-21 15:16:06.595700] [VERBOS] [BACKGROUND-SOCKET] sent back pong
[2021-08-21 15:16:36.597214] [VERBOS] [BACKGROUND-SOCKET] sent back pong
[2021-08-21 15:17:06.598997] [VERBOS] [BACKGROUND-SOCKET] sent back pong
[2021-08-21 15:17:36.613866] [VERBOS] [BACKGROUND-SOCKET] sent back pong
[2021-08-21 15:18:06.627925] [VERBOS] [BACKGROUND-SOCKET] sent back pong
[2021-08-21 15:18:36.629938] [VERBOS] [BACKGROUND-SOCKET] sent back pong
[2021-08-21 15:19:06.636982] [VERBOS] [BACKGROUND-SOCKET] sent back pong
[2021-08-21 15:19:36.638024] [VERBOS] [BACKGROUND-SOCKET] sent back pong

[NO LOGS AFTER THIS TIME -- Assuming this is when the flutter app become unresponsive]

```
</details>

<details>
<summary>Background App (Scala) Logs for pinging flutter app to see if it's responsive</summary>

```

2021.08.21 15:09:06:336 [main      ] [INFO ] [API-SOCKET].connect:49 - Connecting to ActionCable
2021.08.21 15:09:06:423 [scala-e...] [INFO ] [API-SOCKET].verifyConnection:68 - Connecting to wss://api.preparedapp.com/cable?token=[REDACTED]...
2021.08.21 15:09:06:463 [scala-e...] [INFO ] [API-SOCKET].verifyConnection:87 - Connection to ActionCable successfully established
2021.08.21 15:09:06:855 [scala-e...] [INFO ] [BACKGROUND-SOCKET].start:66 - Server started on HTTP localhost:8000
2021.08.21 15:09:07:118 [EventLoop ] [INFO ] [API-SOCKET].connected:93 - Connected
2021.08.21 15:09:07:423 [scala-e...] [INFO ] [BACKGROUND-SOCKET].webSocketConnected:218 - WebSocket connection established!
2021.08.21 15:09:07:486 [scala-e...] [INFO ] [BACKGROUND-SOCKET].webSocketConnected:229 - WebSocket connection open!
2021.08.21 15:09:36:517 [XNIO-1 ...] [INFO ] [BACKGROUND-SOCKET].processMessage:200 - Received PONG from Flutter client
2021.08.21 15:10:06:516 [XNIO-1 ...] [INFO ] [BACKGROUND-SOCKET].processMessage:200 - Received PONG from Flutter client
2021.08.21 15:10:36:531 [XNIO-1 ...] [INFO ] [BACKGROUND-SOCKET].processMessage:200 - Received PONG from Flutter client
2021.08.21 15:11:06:533 [XNIO-1 ...] [INFO ] [BACKGROUND-SOCKET].processMessage:200 - Received PONG from Flutter client
2021.08.21 15:11:36:534 [XNIO-1 ...] [INFO ] [BACKGROUND-SOCKET].processMessage:200 - Received PONG from Flutter client
2021.08.21 15:12:06:534 [XNIO-1 ...] [INFO ] [BACKGROUND-SOCKET].processMessage:200 - Received PONG from Flutter client
2021.08.21 15:12:36:534 [XNIO-1 ...] [INFO ] [BACKGROUND-SOCKET].processMessage:200 - Received PONG from Flutter client
2021.08.21 15:13:06:549 [XNIO-1 ...] [INFO ] [BACKGROUND-SOCKET].processMessage:200 - Received PONG from Flutter client
2021.08.21 15:13:36:562 [XNIO-1 ...] [INFO ] [BACKGROUND-SOCKET].processMessage:200 - Received PONG from Flutter client
2021.08.21 15:14:06:572 [XNIO-1 ...] [INFO ] [BACKGROUND-SOCKET].processMessage:200 - Received PONG from Flutter client
2021.08.21 15:14:36:584 [XNIO-1 ...] [INFO ] [BACKGROUND-SOCKET].processMessage:200 - Received PONG from Flutter client
2021.08.21 15:15:06:584 [XNIO-1 ...] [INFO ] [BACKGROUND-SOCKET].processMessage:200 - Received PONG from Flutter client
2021.08.21 15:15:36:592 [XNIO-1 ...] [INFO ] [BACKGROUND-SOCKET].processMessage:200 - Received PONG from Flutter client
2021.08.21 15:16:06:596 [XNIO-1 ...] [INFO ] [BACKGROUND-SOCKET].processMessage:200 - Received PONG from Flutter client
2021.08.21 15:16:36:598 [XNIO-1 ...] [INFO ] [BACKGROUND-SOCKET].processMessage:200 - Received PONG from Flutter client
2021.08.21 15:17:06:599 [XNIO-1 ...] [INFO ] [BACKGROUND-SOCKET].processMessage:200 - Received PONG from Flutter client
2021.08.21 15:17:36:614 [XNIO-1 ...] [INFO ] [BACKGROUND-SOCKET].processMessage:200 - Received PONG from Flutter client
2021.08.21 15:18:06:628 [XNIO-1 ...] [INFO ] [BACKGROUND-SOCKET].processMessage:200 - Received PONG from Flutter client
2021.08.21 15:18:36:630 [XNIO-1 ...] [INFO ] [BACKGROUND-SOCKET].processMessage:200 - Received PONG from Flutter client
2021.08.21 15:19:06:637 [XNIO-1 ...] [INFO ] [BACKGROUND-SOCKET].processMessage:200 - Received PONG from Flutter client
2021.08.21 15:20:36:650 [scala-e...] [WARN ] [BACKGROUND-SOCKET].delayedPing:100 - No response for 90.011 seconds. Closing connection...
2021.08.21 15:20:36:656 [scala-e...] [INFO ] [BACKGROUND-SOCKET].disconnect:175 - Disconnecting WebSocket connection
2021.08.21 15:20:36:661 [scala-e...] [INFO ] [BACKGROUND-SOCKET].webSocketConnected:235 - WebSocket connection closed!
2021.08.21 15:22:36:677 [XNIO-1 ...] [WARN ] [BACKGROUND-SOCKET].webSocketConnected:223 - WebSocket error, closing connection!
2021.08.22 11:01:02:817 [EventLoop ] [ERROR] [API-SOCKET].failed:115 - Failed!
com.hosopy.actioncable.ActionCableException: java.net.SocketTimeoutException: Read timed out
	at com.hosopy.actioncable.Consumer$1.onFailure(Consumer.java:44)
	at com.hosopy.actioncable.Connection$4$2.run(Connection.java:268)
	at com.hosopy.concurrent.EventLoop$2.run(EventLoop.java:69)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(null)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(null)
	at java.lang.Thread.run(null)

2021.08.22 11:01:02:844 [EventLoop ] [INFO ] [API-SOCKET].connect:49 - Connecting to ActionCable
2021.08.22 11:01:20:521 [scala-e...] [INFO ] [API-SOCKET].verifyConnection:68 - Connecting to wss://api.preparedapp.com/cable?token=[REDACTED]...
2021.08.22 11:01:20:522 [scala-e...] [INFO ] [API-SOCKET].verifyConnection:87 - Connection to ActionCable successfully established
2021.08.22 11:01:20:918 [EventLoop ] [INFO ] [API-SOCKET].connected:93 - Connected

```

</details>

In the logs you can see the scala app was able to become responsive after the computer woke up from sleep (and connect to the API-SOCKET) but the flutter app did  not. The Background Scala task also went to sleep after the flutter task both times. 

## Flutter doctor
```
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1200], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.4)
[√] Android Studio (version 4.1.0)
[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
[√] Connected device (4 available)
```

</details>

**Comment by TahaTesser** [comment]
Hi @Nealsoni00 

> 
> Uses bitsdojo_window for the windows window.
> The app has a perpetual Websocket connection to a server to receive alerts using web_socket_channel. when the websocket disconnects, it attempts to reconnect every 15 seconds. This logic works properly when the computer's wifi is turned on and off.
> The desktop app is also connected to a background application (scala) using a dart:io websocket connection. This logic follows a 10 second reconnect if not connected to socket.
> I added a runZonedGuarded() around the runApp to catch all errors and prevent them from propagating up. Also added a FlutterError.onError after WidgetsFlutterBinding.ensureInitialized(); to catch all uncaught errors as well.


Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) in a repository that has this code and implementation required for this reproduciton 
Thank you

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
