### ISSUE TITLE
ScrollController doesn't work with dismantle widgets

### ISSUE THREAD

**Issue by Sh00ny** [flutter/flutter#88659]
ScrollController is working perfectly fine when the body widget, BottomNavigationBar widget, and logic are inside one class i.e HomeScreen. But when I place those widgets in different files to be well organized it throws an errors
```
[The following assertion was thrown while handling a gesture:
ScrollController not attached to any scroll views.
'package:flutter/src/widgets/scroll_controller.dart':
Failed assertion: line 171 pos 12: '_positions.isNotEmpty'

When the exception was thrown, this was the stack: 
#2      ScrollController.jumpTo (package:flutter/src/widgets/scroll_controller.dart:171:12)
#3      HomeBody.scrollUp (package:dummy_app/Widgets/HomeBody.dart:15:23)
#4      MyBottomNavBar.build.<anonymous closure> (package:dummy_app/Widgets/BottomNavBar.dart:12:21)
#5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:607:11)
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#a0153
  debugOwner: GestureDetector
  state: possible
  won arena
  finalPosition: Offset(216.5, 868.5)
  finalLocalPosition: Offset(216.5, 20.5)
  button: 1
  sent tap down]([url](URL))
```

With the code below it works perfectly
```
[import 'package:dummy_app/Controller/FirebaseController.dart';
import 'package:dummy_app/Widgets/BottomNavBar.dart';
import 'package:dummy_app/Widgets/HomeBody.dart';
import 'package:dummy_app/models/NewsModel.dart';
import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:get/get.dart';

class HomeScreen extends StatelessWidget {
  //
  final _controller = Get.find<FirebaseController>();

  //
  ScrollController _scrollController = ScrollController();

  //
  void scrollUp() {
    _scrollController.jumpTo(0);
    print('scrollUPFun');
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('The Dummy App'),
      ),
      bottomNavigationBar: Container(
        child: GestureDetector(
          onTap: () {
            scrollUp();
            print('tapped');
          },
          child: Chip(
            label: Text('News'),
          ),
        ),
      ),
      body: SingleChildScrollView(
        controller: _scrollController,
        child: Container(
          child: StreamBuilder<DocumentSnapshot>(
            stream: _controller.streambuilder(),
            builder: (context, snapshot) {
              String _todayString = snapshot.data!['today'];
              String _yesterdayString = snapshot.data!['yesterday'];
              List _mapDataList1 = snapshot.data![_todayString];
              List _mapDataList2 = snapshot.data![_yesterdayString];
              return Column(
                children: [
                  ListView.builder(
                    controller: _scrollController,
                    shrinkWrap: true,
                    physics: NeverScrollableScrollPhysics(),
                    itemCount: _mapDataList1.length,
                    itemBuilder: (context, index) {
                      return MyContainer(
                        title: _mapDataList1[index]['title'],
                        titleImage: _mapDataList1[index]['titleImage'],
                      );
                    },
                  ),
                  ListView.builder(
                    shrinkWrap: true,
                    physics: NeverScrollableScrollPhysics(),
                    itemCount: _mapDataList2.length,
                    itemBuilder: (context, index) {
                      return MyContainer(
                        title: _mapDataList2[index]['title'],
                        titleImage: _mapDataList2[index]['titleImage'],
                      );
                    },
                  ),
                ],
              );
            },
          ),
        ),
      ),
    );
  }
}]
```

It doesn't work with this code as I placed every widget in an individual file

```
// HomeScreen
class HomeScreen extends StatelessWidget {
  HomeBody _homeBody = HomeBody();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('The Dummy App'),
      ),
      bottomNavigationBar: MyBottomNavBar(),
      body: HomeBody(),
    );
  }
}
```
```
// Homebody widget file
class HomeBody extends StatelessWidget {
  //
  final _controller = Get.find<FirebaseController>();

  //
  ScrollController _scrollController = ScrollController();

  //
  void scrollUp() {
    _scrollController.jumpTo(0);
    print('scrollUPFun');
  }

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      controller: _scrollController,
      child: Container(
        child: StreamBuilder<DocumentSnapshot>(
          stream: _controller.streambuilder(),
          builder: (context, snapshot) {
            String _todayString = snapshot.data!['today'];
            String _yesterdayString = snapshot.data!['yesterday'];
            List _mapDataList1 = snapshot.data![_todayString];
            List _mapDataList2 = snapshot.data![_yesterdayString];
            return Column(
              children: [
                ListView.builder(
                  controller: _scrollController,
                  shrinkWrap: true,
                  physics: NeverScrollableScrollPhysics(),
                  itemCount: _mapDataList1.length,
                  itemBuilder: (context, index) {
                    return MyContainer(
                      title: _mapDataList1[index]['title'],
                      titleImage: _mapDataList1[index]['titleImage'],
                    );
                  },
                ),
                ListView.builder(
                  shrinkWrap: true,
                  physics: NeverScrollableScrollPhysics(),
                  itemCount: _mapDataList2.length,
                  itemBuilder: (context, index) {
                    return MyContainer(
                      title: _mapDataList2[index]['title'],
                      titleImage: _mapDataList2[index]['titleImage'],
                    );
                  },
                ),
              ],
            );
          },
        ),
      ),
    );
  }
}

//
class MyContainer extends StatelessWidget {
  late String title;
  late String titleImage;
  MyContainer({required this.title, required this.titleImage});

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(8.0),
      child: Card(
        elevation: 5,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(12.0),
        ),
        child: Stack(
          alignment: Alignment.bottomCenter,
          children: [
            Container(
              height: 250.0,
              width: double.infinity,
              decoration: BoxDecoration(
                borderRadius: BorderRadius.circular(12.0),
                image: DecorationImage(
                  fit: BoxFit.cover,
                  image: NetworkImage(titleImage),
                ),
              ),
            ),
            Container(
              decoration: BoxDecoration(
                color: Colors.white.withOpacity(0.9),
                borderRadius: BorderRadius.only(
                  bottomRight: Radius.circular(12),
                  bottomLeft: Radius.circular(12),
                ),
              ),
              child: ListTile(
                title: Text(title),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```
```
// Bottom Nav widget file
class MyBottomNavBar extends StatelessWidget {
  HomeBody _homeBody = HomeBody();
  @override
  Widget build(BuildContext context) {
    return Container(
      child: GestureDetector(
        onTap: () {
          _homeBody.scrollUp();
          print('tapped');
        },
        child: Chip(
          label: Text('News'),
        ),
      ),
    );
  }
}
```

PS:  I think the scrollUp() method is not working.

**Comment by darshankawar** [comment]
@Sh00ny 
Can you provide `flutter doctor -v` along with a minimal code sample without any 3rd party plugin code ?
I see from your sample above that you are using `cloud_firestore` and `get`, so please provide an updated code sample without those plugin code.
Thanks.

**Comment by Sh00ny** [comment]
> @Sh00ny
> Can you provide `flutter doctor -v` along with a minimal code sample without any 3rd party plugin code ?
> I see from your sample above that you are using `cloud_firestore` and `get`, so please provide an updated code sample without those plugin code.
> Thanks.

```
shoony@Shoonys-MacBook-Air dummy_app % flutter doctor -v
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.1 20G80 darwin-arm, locale en-US)
    • Flutter version 2.2.3 at /Users/shoony/Developer/flutter
    • Framework revision f4abaa0735 (8 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/shoony/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (2 available)
    • iPhone 11 (mobile) • A36F7F3C-13BE-44B3-A4AD-EF9D0DB7DD44 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)       • chrome                               • web-javascript •
      Google Chrome 92.0.4515.159

• No issues found!
```

**Comment by Sh00ny** [comment]
There is nothing more to the code @darshankawar just a Controller. Everything is working when I placed all the widgets in a single widget/page/scaffold but when I put them in the different file it doesn't work.

Here the controller code

```
class FirebaseController extends GetxController {
  @override

  // Stream for StreamBuilder
  Stream<DocumentSnapshot> streambuilder() {
    return FirebaseFirestore.instance
        .collection('news')
        .doc('Business')
        .snapshots();
  }
}

**Comment by davidmartos96** [comment]
@Sh00ny The problem is how you are communicating the different widgets.
To begin with, you shouldn't do this:

```dart
class MyBottomNavBar extends StatelessWidget {
  HomeBody _homeBody = HomeBody(); // This line is wrong
```

Widgets are a piece of your UI, you cannot create one in one place and the same on in another and then call a method. A widget is built, and you should return it in the `build` function.
That being said, you should read through this https://flutter.dev/docs/development/data-and-backend/state-mgmt/simple

It goes into anti patterns like the one you are using (here https://flutter.dev/docs/development/data-and-backend/state-mgmt/simple#lifting-state-up) and it describes a simple way to send data and event across different widgets.

**Comment by Sh00ny** [comment]
Thank you. May you please suggest how can I work around it? I tried the constructor but doesn't work. May you please? @davidmartos96

**Comment by davidmartos96** [comment]
@Sh00ny There are different ways to solve it. The important thing is to know the concepts and how the different types of widgets work and how to pass data around.

One way, without any external package would be via a callback and "Lifting the state up". In your example, the ScrollController is shared, you need to declare it above, and inside a StatefulWidget's State because you only want to create it once.

```dart
class _HomeScreenState extends State<HomeScreen> {
  final ScrollController controller = ScrollController();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('The Dummy App'),
      ),
      bottomNavigationBar: MyBottomNavBar(
        onTap: () {
          controller.jumpTo(0);
        }
      ),
      body: HomeBody(controller),
    );
  }
}
```

**Comment by Sh00ny** [comment]
I tried your method, But now the error is gone but the controller still not working
Kindly check the code @davidmartos96 

HomeScreen
```
// HomeScreen File
class HomeScreen extends StatelessWidget {
  final ScrollController controller = ScrollController();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('The Dummy App'),
      ),
      bottomNavigationBar: MyBottomNavBar(
        ontap: () {
          controller.jumpTo(0);
        },
      ),
      body: HomeBody(
        controller: controller,
      ),
    );
  }
}
```

Homebody
```
// Homebody widget file
class HomeBody extends StatelessWidget {
  final _controller = Get.find<FirebaseController>();

  late final ScrollController controller;
  HomeBody({required this.controller});

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      controller: controller,
      child: Container(
        child: StreamBuilder<DocumentSnapshot>(
          stream: _controller.streambuilder(),
          builder: (context, snapshot) {
            String _todayString = snapshot.data!['today'];
            String _yesterdayString = snapshot.data!['yesterday'];
            List _mapDataList1 = snapshot.data![_todayString];
            List _mapDataList2 = snapshot.data![_yesterdayString];
            return Column(
              children: [
                ListView.builder(
                  controller: controller,
                  shrinkWrap: true,
                  physics: NeverScrollableScrollPhysics(),
                  itemCount: _mapDataList1.length,
                  itemBuilder: (context, index) {
                    return MyContainer(
                      title: _mapDataList1[index]['title'],
                      titleImage: _mapDataList1[index]['titleImage'],
                    );
                  },
                ),
                ListView.builder(
                  shrinkWrap: true,
                  physics: NeverScrollableScrollPhysics(),
                  itemCount: _mapDataList2.length,
                  itemBuilder: (context, index) {
                    return MyContainer(
                      title: _mapDataList2[index]['title'],
                      titleImage: _mapDataList2[index]['titleImage'],
                    );
                  },
                ),
              ],
            );
          },
        ),
      ),
    );
  }
}
```

MyBottomNavBar
```
// Bottom Nav widget file
class MyBottomNavBar extends StatelessWidget {
  late Function ontap;

  MyBottomNavBar({required this.ontap});
  @override
  Widget build(BuildContext context) {
    return Container(
      child: GestureDetector(
        onTap: ontap(),
        child: Chip(
          label: Text('News'),
        ),
      ),
    );
  }
```

**Comment by davidmartos96** [comment]
@Sh00ny Never pass `Function` as an argument. There are better ways to define a function with the arguments and types you expect.

`final void Function() onTap;`

or

`final VoidCallback onTap;`

And then 
```dart
child: GestureDetector(
  onTap: onTap
```

Also, watch out with creating the ScrollController in a StatelessWIdget. It makes more sense using statefulWidget so that the scroll controller state is preserved until the widget is removed from your UI.

I encourage you to read through the Dart docs https://dart.dev/guides/language/language-tour and Flutter docs https://flutter.dev/docs for these kind of questions or StackOverflow. Issues here should be reserved for bug reports.

**Comment by Sh00ny** [comment]
Thank you for the advice. I did read the docs and learned few new things. I even have a question on StackOverflow regarding this and I appreciate your time. But the problem is I'm not getting any errors. I changed my code as per your guidance it did work in the dummy app but it doesn't respond in the production app. 

Kindly go once through it.

HomeScreen
```
class HomeScreen extends StatelessWidget {
  final dataController = Get.put(DataController());
  //
  final ScrollController scrollcontroller = ScrollController();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: homeScreenAppBar(context),
      endDrawer: menuDrawer(context),
      body: HomeBody(
        scrollController1: scrollcontroller,
      ),
      bottomNavigationBar: MyBottomNavBar(
        ontap: () {
          scrollcontroller.jumpTo(0);
        },
      ),
    );
  }
}
```
HomeBody
```
class HomeBody extends StatelessWidget {
  //
  final _controller = Get.find<Controller>();

  //
  final _firebaseDatabase = Get.find<FirebaseDataController>();

  // AdMob Controller
  final _adMobController = Get.find<AdMobController>();

  // ScrollController
  final ScrollController scrollController1;

  HomeBody({this.scrollController1});

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      controller: scrollController1,
      child: Container(
        child: GetBuilder<Controller>(
          builder: (_) => StreamBuilder<DocumentSnapshot>(
            stream: _controller.stream(),
            builder: (context, snapshot) {
              if (!snapshot.hasData) {
                return Center(child: CircularProgressIndicator());
              } else if (snapshot.hasError) {
                return Text(
                    'Sorry, Something went wrong!\nVisit www.brief9.com');
              } else if (snapshot.connectionState == ConnectionState.done) {}

              /// Function to assign values to data Fields
              _firebaseDatabase.setdataFields(snapshot.data);
              // String _todayString = snapshot.data['today'];
              // String _yesterdayString = snapshot.data['yesterday'] ?? null;
              // List _mapDataList1 = snapshot.data[_todayString];
              // List _mapDataList2 = snapshot.data[_yesterdayString] ?? null;
              return Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  /// ----------------------------   List one with banner ad
                  ListView.builder(
                    controller: scrollController1,
                    physics: NeverScrollableScrollPhysics(),
                    shrinkWrap: true,
                    itemCount: _firebaseDatabase.mapDataList1.length,
                    itemBuilder: (context, index) {
                      return MyContainer(
                        title: _firebaseDatabase.mapDataList1[index]['title'] ??
                            'Loading...',
                        titleImage: _firebaseDatabase.mapDataList1[index]
                                ['titleImage'] ??
                            _firebaseDatabase.mapDataList1[index]['titleImage'],
                        imageSource: _firebaseDatabase.mapDataList1[index]
                                ['imageSource'] ??
                            '',
                        index: index,
                        context: context,
                      );
                    },
                  ),

                  /// Banner Ad
                  _adMobController.adErrorHome
                      ? Container()
                      : Padding(
                          padding: EdgeInsets.symmetric(
                            horizontal: 0.6.h,
                            vertical: 0.7.h,
                          ),
                          child: Card(
                            elevation: 5,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(12.0),
                            ),
                            child: Container(
                              alignment: Alignment.center,
                              child: _adMobController.bannerAdWidget,
                              width: double.infinity,
                              height: 250,
                            ),
                          ),
                        ),

                  // Divider & Yesterday
                  _firebaseDatabase.mapDataList2 == null ||
                          _firebaseDatabase.mapDataList2.isEmpty
                      ? Container()
                      : Divider(
                          thickness: 2,
                          indent: 10.0,
                          endIndent: 10.0,
                        ),
                  _firebaseDatabase.mapDataList2 == null ||
                          _firebaseDatabase.mapDataList2.isEmpty
                      ? Container()
                      : Padding(
                          padding: EdgeInsets.symmetric(
                            horizontal: 1.5.h,
                            vertical: 0.7.h,
                          ),
                          child: Text(
                            'Yesterday',
                            style: TextStyle(
                              fontSize: 20.sp,
                              fontFamily: 'PTSerif',
                              color: Colors.blueAccent,
                              fontWeight: FontWeight.bold,
                            ),
                          ),
                        ),

                  /// ----------------------------   List 2 with banner ad
                  _firebaseDatabase.mapDataList2 == null
                      ? Container()
                      : ListView.builder(
                          // controller: scrollController,
                          physics: NeverScrollableScrollPhysics(),
                          shrinkWrap: true,
                          itemCount: _firebaseDatabase.mapDataList2.length,
                          itemBuilder: (context, index) {
                            return MyContainer2(
                              title: _firebaseDatabase.mapDataList2[index]
                                      ['title'] ??
                                  'Loading...',
                              titleImage: _firebaseDatabase.mapDataList2[index]
                                      ['titleImage'] ??
                                  '',
                              imageSource: _firebaseDatabase.mapDataList2[index]
                                      ['imageSource'] ??
                                  '',
                              index: index,
                              context: context,
                            );
                          },
                        ),

                  /// Banner Ad 2
                  _adMobController.adErrorHome2
                      ? Container()
                      : Padding(
                          padding: EdgeInsets.symmetric(
                            horizontal: 0.6.h,
                            vertical: 0.7.h,
                          ),
                          child: Card(
                            elevation: 5,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(12.0),
                            ),
                            child: Container(
                              alignment: Alignment.center,
                              child: _adMobController.bannerAdWidget2,
                              width: double.infinity,
                              height: 250,
                            ),
                          ),
                        ),
                ],
              );
            },
          ),
        ),
      ),
    );
  }
}
```
MyBottomNavBar
```
class MyBottomNavBar extends StatefulWidget {
  final VoidCallback ontap;

  MyBottomNavBar({this.ontap});

  @override
  _MyBottomNavBarState createState() => _MyBottomNavBarState();
}

class _MyBottomNavBarState extends State<MyBottomNavBar> {
  //
  int _selectedIndex = 0;

  //
  final _analyticsService = AnalyticsService();

  @override
  Widget build(BuildContext context) {
    return GetBuilder<ThemeController>(
      builder: (_themeController) => Container(
        height: 8.5.h,
        color: Colors.grey[200],
        child: GetBuilder<Controller>(
          builder: (_controller) => ListView(
            shrinkWrap: true,
            scrollDirection: Axis.horizontal,
            children: [
              ListView.builder(
                padding: EdgeInsets.symmetric(horizontal: 1.h),
                shrinkWrap: true,
                scrollDirection: Axis.horizontal,
                itemCount: _controller.finalFavList.length,
                itemBuilder: (context, index) => Padding(
                  padding: EdgeInsets.only(bottom: 1.h, left: 1.h, right: 1.h),
                  child: Center(
                    child: GestureDetector(
                      onTap: () {
                        setState(() {
                          _selectedIndex = index;
                        });
                        _controller.changeDocId(index);
                        _controller.stream();
                        widget.ontap;
                        //   _analyticsService
                        //       .getTopicEvent(_controller.mainDocId.value);
                      },
                      child: Chip(
                        padding: EdgeInsets.all(0.5.h),
                        backgroundColor: index == _selectedIndex
                            ? Colors.blueAccent.withOpacity(0.6)
                            : Colors.grey[300],
                        elevation: index == _selectedIndex ? 3.0 : 1.0,
                        label: Text(
                          '${_controller.finalFavList[index]}',
                          style: TextStyle(
                            color: index == _selectedIndex
                                ? Colors.white
                                : Colors.black87,
                            fontSize: 15.sp,
                            fontWeight: FontWeight.bold,
                          ),
                        ),
                      ),
                    ),
                  ),
                ),
              ),

              /// Add Button
              GestureDetector(
                onTap: () => Navigator.push(
                    context,
                    MaterialPageRoute(
                        builder: (context) => NewsCategoryScreen())),
                child: Padding(
                  padding: EdgeInsets.only(right: 10.0),
                  child: Chip(
                    padding: EdgeInsets.all(0.5.h),
                    backgroundColor: Color(0xfff5f5f5),
                    elevation: 1.0,
                    shape: StadiumBorder(
                      side: BorderSide(
                        color: Colors.green.shade300,
                      ),
                    ),
                    avatar: Icon(
                      Icons.add,
                      color: Colors.green,
                    ),
                    label: Text(
                      'Add',
                      style: TextStyle(
                        fontSize: 13.sp,
                        color: Colors.green,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

There is no error at all. So I couldn't get my head around. But one thing is that callback is not responding. @davidmartos96
