### ISSUE TITLE
`image.debugGetOpenHandleStackTraces()?.length` is `0` when `ImageInfo` is disposed

### ISSUE THREAD

**Issue by raulmabe** [flutter/flutter#88661]
## Steps to Reproduce
I don't know as the full stacktrace isn't printed

<details>
  <summary>Logs</summary>

```
'package:flutter/src/painting/image_stream.dart': Failed assertion: line 122 pos 12: '(image.debugGetOpenHandleStackTraces()?.length ?? 1) > 0': is not true.


#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      ImageInfo.dispose (package:flutter/src/painting/image_stream.dart:122:12)
#3      ImageStreamCompleter._maybeDispose (package:flutter/src/painting/image_stream.dart:576:20)
#4      ImageStreamCompleterHandle.dispose (package:flutter/src/painting/image_stream.dart:447:17)
#5      _CachedImageBase.dispose.<anonymous closure> (package:flutter/src/painting/image_cache.dart:627:15)
#6      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#7      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1090:9)
#8      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:998:5)
#9      _rootRun (dart:async/zone.dart:1354:13)
#10     _CustomZone.run (dart:async/zone.dart:1258:19)
#11     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
#12     _invoke (dart:ui/hooks.dart:163:10)
#13     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:259:5)
#14     _drawFrame (dart:ui/hooks.dart:126:31)

#0      new Image._.<anonymous closure> (dart:ui/painting.dart:1647:32)
#1      new Image._ (dart:ui/painting.dart:1649:6)
#2      Codec.getNextFrame.<anonymous closure> (dart:ui/painting.dart:1994:24)
```

```
➜  diven_app git:(dev) ✗ flutter doctor -v
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.1 20C69 darwin-x64, locale es-ES)
    • Flutter version 2.2.3 at /Users/mabe/development/flutter
    • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mabe/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • 49AB9A7D-2410-4F53-9244-D179CA89E36D • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 92.0.4515.159

• No issues found!
```

</details>

I get this error thrown several times across the app when switching pages. I also get this error sometimes:
```
log] Bad state: Cannot clone a disposed image.
      The clone() method of a previously-disposed Image was called. Once an Image object has been disposed, it can no longer be used to create handles, as the underlying data may have been released.
[log] #0      Image.clone (dart:ui/painting.dart:1807:7)
#1      ImageInfo.clone
package:flutter/…/painting/image_stream.dart:51
#2      ImageStreamCompleter.addListener
package:flutter/…/painting/image_stream.dart:504
#3      ImageStream.addListener
package:flutter/…/painting/image_stream.dart:367
#4      _ImageState._listenToStream
package:flutter/…/widgets/image.dart:1255
#5      _ImageState.didChangeDependencies
package:flutter/…/widgets/image.dart:1123
#6      StatefulElement.performRebuild
package:flutter/…/widgets/framework.dart:4743
#7      Element.rebuild
package:flutter/…/widgets/framework.dart:4267
#8      StatefulElement.update
package:flutter/…/widgets/framework.dart:4778
#9      Element.updateChild
package:flutter/…/widgets/framework.dart:3350
#10     ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4599
#11     StatefulElement.performRebuild
package:flutter/…/widgets/framework.dart:4746
#12     Element.rebuild
package:flutter/…/widgets/framework.dart:4267
#13     StatefulElement.update
package:flutter/…/widgets/framework.dart:4778
#14     Element.updateChild
package:flutter/…/widgets/framework.dart:3350
#15     RenderObjectElement.updateChildren
package:flutter/…/widgets/framework.dart:5596
#16     MultiChildRenderObjectElement.update
package:flutter/…/widgets/framework.dart:6243
#17     Element.updateChild
package:flutter/…/widgets/framework.dart:3350
#18     ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4599
#19     StatefulElement.performRebuild
package:flutter/…/widgets/framework.dart:4746
#20     Element.rebuild
package:flutter/…/widgets/framework.dart:4267
#21     StatefulElement.update
package:flutter/…/widgets/framework.dart:4778
#22     Element.updateChild
package:flutter/…/widgets/framework.dart:3350
#23     ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4599
#24     StatefulElement.performRebuild
package:flutter/…/widgets/framework.dart:4746
#25     Element.rebuild
package:flutter/…/widgets/framework.dart:4267
#26     BuildOwner.buildScope
package:flutter/…/widgets/framework.dart:2582
#27     WidgetsBinding.drawFrame
package:flutter/…/widgets/binding.dart:875
#28     RendererBinding._handlePersistentFrameCallback
package:flutter/…/rendering/binding.dart:328
#29     SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1144
#30     SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1082
#31     SchedulerBinding._handleDrawFrame
package:flutter/…/scheduler/binding.dart:998
#32     _rootRun (dart:async/zone.dart:1354:13)
#33     _CustomZone.run (dart:async/zone.dart:1258:19)
#34     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
#35     _invoke (dart:ui/hooks.dart:163:10)
#36     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:259:5)
#37     _drawFrame (dart:ui/hooks.dart:126:31)


```

I use `Image.network` extensively across the app.

**Comment by darshankawar** [comment]
@raulmabe 
Is there a way for you to replicate it locally ? or play around with the release version of the app and see where exactly it fails ?

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
