### ISSUE TITLE
Aborting migration to null-safety due to an exception.

### ISSUE THREAD

**Issue by elikyalk** [flutter/flutter#88692]
I get this issue when migrating to null-safety

```
See https://dart.dev/go/null-safety-migration for a migration guide.

Analyzing project...
[-------------------------------------------------------------------------------------------------------------------------------------------------------------------------|]No analysis issues found.

Generating migration suggestions...
[----------------------                                                                                                                                                    ]Aborting migration due to an exception.  This most likely is due to a
bug in the migration tool.  Please consider filing a bug report at:

https://github.com/dart-lang/sdk/issues/new
Please include the SDK version (2.13.4) in your bug report.

To attempt to perform migration anyway, you may re-run with
--ignore-exceptions.

Exception details:

NoSuchMethodError: The getter 'library' was called on null.
Receiver: null
Tried calling: library at offset 529 in /Users/splitti1/Projects/Splitti/lib/new_models/group.status.logs.model.dart (TextColumn)

#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      Variables._createDecoratedElementType (package:nnbd_migration/src/variables.dart:374:40)
#2      Variables.decoratedElementType (package:nnbd_migration/src/variables.dart:100:9)
#3      EdgeBuilder.visitTypeName (package:nnbd_migration/src/edge_builder.dart:1793:40)
#4      TypeNameImpl.accept (package:analyzer/src/dart/ast/ast.dart:10068:50)
#5      EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#6      EdgeBuilder._handleExecutableDeclaration (package:nnbd_migration/src/edge_builder.dart:2473:5)
#7      EdgeBuilder.visitMethodDeclaration (package:nnbd_migration/src/edge_builder.dart:1243:5)
#8      MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:6942:50)
#9      EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#10     EdgeBuilder._dispatchList (package:nnbd_migration/src/edge_builder.dart:2229:7)
#11     EdgeBuilder.visitClassOrMixinOrExtensionDeclaration (package:nnbd_migration/src/edge_builder.dart:607:7)
#12     EdgeBuilder.visitClassDeclaration (package:nnbd_migration/src/edge_builder.dart:574:5)
#13     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1514:50)
#14     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2207:24)
#15     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1340:9)
#16     GeneralizingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:202:52)
#17     CompletenessTracker.visitCompilationUnit.<anonymous closure> (package:nnbd_migration/src/utilities/completeness_tracker.dart:52:24)
#18     PermissiveModeVisitor.reportExceptionsIfPermissive (package:nnbd_migration/src/utilities/permissive_mode.dart:26:24)
#19     CompletenessTracker.visitCompilationUnit (package:nnbd_migration/src/utilities/completeness_tracker.dart:43:5)
#20     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2105:50)
#21     NullabilityMigrationImpl.processInput (package:nnbd_migration/src/nullability_migration_impl.dart:244:12)
#22     NonNullableFix.processUnit (package:nnbd_migration/src/front_end/non_nullable_fix.dart:164:15)
#23     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1152:19)
#24     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1150:28)
#25     _FixCodeProcessor.processResources (package:nnbd_migration/migration_cli.dart:1079:30)
<asynchronous suspension>
#26     _FixCodeProcessor.runLaterPhases (package:nnbd_migration/migration_cli.dart:1150:5)
<asynchronous suspension>
#27     MigrationCliRunner.run (package:nnbd_migration/migration_cli.dart:747:24)
<asynchronous suspension>
#28     MigrateCommand.run (package:nnbd_migration/migration_cli.dart:184:7)
<asynchronous suspension>
#29     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#30     DartdevRunner.runCommand (package:dartdev/dartdev.dart:199:18)
<asynchronous suspension>
#31     runDartdev (package:dartdev/dartdev.dart:53:16)
<asynchronous suspension>
#32     main (file:///opt/s/w/ir/cache/builder/src/third_party/dart/pkg/dartdev/bin/dartdev.dart:11:3)
<asynchronous suspension>

```

**Comment by stuartmorgan** [comment]
The Dart migration tool is part of Dart, not Flutter. As the error says this needs to be filed against that project:
> Please consider filing a bug report at:
> 
> https://github.com/dart-lang/sdk/issues/new

**Comment by elikyalk** [comment]
> The Dart migration tool is part of Dart, not Flutter. As the error says this needs to be filed against that project:
> 
> > Please consider filing a bug report at:
> > https://github.com/dart-lang/sdk/issues/new

Thank's
