### ISSUE TITLE
`Paragraph.getBoxesForPlaceholders` returns NaN when font size is zero

### ISSUE THREAD

**Issue by daohoangson** [flutter/flutter#88708]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(
      home: Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    ));

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final style = DefaultTextStyle.of(context).style;
    return SingleChildScrollView(
      child: RichText(
        text: TextSpan(
          children: [
            const WidgetSpan(child: SizedBox(width: 10, height: 10)),
            TextSpan(text: 'hover me', style: style),
          ],
          style: style.copyWith(fontSize: 0.0),
        ),
      ),
    );
  }
}
```

3. Hover the mouse / touch the "hover me" text. Live demo at https://dartpad.dev/?id=a69cf847dda053eab3c9d2cff2a0b65d&null_safety=true

**Expected results:** no error

**Actual results:** lots of error. And the `_inlinePlaceholderBoxes` has NaN values.

<img width="1395" alt="Screen Shot 2021-08-23 at 21 27 22" src="https://user-images.githubusercontent.com/239336/130468058-c6dc5d6e-36cc-4ed2-9e5c-bd6b07998ebf.png">

<details>
  <summary>Logs</summary>

```
[ +331 ms] com.example.bug: 6735
[        ] Waiting for observatory port to be available...
[+3004 ms] Observatory URL on device: http://127.0.0.1:62508/b86m1e-gJ3E=/
[   +5 ms] Caching compiled dill
[  +42 ms] Connecting to service protocol: http://127.0.0.1:62508/b86m1e-gJ3E=/
[ +117 ms] Launching a Dart Developer Service (DDS) instance at
http://127.0.0.1:0, connecting to VM service at
http://127.0.0.1:62508/b86m1e-gJ3E=/.
[ +153 ms] DDS is listening at http://127.0.0.1:62511/GrAFbiZmz0A=/.
[  +51 ms] Successfully connected to service protocol:
http://127.0.0.1:62508/b86m1e-gJ3E=/
[ +188 ms] DevFS: Creating new filesystem on the device (null)
[  +19 ms] DevFS: Created new filesystem on the device
(file:///Users/sondh/Library/Developer/CoreSimulator/Devices/95E05965-7F9C-4E0A-
BF1D-4F3CC5E17FC4/data/Containers/Data/Application/208EFE4F-077C-4A8B-B11E-C5C40
030EC3E/tmp/bugbbQwEX/bug/)
[   +5 ms] Updating assets
[ +160 ms] Syncing files to device iPhone 12 Pro Max...
[   +2 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +8 ms] <- recompile package:bug/main.dart
209f370e-d07b-400d-b32c-408d2d39ea1b
[        ] <- 209f370e-d07b-400d-b32c-408d2d39ea1b
[ +125 ms] Updating files.
[        ] DevFS: Sync finished
[   +1 ms] Syncing files to device iPhone 12 Pro Max... (completed in 139ms)
[   +1 ms] Synced 0.0MB.
[   +1 ms] <- accept
[  +14 ms] Connected to _flutterView/0x7f9479018a20.
[   +9 ms] Flutter run key commands.
[   +2 ms] r Hot reload. 🔥🔥🔥
[   +1 ms] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] 💪 Running with sound null safety 💪
[        ] An Observatory debugger and profiler on iPhone 12 Pro Max is
available at:
           http://127.0.0.1:62511/GrAFbiZmz0A=/
[ +883 ms] The Flutter DevTools debugger and profiler on iPhone 12 Pro Max is
available at:

http://127.0.0.1:9105?uri=http%3A%2F%2F127.0.0.1%3A62511%2FGrAFbiZmz0A%3D%2F
[+4566 ms] [VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception:
'package:flutter/src/gestures/hit_test.dart': Failed assertion: line 213 pos 7:
'_debugVectorMoreOrLessEquals(transform.getRow(2), Vector4(0, 0, 1, 0)) &&
                          _debugVectorMoreOrLessEquals(transform.getColumn(2),
Vector4(0, 0, 1, 0))': The third row and third column of a transform matrix for
pointer events must be Vector4(0, 0, 1, 0) to ensure that a transformed point is
directly under the pointing device. Did you forget to run the paint matrix
through PointerEvent.removePerspectiveTransform? The provided matrix is:
                    [0] NaN,NaN,NaN,NaN
                    [1] NaN,NaN,NaN,NaN
                    [2] NaN,NaN,NaN,NaN
                    [3] NaN,NaN,NaN,NaN
                    
                    #0      _AssertionError._doThrowNew
(dart:core-patch/errors_patch.dart:46:39)
                    #1      _AssertionError._throwNew
(dart:core-patch/errors_patch.dart:36:5)
                    #2      HitTestResult.pushTransform
(package:flutter/src/gestures/hit_test.dart:213:7)
                    #3      BoxHitTestResult.addWithRawTransform
(package:flutter/src/rendering/box.dart:824:7)
                    #4      BoxHitTestResult<…>
[+4500 ms] DevFS: Deleting filesystem on the device
(file:///Users/sondh/Library/Developer/CoreSimulator/Devices/95E05965-7F9C-4E0A-
BF1D-4F3CC5E17FC4/data/Containers/Data/Application/208EFE4F-077C-4A8B-B11E-C5C40
030EC3E/tmp/bugbbQwEX/bug/)
[   +5 ms] DevFS: Deleted filesystem on the device
(file:///Users/sondh/Library/Developer/CoreSimulator/Devices/95E05965-7F9C-4E0A-
BF1D-4F3CC5E17FC4/data/Containers/Data/Application/208EFE4F-077C-4A8B-B11E-C5C40
030EC3E/tmp/bugbbQwEX/bug/)
[  +66 ms] Service protocol connection closed.
[        ] Application finished.
[   +4 ms] "flutter run" took 49,809ms.
[ +190 ms] ensureAnalyticsSent: 186ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0

```

The log was too long, I have to truncate it, [full log here](https://github.com/flutter/flutter/files/7032801/run.log.gz)

```
Analyzing bug...                                                        
No issues found! (ran in 1.7s)
```

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.3 20E232 darwin-x64, locale
    en-VN)
    • Flutter version 2.2.3 at /Users/sondh/fvm/versions/stable
    • Framework revision f4abaa0735 (8 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/sondh/Library/Android/sdk
    • Platform android-S, build-tools 30.0.3
    • ANDROID_HOME = /Users/sondh/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • 95E05965-7F9C-4E0A-BF1D-4F3CC5E17FC4 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • macOS 11.3 20E232 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 92.0.4515.159

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Verified on latest stable and master and see the same behavior.

<details>
<summary>console error log</summary>


```
Syncing files to device iPhone 12 Pro Max...
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: 'package:flutter/src/gestures/hit_test.dart': Failed assertion: line 213 pos 7: '_debugVectorMoreOrLessEquals(transform.getRow(2), Vector4(0, 0, 1, 0)) &&
      _debugVectorMoreOrLessEquals(transform.getColumn(2), Vector4(0, 0, 1, 0))': The third row and third column of a transform matrix for pointer events must be Vector4(0, 0, 1, 0) to ensure that a transformed point is directly under the pointing device. Did you forget to run the paint matrix through PointerEvent.removePerspectiveTransform? The provided matrix is:
[0] NaN,NaN,NaN,NaN
[1] NaN,NaN,NaN,NaN
[2] NaN,NaN,NaN,NaN
[3] NaN,NaN,NaN,NaN

#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      HitTestResult.pushTransform (package:flutter/src/gestures/hit_test.dart:213:7)
#3      BoxHitTestResult.addWithRawTransform (package:flutter/src/rendering/box.dart:824:7)
#4      BoxHitTestResult<…>
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: 'package:flutter/src/gestures/hit_test.dart': Failed assertion: line 213 pos 7: '_debugVectorMoreOrLessEquals(transform.getRow(2), Vector4(0, 0, 1, 0)) &&
      _debugVectorMoreOrLessEquals(transform.getColumn(2), Vector4(0, 0, 1, 0))': The third row and third column of a transform matrix for pointer events must be Vector4(0, 0, 1, 0) to ensure that a transformed point is directly under the pointing device. Did you forget to run the paint matrix through PointerEvent.removePerspectiveTransform? The provided matrix is:
[0] NaN,NaN,NaN,NaN
[1] NaN,NaN,NaN,NaN
[2] NaN,NaN,NaN,NaN
[3] NaN,NaN,NaN,NaN

#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      HitTestResult.pushTransform (package:flutter/src/gestures/hit_test.dart:213:7)
#3      BoxHitTestResult.addWithRawTransform (package:flutter/src/rendering/box.dart:824:7)
#4      BoxHitTestResult<…>



```


</details>

<details>
<summary> stable and master flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.2.3 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision f4abaa0735 (4 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dhs/Library/Android/sdk
    • Java binary at: /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.    

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • SM G975F (mobile) • RZ8M802WY0X • android-arm64 • Android 10 (API 29)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 91.0.4472.114

• No issues found!

[✓] Flutter (Channel master, 2.5.0-7.0.pre.211, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.5.0-7.0.pre.211 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 56b681247d (4 hours ago), 2021-08-23 20:44:05 -0400
    • Engine revision 926ce0d855
    • Dart version 2.15.0 (build 2.15.0-43.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dhs/Library/Android/sdk
    • Java binary at: /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.    

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • SM G975F (mobile) • RZ8M802WY0X • android-arm64 • Android 10 (API 29)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 91.0.4472.114






```

</details>

**Comment by darshankawar** [comment]
Verified this issue on latest stable (3.0.1) and confirmed that the issue doesn't occur anymore and has been fixed.

```
Launching lib/main.dart on iPhone 13 in debug mode...
Running pod install...
Running Xcode build...
Xcode build done.                                           55.5s
Debug service listening on ws://127.0.0.1:50449/uFNay5SCjsw=/ws
Syncing files to device iPhone 13...
```


https://user-images.githubusercontent.com/67046386/171556498-86ff2dd0-6d59-4c7b-936e-fdb965ed601d.mov

<details>
<summary> stable flutter doctor -v </summary>

```

[✓] Flutter (Channel unknown, 3.0.1, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.0.1 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository unknown
    • Framework revision fb57da5f94 (3 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

</details>

Closing this as fixed.
