### ISSUE TITLE
vpython setup flaky failure on Engine Windows builds

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#88719]
A couple of instances of this in the past few days:

https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20Host%20Engine/11519/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20Unopt/1248/overview

```
[E2021-08-20T18:19:34.841758-07:00 5092 0 venv.go:987] Command (cwd=C:\b\s\w\ir\x\t\vpython_bootstrap475928925\packages\virtualenv-16.7.10): [C:\b\s\w\ir\cipd_bin_packages\cpython3\bin\python3.exe -B -E -s virtualenv.py --no-download C:\b\s\w\ir\cache\vpython\51ae26]
Process output:
Using base prefix 'C:\\b\\s\\w\\ir\\cipd_bin_packages\\cpython3\\bin'
Traceback (most recent call last):
  File "virtualenv.py", line 2642, in <module>
    main()
  File "virtualenv.py", line 859, in main
    create_environment(
  File "virtualenv.py", line 1161, in create_environment
    install_python(home_dir, lib_dir, inc_dir, bin_dir, site_packages=site_packages, clear=clear, symlink=symlink)
  File "virtualenv.py", line 1450, in install_python
    copy_required_modules(home_dir, symlink)
  File "virtualenv.py", line 1342, in copy_required_modules
    copyfile(filename, dst_filename, symlink)
  File "virtualenv.py", line 425, in copyfile
    copy_file_or_folder(src, dest, symlink)
  File "virtualenv.py", line 400, in copy_file_or_folder
    shutil.copytree(src, dest, symlink)
  File "C:\b\s\w\ir\cipd_bin_packages\cpython3\bin\lib\shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "C:\b\s\w\ir\cipd_bin_packages\cpython3\bin\lib\shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('C:\\b\\s\\w\\ir\\cipd_bin_packages\\cpython3\\bin\\lib\\encodings\\__pycache__\\utf_8.cpython-38.pyc.2398892502592', 'C:\\b\\s\\w\\ir\\cache\\vpython\\51ae26\\lib\\encodings\\__pycache__\\utf_8.cpython-38.pyc.2398892502592', "[Errno 2] No such file or directory: 'C:\\\\b\\\\s\\\\w\\\\ir\\\\cipd_bin_packages\\\\cpython3\\\\bin\\\\lib\\\\encodings\\\\__pycache__\\\\utf_8.cpython-38.pyc.2398892502592'")]
```

**Comment by zanderso** [comment]
Again here https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20Host%20Engine/11547/overview. Bumping this up.

**Comment by keyonghan** [comment]
Issue started happening on 08/20 twice, and one more three hours ago. These three failures happened on different bots. Don't see any suspicious recipe changes either.
Will keep debugging/monitoring.

**Comment by godofredoc** [comment]
There was a change to use vpython instead of python in the buildroot: https://github.com/flutter/buildroot/pull/501 which was rolled here: https://github.com/flutter/engine/pull/28226

**Comment by iskakaushik** [comment]
The original change was needed so fuchsia gn rules can parse yaml files, it was recommended that we use `vpython` to fetch dependencies and also provide reproducible builds across all environments. I am not sure why its flaking on windows.

**Comment by godofredoc** [comment]
@cbracken do you have by any chance the link to the chromium bug?

**Comment by zanderso** [comment]
@cbracken Can we close this?

**Comment by cbracken** [comment]
I believe so. Thanks for the reminder.
