### ISSUE TITLE
Nullability bug in `_network_image.io.dart`

### ISSUE THREAD

**Issue by egaga** [flutter/flutter#88733]
## Steps to Reproduce

The following code fails before throwing exception!

```
if (response.statusCode != HttpStatus.ok) {
// The network may be only temporarily unavailable, or the file will be
// added on the server later. Avoid having future calls to resolve
// fail to check the network again.
await response.drain<List<int>>();
throw image_provider.NetworkImageLoadException(statusCode: response.statusCode, uri: resolved);
}
```     

**Expected results:** 

This should be invoked:
`throw image_provider.NetworkImageLoadException(statusCode: response.statusCode, uri: resolved);`

**Actual results:** 
```
I/flutter (18983): The following _CastError was thrown resolving an image codec:
I/flutter (18983): type 'Null' is not a subtype of type 'List<int>' in type cast
I/flutter (18983): 
I/flutter (18983): When the exception was thrown, this was the stack:
I/flutter (18983): #1      NetworkImage._loadAsync (package:flutter/src/painting/_network_image_io.dart:99:24)
I/flutter (18983): <asynchronous suspension>
```

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-x64, locale en-FI)
    • Flutter version 2.2.3 at /Users/egaga/dev/flutter
    • Framework revision f4abaa0735 (8 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

```

</details>

**Comment by TahaTesser** [comment]
Hi @egaga 

> I/flutter (18983): The following _CastError was thrown resolving an image codec:
> I/flutter (18983): type 'Null' is not a subtype of type 'List<int>' in type cast

Can you please provide a reproducible sample for this?

**Comment by egaga** [comment]
Not yet, not sure if have time to minimize, but I can give you a little bit context:

`Image.network` has https url to Amazon S3 bucket.
Then the image is removed from the Amazon and the Flutter app screen gets rebuild/re-rendered this happens.

I know it would be important to provide an example, and I am sorry that I haven't.

**Comment by egaga** [comment]
Here is a working example, requires the template produced by `flutter create bug`.

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Image Network error bug',
      home: _ImageNetworkBuggy(),
    );
  }
}

class _ImageNetworkBuggy extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Image.network("https://upload.wikimedia.org/wikipedia/commons/c/c4/DNA_double_helix_horizontal2.png")
      ),
    );
  }
}


```

**Comment by TahaTesser** [comment]
@egaga 
Both latest stable and master don't throw mull safety error using your code sample
```console
[        ] For a more detailed help message, press "h". To quit, press "q".
[   +1 ms] An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:49342/uKos-S7cet8=
[ +463 ms] DevTools activation throttled until 2021-09-18 00:20:49.454218.
[ +583 ms] The Flutter DevTools debugger and profiler on Chrome is available at:
                    http://127.0.0.1:9101?uri=http://127.0.0.1:49342/uKos-S7cet8=
[  +38 ms] ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
[   +2 ms] The following ImageCodecException was thrown resolving an image codec:
[   +1 ms] Failed to load network image.
[   +2 ms] Image URL: https://upload.wikimedia.org/wikipedia/commons/c/c4/DNA_double_helix_horizontal2.png
[   +1 ms] Server response code: 404
[   +2 ms] When the exception was thrown, this was the stack
[   +1 ms] Image provider:
[   +1 ms]   NetworkImage("https://upload.wikimedia.org/wikipedia/commons/c/c4/DNA_double_helix_horizontal2.png",
[        ]   scale: 1)
[        ] Image key:
[        ]   NetworkImage("https://upload.wikimedia.org/wikipedia/commons/c/c4/DNA_double_helix_horizontal2.png",
[        ]   scale: 1)
[        ] ════════════════════════════════════════════════════════════════════════════════════════════════════

```

**Comment by unelma** [comment]
@TahaTesser That's good. I have upgraded Flutter a week ago to `2.5.<something>`.
I will try next week again to ensure I had correct version of _stable_ and if I get still that error, I'll send you current `flutter doctor` output.

**Comment by egaga** [comment]
I upgraded to flutter `2.5.1` and still get the same error on iOS:

```
======== Exception caught by image resource service ================================================
The following _CastError was thrown resolving an image codec:
type 'Null' is not a subtype of type 'List<int>' in type cast

When the exception was thrown, this was the stack: 
#1      NetworkImage._loadAsync (package:flutter/src/painting/_network_image_io.dart:99:24)
<asynchronous suspension>
(elided one frame from dart:async)
Image provider: NetworkImage("https://upload.wikimedia.org/wikipedia/commons/c/c4/DNA_double_helix_horizontal2.png", scale: 1.0)
Image key: NetworkImage("https://upload.wikimedia.org/wikipedia/commons/c/c4/DNA_double_helix_horizontal2.png", scal
```

`flutter doctor -v` (with IDE and Android specific stuff omitted):

```
[✓] Flutter (Channel stable, 2.5.1, on macOS 11.5.2 20G95 darwin-x64, locale en-FI)
    • Flutter version 2.5.1 at /Users/egaga/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (3 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Connected device (3 available)
    • iPhone (mobile) • 00008030-000E38992E9A402E • ios            • iOS 14.7.1 18G82

```

**Comment by egaga** [comment]
If I edit the flutter code by commenting out like this

```
//await response.drain<List<int>>();
```

Then I get the correct exception.

```
======== Exception caught by image resource service ================================================
The following NetworkImageLoadException was thrown resolving an image codec:
HTTP request failed, statusCode: 404, https://upload.wikimedia.org/wikipedia/commons/c/c4/DNA_double_helix_horizontal2.png

When the exception was thrown, this was the stack: 
#0      NetworkImage._loadAsync (package:flutter/src/painting/_network_image_io.dart:100:9)
<asynchronous suspension>
Image provider: NetworkImage("https://upload.wikimedia.org/wikipedia/commons/c/c4/DNA_double_helix_horizontal2.png", scale: 1.0)
Image key: NetworkImage("https://upload.wikimedia.org/wikipedia/commons/c/c4/DNA_double_helix_horizontal2.png", scale: 1.0)
====================================================================================================
```

**Comment by egaga** [comment]
Or if I fix the code as the error indicates, like this:
```
await response.drain<List<int>?>();
```

It works, too.

**Comment by egaga** [comment]
Just see the code in master:

https://github.com/flutter/flutter/blob/83dfb2237a22ad92c38e345b3aa85aeecae732aa/packages/flutter/lib/src/painting/_network_image_io.dart#L99

https://github.com/dart-lang/sdk/blob/d45095c4d717fecf5624c07cc0d90656e7e97115/sdk/lib/async/stream.dart#L1091

The documentation for latter file (API) even says:
> The [futureValue] must not be omitted if `null` is not assignable to [E].

And your call-site code has `E = List<int>` and called with `null` so you are not conforming to the API requirements AFAIK. Sorry if I'm mistaken.

**Comment by PerLycke** [comment]
@egaga You are not alone with this issue. In our Crashlytics we have:

> This issue has 955 non-fatal events affecting 218 users

> Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: type 'Null' is not a subtype of type 'List<int>' in type cast. Error thrown Instance of 'ErrorDescription'.
>        at Stream.drain(Stream.java)
>        at NetworkImage._loadAsync(NetworkImage.java:99)

I haven't had the time to debug it like you, so props to you 👍

**Comment by bobandrew** [comment]
I have same bug 
![image](https://user-images.githubusercontent.com/4517015/142058745-33fecf36-8dda-42b0-aa42-ee916f42d523.png)

**Comment by amanv8060** [comment]
Hi @egaga, I was going through the list of issues randomly and found this, upon looking, it looks likes this issue has been fixed by https://github.com/flutter/flutter/pull/89021. 
cc/ @TahaTesser

**Comment by egaga** [comment]
Hey @amanv8060 , it seems the code in master is fixed in different manner:
https://github.com/flutter/flutter/blob/8017883a5dfd13d709c4bd04d617f54a6cb2271f/packages/flutter/lib/src/painting/_network_image_io.dart#L97
