### ISSUE TITLE
How to scroll a ListView and tap on a child

### ISSUE THREAD

**Issue by mleonhard** [flutter/flutter#88762]
## Use case

I am developing a mobile app that uses a [`ListView`](https://api.flutter.dev/flutter/widgets/ListView-class.html) with a static list of child widgets.  I'm writing a test that must scroll the view and tap on a child widget.

One can use `WidgetTester.scrollUntilVisible()` (inherited from [`WidgetController.scrollUntilVisible`](https://api.flutter.dev/flutter/flutter_test/WidgetController/scrollUntilVisible.html)) to scroll a parent widget repeatedly until a particular child is visible.  The widget is now in view and being built, so one can call `WidgetTester.ensureVisible()` (inherited from [`WidgetController.ensureVisible`](https://api.flutter.dev/flutter/flutter_test/WidgetController/ensureVisible.html)) and scroll it completely into the viewport.

Unfortunately, both of those functions rely on the parent widget being  [`Scrollable`](https://api.flutter.dev/flutter/widgets/Scrollable-class.html).  Sadly, contrary to its documentation, `ListView` does NOT extend `Scrollable`.  Even more sadly, `Scrollable` is not an interface that we could implement on a custom widget.

We can use `WidgetTester.dragUntilVisible()` (inherited from [`WidgetController.dragUntilVisible`](https://api.flutter.dev/flutter/flutter_test/WidgetController/dragUntilVisible.html)) to scroll the `ListView`.  But there is no way to make sure that the center of the child widget is in the viewport so `tap` will succeed.  There is no `dragEnsureVisible()`.

I thought of some poor workarounds:
- Replace the `ListView` with a [`Column`](https://api.flutter.dev/flutter/widgets/Column-class.html) inside a [`SingleChildScrollView`](https://api.flutter.dev/flutter/widgets/SingleChildScrollView-class.html).  This will make the app heavier.
- Write my own `dragEnsureVisible()` test function.
- Write my own `tap()` that will tap on any visible part of the target.

## Proposal

Provide a way to write a test that scrolls a `ListView` and taps on a child widget.

**Comment by mleonhard** [comment]
[`SingleChildScrollView`](https://api.flutter.dev/flutter/widgets/SingleChildScrollView-class.html) is also not [`Scrollable`](https://api.flutter.dev/flutter/widgets/Scrollable-class.html).  This is quite frustrating.

**Comment by mleonhard** [comment]
When the scene has multiple multiple `Scrollable` widgets, `WidgetTester.scrollUntilVisible()` throws an error:

```
flutter: ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
flutter: The following StateError was thrown running a test:
flutter: Bad state: Too many elements
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      Iterable.single (dart:core/iterable.dart:500:24)
flutter: #1      WidgetController.widget (package:flutter_test/src/controller.dart:67:30)
flutter: #2      WidgetController.scrollUntilVisible.<anonymous closure> (package:flutter_test/src/controller.dart:1139:15)
flutter: #3      WidgetController.scrollUntilVisible.<anonymous closure> (package:flutter_test/src/controller.dart:1137:39)
flutter: #6      TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
flutter: #7      WidgetController.scrollUntilVisible (package:flutter_test/src/controller.dart:1137:27)
flutter: #8      _scrollIntoView (file:///project/integration_test/app_test.dart:40:16)
flutter: #9      main.<anonymous closure> (file:///project/integration_test/app_test.dart:100:11)
```

The workaround is to provide the key of the scrolling widget.  Unfortunately this must be the key of the actual `Scrollable` widget, not its parent.  There is no way to assign a key to the `Scrollable` widget inside a `ListView` or `SingleChildScrollView`.  Shall I file a ticket to add that?  Is there really no way to scroll and tap from an integration test?  I'm incredulous.  Flutter is past 2.0.  My approach must be flawed to hit so many roadblocks while trying to make a integration simple test for my simple app.  All the test needs to do is tap a button, check a few checkboxes, and tap another button!  *extreme frustration*

**Comment by mleonhard** [comment]
[`CupertinoTextField`](https://api.flutter.dev/flutter/cupertino/CupertinoTextField-class.html) contains an [`EditableText`](https://api.flutter.dev/flutter/widgets/EditableText-class.html) widget which contains a [`Scrollable`](https://api.flutter.dev/flutter/widgets/Scrollable-class.html).  So `WidgetTester.scrollUntilVisible()` always crashes when a ListView and a text field are visible.

Steps to reproduce:
1. `flutter create example4`
2. Update files:
<details><summary>integration_test/example_test.dart</summary>

```dart
import 'package:example4/example_main.dart' show ExampleApp;
import 'package:flutter/widgets.dart' show ValueKey;
import 'package:flutter_test/flutter_test.dart'
    show find, testWidgets, WidgetTester;
import 'package:integration_test/integration_test.dart'
    show IntegrationTestWidgetsFlutterBinding;

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();
  testWidgets("test1", (WidgetTester tester) async {
    await tester.pumpWidget(ExampleApp());
    final target = find.byKey(ValueKey('target'));
    // await tester.dragUntilVisible(
    //   target,
    //   find.byKey(ValueKey('table')),
    //   Offset(0.0, -200.0),
    // );
    await tester.scrollUntilVisible(
      target,
      -100.0,
      // Without this, fails with "Bad state: Too many elements".
      // With this, fails with "'ListView' is not a subtype of type 'Scrollable'".
      // scrollable: find.byKey(ValueKey('table')),
    );
    await Future.delayed(Duration(seconds: 1), () async {});
    // await tester.pumpAndSettle();
    await Future.delayed(Duration(seconds: 1), () async {});
    await tester.ensureVisible(target);
    await Future.delayed(Duration(seconds: 1), () async {});
    // await tester.pumpAndSettle();
    await Future.delayed(Duration(seconds: 1), () async {});
    await tester.tap(target);
    await Future.delayed(Duration(seconds: 1), () async {});
    await tester.pumpAndSettle();
    await Future.delayed(Duration(seconds: 1), () async {});
  });
}
```

</details>

<details><summary>lib/example_main.dart</summary>

```dart
// lib/example_main.dart
import 'package:flutter/cupertino.dart'
    show
        CupertinoApp,
        CupertinoPage,
        CupertinoPageScaffold,
        CupertinoTextField,
        runApp;
import 'package:flutter/widgets.dart'
    show
        BuildContext,
        Color,
        Container,
        EdgeInsets,
        GestureDetector,
        ListView,
        Navigator,
        Padding,
        StatelessWidget,
        ValueKey,
        Widget;

class ExampleApp extends StatelessWidget {
  @override
  Widget build(BuildContext ctx) {
    print('BUILD');
    return CupertinoApp(
      home: Navigator(
        onPopPage: (_route, _result) => true,
        pages: [
          CupertinoPage(
            title: "Home",
            child: CupertinoPageScaffold(
              key: const ValueKey('home-page'),
              child: ListView(
                key: const ValueKey('table'),
                children: <Widget>[
                  CupertinoTextField(placeholder: 'placeholder'),
                  Container(height: 200, color: Color(0xffDDDDDD)),
                  Container(height: 200, color: Color(0xffBBBBBB)),
                  Container(height: 200, color: Color(0xff999999)),
                  Container(height: 200, color: Color(0xff777777)),
                  Container(height: 200, color: Color(0xff555555)),
                  Padding(
                    padding: EdgeInsets.all(5.0),
                    child: GestureDetector(
                      key: ValueKey('target'),
                      onTap: () {
                        print('TAPPED');
                      },
                      child: Container(height: 200, color: Color(0xffFF8888)),
                    ),
                  ),
                  Container(height: 200, color: Color(0xff555555)),
                  Container(height: 200, color: Color(0xff777777)),
                  Container(height: 200, color: Color(0xff999999)),
                  Container(height: 200, color: Color(0xffBBBBBB)),
                  Container(height: 200, color: Color(0xffDDDDDD)),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}

void main() {
  runApp(ExampleApp());
}
```

</details>

<details><summary>test_driver/integration_test.dart</summary>

```dart
import 'package:integration_test/integration_test_driver.dart'
    show integrationDriver;

Future<void> main() => integrationDriver();
```

</details>

<details><summary>pubspec.yaml</summary>

```yaml
name: example4
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
flutter:
```

</details>

<details><summary>flutter drive output</summary>

```
example4 % flutter drive --driver=test_driver/integration_test.dart --target=integration_test/example_test.dart -d test-sim
Running "flutter pub get" in example4...                           685ms
Running Xcode build...                                                  
 └─Compiling, linking and signing...                      2,218ms
Xcode build done.                                            5.9s
VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:58437/kUuF6d_jfCo=/
VMServiceFlutterDriver: Isolate found with number: 303589075521103
VMServiceFlutterDriver: Isolate is paused at start.
VMServiceFlutterDriver: Attempting to resume isolate
flutter: 00:00 +0: test1
VMServiceFlutterDriver: Connected to Flutter application.
flutter: BUILD
flutter: (The following exception is now available via WidgetTester.takeException:)
flutter: ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
flutter: The following StateError was thrown running a test:
flutter: Bad state: Too many elements
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      Iterable.single (dart:core/iterable.dart:500:24)
flutter: #1      WidgetController.widget (package:flutter_test/src/controller.dart:67:30)
flutter: #2      WidgetController.scrollUntilVisible.<anonymous closure> (package:flutter_test/src/controller.dart:1139:15)
flutter: #3      WidgetController.scrollUntilVisible.<anonymous closure> (package:flutter_test/src/controller.dart:1137:39)
flutter: #6      TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
flutter: #7      WidgetController.scrollUntilVisible (package:flutter_test/src/controller.dart:1137:27)
flutter: #8      main.<anonymous closure> (file:///example4/integration_test/example_test.dart:18:18)
flutter: <asynchronous suspension>
flutter: <asynchronous suspension>
flutter: (elided 3 frames from dart:async and package:stack_trace)
flutter:
flutter: The test description was:
flutter:   test1
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: (If WidgetTester.takeException is called, the above exception will be ignored. If it is not, then the above exception will be dumped when another exception is caught by the framework or when the test ends, whichever happens first, and
then the test will fail due to having not caught or expected the exception.)
flutter: ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
flutter: The following StateError was thrown running a test:
flutter: Bad state: Too many elements
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      Iterable.single (dart:core/iterable.dart:500:24)
flutter: #1      WidgetController.widget (package:flutter_test/src/controller.dart:67:30)
flutter: #2      WidgetController.scrollUntilVisible.<anonymous closure> (package:flutter_test/src/controller.dart:1139:15)
flutter: #3      WidgetController.scrollUntilVisible.<anonymous closure> (package:flutter_test/src/controller.dart:1137:39)
flutter: #6      TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
flutter: #7      WidgetController.scrollUntilVisible (package:flutter_test/src/controller.dart:1137:27)
flutter: #8      main.<anonymous closure> (file:///example4/integration_test/example_test.dart:18:18)
flutter: <asynchronous suspension>
flutter: <asynchronous suspension>
flutter: (elided 3 frames from dart:async and package:stack_trace)
flutter:
flutter: The test description was:
flutter:   test1
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: 00:00 +0: test1 [E]
flutter:   Test failed. See exception logs above.
  The test description was: test1
flutter:
flutter: 00:00 +0 -1: (tearDownAll)
flutter: Warning: integration_test plugin was not detected.

If you're running the tests with `flutter drive`, please make sure your tests
are in the `integration_test/` directory of your package and use
`flutter test $path_to_test` to run it instead.

If you're running the tests with Android instrumentation or XCTest, this means
that you are not capturing test results properly! See the following link for
how to set up the integration_test plugin:

https://flutter.dev/docs/testing/integration-tests#testing-on-firebase-test-lab
flutter: 00:00 +1 -1: Some tests failed.
Failure Details:
Failure in method: test1
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following StateError was thrown running a test:
Bad state: Too many elements

When the exception was thrown, this was the stack:
#0      Iterable.single (dart:core/iterable.dart:500:24)
#1      WidgetController.widget (package:flutter_test/src/controller.dart:67:30)
#2      WidgetController.scrollUntilVisible.<anonymous closure> (package:flutter_test/src/controller.dart:1139:15)
#3      WidgetController.scrollUntilVisible.<anonymous closure> (package:flutter_test/src/controller.dart:1137:39)
#6      TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#7      WidgetController.scrollUntilVisible (package:flutter_test/src/controller.dart:1137:27)
#8      main.<anonymous closure> (file:///example4/integration_test/example_test.dart:18:18)
<asynchronous suspension>
<asynchronous suspension>
(elided 3 frames from dart:async and package:stack_trace)

The test description was:
  test1
═════════════════════════════════════════════════════════════════

end of failure 1



Failed to stop app
example4 % 
```

</details>

Potential workaround: Calling `WidgetTester.pumpAndSettle()` brings the whole widget on screen, allowing the `tap()` to succeed.  See commented-out code in `example_test.dart` above.  I don't why this works.  More importantly, I don't know whether it will work for other layouts and target heights.

**Comment by maheshmnj** [comment]
@mleonhard I was able to run a successful test to scroll the list and tap the target

<details>
<summary>test.dart</summary>

```dart
import 'package:counter_app/main.dart';
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart' show ValueKey;
import 'package:flutter_test/flutter_test.dart'
    show Finder, WidgetTester, expect, find, findsOneWidget, testWidgets;
import 'package:integration_test/integration_test.dart'
    show IntegrationTestWidgetsFlutterBinding;

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  testWidgets("test1", (WidgetTester tester) async {
    await tester.pumpWidget(ExampleApp());
    final target = find.byKey(ValueKey('target'));
    await tester.dragUntilVisible(
        target, find.byKey(ValueKey('table')), Offset(0.0, -50.0),
        maxIteration: 100);
    await tester.pumpAndSettle();
    Future.delayed(Duration(seconds: 2));
    expect(target, findsOneWidget);
  });
}

```
</details>


<details>
<summary>logs</summary>

```console
mahesh@Maheshs-Air-M1 counter_app % flutter drive --driver=test_driver/integration_test.dart --target=integration_test/test.dart
Running "flutter pub get" in counter_app...                        946ms
Running Xcode build...                                                  
 └─Compiling, linking and signing...                      2,804ms
Xcode build done.                                           19.5s
VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:64573/Z9SJrRLCNXo=/
VMServiceFlutterDriver: Isolate found with number: 1624625829123575
VMServiceFlutterDriver: Isolate is paused at start.
VMServiceFlutterDriver: Attempting to resume isolate
mahesh@Maheshs-Air-M1 counter_app % flutter drive --driver=test_driver/integration_test.dart --target=integration_test/test.dart
Running "flutter pub get" in counter_app...                        991ms
Running pod install...                                           1,104ms
Running Xcode build...                                                  
 └─Compiling, linking and signing...                         5.5s
Xcode build done.                                           23.6s
VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:64656/nw2RnN-tIq8=/
VMServiceFlutterDriver: Isolate found with number: 1681936414617211
VMServiceFlutterDriver: Isolate is paused at start.
VMServiceFlutterDriver: Attempting to resume isolate
flutter: 00:00 +0: test1
VMServiceFlutterDriver: Connected to Flutter application.
flutter: 00:02 +1: (tearDownAll)
flutter: Warning: integration_test plugin was not detected.

If you're running the tests with `flutter drive`, please make sure your tests
are in the `integration_test/` directory of your package and use
`flutter test $path_to_test` to run it instead.

If you're running the tests with Android instrumentation or XCTest, this means
that you are not capturing test results properly! See the following link for
how to set up the integration_test plugin:

https://flutter.dev/docs/testing/integration-tests#testing-on-firebase-test-lab
flutter: 00:02 +2: All tests passed!
All tests passed.
Failed to stop app
```
</details>

let me know if I am missing anything.

Thanks

**Comment by mleonhard** [comment]
@maheshmnj You have implemented the workaround I pointed out above, calling `WidgetTester.pumpAndSettle()`.

We need to find out why that call is necessary and then make a change to Flutter.  Potential changes to help users write tests without fighting for hours to do simple things:
- Fix `scrollUntilVisible()` so it works when more than one `Scrollable` widget are on screen.
- Update the [`scrollUntilVisible()`](https://api.flutter.dev/flutter/flutter_test/WidgetController/scrollUntilVisible.html) docs to clearly warn users that the function crashes when more than one `Scrollable` widget are on the screen.  Provide a list of standard widgets that contain `Scrollable` widgets, like [`cupertino:CupertinoTextField`](https://api.flutter.dev/flutter/cupertino/CupertinoTextField-class.html) and [`material:TextField`](https://api.flutter.dev/flutter/material/TextField-class.html).
- Make `scrollUntilVisible()` crash with a useful error message when more than one `Scrollable` widget are on the screen.  Show the offending widgets.
- Change `dragUntilVisible()` so the call to `pumpAndSettle()` is unnecessary.
- Update the [`dragUntilVisible()`](https://api.flutter.dev/flutter/flutter_test/WidgetController/dragUntilVisible.html) docs to clearly tell users to call `pumpAndSettle()`.
- Provide a working example of tapping on widgets in a `ListView`.

**Comment by maheshmnj** [comment]
@mleonhard, Calling `pumpAndSettle()` is not a workaround but a necessity of the framework to wait for the scheduled frames to be painted, You are scrolling a list which is basically scheduling a new frame to paint on the screen, unless you call either `pump` or ` pumpAndSettle` the scheduled frames won't be rendered, And whatever you assert would eventually fail and that is expected.
You can read more about using [pumpAndSettle here](https://api.flutter.dev/flutter/flutter_test/WidgetTester/pumpAndSettle.html). Optionally you may look at this test in the source code which shows [tapping a item in a listview   ](https://github.com/flutter/flutter/blob/f4abaa0735eba4dfd8f33f73363911d63931fe03/packages/flutter/test/widgets/scroll_view_test.dart#L752)

The rest of the pointers looks like a documentation proposal to me than a bug.

**Comment by mleonhard** [comment]
Gaps in documentation are bugs.  They affect users just as much as code bugs.  If calling `pump()` or `pumpAndSettle()` is a requirement, users need a way to learn it easily, without wasting hours on research and trial-and-error.

When you call it a documentation proposal, you reject code fixes to make the functions work as expected and reduce boilerplate.  I disagree with your decision.

This issue is about the underlying usability problem that I faced.  I documented the problem clearly.  My first comment is confused because I was confused.  It serves as documentation of the knowledge gaps that an experienced engineer faces when using Flutter docs & code.

Please stop marking this ticket as "waiting for customer response".  The next step for this issue is to decide on fixes.  You do not push the issue forward toward resolution when you say "It's a documentation proposal" or assign it back to me.  This issue needs attention from someone with deep knowledge of the `integration_test` and `flutter_test` modules.

**Comment by maheshmnj** [comment]
Labelled the issue for further investigation

**Comment by RajathaBS** [comment]
Hi All, I think I'm encountering this issue on my app as well. Below are the steps 
1) Navigate to mobile app page where you tap on a field to open a listview of cities with search field at the top
2) Search a valid text city name , when pump and settle, the suggested city option is diplayed 
3) Try tap on suggested city name

App is closing **erroneously**. Please help me

**Comment by maheshmnj** [comment]
> App is closing erroneously. Please help me

@RajathaBS please note that the GitHub issue tracker is not to provide assistance with personal code, If you believe the app crash is due to an error in the framework please consider filing a new issue with sufficient details requested in the issue template.

Thanks

**Comment by RajathaBS** [comment]
Hi @maheshmnj  , this seems to be not an app issue and more like flutter. I will try to get the complete logs and attach

**Comment by MilesAdamson** [comment]
I also ran into this issue today and I've got to say it's extremely unintuitive to scroll a `ListView` in a widget test.

- You cannot use scrollUntilVisible as-is because a `ListView` is not `Scrollable` (how could anyone guess that)
- You cannot provide a key to your own widget which scrolls to it, because this must be the key of the scrollable, not the list view
- You can scroll the list view by an arbitrary amount, which does work, but seems extremely fragile due to it depending on the height of other widgets. If I know my list view should have `[widget1, widget2 widget3]`, I should be able to scroll to widget 3 with 1 call which scrolls past widget 1 and 2 regardless of how tall they happen to be.

I have written this workaround which seems to help but it feels quite hacky to use.

```
import 'package:flutter_test/flutter_test.dart';

Future<void> scrollUntilFound(
  WidgetTester tester,
  Finder finder, {
  int attempts = 20,
}) async {
  for (int i = 1; i <= attempts; i++) {
    final gesture = await tester.startGesture(const Offset(0, 300));
    await gesture.moveBy(const Offset(0, -300));
    await tester.pump();

    try {
      expect(finder, findsOneWidget);
      await tester.pumpAndSettle();
      return;
    } catch (e) {
      if (i == attempts) {
        rethrow;
      }
    }
  }
}

```

What I would like to be able to do is simply this:

```
    await tester.scrollUntilVisible(
      itemFinder,
      500.0,
      scrollable: find.byKey(ListView),
    );
```

**Comment by corran2go** [comment]
You can just search for the Scrollable of the ListView:

`final scrollableFinder = find.descendant(
  of: find.byType(ListView),
  matching: find.byType(Scrollable),
);`

**Comment by genevievelanzer** [comment]
I have gotten my tests working locally on both Android and iOS emulators with the following: 
```
Future<void> scrollAndTapButton(WidgetTester tester, Key buttonKey) async {
  final scrollableWidget = find
      .descendant(
        of: find.byType(ListView),
        matching: find.byType(Scrollable),
      )
      .last;

  final button = find.byKey(buttonKey);
  await tester.scrollUntilVisible(
    button,
    300.0,
    scrollable: scrollableWidget,
  );
  await tester.tap(button);
```

However, when it runs on Firebase Test Lab, the scrolling does not work. Any ideas ?

**Comment by leyvaje** [comment]
Perhaps the virtual device in Firebase Lab has a different screen size than
the one you use in your local machine tests?

>> Sent from Gmail for iPhone <<
