### ISSUE TITLE
FileSystemException: FileSystemException: Cannot resolve symbolic links, path = 'D:\android\sdk\platform-tools\adb' (OS Error: 系统找不到指定的文件。

### ISSUE THREAD

**Issue by HuangHanquan** [flutter/flutter#8882]
## command

flutter doctor

## exception

FileSystemException: FileSystemException: Cannot resolve symbolic links, path = 'D:\android\sdk\platform-tools\adb' (OS Error: 系统找不到指定的文件。
, errno = 2)

```
#0      FileSystemEntity._throwIfError (dart:io/file_system_entity.dart:678)
#1      FileSystemEntity.resolveSymbolicLinksSync (dart:io/file_system_entity.dart:346)
#2      ForwardingFileSystemEntity.resolveSymbolicLinksSync (package:file/src/forwarding/forwarding_file_system_entity.dart:54)
#3      AndroidSdk.locateAndroidSdk (package:flutter_tools/src/android/android_sdk.dart:104)
#4      AppContext.putIfAbsent (package:flutter_tools/src/base/context.dart:46)
#5      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:253)
<asynchronous suspension>
#6      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#7      Future.Future.sync (dart:async/future.dart:208)
#8      CommandRunner.run (package:args/command_runner.dart:109)
#9      FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:157)
#10     run.<anonymous closure> (package:flutter_tools/executable.dart:140)
<asynchronous suspension>
#11     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#12     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#13     _rootRun (dart:async/zone.dart:1150)
#14     _CustomZone.run (dart:async/zone.dart:1026)
#15     runZoned (dart:async/zone.dart:1503)
#16     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#17     run (package:flutter_tools/executable.dart:113)
<asynchronous suspension>
#18     main (package:flutter_tools/executable.dart:66)
<asynchronous suspension>
#19     main (file:///E:/dart-lang/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#20     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

## flutter doctor

```
encountered exception: FileSystemException: Cannot resolve symbolic links, path = 'D:\android\sdk\platform-tools\adb' (OS Error: 系统找不到指定的文件。
, errno = 2)

#0      FileSystemEntity._throwIfError (dart:io/file_system_entity.dart:678)
#1      FileSystemEntity.resolveSymbolicLinksSync (dart:io/file_system_entity.dart:346)
#2      ForwardingFileSystemEntity.resolveSymbolicLinksSync (package:file/src/forwarding/forwarding_file_system_entity.dart:54)
#3      AndroidSdk.locateAndroidSdk (package:flutter_tools/src/android/android_sdk.dart:104)
#4      getAdbPath (package:flutter_tools/src/android/android_sdk.dart:49)
#5      getAdbDevices (package:flutter_tools/src/android/android_device.dart:497)
#6      AndroidDevices.pollingGetDevices (package:flutter_tools/src/android/android_device.dart:36)
#7      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:117)
#8      DeviceManager.getAllConnectedDevices.<anonymous closure> (package:flutter_tools/src/device.dart:75)
#9      ExpandIterator.moveNext (dart:_internal/iterable.dart:480)
#10     List.List.from (dart:core-patch/array_patch.dart:39)
#11     Iterable.toList (dart:core/iterable.dart:347)
#12     DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:76)
<asynchronous suspension>
#13     DeviceValidator.validate (package:flutter_tools/src/doctor.dart:515)
<asynchronous suspension>
#14     Doctor.diagnose (package:flutter_tools/src/doctor.dart:143)
<asynchronous suspension>
#15     _doctorText.<anonymous closure> (package:flutter_tools/executable.dart:287)
#16     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#17     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#18     _rootRun (dart:async/zone.dart:1150)
#19     _CustomZone.run (dart:async/zone.dart:1026)
#20     runZoned (dart:async/zone.dart:1503)
#21     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#22     _doctorText (package:flutter_tools/executable.dart:287)
<asynchronous suspension>
#23     _createLocalCrashReport (package:flutter_tools/executable.dart:262)
<asynchronous suspension>
#24     _handleToolError (package:flutter_tools/executable.dart:217)
<asynchronous suspension>
#25     run.<anonymous closure> (package:flutter_tools/executable.dart:144)
<asynchronous suspension>
#26     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#27     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#28     _rootRun (dart:async/zone.dart:1150)
#29     _CustomZone.run (dart:async/zone.dart:1026)
#30     runZoned (dart:async/zone.dart:1503)
#31     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#32     run (package:flutter_tools/executable.dart:113)
<asynchronous suspension>
#33     main (package:flutter_tools/executable.dart:66)
<asynchronous suspension>
#34     main (file:///E:/dart-lang/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#35     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

**Comment by nanowang** [comment]
FYI, that sentence roughly means system couldn't find specific file.

**Comment by goderbauer** [comment]
@HuangHanquan Thanks for the report. Can you please tell me which version of Windows you are using and if the crash occurred in PowerShell, in Cmd, or in both?

**Comment by goderbauer** [comment]
From the stack trace it looks like Flutter is trying to locate the Android SDK and it es failing when it calls Dart's `resolveSymbolicLinks` method. This method is known to not work on Windows (see https://github.com/dart-lang/sdk/issues/29096).

Instead of having Flutter trying to locate the Android SDK for you, you can try to set the environment variable `ANDROID_HOME` to point to the location of your SDK (probably `D:\android\sdk`). Refer to step 5 of [wiki/Flutter-on-Windows](https://github.com/flutter/flutter/wiki/Flutter-on-Windows) to learn how to set an environment variable on Windows. Let me know if that works.

**Comment by welldone217** [comment]
you can change the file  D:\android\sdk\platform-tools\adb.exe  to  D:\android\sdk\platform-tools\adb  .i changed not found some worng yet  :)

**Comment by goderbauer** [comment]
I just submitted a fix for the issue. If you update to the latest Flutter version it should work now.

**Comment by HuangHanquan** [comment]
it's ok.
