### ISSUE TITLE
Using software text editing controls breaks deleting on CJK keyboards

### ISSUE THREAD

**Issue by Renzo-Olivares** [flutter/flutter#88827]
<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Text Delta Demo'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final TextEditingController _controller = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            TextField(
              autofocus: true,
              controller: _controller,
              maxLines: null,
            ),
          ],
        ),
      ),
    );
  }
}
``` 
	
</details>

## Steps to Reproduce

1. Run the app
2. Type something in the text field
3. Use the software text editing controls in gboard to make a selection and press copy.
4. Switch to simplified chinese IME
5. Move cursor to the end
6. Try to delete

**Expected results:** 
It is expected that characters will be deleted when pressing backspace.

**Actual results:**
<img src="https://user-images.githubusercontent.com/948037/130697515-99b634bd-dbf0-41e6-b4a1-f6c8d7edc0a6.gif" height="450" />

Nothing is deleted.

<details>
  <summary>Logs</summary>

```
[{"id":13,"result":{"enabled":"false","type":"_extensionType","method":"ext.flutter.inspector.trackRepaintWidgets"}}]
[+2617 ms] D/InputMethodManager(21521): showSoftInput() view=io.flutter.embedding.android.FlutterView{5e3e1fd VFE...... .F...... 0,0-1440,2984 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
[   +1 ms] D/InsetsController(21521): show(ime(), fromIme=true)
[ +156 ms] D/InputMethodManager(21521): showSoftInput() view=io.flutter.embedding.android.FlutterView{5e3e1fd VFE...... .F...... 0,0-1440,2984 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
[   +1 ms] D/InsetsController(21521): show(ime(), fromIme=true)
[ +156 ms] D/InputMethodManager(21521): showSoftInput() view=io.flutter.embedding.android.FlutterView{5e3e1fd VFE...... .F...... 0,0-1440,2984 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
[   +2 ms] D/InsetsController(21521): show(ime(), fromIme=true)
[ +135 ms] D/InputMethodManager(21521): showSoftInput() view=io.flutter.embedding.android.FlutterView{5e3e1fd VFE...... .F...... 0,0-1440,2984 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
[   +3 ms] D/InsetsController(21521): show(ime(), fromIme=true)
[ +231 ms] D/InputMethodManager(21521): showSoftInput() view=io.flutter.embedding.android.FlutterView{5e3e1fd VFE...... .F...... 0,0-1440,2984 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
[  +13 ms] D/InsetsController(21521): show(ime(), fromIme=true)
[ +246 ms] D/InputMethodManager(21521): showSoftInput() view=io.flutter.embedding.android.FlutterView{5e3e1fd VFE...... .F...... 0,0-1440,2984 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
[   +2 ms] D/InsetsController(21521): show(ime(), fromIme=true)
[ +168 ms] D/InputMethodManager(21521): showSoftInput() view=io.flutter.embedding.android.FlutterView{5e3e1fd VFE...... .F...... 0,0-1440,2984 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
[   +2 ms] D/InsetsController(21521): show(ime(), fromIme=true)
[  +94 ms] D/InputMethodManager(21521): showSoftInput() view=io.flutter.embedding.android.FlutterView{5e3e1fd VFE...... .F...... 0,0-1440,2984 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
[   +1 ms] D/InsetsController(21521): show(ime(), fromIme=true)
[ +100 ms] D/InputMethodManager(21521): showSoftInput() view=io.flutter.embedding.android.FlutterView{5e3e1fd VFE...... .F...... 0,0-1440,2984 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
[   +3 ms] D/InsetsController(21521): show(ime(), fromIme=true)
[ +108 ms] D/InputMethodManager(21521): showSoftInput() view=io.flutter.embedding.android.FlutterView{5e3e1fd VFE...... .F...... 0,0-1440,2984 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
[   +3 ms] D/InsetsController(21521): show(ime(), fromIme=true)
[ +127 ms] D/InputMethodManager(21521): showSoftInput() view=io.flutter.embedding.android.FlutterView{5e3e1fd VFE...... .F...... 0,0-1440,2984 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
[   +2 ms] D/InsetsController(21521): show(ime(), fromIme=true)
[+4156 ms] D/InputMethodManager(21521): showSoftInput() view=io.flutter.embedding.android.FlutterView{5e3e1fd VFE...... .F...... 0,0-1440,2984 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
[   +2 ms] D/InsetsController(21521): show(ime(), fromIme=true)

======== Exception caught by services library ======================================================
The following _CastError was thrown during a platform message callback:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      KeyEventManager._convertRawEventAndStore (package:flutter/src/services/hardware_keyboard.dart:884:64)
#1      RawKeyboard.handleRawKeyEvent (package:flutter/src/services/raw_keyboard.dart:677:17)
#2      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:818:33)
#3      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:73:49)
#4      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:72:47)
#5      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:379:35)
#6      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:376:46)
#7      _invoke2.<anonymous closure> (dart:ui/hooks.dart:205:15)
#11     _invoke2 (dart:ui/hooks.dart:204:10)
#12     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#13     _Channel.push (dart:ui/channel_buffers.dart:132:31)
#14     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#15     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:544:22)
#16     _dispatchPlatformMessage (dart:ui/hooks.dart:92:31)
(elided 3 frames from dart:async)
====================================================================================================
[ +164 ms] D/InputMethodManager(21521): showSoftInput() view=io.flutter.embedding.android.FlutterView{5e3e1fd VFE...... .F...... 0,0-1440,2984 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
[   +2 ms] D/InsetsController(21521): show(ime(), fromIme=true)

======== Exception caught by services library ======================================================
The following _CastError was thrown during a platform message callback:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      KeyEventManager._convertRawEventAndStore (package:flutter/src/services/hardware_keyboard.dart:884:64)
#1      RawKeyboard.handleRawKeyEvent (package:flutter/src/services/raw_keyboard.dart:677:17)
#2      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:818:33)
#3      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:73:49)
#4      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:72:47)
#5      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:379:35)
#6      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:376:46)
#7      _invoke2.<anonymous closure> (dart:ui/hooks.dart:205:15)
#11     _invoke2 (dart:ui/hooks.dart:204:10)
#12     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#13     _Channel.push (dart:ui/channel_buffers.dart:132:31)
#14     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#15     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:544:22)
#16     _dispatchPlatformMessage (dart:ui/hooks.dart:92:31)
(elided 3 frames from dart:async)
====================================================================================================
[ +155 ms] D/InputMethodManager(21521): showSoftInput() view=io.flutter.embedding.android.FlutterView{5e3e1fd VFE...... .F...... 0,0-1440,2984 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
[   +3 ms] D/InsetsController(21521): show(ime(), fromIme=true)

======== Exception caught by services library ======================================================
The following _CastError was thrown during a platform message callback:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      KeyEventManager._convertRawEventAndStore (package:flutter/src/services/hardware_keyboard.dart:884:64)
#1      RawKeyboard.handleRawKeyEvent (package:flutter/src/services/raw_keyboard.dart:677:17)
#2      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:818:33)
#3      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:73:49)
#4      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:72:47)
#5      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:379:35)
#6      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:376:46)
#7      _invoke2.<anonymous closure> (dart:ui/hooks.dart:205:15)
#11     _invoke2 (dart:ui/hooks.dart:204:10)
#12     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#13     _Channel.push (dart:ui/channel_buffers.dart:132:31)
#14     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#15     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:544:22)
#16     _dispatchPlatformMessage (dart:ui/hooks.dart:92:31)
(elided 3 frames from dart:async)
====================================================================================================
[ +925 ms] D/InputMethodManager(21521): showSoftInput() view=io.flutter.embedding.android.FlutterView{5e3e1fd VFE...... .F...... 0,0-1440,2984 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
[  +18 ms] D/InsetsController(21521): show(ime(), fromIme=true)

======== Exception caught by services library ======================================================
The following _CastError was thrown during a platform message callback:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      KeyEventManager._convertRawEventAndStore (package:flutter/src/services/hardware_keyboard.dart:884:64)
#1      RawKeyboard.handleRawKeyEvent (package:flutter/src/services/raw_keyboard.dart:677:17)
#2      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:818:33)
#3      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:73:49)
#4      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:72:47)
#5      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:379:35)
#6      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:376:46)
#7      _invoke2.<anonymous closure> (dart:ui/hooks.dart:205:15)
#11     _invoke2 (dart:ui/hooks.dart:204:10)
#12     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#13     _Channel.push (dart:ui/channel_buffers.dart:132:31)
#14     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#15     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:544:22)
#16     _dispatchPlatformMessage (dart:ui/hooks.dart:92:31)
(elided 3 frames from dart:async)
====================================================================================================
[+9491 ms] D/InputMethodManager(21521): showSoftInput() view=io.flutter.embedding.android.FlutterView{5e3e1fd VFE...... .F...... 0,0-1440,2984 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
```

```
[✓] Flutter (Channel master, 2.5.0-7.0.pre.223, on macOS 11.5.2 20G95 darwin-x64, locale en)
    • Flutter version 2.5.0-7.0.pre.223 at /Users/roliv/flutter
    • Upstream repository git@github.com:Renzo-Olivares/flutter.git
    • Framework revision fad666bdff (57 minutes ago), 2021-08-24 17:34:03 -0400
    • Engine revision a9efb963de
    • Dart version 2.15.0 (build 2.15.0-43.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/roliv/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio with /Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio with /Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • Pixel 4 XL (mobile)        • 9B191FFBA003NC                       • android-arm64  • Android 12 (API 31)
    • iPhone 12 Pro Max (mobile) • FB10EA59-14BD-490D-B0BE-7BC05D412B59 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 11.5.2 20G95 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 92.0.4515.159

• No issues found!
```

</details>

**Comment by Renzo-Olivares** [comment]
CC @justinmc

**Comment by TahaTesser** [comment]
Hi @Renzo-Olivares 
Thanks for filing the issue

I'm unable to reproduce it on Android 11 (K20 Pro) on the latest `master` channel

### Preview

https://user-images.githubusercontent.com/48603081/131499379-2d5a85ab-eab7-41ca-931b-47ca7732fb07.mp4




<details> 


<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel master, 2.6.0-1.0.pre.136, on macOS 12.0 21A5304g darwin-x64, locale en-US)
    • Flutter version 2.6.0-1.0.pre.136 at /Users/tahatesser/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 96f977f4df (6 hours ago), 2021-08-31 02:16:01 -0400
    • Engine revision fda0ac4520
    • Dart version 2.15.0 (build 2.15.0-66.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/tahatesser/Code/android-sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = /Users/tahatesser/Code/android-sdk
    • Java binary at: /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7621141/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7621141/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (5 available)
    • Redmi K20 Pro (mobile) • def0ad20                             • android-arm64  • Android 11 (API 30)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios            • iOS 15.0 19A5325f
    • iPhone 12 (mobile)     • 77819686-4E78-4DC9-96A8-6D0E8587E397 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 12.0 21A5304g darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 92.0.4515.159

• No issues found!
```

</details>

**Comment by Renzo-Olivares** [comment]
Hi @TahaTesser  i'll close this. I also tried it on master and it is working now.
