### ISSUE TITLE
flutter_test timeout logic - addTime - positive is flaky

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#88838]
This has been failing on and off since at least https://github.com/flutter/engine/pull/27787 on 2021-07-29.

```
#44     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:0:0)
#49     Invoker._onRun.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:386:9)
#50     Invoker._guardIfGuarded (package:test_api/src/backend/invoker.dart:429:15)
#51     Invoker._onRun.<anonymous closure> (package:test_api/src/backend/invoker.dart:385:7)
#58     Invoker._onRun (package:test_api/src/backend/invoker.dart:384:11)
#59     LiveTestController.run (package:test_api/src/backend/live_test_controller.dart:153:11)
#60     RemoteListener._runLiveTest.<anonymous closure> (package:test_api/src/backend/remote_listener.dart:257:16)
#65     RemoteListener._runLiveTest (package:test_api/src/backend/remote_listener.dart:256:5)
#66     RemoteListener._serializeTest.<anonymous closure> (package:test_api/src/backend/remote_listener.dart:209:7)
#84     _GuaranteeSink.add (package:stream_channel/src/guarantee_channel.dart:125:12)
#85     new _MultiChannel.<anonymous closure> (package:stream_channel/src/multi_channel.dart:159:31)
#89     CastStreamSubscription._onData (dart:_internal/async_cast.dart:85:11)
#123    new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1150:21)
#131    _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:338:23)
#132    _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:232:46)
#142    _Socket._onData (dart:io-patch/socket_patch.dart:2166:41)
#151    new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1702:33)
#152    _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1213:14)
(elided 125 frames from class _RawReceivePortImpl, class _Timer, dart:async, dart:async-patch, and package:stack_trace)

The test description was:
  flutter_test timeout logic - addTime - positive
════════════════════════════════════════════════════════════════════════════════════════════════════

00:06 +0 -1: flutter_test timeout logic - addTime - positive [E]                                                                                                                                       
  Test failed. See exception logs above.
  The test description was: flutter_test timeout logic - addTime - positive
  

00:06 +0 -1: Some tests failed.  
```

Looking at commits since 2021-06-21, I see:
* https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Web%20Framework%20tests/4736/overview
* https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Web%20Framework%20tests/4735/overview
* https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Web%20Framework%20tests/4722/overview
* https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Web%20Framework%20tests/4698/overview
* https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Web%20Framework%20tests/4650/overview
* https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Web%20Framework%20tests/4373/overview
* https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Web%20Framework%20tests/4371/overview

Previous issue: https://github.com/flutter/flutter/issues/18507

**Comment by chinmaygarde** [comment]
This is a framework test thats been flaky in our presubmits. @goderbauer I am not sure if we have seen this test in CI in the framwork. cc @Hixie as the original test author.

**Comment by Hixie** [comment]
Do we have complete logs anywhere? What's the actual exception? (The logs above seem truncated.)

**Comment by Hixie** [comment]
Ah here we go:

```
Back to build
Raw log | Switch to full mode | Login
▌23:12:48▐ STARTING ANALYSIS
════════════════════════════════════════════════════════════════════════════════
Running smoketests...
▌23:12:48▐ RUNNING: cd .; bin/cache/artifacts/engine/linux-x64/flutter_tester --help
▌23:12:48▐ ELAPSED TIME: 0.086s for bin/cache/artifacts/engine/linux-x64/flutter_tester --help in .
▌23:12:48▐ RUNNING: cd dev/automated_tests; ../../bin/flutter test --test-randomize-ordering-seed=20210824 --local-engine /b/s/w/ir/x/w/recipe_cleanup/builder/src/out/host_debug_unopt test_smoke_test/pass_test.dart
▌23:13:03▐ ELAPSED TIME: 15.288s for ../../bin/flutter test --test-randomize-ordering-seed=20210824 --local-engine /b/s/w/ir/x/w/recipe_cleanup/builder/src/out/host_debug_unopt test_smoke_test/pass_test.dart in dev/automated_tests
▌23:13:03▐ RUNNING: cd dev/automated_tests; ../../bin/flutter test --test-randomize-ordering-seed=20210824 --local-engine /b/s/w/ir/x/w/recipe_cleanup/builder/src/out/host_debug_unopt test_smoke_test/fail_test.dart
▌23:13:07▐ ELAPSED TIME: 3.689s for ../../bin/flutter test --test-randomize-ordering-seed=20210824 --local-engine /b/s/w/ir/x/w/recipe_cleanup/builder/src/out/host_debug_unopt test_smoke_test/fail_test.dart in dev/automated_tests
▌23:13:07▐ RUNNING: cd dev/automated_tests; ../../bin/flutter test --test-randomize-ordering-seed=20210824 --local-engine /b/s/w/ir/x/w/recipe_cleanup/builder/src/out/host_debug_unopt test_smoke_test/timeout_pass_test.dart
Shuffling test order with --test-randomize-ordering-seed=20210824

00:00 +0: loading /b/s/w/ir/x/w/flutter/dev/automated_tests/test_smoke_test/timeout_pass_test.dart                                                                                                     
00:01 +0: loading /b/s/w/ir/x/w/flutter/dev/automated_tests/test_smoke_test/timeout_pass_test.dart                                                                                                     
00:02 +0: loading /b/s/w/ir/x/w/flutter/dev/automated_tests/test_smoke_test/timeout_pass_test.dart                                                                                                     
00:02 +0: flutter_test timeout logic - addTime - positive                                                                                                                                              
00:03 +0: flutter_test timeout logic - addTime - positive                                                                                                                                              
00:04 +0: flutter_test timeout logic - addTime - positive                                                                                                                                              
00:05 +0: flutter_test timeout logic - addTime - positive                                                                                                                                              
00:06 +0: flutter_test timeout logic - addTime - positive                                                                                                                                              
00:06 +0: flutter_test timeout logic - addTime - positive                                                                                                                                              
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TimeoutException was thrown running a test:
TimeoutException after 0:00:04.000000: The test exceeded the timeout. It may have hung.
Consider using "tester.binding.addTime" to increase the timeout before expensive operations.

When the exception was thrown, this was the stack:
#2      AutomatedTestWidgetsFlutterBinding._checkTimeout (package:flutter_test/src/binding.dart:1176:26)
#22     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1215:29)
#23     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:169:24)
#24     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:199:19)
#27     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:0:0)
#32     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:197:13)
#33     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:180:48)
#34     Invoker._waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:257:15)
#35     Invoker._waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:254:14)
#40     Invoker._waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:254:5)
#41     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:397:17)
#44     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:0:0)
#49     Invoker._onRun.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:386:9)
#50     Invoker._guardIfGuarded (package:test_api/src/backend/invoker.dart:429:15)
#51     Invoker._onRun.<anonymous closure> (package:test_api/src/backend/invoker.dart:385:7)
#58     Invoker._onRun (package:test_api/src/backend/invoker.dart:384:11)
#59     LiveTestController.run (package:test_api/src/backend/live_test_controller.dart:153:11)
#60     RemoteListener._runLiveTest.<anonymous closure> (package:test_api/src/backend/remote_listener.dart:257:16)
#65     RemoteListener._runLiveTest (package:test_api/src/backend/remote_listener.dart:256:5)
#66     RemoteListener._serializeTest.<anonymous closure> (package:test_api/src/backend/remote_listener.dart:209:7)
#84     _GuaranteeSink.add (package:stream_channel/src/guarantee_channel.dart:125:12)
#85     new _MultiChannel.<anonymous closure> (package:stream_channel/src/multi_channel.dart:159:31)
#89     CastStreamSubscription._onData (dart:_internal/async_cast.dart:85:11)
#123    new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1150:21)
#131    _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:338:23)
#132    _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:232:46)
#142    _Socket._onData (dart:io-patch/socket_patch.dart:2166:41)
#151    new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1702:33)
#152    _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1213:14)
(elided 125 frames from class _RawReceivePortImpl, class _Timer, dart:async, dart:async-patch, and package:stack_trace)

The test description was:
  flutter_test timeout logic - addTime - positive
════════════════════════════════════════════════════════════════════════════════════════════════════

00:06 +0 -1: flutter_test timeout logic - addTime - positive [E]                                                                                                                                       
  Test failed. See exception logs above.
  The test description was: flutter_test timeout logic - addTime - positive
  

00:06 +0 -1: Some tests failed.                                                                                                                                                                        


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
ERROR: Last command exited with 1 (expected: zero).
Command: ../../bin/flutter test --test-randomize-ordering-seed=20210824 --local-engine /b/s/w/ir/x/w/recipe_cleanup/builder/src/out/host_debug_unopt test_smoke_test/timeout_pass_test.dart
Relative working directory: dev/automated_tests
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━



This is LogDog
Rendering took 0.14s
```

**Comment by Hixie** [comment]
Looks like for some reason this no-op test takes six seconds (!!!) to run. The fix is probably just to change the additionalTime on line 11 of timeout_pass_test.dart to 20000 milliseconds instead of 2000.

We can also just remove this test entirely, since we don't actually use the initialTimeout feature in practice. In fact maybe we should just remove the whole addTime logic entirely, since we don't use it. IIRC it predates our policy of just not having timeouts.

**Comment by chinmaygarde** [comment]
[Tree is red today](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20SDK%20Drone/89537/overview) because of this. Bumping priority of this issue. The AI per Ian is that the test must go.

**Comment by chinmaygarde** [comment]
This made the tree red again just now. There is another job running and this issue will be fixed pending the linked PR.

**Comment by Hixie** [comment]
PR is ready to go modulo an updated review of the test.dart changes (which were made after the first review to handle flakiness that the fix would otherwise have introduced).
