### ISSUE TITLE
SocketException: Reading from a closed socket

### ISSUE THREAD

**Issue by huangsir0** [flutter/flutter#88863]
## Steps to Reproduce

I don't know how to reproduce this SocketException，it suddenly report an error during the application.

## flutter doctor 
``` dart
[✓] Flutter (Channel stable, 2.2.0, on macOS 11.2.3 20D91 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.2.0 at /Users/huangsir/flutter-2.0.6/flutter
    • Framework revision b22742018b (3 months ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
```

## error stack

```dart
flutter: content: Caught error: SocketException: Reading from a closed socket
flutter: content: #0      _RawSecureSocket.read (dart:io/secure_socket.dart:662:7)
#1      _Socket._onData (dart:io-patch/socket_patch.dart:2159:28)
#2      _rootRunUnary (dart:async/zone.dart:1362:47)
#3      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#7      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#8      _StreamController._add (dart:async/stream_controller.dart:607:7)
#9      _StreamController.add (dart:async/stream_controller.dart:554:5)
#10     _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:991:19)
#11     _rootRun (dart:async/zone.dart:1346:47)
#12     _CustomZone.run (dart:async/zone.dart:1258:19)
#13     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
#14     _CustomZone.bindCallbackGuarded.<an<…>
```

**Comment by darshankawar** [comment]
@huangsir0 
The log is pointing to dart, so this need to be reported in dedicated repo: https://github.com/dart-lang/http/issues
Closing from here.
