### ISSUE TITLE
Flutter run using local flutter engine

### ISSUE THREAD

**Issue by sharathks84** [flutter/flutter#88870]
## Steps to Reproduce

1. ... I have setup development environment following the Wiki steps
2. ... flutter run --local-engine=android_debug_unopt
3. ...

## Logs

<details>
<summary>Logs</summary>

/flutter/workspace/sample$ flutter run --local-engine-src-path /home/sharath/ohos/engine/src --local-engine=android_debug_unopt
Launching lib/main.dart on LIO AL00 in debug mode...
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
../../../snap/flutter/common/flutter/packages/flutter/lib/src/semantics/semantics.dart:2103:23: Error: Required named parameter 'decreasedValueAttributes' must be provided.
    builder.updateNode(                                                 
                      ^                                                 
                                                                        
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* Where:                                                                
Script '/home/sharath/snap/flutter/common/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1035
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:compileFlutterBuildDebug'.              
> Process 'command '/home/sharath/snap/flutter/common/flutter/bin/flutter'' finished with non-zero exit value 1
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 14s                                                     
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        15.2s
Exception: Gradle task assembleDebug failed with exit code 1

```
```

```
```

</details>

**Comment by TahaTesser** [comment]
Hi @sharathks84 
Make sure you're on the latest Flutter `master` channel
When you running a local engine, you have to latest master so the APIs match the engine master branch. 

if the problem persists, you should've been able to reproduce this by running the app directly without a local engine. As the error coming from the app, not the local engine 

If the problem persists, can you please provide your `flutter doctor -v` with the upgrade, complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by sharathks84** [comment]
Hi Taha,
I used this method to get Flutter-SDK "sudo snap install flutter --classic"
When i run directly i do not get this error this is API signature mismatch.

verbose log
"
[  +86 ms] executing: uname -m
[  +52 ms] Exit code 0 from: uname -m
[   +2 ms] x86_64
[  +11 ms] executing: [/home/sharath/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +7 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] f4abaa0735eba4dfd8f33f73363911d63931fe03
[        ] executing: [/home/sharath/snap/flutter/common/flutter/] git tag --points-at f4abaa0735eba4dfd8f33f73363911d63931fe03
[  +13 ms] Exit code 0 from: git tag --points-at f4abaa0735eba4dfd8f33f73363911d63931fe03
[        ] 2.2.3
[   +6 ms] executing: [/home/sharath/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/sharath/snap/flutter/common/flutter/] git ls-remote --get-url origin
[  +10 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +48 ms] Local engine source at /home/sharath/ohos/engine/src
[  +79 ms] executing: [/home/sharath/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +165 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +95 ms] executing: /home/sharath/Android/Sdk/platform-tools/adb devices -l
[  +48 ms] List of devices attached
           QFF0219929002320       device usb:1-1 product:LIO-AL00 model:LIO_AL00 device:HWLIO transport_id:3
[   +7 ms] /home/sharath/Android/Sdk/platform-tools/adb -s QFF0219929002320 shell getprop
[ +149 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +110 ms] Skipping pub get: version match.
[ +121 ms] Generating /home/sharath/flutter/workspace/sample/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +83 ms] ro.hardware = kirin990
[        ] ro.build.characteristics = default
[  +34 ms] Initializing file store
[  +12 ms] Skipping target: gen_localizations
[  +10 ms] complete
[   +6 ms] Launching lib/main.dart on LIO AL00 in debug mode...
[   +7 ms] /home/sharath/ohos/engine/src/out/host_debug_unopt/dart-sdk/bin/dart --disable-dart-dev
/home/sharath/ohos/engine/src/out/host_debug_unopt/gen/frontend_server.dart.snapshot --sdk-root
/home/sharath/ohos/engine/src/out/android_debug_unopt/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names
--experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill /tmp/flutter_tools.TUAQYP/flutter_tool.XABCCE/app.dill
--packages /home/sharath/flutter/workspace/sample/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false
--enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill
build/3c113a45063dc6628e68a4111abcacad.cache.dill.track.dill --enable-experiment=alternative-invalidation-strategy
[  +12 ms] executing: /home/sharath/Android/Sdk/build-tools/31.0.0/aapt dump xmltree
/home/sharath/flutter/workspace/sample/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[  +10 ms] Exit code 0 from: /home/sharath/Android/Sdk/build-tools/31.0.0/aapt dump xmltree
/home/sharath/flutter/workspace/sample/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[   +1 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1e
               A: android:compileSdkVersionCodename(0x01010573)="11" (Raw: "11")
               A: package="com.example.sample" (Raw: "com.example.sample")
               A: platformBuildVersionCode=(type 0x10)0x1e
               A: platformBuildVersionName=(type 0x10)0xb
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1e
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=16)
                 A: android:label(0x01010001)="sample" (Raw: "sample")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw:
                 "androidx.core.app.CoreComponentFactory")
                 E: activity (line=21)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.sample.MainActivity" (Raw: "com.example.sample.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=35)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=45)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw:
                     "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=49)
                     E: action (line=50)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=52)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=59)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[  +10 ms] executing: /home/sharath/Android/Sdk/platform-tools/adb -s QFF0219929002320 shell -x logcat -v time -t 1
[  +20 ms] <- compile package:sample/main.dart
[ +111 ms] --------- beginning of main
                    08-25 17:56:14.040 I/        (  642): maxrss: 11700, shared: 0, unshared: 0, unshared stack: 0
[  +14 ms] executing: /home/sharath/Android/Sdk/platform-tools/adb version
[   +8 ms] Android Debug Bridge version 1.0.41
           Version 31.0.3-7562133
           Installed as /home/sharath/Android/Sdk/platform-tools/adb
[   +2 ms] executing: /home/sharath/Android/Sdk/platform-tools/adb start-server
[  +60 ms] Building APK
[  +25 ms] Running Gradle task 'assembleDebug'...
[   +6 ms] Using gradle from /home/sharath/flutter/workspace/sample/android/gradlew.
[  +39 ms] Using local engine: /home/sharath/ohos/engine/src/out/android_debug_unopt
           Local Maven repo: /tmp/flutter_tools.TUAQYP/flutter_tool_local_engine_repo.KPWMVQ
[  +26 ms] executing: /home/sharath/android-studio/jre/bin/java -version
[ +166 ms] Exit code 0 from: /home/sharath/android-studio/jre/bin/java -version
[        ] openjdk version "11.0.10" 2021-01-19
           OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
           OpenJDK 64-Bit Server VM (build 11.0.10+0-b96-7249189, mixed mode)
[   +6 ms] executing: [/home/sharath/flutter/workspace/sample/android/] /home/sharath/flutter/workspace/sample/android/gradlew -Pverbose=true
-Plocal-engine-repo=/tmp/flutter_tools.TUAQYP/flutter_tool_local_engine_repo.KPWMVQ -Plocal-engine-build-mode=debug
-Plocal-engine-out=/home/sharath/ohos/engine/src/out/android_debug_unopt -Ptarget-platform=android-arm
-Ptarget=/home/sharath/flutter/workspace/sample/lib/main.dart -Pdart-defines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== -Pdart-obfuscation=false
-Ptrack-widget-creation=true -Ptree-shake-icons=false -Pfilesystem-scheme=org-dartlang-root assembleDebug
[+1753 ms] Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns
http://schemas.android.com/repository/android/common/01
[   +4 ms] Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns
http://schemas.android.com/repository/android/generic/01
[        ] Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns
http://schemas.android.com/sdk/android/repo/addon2/01
[        ] Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns
http://schemas.android.com/sdk/android/repo/repository2/01
[        ] Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns
http://schemas.android.com/sdk/android/repo/sys-img2/01
[+1977 ms] > Task :app:compileFlutterBuildDebug
[        ] [  +98 ms] executing: uname -m
[        ] [  +54 ms] Exit code 0 from: uname -m
[        ] [   +1 ms] x86_64
[        ] [   +8 ms] executing: [/home/sharath/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] [   +6 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] f4abaa0735eba4dfd8f33f73363911d63931fe03
[        ] [        ] executing: [/home/sharath/snap/flutter/common/flutter/] git tag --points-at f4abaa0735eba4dfd8f33f73363911d63931fe03
[        ] [  +11 ms] Exit code 0 from: git tag --points-at f4abaa0735eba4dfd8f33f73363911d63931fe03
[        ] [        ] 2.2.3
[        ] [   +7 ms] executing: [/home/sharath/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/stable
[        ] [        ] executing: [/home/sharath/snap/flutter/common/flutter/] git ls-remote --get-url origin
[        ] [   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +53 ms] Local engine source at /home/sharath/ohos/engine/src
[   +3 ms] [  +32 ms] executing: [/home/sharath/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[        ] [   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] stable
[        ] [  +86 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [ +124 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +2 ms] [   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [  +49 ms] Initializing file store
[        ] [   +6 ms] Done initializing file store
[        ] [  +49 ms] Skipping target: gen_localizations
[        ] [ +711 ms] kernel_snapshot: Starting due to {}
[        ] [  +11 ms] /home/sharath/ohos/engine/src/out/host_debug_unopt/dart-sdk/bin/dart --disable-dart-dev
/home/sharath/ohos/engine/src/out/host_debug_unopt/gen/frontend_server.dart.snapshot --sdk-root
/home/sharath/ohos/engine/src/out/android_debug_unopt/flutter_patched_sdk/ --target=flutter --no-print-incremental-dependencies
-DFLUTTER_WEB_AUTO_DETECT=true -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --no-link-platform
--packages /home/sharath/flutter/workspace/sample/.dart_tool/package_config.json --output-dill
/home/sharath/flutter/workspace/sample/.dart_tool/flutter_build/da5ff3ce340b4a1de4e37ab08efae4e8/app.dill --depfile
/home/sharath/flutter/workspace/sample/.dart_tool/flutter_build/da5ff3ce340b4a1de4e37ab08efae4e8/kernel_snapshot.d package:sample/main.dart
[+1638 ms] ../../../snap/flutter/common/flutter/packages/flutter/lib/src/semantics/semantics.dart:2103:23: Error: Required named parameter
'decreasedValueAttributes' must be provided.
[        ]     builder.updateNode(
[        ]                       ^
[+3828 ms] [+5684 ms] ../../../snap/flutter/common/flutter/packages/flutter/lib/src/semantics/semantics.dart:2103:23: Error: Required named
parameter 'decreasedValueAttributes' must be provided.
[        ] [   +3 ms]     builder.updateNode(
[        ] [        ]                       ^
[+3999 ms] [+3967 ms] Persisting file store
[        ] [  +13 ms] Done persisting file store
[   +8 ms] [   +5 ms] Target kernel_snapshot failed: Exception
[        ]            #0      KernelSnapshot.build (package:flutter_tools/src/build_system/targets/common.dart:291:7)
[        ]            <asynchronous suspension>
[        ]            #1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:828:9)
[        ]            <asynchronous suspension>
[        ]            #2      Future.wait.<anonymous closure> (dart:async/future.dart)
[        ]            <asynchronous suspension>
[        ]            #3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:766:32)
[        ]            <asynchronous suspension>
[        ]            #4      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:595:16)
[        ]            <asynchronous suspension>
[        ]            #5      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:318:32)
[        ]            <asynchronous suspension>
[        ]            #6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
[        ]            <asynchronous suspension>
[        ]            #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #8      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
[        ]            <asynchronous suspension>
[        ]            #9      FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
[        ]            <asynchronous suspension>
[        ]            #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
[        ]            <asynchronous suspension>
[        ]            #12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
[        ]            <asynchronous suspension>
[        ]            #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #14     main (package:flutter_tools/executable.dart:91:3)
[        ]            <asynchronous suspension>
[        ] [   +6 ms] 
[        ]            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
[        ]            #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:335:7)
[        ]            <asynchronous suspension>
[        ]            #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
[        ]            <asynchronous suspension>
[        ]            #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
[        ]            <asynchronous suspension>
[        ]            #5      FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
[        ]            <asynchronous suspension>
[        ]            #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
[        ]            <asynchronous suspension>
[        ]            #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
[        ]            <asynchronous suspension>
[        ]            #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #10     main (package:flutter_tools/executable.dart:91:3)
[        ]            <asynchronous suspension>
[        ] [  +15 ms] "flutter assemble" took 10,676ms.
[ +279 ms] [ +234 ms] ensureAnalyticsSent: 232ms
[        ] [   +1 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 1
[        ] > Task :app:compileFlutterBuildDebug FAILED
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
[        ] 1 actionable task: 1 executed
[        ] FAILURE: Build failed with an exception.
[        ] * Where:
[        ] Script '/home/sharath/snap/flutter/common/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1035
[        ] * What went wrong:
[        ] Execution failed for task ':app:compileFlutterBuildDebug'.
[        ] > Process 'command '/home/sharath/snap/flutter/common/flutter/bin/flutter'' finished with non-zero exit value 1
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to
get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 13s
[ +430 ms] Running Gradle task 'assembleDebug'... (completed in 14.2s)
[   +5 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +2 ms] "flutter run" took 15,273ms.
[   +4 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:663:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[ +120 ms] ensureAnalyticsSent: 117ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
"
