### ISSUE TITLE
Starting an Activity with a cached engine containing platform views should recreate the platform views

### ISSUE THREAD

**Issue by bparrishMines** [flutter/flutter#88880]
When an engine is detached from a `FlutterActivity`. [FlutterActivity.release](https://github.com/flutter/engine/blob/6c8ef61b5358d54b62a7acd195b9994c4246cff1/shell/platform/android/io/flutter/embedding/android/FlutterActivity.java#L649) is called. This eventually leads down to calling [PlatformViewsController.destroyOverlaySurfaces](https://github.com/flutter/engine/blob/6c8ef61b5358d54b62a7acd195b9994c4246cff1/shell/platform/android/io/flutter/plugin/platform/PlatformViewsController.java#L970). And when the cached engine is detached from an Activity and reused with a new Activity this leads to:
```
E/flutter: [ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(49)] java.lang.IllegalStateException: The overlay surface (id:0) doesn't exist
        at io.flutter.plugin.platform.PlatformViewsController.onDisplayOverlaySurface(PlatformViewsController.java:796)
        at io.flutter.embedding.engine.FlutterJNI.onDisplayOverlaySurface(FlutterJNI.java:960)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:174)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
A/flutter: [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1414)] Check failed: CheckException(env). 
A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 15403 (e.myapplication), pid 15403 (e.myapplication)
``` 

Despite that, the old `PlatformView`s are attached to the old `Activity`, so all references should/will be removed. So I believe the only way Flutter could support detaching a cached engine containing `PlatformView`s and restarting a new Activity with it, is if it recreated all the `PlatformView`s with the new `Activity` and their creation arguments. (e.g. [PlatformViewFactory.create](https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/plugin/platform/PlatformViewFactory.java#L28)).

**Comment by bparrishMines** [comment]
affects https://github.com/googleads/googleads-mobile-flutter/issues/265

**Comment by blasten** [comment]
that seems like a more fundamental problem. The original bug was about the overlay surfaces, but I don't think a new message is sent to the platform.

@bparrishMines would you be interested in creating a test? I wonder if this has always been broken in virtual displays too.

**Comment by LongXiangGuo** [comment]
> 

I have met the seem issue in my project, e.g.  Used the cache engine -> Open WebView -> Change the darkMode -> return to webview,(webview is show a blank sceen and any javascript call will lead the app crashed), are there any temp solutions without recreate a new webview?

<details>
<summary>crash log</summary>
2967 ms] E/flutter (11896): [ERROR:flutter/fml/platform/android/jni_util.cc(182)] java.lang.IllegalStateException: The overlay surface (id:0) doesn't exist
[        ] E/flutter (11896): 	at io.flutter.plugin.platform.PlatformViewsController.onDisplayOverlaySurface(PlatformViewsController.java:821)
[        ] E/flutter (11896): 	at io.flutter.embedding.engine.FlutterJNI.onDisplayOverlaySurface(FlutterJNI.java:1010)
[        ] E/flutter (11896): 	at android.os.MessageQueue.nativePollOnce(Native Method)
[        ] E/flutter (11896): 	at android.os.MessageQueue.next(MessageQueue.java:363)
[        ] E/flutter (11896): 	at android.os.Looper.loop(Looper.java:176)
[        ] E/flutter (11896): 	at android.app.ActivityThread.main(ActivityThread.java:8668)
[        ] E/flutter (11896): 	at java.lang.reflect.Method.invoke(Native Method)
[        ] E/flutter (11896): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
[        ] E/flutter (11896): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
[        ] E/flutter (11896):
[        ] F/flutter (11896): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1403)] Check failed: fml::jni::CheckException(env).

</details>

<details>
<summary>flutter doctor</summary>
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 2.5.3, on macOS 11.5.1 20G80 darwin-x64, locale
    en-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Community Edition (version 2021.2)
[✓] VS Code (version 1.62.3)
[✓] Connected device (1 available)
    ! Error: US的iPhone is not connected. Xcode will continue when US的iPhone is
      connected. (code -13)

• No issues found!
</details>

**Comment by LongXiangGuo** [comment]
May be you can apply the configChanges in the AndroidManifest

> > 
> 
> I have met the seem issue in my project, e.g. Used the cache engine -> Open WebView -> Change the darkMode -> return to webview,(webview is show a blank sceen and any javascript call will lead the app crashed), are there any temp solutions without recreate a new webview?
> 
> crash log
> 2967 ms] E/flutter (11896): [ERROR:flutter/fml/platform/android/jni_util.cc(182)] java.lang.IllegalStateException: The overlay surface (id:0) doesn't exist [ ] E/flutter (11896): at io.flutter.plugin.platform.PlatformViewsController.onDisplayOverlaySurface(PlatformViewsController.java:821) [ ] E/flutter (11896): at io.flutter.embedding.engine.FlutterJNI.onDisplayOverlaySurface(FlutterJNI.java:1010) [ ] E/flutter (11896): at android.os.MessageQueue.nativePollOnce(Native Method) [ ] E/flutter (11896): at android.os.MessageQueue.next(MessageQueue.java:363) [ ] E/flutter (11896): at android.os.Looper.loop(Looper.java:176) [ ] E/flutter (11896): at android.app.ActivityThread.main(ActivityThread.java:8668) [ ] E/flutter (11896): at java.lang.reflect.Method.invoke(Native Method) [ ] E/flutter (11896): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) [ ] E/flutter (11896): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109) [ ] E/flutter (11896): [ ] F/flutter (11896): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1403)] Check failed: fml::jni::CheckException(env).
> flutter doctor

Since there is only one activity, fixed is by add the uiMode to `android:configChanges` in the AndroidManifest.

**Comment by houziruinb87** [comment]
Same Issue,How to fix this bug.

**Comment by allenymt** [comment]
> @blasten Today, I tried the newest code of the flutter engine (include commits in this pull request [flutter/engine#28894](https://github.com/flutter/engine/pull/28894)). And when the cached engine is detached from an Activity and reused with a new Activity, the app does not crash, but the PlatformView does not display.
> 
>  video.mp4

@blasten 
I reproduced the same problem

**Comment by bparrishMines** [comment]
@LongXiangGuo @houziruinb87 @allenymt As of now there isn't a workaround besides ensuring that you remove all Platform Views from the current screen before the engine is cached. Maintaining the View's state is the  main problem with starting a new Platform View with a new Activity. In theory this could be solved by adding a [save state](https://developer.android.com/topic/libraries/architecture/saving-states) to the Android `PlatformView` interface. But, we don't currently have anyone to work on this at the moment.
