### ISSUE TITLE
Error: Instance of 'AuthExceptionController'

### ISSUE THREAD

**Issue by cindRoberta** [flutter/flutter#89116]
what is the reason for this error?
```dart
// controller
void login(BuildContext context) async {
  isLoading.value = Status.loading;
  try {
    UserModel? user = await repository.signInWithEmailAndPassword(
          emailTextController.text, passwordTextController.text);

    if (user != null) {
      box.write("auth", user);
      QR.navigator.replaceAll('/initial');
    }
  } on AuthException catch (error) {
    throw AuthExceptionController(title: error.title, content: error.content);
  } finally {
    isLoading.value = Status.success;
  }
}

// page
onPressed: () {
  if (_formKey.currentState!.validate()) {
    try {
      _authenticationController.login(context);
    } on AuthExceptionController catch (error) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text(error.content)));
    }
  }
}
```
```
Error: Instance of 'AuthExceptionController'
    at Object.throw_ [as throw] (http://localhost:32773/dart_sdk.js:5079:11)
    at authentication_controller.AuthenticationController.init.login
    (http://localhost:32773/packages/triple_example/controller/authentication_controller.dart.lib.js:198:23)
    at login.throw (<anonymous>)
    at http://localhost:32773/dart_sdk.js:38634:38
    at _RootZone.runBinary (http://localhost:32773/dart_sdk.js:38504:59)
    at _FutureListener.thenAwait.handleError (http://localhost:32773/dart_sdk.js:33711:33)
    at handleError (http://localhost:32773/dart_sdk.js:34268:51)
    at Function._propagateToListeners (http://localhost:32773/dart_sdk.js:34294:17)
    at _Future.new.[_completeError] (http://localhost:32773/dart_sdk.js:34144:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:32773/dart_sdk.js:34180:31)
    at Object._microtaskLoop (http://localhost:32773/dart_sdk.js:38767:13)
    at _startMicrotaskLoop (http://localhost:32773/dart_sdk.js:38773:13)
    at http://localhost:32773/dart_sdk.js:34506:9
```

**Comment by cindRoberta** [comment]
```dart
// controller
Future<void> login() async {
  isLoading.value = Status.loading;
  try {
    UserModel? user = await repository.signInWithEmailAndPassword(
          emailTextController.text, passwordTextController.text);

    if (user != null) {
      box.write("auth", user);
      QR.navigator.replaceAll('/initial');
    }
  } on AuthException catch (error) {
    throw AuthException(title: error.title, content: error.content);
  } finally {
    isLoading.value = Status.success;
  }
}

// page
onPressed: () async {
  if (_formKey.currentState!.validate()) {
    try {
      await _authenticationController.login();
    } on AuthException catch (error) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text(error.content)));
    }
  }
}
```
