### ISSUE TITLE
Flutter crash report: `StateError: Bad state: Stream has already been listened to.` which used as debugger server by emacs dap-mode

### ISSUE THREAD

**Issue by zw963** [flutter/flutter#89132]
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter run --machine --start-paused --target lib/main.dart

## exception

StateError: Bad state: Stream has already been listened to.

```
#0      _StreamController._subscribe (dart:async/stream_controller.dart:635:7)
#1      _ControllerStream._createSubscription (dart:async/stream_controller.dart:786:19)
#2      _StreamImpl.listen (dart:async/stream_impl.dart:473:9)
#3      _Socket.listen (dart:io-patch/socket_patch.dart:2020:31)
#4      _StdStream.listen (dart:io/stdio.dart:22:20)
#5      new _SinkTransformerStreamSubscription (dart:async/stream_transformers.dart:49:16)
#6      _BoundSinkStream.listen (dart:async/stream_transformers.dart:171:9)
#7      new _SinkTransformerStreamSubscription (dart:async/stream_transformers.dart:49:16)
#8      _BoundSinkStream.listen (dart:async/stream_transformers.dart:171:9)
#9      new _ForwardingStreamSubscription (dart:async/stream_pipe.dart:114:10)
#10     _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:86:16)
#11     _ForwardingStream.listen (dart:async/stream_pipe.dart:81:12)
#12     new _ForwardingStreamSubscription (dart:async/stream_pipe.dart:114:10)
#13     _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:86:16)
#14     _ForwardingStream.listen (dart:async/stream_pipe.dart:81:12)
#15     new Daemon (package:flutter_tools/src/commands/daemon.dart:88:42)
#16     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:534:29)
<asynchronous suspension>
#17     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#19     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#20     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
<asynchronous suspension>
#21     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#22     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
<asynchronous suspension>
#23     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#24     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#25     main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale en_US.UTF-8)
    • Flutter version 2.2.3 at /home/zw963/Dropbox/linux/utils/flutter
    • Framework revision f4abaa0735 (8 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4
    • Pub download mirror https://mirrors.tuna.tsinghua.edu.cn/dart-pub
    • Flutter download mirror https://mirrors.tuna.tsinghua.edu.cn/flutter

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/zw963/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /home/zw963/Android/Sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/google-chrome-stable

[✓] Linux toolchain - develop for Linux desktop
    • clang version 12.0.1
    • cmake version 3.21.2
    • ninja version 1.10.2
    • pkg-config version 1.7.3

[✓] Android Studio (version 2020.3)
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 92.0.4515.159

• No issues found!
```

**Comment by darshankawar** [comment]
A similar issue was reported but got closed due to inactivity, https://github.com/flutter/flutter/issues/73931
Labeling this as applicable.

**Comment by zw963** [comment]
any update? if need more detail, please @ me.

**Comment by zw963** [comment]
keep active

**Comment by zw963** [comment]
It seem like works for me after several times update for client and emacs packages.

Thanks all.
