### ISSUE TITLE
flutter_test:expect in async fn to show stack trace

### ISSUE THREAD

**Issue by mleonhard** [flutter/flutter#89138]
I am writing tests for a mobile app.  The same set of calls to `flutter_test` appear many times in the tests, so I factored them out into a function.  Unfortunately, when an `expect` fails inside this function, the resulting error message does not show a full stack trace.  The error message contains only one line, the line inside the function.  The error does not show which line of the test called the function.  This omission occurs only when the function does an `await` before the failing `expect`.

Stack traces are important information for engineers trying to fix failing tests.  Let's change `flutter_test:expect` to show full stack traces.

## Steps to Reproduce

1. Run `flutter create example4`
2. Update the files as follows:

<details><summary>pubspec.yaml</summary>

```yaml
name: example4
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
flutter:
```

</details>

<details><summary>integration_test/example_test.dart</summary>

```dart
import 'package:example4/example_main.dart' show ExampleApp;
import 'package:flutter_test/flutter_test.dart'
    show expect, find, findsOneWidget, testWidgets, WidgetTester;
import 'package:integration_test/integration_test.dart'
    show IntegrationTestWidgetsFlutterBinding;

Future<void> checkForNonexistent(WidgetTester tester) async {
  await Future.delayed(Duration(milliseconds: 100));
  expect(find.text('nonexistent'), findsOneWidget);
}

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();
  testWidgets("test1", (WidgetTester tester) async {
    await tester.pumpWidget(ExampleApp());
    await checkForNonexistent(tester);
  });
}
```

</details>

<details><summary>lib/example_main.dart</summary>

```dart
// lib/example_main.dart
import 'package:flutter/cupertino.dart' show CupertinoApp, runApp;
import 'package:flutter/widgets.dart'
    show BuildContext, Center, Container, StatelessWidget, Text, Widget;

class ExampleApp extends StatelessWidget {
  @override
  Widget build(BuildContext ctx) =>
      CupertinoApp(home: Container(child: Center(child: Text('hello'))));
}

void main() {
  runApp(ExampleApp());
}
```

</details>

<details><summary>test_driver/integration_test.dart</summary>

```dart
import 'package:integration_test/integration_test_driver.dart'
    show integrationDriver;

Future<void> main() => integrationDriver();
```

</details>

3. Run `flutter drive`

**Expected results:**
A stack trace that includes the caller of the function:
```
When the exception was thrown, this was the stack:
#4      checkForNonexistent (file:///example4/integration_test/example_test.dart:9:3)
#5      main.<anonymous closure> (file:///example4/integration_test/example_test.dart:16:11)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)
```

**Actual results:**

```
When the exception was thrown, this was the stack:
#4      checkForNonexistent (file:///example4/integration_test/example_test.dart:9:3)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)
```

<details><summary>flutter drive output</summary>

```
example4 % flutter drive --driver=test_driver/integration_test.dart --target=integration_test/example_test.dart -d test-sim
Running "flutter pub get" in example4...                           722ms
Running Xcode build...                                                  
 └─Compiling, linking and signing...                      2,775ms
Xcode build done.                                           17.7s
VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:58211/d5PX7bSZ7XQ=/
VMServiceFlutterDriver: Isolate found with number: 2334125552352555
VMServiceFlutterDriver: Isolate is paused at start.
VMServiceFlutterDriver: Attempting to resume isolate
flutter: 00:00 +0: test1
VMServiceFlutterDriver: Connected to Flutter application.
flutter: (The following exception is now available via WidgetTester.takeException:)
flutter: ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
flutter: The following TestFailure object was thrown running a test:
flutter:   Expected: exactly one matching node in the widget tree
flutter:   Actual: _TextFinder:<zero widgets with text "nonexistent" (ignoring offstage widgets)>
flutter:    Which: means none were found but one was expected
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #4      checkForNonexistent (file:///example4/integration_test/example_test.dart:9:3)
flutter: <asynchronous suspension>
flutter: <asynchronous suspension>
flutter: (elided one frame from package:stack_trace)
flutter: ...
flutter:
flutter: This was caught by the test expectation on the following line:
flutter:   file:///example4/integration_test/example_test.dart line 9
flutter: The test description was:
flutter:   test1
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: (If WidgetTester.takeException is called, the above exception will be ignored. If it is not, then the above exception will be dumped when another exception is caught by the framework or when the test ends, whichever happens first, and
then the test will fail due to having not caught or expected the exception.)
flutter: ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
flutter: The following TestFailure object was thrown running a test:
flutter:   Expected: exactly one matching node in the widget tree
flutter:   Actual: _TextFinder:<zero widgets with text "nonexistent" (ignoring offstage widgets)>
flutter:    Which: means none were found but one was expected
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #4      checkForNonexistent (file:///example4/integration_test/example_test.dart:9:3)
flutter: <asynchronous suspension>
flutter: <asynchronous suspension>
flutter: (elided one frame from package:stack_trace)
flutter: ...
flutter:
flutter: This was caught by the test expectation on the following line:
flutter:   file:///example4/integration_test/example_test.dart line 9
flutter: The test description was:
flutter:   test1
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: 00:00 +0: test1 [E]
flutter:   Test failed. See exception logs above.
  The test description was: test1
flutter:
flutter: 00:00 +0 -1: (tearDownAll)
flutter: Warning: integration_test plugin was not detected.

If you're running the tests with `flutter drive`, please make sure your tests
are in the `integration_test/` directory of your package and use
`flutter test $path_to_test` to run it instead.

If you're running the tests with Android instrumentation or XCTest, this means
that you are not capturing test results properly! See the following link for
how to set up the integration_test plugin:

https://flutter.dev/docs/testing/integration-tests#testing-on-firebase-test-lab
flutter: 00:00 +1 -1: Some tests failed.
Failure Details:
Failure in method: test1
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following TestFailure object was thrown running a test:
  Expected: exactly one matching node in the widget tree
  Actual: _TextFinder:<zero widgets with text "nonexistent"
(ignoring offstage widgets)>
   Which: means none were found but one was expected

When the exception was thrown, this was the stack:
#4      checkForNonexistent (file:///example4/integration_test/example_test.dart:9:3)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///example4/integration_test/example_test.dart line 9
The test description was:
  test1
═════════════════════════════════════════════════════════════════

end of failure 1



Failed to stop app
example4 % 
```

</details>

<details><summary>flutter doctor -v output</summary>

```
example4 % flutter doctor -v
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.1 20G80 darwin-x64, locale en-US)
    • Flutter version 2.2.3 at /Users/user/.flutter
    • Framework revision f4abaa0735 (8 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Connected device (3 available)
    • test-sim (mobile) • E1A7325E-D299-42D4-A89C-B5DD7CF7DB06 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • iPhone 8 (mobile) • 87606CD6-83B2-433B-9458-FD6944930D2F • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)      • chrome                               • web-javascript • Google Chrome 92.0.4515.159
    ! Error: User's iPhone is not connected. Xcode will continue when User's iPhone is connected. (code -13)

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report and code sample. I see the same behavior on latest stable.

```
When the exception was thrown, this was the stack:
#0      throwErr1 (file:///int_test_sample/integration_test/app_test.dart:8:3)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)
```

<details>
<summary> flutter doctor -v </summary>

```
[[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.2.3 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision f4abaa0735 (9 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dhs/Library/Android/sdk
    • Java binary at: /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.    

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome    

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • SM G975F (mobile) • RZ8M802WY0X • android-arm64 • Android 10 (API 29)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 91.0.4472.114



```

</details>

**Comment by mleonhard** [comment]
I'm seeing this in all async tasks, not just the test's task.  A test just triggered a crash in a background task of an app.  The stack trace is cut off at the most recent `await`.

**Comment by mleonhard** [comment]
This is intolerable. :(

**Comment by jiahaog** [comment]
<details><summary>Repro with `flutter test`</summary>

```dart
import 'package:flutter/widgets.dart' show Container;
import 'package:flutter_test/flutter_test.dart';

Future<void> throwErr1() async {
  await Future.delayed(Duration(milliseconds: 100));
  throw 'err1';
}

void main() {
   LiveTestWidgetsFlutterBinding();
  testWidgets("test1", (WidgetTester tester) async {
    await tester.pumpWidget(Container());
    await throwErr1();
  });
}
```

</details>

I can't reproduce with just `test` instead of `testWidgets`, so it's probably something to do with the testAsyncUtils, or one of the zone wrappers in `testWidgets`.

Changing the Dart test runner to *not* use `--chain-stack-traces` causes the stack traces to show up properly. I'm not sure if we want to remove the flag though, since it results in an [unactionable message](https://github.com/flutter/flutter/issues/84966#issuecomment-866587953) that appears in all failed tests. #84966 is another issue that can be fixed by removing that flag.

**Comment by acoutts** [comment]
Having this issue as well. Are there any more ideas to enrich the stack traces? Makes it really hard to track down what part of a test failed.

**Comment by acoutts** [comment]
My workaround for now is to pass `StackTrace.current` as a function parameter to any function inside the test function that might throw or expect/fail, and append that stackTrace when it throws.

```dart
  Future<void> waitForPredicate(
    final bool Function() predicate, {
    final Duration timeout = const Duration(seconds: 30),
    required final String timeoutErrorMessage,
    required final StackTrace stackTrace,
  }) async {
    final start = DateTime.now();
    while (predicate() == false) {
      if (DateTime.now().difference(start).inMilliseconds >
          timeout.inMilliseconds) {
        throw '$timeoutErrorMessage\n$stackTrace';
      }
      await pumpRepeat(60);
    }

    /// Pump one more second before exiting
    await pumpRepeat(60);
  }

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  group('internal_payment_test', () {
    testWidgets(
      'should send an internal payment',
      (final tester) async {
        /// Start the app and test
        await startApp(tester);

        /// Wait for home screen
        await tester.waitForPredicate(
          () => find.byType(HomeScreen).evaluate().isNotEmpty,
          timeoutErrorMessage:
              '[internal_payment_test] waiting for HomeScreen to be visible}',
          stackTrace: StackTrace.current,
        );
     },
      tags: TestTags.driver,
    );
  });
}
```

With this I can see the stack trace I need (`internal_payment_test.dart:79:34`)
```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following message was thrown running a test:
[internal_payment_test] waiting for tx to be updated to completed
#0      main.<anonymous closure>.<anonymous closure>
(file:///......redacted...../integration_test/payment_tests/internal_payment_test.dart:79:34)
<asynchronous suspension>
#1      StackZoneSpecification._registerUnaryCallback.<anonymous closure>
(package:stack_trace/src/stack_zone_specification.dart:125:47)
<asynchronous suspension>

When the exception was thrown, this was the stack:
#0      TesterExt.waitForPredicate (file:///......redacted...../integration_test/_shared/widget_tester_ext.dart:38:9)
2
<asynchronous suspension>
(elided one frame from package:stack_trace)

The test description was:
  should send an internal payment
════════════════════════════════════════════════════════════════════════════════════════════════════
Test failed. See exception logs above.
The test description was: should send an internal payment

✖ internal_payment_test should send an internal payment
Exited (1)
```
