### ISSUE TITLE
BottomSheet class has enableDrag default to true, but doesn't enforce assigning an AnimationController

### ISSUE THREAD

**Issue by Lootwig** [flutter/flutter#89168]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows:

Replace the `_incrementCounter()` method with

```[dart]
void _incrementCounter() {
    showModalBottomSheet(
        context: context,
        builder: (_) {
          return BottomSheet(
              onClosing: () {},
              builder: (_) => Container(
                    height: 200,
                    color: Colors.red,
                  ));
        });
  }
```

3. Run the app, click the FAB, perform a drag gesture on the appearing sheet. Console logs exceptions, caused by a call to `widget.animationController!` in the bottom sheet code even though there is no such controller.

Controller assignment should either be enforced by asserts and documented, or the `_dismissUnderway` getter should use a `?` null check instead of `!` requirement.

<details>
  <summary>Logs</summary>

```
======== Exception caught by gesture ===============================================================
The following _CastError was thrown while handling a gesture:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      _BottomSheetState._dismissUnderway (package:flutter/src/material/bottom_sheet.dart:193:58)
#1      _BottomSheetState._handleDragEnd (package:flutter/src/material/bottom_sheet.dart:208:9)
#2      DragGestureRecognizer._checkEnd.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:473:47)
#3      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#4      DragGestureRecognizer._checkEnd (package:flutter/src/gestures/monodrag.dart:473:5)
...
Handler: "onEnd"
Recognizer: VerticalDragGestureRecognizer#d2597
  debugOwner: GestureDetector
  start behavior: start
====================================================================================================
```

```
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1165], locale en-US)
    • Flutter version 2.2.3 at C:\flutter
    • Framework revision f4abaa0735 (9 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\_\AppData\Local\Android\Sdk\
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\_\AppData\Local\Android\Sdk\
    • ANDROID_SDK_ROOT = C:\Users\_\AppData\Local\Android\Sdk\
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.30804.86
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2021.1.2
    • Flutter plugin version 59.0.4
    • Dart plugin version 212.4746.57

[√] VS Code (version 1.58.2)
    • VS Code at C:\Users\_\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.1.0

[√] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.1165]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 92.0.4515.159
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 92.0.902.84

• No issues found!

```

</details>

**Comment by TahaTesser** [comment]
Hi @Lootwig 
Thanks for filing the issue

### Reproducible code sample

<details> 
<summary>complete minimal runnable code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {

void _incrementCounter(BuildContext context) {
    showModalBottomSheet(
        context: context,
        builder: (_) {
          return BottomSheet(
              onClosing: () {},
              builder: (_) => Container(
                    height: 200,
                    color: Colors.red,
                  ));
        });
  }


  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text('Hello World'),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () => _incrementCounter(context),
      ),
    );
  }
}
``` 

</details>

### Logs

|  `stable`  | `master` |
| :---: |:---: |
|  ❗️  |   ❗️  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 12.0 21A5304g darwin-x64, locale en-US)
    • Flutter version 2.2.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision f4abaa0735 (9 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/tahatesser/Code/android-sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = /Users/tahatesser/Code/android-sdk
    • Java binary at: /Users/tahatesser/Code/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 13.0, Build version 13A5212g
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2020.3)
    • Android Studio at /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7621141/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios            • iOS 15.0
    • iPhone 12 (mobile)     • 77819686-4E78-4DC9-96A8-6D0E8587E397 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 12.0 21A5304g darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 92.0.4515.159

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel master, 2.6.0-1.0.pre.136, on macOS 12.0 21A5304g darwin-x64, locale en-US)
    • Flutter version 2.6.0-1.0.pre.136 at /Users/tahatesser/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 96f977f4df (3 hours ago), 2021-08-31 02:16:01 -0400
    • Engine revision fda0ac4520
    • Dart version 2.15.0 (build 2.15.0-66.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/tahatesser/Code/android-sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = /Users/tahatesser/Code/android-sdk
    • Java binary at: /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7621141/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7621141/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios            • iOS 15.0 19A5325f
    • iPhone 12 (mobile)     • 77819686-4E78-4DC9-96A8-6D0E8587E397 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 12.0 21A5304g darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 92.0.4515.159

• No issues found!
```

</details>

✅: No Issue ❗️: Issue reproduced

Thanks for filing the issue
