### ISSUE TITLE
Platform-specfic plugin throws `MissingPluginImplementation` on other platforms

### ISSUE THREAD

**Issue by guidezpl** [flutter/flutter#89191]
Repro steps:

```
flutter create test --template=plugin --platforms=android
cd test
flutter pub get
cd example
flutter create .
```

```
flutter run -d iphone
Launching lib/main.dart on iPhone 12 Pro in debug mode...
Warning: Missing build name (CFBundleShortVersionString).
Warning: Missing build number (CFBundleVersion).
Action Required: You must set a build name and number in the pubspec.yaml file version
field before submitting to the App Store.
Running pod install...                                           1,427ms
Running Xcode build...
 └─Compiling, linking and signing...                         6.6s
Xcode build done.                                           27.4s
Syncing files to device iPhone 12 Pro...                           201ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on iPhone 12 Pro is available at:
http://127.0.0.1:63917/ng648fSoWNo=/
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method getPlatformVersion on channel test)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
<asynchronous suspension>
#1      Test.platformVersion (package:test/test.dart:10:29)
<asynchronous suspension>
#2      _MyAppState.initPlatformState (package:test_example/main.dart:34:11)
<asynchronous suspension>
The Flutter DevTools debugger and profiler on iPhone 12 Pro is available at:
http://127.0.0.1:9100?uri=http://127.0.0.1:63917/ng648fSoWNo=/
```

```
flutter run -d chrome
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             17.0s
This app is linked to the debug service: ws://127.0.0.1:64948/hfHgDcz2wb0=/ws
Debug service listening on ws://127.0.0.1:64948/hfHgDcz2wb0=/ws

💪 Running with sound null safety 💪

🔥  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".

An Observatory debugger and profiler on Chrome is available at:
http://127.0.0.1:64948/hfHgDcz2wb0=
Error: MissingPluginException(No implementation found for method getPlatformVersion on
channel test)
    at Object.throw_ [as throw] (http://localhost:64860/dart_sdk.js:5079:11)
    at MethodChannel._invokeMethod
    (http://localhost:64860/packages/flutter/src/services/restoration.dart.lib.js:1526:2
    1)
    at _invokeMethod.next (<anonymous>)
    at http://localhost:64860/dart_sdk.js:38629:33
    at _RootZone.runUnary (http://localhost:64860/dart_sdk.js:38500:59)
    at _FutureListener.thenAwait.handleValue
    (http://localhost:64860/dart_sdk.js:33700:29)
    at handleValueCallback (http://localhost:64860/dart_sdk.js:34252:49)
    at Function._propagateToListeners (http://localhost:64860/dart_sdk.js:34290:17)
    at _Future.new.[_completeWithValue] (http://localhost:64860/dart_sdk.js:34138:23)
    at async._AsyncCallbackEntry.new.callback
    (http://localhost:64860/dart_sdk.js:34159:35)
    at Object._microtaskLoop (http://localhost:64860/dart_sdk.js:38767:13)
    at _startMicrotaskLoop (http://localhost:64860/dart_sdk.js:38773:13)
    at http://localhost:64860/dart_sdk.js:34506:9
The Flutter DevTools debugger and profiler on Chrome is available at:
http://127.0.0.1:9100?uri=http://127.0.0.1:64948/hfHgDcz2wb0=
```

I thought the new format used since https://github.com/flutter/flutter/issues/10288 would fix this issue.

`pubspec.yaml`:
```
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.example.test
        pluginClass: TestPlugin
```

**Comment by TahaTesser** [comment]
Hi @guidezpl 
Thanks for filing the issue, I think `flutter create .` shouldn't generate unsupported platforms I'm in the first place based on plugin supported platforms 

`flutter create --template=plugin --platforms=android test`


<details> 
<summary>logs</summary> 
	
```console
/Users/tahatesser/StudioProjects/test/example/android/app/src/main/java/io/flutt
er/plugins/GeneratedPluginRegistrant.java
[ +230 ms] Launching lib/main.dart on Chrome in debug mode...
[ +140 ms] Updating assets
[ +120 ms] Waiting for connection from debug service on Chrome...
[  +20 ms] Found plugin test at /Users/tahatesser/StudioProjects/test/
[  +18 ms] Found plugin test at /Users/tahatesser/StudioProjects/test/
[  +88 ms] <- reset
[  +11 ms] /Users/tahatesser/Code/flutter_master/bin/cache/dart-sdk/bin/dart
--disable-dart-dev
/Users/tahatesser/Code/flutter_master/bin/cache/artifacts/engine/darwin-x64/fron
tend_server.dart.snapshot --sdk-root
/Users/tahatesser/Code/flutter_master/bin/cache/flutter_web_sdk/ --incremental
--target=dartdevc --debugger-module-names --experimental-emit-debug-metadata
-DFLUTTER_WEB_AUTO_DETECT=true --output-dill
/var/folders/ml/gl4d5v8n2rn6qpd8yf3t7tl40000gn/T/flutter_tools.vpiuSL/flutter_to
ol.MJSl2J/app.dill --libraries-spec
file:///Users/tahatesser/Code/flutter_master/bin/cache/flutter_web_sdk/libraries
.json --packages
/Users/tahatesser/StudioProjects/test/example/.dart_tool/package_config.json
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts
--track-widget-creation --filesystem-root
/var/folders/ml/gl4d5v8n2rn6qpd8yf3t7tl40000gn/T/flutter_tools.vpiuSL/flutter_to
ols.FD7LGW --filesystem-scheme org-dartlang-app --initialize-from-dill
build/b1b715402d823b7fd5c2b68d2edcb2ce.cache.dill.track.dill --platform
file:///Users/tahatesser/Code/flutter_master/bin/cache/flutter_web_sdk/kernel/fl
utter_ddc_sdk_sound.dill --sound-null-safety
[  +21 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+17672 ms] Waiting for connection from debug service on Chrome... (completed in
17.8s)
[   +1 ms] Synced 26.3MB.
[        ] <- accept
[        ] Caching compiled dill
[ +121 ms] Using Google Chrome 92.0.4515.159 

[   +9 ms] executing: sysctl hw.optional.arm64
[   +6 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[ +650 ms] [CHROME]:
[   +1 ms] [CHROME]:DevTools listening on
ws://127.0.0.1:59714/devtools/browser/500a3a7d-8ffb-4878-8db3-9aec2efc7b2d
[+1681 ms] DwdsInjector: Received request for entrypoint at
http://localhost:59674/main_module.bootstrap.js
[   +5 ms] MetadataProvider: Loading debug metadata...
[  +17 ms] MetadataProvider: Loaded debug metadata (sound null safety)
[   +7 ms] DwdsInjector: Injected debugging metadata for entrypoint at
http://localhost:59674/main_module.bootstrap.js
[+1947 ms] ChromeProxyService: Initializing expression compiler for
main_module.bootstrap.js with sound null safety: true
[ +112 ms] DevHandler: Debug service listening on
ws://127.0.0.1:59742/4ZwAPEmVytQ=/ws

[  +33 ms] This app is linked to the debug service:
ws://127.0.0.1:59742/4ZwAPEmVytQ=/ws
[  +16 ms] Debug service listening on ws://127.0.0.1:59742/4ZwAPEmVytQ=/ws
[        ] 💪 Running with sound null safety 💪
[   +6 ms] 🔥  To hot restart changes while running, press "r" or "R".
[   +1 ms] For a more detailed help message, press "h". To quit, press "q".
[   +1 ms] An Observatory debugger and profiler on Chrome is available at:
           http://127.0.0.1:59742/4ZwAPEmVytQ=
[+1214 ms] DevTools activation throttled until 2021-08-31 22:54:31.913929.
[+2247 ms] Error: MissingPluginException(No implementation found for method
                    getPlatformVersion on channel test)
                        at Object.throw_ [as throw]
(http://localhost:59674/dart_sdk.js:5079:11)
                        at MethodChannel._invokeMethod

(http://localhost:59674/packages/flutter/src/services/restoration.dart.lib.j
                        s:1526:21)
                        at _invokeMethod.next (<anonymous>)
                        at http://localhost:59674/dart_sdk.js:38642:33
                        at _RootZone.runUnary
(http://localhost:59674/dart_sdk.js:38513:59)
                        at _FutureListener.thenAwait.handleValue
                        (http://localhost:59674/dart_sdk.js:33713:29)
                        at handleValueCallback
(http://localhost:59674/dart_sdk.js:34265:49)
                        at Function._propagateToListeners
                        (http://localhost:59674/dart_sdk.js:34303:17)
                        at _Future.new.[_completeWithValue]
                        (http://localhost:59674/dart_sdk.js:34151:23)
                        at async._AsyncCallbackEntry.new.callback
                        (http://localhost:59674/dart_sdk.js:34172:35)
                        at Object._microtaskLoop
(http://localhost:59674/dart_sdk.js:38780:13)
                        at _startMicrotaskLoop
(http://localhost:59674/dart_sdk.js:38786:13)
                        at http://localhost:59674/dart_sdk.js:34519:9
[   +5 ms] The Flutter DevTools debugger and profiler on Chrome is available at:
           http://127.0.0.1:9104?uri=http://127.0.0.1:59742/4ZwAPEmVytQ=
```
	
</details>


### Logs

|  `stable`  | `master` |
| :---: |:---: |
|  ❗️  |   ❗️  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 12.0 21A5304g darwin-x64, locale en-US)
    • Flutter version 2.2.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision f4abaa0735 (9 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/tahatesser/Code/android-sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = /Users/tahatesser/Code/android-sdk
    • Java binary at: /Users/tahatesser/Code/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 13.0, Build version 13A5212g
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2020.3)
    • Android Studio at /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7621141/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios            • iOS 15.0
    • iPhone 12 (mobile)     • 77819686-4E78-4DC9-96A8-6D0E8587E397 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 12.0 21A5304g darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 92.0.4515.159

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel master, 2.6.0-1.0.pre.136, on macOS 12.0 21A5304g darwin-x64, locale en-US)
    • Flutter version 2.6.0-1.0.pre.136 at /Users/tahatesser/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 96f977f4df (3 hours ago), 2021-08-31 02:16:01 -0400
    • Engine revision fda0ac4520
    • Dart version 2.15.0 (build 2.15.0-66.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/tahatesser/Code/android-sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = /Users/tahatesser/Code/android-sdk
    • Java binary at: /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7621141/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7621141/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios            • iOS 15.0 19A5325f
    • iPhone 12 (mobile)     • 77819686-4E78-4DC9-96A8-6D0E8587E397 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 12.0 21A5304g darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 92.0.4515.159

• No issues found!
```
		
</details>

✅: No Issue ❗️: Issue reproduced

Thanks for filing the issue

**Comment by stuartmorgan** [comment]
> Unhandled Exception: MissingPluginException(No implementation found for method getPlatformVersion on channel test)
> #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)

This error message is correct, and this is the expected behavior of calling a platform channel method when no handler is registered for that channel.

> I thought the new format used since #10288 would fix this issue.

I'm not sure what you mean by "fix"; what do you expect to happen when you call a method that has no implementation?

(Also, that issue was not about runtime behavior.)

**Comment by stuartmorgan** [comment]
> I think `flutter create .` shouldn't generate unsupported platforms I'm in the first place based on plugin-supported platforms.

It wasn't run in the plugin package, it was run in the example package, which is an app. An app has no concept of supported platforms beyond what platforms have been added to it, and that command was requesting adding all platforms.

If someone goes out of their way to add more platforms to their example than were created as part of the plugin creation, as was done here, they are welcome to do so. There are valid use cases for doing so (e.g., if the plugin's Dart code is intended to do special handling for unsupported platforms.)

**Comment by TahaTesser** [comment]
@stuartmorgan 

> 
If someone goes out of their way to add more platforms to their example than were created as part of the plugin creation, as was done here, they are welcome to do so. There are valid use cases for doing so (e.g., if the plugin's Dart code is intended to do special handling for unsupported platforms.)


That's interesting, haven't thought about that, thanks

**Comment by guidezpl** [comment]
> I'm not sure what you mean by "fix"; what do you expect to happen when you call a method that has no implementation?
> (Also, that issue was not about runtime behavior.)

I assumed, wrongly, that declaring a plugin for one platform would cause its use to be ignore on other platforms.

@stuartmorgan So is it correct to say consumers of platform-specific plugins are responsible for gating its use on other platforms, something like:

```
if (TargetPlatform.android) {
   android_only_plugin.getPlatformVersion(...)
} else {
 ...
}
```

The other option is to register a dummy handler for all non-supported platforms to avoid consumers having to do this, which feels wrong.

**Comment by stuartmorgan** [comment]
> [...] would cause its use to be ignore on other platforms.

It's not just that it doesn't do this, but "ignored" is not even a clearly defined concept here. If someone writes:
```
final String version = android_only_plugin.getPlatformVersion()
```
what would it mean to ignore it? Never returning from the `await`? Trying to define a special value for every type that corresponds to "ignored"? (To illustrate the problem with the latter: what value would you choose, arbitrarily, for all calls that return a `bool` to automatically return?)

> @stuartmorgan So is it correct to say consumers of platform-specific plugins are responsible for gating its use on other platforms

Not as a statement of fact, no. That's often the expected pattern, but it's entirely up to the plugin author how they want to handle other platforms.

> The other option is to register a dummy handler for all non-supported platforms to avoid consumers having to do this, which feels wrong.

That isn't the only other option (and it would be a very poor one for several reasons); method channels are an internal implementation detail of plugins, and how the plugin's Dart code chooses to use them is up to the plugin author. There's no reason, for instance, that a plugin author couldn't write the following:

```
Future<String?> getPlatformVersion() async {
  if (TargetPlatform.isAndroid) {
    ...
  } else {
    return null;
  }
}
```

I don't think that's probably a good idea in most cases, including that one, but it depends a lot on the specific use case. A much more reasonable example is:

```
Future<void> configureAndroidThing() async {
  if (TargetPlatform.isAndroid) {
    ...
  } else {
    // This thing doesn't make sense on any other platform, and there's no reason for a caller to
    // do anything other than no-op on another platform, so just do it internally.
  }
}
```

**Comment by guidezpl** [comment]
Thanks for the detailed answer. I should have RTFM, what I was looking for was [`OptionalMethodChannel`](https://api.flutter.dev/flutter/services/OptionalMethodChannel-class.html)
