### ISSUE TITLE
Flaky failures "Error: Unable to create sample for packages/flutter/lib/src/material/switch_list_tile.dart:79" on Flutter HHH

### ISSUE THREAD

**Issue by alexmarkov** [flutter/flutter#89243]
Flutter HEAD-HEAD-HEAD bot sometimes fails on "flutter analyze" step with the following error:

```
▌09:00:27▐ Sample code...
▌09:00:27▐ RUNNING: cd .; bin/cache/dart-sdk/bin/dart /b/s/w/ir/cache/builder/flutter/dev/bots/analyze_sample_code.dart
Found 365 snippet code blocks, 43 sample code sections, and 225 dartpad sections.
Unhandled exception:
packages/flutter/lib/src/material/switch_list_tile.dart:79: Error: Unable to create sample for packages/flutter/lib/src/material/switch_list_tile.dart:79 (using input from /b/s/w/ir/x/t/flutter_analyze_sample_code.IVDKPE/sample.packages.flutter.lib.src.material.switch_list_tile.79.input):

Cannot delete file, path = '/home/chrome-bot/.pub-cache/bin/snippets' (OS Error: No such file or directory, errno = 2)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
ERROR: Last command exited with 255 (expected: zero).
Command: bin/cache/dart-sdk/bin/dart /b/s/w/ir/cache/builder/flutter/dev/bots/analyze_sample_code.dart
Relative working directory: .
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

Logs:
https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8837374353113050129/+/u/flutter_analyze/stdout
https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8837595170234499361/+/u/flutter_analyze/stdout

/cc @gspencergoog

**Comment by gspencergoog** [comment]
This doesn't feel like something to do with the sample code analysis itself: perhaps the fact that the snippets package was activated with `pub global activate snippets`?

The location is says it's trying to delete is the executable that is installed by the global activate, so maybe something else is removing it at the same time, and it's a race as to who gets there first?

The analysis code will try and recursively delete the temporary directory it created, but that temporary directory is not in `/home/chrome-bot`, so I don't know how it would try and delete that.

The "unable to create sample" message is just because it can't run the snippets tool, which, if it doesn't exist, would make it hard to run. :)

**Comment by TahaTesser** [comment]
Adding wait label on the issue, awaiting response on the comment above

**Comment by alexmarkov** [comment]
@jonasfj @jakemac53 In case this is a `pub` bug.

@athomas Do you know why `pub global activate snippets` might not work on Flutter HHH bot and what could be running in parallel with that test?

**Comment by jakemac53** [comment]
Is it possible to get a stack trace for this error?

**Comment by athomas** [comment]
The Dart infrastructure doesn't run things in parallel, but flutter's test runner might. I also don't what could cause the `pub global activate` to fail.

**Comment by gspencergoog** [comment]
Is there some part of the infrastructure that removes the pub cache?

**Comment by athomas** [comment]
Not while the a task is running. Between tasks, it's possible (but I wouldn't expect it to happen unless the VM is recycled).

**Comment by gspencergoog** [comment]
I've been helping the pub folks repro this: https://github.com/dart-lang/pub/issues/3165
It does appear to be something with pub, but the latest version of Dart sdk has possibly solved this, or at least moved the race.

**Comment by sigmundch** [comment]
Another instance today in the flutter-hhh web bots too: https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8830488649796574689/+/u/flutter_analyze/stdout

**Comment by alexmarkov** [comment]
Still happens:

```
/b/s/w/ir/cache/builder/engine/src/out/host_debug/dart-sdk/bin/dart pub global run snippets --output=/b/s/w/ir/x/t/flutter_analyze_sample_code.FVHRRV/sample.packages.flutter.lib.src.cupertino.page_scaffold.22.dart --input=/b/s/w/ir/x/t/flutter_analyze_sample_code.FVHRRV/sample.packages.flutter.lib.src.cupertino.page_scaffold.22.input --no-format-output
 Creating /b/s/w/ir/x/t/flutter_analyze_sample_code.FVHRRV/sample.packages.flutter.lib.src.cupertino.nav_bar.230.input.
 Writing /b/s/w/ir/x/t/flutter_analyze_sample_code.FVHRRV/sample.packages.flutter.lib.src.cupertino.nav_bar.230.input.
 Generating sample for packages/flutter/lib/src/cupertino/nav_bar.dart:230
 /b/s/w/ir/cache/builder/engine/src/out/host_debug/dart-sdk/bin/dart pub global run snippets --output=/b/s/w/ir/x/t/flutter_analyze_sample_code.FVHRRV/sample.packages.flutter.lib.src.cupertino.nav_bar.230.dart --input=/b/s/w/ir/x/t/flutter_analyze_sample_code.FVHRRV/sample.packages.flutter.lib.src.cupertino.nav_bar.230.input --no-format-output
 Creating /b/s/w/ir/x/t/flutter_analyze_sample_code.FVHRRV/sample.packages.flutter.lib.src.cupertino.scrollbar.42.input.
 Writing /b/s/w/ir/x/t/flutter_analyze_sample_code.FVHRRV/sample.packages.flutter.lib.src.cupertino.scrollbar.42.input.
 Generating sample for packages/flutter/lib/src/cupertino/scrollbar.dart:42
 /b/s/w/ir/cache/builder/engine/src/out/host_debug/dart-sdk/bin/dart pub global run snippets --output=/b/s/w/ir/x/t/flutter_analyze_sample_code.FVHRRV/sample.packages.flutter.lib.src.cupertino.scrollbar.42.dart --input=/b/s/w/ir/x/t/flutter_analyze_sample_code.FVHRRV/sample.packages.flutter.lib.src.cupertino.scrollbar.42.input --no-format-output
 Creating /b/s/w/ir/x/t/flutter_analyze_sample_code.FVHRRV/sample.packages.flutter.lib.src.cupertino.scrollbar.52.input.
 Writing /b/s/w/ir/x/t/flutter_analyze_sample_code.FVHRRV/sample.packages.flutter.lib.src.cupertino.scrollbar.52.input.
 Generating sample for packages/flutter/lib/src/cupertino/scrollbar.dart:52
 /b/s/w/ir/cache/builder/engine/src/out/host_debug/dart-sdk/bin/dart pub global run snippets --output=/b/s/w/ir/x/t/flutter_analyze_sample_code.FVHRRV/sample.packages.flutter.lib.src.cupertino.scrollbar.52.dart --input=/b/s/w/ir/x/t/flutter_analyze_sample_code.FVHRRV/sample.packages.flutter.lib.src.cupertino.scrollbar.52.input --no-format-output
 Cannot delete file, path = '/home/chrome-bot/.pub-cache/bin/snippets' (OS Error: No such file or directory, errno = 2)
 Can't load Kernel binary: Invalid kernel binary: Indicated size is invalid.
 Creating /b/s/w/ir/x/t/flutter_analyze_sample_code.FVHRRV/sample.packages.flutter.lib.src.cupertino.refresh.270.input.
 Writing /b/s/w/ir/x/t/flutter_analyze_sample_code.FVHRRV/sample.packages.flutter.lib.src.cupertino.refresh.270.input.
 Generating sample for packages/flutter/lib/src/cupertino/refresh.dart:270
 /b/s/w/ir/cache/builder/engine/src/out/host_debug/dart-sdk/bin/dart pub global run snippets --output=/b/s/w/ir/x/t/flutter_analyze_sample_code.FVHRRV/sample.packages.flutter.lib.src.cupertino.refresh.270.dart --input=/b/s/w/ir/x/t/flutter_analyze_sample_code.FVHRRV/sample.packages.flutter.lib.src.cupertino.refresh.270.input --no-format-output
 Unhandled exception:
 packages/flutter/lib/src/cupertino/scrollbar.dart:42: Error: Unable to create sample for packages/flutter/lib/src/cupertino/scrollbar.dart:42 (using input from /b/s/w/ir/x/t/flutter_analyze_sample_code.FVHRRV/sample.packages.flutter.lib.src.cupertino.scrollbar.42.input).
```
https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8829666902513887617/+/u/flutter_analyze/stdout

**Comment by sigmundch** [comment]
similar error today:
https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8829127541665632737/+/u/flutter_analyze/stdout

```
RUNNING: cd .; bin/cache/dart-sdk/bin/dart /b/s/w/ir/cache/builder/flutter/dev/bots/analyze_sample_code.dart --verbose
Found 367 snippet code blocks, 38 sample code sections, and 238 dartpad sections.
Creating /b/s/w/ir/x/t/flutter_analyze_sample_code.PWIJQV/sample.packages.flutter.lib.src.cupertino.page_scaffold.22.input.
Writing /b/s/w/ir/x/t/flutter_analyze_sample_code.PWIJQV/sample.packages.flutter.lib.src.cupertino.page_scaffold.22.input.
Generating sample for packages/flutter/lib/src/cupertino/page_scaffold.dart:22
/b/s/w/ir/cache/builder/flutter/bin/flutter --version --machine
{
  "frameworkVersion": "2.6.0-12.0.pre.854",
  "channel": "unknown",
  "repositoryUrl": "unknown source",
  "frameworkRevision": "361d416e6abb66bf601c5a6600fbc37706bb6c14",
  "frameworkCommitDate": "2021-11-29 22:01:32 -0800",
  "engineRevision": "7ba215c2c6a0c30d2f1630ef46fdbff9bed608b1",
  "dartSdkVersion": "2.16.0 (build 2.16.0-edge.1926ff8c6798ecd0ad88d544091411933519e808)",
  "devToolsVersion": "2.8.0",
  "flutterRoot": "/b/s/w/ir/cache/builder/flutter"
}
/b/s/w/ir/cache/builder/engine/src/out/host_debug/dart-sdk/bin/dart pub global run snippets --output=/b/s/w/ir/x/t/flutter_analyze_sample_code.PWIJQV/sample.packages.flutter.lib.src.cupertino.page_scaffold.22.dart --input=/b/s/w/ir/x/t/flutter_analyze_sample_code.PWIJQV/sample.packages.flutter.lib.src.cupertino.page_scaffold.22.input --no-format-output
Creating /b/s/w/ir/x/t/flutter_analyze_sample_code.PWIJQV/sample.packages.flutter.lib.src.cupertino.nav_bar.230.input.
Writing /b/s/w/ir/x/t/flutter_analyze_sample_code.PWIJQV/sample.packages.flutter.lib.src.cupertino.nav_bar.230.input.
Generating sample for packages/flutter/lib/src/cupertino/nav_bar.dart:230
/b/s/w/ir/cache/builder/engine/src/out/host_debug/dart-sdk/bin/dart pub global run snippets --output=/b/s/w/ir/x/t/flutter_analyze_sample_code.PWIJQV/sample.packages.flutter.lib.src.cupertino.nav_bar.230.dart --input=/b/s/w/ir/x/t/flutter_analyze_sample_code.PWIJQV/sample.packages.flutter.lib.src.cupertino.nav_bar.230.input --no-format-output
Creating /b/s/w/ir/x/t/flutter_analyze_sample_code.PWIJQV/sample.packages.flutter.lib.src.cupertino.scrollbar.42.input.
Writing /b/s/w/ir/x/t/flutter_analyze_sample_code.PWIJQV/sample.packages.flutter.lib.src.cupertino.scrollbar.42.input.
Generating sample for packages/flutter/lib/src/cupertino/scrollbar.dart:42
/b/s/w/ir/cache/builder/engine/src/out/host_debug/dart-sdk/bin/dart pub global run snippets --output=/b/s/w/ir/x/t/flutter_analyze_sample_code.PWIJQV/sample.packages.flutter.lib.src.cupertino.scrollbar.42.dart --input=/b/s/w/ir/x/t/flutter_analyze_sample_code.PWIJQV/sample.packages.flutter.lib.src.cupertino.scrollbar.42.input --no-format-output
Creating /b/s/w/ir/x/t/flutter_analyze_sample_code.PWIJQV/sample.packages.flutter.lib.src.cupertino.scrollbar.52.input.
Writing /b/s/w/ir/x/t/flutter_analyze_sample_code.PWIJQV/sample.packages.flutter.lib.src.cupertino.scrollbar.52.input.
Generating sample for packages/flutter/lib/src/cupertino/scrollbar.dart:52
/b/s/w/ir/cache/builder/engine/src/out/host_debug/dart-sdk/bin/dart pub global run snippets --output=/b/s/w/ir/x/t/flutter_analyze_sample_code.PWIJQV/sample.packages.flutter.lib.src.cupertino.scrollbar.52.dart --input=/b/s/w/ir/x/t/flutter_analyze_sample_code.PWIJQV/sample.packages.flutter.lib.src.cupertino.scrollbar.52.input --no-format-output
Could not make "/home/chrome-bot/.pub-cache/bin/snippets" executable (exit code 1):
chmod: cannot access '/home/chrome-bot/.pub-cache/bin/snippets': No such file or directory
Could not make "/home/chrome-bot/.pub-cache/bin/snippets" executable (exit code 1):
chmod: cannot access '/home/chrome-bot/.pub-cache/bin/snippets': No such file or directory
Creating /b/s/w/ir/x/t/flutter_analyze_sample_code.PWIJQV/sample.packages.flutter.lib.src.cupertino.refresh.270.input.
Writing /b/s/w/ir/x/t/flutter_analyze_sample_code.PWIJQV/sample.packages.flutter.lib.src.cupertino.refresh.270.input.
Generating sample for packages/flutter/lib/src/cupertino/refresh.dart:270
/b/s/w/ir/cache/builder/engine/src/out/host_debug/dart-sdk/bin/dart pub global run snippets --output=/b/s/w/ir/x/t/flutter_analyze_sample_code.PWIJQV/sample.packages.flutter.lib.src.cupertino.refresh.270.dart --input=/b/s/w/ir/x/t/flutter_analyze_sample_code.PWIJQV/sample.packages.flutter.lib.src.cupertino.refresh.270.input --no-format-output
Unhandled exception:
packages/flutter/lib/src/cupertino/nav_bar.dart:230: Error: Unable to create sample for packages/flutter/lib/src/cupertino/nav_bar.dart:230 (using input from /b/s/w/ir/x/t/flutter_analyze_sample_code.PWIJQV/sample.packages.flutter.lib.src.cupertino.nav_bar.230.input).
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
ERROR: Last command exited with 255 (expected: zero).
Command: bin/cache/dart-sdk/bin/dart /b/s/w/ir/cache/builder/flutter/dev/bots/analyze_sample_code.dart --verbose
Relative working directory: .
```

**Comment by scheglov** [comment]
Now it happens on almost all my CLs.
https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8828388651774018545/+/u/analyze_flutter_flutter/stdout

**Comment by alexmarkov** [comment]
Failed once again:

```
/b/s/w/ir/cache/builder/engine/src/out/host_debug/dart-sdk/bin/dart pub global run snippets --output=/b/s/w/ir/x/t/flutter_analyze_sample_code.VLLHIB/sample.packages.flutter.lib.src.cupertino.page_scaffold.22.dart --input=/b/s/w/ir/x/t/flutter_analyze_sample_code.VLLHIB/sample.packages.flutter.lib.src.cupertino.page_scaffold.22.input --no-format-output
Creating /b/s/w/ir/x/t/flutter_analyze_sample_code.VLLHIB/sample.packages.flutter.lib.src.cupertino.nav_bar.230.input.
Writing /b/s/w/ir/x/t/flutter_analyze_sample_code.VLLHIB/sample.packages.flutter.lib.src.cupertino.nav_bar.230.input.
Generating sample for packages/flutter/lib/src/cupertino/nav_bar.dart:230
/b/s/w/ir/cache/builder/engine/src/out/host_debug/dart-sdk/bin/dart pub global run snippets --output=/b/s/w/ir/x/t/flutter_analyze_sample_code.VLLHIB/sample.packages.flutter.lib.src.cupertino.nav_bar.230.dart --input=/b/s/w/ir/x/t/flutter_analyze_sample_code.VLLHIB/sample.packages.flutter.lib.src.cupertino.nav_bar.230.input --no-format-output
Creating /b/s/w/ir/x/t/flutter_analyze_sample_code.VLLHIB/sample.packages.flutter.lib.src.cupertino.scrollbar.42.input.
Writing /b/s/w/ir/x/t/flutter_analyze_sample_code.VLLHIB/sample.packages.flutter.lib.src.cupertino.scrollbar.42.input.
Generating sample for packages/flutter/lib/src/cupertino/scrollbar.dart:42
/b/s/w/ir/cache/builder/engine/src/out/host_debug/dart-sdk/bin/dart pub global run snippets --output=/b/s/w/ir/x/t/flutter_analyze_sample_code.VLLHIB/sample.packages.flutter.lib.src.cupertino.scrollbar.42.dart --input=/b/s/w/ir/x/t/flutter_analyze_sample_code.VLLHIB/sample.packages.flutter.lib.src.cupertino.scrollbar.42.input --no-format-output
Creating /b/s/w/ir/x/t/flutter_analyze_sample_code.VLLHIB/sample.packages.flutter.lib.src.cupertino.scrollbar.52.input.
Writing /b/s/w/ir/x/t/flutter_analyze_sample_code.VLLHIB/sample.packages.flutter.lib.src.cupertino.scrollbar.52.input.
Generating sample for packages/flutter/lib/src/cupertino/scrollbar.dart:52
/b/s/w/ir/cache/builder/engine/src/out/host_debug/dart-sdk/bin/dart pub global run snippets --output=/b/s/w/ir/x/t/flutter_analyze_sample_code.VLLHIB/sample.packages.flutter.lib.src.cupertino.scrollbar.52.dart --input=/b/s/w/ir/x/t/flutter_analyze_sample_code.VLLHIB/sample.packages.flutter.lib.src.cupertino.scrollbar.52.input --no-format-output
Cannot delete file, path = '/home/chrome-bot/.pub-cache/bin/snippets' (OS Error: No such file or directory, errno = 2)
Could not make "/home/chrome-bot/.pub-cache/bin/snippets" executable (exit code 1):
chmod: cannot access '/home/chrome-bot/.pub-cache/bin/snippets': No such file or directory
Creating /b/s/w/ir/x/t/flutter_analyze_sample_code.VLLHIB/sample.packages.flutter.lib.src.cupertino.refresh.270.input.
Writing /b/s/w/ir/x/t/flutter_analyze_sample_code.VLLHIB/sample.packages.flutter.lib.src.cupertino.refresh.270.input.
Generating sample for packages/flutter/lib/src/cupertino/refresh.dart:270
/b/s/w/ir/cache/builder/engine/src/out/host_debug/dart-sdk/bin/dart pub global run snippets --output=/b/s/w/ir/x/t/flutter_analyze_sample_code.VLLHIB/sample.packages.flutter.lib.src.cupertino.refresh.270.dart --input=/b/s/w/ir/x/t/flutter_analyze_sample_code.VLLHIB/sample.packages.flutter.lib.src.cupertino.refresh.270.input --no-format-output
Unhandled exception:
packages/flutter/lib/src/cupertino/scrollbar.dart:52: Error: Unable to create sample for packages/flutter/lib/src/cupertino/scrollbar.dart:52 (using input from /b/s/w/ir/x/t/flutter_analyze_sample_code.VLLHIB/sample.packages.flutter.lib.src.cupertino.scrollbar.52.input).
#0      SampleChecker._writeSample (file:///b/s/w/ir/cache/builder/flutter/dev/bots/analyze_sample_code.dart:515:7)
<asynchronous suspension>
#1      _TaskQueueItem.run (file:///b/s/w/ir/cache/builder/flutter/dev/bots/analyze_sample_code.dart:171:27)
<asynchronous suspension>
```

https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8827864703397373169/+/u/flutter_analyze/stdout

**Comment by sigmundch** [comment]
@gspencergoog - since this issue is still happening, would you be OK if we change this step to not run generate snippets in parallel to keep the bot from flaking for now?

**Comment by gspencergoog** [comment]
@sigmundch I think part of the reason (if I remember correctly) I converted it originally was so that it wouldn't take too long for the CI bot time limits. But if it still fits within the time limits, then sure.  Ideally, I could still run it locally in parallel.

Also, I'd definitely rather get a fix for the root problem: it should be safe to run pub in parallel. Disabling it should be a short-term band-aid.

**Comment by sigmundch** [comment]
:crossed_fingers: a few changes landed in pub that can potentially address the existing flakiness: https://github.com/dart-lang/pub/issues/3165

Let's keen an eye on this bot and close this issue if we don't see more instances of this in the next week.

**Comment by sigmundch** [comment]
Unfortunately I saw this failure again in the HHH bot: https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8824124226668318801/+/u/flutter_analyze/stdout

@sigurdm  - are the fixes from https://github.com/dart-lang/pub/commit/8f5ab7b1aba3b9f66b56246d77e167990339d317 rolled into the Dart SDK?

**Comment by sigmundch** [comment]
Just found the version in our DEPS, it appears still from back in December, so it doesn't have the fixes.

@sigurdm - keep us posted when the roll occurs so we can monitor this issue.

Thanks!

**Comment by sigurdm** [comment]
Keep an eye on https://dart-review.googlesource.com/c/sdk/+/226103

**Comment by sigurdm** [comment]
Sorry - that was an old roll - the right url is: https://dart-review.googlesource.com/c/sdk/+/229542

**Comment by sigmundch** [comment]
I have not seen this failure come up in the last 200 runs of the flutter-analyze bot.  [The fixes][1] from @sigurdm landed in the main Dart branch in https://github.com/dart-lang/sdk/commit/bc7554107bf733687231981da6f7f1bc892999bd on Jan 27 and the last failure of this kind was two days prior to that on Jan 25! I'm cautiously optimistic that the last set of changes did the trick. woohoo! 🎉🎉 

I'll close this issue at this time, but we can reopen if we encounter it again.

[1]: https://github.com/dart-lang/pub/pull/3285
