### ISSUE TITLE
[camera] `setExposureOffset` throws null exception

### ISSUE THREAD

**Issue by AlexV525** [flutter/flutter#89281]
## Steps to Reproduce

When the min offset is `-2` and max is `2`:

```dart
controller.setExposureOffset(0);
```

Throws:
```
E/flutter ( 6027): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
E/flutter ( 6027): #0      MethodChannelCamera.setExposureOffset (package:camera_platform_interface/src/method_channel/method_channel_camera.dart:338:25)
```

## Versions
camera: 0.9.2+1
Flutter: 2.2.3

**Comment by TahaTesser** [comment]
Hi @AlexV525 
Thanks for filing the issue, I was gonna file an issue of this, this is easily reproducible by dragging the exposure bar.



### Preview

https://user-images.githubusercontent.com/48603081/131638767-4aa230ad-6c05-45c9-93ca-a070eb514b4c.mp4







### Logs

<details> 
<summary>logs</summary> 
	
```console
[        ] E/flutter ( 3802): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
[        ] E/flutter ( 3802): #0      MethodChannelCamera.setExposureOffset
(package:camera_platform_interface/src/method_channel/method_channel_camera.dart:338:25)
[        ] E/flutter ( 3802): <asynchronous suspension>
[        ] E/flutter ( 3802): #1      _CameraExampleHomeState.setExposureOffset (package:camera_example/main.dart:887:16)
[        ] E/flutter ( 3802): <asynchronous suspension>
[        ] E/flutter ( 3802): 
[   +3 ms] I/chatty  ( 3802): uid=10310(io.flutter.plugins.cameraexample) 1.ui identical 1 line
[        ] E/flutter ( 3802): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
[        ] E/flutter ( 3802): #0      MethodChannelCamera.setExposureOffset
(package:camera_platform_interface/src/method_channel/method_channel_camera.dart:338:25)
[        ] E/flutter ( 3802): <asynchronous suspension>
[        ] E/flutter ( 3802): #1      _CameraExampleHomeState.setExposureOffset (package:camera_example/main.dart:887:16)
[        ] E/flutter ( 3802): <asynchronous suspension>
[        ] E/flutter ( 3802): 
[ +466 ms] E/flutter ( 3802): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
[   +1 ms] E/flutter ( 3802): #0      MethodChannelCamera.setExposureOffset
(package:camera_platform_interface/src/method_channel/method_channel_camera.dart:338:25)
[        ] E/flutter ( 3802): <asynchronous suspension>
[        ] E/flutter ( 3802): #1      _CameraExampleHomeState.setExposureOffset (package:camera_example/main.dart:887:16)
[        ] E/flutter ( 3802): <asynchronous suspension>
[        ] E/flutter ( 3802): 
[  +58 ms] E/flutter ( 3802): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
[        ] E/flutter ( 3802): #0      MethodChannelCamera.setExposureOffset
(package:camera_platform_interface/src/method_channel/method_channel_camera.dart:338:25)
[        ] E/flutter ( 3802): <asynchronous suspension>
[        ] E/flutter ( 3802): #1      _CameraExampleHomeState.setExposureOffset (package:camera_example/main.dart:887:16)
[        ] E/flutter ( 3802): <asynchronous suspension>
[        ] E/flutter ( 3802): 
[  +14 ms] I/chatty  ( 3802): uid=10310(io.flutter.plugins.cameraexample) 1.ui identical 5 lines
[   +1 ms] E/flutter ( 3802): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
[        ] E/flutter ( 3802): #0      MethodChannelCamera.setExposureOffset
(package:camera_platform_interface/src/method_channel/method_channel_camera.dart:338:25)
[   +1 ms] E/flutter ( 3802): <asynchronous suspension>
[        ] E/flutter ( 3802): #1      _CameraExampleHomeState.setExposureOffset (package:camera_example/main.dart:887:16)
[        ] E/flutter ( 3802): <asynchronous suspension>
[        ] E/flutter ( 3802): 
[  +19 ms] E/flutter ( 3802): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
[   +1 ms] E/flutter ( 3802): #0      MethodChannelCamera.setExposureOffset
(package:camera_platform_interface/src/method_channel/method_channel_camera.dart:338:25)
[        ] E/flutter ( 3802): <asynchronous suspension>
[        ] E/flutter ( 3802): #1      _CameraExampleHomeState.setExposureOffset (package:camera_example/main.dart:887:16)
[        ] E/flutter ( 3802): <asynchronous suspension>
[        ] E/flutter ( 3802): 
[+8730 ms] W/Choreographer( 3802): Frame time is 0.01021 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct
timebase.
[ +375 ms] E/flutter ( 3802): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
[   +1 ms] E/flutter ( 3802): #0      MethodChannelCamera.setExposureOffset
(package:camera_platform_interface/src/method_channel/method_channel_camera.dart:338:25)
[        ] E/flutter ( 3802): <asynchronous suspension>
[        ] E/flutter ( 3802): #1      _CameraExampleHomeState.setExposureOffset (package:camera_example/main.dart:887:16)
[        ] E/flutter ( 3802): <asynchronous suspension>
[        ] E/flutter ( 3802): 
[  +45 ms] E/flutter ( 3802): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
[        ] E/flutter ( 3802): #0      MethodChannelCamera.setExposureOffset
(package:camera_platform_interface/src/method_channel/method_channel_camera.dart:338:25)
[        ] E/flutter ( 3802): <asynchronous suspension>
[        ] E/flutter ( 3802): #1      _CameraExampleHomeState.setExposureOffset (package:camera_example/main.dart:887:16)
[        ] E/flutter ( 3802): <asynchronous suspension>
[        ] E/flutter ( 3802): 
[   +2 ms] E/flutter ( 3802): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
[        ] E/flutter ( 3802): #0      MethodChannelCamera.setExposureOffset
(package:camera_platform_interface/src/method_channel/method_channel_camera.dart:338:25)
[   +1 ms] E/flutter ( 3802): <asynchronous suspension>
[        ] E/flutter ( 3802): #1      _CameraExampleHomeState.setExposureOffset (package:camera_example/main.dart:887:16)
[        ] E/flutter ( 3802): <asynchronous suspension>
[        ] E/flutter ( 3802): 
[        ] E/flutter ( 3802): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
[        ] E/flutter ( 3802): #0      MethodChannelCamera.setExposureOffset
(package:camera_platform_interface/src/method_channel/method_channel_camera.dart:338:25)
[        ] E/flutter ( 3802): <asynchronous suspension>
[        ] E/flutter ( 3802): #1      _CameraExampleHomeState.setExposureOffset (package:camera_example/main.dart:887:16)
[        ] E/flutter ( 3802): <asynchronous suspension>
[        ] E/flutter ( 3802): 
[  +18 ms] I/chatty  ( 3802): uid=10310(io.flutter.plugins.cameraexample) 1.ui identical 2 lines
[   +1 ms] E/flutter ( 3802): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
[        ] E/flutter ( 3802): #0      MethodChannelCamera.setExposureOffset
(package:camera_platform_interface/src/method_channel/method_channel_camera.dart:338:25)
[   +1 ms] E/flutter ( 3802): <asynchronous suspension>
[   +1 ms] E/flutter ( 3802): #1      _CameraExampleHomeState.setExposureOffset (package:camera_example/main.dart:887:16)
[        ] E/flutter ( 3802): <asynchronous suspension>
[        ] E/flutter ( 3802): 
[  +20 ms] E/flutter ( 3802): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
[        ] E/flutter ( 3802): #0      MethodChannelCamera.setExposureOffset
(package:camera_platform_interface/src/method_channel/method_channel_camera.dart:338:25)
[        ] E/flutter ( 3802): <asynchronous suspension>
[        ] E/flutter ( 3802): #1      _CameraExampleHomeState.setExposureOffset (package:camera_example/main.dart:887:16)
[        ] E/flutter ( 3802): <asynchronous suspension>
[        ] E/flutter ( 3802): 
[   +6 ms] I/chatty  ( 3802): uid=10310(io.flutter.plugins.cameraexample) 1.ui identical 3 lines
[        ] E/flutter ( 3802): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
[        ] E/flutter ( 3802): #0      MethodChannelCamera.setExposureOffset
(package:camera_platform_interface/src/method_channel/method_channel_camera.dart:338:25)
[        ] E/flutter ( 3802): <asynchronous suspension>
[        ] E/flutter ( 3802): #1      _CameraExampleHomeState.setExposureOffset (package:camera_example/main.dart:887:16)
[        ] E/flutter ( 3802): <asynchronous suspension>
[        ] E/flutter ( 3802): 
[  +30 ms] E/flutter ( 3802): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
[        ] E/flutter ( 3802): #0      MethodChannelCamera.setExposureOffset
(package:camera_platform_interface/src/method_channel/method_channel_camera.dart:338:25)
[        ] E/flutter ( 3802): <asynchronous suspension>
[        ] E/flutter ( 3802): #1      _CameraExampleHomeState.setExposureOffset (package:camera_example/main.dart:887:16)
[        ] E/flutter ( 3802): <asynchronous suspension>
[        ] E/flutter ( 3802): 
[   +6 ms] E/flutter ( 3802): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
[        ] E/flutter ( 3802): #0      MethodChannelCamera.setExposureOffset
(package:camera_platform_interface/src/method_channel/method_channel_camera.dart:338:25)
[        ] E/flutter ( 3802): <asynchronous suspension>
[        ] E/flutter ( 3802): #1      _CameraExampleHomeState.setExposureOffset (package:camera_example/main.dart:887:16)
[        ] E/flutter ( 3802): <asynchronous suspension>
```
	
</details>

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale en_US.UTF-8)
    • Flutter version 2.2.3 at /home/taha/Code/flutter_stable
    • Framework revision f4abaa0735 (9 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/taha/Code/android-sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = /home/taha/Code/android-sdk
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 12.0.0-3ubuntu1~21.04.1
    • cmake version 3.18.4
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 59.0.2
    • Dart plugin version 203.8292
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.59.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • def0ad20 • android-arm64  • Android 11 (API 30)
    • Linux (desktop)        • linux    • linux-x64      • Linux
    • Chrome (web)           • chrome   • web-javascript • Google Chrome 93.0.4577.63

• No issues found!
```

</details>


Thanks for filing the issue
