### ISSUE TITLE
UI exception

### ISSUE THREAD

**Issue by ni3vspace** [flutter/flutter#89289]
<details> 
<summary>code snippet</summary> 

```dart
GridView.builder( itemBuilder: (_, index) => Row(children: <Widget>[
          Container(child: GestureDetector(child:Row(
              children: [
                Expanded(child:Column(
                  children: <Widget>[
                    Container(
                      child: Image.network(
                        Constants.ImagePath +data[index].ImageId,
                        width: 70,
                        height: 60,
                        fit: BoxFit.scaleDown,
                        errorBuilder: (BuildContext context, Object exception, StackTrace stackTrace) {
                          return Image.asset('images/placeholder.jpg',width: 70,
                            height: 60,);
                        },
                      ),
                    ),
                    Padding(
                        padding: const EdgeInsets.fromLTRB(
                            0.0, 5.0, 0.0, 0.0)),
                    Expanded(
                      child: Text(
                        data[index].label!=null?data[index].name:"",
                        textAlign: TextAlign.center,
                        maxLines: 2,
                        style: TextStyle(fontSize: 14.0),
                        overflow: TextOverflow.ellipsis,
                      ),
                    )
                  ],
                )
```

</details>

<details> 
<summary>logs</summary> 
	
```console
The following assertion was thrown during performLayout():
RenderBox was not laid out: RenderFlex#02eb8 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  GridView file:///F:/Project/Neighbore_Office/New%20Customer%20Standalone/lib/ui/Widgets/ProductsHorizantalMenu.dart:23:21
When the exception was thrown, this was the stack: 
#2      RenderBox.size (package:flutter/src/rendering/box.dart:1940:12)
#3      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:119:21)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#5      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
#6      RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
...
The following RenderObject was being processed when the exception was fired: RenderRepaintBoundary#2f4d2 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  needs compositing
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=88.0, h=80.0)
...  size: MISSING
...  usefulness ratio: no metrics collected yet (never painted)
RenderObject: RenderRepaintBoundary#2f4d2 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  needs compositing
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=88.0, h=80.0)
  size: MISSING
  usefulness ratio: no metrics collected yet (never painted)
...  child: RenderFlex#02eb8 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: <none> (can use size)
...    constraints: BoxConstraints(w=88.0, h=80.0)
...    size: MISSING
...    direction: horizontal
...    mainAxisAlignment: start
...    mainAxisSize: max
...    crossAxisAlignment: center
...    textDirection: ltr
...    verticalDirection: down
...    child 1: RenderSemanticsGestureHandler#2dc78 relayoutBoundary=up1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
...      constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=80.0)
...      size: MISSING
...      gestures: tap
...      child: RenderPointerListener#ae6c4 relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=80.0)
...        size: MISSING
...        behavior: opaque
...        listeners: down
...        child: RenderFlex#572b2 relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=80.0)
...          size: MISSING
...          direction: horizontal
...          mainAxisAlignment: start
...          mainAxisSize: max
...          crossAxisAlignment: center
...          textDirection: ltr
...          verticalDirection: down
```
	
</details>

**Comment by TahaTesser** [comment]
Hi @ni3vspace 
Your code snippet is incomplete and has missing code 

Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
