### ISSUE TITLE
[tool_crash] ProcessException: Failed to find ".\Microsoft\Edge\Application\msedge.exe" in the search path. Command: .\Microsoft\Edge\Application\msedge.exe, OS error code: 0

### ISSUE THREAD

**Issue by ghost** [flutter/flutter#89358]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Failed to find ".\Microsoft\Edge\Application\msedge.exe" in the search path. Command: .\Microsoft\Edge\Application\msedge.exe, OS error code: 0
```
#0      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:58:7)
#1      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:664:24)
#2      _run (package:flutter_tools/src/base/error_handling_io.dart:544:20)
#3      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:663:12)
#4      ChromiumLauncher._spawnChromiumProcess (package:flutter_tools/src/web/chrome.dart:243:53)
#5      ChromiumLauncher.launch (package:flutter_tools/src/web/chrome.dart:221:36)
<asynchronous suspension>
#6      ChromiumDevice.startApp (package:flutter_tools/src/web/web_device.dart:136:17)
<asynchronous suspension>
#7      ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:541:9)
<asynchronous suspension>
#8      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.18362.1256], locale fr-FR)
    • Flutter version 2.2.3 at C:\src\flutter
    • Framework revision f4abaa0735 (9 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.59.1)
    • VS Code at C:\Users\ART Sider\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.72
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 90.0.818.42 (unsupported)

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f4abaa0735eba4dfd8f33f73363911d63931fe03

**Comment by darshankawar** [comment]
I don't see any related / similar or duplicate issue, so labeling accordingly.

**Comment by christopherfujino** [comment]
Similar stacktrace from stable/2.5.1:

```
Thread 0 main threadProcessPackageException: ProcessException: Failed to find "/Users/Fujino/Desktop/<path>/<app_name>/android/gradlew" in the search path.  Command: "/Users/Fujino/Desktop/<path>/<app_name>/android/gradlew 
at LocalProcessManager.start(local_process_manager.dart:58)
at ErrorHandlingProcessManager.start.<anonymous closure>(error_handling_io.dart:691)
at _run(error_handling_io.dart:567)
at ErrorHandlingProcessManager.start(error_handling_io.dart:690)
at _DefaultProcessUtils.start(process.dart:425)
at _DefaultProcessUtils.stream(process.dart:444)
at AndroidGradleBuilder.buildGradleApp(gradle.dart:357)
at AndroidGradleBuilder.buildApk(gradle.dart:178)
at BuildApkCommand.runCommand(build_apk.dart:105)
at <asynchronous gap>(async)
at FlutterCommand.run.<anonymous closure>(flutter_command.dart:1125)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:150)
at <asynchronous gap>(async)
at CommandRunner.runCommand(command_runner.dart:209)
at <asynchronous gap>(async)
at FlutterCommandRunner.runCommand.<anonymous closure>(flutter_command_runner.dart:288)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:150)
at <asynchronous gap>(async)
at FlutterCommandRunner.runCommand(flutter_command_runner.dart:236)
at <asynchronous gap>(async)
at run.<anonymous closure>.<anonymous closure>(runner.dart:62)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:150)
at <asynchronous gap>(async)
at main(executable.dart:92)
at <asynchronous gap>(async)
```
