### ISSUE TITLE
I've got problem with navigator.pop(context), I can't even use device back button cause the same error will pop out

### ISSUE THREAD

**Issue by hairo-vian** [flutter/flutter#89419]
The error thrown is 

```console
======== Exception caught by gesture ===============================================================
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 5067 pos 12: '!_debugLocked': is not true.`
```

Here is my code

<details>
<summary>code sample</summary>

main.dart

```dart
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Hive.initFlutter();
  Hive.registerAdapter(CartAdapter());
  await Hive.openBox<Cart>(Cart.tableName);

  setupDependencyInjection();
  runApp(ProviderScope(child: MyApp()));
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: SplashScreen(
          AssetsContract.flareSiteAnimation,
          FutureBuilder(
              future: InitApp().initAppReady(),
              builder: (context, snapshot) {
                if (snapshot.connectionState == ConnectionState.done &&
                    snapshot.hasData &&
                    snapshot.data) {
                  return getItSharedPreferences.isLogin()
                      ? MenuScreen()
                      : LoginScreen();
                }
                return LoginScreen();
              }),
          startAnimation: AssetsContract.flareSiteAnimation_startup,
          backgroundColor: Colors.white,
        ),
      ),
      onGenerateRoute: RouteGenerator.generateRoute,
    );
  }
}
```

route_generator.dart

```dart
class RouteGenerator {
  static Route<dynamic> generateRoute(RouteSettings settings) {
    final args = settings.arguments;
    switch (settings.name) {
      case RouteContract.login:
        return MaterialPageRoute(
          settings: settings,
          builder: (context) => LoginScreen(),
        );
        break;
      case RouteContract.error:
        ErrorArguments arguments = args;
        return MaterialPageRoute(
          settings: settings,
          builder: (context) => ErrorScreen(
            error: arguments.error,
            from: arguments.from,
          ),
        );
        break;
      case RouteContract.menu:
        return MaterialPageRoute(
          settings: settings,
          builder: (context) => MenuScreen(),
        );
        break;
      case RouteContract.cart:
        return MaterialPageRoute(
            builder: (context) => CartScreen(), settings: settings);
        break;
      default:
        return MaterialPageRoute(builder: (context) => ErrorScreen());
        break;
    }
  }
}
```

error_view.dart

```dart
class ErrorArguments {
  final ErrorModel error;
  final String from;

  ErrorArguments(this.error, this.from);
}

class ErrorScreen extends StatefulWidget {
  final ErrorModel error;
  final String from;

  const ErrorScreen({
    Key key,
    this.error,
    this.from,
  }) : super(key: key);

  @override
  _ErrorScreenState createState() => _ErrorScreenState();
}

class _ErrorScreenState extends State<ErrorScreen> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Container(
          width: MediaQuery.of(context).size.width,
          height: MediaQuery.of(context).size.height,
          child: Padding(
            padding: const EdgeInsets.all(12.0),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              crossAxisAlignment: CrossAxisAlignment.center,
              children: [
                Image(
                  image: AssetImage(AssetsContract.errorIcon),
                ),
                Text(
                  widget.error.code,
                  style: GoogleFonts.kronaOne(
                    fontSize: 20,
                    color: Colors.black,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                SizedBox(
                  height: 20,
                ),
                Text(
                  widget.error.message,
                  style: GoogleFonts.roboto(
                    fontSize: 15,
                    color: Colors.black,
                  ),
                  textAlign: TextAlign.center,
                ),
              ],
            ),
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        splashColor: Colors.amber,
        backgroundColor: Colors.red,
        elevation: 0,
        onPressed: () {
          Navigator.popAndPushNamed(context,widget.from);
        },
        child: Icon(
          Icons.cancel_outlined,
          color: Colors.white,
        ),
      ),
    );
  }
}
```
it keep showing the same error whenever I call the Navigator.pop(context);
*I've tried many solutions I found in many forums like : 

```dart
Future.delayed(Duration.zero, () {
  Navigator.pop(context);
});
```

```dart
SchedulerBinding.instance.addPostFrameCallback((_) {
  Navigator.pop(context);
});
```

```dart
WidgetsBinding.instance.addPostFrameCallback((_) {
  Navigator.pop(context);
});
```
</details>

but it keep showing the same issues, don't what I need to do anymore.

btw, here is my flutter doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19041.1165], locale en-ID)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[!] Android Studio (not installed)
[√] VS Code (version 1.59.1)
[√] Connected device (3 available)
```

**Comment by hairo-vian** [comment]
I've had no problem when pushNamed / pushReplacementNamed but pop is really can't be used

**Comment by maheshmnj** [comment]
Hi, @hairo-vian can you narrow down the code further without any third party-plugins?

**Comment by hairo-vian** [comment]
might be able for flaresplashscreen & hive. 
But I do need the riverpod to stay though, because I used it in all of my view

**Comment by maheshmnj** [comment]
Please make sure the code is ready to run with minimal or no code changes with the issue being reproducible.

**Comment by hairo-vian** [comment]
```
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  setupDependencyInjection();
  runApp(ProviderScope(child: MyApp()));
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: ErrorScreen();
      ),
      onGenerateRoute: RouteGenerator.generateRoute,
    );
  }
}

```
```

class ErrorScreen extends StatefulWidget {
  final ErrorModel error;
  final String from;

  const ErrorScreen({
    Key key,
    this.error,
    this.from,
  }) : super(key: key);

  @override
  _ErrorScreenState createState() => _ErrorScreenState();
}

class _ErrorScreenState extends State<ErrorScreen> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Container(
          width: MediaQuery.of(context).size.width,
          height: MediaQuery.of(context).size.height,
          child: Padding(
            padding: const EdgeInsets.all(12.0),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              crossAxisAlignment: CrossAxisAlignment.center,
              children: [
                Text(
                  "Some code",
                ),
                SizedBox(
                  height: 20,
                ),
                Text(
                  "some message",
                  textAlign: TextAlign.center,
                ),
              ],
            ),
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        splashColor: Colors.amber,
        backgroundColor: Colors.red,
        elevation: 0,
        onPressed: () {
          Navigator.pop(context);
        },
        child: Icon(
          Icons.cancel_outlined,
          color: Colors.white,
        ),
      ),
    );
  }
}



```

**Comment by hairo-vian** [comment]
this should do the work, only use flutter riverpod

`flutter_riverpod: ^0.12.1`

**Comment by maheshmnj** [comment]
@hairo-vian  `flutter_riverpod: ^0.12.1` fails to run on the latest stable 2.2.3 I tried setting dart sdk to `sdk: ">=2.10.0 <3.0.0"` as per the [minimum constraints of 2.8](https://pub.dev/packages/flutter_riverpod/versions) but it still fails to run.
However, when I upgrade to the latest version `flutter_riverpod: ^0.14.0+3` it works fine and I could pop the widget without any errors.


<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

import 'package:flutter_riverpod/flutter_riverpod.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(ProviderScope(child: MyApp()));
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Flutter Demo',
        debugShowCheckedModeBanner: false,
        theme: ThemeData(
          primarySwatch: Colors.blue,
        ),
        home: ErrorScreen());
  }
}

class ErrorScreen extends StatefulWidget {
  @override
  _ErrorScreenState createState() => _ErrorScreenState();
}

class _ErrorScreenState extends State<ErrorScreen> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Container(
          width: MediaQuery.of(context).size.width,
          height: MediaQuery.of(context).size.height,
          child: Padding(
            padding: const EdgeInsets.all(12.0),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              crossAxisAlignment: CrossAxisAlignment.center,
              children: [
                Text(
                  "Some code",
                ),
                SizedBox(
                  height: 20,
                ),
                Text(
                  "some message",
                  textAlign: TextAlign.center,
                ),
              ],
            ),
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        splashColor: Colors.amber,
        backgroundColor: Colors.red,
        elevation: 0,
        onPressed: () {
          Navigator.pop(context);
        },
        child: Icon(
          Icons.cancel_outlined,
          color: Colors.white,
        ),
      ),
    );
  }
}


```
</details>


<details>
<summary>build logs</summary>

```console
Launching lib/main.dart on iPhone 12 Pro in debug mode...
Xcode build done.                                           12.4s
Failed to build iOS app
Error output from Xcode build:
↳
    objc[7340]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x1ff92fad8) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x115c702b8). One of the two will be used. Which one is undefined.
    objc[7340]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x1ff92fb28) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x115c70308). One of the two will be used. Which one is undefined.
    ** BUILD FAILED **
Xcode's output:
↳
    ../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/riverpod-0.12.4/lib/src/common.freezed.dart:121:4: Error: Getter not found: 'nullable'.
      @nullable
       ^^^^^^^^
    ../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/riverpod-0.12.4/lib/src/common.freezed.dart:121:4: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
      @nullable
       ^
    ../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/riverpod-0.12.4/lib/src/common.freezed.dart:206:4: Error: Getter not found: 'nullable'.
      @nullable
       ^^^^^^^^
    ../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/riverpod-0.12.4/lib/src/common.freezed.dart:206:4: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
      @nullable
       ^
    ../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/riverpod-0.12.4/lib/src/common.dart:66:34: Error: Getter not found: 'nullable'.
      const factory AsyncValue.data(@nullable T value) = AsyncData<T>;
                                     ^^^^^^^^
    ../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/riverpod-0.12.4/lib/src/common.dart:66:34: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
      const factory AsyncValue.data(@nullable T value) = AsyncData<T>;
                                     ^
    ../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/riverpod-0.12.4/lib/src/common.freezed.dart:17:25: Error: Getter not found: 'nullable'.
      AsyncData<T> data<T>(@nullable T value) {
                            ^^^^^^^^
    ../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/riverpod-0.12.4/lib/src/common.freezed.dart:17:25: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
      AsyncData<T> data<T>(@nullable T value) {
                            ^
    ../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/riverpod-0.12.4/lib/src/common.freezed.dart:45:28: Error: Getter not found: 'nullable'.
        @required Result data(@nullable T value),
                               ^^^^^^^^
    ../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/riverpod-0.12.4/lib/src/common.freezed.dart:45:28: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
        @required Result data(@nullable T value),
                               ^
    ../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/riverpod-0.12.4/lib/src/common.freezed.dart:51:18: Error: Getter not found: 'nullable'.
        Result data(@nullable T value),
                     ^^^^^^^^
    ../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/riverpod-0.12.4/lib/src/common.freezed.dart:51:18: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
        Result data(@nullable T value),
                     ^
    ../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/riverpod-0.12.4/lib/src/common.freezed.dart:93:15: Error: Getter not found: 'nullable'.
      $Res call({@nullable T value});
                  ^^^^^^^^
    ../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/riverpod-0.12.4/lib/src/common.freezed.dart:93:15: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
      $Res call({@nullable T value});
                  ^
    ../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/riverpod-0.12.4/lib/src/common.freezed.dart:118:22: Error: Getter not found: 'nullable'.
      const _$AsyncData(@nullable this.value) : super._();
                         ^^^^^^^^
    ../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/riverpod-0.12.4/lib/src/common.freezed.dart:118:22: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
      const _$AsyncData(@nullable this.value) : super._();
                         ^
    ../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/riverpod-0.12.4/lib/src/common.freezed.dart:148:28: Error: Getter not found: 'nullable'.
        @required Result data(@nullable T value),
                               ^^^^^^^^
    ../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/riverpod-0.12.4/lib/src/common.freezed.dart:148:28: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
        @required Result data(@nullable T value),
                               ^
    ../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/riverpod-0.12.4/lib/src/common.freezed.dart:161:18: Error: Getter not found: 'nullable'.
        Result data(@nullable T value),
                     ^^^^^^^^
    ../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/riverpod-0.12.4/lib/src/common.freezed.dart:161:18: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
        Result data(@nullable T value),
                     ^
    ../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/riverpod-0.12.4/lib/src/common.freezed.dart:204:28: Error: Getter not found: 'nullable'.
      const factory AsyncData(@nullable T value) = _$AsyncData<T>;
                               ^^^^^^^^
    ../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/riverpod-0.12.4/lib/src/common.freezed.dart:204:28: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
      const factory AsyncData(@nullable T value) = _$AsyncData<T>;
                               ^
    ../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/riverpod-0.12.4/lib/src/common.freezed.dart:250:28: Error: Getter not found: 'nullable'.
        @required Result data(@nullable T value),
                               ^^^^^^^^
    ../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/riverpod-0.12.4/lib/src/common.freezed.dart:250:28: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
        @required Result data(@nullable T value),
                               ^
    ../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/riverpod-0.12.4/lib/src/common.freezed.dart:263:18: Error: Getter not found: 'nullable'.
        Result data(@nullable T value),
                     ^^^^^^^^
    ../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/riverpod-0.12.4/lib/src/common.freezed.dart:263:18: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
        Result data(@nullable T value),
                     ^
    ../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/riverpod-0.12.4/lib/src/common.freezed.dart:380:28: Error: Getter not found: 'nullable'.
        @required Result data(@nullable T value),
                               ^^^^^^^^
    ../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/riverpod-0.12.4/lib/src/common.freezed.dart:380:28: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
        @required Result data(@nullable T value),
                               ^
    ../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/riverpod-0.12.4/lib/src/common.freezed.dart:393:18: Error: Getter not found: 'nullable'.
        Result data(@nullable T value),
                     ^^^^^^^^
    ../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/riverpod-0.12.4/lib/src/common.freezed.dart:393:18: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
        Result data(@nullable T value),
                     ^
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Analyzing workspace
    note: Constructing build description
    note: Build preparation complete
    /Users/mahesh/Desktop/mysample/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.5.99. (in target 'Flutter' from project 'Pods')
Could not build the application for the simulator.
Error launching application on iPhone 12 Pro.
Exited (sigterm)

```
</details>

**Comment by hairo-vian** [comment]
hmmm..... 
can I just drop the whole project?
I've been working on this project for a long time & still not found the way to fix it. 
There are no secrets in there because it's only for my self training.

**Comment by maheshmnj** [comment]
Sure, But it would be great if you could narrow down the project to limited code by removing the unwanted part and keeping only the reproducible code this will help to track down the issue.

Thanks.

**Comment by hairo-vian** [comment]
I just track it down by now, I've tried normal way of navigator push & pop which used onPressed & they can work normally.
The error only occur if I call Navigator.Push after API call, therefore the Navigator.pop will result error as I said before.

**Comment by maheshmnj** [comment]
@hairo-vian as [mentioned before](https://github.com/flutter/flutter/issues/89419#issuecomment-913367636) with
`flutter_riverpod: ^0.14.0+31` your code sample works fine(no console errors.)

https://user-images.githubusercontent.com/31410839/133966029-edc41f0f-9079-41ef-bdb0-2eeff86e1cc9.mov

**Comment by hairo-vian** [comment]
yes, I know it. The problem wasn't because the riverpod. 
You can try to run this repository instead 
[https://github.com/hairo-vian/new_hairo_cashier.git](url)

**Comment by maheshmnj** [comment]
> You can try to run this repository instead
https://github.com/hairo-vian/new_hairo_cashier.git

@hairo-vian please make sure the repo is publicly accessible and also describe the steps to reproduce the issue.

**Comment by hairo-vian** [comment]
[https://github.com/hairo-vian/new_hairo_cashier](url)
this repo is publicly accessible. 

The steps : 
1. run pub get 
2. run the programs
3. enter any username / password (anythins is fine, it'll result error anyway)
4. You'll navigate to the error screen.
5. Click the FAB button on right bottom
6. The error reproduced

**Comment by maheshmnj** [comment]
@hairo-vian 

![image](https://user-images.githubusercontent.com/31410839/133967315-5ccc7688-1172-4800-9e33-5c0e0195de52.png)

**Comment by hairo-vian** [comment]
My Bad, Try again will you?

**Comment by maheshmnj** [comment]
@hairo-vian when running your application I get a bunch of errors before the application loads, I see that you are updating the state of the application while the build is in progress a quick fix for it is change.

_login_view.dart_ on line 34 

```
 viewModel.observeStateEvent(context);
```
to 

```
    WidgetsBinding.instance!.addPostFrameCallback((timeStamp) {
      viewModel.observeStateEvent(context);
    });
```   

<details>
<summary>logs</summary>

```
Launching lib/main.dart on iPhone 12 Pro in debug mode...
Xcode build done.                                           30.8s
Connecting to VM Service at ws://127.0.0.1:60111/ORiH_uR0zyk=/ws
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: setState() or markNeedsBuild() called during build.
This UncontrolledProviderScope widget cannot be marked as needing to build because the framework is already in the process of building widgets.  A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was:
  UncontrolledProviderScope
The widget which was currently being built when the offending call was made was:
  LoginScreen
#0      Element.markNeedsBuild.<anonymous closure>
#1      Element.markNeedsBuild
#2      ProviderElement._debugMarkWillChange.<a<…>
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: At least listener of the StateNotifier Instance of 'LoginViewModel' threw an exception
when the notifier tried to update its state.
The exceptions thrown are:
setState() or markNeedsBuild() called during build.
This UncontrolledProviderScope widget cannot be marked as needing to build because the framework is already in the process of building widgets.  A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was:
  UncontrolledProviderScope
The widget which was currently being built when the offending call was made was:
  LoginScreen
#0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/w<…>
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: setState() or markNeedsBuild() called during build.
This Overlay widget cannot be marked as needing to build because the framework is already in the process of building widgets.  A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was:
  Overlay-[LabeledGlobalKey<OverlayState>#2b4b6]
The widget which was currently being built when the offending call was made was:
  LoginScreen
#0      Element.markNeedsBuild.<anonymous closure>
#1      Element.markNeedsBuild
#2      State.setState (package:flutter/src/<…>
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 3029 pos 18: '!navigator._debugLocked': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      _RouteEntry.handlePush.<anonymous closure>
#3      TickerFuture.whenCompleteOrCancel.thunk
#4      _rootRunUnary (dart:async/zone.dart:1436:47)
#5      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
<asynchronous suspension>
#6      TickerFuture.whenCompleteOrCancel.thunk (package:flutter/src/scheduler/ticker.dart)
<asynchronous suspension>

════════ Exception caught by gesture ═══════════════════════════════════════════
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 5098 pos 12: '!_debugLocked': is not true.

When the exception was thrown, this was the stack
#2      NavigatorState.pop
#3      _ErrorScreenState.build.<anonymous closure>
#4      _InkResponseState._handleTap
#5      GestureRecognizer.invokeCallback
#6      TapGestureRecognizer.handleTapUp
#7      BaseTapGestureRecognizer._checkUp
#8      BaseTapGestureRecognizer.handlePrimaryPointer
#9      PrimaryPointerGestureRecognizer.handleEvent
#10     PointerRouter._dispatch
#11     PointerRouter._dispatchEventToRoutes.<anonymous closure>
#12     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:400:8)
#13     PointerRouter._dispatchEventToRoutes
#14     PointerRouter.route
#15     GestureBinding.handleEvent
#16     GestureBinding.dispatchEvent
#17     RendererBinding.dispatchEvent
#18     GestureBinding._handlePointerEventImmediately
#19     GestureBinding.handlePointerEvent
#20     GestureBinding._flushPointerEventQueue
#21     GestureBinding._handlePointerDataPacket
#25     _invoke1 (dart:ui/hooks.dart:185:10)
#26     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
#27     _dispatchPointerDataPacket (dart:ui/hooks.dart:98:31)
(elided 5 frames from class _AssertionError and dart:async)
Handler: "onTap"
Recognizer: TapGestureRecognizer#984f6
    debugOwner: GestureDetector
    state: possible
    won arena
    finalPosition: Offset(346.3, 774.7)
    finalLocalPosition: Offset(28.3, 36.7)
    button: 1
    sent tap down
════════════════════════════════════════════════════════════════════════════════

```
</details>

**Comment by maheshmnj** [comment]
Closing as working as expected if you disagree feel free to write in the comments and  I will reopen it.

Thank you.

**Comment by hairo-vian** [comment]
Yes, it worked what it supposed to.
Thanks you really help me
