### ISSUE TITLE
[Camera] java.lang.IllegalStateException: CameraDevice was already closed

### ISSUE THREAD

**Issue by MATTYGILO** [flutter/flutter#89479]
## Steps to Reproduce

I am using flutter camera plugin on Android.

I run `await controller.initialize()` and the app crashes with this bug

**Expected results:** 

I don't expect it to crash

**Actual results:** 

It crashes

<details>
  <summary>E/AndroidRuntime( 5737): FATAL EXCEPTION: CameraBackground
E/AndroidRuntime( 5737): Process: com.my.app, PID: 5737
E/AndroidRuntime( 5737): java.lang.IllegalStateException: CameraDevice was already closed
E/AndroidRuntime( 5737): 	at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:2445)
E/AndroidRuntime( 5737): 	at android.hardware.camera2.impl.CameraDeviceImpl.createCaptureSessionInternal(CameraDeviceImpl.java:653)
E/AndroidRuntime( 5737): 	at android.hardware.camera2.impl.CameraDeviceImpl.createCaptureSession(CameraDeviceImpl.java:639)
E/AndroidRuntime( 5737): 	at io.flutter.plugins.camera.Camera.createCaptureSessionWithSessionConfig(Camera.java:399)
E/AndroidRuntime( 5737): 	at io.flutter.plugins.camera.Camera.createCaptureSession(Camera.java:385)
E/AndroidRuntime( 5737): 	at io.flutter.plugins.camera.Camera.createCaptureSession(Camera.java:317)
E/AndroidRuntime( 5737): 	at io.flutter.plugins.camera.Camera.startPreview(Camera.java:969)
E/AndroidRuntime( 5737): 	at io.flutter.plugins.camera.Camera$1.onOpened(Camera.java:254)
E/AndroidRuntime( 5737): 	at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java:149)
E/AndroidRuntime( 5737): 	at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime( 5737): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 5737): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime( 5737): 	at android.os.HandlerThread.run(HandlerThread.java:65)
</summary>

```
```

```
```

```
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.3.1 20E241 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.6 at
      /path/
    • Framework revision 1d9032c7e1 (4 months ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /path/
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /path/
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Connected device (2 available)
    • ONEPLUS A3003 (mobile) • 300ef9a8 • android-arm64  • Android 9 (API 28)
    • Chrome (web)           • chrome   • web-javascript • Google Chrome
      92.0.4515.159

! Doctor found issues in 1 category.
```

</details>

**Comment by TahaTesser** [comment]
Hi @MATTYGILO 
I just tried `camera: ^0.9.2+2` using the [official sample](https://pub.dev/packages/camera/example), no such error in the logs 

Can you please try `flutter pub upgrade` then run the app on the latest `camera: ^0.9.2+2` .


If the problem persists, can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by nt4f04uNd** [comment]
Seems like a duplicate of https://github.com/flutter/flutter/issues/89431
