### ISSUE TITLE
No MaterialLocalizations found

### ISSUE THREAD

**Issue by githubusar** [flutter/flutter#89540]
I am creating an app that shows a popup message when it reaches the end of the list, but no popup message is showing i am using rflutter package to show the popup message. the link of rflutter package: https://pub.dev/packages/rflutter_alert,
and when i click run on android studio it shows No MaterialLocalizations found

the code:

<details>
<summary>code sample</summary>

```dart
import 'package:demo/quiz_brain.dart';
import 'package:flutter/material.dart';
import 'package:rflutter_alert/rflutter_alert.dart';

void main() {
  runApp(QuizApp());
}

class QuizApp extends StatefulWidget {
  const QuizApp({Key? key}) : super(key: key);

  @override
  _QuizAppState createState() => _QuizAppState();
}

List scorekeeper = [];

class _QuizAppState extends State {
  QuizBrain quizObject = QuizBrain();

  void checkAnswer(bool userPickedAnswer) {
    bool correctanswer = quizObject.getquestionAnswer();
    setState(() {
      if (quizObject.isfinished() == true) {
        Alert(
          context: context,
          title: 'Warning',
          desc: 'You have reached the end of the questions',
        ).show();

        quizObject.reset();
        scorekeeper = [];
      } else {
        if (correctanswer == userPickedAnswer) {
          scorekeeper.add(Icon(
            Icons.check,
            color: Colors.green,
          ));
        } else {
          scorekeeper.add(Icon(
            Icons.close,
            color: Colors.red,
          ));
        }
        quizObject.nextQuestion();
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        backgroundColor: Colors.black,
        body: SafeArea(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Expanded(
                flex: 5,
                child: Center(
                  child: Text(
                    quizObject.getquestiontext(),
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      fontSize: 30,
                      color: Colors.white,
                    ),
                  ),
                ),
              ),
              Expanded(
                child: Padding(
                  padding: const EdgeInsets.all(15.0),
                  child: TextButton(
                    onPressed: () {
                      checkAnswer(true);
                    },
                    style: TextButton.styleFrom(
                      backgroundColor: Colors.green,
                    ),
                    child: Center(
                      child: Text(
                        'True',
                        style: TextStyle(
                          fontSize: 20,
                          color: Colors.white,
                        ),
                      ),
                    ),
                  ),
                ),
              ),
              Expanded(
                child: Padding(
                  padding: const EdgeInsets.all(15.0),
                  child: TextButton(
                    onPressed: () {
                      checkAnswer(false);
                    },
                    style: TextButton.styleFrom(
                      backgroundColor: Colors.red,
                    ),
                    child: Center(
                      child: Text(
                        'False',
                        style: TextStyle(
                          fontSize: 20,
                          color: Colors.white,
                        ),
                      ),
                    ),
                  ),
                ),
              ),
              Row(
                children: scorekeeper,
              ),
            ],
          ),
        ),
      ),
    );
  }
}

```
</details>

when i click run on android studio i get this message:

```
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: No MaterialLocalizations found.
QuizApp widgets require MaterialLocalizations to be provided by a Localizations widget ancestor.
The material library uses Localizations to generate messages, labels, and abbreviations.
To introduce a MaterialLocalizations, either use a MaterialApp at the root of your application to include them automatically, or add a Localization widget with a MaterialLocalizations delegate.
The specific widget that could not find a MaterialLocalizations ancestor was:
  QuizApp
The ancestors of this widget were:
  [root]
#0      debugCheckHasMaterialLocalizations.<anonymous closure> (package:flutter/src/material/debug.dart:69:7)
#1      debugCheckHasMaterialLocalizations (package:flutter/src/material/debug.dart:89:4)
#2      MaterialLocalizations.of (package:flutter/src/material/material_localizations.dart:515:12)
#3      Alert.show (package:rflutter_alert/src/alert.dart:76:35)
#4      _QuizAppState.checkAnswer.<anonymous closure<…>
```

this flutter doctor-v:
<details>
<summary>flutter doctor -v</summary>

```
/Users/mac/Developer/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.1 20G80 darwin-x64, locale en-GB)
    • Flutter version 2.2.3 at /Users/mac/Developer/flutter
    • Framework revision f4abaa0735 (10 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mac/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Community Edition (version 2021.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 59.0.4
    • Dart plugin version 212.4746.57

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • 5B4B455E-E89F-4A52-9F41-74C9CB2DAD56 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 11.5.1 20G80 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 92.0.4515.159

• No issues found!
```
</details>

**Comment by maheshmnj** [comment]
Hi @githubusar, when filing issues please try to fill some or all of the information requested in the issue template. The issue description doesn't seem to make any sense to me. 
Please update the issue description describing the steps to reproduce the issue along with the output of `flutter doctor -v` and a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) (if applicable).

**Comment by githubusar** [comment]
> Hi @githubusar, when filing issues please try to fill some or all of the information requested in the issue template. The issue description doesn't seem to make any sense to me.
> Please update the issue description describing the steps to reproduce the issue along with the output of `flutter doctor -v` and a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) (if applicable).

hi i have updated my issue description

**Comment by maheshmnj** [comment]
@githubusar I saw your code sample and I see that you are directly using the flutter widgets  inside the MaterialApp

```dart
home: Scaffold(...)
```
 so the context that gets passed down the widget tree does not have [ MaterialLocalizations](https://api.flutter.dev/flutter/material/MaterialLocalizations-class.html), so there are two ways you can deal with this either instantiate another flutter Widget and pass it to home. 

<details>
<summary>modified code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(QuizApp());
}

class QuizApp extends StatefulWidget {
  const QuizApp({Key? key}) : super(key: key);

  @override
  _QuizAppState createState() => _QuizAppState();
}

List scorekeeper = [];

class _QuizAppState extends State {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(debugShowCheckedModeBanner: false, home: QuizHome());
  }
}

class QuizHome extends StatefulWidget {
  const QuizHome({Key? key}) : super(key: key);

  @override
  _QuizHomeState createState() => _QuizHomeState();
}

class _QuizHomeState extends State<QuizHome> {
  QuizBrain quizObject = QuizBrain();

  void checkAnswer(bool userPickedAnswer) {
    bool correctanswer = quizObject.getquestionAnswer();
    setState(() {
      if (quizObject.isfinished() == true) {
        Alert(
          context: context,
          title: 'Warning',
          desc: 'You have reached the end of the questions',
        ).show();

        quizObject.reset();
        scorekeeper = [];
      } else {
        if (correctanswer == userPickedAnswer) {
          scorekeeper.add(Icon(
            Icons.check,
            color: Colors.green,
          ));
        } else {
          scorekeeper.add(Icon(
            Icons.close,
            color: Colors.red,
          ));
        }
        quizObject.nextQuestion();
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.black,
      body: SafeArea(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Expanded(
              flex: 5,
              child: Center(
                child: Text(
                  quizObject.getquestiontext(),
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    fontSize: 30,
                    color: Colors.white,
                  ),
                ),
              ),
            ),
            Expanded(
              child: Padding(
                padding: const EdgeInsets.all(15.0),
                child: TextButton(
                  onPressed: () {
                    checkAnswer(true);
                  },
                  style: TextButton.styleFrom(
                    backgroundColor: Colors.green,
                  ),
                  child: Center(
                    child: Text(
                      'True',
                      style: TextStyle(
                        fontSize: 20,
                        color: Colors.white,
                      ),
                    ),
                  ),
                ),
              ),
            ),
            Expanded(
              child: Padding(
                padding: const EdgeInsets.all(15.0),
                child: TextButton(
                  onPressed: () {
                    checkAnswer(false);
                  },
                  style: TextButton.styleFrom(
                    backgroundColor: Colors.red,
                  ),
                  child: Center(
                    child: Text(
                      'False',
                      style: TextStyle(
                        fontSize: 20,
                        color: Colors.white,
                      ),
                    ),
                  ),
                ),
              ),
            ),
            Row(
              children: scorekeeper,
            ),
          ],
        ),
      ),
    );
  }
}
```
</details>

or 


wrap the Scaffold in a builder.

```dart
 home: Builder(
     builder: (context) {
        return Scaffold(...);
      }
 );
```

And that should solve the issue.

Closing this issue as invalid, If you disagree feel free to write in the comments and I will reopen it.

Thank you.

**Comment by githubusar** [comment]
> @githubusar I saw your code sample and I see that you are directly using the flutter widgets inside the MaterialApp
> 
> ```dart
> home: Scaffold(...)
> ```
> 
> so the context that gets passed down the widget tree does not have [ MaterialLocalizations](https://api.flutter.dev/flutter/material/MaterialLocalizations-class.html), so there are two ways you can deal with this either instantiate another flutter Widget and pass it to home.
> 
> modified code sample
> or
> 
> wrap the Scaffold in a builder.
> 
> ```dart
>  home: Builder(
>      builder: (context) {
>         return Scaffold(...);
>       }
>  );
> ```
> 
> And that should solve the issue.
> 
> Closing this issue as invalid, If you disagree feel free to write in the comments and I will reopen it.
> 
> Thank you.

Thank you very much.
