### ISSUE TITLE
setState() or markNeedsBuild() called when widget tree was locked.

### ISSUE THREAD

**Issue by xiao-cao-x** [flutter/flutter#89554]
I switched the page to the login page after logging out my account, and the following exception occurred.
```
======== Exception caught by widgets library =======================================================
The following assertion was thrown while finalizing the widget tree:
setState() or markNeedsBuild() called when widget tree was locked.

This Scaffold widget cannot be marked as needing to build because the framework is locked.
The widget on which setState() or markNeedsBuild() was called was: Scaffold
  dependencies: [UnmanagedRestorationScope, _LocalizationsScope-[GlobalKey#1f885], Directionality, _ScaffoldMessengerScope, _InheritedTheme, _EffectiveTickerMode, MediaQuery]
  state: ScaffoldState#199f7(tickers: tracking 2 tickers)
When the exception was thrown, this was the stack: 
#0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4310:9)
#1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4320:6)
#2      State.setState (package:flutter/src/widgets/framework.dart:1108:15)
#3      ScaffoldState._drawerOpenedCallback (package:flutter/src/material/scaffold.dart:2325:5)
#4      DrawerControllerState.close (package:flutter/src/material/drawer.dart:488:28)
#5      DrawerControllerState._handleHistoryEntryRemoved (package:flutter/src/material/drawer.dart:393:5)
#6      LocalHistoryEntry._notifyRemoved (package:flutter/src/widgets/routes.dart:454:15)
#7      LocalHistoryRoute.removeLocalHistoryEntry (package:flutter/src/widgets/routes.dart:619:11)
#8      LocalHistoryEntry.remove (package:flutter/src/widgets/routes.dart:449:13)
#9      DrawerControllerState.dispose (package:flutter/src/material/drawer.dart:333:20)
#10     StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4895:11)
#11     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1883:13)
#12     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#13     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#14     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#15     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#16     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#17     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#18     ListIterable.forEach (dart:_internal/iterable.dart:39:13)
#19     _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:1892:25)
#20     BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2879:27)
#21     BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2510:15)
#22     BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2878:7)
#23     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:884:19)
#24     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
#25     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
#26     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1080:9)
#27     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#31     _invoke (dart:ui/hooks.dart:166:10)
#32     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#33     _drawFrame (dart:ui/hooks.dart:129:31)
(elided 3 frames from dart:async)
====================================================================================================
```
---
### Is caused by such a piece of code
```
if (null == accountManager.current){
   return Scaffold(...);
}
return Scaffold(... , drawre : xxx );
```

Because there is no Drawer on the login page, so an exception occurred at this location
```
#4      DrawerControllerState.close (package:flutter/src/material/drawer.dart:488:28)
#5      DrawerControllerState._handleHistoryEntryRemoved (package:flutter/src/material/drawer.dart:393:5)
```
And a back button appeared on the login page (root page)
![image](https://user-images.githubusercontent.com/76673990/132241631-659b1738-5fd0-42d7-8dde-40c9576d7dad.png)

**Comment by maheshmnj** [comment]
Hi @xiao-cao-x, Thanks for filing the issue, Please share a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) along with the output of `flutter doctor -v` to better address the issue.

Ps: from the error I can understand that you are probably calling setState while the tree has not yet built or is still building.
 

You could optionally try a check before calling setState

```
if (mounted) {
   //Do something
setState(() {});
}
```

**Comment by xiao-cao-x** [comment]
> 嗨@xiao-cao-x，感谢您提交问题，请分享一个[最小且完整的可重现代码](https://stackoverflow.com/help/minimal-reproducible-example)以及输出`flutter doctor -v`以更好地解决问题。
> 
> Ps：从错误中我可以理解您可能在树尚未构建或仍在构建时调用 setState 。
> 
> 您可以选择在调用 setState 之前尝试检查
> 
> ```
> if (mounted) {
>    //Do something
> setState(() {});
> }
> ```

I have solved it. The reason is that the Drawer opened when I switch to the login page is not closed (the page jumps from the `Drawer`)
I just need to call `Navigator.pop` to close `Drawer` before jumping to the page (`Navigator.push`).

**Comment by xiao-cao-x** [comment]
> Hi @xiao-cao-x, Thanks for filing the issue, Please share a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) along with the output of `flutter doctor -v` to better address the issue.
> 
> Ps: from the error I can understand that you are probably calling setState while the tree has not yet built or is still building.
> 
> You could optionally try a check before calling setState
> 
> ```
> if (mounted) {
>    //Do something
> setState(() {});
> }
> ```

I have solved it. The reason is that the Drawer opened when I switch to the login page is not closed (the page jumps from the `Drawer`)
I just need to call `Navigator.pop` to close `Drawer` before jumping to the page (`Navigator.push`).

**Comment by maheshmnj** [comment]
glad you solved it :)
