### ISSUE TITLE
[Camera] CamcorderProfile deprecated in Android API level 31

### ISSUE THREAD

**Issue by andreidiaconu** [flutter/flutter#89578]
The camera plugin can not be used with Android API level 31 because it uses a deprecated method and warnings are treated as errors.

## Steps to Reproduce

1. Start new project and use latest camera plugin
2. Set compile and target API versions in your build.gradle file to API level 31:
```
compileSdkVersion = 31
targetSdkVersion = 31
```
3. `flutter build apk`

**Expected results:** Build is successful

**Actual results:** Build fails with 8 warnings, treated as one error.

```
camera/features/resolution/ResolutionFeature.java:135: warning: [deprecation] get(int,int) in CamcorderProfile has been deprecated
           return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_HIGH);
                                  ^
camera/features/resolution/ResolutionFeature.java:139: warning: [deprecation] get(int,int) in CamcorderProfile has been deprecated
           return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_2160P);
                                  ^
camera/features/resolution/ResolutionFeature.java:143: warning: [deprecation] get(int,int) in CamcorderProfile has been deprecated
           return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_1080P);
                                  ^
camera/features/resolution/ResolutionFeature.java:147: warning: [deprecation] get(int,int) in CamcorderProfile has been deprecated
           return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_720P);
                                  ^
camera/features/resolution/ResolutionFeature.java:151: warning: [deprecation] get(int,int) in CamcorderProfile has been deprecated
           return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_480P);
                                  ^
camera/features/resolution/ResolutionFeature.java:155: warning: [deprecation] get(int,int) in CamcorderProfile has been deprecated
           return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_QVGA);
                                  ^
camera/features/resolution/ResolutionFeature.java:159: warning: [deprecation] get(int,int) in CamcorderProfile has been deprecated
           return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_LOW);
                                  ^
 error: warnings found and -Werror specified
camera/media/MediaRecorderBuilder.java:15: warning: [deprecation] MediaRecorder() in MediaRecorder has been deprecated
       return new MediaRecorder();
              ^
 1 error
 8 warnings
```

This affects https://github.com/flutter/flutter/pull/89511 which relands https://github.com/flutter/engine/pull/24756 which requires Android API 31. 

@blasten I'm pinging you here since you are most familiar with the affected issues and you also seem to have solved this in the past, when the camera did not work with API 30 https://github.com/flutter/plugins/pull/3299 - I intend to also open a PR for this issue, but I still think you should be in the loop.

**Comment by TahaTesser** [comment]
Hi @andreidiaconu 
Thanks for filing the issue, I can reproduce in a new project


<details> 
<summary>logs</summary> 
	
```console
[ +901 ms] C:\Users\Taha\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\camera-0.9.2+2\android\src\main\java\io\flutter\plugins\camera\features\resolution\ResolutionFeature.java:135: warning: [deprecation] get(int,int) in CamcorderProfile has been deprecated
[   +3 ms]           return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_HIGH);
[   +1 ms]                                  ^
[        ] C:\Users\Taha\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\camera-0.9.2+2\android\src\main\java\io\flutter\plugins\camera\features\resolution\ResolutionFeature.java:139: warning: [deprecation] get(int,int) in CamcorderProfile has been deprecated
[        ]           return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_2160P);
[   +1 ms]                                  ^
[        ] C:\Users\Taha\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\camera-0.9.2+2\android\src\main\java\io\flutter\plugins\camera\features\resolution\ResolutionFeature.java:143: warning: [deprecation] get(int,int) in CamcorderProfile has been deprecated
[        ]           return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_1080P);
[   +1 ms]                                  ^
[   +1 ms] C:\Users\Taha\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\camera-0.9.2+2\android\src\main\java\io\flutter\plugins\camera\features\resolution\ResolutionFeature.java:147: warning: [deprecation] get(int,int) in CamcorderProfile has been deprecated
[   +3 ms]           return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_720P);
[        ]                                  ^
[        ] C:\Users\Taha\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\camera-0.9.2+2\android\src\main\java\io\flutter\plugins\camera\features\resolution\ResolutionFeature.java:151: warning: [deprecation] get(int,int) in CamcorderProfile has been deprecated
[        ]           return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_480P);
[        ]                                  ^
[        ] C:\Users\Taha\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\camera-0.9.2+2\android\src\main\java\io\flutter\plugins\camera\features\resolution\ResolutionFeature.java:155: warning: [deprecation] get(int,int) in CamcorderProfile has been deprecated
[        ]           return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_QVGA);
[        ]                                  ^
[        ] C:\Users\Taha\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\camera-0.9.2+2\android\src\main\java\io\flutter\plugins\camera\features\resolution\ResolutionFeature.java:159: warning: [deprecation] get(int,int) in CamcorderProfile has been deprecated
[        ]           return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_LOW);
[   +1 ms]                                  ^
[        ] error: warnings found and -Werror specified
[        ] C:\Users\Taha\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\camera-0.9.2+2\android\src\main\java\io\flutter\plugins\camera\media\MediaRecorderBuilder.java:15: warning: [deprecation] MediaRecorder() in MediaRecorder has been deprecated
[        ]       return new MediaRecorder();
[        ]              ^
[        ] 1 error
[        ] 8 warnings
[  +67 ms] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Execution failed for task ':camera:compileDebugJavaWithJavac'.
[        ] > Compilation failed; see the compiler error output for details.
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 4s
[+3168 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +4 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:669:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>
```
	
</details>


<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel master, 2.6.0-1.0.pre.193, on Microsoft Windows [Version 10.0.22000.176], locale en-US)
    • Flutter version 2.6.0-1.0.pre.193 at C:\Users\Taha\Code\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0c5431d99c (34 hours ago), 2021-09-05 22:31:02 -0400
    • Engine revision b9c633900e
    • Dart version 2.15.0 (build 2.15.0-82.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Taha\Code\android-sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = C:\Users\Taha\Code\android-sdk
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31624.102
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.60.0)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.26.0

[✓] Connected device (5 available)
    • IN2011 (mobile)         • c9d8ee0c • android-arm64   • Android 11 (API 30)
    • Windows (desktop)       • windows  • windows-x64     • Microsoft Windows [Version 10.0.22000.176]
    • Windows (UWP) (desktop) • winuwp   • windows-uwp-x64 •
    • Chrome (web)            • chrome   • web-javascript  • Google Chrome 93.0.4577.63
    • Edge (web)              • edge     • web-javascript  • Microsoft Edge 92.0.902.84

• No issues found!
```
	
</details>

However, when change target to `31` in the official example from cloned `flutter/plugins` 
![image](https://user-images.githubusercontent.com/48603081/132344211-cbde3035-b83a-439a-a64d-d267f214bcc5.png)

```console
PS C:\Users\Taha\StudioProjects\plugins\packages\camera\camera\example> fm build apk

💪 Building with sound null safety 💪

Calling mockable JAR artifact transform to create file: C:\Users\Taha\.gradle\caches\transforms-2\files-2.1\23c94572e0d42c9193fc5a4eb4637df2\android.jar with input C:\Users\Taha\Code\android-sdk\platforms\android-31\android.jar
Removed unused resources: Binary resource data reduced from 39KB to 33KB: Removed 14%
Running Gradle task 'assembleRelease'...                           75.0s
✓  Built build\app\outputs\flutter-apk\app-release.apk (16.8MB).
PS C:\Users\Taha\StudioProjects\plugins\packages\camera\camera\example>
```

**Comment by andreidiaconu** [comment]
@TahaTesser It might be related to building from a local copy of the plugin. I noticed that when this last happened, the issue was also hard to reproduce using the example project: https://github.com/flutter/flutter/issues/69883#issuecomment-722927762

Thank you for also trying a fresh project, where the issue is indeed reproducible.

**Comment by Tom3652** [comment]
I was going to make the same issue. 
I can't build my app with the new target for Android 12.

**Comment by lvlrSajjad** [comment]
I have this problem too.
I set compileSdkVersion & targetSdkVersion to 31 and now it gives me this error:
```
Execution failed for task ':camera:compileDebugJavaWithJavac'.
```
I had to do this for another library ...

**Comment by Lix-ai** [comment]
Google, you must fix it

**Comment by blasten** [comment]
@camsim99 is working on the fix in flutter/plugins#4423

**Comment by devmaczw** [comment]
Getting the same error. We need an update on this

**Comment by SergioSanchezUltralytics** [comment]
Any solution apart from this?

> > > @camsim99 is working on the fix in [flutter/plugins#4423](https://github.com/flutter/plugins/pull/4423)
> > 
> > 
> > How can you pull this ? Could you help me? I try to declare on pubspec.yaml like this:
> > ```
> >  camera:
> >    git:
> >      url: https://github.com/camsim99/plugins.git
> >      path: packages/camera/camera
> >      ref: master
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but i get the same error as before
> 
> This work for me, as a temporary solution of course :
> 
> ```
> dependencies:
>   ...
>   # camera: ^0.9.4+2
>   camera:
>    git:
>      url: https://github.com/camsim99/plugins.git
>      path: packages/camera/camera
>      ref: issue_89578_dev
>   ...
> ```

**Comment by Puspharaj** [comment]
I cannot downgrade the compiledSDK version from 31 to 30, as geolocator cannot be compiled with 30. Recent plugin started to show similar error like this, Frustrating.  I am using tflite_flutter package that does not allow me to lower the compilesdk version. Looks like im in a space loop, Image_Picker depends on camera(0.8.0 - old) and tflite_flutter cannot accept more than camera 0.8,.... 

Please publish the plugin ASAP, I cannot test a new feature and leaving the project questionable before my audience and might leads to discontinue.

**Comment by AlexV525** [comment]
> Looks like im in a space loop, Image_Picker depends on camera(0.8.0 - old) and tflite_flutter cannot accept more than camera 0.8,....

I've checked your case. `image_picker` and `tflite_flutter` didn't depend on `camera`, and they're satisfied with each other.
![image](https://user-images.githubusercontent.com/15884415/137928544-c6af9e78-2456-4246-9966-7ea5ef993813.png)
