### ISSUE TITLE
RangeError (index): Index out of range: index should be less than 345600: 10

### ISSUE THREAD

**Issue by bazinac** [flutter/flutter#89584]
I have recently migrated my app to Flutter 2.3 with null safety and I encountered weird error. I have following function which I use to convert CameraImage (YUV) into RGB image, which worked flawlessly before going from Flutter 1.26 to 2.3 and migrating. Afterwards, it started to complain about RangeError (index): Index out of range, which I do not understand and error description is not helpful as reported index is actually within allowed range.

```
import 'package:camera/camera.dart';
import 'package:image/image.dart' as imageLib;

class ImageUtils {
...
  static imageLib.Image convertYUV420ToImage(CameraImage cameraImage) {
  
     final int width = cameraImage.width;
     final int height = cameraImage.height;
  
     final int uvRowStride = cameraImage.planes[1].bytesPerRow;
     final int? uvPixelStride = cameraImage.planes[1].bytesPerPixel;
  
     final image = imageLib.Image(width, height);
     for (int w = 0; w < width; w++) {
       for (int h = 0; h < height; h++) {
         final int uvIndex =
             uvPixelStride! * (w / 2).floor() + uvRowStride * (h / 2).floor();
         final int index = h * width + w;
  
         print("index $index and $uvIndex");
         final y = cameraImage.planes[0].bytes[index];
         final u = cameraImage.planes[1].bytes[uvIndex];
         final v = cameraImage.planes[2].bytes[uvIndex];
  
         image.data[index] = ImageUtils.yuv2rgb(y, u, v);
       }
     }
     return image;
   }
 }
```
### Log output:
...
```
I/flutter (19516): index 344169 and 172088
I/flutter (19516): index 344889 and 172088
I/flutter (19516): index 10 and 10
E/flutter (19516): [ERROR:flutter/runtime/dart_isolate.cc(1138)] Unhandled exception:
E/flutter (19516): RangeError (index): Index out of range: index should be less than 345600: 10
E/flutter (19516): #0      _Uint8ArrayView.[] (dart:typed_data-patch/typed_data_patch.dart:4070:7)
E/flutter (19516): #1      ImageUtils.convertYUV420ToImage (package:anh_flutter/recognition/ImageUtils.dart:42:46)
E/flutter (19516): #2      ImageUtils.convertCameraImage (package:anh_flutter/recognition/ImageUtils.dart:13:14)
E/flutter (19516): #3      IsolateUtils.entryPoint (package:anh_flutter/recognition/IsolateUtils.dart:47:30)
```
Which hardly makes any sense as **10** is less than **345600**. I also checked that **cameraImage.planes[0].bytes.length** is indeed **345600** as expected.

Pls could anyone help me understanding what might be wrong here?

### Doctor:
```
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale en_US.UTF-8)
    • Flutter version 2.2.3 at /home/bazinac/snap/flutter/common/flutter
    • Framework revision f4abaa0735 (10 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/bazinac/Android/Sdk
    • Platform android-30, build-tools 31.0.0
    • Java binary at: /home/bazinac/SW/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/bazinac/SW/android-studio
    • Flutter plugin version 60.1.2
    • Dart plugin version 203.8292
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] IntelliJ IDEA Community Edition (version 2021.2)
    • IntelliJ at /snap/intellij-idea-community/320
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (2 available)
    • SM G980F (mobile) • RF8NA1BGQ5L • android-arm64  • Android 11 (API 30)

```

**Comment by TahaTesser** [comment]
Hi @bazinac 
Thanks for filing the issue
Similar to https://github.com/flutter/flutter/issues/84276 https://github.com/flutter/flutter/issues/76029

**Comment by bazinac** [comment]
> Hi @bazinac
> Thanks for filing the issue
> Similar to #84276 #76029

I have noticed those two, but I believe here difference is that error output claims that index 10 is not within range 0 to 345600. In two preceding reports offending value was breaching size of collection...

**Comment by fuzzybinary** [comment]
I'm able to replicate this with my app after an upgrade to Flutter 2.5. https://github.com/fuzzybinary/flutter_lost_cities

Tap on any of the numbers on the first screen and you'll be taken to a camera view that will crash attempting to convert the image from YUV420. This is on a Pixel 3 running Android 11.  I tried updating camera to 0.9.2+2 and the issue persists.

**Comment by mraleph** [comment]
I suspect Dart JIT compiler issue. Reliably reproduces with @fuzzybinary code in debug mode.

**Comment by mraleph** [comment]
Does not reproduce on master so it might be already fixed - though it might be just hidden by some other changes.

**Comment by bazinac** [comment]
I also found similar issue happens when trying to convert image of format _ImageFormatGroup.jpeg_ to _imageLib.Image_ with following method.

  static imageLib.Image convertJpegToImage(CameraImage cameraImage) {
    return imageLib.Image.fromBytes(
        cameraImage.width, cameraImage.height, cameraImage.planes[0].bytes,
        format: imageLib.Format.rgb, channels: imageLib.Channels.rgb);
  }

**Comment by jason-simmons** [comment]
The issue seen in the https://github.com/fuzzybinary/flutter_lost_cities app stopped reproducing after this commit:
  https://github.com/dart-lang/sdk/commit/21298ee88433572bc0f483635d1d5e127bfd1d3c

That commit set the `enable_isolate_groups` flag to `true` by default.

The issue still occurs if I build a tip of tree engine with the latest Dart SDK and set `enable_isolate_groups` back to `false`.

@mraleph

**Comment by mkustermann** [comment]
@dcharkes Could you take a look at this? (the flag switch of `--enable-isolate-groups` should not have any functional changes)

**Comment by WillianSalceda** [comment]
Bump! I have the same problem with the exact same code

**Comment by dcharkes** [comment]
Reproduces with `flutter run --dart-flags --enable-isolate-groups=false -d emu` on https://github.com/fuzzybinary/flutter_lost_cities on 

```
flutter --version
Flutter 2.6.0-12.0.pre.124 • channel analyze-sample-code-verbosity • git@github.com:flutter/flutter.git
Framework • revision f0fdd68af8 (17 hours ago) • 2021-09-28 17:03:52 +0000
Engine • revision 9fa0bc833c
Tools • Dart 2.15.0 (build 2.15.0-154.0.dev)
```

Also reproduces on `flutter run --local-engine=android_debug_unopt_x86 --local-engine-src-path=$HOME/flt/engine/src -d emu` with https://github.com/flutter/engine/commit/520be3012286b4c5bce6c8038e7572820fa9ce6c, https://github.com/dart-lang/sdk/commit/f452a6585cbdc7804f07cdbf834bf8b7cef01faf, and `enable_isolate_groups` set back to false.

I will investigate.

**Comment by bazinac** [comment]
Hmm, it might be the case, but I am wondering why it works fine the in production version of my app (which still uses Flutter 1.26 because of this issue).

**Comment by bazinac** [comment]
Actually it turns out that behavior does not reproduce in master, my bad. So it was fixed, thanks for the support!
