### ISSUE TITLE
When I select a image for gallery, The application crash and report Only owner is able to interact with pending media content://media/external/images/media/94524

### ISSUE THREAD

**Issue by qs991011** [flutter/flutter#89645]
I think the reason is iamge cause. So How can I prevent this issue.

<details> 
<summary>logs</summary> 
	
```console
D/ActivityThread(23269): Won't deliver top position change in state=5
I/BlockMonitor(23269): dispatchingThrewException In MainThread
D/AndroidRuntime(23269): Shutting down VM
I/QarthLog(23269): [PatchStore] createDisableExceptionQarthFile
I/QarthLog(23269): [PatchStore] create disable file for com.example.fluitpatrol uid is 10913
E/AndroidRuntime(23269): FATAL EXCEPTION: main
E/AndroidRuntime(23269): Process: com.example.fluitpatrol, PID: 23269
E/AndroidRuntime(23269): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2342, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/image:94524 flg=0x1 }} to activity {com.example.fluitpatrol/com.example.fluitpatrol.MainActivity}: java.lang.IllegalStateException: Only owner is able to interact with pending media content://media/external/images/media/94524
E/AndroidRuntime(23269): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5782)
E/AndroidRuntime(23269): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5823)
E/AndroidRuntime(23269): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime(23269): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
E/AndroidRuntime(23269): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
E/AndroidRuntime(23269): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613)
E/AndroidRuntime(23269): 	at android.os.Handler.dispatchMessage(Handler.java:110)
E/AndroidRuntime(23269): 	at android.os.Looper.loop(Looper.java:219)
E/AndroidRuntime(23269): 	at android.app.ActivityThread.main(ActivityThread.java:8668)
E/AndroidRuntime(23269): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(23269): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/AndroidRuntime(23269): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
E/AndroidRuntime(23269): Caused by: java.lang.IllegalStateException: Only owner is able to interact with pending media content://media/external/images/media/94524
E/AndroidRuntime(23269): 	at android.os.Parcel.createException(Parcel.java:2098)
E/AndroidRuntime(23269): 	at android.os.Parcel.readException(Parcel.java:2058)
E/AndroidRuntime(23269): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:188)
E/AndroidRuntime(23269): 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
E/AndroidRuntime(23269): 	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:705)
E/AndroidRuntime(23269): 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1698)
E/AndroidRuntime(23269): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1514)
E/AndroidRuntime(23269): 	at android.content.ContentResolver.openInputStream(ContentResolver.java:1198)
E/AndroidRuntime(23269): 	at io.flutter.plugins.imagepicker.FileUtils.getPathFromUri(FileUtils.java:45)
E/AndroidRuntime(23269): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseImageResult(ImagePickerDelegate.java:486)
E/AndroidRuntime(23269): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:463)
E/AndroidRuntime(23269): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:739)
E/AndroidRuntime(23269): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:426)
E/AndroidRuntime(23269): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:677)
E/AndroidRuntime(23269): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:624)
E/AndroidRuntime(23269): 	at android.app.Activity.dispatchActivityResult(Activity.java:8541)
E/AndroidRuntime(23269): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5775)
E/AndroidRuntime(23269): 	... 11 more
I/Process (23269): Sending signal. PID: 23269 SIG: 9
Lost connection to device.
```
	
</details>

**Comment by TahaTesser** [comment]
Hi @qs991011 
Are you using `image_picker`? Which device are you using? 

Can you please provide your `flutter doctor -v`, your `flutter run --verbose`, your `pubspec.yaml`, and a minimal reproducible code sample.
Thank you

**Comment by qs991011** [comment]
yes, I use the huawei P30.
the code show
`
  Future _getGalleryImage() async {
      var image = await _picker.pickImage(
          source: ImageSource.gallery, imageQuality: 25); // 使用图库
      setState(() {
        _imageFile = image;
      });
  }
`

the doctor 

![flutter3](https://user-images.githubusercontent.com/15025829/132489090-76605fe2-9d0a-47d4-8de4-84b1d9ecc91d.png)

the  yaml
`name: fluitpatrol
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  fluttertoast: ^8.0.1-nullsafety.0
  share: ^2.0.0
  flutter_spinkit: ^5.0.0
  sqflite: 2.0.0
  pub_semver: 2.0.0
  flutter_svg: 0.21.0-nullsafety.0
  flutter_slidable: ^0.6.0-nullsafety.0
  dio: 4.0.0
  path_provider: 2.0.0
  flutter_webview_plugin: 0.3.11
  webview_flutter: 2.0.0
    #bezier: ^1.1.5
  flare_flutter: ^3.0.0-nullsafety.0
    # 固定版本
  flutter_redux: 0.8.0
  rxdart: 0.26.0
  graphql: 5.0.0-nullsafety.1+readmefix
    #flutter_cache_manager: 3.0.0-nullsafety.0
  provider: 5.0.0
  permission_handler: 6.0.1
  json_annotation: 4.0.1
  package_info: 2.0.0
  connectivity: 3.0.0
  flutter_markdown: 0.6.0
  device_info: 2.0.0
  url_launcher: 6.0.1
  google_fonts: 2.0.0
  android_intent: 2.0.0
  shared_preferences: 2.0.1
  built_value: 8.0.6
  simple_animations: 3.0.1
  supercharged: 2.0.0
  animations: 2.0.0
  auto_size_text: 3.0.0-nullsafety.0
  flutter_localizations:
    sdk: flutter
  photo_view: 0.11.1
  encrypt: ^5.0.0
  amap_flutter_location: ^2.0.0
  image_picker: ^0.8.4
  amap_flutter_map: ^2.0.1
  video_player: ^2.1.14
  roundcheckbox: ^2.0.2+1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  flutter_easyloading: ^3.0.0
  rounded_loading_button: ^2.0.3
  intl: ^0.17.0
  marquee: ^2.2.0
  flutter_datetime_picker: ^1.5.1

  multi_select_flutter: ^4.0.0

  async: ^2.4.1
  pull_to_refresh: ^2.0.0




  #cached_network_image: ^3.1.0

  #date_format: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.9.0
  json_serializable: ^4.1.0


 #  test:  ^1.17.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  assets:
    - static/images/
    - static/file/


  fonts:
    - family: wxcIconFont
      fonts:
        - asset: static/font/iconfont.ttf
    - family: google_kavivanar
      fonts:
        - asset: static/font/google_kavivanar.ttf
`

**Comment by TahaTesser** [comment]
Hi @qs991011 


Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by TahaTesser** [comment]
k

**Comment by uzumaki258** [comment]
I got some crashes in Firebase. 
![image](https://user-images.githubusercontent.com/26773292/134097592-2225dd52-be50-4cf6-aa38-3d0a459e3be0.png)
I will try to reproduce it.
