### ISSUE TITLE
No implementation found for method getApplicationSupportDirectory on channel plugins.flutter.io/path_provider

### ISSUE THREAD

**Issue by lakshmiprasadkota** [flutter/flutter#89650]
## Steps to Reproduce

I upgraded packages into the latest version and migrate my code into null safety, after that I got this errors 

```
Future<String> downloadDir(int? bookId) async {
  var downloadDirectory = await getApplicationDocumentsDirectory();
  var _savedBooksDir = Directory('${downloadDirectory.path}');
  return '${_savedBooksDir.path}/$bookId.epub';
}

Future getRawEpub(int bookId) async {
  var downloadDirectory = await getApplicationDocumentsDirectory();
  var file = File('${Directory(downloadDirectory.path).path}/$bookId.epub');
  return file.existsSync() ? file : null;
}

Future deleteEpub(int bookId) async {
  var downloadDirectory = await getApplicationDocumentsDirectory();
  var _savedBooksDir = Directory('${downloadDirectory.path}');
  var file = File('${_savedBooksDir.path}/$bookId.epub');

  if (file.existsSync()) {
    await file.delete();
  }
}

Future deleteEpubs() async {
  var downloadDirectory = await getApplicationDocumentsDirectory();
  var _savedBooksDir = Directory('${downloadDirectory.path}');
  var files = _savedBooksDir.listSync();
  for (var item in files) {
    if (item.path.contains('.epub')) {
      await item.delete();
    }
  }
}
```

## Logs

<details>
<summary>logs</summary>

```
Restarted application in 1,904ms.
E/flutter (31652): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationSupportDirectory on channel plugins.flutter.io/path_provider)
E/flutter (31652): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
E/flutter (31652): <asynchronous suspension>
E/flutter (31652): #1      getApplicationSupportDirectory (package:path_provider/path_provider.dart:100:24)
E/flutter (31652): <asynchronous suspension>
E/flutter (31652): #2      _localPath (package:google_fonts/src/file_io_desktop_and_mobile.dart:28:21)
E/flutter (31652): <asynchronous suspension>
E/flutter (31652): #3      _localFile (package:google_fonts/src/file_io_desktop_and_mobile.dart:33:16)
E/flutter (31652): <asynchronous suspension>
E/flutter (31652): #4      saveFontToDeviceFileSystem (package:google_fonts/src/file_io_desktop_and_mobile.dart:7:16)
E/flutter (31652): <asynchronous suspension>
E/flutter (31652): 
E/flutter (31652): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationSupportDirectory on channel plugins.flutter.io/path_provider)
E/flutter (31652): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
E/flutter (31652): <asynchronous suspension>
E/flutter (31652): #1      getApplicationSupportDirectory (package:path_provider/path_provider.dart:100:24)
E/flutter (31652): <asynchronous suspension>
E/flutter (31652): #2      _localPath (package:google_fonts/src/file_io_desktop_and_mobile.dart:28:21)
E/flutter (31652): <asynchronous suspension>
E/flutter (31652): #3      _localFile (package:google_fonts/src/file_io_desktop_and_mobile.dart:33:16)
E/flutter (31652): <asynchronous suspension>
E/flutter (31652): #4      saveFontToDeviceFileSystem (package:google_fonts/src/file_io_desktop_and_mobile.dart:7:16)
E/flutter (31652): <asynchronous suspension>
E/flutter (31652): 
E/flutter (31652): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method read on channel plugins.it_nomads.com/flutter_secure_storage)
E/flutter (31652): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
E/flutter (31652): <asynchronous suspension>
E/flutter (31652): #1      FlutterSecureStorage.read (package:flutter_secure_storage/flutter_secure_storage.dart:50:27)
E/flutter (31652): <asynchronous suspension>
E/flutter (31652): #2      FlutterSecureStorage.containsKey (package:flutter_secure_storage/flutter_secure_storage.dart:71:9)
E/flutter (31652): <asynchronous suspension>
E/flutter (31652): #3      LocalStorage.getItemData (package:libri_app/utils/local_storage.dart:192:12)
E/flutter (31652): <asynchronous suspension>
E/flutter (31652): #4      SplashVM._handlePersistentLogin (package:libri_app/core/viewmodels/splash_vm.dart:55:19)
E/flutter (31652): <asynchronous suspension>
E/flutter (31652):
```

```
```

```
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1165], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] Connected device (4 available)

• No issues found!
```

</details>

**Comment by maheshmnj** [comment]
Hi @lakshmiprasadkota, Thanks for filing the issue, Please share a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) to better address the issue, the minimal code should be ready to run with minimal or no code changes.
Optionally you may also take a look at this [stackoverflow thread](https://stackoverflow.com/questions/58080990/no-implementation-found-for-method-getapplicationdocumentsdirectory-on-channel-p)

Thank you.

**Comment by lavahasif** [comment]
flutter clean  and  flutter pub get  .solve the  problem.
else check  the build folder properly generated the android module like shared preference  folder  like this. 
![image](https://user-images.githubusercontent.com/22430922/132778036-1372e306-969e-42b7-962c-3d092767358e.png)
not this 
![image](https://user-images.githubusercontent.com/22430922/132778136-df5510aa-104f-48f5-ac5f-745e14caa1af.png)
like this .then check your pubsec.yaml code and check your assets folder name other than assets

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
