### ISSUE TITLE
[Web] Right shift cannot press when focused on TextField using Visual Studio Code

### ISSUE THREAD

**Issue by licy183** [flutter/flutter#89665]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Add a `TextField`
3. Focus on the `TextField` and then press right shift.

Then an exception was thrown and will pause on Visual Studio Code. How normal is this?

<details>
  <summary>Logs</summary>

```
Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/keyboard_binding.dart:352:16
                    result != null
                    "Invalid modifier location: Shift, 0"
                        at Object.throw_ [as throw] (http://localhost:58212/dart_sdk.js:5061:11)
                        at Object.assertFailed (http://localhost:58212/dart_sdk.js:4986:15)
                        at http://localhost:58212/dart_sdk.js:159178:39
                        at _engine.KeyboardConverter.new.handleEvent (http://localhost:58212/dart_sdk.js:159184:25)
                        at http://localhost:58212/dart_sdk.js:158928:76
                        at loggedHandler (http://localhost:58212/dart_sdk.js:158906:43)
```

```
Analyzing webtest...
No issues found! (ran in 2.1s)
```

```
[√] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.19043.1110], locale zh-CN)
    • Flutter version 2.5.0 at D:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (10 hours ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Ayasei\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.10.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.10.31424.327
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2020.3.2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.60.0)
    • VS Code at C:\Users\Ayasei\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.26.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1110]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 93.0.4577.63
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 93.0.961.38

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@licy183 
I verified this behavior on latest master and stable using below sample code, but wasn't able to replicate the error.

```
body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: TextField(
          decoration: InputDecoration(
            hintText: 'enter'
          ),
        )
      ),
```
Since you mentioned on VSCode, I am not sure if that's causing it, because I tried it on Android studio.

<details>
<summary> flutter doctor -v </summary>

```
[√] Flutter (Channel master, 2.6.0-1.0.pre.237, on Microsoft Windows [Version 10.0.19042.1165], locale en-US)
    • Flutter version 2.6.0-1.0.pre.237 at D:\FlutterSDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a54b10254a (2 hours ago), 2021-09-10 07:22:02 +0300
    • Engine revision 57bc7414b8
    • Dart version 2.15.0 (build 2.15.0-92.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Win\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31624.102
    X The current Visual Studio installation is incomplete. Please reinstall Visual Studio.

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.60.0)
    • VS Code at C:\Users\Win\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm    • Android 8.1.0 (API 27)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.19042.1165]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 93.0.4577.63
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 93.0.961.38

! Doctor found issues in 1 category.

[√] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.19042.1165], locale en-US)
    • Flutter version 2.2.3 at D:\FlutterSDK\flutter
    • Framework revision f4abaa0735 (31 hours ago), 2021-09-07 12:46:11 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Win\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Connected device (5 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm    • Android 8.1.0 (API 27)
    • SM G975F (mobile) • RZ8M802WY0X      • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.19042.1165]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 93.0.4577.63
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 92.0.902.84

! Doctor found issues in 1 category.

C:\Users\Win>

```

</details>

Can you also try it on latest master with same settings and see if it persists ?

**Comment by licy183** [comment]
@darshankawar 
I tried it on latest master, and I got the same assert failed error. I also tried it on Android Studio. It didn't pause but also got the assert failed error. Maybe only VSCode will pause on that error.
So is it normal to get such an error when pressing right shift key on keyboard?

```
Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/keyboard_binding.dart:353:16
result != null
"Invalid modifier location: Shift, 0"
    at Object.throw_ [as throw] (http://localhost:60569/dart_sdk.js:5080:11)
    at Object.assertFailed (http://localhost:60569/dart_sdk.js:5005:15)
    at http://localhost:60569/dart_sdk.js:168686:39
    at _engine.KeyboardConverter.new.handleEvent (http://localhost:60569/dart_sdk.js:168692:25)
    at http://localhost:60569/dart_sdk.js:168425:74
    at loggedHandler (http://localhost:60569/dart_sdk.js:168401:18)
```
or
```
Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/src/services/hardware_keyboard.dart:787:16
false
"Should never encounter KeyData when transitMode is rawKeyData."
    at Object.throw_ [as throw] (http://localhost:61047/dart_sdk.js:5061:11)
    at Object.assertFailed (http://localhost:61047/dart_sdk.js:4986:15)
    at hardware_keyboard.KeyEventManager.new.handleKeyData (http://localhost:61047/packages/flutter/src/services/restoration.dart.lib.js:5334:28)
    at http://localhost:61047/dart_sdk.js:160131:47
    at Object.invoke (http://localhost:61047/dart_sdk.js:179656:7)
    at _engine.EnginePlatformDispatcher.__.invokeOnKeyData (http://localhost:61047/dart_sdk.js:160131:17)
    at _engine.KeyboardBinding.__.[_onKeyData] (http://localhost:61047/dart_sdk.js:158922:49)
    at _engine.KeyboardConverter.new.handleEvent (http://localhost:61047/dart_sdk.js:159261:52)
    at http://localhost:61047/dart_sdk.js:158928:76
    at loggedHandler (http://localhost:61047/dart_sdk.js:158906:43)

```

**Comment by darshankawar** [comment]
> So is it normal to get such an error when pressing right shift key on keyboard?

It is definitely not normal. So, to replicate it, you have a textfield and you tap on it and then press right Shift key which throws this assertion ?  Are you using a physical or virtual keyboard for it ?

**Comment by licy183** [comment]
> Are you using a physical or virtual keyboard for it ?
I'm using a physical keyboard. Browser is Chrome 93.0.4577.63 on Windows 10 21H1 (19043.1110).

**Comment by darshankawar** [comment]
@licy183 
Sorry for getting back late on this. I tried again on latest stable using VSCode but still was unable to replicate or see the issue. I ran the sample code using both renderers but still don't see the issue.
Would be good if you could provide us a short video, what steps are you taking and then the error thrown.
Thanks.

**Comment by darshankawar** [comment]
@licy183 
Thanks for the video. I followed exact steps mentioned in it, but still unable to replicate the error.
One thing I noticed is, the location where you created the app. Is it inside where your Flutter SdK is ?

**Comment by licy183** [comment]
@darshankawar 
No, the project was created outside the SDK path. The SDK on master branch is at ~/Desktop/test/flutter_master, but I created the project at ~/Desktop/test/demo.

**Comment by darshankawar** [comment]
I've been unable to replicate this behavior per my earlier comments, so I am going ahead and labeling it for further investigation from web team.

**Comment by mdebbar** [comment]
It looks like this because the [`kWebLogicalLocationMap["Shift"][0]`](https://github.com/flutter/engine/blob/master/lib/web_ui/lib/src/engine/key_map.dart#L627) is null. @dkwingsmt any idea why there's a null there?

**Comment by maheshmnj** [comment]
Probably related to https://github.com/flutter/flutter/issues/90167

**Comment by licy183** [comment]
Any update? I have found that it may be ralated to the Microsoft IME. When I use Chinese IME and press right shift, it will produce such an exception, but when I use English IME, it will not.

**Comment by johnwcchau** [comment]
I have the same problem using MS Japanese IME, Chrome 103.0.5060.114 Windows 10, this bug will not happen when switching to non-IME input method

**Comment by justinmc** [comment]
Looks like we were struggling to reproduce this years ago, @licy183 have you still been seeing this bug?  I'm wondering if we should close it at this point.

**Comment by licy183** [comment]
I can't reproduce it anymore, so I think it has been resolved and I'll close this issue. Thank you for all your attention and help!

`flutter doctor -v`

<details>

```
Flutter assets will be downloaded from https://mirrors.tuna.tsinghua.edu.cn/flutter. Make sure you trust this source!
[✓] Flutter (Channel stable, 3.19.3, on Microsoft Windows [版本 10.0.22635.3276], locale zh-CN)
    • Flutter version 3.19.3 on channel stable at D:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (13 hours ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1
    • Pub download mirror https://mirrors.tuna.tsinghua.edu.cn/dart-pub
    • Flutter download mirror https://mirrors.tuna.tsinghua.edu.cn/flutter

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at D:\Android\Sdk
    • Platform android-33-ext4, build-tools 33.0.1
    • Java binary at: D:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.4.4)
    • Visual Studio at D:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.4.33213.308
    • Windows 10 SDK version 10.0.22000.0

[✓] Android Studio (version 2022.1)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[✓] VS Code, 64-bit edition (version 1.87.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.84.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.22635.3276]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 122.0.6261.111
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 123.0.2420.20

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by justinmc** [comment]
Sounds good! Thanks for checking in on this @licy183 after all this time.
