### ISSUE TITLE
[web] Flutter 2.5, Unsupported operation: bool.fromEnvironment can only be used as a const constructor

### ISSUE THREAD

**Issue by litt1e-p** [flutter/flutter#89724]
## Steps to Reproduce

1. Run `flutter run -d chrome`.
2. chrome opened with en error in console and there is nothing showing on screen

**Expected results:** 

show content in web

**Actual results:** 

chrome console throw an error below

<details>
  <summary>Logs</summary>

```
An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:60598/DS1DbYFakpw=
Error: Unsupported operation: bool.fromEnvironment can only be used as a const constructor
    at Object.throw_ [as throw] (http://localhost:60280/dart_sdk.js:5061:11)
    at Function.fromEnvironment (http://localhost:60280/dart_sdk.js:118700:17)
    at Function.get isRelease [as isRelease] (http://localhost:60280/packages/news/common/router/router.dart.lib.js:3498:24)
    at new http.HttpUtil._internal (http://localhost:60280/packages/news/common/router/router.dart.lib.js:3947:24)
    at get _instance (http://localhost:60280/packages/news/common/router/router.dart.lib.js:3984:14)
    at Function.desc.get [as _instance] (http://localhost:60280/dart_sdk.js:5552:17)
    at Function.new (http://localhost:60280/packages/news/common/router/router.dart.lib.js:3653:28)
    at init (http://localhost:60280/packages/news/common/router/router.dart.lib.js:3504:26)
    at init.next (<anonymous>)
    at http://localhost:60280/dart_sdk.js:38640:33
    at _RootZone.runUnary (http://localhost:60280/dart_sdk.js:38511:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:60280/dart_sdk.js:33713:29)
    at handleValueCallback (http://localhost:60280/dart_sdk.js:34265:49)
    at Function._propagateToListeners (http://localhost:60280/dart_sdk.js:34303:17)
    at _Future.new.[_completeWithValue] (http://localhost:60280/dart_sdk.js:34151:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:60280/dart_sdk.js:34172:35)
    at Object._microtaskLoop (http://localhost:60280/dart_sdk.js:38778:13)
    at _startMicrotaskLoop (http://localhost:60280/dart_sdk.js:38784:13)
    at http://localhost:60280/dart_sdk.js:34519:9
```

```
```

```
```

</details>

## environment

flutter doctor -v:
```
[✓] Flutter (Channel stable, 2.5.0, on Mac OS X 10.15.2 19C57 darwin-x64)
[✗] Android toolchain - develop for Android devices
[!] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
• Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] VS Code (version 1.60.0)
[✓] Connected device (1 available)
 • Chrome (web) • chrome • web-javascript • Google Chrome 93.0.4577.63
```

**Comment by TahaTesser** [comment]
Hi @litt1e-p 
`flutter run -d chrome` has no issue on the latest stable, are you assign any value to the command? using code sample?

<img width="940" alt="Screenshot 2021-09-09 at 13 57 34" src="https://user-images.githubusercontent.com/48603081/132673994-18c3a76d-99b8-4643-bf71-acb83f266dd5.png">


<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.5.0, on macOS 12.0 21A5506j darwin-x64, locale en-GB)
    • Flutter version 2.5.0 at /Users/tahatesser/Code/flutter_stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (29 hours ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7621141/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 13.0, Build version 13A5212g
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7621141/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7621141/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7583922/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.0 21A5506j darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 93.0.4577.63

• No issues found!
```
	
</details>

**Comment by litt1e-p** [comment]
@TahaTesser sorry, it is my fault, it works well now while I replace `static` with `const` as below:
```
// static bool prd = bool.fromEnvironment("dart.vm.product");
const bool prd = bool.fromEnvironment("dart.vm.product");
```
thanks for your reply
