### ISSUE TITLE
[Android 12 beta] App crashes after changing location permission details and returning to app (NPE in FlutterEngineActivityPluginBinding, Unable to resume activity)

### ISSUE THREAD

**Issue by PieterAelse** [flutter/flutter#89737]
## Steps to Reproduce
**See attached video.**

**Issue starts at step 13**, other steps are needed to get there.

1. Download/install the Philips Hue app on a device running Android 12 beta (in my case SPB5.210812.002 to be precise).
2. Setup the app (connect to a .bridge, lights etc).
3. Go to the tab "Automations".
4. Tap on the blue "Create automation" button, or the blue "+" button, _this will start the creation flow._
5. Select "Coming Home" (or "Leaving Home) automation.
6. Tap on the blue "Add this device" button, _this will start a setup flow (permissions etc)._
7. Tap "Next" until you need to "Enable out of home" control.
8. Enable "out of home" control by logging in, _proceeding to the next step._
9. Tap on "Allow access" to get the first permission pop-up.
10. Select "Precise" and either "While using the app" or "Only this time" _(the latter choice doesn't matter much). The next step will show a GoogleMaps screen with your current location._
11. Tap on "Save this location". _The next step will show info about battery optimization._
12. Tap on "Turn off" and "Allow" on the system dialog that pops up. _Next step will be "complaining" that the permission needs to be the "Always" type, not "While using the app" or "Only this time"._
13. Tap on "Allow access" and in the system dialog tap on "Allow in settings". _The permission settings screen will be shown._
14. Tap on "Allow all the time" **and** flip the toggle of "Use precise location" to **off**, in that order! (doing it the other way around didn't result in crash for me).
15. Leave the screen with e.g. the Android hardware back button/swipe or the back button on the top left.
16. ==> the app crashes on a NPE in Flutter activity code.

**Snippet**

> Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Map.containsKey(java.lang.Object)' on a null object reference
>         at e.b.a.n.onRequestPermissionsResult(Unknown Source:110)
>         at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult(Unknown Source:20)
>         at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onRequestPermissionsResult(Unknown Source:15)
>         at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onRequestPermissionsResult(Unknown Source:59)
>         at io.flutter.embedding.android.FlutterActivity.onRequestPermissionsResult(Unknown Source:10)

**Expected results:** 
The origin app app (in this case Hue) is shown.

**Actual results:** 
The app crashes.

**Video's**
Can be viewed/downloaded here: https://photos.app.goo.gl/Cp8Yx73cnmDSXakeA 

<details>
  <summary>Logs</summary>
  
```console
    --------- beginning of crash
2021-09-09 11:06:35.651 18670-18670/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.philips.lighting.hue2, PID: 18670
    java.lang.RuntimeException: Unable to resume activity {com.philips.lighting.hue2/com.philips.lighting.hue2.ContentActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=24, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.philips.lighting.hue2/com.philips.lighting.hue2.ContentActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Map.containsKey(java.lang.Object)' on a null object reference
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4761)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4794)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
        at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2214)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=24, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.philips.lighting.hue2/com.philips.lighting.hue2.ContentActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Map.containsKey(java.lang.Object)' on a null object reference
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5304)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4748)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4794) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54) 
        at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2214) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7842) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Map.containsKey(java.lang.Object)' on a null object reference
        at e.b.a.n.onRequestPermissionsResult(Unknown Source:110)
        at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult(Unknown Source:20)
        at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onRequestPermissionsResult(Unknown Source:15)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onRequestPermissionsResult(Unknown Source:59)
        at io.flutter.embedding.android.FlutterActivity.onRequestPermissionsResult(Unknown Source:10)
        at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8529)
        at android.app.Activity.dispatchActivityResult(Activity.java:8386)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5297)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4748) 
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4794) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54) 
        at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2214) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7842) 
```

</details>

<details>
  <summary>Flutter docter -v</summary>
  
  ```
[macbook-name]:Code pieter$ flutter doctor -v
[✓] Flutter (Channel unknown, 2.2.2, on macOS 11.5.1 20G80 darwin-x64, locale
    en-US)
    • Flutter version 2.2.2 at [path]/dev/flutter
    • Framework revision d79295af24 (3 months ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version
    30.0.2)
    • Android SDK at /Users/pieter/Library/Android/sdk
    • Platform android-S, build-tools 30.0.2
    • ANDROID_HOME = /Users/pieter/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 59.0.4
    • Dart plugin version 212.5080.8

[✓] Connected device (3 available)
    • Pixel 3a (mobile) • 943AY0JP36 • android-arm64  • Android 12 (API 31)
    • macOS (desktop)   • macos      • darwin-x64     • macOS 11.5.1 20G80
      darwin-x64
    • Chrome (web)      • chrome     • web-javascript • Google Chrome
      93.0.4577.63

! Doctor found issues in 1 category.
```

</details>

**Comment by TahaTesser** [comment]
Hi @PieterAelse 
Thanks for filing the issue, based on your `doctor -v` (2.2.2), looks `Philips Hue app` built on this version. 

Can you please reproduce the issue running on the latest stable `2.5.0`?

**Comment by PieterAelse** [comment]
@TahaTesser Indeed it was 2.2.2. I've tried with 2.5.0 and the issue remains. **But**, because I was using a debug build now I noticed in the stacktrace that there's a mention of a permissions plugin where it crashes (line was obfuscated before).

Before:

> Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Map.containsKey(java.lang.Object)' on a null object reference
>         at e.b.a.n.onRequestPermissionsResult(Unknown Source:110)
>         at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult(Unknown Source:20)

Now I noticed it from the package [permission_handler](https://pub.dev/packages/permission_handler) :

>Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Map.containsKey(java.lang.Object)' on a null object reference
>         at com.baseflow.permissionhandler.PermissionManager.onRequestPermissionsResult(PermissionManager.java:133)
>         at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:713)

So I will head over to their repo and report it there! 😄

**Comment by danagbemava-nc** [comment]
Closing based on [this comment](https://github.com/flutter/flutter/issues/89737#issuecomment-916089182).
