### ISSUE TITLE
Flutter 2.5 makes diagnosing unbounded height worse - And that's saying something

### ISSUE THREAD

**Issue by jhancock4d** [flutter/flutter#89788]
## Steps to Reproduce

Put a column with main axis size = max in a scrollable and run it on Android.

In VS Code this goes through no less than 11 breakpoints in the flutter sdk. The release notes say that it's supposed to make breaking into flutter sdk better and not obnoxious but it's WAY worse.

AND the gibberish it spews makes it all but impossible to tell what control actually has the issue in all but trial and error
AND if you change something after that, hot reload doesn't work and hangs and you have to stop debug and start it again.

## What it should do
Break on the actual line of code for the actual control that actually is causing the problem WITHOUT breaking into ANY of the flutter sdk.

**Comment by darshankawar** [comment]
> Put a column with main axis size = max in a scrollable and run it on Android.

@jhancock4d Used below code sample to verify this:

```
body: Center(
          child: SingleChildScrollView(
            child: Column(
              mainAxisSize: MainAxisSize.max,
              children: [
                Text('Test'),
                Text('Test'),
                Text('Test')
              ],
            ),
          )
        ),
```

Although, I don't use VSCode, atleast on AS, there were not any logs while I ran the code and also after hot reload, the log was clean.



> hot reload doesn't work and hangs and you have to stop debug and start it again.

Does it throw any error when you perform hot reload ? 

In order to properly address this issue, would be good if you could provide us a minimal code sample, the log spew you mentioned.
Thanks.

**Comment by jhancock4d** [comment]
There's no error on hot reload, it just sits there forever until you kill the debug session.

This started throwing in Flutter 2.5.0 and worked fine in the previous stable release.

This code, on a Scaffold used to work fine, but now it errors with the below. I've worked around it by putting a Flexible with fit.loose, but finding that was almost impossible:

```
Theme(
      data: gridTheme,
      child: Card(
        borderOnForeground: false,
        elevation: widget.elevation,
        margin: widget.padding,
        child: LayoutBuilder(
          builder: (context, constraints) => Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            mainAxisSize: constraints.hasBoundedHeight
                ? MainAxisSize.max
                : MainAxisSize.min,
            children: [
              ResponsiveDataGridPagedBodyWidget(
                widget.gridState,
                widget.theme,
                pageItems,
                true, //constraints.hasBoundedHeight,
              ),
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  IconButton(
                    onPressed: () => setPage(1),
                    icon: Icon(
                      Icons.first_page,
                    ),
                  ),
                  IconButton(
                    onPressed: currentPage == 1
                        ? null
                        : () => setPage(
                              math.max(1, currentPage - 1),
                            ),
                    icon: Icon(
                      Icons.fast_rewind,
                    ),
                  ),
                  Spacer(),
                  Spacer(),
                  IconButton(
                    onPressed: currentPage == pageCount
                        ? null
                        : () => setPage(math.min(pageCount, currentPage + 1)),
                    icon: Icon(
                      Icons.fast_forward,
                    ),
                  ),
                  IconButton(
                    onPressed: () => setPage(pageCount),
                    icon: Icon(
                      Icons.last_page,
                    ),
                  ),
                ],
              ),
            ],
          ),
        );
```

Interesting if you inject a LayoutBuilder above card, then hasBoundedHeight is true, card makes it false, but it is false after the card even though the card is in a theme which is the body for the scaffold. And strangely, hasInfiniteHeight = false which seems to be a contradiction in terms. If it doesn't have bounded height is't it by definition infiiteHeight? And why did this change?

In any event, the issue here is that the spew is all but impossible to figure out what's going on. It doesn't reference the actual controls, so trying to figure out what it's referring to with stuff like this "RenderRepaintBoundary#f9b2b..." is next to impossible.

The debugger should be breaking directly on the control that would cause infinite height so that we can actually fix this. My junior devs, have A TON of problems with flutter because of this, and find this impenetrable to understand based on this noise. (yes all of the teaching them in the world of what this means still causes errors that they have to figure out.)

Also, the bottom line of the spew, isn't actually what's causing the unbounded height.  It's a child of that that is also a Column, that causes it but it reports the incorrect control as the problem.


Here's the spew:

```
Launching lib\main.dart on Windows in debug mode...
Connecting to VM Service at ws://127.0.0.1:63736/znxLwCtX_Mg=/ws

════════ Exception caught by rendering library ═════════════════════════════════
The following assertion was thrown during performLayout():
RenderFlex children have non-zero flex but incoming height constraints are unbounded.

When a column is in a parent that does not provide a finite height constraint, for example if it is in a vertical scrollable, it will try to shrink-wrap its children along the vertical axis. Setting a flex on a child (e.g. using Expanded) indicates that the child is to expand to fill the remaining space in the vertical direction.
These two directives are mutually exclusive. If a parent is to shrink-wrap its child, the child cannot simultaneously expand to fit its parent.

Consider setting mainAxisSize to MainAxisSize.min and using FlexFit.loose fits for the flexible children (using Flexible rather than Expanded). This will allow the flexible children to size themselves to less than the infinite remaining space they would otherwise be forced to take, and then will cause the RenderFlex to shrink-wrap the children rather than expanding to fit the maximum constraints provided by the parent.

If this message did not help you determine the problem, consider using debugDumpRenderTree():
  https://flutter.dev/debugging/#rendering-layer
  http://api.flutter.dev/flutter/rendering/debugDumpRenderTree.html
The affected RenderFlex is: RenderFlex#bc541 relayoutBoundary=up10 NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE
    parentData: offset=Offset(0.0, 0.0) (can use size)
    constraints: BoxConstraints(0.0<=w<=1256.3, 0.0<=h<=Infinity)
    size: Size(36.0, 36.0)
    direction: vertical
    mainAxisAlignment: start
    mainAxisSize: min
    crossAxisAlignment: stretch
    verticalDirection: down
    child 1: RenderRepaintBoundary#f9b2b NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        needs compositing
        parentData: offset=Offset(0.0, 0.0); flex=1; fit=FlexFit.tight
        constraints: MISSING
        size: MISSING
        usefulness ratio: no metrics collected yet (never painted)
        child: RenderSemanticsGestureHandler#b2569 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
            parentData: <none>
            constraints: MISSING
            size: MISSING
            behavior: deferToChild
            gestures: <none>
            child: RenderPointerListener#9c3c8 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
                parentData: <none>
                constraints: MISSING
                size: MISSING
                behavior: deferToChild
                listeners: down
                child: RenderMouseRegion#f4f9c NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
                    parentData: <none>
                    constraints: MISSING
                    size: MISSING
                    listeners: hover, exit
    child 2: RenderFlex#77bb0 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        parentData: offset=Offset(0.0, 0.0); flex=null; fit=null
        constraints: MISSING
        size: MISSING
        direction: horizontal
        mainAxisAlignment: spaceBetween
        mainAxisSize: max
        crossAxisAlignment: center
        textDirection: ltr
        verticalDirection: down
        child 1: RenderSemanticsAnnotations#adb20 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
            parentData: offset=Offset(0.0, 0.0); flex=null; fit=null
            constraints: MISSING
            size: MISSING
            child: RenderSemanticsAnnotations#01fea NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
                parentData: <none>
                constraints: MISSING
                size: MISSING
                child: RenderMouseRegion#7cb7b NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
                    parentData: <none>
                    constraints: MISSING
                    size: MISSING
                    listeners: enter, exit
                    cursor: SystemMouseCursor(click)
        child 2: RenderSemanticsAnnotations#689ea NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
            parentData: offset=Offset(0.0, 0.0); flex=null; fit=null
            constraints: MISSING
            size: MISSING
            child: RenderSemanticsAnnotations#f7c4e NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
                parentData: <none>
                constraints: MISSING
                size: MISSING
                child: RenderMouseRegion#48749 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
                    parentData: <none>
                    constraints: MISSING
                    size: MISSING
                    listeners: enter, exit
                    cursor: SystemMouseCursor(click)
        child 3: RenderConstrainedBox#3e532 NEEDS-LAYOUT NEEDS-PAINT
            parentData: offset=Offset(0.0, 0.0); flex=1; fit=FlexFit.tight
            constraints: MISSING
            size: MISSING
            additionalConstraints: BoxConstraints(w=0.0, h=0.0)
        child 4: RenderConstrainedBox#f1b82 NEEDS-LAYOUT NEEDS-PAINT
            parentData: offset=Offset(0.0, 0.0); flex=1; fit=FlexFit.tight
            constraints: MISSING
            size: MISSING
            additionalConstraints: BoxConstraints(w=0.0, h=0.0)
        child 5: RenderSemanticsAnnotations#fb0ba NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
            parentData: offset=Offset(0.0, 0.0); flex=null; fit=null
            constraints: MISSING
            size: MISSING
            child: RenderSemanticsAnnotations#08795 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
                parentData: <none>
                constraints: MISSING
                size: MISSING
                child: RenderMouseRegion#81739 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
                    parentData: <none>
                    constraints: MISSING
                    size: MISSING
                    listeners: enter, exit
                    cursor: SystemMouseCursor(click)
        child 6: RenderSemanticsAnnotations#bccc8 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
            parentData: offset=Offset(0.0, 0.0); flex=null; fit=null
            constraints: MISSING
            size: MISSING
            child: RenderSemanticsAnnotations#5e60d NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
                parentData: <none>
                constraints: MISSING
                size: MISSING
                child: RenderMouseRegion#dd9dc NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
                    parentData: <none>
                    constraints: MISSING
                    size: MISSING
                    listeners: enter, exit
                    cursor: SystemMouseCursor(click)
The creator information is set to: Column ← LayoutBuilder ← FutureBuilder<void> ← PagerWidget<ExampleData>-[<Instance of 'LoadCriteria'>] ← Column ← NotificationListener<GridCriteriaChangeNotification> ← LayoutBuilder ← Container ← Semantics ← DefaultTextStyle ← AnimatedDefaultTextStyle ← _InkFeatures-[GlobalKey#3d244 ink renderer] ← ⋯
The nearest ancestor providing an unbounded width constraint is: RenderFlex#6d8eb relayoutBoundary=up8 NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE

See also: https://flutter.dev/layout/

If none of the above helps enough to fix this problem, please don't hesitate to file a bug:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md
The relevant error-causing widget was
Column Column:file:///D:/Repos/concerti/responsive_data_grid/responsive_data_grid/lib/src/widgets/pager.dart:93:46
When the exception was thrown, this was the stack
#0      RenderFlex.performLayout.<anonymous closure>
#1      RenderFlex.performLayout
#2      RenderObject.layout
#3      _RenderLayoutBuilder.performLayout
#4      RenderObject.layout
#5      ChildLayoutHelper.layoutChild
#6      RenderFlex._computeSizes
#7      RenderFlex.performLayout
#8      RenderObject.layout
#9      _RenderLayoutBuilder.performLayout
#10     RenderObject.layout
#11     RenderProxyBoxMixin.performLayout
#12     RenderObject.layout
#13     RenderProxyBoxMixin.performLayout
#14     RenderObject.layout
#15     RenderProxyBoxMixin.performLayout
#16     RenderCustomPaint.performLayout
#17     RenderObject.layout
#18     RenderProxyBoxMixin.performLayout
#19     _RenderCustomClip.performLayout
#20     RenderObject.layout
#21     RenderPadding.performLayout
#22     RenderObject.layout
#23     RenderProxyBoxMixin.performLayout
#24     RenderObject.layout
#25     MultiChildLayoutDelegate.layoutChild
#26     _ScaffoldLayout.performLayout
#27     MultiChildLayoutDelegate._callPerformLayout
#28     RenderCustomMultiChildLayoutBox.performLayout
#29     RenderObject._layoutWithoutResize
#30     PipelineOwner.flushLayout
#31     RendererBinding.drawFrame
#32     WidgetsBinding.drawFrame
#33     RendererBinding._handlePersistentFrameCallback
#34     SchedulerBinding._invokeFrameCallback
#35     SchedulerBinding.handleDrawFrame
#36     SchedulerBinding._handleDrawFrame
#40     _invoke (dart:ui/hooks.dart:166:10)
#41     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#42     _drawFrame (dart:ui/hooks.dart:129:31)
(elided 3 frames from dart:async)
The following RenderObject was being processed when the exception was fired: RenderFlex#bc541 relayoutBoundary=up10 NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE
RenderObject: RenderFlex#bc541 relayoutBoundary=up10 NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE
    parentData: offset=Offset(0.0, 0.0) (can use size)
    constraints: BoxConstraints(0.0<=w<=1256.3, 0.0<=h<=Infinity)
    size: Size(36.0, 36.0)
    direction: vertical
    mainAxisAlignment: start
    mainAxisSize: min
    crossAxisAlignment: stretch
    verticalDirection: down
    child 1: RenderRepaintBoundary#f9b2b NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        needs compositing
        parentData: offset=Offset(0.0, 0.0); flex=1; fit=FlexFit.tight
        constraints: MISSING
        size: MISSING
        usefulness ratio: no metrics collected yet (never painted)
        child: RenderSemanticsGestureHandler#b2569 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
            parentData: <none>
            constraints: MISSING
            size: MISSING
            behavior: deferToChild
            gestures: <none>
            child: RenderPointerListener#9c3c8 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
                parentData: <none>
                constraints: MISSING
                size: MISSING
                behavior: deferToChild
                listeners: down
                child: RenderMouseRegion#f4f9c NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
                    parentData: <none>
                    constraints: MISSING
                    size: MISSING
                    listeners: hover, exit
    child 2: RenderFlex#77bb0 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        parentData: offset=Offset(0.0, 0.0); flex=null; fit=null
        constraints: MISSING
        size: MISSING
        direction: horizontal
        mainAxisAlignment: spaceBetween
        mainAxisSize: max
        crossAxisAlignment: center
        textDirection: ltr
        verticalDirection: down
        child 1: RenderSemanticsAnnotations#adb20 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
            parentData: offset=Offset(0.0, 0.0); flex=null; fit=null
            constraints: MISSING
            size: MISSING
            child: RenderSemanticsAnnotations#01fea NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
                parentData: <none>
                constraints: MISSING
                size: MISSING
                child: RenderMouseRegion#7cb7b NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
                    parentData: <none>
                    constraints: MISSING
                    size: MISSING
                    listeners: enter, exit
                    cursor: SystemMouseCursor(click)
        child 2: RenderSemanticsAnnotations#689ea NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
            parentData: offset=Offset(0.0, 0.0); flex=null; fit=null
            constraints: MISSING
            size: MISSING
            child: RenderSemanticsAnnotations#f7c4e NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
                parentData: <none>
                constraints: MISSING
                size: MISSING
                child: RenderMouseRegion#48749 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
                    parentData: <none>
                    constraints: MISSING
                    size: MISSING
                    listeners: enter, exit
                    cursor: SystemMouseCursor(click)
        child 3: RenderConstrainedBox#3e532 NEEDS-LAYOUT NEEDS-PAINT
            parentData: offset=Offset(0.0, 0.0); flex=1; fit=FlexFit.tight
            constraints: MISSING
            size: MISSING
            additionalConstraints: BoxConstraints(w=0.0, h=0.0)
        child 4: RenderConstrainedBox#f1b82 NEEDS-LAYOUT NEEDS-PAINT
            parentData: offset=Offset(0.0, 0.0); flex=1; fit=FlexFit.tight
            constraints: MISSING
            size: MISSING
            additionalConstraints: BoxConstraints(w=0.0, h=0.0)
        child 5: RenderSemanticsAnnotations#fb0ba NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
            parentData: offset=Offset(0.0, 0.0); flex=null; fit=null
            constraints: MISSING
            size: MISSING
            child: RenderSemanticsAnnotations#08795 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
                parentData: <none>
                constraints: MISSING
                size: MISSING
                child: RenderMouseRegion#81739 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
                    parentData: <none>
                    constraints: MISSING
                    size: MISSING
                    listeners: enter, exit
                    cursor: SystemMouseCursor(click)
        child 6: RenderSemanticsAnnotations#bccc8 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
            parentData: offset=Offset(0.0, 0.0); flex=null; fit=null
            constraints: MISSING
            size: MISSING
            child: RenderSemanticsAnnotations#5e60d NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
                parentData: <none>
                constraints: MISSING
                size: MISSING
                child: RenderMouseRegion#dd9dc NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
                    parentData: <none>
                    constraints: MISSING
                    size: MISSING
                    listeners: enter, exit
                    cursor: SystemMouseCursor(click)
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
RenderBox was not laid out: RenderRepaintBoundary#f9b2b NEEDS-LAYOUT NEEDS-PAINT
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1929 pos 12: 'hasSize'

The relevant error-causing widget was
Column Column:file:///D:/Repos/concerti/responsive_data_grid/responsive_data_grid/lib/src/widgets/pager.dart:93:46
════════════════════════════════════════════════════════════════════════════════

```

**Comment by darshankawar** [comment]
@jhancock4d 
Thanks for the details. From `RenderDumpTree()`, I see that it's showing:

```
constraints: MISSING
                size: MISSING
```
And hence throwing `Failed assertion: line 1929 pos 12: 'hasSize'` on `pager.dart`. Can you please provide the missing code snippet for `setPage()`, `ResponsiveDataGridPagedBodyWidget(
                widget.gridState,
                widget.theme,
                pageItems,
                true, //constraints.hasBoundedHeight,
              ),`

so that we can directly use your entire code sample and run to verify this ?

**Comment by jhancock4d** [comment]
Here's the build of that stateless widget.  The problem is that before that even though there is nothing that actually has any height at all (just listeners etc.) this tries to set itself to expand, but can't because even though everything really does have bounded height it errors.

But nevertheless, this is the code that actually causes the error (the expanded down below):

```
    final child = ListView.separated(
      separatorBuilder: (context, index) =>
          grid.widget.separatorThickness == null ||
                  grid.widget.separatorThickness == 0.0
              ? Container()
              : Divider(
                  thickness: grid.widget.separatorThickness,
                ),
      shrinkWrap: !scroll,
      scrollDirection: Axis.vertical,
      physics: !scroll
          ? const NeverScrollableScrollPhysics()
          : const AlwaysScrollableScrollPhysics(),
      padding: grid.widget.padding.copyWith(top: 0, bottom: 0),
      itemCount: items.length,
      itemBuilder: (context, index) {
        final item = items[index];
        return DataGridRowWidget<TItem>(
          item,
          grid.widget.columns,
          grid.widget.itemTapped,
          theme,
          grid.widget.contentPadding,
        );
      },
    );

    return scroll
        ? Expanded(
            child: child,
          )
        : child;

```

**Comment by darshankawar** [comment]
Thanks for the details. Keeping this open for further insights from the team.
