### ISSUE TITLE
Drag scrolling doesn't work on DESKTOP and WEB apps -- After upgrading to flutter 2.5.0 (stable)

### ISSUE THREAD

**Issue by newtaDev** [flutter/flutter#89814]
### **vertical and horizontal drag scrolling in listView,SingleChildScrollView,ListView.builder,PageView doesn't  work in DESKTOP and WEB applications, in mobile works fine**

- before upgrading to **flutter 2.5.0** , It was working fine 

- And sometimes it also throws this error after **HOT RESTARTING** the application

```
════════ Exception caught by services library ══════════════════════════════════
The following assertion was thrown during a platform message callback:

A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#862ce(physicalKey: PhysicalKeyboardKey#700e2(usbHidUsage: "0x000700e2", debugName: "Alt Left"), logicalKey: LogicalKeyboardKey#00104(keyId: "0x200000104", keyLabel: "Alt Left", debugName: "Alt Left"), character: null, timeStamp: 0:31:28.970000, synthesized)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 441 pos 16: '_pressedKeys.containsKey(event.physicalKey)'

2

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack
#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure>
package:flutter/…/services/hardware_keyboard.dart:441
#3      HardwareKeyboard._assertEventIsRegular
package:flutter/…/services/hardware_keyboard.dart:452
#4      HardwareKeyboard.handleKeyEvent
package:flutter/…/services/hardware_keyboard.dart:543
#5      KeyEventManager.handleRawKeyMessage
package:flutter/…/services/hardware_keyboard.dart:821
#6      BasicMessageChannel.setMessageHandler.<anonymous closure>
package:flutter/…/services/platform_channel.dart:73
#7      BasicMessageChannel.setMessageHandler.<anonymous closure>
package:flutter/…/services/platform_channel.dart:72
#8      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>
package:flutter/…/services/binding.dart:379
#9      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>
package:flutter/…/services/binding.dart:376
#10     _invoke2.<anonymous closure> (dart:ui/hooks.dart:205:15)
#14     _invoke2 (dart:ui/hooks.dart:204:10)
#15     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#16     _Channel.push (dart:ui/channel_buffers.dart:132:31)
#17     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#18     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:544:22)
#19     _dispatchPlatformMessage (dart:ui/hooks.dart:92:31)
(elided 5 frames from class _AssertionError and dart:async)
════════════════════════════════════════════════════════════════════════════════

```

**flutter doctor -v**
```

[✓] Flutter (Channel stable, 2.5.0, on Ubuntu 20.04.3 LTS 5.11.0-27-generic, locale en_GB.UTF-8)
    • Flutter version 2.5.0 at /home/dev-mallu/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (2 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/dev-mallu/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /home/dev-mallu/Android/Sdk
    • Java binary at: /home/dev-mallu/Downloads/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 4.1)
    • Android Studio at /home/dev-mallu/Downloads/android-studio
    • Flutter plugin version 52.0.1
    • Dart plugin version 201.9245
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.59.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • Redmi 6 Pro (mobile) • 48b191740505 • android-arm64  • Android 9 (API 28)
    • Linux (desktop)      • linux        • linux-x64      • Ubuntu 20.04.3 LTS 5.11.0-27-generic
    • Chrome (web)         • chrome       • web-javascript • Google Chrome 92.0.4515.159

• No issues found!
```

**Comment by TheJulianJES** [comment]
The scrolling part is expected. Please see: https://flutter.dev/docs/release/breaking-changes/default-scroll-behavior-drag

**Comment by newtaDev** [comment]
Thank you @TheJulianJES
