### ISSUE TITLE
Very strange error

### ISSUE THREAD

**Issue by jesselpereira** [flutter/flutter#89813]
Hi, I'm new to Flutter and I just upgraded to 2.5 but I'm having an error that I can't understand.

```
Launching lib\main.dart on SM G611MT in debug mode...
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:50240/OF-IBcc23Ms=/ws
D/vndksupport(31118): Loading /vendor/lib/hw/android.hardware.graphics.mapper@2.0-impl.so from current namespace instead of sphal namespace.
E/flutter (31118): [ERROR:flutter/fml/platform/android/jni_util.cc(182)] java.lang.SecurityException: Permission Denial: broadcast from android asks to run as user -1 but is calling from user 0; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
E/flutter (31118): 	at android.os.Parcel.createException(Parcel.java:1966)
E/flutter (31118): 	at android.os.Parcel.readException(Parcel.java:1934)
E/flutter (31118): 	at android.os.Parcel.readException(Parcel.java:1884)
E/flutter (31118): 	at android.app.IActivityManager$Stub$Proxy.reportActivityFullyDrawn(IActivityManager.java:7309)
E/flutter (31118): 	at android.app.Activity.reportFullyDrawn(Activity.java:2092)
E/flutter (31118): 	at io.flutter.embedding.android.FlutterActivity.onFlutterUiDisplayed(FlutterActivity.java:1061)
E/flutter (31118): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$1.onFlutterUiDisplayed(FlutterActivityAndFragmentDelegate.java:88)
E/flutter (31118): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (31118): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/flutter (31118): 	at android.os.Looper.loop(Looper.java:181)
E/flutter (31118): 	at android.app.ActivityThread.main(ActivityThread.java:7124)
E/flutter (31118): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (31118): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
E/flutter (31118): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
E/flutter (31118): Caused by: android.os.RemoteException: Remote stack trace:
E/flutter (31118): 	at com.android.server.am.UserController.handleIncomingUser(UserController.java:1827)
E/flutter (31118): 	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:25923)
E/flutter (31118): 	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:25854)
E/flutter (31118): 	at com.android.server.am.ActivityManagerService.broadcastIntent(ActivityManagerService.java:26724)
E/flutter (31118): 	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1264)
2
E/flutter (31118):
F/flutter (31118): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1201)] Check failed: fml::jni::CheckException(env).
F/libc    (31118): Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 31118 (breaklabs.onpay), pid 31118 (breaklabs.onpay)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'samsung/on7xrefltedtvvj/on7xreflte:9/PPR1.180610.011/G611MTVJS8CUG1:user/release-keys'
Revision: '8'
ABI: 'arm'
pid: 31118, tid: 31118, name: breaklabs.onpay  >>> br.com.breaklabs.onpay <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1201)] Check failed: fml::jni::CheckException(env).
'
    r0  00000000  r1  0000798e  r2  00000006  r3  00000008
    r4  0000798e  r5  0000798e  r6  ff7ee0e4  r7  0000010c
    r8  00000001  r9  ff7ee1f8  r10 ecb347ac  r11 00000034
    ip  00000041  sp  ff7ee0d0  lr  efaed0c5  pc  efae3f76
backtrace:
    #00 pc 0001cf76  /system/lib/libc.so (abort+58)
    #01 pc 011cc85d  /data/app/br.com.breaklabs.onpay-kXm_dBDvbRigQSTNQufOng==/lib/arm/libflutter.so (offset 0x11cb000)
    #02 pc 000035fe  [anon:libc_malloc:c9680000]
Lost connection to device.
Exited (sigterm)
```

If anyone can help me, please. Thanks.

**Comment by reddnavneet** [comment]
Permission Denial: broadcast from android asks to run as user -1 but is calling from user 0; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS

1. run flutter clean and then flutter analyze
2. If you are using a device instead of the emulator then try to remove the app from the phone and reinstall
3. Or check the phone permission.

**Comment by TheJulianJES** [comment]
Duplicate of https://github.com/flutter/flutter/issues/88767

**Comment by jesselpereira** [comment]
The error happened because I simply removed the snippet below the code from the AndroidManifest.xml file:

```
<meta-data
    android:name="io.flutter.embedding.android.SplashScreenDrawable"
    android:resource="@drawable/launch_background"
    />
```

I use the flutter native splash package so I returned the removed code and the application worked.

**Comment by danagbemava-nc** [comment]
Hi @jesselpereira, is it safe to assume that your issue has been solved?

**Comment by jesselpereira** [comment]
> Hi @jesselpereira, is it safe to assume that your issue has been solved?

Yep, has been solved.
