### ISSUE TITLE
App build successful but cannot run

### ISSUE THREAD

**Issue by jnbDeveloper** [flutter/flutter#89823]
<details>
<summary> logs</summary>

```console
Launching lib\main.dart on SM M127F in debug mode...

lib\main.dart:1
Parameter format not correct -
√  Built build\app\outputs\flutter-apk\app-debug.apk.
E/AndroidRuntime(22854): FATAL EXCEPTION: main
E/AndroidRuntime(22854): Process: com.example.digital_id, PID: 22854
E/AndroidRuntime(22854): java.lang.ClassCastException: com.example.digital_id.MainActivity cannot be cast to io.flutter.embedding.android.FlutterActivity
E/AndroidRuntime(22854): 	at com.amolg.flutterbarcodescanner.FlutterBarcodeScannerPlugin.createPluginSetup(FlutterBarcodeScannerPlugin.java:248)
E/AndroidRuntime(22854): 	at com.amolg.flutterbarcodescanner.FlutterBarcodeScannerPlugin.onAttachedToActivity(FlutterBarcodeScannerPlugin.java:275)
E/AndroidRuntime(22854): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.add(FlutterEngineConnectionRegistry.java:153)
E/AndroidRuntime(22854): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:16)
E/AndroidRuntime(22854): 	at com.example.digital_id.MainActivity.configureFlutterEngine(MainActivity.kt:9)
E/AndroidRuntime(22854): 	at io.flutter.embedding.android.FlutterFragment.configureFlutterEngine(FlutterFragment.java:1023)
E/AndroidRuntime(22854): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:180)
E/AndroidRuntime(22854): 	at io.flutter.embedding.android.FlutterFragment.onAttach(FlutterFragment.java:609)

```
</details>

**Comment by danagbemava-nc** [comment]
Hi @jnbDeveloper, the logs your provided suggest that the error is coming from the `flutter_barcode_scanner` plugin. I would suggest you take that up on their repo. 

Closing as this is not an issue with `flutter` itself but a third party plugin. 

If you disagree, kindly post a comment stating why and I will reopen.

Thank you
