### ISSUE TITLE
Downloading Gradle every time

### ISSUE THREAD

**Issue by Mayank-9018** [flutter/flutter#89903]
I am on a metered connection and every time I open VS Code or Android Studio and run the project, it downloads Gradle every time, I did `flutter run --verbose` and for every project and on the same project too, everytime it just deletes the files in `.gradle` and starts redownloading everything. I am on a metered connection and this issue is costing me.

And if run the app without internet connection, I receive this error:

#89000 and #89959 are similar issues. Any workaround or maybe including a flag to work around this would be appreciated.

## Logs

<details>
<summary>Logs</summary>

```
[  +18 ms] Running Gradle task 'assembleDebug'...
[   +3 ms] Using gradle from /home/mayank/StudioProjects/check/android/gradlew.
[  +17 ms] executing: /snap/android-studio/114/android-studio/jre/bin/java -version
[ +106 ms] Exit code 0 from: /snap/android-studio/114/android-studio/jre/bin/java -version
[        ] openjdk version "11.0.10" 2021-01-19
           OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
           OpenJDK 64-Bit Server VM (build 11.0.10+0-b96-7249189, mixed mode)
[   +2 ms] executing: [/home/mayank/StudioProjects/check/android/] /home/mayank/StudioProjects/check/android/gradlew
-Pverbose=true -Ptarget-platform=android-arm64 -Ptarget=/home/mayank/StudioProjects/check/lib/main.dart
-Pdart-defines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== -Pdart-obfuscation=false -Ptrack-widget-creation=true
-Ptree-shake-icons=false -Pfilesystem-scheme=org-dartlang-root assembleDebug
[ +229 ms] Downloading https://services.gradle.org/distributions/gradle-6.7-all.zip
[ +207 ms] Exception in thread "main" java.net.UnknownHostException: services.gradle.org
[   +1 ms]      at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:220)
[        ]      at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[        ]      at java.base/java.net.Socket.connect(Socket.java:609)
[        ]      at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:289)
[        ]      at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
[        ]      at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
[        ]      at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
[        ]      at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
[        ]      at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
[        ]      at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
[        ]      at
java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnect
ion.java:203)
[        ]      at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
[        ]      at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
[        ]      at
java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:
189)
[        ]      at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
[        ]      at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
[        ]      at
java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
[        ]      at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
[        ]      at org.gradle.wrapper.Download.download(Download.java:44)
[        ]      at org.gradle.wrapper.Install$1.call(Install.java:61)
[        ]      at org.gradle.wrapper.Install$1.call(Install.java:48)
[        ]      at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
[        ]      at org.gradle.wrapper.Install.createDist(Install.java:48)
[        ]      at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
[        ]      at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
[  +26 ms] Running Gradle task 'assembleDebug'... (completed in 589ms)
[+7844 ms] Exception: Gradle task assembleDebug failed with exit code 1
[        ] "flutter run" took 9,232ms.
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:669:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1125:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>
```

```
[✓] Flutter (Channel master, 2.6.0-1.0.pre.219, on Ubuntu 21.04 5.11.0-25-generic, locale en_IN)
    • Flutter version 2.6.0-1.0.pre.219 at /home/mayank/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 58944e6b88 (2 days ago), 2021-09-08 19:37:34 -0700
    • Engine revision 6a3b04632b
    • Dart version 2.15.0 (build 2.15.0-82.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/mayank/android-sdk/
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = /home/mayank/android-sdk/
    • Java binary at: /snap/android-studio/114/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /snap/android-studio/114/android-studio
    • Flutter plugin version 59.0.2
    • Dart plugin version 203.8292
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • Redmi 4 (mobile) • 6b0b6837d440 • android-arm64  • Android 10 (API 29)
    • Linux (desktop)  • linux        • linux-x64      • Ubuntu 21.04 5.11.0-25-generic
    • Chrome (web)     • chrome       • web-javascript • Google Chrome 92.0.4515.107

• No issues found!

```

</details>

**Comment by darshankawar** [comment]
@Mayank-9018 
What does `I am on a metered connection` mean ? 
If you are connected to normal wifi, does it work as intended ?

**Comment by Mayank-9018** [comment]
@darshankawar Metered connection, as in, it has a data limit.

This also happens on a normal wifi connection.

**Comment by alejandrogiubel** [comment]
Yes this issue is cost to me a lot of data connection in something named `cache`. That its functions is reuse the downloaded files for prevent future redundant downloads. Like @Mayank-9018 says, we need any workaround or a flag to avoid this issue.

**Comment by darshankawar** [comment]
@Mayank-9018 
Please check [this](https://stackoverflow.com/questions/62589406/way-to-stop-android-studio-gradle-build-from-using-internet-data) SO link and see if if helps.

**Comment by Mayank-9018** [comment]
If I were to believe [this](https://stackoverflow.com/a/62589571) answer, gradle will reuse the artifacts. Gradle had to re-download certain files (possibly?) as a result of my upgrading from 2.2.x to 2.5 and then switching from Stable to Master channel. I'll keep an eye on it, and if the problem persists, I'll reopen the issue. For the time being, I'm closing the issue. Thank you for your time, @darshankawar

**Comment by asatayo** [comment]
Me too, and it’s becoming serious re-downloaded the gradle five times a week. Any solution please. I thought the issue was to change the emulator version but not yet. 

Flutter 2.51
Dart.    2.14.2
