### ISSUE TITLE
Scrollable Disposes Position On Route Change

### ISSUE THREAD

**Issue by caseycrogers** [flutter/flutter#89924]
## Steps to Reproduce

1. Nest a `ListView` in a `Navigator`.
2. Nest a stateful widget that listens on scroll changes via `Scrollable.of(context)!.addListener(...)` inside the list view. Have it display or print the current scroll offset.
3. Run the app.
4. Push an arbitrary new page over the `ListView` page.
5. Pop the arbitrary page.
6. Scroll down the list view.

**Expected results:** 

The stateful widget listening to the scroll position updates to reflect the list view offset in step 6.

**Actual results:** 

The listener fails to fire and the stateful widget fails to update. Additionally, if the stateful widget calls `removeListener` in it's dispose function, that call will throw because the `position` change notifier has been disposed.

**What's happening:**

It appears that `ListView` disposes of it's scroll position notifier when it is no longer the current route, and then rebuilds the notifier when it's enclosing route becomes current again. This breaks any listeners relying on the position notifier.

**Repro code:**
(apologies for the size of the repro code, it's a hard bug to demonstrate).

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  int? _selectedItem;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        body: Builder(
          builder: (context) {
            return SafeArea(
              child: Navigator(
                onPopPage: (route, result) {
                  if (!route.didPop(result)) {
                    return false;
                  }
                  _selectedItem = null;
                  return true;
                },
                pages: [
                  MaterialPage(
                    child: ListView(
                      children: [
                        ScrollAwareWidget(),
                        ...List.generate(
                          30,
                          (index) => TextButton(
                              onPressed: () {
                                setState(() {
                                  _selectedItem = index;
                                });
                              },
                              child: Text(index.toString())),
                        ),
                      ],
                    ),
                  ),
                  if (_selectedItem != null)
                    MaterialPage(
                      child: Builder(
                        builder: (context) => Align(
                          alignment: Alignment.topLeft,
                          child: Row(
                            children: [
                              IconButton(
                                onPressed: () => Navigator.of(context).pop(),
                                icon: Icon(Icons.arrow_back),
                              ),
                              Text('Selected Item: $_selectedItem'),
                            ],
                          ),
                        ),
                      ),
                    ),
                ],
              ),
            );
          },
        ),
      ),
    );
  }
}

class ScrollAwareWidget extends StatefulWidget {
  ScrollAwareWidget({Key? key}) : super(key: key);

  @override
  _ScrollAwareWidgetState createState() => _ScrollAwareWidgetState();
}

class _ScrollAwareWidgetState extends State<ScrollAwareWidget> {
  bool initialized = false;
  late ScrollPosition _position;
  double _scrollProgress = 0;

  @override
  void didChangeDependencies() {
    if (!initialized) {
      initialized = true;
      _position = Scrollable.of(context)!.position;
      _position.addListener(_onScroll);
    }
    super.didChangeDependencies();
  }

  @override
  void dispose() {
    _position.removeListener(_onScroll);
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Text(_scrollProgress.toString(), style: TextStyle(fontSize: 36));
  }

  void _onScroll() {
    setState(() {
      _scrollProgress = _position.pixels;
    });
  }
}
```

<details>
  <summary>Logs</summary>

```
Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.19043.1165], locale en-US)
```

</details>

**Comment by maheshmnj** [comment]
Hi @caseycrogers, Thanks for filing the issue. I am able to replicate the issue on the latest stable and the master channel it seems like the listener is Active I could see the events firing up on pop, post the exception.
 
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.5.2 20G95 darwin-arm, locale en-GB)
    • Flutter version 2.5.0 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (5 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • iPad Pro (11-inch) (3rd generation) (mobile) • 4367E72A-10EB-46BA-9E12-D89A8F0DA157 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5
      (simulator)
    • macOS (desktop)                              • macos                                • darwin-arm64   • macOS 11.5.2 20G95 darwin-arm
    • Chrome (web)                                 • chrome                               • web-javascript • Google Chrome 93.0.4577.63

• No issues found!
```

```
[✓] Flutter (Channel master, 2.6.0-1.0.pre.103, on macOS 11.5.2 20G95 darwin-arm, locale en-GB)
    • Flutter version 2.6.0-1.0.pre.103 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2c30b252a5 (2 weeks ago), 2021-08-27 23:26:03 -0400
    • Engine revision ca52647cd2
    • Dart version 2.15.0 (build 2.15.0-65.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • iPad Pro (11-inch) (3rd generation) (mobile) • 4367E72A-10EB-46BA-9E12-D89A8F0DA157 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5
      (simulator)
    • macOS (desktop)                              • macos                                • darwin-arm64   • macOS 11.5.2 20G95 darwin-arm
    • Chrome (web)                                 • chrome                               • web-javascript • Google Chrome 93.0.4577.63

• No issues found!
```
</details>


 
 
 <details>
<summary>logs</summary>

```console
Launching lib/main.dart on iPhone 12 Pro in debug mode...
Xcode build done.                                           17.2s
Connecting to VM Service at ws://127.0.0.1:55893/eNDuqYZ7h4A=/ws

════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
A ScrollPositionWithSingleContext was used after being disposed.

Once you have called dispose() on a ScrollPositionWithSingleContext, it can no longer be used.
When the exception was thrown, this was the stack
#0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure>
#1      ChangeNotifier._debugAssertNotDisposed
#2      ChangeNotifier.removeListener
#3      _ScrollAwareWidgetState.dispose
#4      StatefulElement.unmount
#5      _InactiveElements._unmount
#6      _InactiveElements._unmount.<anonymous closure>
#7      SingleChildRenderObjectElement.visitChildren
#8      _InactiveElements._unmount
#9      _InactiveElements._unmount.<anonymous closure>
#10     SingleChildRenderObjectElement.visitChildren
#11     _InactiveElements._unmount
#12     _InactiveElements._unmount.<anonymous closure>
#13     ComponentElement.visitChildren
#14     _InactiveElements._unmount
#15     _InactiveElements._unmount.<anonymous closure>
#16     ComponentElement.visitChildren
#17     _InactiveElements._unmount
#18     _InactiveElements._unmount.<anonymous closure>
#19     ComponentElement.visitChildren
#20     _InactiveElements._unmount
#21     _InactiveElements._unmount.<anonymous closure>
#22     ComponentElement.visitChildren
#23     _InactiveElements._unmount
#24     ListIterable.forEach (dart:_internal/iterable.dart:39:13)
#25     _InactiveElements._unmountAll
#26     BuildOwner.finalizeTree.<anonymous closure>
#27     BuildOwner.lockState
#28     BuildOwner.finalizeTree
#29     WidgetsBinding.drawFrame
#30     RendererBinding._handlePersistentFrameCallback
#31     SchedulerBinding._invokeFrameCallback
#32     SchedulerBinding.handleDrawFrame
#33     SchedulerBinding._handleDrawFrame
#37     _invoke (dart:ui/hooks.dart:166:10)
#38     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#39     _drawFrame (dart:ui/hooks.dart:129:31)
(elided 3 frames from dart:async)
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
A ScrollPositionWithSingleContext was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

```
</details>

**Comment by goderbauer** [comment]
This code looks fishy:

```dart
  @override
  void didChangeDependencies() {
    if (!initialized) {
      initialized = true;
      _position = Scrollable.of(context)!.position;
      _position.addListener(_onScroll);
    }
    super.didChangeDependencies();
  }
```

This should be:

```dart
  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    var newPosition = Scrollable.of(context)!.position;
    if (newPosition != _position) {
     _position?.removeListener(_onScroll);
     _position = newPosition;
     _position.addListener(_onScroll);
    }
  }
```

`Scrollable.of` creates a dependency on the Scrollable. Whenever its return value changes, `didChangeDependencies` is called again and its value has to be re-obtained. 

Let me know if changing it to that fixes the problem.

**Comment by caseycrogers** [comment]
Yeah that worked, thanks! It looks route is changing the position before disposing it so a call to `removeListener` here will run before it's disposed?
