### ISSUE TITLE
Keyboard freezes in app and throws exceptions when pressing Shift + <certain keys>

### ISSUE THREAD

**Issue by devtud** [flutter/flutter#89981]
## Steps to Reproduce

1. Create an app with TextField.
2. (With TextField focused or NOT - it doesn't matter) Press repeatedly and fast Shift + <one of: 1...9 | ?  etc>

**Expected results:** 
No exception is raised, keyboard works well, the text field can be normally edited.

**Actual results:** 
- An exception is raised at each key stroke
- Keyboard "freezes" and it's impossible to type anything in the text field.
 
<details>
  <summary>Logs</summary>

```
A KeyUpEvent is dispatched, but the state shows that the physical key is pressed on a different logical key. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#8e561(physicalKey: PhysicalKeyboardKey#70020(usbHidUsage: "0x00070020", debugName: "Digit 3"), logicalKey: LogicalKeyboardKey#00023(keyId: "0x00000023", keyLabel: "#", debugName: "Number Sign"), character: null, timeStamp: 8:22:29.137000) and the recorded logical key LogicalKeyboardKey#00033(keyId: "0x00000033", keyLabel: "3", debugName: "Digit 3")
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 444 pos 16: '_pressedKeys[event.physicalKey] == event.logicalKey'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:444:16)
#3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:452:6)
#4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:543:5)
#5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:821:35)
#6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:73:49)
#7      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:72:47)
#8      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:379:35)
#9      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:376:46)
#10     _invoke2.<anonymous closure> (dart:ui/hooks.dart:205:15)
#14     _invoke2 (dart:ui/hooks.dart:204:10)
#15     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#16     _Channel.push (dart:ui/channel_buffers.dart:132:31)
#17     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#18     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:544:22)
#19     _dispatchPlatformMessage (dart:ui/hooks.dart:92:31)
(elided 5 frames from class _AssertionError and dart:async)
====================================================================================================

```

```
$ flutter analyze
Analyzing app...                                                        
No issues found! (ran in 1.4s)
```

```
$ flutter doctor -v
[✓] Flutter (Channel stable, 2.5.0, on EndeavourOS 5.10.63-1-lts, locale en_US.UTF-8)
    • Flutter version 2.5.0 at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (5 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31)
    • Android SDK at /opt/android-sdk
    • Platform android-31, build-tools 31
    • ANDROID_HOME = /opt/android-sdk
    • ANDROID_SDK_ROOT = /opt/android-sdk
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 12.0.1
    • cmake version 3.21.2
    • ninja version 1.10.2
    • pkg-config version 1.7.3

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at /opt/intellij-idea-ultimate-edition
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • EndeavourOS 5.10.63-1-lts
    • Chrome (web)    • chrome • web-javascript • Chromium 93.0.4577.63 Arch Linux

! Doctor found issues in 1 category.

```

</details>

**Comment by maheshmnj** [comment]
Hi @devtud, Thanks for filing the issue. There seems to be a similar issue describing this case please follow up there for further updates.

Closing this issue as a duplicate, If you disagree feel free to  write in the comments and I will reopen it.

Thank you.
