### ISSUE TITLE
Opening Drawer with ListView throws: The provided ScrollController is currently attached to more than one ScrollPosition.

### ISSUE THREAD

**Issue by dotupNET** [flutter/flutter#89992]
This behavior is on mac devices with Flutter v2.5.0. v2.3.3 is working as expected.
There's no exception in iOS Simulator

## Steps to Reproduce

1. Clone https://github.com/dotupNET/flutter_refresh_indicator or 
2. Run on macos
3.  Open Drawer

**Expected results:** 
- No exception when opening drawer

**Actual results:**

Exception has occurred.
FlutterError (The provided ScrollController is currently attached to more than one ScrollPosition.
The Scrollbar requires a single ScrollPosition in order to be painted.
When the scrollbar is interactive, the associated Scrollable widgets must have unique ScrollControllers. The provided ScrollController must be unique to a Scrollable widget.)

```
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.5.1 20G80 darwin-arm, locale de-DE)
    • Flutter version 2.5.0 at /Users/peterullrich/data/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (5 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/peterullrich/Library/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/peterullrich/Library/Android/Sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.60.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.5.1 20G80 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 93.0.4577.63

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report. It seems to be a regression, specially on macOS, as the same works properly on 2.2.3.

1. On Stable 2.5.0 and on latest master, running macOS desktop, scrolling the listview and then tapping on Appdrawer throws below exception:

<details>
<summary>console error log</summary>



```
Launching lib/main.dart on macOS in debug mode...
Building macOS application...
Debug service listening on ws://127.0.0.1:52367/CQgXRozlKtQ=/ws
Syncing files to device macOS...

======== Exception caught by animation library =====================================================
The following assertion was thrown while notifying status listeners for AnimationController:
The provided ScrollController is currently attached to more than one ScrollPosition.

The Scrollbar requires a single ScrollPosition in order to be painted.

When the scrollbar is interactive, the associated Scrollable widgets must have unique ScrollControllers. The provided ScrollController must be unique to a Scrollable widget.

When the exception was thrown, this was the stack: 
#0      RawScrollbarState._debugCheckHasValidScrollPosition.<anonymous closure> (package:flutter/src/widgets/scrollbar.dart:1315:9)
#1      RawScrollbarState._debugCheckHasValidScrollPosition (package:flutter/src/widgets/scrollbar.dart:1339:6)
#2      RawScrollbarState._validateInteractions (package:flutter/src/widgets/scrollbar.dart:1257:14)
#3      AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:233:19)
#4      AnimationController._checkStatusChanged (package:flutter/src/animation/animation_controller.dart:814:7)
#5      AnimationController._startSimulation (package:flutter/src/animation/animation_controller.dart:748:5)
#6      AnimationController._animateToInternal (package:flutter/src/animation/animation_controller.dart:611:12)
#7      AnimationController.reverse (package:flutter/src/animation/animation_controller.dart:495:12)
#8      RawScrollbarState._maybeStartFadeoutTimer.<anonymous closure> (package:flutter/src/widgets/scrollbar.dart:1412:37)
(elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
The AnimationController notifying status listeners was: AnimationController#ff62b(◀ 1.000)
====================================================================================================
Application finished.



```


</details>

The same code and behavior works well on iOS simulator and iphone device on 2.5.0

Running the same code on Stable 2.2.3, works well on macOS desktop. 

<details>
<summary> stable, master flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.5.0, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.5.0 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (2 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 93.0.4577.63

• No issues found!

[✓] Flutter (Channel master, 2.6.0-6.0.pre.82, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.6.0-6.0.pre.82 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3b7adb989f (88 minutes ago), 2021-09-13 21:32:04 -0700
    • Engine revision abb1980f65
    • Dart version 2.15.0 (build 2.15.0-96.0.dev)

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.4 19E2269
      darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 93.0.4577.63

• No issues found!




```

</details>

**Comment by Piinks** [comment]
@dotupNET can you provide a minimal reproduction of your issue?  The repo you linked above contains multiple file with ~400 lines of code. Please see our [issue hygiene page](https://github.com/flutter/flutter/wiki/Issue-hygiene#provide-reduced-test-cases) in the wiki about providing issue reproductions.

**Comment by Piinks** [comment]
This appears to be expected behavior.

On desktop, a `Scrollbar` is automatically applied to scrollable content. This is why this error is not happening on iOS. 

Further, all vertical `ScrollViews`, when not provided a `ScrollController`, will attach to the `PrimaryScrollController`.
When the `Scrollbar` goes to draw itself, if its associated `ScrollView` has not been given a `ScrollController` (similarly) it looks up the `PrimaryScrollController`. In your case, it looks up the `PrimaryScrollController`, and finds more than one `ScrollPosition` attached. The `Scrollbar` cannot reflect more than one `ScrollPosition`, resulting in the error.

It looks like if you provide a `ScrollController` to one of your `ListView`s, there will be no error. Or you can disable the automatic desktop scrollbars using the guide linked below.

You can read more about this here:
- https://flutter.dev/docs/release/breaking-changes/default-desktop-scrollbars
- https://api.flutter.dev/flutter/widgets/PrimaryScrollController-class.html
- https://api.flutter.dev/flutter/material/Scrollbar-class.html
