### ISSUE TITLE
BottomNavigationBar error: '!_needsLayout' is not true

### ISSUE THREAD

**Issue by justinmc** [flutter/flutter#89995]
1. Run the given app below.  I'm using a physical iPhone 7 running iOS 14.7.
 2. Switch back and forth quickly between the different "pages".
 3. This error is usually logged for me within 10 seconds of switching pages.

```
Unhandled Exception: 'package:flutter/src/painting/text_painter.dart': Failed assertion: line 900 pos 12: '!_needsLayout': is not true.
```

<details>

<summary>Code</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _currentPage = 0;

  static const List<Widget> _pages = <Widget>[
    Page(title: 'one'),
    Page(title: 'two'),
    Page(title: 'three'),
  ];

  void _onTap(int index) {
    setState(() {
      _currentPage = index;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Switching Error Demo'),
      ),
      bottomNavigationBar: BottomNavigationBar(
        showSelectedLabels: false,
        showUnselectedLabels: false,
        selectedItemColor: Colors.white,
        backgroundColor: Theme.of(context).appBarTheme.backgroundColor,
        currentIndex: _currentPage,
        onTap: _onTap,
        items: const <BottomNavigationBarItem>[
          BottomNavigationBarItem(
            icon: Icon(Icons.account_balance, size: 28),
            label: 'one',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.android, size: 28),
            label: 'two',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.airline_seat_flat_rounded, size: 28),
            label: 'three',
          ),
        ],
      ),
      body: _pages[_currentPage],
    );
  }
}

class Page extends StatelessWidget {
  const Page({
    Key? key,
    required this.title,
  }) : super(key: key);

  final String title;

  @override
  Widget build(BuildContext context) {
    return Center(
      child: SizedBox(
        width: 150,
        child: Text(title),
      ),
    );
  }
}
```

</details>

<details>

<summary>Error logs</summary>

```
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: 'package:flutter/src/painting/text_painter.dart': Failed assertion: line 900 pos 12: '!_needsLayout': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:47:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      TextPainter.getPositionForOffset (package:flutter/src/painting/text_painter.dart:900:12)
#3      RenderParagraph.hitTestChildren (package:flutter/src/rendering/paragraph.dart:444:52)
#4      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2413:11)
#5      RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#6      RenderTransform.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/proxy_box.dart:2386:22)
#7      BoxHitTestResult.addWithRawTransform (package:flutter/src/rendering/box.dart:825:31)
#8      BoxHitTestResult.addWithPaintTransform (package:flutter/src/rendering/box.dart:750:12)
#9      RenderTransform.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:2382:19)
#10     RenderTransform.hitTest (package:flutter/src/rendering/proxy_box.dart:2376:12)
#11     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#12     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2413:11)
#13     RenderShiftedBox.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/shifted_box.dart:92:25)
#14     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:786:31)
#15     RenderShiftedBox.hitTestChildren (package:flutter/src/rendering/shifted_box.dart:87:21)
#16     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2413:11)
#17     RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2774:25)
#18     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:786:31)
#19     RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2769:33)
#20     RenderFlex.hitTestChildren (package:flutter/src/rendering/flex.dart:1072:12)
#21     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2413:11)
#22     RenderShiftedBox.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/shifted_box.dart:92:25)
#23     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:786:31)
#24     RenderShiftedBox.hitTestChildren (package:flutter/src/rendering/shifted_box.dart:87:21)
#25     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2413:11)
#26     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#27     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:178:19)
#28     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#29     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2413:11)
#30     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#31     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2413:11)
#32     RenderMouseRegion.hitTest (package:flutter/src/rendering/proxy_box.dart:2958:18)
#33     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#34     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2413:11)
#35     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#36     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2413:11)
#37     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#38     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:178:19)
#39     RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2774:25)
#40     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:786:31)
#41     RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2769:33)
#42     RenderStack.hitTestChildren (package:flutter/src/rendering/stack.dart:620:12)
#43     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2413:11)
#44     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#45     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2413:11)
#46     RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2774:25)
#47     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:786:31)
#48     RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2769:33)
#49     RenderFlex.hitTestChildren (package:flutter/src/rendering/flex.dart:1072:12)
#50     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2413:11)
#51     RenderShiftedBox.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/shifted_box.dart:92:25)
#52     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:786:31)
#53     RenderShiftedBox.hitTestChildren (package:flutter/src/rendering/shifted_box.dart:87:21)
#54     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2413:11)
#55     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#56     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2413:11)
#57     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#58     RenderCustomPaint.hitTestChildren (package:flutter/src/rendering/custom_paint.dart:535:18)
#59     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2413:11)
#60     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#61     RenderCustomPaint.hitTestChildren (package:flutter/src/rendering/custom_paint.dart:535:18)
#62     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2413:11)
#63     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#64     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2413:11)
#65     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#66     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2413:11)
#67     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#68     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2413:11)
#69     RenderPhysicalModel.hitTest (package:flutter/src/rendering/proxy_box.dart:1908:18)
#70     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#71     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2413:11)
#72     RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2774:25)
#73     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:786:31)
#74     RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2769:33)
#75     RenderCustomMultiChildLayoutBox.hitTestChildren (package:flutter/src/rendering/custom_layout.dart:414:12)
#76     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2413:11)
#77     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#78     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2413:11)
#79     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#80     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2413:11)
#81     RenderPhysicalModel.hitTest (package:flutter/src/rendering/proxy_box.dart:1908:18)
#82     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#83     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2413:11)
#84     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#85     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2413:11)
#86     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#87     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2413:11)
#88     RenderIgnorePointer.hitTest (package:flutter/src/rendering/proxy_box.dart:3309:31)
#89     RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2774:25)
#90     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:786:31)
#91     RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2769:33)
#92     RenderStack.hitTestChildren (package:flutter/src/rendering/stack.dart:620:12)
#93     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2413:11)
#94     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#95     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2413:11)
#96     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#97     RenderFractionalTranslation.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/proxy_box.dart:2767:22)
#98     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:786:31)
#99     RenderFractionalTranslation.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:2761:19)
#100    RenderFractionalTranslation.hitTest (package:flutter/src/rendering/proxy_box.dart:2747:12)
#101    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#102    RenderFractionalTranslation.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/proxy_box.dart:2767:22)
#103    BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:786:31)
#104    RenderFractionalTranslation.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:2761:19)
#105    RenderFractionalTranslation.hitTest (package:flutter/src/rendering/proxy_box.dart:2747:12)
#106    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#107    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2413:11)
#108    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#109    _RenderFocusTrap.hitTest (package:flutter/src/widgets/routes.dart:2132:19)
#110    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#111    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2413:11)
#112    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#113    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2413:11)
#114    RenderOffstage.hitTest (package:flutter/src/rendering/proxy_box.dart:3428:31)
#115    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#116    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2413:11)
#117    _RenderTheatre.hitTestChildren.<anonymous closure> (package:flutter/src/widgets/overlay.dart:773:25)
#118    BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:786:31)
#119    _RenderTheatre.hitTestChildren (package:flutter/src/widgets/overlay.dart:768:33)
#120    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2413:11)
#121    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#122    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2413:11)
#123    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#124    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2413:11)
#125    RenderAbsorbPointer.hitTest (package:flutter/src/rendering/proxy_box.dart:3526:17)
#126    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#127    RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:178:19)
#128    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#129    RenderCustomPaint.hitTestChildren (package:flutter/src/rendering/custom_paint.dart:535:18)
#130    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2413:11)
#131    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#132    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2413:11)
#133    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#134    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2413:11)
#135    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#136    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2413:11)
#137    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#138    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2413:11)
#139    RenderView.hitTest (package:flutter/src/rendering/view.dart:185:14)
#140    RendererBinding.hitTest (package:flutter/src/rendering/binding.dart:483:16)
#141    GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:346:7)
#142    GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
#143    GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#144    GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#145    _rootRunUnary (dart:async/zone.dart:1444:13)
#146    _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#147    _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#148    _invoke1 (dart:ui/hooks.dart:185:10)
#149    PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
#150    _dispatchPointerDataPacket (dart:ui/hooks.dart:98:31)
```

</details>

### Related

This might be related to causing an app to freeze on iOS in https://github.com/openfoodfacts/smooth-app/issues/483.

<details>

<summary>flutter doctor</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 2.6.0-6.0.pre.56, on macOS 11.5.2 20G95 darwin-x64, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 12.5)
[✓] Chrome - develop for the web
[!] Android Studio
    ✗ Unable to find bundled Java version.
[✓] VS Code (version 1.59.1)
[✓] Connected device (3 available)

! Doctor found issues in 2 categories.
```

<details>

**Comment by LongCatIsLooong** [comment]
This looks like a duplicate of https://github.com/flutter/flutter/issues/85108?

**Comment by darshankawar** [comment]
Hi @justinmc 
Tried the code sample using iPhone 6s (OS 14.4.1) on latest stable and master but didn't see the exception.

<details>
<summary> stable, master flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.5.0, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.5.0 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (2 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 93.0.4577.63

• No issues found!

[✓] Flutter (Channel master, 2.6.0-6.0.pre.82, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.6.0-6.0.pre.82 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3b7adb989f (88 minutes ago), 2021-09-13 21:32:04 -0700
    • Engine revision abb1980f65
    • Dart version 2.15.0 (build 2.15.0-96.0.dev)

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.4 19E2269
      darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 93.0.4577.63

• No issues found!




```

</details>

Maybe on master it's fixed with 85108 ?

**Comment by justinmc** [comment]
I tried again on the latest master and it seems to be fixed, thanks!
