### ISSUE TITLE
[cocoon] APIs: file flaky issue and PR & deflaky flaky builders fail

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#90019]
Both `/api/file_flaky_issue_and_pr` and `/api/deflake_flaky_builders` fail with follow error. Could you help take a look @chunhtai ?

```
Invalid argument(s) (input): Must not be null
#0      _RegExp.firstMatch (dart:core-patch/regexp_patch.dart:221:24)
#1      retrieveMetaTagsFromContent (package:cocoon_service/src/request_handlers/flaky_handler_utils.dart:442:55)
#2      getExistingPRs (package:cocoon_service/src/request_handlers/flaky_handler_utils.dart:231:43)
<asynchronous suspension>
#3      FileFlakyIssueAndPR.get (package:cocoon_service/src/request_handlers/file_flaky_issue_and_pr.dart:43:55)
<asynchronous suspension>
#4      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:46:22)
<asynchronous suspension>
#5      ApiRequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/api_request_handler.dart:150:7)
<asynchronous suspension>
#6      ApiRequestHandler.service (package:cocoon_service/src/request_handling/api_request_handler.dart:149:5)
<asynchronous suspension>
#7      main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:252:9)
```

**Comment by chunhtai** [comment]
It looks like some PR may have malformed meta tag, need to run locally to find out the root cause.
blocked on https://github.com/flutter/flutter/issues/90402

**Comment by keyonghan** [comment]
Security issue has been more and more important, and that's why we have cleaned up most keys and service accounts. The `flutter-devicelab` is one of them. Do you think we can add more logs to cocoon rather than running locally which is connecting to the prod data? The long term fix is to have a staging/dev version of cocoon.

**Comment by chunhtai** [comment]
sounds good to me

**Comment by keyonghan** [comment]
These APIs hit null safety issues:
```
type 'Null' is not a subtype of type 'Object' in type cast
#0      new TableCell.fromJson (package:googleapis/bigquery/v2.dart:11018:50)
#1      new TableRow.fromJson.<anonymous closure> (package:googleapis/bigquery/v2.dart:11704:56)
#2      MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
#3      ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
#4      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:188:27)
#5      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#6      new List.of (dart:core-patch/array_patch.dart:51:28)
#7      ListIterable.toList (dart:_internal/iterable.dart:213:44)
#8      new TableRow.fromJson (package:googleapis/bigquery/v2.dart:11706:20)
#9      new QueryResponse.fromJson.<anonymous closure> (package:googleapis/bigquery/v2.dart:9588:54)
#10     MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
#11     ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
#12     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:188:27)
#13     new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#14     new List.of (dart:core-patch/array_patch.dart:51:28)
#15     ListIterable.toList (dart:_internal/iterable.dart:213:44)
#16     new QueryResponse.fromJson (package:googleapis/bigquery/v2.dart:9590:20)
#17     JobsResource.query (package:googleapis/bigquery/v2.dart:796:26)
<asynchronous suspension>
#18     BigqueryService.listBuilderStatistic (package:cocoon_service/src/service/bigquery.dart:86:36)
<asynchronous suspension>
#19     FileFlakyIssueAndPR.get (package:cocoon_service/src/request_handlers/file_flaky_issue_and_pr.dart:39:57)
```

**Comment by keyonghan** [comment]
Created https://github.com/google/googleapis.dart/issues/306 to track upstream fix.

**Comment by kevmoo** [comment]
@keyonghan – fixed upstream problem. Trying to figure out what the next release will be!

**Comment by keyonghan** [comment]
Seems we need to update `gcloud` to point to the latest googleapis version:
```
Because no versions of gcloud match >0.8.3 <0.9.0 and gcloud >=0.8.0 <0.8.3 depends on googleapis ^3.0.0, gcloud >=0.8.0 <0.8.3-∞ or >0.8.3 <0.9.0 requires googleapis ^3.0.0.
And because gcloud 0.8.3 depends on googleapis >=3.0.0 <6.0.0, gcloud ^0.8.0 requires googleapis >=3.0.0 <6.0.0.
So, because cocoon_service depends on both gcloud ^0.8.2 and googleapis ^6.0.0, version solving failed.
```

I created https://github.com/dart-lang/gcloud/pull/128. PTAL. I am not sure how the workflow is to push a new version of gcloud to pub.dev. Please advise what else is needed here. Thanks!

**Comment by keyonghan** [comment]
The bot should ignore PRs with empty message body:
```
Unable to parse body of https://github.com/flutter/flutter/pull/91789
Null check operator used on a null value
#0      getExistingPRs (package:cocoon_service/src/request_handlers/flaky_handler_utils.dart:235:7)
<asynchronous suspension>
#1      DeflakeFlakyBuilders._getEligibleFlakyBuilders (package:cocoon_service/src/request_handlers/deflake_flaky_builders.dart:84:57)
<asynchronous suspension>
#2      DeflakeFlakyBuilders.get (package:cocoon_service/src/request_handlers/deflake_flaky_builders.dart:54:49)
<asynchronous suspension>
```
