### ISSUE TITLE
[tool_crash] FileSystemException: Creation failed, OS Error: A file cannot be created if it already exists., errno = 183

### ISSUE THREAD

**Issue by jimbo-jones1313** [flutter/flutter#90028]
[flutter_01.log](https://github.com/flutter/flutter/files/7159437/flutter_01.log)

**Comment by darshankawar** [comment]
A similar / related issue is: https://github.com/flutter/flutter/issues/74227

**Comment by jimbo-jones1313** [comment]
Update: after playing around with the Visual Studio packages, the dependencies were finally cleared up (thank you!), but now I'm back to the previous error (just some of the details have changed):

> Flutter could not download and/or extract https://storage.googleapis.com/flutter_infra_release/flutter/d5adde01dd672ba4f6819d85218beb01142dca27/flutter-web-sdk-windows-x64.zip. Ensure you have network connectivity and all of the required dependencies listed at flutter.dev/setup.
> The original exception was: FileSystemException: Creation failed, path = 'H:\flutter\bin\cache\flutter_web_sdk\flutter_web_sdk/lib/ui/src/ui' (OS Error: Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist.
> , errno = 183).

I have tried deleting the 'flutter\bin\cache\flutter_web_sdk\flutter_web_sdk' folder (the last one in the hierarchy), and get various error messages.
Repeating the "run" without any deletions just got me this:

> Flutter failed to check for directory existence at "H:\flutter\bin\cache\flutter_web_sdk". The flutter tool cannot access the file or directory.
> Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current user
[flutter_06.log](https://github.com/flutter/flutter/files/7183903/flutter_06.log)
[flutter_05.log](https://github.com/flutter/flutter/files/7183904/flutter_05.log)
.

**Comment by DavidOrakpo** [comment]
May 2023, this issue has still not been solved sigh

**Comment by huycozy** [comment]
Leaving information from duplicate issue https://github.com/flutter/flutter/issues/131978 on new Flutter version for better tracking (the stack trace from OP is on a file, so it's not convenient to quickly capture information)

On stable/3.10.6 with command: `flutter build windows`

```
FileSystemException: Cannot create link, OS Error: No se puede crear un archivo que ya existe.
, errno = 183

#0      _Link.throwIfError (dart:io/link.dart:254:7)
#1      _Link.createSync (dart:io/link.dart:182:5)
#2      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#3      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#4      _createPlatformPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:1055:12)
#5      createPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:985:5)
#6      buildWindows (package:flutter_tools/src/windows/build_windows.dart:64:3)
#7      BuildWindowsCommand.runCommand (package:flutter_tools/src/commands/build_windows.dart:56:11)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
<asynchronous suspension>
#14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```

**Comment by milindgoel15** [comment]
Any temporary workaround for this issue?

**Comment by robinmonsere** [comment]
Any updates on this? Getting the same exact error with ` flutter run -d windows -v`

**Comment by arjunthakur4933** [comment]
hey, I had the same error today, in android studio => 1. flutter clean 2. fluuter pub get, this may solve the issue if this doesnt help 3. flutter pub upgrade

**Comment by Buzhifanji** [comment]
I had the same error today, in window 10.

I get the error info with `flutter run -d windows -v`

`[+9009 ms] Error: Building with plugins requires symlink support.

                    Please enable Developer Mode in your system settings. Run
                      start ms-settings:developers
                    to open settings.
[   +9 ms] "flutter run" took 10,714ms.
[   +4 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:811:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1389:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:355:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:295:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:119:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>`

I solved it by doing this

[Go to system settings, click Update and Security, click For Developers ->Developer Mode -> Enable Install apps from any source, including loose files.](https://stackoverflow.com/questions/68089177/flutter-building-with-plugins-requires-symlink-support)

**Comment by iulian0512** [comment]
> May 2023, this issue has still not been solved sigh

June 2025 still not fixed

**Comment by loic-sharma** [comment]
Redirecting this back to the tool team. One comment indicates this problem can happen when downloading artifacts ([link](https://github.com/flutter/flutter/issues/90028#issuecomment-921601655)), another comment indicates this problem can happen when using Android Studio ([here](https://github.com/flutter/flutter/issues/90028#issuecomment-1949788474)), which is rarely used to build Windows app. I suspect this problem affects all Flutter targets if the host machine is on Windows.

For folks hitting this issue, please upvote 👍 the issue itself. This will help us prioritize. Thanks!

**Comment by anders-au** [comment]
I had a variant of this error occur in Windows VS Code due to a downloaded asset file that was marked as Read Only by Windows. This meant it was able to be copied to the build once, but flutter subsequently was not able to delete and replace it when rebuilding. Unchecking the Read Only property on any problem files in Windows Explorer fixed my issue.

`Target debug_android_application failed: PathExistsException: Cannot copy file to 'C:build/dir/path.ext', path = 'C:\path\to\problem\asset.ext' (OS Error: Cannot create a file when that file already exists.`

<img width="508" height="286" alt="Image" src="https://github.com/user-attachments/assets/e85b096a-8202-4f00-8229-40bdfc9af729" />
