### ISSUE TITLE
[web] browser back button throws `Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/navigation/history.dart:311:14`

### ISSUE THREAD

**Issue by mathiuleo** [flutter/flutter#90031]
Hello,

I got this error on Flutter 2.5 and it only happen for web when i click back button from browser after hot restart.
I am using Navigator 2.0
Before i am using Flutter 2.2.2 and there are no error.

```
Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/navigation/history.dart:311:14
_userProvidedRouteName != null
is not true
    at Object.throw_ [as throw] (http://localhost:62292/dart_sdk.js:5061:11)
    at Object.assertFailed (http://localhost:62292/dart_sdk.js:4986:15)
    at _engine.SingleEntryBrowserHistory.new.onPopState (http://localhost:62292/dart_sdk.js:159565:59)
```

Below is spec :
```
$ flutter doctor -v
[√] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.19042.1165], locale en-ID)
    • Flutter version 2.5.0 at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (6 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.59.0)
    • VS Code at C:\Users\Mathiu\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 93.0.4577.63
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 93.0.961.44

! Doctor found issues in 1 category.
```

Thank you and best regards

**Comment by danagbemava-nc** [comment]
Hi @mathiuleo, thanks for filing the issue. 

Can you please provide you flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Thank you

**Comment by mathiuleo** [comment]
Hello @danagbemava-nc ,

Thank you for your response and thank you for your help. Much appreciated.

Below is the minimal code sample :
**main.dart**
```
import 'dart:ui';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_error/page2.dart';

void main() {
  // this function makes application always run in portrait mode
  WidgetsFlutterBinding.ensureInitialized();
  SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp])
      .then((_) {
    runApp(MyApp());
  });
}

class MyCustomScrollBehavior extends MaterialScrollBehavior {
  // Override behavior methods and getters like dragDevices
  @override
  Set<PointerDeviceKind> get dragDevices => {
        PointerDeviceKind.touch,
        PointerDeviceKind.mouse,
        // etc.
      };
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      scrollBehavior: MyCustomScrollBehavior(),
      title: 'Main Page',
      home: MyHome(),
    );
  }
}

class MyHome extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
            title: Text('Main Page')
        ),
        body: Container(
          child: Center(
            child: TextButton(
              child: Text('Go to page 2'),
              onPressed: () {
                Navigator.push(context, MaterialPageRoute(builder: (context) => Page2()));
              },
            ),
          ),
        )
    );
  }
}
```

**page2.dart**
```
import 'package:flutter/material.dart';

class Page2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        backgroundColor: Colors.white,
        appBar: AppBar(
            title: Text('Page 2')
        ),
        body: Container(
          child: Center(
            child: Text('Page 2'),
          ),
        )
    );
  }
}
```

And then i write command "**flutter run -d chrome --verbose**" on the terminal and i do hot restart by pressing "**r**".
After i do a hot restart, then the back button on the browser can be clicked. And i click back button on the browser, not back button on the AppBar because sometimes i don't use AppBar on my Flutter Application.

below is the full result :
```
D:\FlutterProjects\flutter_error>flutter run -d chrome --verbose
[  +67 ms] executing: [D:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +426 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 4cc385b4b84ac2f816d939a49ea1f328c4e0b48e
[   +1 ms] executing: [D:\flutter/] git tag --points-at 4cc385b4b84ac2f816d939a49ea1f328c4e0b48e
[  +61 ms] Exit code 0 from: git tag --points-at 4cc385b4b84ac2f816d939a49ea1f328c4e0b48e
[        ] 2.5.0
[   +9 ms] executing: [D:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +35 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [D:\flutter/] git ls-remote --get-url origin
[  +31 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +111 ms] executing: [D:\flutter/] git rev-parse --abbrev-ref HEAD
[  +34 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[  +68 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +86 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +68 ms] Skipping pub get: version match.
[ +106 ms] Generating D:\FlutterProjects\flutter_error\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +111 ms] Launching lib\main.dart on Chrome in debug mode...
[ +108 ms] Updating assets
[  +64 ms] Waiting for connection from debug service on Chrome...
[  +87 ms] <- reset
[  +10 ms] D:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev D:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root D:\flutter\bin\cache\flutter_web_sdk/
--incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
C:\Users\Hendra\AppData\Local\Temp\flutter_tools.80359ec0\flutter_tool.779a475d\app.dill --libraries-spec file:///D:/flutter/bin/cache/flutter_web_sdk/libraries.json --packages
D:\FlutterProjects\flutter_error\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root
C:\Users\Hendra\AppData\Local\Temp\flutter_tools.80359ec0\flutter_tools.f3f91ddc --filesystem-scheme org-dartlang-app --initialize-from-dill build\b1b715402d823b7fd5c2b68d2edcb2ce.cache.dill.track.dill
--platform file:///D:/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk_sound.dill --sound-null-safety
[  +11 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+13673 ms] Waiting for connection from debug service on Chrome... (completed in 13.8s)
[   +2 ms] Synced 26.2MB.
[   +1 ms] <- accept
[        ] Caching compiled dill
[ +366 ms] [CHROME]:
[   +1 ms] [CHROME]:DevTools listening on ws://127.0.0.1:51065/devtools/browser/79fb406d-c28a-4b76-b55c-17188d1ee883
[ +499 ms] DwdsInjector: Received request for entrypoint at http://localhost:51012/main_module.bootstrap.js
[   +7 ms] MetadataProvider: Loading debug metadata...
[  +12 ms] MetadataProvider: Loaded debug metadata (sound null safety)
[   +6 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:51012/main_module.bootstrap.js
[+1826 ms] ChromeProxyService: Initializing expression compiler for main_module.bootstrap.js with sound null safety: true
[  +56 ms] DevHandler: Debug service listening on ws://127.0.0.1:53619/pFOTIf6h-nM=/ws

[  +20 ms] This app is linked to the debug service: ws://127.0.0.1:53619/pFOTIf6h-nM=/ws
[   +8 ms] Debug service listening on ws://127.0.0.1:53619/pFOTIf6h-nM=/ws
[   +1 ms]  Running with sound null safety 
[   +3 ms]   To hot restart changes while running, press "r" or "R".
[        ] For a more detailed help message, press "h". To quit, press "q".
[   +2 ms] An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:53619/pFOTIf6h-nM=
[ +519 ms] DevTools activation throttled until 2021-09-16 22:56:59.512663.
[+1135 ms] The Flutter DevTools debugger and profiler on Chrome is available at: http://127.0.0.1:9104?uri=http://127.0.0.1:53619/pFOTIf6h-nM=
[+5481 ms] Performing hot restart...
[   +3 ms] Initializing file store
[   +8 ms] Skipping target: gen_localizations
[   +3 ms] Skipping target: gen_dart_plugin_registrant
[   +1 ms] Skipping target: _composite
[   +2 ms] complete
[  +29 ms] Scanned through 523 files in 28ms
[   +1 ms] Waiting for connection from debug service on Chrome...
[   +1 ms] <- recompile org-dartlang-app:/web_entrypoint.dart 8229da02-cf3f-44ff-bc5d-538f01e50d3a
[        ] <- 8229da02-cf3f-44ff-bc5d-538f01e50d3a
[  +14 ms] Waiting for connection from debug service on Chrome... (completed in 15ms)
[   +1 ms] Synced 0.0MB.
[        ] <- accept
[   +3 ms] DwdsVmClient: Attempting a hot restart
[   +1 ms] DwdsVmClient: Attempting to disable breakpoints and resume the isolate
[ +852 ms] DwdsVmClient: Successfully disabled breakpoints and resumed the isolate
[   +1 ms] DwdsVmClient: Attempting to get execution context ID.
[        ] DwdsVmClient: Got execution context ID.
[        ] DwdsVmClient: Issuing $dartHotRestart request.
[  +32 ms] ChromeProxyService: Initializing expression compiler for main_module.bootstrap.js with sound null safety: true
[  +20 ms] DwdsVmClient: $dartHotRestart request complete.
[   +1 ms] DwdsVmClient: Waiting for Isolate Start event.
[   +2 ms] DwdsVmClient: Successful hot restart
[   +7 ms] Performing hot restart... (completed in 993ms)
[   +1 ms] Restarted application in 996ms.
[+26396 ms] Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/navigation/history.dart:311:14
                     _userProvidedRouteName != null
                     is not true
                         at Object.throw_ [as throw] (http://localhost:51012/dart_sdk.js:5061:11)
                         at Object.assertFailed (http://localhost:51012/dart_sdk.js:4986:15)
                         at _engine.SingleEntryBrowserHistory.new.onPopState (http://localhost:51012/dart_sdk.js:159565:59)
[  +10 ms] Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/navigation/history.dart:266:12
           _isOriginEntry(state)
           is not true
               at Object.throw_ [as throw] (http://localhost:51012/dart_sdk.js:5061:11)
               at Object.assertFailed (http://localhost:51012/dart_sdk.js:4986:15)
               at _engine.SingleEntryBrowserHistory.new.[_unwrapOriginState] (http://localhost:51012/dart_sdk.js:159541:74)
               at _engine.SingleEntryBrowserHistory.new.tearDown (http://localhost:51012/dart_sdk.js:159598:79)
               at tearDown.next (<anonymous>)
               at http://localhost:51012/dart_sdk.js:38640:33
               at _RootZone.runUnary (http://localhost:51012/dart_sdk.js:38511:59)
               at _FutureListener.thenAwait.handleValue (http://localhost:51012/dart_sdk.js:33713:29)
               at handleValueCallback (http://localhost:51012/dart_sdk.js:34265:49)
               at Function._propagateToListeners (http://localhost:51012/dart_sdk.js:34303:17)
               at _Future.new.[_completeWithValue] (http://localhost:51012/dart_sdk.js:34151:23)
               at async._AsyncCallbackEntry.new.callback (http://localhost:51012/dart_sdk.js:34172:35)
               at Object._microtaskLoop (http://localhost:51012/dart_sdk.js:38778:13)
               at _startMicrotaskLoop (http://localhost:51012/dart_sdk.js:38784:13)
               at http://localhost:51012/dart_sdk.js:34519:9
```

![backbutton](https://user-images.githubusercontent.com/90678226/133548796-4cfc8c96-d000-40aa-9426-79339c4b9e0b.jpg)


Thank you and best regards

**Comment by danagbemava-nc** [comment]
Issue is reproducible on `stable 2.5.0` and `master` but not on `stable 2.2.3`. 

To reproduce, run `flutter run -v -d chrome`.
After the browser opens, hit `r` in the cmd/terminal until the `forward` and `back` browser buttons are enabled. Then go to page 2 and use the browser `back` button to go back to the home screen.


<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel master, 2.6.0-6.0.pre.114, on macOS 11.5.1 20G80
    darwin-arm, locale en-GB)
    • Flutter version 2.6.0-6.0.pre.114 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd1892f04f (2 hours ago), 2021-09-15 22:17:02 -0700
    • Engine revision 5a09f16031
    • Dart version 2.15.0 (build 2.15.0-110.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.60.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (4 available)
    • M2007J20CG (mobile)    • 5dd3be00                  • android-arm64  •
      Android 11 (API 30)
    • Nexus’ IPhone (mobile) • 00008020-001875E83A38002E • ios            • iOS
      14.7.1 18G82
    • macOS (desktop)        • macos                     • darwin-arm64   •
      macOS 11.5.1 20G80 darwin-arm
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 93.0.4577.82

• No issues found!
```

```console
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.5.1 20G80 darwin-arm, locale
    en-GB)
    • Flutter version 2.5.0 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (8 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.60.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (4 available)
    • M2007J20CG (mobile)    • 5dd3be00                  • android-arm64  •
      Android 11 (API 30)
    • Nexus’ IPhone (mobile) • 00008020-001875E83A38002E • ios            • iOS
      14.7.1 18G82
    • macOS (desktop)        • macos                     • darwin-arm64   •
      macOS 11.5.1 20G80 darwin-arm
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 93.0.4577.82

• No issues found!
```
</details>

[log.txt](https://github.com/flutter/flutter/files/7175857/log.txt)

**Comment by yjbanov** [comment]
I'm wondering if it has to do with the fact that we erase all program state during a hot restart.

/cc @mdebbar
