### ISSUE TITLE
Flutter Doctor Dart null check error in Android Toolchain check

### ISSUE THREAD

**Issue by ben-milanko** [flutter/flutter#90042]
## Steps to Reproduce

1. Updated to flutter 2.5
2. Re-installed cmdline-tools from Android Studio

## Logs

<details>
<summary>Logs</summary>

```
[☠] Android toolchain - develop for Android devices (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ Null check operator used on a null value
    • #0      AndroidValidator.validate (package:flutter_tools/src/android/android_workflow.dart:205:40)
      #1      GroupedValidator.validate.<anonymous closure> (package:flutter_tools/src/doctor_validator.dart:87:56)
      #2      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #3      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #4      _rootRun (dart:async/zone.dart:1428:13)
      #5      _CustomZone.run (dart:async/zone.dart:1328:19)
      #6      _runZoned (dart:async/zone.dart:1863:10)
      #7      runZonedGuarded (dart:async/zone.dart:1851:12)
      #8      runZoned (dart:async/zone.dart:1782:12)
      #9      asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #10     GroupedValidator.validate (package:flutter_tools/src/doctor_validator.dart:87:11)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #12     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #13     _rootRun (dart:async/zone.dart:1428:13)
      #14     _CustomZone.run (dart:async/zone.dart:1328:19)
      #15     _runZoned (dart:async/zone.dart:1863:10)
      #16     runZonedGuarded (dart:async/zone.dart:1851:12)
      #17     runZoned (dart:async/zone.dart:1782:12)
      #18     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #19     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:200:9)
      #20     Doctor.diagnose (package:flutter_tools/src/doctor.dart:304:47)
      #21     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:47)
      #22     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1274:12)
      <asynchronous suspension>
      #23     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
      <asynchronous suspension>
      #24     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #25     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #26     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
      <asynchronous suspension>
      #27     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #28     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
      <asynchronous suspension>
      #29     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #31     main (package:flutter_tools/executable.dart:92:3)
      <asynchronous suspension>
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.0, on Ubuntu 20.04.3 LTS 5.10.0-1045-oem, locale en_AU.UTF-8)
[☠] Android toolchain - develop for Android devices (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ Null check operator used on a null value
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 4.1)
[✓] VS Code
[✓] Connected device (4 available)

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment]
@ben-milanko 
Can you provide output of `flutter doctor -vv`?

**Comment by ben-milanko** [comment]
Here's the verbose output:
<details>

```
[  +68 ms] executing: uname -m
[  +33 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +6 ms] executing: [/home/ben/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +7 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 4cc385b4b84ac2f816d939a49ea1f328c4e0b48e
[        ] executing: [/home/ben/snap/flutter/common/flutter/] git tag --points-at 4cc385b4b84ac2f816d939a49ea1f328c4e0b48e
[  +14 ms] Exit code 0 from: git tag --points-at 4cc385b4b84ac2f816d939a49ea1f328c4e0b48e
[        ] 2.5.0
[  +14 ms] executing: [/home/ben/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/ben/snap/flutter/common/flutter/] git ls-remote --get-url origin
[   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +43 ms] Waiting to be able to obtain lock of Flutter binary artifacts directory: /home/ben/snap/flutter/common/flutter/bin/cache/lockfile
[        ] Waiting for another flutter command to release the startup lock...
[+14451 ms] executing: [/home/ben/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +62 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +65 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +21 ms] executing: [/home/ben/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[        ] Skipping request to fetchTags - on well known channel stable.
[        ] executing: [/home/ben/snap/flutter/common/flutter/] git tag --points-at HEAD
[  +15 ms] Exit code 0 from: git tag --points-at HEAD
[        ] 2.5.0
[   +4 ms] executing: /home/ben/development/android-studio/jre/bin/java -version
[  +59 ms] Exit code 0 from: /home/ben/development/android-studio/jre/bin/java -version
[        ] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
           OpenJDK 64-Bit Server VM (build 25.242-b3-6222593, mixed mode)
[  +14 ms] executing: /home/ben/development/android-studio/jre/bin/java -version
[  +49 ms] Exit code 0 from: /home/ben/development/android-studio/jre/bin/java -version
[        ] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
           OpenJDK 64-Bit Server VM (build 25.242-b3-6222593, mixed mode)
[  +21 ms] executing: [/home/ben/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%ar
[   +7 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%ar
[        ] 6 days ago
[ +194 ms] executing: /usr/lib/android-sdk/platform-tools/adb devices -l
[  +31 ms] [✓] Flutter (Channel stable, 2.5.0, on Ubuntu 20.04.3 LTS 5.10.0-1045-oem, locale en_AU.UTF-8)
[   +1 ms]     • Flutter version 2.5.0 at /home/ben/snap/flutter/common/flutter
[        ]     • Upstream repository https://github.com/flutter/flutter.git
[        ]     • Framework revision 4cc385b4b8 (6 days ago), 2021-09-07 23:01:49 -0700
[        ]     • Engine revision f0826da7ef
[        ]     • Dart version 2.14.0
[   +2 ms] [☠] Android toolchain - develop for Android devices (the doctor check crashed)
[        ]     ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
[   +3 ms]     ✗ Null check operator used on a null value
[        ]     • #0      AndroidValidator.validate (package:flutter_tools/src/android/android_workflow.dart:205:40)
[        ]       #1      GroupedValidator.validate.<anonymous closure> (package:flutter_tools/src/doctor_validator.dart:87:56)
[        ]       #2      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
[        ]       #3      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
[        ]       #4      _rootRun (dart:async/zone.dart:1428:13)
[        ]       #5      _CustomZone.run (dart:async/zone.dart:1328:19)
[        ]       #6      _runZoned (dart:async/zone.dart:1863:10)
[        ]       #7      runZonedGuarded (dart:async/zone.dart:1851:12)
[        ]       #8      runZoned (dart:async/zone.dart:1782:12)
[        ]       #9      asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
[        ]       #10     GroupedValidator.validate (package:flutter_tools/src/doctor_validator.dart:87:11)
[        ]       #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
[        ]       #12     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
[        ]       #13     _rootRun (dart:async/zone.dart:1428:13)
[        ]       #14     _CustomZone.run (dart:async/zone.dart:1328:19)
[        ]       #15     _runZoned (dart:async/zone.dart:1863:10)
[        ]       #16     runZonedGuarded (dart:async/zone.dart:1851:12)
[        ]       #17     runZoned (dart:async/zone.dart:1782:12)
[        ]       #18     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
[        ]       #19     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:200:9)
[        ]       #20     Doctor.diagnose (package:flutter_tools/src/doctor.dart:304:47)
[        ]       #21     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:47)
[        ]       #22     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1274:12)
[        ]       <asynchronous suspension>
[        ]       #23     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
[        ]       <asynchronous suspension>
[        ]       #24     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]       <asynchronous suspension>
[        ]       #25     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
[        ]       <asynchronous suspension>
[        ]       #26     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
[        ]       <asynchronous suspension>
[        ]       #27     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]       <asynchronous suspension>
[        ]       #28     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
[        ]       <asynchronous suspension>
[        ]       #29     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
[        ]       <asynchronous suspension>
[        ]       #30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]       <asynchronous suspension>
[        ]       #31     main (package:flutter_tools/executable.dart:92:3)
[        ]       <asynchronous suspension>
[        ] [✓] Chrome - develop for the web
[        ]     • Chrome at google-chrome
[  +51 ms] List of devices attached
           3a89e8b6               device usb:3-5.4 product:gts210veltedx model:SM_T819Y device:gts210velte transport_id:1
[  +12 ms] /usr/lib/android-sdk/platform-tools/adb -s 3a89e8b6 shell getprop
[  +79 ms] [✓] Linux toolchain - develop for Linux desktop
[        ]     • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
[        ]     • cmake version 3.10.2
[        ]     • ninja version 1.8.2
[        ]     • pkg-config version 0.29.1
[   +1 ms] [✓] Android Studio (version 4.1)
[        ]     • Android Studio at /home/ben/development/android-studio
[        ]     • Flutter plugin version 52.1.1
[        ]     • Dart plugin version 201.9317
[        ]     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
[        ] [✓] VS Code
[        ]     • VS Code at /snap/code/current
[        ]     • Flutter extension version 3.26.0
[  +35 ms] ro.hardware = qcom
[  +69 ms] executing: /usr/lib/android-sdk/platform-tools/adb devices -l
[  +12 ms] List of devices attached
           3a89e8b6               device usb:3-5.4 product:gts210veltedx model:SM_T819Y device:gts210velte transport_id:1
[   +3 ms] [✓] Connected device (3 available)
[        ]     • SM T819Y (mobile) • 3a89e8b6 • android-arm64  • Android 7.0 (API 24)
[        ]     • Linux (desktop)   • linux    • linux-x64      • Ubuntu 20.04.3 LTS 5.10.0-1045-oem
[        ]     • Chrome (web)      • chrome   • web-javascript • Google Chrome 93.0.4577.63
[        ] ! Doctor found issues in 1 category.
[  +16 ms] "flutter doctor" took 813ms.
[ +258 ms] ensureAnalyticsSent: 252ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0
```

</details>

Also after downgrading flutter doctor returns:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale en_AU.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 27.0.1)
    ✗ Flutter requires Android SDK 29 and the Android BuildTools 28.0.3
      To update the Android SDK visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 4.1)
[✓] Connected device (3 available)

! Doctor found issues in 1 category.
```

**Comment by ben-milanko** [comment]
The issue has gone away by changing to a valid android SDK path however the crashing null check shouldn't be happening.
```
flutter config --android-sdk /path/to/valid/sdk
```

**Comment by darshankawar** [comment]
Thanks for the update. Keeping open for further insights from tools team.

/cc: @jonahwilliams
