### ISSUE TITLE
[Windows] Application crashed while pressing the right control with left and right arrow keys combinations in debug mode

### ISSUE THREAD

**Issue by ashok-kuvaraja** [flutter/flutter#90050]
Hi Team,

  I have created a simple application with `FocusNode` widget. My application is crashed while pressing the right control with left and right arrow keys combinations (**CTRL + ArrowLeft** and **CTRL + ArrowRight**) after Flutter 2.5.0 version in windows platform in debug mode. It was working fine before the Flutter 2.5.0 version. Please check and do the needful.  

## Steps to Reproduce

1. Run the below simple sample.
2. Press **Right CTRL + ArrowLeft** key combination simultaneously. 

```dart

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(MyApp());
}

/// The application that contains datagrid on it.
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Key Navigation Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: KeyNavigationSample(),
    );
  }
}

class KeyNavigationSample extends StatefulWidget {
  KeyNavigationSample({Key? key}) : super(key: key);

  @override
  _KeyNavigationSampleState createState() => _KeyNavigationSampleState();
}

class _KeyNavigationSampleState extends State<KeyNavigationSample> {
  late FocusNode focusNode;

  @override
  void initState() {
    super.initState();
    focusNode = FocusNode();
    focusNode.requestFocus();
  }

  KeyEventResult handleKeyEvent(FocusNode focusNode, RawKeyEvent keyEvent) {
    if (keyEvent.isControlPressed) {
      if (keyEvent.logicalKey == LogicalKeyboardKey.arrowLeft) {
        print('CTRL + ArrowLeft is triggered');
      }
    }
    return KeyEventResult.handled;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Focus(
        focusNode: focusNode,
        onKey: handleKeyEvent,
        child: Container(color: Colors.indigo),
      ),
    );
  }

  @override
  void dispose() {
    focusNode.dispose();
    super.dispose();
  }
}

```

**Expected results:** The key combination should be worked.

**Actual results:** Application is crashed.

<details>
  <summary> Failure Logs</summary>

```
════════ Exception caught by services library ══════════════════════════════════
The following assertion was thrown during a platform message callback:
A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real applications,
 please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event 
model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#4c011(physicalKey: PhysicalKeyboardKey#700e4(usbHidUsage: "0x000700e4", debugName: "Control Right"), logicalKey: 
LogicalKeyboardKey#00101(keyId: "0x200000101", keyLabel: "Control Right", debugName: "Control Right"), character: null, 
timeStamp: 264:43:19.674030, synthesized)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 441 pos 16: '_pressedKeys.containsKey(event.physicalKey)'

2

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack
#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure>
package:flutter/…/services/hardware_keyboard.dart:441
#3      HardwareKeyboard._assertEventIsRegular
package:flutter/…/services/hardware_keyboard.dart:452
#4      HardwareKeyboard.handleKeyEvent
package:flutter/…/services/hardware_keyboard.dart:543
#5      KeyEventManager.handleRawKeyMessage
package:flutter/…/services/hardware_keyboard.dart:821
#6      BasicMessageChannel.setMessageHandler.<anonymous closure>
package:flutter/…/services/platform_channel.dart:73
#7      BasicMessageChannel.setMessageHandler.<anonymous closure>
package:flutter/…/services/platform_channel.dart:72
#8      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>
package:flutter/…/services/binding.dart:379
#9      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>
package:flutter/…/services/binding.dart:376
#10     _invoke2.<anonymous closure> (dart:ui/hooks.dart:205:15)
#14     _invoke2 (dart:ui/hooks.dart:204:10)
#15     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#16     _Channel.push (dart:ui/channel_buffers.dart:132:31)
#17     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#18     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:544:22)
#19     _dispatchPlatformMessage (dart:ui/hooks.dart:92:31)
(elided 5 frames from class _AssertionError and dart:async)
```

</details>

<details>
 <summary> Flutter doctor </summary>

```

[√] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.18363.1440], locale en-US)
    • Flutter version 2.5.0 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (6 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\AshokKuvaraja\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Professional 2019 16.4.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional
    • Visual Studio Professional 2019 version 16.4.29806.167
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] VS Code, 64-bit edition (version 1.58.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.25.0

[√] Connected device (4 available)
    • Moto G 5S (mobile)           • ZY3228D7NG    • android-arm    • Android 7.1.1 (API 25)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.18363.1440]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 93.0.4577.63

! Doctor found issues in 1 category.

```

</details>

**Comment by darshankawar** [comment]
@ashok-kuvaraja 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/89982
Please follow-up in it for further updates.
Closing this as duplicate.
