### ISSUE TITLE
Flutter 

### ISSUE THREAD

**Issue by shahr8888** [flutter/flutter#90053]
FAILURE: Build failed with an exception.

* What went wrong:
Could not open settings generic class cache for settings file 'D:\Softwares\my_app\android\settings.gradle' (C:\Users\shahr\.gradle\caches\6.7\scripts\1fnwrr8g4roh
fp291nvlxj5qe).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 60

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                         3.9s
Exception: Gradle task assembleDebug failed with exit code 1

![image](https://user-images.githubusercontent.com/89586584/133272958-a9458745-e2c2-4186-b579-ba221775ef43.png)

**Comment by jesselpereira** [comment]
I found a solution but it didn't solve all my doubts. The solution I found can only be done by Android Studio.

When opening your project in Android Studio, the same problem occurs, but when you click **Tools => Flutter => Open for editing in Android Studio**, it opens an android page of your project (I recommend opening on the same screen), and starts to load **build.gradle** requests, needed to validate _settings.gradle_.

After finishing the loading (may take a long time) click on **File => Invalidate Caches / Restart... => Invalidate and Restart**, to erase the cache memory present in Android Studio and the next time you open the application, it won't cause any more problems when opening the virtualization.

**Comment by maheshmnj** [comment]
@jesselpereira, please share the output of `flutter doctor -v` and also try `flutter clean` and then do a flutter build

Thanks

**Comment by shahr8888** [comment]
For **flutter doc -v**
![1 FDV](https://user-images.githubusercontent.com/89586584/133489371-dbba07ea-aa93-4eaf-8554-9b68af91f3b9.png)
![2 FDV](https://user-images.githubusercontent.com/89586584/133489376-fe03410c-cdea-427a-8431-712f63e3dba5.png)

For **flutter run -v**
![FRV 1](https://user-images.githubusercontent.com/89586584/133490090-fde19adb-cf61-4365-aaa9-2fa09185e6c9.png)
![FRV 2](https://user-images.githubusercontent.com/89586584/133490099-788ab346-ba16-4825-a522-e25d47f00d7d.png)
![FRV 3](https://user-images.githubusercontent.com/89586584/133490100-3bdb46f7-4fae-42d2-b156-68882514944d.png)


And For **flutter clean**:


![FC](https://user-images.githubusercontent.com/89586584/133490323-74bfa25e-1845-4964-9cc7-2825457432f6.png)

**Comment by shahr8888** [comment]
Ad also here is when i run it on Flutter terminal
![image](https://user-images.githubusercontent.com/89586584/133491413-ce589bc3-c7a7-4185-a72e-38406fd60688.png)
![image](https://user-images.githubusercontent.com/89586584/133491479-89e935ab-6085-495f-b6a9-49e3d39e5205.png)
![image](https://user-images.githubusercontent.com/89586584/133491498-d632aff4-e6e2-4dbc-9c61-1b59ff902c8e.png)
![image](https://user-images.githubusercontent.com/89586584/133491518-1afd4547-5c4e-4124-a711-6a779bc1d82a.png)

**Comment by maheshmnj** [comment]
@shahr8888 Please share the text format of the output and not the screenshots.

Also, you need to execute `flutter run -v` from the root of your flutter project, I believe you are running it inside the flutter sdk. Could you also share the location where you downloaded the flutter SDK?

**Comment by shahr8888** [comment]
yes i uploaded the ss of flutter run -v and my location for the flutter sdk is in a custom location in drive D

**Comment by maheshmnj** [comment]
@shahr8888  please share the output of `flutter run -v` in a text form.

**Comment by shahr8888** [comment]
[ +113 ms] executing: [D:\Softwares\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +148 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] f4abaa0735eba4dfd8f33f73363911d63931fe03
[   +2 ms] executing: [D:\Softwares\src\flutter/] git tag --points-at f4abaa0735eba4dfd8f33f73363911d63931fe03
[ +811 ms] Exit code 0 from: git tag --points-at f4abaa0735eba4dfd8f33f73363911d63931fe03
[        ] 2.2.3
[  +10 ms] executing: [D:\Softwares\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +76 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[   +1 ms] executing: [D:\Softwares\src\flutter/] git ls-remote --get-url origin
[  +60 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +601 ms] executing: [D:\Softwares\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +46 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +100 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +8 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +144 ms] executing: D:\Softwares\AS\platform-tools\adb.exe devices -l
[ +100 ms] List of devices attached
                    emulator-5554          device product:sdk_phone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:1
[  +12 ms] D:\Softwares\AS\platform-tools\adb.exe -s emulator-5554 shell getprop
[ +107 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +191 ms] Skipping pub get: version match.
[ +389 ms] Generating D:\Softwares\my_app\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +104 ms] ro.hardware = ranchu
[  +28 ms] Using hardware rendering with device Android SDK built for x86. If you notice graphics artifacts, consider enabling software rendering with
           "--enable-software-rendering".
[  +41 ms] Initializing file store
[  +28 ms] Skipping target: gen_localizations
[  +13 ms] complete
[   +7 ms] Launching lib\main.dart on Android SDK built for x86 in debug mode...
[  +15 ms] D:\Softwares\src\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
D:\Softwares\src\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
D:\Softwares\src\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names
--experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
C:\Users\shahr\AppData\Local\Temp\flutter_tools.a2d991f2\flutter_tool.c30e0217\app.dill --packages D:\Softwares\my_app\.dart_tool\package_config.json
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill
build\3c113a45063dc6628e68a4111abcacad.cache.dill.track.dill --enable-experiment=alternative-invalidation-strategy
[  +67 ms] executing: D:\Softwares\AS\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v time -t 1
[  +24 ms] <- compile package:my_app/main.dart
[ +137 ms] --------- beginning of main
                    09-16 23:14:18.224 E/wifi_forwarder(  469): RemoteConnection failed to initialize: RemoteConnection failed to open pipe
[  +21 ms] executing: D:\Softwares\AS\platform-tools\adb.exe version
[  +63 ms] Android Debug Bridge version 1.0.41
           Version 31.0.3-7562133
           Installed as D:\Softwares\AS\platform-tools\adb.exe
[   +8 ms] executing: D:\Softwares\AS\platform-tools\adb.exe start-server
[ +103 ms] Building APK
[  +39 ms] Running Gradle task 'assembleDebug'...
[  +13 ms] Using gradle from D:\Softwares\my_app\android\gradlew.bat.
[  +32 ms] executing: [D:\Softwares\my_app\android/] D:\Softwares\my_app\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-x86
-Ptarget=D:\Softwares\my_app\lib\main.dart -Pdart-defines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== -Pdart-obfuscation=false -Ptrack-widget-creation=true
-Ptree-shake-icons=false -Pfilesystem-scheme=org-dartlang-root assembleDebug
[+9913 ms] Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details
[+16861 ms] FAILURE: Build failed with an exception.
[  +11 ms] * What went wrong:
[   +3 ms] Could not open settings generic class cache for settings file 'D:\Softwares\my_app\android\settings.gradle'
(C:\Users\shahr\.gradle\caches\6.7\scripts\1fnwrr8g4rohfp291nvlxj5qe).
[   +2 ms] > BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 60
[   +1 ms] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[   +1 ms] * Get more help at https://help.gradle.org
[   +1 ms] BUILD FAILED in 25s
[ +815 ms] Running Gradle task 'assembleDebug'... (completed in 27.6s)
[   +9 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +5 ms] "flutter run" took 29,390ms.
[   +8 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:663:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[ +273 ms] ensureAnalyticsSent: 268ms
[   +3 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +6 ms] exiting with code 1

**Comment by maheshmnj** [comment]
@shahr8888 this looks like this issue is related to JDK 16, can you try downgrading to JDK11 and see if that works. I would suggest using Android Studio to easily switch between JDK's. And then please share the `flutter doctor -v` in the form of text.

**Comment by shahr8888** [comment]
Thank You i will try that

**Comment by shahr8888** [comment]
[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

after i run flutter doctor -v i have this error and I am doing my work on Android Studio....

**Comment by maheshmnj** [comment]
@shahr8888, please upgrade to latest stable 2.5.1 by running 

```
flutter upgrade
```
and if the issue persists, then please share the version of Android studio and the output of `flutter doctor -v`

Thanks.
