### ISSUE TITLE
Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader

### ISSUE THREAD

**Issue by bhushan2k** [flutter/flutter#90073]
This issue is getting on release apk only. Tried couple of solutions mentioned on references at the bottom but no luck.

## Steps to Reproduce

Install release APK by first going Build > Flutter > Build APK and then manually installing apk

or

Install from PlayStore

## Logs on Logcat

```
2021-09-14 22:35:48.517 12366-12366/? E/FlutterLoader: Flutter initialization failed.
    java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.pockethcm.greytrix.test-8g2MGFqmlyJkq-euudSAPw==/base.apk"],nativeLibraryDirectories=[/data/app/com.pockethcm.greytrix.test-8g2MGFqmlyJkq-euudSAPw==/lib/x86, /data/app/com.pockethcm.greytrix.test-8g2MGFqmlyJkq-euudSAPw==/base.apk!/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libflutter.so"
        at java.util.concurrent.FutureTask.report(FutureTask.java:123)
        at java.util.concurrent.FutureTask.get(FutureTask.java:193)
        at io.flutter.embedding.engine.g.c.d(Unknown Source:23)
        at io.flutter.embedding.engine.a.<init>(Unknown Source:174)
        at io.flutter.embedding.engine.a.<init>(Unknown Source:16)
        at io.flutter.embedding.android.f.B(Unknown Source:106)
        at io.flutter.embedding.android.f.k(Unknown Source:7)
        at io.flutter.embedding.android.e.onCreate(Unknown Source:13)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.pockethcm.greytrix.test-8g2MGFqmlyJkq-euudSAPw==/base.apk"],nativeLibraryDirectories=[/data/app/com.pockethcm.greytrix.test-8g2MGFqmlyJkq-euudSAPw==/lib/x86, /data/app/com.pockethcm.greytrix.test-8g2MGFqmlyJkq-euudSAPw==/base.apk!/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libflutter.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
        at java.lang.System.loadLibrary(System.java:1657)
        at io.flutter.embedding.engine.FlutterJNI.loadLibrary(Unknown Source:13)
        at io.flutter.embedding.engine.g.c$a.a(Unknown Source:14)
        at io.flutter.embedding.engine.g.c$a.call(Unknown Source:0)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
2021-09-14 22:35:48.564 12366-12366/? D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
2021-09-14 22:35:48.614 12366-12366/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.pockethcm.greytrix.test, PID: 12366
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.pockethcm.greytrix.test/com.pockethcm.greytrix.test.MainActivity}: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.pockethcm.greytrix.test-8g2MGFqmlyJkq-euudSAPw==/base.apk"],nativeLibraryDirectories=[/data/app/com.pockethcm.greytrix.test-8g2MGFqmlyJkq-euudSAPw==/lib/x86, /data/app/com.pockethcm.greytrix.test-8g2MGFqmlyJkq-euudSAPw==/base.apk!/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libflutter.so"
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.pockethcm.greytrix.test-8g2MGFqmlyJkq-euudSAPw==/base.apk"],nativeLibraryDirectories=[/data/app/com.pockethcm.greytrix.test-8g2MGFqmlyJkq-euudSAPw==/lib/x86, /data/app/com.pockethcm.greytrix.test-8g2MGFqmlyJkq-euudSAPw==/base.apk!/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libflutter.so"
        at io.flutter.embedding.engine.g.c.d(Unknown Source:354)
        at io.flutter.embedding.engine.a.<init>(Unknown Source:174)
        at io.flutter.embedding.engine.a.<init>(Unknown Source:16)
        at io.flutter.embedding.android.f.B(Unknown Source:106)
        at io.flutter.embedding.android.f.k(Unknown Source:7)
        at io.flutter.embedding.android.e.onCreate(Unknown Source:13)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
     Caused by: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.pockethcm.greytrix.test-8g2MGFqmlyJkq-euudSAPw==/base.apk"],nativeLibraryDirectories=[/data/app/com.pockethcm.greytrix.test-8g2MGFqmlyJkq-euudSAPw==/lib/x86, /data/app/com.pockethcm.greytrix.test-8g2MGFqmlyJkq-euudSAPw==/base.apk!/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libflutter.so"
        at java.util.concurrent.FutureTask.report(FutureTask.java:123)
        at java.util.concurrent.FutureTask.get(FutureTask.java:193)
        at io.flutter.embedding.engine.g.c.d(Unknown Source:23)
        at io.flutter.embedding.engine.a.<init>(Unknown Source:174) 
        at io.flutter.embedding.engine.a.<init>(Unknown Source:16) 
        at io.flutter.embedding.android.f.B(Unknown Source:106) 
        at io.flutter.embedding.android.f.k(Unknown Source:7) 
        at io.flutter.embedding.android.e.onCreate(Unknown Source:13) 
        at android.app.Activity.performCreate(Activity.java:7009) 
        at android.app.Activity.performCreate(Activity.java:7000) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
     Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.pockethcm.greytrix.test-8g2MGFqmlyJkq-euudSAPw==/base.apk"],nativeLibraryDirectories=[/data/app/com.pockethcm.greytrix.test-8g2MGFqmlyJkq-euudSAPw==/lib/x86, /data/app/com.pockethcm.greytrix.test-8g2MGFqmlyJkq-euudSAPw==/base.apk!/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libflutter.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
        at java.lang.System.loadLibrary(System.java:1657)
        at io.flutter.embedding.engine.FlutterJNI.loadLibrary(Unknown Source:13)
        at io.flutter.embedding.engine.g.c$a.a(Unknown Source:14)
        at io.flutter.embedding.engine.g.c$a.call(Unknown Source:0)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
2021-09-14 22:35:48.616 12366-12366/? E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

## Stack Trace on Crashes and ANRs on PlayStore Console
```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> com.pockethcm.greytrix.test <<<

backtrace:
  #00  pc 000000000001e658  /system/lib64/libc.so (abort+120)
  #00  pc 00000000000083e4  /system/lib64/liblog.so (__android_log_assert+296)
  #00  pc 00000000000468fc  /system/lib64/libhwui.so (android::uirenderer::debug::GlesErrorCheckWrapper::assertNoErrors(char const*)+384)
  #00  pc 0000000000089b00  /system/lib64/libhwui.so (android::uirenderer::Caches::flush(android::uirenderer::Caches::FlushMode)+164)
  #00  pc 00000000000752fc  /system/lib64/libhwui.so (android::uirenderer::renderthread::Bridge_destroyHardwareResources(android::uirenderer::renderthread::destroyHardwareResourcesArgs*)+12)
  #00  pc 0000000000076934  /system/lib64/libhwui.so (android::uirenderer::renderthread::MethodInvokeRenderTask::run()+24)
  #00  pc 0000000000076cc8  /system/lib64/libhwui.so (android::uirenderer::renderthread::SignalingRenderTask::run()+28)
  #00  pc 0000000000077c18  /system/lib64/libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop()+336)
  #00  pc 0000000000011590  /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+276)
  #00  pc 00000000000aa03c  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::javaThreadShell(void*)+136)
  #00  pc 0000000000077968  /system/lib64/libc.so (__pthread_start(void*)+36)
  #00  pc 000000000001fa30  /system/lib64/libc.so (__start_thread+68)
```

## Devices

- Real device running on 8.1
- Emulator 8.1

## Similar Reference

[Reference 1](https://github.com/flutter/flutter/issues/64697)
[Reference 2](https://github.com/flutter/flutter/issues/32756)
[Reference 3](https://medium.com/codechai/flutter-app-couldnt-find-libflutter-so-c95ad81cbccd)

**Comment by darshankawar** [comment]
@bhushan2k 
There's a similar open issue describing your case, https://github.com/flutter/flutter/issues/83596
Please follow-up in it for reference.
Closing this as duplicate.
