### ISSUE TITLE
flutter crashes when Android Studio is older than v2.2.0

### ISSUE THREAD

**Issue by yyoon** [flutter/flutter#9008]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception

ArgumentError: Invalid argument(s): Cannot find executable for /opt/android-studio-2.1/jre/bin/java.

```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:115)
#1      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:86)
#2      AndroidStudio._init (package:flutter_tools/src/android/android_studio.dart:285)
#3      AndroidStudio.AndroidStudio (package:flutter_tools/src/android/android_studio.dart:54)
#4      AndroidStudio.AndroidStudio.fromHomeDot (package:flutter_tools/src/android/android_studio.dart:96)
#5      AndroidStudio._allLinuxOrWindows (package:flutter_tools/src/android/android_studio.dart:205)
#6      AndroidStudio.allInstalled (package:flutter_tools/src/android/android_studio.dart:142)
#7      AndroidStudioValidator.allValidators (package:flutter_tools/src/android/android_studio_validator.dart:23)
#8      Doctor.validators (package:flutter_tools/src/doctor.dart:56)
#9      Doctor.diagnose (package:flutter_tools/src/doctor.dart:114)
<asynchronous suspension>
#10     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:19)
<asynchronous suspension>
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:151)
<asynchronous suspension>
#12     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:121)
#13     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:261)
<asynchronous suspension>
#15     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#16     Future.Future.sync (dart:async/future.dart:208)
#17     CommandRunner.run (package:args/command_runner.dart:109)
#18     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:157)
#19     run.<anonymous closure> (package:flutter_tools/executable.dart:140)
<asynchronous suspension>
#20     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#21     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#22     _rootRun (dart:async/zone.dart:1150)
#23     _CustomZone.run (dart:async/zone.dart:1026)
#24     runZoned (dart:async/zone.dart:1503)
#25     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#26     run (package:flutter_tools/executable.dart:113)
<asynchronous suspension>
#27     main (package:flutter_tools/executable.dart:66)
<asynchronous suspension>
#28     main (file:///usr/local/google/home/youngseokyoon/Programming/fuchsia/lib/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#29     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#30     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

## flutter doctor

```
encountered exception: Invalid argument(s): Cannot find executable for /opt/android-studio-2.1/jre/bin/java.

#0      _getExecutable (package:process/src/interface/local_process_manager.dart:115)
#1      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:86)
#2      AndroidStudio._init (package:flutter_tools/src/android/android_studio.dart:285)
#3      AndroidStudio.AndroidStudio (package:flutter_tools/src/android/android_studio.dart:54)
#4      AndroidStudio.AndroidStudio.fromHomeDot (package:flutter_tools/src/android/android_studio.dart:96)
#5      AndroidStudio._allLinuxOrWindows (package:flutter_tools/src/android/android_studio.dart:205)
#6      AndroidStudio.allInstalled (package:flutter_tools/src/android/android_studio.dart:142)
#7      AndroidStudio.latestValid (package:flutter_tools/src/android/android_studio.dart:132)
#8      AppContext.putIfAbsent (package:flutter_tools/src/base/context.dart:46)
#9      androidStudio (package:flutter_tools/src/android/android_studio.dart:17)
#10     javaPath (package:flutter_tools/src/android/android_studio.dart:49)
#11     AndroidWorkflow._findJavaBinary (package:flutter_tools/src/android/android_workflow.dart:37)
#12     AndroidWorkflow.validate (package:flutter_tools/src/android/android_workflow.dart:145)
<asynchronous suspension>
#13     Doctor.diagnose (package:flutter_tools/src/doctor.dart:119)
<asynchronous suspension>
#14     _doctorText.<anonymous closure> (package:flutter_tools/executable.dart:287)
#15     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#16     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#17     _rootRun (dart:async/zone.dart:1150)
#18     _CustomZone.run (dart:async/zone.dart:1026)
#19     runZoned (dart:async/zone.dart:1503)
#20     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#21     _doctorText (package:flutter_tools/executable.dart:287)
<asynchronous suspension>
#22     _createLocalCrashReport (package:flutter_tools/executable.dart:262)
<asynchronous suspension>
#23     _handleToolError (package:flutter_tools/executable.dart:217)
<asynchronous suspension>
#24     run.<anonymous closure> (package:flutter_tools/executable.dart:144)
<asynchronous suspension>
#25     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#26     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#27     _rootRun (dart:async/zone.dart:1150)
#28     _CustomZone.run (dart:async/zone.dart:1026)
#29     runZoned (dart:async/zone.dart:1503)
#30     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#31     run (package:flutter_tools/executable.dart:113)
<asynchronous suspension>
#32     main (package:flutter_tools/executable.dart:66)
<asynchronous suspension>
#33     main (file:///usr/local/google/home/youngseokyoon/Programming/fuchsia/lib/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#34     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by yyoon** [comment]
cc/ @goderbauer

**Comment by goderbauer** [comment]
@yyoon Can you update your Android Studio to the latest version from here: https://developer.android.com/studio/index.html

Your version 2.1 does not come bundled with the JDK. Android Studio v2.2.0 (September 2016) is the first one that includes the JDK.

We should probably check for that and only attempt to use the bundled JDK when Android Studio is new enough.

**Comment by yyoon** [comment]
Yeah, I think there should be the check.

For some reason I have Android Studio 2.1, 2.2, 2.3 installed separately on my machine. I could probably try again after uninstalling 2.1.

**Comment by goderbauer** [comment]
I just pushed a path. Can you upgrade your flutter installation and try again? Thanks.

**Comment by yyoon** [comment]
Works fine now. Thanks!
