### ISSUE TITLE
Crash in download_dart_sdk.py on Windows machines with > 60 cores

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#90085]
Running `src/flutter/tools/download_dart_sdk.py` (which is done by gclient sync/runhooks) under `cmd.exe` or `git-bash` triggers the following error:
```
Running hooks:  88% ( 8/ 9) Download prebuilt Dart SDK
________ running 'python3 src/flutter/tools/download_dart_sdk.py' in 'C:\src\flutter\engine'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\src\depot_tools\bootstrap-2@3_8_10_chromium_20_bin\python3\bin\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\src\depot_tools\bootstrap-2@3_8_10_chromium_20_bin\python3\bin\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\src\depot_tools\bootstrap-2@3_8_10_chromium_20_bin\python3\bin\lib\multiprocessing\pool.py", line 519, in _handle_workers
    cls._wait_for_updates(current_sentinels, change_notifier)
  File "C:\src\depot_tools\bootstrap-2@3_8_10_chromium_20_bin\python3\bin\lib\multiprocessing\pool.py", line 499, in _wait_for_updates
    wait(sentinels, timeout=timeout)
  File "C:\src\depot_tools\bootstrap-2@3_8_10_chromium_20_bin\python3\bin\lib\multiprocessing\connection.py", line 879, in wait
    ready_handles = _exhaustive_wait(waithandle_to_obj.keys(), timeout)
  File "C:\src\depot_tools\bootstrap-2@3_8_10_chromium_20_bin\python3\bin\lib\multiprocessing\connection.py", line 811, in _exhaustive_wait
    res = _winapi.WaitForMultipleObjects(L, False, timeout)
ValueError: need at most 63 handles, got a sequence of length 74
```

This is _not_ an issue when running under PowerShell. As a temporary workaround, the user can set an environment variable to avoid this issue by not using the prebuilt Dart SDK:
```
FLUTTER_PREBUILT_DART_SDK=false
```

**Comment by cbracken** [comment]
This was fixed by https://github.com/flutter/engine/pull/28623

**Comment by cbracken** [comment]
Summary of the issue for future archaeologists:

The multiprocessing package relies on the win32 WaitForMultipleObjects
call, which supports waiting on a maximum of MAXIMUM_WAIT_OBJECTS
(defined by Windows to be 64) handles, processes in this case. To avoid
hitting this, we limit ourselves to 60 handles (since there are a couple
extra processes launched for the queue reader and thread wakeup reader).

When left unspecified, the multiprocessing module defaults this value to
os.cpu_count(), so this error is triggered only on machines with > 60
cores. Technically, the limit should be 61, but there's a second Python
bug in the process count check containing an off-by-one error.

See: https://bugs.python.org/issue2690 (handle limit)
See: https://bugs.python.org/issue40263 (off-by-one error)
