### ISSUE TITLE
[Camera] Flutter module - iOS app - No implementation found for method availableCameras on channel plugins.flutter.io/camera

### ISSUE THREAD

**Issue by page-fault-in-nonpaged-area** [flutter/flutter#90082]
This is a ticket in reference to https://github.com/flutter/flutter/issues/89500, Just in case it's off-topic or not applicable to tag platform-android. 

## Steps to Reproduce

1. [Create flutter module](https://flutter.dev/docs/development/add-to-app/ios/project-setup) (Option A, Cocoapods)
2. Enable camera in Info plist privacy
3. main.dart: https://pastebin.com/LTrnKvqe

**Expected results:** 

Working camera

**Actual results:** 
```
<asynchronous suspension>
#1      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:342:35)
<asynchronous suspension>
#2      MethodChannelCamera.availableCameras (package:camera_platform_interface/src/method_channel/method_channel_camera.dart:62:52)
<asynchronous suspension>
#3      obtainCamera (package:smartscan/main.dart:16:13)
<asynchronous suspension>
2021-09-14 15:58:25.677443-0400 MyStore[7022:433140] [VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method availableCameras on channel plugins.flutter.io/camera)
```
flutter doctor:

```console
[✓] Flutter (Channel master, 2.6.0-6.0.pre.6, on macOS 11.3.1 20E241 darwin-x64, locale en-CA)
    • Flutter version 2.6.0-6.0.pre.6 at /Users/wilyang/sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0c5431d99c (9 days ago), 2021-09-05 22:31:02 -0400
    • Engine revision b9c633900e
    • Dart version 2.15.0 (build 2.15.0-82.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/wilyang/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.60.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] VS Code (version 1.61.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] VS Code (version 1.59.0-insider)
    • VS Code at /Users/wilyang/Downloads/VSCode-darwin-universal/Visual Studio Code - Insiders.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • William’s iPhone (mobile) • d93ca1b0c20d147bd5a6cac733ac518d8e13db2d • ios            • iOS 14.7.1 18G82
    • Chrome (web)              • chrome                                   • web-javascript • Google Chrome 93.0.4577.63
```
Note: I am not working with Android. Only iOS.

**Comment by danagbemava-nc** [comment]
Hi @page-fault-in-nonpaged-area, can you provide a sample repo that able to run without much change?

Thank you

**Comment by page-fault-in-nonpaged-area** [comment]
Hi @danagbemava-nc, attached is the repo reproducing the bug: https://github.com/page-fault-in-nonpaged-area/CameraTest . It follows the guide @ https://flutter.dev/docs/development/add-to-app/ios/project-setup

Thanks!

**Comment by danagbemava-nc** [comment]
Issue is reproducible on `master` and `stable` using `camera: ^0.9.3`.

<details>
<summary>logs from xcode</summary>

```console
Opening...
2021-09-16 06:35:30.540302+0000 CameraTest[11397:3278840] Metal API Validation Enabled
2021-09-16 06:35:30.764075+0000 CameraTest[11397:3279307] flutter: Observatory listening on http://127.0.0.1:55979/FeHvCB5ebeU=/
2021-09-16 06:35:33.884142+0000 CameraTest[11397:3279293] flutter: Error: MissingPluginException(No implementation found for method availableCameras on channel plugins.flutter.io/camera).code
Error Message: MissingPluginException(No implementation found for method availableCameras on channel plugins.flutter.io/camera).message
Opening...
2021-09-16 06:40:53.792227+0000 CameraTest[11397:3281071] flutter: Error: MissingPluginException(No implementation found for method availableCameras on channel plugins.flutter.io/camera).code
Error Message: MissingPluginException(No implementation found for method availableCameras on channel plugins.flutter.io/camera).message
2021-09-16 06:40:56.891207+0000 CameraTest[11397:3281071] flutter: Error: MissingPluginException(No implementation found for method availableCameras on channel plugins.flutter.io/camera).code
Error Message: MissingPluginException(No implementation found for method availableCameras on channel plugins.flutter.io/camera).message
```
</details>

<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel master, 2.6.0-6.0.pre.114, on macOS 11.5.1 20G80
    darwin-arm, locale en-GB)
    • Flutter version 2.6.0-6.0.pre.114 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd1892f04f (87 minutes ago), 2021-09-15 22:17:02 -0700
    • Engine revision 5a09f16031
    • Dart version 2.15.0 (build 2.15.0-110.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.60.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • Nexus’ IPhone (mobile) • 00008020-001875E83A38002E • ios            • iOS
      14.7.1 18G82
    • macOS (desktop)        • macos                     • darwin-arm64   •
      macOS 11.5.1 20G80 darwin-arm
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 93.0.4577.82

• No issues found!
```

```console
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.5.1 20G80 darwin-arm, locale
    en-GB)
    • Flutter version 2.5.0 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (8 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.60.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • Nexus’ IPhone (mobile) • 00008020-001875E83A38002E • ios            • iOS
      14.7.1 18G82
    • macOS (desktop)        • macos                     • darwin-arm64   •
      macOS 11.5.1 20G80 darwin-arm
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 93.0.4577.82

• No issues found!
```
</details>

**Comment by page-fault-in-nonpaged-area** [comment]
Hello all! This has been partially solved with a solution. The problem is present if using the _implicit_ FlutterEngine. The solution is to use the non-implicit (explicit?) FlutterEngine as described in the [guide](https://flutter.dev/docs/development/add-to-app/ios/add-flutter-screen?tab=engine-swift-tab). May be worthwhile to look at why implicit doesn't work tho. 

Thanks all!

**Comment by jmagman** [comment]
You need to call `GeneratedPluginRegistrant.register`.
https://flutter.dev/docs/development/add-to-app/ios/add-flutter-screen?tab=engine-swift-tab#create-a-flutterengine

This error message could be better.

**Comment by page-fault-in-nonpaged-area** [comment]
Can confirm implicit worked with `GeneratedPluginRegistrant.register(with: controller.pluginRegistry())`. Thanks all! 🎉
