### ISSUE TITLE
Web app not working with Flutter 2.5.0

### ISSUE THREAD

**Issue by jerryhamby** [flutter/flutter#90093]
Looking for some help or advice.

I have created a default app I’m trying to test run, but I keep getting this error 
(Only when I include cloud_firestore: ^2.5.2) otherwise 
the app will launch perfectly OK. FYI, I have 26 other plugins I’m testing and
no  problem except when including cloud_firestore.

Here is my test with cloud_firestore. 
I have also tested cloud_firestore_web: ^2.4.2 with same results.

FYI, I have gotten 2.5.0 to work with IOS using "pod update Firebase/CoreOnly"
One more thing, using the previous version of Flutter (I think 2.3.2) everything was working great.

<details>
<summary>flutter run</summary>

```console
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             13.4s
This app is linked to the debug service: ws://127.0.0.1:56034/noB7gMX1qaI=/ws
Debug service listening on ws://127.0.0.1:56034/noB7gMX1qaI=/ws

💪 Running with sound null safety 💪

🔥  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".

An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:56034/noB7gMX1qaI=
TypeError: Cannot read properties of undefined (reading 'app')
    at Object.app$ [as app] (http://localhost:55985/packages/firebase_core_web/src/interop/core.dart.lib.js:31:101)
    at new cloud_firestore_web.FirebaseFirestoreWeb.new
    (http://localhost:55985/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:833:64)
    at Function.registerWith (http://localhost:55985/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:745:73)
    at Object.registerPlugins
    (http://localhost:55985/packages/flutter_application_1xxx/generated_plugin_registrant.dart.lib.js:19:46)
    at main (http://localhost:55985/web_entrypoint.dart.lib.js:31:35)
    at main.next (<anonymous>)
    at runBody (http://localhost:55985/dart_sdk.js:38659:34)
    at Object._async [as async] (http://localhost:55985/dart_sdk.js:38690:7)
    at main$ (http://localhost:55985/web_entrypoint.dart.lib.js:30:18)
    at http://localhost:55985/main_module.bootstrap.js:19:10
    at Array.forEach (<anonymous>)
    at window.$dartRunMain (http://localhost:55985/main_module.bootstrap.js:18:32)
    at <anonymous>:1:8
    at Object.runMain (http://localhost:55985/dwds/src/injected/client.js:8452:21)
    at http://localhost:55985/dwds/src/injected/client.js:24130:19
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:55985/dwds/src/injected/client.js:4461:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:55985/dwds/src/injected/client.js:11511:12)
    at Object._asyncStartSync (http://localhost:55985/dwds/src/injected/client.js:4425:20)
    at main__closure3.$call$body$main__closure (http://localhost:55985/dwds/src/injected/client.js:24142:16)
    at main__closure3.call$1 (http://localhost:55985/dwds/src/injected/client.js:24069:19)
    at StaticClosure._rootRunUnary (http://localhost:55985/dwds/src/injected/client.js:4823:18)
    at _CustomZone.runUnary$2$2 (http://localhost:55985/dwds/src/injected/client.js:12879:39)
    at _CustomZone.runUnaryGuarded$1$2 (http://localhost:55985/dwds/src/injected/client.js:12826:14)
    at _ForwardingStreamSubscription._sendData$1 (http://localhost:55985/dwds/src/injected/client.js:12416:19)
    at _ForwardingStreamSubscription._add$1 (http://localhost:55985/dwds/src/injected/client.js:12362:15)
    at _ForwardingStreamSubscription._add$1 (http://localhost:55985/dwds/src/injected/client.js:12695:12)
    at _MapStream._handleData$2 (http://localhost:55985/dwds/src/injected/client.js:12756:12)
    at _ForwardingStreamSubscription._handleData$1 (http://localhost:55985/dwds/src/injected/client.js:12721:20)
    at Object.eval (eval at Closure_forwardCallTo (http://localhost:55985/dwds/src/injected/client.js:1701:14),
    <anonymous>:3:44)
    at StaticClosure._rootRunUnary (http://localhost:55985/dwds/src/injected/client.js:4823:18)
    at _CustomZone.runUnary$2$2 (http://localhost:55985/dwds/src/injected/client.js:12879:39)
    at _CustomZone.runUnaryGuarded$1$2 (http://localhost:55985/dwds/src/injected/client.js:12826:14)
    at _ControllerSubscription._sendData$1 (http://localhost:55985/dwds/src/injected/client.js:12416:19)
    at _ControllerSubscription._add$1 (http://localhost:55985/dwds/src/injected/client.js:12362:15)
    at _SyncStreamController._sendData$1 (http://localhost:55985/dwds/src/injected/client.js:12201:32)
    at _SyncStreamController.add$1 (http://localhost:55985/dwds/src/injected/client.js:12082:15)
    at Object.eval (eval at Closure_forwardInterceptedCallTo
    (http://localhost:55985/dwds/src/injected/client.js:1781:14), <anonymous>:3:45)
    at StaticClosure._rootRunUnary (http://localhost:55985/dwds/src/injected/client.js:4823:18)
    at _CustomZone.runUnary$2$2 (http://localhost:55985/dwds/src/injected/client.js:12879:39)
    at _CustomZone.runUnaryGuarded$1$2 (http://localhost:55985/dwds/src/injected/client.js:12826:14)
    at _ControllerSubscription._sendData$1 (http://localhost:55985/dwds/src/injected/client.js:12416:19)
    at _ControllerSubscription._add$1 (http://localhost:55985/dwds/src/injected/client.js:12362:15)
    at _SyncStreamController._sendData$1 (http://localhost:55985/dwds/src/injected/client.js:12201:32)
    at _SyncStreamController.add$1 (http://localhost:55985/dwds/src/injected/client.js:12082:15)
    at _GuaranteeSink.add$1 (http://localhost:55985/dwds/src/injected/client.js:23581:25)
    at HtmlWebSocketChannel_closure1.call$1 (http://localhost:55985/dwds/src/injected/client.js:23874:60)
    at _EventStreamSubscription_closure.call$1 (http://localhost:55985/dwds/src/injected/client.js:18042:26)
    at StaticClosure._rootRunUnary (http://localhost:55985/dwds/src/injected/client.js:4829:16)
    at _CustomZone.runUnary$2$2 (http://localhost:55985/dwds/src/injected/client.js:12879:39)
    at _CustomZone.runUnaryGuarded$1$2 (http://localhost:55985/dwds/src/injected/client.js:12826:14)
    at _CustomZone_bindUnaryCallbackGuarded_closure.call$1 (http://localhost:55985/dwds/src/injected/client.js:13016:25)
    at invokeClosure (http://localhost:55985/dwds/src/injected/client.js:1524:26)
    at WebSocket.<anonymous> (http://localhost:55985/dwds/src/injected/client.js:1543:18)
```
</details>

**Comment by definev** [comment]
You must add issue in firebase plugin repo not in flutter repo

**Comment by danagbemava-nc** [comment]
Hi @jerryhamby, this looks like it might be an issue with `cloud_firestore`. 

Please file the issue on the [flutter_fire repo](https://github.com/firebaseextended/flutterfire). 

Closing as this is not an issue with flutter itself. If you disagree, please write in the comments and I will reopen it.

Thank you
