### ISSUE TITLE
_CastError: Null check operator used on a null value at MaterialFonts.updateInner(flutter_cache.dart:141)

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#90092]
Number 6 crasher on Flutter 2.5
```
Thread 0 main thread_CastError: Null check operator used on a null value
at MaterialFonts.updateInner(flutter_cache.dart:141)
at CachedArtifact.update(cache.dart:688)
at Cache.updateAll(cache.dart:557)
at <asynchronous gap>(async)
at FlutterCommand.verifyThenRunCommand(flutter_command.dart:1228)
at <asynchronous gap>(async)
at FlutterCommand.run.<anonymous closure>(flutter_command.dart:1125)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:150)
at <asynchronous gap>(async)
at CommandRunner.runCommand(command_runner.dart:209)
at <asynchronous gap>(async)
at FlutterCommandRunner.runCommand.<anonymous closure>(flutter_command_runner.dart:288)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:150)
at <asynchronous gap>(async)
at FlutterCommandRunner.runCommand(flutter_command_runner.dart:236)
at <asynchronous gap>(async)
at run.<anonymous closure>.<anonymous closure>(runner.dart:62)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:150)
at <asynchronous gap>(async)
at main(executable.dart:92)
at <asynchronous gap>(async)
```
https://github.com/flutter/flutter/blob/4cc385b4b84ac2f816d939a49ea1f328c4e0b48e/packages/flutter_tools/lib/src/flutter_cache.dart#L141

Caused by https://github.com/flutter/flutter/pull/85242#discussion_r658287550
> I think the right thing to do is `!` so if it does fail it shows up in crash logging

**Comment by jmagman** [comment]
A check for `version` existence was added after `updateInner` (too late) in #79864.  I'm not sure why `version` is null at this point.

**Comment by christopherfujino** [comment]
it looks to me like this can only be null if the version file does not exist on disk: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/cache.dart#L609

```
    return versionFile.existsSync() ? versionFile.readAsStringSync().trim() : null;
```

I'm not sure how that is possible though...

**Comment by christopherfujino** [comment]
Ohh, actually, if I look at this: https://github.com/flutter/flutter/issues/91942

The user does not have an engine version too, and are on Windows. I wonder if this is the unzipping error where not all files are present?

**Comment by christopherfujino** [comment]
A newer stacktrace from https://github.com/flutter/flutter/issues/141450 at stable 3.13.1

```
_TypeError: (#0 MaterialFonts.updateInner (package:flutter_tools/src/flutter_cache.dart:151:49))

#0      MaterialFonts.updateInner (package:flutter_tools/src/flutter_cache.dart:151:49)
#1      CachedArtifact.update (package:flutter_tools/src/cache.dart:812:11)
#2      Cache.updateAll (package:flutter_tools/src/cache.dart:679:24)
<asynchronous suspension>
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1566:7)
<asynchronous suspension>
#4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
<asynchronous suspension>
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
<asynchronous suspension>
#10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>
```
