### ISSUE TITLE
[Android 12][Keyboard] Display ID mismatch found.

### ISSUE THREAD

**Issue by hsalazarl** [flutter/flutter#90207]
Using Android 12 (API 31) with webview plugins such as [webview_flutter](https://pub.dev/packages/webview_flutter) or [flutter_inappwebview](https://pub.dev/packages/flutter_inappwebview) fail to show the keyboard with this exception:

```
[   +1 ms] V/InputMethodManager(10400): b/117267690: Display ID mismatch found. ViewRootImpl displayId=20 InputMethodManager displayId=0. Use the right InputMethodManager instance to avoid performance overhead.
[        ] V/InputMethodManager(10400): java.lang.Throwable
[        ] V/InputMethodManager(10400): 	at android.view.inputmethod.InputMethodManager.getFallbackInputMethodManagerIfNecessary(InputMethodManager.java:549)
[        ] V/InputMethodManager(10400): 	at android.view.inputmethod.InputMethodManager.restartInput(InputMethodManager.java:1843)
[        ] V/InputMethodManager(10400): 	at org.chromium.content.browser.input.ImeAdapterImpl.H(chromium-TrichromeWebViewGoogle6432.apk-stable-447211487:4)
[        ] V/InputMethodManager(10400): 	at org.chromium.content.browser.input.ImeAdapterImpl.updateState(chromium-TrichromeWebViewGoogle6432.apk-stable-447211487:30)
[        ] V/InputMethodManager(10400): 	at android.os.MessageQueue.nativePollOnce(Native Method)
[        ] V/InputMethodManager(10400): 	at android.os.MessageQueue.next(MessageQueue.java:335)
[        ] V/InputMethodManager(10400): 	at android.os.Looper.loopOnce(Looper.java:161)
[        ] V/InputMethodManager(10400): 	at android.os.Looper.loop(Looper.java:288)
[        ] V/InputMethodManager(10400): 	at android.app.ActivityThread.main(ActivityThread.java:7842)
[        ] V/InputMethodManager(10400): 	at java.lang.reflect.Method.invoke(Native Method)
[        ] V/InputMethodManager(10400): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
[        ] V/InputMethodManager(10400): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
[        ] V/InputMethodManager(10400): b/117267690: Display ID mismatch found. ViewRootImpl displayId=20 InputMethodManager displayId=0. Use the right InputMethodManager instance to avoid performance overhead.
[        ] V/InputMethodManager(10400): java.lang.Throwable
[        ] V/InputMethodManager(10400): 	at android.view.inputmethod.InputMethodManager.getFallbackInputMethodManagerIfNecessary(InputMethodManager.java:549)
[        ] V/InputMethodManager(10400): 	at android.view.inputmethod.InputMethodManager.showSoftInput(InputMethodManager.java:1625)
[        ] V/InputMethodManager(10400): 	at android.view.inputmethod.InputMethodManager.showSoftInput(InputMethodManager.java:1617)
[        ] V/InputMethodManager(10400): 	at sH.d(chromium-TrichromeWebViewGoogle6432.apk-stable-447211487:3)
[        ] V/InputMethodManager(10400): 	at org.chromium.content.browser.input.ImeAdapterImpl.L(chromium-TrichromeWebViewGoogle6432.apk-stable-447211487:20)
[        ] V/InputMethodManager(10400): 	at org.chromium.content.browser.input.ImeAdapterImpl.updateState(chromium-TrichromeWebViewGoogle6432.apk-stable-447211487:32)
[        ] V/InputMethodManager(10400): 	at android.os.MessageQueue.nativePollOnce(Native Method)
[        ] V/InputMethodManager(10400): 	at android.os.MessageQueue.next(MessageQueue.java:335)
[        ] V/InputMethodManager(10400): 	at android.os.Looper.loopOnce(Looper.java:161)
[        ] V/InputMethodManager(10400): 	at android.os.Looper.loop(Looper.java:288)
[        ] V/InputMethodManager(10400): 	at android.app.ActivityThread.main(ActivityThread.java:7842)
[        ] V/InputMethodManager(10400): 	at java.lang.reflect.Method.invoke(Native Method)
[        ] V/InputMethodManager(10400): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
[        ] V/InputMethodManager(10400): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
[        ] W/InputMethodManager(10400): Ignoring showSoftInput() as view=com.pichillilorenzo.flutter_inappwebview.in_app_webview.InAppWebView{c5bb4f2 VFEDHVCL. .F...... 0,0-1080,1911} is not served.
```

Steps to reproduce:
1. Create a new flutter app.
2. Add plugins to the **pubspec.yaml** file: **webview_flutter: ^2.0.13** or **flutter_inappwebview: ^5.3.2**
3. Add the webview to the widget tree:
```
InAppWebView(
        key: webViewKey,
        initialUrlRequest:
            URLRequest(url: Uri.parse("https://google.com")),
        onConsoleMessage: (controller, consoleMessage) {
          print(consoleMessage);
        },
      ),
```
or
```
WebView(
        initialUrl: 'https://google.com'
      ),
```
4. Build and launch the app.
5. Tap the google's search bar and you will see the exception in logs.

Flutter doctor:
```
[✓] Flutter (Channel stable, 2.2.2, on Linux, locale en_US.UTF-8)
    • Flutter version 2.2.2 at /home/holland/tools/flutter
    • Framework revision d79295af24 (3 months ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/holland/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at:
      /home/holland/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7
      351085/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 4.2)
    • Android Studio at /home/holland/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7351085
    • Flutter plugin version 60.1.1
    • Dart plugin version 202.8531
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at /home/holland/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/211.7442.40
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 211.7727

[✓] Connected device (1 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64 • Android 12 (API 31) (emulator)

! Doctor found issues in 1 category.
```

Old issues: 
[43000](https://github.com/flutter/flutter/issues/43000)
[38375](https://github.com/flutter/flutter/issues/38375)

**Comment by TahaTesser** [comment]
Hi @hsalazarl 
Thanks for filing the issue, the issue is only reproducible with using non-hybrid composition (aka Virtual Displays) on Android 12

### Reproducible code sample

<details> 
<summary>complete minimal runnable code sample</summary>

```dart
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  State<Home> createState() => _HomeState();
}

class _HomeState extends State<Home> {

@override
void initState() {
  super.initState();
  //  if (Platform.isAndroid) WebView.platform = SurfaceAndroidWebView();

}

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: WebView(
        initialUrl: 'https://google.com'
      ),

      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}
``` 

</details>


### Pubspec.yaml
```yaml
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  webview_flutter: ^2.0.13
```

### Logs

<details> 
<summary>logs</summary> 
	
```console
```
	
</details>

|  `stable`  | `master` |
| :---: |:---: |
|  ❗️  |   ❗️  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.22000.194], locale en-US)
    • Flutter version 2.5.0 at C:\Users\Taha\Code\flutter_stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (9 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Taha\Code\android-sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\android-sdk
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31702.278
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.60.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.26.0

[✓] Connected device (5 available)
    • SM M025F (mobile)            • R9ZR205XX0A   • android-arm    • Android 11 (API 30)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22000.194]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 93.0.4577.82
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 93.0.961.47

• No issues found!
```

```console
[✓] Flutter (Channel master, 2.6.0-6.0.pre.115, on Microsoft Windows [Version 10.0.22000.194], locale en-US)
    • Flutter version 2.6.0-6.0.pre.115 at C:\Users\Taha\Code\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb185d73ce (21 hours ago), 2021-09-16 18:23:22 +0200
    • Engine revision 5a09f16031
    • Dart version 2.15.0 (build 2.15.0-110.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Taha\Code\android-sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\android-sdk
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31702.278
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.60.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.26.0

[✓] Connected device (6 available)
    • SM M025F (mobile)            • R9ZR205XX0A   • android-arm     • Android 11 (API 30)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64     • Android 12 (API 31) (emulator)
    • Windows (desktop)            • windows       • windows-x64     • Microsoft Windows [Version 10.0.22000.194]
    • Windows (UWP) (desktop)      • winuwp        • windows-uwp-x64 •
    • Chrome (web)                 • chrome        • web-javascript  • Google Chrome 93.0.4577.82
    • Edge (web)                   • edge          • web-javascript  • Microsoft Edge 93.0.961.47

• No issues found!
```
		
</details>

✅: No Issue ❗️: Issue reproduced

Thanks for filing the issue

**Comment by hsalazarl** [comment]
@TahaTesser thank you for your answer.
So you think a change is required on webview_flutter plugin side in order to use hybrid composition? or will a fix be applied to Virtual Display?

Thank you.

**Comment by hsalazarl** [comment]
@TahaTesser please disregard my last comment on webview_flutter. Was not aware that plugin had an option to set the platform view mode.

**Comment by winterdl** [comment]
<img width="776" alt="Screen Shot 2021-09-23 at 11 48 48 AM" src="https://user-images.githubusercontent.com/302480/134456017-d522a0e4-4f79-47af-ba91-83633d481b56.png">

```
flutter doctor -v
[✓] Flutter (Channel beta, 2.6.0-5.2.pre, on macOS 11.5.2 20G95 darwin-x64, locale en-US)
    • Flutter version 2.6.0-5.2.pre at /Volumes/MacData/dev/fvm/2.5.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 400608f101 (7 days ago), 2021-09-15 15:50:26 -0700
    • Engine revision 1d521d89d8
    • Dart version 2.15.0 (build 2.15.0-82.2.beta)
```

**Comment by yapcwed** [comment]
I'm experiencing the same issue on my Pixel 5. Switching to _Hybrid composition mode_ as [described in the README](https://pub.dev/packages/webview_flutter) solved the issue. I have yet to check the performance impact on Android < 10, though. 

@TahaTesser Is there an ETA for the fix? Also could you please add the `p: webview-keyboard` label to this issue so that it shows up when following the keyboard issues link from the webview_flutter README? Thx!

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale en-CH)
    • Flutter version 2.5.3 at /Users/wederch/Library/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (4 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4
```

**Comment by SkywalkerDarren** [comment]
```
[+2870 ms] V/InputMethodManager(31235): b/117267690: Display ID mismatch found. ViewRootImpl displayId=5 InputMethodManager displayId=0. Use the right InputMethodManager instance to avoid performance overhead.
[        ] V/InputMethodManager(31235): java.lang.Throwable
[        ] V/InputMethodManager(31235): 	at android.view.inputmethod.InputMethodManager.getFallbackInputMethodManagerIfNecessary(InputMethodManager.java:549)
[        ] V/InputMethodManager(31235): 	at android.view.inputmethod.InputMethodManager.showSoftInput(InputMethodManager.java:1625)
[        ] V/InputMethodManager(31235): 	at android.view.inputmethod.InputMethodManager.showSoftInput(InputMethodManager.java:1617)
[        ] V/InputMethodManager(31235): 	at TK.d(Unknown Source:10)
[        ] V/InputMethodManager(31235): 	at org.chromium.content.browser.input.ImeAdapterImpl.v(Unknown Source:117)
[        ] V/InputMethodManager(31235): 	at org.chromium.content.browser.input.ImeAdapterImpl.updateState(Unknown Source:225)
[        ] V/InputMethodManager(31235): 	at android.os.MessageQueue.nativePollOnce(Native Method)
[        ] V/InputMethodManager(31235): 	at android.os.MessageQueue.next(MessageQueue.java:335)
[        ] V/InputMethodManager(31235): 	at android.os.Looper.loopOnce(Looper.java:161)
[        ] V/InputMethodManager(31235): 	at android.os.Looper.loop(Looper.java:288)
[        ] V/InputMethodManager(31235): 	at android.app.ActivityThread.main(ActivityThread.java:7839)
[        ] V/InputMethodManager(31235): 	at java.lang.reflect.Method.invoke(Native Method)
[        ] V/InputMethodManager(31235): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
[        ] V/InputMethodManager(31235): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
[        ] W/InputMethodManager(31235): Ignoring showSoftInput() as view=io.flutter.plugins.webviewflutter.WebViewHostApiImpl$InputAwareWebViewPlatformView{988a70e VFEDHVC.. .F...... 0,0-1440,2919} is not served.
[        ] I/AssistStructure(31235): Flattened final assist data: 248 bytes, containing 1 windows, 2 views
```

```
[✓] Flutter (Channel stable, 2.5.3, on Manjaro Linux 5.10.70-1-MANJARO, locale zh_CN.UTF-8)
    • Flutter version 2.5.3 at /home/darren/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (5 周前), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/darren/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = /home/darren/Android/Sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version openjdk version "11.0.10" 2021-01-19
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/google-chrome-stable

[✓] Linux toolchain - develop for Linux desktop
    • clang version 13.0.0
    • cmake version 3.21.4
    • ninja version 1.10.2
    • pkg-config version 1.8.0

[✓] Android Studio (version 2020.3)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 61.2.2
    • Dart plugin version 203.8452
    • Java version openjdk version "11.0.10" 2021-01-19

[✓] Connected device (3 available)
    • Pixel 6 Pro (mobile) • 19051FDEE001RV • android-arm64  • Android 12 (API 31)
    • Linux (desktop)      • linux          • linux-x64      • Manjaro Linux 5.10.70-1-MANJARO
    • Chrome (web)         • chrome         • web-javascript • Google Chrome 96.0.4664.45

• No issues found!
```

**Comment by SuhwanCha** [comment]
Still same issue

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
```

**Comment by parkgrrr** [comment]
I also have this issue, and when I switch to hybrid composition mode the app freezes as documented in this issue. I do not know of a workaround for my app, as separate bugs exist in both webviews. https://github.com/flutter/flutter/issues/86157

**Comment by giaur500** [comment]
I am getting the same issue. Any news? Please provide some workaround.

**Comment by shinlh** [comment]
Any updates about this issue?

**Comment by crayonxiaoxin** [comment]
I am getting the same issue.

**Comment by vbuberen** [comment]
Would like to add some information about the issue for those, who also affected. I believe that if the project has minSDK higher than 19 `webview_flutter` will switch to virtual displays, instead of hybrid composition despite readme file claiming that hybrid composition is turned on by default. 

I work on a project where I changed minSDK to 21 a few weeks ago (earlier had 19) and users with Android 12 started reporting that keyboard doesn't appear for them. What helped me is forcing hybrid composition manually:

```
@override
  void initState() {
    if (Platform.isAndroid) WebView.platform = SurfaceAndroidWebView();
    super.initState();
  }
```
Only after this change keyboard started to appear on Android 12 devices as well as the exception mentioned in the issue disappeared.

**Comment by PawanFyers** [comment]
Same issue on `flutter_webview: 3.0.1` using Flutter 2.8.0 & 2.8.1

**Comment by shamerKill** [comment]
> Would like to add some information about the issue for those, who also affected. I believe that if the project has minSDK higher than 19 `webview_flutter` **BEFORE 3.0.0** version will not use hybrid composition despite readme file claiming that hybrid composition is turned on by default.
> 
> I work on a project where I changed minSDK to 21 a few weeks ago (earlier had 19) and users with Android 12 started reporting that keyboard doesn't appear for them. What helped me is forcing hybrid composition manually:
> 
> ```
> @override
>   void initState() {
>     if (Platform.isAndroid) WebView.platform = SurfaceAndroidWebView();
>     super.initState();
>   }
> ```
> 
> Only after this change keyboard started to appear on Android 12 devices as well as the exception mentioned in the issue disappeared.
> 
> So those affected should check that their `flutter_webview` version is updated to `3.0.0` or use the code I provided.
> 
> The reason I can't update to 3.0.0 and not use it? Because of dependencies like `flutter_html`, which aren't compatible with `flutter_webview: 3.0.0` yet.

In this way, I solved my problem. Thank you

**Comment by henriquezanfa** [comment]
Using the `flutter_inappwebview` I was able to fix this issue by setting `useHybridComposition: true`. Thanks to [this comment](https://github.com/pichillilorenzo/flutter_inappwebview/issues/1083#issuecomment-1057181846).

```
InAppWebView(
    initialOptions: InAppWebViewGroupOptions(
        android: AndroidInAppWebViewOptions(
            useHybridComposition: true,
        ),
   ),
),
```

**Comment by GauravCalidig** [comment]
[This](https://github.com/flutter/flutter/issues/90207#issuecomment-1104398320) worked for me as well in Android 12

**Comment by him123** [comment]
> Using the `flutter_inappwebview` I was able to fix this issue by setting `useHybridComposition: true`. Thanks to [this comment](https://github.com/pichillilorenzo/flutter_inappwebview/issues/1083#issuecomment-1057181846).
> 
> ```
> InAppWebView(
>     initialOptions: InAppWebViewGroupOptions(
>         android: AndroidInAppWebViewOptions(
>             useHybridComposition: true,
>         ),
>    ),
> ),
> ```

It works for me.....Thanks so much for sharing

**Comment by 94wogus-quantit** [comment]
> Using the `flutter_inappwebview` I was able to fix this issue by setting `useHybridComposition: true`. Thanks to [this comment](https://github.com/pichillilorenzo/flutter_inappwebview/issues/1083#issuecomment-1057181846).
> 
> ```
> InAppWebView(
>     initialOptions: InAppWebViewGroupOptions(
>         android: AndroidInAppWebViewOptions(
>             useHybridComposition: true,
>         ),
>    ),
> ),
> ```

it is not works for me....

**Comment by mozerrr** [comment]
Problem repeated on android 12L / api 32.

**Comment by GHO5TMEDO** [comment]
Still having this issue with no fix...
