### ISSUE TITLE
Engine presubmits flaky on gradle network errors.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#90220]
This was [encountered on CI recently](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8835969220283165777/+/u/build_android_profile__default_clang_x64_gen_snapshot_/build_android_profile_default_clang_x64_gen_snapshot/stdout) while Gradle tried to fetch the Netty package.

```
python3 ../../flutter/testing/rules/run_gradle.py /b/s/w/ir/cache/builder/src/flutter/testing/scenario_app/android lint --no-daemon -Pflutter_jar=/b/s/w/ir/cache/builder/src/out/android_profile/flutter.jar -Pout_dir=/b/s/w/ir/cache/builder/src/out/android_profile/scenario_app --project-cache-dir=/b/s/w/ir/cache/builder/src/out/android_profile/scenario_app/.gradle --gradle-user-home=/b/s/w/ir/cache/builder/src/out/android_profile/scenario_app/.gradle -Plibapp=/b/s/w/ir/cache/builder/src/out/android_profile/gen/flutter/testing/scenario_app/android/libs

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Did not resolve 'io.netty:netty-resolver:4.1.34.Final' which is part of the dependency lock state
   > Could not resolve io.netty:netty-resolver:4.1.34.Final.
     Required by:
         project :
      > Could not resolve io.netty:netty-resolver:4.1.34.Final.
         > Could not get resource 'https://jcenter.bintray.com/io/netty/netty-resolver/4.1.34.Final/netty-resolver-4.1.34.Final.pom'.
            > Could not GET 'https://jcenter.bintray.com/io/netty/netty-resolver/4.1.34.Final/netty-resolver-4.1.34.Final.pom'.
               > Read timed out
   > Could not resolve io.netty:netty-resolver:4.1.34.Final.
     Required by:
         project : > io.netty:netty-transport:4.1.34.Final
      > Could not resolve io.netty:netty-resolver:4.1.34.Final.
         > Could not get resource 'https://jcenter.bintray.com/io/netty/netty-resolver/4.1.34.Final/netty-resolver-4.1.34.Final.pom'.
            > Could not GET 'https://jcenter.bintray.com/io/netty/netty-resolver/4.1.34.Final/netty-resolver-4.1.34.Final.pom'.
               > Read timed out

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 24s
Traceback (most recent call last):
  File "../../flutter/testing/rules/run_gradle.py", line 46, in <module>
    sys.exit(main())
  File "../../flutter/testing/rules/run_gradle.py", line 37, in main
    subprocess.check_output(
  File "/b/s/w/ir/cipd_bin_packages/cpython3/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/b/s/w/ir/cipd_bin_packages/cpython3/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/b/s/w/ir/cache/builder/src/gradle/bin/gradle', 'lint', '--no-daemon', '-Pflutter_jar=/b/s/w/ir/cache/builder/src/out/android_profile/flutter.jar', '-Pout_dir=/b/s/w/ir/cache/builder/src/out/android_profile/scenario_app', '--project-cache-dir=/b/s/w/ir/cache/builder/src/out/android_profile/scenario_app/.gradle', '--gradle-user-home=/b/s/w/ir/cache/builder/src/out/android_profile/scenario_app/.gradle', '-Plibapp=/b/s/w/ir/cache/builder/src/out/android_profile/gen/flutter/testing/scenario_app/android/libs']' returned non-zero exit status 1.
ninja: build stopped: subcommand failed.

```

**Comment by chinmaygarde** [comment]
cc @blasten @dnfield

**Comment by blasten** [comment]
@godofredoc I think the Gradle cache isn't enabled for the engine, right? do you remember where this is configured?

**Comment by whesse** [comment]
Our Flutter builder in Dart CI is also failing on the android engine build with this error, so we will want to enable the Gradle cache for it as well.  We had 4 failures on 2021-09-16 06:00 UTC to 15:00 UTC, none before or after that.
https://ci.chromium.org/p/dart/builders/ci.sandbox/flutter-engine-linux

**Comment by godofredoc** [comment]
The cache is already in the .ci.yaml file. Already there https://github.com/flutter/engine/blob/master/.ci.yaml#L33 the only thing that's missing is setting up the following env variables in the building step:

```
    env['GRADLE_USER_HOME'] = self.m.path['cache'].join('gradle')
    env['GRADLE_OPTS'] = '-Dorg.gradle.daemon=false'
```
