### ISSUE TITLE
Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/canvaskit/surface_factory.dart:111:12 _cache.contains(surface) is not true     

### ISSUE THREAD

**Issue by anasssanba1** [flutter/flutter#90231]
at Object.throw_ [as throw] (http://localhost:50036/dart_sdk.js:5061:11)     at Object.assertFailed (http://localhost:50036/dart_sdk.js:4986:15)     at _engine.SurfaceFactory.new.isLive (http://localhost:50036/dart_sdk.js:139913:51)     at _engine.Surface.new.[_contextLostListener] (http://localhost:50036/dart_sdk.js:139641:19)

**Comment by anasssanba1** [comment]
idon't have any issue i just want to report this

**Comment by darshankawar** [comment]
@anasssanba1 
Would be good to provide more details on this issue by sharing your `flutter doctor -v` and a code as when does it throw this issue. That way we can make it actionable. Just providing error message won't help much.

**Comment by TahaTesser** [comment]
duplicate of https://github.com/flutter/flutter/issues/90236
