### ISSUE TITLE
Flutter Web : "Should never encounter KeyData when transitMode is rawKeyData."

### ISSUE THREAD

**Issue by Joseph0717** [flutter/flutter#90249]
version
Flutter 2.5.0 • channel stable • https://github.com/flutter/flutter.git 
Framework • revision 4cc385b4b8 (9 days ago) • 2021-09-07 23:01:49 -0700
Engine • revision f0826da7ef
Tools • Dart 2.14.0

Flutter channels:
  master
  dev
  beta
* stable

```

TextEditingController username = TextEditingController();

TextField(
                                  controller: username,
                                  style: TextStyle(
                                    fontSize: 16.sp,
                                    fontWeight: FontWeight.bold,
                                    color: Color(0xff333333),
                                  ),
                                  cursorColor: Color(0xff000000),
                                  decoration: InputDecoration(
                                    hintText: '请输入用户名',
                                    hintStyle: TextStyle(
                                      fontSize: 14.sp,
                                      fontWeight: FontWeight.bold,
                                      color: Color(0xffb8bdc6),
                                    ),
                                    isCollapsed: true,
                                    contentPadding: EdgeInsets.symmetric(
                                      vertical: 10.h,
                                      horizontal: 0.w,
                                    ),
                                    border: OutlineInputBorder(
                                      borderRadius: BorderRadius.circular(10.r),
                                      borderSide: BorderSide.none,
                                    ),
                                    icon: Row(
                                      mainAxisSize: MainAxisSize.min,
                                      children: [
                                        SizedBox(
                                          width: 50.w,
                                          child: Text(
                                            '用户名',
                                            style: TextStyle(
                                              fontSize: 16.sp,
                                              fontWeight: FontWeight.bold,
                                              color: Color(0xff333333),
                                            ),
                                          ),
                                        ),
                                        Padding(
                                          padding: EdgeInsets.only(left: 10.w),
                                          child: Container(
                                            width: 2.w,
                                            height: 10.h,
                                            color: Color(0xffb8bdc6),
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ),
```

```
Error: Assertion failed:
..\…\services\hardware_keyboard.dart:787
false
"Should never encounter KeyData when transitMode is rawKeyData."
    at Object.throw_ [as throw] (http://localhost:55289/dart_sdk.js:5061:11)
    at Object.assertFailed (http://localhost:55289/dart_sdk.js:4986:15)
    at hardware_keyboard.KeyEventManager.new.handleKeyData (http://localhost:55289/packages/flutter/src/services/restoration.dart.lib.js:5334:28)
    at http://localhost:55289/dart_sdk.js:160131:47
    at Object.invoke (http://localhost:55289/dart_sdk.js:179656:7)
    at _engine.EnginePlatformDispatcher.__.invokeOnKeyData (http://localhost:55289/dart_sdk.js:160131:17)
    at _engine.KeyboardBinding.__.[_onKeyData] (http://localhost:55289/dart_sdk.js:158922:49)
```

![image](https://user-images.githubusercontent.com/25415733/133738611-6b4add66-7568-481b-8b12-3a5c4568b1ef.png)

**Comment by Joseph0717** [comment]
all TextField error

**Comment by maheshmnj** [comment]
Hi @Joseph0717, Thanks for filing the issue. There's already an open issue describing this case https://github.com/flutter/flutter/issues/90249. Please follow up there for further updates closing this issue as a duplicate.
If you disagree feel free to write in the comments and I will reopen it.

Thank you.

**Comment by Joseph0717** [comment]
OK,Thank you.
