### ISSUE TITLE
Flutter has exited unexpectedly - after upgrading Flutter on stable channel

### ISSUE THREAD

**Issue by Salby** [flutter/flutter#90259]
After upgrading Flutter on the stable channel I am unable to use any tools that interact with my app, such as running `flutter pub get` or `flutter test`, `flutter analyze` etc.

I get an error log that seems to indicate that the problem is which the localizations package, but the flutter_tools package isn't in my app's directory, and the problem persists after running `flutter pub cache repair`.

## Logs

<details>
<summary>Logs</summary>

```
```
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter --no-color pub get

## exception

_CastError: Null check operator used on a null value

```
#0      _generateSelectMethod (package:flutter_tools/src/localizations/gen_l10n.dart:308:40)
#1      _generateMethod (package:flutter_tools/src/localizations/gen_l10n.dart:386:12)
#2      LocalizationsGenerator._generateBaseClassFile.<anonymous closure> (package:flutter_tools/src/localizations/gen_l10n.dart:1092:14)
#3      MappedIterator.moveNext (dart:_internal/iterable.dart:391:20)
#4      Iterable.join (dart:core/iterable.dart:364:23)
#5      LocalizationsGenerator._generateBaseClassFile (package:flutter_tools/src/localizations/gen_l10n.dart:1105:41)
#6      LocalizationsGenerator._generateCode (package:flutter_tools/src/localizations/gen_l10n.dart:1187:46)
#7      LocalizationsGenerator.writeOutputFiles (package:flutter_tools/src/localizations/gen_l10n.dart:1262:47)
#8      generateLocalizations (package:flutter_tools/src/localizations/gen_l10n.dart:69:9)
#9      GenerateLocalizationsTarget.build (package:flutter_tools/src/build_system/targets/localizations.dart:59:5)
#10     _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:836:27)
<asynchronous suspension>
#11     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:603:16)
<asynchronous suspension>
#12     generateLocalizationsSyntheticPackage (package:flutter_tools/src/dart/generate_synthetic_packages.dart:58:30)
<asynchronous suspension>
#13     PackagesGetCommand._runPubGet (package:flutter_tools/src/commands/packages.dart:130:7)
<asynchronous suspension>
#14     PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:172:5)
<asynchronous suspension>
#15     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#17     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#18     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
<asynchronous suspension>
#19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#20     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
<asynchronous suspension>
#21     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#22     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#23     main (package:flutter_tools/executable.dart:92:3)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel stable, 2.5.0, on Arch Linux 5.14.3-arch1-1, locale en_DK.UTF-8)
    • Flutter version 2.5.0 at /home/salby/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (9 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /opt/android-sdk
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /opt/android-sdk
    • Java binary at: /opt/android-studio-beta/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2020.3)
    • Android Studio at /opt/android-studio-beta
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Android Studio (version 2020.3)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 60.1.2
    • Dart plugin version 203.8292
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

```
```

</details>

**Comment by Salby** [comment]
I resolved the problem by not attempting to generate localized "select" strings, as they appear to no longer be supported.
