### ISSUE TITLE
Exception caught by services library (hardware_keyboard.dart)

### ISSUE THREAD

**Issue by sergeysemko** [flutter/flutter#90255]
## Steps to Reproduce

I am using an Android device (PM80) with a built-in 1D / 2D laser barcode scanner. Scanner works in Keyboard Emulation Mode.
To get the exception, I just scan a barcode with an uppercase letter (e.g. ABC-abc-1234)
Exception reproduces in simple Flutter app

<details>
  <summary>
════════ Exception caught by services library ══════════════════════════════════
A KeyUpEvent is dispatched, but the state shows that the physical key is pressed on a different logical key. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#0ef75(physicalKey: PhysicalKeyboardKey#700e1(usbHidUsage: "0x000700e1", debugName: "Shift Left"), logicalKey: LogicalKeyboardKey#00404(keyId: "0x100000404", keyLabel: "Cut", debugName: "Cut"), character: null, timeStamp: 0:31:05.779105, synthesized) and the recorded logical key LogicalKeyboardKey#00102(keyId: "0x200000102", keyLabel: "Shift Left", debugName: "Shift Left")
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 448 pos 13: '_pressedKeys[event.physicalKey] == event.logicalKey'
</summary>

```
[ +109 ms] --------- beginning of main
                    09-17 09:51:57.110 W/ResourceType( 1187): ResTable_typeSpec entry count inconsistent: given 19, previously 21
[  +10 ms] executing: /Users/user/Library/Android/sdk/platform-tools/adb -s 7e5be9f shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez
enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true com.ossystem.okpad/com.ossystem.okpad.MainActivity
[+1406 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.ossystem.okpad/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
[+1434 ms] W/FlutterActivityAndFragmentDelegate(10590): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
[ +502 ms] Observatory URL on device: http://127.0.0.1:38135/5cxm3SGSIQM=/
[   +1 ms] executing: /Users/user/Library/Android/sdk/platform-tools/adb -s 7e5be9f forward tcp:0 tcp:38135
[  +11 ms] 51589
[        ] Forwarded host port 51589 to device port 38135 for Observatory
[  +10 ms] Caching compiled dill
[ +106 ms] Connecting to service protocol: http://127.0.0.1:51589/5cxm3SGSIQM=/
[ +766 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:51589/5cxm3SGSIQM=/.
[ +398 ms] DDS is listening at http://127.0.0.1:51594/hTGcHt5qIpQ=/.
[  +97 ms] Successfully connected to service protocol: http://127.0.0.1:51589/5cxm3SGSIQM=/
[ +195 ms] DevFS: Creating new filesystem on the device (null)
[  +97 ms] DevFS: Created new filesystem on the device (file:///data/user/0/com.ossystem.okpad/code_cache/okpadXHBSYT/okpad/)
[   +3 ms] Updating assets
[ +173 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
[   +8 ms] Syncing files to device PM80...
[   +4 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +4 ms] <- recompile package:okpad/main.dart d4cda698-4426-424f-b465-84eb87ccaddb
[        ] <- d4cda698-4426-424f-b465-84eb87ccaddb
[ +185 ms] Updating files.
[        ] DevFS: Sync finished
[   +3 ms] Syncing files to device PM80... (completed in 197ms)
[   +2 ms] Synced 0.0MB.
[  +11 ms] <- accept
[  +16 ms] Connected to _flutterView/0xb8ff8c10.
[  +34 ms] Flutter run key commands.
[  +10 ms] r Hot reload. 🔥🔥🔥
[   +4 ms] R Hot restart.
[        ] h List all available interactive commands.
[   +1 ms] d Detach (terminate "flutter run" but leave application running).
[   +1 ms] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] 💪 Running with sound null safety 💪
[   +4 ms] An Observatory debugger and profiler on PM80 is available at: http://127.0.0.1:51594/hTGcHt5qIpQ=/
[ +159 ms] Activating Dart DevTools...
[+5102 ms] I/flutter (10590): No observables detected in the build method of Observer
[        ] I/flutter (10590): #3      _SettingsScreenState._buildBody (package:okpad/ui/settings/settings.dart:109:21)
[  +32 ms] Activating Dart DevTools... (completed in 5.1s)
[+2545 ms] I/flutter (10590): No observables detected in the build method of Observer
[        ] I/flutter (10590): #3      _SettingsScreenState._buildBody (package:okpad/ui/settings/settings.dart:109:21)
[ +378 ms] The Flutter DevTools debugger and profiler on PM80 is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:51594/hTGcHt5qIpQ=/
[+9952 ms] 
                    ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
                    The following _CastError was thrown during a platform message callback:
                    Null check operator used on a null value
                    
                    When the exception was thrown, this was the stack:
                    #0      KeyEventManager._convertRawEventAndStore (package:flutter/src/services/hardware_keyboard.dart:888:64)
                    #1      RawKeyboard.handleRawKeyEvent (package:flutter/src/services/raw_keyboard.dart:677:17)
                    #2      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:821:33)
                    #3      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:73:49)
                    #4      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:72:47)
                    #5      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:379:35)
                    #6      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:376:46)
                    #7      _invoke2.<anonymous closure> (dart:ui/hooks.dart:205:15)
                    #11     _invoke2 (dart:ui/hooks.dart:204:10)
                    #12     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
                    #13     _Channel.push (dart:ui/channel_buffers.dart:132:31)
                    #14     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
                    #15     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:544:22)
                    #16     _dispatchPlatformMessage (dart:ui/hooks.dart:92:31)
                    (elided 3 frames from dart:async)
                    ════════════════════════════════════════════════════════════════════════════════════════════════════
[  +31 ms] 
           Another exception was thrown: Null check operator used on a null value
[  +39 ms] 
           Another exception was thrown: Null check operator used on a null value
[  +32 ms] 
           Another exception was thrown: Null check operator used on a null value
[  +30 ms] 
           Another exception was thrown: Null check operator used on a null value
[  +25 ms] 
           Another exception was thrown: Null check operator used on a null value
[  +28 ms] 
           Another exception was thrown: Null check operator used on a null value
[  +23 ms] 
           Another exception was thrown: Null check operator used on a null value
[  +23 ms] 
           Another exception was thrown: Null check operator used on a null value
[  +21 ms] 
           Another exception was thrown: Null check operator used on a null value
[  +25 ms] 
           Another exception was thrown: Null check operator used on a null value
[  +21 ms] 
           Another exception was thrown: Null check operator used on a null value
[  +31 ms] 
           Another exception was thrown: Null check operator used on a null value
[  +23 ms] 
           Another exception was thrown: Null check operator used on a null value
[  +22 ms] 
           Another exception was thrown: Null check operator used on a null value
[  +22 ms] 
           Another exception was thrown: Null check operator used on a null value
[  +18 ms] 
           Another exception was thrown: Null check operator used on a null value
[  +24 ms] 
           Another exception was thrown: Null check operator used on a null value
[  +22 ms] 
           Another exception was thrown: Null check operator used on a null value
[  +22 ms] 
           Another exception was thrown: Null check operator used on a null value
[  +20 ms] 
           Another exception was thrown: Null check operator used on a null value
[  +47 ms] 
           Another exception was thrown: Null check operator used on a null value
[  +27 ms] 
           Another exception was thrown: Null check operator used on a null value
[  +21 ms] 
           Another exception was thrown: Null check operator used on a null value
[  +19 ms] 
           Another exception was thrown: Null check operator used on a null value
[  +19 ms] 
           Another exception was thrown: Null check operator used on a null value
[  +80 ms] 
           Another exception was thrown: A KeyUpEvent is dispatched, but the state shows that the physical key is pressed on a different logical key. If this occurs in real application, please
report this bug
           to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event:
KeyUpEvent#c00bb(physicalKey:
           PhysicalKeyboardKey#700e1(usbHidUsage: "0x000700e1", debugName: "Shift Left"), logicalKey: LogicalKeyboardKey#00404(keyId: "0x100000404", keyLabel: "Cut", debugName: "Cut"), character:
null,
           timeStamp: 0:35:54.271630, synthesized) and the recorded logical key LogicalKeyboardKey#00102(keyId: "0x200000102", keyLabel: "Shift Left", debugName: "Shift Left")
[+16238 ms] Application finished.
```

```
[✓] Flutter (Channel stable, 2.5.0, on Mac OS X 10.13.6 17G14033 darwin-x64, locale en-UA)
    • Flutter version 2.5.0 at /Users/vadimzakharkin/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (9 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/vadimzakharkin/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.60.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • PM80 (mobile) • 7e5be9f • android-arm    • Android 6.0.1 (API 23)
    • Chrome (web)  • chrome  • web-javascript • Google Chrome 93.0.4577.82
```

</details>

**Comment by darshankawar** [comment]
@sergeysemko 
There's a similar open issue describing your case, https://github.com/flutter/flutter/issues/89982
Please follow-up there for updates.
Closing this as duplicate.
