### ISSUE TITLE
[palette_generator] PaletteGenerator.fromImageProvider(image) ,image Black or white will report an error

### ISSUE THREAD

**Issue by zhouxiaofu** [flutter/flutter#90266]
palette_generator 0.3.1

palette_generator PaletteGenerator.fromImageProvider(image) ,image Black or white will report an error

 **PaletteGenerator.fromImageProvider (package:palette_generator/palette_generator.dart:261:46)**

Unhandled Exception: NoSuchMethodError: The method 'resolve' was called on null.
E/flutter (26539): Receiver: null
E/flutter (26539): Tried calling: resolve(Instance of 'ImageConfiguration')
E/flutter (26539): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:63:5)
E/flutter (26539): #1      PaletteGenerator.fromImageProvider (package:palette_generator/palette_generator.dart:261:46)

![image](https://user-images.githubusercontent.com/34471928/133784992-37aa3f76-b89a-4709-b937-08191f7c2157.png)

**Comment by danagbemava-nc** [comment]
Hi @zhouxiaofu, 

Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Thank you

**Comment by zhouxiaofu** [comment]
E:\flutter\flutter_issues_90266>flutter doctor -v
[√] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.19041.1165], locale zh-CN)
    • Flutter version 2.5.0 at E:\appData\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (9 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at E:\appData\Android\Sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at E:\appData\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at E:\appData\JetBrains\IntelliJ IDEA 2019.3.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (4 available)
    • M2011K2C (mobile)                  • 192.168.0.199:5555 • android-arm64  • Android 11 (API 30)
    • Android SDK built for x86 (mobile) • emulator-5554      • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome             • web-javascript • Google Chrome 93.0.4577.82
    • Edge (web)                         • edge               • web-javascript • Microsoft Edge 89.0.774.68

! Doctor found issues in 1 category.




Here is my code to determine that pure white or black images do not get color  

I clicked three buttons in turn , This is the log I printed out

I/flutter (25547): test white image
E/flutter (25547): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value
E/flutter (25547): #0      _MyHomePageState.build.<anonymous closure>.<anonymous closure> (package:flutter_issues_90266/main.dart:54:95)
E/flutter (25547): #1      _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter (25547): #2      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (25547): <asynchronous suspension>
E/flutter (25547): 
I/flutter (25547): test black image
E/flutter (25547): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value
E/flutter (25547): #0      _MyHomePageState.build.<anonymous closure>.<anonymous closure> (package:flutter_issues_90266/main.dart:66:95)
E/flutter (25547): #1      _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter (25547): #2      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (25547): <asynchronous suspension>
E/flutter (25547): 
I/flutter (25547): test normal image
I/flutter (25547): paletteGenerator.dominantColor.color Color(0xff2a2925)


**demo code**



`import 'package:flutter/material.dart';
import 'package:palette_generator/palette_generator.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter issues 90266',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter issues 90266'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            TextButton(
                child: const Text("test white image"),
                onPressed: () {
                  print("test white image");
                  ImageProvider imageProvider =
                  const NetworkImage("https://i.etsystatic.com/14403653/c/600/476/0/61/il/26b691/1836932087/il_340x270.1836932087_43om.jpg");
                  PaletteGenerator.fromImageProvider(imageProvider)
                      .then((paletteGenerator) {
                    print(
                        'paletteGenerator.dominantColor.color ${paletteGenerator.dominantColor!.color}');
                  });
                }),
            TextButton(
                child: const Text("test black image"),
                onPressed: () {
                  print("test black image");
                  ImageProvider imageProvider =
                  const NetworkImage("https://wallpaper.dog/large/10835229.jpg");
                  PaletteGenerator.fromImageProvider(imageProvider)
                      .then((paletteGenerator) {
                    print(
                        'paletteGenerator.dominantColor.color ${paletteGenerator.dominantColor!.color}');
                  });
                }),
            TextButton(
                child: const Text("test normal image"),
                onPressed: () {
                  print("test normal image");
                  ImageProvider imageProvider =
                  const NetworkImage("https://i.pinimg.com/originals/e8/49/34/e849348523f2075d8656a2fae259bcfd.png");
                  PaletteGenerator.fromImageProvider(imageProvider)
                      .then((paletteGenerator) {
                    print(
                        'paletteGenerator.dominantColor.color ${paletteGenerator.dominantColor!.color}');
                  });
                }),
          ],
        ),
      ),
    );
  }
}
`

**Comment by zhouxiaofu** [comment]
E:\flutter\flutter_issues_90266>flutter doctor -v
[√] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.19041.1165], locale zh-CN)
• Flutter version 2.5.0 at E:\appData\flutter
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision 4cc385b (9 days ago), 2021-09-07 23:01:49 -0700
• Engine revision f0826da7ef
• Dart version 2.14.0
• Pub download mirror https://pub.flutter-io.cn
• Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
• Android SDK at E:\appData\Android\Sdk
X cmdline-tools component is missing
Run path/to/sdkmanager --install "cmdline-tools;latest"
See https://developer.android.com/studio/command-line for more details.
X Android license status unknown.
Run flutter doctor --android-licenses to accept the SDK licenses.
See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
• Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
• Android Studio at E:\appData\Android\Android Studio
• Flutter plugin can be installed from:
https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
https://plugins.jetbrains.com/plugin/6351-dart
• Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
• IntelliJ at E:\appData\JetBrains\IntelliJ IDEA 2019.3.3
• Flutter plugin can be installed from:
https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (4 available)
• M2011K2C (mobile) • 192.168.0.199:5555 • android-arm64 • Android 11 (API 30)
• Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)
• Chrome (web) • chrome • web-javascript • Google Chrome 93.0.4577.82
• Edge (web) • edge • web-javascript • Microsoft Edge 89.0.774.68

! Doctor found issues in 1 category.

Here is my code to determine that pure white or black images do not get color

I clicked three buttons in turn , This is the log I printed out

I/flutter (25547): test white image
E/flutter (25547): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value
E/flutter (25547): #0 _MyHomePageState.build.. (package:flutter_issues_90266/main.dart:54:95)
E/flutter (25547): #1 _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter (25547): #2 _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (25547):
E/flutter (25547):
I/flutter (25547): test black image
E/flutter (25547): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value
E/flutter (25547): #0 _MyHomePageState.build.. (package:flutter_issues_90266/main.dart:66:95)
E/flutter (25547): #1 _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter (25547): #2 _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (25547):
E/flutter (25547):
I/flutter (25547): test normal image
I/flutter (25547): paletteGenerator.dominantColor.color Color(0xff2a2925)

demo code

`import 'package:flutter/material.dart';
import 'package:palette_generator/palette_generator.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter issues 90266',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter issues 90266'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            TextButton(
                child: const Text("test white image"),
                onPressed: () {
                  print("test white image");
                  ImageProvider imageProvider =
                  const NetworkImage("https://i.etsystatic.com/14403653/c/600/476/0/61/il/26b691/1836932087/il_340x270.1836932087_43om.jpg");
                  PaletteGenerator.fromImageProvider(imageProvider)
                      .then((paletteGenerator) {
                    print(
                        'paletteGenerator.dominantColor.color ${paletteGenerator.dominantColor!.color}');
                  });
                }),
            TextButton(
                child: const Text("test black image"),
                onPressed: () {
                  print("test black image");
                  ImageProvider imageProvider =
                  const NetworkImage("https://wallpaper.dog/large/10835229.jpg");
                  PaletteGenerator.fromImageProvider(imageProvider)
                      .then((paletteGenerator) {
                    print(
                        'paletteGenerator.dominantColor.color ${paletteGenerator.dominantColor!.color}');
                  });
                }),
            TextButton(
                child: const Text("test normal image"),
                onPressed: () {
                  print("test normal image");
                  ImageProvider imageProvider =
                  const NetworkImage("https://i.pinimg.com/originals/e8/49/34/e849348523f2075d8656a2fae259bcfd.png");
                  PaletteGenerator.fromImageProvider(imageProvider)
                      .then((paletteGenerator) {
                    print(
                        'paletteGenerator.dominantColor.color ${paletteGenerator.dominantColor!.color}');
                  });
                }),
          ],
        ),
      ),
    );
  }
}
`

**Comment by zhouxiaofu** [comment]
> 嗨@周小福，
> 
> 能否请您提供您`flutter doctor -v`和`flutter run --verbose`日志，以及[最小的完整可重复的代码示例](https://stackoverflow.com/help/minimal-reproducible-example)？
> 
> 谢谢

**Comment by zhouxiaofu** [comment]
> Hi @zhouxiaofu,
> 
> Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
> 
> Thank you

I have provided the code

**Comment by danagbemava-nc** [comment]
Hi @zhouxiaofu, 
The reason you get the `Unhandled Exception: Null check operator used on a null value` is because you're forcing a value that could be null to produce a value and in the case of the white and black, the `PaletteColor` is null. 

If you should change the `print` statement to

`print('paletteGenerator.dominantColor.color ${paletteGenerator.dominantColor?.color}')`. 

It shouldn't be throwing any exceptions. 

But I suspect that your actual issue is the fact that it is unable to produce the dominant colors for the white and black images. 

Am I correct in this assumption?
