### ISSUE TITLE
Flutter For Windows throws an exception when pressing any key on the window.

### ISSUE THREAD

**Issue by xiao-cao-x** [flutter/flutter#90263]
I pressed a key on the window , and Flutter throws me an exception.

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: 'package:flutter/src/services/hardware_keyboard.dart': Failed assertion: line 787 pos 16: 'false': Should never encounter KeyData when transitMode is rawKeyData.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      KeyEventManager.handleKeyData (package:flutter/src/services/hardware_keyboard.dart:787:16)
#3      PlatformDispatcher._dispatchKeyData.<anonymous closure> (dart:ui/platform_dispatcher.dart:375:61)
#4      _invoke2.<anonymous closure> (dart:ui/hooks.dart:205:15)
#5      _rootRun (dart:async/zone.dart:1428:13)
#6      _CustomZone.run (dart:async/zone.dart:1328:19)
#7      _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#8      _invoke2 (dart:ui/hooks.dart:204:10)
#9      PlatformDispatcher._dispatchKeyData (dart:ui/platform_dispatcher.dart:373:5)
#10     _dispatchKeyData (dart:ui/hooks.dart:104:31)
```

`flutter doctor -v`
```
[✓] Flutter (Channel beta, 2.6.0-5.2.pre, on Microsoft Windows [Version 10.0.19043.1149], locale zh-CN)
    • Flutter version 2.6.0-5.2.pre at D:\SDK\Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 400608f101 (2 days ago), 2021-09-15 15:50:26 -0700
    • Engine revision 1d521d89d8
    • Dart version 2.15.0 (build 2.15.0-82.2.beta)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at D:\SDK\Android
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = D:\SDK\Android
    • Java binary at: D:\IDE\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Enterprise 2019 16.11.3)
    • Visual Studio at D:\IDE\Microsoft Visual Studio\2019\Enterprise
    • Visual Studio Enterprise 2019 version 16.11.31702.278
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.1)
    • Android Studio at D:\IDE\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at D:\IDE\IDEA
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5284.31

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1149]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 93.0.4577.82
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 93.0.961.47

• No issues found!
```

**Comment by maheshmnj** [comment]
@xiao-cao-x Thanks for filing the issue. There is already a similar issue describing this case https://github.com/flutter/flutter/issues/90194. Please follow up there for further updates closing this issue as a duplicate. If you disagree feel free to write in the comments and I will reopen it.

Thank you.

**Comment by xiao-cao-x** [comment]
> @xiao-cao-x Thanks for filing the issue. There is already a similar issue describing this case #90194. Please follow up there for further updates closing this issue as a duplicate. If you disagree feel free to write in the comments and I will reopen it.
> 
> Thank you.

What I encountered is the exception raised by pressing any key on the main window (Windows), `there is nothing on the window`, not the exception raised on the TextField.

He appears on sdk: ">=2.14.0 <3.0.0"
I returned the SDK version to 2.1.12 and the problem disappeared.

I think it's different.

**Comment by xiao-cao-x** [comment]
> What I encountered is the exception raised by pressing any key on the main window (Windows, `there is nothing on the window`), not the exception raised on the TextField.

This includes alt+tab cutting the screen to the Flutter program window

**Comment by maheshmnj** [comment]
@xiao-cao-x  thanks for the clarification, reopening the issue for further investigation.

**Comment by maheshmnj** [comment]
Hi @xiao-cao-x, I could not reproduce the issue on the beta channel. verified on windows as well as mac. Heres what I did I ran a flutter sample app with a text field in the center

- pressed any keys without interacting with text field
- or pressed alt+tab on windows to switch window

Could you please try switching to the latest master channel and see if that fixes the issue.

You can switch to master by running 

```
flutter channel master
flutter upgrade
``` 

If the issue persists, please share the exact steps to reproduce the issue.

<details>
<summary>flutter doctor -v</summary>


```
[✓] Flutter (Channel beta, 2.6.0-5.2.pre, on Microsoft Windows [Version 10.0.22000.194], locale en-US)
    • Flutter version 2.6.0-5.2.pre at C:\Users\Taha\Code\flutter_beta
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 400608f101 (2 days ago), 2021-09-15 15:50:26 -0700
    • Engine revision 1d521d89d8
    • Dart version 2.15.0 (build 2.15.0-82.2.beta)
```

```
[✓] Flutter (Channel beta, 2.6.0-5.2.pre, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.6.0-5.2.pre at /Users/mahesh/Documents/flutter_beta
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 400608f101 (2 days ago), 2021-09-15 15:50:26 -0700
    • Engine revision 1d521d89d8
    • Dart version 2.15.0 (build 2.15.0-82.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • iPad Pro (11-inch) (3rd generation) (mobile) • 4367E72A-10EB-46BA-9E12-D89A8F0DA157 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)                              • macos                                • darwin-arm64   • macOS 11.6 20G165
      darwin-arm
    • Chrome (web)                                 • chrome                               • web-javascript • Google Chrome
      93.0.4577.82

• No issues found!
```
</details>

**Comment by xiao-cao-x** [comment]
I tried clearing the cache and the program and then running pub get, and then compiling, solved the problem.
May be caused by this library
```yaml
fluent_ui:
 git: https://github.com/bdlukaa/fluent_ui.git
```
