### ISSUE TITLE
Key handling issue on ubuntu 21.04 flutter web

### ISSUE THREAD

**Issue by KaushickSArgekar** [flutter/flutter#90273]
When I launch the app and switch between vs code and debug chrome tab this error occurs

Error: Assertion failed:
../…/services/hardware_keyboard.dart:787
false
"Should never encounter KeyData when transitMode is rawKeyData."
    at Object.throw_ [as throw] (http://localhost:5000/dart_sdk.js:5061:11)
    at Object.assertFailed (http://localhost:5000/dart_sdk.js:4986:15)
    at hardware_keyboard.KeyEventManager.new.handleKeyData (http://localhost:5000/packages/flutter/src/services/restoration.dart.lib.js:5334:28)
    at http://localhost:5000/dart_sdk.js:160131:47
    at Object.invoke (http://localhost:5000/dart_sdk.js:179656:7)

**Comment by TahaTesser** [comment]
Hi @KaushickSArgekar 
Thanks for the issue, a similar issue has been filed before for web https://github.com/flutter/flutter/issues/90249 by @Joseph0717 and @Mayank-9018 also reproduced this issue https://github.com/flutter/flutter/issues/89729#issuecomment-922287878 but unable to determine how to reproduce it, even tho error is thrown keyboard input works.

Linux desktop issue is caused by a hot restart or changing keyboard, keyboard input stops working.

> When I launch the app and switch between vs code and debug chrome tab this error occurs

I tried to reproduce the issue using the steps here but the console has no error on the latest `stable` channel 

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.5.1, on Zorin OS 16 5.11.0-34-generic, locale en_US.UTF-8)
    • Flutter version 2.5.1 at /home/taha/Code/flutter_stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (3 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/taha/Code/android-sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = /home/taha/Code/android-sdk
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 60.1.2
    • Dart plugin version 203.8292
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Zorin OS 16 5.11.0-34-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 93.0.4577.82

• No issues found!
```
	
</details>


Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample and steps to reproduce the issue, and complete `flutter run -d chrome  --verbose` logs running the minimal code sample?
Thank you
