### ISSUE TITLE
Windows app crashes when typing combining characters (like ^)

### ISSUE THREAD

**Issue by mregnauld** [flutter/flutter#90344]
## Steps to Reproduce

1. Create a Flutter app for Windows, with a `TextFormField` in it.
2. Launch the app and type, in that order, something like: a^b

**Expected results:**

I should see "a^b" in my `TextFormField`.

**Actual results:**

My app crashes when I type the character "^"
**_Important:_** for some reason, the app doesn't crash if I type that character first

<details>
  <summary>Logs</summary>

Logs when crash:

```
flutter: ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
flutter: The following RangeError was thrown during a platform message callback:
flutter: Invalid value: Not in inclusive range 0..1114111: 2147483742
flutter: 
flutter: When the exception was thrown, this was the stack:
flutter: #0      new String.fromCharCode (dart:core-patch/string_patch.dart:45:5)
flutter: #1      new RawKeyEvent.fromMessage (package:flutter/src/services/raw_keyboard.dart:377:32)
flutter: #2      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:815:46)
flutter: #3      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:73:49)
flutter: #4      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:72:47)
flutter: #5      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:379:35)
flutter: #6      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:376:46)
flutter: #7      _invoke2.<anonymous closure> (dart:ui/hooks.dart:205:15)
flutter: #11     _invoke2 (dart:ui/hooks.dart:204:10)
flutter: #12     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
flutter: #13     _Channel.push (dart:ui/channel_buffers.dart:132:31)
flutter: #14     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
flutter: #15     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:544:22)
flutter: #16     _dispatchPlatformMessage (dart:ui/hooks.dart:92:31)
flutter: (elided 3 frames from dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

flutter doctor -v:

```
[√] Flutter (Channel master, 2.5.0-7.0.pre.110, on Microsoft Windows [version 10.0.19043.1165], locale fr-FR)
    • Flutter version 2.5.0-7.0.pre.110 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3572a7e8b7 (5 weeks ago), 2021-08-17 11:52:05 -0700
    • Engine revision 7dc8eba6ae
    • Dart version 2.15.0 (build 2.15.0-15.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\AndroidSDK
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31605.320
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] IntelliJ IDEA Community Edition (version 2021.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.2
    • Flutter plugin version 59.0.4
    • Dart plugin version 212.4746.57

[√] Connected device (4 available)
    • SM M515F (mobile) • RF8NC0PSMMV • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [version 10.0.19043.1165]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 93.0.4577.82
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 92.0.902.78

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment]
@mregnauld 
I see that you are on older version of master (`2.5.0-7.0.pre.110`).
Can you upgrade to latest (`2.6.0-6.0.pre.147`) and try the same steps to see if issue still persists or not ?

**Comment by mregnauld** [comment]
Sure, as soon as the `flutter upgrade` command decides to work....
