### ISSUE TITLE
Using WidgetTester.enterText on a disabled TextFormField breaks future calls

### ISSUE THREAD

**Issue by MatthewLM** [flutter/flutter#90345]
## Steps to Reproduce

1. Use `enterText` on a `TextFormField`. See that it works.
2. Disable and renable the form and see that `enterText` continues to work.
3. This time, disable the field and use `enterText`. See that does not change the text value, as expected.
4. Re-enable the field and see that `enterText` doesn't work despite being enabled again.

`enterText` only breaks after having used it on a disabled field and then re-enabling it.

Here is an example of a failing test when the commented line is uncommented:

```
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

class TestFieldDisable extends StatefulWidget {
    @override
    State<StatefulWidget> createState() => TestFieldDisableState();
}

class TestFieldDisableState extends State<TestFieldDisable> {

    bool _enabled = true;

    set enabled(bool to) => setState(() {
        _enabled = to;
    });

    @override
    Widget build(BuildContext context) => TextFormField(enabled: _enabled);

}

void main() {

    testWidgets("TextFormField should accept text when renabled", (tester) async {

        await tester.pumpWidget(
            MaterialApp(home: Scaffold(body: TestFieldDisable()))
        );

        final disablerState = tester.state<TestFieldDisableState>(
            find.byType(TestFieldDisable)
        );

        final fieldFinder = find.byType(TextFormField);
        final fieldState = tester.state<FormFieldState>(fieldFinder);

        await tester.enterText(fieldFinder, "one");
        await tester.pump();
        expect(fieldState.value, "one");

        disablerState.enabled = false;
        await tester.pump();

        // await tester.enterText(fieldFinder, "two"); // Uncomment to break
        await tester.pump();
        expect(fieldState.value, "one");

        disablerState.enabled = true;
        await tester.pump();

        await tester.enterText(fieldFinder, "two");
        await tester.pump();
        expect(fieldState.value, "two");

    });

}
```

**Expected results:**

`enterText` should continue to work when the field is enabled again.

**Actual results:**

The final `expect` fails due to remaining as "one" instead of "two".

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 2.5.1, on Debian GNU/Linux 10 (buster) 4.19.0-17-amd64, locale en_GB.UTF-8)
    • Flutter version 2.5.1 at...
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (2 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2
```

</details>

**Comment by darshankawar** [comment]
@MatthewLM 
Thanks for the report. I am getting below exception upon running the test:

```
package:flutter_tools/src/test/flutter_tester_device.dart 224:73  FlutterTesterTestDevice.finished
===== asynchronous gap ===========================
dart:async/future.dart                                            Future.any.onValue

Failed to load "/Users/dhs/Documents/NCFlutter/ios_bug/test/widget_test.dart": Shell subprocess ended cleanly. Did main() call exit()?
```

Is this the one you are seeing ?

**Comment by MatthewLM** [comment]
@darshankawar When I run without uncommenting the line I get `All tests passed!`. Otherwise I get:

```
00:02 +0: TextFormField should accept text when renabled
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
  Expected: 'two'
  Actual: 'one'
   Which: is different.
          Expected: two
            Actual: one
                    ^
           Differ at offset 0

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (field_disable_test.dart:53:9)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  field_disable_test.dart line 53
The test description was:
  TextFormField should accept text when renabled
════════════════════════════════════════════════════════════════════════════════════════════════════
00:02 +0 -1: TextFormField should accept text when renabled [E]
  Test failed. See exception logs above.
  The test description was: TextFormField should accept text when renabled

00:02 +0 -1: Some tests failed.
```

**Comment by darshankawar** [comment]
Verified by uncommenting the line and on latest stable and master but still see the same exception:

```
package:flutter_tools/src/test/flutter_tester_device.dart 224:73  FlutterTesterTestDevice.finished
===== asynchronous gap ===========================
dart:async/future.dart                                            Future.any.onValue

Failed to load "/Users/dhs/Documents/NCFlutter/ios_bug/test/widget_test.dart": Shell subprocess ended cleanly. Did main() call exit()?
```
I see that you are on Linux. Not sure if that's a factor though.

**Comment by darshankawar** [comment]
@MatthewLM 
No worries. I think I had some cache issues in the project. Running `flutter clean` solved it for me and then I was able to run the tests which throws same error as you mentioned.

<details>
<summary>console error log</summary>



```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
  Expected: 'two'
  Actual: 'one'
   Which: is different.
          Expected: two
            Actual: one
                    ^
           Differ at offset 0

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///Users/dhs/Documents/NCFlutter/ios_bug/test/widget_test.dart:59:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///Users/dhs/Documents/NCFlutter/ios_bug/test/widget_test.dart line 59
The test description was:
  TextFormField should accept text when renabled
════════════════════════════════════════════════════════════════════════════════════════════════════
00:02 +0 -1: TextFormField should accept text when renabled [E]                                                                                                                          
  Test failed. See exception logs above.
  The test description was: TextFormField should accept text when renabled
  
00:02 +0 -1: Some tests failed.                                                                                                                                                          
dhs@Dhss-MacBook-Pro ios_bug % 

```


</details>

<details>
<summary> stable, master flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.5.1, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.5.1 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (2 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 93.0.4577.63

• No issues found!

[✓] Flutter (Channel master, 2.6.0-6.0.pre.127, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.6.0-6.0.pre.127 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ec3bd9edc4 (2 hours ago), 2021-09-16 20:02:02 -0700
    • Engine revision 72f08e4da3
    • Dart version 2.15.0 (build 2.15.0-116.0.dev)

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.4 19E2269
      darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 93.0.4577.63

• No issues found!




```

</details>

**Comment by tirth-patel-nc** [comment]
# Triage Report

I was able to reproduce the issue using the provided code sample on both the `stable (3.29.3)` and `master (3.32.0-1.0.pre.463)` channels.

<img width="1456" alt="Image" src="https://github.com/user-attachments/assets/89cd28ed-378c-4485-962c-6d72a28d3aeb" />

<details>
<summary>Code Sample (Same as OP)</summary>

```dart
import 'package:flutter/material.dart';

class TestFieldDisable extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => TestFieldDisableState();
}

class TestFieldDisableState extends State<TestFieldDisable> {
  bool _enabled = true;

  set enabled(bool to) => setState(() {
    _enabled = to;
  });

  @override
  Widget build(BuildContext context) => TextFormField(enabled: _enabled);
}
```

</details>

<details>
<summary>Test File (Same as OP)</summary>

```dart
import 'package:flutter_test/flutter_test.dart';
import 'package:flutter/material.dart';
import 'package:hello_world/main.dart';

void main() {
  testWidgets("TextFormField should accept text when renabled", (tester) async {
    await tester.pumpWidget(
      MaterialApp(home: Scaffold(body: TestFieldDisable())),
    );

    final disablerState = tester.state<TestFieldDisableState>(
      find.byType(TestFieldDisable),
    );

    final fieldFinder = find.byType(TextFormField);
    final fieldState = tester.state<FormFieldState>(fieldFinder);

    await tester.enterText(fieldFinder, "one");
    await tester.pump();
    expect(fieldState.value, "one");

    disablerState.enabled = false;
    await tester.pump();

    await tester.enterText(fieldFinder, "two"); // Uncomment to break
    await tester.pump();
    expect(fieldState.value, "one");

    disablerState.enabled = true;
    await tester.pump();

    await tester.enterText(fieldFinder, "two");
    await tester.pump();
    expect(fieldState.value, "two");
  });
}
```

</details>

<details>
  <summary>stable (3.29.3) - flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.29.3, on macOS 15.4.1 24E263 darwin-arm64, locale
    en-IN) [970ms]
    • Flutter version 3.29.3 on channel stable at
      /Users/tirthpatel/Development/flutter_stable/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ea121f8859 (4 weeks ago), 2025-04-11 19:10:07 +0000
    • Engine revision cf56914b32
    • Dart version 3.7.2
    • DevTools version 2.42.3

[✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0)
    [855ms]
    • Android SDK at /Users/tirthpatel/Library/Android/sdk
    • Platform android-36, build-tools 36.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on
      this machine.
      To manually set the JDK path, use: `flutter config
      --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13355223-b631.42)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.3) [556ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16E140
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [9ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.3) [9ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13355223-b631.42)

[✓] VS Code (version 1.99.3) [8ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available) [5.5s]
    • macOS (desktop)                 • macos                 • darwin-arm64   •
      macOS 15.4.1 24E263 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         •
      macOS 15.4.1 24E263 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript •
      Google Chrome 135.0.7049.115

[✓] Network resources [559ms]
    • All expected network resources are available.

• No issues found!
```

</details>

<details>
  <summary>master (3.32.0-1.0.pre.463) - flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 3.32.0-1.0.pre.463, on macOS 15.4.1 24E263 darwin-arm64, locale en-IN) [1,676ms]
    • Flutter version 3.32.0-1.0.pre.463 on channel master at /Users/tirthpatel/Development/flutter_master/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 194fb17d2a (2 hours ago), 2025-05-07 20:28:23 -0700
    • Engine revision 194fb17d2a
    • Dart version 3.9.0 (build 3.9.0-97.0.dev)
    • DevTools version 2.46.0-dev.0

[✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0) [761ms]
    • Android SDK at /Users/tirthpatel/Library/Android/sdk
    • Emulator version 35.4.9.0 (build_id 13025442) (CL:N/A)
    • Platform android-36, build-tools 36.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13355223-b631.42)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.3) [438ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16E140
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [7ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.3) [7ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13355223-b631.42)

[✓] VS Code (version 1.99.3) [6ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.110.0

[✓] Connected device (2 available) [5.5s]
    • macOS (desktop) • macos  • darwin-arm64   • macOS 15.4.1 24E263 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 135.0.7049.115

[✓] Network resources [774ms]
    • All expected network resources are available.

• No issues found!
```

</details>
