### ISSUE TITLE
I can't know where is the issue (Bad state: No element)

### ISSUE THREAD

**Issue by albearmousa** [flutter/flutter#90342]
**main.dart**

```
import 'package:flutter/material.dart';
import 'package:meals_app/screens/categories_screen.dart';
import 'package:meals_app/screens/category_meals_screen.dart';
import 'package:meals_app/screens/meal_detail_screen.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.pink,
        accentColor: Colors.amber,
        canvasColor: Color.fromRGBO(225, 254, 229, 1),
        fontFamily: 'Raleway',
        textTheme: ThemeData.light().textTheme.copyWith(
              bodyText2: TextStyle(
                color: Color.fromRGBO(20, 51, 51, 1),
              ),
              bodyText1: TextStyle(
                color: Color.fromRGBO(20, 51, 51, 1),
              ),
              headline6: TextStyle(
                  fontSize: 20,
                  fontFamily: 'RobotoCondensed',
                  fontWeight: FontWeight.bold,),
            ),
      ),
      initialRoute: '/',
      routes: {
        '/': (context) => CategoriesScreen(),
        CategoryMealsScreen.routeName: (context) => CategoryMealsScreen(),
        MealDetailScreen.routeName: (context) => MealDetailScreen(),
      },
      onGenerateRoute: (settings) {
        print(settings.arguments);
      },
      onUnknownRoute: (settings) {
        return MaterialPageRoute(builder: (ctx) => CategoriesScreen());
      },
    );
  }
}


```
**MealDetailScreen:**

```
import 'package:flutter/material.dart';
import 'package:meals_app/dummy_data.dart';

class MealDetailScreen extends StatelessWidget {
  static const routeName = '/meal_detail_screen';

  @override
  Widget build(BuildContext context) {
    final mealId = ModalRoute.of(context)!.settings.arguments.toString();
    final selectedMeal = DUMMY_MEALS.firstWhere(
      (meal) => meal.imageUrl == 'mealId',
    );
    return Scaffold(
      appBar: AppBar(
        title: Text('$mealId'),
      ),
      body: Column(
        children: [
          Container(
            height: 300,
            width: double.infinity,
            child: Image.network(
              selectedMeal.imageUrl,
              fit: BoxFit.cover,
            ),
          ),
        ],
      ),
    );
  }
}

```

**The Exception:**

```
======== Exception caught by widgets library =======================================================
The following StateError was thrown building MealDetailScreen(dirty, dependencies: [_ModalScopeStatus]):
Bad state: No element

The relevant error-causing widget was: 
  MealDetailScreen file:///C:/Users/lenovo/AndroidStudioProjects/meals_app/lib/main.dart:38:50
When the exception was thrown, this was the stack: 
#0      ListMixin.firstWhere (dart:collection/list.dart:167:5)
#1      MealDetailScreen.build (package:meals_app/screens/meal_detail_screen.dart:10:38)
#2      StatelessElement.build (package:flutter/src/widgets/framework.dart:4648:28)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4574:15)
#4      Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
...
====================================================================================================

```

**Comment by Pilaba** [comment]
**DUMMY_MEALS.firstWhere** throws **"Bad state: No element"**  when no elements found in the list.

**Comment by darshankawar** [comment]
@albearmousa 
This looks like a question that can be asked on support channels like StackOverflow.
Closing from here as this is more of a help question rather than bug.
