### ISSUE TITLE
Can't gather performance timeline using flutter drive

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#90410]
I am trying to write a test that uses [`watchPerformance`](https://api.flutter.dev/flutter/package-integration_test_integration_test/IntegrationTestWidgetsFlutterBinding/watchPerformance.html) to write the correct `build/integration_response_data.json` file for reading in `chrome://tracing`.

The test passes when using `flutter test integration_test/app_test.dart`, but not when I run `flutter drive` to specify a custom `integrationDriver` from the `integration_test_driver` package. 

I also wonder if it's possible to specify the custom `integrationDriver` using the `flutter test` command, not `flutter drive`, since this seems to be the new way to run `integration_test` tests.

cc: @dnfield @csells 

## Steps to Reproduce

1. Create the scrolling app from the [Handle scrolling](https://flutter.dev/docs/cookbook/testing/integration/scrolling) cookbook article:

```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp(
    items: List<String>.generate(10000, (i) => "Item $i"),
  ));
}

class MyApp extends StatelessWidget {
  final List<String> items;

  const MyApp({Key? key, required this.items}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    const title = 'Long List';

    return MaterialApp(
      title: title,
      home: Scaffold(
        appBar: AppBar(
          title: const Text(title),
        ),
        body: ListView.builder(
          // Add a key to the ListView. This makes it possible to
          // find the list and scroll through it in the tests.
          key: const Key('long_list'),
          itemCount: items.length,
          itemBuilder: (context, index) {
            return ListTile(
              title: Text(
                items[index],
                // Add a key to the Text widget for each item. This makes
                // it possible to look for a particular item in the list
                // and verify that the text is correct
                key: Key('item_${index}_text'),
              ),
            );
          },
        ),
      ),
    );
  }
}
```

2. Create a file, `integration_test/app_test.dart`:

```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';

// The application under test.
import 'package:integration_test_experiments/main.dart';

void main() {
  final binding = IntegrationTestWidgetsFlutterBinding.ensureInitialized()
      as IntegrationTestWidgetsFlutterBinding;

  testWidgets('Scroll to item 50', (WidgetTester tester) async {
    // Build our app and trigger a frame.
    await tester.pumpWidget(MyApp(
      items: List<String>.generate(10000, (i) => "Item $i"),
    ));

    final listFinder = find.byType(Scrollable);
    final itemFinder = find.byKey(const ValueKey('item_50_text'));

    await binding.watchPerformance(
      () async {
        // Scroll until the item to be found appears.
        await tester.scrollUntilVisible(
          itemFinder,
          500.0,
          scrollable: listFinder,
        );
      },
      reportKey: 'scrolling_summary',
    );

    // Verify that the item contains the correct text.
    expect(itemFinder, findsOneWidget);
  });
}
```

3. Add a file, `test_driver/perf_driver.dart` that writes the response data in separate timeline files (https://github.com/flutter/flutter/pull/88604):

```dart
import 'package:integration_test/integration_test_driver.dart';

Future<void> main() {
  return integrationDriver(
    responseDataCallback: (data) async {
      if (data != null) {
        for (var entry in data.entries) {
          print('Writing ${entry.key} to the disk.');
          await writeResponseData(
            entry.value as Map<String, dynamic>,
            testOutputFilename: entry.key,
          );
        }
      }
    },
  );
}
```

Run the integration test using the `perf_driver.dart` driver configuration:

```
flutter drive \
  --driver=test_driver/perf_driver.dart \
  --target=integration_test/app_test.dart \
  -d <DEVICE_ID>
```

Observe exception:

```
flutter drive \
  --driver=test_driver/integration_driver.dart \
  --target=integration_test/app_test.dart -d 13181FDD400226
Running "flutter pub get" in integration_test_experiments...        808ms
Running Gradle task 'assembleDebug'...                              4.5s
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...                 3.6s
VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:60052/Z7lQhlgRbYw=/
VMServiceFlutterDriver: Isolate found with number: 3018735296192043
VMServiceFlutterDriver: Isolate is paused at start.
VMServiceFlutterDriver: Attempting to resume isolate
I/flutter (16092): 00:00 +0: Scroll to item 50
VMServiceFlutterDriver: Connected to Flutter application.
I/flutter (16092): ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
I/flutter (16092): The following SocketException was thrown running a test:
I/flutter (16092): OS Error: Connection refused, errno = 111, address = localhost, port = 41680
I/flutter (16092): 
I/flutter (16092): When the exception was thrown, this was the stack:
I/flutter (16092): #0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:677:35)
I/flutter (16092): #1      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1680:26)
I/flutter (16092): #2      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27:23)
I/flutter (16092): #3      Socket._startConnect (dart:io-patch/socket_patch.dart:1891:22)
I/flutter (16092): #4      Socket.startConnect (dart:io/socket.dart:738:21)
I/flutter (16092): #5      _ConnectionTarget.connect (dart:_http/http_impl.dart:2439:18)
I/flutter (16092): #6      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2805:12)
I/flutter (16092): #7      _HttpClient._getConnection (dart:_http/http_impl.dart:2810:12)
I/flutter (16092): #8      _HttpClient._openUrl (dart:_http/http_impl.dart:2694:12)
I/flutter (16092): #9      _HttpClient.openUrl (dart:_http/http_impl.dart:2568:7)
I/flutter (16092): #10     _WebSocketImpl.connect (dart:_http/websocket_impl.dart:1027:24)
I/flutter (16092): #11     WebSocket.connect (dart:_http/websocket.dart:379:22)
I/flutter (16092): #12     vmServiceConnectUri (package:vm_service/vm_service_io.dart:32:44)
I/flutter (16092): #13     IntegrationTestWidgetsFlutterBinding.enableTimeline
(package:integration_test/integration_test.dart:244:26)
I/flutter (16092): <asynchronous suspension>
I/flutter (16092): #14     IntegrationTestWidgetsFlutterBinding.traceTimeline
(package:integration_test/integration_test.dart:269:5)
I/flutter (16092): <asynchronous suspension>
I/flutter (16092): #15     IntegrationTestWidgetsFlutterBinding._runAndGetGCInfo
(package:integration_test/integration_test.dart:321:34)
I/flutter (16092): <asynchronous suspension>
I/flutter (16092): #16     IntegrationTestWidgetsFlutterBinding.watchPerformance
(package:integration_test/integration_test.dart:376:43)
I/flutter (16092): <asynchronous suspension>
I/flutter (16092): #17     main.<anonymous closure>
(file:///Users/ryjohn/code/github/johnpryan/integration_test_experiments/integration_test/app_test.dart:23:5)
I/flutter (16092): <asynchronous suspension>
I/flutter (16092): #18     testWidgets.<anonymous closure>.<anonymous closure>
(package:flutter_test/src/widget_tester.dart:176:15)
I/flutter (16092): <asynchronous suspension>
I/flutter (16092): #19     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:817:5)
I/flutter (16092): <asynchronous suspension>
I/flutter (16092): 
I/flutter (16092): The test description was:
I/flutter (16092):   Scroll to item 50
I/flutter (16092): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (16092): 00:03 +0: Scroll to item 50 [E]
I/flutter (16092):   Test failed. See exception logs above.
I/flutter (16092):   The test description was: Scroll to item 50
I/flutter (16092):   
I/flutter (16092): Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
I/flutter (16092): For example, 'dart test --chain-stack-traces'.
I/flutter (16092): 00:03 +0 -1: (tearDownAll)
I/flutter (16092): 00:03 +1 -1: Some tests failed.
Failure Details:
Failure in method: Scroll to item 50
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following SocketException was thrown running a test:
OS Error: Connection refused, errno = 111, address = localhost,
port = 41680

When the exception was thrown, this was the stack:
#0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:677:35)
#1      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1680:26)
#2      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27:23)
#3      Socket._startConnect (dart:io-patch/socket_patch.dart:1891:22)
#4      Socket.startConnect (dart:io/socket.dart:738:21)
#5      _ConnectionTarget.connect (dart:_http/http_impl.dart:2439:18)
#6      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2805:12)
#7      _HttpClient._getConnection (dart:_http/http_impl.dart:2810:12)
#8      _HttpClient._openUrl (dart:_http/http_impl.dart:2694:12)
#9      _HttpClient.openUrl (dart:_http/http_impl.dart:2568:7)
#10     _WebSocketImpl.connect (dart:_http/websocket_impl.dart:1027:24)
#11     WebSocket.connect (dart:_http/websocket.dart:379:22)
#12     vmServiceConnectUri (package:vm_service/vm_service_io.dart:32:44)
#13     IntegrationTestWidgetsFlutterBinding.enableTimeline (package:integration_test/integration_test.dart:244:26)
<asynchronous suspension>
#14     IntegrationTestWidgetsFlutterBinding.traceTimeline (package:integration_test/integration_test.dart:269:5)
<asynchronous suspension>
#15     IntegrationTestWidgetsFlutterBinding._runAndGetGCInfo (package:integration_test/integration_test.dart:321:34)
<asynchronous suspension>
#16     IntegrationTestWidgetsFlutterBinding.watchPerformance (package:integration_test/integration_test.dart:376:43)
<asynchronous suspension>
#17     main.<anonymous closure> (file:///Users/ryjohn/code/github/johnpryan/integration_test_experiments/integration_test/app_test.dart:23:5)
<asynchronous suspension>
#18     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:176:15)
<asynchronous suspension>
#19     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:817:5)
<asynchronous suspension>

The test description was:
  Scroll to item 50
═════════════════════════════════════════════════════════════════

end of failure 1

```

**Comment by dnfield** [comment]
If you want to use the driver protocol, you have to have a call to `enableFlutterDriverExtension` in the application code running on the device.  It seems like that might be missing and causing a problem?

Although I wouldn't expect the socket error becuase of that. @jiahaog might have some idea here too.

**Comment by johnpryan** [comment]
Ah, right. I need to add `enableFlutterDriverExtension` for `flutter drive`. Adding it didn't seem to help with the socket error, though.

**Comment by jiahaog** [comment]
This looks like an issue with the DDS and Flutter Tools integration, cc @bkonyi 

The call to `developer.Service.getInfo().serverUri` in `package:integration_test` is returning the VM service that may not be accessible by devices that do not share the same network interface as the host (like on Android).

https://github.com/flutter/flutter/blob/a133306791fef464dcccd8e5417a0841fff35f3f/packages/integration_test/lib/integration_test.dart#L245

It can be reproduced with the following minimal example (below shows Android):

```dart
import 'dart:developer' as developer;

void main() async {
  await Future.delayed(Duration(seconds: 15));

  final vmServiceUri = await developer.Service.getInfo().serverUri;
  print('Service protocol info is $vmServiceUri');
}
```

In one terminal:

```
$ flutter run

...

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on Pixel 4a is available at: http://127.0.0.1:59997/0PsllF9SAC0=/
I/flutter (21968): Service protocol info is http://127.0.0.1:59997/0PsllF9SAC0=/
```

And in another terminal

```
$ adb logcat | grep -e Observatory -e 'Service protocol info'

09-21 13:44:55.286 21968 22013 I flutter : Observatory listening on http://127.0.0.1:40505/iGx-Iik9aKs=/
09-21 13:45:10.353 21968 21994 I flutter : Service protocol info is http://127.0.0.1:59997/0PsllF9SAC0=/
```

- `http://127.0.0.1:40505/iGx-Iik9aKs=/` is the uri of the vm service, on the device
- `http://127.0.0.1:59997/0PsllF9SAC0=/` is the uri of the vm service, accessible from the host (after forwarding by `adb forward` and dds to the above)

The `Service protocol info is http://127.0.0.1:59997/0PsllF9SAC0=/` printed above on the device via the logcat, is incorrect since this is not accessible by default from the device. `http://127.0.0.1:40505/iGx-Iik9aKs=/` should be returned instead from `developer.Service.getInfo().serverUri`.

This is because when DDS starts, it [sends a `_yieldControlToDDS` vm service call](https://github.com/dart-lang/sdk/blob/e995cb5f7cd67d39c1ee4bdbe95c8241db36725f/pkg/dds/lib/src/dds_impl.dart#L175-L177), which changes the value returned by `developer.Service.getInfo().serverUri`. Currently, this passes the URI of the vm service from the perspective of the host, which is incorrect when it is accessed via `developer.Service.getInfo().serverUri` for network calls originating from the device.

---

On a less related note, there is no need to use `enableFlutterDriverExtension` here, since the driver protocol isn't used to access the timeline in the test above. Integration tests [automatically register](https://github.com/flutter/flutter/blob/a133306791fef464dcccd8e5417a0841fff35f3f/packages/integration_test/lib/_callback_io.dart#L29-L54) a service extension that is sufficient for `flutter drive` to collect results with the `IntegrationTestDriver`.

**Comment by TahaTesser** [comment]
<details> 
<summary>logs</summary> 
	
```console
Running Gradle task 'assembleDebug'...                             21.2s
✓  Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...                 3.1s
W/DisplayEventDispatcher(21304): dispatcher 0xb400007c5bbf3610 ~ ignoring unknown event type 0x6d746f6e
W/DisplayEventDispatcher(21304): dispatcher 0xb400007c0bbd52d0 ~ ignoring unknown event type 0x6d746f6e
VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:63813/Ox-Md4v26Jw=/
VMServiceFlutterDriver: Isolate found with number: 1371214840984515
VMServiceFlutterDriver: Isolate is paused at start.
VMServiceFlutterDriver: Attempting to resume isolate
I/flutter (21304): 00:00 +0: Scroll to item 50
VMServiceFlutterDriver: Connected to Flutter application.
D/ViewRootImpl[MainActivity](21304): windowFocusChanged hasFocus=false inTouchMode=true
D/OpScreenModeManager(21304): setRefreshRate parent io.flutter.embedding.android.FlutterView{3dd8fe5 VFED.....
........ 0,0-1080,2355 #1} parent width 1080 parent height 2355 mRatio 1.2
D/OpScreenModeManager(21304): setRefreshRate view io.flutter.embedding.android.FlutterSurfaceView{7e07a29
V.E...... ........ 0,0-1080,2355} viewRate 1 width 1080 height 2355
D/OpScreenModeManager(21304): setRefreshRate parent io.flutter.embedding.android.FlutterView{3dd8fe5 VFED.....
......ID 0,0-1080,2400 #1} parent width 1080 parent height 2400 mRatio 1.2
D/OpScreenModeManager(21304): setRefreshRate view io.flutter.embedding.android.FlutterSurfaceView{7e07a29
V.E...... ......ID 0,0-1080,2400} viewRate 1 width 1080 height 2400
E/.example.triag(21304): Invalid ID 0x00000001.
D/OpScreenModeManager(21304): setRefreshRate parent io.flutter.embedding.android.FlutterView{3dd8fe5 VFED.....
........ 0,0-1080,2400 #1} parent width 1080 parent height 2400 mRatio 1.2
D/OpScreenModeManager(21304): setRefreshRate view io.flutter.embedding.android.FlutterSurfaceView{7e07a29
V.E...... ........ 0,0-1080,2400} viewRate 1 width 1080 height 2400
I/flutter (21304): ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK
╞════════════════════════════════════════════════════
I/flutter (21304): The following SocketException was thrown running a test:
I/flutter (21304): OS Error: Connection refused, errno = 111, address = localhost, port = 41716
I/flutter (21304):
I/flutter (21304): When the exception was thrown, this was the stack:
I/flutter (21304): #0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:681:35)
I/flutter (21304): #1      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1704:26)
I/flutter (21304): #2      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27:23)
I/flutter (21304): #3      Socket._startConnect (dart:io-patch/socket_patch.dart:1915:22)
I/flutter (21304): #4      Socket.startConnect (dart:io/socket.dart:738:21)
I/flutter (21304): #5      _ConnectionTarget.connect (dart:_http/http_impl.dart:2440:18)
I/flutter (21304): #6      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2806:12)
I/flutter (21304): #7      _HttpClient._getConnection (dart:_http/http_impl.dart:2811:12)
I/flutter (21304): #8      _HttpClient._openUrl (dart:_http/http_impl.dart:2695:12)
I/flutter (21304): #9      _HttpClient.openUrl (dart:_http/http_impl.dart:2569:7)
I/flutter (21304): #10     _WebSocketImpl.connect (dart:_http/websocket_impl.dart:1027:42)
I/flutter (21304): #11     WebSocket.connect (dart:_http/websocket.dart:380:22)
I/flutter (21304): #12     vmServiceConnectUri (package:vm_service/vm_service_io.dart:32:44)
I/flutter (21304): #13     IntegrationTestWidgetsFlutterBinding.enableTimeline
(package:integration_test/integration_test.dart:247:32)
I/flutter (21304): <asynchronous suspension>
I/flutter (21304): #14     IntegrationTestWidgetsFlutterBinding.traceTimeline
(package:integration_test/integration_test.dart:272:5)
I/flutter (21304): <asynchronous suspension>
I/flutter (21304): #15     IntegrationTestWidgetsFlutterBinding._runAndGetGCInfo
(package:integration_test/integration_test.dart:347:34)
I/flutter (21304): <asynchronous suspension>
I/flutter (21304): #16     IntegrationTestWidgetsFlutterBinding.watchPerformance
(package:integration_test/integration_test.dart:402:43)
I/flutter (21304): <asynchronous suspension>
I/flutter (21304): #17     main.<anonymous closure>
(file:///C:/Users/Taha/StudioProjects/triage/integration_test/app_test.dart:23:5)
I/flutter (21304): <asynchronous suspension>
I/flutter (21304): #18     testWidgets.<anonymous closure>.<anonymous closure>
(package:flutter_test/src/widget_tester.dart:170:15)
I/flutter (21304): <asynchronous suspension>
I/flutter (21304): #19     TestWidgetsFlutterBinding._runTestBody
(package:flutter_test/src/binding.dart:803:5)
I/flutter (21304): <asynchronous suspension>
I/flutter (21304):
I/flutter (21304): The test description was:
I/flutter (21304):   Scroll to item 50
I/flutter (21304):
════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (21304): 00:04 +0: Scroll to item 50 [E]
I/flutter (21304):   Test failed. See exception logs above.
I/flutter (21304):   The test description was: Scroll to item 50
I/flutter (21304):
I/flutter (21304): Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
I/flutter (21304): For example, 'dart test --chain-stack-traces'.
I/flutter (21304): 00:04 +0 -1: (tearDownAll)
I/flutter (21304): 00:04 +1 -1: Some tests failed.
Failure Details:
Failure in method: Scroll to item 50
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following SocketException was thrown running a test:
OS Error: Connection refused, errno = 111, address = localhost,
port = 41716

When the exception was thrown, this was the stack:
#0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:681:35)
#1      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1704:26)
#2      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27:23)
#3      Socket._startConnect (dart:io-patch/socket_patch.dart:1915:22)
#4      Socket.startConnect (dart:io/socket.dart:738:21)
#5      _ConnectionTarget.connect (dart:_http/http_impl.dart:2440:18)
#6      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2806:12)
#7      _HttpClient._getConnection (dart:_http/http_impl.dart:2811:12)
#8      _HttpClient._openUrl (dart:_http/http_impl.dart:2695:12)
#9      _HttpClient.openUrl (dart:_http/http_impl.dart:2569:7)
#10     _WebSocketImpl.connect (dart:_http/websocket_impl.dart:1027:42)
#11     WebSocket.connect (dart:_http/websocket.dart:380:22)
#12     vmServiceConnectUri (package:vm_service/vm_service_io.dart:32:44)
#13     IntegrationTestWidgetsFlutterBinding.enableTimeline (package:integration_test/integration_test.dart:247:32)
<asynchronous suspension>
#14     IntegrationTestWidgetsFlutterBinding.traceTimeline (package:integration_test/integration_test.dart:272:5)
<asynchronous suspension>
#15     IntegrationTestWidgetsFlutterBinding._runAndGetGCInfo (package:integration_test/integration_test.dart:347:34)
<asynchronous suspension>
#16     IntegrationTestWidgetsFlutterBinding.watchPerformance (package:integration_test/integration_test.dart:402:43)
<asynchronous suspension>
#17     main.<anonymous closure> (file:///C:/Users/Taha/StudioProjects/triage/integration_test/app_test.dart:23:5)
<asynchronous suspension>
#18     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:170:15)
<asynchronous suspension>
#19     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:803:5)
<asynchronous suspension>

The test description was:
  Scroll to item 50
═════════════════════════════════════════════════════════════════

end of failure 1
```
	
</details>


|  `stable`  | `master` |
| :---: |:---: |
|  ❗️  |   ❗️  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.5.1, on Microsoft Windows [Version 10.0.22000.194], locale en-US)
    • Flutter version 2.5.1 at C:\Users\Taha\Code\flutter_stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (4 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Taha\Code\android-sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\android-sdk
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31702.278
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.60.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.26.0

[✓] Connected device (4 available)
    • IN2011 (mobile)   • c9d8ee0c • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows  • windows-x64    • Microsoft Windows [Version 10.0.22000.194]
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 93.0.4577.82
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 93.0.961.47

• No issues found!
```

```console
[✓] Flutter (Channel master, 2.6.0-6.0.pre.161, on Microsoft Windows [Version 10.0.22000.194], locale en-US)
    • Flutter version 2.6.0-6.0.pre.161 at C:\Users\Taha\Code\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 89123e8489 (2 hours ago), 2021-09-21 00:18:03 -0700
    • Engine revision 7e94275f73
    • Dart version 2.15.0 (build 2.15.0-126.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Taha\Code\android-sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\android-sdk
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31702.278
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.60.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.26.0

[✓] Connected device (5 available)
    • IN2011 (mobile)         • c9d8ee0c • android-arm64   • Android 11 (API 30)
    • Windows (desktop)       • windows  • windows-x64     • Microsoft Windows [Version 10.0.22000.194]
    • Windows (UWP) (desktop) • winuwp   • windows-uwp-x64 •
    • Chrome (web)            • chrome   • web-javascript  • Google Chrome 93.0.4577.82
    • Edge (web)              • edge     • web-javascript  • Microsoft Edge 93.0.961.47

• No issues found!
```
		
</details>

✅: No Issue ❗️: Issue reproduced

Thanks for filing the issue

**Comment by dnfield** [comment]
Ah!  Yes you have to run with --no-dds

**Comment by amrgetment** [comment]
@dnfield Could you tell Flutter team to give E2E testing more attention?
As now if we support different screens sizes and platforms then E2E testing is essential for more developers
