### ISSUE TITLE
Can't build with Flutter 2.5 

### ISSUE THREAD

**Issue by samuel-utbult-oborgen** [flutter/flutter#90433]
I have tried to upgrade my project to Flutter 2.5, but when I try to build a publishable version of the project, I get the following error. There are no detailed error message explaining what went wrong and I have tried all kinds of options.

## Steps to Reproduce

1. Install Flutter inside a Docker container.
2. Copy the project into the container.
3. Run the following command: `flutter build web -v --no-sound-null-safety`

## Logs

<details>
<summary>Logs</summary>

```
Exception: Failed to compile application for the Web.
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      buildWeb (package:flutter_tools/src/web/compile.dart:82:5)
           <asynchronous suspension>
           #2      BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:117:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>
```

```                                                                                               
[✓] Flutter (Channel stable, 2.5.1, on Ubuntu 20.04.3 LTS 5.10.47-linuxkit, locale en_US)
    • Flutter version 2.5.1 at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (3 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /opt/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 93.0.4577.82

! Doctor found issues in 2 categories.
```

</details>

**Comment by TahaTesser** [comment]
Hi @samuel-utbult-oborgen 

> Copy the project into the container.


The issue looks like it is related to your project rather than Flutter on Docker, also your logs are incomplete

Can you please provide a complete reproducible minimal code sample, and complete `flutter build web -v --no-sound-null-safety` logs running the minimal code sample?
Thank you

**Comment by samuel-utbult-oborgen** [comment]
This project is fairly large and is made up of proprietary code used within a company, so it's not possible to post the entire project here. Nevertheless, I'll try to build the Flutter hello world project using the same Docker image and return later with the result when that has been done.

However, it would be reasonable to have a clear error message from the build command and not just a message describing that the build has failed.

**Comment by samuel-utbult-oborgen** [comment]
After some more digging, I found the reason why the undescriptive error was raised in the first place. The project contains a generated file containing 287,448 lines. With a certain configuration change, this line count could be lowered to 71,847, which made it so the error wasn't raised.

I'd like to point out that the reason why this generated file is necessary in the first place is because Flutter have no built in method of converting classes to JSON and vice versa. Also, Dart doesn't have proper mirroring support. Together, these issues have caused the necessity to basically have a long file checking every type and combination of generic types for the purpose of serialization and deserialization.

A great counterexample to this is C#, where classes and records can be converted to and from JSON with the built in library System.Text.Json without ever having to deal with code generation. If something similar was introduced in Flutter or Dart, it would be greatly appreciated by us and probably by a lot of other developers since JSON is one of the most common methods used to serialize data.

**Comment by navaronbracke** [comment]
> Also, Dart doesn't have proper mirroring support. Together, these issues have caused the necessity to basically have a long file checking every type and combination of generic types for the purpose of serialization and deserialization.

`dart:mirrors` is explicitly disabled for Flutter projects, since that makes tree shaking unusable, as all code is then implicitly used for things like reflection iirc.

**Comment by TahaTesser** [comment]
Hi @samuel-utbult-oborgen 

> After some more digging, I found the reason why the undescriptive error was raised in the first place. The project contains a generated file containing 287,448 lines. With a certain configuration change, this line count could be lowered to 71,847, which made it so the error wasn't raised.

Is the issue only with the web build with a large file? Can you build for other platforms like android, ios or desktop without such issues?

**Comment by samuel-utbult-oborgen** [comment]
> Hi @samuel-utbult-oborgen
> 
> > After some more digging, I found the reason why the undescriptive error was raised in the first place. The project contains a generated file containing 287,448 lines. With a certain configuration change, this line count could be lowered to 71,847, which made it so the error wasn't raised.
> 
> Is the issue only with the web build with a large file? Can you build for other platforms like android, ios or desktop without such issues?

I could run `flutter test` with the large file. However, I haven't tried to build for iOS or Android with the large file using Flutter 2.5. I haven't tried to run a development server under those conditions either. But I can try to do these things to see what happens.
