### ISSUE TITLE
App crashes when cursor is at the front of TextField and backspace is pressed

### ISSUE THREAD

**Issue by xster** [flutter/flutter#90472]
b/200629367

- Focus is on a TextField
- TextField gets rebuilt
- Cursor moves to the front
- Backspace is pressed

crashes with:

```
======== Exception caught by services library ======================================================
The following assertion was thrown during a platform message callback:
A KeyDownEvent is dispatched, but the state shows that the physical key is already pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyDownEvent#062b0(physicalKey: PhysicalKeyboardKey#00000(usbHidUsage: "0x1100000000", debugName: "Key with ID 0x1100000000"), logicalKey: LogicalKeyboardKey#00008(keyId: "0x100000008", keyLabel: "Backspace", debugName: "Backspace"), character: "�", timeStamp: 54:39:16.008167)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 437 pos 16: '!_pressedKeys.containsKey(event.physicalKey)'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack:
#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:437:16)
#3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:452:6)
#4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:543:5)
#5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:821:35)
#6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:77:49)
#7      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:76:47)
#8      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:387:35)
#9      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:384:46)
#10     _invoke2.<anonymous closure> (dart:ui/hooks.dart:205:15)
#14     _invoke2 (dart:ui/hooks.dart:204:10)
#15     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#16     _Channel.push (dart:ui/channel_buffers.dart:132:31)
#17     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#18     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:544:22)
#19     _dispatchPlatformMessage (dart:ui/hooks.dart:92:31)
(elided 5 frames from class _AssertionError and dart:async)
```

**Comment by HansMuller** [comment]
CC @dkwingsmt

**Comment by TahaTesser** [comment]
> - Focus is on a TextField
> - TextField gets rebuilt
> - Cursor moves to the front
> - Backspace is pressed

This can be reproduced with any key, just backspace, the app crashed with the F key on Windows

<details> 
<summary>logs</summary> 
	
```console
[ +134 ms] Hot restart performed in 259ms.
[        ] Performing hot restart... (completed in 260ms)
[        ] Restarted application in 270ms.
[ +675 ms] Unable to parse JSON message:
[   +1 ms] The document is empty.
[  +10 ms]
           ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY
           ╞══════════════════════════════════════════════════════════
           The following assertion was thrown during a platform message
callback:
           A KeyUpEvent is dispatched, but the state shows that the physical
key is not
           pressed. If this occurs
           in real application, please report this bug to Flutter. If this
occurs in
           unit tests, please ensure
           that simulated events follow Flutter's event model as documented
in
           `HardwareKeyboard`. This was the
           event: KeyUpEvent#327ae(physicalKey:
PhysicalKeyboardKey#70009(usbHidUsage:
           "0x00070009", debugName:
           "Key F"), logicalKey: LogicalKeyboardKey#00066(keyId:
"0x00000066",
           keyLabel: "F", debugName: "Key
           F"), character: null, timeStamp: 114:43:52.384859)
           'package:flutter/src/services/hardware_keyboard.dart':
           Failed assertion: line 441 pos 16:
           '_pressedKeys.containsKey(event.physicalKey)'

           Either the assertion indicates an error in the framework itself,
or we
           should provide substantially
           more information in this error message to help you determine and
fix the
           underlying cause.
           In either case, please report this assertion by filing a bug on
GitHub:
             https://github.com/flutter/flutter/issues/new?template=2_bug.md

           When the exception was thrown, this was the stack:
           #2      HardwareKeyboard._assertEventIsRegular.<anonymous
closure>
           (package:flutter/src/services/hardware_keyboard.dart:441:16)
           #3      HardwareKeyboard._assertEventIsRegular
           (package:flutter/src/services/hardware_keyboard.dart:452:6)
           #4      HardwareKeyboard.handleKeyEvent
           (package:flutter/src/services/hardware_keyboard.dart:543:5)
           #5      KeyEventManager.handleRawKeyMessage
           (package:flutter/src/services/hardware_keyboard.dart:821:35)
           #6      BasicMessageChannel.setMessageHandler.<anonymous closure>
           (package:flutter/src/services/platform_channel.dart:77:49)
           #7      BasicMessageChannel.setMessageHandler.<anonymous closure>
           (package:flutter/src/services/platform_channel.dart:76:47)
           #8      _DefaultBinaryMessenger.setMessageHandler.<anonymous
closure>
           (package:flutter/src/services/binding.dart:386:35)
           #9      _DefaultBinaryMessenger.setMessageHandler.<anonymous
closure>
           (package:flutter/src/services/binding.dart:383:46)
           #10     _invoke2.<anonymous closure> (dart:ui/hooks.dart:205:15)
           #14     _invoke2 (dart:ui/hooks.dart:204:10)
           #15     _ChannelCallbackRecord.invoke
(dart:ui/channel_buffers.dart:42:5)
           #16     _Channel.push (dart:ui/channel_buffers.dart:132:31)
           #17     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
           #18     PlatformDispatcher._dispatchPlatformMessage
           (dart:ui/platform_dispatcher.dart:544:22)
           #19     _dispatchPlatformMessage (dart:ui/hooks.dart:92:31)
           (elided 5 frames from class _AssertionError and dart:async)

════════════════════════════════════════════════════════════════════════════
           ════════════════════════
[  +10 ms]
           Another exception was thrown: A KeyUpEvent is dispatched, but the
state
           shows that the physical key is not pressed. If this occurs in
real
           application, please report this bug to Flutter. If this occurs in
unit
           tests, please ensure that simulated events follow Flutter's event
model as
           documented in `HardwareKeyboard`. This was the event:
           KeyUpEvent#327ae(physicalKey:
PhysicalKeyboardKey#70009(usbHidUsage:
           "0x00070009", debugName: "Key F"), logicalKey:
           LogicalKeyboardKey#00066(keyId: "0x00000066", keyLabel: "F",
debugName: "Key
           F"), character: null, timeStamp: 114:43:52.384859)
[   +2 ms]
           Another exception was thrown: A KeyUpEvent is dispatched, but the
state
           shows that the physical key is not pressed. If this occurs in
real
           application, please report this bug to Flutter. If this occurs in
unit
           tests, please ensure that simulated events follow Flutter's event
model as
           documented in `HardwareKeyboard`. This was the event:
           KeyUpEvent#327ae(physicalKey:
PhysicalKeyboardKey#70009(usbHidUsage:
           "0x00070009", debugName: "Key F"), logicalKey:
           LogicalKeyboardKey#00066(keyId: "0x00000066", keyLabel: "F",
debugName: "Key
           F"), character: null, timeStamp: 114:43:52.384859)
[   +4 ms]
           Another exception was thrown: A KeyUpEvent is dispatched, but the
state
           shows that the physical key is not pressed. If this occurs in
real
           application, please report this bug to Flutter. If this occurs in
unit
           tests, please ensure that simulated events follow Flutter's event
model as
           documented in `HardwareKeyboard`. This was the event:
           KeyUpEvent#327ae(physicalKey:
PhysicalKeyboardKey#70009(usbHidUsage:
           "0x00070009", debugName: "Key F"), logicalKey:
           LogicalKeyboardKey#00066(keyId: "0x00000066", keyLabel: "F",
debugName: "Key
           F"), character: null, timeStamp: 114:43:52.384859)
[   +3 ms]
           Another exception was thrown: A KeyUpEvent is dispatched, but the
state
           shows that the physical key is not pressed. If this occurs in
real
           application, please report this bug to Flutter. If this occurs in
unit
           tests, please ensure that simulated events follow Flutter's event
model as
           documented in `HardwareKeyboard`. This was the event:
           KeyUpEvent#327ae(physicalKey:
PhysicalKeyboardKey#70009(usbHidUsage:
           "0x00070009", debugName: "Key F"), logicalKey:
           LogicalKeyboardKey#00066(keyId: "0x00000066", keyLabel: "F",
debugName: "Key
           F"), character: null, timeStamp: 114:43:52.384859)
[   +3 ms]
           Another exception was thrown: A KeyUpEvent is dispatched, but the
state
           shows that the physical key is not pressed. If this occurs in
real
           application, please report this bug to Flutter. If this occurs in
unit
           tests, please ensure that simulated events follow Flutter's event
model as
           documented in `HardwareKeyboard`. This was the event:
           KeyUpEvent#327ae(physicalKey:
PhysicalKeyboardKey#70009(usbHidUsage:
           "0x00070009", debugName: "Key F"), logicalKey:
           LogicalKeyboardKey#00066(keyId: "0x00000066", keyLabel: "F",
debugName: "Key
           F"), character: null, timeStamp: 114:43:52.384859)
[   +3 ms]
           Another exception was thrown: A KeyUpEvent is dispatched, but the
state
           shows that the physical key is not pressed. If this occurs in
real
           application, please report this bug to Flutter. If this occurs in
unit
           tests, please ensure that simulated events follow Flutter's event
model as
           documented in `HardwareKeyboard`. This was the event:
           KeyUpEvent#327ae(physicalKey:
PhysicalKeyboardKey#70009(usbHidUsage:
           "0x00070009", debugName: "Key F"), logicalKey:
           LogicalKeyboardKey#00066(keyId: "0x00000066", keyLabel: "F",
debugName: "Key
           F"), character: null, timeStamp: 114:43:52.384859)
[   +8 ms]
           Another exception was thrown: A KeyUpEvent is dispatched, but the
state
           shows that the physical key is not pressed. If this occurs in
real
           application, please report this bug to Flutter. If this occurs in
unit
           tests, please ensure that simulated events follow Flutter's event
model as
           documented in `HardwareKeyboard`. This was the event:
           KeyUpEvent#327ae(physicalKey:
PhysicalKeyboardKey#70009(usbHidUsage:
           "0x00070009", debugName: "Key F"), logicalKey:
           LogicalKeyboardKey#00066(keyId: "0x00000066", keyLabel: "F",
debugName: "Key
           F"), character: null, timeStamp: 114:43:52.384859)
[ +453 ms] Service protocol connection closed.
[   +1 ms] Lost connection to device.
[   +2 ms] DevFS: Deleting filesystem on the device
(file:///C:/Users/Taha/AppData/Local/Temp/triage1b912c48/triage/)
[ +252 ms] Ignored error while cleaning up DevFS: TimeoutException after
0:00:00.250000: Future not completed
[  +11 ms] "flutter run" took 43,121ms.
[  +43 ms] ensureAnalyticsSent: 40ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0
PS C:\Users\Taha\StudioProjects\triage>
```
	
</details>


|  `stable`  | `master` |
| :---: |:---: |
|  ❗️  |   ❗️  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.5.1, on Microsoft Windows [Version
    10.0.22000.194], locale en-US)
    • Flutter version 2.5.1 at C:\Users\Taha\Code\flutter_stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (5 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Android toolchain - develop for Android devices (Android SDK version
    31.0.0)
    • Android SDK at C:\Users\Taha\Code\android-sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\android-sdk
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019
    16.11.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual
      Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31702.278
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
[✓] VS Code (version 1.60.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows
      [Version 10.0.22000.194]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome
      93.0.4577.82
    • Edge (web)        • edge    • web-javascript • Microsoft Edge
      93.0.961.47

• No issues found!
```

```console
[✓] Flutter (Channel master, 2.6.0-6.0.pre.171, on Microsoft Windows [Version 10.0.22000.194], locale en-US)
    • Flutter version 2.6.0-6.0.pre.171 at C:\Users\Taha\Code\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 321c872ca7 (5 hours ago), 2021-09-22 02:38:06 -0400
    • Engine revision b0f3c0f7e4
    • Dart version 2.15.0 (build 2.15.0-127.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Taha\Code\android-sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\android-sdk
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31702.278
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.60.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.26.0

[✓] Connected device (4 available)
    • Windows (desktop)       • windows • windows-x64     • Microsoft Windows [Version 10.0.22000.194]
    • Windows (UWP) (desktop) • winuwp  • windows-uwp-x64 •
    • Chrome (web)            • chrome  • web-javascript  • Google Chrome 93.0.4577.82
    • Edge (web)              • edge    • web-javascript  • Microsoft Edge 93.0.961.47

• No issues found!
```
		
</details>

✅: No Issue ❗️: Issue reproduced


There have been a couple of issues with text field during rebuilt

Same on macOS, instead of crash, the app stops taking input
https://github.com/flutter/flutter/issues/89748

On Linux, also same, no more input after hot restart, this can be triggered by switching keyboard too
https://github.com/flutter/flutter/issues/89729

**Comment by TahaTesser** [comment]
Over my triage experience, I've seen windows apps tend to crash whenever something goes wrong so the crash is real but is expected on Windows, while Linux and macOS desktop tend throw errors but rarely ever crash

**Comment by dkwingsmt** [comment]
I'm able to reproduce an error but not exactly the described one. This is my code:
```dart
import 'package:flutter/material.dart';

class MyWidget extends StatefulWidget {
  /// Create state for this widget.
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

/// State for [MyHomePage].
class _MyHomePageState extends State<MyWidget> {

  @override
  void initState() {
    super.initState();
    Future.delayed(const Duration(seconds: 2), () {
      setState(() {
        title = 'Initted.';
        controller.text = '1';
      });
    });
  }

  final TextEditingController controller = TextEditingController();
  String title = 'Init...';

  /// Build a widget.
  @override
  Widget build(BuildContext context) {
    // final focusNode = FocusNode();
    return Scaffold(
      appBar: AppBar(title: Text('Keyboard Test')),
      body: Center(
        child: TextField(
          controller: controller,
          autofocus: true,
          decoration: InputDecoration(
            labelText: title,
          ),
        ),
      ),
    );
  }
}
```
Running with latest framework `321c872ca71b463944b823a9e7b829e0f8b51c9c` and engine `ec009a3d1b78b25c944e7408a876ae40c8d4990c`,
```
flutter run --local-engine=host_debug_unopt -d windows
```

Step:
1. Press `Backspace`

The app crashes with the following log:
```
Unable to parse JSON message:
The document is empty.

══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
The following assertion was thrown during a platform message callback:
'package:flutter/src/widgets/text_editing_action_target.dart': Failed assertion: line 81 pos 12:
'index >= 0 && index <= string.length': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack:
#2      TextEditingActionTarget.nextCharacter (package:flutter/src/widgets/text_editing_action_target.dart:81:12)
#3      TextEditingActionTarget.moveSelectionRight (package:flutter/src/widgets/text_editing_action_target.dart:1211:20)
#4      _MoveSelectionRightTextAction.invoke (package:flutter/src/widgets/default_text_editing_actions.dart:246:30)
#5      ActionDispatcher.invokeAction (package:flutter/src/widgets/actions.dart:573:21)
#6      ShortcutManager.handleKeypress (package:flutter/src/widgets/shortcuts.dart:717:38)
#7      _ShortcutsState._handleOnKey (package:flutter/src/widgets/shortcuts.dart:918:20)
#8      FocusManager._handleKeyMessage (package:flutter/src/widgets/focus_manager.dart:1593:32)
#9      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:830:35)
#10     BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:77:49)
#11     BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:76:47)
#12     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:386:35)
#13     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:383:46)
#14     _invoke2.<anonymous closure> (dart:ui/hooks.dart:205:15)
#18     _invoke2 (dart:ui/hooks.dart:204:10)
#19     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#20     _Channel.push (dart:ui/channel_buffers.dart:132:31)
#21     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#22     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:544:22)
#23     _dispatchPlatformMessage (dart:ui/hooks.dart:92:31)
(elided 5 frames from class _AssertionError and dart:async)
════════════════════════════════════════════════════════════════════════════════════════════════════
Lost connection to device.
```

It seems to me related more to text selection than keyboard. @justinmc Can you take a look, since you've just done the text editing model refactor a while ago?

**Comment by TahaTesser** [comment]
With the code sample, I'm getting error on Windows  `RangeError (end): Invalid value: Not in inclusive range 0..1: -1` and fatal crash

<details> 
<summary>logs</summary> 
	
```console
[        ] Syncing files to device Windows... (completed in 81ms)
[   +1 ms] Synced 0.0MB.
[   +2 ms] <- accept
[   +2 ms] Connected to _flutterView/0x265aa1b62f0.
[   +3 ms] Flutter run key commands.
[   +2 ms] r Hot reload. 🔥🔥🔥
[   +1 ms] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[   +1 ms] q Quit (terminate the application on the device).
[        ] 💪 Running with sound null safety 💪
[   +1 ms] An Observatory debugger and profiler on Windows is available at: http://127.0.0.1:55438/E9-OJ9LayFk=/
[ +243 ms] DevTools activation throttled until 2021-09-22 22:52:45.681217.
[ +757 ms] The Flutter DevTools debugger and profiler on Windows is available at:
                    http://127.0.0.1:9101?uri=http://127.0.0.1:55438/E9-OJ9LayFk=/
[+37339 ms] Unable to parse JSON message:
[   +1 ms] The document is empty.
[   +7 ms]
           ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
           The following RangeError was thrown during a platform message callback:
           RangeError (end): Invalid value: Not in inclusive range 0..1: -1

           When the exception was thrown, this was the stack:
           #0      RangeError.checkValidRange (dart:core/errors.dart:338:9)
           #1      _StringBase.substring (dart:core-patch/string_patch.dart:400:27)
           #2      TextRange.textBefore (dart:ui/text.dart:2785:17)
           #3      TextEditingActionTarget.delete (package:flutter/src/widgets/text_editing_action_target.dart:344:58)
           #4      _DeleteTextAction.invoke (package:flutter/src/widgets/default_text_editing_actions.dart:92:30)
           #5      ActionDispatcher.invokeAction (package:flutter/src/widgets/actions.dart:573:21)
           #6      ShortcutManager.handleKeypress (package:flutter/src/widgets/shortcuts.dart:717:38)
           #7      _ShortcutsState._handleOnKey (package:flutter/src/widgets/shortcuts.dart:918:20)
           #8      FocusManager._handleKeyMessage (package:flutter/src/widgets/focus_manager.dart:1593:32)
           #9      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:830:35)
           #10     BasicMessageChannel.setMessageHandler.<anonymous closure>
(package:flutter/src/services/platform_channel.dart:77:49)
           #11     BasicMessageChannel.setMessageHandler.<anonymous closure>
(package:flutter/src/services/platform_channel.dart:76:47)
           #12     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>
(package:flutter/src/services/binding.dart:386:35)
           #13     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>
(package:flutter/src/services/binding.dart:383:46)
           #14     _invoke2.<anonymous closure> (dart:ui/hooks.dart:205:15)
           #18     _invoke2 (dart:ui/hooks.dart:204:10)
           #19     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
           #20     _Channel.push (dart:ui/channel_buffers.dart:132:31)
           #21     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
           #22     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:544:22)
           #23     _dispatchPlatformMessage (dart:ui/hooks.dart:92:31)
           (elided 3 frames from dart:async)
           ════════════════════════════════════════════════════════════════════════════════════════════════════
[ +436 ms] Service protocol connection closed.
[   +1 ms] Lost connection to device.
[   +2 ms] DevFS: Deleting filesystem on the device (file:///C:/Users/Taha/AppData/Local/Temp/testappb3aa9d87/testapp/)        
[ +260 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
[  +16 ms] "flutter run" took 114,097ms.
[  +49 ms] ensureAnalyticsSent: 45ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0
PS C:\Users\Taha\StudioProjects\testapp> 
```
	
</details>

https://github.com/flutter/flutter/issues/90472#issuecomment-924838153 `HardwareKeyboard` key issues reproduce when quickly  enter any  key hot restart or  app rebuilt  and app crashes with similar error as https://github.com/flutter/flutter/issues/90472#issue-1003063435

**Comment by dkwingsmt** [comment]
@TahaTesser Oops, I pasted the wrong log. I've updated it.

**Comment by dkwingsmt** [comment]
@TahaTesser Thanks for triaging, although if the problem you found out was "pressing keys after hot restarting/reloading" then I don't think it's the same as what xstar described, which said "TextField gets rebuilt".

**Comment by TahaTesser** [comment]
@dkwingsmt 
Ohhh... that makes sense, thanks

**Comment by justinmc** [comment]
I think this is probably in my domain, I've assigned myself.  I've been seeing problems with `-1,-1` invalid selections like this.

@dkwingsmt To reproduce the bug with your code, do you press backspace before or after the label changes to "Initted"?  I couldn't reproduce this on my Mac but I'll try again on my Windows machine later.

**Comment by dkwingsmt** [comment]
@justinmc After. Yes I did it on Windows.

**Comment by justinmc** [comment]
I believe this bug will happen from any keyboard shortcut that affects the selection, not just delete.  I also believe this bug will happen on every platform except for Mac.

Fix and longer description of the cause in https://github.com/flutter/flutter/pull/90826.
