### ISSUE TITLE
[in_app_purchase] _$SkuDetailsWrapperFromJson cast error: type 'int' is not a subtype of type 'String?' in type cast

### ISSUE THREAD

**Issue by eyelexv** [flutter/flutter#90509]
InAppPurchase.instance.queryProductDetails({...}) method crashed with following exception

```
#0      _$SkuDetailsWrapperFromJson (package:in_app_purchase_android/src/billing_client_wrappers/sku_details_wrapper.g.dart:15:47)
#1      new SkuDetailsWrapper.fromJson (package:in_app_purchase_android/src/billing_client_wrappers/sku_details_wrapper.dart:56:7)
#2      _$SkuDetailsResponseWrapperFromJson.<anonymous closure> (package:in_app_purchase_android/src/billing_client_wrappers/sku_details_wrapper.g.dart:59:35)
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
#4      ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
#5      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:188:27)
#6      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#7      new List.of (dart:core-patch/array_patch.dart:50:28)
#8      ListIterable.toList (dart:_internal/iterable.dart:213:44)
#9      _$SkuDetailsResponseWrapperFromJson (package:in_app_purchase_android/src/billing_client_wrappers/sku_details_wrapper.g.dart:60:14)
#10     new SkuDetailsResponseWrapper.fromJson (package:in_app_purchase_android/src/billing_client_wrappers/sku_details_wrapper.dart:182:7)
#11     BillingClient.querySkuDetails (package:in_app_purchase_android/src/billing_client_wrappers/billing_client_wrapper.dart:146:38)
<asynchronous suspension>
#12     Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#13     InAppPurchaseAndroidPlatform.queryProductDetails (package:in_app_purchase_android/src/in_app_purchase_android_platform.dart:81:19)
<asynchronous suspension>
#14     InAppPurchaseCubit._loadProducts (package:vsmrk_user/features/payment/blocs/in_app_purchase/in_app_purchase_cubit.dart:135:24)
<asynchronous suspension>
#15     InAppPurchaseCubit.started (package:vsmrk_user/features/payment/blocs/in_app_purchase/in_app_purchase_cubit.dart:44:7)
<asynchronous suspension>
```

flutter doctor -v

```
[✓] Flutter (Channel stable, 2.5.1, on macOS 11.5.2 20G95 darwin-arm, locale
    ru-RU)
    • Flutter version 2.5.1 at /Users/alex/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (5 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/alex/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/alex/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.60.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

• No issues found!
```

<img width="817" alt="Снимок экрана 2021-09-22 в 12 22 30" src="https://user-images.githubusercontent.com/82671396/134318074-300f2054-232d-41e5-83d7-54cf69ce1d27.png">

**Comment by darshankawar** [comment]
@eyelexv 
This error is a result of a fix made to another issue, https://github.com/flutter/plugins/pull/4364.
See [this](https://github.com/flutter/flutter/issues/90244#issuecomment-924678704) issue comment for your reference, which has a link to the [PR](https://github.com/flutter/plugins/pull/4370) to fix this.
Please follow-up in it for further updates.
I am going ahead and closing this as a duplicate.
