### ISSUE TITLE
using charts.PieChart always crash if try to set defaultRenderer: new charts.ArcRendererConfig( arcWidth: 60, customRendererId: 'novoId')with any value

### ISSUE THREAD

**Issue by HassanDarwish** [flutter/flutter#90515]
Performing hot reload...
Syncing files to device SM A125F...

======== Exception caught by rendering library =====================================================
The following _CastError was thrown during performLayout():
type 'List<ArcRendererElement<dynamic>>' is not a subtype of type 'List<ArcRendererElement<Object>>?' in type cast

The relevant error-causing widget was: 
  PieChart<dynamic> file:///E:/flutter-parts/accborad/lib/SimplePieChart.dart:23:16
When the exception was thrown, this was the stack: 
#0      TypedRegistry.getAttr (package:charts_common/src/common/typed_registry.dart:20:27)
#1      MutableSeries.getAttr (package:charts_common/src/chart/common/processed_series.dart:213:48)
#2      ArcRenderer.update.<anonymous closure> (package:charts_common/src/chart/pie/arc_renderer.dart:164:18)
#3      List.forEach (dart:core-patch/growable_array.dart:403:8)
#4      ArcRenderer.update (package:charts_common/src/chart/pie/arc_renderer.dart:156:16)
...
The following RenderObject was being processed when the exception was fired: ChartContainerRenderObject<dynamic>#66510 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=411.4, h=264.3)
...  semantic boundary
...  size: MISSING
RenderObject: ChartContainerRenderObject<dynamic>#66510 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=411.4, h=264.3)
  semantic boundary
  size: MISSING
====================================================================================================

======== Exception caught by rendering library =====================================================
The following assertion was thrown during performLayout():
RenderBox was not laid out: ChartContainerRenderObject<dynamic>#66510 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1930 pos 12: 'hasSize'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  PieChart<dynamic> file:///E:/flutter-parts/accborad/lib/SimplePieChart.dart:23:16
When the exception was thrown, this was the stack: 
#2      RenderBox.size (package:flutter/src/rendering/box.dart:1930:12)
#3      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:117:21)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
#5      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#6      RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
...
The following RenderObject was being processed when the exception was fired: RenderPointerListener#9f7c8 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=411.4, h=264.3)
...  size: MISSING
...  behavior: deferToChild
...  listeners: down
  child: ChartContainerRenderObject<dynamic>#66510 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
    parentData: <none> (can use size)
    constraints: BoxConstraints(w=411.4, h=264.3)
    semantic boundary
    size: MISSING
RenderObject: RenderPointerListener#9f7c8 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=411.4, h=264.3)
  size: MISSING
  behavior: deferToChild
  listeners: down
  child: ChartContainerRenderObject<dynamic>#66510 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
    parentData: <none> (can use size)
    constraints: BoxConstraints(w=411.4, h=264.3)
    semantic boundary
    size: MISSING
====================================================================================================

======== Exception caught by rendering library =====================================================
The following assertion was thrown during performLayout():
RenderBox was not laid out: RenderPointerListener#9f7c8 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1930 pos 12: 'hasSize'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  PieChart<dynamic> file:///E:/flutter-parts/accborad/lib/SimplePieChart.dart:23:16
When the exception was thrown, this was the stack: 
#2      RenderBox.size (package:flutter/src/rendering/box.dart:1930:12)
#3      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:117:21)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
#5      MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
#6      WidgetLayoutDelegate.performLayout (package:charts_flutter/src/widget_layout_delegate.dart:80:7)
...
The following RenderObject was being processed when the exception was fired: RenderSemanticsGestureHandler#f7f29 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  parentData: offset=Offset(0.0, 0.0); id=chartContainer (can use size)
...  constraints: BoxConstraints(w=411.4, h=264.3)
...  size: MISSING
...  behavior: deferToChild
...  gestures: tap
RenderObject: RenderSemanticsGestureHandler#f7f29 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  parentData: offset=Offset(0.0, 0.0); id=chartContainer (can use size)
  constraints: BoxConstraints(w=411.4, h=264.3)
  size: MISSING
  behavior: deferToChild
  gestures: tap
...  child: RenderPointerListener#9f7c8 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: <none> (can use size)
...    constraints: BoxConstraints(w=411.4, h=264.3)
...    size: MISSING
...    behavior: deferToChild
...    listeners: down
...    child: ChartContainerRenderObject<dynamic>#66510 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=411.4, h=264.3)
...      semantic boundary
...      size: MISSING
====================================================================================================

======== Exception caught by rendering library =====================================================
The following assertion was thrown during performLayout():
RenderBox was not laid out: RenderSemanticsGestureHandler#f7f29 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1930 pos 12: 'hasSize'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  PieChart<dynamic> file:///E:/flutter-parts/accborad/lib/SimplePieChart.dart:23:16
When the exception was thrown, this was the stack: 
#2      RenderBox.size (package:flutter/src/rendering/box.dart:1930:12)
#3      MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:172:18)
#4      WidgetLayoutDelegate.performLayout (package:charts_flutter/src/widget_layout_delegate.dart:80:7)
#5      MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
#6      RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:404:14)
...
The following RenderObject was being processed when the exception was fired: RenderCustomMultiChildLayoutBox#9a4b6 relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  parentData: offset=Offset(0.0, 200.0); flex=1; fit=FlexFit.tight (can use size)
...  constraints: BoxConstraints(0.0<=w<=411.4, h=264.3)
...  size: Size(411.4, 264.3)
RenderObject: RenderCustomMultiChildLayoutBox#9a4b6 relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  parentData: offset=Offset(0.0, 200.0); flex=1; fit=FlexFit.tight (can use size)
  constraints: BoxConstraints(0.0<=w<=411.4, h=264.3)
  size: Size(411.4, 264.3)
...  child 1: RenderSemanticsGestureHandler#f7f29 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: offset=Offset(0.0, 0.0); id=chartContainer (can use size)
...    constraints: BoxConstraints(w=411.4, h=264.3)
...    size: MISSING
...    behavior: deferToChild
...    gestures: tap
...    child: RenderPointerListener#9f7c8 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=411.4, h=264.3)
...      size: MISSING
...      behavior: deferToChild
...      listeners: down
...      child: ChartContainerRenderObject<dynamic>#66510 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=411.4, h=264.3)
...        semantic boundary
...        size: MISSING
====================================================================================================

======== Exception caught by rendering library =====================================================
The following assertion was thrown during paint():
RenderBox was not laid out: ChartContainerRenderObject<dynamic>#66510
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1930 pos 12: 'hasSize'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  PieChart<dynamic> file:///E:/flutter-parts/accborad/lib/SimplePieChart.dart:23:16
When the exception was thrown, this was the stack: 
#2      RenderBox.size (package:flutter/src/rendering/box.dart:1930:12)
#3      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:563:27)
#4      RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:605:7)
#5      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
#6      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
...
The following RenderObject was being processed when the exception was fired: ChartContainerRenderObject<dynamic>#66510
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=411.4, h=264.3)
...  semantic boundary
...  size: MISSING
RenderObject: ChartContainerRenderObject<dynamic>#66510
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=411.4, h=264.3)
  semantic boundary
  size: MISSING
====================================================================================================
Reloaded 1 of 816 libraries in 2,514ms.

======== Exception caught by rendering library =====================================================
The following assertion was thrown during paint():
RenderBox was not laid out: ChartContainerRenderObject<dynamic>#66510
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1930 pos 12: 'hasSize'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  PieChart<dynamic> file:///E:/flutter-parts/accborad/lib/SimplePieChart.dart:23:16
When the exception was thrown, this was the stack: 
#2      RenderBox.size (package:flutter/src/rendering/box.dart:1930:12)
#3      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:563:27)
#4      RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:605:7)
#5      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
#6      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
...
The following RenderObject was being processed when the exception was fired: ChartContainerRenderObject<dynamic>#66510
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=411.4, h=264.3)
...  semantic boundary
...  size: MISSING
RenderObject: ChartContainerRenderObject<dynamic>#66510
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=411.4, h=264.3)
  semantic boundary
  size: MISSING
====================================================================================================

======== Exception caught by rendering library =====================================================
The following assertion was thrown during paint():
RenderBox was not laid out: ChartContainerRenderObject<dynamic>#66510
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1930 pos 12: 'hasSize'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  PieChart<dynamic> file:///E:/flutter-parts/accborad/lib/SimplePieChart.dart:23:16
When the exception was thrown, this was the stack: 
#2      RenderBox.size (package:flutter/src/rendering/box.dart:1930:12)
#3      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:563:27)
#4      RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:605:7)
#5      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
#6      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
...
The following RenderObject was being processed when the exception was fired: ChartContainerRenderObject<dynamic>#66510
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=411.4, h=264.3)
...  semantic boundary
...  size: MISSING
RenderObject: ChartContainerRenderObject<dynamic>#66510
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=411.4, h=264.3)
  semantic boundary
  size: MISSING
====================================================================================================

======== Exception caught by rendering library =====================================================
The following assertion was thrown during paint():
RenderBox was not laid out: ChartContainerRenderObject<dynamic>#66510
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1930 pos 12: 'hasSize'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  PieChart<dynamic> file:///E:/flutter-parts/accborad/lib/SimplePieChart.dart:23:16
When the exception was thrown, this was the stack: 
#2      RenderBox.size (package:flutter/src/rendering/box.dart:1930:12)
#3      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:563:27)
#4      RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:605:7)
#5      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
#6      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
...
The following RenderObject was being processed when the exception was fired: ChartContainerRenderObject<dynamic>#66510
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=411.4, h=264.3)
...  semantic boundary
...  size: MISSING
RenderObject: ChartContainerRenderObject<dynamic>#66510
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=411.4, h=264.3)
  semantic boundary
  size: MISSING
====================================================================================================

======== Exception caught by rendering library =====================================================
The following assertion was thrown during paint():
RenderBox was not laid out: ChartContainerRenderObject<dynamic>#66510
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1930 pos 12: 'hasSize'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  PieChart<dynamic> file:///E:/flutter-parts/accborad/lib/SimplePieChart.dart:23:16
When the exception was thrown, this was the stack: 
#2      RenderBox.size (package:flutter/src/rendering/box.dart:1930:12)
#3      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:563:27)
#4      RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:605:7)
#5      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
#6      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
...
The following RenderObject was being processed when the exception was fired: ChartContainerRenderObject<dynamic>#66510
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=411.4, h=264.3)
...  semantic boundary
...  size: MISSING
RenderObject: ChartContainerRenderObject<dynamic>#66510
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=411.4, h=264.3)
  semantic boundary
  size: MISSING
====================================================================================================

======== Exception caught by rendering library =====================================================
The following assertion was thrown during paint():
RenderBox was not laid out: ChartContainerRenderObject<dynamic>#66510
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1930 pos 12: 'hasSize'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  PieChart<dynamic> file:///E:/flutter-parts/accborad/lib/SimplePieChart.dart:23:16
When the exception was thrown, this was the stack: 
#2      RenderBox.size (package:flutter/src/rendering/box.dart:1930:12)
#3      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:563:27)
#4      RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:605:7)
#5      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
#6      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
...
The following RenderObject was being processed when the exception was fired: ChartContainerRenderObject<dynamic>#66510
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=411.4, h=264.3)
...  semantic boundary
...  size: MISSING
RenderObject: ChartContainerRenderObject<dynamic>#66510
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=411.4, h=264.3)
  semantic boundary
  size: MISSING
====================================================================================================

**Comment by danagbemava-nc** [comment]
Hi @HassanDarwish, the logs you have provided doesn't give much information to act on. 

please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Thank you

**Comment by Joseph0717** [comment]
me too https://github.com/google/charts/issues/688

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by houqinzhe** [comment]
Has this problem been solved?
