### ISSUE TITLE
[VideoPlayer Plugin] java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.endsWith(java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by siddhesh-boppo** [flutter/flutter#90523]
### Getting exception and app crashes
it seems issue in  ### video_player_platform_interface
`
2021-09-20 19:04:31.318 15112-15195/? E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(null, java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.endsWith(java.lang.String)' on a null object reference, null, null)
    #0      VideoPlayerApi.create (package:video_player_platform_interface/messages.dart:205)
    <asynchronous suspension>
    #1      MethodChannelVideoPlayer.create (package:video_player_platform_interface/method_channel_video_player.dart:46)
    <asynchronous suspension>
    #2      VideoPlayerController.initialize (package:video_player/video_player.dart:282)
    <asynchronous suspension>
    #3      ChewieController._initialize (package:chewie/src/chewie_player.dart:347)
    <asynchronous suspension>`

### After running flutter doctor -v

[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-IN)
    • Flutter version 1.22.6 at /Users/siddheshnanche/Documents/Flutter/flutter
    • Framework revision 9b2d32b605 (8 months ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/siddheshnanche/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.60.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (1 available)
    • Redmi Note 7 Pro (mobile) • a0d81adc • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.

Please help to solve this issue

**Comment by maheshmnj** [comment]
Hi @siddhesh-boppo, Thanks for filing the issue. Please share a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) along with the exact steps and the version of the video_player plugin you are having issue with, to reproduce the issue.

Thank you

**Comment by siddhesh-boppo** [comment]
**Here is my code**

`mport 'package:chewie/chewie.dart';
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

class ChewieListItem extends StatefulWidget {
  // This will contain the URL/asset path which we want to play
  final String videoUrl;

  ChewieListItem({@required this.videoUrl});

  @override
  _ChewieListItemState createState() => _ChewieListItemState();
}

class _ChewieListItemState extends State<ChewieListItem> {
  VideoPlayerController _controller;
  ChewieController _chewieController;
  // ChewieController _chewieController;
  Future<void> initializePlayer() async {
    _controller = VideoPlayerController.network(
        'https://github.com/flutter/assets-for-api-docs/blob/master/assets/videos/butterfly.mp4?raw=true');
    // _controller = VideoPlayerController.network(
    //     'https://hdyaar.org/cache/CAT_bollywood-videos/CAT_hindi-video-songs/6719/mp4/mp4-mobile/Khatam%20Hue%20Waande%20Emiway%20-%20HDYaar.Com.mp4');
    await Future.wait([
      _controller.initialize(),
    ]).then((value) {
      _createChewieController();
      setState(() {});
    });
  }

  void _createChewieController() {
    _chewieController = ChewieController(
      videoPlayerController: _controller,
      autoPlay: true,
      // aspectRatio: 16 / 11,
      // Prepare the video to be played and display the first frame
      autoInitialize: true,
      looping: false,
      // Errors can occur for example when trying to play a video
      // from a non-existent URL
      showControls: true,
      showControlsOnInitialize: true,
      allowPlaybackSpeedChanging: false,
      aspectRatio: 16 / 11,
      errorBuilder: (context, errorMessage) {
        print('Video error $errorMessage');
        return Center(
          child: Text(
            'Error while playing this video',
            style: TextStyle(color: Colors.white),
          ),
        );
      },
    );
  }

  @override
  void initState() {
    super.initState();
    initializePlayer();
  }

  @override
  Widget build(BuildContext context) => (_chewieController == null)
      ? Container()
      : Chewie(
          controller: _chewieController,
        );

  @override
  void dispose() {
    // IMPORTANT to dispose of all the used resources
    _controller.dispose();
    _chewieController?.dispose();
    super.dispose();
  }
}`

in pubspec.yaml file using this dependencies
chewie: ^0.12.2 
video_player: ^1.0.1

_you can simply create demo project and add above code_

**steps to reproduce issue**

1. create project using above code
2. run on android device
3. play video 
4. forward video
5. close video
6. follow 3, 4 and 5 steps continuously crash will occur

Sometime on back press of android device crash occurs. If you didn't see crash then minimise the app and resume it and then  follow 3, 4 and 5 steps

tried with other dependencies
yoyo_player: ^0.1.0
better_player
better_video_player


Since all are using basic lib video_player: ^1.0.1, all crashes
please help to get rid of this bug

**Comment by maheshmnj** [comment]
@siddhesh-boppo, thanks for the code sample, It looks like you are trying to run an old flutter project,  As mentioned above you are using the older version of the Flutter SDK and unfortunately we do not provide support to very old versions, You are also using the video_player plugin which is very old, the latest version is `video_player: ^2.2.5`, could you please try upgrading to the latest version? 

> yoyo_player: ^0.1.0
better_player
better_video_player

If you still see the crash after upgrading please try using only video_player. since, all these plugins are third-party plugins including `chewie`, which could potentially be causing the crash. if you still see the crash, feel free to write back with more details and a complete crash log.

**Comment by siddhesh-boppo** [comment]
@maheshmnj Since SDK flutter SDK has some issues, I can't upgrade it right now. Could you please run the above code using SDK 1.22.6?

**Comment by maheshmnj** [comment]
@siddhesh-boppo even if the issue was reproducible on `1.22.6`, we, unfortunately, do not provide support to older versions. So it is recommended to upgrade to the latest version.

>  Since SDK flutter SDK has some issues

If you feel so please consider filing a new issue with the exact steps.

Thanks
