### ISSUE TITLE
Bug: Unable to debug the flutter web app, browser console shows "Error from backend:  Error: Bad state: Not connected to an application."

### ISSUE THREAD

**Issue by mnttnm** [flutter/flutter#90568]
I often lose connection between VSCode and the web emulator (Chrome). When this happens VSCode continue to show "Performing hot restart" and nothing works.

The only way to get the connection back is to terminate the Chrome instance and launch it again.

Output flutter doctor -v
```
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.5.2 20G95 darwin-x64, locale en-IN)
    • Flutter version 2.5.0 at /Users/mohittater/workspace/learn/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (2 weeks ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mohittater/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.60.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 93.0.4577.82

• No issues found!
```

**Browser console error:**

```
client.js:24134 Error from backend:

Error: Bad state: Not connected to an application.

Stack Trace:
#0      DevHandler._handleConnection.<anonymous closure> (package:dwds/src/handlers/dev_handler.dart:255:13)
#1      DevHandler._handleConnection.<anonymous closure> (package:dwds/src/handlers/dev_handler.dart:242:38)
#2      _rootRunUnary (dart:async/zone.dart:1436:47)
#3      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#7      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
#8      _MapStream._handleData (dart:async/stream_pipe.dart:218:10)
#9      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
#10     _rootRunUnary (dart:async/zone.dart:1436:47)
#11     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#12     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#14     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#15     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#16     _StreamController._add (dart:async/stream_controller.dart:607:7)
#17     _StreamController.add (dart:async/stream_controller.dart:554:5)
#18     new WebSocketImpl.fromSocket.<anonymous closure> (package:web_socket_channel/src/copy/web_socket_impl.dart:730:21)
#19     _rootRunUnary (dart:async/zone.dart:1436:47)
#20     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#22     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#23     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#24     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#25     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#26     _WebSocketProtocolTransformer._messageFrameEnd (package:web_socket_channel/src/copy/web_socket_impl.dart:319:23)
#27     _WebSocketProtocolTransformer.add (package:web_socket_channel/src/copy/web_socket_impl.dart:218:46)
#28     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#29     _rootRunUnary (dart:async/zone.dart:1436:47)
#30     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#31     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#32     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#33     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#34     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#35     _StreamController._add (dart:async/stream_controller.dart:607:7)
#36     _StreamController.add (dart:async/stream_controller.dart:554:5)
#37     _Socket._onData (dart:io-patch/socket_patch.dart:2166:41)
#38     _rootRunUnary (dart:async/zone.dart:1444:13)
#39     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#40     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#41     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#42     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#43     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#44     _StreamController._add (dart:async/stream_controller.dart:607:7)
#45     _StreamController.add (dart:async/stream_controller.dart:554:5)
#46     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1702:33)
#47     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1213:14)
#48     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#49     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#50     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
#51     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)

(anonymous) @ client.js:24134
(anonymous) @ client.js:4461
call$2 @ client.js:11511
_asyncStartSync @ client.js:4425
$call$body$main__closure @ client.js:24142
call$1 @ client.js:24069
_rootRunUnary @ client.js:4823
runUnary$2$2 @ client.js:12879
runUnaryGuarded$1$2 @ client.js:12826
_sendData$1 @ client.js:12416
_add$1 @ client.js:12362
_add$1 @ client.js:12695
_handleData$2 @ client.js:12756
_handleData$1 @ client.js:12721
eval @ VM1962:3
_rootRunUnary @ client.js:4823
runUnary$2$2 @ client.js:12879
runUnaryGuarded$1$2 @ client.js:12826
_sendData$1 @ client.js:12416
_add$1 @ client.js:12362
_sendData$1 @ client.js:12201
add$1 @ client.js:12082
eval @ VM1968:3
_rootRunUnary @ client.js:4823
runUnary$2$2 @ client.js:12879
runUnaryGuarded$1$2 @ client.js:12826
_sendData$1 @ client.js:12416
_add$1 @ client.js:12362
_sendData$1 @ client.js:12201
add$1 @ client.js:12082
add$1 @ client.js:23581
call$1 @ client.js:23874
call$1 @ client.js:18042
_rootRunUnary @ client.js:4829
runUnary$2$2 @ client.js:12879
runUnaryGuarded$1$2 @ client.js:12826
call$1 @ client.js:13016
invokeClosure @ client.js:1524
(anonymous) @ client.js:1543
Show 9 more frames
```

**Comment by TahaTesser** [comment]
Hi @mnttnm 
Unable to reproduce the issue on macOS in VS code when running a new project on the web, I also hot restart several times, still no issue
`Chrome (web)    • chrome • web-javascript • Google Chrome 94.0.4606.54` 

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.5.1, on macOS 12.0 21A5522h darwin-x64, locale en-GB)
    • Flutter version 2.5.1 at /Users/tahatesser/Code/flutter_stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (6 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.0 21A5522h darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 94.0.4606.54

! Doctor found issues in 1 category.
```
	
</details>

Your chrome is slightly older, could you upgrade your and try the latest `(Channel stable, 2.5.1)` instead of `2.5.0`

Thank you

**Comment by mnttnm** [comment]
@TahaTesser This is an intermittent issue and I faced it very often, but I am still unsure about the steps to reproduce this. While I cannot reproduce it on demand, Do you have anything that you would like me to capture for debugging>?

**Comment by mnttnm** [comment]
I have upgraded chrome to the latest available and I am still facing this issue. I am attaching a screen record for better clarity. I noticed this in the output of `flutter doctor -v` command.

https://user-images.githubusercontent.com/8184277/134609782-4a63848b-7b75-44fc-b4fc-059e87070678.mov


**Device emulator-5554 is offline**

**Comment by TahaTesser** [comment]
Hi @mnttnm 
Would you mind trying the same thing in Android Studio and also in terminal `flutter run -d chrome`?

**Comment by mnttnm** [comment]
Sure, I can use flutter run -d chrome from now onwards.

**Comment by TahaTesser** [comment]
@mnttnm 
I meant does the issue reproduces with Android Studio or command line

**Comment by mnttnm** [comment]
Actually what I meant is that since the issue is not reproducible at will. I will now use the flutter run command for some time and will report if the issue happens again.
