### ISSUE TITLE
can't solve this android toolchain issue

### ISSUE THREAD

**Issue by Akethaki** [flutter/flutter#90579]
## Steps to Reproduce

**1. there's an issue with the android toolchain in flutter
2. I'm not using Android Studio (system requirements isn't good to install android studio)
3. I installed the latest version of android sdk**  

C:\WINDOWS\system32>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.1, on Microsoft Windows [Version 10.0.18362.1082], locale en-US)
**[☠] Android toolchain - develop for Android devices (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X Null check operator used on a null value**
[√] Chrome - develop for the web
[!] Android Studio (not installed)
[√] VS Code (version 1.60.1)
[√] Connected device (2 available)

! Doctor found issues in 2 categories.

**Output of running 'flutter doctor --android-licenses', is:**

C:\Windows\System32>flutter doctor --android-licenses
Android sdkmanager not found. Update to the latest Android SDK and ensure that the cmdline-tools are installed to
resolve this.

<details>
**with the command 'flutter doctor --verbose':**

C:\Windows\System32>flutter doctor --verbose
[√] Flutter (Channel stable, 2.5.1, on Microsoft Windows [Version 10.0.18362.1082], locale en-US)
    • Flutter version 2.5.1 at C:\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (6 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

**[☠] Android toolchain - develop for Android devices (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X Null check operator used on a null value**
    • #0      AndroidValidator.validate (package:flutter_tools/src/android/android_workflow.dart:205:40)
      #1      GroupedValidator.validate.<anonymous closure> (package:flutter_tools/src/doctor_validator.dart:87:56)
      #2      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #3      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #4      _rootRun (dart:async/zone.dart:1428:13)
      #5      _CustomZone.run (dart:async/zone.dart:1328:19)
      #6      _runZoned (dart:async/zone.dart:1863:10)
      #7      runZonedGuarded (dart:async/zone.dart:1851:12)
      #8      runZoned (dart:async/zone.dart:1782:12)
      #9      asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #10     GroupedValidator.validate (package:flutter_tools/src/doctor_validator.dart:87:11)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #12     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #13     _rootRun (dart:async/zone.dart:1428:13)
      #14     _CustomZone.run (dart:async/zone.dart:1328:19)
      #15     _runZoned (dart:async/zone.dart:1863:10)
      #16     runZonedGuarded (dart:async/zone.dart:1851:12)
      #17     runZoned (dart:async/zone.dart:1782:12)
      #18     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #19     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:200:9)
      #20     Doctor.diagnose (package:flutter_tools/src/doctor.dart:304:47)
      #21     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:47)
      #22     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1274:12)
      <asynchronous suspension>
      #23     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
      <asynchronous suspension>
      #24     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #25     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #26     FlutterCommandRunner.runCommand.<anonymous closure>
      (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
      <asynchronous suspension>
      #27     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #28     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
      <asynchronous suspension>
      #29     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #31     main (package:flutter_tools/executable.dart:92:3)
      <asynchronous suspension>

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.60.1)
    • VS Code at C:\Users\Ishara\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.26.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 93.0.4577.82
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 91.0.864.54

! Doctor found issues in 2 categories.

```
```

**output of running `flutter doctor -v`** 

C:\Windows\System32>flutter doctor -v
[√] Flutter (Channel stable, 2.5.1, on Microsoft Windows [Version 10.0.18362.1082], locale en-US)
    • Flutter version 2.5.1 at C:\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (6 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

**[☠] Android toolchain - develop for Android devices (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X Null check operator used on a null value**
    • #0      AndroidValidator.validate (package:flutter_tools/src/android/android_workflow.dart:205:40)
      #1      GroupedValidator.validate.<anonymous closure> (package:flutter_tools/src/doctor_validator.dart:87:56)
      #2      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #3      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #4      _rootRun (dart:async/zone.dart:1428:13)
      #5      _CustomZone.run (dart:async/zone.dart:1328:19)
      #6      _runZoned (dart:async/zone.dart:1863:10)
      #7      runZonedGuarded (dart:async/zone.dart:1851:12)
      #8      runZoned (dart:async/zone.dart:1782:12)
      #9      asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #10     GroupedValidator.validate (package:flutter_tools/src/doctor_validator.dart:87:11)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #12     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #13     _rootRun (dart:async/zone.dart:1428:13)
      #14     _CustomZone.run (dart:async/zone.dart:1328:19)
      #15     _runZoned (dart:async/zone.dart:1863:10)
      #16     runZonedGuarded (dart:async/zone.dart:1851:12)
      #17     runZoned (dart:async/zone.dart:1782:12)
      #18     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #19     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:200:9)
      #20     Doctor.diagnose (package:flutter_tools/src/doctor.dart:304:47)
      #21     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:47)
      #22     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1274:12)
      <asynchronous suspension>
      #23     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
      <asynchronous suspension>
      #24     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #25     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #26     FlutterCommandRunner.runCommand.<anonymous closure>
      (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
      <asynchronous suspension>
      #27     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #28     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
      <asynchronous suspension>
      #29     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #31     main (package:flutter_tools/executable.dart:92:3)
      <asynchronous suspension>

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.60.1)
    • VS Code at C:\Users\Ishara\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.26.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 93.0.4577.82
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 91.0.864.54

! Doctor found issues in 2 categories.

```
```

</details>

**Comment by Akethaki** [comment]
please be kind enough to solve this

**Comment by TahaTesser** [comment]
Hi @Akethaki 
This looks like an issue with your Android SDK setup, how did you install it? 
Please provide complete reproducible steps and make sure the SDK is added to the system path

**Comment by Akethaki** [comment]
Hi @TahaTesser 
here i will attach from where i downloaded the android sdk setup
![Capture](https://user-images.githubusercontent.com/79906774/134485861-94366c3d-e648-4a05-b2e5-9240298f4e31.PNG)

this is how i added SDK  to the system path
![env1](https://user-images.githubusercontent.com/79906774/134485964-2350301f-c2c9-448c-8203-97a22a4a8fd3.PNG)
![Capture2](https://user-images.githubusercontent.com/79906774/134485994-2a9574f0-e5bc-46a9-ba58-7ab465b80576.PNG)

**Comment by Akethaki** [comment]
Hi @TahaTesser 
This is my unziped sdk folder
![sdk folder](https://user-images.githubusercontent.com/79906774/134486451-e0631f4d-273e-4e1e-88b2-6c2ec590ecf0.PNG)

Thank you

**Comment by TahaTesser** [comment]
Hi @Akethaki 
https://github.com/flutter/flutter/issues/90579#issuecomment-925654954 only shows how you installed CMD tools, not how you downloaded Android SDK.
You need to install Android Studio to properly update Android SDK.

**Comment by Akethaki** [comment]
Hi @TahaTesser 

I did Android SDK downloading According to this guidelines
![sdk_down](https://user-images.githubusercontent.com/79906774/134637181-3f9a6d3e-76f3-4dd7-8b85-460e868fcf86.PNG)

actually i an unable to install Android Studio due to system ram, space and all

**Comment by r4f43ll83** [comment]
I have the same issue. VSCode + android28 emulator (working fine) without  Android Studio. 
Had it working fine for some time, but after last flutter upgrade got licenses warning in vscode. 
Run **flutter doctor --android-licenses** returned **Android sdkmanager tool not found** 
Tried to reinstall sdk but then got same error as OP.

**Comment by TahaTesser** [comment]
Hi @Akethaki  @r4f43ll83 
I just tried the same components, indeed the error is reproduced than I compared components that are installed by Android Studio, looks like you're installing outdated components

Please try this below and also make sure to install `cmdline-tools;latest` even from sdkmanager at the end to get rid "Android sdkmanager tool not found" error 

Execute the following and accept the licenses, no errors with the steps below 
```console
./sdkmanager "platform-tools"  --sdk_root=$HOME/Code/SDK
./sdkmanager "build-tools;29.0.2"  --sdk_root=$HOME/Code/SDK
./sdkmanager "platforms;android-29"  --sdk_root=$HOME/Code/SDK
./sdkmanager "platform-tools"  --sdk_root=$HOME/Code/SD
./sdkmanager "cmdline-tools;latest"  --sdk_root=$HOME/Code/SDK
```
`flutter doctor --android-licenses`

Result:
```console
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.
```

**Comment by r4f43ll83** [comment]
@TahaTesser That indeed solved the issue. Thanks
