### ISSUE TITLE
Tapping on drop down menu item using key during Integration test errors out

### ISSUE THREAD

**Issue by HemilTheRebel** [flutter/flutter#90654]
## Steps to Reproduce

1. Create a new flutter project
2. Follow the steps [here](https://flutter.dev/docs/testing/integration-tests) to add integration_test
3. Replace the contents of main.dart with this dummy app:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int? _value;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: DropdownButtonFormField<int>(
        value: _value,
        key: const Key('ddb'),
        items: const [
          DropdownMenuItem(
            child: Text('0', key: Key('0')),
            value: 0,
          ),
          DropdownMenuItem(
            child: Text('1', key: Key('1')),
            value: 1,
          ),
          DropdownMenuItem(
            child: Text('2', key: Key('2')),
            value: 2,
          ),
        ],
        onChanged: (value) {
          setState((){
            _value = value;
          });
        },
      ),
    );
  }
}
```
4. Create an integration test with the name main_test.dart in the integration_test folder:
```dart
import 'package:drop_down_menu_test/main.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  testWidgets("failing test example", (WidgetTester tester) async {
    await tester.pumpWidget(MyApp());
    await tester.tap(find.byKey(const Key('ddb')));
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(const Key('0')));
  });
}
```

5. Run the command: `flutter drive --driver=test_driver/integration_test.dart --target=integration_test/main_test.dart`
## Logs

<details>
<summary>Logs</summary>

```
Running "flutter pub get" in drop_down_menu_test...                689ms
Running Gradle task 'assembleDebug'...                             19.5s
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...              2,275ms
VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:37523/oC9bmPZWmfA=/
VMServiceFlutterDriver: Isolate found with number: 2939723589104431
VMServiceFlutterDriver: Isolate is paused at start.
VMServiceFlutterDriver: Attempting to resume isolate
I/flutter ( 4321): 00:00 +0: failing test example
VMServiceFlutterDriver: Connected to Flutter application.
I/flutter ( 4321): 1
I/flutter ( 4321): ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
I/flutter ( 4321): The following assertion was thrown running a test:
I/flutter ( 4321): The finder "2 widgets with key [<'0'>] (ignoring offstage widgets): [Text-[<'0'>]("0", dependencies:
I/flutter ( 4321): [DefaultTextStyle, MediaQuery]), Text-[<'0'>]("0", dependencies: [DefaultTextStyle, MediaQuery])]"
I/flutter ( 4321): (used in a call to "tap()") ambiguously found multiple matching widgets. The "tap()" method needs a
I/flutter ( 4321): single target.
I/flutter ( 4321): 
I/flutter ( 4321): When the exception was thrown, this was the stack:
I/flutter ( 4321): #0      WidgetController._getElementPoint (package:flutter_test/src/controller.dart:906:7)
I/flutter ( 4321): #1      WidgetController.getCenter (package:flutter_test/src/controller.dart:841:12)
I/flutter ( 4321): #2      WidgetController.tap (package:flutter_test/src/controller.dart:273:18)
I/flutter ( 4321): #3      main.<anonymous closure>
(file:///home/hemil/AndroidStudioProjects/drop_down_menu_test/integration_test/main_test.dart:13:18)
I/flutter ( 4321): <asynchronous suspension>
I/flutter ( 4321): #4      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:176:15)
I/flutter ( 4321): <asynchronous suspension>
I/flutter ( 4321): #5      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:817:5)
I/flutter ( 4321): <asynchronous suspension>
I/flutter ( 4321): 
I/flutter ( 4321): The test description was:
I/flutter ( 4321):   failing test example
I/flutter ( 4321): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 4321): 00:01 +0: failing test example [E]
I/flutter ( 4321):   Test failed. See exception logs above.
I/flutter ( 4321):   The test description was: failing test example
I/flutter ( 4321):   
I/flutter ( 4321): Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
I/flutter ( 4321): For example, 'dart test --chain-stack-traces'.
I/flutter ( 4321): 00:01 +0 -1: (tearDownAll)
W/_down_menu_tes( 4321): Accessing hidden method
Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
W/_down_menu_tes( 4321): Accessing hidden method
Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
I/flutter ( 4321): 00:01 +1 -1: Some tests failed.
Failure Details:
Failure in method: failing test example
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following assertion was thrown running a test:
The finder "2 widgets with key [<'0'>] (ignoring offstage
widgets): [Text-[<'0'>]("0", dependencies: [DefaultTextStyle,
MediaQuery]), Text-[<'0'>]("0", dependencies: [DefaultTextStyle,
MediaQuery])]" (used in a call to "tap()") ambiguously found
multiple matching widgets. The "tap()" method needs a single
target.

When the exception was thrown, this was the stack:
#0      WidgetController._getElementPoint (package:flutter_test/src/controller.dart:906:7)
#1      WidgetController.getCenter (package:flutter_test/src/controller.dart:841:12)
#2      WidgetController.tap (package:flutter_test/src/controller.dart:273:18)
#3      main.<anonymous closure> (file:///home/hemil/AndroidStudioProjects/drop_down_menu_test/integration_test/main_test.dart:13:18)
<asynchronous suspension>
#4      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:176:15)
<asynchronous suspension>
#5      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:817:5)
<asynchronous suspension>

The test description was:
  failing test example
═════════════════════════════════════════════════════════════════

end of failure 1
```

Flutter doctor -v
```
[✓] Flutter (Channel stable, 2.5.1, on Debian GNU/Linux 10 (buster) 4.19.0-17-amd64, locale en_IN)
    • Flutter version 2.5.1 at /home/hemil/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (6 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/hemil/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /home/hemil/Downloads/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/hemil/Downloads/android-studio
    • Flutter plugin version 60.1.2
    • Dart plugin version 203.8292
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (2 available)
    • Google Pixel 3 (mobile) • 192.168.56.101:5555 • android-x86    • Android 10 (API 29)
    • Chrome (web)            • chrome              • web-javascript • Google Chrome 94.0.4606.54

• No issues found!
```

</details>

## Expected Output
Tests should pass

## Actual output
Error saying two widgets with key 0 were found

## What I have tried
- Adding the key to drop down menu item instead of text
- Replacing drop down button form field with drop down button

In all the cases, I get the same error. I haven't tried flutter driver to see if that works.

**Comment by darshankawar** [comment]
@HemilTheRebel 
Thanks for the detailed report. This seems to be an issue in the widget tests itself coming from flutter_test package. See a similar open issue describing the same case, https://github.com/flutter/flutter/issues/89905

Is it ok for you to follow-up in linked issue for further updates ?

**Comment by HemilTheRebel** [comment]
Yes
