### ISSUE TITLE
Container doesn't work with both borderRadius and NOT ALL border sides

### ISSUE THREAD

**Issue by Albert221** [flutter/flutter#90669]
You can paste it straight into https://dartpad.dev.

> Based on Flutter 2.5.1 Dart SDK 2.14.2

I get _Script error_ whenever I try to display a `Container` that have some sides with border and some not with a border radius. Both all border radiuses or just the border radius for corners that do have borders.

I'd expect some kind of an `AssertionError` to be popped up for the developer to see what he did wrong and/or have the `Container` fixed to properly render the rounded corner for corners that do have a border side specified.

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final side = BorderSide(
      width: 10,
      color: Colors.blue.withOpacity(0.5),
    );

    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Container(
            width: 100,
            height: 100,
            decoration: BoxDecoration(
              color: Colors.red,
              border: Border(left: side, top: side, right: side),
//               borderRadius: BorderRadius.vertical( // This doesn't work too
//                 top: Radius.circular(5),
//               ),
              borderRadius: BorderRadius.circular(5),
            ),
          ),
        ),
      ),
    );
  }
}
```

**Comment by darshankawar** [comment]
@Albert221 
Thanks for the report. I do see the `script error` upon running the code sample in dart pad, but running it on mobile (ex: iOS simulator) does throw the required assertion failure as below:

<details>
<summary>console error log</summary>

```

======== Exception caught by rendering library =====================================================
The following assertion was thrown during paint():
A borderRadius can only be given for a uniform Border.

The following is not uniform:
BorderSide.color
BorderSide.width
BorderSide.style
The relevant error-causing widget was: 
  Container Container:file:///Users/dhs/Documents/NCFlutter/ios_bug/lib/main.dart:16:18
When the exception was thrown, this was the stack: 
#0      Border.paint.<anonymous closure> (package:flutter/src/painting/box_border.dart:523:9)
#1      Border.paint (package:flutter/src/painting/box_border.dart:532:6)
#2      _BoxDecorationPainter.paint (package:flutter/src/painting/box_decoration.dart:484:25)
#3      RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:2150:17)
#4      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#5      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#6      RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#7      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#8      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#9      RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:79:15)
#10     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#11     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#12     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2794:15)
#13     RenderCustomMultiChildLayoutBox.paint (package:flutter/src/rendering/custom_layout.dart:409:5)
#14     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#15     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#16     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#17     _RenderInkFeatures.paint (package:flutter/src/material/material.dart:553:11)
#18     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#19     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#20     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#21     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:398:12)
#22     RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:1929:15)
#23     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#24     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#25     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#26     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#27     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#28     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#29     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#30     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:141:11)
#31     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
#32     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:206:7)
#33     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:7)
#34     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#35     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#36     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#37     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2794:15)
#38     RenderStack.paintStack (package:flutter/src/rendering/stack.dart:629:5)
#39     RenderStack.paint (package:flutter/src/rendering/stack.dart:645:7)
#40     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#41     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#42     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#43     RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:2169:11)
#44     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#45     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#46     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#47     RenderFractionalTranslation.paint (package:flutter/src/rendering/proxy_box.dart:2764:13)
#48     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#49     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#50     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#51     RenderFractionalTranslation.paint (package:flutter/src/rendering/proxy_box.dart:2764:13)
#52     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#53     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#54     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#55     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#56     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:141:11)
#57     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
#58     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:206:7)
#59     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:7)
#60     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#61     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#62     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#63     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#64     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#65     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#66     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#67     RenderOffstage.paint (package:flutter/src/rendering/proxy_box.dart:3423:11)
#68     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#69     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#70     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#71     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#72     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#73     _RenderTheatre.paintStack (package:flutter/src/widgets/overlay.dart:788:15)
#74     _RenderTheatre.paint (package:flutter/src/widgets/overlay.dart:806:7)
#75     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#76     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#77     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#78     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#79     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#80     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#81     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#82     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#83     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#84     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#85     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#86     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#87     RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:608:11)
#88     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#89     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#90     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#91     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#92     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#93     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#94     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#95     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#96     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#97     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#98     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#99     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#100    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#101    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#102    RenderView.paint (package:flutter/src/rendering/view.dart:209:15)
#103    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#104    PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:141:11)
#105    PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
#106    PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:979:29)
#107    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:455:19)
#108    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#109    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
#110    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
#111    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#112    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:863:7)
(elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
The following RenderObject was being processed when the exception was fired: RenderDecoratedBox#3f2c1
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=100.0, h=100.0)
...  size: Size(100.0, 100.0)
...  decoration: BoxDecoration
...    color: MaterialColor(primary value: Color(0xfff44336))
...    border: Border(top: BorderSide(Color(0x802196f3), 10.0, BorderStyle.solid), right: BorderSide(Color(0x802196f3), 10.0, BorderStyle.solid), left: BorderSide(Color(0x802196f3), 10.0, BorderStyle.solid))
...    borderRadius: BorderRadius.circular(5.0)
...  configuration: ImageConfiguration(bundle: PlatformAssetBundle#e9c32(), devicePixelRatio: 3.0, locale: en_US, textDirection: TextDirection.ltr, platform: iOS)
  child: RenderPadding#d651c NEEDS-PAINT
    parentData: <none> (can use size)
    constraints: BoxConstraints(w=100.0, h=100.0)
    size: Size(100.0, 100.0)
    padding: EdgeInsets(10.0, 10.0, 10.0, 0.0)
    textDirection: ltr
RenderObject: RenderDecoratedBox#3f2c1
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=100.0, h=100.0)
  size: Size(100.0, 100.0)
  decoration: BoxDecoration
    color: MaterialColor(primary value: Color(0xfff44336))
    border: Border(top: BorderSide(Color(0x802196f3), 10.0, BorderStyle.solid), right: BorderSide(Color(0x802196f3), 10.0, BorderStyle.solid), left: BorderSide(Color(0x802196f3), 10.0, BorderStyle.solid))
    borderRadius: BorderRadius.circular(5.0)
  configuration: ImageConfiguration(bundle: PlatformAssetBundle#e9c32(), devicePixelRatio: 3.0, locale: en_US, textDirection: TextDirection.ltr, platform: iOS)
  child: RenderPadding#d651c NEEDS-PAINT
    parentData: <none> (can use size)
    constraints: BoxConstraints(w=100.0, h=100.0)
    size: Size(100.0, 100.0)
    padding: EdgeInsets(10.0, 10.0, 10.0, 0.0)
    textDirection: ltr
====================================================================================================





```


</details>

which basically throws `A borderRadius can only be given for a uniform Border.` and that I believe is discussed in this open issue, https://github.com/flutter/flutter/issues/12583

**Comment by Albert221** [comment]
You're right. That's a duplicate of #12583. I believe I somehow missed the assertion error in the console because I just wasn't seeing what I expected and I didn't see the red error widget

**Comment by darshankawar** [comment]
Since the correct assertion failure is thrown running on mobile, I think this could be a dartpad specific issue and probably need to open in dedicated repo: https://github.com/dart-lang/dart-pad/issues
