### ISSUE TITLE
No toolchains found in the NDK toolchains folder for ABI with prefix: arm-linux-androideabi

### ISSUE THREAD

**Issue by davejlin** [flutter/flutter#90674]
## Steps to Reproduce

0. Use Flutter version 2.0.5
1. Build Android apk on GitHub using:

```
flutter build apk --release --build-number=${{ github.run_number }} --obfuscate --split-debug-info=debug_info --flavor dev
```

## Logs

```
[        ] > Task :app:stripDevDebugDebugSymbols FAILED
[        ] Support for ANDROID_NDK_HOME is deprecated and will be removed in the future. Use android.ndkVersion in build.gradle instead.
[  +75 ms] > Task :app:mergeDexDevDebug
[  +92 ms] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
[        ] Execution failed for task ':app:stripDevDebugDebugSymbols'.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] > No toolchains found in the NDK toolchains folder for ABI with prefix: arm-linux-androideabi
[        ] See https://docs.gradle.org/5.6.2/userguide/command_line_interface.html#sec:command_line_warnings
[        ] * Try:
[        ] 393 actionable tasks: 392 executed, 1 up-to-date
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 3m 53s
[+1157 ms] Running Gradle task 'assembleDevDebug'... (completed in 235.1s)
[  +11 ms] "flutter apk" took 236,859ms.
[   +6 ms] Gradle task assembleDevDebug failed with exit code 1
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      buildGradleApp (package:flutter_tools/src/android/gradle.dart:411:7)
           <asynchronous suspension>
           #2      _AndroidBuilderImpl.buildApk (package:flutter_tools/src/android/android_builder.dart:101:7)
           <asynchronous suspension>
           #3      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:103:5)
           <asynchronous suspension>
           #4      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
           <asynchronous suspension>
           #5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #8      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
[   +3 ms] ensureAnalyticsSent: 1ms
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #14     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
[   +2 ms] Running shutdown hooks
           #16     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
[        ] Shutdown hooks complete
           #17     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #18     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>


[   +2 ms] exiting with code 1
Error: Process completed with exit code 1.
```

## Workaround:

The above error occurs when the build uses the current latest NDK version 23.0.7599858.

If I pin the NDK version to 22.1.7171670 (the version prior to the current latest), the build succeeds.

In ```.../android/app/build.gradle```:

```
android {
    ndkVersion "22.1.7171670"
}
```

## Related Issue:

Appears to be similar to https://github.com/flutter/flutter/issues/76393 but with different NDK versions.

</details>

**Comment by darshankawar** [comment]
> 1. Use Flutter version 2.0.5

@davejlin 
Current stable version is 2.5.1, so I suggest you to upgrade to latest and try again to see if you get same error or not.
2.0.5 is old version and any issues related to it won't be fix in that version, you'll need to upgrade.

Thanks.

**Comment by darshankawar** [comment]
@davejlin 
Thanks for the update. Does it mean the issue is resolved ?

**Comment by davejlin** [comment]
> @davejlin Thanks for the update. Does it mean the issue is resolved ?

@darshankawar I'm in the process of trying to update our code now.  
I will resolve this issue when I can confirm it's no longer an issue in the updated code.
Thanks.

**Comment by davejlin** [comment]
@darshankawar I'll close the issue for now, as it will take time to migrate my project up.  Will reopen if still an issue afterwards.  Thanks again.
