### ISSUE TITLE
Unable to create file after simulator started using iPhone 13

### ISSUE THREAD

**Issue by eliashanna78** [flutter/flutter#90709]
Hi,
My app was working normally until the simulator changed to iPhone 13, now I'm getting an error when creating files:
```
Future<File> get planDataFile async {
  final path = await _localPath;
  return File('$path/planData');
}

Future<Plan> createFile() async {
  var syncPath = await planDataFile;
  if (!File('$syncPath').existsSync()) {
    new File('$syncPath').createSync();
  }
}
```

Error logs:

[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: FileSystemException: Cannot create file, path = 'File: '/Users/[user]/Library/Developer/CoreSimulator/Devices/086D31E9-3552-440C-A5D4-134520461353/data/Containers/Data/Application/212EDDC5-E435-45D0-9415-1FE4957DF8F8/Documents/planData'' (OS Error: No such file or directory, errno = 2)
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.createSync (dart:io/file_impl.dart:273:5)
#2      readPlan (package:planner/utils/utils.dart:25:27)
<asynchronous suspension>
Application finished.

Any suggestions?

**Comment by maheshmnj** [comment]
Hi, @eliashanna78 Thanks for filing the issue, Please share the output of `flutter doctor -v` and minimal and complete reproducible code without unknown variables.

Thanks.

**Comment by eliashanna78** [comment]
@maheshmnj Hi, thanks for the reply,

this is my minimal app:
```
import 'package:flutter/material.dart';
import 'package:path_provider/path_provider.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'app',
      theme: ThemeData(        primarySwatch: Colors.blueGrey,
      ),
      home: MyHomePage(title: 'app'),
    );
  }
}

Future<String> get _localPath async {
  Directory? dir;
  if (Platform.isAndroid) {
    dir = await getExternalStorageDirectory();
  } else {
    dir = await getApplicationDocumentsDirectory();
  }
  return dir!.path;
}

Future<File> get planDataFile async {
  final path = await _localPath;
  return File('$path/planData');
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  void initState() {
    super.initState();
    planDataFile
        .then((File value) => {new File('$value').create(), print('hi')});
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: DefaultTabController(
      length: 0,
      child: Scaffold(
        appBar: AppBar(
          backgroundColor: Colors.blueGrey,
          bottom: const TabBar(
            tabs: [],
          ),
          title: const Text('App'),
        ),
      ),
    ));
  }
}
```

Output when running:

Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Running Xcode build...
Xcode build done.                                           23.3s
Debug service listening on ws://127.0.0.1:49471/b1wdCVJiYCI=/ws
Syncing files to device iPhone 12 Pro Max...
flutter: hi
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: FileSystemException: Cannot create file, path = 'File: '/Users/ehanna/Library/Developer/CoreSimulator/Devices/C7AB23B6-FC2F-40EA-9F78-B9802D18167E/data/Containers/Data/Application/DE7690A1-6E4E-4E86-BDD6-AABA090138CB/Documents/planData'' (OS Error: No such file or directory, errno = 2)
#0      _File.create.<anonymous closure> (dart:io/file_impl.dart:255:9)
#1      _rootRunUnary (dart:async/zone.dart:1436:47)
#2      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
<asynchronous suspension>


flutter doctor -v output:

flutter doctor -v
[✓] Flutter (Channel stable, 2.5.1, on macOS 11.5.2 20G95 darwin-x64, locale en)
    • Flutter version 2.5.1 at /Users/ehanna/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (10 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/ehanna/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • C7AB23B6-FC2F-40EA-9F78-B9802D18167E • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 93.0.4577.82

! Doctor found issues in 1 category.

**Comment by maheshmnj** [comment]
@eliashanna78  This is working as expected in your code


>  planDataFile.then((File value) => {new File('$value').create(), print('hi')});
        
you are passing a File object to File as a String which will be an invalid path it should be 

```dart
 planDataFile.then((File value) => value.create(), onError: (x) { print('hi');});
```

**Comment by eliashanna78** [comment]
@maheshmnj Thanks for the help, not sure how this was messed :) I will close the issue it's working
