### ISSUE TITLE
flutter doctor --android-licenses returns exceptions in Android Studio Arctic Fox

### ISSUE THREAD

**Issue by santaanto** [flutter/flutter#90717]
Hello,
I have just updated my Android Studio to latest version Arctic Fox.
I have checked for updates for Flutter plugin, but was already at the latest.
Now I run flutter doctor from terminal, to check everything is OK :
 
Microsoft Windows [Version 10.0.19042.1237]
(c) Microsoft Corporation. All rights reserved.

C:\>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19042.1237], locale en-GB)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] Connected device (2 available)

! Doctor found issues in 1 category.

C:\>flutter doctor --android-licenses
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more

what could be causing this issue ? 
thank you

**Comment by Josiassejod1** [comment]
Hey @santaanto because of the update, your machine needs to ad new sdk tools in Android Studio, you can checkout other responses here, this is a similar issue https://github.com/flutter/flutter/issues/56778

**Comment by santaanto** [comment]
Thank you, I had just fixed this by selecting "Android SDK command line tools (latest)" from Tools->Sdk Manager->SDK Tools menu. I don't undertand why it was unselected by the new update as with previous installation this was OK, but anyway now it works ! thank you
