### ISSUE TITLE
can't start process from windows app

### ISSUE THREAD

**Issue by EightRice** [flutter/flutter#90762]
Trying to run a new host process from a desktop app (windows) with the provided example code:

```
import 'dart:io';

main() {
  // List all files in the current directory in UNIX-like systems.
  Process.run('dir', ['/p']).then((ProcessResult results) {
    print(results.stdout);
  });
}
```
and get

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: ProcessException: The system cannot find the file specified.


  Command: dir
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:390:33)
#1      Process.start (dart:io-patch/process_patch.dart:36:20)
#2      _runNonInteractiveProcess (dart:io-patch/process_patch.dart:565:18)
#3      Process.run (dart:io-patch/process_patch.dart:47:12)
#4      MyApp.build (package:dashboard/main.dart:25:11)
#5      StatelessElement.build (package:flutter/src/widgets/framework.dart:4657:28)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4583:15)
#7      Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4561:5)
#9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4556:5)
#10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3631:14)
#11     Element.updateChild (package:flutter/src/widgets/framework.dart:3383:18)
#12     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1198:16)
#13     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1167:5)
#14     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1112:18)        t:1112:18)
#15     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2531:19)
#16     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1111:13)
#17     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:944:7)                           )
#18     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:924:7)
#19     _rootRun (dart:async/zone.dart:1420:47)
#20     _CustomZone.run (dart:async/zone.dart:1328:19)
#21     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
#23     _rootRun (dart:async/zone.dart:1428:13)
#24     _CustomZone.run (dart:async/zone.dart:1328:19)
#25     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1260:23)
#26     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#27     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)
#28     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426:5)
#29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:187:12)    
```

**Comment by EightRice** [comment]
it just didn't find "dir"
