### ISSUE TITLE
The route's exit transition will be complete after its corresponding State has been disposed

### ISSUE THREAD

**Issue by 0xZOne** [flutter/flutter#90800]
I want to do something when the route's exit transition is complete.  It works fine in Flutter 1.22.6. BUT, when I upgrade Flutter SDK to 2.2.3 or above, it does **not** work because mounted is FALSE, not TRUE anymore.

The route's exit transition will be complete after its corresponding State has been unmounted in Flutter 2.2.3 or above. Is this expected?

It seems to Flutter 1.22.6 's behavior more reasonable.

```dart
class _SecondScreenState extends State<SecondScreen> {
  @override
  void didChangeDependencies() {
    ModalRoute.of(context)?.completed.then((data) {
      print('Is the result expected? mounted=$mounted');
      if (mounted) {
        // do things
      }
    });
    super.didChangeDependencies();
  }

  @override
  void dispose() {
    super.dispose();
    print('#dispose');
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
    ......
    );
  }
}
```

See [here](https://github.com/0xZOne/transition_route_demo/blob/main/lib/main.dart) for complete demo.

<details>
  <summary>Logs</summary>

Flutter 1.22.6:

```dart
I/flutter (14439): #0      TransitionRoute.dispose (package:flutter/src/widgets/routes.dart:425:36)
I/flutter (14439): #1      _RouteEntry.dispose (package:flutter/src/widgets/navigator.dart:2538:11)
I/flutter (14439): #2      NavigatorState._flushHistoryUpdates (package:flutter/src/widgets/navigator.dart:3294:13)
I/flutter (14439): #3      NavigatorState.finalizeRoute (package:flutter/src/widgets/navigator.dart:3960:5)
I/flutter (14439): #4      TransitionRoute._handleStatusChanged (package:flutter/src/widgets/routes.dart:192:21)
I/flutter (14439): #5      AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:199:19)
I/flutter (14439): #6      AnimationController._checkStatusChanged (package:flutter/src/animation/animation_controller.dart:782:7)
I/flutter (14439): #7      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:798:5)
I/flutter (14439): #8      Ticker._tick (package:flutter/src/scheduler/ticker.dart:238:12)
I/flutter (14439): #9      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1150:15)
I/flutter (14439): #10     SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1064:11)
I/flutter (14439): #11     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
I/flutter (14439): #12     SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1062:17)
I/flutter (14439): #13     SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:993:5)
I/flutter (14439): #14     _rootRunUnary (dart:async/zone.dart:1206:13)
I/flutter (14439): #15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
I/flutter (14439): #16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
I/flutter (14439): #17     _invoke1 (dart:ui/hooks.dart:327:10)
I/flutter (14439): #18     _beginFrame (dart:ui/hooks.dart:245:3)
```

Flutter 2.2.3

```dart
I/flutter (26072): #0      TransitionRoute.dispose (package:flutter/src/widgets/routes.dart:423:36)
I/flutter (26072): #1      _RouteEntry.dispose.<anonymous closure> (package:flutter/src/widgets/navigator.dart:3164:19)
I/flutter (26072): #2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:243:25)
I/flutter (26072): #3      OverlayEntry._updateMounted (package:flutter/src/widgets/overlay.dart:130:5)
I/flutter (26072): #4      _OverlayEntryWidgetState.dispose (package:flutter/src/widgets/overlay.dart:200:18)
I/flutter (26072): #5      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4860:11)
I/flutter (26072): #6      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1863:13)
I/flutter (26072): #7      ListIterable.forEach (dart:_internal/iterable.dart:39:13)
I/flutter (26072): #8      _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:1872:25)
I/flutter (26072): #9      BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2880:27)
I/flutter (26072): #10     BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2513:15)
I/flutter (26072): #11     BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2879:7)
I/flutter (26072): #12     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:877:19)
I/flutter (26072): #13     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:344:5)
I/flutter (26072): #14     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1147:15)
I/flutter (26072): #15     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1085:9)
I/flutter (26072): #16     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:998:5)
I/flutter (26072): #17     _rootRun (dart:async/zone.dart:1354:13)
I/flutter (26072): #18     _CustomZone.run (dart:async/zone.dart:1258:19)
I/flutter (26072): #19     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
I/flutter (26072): #20     _invoke (dart:ui/hooks.dart:163:10)
I/flutter (26072): #21     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:281:5)
I/flutter (26072): #22     _drawFrame (dart:ui/hooks.dart:126:31)
```

```
[✓] Flutter (Channel unknown, 2.5.1, on macOS 11.5.2 20G95 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.5.1 at /Users/zero/development/flutter
    • Upstream repository unknown
    • Framework revision ffb2ecea52 (10 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/zero/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/zero/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/zero/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.60.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Lenovo L78051 (mobile) • 30.103.233.151:24003                     • android-arm64  • Android 10 (API 29)
    • iPhone (mobile)        • 50131fb4dcef9d96405ec953e272bd5c24468370 • ios            • iOS 14.4.2 18D70
    • Chrome (web)           • chrome                                   • web-javascript • Google Chrome 93.0.4577.82

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@0xZOne 
Ran your code sample and observed below after navigating back to launch screen:

```
`flutter: #dispose
flutter: Is the result expected? mounted=false`
```

Since the `dispose()` method gets called after navigating back, the state object becomes unmounted and hence you get `mounted=false`. 

`mounted = true` will remain until we call `dispose()` method but once it is called, it changes to `false`.

See also the documentation for more details / reference: https://api.flutter.dev/flutter/widgets/State/mounted.html

I am going ahead and closing this as WAI. If you disagree, write in comments and I'll reopen it.
Thanks.

**Comment by 0xZOne** [comment]
@darshankawar 

Could you please explain the change about this from 1.22.6 to 2.2.3 in more detail? Thanks.

**Comment by 0xZOne** [comment]
https://stackoverflow.com/q/69504754/17112156
