### ISSUE TITLE
[Linux] Pressing Alt-Tab without moving the mouse after startup breaks mouse movement afterwards

### ISSUE THREAD

**Issue by dkwingsmt** [flutter/flutter#90838]
Reproduction code: 
```dart
import 'package:flutter/material.dart';

class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: TextField(),
      ),
    );
  }
}
```

Reproduction step: 
1. `flutter run -d linux`
2. Alt-Tab to the app, if needed, without moving the mouse at all
3. Alt-Tab to other apps

Expected result: The app is still usable.

Actual result: The app keeps informing assertion for the mouse system and does not respond to mouse interactions. The first of the errors is:
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: 'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 317 pos 18: 'event is! PointerRemovedEvent': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:47:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      MouseTracker.updateWithEvent.<anonymous closure>.<anonymous closure> (package:flutter/src/rendering/mouse_tracker.dart:317:18)
#3      MouseTracker._deviceUpdatePhase (package:flutter/src/rendering/mouse_tracker.dart:206:9)
#4      MouseTracker.updateWithEvent.<anonymous closure> (package:flutter/src/rendering/mouse_tracker.dart:312:7)
#5      MouseTracker._monitorMouseConnection (package:flutter/src/rendering/mouse_tracker.dart:190:9)
#6      MouseTracker.updateWithEvent (package:flutter/src/rendering/mouse_tracker.dart:311:5)
#7      RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:270:20)
#8      GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
#9      GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
#10     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#11     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#12     _rootRunUnary (dart:async/zone.dart:1444:13)
#13     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#14     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#15     _invoke1 (dart:ui/hooks.dart:185:10)
#16     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
#17     _dispatchPointerDataPacket (dart:ui/hooks.dart:98:31)
```

Version:
```
 flutter doctor -v                                     ✔  10102  16:00:08
[✓] Flutter (Channel master, 2.6.0-12.0.pre.64, on Debian GNU/Linux rodete 5.10.46-4rodete4-amd64, locale
    en_US.UTF-8)
    • Flutter version 2.6.0-12.0.pre.64 at /usr/local/google/home/tongmu/dev/flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision 975da38dd3 (4 days ago), 2021-09-23 14:13:04 -0400
    • Engine revision a3911f24a5
    • Dart version 2.15.0 (build 2.15.0-140.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /usr/local/google/home/tongmu/Android/Sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Debian clang version 11.0.1-2
    • cmake version 3.18.4
    • ninja version 1.8.2
    • pkg-config version 0.29.2

[✓] Android Studio (version 3.5)
    • Android Studio at /usr/local/google/home/tongmu/src/android-studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.60.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Debian GNU/Linux rodete 5.10.46-4rodete4-amd64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 94.0.4606.61

! Doctor found issues in 1 category.
```

**Comment by TahaTesser** [comment]
Hi 
Thanks for filing the issue



### Logs

<details> 
<summary>logs</summary> 
	
```console
[  +86 ms] Syncing files to device Linux...
[   +1 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +2 ms] <- recompile package:triage/main.dart 543e41d9-f46f-43b2-9bad-1af7a28092f9
[        ] <- 543e41d9-f46f-43b2-9bad-1af7a28092f9
[ +141 ms] Updating files.
[        ] DevFS: Sync finished
[        ] Syncing files to device Linux... (completed in 147ms)
[   +1 ms] Synced 0.0MB.
[   +2 ms] <- accept
[   +4 ms] Connected to _flutterView/0x2e66cb0.
[   +6 ms] Flutter run key commands.
[   +4 ms] r Hot reload. 🔥🔥🔥
[   +1 ms] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] 💪 Running with sound null safety 💪
[   +1 ms] An Observatory debugger and profiler on Linux is available at: http://127.0.0.1:42647/e0svGDHcEk0=/
[ +338 ms] DevTools activation throttled until 2021-09-30 03:46:51.814847.
[ +537 ms] The Flutter DevTools debugger and profiler on Linux is available at: http://127.0.0.1:9102?uri=http://127.0.0.1:42647/e0svGDHcEk0=/
[+23136 ms] [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: 'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 317 pos 18: 'event is!
PointerRemovedEvent': is not true.
[        ] #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
[        ] #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
[        ] #2      MouseTracker.updateWithEvent.<anonymous closure>.<anonymous closure> (package:flutter/src/rendering/mouse_tracker.dart:317:18)
[        ] #3      MouseTracker._deviceUpdatePhase (package:flutter/src/rendering/mouse_tracker.dart:206:9)
[        ] #4      MouseTracker.updateWithEvent.<anonymous closure> (package:flutter/src/rendering/mouse_tracker.dart:312:7)
[        ] #5      MouseTracker._monitorMouseConnection (package:flutter/src/rendering/mouse_tracker.dart:190:9)
[        ] #6      MouseTracker.updateWithEvent (package:flutter/src/rendering/mouse_tracker.dart:311:5)
[        ] #7      RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:270:20)
[        ] #8      GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
[        ] #9      GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
[        ] #10     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
[        ] #11     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
[        ] #12     _rootRunUnary (dart:async/zone.dart:1444:13)
[        ] #13     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
[        ] #14     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
[        ] #15     _invoke1 (dart:ui/hooks.dart:185:10)
[        ] #16     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
[        ] #17     _dispatchPointerDataPacket (dart:ui/hooks.dart:98:31)
[ +750 ms] [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: 'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 201 pos 12:
'!_debugDuringDeviceUpdate': is not true.
[        ] #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
[        ] #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
[        ] #2      MouseTracker._deviceUpdatePhase (package:flutter/src/rendering/mouse_tracker.dart:201:12)
[        ] #3      MouseTracker.updateWithEvent.<anonymous closure> (package:flutter/src/rendering/mouse_tracker.dart:312:7)
[        ] #4      MouseTracker._monitorMouseConnection (package:flutter/src/rendering/mouse_tracker.dart:190:9)
[        ] #5      MouseTracker.updateWithEvent (package:flutter/src/rendering/mouse_tracker.dart:311:5)
[        ] #6      RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:270:20)
[        ] #7      GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
[        ] #8      GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
[        ] #9      GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
[        ] #10     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
[        ] #11     _rootRunUnary (dart:async/zone.dart:1444:13)
[        ] #12     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
[        ] #13     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
[        ] #14     _invoke1 (dart:ui/hooks.dart:185:10)
[        ] #15     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
[        ] #16     _dispatchPointerDataPacket (dart:ui/hooks.dart:98:31)
[ +411 ms] [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: 'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 201 pos 12:
'!_debugDuringDeviceUpdate': is not true.
[        ] #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
[        ] #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
[        ] #2      MouseTracker._deviceUpdatePhase (package:flutter/src/rendering/mouse_tracker.dart:201:12)
[        ] #3      MouseTracker.updateWithEvent.<anonymous closure> (package:flutter/src/rendering/mouse_tracker.dart:312:7)
[        ] #4      MouseTracker._monitorMouseConnection (package:flutter/src/rendering/mouse_tracker.dart:190:9)
[        ] #5      MouseTracker.updateWithEvent (package:flutter/src/rendering/mouse_tracker.dart:311:5)
[        ] #6      RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:270:20)
[        ] #7      GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
[        ] #8      GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
[        ] #9      GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
[        ] #10     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
[        ] #11     _rootRunUnary (dart:async/zone.dart:1444:13)
[        ] #12     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
[        ] #13     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
[        ] #14     _invoke1 (dart:ui/hooks.dart:185:10)
[        ] #15     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
[        ] #16     _dispatchPointerDataPacket (dart:ui/hooks.dart:98:31)
[ +578 ms] [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: 'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 201 pos 12:
'!_debugDuringDeviceUpdate': is not true.
[        ] #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
[        ] #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
[        ] #2      MouseTracker._deviceUpdatePhase (package:flutter/src/rendering/mouse_tracker.dart:201:12)
[        ] #3      MouseTracker.updateWithEvent.<anonymous closure> (package:flutter/src/rendering/mouse_tracker.dart:312:7)
[        ] #4      MouseTracker._monitorMouseConnection (package:flutter/src/rendering/mouse_tracker.dart:190:9)
[        ] #5      MouseTracker.updateWithEvent (package:flutter/src/rendering/mouse_tracker.dart:311:5)
[        ] #6      RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:270:20)
[        ] #7      GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
[        ] #8      GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
[        ] #9      GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
[        ] #10     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
[        ] #11     _rootRunUnary (dart:async/zone.dart:1444:13)
[        ] #12     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
[        ] #13     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
[        ] #14     _invoke1 (dart:ui/hooks.dart:185:10)
[        ] #15     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
[        ] #16     _dispatchPointerDataPacket (dart:ui/hooks.dart:98:31)
[ +847 ms] [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: 'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 201 pos 12:
'!_debugDuringDeviceUpdate': is not true.
[        ] #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
[        ] #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
[        ] #2      MouseTracker._deviceUpdatePhase (package:flutter/src/rendering/mouse_tracker.dart:201:12)
[        ] #3      MouseTracker.updateWithEvent.<anonymous closure> (package:flutter/src/rendering/mouse_tracker.dart:312:7)
[        ] #4      MouseTracker._monitorMouseConnection (package:flutter/src/rendering/mouse_tracker.dart:190:9)
[        ] #5      MouseTracker.updateWithEvent (package:flutter/src/rendering/mouse_tracker.dart:311:5)
[        ] #6      RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:270:20)
[        ] #7      GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
[        ] #8      GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
[        ] #9      GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
[        ] #10     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
[        ] #11     _rootRunUnary (dart:async/zone.dart:1444:13)
[        ] #12     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
[        ] #13     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
[        ] #14     _invoke1 (dart:ui/hooks.dart:185:10)
[        ] #15     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
[        ] #16     _dispatchPointerDataPacket (dart:ui/hooks.dart:98:31)
```
	
</details>

|  `stable`  | `master` |
| :---: |:---: |
|  ❗️  |   ❗️  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.5.1, on Zorin OS 16 5.11.0-37-generic, locale en_US.UTF-8)
    • Flutter version 2.5.1 at /home/taha/Code/flutter_stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (12 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/taha/Code/android-sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = /home/taha/Code/android-sdk
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 60.1.2
    • Dart plugin version 203.8292
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Zorin OS 16 5.11.0-37-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 94.0.4606.61

• No issues found!
```

```console
[✓] Flutter (Channel master, 2.6.0-12.0.pre.136, on Zorin OS 16 5.11.0-37-generic, locale en_US.UTF-8)
    • Flutter version 2.6.0-12.0.pre.136 at /home/taha/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision aaa14b8004 (4 hours ago), 2021-09-29 06:03:04 -0400
    • Engine revision bccb3a57eb
    • Dart version 2.15.0 (build 2.15.0-156.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/taha/Code/android-sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = /home/taha/Code/android-sdk
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 60.1.2
    • Dart plugin version 203.8292
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Zorin OS 16 5.11.0-37-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 94.0.4606.61

• No issues found!
```
		
</details>

✅: No Issue ❗️: Issue reproduced

Thanks for filing the issue
