### ISSUE TITLE
[flutter_image] A Timer is still pending even after the widget tree was disposed.

### ISSUE THREAD

**Issue by cirediew** [flutter/flutter#90861]
When running a widget test on a widget which includes a `NetworkImageWithRetry` from package `flutter_image` I get the following exception:

```
Pending timers:
Timer (duration: 0:00:30.000000, periodic: false), created:
#0      new FakeTimer._ (package:fake_async/fake_async.dart:284:41)
#1      FakeAsync._createTimer (package:fake_async/fake_async.dart:248:27)
#2      FakeAsync.run.<anonymous closure> (package:fake_async/fake_async.dart:181:19)
#6      NetworkImageWithRetry._loadWithRetry (package:flutter_image/network.dart:143:14)
<asynchronous suspension>
<asynchronous suspension>
(elided 4 frames from dart:async and package:stack_trace)

══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
A Timer is still pending even after the widget tree was disposed.
'package:flutter_test/src/binding.dart':
Failed assertion: line 1278 pos 12: '!timersPending'

When the exception was thrown, this was the stack:
#2      AutomatedTestWidgetsFlutterBinding._verifyInvariants (package:flutter_test/src/binding.dart:1278:12)
#3      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:832:7)
<asynchronous suspension>
(elided 2 frames from class _AssertionError)
════════════════════════════════════════════════════════════════════════════════════════════════════

Test failed. See exception logs above.
The test description was: Widget Test
```

## Steps to Reproduce

Using this small example the exception can be reproduced.
```dart
class Example extends StatelessWidget {
  const Example({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Column(
        children: const [
          Text('example'),
          Image(
            image: NetworkImageWithRetry('https://flutter.dev/assets/images/shared/brand/flutter/logo/flutter-lockup.png'),
          )
        ],
      ),
    );
  }
}
```
```dart
  testWidgets('Widget Test', (tester) async {
    await tester.pumpWidget(
      const Example(),
    );
    expect(find.text('example'), findsOneWidget);
  });
```
I haven't been able to find a solution to solve this issue myself.
I tried a custom `fetchStrategy` and set attempts to 1 and the timeouts to 1 second, however that makes no difference.

Edit:
```
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 2.5.0 at /Users/me/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (3 weeks ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0
```
```
flutter_image: 4.1.0
```

**Comment by danagbemava-nc** [comment]
Hi @cirediew, 
Running tests with a live/external url is not something that works because network requests take quite a bit of time to complete. They are usually mocked. You can check the `flutter_image` `tests` folder t see how they test it.

As to why you're getting `A Timer is still pending even after the widget tree was disposed`, I can't quite say. 

When I run your example, the output below is what I get which is expected because I'm making a network request in a test. 

Is there anymore context/information you can provide?

Thank you

<details>
<summary>code and logs</summary>

`test method`

```dart
void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  testWidgets('Widget Test', (tester) async {
    await tester.pumpWidget(
      const Example(),
    );
    expect(find.text('example'), findsOneWidget);
  });
}

```

`console output`

```console
══╡ EXCEPTION CAUGHT BY PACKAGE:FLUTTER_IMAGE ╞═════════════════════════════════════════════════════
The following FetchFailure was thrown NetworkImageWithRetry failed to load
https://flutter.dev/assets/images/shared/brand/flutter/logo/flutter-lockup.png:
FetchFailure(
  attemptCount: 1
  httpStatusCode: 400
  totalDuration: 0:00:00.122179
  originalException: null
)
════════════════════════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
The following FetchFailure was thrown resolving a single-frame image stream:
FetchFailure(
  attemptCount: 1
  httpStatusCode: 400
  totalDuration: 0:00:00.122179
  originalException: null
)

When the exception was thrown, this was the stack:
#0      NetworkImageWithRetry._loadWithRetry (package:flutter_image/network.dart:212:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

Image provider:
NetworkImageWithRetry("https://flutter.dev/assets/images/shared/brand/flutter/logo/flutter-lockup.png",
scale: 1.0)
Image key:
NetworkImageWithRetry("https://flutter.dev/assets/images/shared/brand/flutter/logo/flutter-lockup.png",
scale: 1.0)
════════════════════════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following message was thrown:
Multiple exceptions (2) were detected during the running of the current test, and at least one was
unexpected.
════════════════════════════════════════════════════════════════════════════════════════════════════
Test failed. See exception logs above.
The test description was: Widget Test

Warning: At least one test in this suite creates an HttpClient. When
running a test suite that uses TestWidgetsFlutterBinding, all HTTP
requests will return status code 400, and no network request will
actually be made. Any test expecting a real network connection and
status code will fail.
To test code that needs an HttpClient, provide your own HttpClient
implementation to the code under test, so that your test can
consistently provide a testable response to the code under test.
✖ Widget Test
Exited (1)
```

</details>

**Comment by cirediew** [comment]
Thank you for your reply.

I've tried to test it like the package example is doing.
This is my code now:
```dart
void main() {
  HttpOverrides.global = null;

  testWidgets('Widget Test', (tester) async {
    await tester.pumpWidget(
      const Example(),
    );
    expect(find.text('example'), findsOneWidget);
  });
}

class Example extends StatelessWidget {
  const Example({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Column(
        children: [
          const Text('example'),
          Image(
            image: NetworkImageWithRetry(
              'http://localhost:11111/immediate_success.png',
            ),
          )
        ],
      ),
    );
  }
}
```
Using the same mock server as the example
[https://github.com/flutter/packages/blob/master/packages/flutter_image/test/network_test_server.dart](https://github.com/flutter/packages/blob/master/packages/flutter_image/test/network_test_server.dart)

And the same script too, excluding the package get and analyze.
```bash
#!/bin/bash
# Copyright 2013 The Flutter Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Fast fail the script on failures.
set -e
# Print commands to stdout
set -x

#flutter packages get
#flutter analyze lib/ test/

dart test/network_test_server.dart &
SERVER_PID=$!
sleep 2

flutter test --plain-name "Widget Test" test/widget_test/test_page_test.dart
kill $SERVER_PID
```

But I stil get the same exception.
```
+ SERVER_PID=2612
+ sleep 2
+ dart test/network_test_server.dart
+ flutter test --plain-name 'Widget Test' test/widget_test/test_page_test.dart
00:03 +0: Widget Test                                                                                                                                                                                    
Pending timers:
Timer (duration: 0:00:30.000000, periodic: false), created:
#0      new FakeTimer._ (package:fake_async/fake_async.dart:284:41)
#1      FakeAsync._createTimer (package:fake_async/fake_async.dart:248:27)
#2      FakeAsync.run.<anonymous closure> (package:fake_async/fake_async.dart:181:19)
#6      NetworkImageWithRetry._loadWithRetry (package:flutter_image/network.dart:143:14)
<asynchronous suspension>
<asynchronous suspension>
(elided 4 frames from dart:async and package:stack_trace)

══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
A Timer is still pending even after the widget tree was disposed.
'package:flutter_test/src/binding.dart':
Failed assertion: line 1278 pos 12: '!timersPending'

When the exception was thrown, this was the stack:
#2      AutomatedTestWidgetsFlutterBinding._verifyInvariants (package:flutter_test/src/binding.dart:1278:12)
#3      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:832:7)
<asynchronous suspension>
(elided 2 frames from class _AssertionError)

The test description was:
  Widget Test
════════════════════════════════════════════════════════════════════════════════════════════════════
00:03 +0 -1: Widget Test [E]                                                                                                                                                                             
  Test failed. See exception logs above.
  The test description was: Widget Test
  
00:03 +0 -1: Some tests failed.    
```

**Comment by danagbemava-nc** [comment]
Hi @cirediew, 

Can you kindly upgrade to stable `2.5.1` and see if you still experience this issue?

Use the following commands

`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

Thank you

**Comment by cirediew** [comment]
@danagbemava-nc 
Updated my flutter but the issue remains the same.

```
+ SERVER_PID=30318
+ sleep 2
+ dart test/network_test_server.dart
+ flutter test --plain-name 'Widget Test' test/widget_test/test_page_test.dart
00:03 +0: Widget Test                                                                                                                                                                                                                  
Pending timers:
Timer (duration: 0:00:30.000000, periodic: false), created:
#0      new FakeTimer._ (package:fake_async/fake_async.dart:284:41)
#1      FakeAsync._createTimer (package:fake_async/fake_async.dart:248:27)
#2      FakeAsync.run.<anonymous closure> (package:fake_async/fake_async.dart:181:19)
#6      NetworkImageWithRetry._loadWithRetry (package:flutter_image/network.dart:143:14)
<asynchronous suspension>
<asynchronous suspension>
(elided 4 frames from dart:async and package:stack_trace)

══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
A Timer is still pending even after the widget tree was disposed.
'package:flutter_test/src/binding.dart':
Failed assertion: line 1278 pos 12: '!timersPending'

When the exception was thrown, this was the stack:
#2      AutomatedTestWidgetsFlutterBinding._verifyInvariants (package:flutter_test/src/binding.dart:1278:12)
#3      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:832:7)
<asynchronous suspension>
(elided 2 frames from class _AssertionError)

The test description was:
  Widget Test
════════════════════════════════════════════════════════════════════════════════════════════════════
00:03 +0 -1: Widget Test [E]                                                                                                                                                                                                           
  Test failed. See exception logs above.
  The test description was: Widget Test
  
00:03 +0 -1: Some tests failed.                                                                                                                                                                                                        
```

<details>
<summary>Flutter doctor</summary>

```
[✓] Flutter (Channel stable, 2.5.1, on macOS 11.6 20G165 darwin-x64, locale en-GB)
    • Flutter version 2.5.1 at /Users/me/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (13 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/me/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/me/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7678000/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/me/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7678000/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/me/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7621141/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • My iPhone 12 (mobile) • CCCE4121-9462-45D6-AB44-83381F52B58C • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)       • macos                                • darwin-x64     • macOS 11.6 20G165 darwin-x64
    • Chrome (web)          • chrome                               • web-javascript • Google Chrome 94.0.4606.61

! Doctor found issues in 1 category.
```

</details>

**Comment by danagbemava-nc** [comment]
@cirediew 

From what I gathered [here](https://github.com/flutter/flutter/issues/53296) and [here](https://github.com/flutter/flutter/issues/47743), it seems this error occurs when a Timer is created 
but it is not cancelled, it might be worth looking into the source of `flutter_image` to see if any 

such timer is used. 

But do you get this error without using the `NetworkImageWithRetry` widget?

**Comment by cirediew** [comment]
@danagbemava-nc 

It must be the timer created by setting the timeout on the get [network.dart#L143](https://github.com/flutter/packages/blob/master/packages/flutter_image/lib/network.dart#L143)

All I would like is a way to test my widgets containing NetworkImageWithRetry. 
I've also tried mocking a HttpClient, but by doing that I've run into the problem of not being able to mock the builder [network.dart#L160](https://github.com/flutter/packages/blob/master/packages/flutter_image/lib/network.dart#L160) since it's a private class.

Obviously the error disappears when I don't use `NetworkImageWithRetry`

**Comment by cirediew** [comment]
@danagbemava-nc 
Thank you, that will work.
I've changed it slightly to
```dart
@visibleForTesting
static ImageProvider? imageProvider;
```
and leave it out of the constructor of my `Example` class.

However, I do think there should be a way to test it by mocking the http client and response, but this is currently prohibited by `_Uint8ListBuilder` being a private class.

**Comment by danagbemava-nc** [comment]
You can test `NetworkImageWithRetry`, but it can't be done in the `widgetTest` at least from what I've seen. 

The `NetworkImageProvider` tests do use a `FakeHttpClient`, however, it is tested as a regular `dart` class and not as a widget. 

Regardless, since your initial issue has been solved, I feel it is safe to close this issue. 

Closing as solved. If you have any more issues, kindly file a new one. 

Thank you
