### ISSUE TITLE
[tool_crash] FormatException from _IOSSimulatorLogReader

### ISSUE THREAD

**Issue by developerpaaji** [flutter/flutter#90899]
## Command
```
flutter run --machine --start-paused -d 18AB0070-B532-41BE-B212-36A462D7977C --dart-define=flutter.inspector.structuredErrors=true --web-allow-expose-url --devtools-server-address http://127.0.0.1:9100/ --target lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FormatException
```
#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1404:5)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:515:9)
#2      _parseJson (dart:convert-patch/convert_patch.dart:41:10)
#3      JsonDecoder.convert (dart:convert/json.dart:506:36)
#4      JsonCodec.decode (dart:convert/json.dart:157:41)
#5      jsonDecode (dart:convert/json.dart:96:10)
#6      _IOSSimulatorLogReader._onUnifiedLoggingLine (package:flutter_tools/src/ios/simulators.dart:857:35)
#7      _rootRunUnary (dart:async/zone.dart:1362:47)
#8      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#9      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#12     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#13     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#14     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#15     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:155:13)
#16     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:130:5)
#17     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#18     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#19     _rootRunUnary (dart:async/zone.dart:1362:47)
#20     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#22     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#23     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#24     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
```
```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.6 20G165 darwin-arm, locale en-IN)
    • Flutter version 2.2.3 at /Users/bhavneetsingh/Documents/flutter
    • Framework revision f4abaa0735 (3 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/bhavneetsingh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.60.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • iPhone 12 (mobile) • 18AB0070-B532-41BE-B212-36A462D7977C • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 94.0.4606.61
    ! Error: iPhone is not connected. Xcode will continue when iPhone is connected. (code -13)

• No issues found!

```

## Flutter Application Metadata
**Type**: null
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
file_picker-4.0.2
flutter_plugin_android_lifecycle-2.0.3
flutter_tts-3.2.2
fluttertoast-8.0.8
path_provider-2.0.3
path_provider_linux-2.0.2
path_provider_macos-2.0.2
path_provider_windows-2.0.3
razorpay_flutter-1.2.7
share-2.0.4
shared_preferences-2.0.7
shared_preferences_linux-2.0.2
shared_preferences_macos-2.0.2
shared_preferences_web-2.0.2
shared_preferences_windows-2.0.2
url_launcher-6.0.10
url_launcher_linux-2.0.2
url_launcher_macos-2.0.2
url_launcher_web-2.0.4
url_launcher_windows-2.0.2

**Comment by christopherfujino** [comment]
Similar stacktrace:

```
Thread 0 main threadFormatException: FormatException: Missing expected digit (at character 3)[-[SimLaunchHostConnection _onQueue_launchInstanceUnload:]_block_invoke:302...  ^
at _ChunkedJsonParser.fail(convert_patch.dart:1405)
at _ChunkedJsonParser.parseNumber(convert_patch.dart:1269)
at _ChunkedJsonParser.parse(convert_patch.dart:937)
at _parseJson(convert_patch.dart:40)
at JsonDecoder.convert(json.dart:506)
at JsonCodec.decode(json.dart:157)
at XCDevice._getAllDevices(xcdevice.dart:115)
at <asynchronous gap>(async)
at XCDevice.getAvailableIOSDevices(xcdevice.dart:227)
at <asynchronous gap>(async)
at IOSDevices._onDeviceEvent(devices.dart:103)
at <asynchronous gap>(async)
```

**Comment by jmagman** [comment]
The JSON decoding is gated on a regex so it at least contains `"eventMessage" : "something"`
https://github.com/flutter/flutter/blob/89637e4e47362273fa7b5b1a5619110336a31372/packages/flutter_tools/lib/src/ios/simulators.dart#L856-L859

My guess is that the `eventMessage` contents aren't correctly escaped?  I'll add a catch here with an error print like https://github.com/flutter/flutter/pull/37958.
