### ISSUE TITLE
Encountered error while archiving for device. 

### ISSUE THREAD

**Issue by ahmedsabahi** [flutter/flutter#90957]
My project run on an ios simulator but when I use " flutter build ipa " Errors appear

<details> 
<summary>logs</summary> 
	
```console
                PhaseScriptExecution Run\ Script

/Users/mac/Library/Developer/Xcode/DerivedData/Runner-cijrjlaolzgrxfchbuobavwtgimc/Build/Intermediates.noindex/ArchiveIntermediates/Runner/I
                ntermediateBuildFilesPath/Runner.build/Release-iphoneos/Runner.build/Script-9740EEB61CF901F6004384FC.sh (in target 'Runner' from
project
                'Runner')
               (1 failure)
----------------------------------------------------

> [+39441 ms] "flutter ipa" took 1,927,425ms.
[   +7 ms] Encountered error while archiving for device.
[   +2 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:277:7)
           <asynchronous suspension>
           #2      BuildIOSArchiveCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:122:50)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>
```
	
</details>

when I use Product>Archive -> [XcodeLogs.txt](https://github.com/flutter/flutter/files/7254006/XcodeLogs.txt)

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.5.1, on macOS 11.6 20G165 darwin-x64, locale en-EG)
    • Flutter version 2.5.1 at /Users/mac/developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (12 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[!] Connected device
    ! No devices available
```
	 
</details>

**Comment by TahaTesser** [comment]
Hi @ahmedsabahi 
Unfortunately, the error is not much helpful, can you please provide complete logs with `flutter build ipa > build_ipa.log` without using third-party packages?
Thank you

**Comment by ahmedsabahi** [comment]
> Hi @ahmedsabahi Unfortunately, the error is not much helpful, can you please provide complete logs with `flutter build ipa > build_ipa.log` without using third-party packages? Thank you

thanks for reply 
`flutter build ipa > build_ipa.log` -> [build_ipa.log](https://github.com/flutter/flutter/files/7258944/build_ipa.log)

**Comment by TahaTesser** [comment]
Hi @ahmedsabahi 
i can only see warning messages, ` archiving failed`  before warning messages,  warning messages it shouldm't fail your archive, looks like you're usine some third-party packages too.


Can you please open Xcode,  make sure there no errors in signing & capabilties?  Try to reprodice the issue without third-party packages in a new project

`flutter create myapp`
`cd myapp`
`flutter build ipa -v > new_ipa.log` (please `-v` for verbose)

**Comment by ahmedsabahi** [comment]
Hi @TahaTesser 

`flutter build ipa -v > new_ipa.log`  -> [myapp_ipa.log](https://github.com/flutter/flutter/files/7271236/myapp_ipa.log)

**Comment by TahaTesser** [comment]
Hi @ahmedsabahi 
This looks  like an issue with your app signing, please try the solution from [here](https://developer.apple.com/forums/thread/86161), if the problem persists, please file an issue on Apple  developer [forum](https://developer.apple.com/forums/)
```console
               [   +7 ms] Target release_unpack_ios failed: Exception: Failed to codesign /Users/mac/Library/Developer/Xcode/DerivedData/Runner-dzfxiniikzzszggygozaqjsbubcn/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/Flutter.framework/Flutter with identity B4A327F6193D241496ECFD28213147ED683E9472.
                          Warning: unable to build chain to self-signed root for signer "Apple Development: Ahmed Sabahy (2U72ML3X44)"
                          /Users/mac/Library/Developer/Xcode/DerivedData/Runner-dzfxiniikzzszggygozaqjsbubcn/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/Flutter.framework/Flutter: errSecInternalComponent
```
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
