### ISSUE TITLE
[Desktop] DropdownButton Failed assertion: line 581 pos 12: 'menuHeight == menuBottom - menuTop': is not true

### ISSUE THREAD

**Issue by KKStudios** [flutter/flutter#90964]
When running the below example code in Windows in maximized (window) Mode (not Window Mode! and not when changing from window mode to maximized Mode!) when trying to select the Dropdownbutton the following Error Message is thrown:

```
'package:flutter/src/material/dropdown.dart': Failed assertion: line 581 pos 12: 'menuHeight == menuBottom - menuTop': is not true.

The relevant error-causing widget was: 
  MaterialApp MaterialApp:file:///D:/Programming/Projects/Flutter/bugtest/lib/main.dart:12:12
When the exception was thrown, this was the stack: 
#2      _DropdownRoute.getMenuLimits (package:flutter/src/material/dropdown.dart:581:12)
#3      _DropdownRoutePage.build (package:flutter/src/material/dropdown.dart:627:44)
#4      StatelessElement.build (package:flutter/src/widgets/framework.dart:4660:28)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4586:15)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4564:5)
#8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4559:5)
#9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3631:14)
```

<details>
<summary>Code to Reproduce the Bug:</summary>

```


void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  String selected = "test";

  @override
  Widget build(BuildContext context) {

    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: (){
          Navigator.push(context, DialogRoute<void>(
              context: context,
              barrierDismissible: false,
              builder: (BuildContext context){

                var height = MediaQuery.of(context).size.height * 0.8;
                var width = MediaQuery.of(context).size.width * 0.8;

                return Dialog(
                    child: SizedBox(
                      height: height,
                      width: width,
                      child: _panelContent(),
                    )
                );
              }
          ));
        },
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }

  Widget _panelContent(){
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: <Widget>[
          Container(
            width: 500,
            height: 200,
            color: Colors.blue,
          ),
          DropdownButton(
              value: selected,
              onChanged: (String? s) => setState(() {
                selected = s ?? selected;
              }),
              items: [DropdownMenuItem(child: Text("test"), value: "test"),
                DropdownMenuItem(child: Text("test 1"), value: "test1"),
                DropdownMenuItem(child: Text("test 2"), value: "test2"),
                DropdownMenuItem(child: Text("test 3"), value: "test3"),
                DropdownMenuItem(child: Text("test 4"), value: "test4"),
                DropdownMenuItem(child: Text("test 5"), value: "test5"),
                DropdownMenuItem(child: Text("test 6"), value: "test6")
              ]),
          Expanded(child: Container(color: Colors.blue,))
        ],
      ),
    );
  }
}




```

</details>
I was able to reproduce the error I was encountering in another application by this code above. Maybe it's just a not intended use case or I did something completely stupid but even then the errormessage is not giving any hint to what the reason was and how I could solve the issue.

Running the above code as Windows application in window mode, it works like intended. When I first run it in window mode and maximize the window it runs as intended. When I start the application as maximized window, the error appears. 
Hope this can be solved fast.

```
Doctor:
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 2.6.0-12.0.pre.136, on Microsoft Windows [Version 10.0.19043.1237], locale de-DE)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.4)
[√] Android Studio (version 4.2)
[√] VS Code (version 1.55.2)
[√] Connected device (3 available)

• No issues found!
```

**Comment by darshankawar** [comment]
> When running the below example code in Windows in Fullscreen Mode

There's no built-in support for Fullscreen mode for desktop yet. See [this](https://stackoverflow.com/a/57827134) comment for your reference which still seems to be true. 

Did you change the runner code directly to launch in full screen mode ?
For full screen support on desktop, you may follow-up in [this](https://github.com/flutter/flutter/issues/67708) open issue for further updates.


> Running the above code as Windows application in window mode, it works like intended.

Since this is WAI, the error you are getting is due to no support for full screen mode.  I am going ahead and closing this.

**Comment by KKStudios** [comment]
@darshankawar I'm terribly sorry, I did not mean the (F11) Fullscreenmode but the Maximized (Window) Mode. Where the view sizes to the full screen size but with the bar at the top where you can change to window mode or minimize the application.

**Comment by darshankawar** [comment]
@KKStudios 
Thanks for clarification. The full screen mode got me confused and hence closed with relevant details.
Reopening.

**Comment by darshankawar** [comment]
I verified this on windows desktop using latest stable and master. The error is replicable only on latest master.

Steps to replicate:

1. Run the sample code.
2. Maximize the window to full screen.
3. Tap on FAB
4. Try to select from dropdown that throws below error on screen:

![Screenshot 2021-09-30 at 2 59 45 PM](https://user-images.githubusercontent.com/67046386/135427474-01505ff2-566b-43cf-94aa-4d9e5ea0665b.png)

<details>
<summary> error log </summary>

```

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building _DropdownRoutePage<String>(dirty):
'package:flutter/src/material/dropdown.dart': Failed assertion: line 581 pos 12: 'menuHeight ==
menuBottom - menuTop': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was:
  MaterialApp MaterialApp:file:///D:/FlutterApps/wintest/lib/main.dart:14:12

When the exception was thrown, this was the stack:
#2      _DropdownRoute.getMenuLimits (package:flutter/src/material/dropdown.dart:581:12)
#3      _DropdownRoutePage.build (package:flutter/src/material/dropdown.dart:627:44)
#4      StatelessElement.build (package:flutter/src/widgets/framework.dart:4660:28)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4586:15)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4564:5)
#8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4559:5)
#9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3631:14)
#10     Element.updateChild (package:flutter/src/widgets/framework.dart:3383:18)
#11     _LayoutBuilderElement._layout.layoutCallback (package:flutter/src/widgets/layout_builder.dart:137:18)
#12     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2531:19)
#13     _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:154:12)
#14     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1968:59)
#15     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:916:15)
#16     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1968:14)
#17     RenderConstrainedLayoutBuilder.rebuildIfNecessary (package:flutter/src/widgets/layout_builder.dart:228:7)
#18     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:317:5)
#19     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#20     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#21     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#22     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#23     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#24     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#25     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#26     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#27     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#29     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#30     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#31     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3410:13)
#32     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#33     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#34     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#35     _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:751:15)
#36     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1713:7)
#37     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:885:18)
#38     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:453:19)
#39     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#40     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
#41     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
#42     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#43     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#47     _invoke (dart:ui/hooks.dart:150:10)
#48     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#49     _drawFrame (dart:ui/hooks.dart:114:31)
(elided 5 frames from class _AssertionError and dart:async)

════════════════════════════════════════════════════════════════════════════════════════════════════
Lost connection to device.

D:\FlutterApps\wintest>


```

</details>

The same steps works properly on latest stable.

![Screenshot 2021-09-30 at 2 59 36 PM](https://user-images.githubusercontent.com/67046386/135427641-2c1ea8a9-3da7-40d7-9e9d-e759b8ab6505.png)


Also verified the same on macOS desktop using latest master and it works fine there.

<details>
<summary> flutter doctor -v </summary>

```

[√] Flutter (Channel master, 2.6.0-12.0.pre.150, on Microsoft Windows [Version 10.0.19042.1237], locale en-US)
    • Flutter version 2.6.0-12.0.pre.150 at D:\FlutterSDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 367531447c (8 hours ago), 2021-09-29 20:03:04 -0400
    • Engine revision 9224a17d1c
    • Dart version 2.15.0 (build 2.15.0-162.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Win\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31624.102
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.60.1)
    • VS Code at C:\Users\Win\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.1237]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 93.0.4577.82
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 93.0.961.52

• No issues found!

[√] Flutter (Channel stable, 2.5.1, on Microsoft Windows [Version 10.0.19042.1237], locale en-US)
    • Flutter version 2.5.1 at D:\FlutterSDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (4 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Win\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31624.102
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.60.1)
    • VS Code at C:\Users\Win\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm    • Android 8.1.0 (API 27)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.19042.1237]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 93.0.4577.82
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 93.0.961.52

• No issues found!

```

</details>

**Comment by KKStudios** [comment]
@darshankawar  
Ok thank you for taking care and sorry again for not being precise on the terms there.
