### ISSUE TITLE
RangeSlider exception during drawFrame: Null check operator used on a null value

### ISSUE THREAD

**Issue by greensopinion** [flutter/flutter#91029]
## Steps to Reproduce

Crash report from released app (steps unknown)

**Expected results:** runs without exceptions

**Actual results:** stack trace (see below)

```
OS: android - RQ3A.210905.001
Null check operator used on a null value
#0      _RenderRangeSlider.assembleSemanticsNode (package:flutter/src/material/range_slider.dart:1575)
#1      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3822)
#2      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3814)
#3      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3814)
#4      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3768)
#5      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3768)
#6      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3768)
#7      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3814)
#8      _RootSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3692)
#9      RenderObject._updateSemantics (package:flutter/src/rendering/object.dart:2731)
#10     PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1080)
#11     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:458)
#12     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883)
#13     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319)
#14     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143)
#15     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1080)
#16     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996)
#17     _rootRun (dart:async/zone.dart:1428)
#18     _CustomZone.run (dart:async/zone.dart:1328)
#19     _CustomZone.runGuarded (dart:async/zone.dart:1236)
#20     _invoke (dart:ui/hooks.dart:166)
#21     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270)
#22     _drawFrame (dart:ui/hooks.dart:129)
```

```
% flutter analyze
Analyzing app...                                     
No issues found! (ran in 3.5s)
```

```
% flutter doctor -v
[✓] Flutter (Channel stable, 2.5.1, on macOS 11.3.1 20E241 darwin-x64, locale en-CA)
    • Flutter version 2.5.1 at /Users/user/development/flutter_stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (13 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/user/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[!] Android Studio
    • Android Studio at /Users/user/Downloads/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.60.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • iPhone 12 (mobile) • 73C2DF31-CA40-4FF0-9532-389A33FFE62E • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 94.0.4606.61

```

**Comment by maheshmnj** [comment]
Hi @greensopinion, Thanks for filing the issue. I verified using the [official sample code](https://api.flutter.dev/flutter/material/RangeSlider-class.html) and it works fine on `stable 2.5.1` and `stable: 2.5.2` as well as the latest master channel. From the logs, I suspect that your project might be using a range slider, and interacting with it might have caused an issue. Without any reproducible steps, It is not very likely to be able to track down the bug. 

I would advise if your project has a range slider to try to create a new project and try to replicate the issue or at least try to reproduce it in your project, It would be really helpful to debug the cause of the bug. 

Thanks

**Comment by greensopinion** [comment]
@maheshmnj Thanks for looking into it! I agree, without reproducible steps, it's hard to know what's going wrong there.

I'll see if I can come up with steps to reproduce. In the meantime, at least the team knows that it's possible for that field to be null when it's dereferenced.
