### ISSUE TITLE
Crash when doing flutter run --release

### ISSUE THREAD

**Issue by vlidholt** [flutter/flutter#9102]
flutter run --release stopped working for some reason, can still build release version from inside Android Studio.

## command

flutter run --release

## exception

FileSystemException: FileSystemException: Cannot copy file to 'android/app/build/outputs/apk/app.apk', path = 'android/app/build/outputs/apk/app-release.apk' (OS Error: No such file or directory, errno = 2)

```
#0      _File.throwIfError (dart:io/file_impl.dart:625)
#1      _File.copySync (dart:io/file_impl.dart:336)
#2      _LocalFileSystemEntity&ForwardingFile.copySync (package:file/src/forwarding/forwarding_file.dart:25)
#3      buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:231)
<asynchronous suspension>
#4      buildGradleProject (package:flutter_tools/src/android/gradle.dart:171)
<asynchronous suspension>
#5      buildApk (package:flutter_tools/src/commands/build_apk.dart:99)
<asynchronous suspension>
#6      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:305)
<asynchronous suspension>
#7      ColdRunner.run (package:flutter_tools/src/run_cold.dart:83)
<asynchronous suspension>
#8      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:281)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:151)
<asynchronous suspension>
#10     RunCommand.verifyThenRunCommand (package:flutter_tools/src/commands/run.dart:196)
<asynchronous suspension>
#11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:121)
#12     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:261)
<asynchronous suspension>
#14     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#15     Future.Future.sync (dart:async/future.dart:208)
#16     CommandRunner.run (package:args/command_runner.dart:109)
#17     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:157)
#18     run.<anonymous closure> (package:flutter_tools/executable.dart:140)
<asynchronous suspension>
#19     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#20     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#21     _rootRun (dart:async/zone.dart:1150)
#22     _CustomZone.run (dart:async/zone.dart:1026)
#23     runZoned (dart:async/zone.dart:1503)
#24     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#25     run (package:flutter_tools/executable.dart:113)
<asynchronous suspension>
#26     main (package:flutter_tools/executable.dart:66)
<asynchronous suspension>
#27     main (file:///Users/vik/Projects/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#28     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

## flutter doctor

```
[✓] Flutter (on Mac OS X 10.12.3 16D32, channel master)
    • Flutter at /Users/vik/Projects/flutter
    • Framework revision f16e634e2e (4 days ago), 2017-03-26 11:52:44
    • Engine revision 61fc1d6e31
    • Tools Dart version 1.23.0-dev.9.0

[✓] Host Executable Compatibility
    • Downloaded executables execute on host

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/vik/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.0

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2016.3.4)
    • Dart plugin version 163.13137
    • Flutter plugin version 0.1.11.1

[✓] Connected devices
    • Nexus 5X • 01023965355db590 • android-arm • Android 6.0 (API 23)

**Comment by eseidelGoogle** [comment]
Presumably building the apk failed first?  FYI @jakobr-google @johnmccutchan

**Comment by sethladd** [comment]
Marked as TODAY and CRASH. Thanks for the feedback.

**Comment by christian-lefty** [comment]
My java build started failing, this is possibly related

Cause: com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
    	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:591)
    	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:546)
    	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:528)
    	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
    	at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
    	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
    	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
    	at com.android.dx.command.dexer.Main.run(Main.java:277)
    	at com.android.dx.command.dexer.Main.main(Main.java:245)
    	at com.android.dx.command.Main.main(Main.java:106)

**Comment by christian-lefty** [comment]
Possibly related? 
https://github.com/flutter/flutter/issues/9120

**Comment by collinjackson** [comment]
I rolled back what I believe is the problematic change, please reopen if you're still seeing issues.

**Comment by vlidholt** [comment]
Upgraded to the latest flutter version today. Still crashing.

## command

flutter run --release

## exception

FileSystemException: FileSystemException: Cannot copy file to 'android/app/build/outputs/apk/app.apk', path = 'android/app/build/outputs/apk/app-release.apk' (OS Error: No such file or directory, errno = 2)

```
#0      _File.throwIfError (dart:io/file_impl.dart:599)
#1      _File.copySync (dart:io/file_impl.dart:321)
#2      _LocalFileSystemEntity&ForwardingFile.copySync (package:file/src/forwarding/forwarding_file.dart:25)
#3      buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:231)
<asynchronous suspension>
#4      buildGradleProject (package:flutter_tools/src/android/gradle.dart:171)
<asynchronous suspension>
#5      buildApk (package:flutter_tools/src/commands/build_apk.dart:78)
<asynchronous suspension>
#6      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:315)
<asynchronous suspension>
#7      ColdRunner.run (package:flutter_tools/src/run_cold.dart:83)
<asynchronous suspension>
#8      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:291)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:151)
<asynchronous suspension>
#10     RunCommand.verifyThenRunCommand (package:flutter_tools/src/commands/run.dart:205)
<asynchronous suspension>
#11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:121)
#12     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:262)
<asynchronous suspension>
#14     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#15     Future.Future.sync (dart:async/future.dart:208)
#16     CommandRunner.run (package:args/command_runner.dart:109)
#17     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:157)
#18     run.<anonymous closure> (package:flutter_tools/executable.dart:140)
<asynchronous suspension>
#19     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#20     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#21     _rootRun (dart:async/zone.dart:1120)
#22     _CustomZone.run (dart:async/zone.dart:1001)
#23     runZoned (dart:async/zone.dart:1465)
#24     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#25     run (package:flutter_tools/executable.dart:113)
<asynchronous suspension>
#26     main (package:flutter_tools/executable.dart:66)
<asynchronous suspension>
#27     main (file:///Users/vik/Projects/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#28     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

## flutter doctor

```
[✓] Flutter (on Mac OS X 10.12.3 16D32, channel master)
    • Flutter at /Users/vik/Projects/flutter
    • Framework revision b52d659406 (13 hours ago), 2017-04-17 15:44:41 -0700
    • Engine revision c24a0e5175
    • Tools Dart version 1.23.0-dev.11.7

[✓] Host Executable Compatibility
    • Downloaded executables execute on host

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/vik/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3, Build version 8E162
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.0

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2016.3.4)
    • Dart plugin version 163.13137
    • Flutter plugin version 0.1.11.1

[✓] Connected devices
    • Nexus 5X • 01023965355db590 • android-arm • Android 6.0 (API 23)

```

**Comment by johnmccutchan** [comment]
@jakobr-google

**Comment by mit-mit** [comment]
@vlidholt can you try to create a new flutter project, and then compare the gradle files it has against yours?

* `/android/build.gradle`
* `/android/gradle.properties`
* `/android/local.properties`
* `/android/settings.gradle`
* `/android/app/build.gradle`

**Comment by collinjackson** [comment]
Removing myself as assignee; I believe my rollback fixed the issue that @christian-lefty was dealing with and Viktor's crash is unrelated.

**Comment by mit-mit** [comment]
Closing this; @vlidholt if you still see this issue after syncing gradle files to latest versions, please let us know!
