### ISSUE TITLE
[tool_crash] FileSystemException: Deletion failed, OS Error: The process cannot access the file because it is being used by another process., errno = 32

### ISSUE THREAD

**Issue by AmarIdeaUsher** [flutter/flutter#91027]
## Command
```
flutter --no-color build apk
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Deletion failed, OS Error: The process cannot access the file because it is being used by another process.
, errno = 32
```
#0      _Directory._deleteSync (dart:io/directory_impl.dart:201:7)
#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:408:7)
#2      _File._deleteSync (dart:io/file_impl.dart:295:50)
#3      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:408:7)
#4      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#5      ErrorHandlingFileSystem.deleteIfExists (package:flutter_tools/src/base/error_handling_io.dart:82:12)
#6      ErrorHandlingFile.copySync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:352:33)
#7      _runSync (package:flutter_tools/src/base/error_handling_io.dart:597:14)
#8      ErrorHandlingFile.copySync (package:flutter_tools/src/base/error_handling_io.dart:336:5)
#9      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:453:13)
<asynchronous suspension>
#10     AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:178:5)
<asynchronous suspension>
#11     BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:105:5)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.5.1, on Microsoft Windows [Version 10.0.18363.1801], locale en-US)
    • Flutter version 2.5.1 at C:\FlutterDev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (13 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Amy\AppData\Local\Android\sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.58.2)
    • VS Code at C:\Users\Amy\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • M2101K6I (mobile) • b571c376 • android-arm64  • Android 11 (API 30)
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 94.0.4606.61
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 93.0.961.52

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f4abaa0735eba4dfd8f33f73363911d63931fe03
### Plugins
audio_session-0.1.5
connectivity-3.0.6
connectivity_for_web-0.4.0
connectivity_macos-0.2.0
flutter_plugin_android_lifecycle-2.0.2
image_picker-0.8.2
image_picker_for_web-2.1.2
just_audio-0.9.5
just_audio_web-0.4.1
path_provider-2.0.2
path_provider_linux-2.0.0
path_provider_macos-2.0.0
path_provider_windows-2.0.1
permission_handler-8.1.4+2
qr_code_scanner-0.5.2
shared_preferences-2.0.6
shared_preferences_linux-2.0.0
shared_preferences_macos-2.0.0
shared_preferences_web-2.0.0
shared_preferences_windows-2.0.0
sqflite-2.0.0+4
vibration-1.7.4-nullsafety.0
vibration_web-1.6.3-nullsafety.0
wakelock-0.5.3+3
wakelock_macos-0.1.0+2
wakelock_web-0.2.0+2
webview_flutter-2.0.10

**Comment by maheshmnj** [comment]
@AmarIdeaUsher could you please share the complete output of 

```
flutter --no-color build apk -v
```  

The output will be quite long so either share it in a text file or put it inside the expandable

```
<details>
<summary>flutter doctor -v</summary>

/// your logs here

</details>
```
