### ISSUE TITLE
Assert with RenderObject deactivate within Table widget

### ISSUE THREAD

**Issue by kevmoo** [flutter/flutter#91068]
Repro steps

- This repo at this branch: https://github.com/kevmoo/vote.dart/tree/flutter_i91068
- Run the `vote_demo` app using desktop
- add/remove candidates

@jacob314 and I noticed that this happens within the `_TableElement` 

```
[✓] Flutter (Channel master, 2.6.0-12.0.pre.160, on macOS 11.6 20G165 darwin-x64, locale en-US)
```

```
======== Exception caught by widgets library =======================================================
The following assertion was thrown building Container(Alignment.center, padding: EdgeInsets.all(9.0)):
A RenderObject was still attached when attempting to deactivate its RenderObjectElement: _RenderColoredBox#faedf relayoutBoundary=up3
'package:flutter/src/widgets/framework.dart':
Failed assertion: line 5725 pos 7: '!renderObject.attached'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      RenderObjectElement.deactivate (package:flutter/src/widgets/framework.dart:5725:7)
#3      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1901:13)
#4      _InactiveElements.add (package:flutter/src/widgets/framework.dart:1915:7)
#5      Element.deactivateChild (package:flutter/src/widgets/framework.dart:3667:30)
#6      Element.updateChild (package:flutter/src/widgets/framework.dart:3378:9)
#7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4611:16)
#8      Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#9      StatelessElement.update (package:flutter/src/widgets/framework.dart:4667:5)
#10     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4611:16)
#12     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#13     StatelessElement.update (package:flutter/src/widgets/framework.dart:4667:5)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4611:16)
#16     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#17     StatelessElement.update (package:flutter/src/widgets/framework.dart:4667:5)
#18     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#19     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5701:32)
#20     _TableElement.update (package:flutter/src/widgets/table.dart:372:19)
#21     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
```

https://user-images.githubusercontent.com/17034/135557412-5524b101-caa1-438b-93b9-955b971e2546.mov

**Comment by kevmoo** [comment]
CC @dnfield – happy to help you reproduce

**Comment by dnfield** [comment]
I think this might just be a bug in Table elements. It looks like @goderbauer might have been the last person to touch code in there - but it looks like when deactivating some child(ren) of the table, we're deactivating an element that still has an attached render object.

**Comment by xu-baolin** [comment]
@kevmoo hi, I can't reproduce it with the demo you provided now, does this problem still exist? If there is, can you provide the minimal demo?

**Comment by kevmoo** [comment]
We can close this out. Will reopen if I can find it!
