### ISSUE TITLE
[tool_crash] ProcessException: The directory name is invalid. Command: C:\Users\nicho\flutter\bin\cache\dart-sdk\bin\pub.BAT, OS error code: 267

### ISSUE THREAD

**Issue by Strangework** [flutter/flutter#91063]
## Command
```
flutter doctor --verbose
```

## Steps to Reproduce
1. Unzip the latest Windows download (flutter_windows_2.5.1-stable.zip) into C:\Users\<USER>\
2. Append C:\Users\USER\flutter\bin to path
3. Run `flutter doctor --verbose`

## Logs
ProcessException: The directory name is invalid.
 Command: C:\Users\nicho\flutter\bin\cache\dart-sdk\bin\pub.BAT, OS error code: 267
```
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:390:33)
#1      Process.start (dart:io-patch/process_patch.dart:36:20)
#2      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:44:22)
#3      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:691:24)
#4      _run (package:flutter_tools/src/base/error_handling_io.dart:567:20)
#5      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:690:12)
#6      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:425:28)
#7      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:444:35)
#8      _DefaultPub.batch (package:flutter_tools/src/dart/pub.dart:308:34)
<asynchronous suspension>
#9      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:248:7)
<asynchronous suspension>
#10     PubDependencies.update (package:flutter_tools/src/flutter_cache.dart:119:5)
<asynchronous suspension>
#11     Cache.updateAll (package:flutter_tools/src/cache.dart:557:9)
<asynchronous suspension>
#12     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1227:7)
<asynchronous suspension>
#13     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
```
```
[✓] Flutter (Channel stable, 2.5.1, on Microsoft Windows [Version 10.0.19042.1237], locale en-US)
    • Flutter version 2.5.1 at C:\Users\nicho\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (13 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\nicho\AppData\Local\Android\sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] Connected device (1 available)
    • Edge (web) • edge • web-javascript • Microsoft Edge 93.0.961.52

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by maheshmnj** [comment]
Hi @Strangework, Thanks for filing the issue. Could you please clear your console and run the same command and share the entire output?

Thanks
