### ISSUE TITLE
I'm facing google sign in issue in android[Flutter]

### ISSUE THREAD

**Issue by darshitpolaris** [flutter/flutter#91084]
E/flutter ( 3299): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null, null)
E/flutter ( 3299): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter ( 3299): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter ( 3299): <asynchronous suspension>
E/flutter ( 3299): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:356:43)
E/flutter ( 3299): <asynchronous suspension>
E/flutter ( 3299): #3      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:235:30)
E/flutter ( 3299): <asynchronous suspension>
E/flutter ( 3299): #4      GoogleSignIn.signIn.isCanceled (package:google_sign_in/google_sign_in.dart)
E/flutter ( 3299): <asynchronous suspension>
E/flutter ( 3299): 

I followed all the steps which are suggested by the google_sign_in package team and also add the SHA1 key in the firebase project then also I get this issue.

**Comment by darshankawar** [comment]
@darshitpolaris 
Check [this](https://github.com/flutter/flutter/issues/33393) open similar issue and see if any of the underlying comments from it helps.
