### ISSUE TITLE
flutter engine (sky_shell) has some flaky failures running the Dart co19 test suite

### ISSUE THREAD

**Issue by a-siva** [flutter/flutter#9109]
## Steps to Reproduce
<path>/engine/src/out/host_debug_unopt/sky_shell --non-interactive --enable_asserts --enable_type_checks --ignore-unrecognized-flags --packages=<dart_workspace_path>/sdk/.packages <dart-workspace-path>/sdk/tests/co19/src/LibTest/isolate/ReceivePort/sendPort_A01_t01.dart

<path>/engine/src/out/host_debug_unopt/sky_shell --non-interactive --enable_asserts --enable_type_checks --ignore-unrecognized-flags --packages=<dart_workspace_path>/sdk/.packages <dart-workspace-path>/sdk/tests/co19/LibTest/async/Future/doWhile_A05_t01

<path>/engine/src/out/host_debug_unopt/sky_shell --non-interactive --enable_asserts --enable_type_checks --ignore-unrecognized-flags --packages=<dart_workspace_path>/sdk/.packages <dart-workspace-path>/sdk/tests/co19/LibTest/async/Future/forEach_A04_t02

## Logs
FAILED: none-flutter-checked debug_x64 co19/LibTest/async/Future/doWhile_A05_t01
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stdout:
unittest-suite-wait-for-done

stderr:
[ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
Expect.equals(expected: <3>, actual: <1>) fails.
#0      _fail (/usr/local/google/home/asiva/workspace/dart-ws3/sdk/tests/co19/src/Utils/expect.dart:17:5)
#1      Expect.equals (/usr/local/google/home/asiva/workspace/dart-ws3/sdk/tests/co19/src/Utils/expect_common.dart:27:5)
#2      main.<anonymous closure> (/usr/local/google/home/asiva/workspace/dart-ws3/sdk/tests/co19/src/LibTest/async/Future/doWhile_A05_t01.dart:74:12)
#3      _RootZone.runUnary (dart:async/zone.dart:1404)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:131)
#5      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#6      _Future._propagateToListeners (dart:async/future_impl.dart:667)
#7      _Future._complete (dart:async/future_impl.dart:467)
#8      _Future.timeout.<anonymous closure> (dart:async/future_impl.dart:727)
#9      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#10     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#11     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Command[vm]: DART_CONFIGURATION=DebugX64 /usr/local/google/home/asiva/workspace/flutter-tot/engine/src/out/host_debug_unopt/sky_shell --non-interactive --enable_asserts --enable_type_checks --ignore-unrecognized-flags --packages=/usr/local/google/home/asiva/workspace/dart-ws3/sdk/.packages /usr/local/google/home/asiva/workspace/dart-ws3/sdk/tests/co19/src/LibTest/async/Future/doWhile_A05_t01.dart
Took 0:00:00.048272

Short reproduction command (experimental):
    python tools/test.py -rflutter --checked -t120 co19/LibTest/async/Future/doWhile_A05_t01

**Comment by zoechi** [comment]
Is this issue still relevant?
