### ISSUE TITLE
Espresso plugin: Example tests fail with Flutter testing APIs not registered with Dart isolate

### ISSUE THREAD

**Issue by prolificcoder** [flutter/flutter#91106]
## Steps to Reproduce

1. git clone git@github.com:flutter/plugins.git
2. cd packages/espresso/example
3. flutter build apk --debug
4. cd android (this step isn't mentioned in README.md)
5. ./gradlew app:connectedAndroidTest
6. We can see the emulator bootup but tests won't run

## Logs

<details>
<summary>Logs</summary>

All the tests failed with the stacktrace like below. 
```
java.lang.RuntimeException: java.util.concurrent.ExecutionException: androidx.test.espresso.flutter.internal.protocol.impl.FlutterProtocolException: Flutter testing APIs not registered with Dart isolate isolates/2544564990536619.
at androidx.test.espresso.flutter.EspressoFlutter$WidgetInteraction$ExceptionPropagator.<init>(EspressoFlutter.java:179)
at androidx.test.espresso.flutter.EspressoFlutter$WidgetInteraction.propagateException(EspressoFlutter.java:164)
at androidx.test.espresso.flutter.EspressoFlutter$WidgetInteraction.performInternal(EspressoFlutter.java:152)
at androidx.test.espresso.flutter.EspressoFlutter$WidgetInteraction.perform(EspressoFlutter.java:107)
at com.example.espresso_example.MainActivityTest.performClick(MainActivityTest.java:44)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:104)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:388)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2248)
Caused by: java.util.concurrent.ExecutionException: androidx.test.espresso.flutter.internal.protocol.impl.FlutterProtocolException: Flutter testing APIs not registered with Dart isolate isolates/2544564990536619.
at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:552)
at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:533)
at com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:84)
at androidx.test.espresso.flutter.action.ActionUtil$FutureIdlingResource$1.call(ActionUtil.java:88)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:920)
Caused by: androidx.test.espresso.flutter.internal.protocol.impl.FlutterProtocolException: Flutter testing APIs not registered with Dart isolate isolates/2544564990536619.
at androidx.test.espresso.flutter.internal.protocol.impl.DartVmService$IsDartVmServiceReady.waitForTestingApiRegistered(DartVmService.java:346)
at androidx.test.espresso.flutter.internal.protocol.impl.DartVmService$IsDartVmServiceReady.run(DartVmService.java:312)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)

```
## Flutter doctor
```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[!] Android Studio (version 2020.3)
    ✗ Unable to find bundled Java version.
[✓] Connected device (2 available)
```

</details>

**Comment by prolificcoder** [comment]
Note that I updated to latest stable flutter 
```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.2, on macOS 11.4 20F71 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.57.1)
[✓] Connected device (2 available)

• No issues found!
``` 
but the same issue still persists

**Comment by prolificcoder** [comment]
WIthout the build step the tests executed fine from the command line. 

I was on flutter 2.2.1 

BTW I got the instruction from here: https://github.com/flutter/plugins/blob/master/packages/espresso/example/README.md?plain=1#L12
![image](https://user-images.githubusercontent.com/149176/136266643-696c5b19-64b3-47bf-a56a-18eafa12628f.png)

I think it should be removed.
