### ISSUE TITLE
flutter engine (sky_shell) fails a number of Dart corelib tests

### ISSUE THREAD

**Issue by a-siva** [flutter/flutter#9111]
## Steps to Reproduce
```
tools/test.py -j4 --checked -rflutter --flutter=<flutter_path>/engine/src/out/host_debug_unopt/sky_shell corelib
```

## Logs
=== Failure summary:

```
FAILED: none-flutter-checked debug_x64 corelib/uri_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stderr:
[ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
NoSuchMethodError: Class '_SimpleUri' has no instance method 'isScheme'.
Receiver: Instance of '_SimpleUri'
Tried calling: isScheme("http")
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      testUri (/usr/local/google/home/asiva/workspace/dart-ws3/sdk/tests/corelib/uri_test.dart:36:21)
#3      main (/usr/local/google/home/asiva/workspace/dart-ws3/sdk/tests/corelib/uri_test.dart:794:3)
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


Command[vm]: DART_CONFIGURATION=DebugX64 /usr/local/google/home/asiva/workspace/flutter-tot/engine/src/out/host_debug_unopt/sky_shell --non-interactive --enable_asserts --enable_type_checks --ignore-unrecognized-flags --packages=/usr/local/google/home/asiva/workspace/dart-ws3/sdk/.packages /usr/local/google/home/asiva/workspace/dart-ws3/sdk/tests/corelib/uri_test.dart
Took 0:00:00.133441

Short reproduction command (experimental):
    python tools/test.py -rflutter --checked -t120 corelib/uri_test


FAILED: none-flutter-checked debug_x64 corelib/string_from_environment_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stderr:
[ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
Expect.equals(expected: <a>, actual: <null>) fails.
#0      Expect._fail (package:expect/expect.dart:435:5)
#1      Expect.equals (package:expect/expect.dart:102:5)
#2      main (/usr/local/google/home/asiva/workspace/dart-ws3/sdk/tests/corelib/string_from_environment_test.dart:9:10)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


Command[vm]: DART_CONFIGURATION=DebugX64 /usr/local/google/home/asiva/workspace/flutter-tot/engine/src/out/host_debug_unopt/sky_shell --non-interactive --enable_asserts --enable_type_checks -Da=a -Db=bb -Dc=ccc -Dd= --ignore-unrecognized-flags --packages=/usr/local/google/home/asiva/workspace/dart-ws3/sdk/.packages /usr/local/google/home/asiva/workspace/dart-ws3/sdk/tests/corelib/string_from_environment_test.dart
Took 0:00:00.035935

Short reproduction command (experimental):
    python tools/test.py -rflutter --checked -t120 corelib/string_from_environment_test


FAILED: none-flutter-checked debug_x64 corelib/uri_example_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stderr:
[ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
NoSuchMethodError: Class '_SimpleUri' has no instance method 'isScheme'.
Receiver: Instance of '_SimpleUri'
Tried calling: isScheme("HTTP")
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      main (/usr/local/google/home/asiva/workspace/dart-ws3/sdk/tests/corelib/uri_example_test.dart:41:21)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


Command[vm]: DART_CONFIGURATION=DebugX64 /usr/local/google/home/asiva/workspace/flutter-tot/engine/src/out/host_debug_unopt/sky_shell --non-interactive --enable_asserts --enable_type_checks --ignore-unrecognized-flags --packages=/usr/local/google/home/asiva/workspace/dart-ws3/sdk/.packages /usr/local/google/home/asiva/workspace/dart-ws3/sdk/tests/corelib/uri_example_test.dart
Took 0:00:00.071019

Short reproduction command (experimental):
    python tools/test.py -rflutter --checked -t120 corelib/uri_example_test


FAILED: none-flutter-checked debug_x64 corelib/bool_from_environment_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stderr:
[ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
Expect.isTrue(false) fails.
#0      Expect._fail (package:expect/expect.dart:435:5)
#1      Expect.isTrue (package:expect/expect.dart:111:5)
#2      main (/usr/local/google/home/asiva/workspace/dart-ws3/sdk/tests/corelib/bool_from_environment_test.dart:9:10)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


Command[vm]: DART_CONFIGURATION=DebugX64 /usr/local/google/home/asiva/workspace/flutter-tot/engine/src/out/host_debug_unopt/sky_shell --non-interactive --enable_asserts --enable_type_checks -Da=true -Db=false -Dc=NOTBOOL -Dd=True --ignore-unrecognized-flags --packages=/usr/local/google/home/asiva/workspace/dart-ws3/sdk/.packages /usr/local/google/home/asiva/workspace/dart-ws3/sdk/tests/corelib/bool_from_environment_test.dart
Took 0:00:00.037582

Short reproduction command (experimental):
    python tools/test.py -rflutter --checked -t120 corelib/bool_from_environment_test


FAILED: none-flutter-checked debug_x64 corelib/int_from_environment_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stderr:
[ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
Expect.equals(expected: <1>, actual: <null>) fails.
#0      Expect._fail (package:expect/expect.dart:435:5)
#1      Expect.equals (package:expect/expect.dart:102:5)
#2      main (/usr/local/google/home/asiva/workspace/dart-ws3/sdk/tests/corelib/int_from_environment_test.dart:9:10)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


Command[vm]: DART_CONFIGURATION=DebugX64 /usr/local/google/home/asiva/workspace/flutter-tot/engine/src/out/host_debug_unopt/sky_shell --non-interactive --enable_asserts --enable_type_checks -Da=1 -Db=-12 -Dc=0x123 -Dd=-0x1234 -De=+0x112296 -Df=99999999999999999999 --ignore-unrecognized-flags --packages=/usr/local/google/home/asiva/workspace/dart-ws3/sdk/.packages /usr/local/google/home/asiva/workspace/dart-ws3/sdk/tests/corelib/int_from_environment_test.dart
Took 0:00:00.037548

Short reproduction command (experimental):
    python tools/test.py -rflutter --checked -t120 corelib/int_from_environment_test


FAILED: none-flutter-checked debug_x64 corelib/data_uri_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stdout:
Diagnostic server listening on http://127.0.0.1:39300/


stderr:
[ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
Expect.equals(expected: <data:;base64,AA/+>, actual: <data:;base64,AA_->) fails.
#0      Expect._fail (package:expect/expect.dart:435:5)
#1      Expect.equals (package:expect/expect.dart:102:5)
#2      testNormalization (/usr/local/google/home/asiva/workspace/dart-ws3/sdk/tests/corelib/data_uri_test.dart:167:10)
#3      main (/usr/local/google/home/asiva/workspace/dart-ws3/sdk/tests/corelib/data_uri_test.dart:32:3)
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


Command[vm]: DART_CONFIGURATION=DebugX64 /usr/local/google/home/asiva/workspace/flutter-tot/engine/src/out/host_debug_unopt/sky_shell --non-interactive --enable_asserts --enable_type_checks --ignore-unrecognized-flags --packages=/usr/local/google/home/asiva/workspace/dart-ws3/sdk/.packages /usr/local/google/home/asiva/workspace/dart-ws3/sdk/tests/corelib/data_uri_test.dart
Took 0:00:00.096949

Short reproduction command (experimental):
    python tools/test.py -rflutter --checked -t120 corelib/data_uri_test


FAILED: none-flutter-checked debug_x64 corelib/from_environment_const_type_test/none
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stderr:
[ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
Expect.equals(expected: <false>, actual: <true>) fails.
#0      Expect._fail (package:expect/expect.dart:435:5)
#1      Expect.equals (package:expect/expect.dart:102:5)
#2      main (/usr/local/google/home/asiva/workspace/dart-ws3/sdk/out/DebugX64/generated_tests/corelib/from_environment_const_type_test_none.dart:39:10)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


Command[vm]: DART_CONFIGURATION=DebugX64 /usr/local/google/home/asiva/workspace/flutter-tot/engine/src/out/host_debug_unopt/sky_shell --non-interactive --enable_asserts --enable_type_checks -Da=true -Db=false -Dc=3 -Dd=STRING --ignore-unrecognized-flags --packages=/usr/local/google/home/asiva/workspace/dart-ws3/sdk/.packages /usr/local/google/home/asiva/workspace/dart-ws3/sdk/out/DebugX64/generated_tests/corelib/from_environment_const_type_test_none.dart
Took 0:00:00.035394

Short reproduction command (experimental):
    python tools/test.py -rflutter --checked -t120 corelib/from_environment_const_type_test/none


FAILED: none-flutter-checked debug_x64 corelib/from_environment_const_type_test/01
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stderr:
[ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
Expect.equals(expected: <false>, actual: <true>) fails.
#0      Expect._fail (package:expect/expect.dart:435:5)
#1      Expect.equals (package:expect/expect.dart:102:5)
#2      main (/usr/local/google/home/asiva/workspace/dart-ws3/sdk/out/DebugX64/generated_tests/corelib/from_environment_const_type_test_01.dart:39:10)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


Command[vm]: DART_CONFIGURATION=DebugX64 /usr/local/google/home/asiva/workspace/flutter-tot/engine/src/out/host_debug_unopt/sky_shell --non-interactive --enable_asserts --enable_type_checks -Da=true -Db=false -Dc=3 -Dd=STRING --ignore-unrecognized-flags --packages=/usr/local/google/home/asiva/workspace/dart-ws3/sdk/.packages /usr/local/google/home/asiva/workspace/dart-ws3/sdk/out/DebugX64/generated_tests/corelib/from_environment_const_type_test_01.dart
Took 0:00:00.036582

Short reproduction command (experimental):
    python tools/test.py -rflutter --checked -t120 corelib/from_environment_const_type_test/01


FAILED: none-flutter-checked debug_x64 corelib/from_environment_const_type_test/05
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stderr:
[ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
Expect.equals(expected: <false>, actual: <true>) fails.
#0      Expect._fail (package:expect/expect.dart:435:5)
#1      Expect.equals (package:expect/expect.dart:102:5)
#2      main (/usr/local/google/home/asiva/workspace/dart-ws3/sdk/out/DebugX64/generated_tests/corelib/from_environment_const_type_test_05.dart:39:10)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


Command[vm]: DART_CONFIGURATION=DebugX64 /usr/local/google/home/asiva/workspace/flutter-tot/engine/src/out/host_debug_unopt/sky_shell --non-interactive --enable_asserts --enable_type_checks -Da=true -Db=false -Dc=3 -Dd=STRING --ignore-unrecognized-flags --packages=/usr/local/google/home/asiva/workspace/dart-ws3/sdk/.packages /usr/local/google/home/asiva/workspace/dart-ws3/sdk/out/DebugX64/generated_tests/corelib/from_environment_const_type_test_05.dart
Took 0:00:00.036808

Short reproduction command (experimental):
    python tools/test.py -rflutter --checked -t120 corelib/from_environment_const_type_test/05


FAILED: none-flutter-checked debug_x64 corelib/from_environment_const_type_test/09
Expected: Pass 
Actual: MissingCompileTimeError
Compile-time error expected.
CommandOutput[vm]:

stderr:
[ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
Expect.equals(expected: <false>, actual: <true>) fails.
#0      Expect._fail (package:expect/expect.dart:435:5)
#1      Expect.equals (package:expect/expect.dart:102:5)
#2      main (/usr/local/google/home/asiva/workspace/dart-ws3/sdk/out/DebugX64/generated_tests/corelib/from_environment_const_type_test_09.dart:39:10)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


Command[vm]: DART_CONFIGURATION=DebugX64 /usr/local/google/home/asiva/workspace/flutter-tot/engine/src/out/host_debug_unopt/sky_shell --non-interactive --enable_asserts --enable_type_checks -Da=true -Db=false -Dc=3 -Dd=STRING --ignore-unrecognized-flags --packages=/usr/local/google/home/asiva/workspace/dart-ws3/sdk/.packages /usr/local/google/home/asiva/workspace/dart-ws3/sdk/out/DebugX64/generated_tests/corelib/from_environment_const_type_test_09.dart
Took 0:00:00.035824

Short reproduction command (experimental):
    python tools/test.py -rflutter --checked -t120 corelib/from_environment_const_type_test/09


FAILED: none-flutter-checked debug_x64 corelib/from_environment_const_type_test/10
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stderr:
[ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
Expect.equals(expected: <false>, actual: <true>) fails.
#0      Expect._fail (package:expect/expect.dart:435:5)
#1      Expect.equals (package:expect/expect.dart:102:5)
#2      main (/usr/local/google/home/asiva/workspace/dart-ws3/sdk/out/DebugX64/generated_tests/corelib/from_environment_const_type_test_10.dart:39:10)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


Command[vm]: DART_CONFIGURATION=DebugX64 /usr/local/google/home/asiva/workspace/flutter-tot/engine/src/out/host_debug_unopt/sky_shell --non-interactive --enable_asserts --enable_type_checks -Da=true -Db=false -Dc=3 -Dd=STRING --ignore-unrecognized-flags --packages=/usr/local/google/home/asiva/workspace/dart-ws3/sdk/.packages /usr/local/google/home/asiva/workspace/dart-ws3/sdk/out/DebugX64/generated_tests/corelib/from_environment_const_type_test_10.dart
Took 0:00:00.035900

Short reproduction command (experimental):
    python tools/test.py -rflutter --checked -t120 corelib/from_environment_const_type_test/10


FAILED: none-flutter-checked debug_x64 corelib/from_environment_const_type_test/12
Expected: Pass 
Actual: MissingCompileTimeError
Compile-time error expected.
CommandOutput[vm]:

stderr:
[ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
Expect.equals(expected: <false>, actual: <true>) fails.
#0      Expect._fail (package:expect/expect.dart:435:5)
#1      Expect.equals (package:expect/expect.dart:102:5)
#2      main (/usr/local/google/home/asiva/workspace/dart-ws3/sdk/out/DebugX64/generated_tests/corelib/from_environment_const_type_test_12.dart:39:10)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


Command[vm]: DART_CONFIGURATION=DebugX64 /usr/local/google/home/asiva/workspace/flutter-tot/engine/src/out/host_debug_unopt/sky_shell --non-interactive --enable_asserts --enable_type_checks -Da=true -Db=false -Dc=3 -Dd=STRING --ignore-unrecognized-flags --packages=/usr/local/google/home/asiva/workspace/dart-ws3/sdk/.packages /usr/local/google/home/asiva/workspace/dart-ws3/sdk/out/DebugX64/generated_tests/corelib/from_environment_const_type_test_12.dart
Took 0:00:00.035470

Short reproduction command (experimental):
    python tools/test.py -rflutter --checked -t120 corelib/from_environment_const_type_test/12


FAILED: none-flutter-checked debug_x64 corelib/from_environment_const_type_test/13
Expected: Pass 
Actual: MissingCompileTimeError
Compile-time error expected.
CommandOutput[vm]:

stderr:
[ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
Expect.equals(expected: <false>, actual: <true>) fails.
#0      Expect._fail (package:expect/expect.dart:435:5)
#1      Expect.equals (package:expect/expect.dart:102:5)
#2      main (/usr/local/google/home/asiva/workspace/dart-ws3/sdk/out/DebugX64/generated_tests/corelib/from_environment_const_type_test_13.dart:39:10)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


Command[vm]: DART_CONFIGURATION=DebugX64 /usr/local/google/home/asiva/workspace/flutter-tot/engine/src/out/host_debug_unopt/sky_shell --non-interactive --enable_asserts --enable_type_checks -Da=true -Db=false -Dc=3 -Dd=STRING --ignore-unrecognized-flags --packages=/usr/local/google/home/asiva/workspace/dart-ws3/sdk/.packages /usr/local/google/home/asiva/workspace/dart-ws3/sdk/out/DebugX64/generated_tests/corelib/from_environment_const_type_test_13.dart
Took 0:00:00.036080

Short reproduction command (experimental):
    python tools/test.py -rflutter --checked -t120 corelib/from_environment_const_type_test/13


FAILED: none-flutter-checked debug_x64 corelib/from_environment_const_type_test/11
Expected: Pass 
Actual: MissingCompileTimeError
Compile-time error expected.
CommandOutput[vm]:

stderr:
[ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
Expect.equals(expected: <false>, actual: <true>) fails.
#0      Expect._fail (package:expect/expect.dart:435:5)
#1      Expect.equals (package:expect/expect.dart:102:5)
#2      main (/usr/local/google/home/asiva/workspace/dart-ws3/sdk/out/DebugX64/generated_tests/corelib/from_environment_const_type_test_11.dart:39:10)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


Command[vm]: DART_CONFIGURATION=DebugX64 /usr/local/google/home/asiva/workspace/flutter-tot/engine/src/out/host_debug_unopt/sky_shell --non-interactive --enable_asserts --enable_type_checks -Da=true -Db=false -Dc=3 -Dd=STRING --ignore-unrecognized-flags --packages=/usr/local/google/home/asiva/workspace/dart-ws3/sdk/.packages /usr/local/google/home/asiva/workspace/dart-ws3/sdk/out/DebugX64/generated_tests/corelib/from_environment_const_type_test_11.dart
Took 0:00:00.047758

Short reproduction command (experimental):
    python tools/test.py -rflutter --checked -t120 corelib/from_environment_const_type_test/11


FAILED: none-flutter-checked debug_x64 corelib/from_environment_const_type_test/14
Expected: Pass 
Actual: MissingCompileTimeError
Compile-time error expected.
CommandOutput[vm]:

stderr:
[ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
Expect.equals(expected: <false>, actual: <true>) fails.
#0      Expect._fail (package:expect/expect.dart:435:5)
#1      Expect.equals (package:expect/expect.dart:102:5)
#2      main (/usr/local/google/home/asiva/workspace/dart-ws3/sdk/out/DebugX64/generated_tests/corelib/from_environment_const_type_test_14.dart:39:10)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


Command[vm]: DART_CONFIGURATION=DebugX64 /usr/local/google/home/asiva/workspace/flutter-tot/engine/src/out/host_debug_unopt/sky_shell --non-interactive --enable_asserts --enable_type_checks -Da=true -Db=false -Dc=3 -Dd=STRING --ignore-unrecognized-flags --packages=/usr/local/google/home/asiva/workspace/dart-ws3/sdk/.packages /usr/local/google/home/asiva/workspace/dart-ws3/sdk/out/DebugX64/generated_tests/corelib/from_environment_const_type_test_14.dart
Took 0:00:00.036686

Short reproduction command (experimental):
    python tools/test.py -rflutter --checked -t120 corelib/from_environment_const_type_test/14


FAILED: none-flutter-checked debug_x64 corelib/from_environment_const_type_test/15
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stderr:
[ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
Expect.equals(expected: <false>, actual: <true>) fails.
#0      Expect._fail (package:expect/expect.dart:435:5)
#1      Expect.equals (package:expect/expect.dart:102:5)
#2      main (/usr/local/google/home/asiva/workspace/dart-ws3/sdk/out/DebugX64/generated_tests/corelib/from_environment_const_type_test_15.dart:39:10)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


Command[vm]: DART_CONFIGURATION=DebugX64 /usr/local/google/home/asiva/workspace/flutter-tot/engine/src/out/host_debug_unopt/sky_shell --non-interactive --enable_asserts --enable_type_checks -Da=true -Db=false -Dc=3 -Dd=STRING --ignore-unrecognized-flags --packages=/usr/local/google/home/asiva/workspace/dart-ws3/sdk/.packages /usr/local/google/home/asiva/workspace/dart-ws3/sdk/out/DebugX64/generated_tests/corelib/from_environment_const_type_test_15.dart
Took 0:00:00.041176

Short reproduction command (experimental):
    python tools/test.py -rflutter --checked -t120 corelib/from_environment_const_type_test/15


FAILED: none-flutter-checked debug_x64 corelib/from_environment_const_type_test/16
Expected: Pass 
Actual: MissingCompileTimeError
Compile-time error expected.
CommandOutput[vm]:

stderr:
[ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
Expect.equals(expected: <false>, actual: <true>) fails.
#0      Expect._fail (package:expect/expect.dart:435:5)
#1      Expect.equals (package:expect/expect.dart:102:5)
#2      main (/usr/local/google/home/asiva/workspace/dart-ws3/sdk/out/DebugX64/generated_tests/corelib/from_environment_const_type_test_16.dart:39:10)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


Command[vm]: DART_CONFIGURATION=DebugX64 /usr/local/google/home/asiva/workspace/flutter-tot/engine/src/out/host_debug_unopt/sky_shell --non-interactive --enable_asserts --enable_type_checks -Da=true -Db=false -Dc=3 -Dd=STRING --ignore-unrecognized-flags --packages=/usr/local/google/home/asiva/workspace/dart-ws3/sdk/.packages /usr/local/google/home/asiva/workspace/dart-ws3/sdk/out/DebugX64/generated_tests/corelib/from_environment_const_type_test_16.dart
Took 0:00:00.036508

Short reproduction command (experimental):
    python tools/test.py -rflutter --checked -t120 corelib/from_environment_const_type_test/16


FAILED: none-flutter-checked debug_x64 corelib/main_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stderr:
[ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
NoSuchMethodError: The getter 'length' was called on null.
Receiver: null
Tried calling: length
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      main (/usr/local/google/home/asiva/workspace/dart-ws3/sdk/tests/corelib/main_test.dart:9:25)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


Command[vm]: DART_CONFIGURATION=DebugX64 /usr/local/google/home/asiva/workspace/flutter-tot/engine/src/out/host_debug_unopt/sky_shell --non-interactive --enable_asserts --enable_type_checks --ignore-unrecognized-flags --packages=/usr/local/google/home/asiva/workspace/dart-ws3/sdk/.packages /usr/local/google/home/asiva/workspace/dart-ws3/sdk/tests/corelib/main_test.dart
Took 0:00:00.046345

Short reproduction command (experimental):
    python tools/test.py -rflutter --checked -t120 corelib/main_test


FAILED: none-flutter-checked debug_x64 corelib/string_from_environment2_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stderr:
[ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
Expect.equals(expected: <ccc>, actual: <null>) fails.
#0      Expect._fail (package:expect/expect.dart:435:5)
#1      Expect.equals (package:expect/expect.dart:102:5)
#2      main (/usr/local/google/home/asiva/workspace/dart-ws3/sdk/tests/corelib/string_from_environment2_test.dart:9:10)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


Command[vm]: DART_CONFIGURATION=DebugX64 /usr/local/google/home/asiva/workspace/flutter-tot/engine/src/out/host_debug_unopt/sky_shell --non-interactive --enable_asserts --enable_type_checks -Da=a -Da=bb -Db=bb -Dc=ccc -Da=ccc -Db=ccc --ignore-unrecognized-flags --packages=/usr/local/google/home/asiva/workspace/dart-ws3/sdk/.packages /usr/local/google/home/asiva/workspace/dart-ws3/sdk/tests/corelib/string_from_environment2_test.dart
Took 0:00:00.036444

Short reproduction command (experimental):
    python tools/test.py -rflutter --checked -t120 corelib/string_from_environment2_test



===
=== 19 tests failed
===
```

**Comment by zoechi** [comment]
Is this issue still relevant?

**Comment by a-siva** [comment]
These issues were filed when we tried running the flutter engine through the Dart test suite. This is probably a stale issue and can be reopened if we find this to be an issue with the latest setup.
