### ISSUE TITLE
flutter engine (sky_shell) fails some tests in the Dart isolate test suite

### ISSUE THREAD

**Issue by a-siva** [flutter/flutter#9114]
## Steps to Reproduce
```
tools/test.py -j4 --checked -rflutter --flutter=<path_to_flutter>/engine/src/out/host_debug_unopt/sky_shell isolate
```

## Logs
=== Failure summary:

```
FAILED: none-flutter-checked debug_x64 isolate/isolate_import_test/01
Expected: Pass 
Actual: Timeout
CommandOutput[vm]:
diagnostics: Process list including children: [5150]
    Trying to capture stack trace for pid 5150
    PID 5150 - process
    TID 5150:
    #0  0x00007fe96392e404 pthread_cond_wait@@GLIBC_2.3.2
    #1  0x0000000000e1d7a5
    #2  0x0000000000e1f3de
    #3  0x0000000000e1f046
    #4  0x0000000000d87bda
    #5  0x0000000000d7ac6f
    #6  0x0000000000db1ba4
    #7  0x0000000000d79df6
    #8  0x0000000000ccd345
    #9  0x0000000000ccc5e0
    #10 0x00007fe961201f45 __libc_start_main
    #11 0x0000000000ccc029
    TID 5152:
    #0  0x00007fe96392e404 pthread_cond_wait@@GLIBC_2.3.2
    #1  0x0000000000e1d7a5
    #2  0x0000000000e1f3de
    #3  0x0000000000e1f046
    #4  0x0000000000d87bda
    #5  0x0000000000d7ac6f
    #6  0x0000000000db1ba4
    #7  0x0000000000d79df6
    #8  0x0000000000e62b39
    #9  0x0000000000e63453
    #10 0x0000000000e48225
    #11 0x00007fe96392a184 start_thread
    #12 0x00007fe9612ddbed __clone
    TID 5153:
    #0  0x00007fe96392e404 pthread_cond_wait@@GLIBC_2.3.2
    #1  0x0000000000e1d7a5
    #2  0x0000000000e1f3de
    #3  0x0000000000e1f046
    #4  0x0000000000d87bda
    #5  0x0000000000d7ac6f
    #6  0x0000000000db1ba4
    #7  0x0000000000d79df6
    #8  0x0000000000e62b39
    #9  0x0000000000e63453
    #10 0x0000000000e48225
    #11 0x00007fe96392a184 start_thread
    #12 0x00007fe9612ddbed __clone
    TID 5154:
    #0  0x00007fe96392e404 pthread_cond_wait@@GLIBC_2.3.2
    #1  0x0000000000e1d7a5
    #2  0x0000000000e1f3de
    #3  0x0000000000e1f046
    #4  0x0000000000d87bda
    #5  0x0000000000d7ac6f
    #6  0x0000000000db1ba4
    #7  0x0000000000d79df6
    #8  0x0000000000e62b39
    #9  0x0000000000e63453
    #10 0x0000000000e48225
    #11 0x00007fe96392a184 start_thread
    #12 0x00007fe9612ddbed __clone
    TID 5155:
    #0  0x00007fe9612de283 epoll_wait
    #1  0x000000000225f965
    #2  0x000000000227a96b
    #3  0x00007fe96392a184 start_thread
    #4  0x00007fe9612ddbed __clone
    
    

stdout:
unittest-suite-wait-for-done
Diagnostic server listening on http://127.0.0.1:36959/
Observatory listening on http://127.0.0.1:39252/


stderr:
[ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
NoSuchMethodError: No top-level getter 'Isolate' declared.
Receiver: top-level
Tried calling: Isolate
#0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:188)
#1      main (/usr/local/google/home/asiva/workspace/dart-ws3/sdk/out/DebugX64/generated_tests/isolate/isolate_import_test_01.dart:17:3)
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


Command[vm]: DART_CONFIGURATION=DebugX64 /usr/local/google/home/asiva/workspace/flutter-tot/engine/src/out/host_debug_unopt/sky_shell --non-interactive --enable_asserts --enable_type_checks --ignore-unrecognized-flags --packages=/usr/local/google/home/asiva/workspace/dart-ws3/sdk/.packages /usr/local/google/home/asiva/workspace/dart-ws3/sdk/out/DebugX64/generated_tests/isolate/isolate_import_test_01.dart
Took 0:02:00.065232

Short reproduction command (experimental):
    python tools/test.py -rflutter --checked -t120 isolate/isolate_import_test/01


FAILED: none-flutter-checked debug_x64 isolate/simple_message_test/01
Expected: Pass 
Actual: Timeout
CommandOutput[vm]:
diagnostics: Process list including children: [5372]
    Trying to capture stack trace for pid 5372
    PID 5372 - process
    TID 5372:
    #0  0x00007f846f3d5404 pthread_cond_wait@@GLIBC_2.3.2
    #1  0x0000000000e1d7a5
    #2  0x0000000000e1f3de
    #3  0x0000000000e1f046
    #4  0x0000000000d87bda
    #5  0x0000000000d7ac6f
    #6  0x0000000000db1ba4
    #7  0x0000000000d79df6
    #8  0x0000000000ccd345
    #9  0x0000000000ccc5e0
    #10 0x00007f846cca8f45 __libc_start_main
    #11 0x0000000000ccc029
    TID 5373:
    #0  0x00007f846f3d5404 pthread_cond_wait@@GLIBC_2.3.2
    #1  0x0000000000e1d7a5
    #2  0x0000000000e1f3de
    #3  0x0000000000e1f046
    #4  0x0000000000d87bda
    #5  0x0000000000d7ac6f
    #6  0x0000000000db1ba4
    #7  0x0000000000d79df6
    #8  0x0000000000e62b39
    #9  0x0000000000e63453
    #10 0x0000000000e48225
    #11 0x00007f846f3d1184 start_thread
    #12 0x00007f846cd84bed __clone
    TID 5374:
    #0  0x00007f846f3d5404 pthread_cond_wait@@GLIBC_2.3.2
    #1  0x0000000000e1d7a5
    #2  0x0000000000e1f3de
    #3  0x0000000000e1f046
    #4  0x0000000000d87bda
    #5  0x0000000000d7ac6f
    #6  0x0000000000db1ba4
    #7  0x0000000000d79df6
    #8  0x0000000000e62b39
    #9  0x0000000000e63453
    #10 0x0000000000e48225
    #11 0x00007f846f3d1184 start_thread
    #12 0x00007f846cd84bed __clone
    TID 5375:
    #0  0x00007f846f3d5404 pthread_cond_wait@@GLIBC_2.3.2
    #1  0x0000000000e1d7a5
    #2  0x0000000000e1f3de
    #3  0x0000000000e1f046
    #4  0x0000000000d87bda
    #5  0x0000000000d7ac6f
    #6  0x0000000000db1ba4
    #7  0x0000000000d79df6
    #8  0x0000000000e62b39
    #9  0x0000000000e63453
    #10 0x0000000000e48225
    #11 0x00007f846f3d1184 start_thread
    #12 0x00007f846cd84bed __clone
    TID 5376:
    #0  0x00007f846cd85283 epoll_wait
    #1  0x000000000225f965
    #2  0x000000000227a96b
    #3  0x00007f846f3d1184 start_thread
    #4  0x00007f846cd84bed __clone
    
    

stdout:
unittest-suite-wait-for-done
Diagnostic server listening on http://127.0.0.1:49400/
Observatory listening on http://127.0.0.1:36142/


stderr:
[ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
Expect.equals(expected: <foo>, actual: <bar>) fails.
#0      Expect._fail (package:expect/expect.dart:435:5)
#1      Expect.equals (package:expect/expect.dart:102:5)
#2      main.<anonymous closure> (/usr/local/google/home/asiva/workspace/dart-ws3/sdk/out/DebugX64/generated_tests/isolate/simple_message_test_01.dart:24:12)
#3      _RootZone.runUnary (dart:async/zone.dart:1404)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:131)
#5      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#6      _Future._propagateToListeners (dart:async/future_impl.dart:667)
#7      _Future._complete (dart:async/future_impl.dart:467)
#8      _cancelAndValue (dart:async/stream_pipe.dart:67)
#9      Stream.first.<anonymous closure> (dart:async/stream.dart:1018)
#10     _RootZone.runUnaryGuarded (dart:async/zone.dart:1338)
#11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#12     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#13     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#14     _StreamController._add (dart:async/stream_controller.dart:635)
#15     _StreamController.add (dart:async/stream_controller.dart:581)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


Command[vm]: DART_CONFIGURATION=DebugX64 /usr/local/google/home/asiva/workspace/flutter-tot/engine/src/out/host_debug_unopt/sky_shell --non-interactive --enable_asserts --enable_type_checks --ignore-unrecognized-flags --packages=/usr/local/google/home/asiva/workspace/dart-ws3/sdk/.packages /usr/local/google/home/asiva/workspace/dart-ws3/sdk/out/DebugX64/generated_tests/isolate/simple_message_test_01.dart
Took 0:02:00.053470

Short reproduction command (experimental):
    python tools/test.py -rflutter --checked -t120 isolate/simple_message_test/01


FAILED: none-flutter-checked debug_x64 isolate/issue_21398_parent_isolate2_test/01
Expected: Pass 
Actual: Timeout
CommandOutput[vm]:
diagnostics: Process list including children: [5394]
    Trying to capture stack trace for pid 5394
    PID 5394 - process
    TID 5394:
    #0  0x00007f1ac33e8404 pthread_cond_wait@@GLIBC_2.3.2
    #1  0x0000000000e1d7a5
    #2  0x0000000000e1f3de
    #3  0x0000000000e1f046
    #4  0x0000000000d87bda
    #5  0x0000000000d7ac6f
    #6  0x0000000000db1ba4
    #7  0x0000000000d79df6
    #8  0x0000000000ccd345
    #9  0x0000000000ccc5e0
    #10 0x00007f1ac0cbbf45 __libc_start_main
    #11 0x0000000000ccc029
    TID 5395:
    #0  0x00007f1ac33e8404 pthread_cond_wait@@GLIBC_2.3.2
    #1  0x0000000000e1d7a5
    #2  0x0000000000e1f3de
    #3  0x0000000000e1f046
    #4  0x0000000000d87bda
    #5  0x0000000000d7ac6f
    #6  0x0000000000db1ba4
    #7  0x0000000000d79df6
    #8  0x0000000000e62b39
    #9  0x0000000000e63453
    #10 0x0000000000e48225
    #11 0x00007f1ac33e4184 start_thread
    #12 0x00007f1ac0d97bed __clone
    TID 5396:
    #0  0x00007f1ac33e8404 pthread_cond_wait@@GLIBC_2.3.2
    #1  0x0000000000e1d7a5
    #2  0x0000000000e1f3de
    #3  0x0000000000e1f046
    #4  0x0000000000d87bda
    #5  0x0000000000d7ac6f
    #6  0x0000000000db1ba4
    #7  0x0000000000d79df6
    #8  0x0000000000e62b39
    #9  0x0000000000e63453
    #10 0x0000000000e48225
    #11 0x00007f1ac33e4184 start_thread
    #12 0x00007f1ac0d97bed __clone
    TID 5397:
    #0  0x00007f1ac33e8404 pthread_cond_wait@@GLIBC_2.3.2
    #1  0x0000000000e1d7a5
    #2  0x0000000000e1f3de
    #3  0x0000000000e1f046
    #4  0x0000000000d87bda
    #5  0x0000000000d7ac6f
    #6  0x0000000000db1ba4
    #7  0x0000000000d79df6
    #8  0x0000000000e62b39
    #9  0x0000000000e63453
    #10 0x0000000000e48225
    #11 0x00007f1ac33e4184 start_thread
    #12 0x00007f1ac0d97bed __clone
    TID 5398:
    #0  0x00007f1ac0d98283 epoll_wait
    #1  0x000000000225f965
    #2  0x000000000227a96b
    #3  0x00007f1ac33e4184 start_thread
    #4  0x00007f1ac0d97bed __clone
    
    

stdout:
unittest-suite-wait-for-done
Diagnostic server listening on http://127.0.0.1:54816/
Observatory listening on http://127.0.0.1:58545/


stderr:
[ERROR:../../flutter/runtime/dart_init.cc(129)] Isolate issue_21398_parent_isolate2_test_01.dart$funcChild-587288253 exited with an error
[ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
'/usr/local/google/home/asiva/workspace/dart-ws3/sdk/out/DebugX64/generated_tests/isolate/issue_21398_parent_isolate2_test_01.dart': malformed type: line 25 pos 24: deferred type 'lib.FromChildIsolate' is not yet loaded
    replyPort.send(new lib.FromChildIsolate());
                       ^

#0      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:264)
#1      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


Command[vm]: DART_CONFIGURATION=DebugX64 /usr/local/google/home/asiva/workspace/flutter-tot/engine/src/out/host_debug_unopt/sky_shell --non-interactive --enable_asserts --enable_type_checks --ignore-unrecognized-flags --packages=/usr/local/google/home/asiva/workspace/dart-ws3/sdk/.packages /usr/local/google/home/asiva/workspace/dart-ws3/sdk/out/DebugX64/generated_tests/isolate/issue_21398_parent_isolate2_test_01.dart
Took 0:02:00.051154

Short reproduction command (experimental):
    python tools/test.py -rflutter --checked -t120 isolate/issue_21398_parent_isolate2_test/01



===
=== 3 tests failed
===
```

**Comment by zoechi** [comment]
Is this issue still relevant?

**Comment by a-siva** [comment]
These issues were filed when we tried running the flutter engine through the Dart test suite. This is probably a stale issue and can be reopened if we find this to be an issue with the latest setup.
