### ISSUE TITLE
Failed assertion: line 1702 pos 12: 'center!.parent == this': is not true.

### ISSUE THREAD

**Issue by Semhylmz** [flutter/flutter#91147]
I am trying to get data from firestore using streambuilder. His code was working fine until I updated the packages to the latest version.
My app freezes on splash screen when I add debug flag to streambuilder line. 

### Here is my code:

`body: CustomScrollView(
        slivers: [
          StreamBuilder<QuerySnapshot>(
            stream: FirebaseFirestore.instance
                .collection('posts')
                .limit(10)
                .orderBy('id', descending: true)
                .snapshots(),
            builder: (BuildContext context,
                AsyncSnapshot<QuerySnapshot> dataSnapshot) {
              return !dataSnapshot.hasData
                  ? SliverToBoxAdapter(
                      child: linearProgress(),
                    )
                  : SliverStaggeredGrid.countBuilder(
                      crossAxisCount: 1,
                      staggeredTileBuilder: (val) => StaggeredTile.fit(1),
                      itemBuilder: (context, index) {
                        DataModel model = DataModel.fromJson(
                            dataSnapshot.data!.docs[index].data()
                                as Map<String, dynamic>);
                        return sourceInfo(model, context);
                      },
                      itemCount: dataSnapshot.data!.docs.length);
            },
          ),
        ],
      ),`

### flutter run --verbose:
  ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
                    The following assertion was thrown during a scheduler callback:
                    'package:flutter/src/rendering/viewport.dart': Failed assertion: line 1702 pos 12: 'center!.parent
                    == this': is not true.
                    
                    Either the assertion indicates an error in the framework itself, or we should provide substantially
                    more information in this error message to help you determine and fix the underlying cause.
                    In either case, please report this assertion by filing a bug on GitHub:
                      https://github.com/flutter/flutter/issues/new?template=2_bug.md
                    
                    When the exception was thrown, this was the stack:
                    #2      RenderViewport.indexOfFirstChild (package:flutter/src/rendering/viewport.dart:1702:12)
                    #3      RenderViewportBase.debugDescribeChildren (package:flutter/src/rendering/viewport.dart:974:17)
                    #4      DiagnosticableTreeNode.getChildren (package:flutter/src/foundation/diagnostics.dart:2995:48)
                    #5      DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1567:32)
                    #6      DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1608:6)
                    #7      DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1632:19)
                    #8      MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
                    #9      ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
                    #10     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:188:27)
                    #11     new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
                    #12     new List.of (dart:core-patch/array_patch.dart:50:28)
                    #13     ListIterable.toList (dart:_internal/iterable.dart:213:44)
                    #14     DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1633:8)
                    #15     DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1595:25)
                    #16     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1608:6)
                    #17     WidgetInspectorService._nodeToJson (package:flutter/src/widgets/widget_inspector.dart:1518:18)
                    #18     WidgetInspectorService._reportError (package:flutter/src/widgets/widget_inspector.dart:924:44)
                    #19     FlutterError.reportError (package:flutter/src/foundation/assertions.dart:1131:14)
                    #20     RenderObject._debugReportException (package:flutter/src/rendering/object.dart:1373:18)
                    #21     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1716:7)
                    #22     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:885:18)
                    #23     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:453:19)
                    #24     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
                    #25     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
                    #26     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
                    #27     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1080:9)
                    #28     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
                    #32     _invoke (dart:ui/hooks.dart:166:10)
                    #33     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
                    #34     _drawFrame (dart:ui/hooks.dart:129:31)
                    (elided 5 frames from class _AssertionError and dart:async)
                    ════════════════════════════════════════════════════════════════════════════════════════════════════

### flutter analyze:
Analyzing ateizm_fikri...

   info - Avoid using unnecessary statements - lib\admin\upload.dart:79:7 - unnecessary_statements
   info - Avoid using unnecessary statements - lib\admin\upload.dart:136:7 - unnecessary_statements
   info - This method overrides a method annotated as '@mustCallSuper' in 'AutomaticKeepAliveClientMixin', but doesn't invoke the overridden method -
          lib\admin\upload.dart:144:10 - must_call_super
   info - The operand can't be null, so the condition is always true - lib\models\data_model.dart:38:28 - unnecessary_null_comparison
   info - Unused import: 'package:ateizm_fikri/admin/upload.dart' - lib\views\blog_page.dart:1:8 - unused_import
   info - Unused import: 'package:firebase_core/firebase_core.dart' - lib\views\blog_page.dart:6:8 - unused_import
   info - 'FlatButton' is deprecated and shouldn't be used. Use TextButton instead. See the migration guide in
          flutter.dev/go/material-button-migration-guide). This feature was deprecated after v1.26.0-18.0.pre. - lib\views\categories_page.dart:67:16
          - deprecated_member_use
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final:
          CategoryDetail.title - lib\views\category_details_page.dart:3:7 - must_be_immutable
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final:
          DetailPage.dataModel - lib\views\detail_page.dart:4:7 - must_be_immutable
   info - 'title' is deprecated and shouldn't be used. Use "label" instead, as it allows for an improved text-scaling experience. This feature was
          deprecated after v1.19.0. - lib\views\home_page.dart:38:15 - deprecated_member_use
   info - 'title' is deprecated and shouldn't be used. Use "label" instead, as it allows for an improved text-scaling experience. This feature was
          deprecated after v1.19.0. - lib\views\home_page.dart:42:15 - deprecated_member_use
   info - 'title' is deprecated and shouldn't be used. Use "label" instead, as it allows for an improved text-scaling experience. This feature was
          deprecated after v1.19.0. - lib\views\home_page.dart:46:15 - deprecated_member_use
   info - Dead code - lib\views\splash_screen.dart:49:5 - dead_code

13 issues found. (ran in 3.7s)

### flutter doctor -v
[√] Flutter (Channel stable, 2.5.1, on Microsoft Windows [Version 10.0.19043.1237], locale tr-TR)
    • Flutter version 2.5.1 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (2 weeks ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Semh-\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2021.2.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 7.1.1 (API 25) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 94.0.4606.61
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 94.0.992.31

• No issues found!

### ERROR:
======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
'package:flutter/src/rendering/viewport.dart': Failed assertion: line 1702 pos 12: 'center!.parent == this': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      RenderViewport.indexOfFirstChild (package:flutter/src/rendering/viewport.dart:1702:12)
#3      RenderViewportBase.debugDescribeChildren (package:flutter/src/rendering/viewport.dart:974:17)
#4      DiagnosticableTreeNode.getChildren (package:flutter/src/foundation/diagnostics.dart:2995:48)
#5      DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1567:32)
#6      DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1608:6)
#7      DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1632:19)
#8      MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
#9      ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
#10     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:188:27)
#11     new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#12     new List.of (dart:core-patch/array_patch.dart:50:28)
#13     ListIterable.toList (dart:_internal/iterable.dart:213:44)
#14     DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1633:8)
#15     DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1595:25)
#16     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1608:6)
#17     WidgetInspectorService._nodeToJson (package:flutter/src/widgets/widget_inspector.dart:1518:18)
#18     WidgetInspectorService._reportError (package:flutter/src/widgets/widget_inspector.dart:924:44)
#19     FlutterError.reportError (package:flutter/src/foundation/assertions.dart:1131:14)
#20     RenderObject._debugReportException (package:flutter/src/rendering/object.dart:1373:18)
#21     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1716:7)
#22     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:885:18)
#23     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:453:19)
#24     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#25     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
#26     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
#27     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1080:9)
#28     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#32     _invoke (dart:ui/hooks.dart:166:10)
#33     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#34     _drawFrame (dart:ui/hooks.dart:129:31)
(elided 5 frames from class _AssertionError and dart:async)
====================================================================================================

**Comment by darshankawar** [comment]
> https://stackoverflow.com/questions/69410227/failed-assertion-line-1702-pos-12-center-parent-this-is-not-true

@Semhylmz The code you shared contains 3rd party plugin firebase code. 
Please provide a self contained complete reproducible code sample without any 3rd party plugins that shows this issue.
Thanks.
