### ISSUE TITLE
Exception: Gradle task assembleDebug failed with exit code 1

### ISSUE THREAD

**Issue by masakmal** [flutter/flutter#91152]
I have a problem on my Flutter application when it's running via Android Studio and Visual Studio Code. I've already tried on my web emulator (Chrome and Edge), it's working well. But, when I switch to mobile version, it's not working. I've already switched on my real phone as well in Developer Options mode, it's still not working. I don't use any proxy or stuff. I had several times reinstalled Java JDK, Android Studio, Visual Studio Code, and Wipe Data for AVD, but it's just not working. The following is the result that I can share:

---
```
Launching lib\main.dart on sdk gphone64 x86 64 in debug mode...
Running Gradle task 'assembleDebug'...
Exception in thread "main" java.net.ConnectException: Connection timed out: connect
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at java.base/java.net.Socket.connect(Socket.java:558)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient$1.run(HttpClient.java:526)
	at java.base/sun.net.www.http.HttpClient$1.run(HttpClient.java:524)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/sun.net.www.http.HttpClient.privilegedOpenServer(HttpClient.java:523)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:564)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:212)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1208)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
	at org.gradle.wrapper.Download.download(Download.java:44)
	at org.gradle.wrapper.Install$1.call(Install.java:61)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Exception: Gradle task assembleDebug failed with exit code 1
```
---
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.1, on Microsoft Windows [Version 10.0.19042.1237], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.60.2)
[√] Connected device (3 available)

• No issues found!
```
---
I hope you guys can solve this problem as this is my first time using Flutter. Thank you in advance.

**Comment by definev** [comment]
You should post this in flutter community on flutter, reddit, e.t.c. I think your issue relate JDK or heap memory.

**Comment by mohitjadav** [comment]
I have also the same error I try to find out the bug for two days and I won't able to find what is actually happen to the code
the solution I have done
create the new project with the same package name overwrite the android file after taking backup
or copy the lib folder to the newly created project assets etc...
hope it will currently solve the issue in your project.

**Comment by TahaTesser** [comment]
Hi @masakmal 
This is not an issue with Flutter, please see https://github.com/flutter/flutter/issues/21818#issuecomment-587311963
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
