### ISSUE TITLE
in_app_purchase: type 'PurchaseDetails' is not a subtype of type 'GooglePlayPurchaseDetails' in type cast

### ISSUE THREAD

**Issue by greensopinion** [flutter/flutter#91164]
## Steps to Reproduce

Unknown, it has only happened in a released app

**Expected results:** Should be able to complete in app purchases without errors

**Actual results:** type cast exception

<details>
```
type 'PurchaseDetails' is not a subtype of type 'GooglePlayPurchaseDetails' in type cast
_CastError
#0      InAppPurchaseAndroidPlatform.completePurchase (package:in_app_purchase_android/src/in_app_purchase_android_platform.dart:162)
#1      InAppPurchase.completePurchase (package:in_app_purchase/in_app_purchase.dart:187)
#2      AppStoreInitializer._completePurchase (package:app/appstore/appstore_initializer.dart:79)
#3      AppStoreInitializer._purchasesUpdated.<anonymous closure> (package:app/appstore/appstore_initializer.dart:65)
#4      _GrowableList.forEach (dart:core-patch/growable_array.dart:403)
#5      AppStoreInitializer._purchasesUpdated (package:app/appstore/appstore_initializer.dart:63)
#6      _rootRunUnary (dart:async/zone.dart:1436)
#7      _CustomZone.runUnary (dart:async/zone.dart:1335)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244)
#9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#10     _DelayedData.perform (dart:async/stream_impl.dart:591)
#11     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706)
#12     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663)
#13     _rootRun (dart:async/zone.dart:1420)
#14     _CustomZone.run (dart:async/zone.dart:1328)
#15     _CustomZone.runGuarded (dart:async/zone.dart:1236)
#16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276)
#17     _rootRun (dart:async/zone.dart:1428)
#18     _CustomZone.run (dart:async/zone.dart:1328)
#19     _CustomZone.runGuarded (dart:async/zone.dart:1236)
#20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)
```

```
% flutter analyze
Analyzing app...                                     
No issues found! (ran in 7.5s)
```

```
% flutter doctor -v
[✓] Flutter (Channel stable, 2.5.1, on macOS 11.3.1 20E241 darwin-x64, locale en-CA)
    • Flutter version 2.5.1 at /Users/dgreen/development/flutter_stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (2 weeks ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dgreen/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[!] Android Studio
    • Android Studio at /Users/dgreen/Downloads/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.60.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • iPhone 12 (mobile) • 73C2DF31-CA40-4FF0-9532-389A33FFE62E • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 94.0.4606.61
```

</details>

**Comment by TahaTesser** [comment]
Hi @greensopinion 
The official [sample](https://pub.dev/packages/in_app_purchase/example) doesn't have to throw this error even when in release mode. 

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.5.2, on macOS 12.0 21A5534d darwin-x64, locale en-GB)
    • Flutter version 2.5.2 at /Users/tahatesser/Code/flutter_stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (4 days ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • def0ad20 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos    • darwin-x64     • macOS 12.0 21A5534d darwin-x64
    • Chrome (web)           • chrome   • web-javascript • Google Chrome 94.0.4606.61

• No issues found!
```
	 
</details>

Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example), and expected results vs actual results
Thank you

**Comment by greensopinion** [comment]
@TahaTesser thanks for the quick response. I'll see what I can do here to reproduce the issue, and compare against the sample. So far I haven't been able to reproduce in test. 

Producing a minimal code sample could be difficult due to the nature of testing in-app purchases, i.e. it has to be an app on Google Play. Let me know if you have any advice on how to do this.

It will be a few days before I get to this since I'm currently on vacation. :D

**Comment by greensopinion** [comment]
I've determined the trigger for this issue, the typecast exception occurs when attempting to complete a purchase that has a status of `error`. From the example app:

```
    final Stream<List<PurchaseDetails>> purchaseUpdated =
        InAppPurchaseConnection.instance.purchaseUpdatedStream;
    _subscription = purchaseUpdated.listen((purchaseDetailsList) {
      _listenToPurchaseUpdated(purchaseDetailsList);
    }, onDone: () {
      _subscription.cancel();
    }, onError: (error) {
      // handle error here.
    });

...




  void _listenToPurchaseUpdated(List<PurchaseDetails> purchaseDetailsList) {
    purchaseDetailsList.forEach((PurchaseDetails purchaseDetails) async {
      if (purchaseDetails.status == PurchaseStatus.pending) {
        showPendingUI();
      } else {
        if (purchaseDetails.status == PurchaseStatus.error) {
          handleError(purchaseDetails.error!);
        } else if (purchaseDetails.status == PurchaseStatus.purchased) {
          bool valid = await _verifyPurchase(purchaseDetails);
          if (valid) {
            deliverProduct(purchaseDetails);
          } else {
            _handleInvalidPurchase(purchaseDetails);
            return;
          }
        }
        if (Platform.isAndroid) {
          if (!_kAutoConsume && purchaseDetails.productID == _kConsumableId) {
            await InAppPurchaseConnection.instance
                .consumePurchase(purchaseDetails);
          }
        }
        if (purchaseDetails.pendingCompletePurchase) {
          await InAppPurchaseConnection.instance
              .completePurchase(purchaseDetails);
        }
      }
    });
  }

...


  void handleError(IAPError error) {
    // HERE <<--- attempting to complete the purchase with await InAppPurchase.instance.completePurchase(purchase);
    // results in the typecast exception
  }
```

I had assumed that completing the purchase was necessary to remove the error from the update queue, but it looks like that was an incorrect assumption.

**Comment by greensopinion** [comment]
How is this supposed to work with the in_app_purchase plugin?

From the Apple docs, `finishTransaction` should be called on failed transactions to remove them from the payment queue: https://developer.apple.com/documentation/storekit/skpaymentqueue/1506003-finishtransaction

> Transactions on the payment queue are persistent until they are completed. StoreKit calls your observer’s paymentQueue(_:updatedTransactions:) method every time your app launches or resumes from background to tell you about transactions in the queue. After you've finished processing a transaction in your app, always call the finishTransaction(_:) method to finish the transaction and remove it from the queue.

From the Google docs, it's not super clear but it seems that completing a purchase is not required for errors: https://developer.android.com/google/play/billing/integrate

How are we supposed to use the in_app_purchase plugin for error scenarios to ensure that `finishTransaction` is invoked for Apple purchases that have an error status? it's not clear from the plugin docs what should be done since the example app doesn't do any error handling, and I couldn't find anything in the API docs.

**Comment by SwiftyFlow** [comment]
Amazed we are still talking about that since 2020...

"There is a pending transaction for the same product identifier. Please either wait for it to be finished or finish it manually using `completePurchase` to avoid edge cases..."

Glad the only solution is 

```
var transactions = await SKPaymentQueueWrapper().transactions();
 transactions.forEach((skPaymentTransactionWrapper) {
    SKPaymentQueueWrapper().finishTransaction(skPaymentTransactionWrapper);
});
```
But SKPaymentQueueWrapper is unknown is the library

So now what? I cancel in-app purchases?

**Comment by lukeirvin** [comment]
How were you able to solve for `type 'PurchaseDetails' is not a subtype of type 'GooglePlayPurchaseDetails' in type cast`?

I'm stuck on this and can't get around it. I have a successful Android subscription but I always get an error and can't get the Android purchase details.

**Comment by abextechnologies** [comment]
I followed the code in the example to create upgrade a subscription (buyNonConsumable) by passing the old purchase. But I'm also getting the error type 'PurchaseDetails' is not a subtype of type 'GooglePlayPurchaseDetails' in type cast.

PurchaseDetails? _oldPurchase = ...; // All purchase details values were saved and are got from my backend

purchaseParam = GooglePlayPurchaseParam(
          productDetails: product,
          changeSubscriptionParam: (_oldPurchase != null)
              ? ChangeSubscriptionParam(
                  oldPurchaseDetails: _oldPurchase! as GooglePlayPurchaseDetails,
                  prorationMode: ProrationMode.immediateWithTimeProration,
                )
              : null);
    } else {
      purchaseParam = PurchaseParam(productDetails: product);
    }
    return await _inAppPurchase.buyNonConsumable(purchaseParam: purchaseParam);
