### ISSUE TITLE
After Changing MainActivity.java, All Plugins don't work

### ISSUE THREAD

**Issue by draxexx** [flutter/flutter#91186]
I changed my MainActivity.java like down below:

```
import android.os.Bundle;
import io.flutter.app.FlutterFragmentActivity;
import io.flutter.plugins.flutter_plugin_android_lifecycle.FlutterAndroidLifecyclePlugin;
import io.flutter.plugins.localauth.LocalAuthPlugin;

public class MainActivity extends FlutterFragmentActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        FlutterAndroidLifecyclePlugin.registerWith(
                registrarFor(
                        "io.flutter.plugins.flutter_plugin_android_lifecycle.FlutterAndroidLifecyclePlugin"));
        LocalAuthPlugin.registerWith(registrarFor("io.flutter.plugins.localauth.LocalAuthPlugin"));
    }
}
```
After that I got MissingPluginException 

```
E/flutter (16666): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: NoSuchMethodError: Class 'MissingPluginException' has no instance method '+'.
E/flutter (16666): Receiver: Instance of 'MissingPluginException'
E/flutter (16666): Tried calling: +("OnError")
E/flutter (16666): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
E/flutter (16666): #1      MainPresenter.getIsFirstOpen.<anonymous closure>
package:flutter_kbb/…/home/MainPresenter.dart:17
E/flutter (16666): #2      _rootRunUnary (dart:async/zone.dart:1362:47)
E/flutter (16666): #3      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
E/flutter (16666): #4      _FutureListener.handleError (dart:async/future_impl.dart:172:20)
E/flutter (16666): #5      Future._propagateToListeners.handleError (dart:async/future_impl.dart:719:47)
E/flutter (16666): #6      Future._propagateToListeners (dart:async/future_impl.dart:740:24)
E/flutter (16666): #7      Future._completeError (dart:async/future_impl.dart:550:5)
E/flutter (16666): #8      _completeOnAsyncError (dart:async-patch/async_patch.dart:274:13)
E/flutter (16666): #9      SharedPreferencesService.getSharedPreferenceValue (package:flutter_kbb/screens/utils/SharedPreferencesService.dart)
package:flutter_kbb/…/utils/SharedPreferencesService.dart:1
E/flutter (16666): <asynchronous suspension>
```

**Comment by TahaTesser** [comment]
Hi @draxexx 
Does the issue reproduce in a new project? 

Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and  your `flutter run --verbose` running the minimal code sample
Thank you

**Comment by draxexx** [comment]
Hi @TahaTesser 

This issue is happening for only one project. There is no problem with a new project. By the way, I'm using **local_auth: ^1.1.7**

flutter doctor -v:

```
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1237], locale tr-TR)
    • Flutter version 2.2.3 at D:\flutter_sdks\flutter_2_2_3
    • Framework revision f4abaa0735 (3 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Burak\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\Burak\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.61.0)
    • VS Code at C:\Users\Burak\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.27.0

[√] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 94.0.4606.71    
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 94.0.992.38    

• No issues found!
```

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
