### ISSUE TITLE
On Android <= 7.0, recent DST Root CA X3 Expiration appears to result in CERTIFICATE_VERIFY_FAILED when fetching https://letsencrypt.org (or other Let's Encrypt domains) via Dart HttpClient or http package which wraps it

### ISSUE THREAD

**Issue by fareesh** [flutter/flutter#91195]
Issue also filed here: https://github.com/dart-lang/io/issues/83

## Background Info

DST Root CA X3 expired on September 30, 2021.
More Info here: https://scotthelme.co.uk/lets-encrypt-old-root-expiration/

## Steps to Reproduce

On an Android 7.0 Nougat emulator, run the following modified main.dart which attempts to make a simple request to fetch https://letsencrypt.org

Dart SDK Version: 2.14.0
Flutter Version: 2.5.0

```dart
import 'dart:io';

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  void initState() {
    super.initState();
    fetchUrl();
  }

  void fetchUrl() async {
    HttpClient client = new HttpClient();
    client
        .getUrl(Uri.parse("https://letsencrypt.org/"))
        .then((HttpClientRequest request) {
      return request.close();
    }).then((HttpClientResponse response) {
      print("Response received");
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```

**Expected results:** 

A successful request

**Actual results:** 

CERTIFICATE_VERIFY_FAILED error, as outlined in the logs.

<details>
  <summary>Logs</summary>

```
E/flutter (26059): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: HandshakeException: Handshake error in client (OS Error:
E/flutter (26059): 	CERTIFICATE_VERIFY_FAILED: certificate has expired(handshake.cc:359))
E/flutter (26059): #0      _SecureFilterImpl._handshake (dart:io-patch/secure_socket_patch.dart:101:69)
E/flutter (26059): #1      _SecureFilterImpl.handshake (dart:io-patch/secure_socket_patch.dart:143:25)
E/flutter (26059): #2      _RawSecureSocket._secureHandshake (dart:io/secure_socket.dart:794:54)
E/flutter (26059): #3      _RawSecureSocket._tryFilter (dart:io/secure_socket.dart:924:19)
E/flutter (26059): <asynchronous suspension>
E/flutter (26059):
```

```
[✓] Flutter (Channel stable, 2.5.0, on Ubuntu 21.04 5.13.9-051309-generic, locale en_IN)
    • Flutter version 2.5.0 at /home/fareesh/src/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (4 weeks ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/fareesh/Downloads/android-sdk-linux
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /home/fareesh/Downloads/android-sdk-linux
    • Java binary at: /home/fareesh/Downloads/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /home/fareesh/Downloads/android-studio
    • Flutter plugin version 53.1.1
    • Dart plugin version 201.9317
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.60.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.26.0

[✓] VS Code (version 1.61.0-insider)
    • VS Code at /usr/share/code-insiders
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 7.0 (API 24) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 94.0.4606.71

• No issues found!

```

</details>

**Comment by stuartmorgan** [comment]
The Dart repository is the correct place for issues with a Dart library; none of the relevant code is part of Flutter itself so there's nothing to track here.

**Comment by andrea689** [comment]
Link to new issue: https://github.com/dart-lang/io/issues/83
