### ISSUE TITLE
FlutterWeb's videoElement lacks the requestPictureInPicture method.

### ISSUE THREAD

**Issue by ahyangnb** [flutter/flutter#91205]
I wanted to use a button to trigger the picture-in-picture feature during Web development, but dartSdk doesn't seem to have this feature.

![image](https://user-images.githubusercontent.com/41765610/135787135-3e5a135b-e733-4bcf-878b-b7e24698bce4.png)

![image](https://user-images.githubusercontent.com/41765610/135787141-d288078c-f63a-42a1-8961-0d8f8a48971b.png)

Video can be triggered by right-clicking in the browser.

## Use case
```dart
    VideoElement videoElement = VideoElement();
    videoElement.src = "xxx.mp4";
    videoElement.play();

    /// click Button
    videoElement.requestPictureInPicture();
```

## Proposal
Because the demand side wants this feature,

I hope to add this feature to the SDK or other solutions that can implement picture-in-picture functionality.

**Comment by ahyangnb** [comment]
I noticed that dart_sdK.js in DartSdk doesn't include the requestPictureInPicture method either.

![image](https://user-images.githubusercontent.com/41765610/136138230-1f53c6d0-3465-47ea-8c20-b3d2ab15c3b4.png)

**Comment by mdebbar** [comment]
The Dart team will need to add this to `dart:html`.

For the time being, you can use JS-interop as a workaround to call the method directly in JavaScript:
```dart
import 'dart:js_util' as js_util;

dynamic requestPIP(VideoElement videoElement) {
  js_util.callMethod(videoElement, 'requestPictureInPicture', <Object>[]);
}


// Later ...

VideoElement videoElement = VideoElement();
videoElement.src = "xxx.mp4";
videoElement.play();

/// click Button
requestPIP(videoElement);
```

**Comment by ahyangnb** [comment]
> The Dart team will need to add this to `dart:html`.
> 
> For the time being, you can use JS-interop as a workaround to call the method directly in JavaScript:
> 
> ```dart
> import 'dart:js_util' as js_util;
> 
> dynamic requestPIP(VideoElement videoElement) {
>   js_util.callMethod(videoElement, 'requestPictureInPicture', <Object>[]);
> }
> 
> 
> // Later ...
> 
> VideoElement videoElement = VideoElement();
> videoElement.src = "xxx.mp4";
> videoElement.play();
> 
> /// click Button
> requestPIP(videoElement);
> ```

```
DOMException: Failed to execute 'requestPictureInPicture' on 'HTMLVideoElement': Must be handling a user gesture if there isn't already an element in Picture-in-Picture.
    at Object.callMethod$ [as callMethod] (http://localhost:50513/dart_sdk.js:61551:22)
    at zego_ww_video_view_impl_state.ZegoWwVideoViewImplState.new.requestPIP (http://localhost:50513/packages/zego_ww/src/web/zego_ww_video_view_impl_state.dart.lib.js:173:15)
    at http://localhost:50513/packages/zego_ww/src/web/zego_ww_video_view_impl_state.dart.lib.js:168:14
    at _rootRunUnary (http://localhost:50513/dart_sdk.js:39567:45)
    at async._CustomZone.new.runUnary (http://localhost:50513/dart_sdk.js:38736:14)
    at _FutureListener.then.handleValue (http://localhost:50513/dart_sdk.js:34073:29)
    at handleValueCallback (http://localhost:50513/dart_sdk.js:34633:49)
    at Function._propagateToListeners (http://localhost:50513/dart_sdk.js:34671:17)
    at _Future.new.[_complete] (http://localhost:50513/dart_sdk.js:34505:25)
    at http://localhost:50513/dart_sdk.js:33638:30
    at _rootRun (http://localhost:50513/dart_sdk.js:39553:45)
    at async._CustomZone.new.run (http://localhost:50513/dart_sdk.js:38729:14)
    at async._CustomZone.new.runGuarded (http://localhost:50513/dart_sdk.js:38629:14)
    at http://localhost:50513/dart_sdk.js:38683:33
    at _rootRun (http://localhost:50513/dart_sdk.js:39559:14)
    at async._CustomZone.new.run (http://localhost:50513/dart_sdk.js:38729:14)
    at http://localhost:50513/dart_sdk.js:38668:33
    at internalCallback (http://localhost:50513/dart_sdk.js:25311:11)
```

**Comment by ahyangnb** [comment]
Solved using the above solution.
