### ISSUE TITLE
EventChannel.binaryMessenger Null check operator used on a null value when listening broadcaststream

### ISSUE THREAD

**Issue by ahmetbugraozcan** [flutter/flutter#91215]
I have a single page with a button. My eventchannel is working well if i dont use isolates. But i am using isolates because want to run this code even app is terminated. When i click the button, compute method runs startlistening method. In startlistening method, i create new eventchannel. There isnt any error before . But if i want to listen broadcaststream, it throws me error:

`E/flutter (23095): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Exception: Null check operator used on a null value
E/flutter (23095): #0      EventChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:453:86)
E/flutter (23095): #1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:473:7)
E/flutter (23095): #2      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:472:64)
E/flutter (23095): #3      _runGuarded (dart:async/stream_controller.dart:773:24)
E/flutter (23095): #4      _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:207:7)
E/flutter (23095): #5      _ControllerStream._createSubscription (dart:async/stream_controller.dart:786:19)
E/flutter (23095): #6      _StreamImpl.listen (dart:async/stream_impl.dart:473:9)
E/flutter (23095): #7      startListening (package:fluttercallhandler/main.dart:12:36)
E/flutter (23095): #8      _IsolateConfiguration.apply (package:flutter/src/foundation/_isolates_io.dart:84:34)
E/flutter (23095): #9      _spawn.<anonymous closure> (package:flutter/src/foundation/_isolates_io.dart:91:65)
E/flutter (23095): #10     _spawn.<anonymous closure> (package:flutter/src/foundation/_isolates_io.dart:90:5)
E/flutter (23095): #11     Timeline.timeSync (dart:developer/timeline.dart:163:22)
E/flutter (23095): #12     _spawn (package:flutter/src/foundation/_isolates_io.dart:88:35)
E/flutter (23095): #13     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:286:17)
E/flutter (23095): #14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
E/flutter (23095): `

This is my main.dart
```
import 'dart:async';
import 'dart:isolate';
import 'dart:ui';

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

Future <String> startListening(String s)  async{
  // WidgetsFlutterBinding.ensureInitialized();
  const EventChannel _stream = EventChannel('fluttercallchannel');
  _stream.receiveBroadcastStream().listen((data) {
    debugPrint("data : " + data.toString());
  });

  return "finish";
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(const MyApp());

}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  void initState() {
    // TODO: implement initState
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(title: Text("FlutterCall")),
        body: Center(
          child: Column(
            children: [
              Text("Test"),
              ElevatedButton(
                  onPressed: () async {
                    print(await compute(startListening, ''));
                    // print();
                  },
                  child: Text("Press to Listen Phone State"))
            ],
          ),
        ),
      ),
    );
  }
}

```

And this is my MainActivity.kt
```
package com.example.fluttercallhandler
import android.app.AlarmManager
import android.app.PendingIntent
import androidx.annotation.NonNull
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import android.content.Context
import android.content.Intent
import android.os.Bundle
import android.os.Handler
import android.os.Looper
import android.os.PersistableBundle
import android.telephony.PhoneStateListener
import android.telephony.TelephonyManager
import android.util.Log
import io.flutter.embedding.android.FlutterView
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MethodChannel
import io.flutter.plugins.GeneratedPluginRegistrant
import androidx.annotation.UiThread as UiThread1

class MainActivity: FlutterActivity() {
    private val CHANNEL = "samples.flutter.dev/battery"
    private val CHANNEL2 = "fluttercallchannel"
    private val TAG = "MainActivity"


    override fun onCreate(savedInstanceState: Bundle?, persistentState: PersistableBundle?) {
        super.onCreate(savedInstanceState, persistentState)
    }
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine)
        EventChannel(flutterEngine.dartExecutor.binaryMessenger, CHANNEL2).setStreamHandler(object : EventChannel.StreamHandler {
            override fun onListen(arguments: Any?, events: EventChannel.EventSink?) {
                val telephony: TelephonyManager =
                    context.getSystemService(Context.TELEPHONY_SERVICE) as TelephonyManager
                telephony.listen( object : PhoneStateListener() {
                    @Override
                    override fun onCallStateChanged(state: Int, incomingNumber: String) {
                        super.onCallStateChanged(state, incomingNumber)
                        Log.i(TAG,"incomingNumber : $incomingNumber")
                        Log.i(TAG,"State oncallstatechanged : $state")
                        events?.success(incomingNumber)
                    }
                }, PhoneStateListener.LISTEN_CALL_STATE)

            }

            override fun onCancel(arguments: Any?) {
            }
        })

    }


} 
```

**Comment by maheshmnj** [comment]
Hi @ahmetbugraozcan, Thanks for filing the issue. I can reproduce the issue on stable 2.5.2 and the
 `master 2.6.0-12.0.pre.165`channel. The exception is only thrown when using [compute](https://api.flutter.dev/flutter/foundation/compute-constant.html) method. 

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.5.2, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.5.2 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (3 days ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 94.0.4606.71

• No issues found!
```

```
[✓] Flutter (Channel master, 2.6.0-12.0.pre.165, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.6.0-12.0.pre.165 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a20743ddfe (3 days ago), 2021-09-30 23:43:02 -0400
    • Engine revision 8ec71b64f6
    • Dart version 2.15.0 (build 2.15.0-167.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 94.0.4606.71

• No issues found!
```
</details>


<details>
<summary>logs</summary>

```console
Launching lib/main.dart on sdk gphone arm64 in debug mode...
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
W/FlutterActivityAndFragmentDelegate(15238): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
Connecting to VM Service at ws://127.0.0.1:54999/CnyqZ39b37Y=/ws
E/flutter (15238): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Exception: Null check operator used on a null value
E/flutter (15238): #0      EventChannel.binaryMessenger
E/flutter (15238): #1      EventChannel.receiveBroadcastStream.<anonymous closure>
E/flutter (15238): #2      EventChannel.receiveBroadcastStream.<anonymous closure>
E/flutter (15238): #3      _runGuarded (dart:async/stream_controller.dart:773:24)
E/flutter (15238): #4      _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:207:7)
E/flutter (15238): #5      _ControllerStream._createSubscription (dart:async/stream_controller.dart:786:19)
E/flutter (15238): #6      _StreamImpl.listen (dart:async/stream_impl.dart:473:9)
E/flutter (15238): #7      startListening
E/flutter (15238): #8      _IsolateConfiguration.apply
E/flutter (15238): #9      _spawn.<anonymous closure>
E/flutter (15238): #10     _spawn.<anonymous closure>
E/flutter (15238): #11     Timeline.timeSync (dart:developer/timeline.dart:163:22)
E/flutter (15238): #12     _spawn
E/flutter (15238): #13     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300:17)
E/flutter (15238): #14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
E/flutter (15238):

```
</details>



[reproducible code](https://github.com/flutter/flutter/files/7278189/flutter-bug.zip)

**Comment by ahmetbugraozcan** [comment]
So what should I do? Is this bug because of my code or flutter?

**Comment by maheshmnj** [comment]
@ahmetbugraozcan  someone from the team will take a look and investigate the issue.

**Comment by BernardinD** [comment]
Any update?

**Comment by liugangnhm** [comment]
same issue in v2.5.0/2.5.1/2.5.2

**Comment by aloyalways** [comment]
> Hi @ahmetbugraozcan, Thanks for filing the issue. I can reproduce the issue on stable 2.5.2 and the `master 2.6.0-12.0.pre.165`channel. The exception is only thrown when using [compute](https://api.flutter.dev/flutter/foundation/compute-constant.html) method.
> 
> flutter doctor -v
> logs
> [reproducible code](https://github.com/flutter/flutter/files/7278189/flutter-bug.zip)

This issue is also evident when using Isolate.spawn function.
