### ISSUE TITLE
[google_maps_flutter_web] [web] onMapCreated not called with AnimatedOpacity

### ISSUE THREAD

**Issue by ahetawal-p** [flutter/flutter#91276]
## Steps to Reproduce
Here is the basic gist of showing google maps after its being created.

```
bool isMapVisible = false;

AnimatedOpacity(
  opacity: isMapVisible ? 1.0 : 0,
  duration: Duration(milliseconds: 600),
  child: GoogleMap(
    initialCameraPosition: CameraPosition(
      target: LatLng(
        37.4503622703105, 127.12989966313339),
        zoom: 16,
    ),
    onMapCreated: (GoogleMapController controller) {
      _controller.complete(controller);
      Future.delayed(
          const Duration(milliseconds: 550),
          () => setState(() {isMapVisible = true;}));
    },
))
```
While the above code works for iOS and Android, it fails to run on `flutter web`. 
The `onMapCreated` callback is never called when opacity is set to `0.0` initially.

**Expected results:** 

**Actual results:** 

<details>
  <summary>flutter doc -v</summary>

```
ahetawal@thatch thatch (main)*$ flutter doctor -v
[✓] Flutter (Channel stable, 2.5.1, on macOS 11.6 20G165 darwin-x64, locale en-US)
    • Flutter version 2.5.1 at /Users/ahetawal/sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (2 weeks ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/ahetawal/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.1)
    • IntelliJ at /Users/ahetawal/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.1)
    • IntelliJ at /Users/ahetawal/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/212.5080.55/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.59.0)
    • VS Code at /Users/ahetawal/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • iPhone 11 Pro (mobile) • EEC598B2-5A92-43AA-8C44-76033FDE5268 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 94.0.4606.61

• No issues found!
</details>

**Comment by maheshmnj** [comment]
Hi @ahetawal-p, Thanks for filing the issue. I can reproduce the issue on the latest stable 2.5.2. and the master channel. The Map fails to load and throws an `assertion failure` when the initial opacity is 0. With this error, the other widgets also do not load this can be understood from the below code sample.  
 
dependencies used: 

>  google_maps_flutter: ^2.0.11
   google_maps_flutter_web: ^0.3.2

<details>
<summary>minimal code sample</summary>

```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Google Maps Demo',
      home: MapSample(),
    );
  }
}

class MapSample extends StatefulWidget {
  @override
  State<MapSample> createState() => MapSampleState();
}

class MapSampleState extends State<MapSample> {
  final Completer<GoogleMapController> _controller = Completer();

  static const CameraPosition _kGooglePlex = CameraPosition(
    target: LatLng(37.42796133580664, -122.085749655962),
    zoom: 14.4746,
  );

  static const CameraPosition _kLake = CameraPosition(
      bearing: 192.8334901395799,
      target: LatLng(37.43296265331129, -122.08832357078792),
      tilt: 59.440717697143555,
      zoom: 19.151926040649414);
  bool isMapVisible = false;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ListView(
        children: [
          SizedBox(
            height: 500,
            child: AnimatedOpacity(
              opacity: isMapVisible ? 1.0 : 0,  /// with 0 initial opacity map fails to load 
              duration: const Duration(milliseconds: 5000),
              child: GoogleMap(
                mapType: MapType.hybrid,
                initialCameraPosition: _kGooglePlex,
                onMapCreated: (GoogleMapController controller) {
                  _controller.complete(controller);
                  setState(() {
                    isMapVisible = true;
                  });
                },
              ),
            ),
          ),
          Center(
            child: AnimatedOpacity(
              opacity: isMapVisible ? 1.0 : 0,
              duration: const Duration(milliseconds: 5000),
              child: Container(
                height: 200,
                width: 200,
                margin: EdgeInsets.all(50),
                color: Colors.red,
              ),
            ),
          )
        ],
      ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: _goToTheLake,
        label: const Text('To the lake!'),
        icon: Icon(Icons.directions_boat),
      ),
    );
  }

  Future<void> _goToTheLake() async {
    final GoogleMapController controller = await _controller.future;
    controller.animateCamera(CameraUpdate.newCameraPosition(_kLake));
  }
}

```
</details>




<details>
<summary>logs</summary>

```
Restarted application in 2,824ms.
Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/canvaskit/surface_factory.dart:111:12
_cache.contains(surface)
is not true
    at Object.throw_ [as throw] (http://localhost:50320/dart_sdk.js:5061:11)
    at Object.assertFailed (http://localhost:50320/dart_sdk.js:4986:15)
    at _engine.SurfaceFactory.new.isLive (http://localhost:50320/dart_sdk.js:139913:51)
    at _engine.Surface.new.[_contextLostListener] (http://localhost:50320/dart_sdk.js:139641:19)

```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.5.2, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.5.2 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (3 days ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 94.0.4606.71

• No issues found!
```

```
[✓] Flutter (Channel master, 2.6.0-12.0.pre.165, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.6.0-12.0.pre.165 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a20743ddfe (3 days ago), 2021-09-30 23:43:02 -0400
    • Engine revision 8ec71b64f6
    • Dart version 2.15.0 (build 2.15.0-167.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 94.0.4606.71

• No issues found!
```
</details>

**Comment by ditman** [comment]
@ahetawal-p I think in some code paths `opacity: 0` is interpreted as: "do not render this widget initially, it won't show up!".

As a workaround, can you try something like:

```dart
  opacity: isMapVisible ? 1.0 : 0.00001,
```

That way opacity will not be "0" for the framework (but it will be for the human eye).

**Comment by ditman** [comment]
(I have a hunch that this is not a GoogleMap issue, it's probably a general issue with PlatformViews. A VideoPlayer widget would probably have the same issue if rendered with 0% opacity)

**Comment by maheshmnj** [comment]
>(I have a hunch that this is not a GoogleMaps-only issue, it's probably a general issue with PlatformViews. A VideoPlayer widget would probably have the same issue if rendered with 0% opacity)

I just verified with `video_player: ^2.2.5` works fine on mobile platforms with 0% opacity on stable `2.5.2`, I could not verify it on the web the video fails to load with or without the AnimatedOpacity, will update the comment if I see any difference. 

<details>
<summary>code sample</summary>


```dart
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(primarySwatch: Colors.blue),
      home: MyHomePage(),
    );
  }
}

class VideoPlayerWidget extends StatefulWidget {
  const VideoPlayerWidget({Key? key}) : super(key: key);

  @override
  _VideoPlayerWidgetState createState() => _VideoPlayerWidgetState();
}

class _VideoPlayerWidgetState extends State<VideoPlayerWidget> {
  @override
  void dispose() {
    super.dispose();
    _controller.dispose();
  }

  late VideoPlayerController _controller;

  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.network(
        // 'https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4'
        'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4')
      ..initialize().then((_) {
        setState(() {});
        _controller.play();
      });
  }

  @override
  Widget build(BuildContext context) {
    return _controller.value.isInitialized
        ? AspectRatio(
            aspectRatio: _controller.value.aspectRatio,
            child: VideoPlayer(_controller),
          )
        : Container(
            height: 200,
            width: 200,
            color: Colors.red,
          );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late FocusNode focusNode;

  @override
  void initState() {
    super.initState();
    focusNode = FocusNode();
    WidgetsBinding.instance!.addPostFrameCallback((timeStamp) {
      setState(() {
        isMapVisible = true;
      });
    });
  }

  @override
  void dispose() {
    super.dispose();
    focusNode.dispose();
  }

  bool isMapVisible = false;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            SizedBox(
                height: 300,
                child: AnimatedOpacity(
                    opacity: isMapVisible ? 1.0 : 0,
                    duration: const Duration(milliseconds: 5000),
                    child: const VideoPlayerWidget()))
          ],
        ),
      ),
    );
  }
}


```

</details>

**Comment by artificerchris** [comment]
I'm running into this same bug, or at least one very like it, but unlike the OP I don't have any animated widgets between me and the map, for me the root cause seems to be the map widget getting rebuilt before `onMapCreated` gets called causes it to never be created. It's most reliably happening in iOS Safari, but I have seen it in macOS Chrome as well.

**Comment by ditman** [comment]
@artificerchris what version of flutter are you using? what's the output of `flutter doctor -v`?

**Comment by felix-ht** [comment]
Just saw a the same assertion on [mapbox flutter](https://github.com/flutter-mapbox-gl/maps) - seems to be quite random tho and happens even without animations.
`Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/canvaskit/surface_factory.dart:111:12`

**Comment by ditman** [comment]
I remember a while ago attempting to render a map with 0% opacity (or was it in a 0x0 div?) would cause the map to *not render anything*. If that's the same case, google maps flutter web is waiting for a "tiles loaded" event to return the controller to the program; maybe that's never happening when the map is rendered invisible :/

**Comment by artificerchris** [comment]
@ditman I'd have to dig in again to be 100% sure, but it seemed like that's what was happening to me too, cause that's the same event (I think from what I remember) that ultimately triggers the `onMapCreated` event on the Flutter side. For me, the issue was very easy to repro in macOS desktop Safari, but as to _why_ it isn't firing tiles loaded, I couldn't say. I'm not animating it in or anything, it's just on a page when I nav to it.

**Comment by ditman** [comment]
@artificerchris I added waiting for tiles loaded as an event in version 0.3.1 of the google_maps_flutter_web package ([changelog](https://pub.dev/packages/google_maps_flutter_web/changelog)), if you want, maybe you can try pinning the version of the package to exactly `0.3.0+4` (the one *before* the change) and see if it helps with the issue?

That way we can discard if it's that event, or maybe some underlying bug/feature in the Google Maps JS SDK. 

(I remember the map not rendering in an invisible/0x0 div way back when we were developing the OG version of the plugin, so I don't expect an improvement, but maybe the tiles loaded is not a reliable event to wait for!)

**Comment by artificerchris** [comment]
I’ll give that a go over the weekend, and report back!

**Comment by artificerchris** [comment]
@ditman I did check over the weekend and re-confirmed with my PM this morning, we didn't start seeing this bug until we upgraded that package and if I roll back that does fix this issue, but that's not a real solution for me cause part of why I upgraded was the fix for the function to transform screen space coords to map coords.

**Comment by ditman** [comment]
@artificerchris yikes, I added the initialization change to be able to test those features of map in a non-crazy way. Maybe there's other events that we can use to detect when the map is ready to go (instead of "tilesloaded"), for example, according to this:

* https://developers.google.com/maps/documentation/javascript/events

It seems the first "bounds_changed" or "projection_change" might suffice (especially because all we care about is for the map to have a proper projection, we don't really care that tiles are actually loaded).

(However, I'm **not sure** if all those events are thrown when initializing at the same time as "tilesloaded" or not.)

I can prepare a PR of google_maps_web that uses some other of the "init" events, and see if that works better for your use case? (You can include it via a Git override?)

**Comment by artificerchris** [comment]
Sounds like a plan to me, I'm fairly busy this week, but I should have time either this evening or tomorrow evening to check it, otherwise it'll have to wait till the weekend. Just @ me and let me know the branch the PR is in and I'll check it out as soon as I can!

**Comment by felix-ht** [comment]
@ditman Just to confirm - currently the assumed cause is that onPlatformViewCreated gets called to late?

**Comment by ditman** [comment]
@artificerchris I created a [PR](https://github.com/flutter/plugins/pull/4612), here's the package git info for overrides/testing:

```yaml
dependencies:
  google_maps_flutter_web:
    git:
      url: https://github.com/ditman/plugins.git
      ref: maps-web-earlier-init
      path: packages/google_maps_flutter/google_maps_flutter_web
```

@felix-ht the surface_factory errors you're seeing should have been fixed in `master` (find the latest [commits by `hterkelsen` in the flutter/engine repo](https://github.com/flutter/engine/commits?author=hterkelsen)). The current theory is that if the map is not visibly loaded, the tiles won't be downloaded and the `loadedtiles` event that was used before to determine when the map was ready might not be firing.

After a bunch of testing, I wrote the changes above, listening to a bunch of other events that *seem* to get fired earlier in the lifecycle of the map, but I'm not super thrilled with the change; in my experience, there seems to be a race condition between the time the different parts of the map are initialized and the time when calculations can be made accurately. It seems that the map is firing certain change events while the map display is loading/being animated/moving around (*internally*)

**Comment by ditman** [comment]
@artificerchris any luck with the new events from the maps? Anybody else?

**Comment by artificerchris** [comment]
@ditman Hey, sorry I never got back to this, no it's still going on for us, we've noticed in chrome once or twice now too, but still always on iOS.

**Comment by ditman** [comment]
@artificerchris just to confirm: [this didn't help](https://github.com/flutter/flutter/issues/91276#issuecomment-993062069)?

**Comment by artificerchris** [comment]
@ditman correct

**Comment by tirth-patel-nc** [comment]
# Triage Report

I was able to reproduce the issue using the provided code sample on both the `stable (3.29.3)` and `master (3.33.0-1.0.pre.104)` channels on Web (for both without `--wasm` and with `--wasm`). Also, I didn't observe any errors in the debug console or browser console.

❗ Using `0.1` or `0.01` makes it work.

On Android & iOS, it is working fine.

<img width="1512" alt="Image" src="https://github.com/user-attachments/assets/11d67c7f-d773-4e49-900e-31fb0dd54fc9" />

<details>
<summary>Code Sample (Same as OP)</summary>

```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(title: 'Flutter Google Maps Demo', home: MapSample());
  }
}

class MapSample extends StatefulWidget {
  const MapSample({super.key});

  @override
  State<MapSample> createState() => MapSampleState();
}

class MapSampleState extends State<MapSample> {
  final Completer<GoogleMapController> _controller = Completer();

  static const CameraPosition _kGooglePlex = CameraPosition(
    target: LatLng(37.42796133580664, -122.085749655962),
    zoom: 14.4746,
  );

  static const CameraPosition _kLake = CameraPosition(
    bearing: 192.8334901395799,
    target: LatLng(37.43296265331129, -122.08832357078792),
    tilt: 59.440717697143555,
    zoom: 19.151926040649414,
  );
  bool isMapVisible = false;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ListView(
        children: [
          SizedBox(
            height: 500,
            child: AnimatedOpacity(
              opacity: isMapVisible ? 1.0 : 0,

              /// with 0 initial opacity map fails to load
              duration: const Duration(milliseconds: 5000),
              child: GoogleMap(
                mapType: MapType.hybrid,
                initialCameraPosition: _kGooglePlex,
                onMapCreated: (GoogleMapController controller) {
                  _controller.complete(controller);
                  setState(() {
                    isMapVisible = true;
                  });
                },
              ),
            ),
          ),
          Center(
            child: AnimatedOpacity(
              opacity: isMapVisible ? 1.0 : 0,
              duration: const Duration(milliseconds: 5000),
              child: Container(
                height: 200,
                width: 200,
                margin: EdgeInsets.all(50),
                color: Colors.red,
              ),
            ),
          ),
        ],
      ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: _goToTheLake,
        label: const Text('To the lake!'),
        icon: Icon(Icons.directions_boat),
      ),
    );
  }

  Future<void> _goToTheLake() async {
    final GoogleMapController controller = await _controller.future;
    controller.animateCamera(CameraUpdate.newCameraPosition(_kLake));
  }
}
```

</details>

<details>
  <summary>stable (3.29.3) - flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.29.3, on macOS 15.4.1 24E263 darwin-arm64, locale
    en-IN) [970ms]
    • Flutter version 3.29.3 on channel stable at
      /Users/tirthpatel/Development/flutter_stable/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ea121f8859 (4 weeks ago), 2025-04-11 19:10:07 +0000
    • Engine revision cf56914b32
    • Dart version 3.7.2
    • DevTools version 2.42.3

[✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0)
    [855ms]
    • Android SDK at /Users/tirthpatel/Library/Android/sdk
    • Platform android-36, build-tools 36.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on
      this machine.
      To manually set the JDK path, use: `flutter config
      --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13355223-b631.42)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.3) [556ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16E140
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [9ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.3) [9ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13355223-b631.42)

[✓] VS Code (version 1.99.3) [8ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available) [5.5s]
    • macOS (desktop)                 • macos                 • darwin-arm64   •
      macOS 15.4.1 24E263 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         •
      macOS 15.4.1 24E263 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript •
      Google Chrome 135.0.7049.115

[✓] Network resources [559ms]
    • All expected network resources are available.

• No issues found!
```

</details>

<details>
  <summary>master (3.33.0-1.0.pre.104) - flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 3.33.0-1.0.pre.104, on macOS 15.4.1 24E263 darwin-arm64, locale en-IN) [1,376ms]
    • Flutter version 3.33.0-1.0.pre.104 on channel master at /Users/tirthpatel/Development/flutter_master/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c685293fc4 (6 hours ago), 2025-05-15 17:55:29 -0700
    • Engine revision c685293fc4
    • Dart version 3.9.0 (build 3.9.0-131.0.dev)
    • DevTools version 2.46.0

[✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0) [809ms]
    • Android SDK at /Users/tirthpatel/Library/Android/sdk
    • Emulator version 35.4.9.0 (build_id 13025442) (CL:N/A)
    • Platform android-36, build-tools 36.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13355223-b631.42)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.3) [498ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16E140
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [8ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.3) [7ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13355223-b631.42)

[✓] VS Code (version 1.100.1) [7ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.110.0

[✓] Connected device (4 available) [5.6s]
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 16 (API 36) (emulator)
    • iPhone 16 Plus (mobile)     • B19185FD-0093-4E49-B587-16642A3EC7D3 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-18-4 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 15.4.1 24E263 darwin-arm64
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 136.0.7103.114

[✓] Network resources [636ms]
    • All expected network resources are available.

• No issues found!
```

</details>
