### ISSUE TITLE
Java Error on run

### ISSUE THREAD

**Issue by rupamking1** [flutter/flutter#91312]
```comsole
Running Gradle task 'assembleDebug'...
Exception in thread "main" java.lang.NoClassDefFoundError: org/gradle/internal/jvm/UnsupportedJavaRuntimeException
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
	at java.base/java.lang.Class.getMethodsRecursive(Class.java:3307)
	at java.base/java.lang.Class.getMethod0(Class.java:3293)
	at java.base/java.lang.Class.getMethod(Class.java:2106)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:29)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: java.lang.ClassNotFoundException: org.gradle.internal.jvm.UnsupportedJavaRuntimeException
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 8 more
```

**Comment by TahaTesser** [comment]
Hi @rupamking1 
First of all, make there are no errors or warnings in your `flutter doctor -v`, android licenses are accepted, if not, install `cmd-tools` from SDK Manager and execute `flutter doctor --android-licenses` Also make sure you've Java 11, not 15 or 16. then run the app

If the problem persists, try https://github.com/flutter/flutter/issues/77161#issuecomment-790859153


If the problem still persists, can you please provide your `flutter doctor -v` with the upgrade, complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by rupamking1** [comment]
#77161 (comment) 
I watched but now it makes another error-

``` 
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:packageDebug'.
> A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
   > java.io.IOException: Failed to generate v1 signature

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 9s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

```

**Comment by TahaTesser** [comment]
@rupamking1 
Your new error is not related to Flutter but Gradle, please try `invalidate caches and restart.` from Android Studio menu

**Comment by rupamking1** [comment]
I already tried  `invalidate caches and restart.` but that not working

Please Explain what is this- 
```
Execution failed for task ':app:packageDebug'.
> A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
   > java.io.IOException: Failed to generate v1 signature
```

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
