### ISSUE TITLE
pod install [!] An error occurred while processing the post-install hook of the Podfile.

### ISSUE THREAD

**Issue by pranjali420** [flutter/flutter#91343]
Generating Pods project
[!] An error occurred while processing the post-install hook of the Podfile.

undefined method `each_child' for #<Dir:0x00007fd6463ad350>

```
/Users/{user}/Documents/Flutter/packages/flutter_tools/bin/podhelper.rb:57:in `block in flutter_additional_ios_build_settings'
/Users/{user}/Documents/Flutter/packages/flutter_tools/bin/podhelper.rb:54:in `each'
/Users/{user}/Documents/Flutter/packages/flutter_tools/bin/podhelper.rb:54:in `flutter_additional_ios_build_settings'
/Users/{user}/Documents/chat_firebase/ios/Podfile:39:in `block (3 levels) in from_ruby'
/Users/{user}/Documents/chat_firebase/ios/Podfile:38:in `each'
/Users/{user}/Documents/chat_firebase/ios/Podfile:38:in `block (2 levels) in from_ruby'
/Users/{user}/.rvm/rubies/ruby-2.5.5/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.10.2/lib/cocoapods-core/podfile.rb:179:in `post_install!'
/Users/{user}/.rvm/rubies/ruby-2.5.5/lib/ruby/gems/2.5.0/gems/cocoapods-1.10.2/lib/cocoapods/installer.rb:897:in `run_podfile_post_install_hook'
/Users/{user}/.rvm/rubies/ruby-2.5.5/lib/ruby/gems/2.5.0/gems/cocoapods-1.10.2/lib/cocoapods/installer.rb:885:in `block in run_podfile_post_install_hooks'
/Users/{user}/.rvm/rubies/ruby-2.5.5/lib/ruby/gems/2.5.0/gems/cocoapods-1.10.2/lib/cocoapods/user_interface.rb:145:in `message'
/Users/{user}/.rvm/rubies/ruby-2.5.5/lib/ruby/gems/2.5.0/gems/cocoapods-1.10.2/lib/cocoapods/installer.rb:884:in `run_podfile_post_install_hooks'
/Users/{user}/.rvm/rubies/ruby-2.5.5/lib/ruby/gems/2.5.0/gems/cocoapods-1.10.2/lib/cocoapods/installer.rb:329:in `block (2 levels) in create_and_save_projects'
/Users/{user}/.rvm/rubies/ruby-2.5.5/lib/ruby/gems/2.5.0/gems/cocoapods-1.10.2/lib/cocoapods/installer/xcode/pods_project_generator/pods_project_writer.rb:61:in `write!'
/Users/{user}/.rvm/rubies/ruby-2.5.5/lib/ruby/gems/2.5.0/gems/cocoapods-1.10.2/lib/cocoapods/installer.rb:328:in `block in create_and_save_projects'
/Users/{user}/.rvm/rubies/ruby-2.5.5/lib/ruby/gems/2.5.0/gems/cocoapods-1.10.2/lib/cocoapods/user_interface.rb:64:in `section'
/Users/{user}/.rvm/rubies/ruby-2.5.5/lib/ruby/gems/2.5.0/gems/cocoapods-1.10.2/lib/cocoapods/installer.rb:307:in `create_and_save_projects'
/Users/{user}/.rvm/rubies/ruby-2.5.5/lib/ruby/gems/2.5.0/gems/cocoapods-1.10.2/lib/cocoapods/installer.rb:299:in `generate_pods_project'
/Users/{user}/.rvm/rubies/ruby-2.5.5/lib/ruby/gems/2.5.0/gems/cocoapods-1.10.2/lib/cocoapods/installer.rb:178:in `integrate'
/Users/{user}/.rvm/rubies/ruby-2.5.5/lib/ruby/gems/2.5.0/gems/cocoapods-1.10.2/lib/cocoapods/installer.rb:166:in `install!'
/Users/{user}/.rvm/rubies/ruby-2.5.5/lib/ruby/gems/2.5.0/gems/cocoapods-1.10.2/lib/cocoapods/command/install.rb:52:in `run'
/Users/{user}/.rvm/gems/ruby-2.5.5/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/{user}/.rvm/rubies/ruby-2.5.5/lib/ruby/gems/2.5.0/gems/cocoapods-1.10.2/lib/cocoapods/command.rb:52:in `run'
/Users/{user}/.rvm/rubies/ruby-2.5.5/lib/ruby/gems/2.5.0/gems/cocoapods-1.10.2/bin/pod:55:in `<top (required)>'
/Users/{user}/.rvm/gems/ruby-2.5.5/bin/pod:23:in `load'
/Users/{user}/.rvm/gems/ruby-2.5.5/bin/pod:23:in <main>'`
```

This is occurring when I run `pod install` I am not able to find the root cause.

**Comment by pranjali420** [comment]
Hi @TahaTesser 
Thanks for the help, I have followed the steps you have provided. But I'm still getting the above errors and additional. to that I am getting below errors as well.

`[  +35 ms] Error running pod install
[   +1 ms] Error launching application on iPhone 8.
[   +3 ms] "flutter run" took 29,504ms.
[   +7 ms] 
           #0      throwToolExit
(package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand
           (package:flutter_tools/src/commands/run.dart:663:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand
(package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand
           (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure>
           (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[ +185 ms] ensureAnalyticsSent: 184ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
`

**Comment by pranjali420** [comment]
@TahaTesser Did you know the root cause of the above errors?

**Comment by TahaTesser** [comment]
@pranjali420 
Would you mind providing complete logs in a file, execute `fluter run -v > run.log`. This will copy logs in a called `run.log`, please provide this file and please provide complete Podfile too

**Comment by pranjali420** [comment]
Hi @TahaTesser 

My `flutter doctor -v`

```
`[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-IN)
    • Flutter version 2.2.3 at /Users/PranjaliW/Documents/Flutter
    • Framework revision f4abaa0735 (3 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed
      instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed
      instructions).

[✓] VS Code (version 1.60.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (3 available)
    • iPhone 8 (mobile)      • 57E75E34-2D1F-4502-BA56-CAF379A4CFDF • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)
    • iPhone 8 Plus (mobile) • C6BCE0BF-38F6-4004-94D5-296D7ED5A42C • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome
      94.0.4606.71
    ! Error: iPhone is not connected. Xcode will continue when iPhone is connected. (code -13)

! Doctor found issues in 2 categories.`

```
My pod file :
```
`# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
`
```
[run.log](https://github.com/flutter/flutter/files/7293803/run.log)

**Comment by pranjali420** [comment]
[run.log](https://github.com/flutter/flutter/files/7294180/run.log)

Here is the latest log file.

**Comment by pranjali420** [comment]
It has been resolve hence closing this thread.
