### ISSUE TITLE
Offset argument contained a NaN value. Linux Desktop

### ISSUE THREAD

**Issue by cwangfr** [flutter/flutter#91379]
## Steps to Reproduce

1. Run `flutter create bug`.
2. 'cd bug'
3. 'flutter run -d linux'

<details>
<summary>logs</summary>

```console
Launching lib/main.dart on Linux in debug mode...
Building Linux application...                                           
Syncing files to device Linux...                                    86ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on Linux is available at:
http://127.0.0.1:37353/dGXn8WYnT30=/

══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY
╞═════════════════════════════════════════════════════════
The following assertion was thrown during paint():
Offset argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 52 pos 10: '<optimized out>'

Either the assertion indicates an error in the framework itself, or we should
provide substantially
more information in this error message to help you determine and fix the
underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was:
  MaterialApp
  MaterialApp:file:///home/xxx/works/temp/bug/lib/main.dart:13:12

When the exception was thrown, this was the stack:
#2      _offsetIsValid (dart:ui/painting.dart:52:10)
#3      Canvas.drawParagraph (dart:ui/painting.dart:4466:12)
#4      TextPainter.paint
(package:flutter/src/painting/text_painter.dart:642:12)
#5      BannerPainter.paint (package:flutter/src/widgets/banner.dart:147:18)
#6      RenderCustomPaint._paintWithPainter
(package:flutter/src/rendering/custom_paint.dart:563:13)
#7      RenderCustomPaint.paint
(package:flutter/src/rendering/custom_paint.dart:610:7)
#8      RenderObject._paintWithContext
(package:flutter/src/rendering/object.dart:2409:7)
#9      PaintingContext.paintChild
(package:flutter/src/rendering/object.dart:189:13)
#10     RenderProxyBoxMixin.paint
(package:flutter/src/rendering/proxy_box.dart:140:15)
#11     RenderObject._paintWithContext
(package:flutter/src/rendering/object.dart:2409:7)
#12     PaintingContext.paintChild
(package:flutter/src/rendering/object.dart:189:13)
#13     RenderProxyBoxMixin.paint
(package:flutter/src/rendering/proxy_box.dart:140:15)
#14     RenderObject._paintWithContext
(package:flutter/src/rendering/object.dart:2409:7)
#15     PaintingContext.paintChild
(package:flutter/src/rendering/object.dart:189:13)
#16     RenderProxyBoxMixin.paint
(package:flutter/src/rendering/proxy_box.dart:140:15)
#17     RenderObject._paintWithContext
(package:flutter/src/rendering/object.dart:2409:7)
#18     PaintingContext.paintChild
(package:flutter/src/rendering/object.dart:189:13)
#19     RenderProxyBoxMixin.paint
(package:flutter/src/rendering/proxy_box.dart:140:15)
#20     RenderObject._paintWithContext
(package:flutter/src/rendering/object.dart:2409:7)
#21     PaintingContext.paintChild
(package:flutter/src/rendering/object.dart:189:13)
#22     RenderView.paint (package:flutter/src/rendering/view.dart:209:15)
#23     RenderObject._paintWithContext
(package:flutter/src/rendering/object.dart:2409:7)
#24     PaintingContext._repaintCompositedChild
(package:flutter/src/rendering/object.dart:141:11)
#25     PaintingContext.repaintCompositedChild
(package:flutter/src/rendering/object.dart:100:5)
#26     PipelineOwner.flushPaint
(package:flutter/src/rendering/object.dart:979:29)
#27     RendererBinding.drawFrame
(package:flutter/src/rendering/binding.dart:455:19)
#28     WidgetsBinding.drawFrame
(package:flutter/src/widgets/binding.dart:883:13)
#29     RendererBinding._handlePersistentFrameCallback
(package:flutter/src/rendering/binding.dart:319:5)
#30     SchedulerBinding._invokeFrameCallback
(package:flutter/src/scheduler/binding.dart:1143:15)
#31     SchedulerBinding.handleDrawFrame
(package:flutter/src/scheduler/binding.dart:1080:9)
#32     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure>
(package:flutter/src/scheduler/binding.dart:863:7)
(elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class
_Timer, dart:async, and dart:async-patch)

The following RenderObject was being processed when the exception was fired:
RenderCustomPaint#03792:
  needs compositing
  creator: CustomPaint ← Banner ← CheckedModeBanner ← Title ← Directionality ←
    _LocalizationsScope-[GlobalKey#380d5] ← Semantics ← Localizations ←
    MediaQuery ←
    _MediaQueryFromWindow ← _FocusMarker ← Focus ← ⋯
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=1280.0, h=720.0)
  size: Size(1280.0, 720.0)
This RenderObject had the following descendants (showing up to depth 5):
    child: RenderPointerListener#3e683
      child: RenderAbsorbPointer#a455c
        child: RenderSemanticsAnnotations#c43bd
          child: _RenderTheatre#3128e
            onstage 1: RenderIgnorePointer#62434
            onstage 2: RenderSemanticsAnnotations#ef258
            no offstage children
════════════════════════════════════════════════════════════════════════════════
════════════════════
The Flutter DevTools debugger and profiler on Linux is available at:
http://127.0.0.1:9101?uri=http://127.0.0.1:37353/dGXn8WYnT30=/
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.5.2, on Ubuntu 20.04.3 LTS 5.11.0-37-generic,
    locale zh_CN.UTF-8)
    • Flutter version 2.5.2 at /home/xxx/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (6 天前), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/xxx/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /snap/android-studio/114/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /snap/android-studio/114/android-studio
    • Flutter plugin version 61.2.2
    • Dart plugin version 203.8430
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.3 LTS 5.11.0-37-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 94.0.4606.71

• No issues found!
```
</details>

**Comment by darshankawar** [comment]
Thanks for confirming. As this is working and fixed on latest master, I feel safe to close this as fixed.
You may need to be on master until the fix makes it to stable. 
Closing for now. If you disagree, write in comments and I'll reopen it.
