### ISSUE TITLE
Unexplained error

### ISSUE THREAD

**Issue by Hu1buerger** [flutter/flutter#91519]
```dart 
class Issue{

  List<LogEntry> _log = <LogEntry>[];
  List<LogEntry> get log => _log;

  Future<void> loadLog() async {
    // logservice reads from sharedPreferences and constructs a list of LogEntrys (returns always != null)
    var logs = await logService.load();
    _log = logs;
    _sortLog();
    return;
  }
}

void main() async {
   final issueObject = Issue();
}
```

An exception gets thrown. I know that the stack looks like this [main, loadLog].
`2021-10-08 21:44:51.524 7922-7951/com.example E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value`

<details>
```
$flutter run --verbose
======== Exception caught by widgets library =======================================================
The following assertion was thrown while applying parent data.:
Incorrect use of ParentDataWidget.

The ParentDataWidget Expanded(flex: 1) wants to apply ParentData of type FlexParentData to a RenderObject, which has been set up to accept ParentData of incompatible type BoxParentData.

Usually, this means that the Expanded widget has the wrong ancestor RenderObjectWidget. Typically, Expanded widgets are placed directly inside Flex widgets.
The offending Expanded is currently placed inside a Padding widget.

The ownership chain for the RenderObject that received the incompatible parent data was:
  Column ← Expanded ← Padding ← SizedBox ← _BodyBuilder ← MediaQuery ← LayoutId-[<_ScaffoldSlot.body>] ← CustomMultiChildLayout ← AnimatedBuilder ← DefaultTextStyle ← ⋯
When the exception was thrown, this was the stack: 
#0      RenderObjectElement._updateParentData.<anonymous closure> (package:flutter/src/widgets/framework.dart:5835:11)
#1      RenderObjectElement._updateParentData (package:flutter/src/widgets/framework.dart:5851:6)
#2      ParentDataElement._applyParentData.applyParentDataToChild (package:flutter/src/widgets/framework.dart:5053:15)
#3      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#4      ParentDataElement._applyParentData (package:flutter/src/widgets/framework.dart:5059:5)
#5      ParentDataElement.notifyClients (package:flutter/src/widgets/framework.dart:5103:5)
#6      ProxyElement.updated (package:flutter/src/widgets/framework.dart:5030:5)
#7      ProxyElement.update (package:flutter/src/widgets/framework.dart:5018:5)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#9      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6202:14)
#10     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#11     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6202:14)
#12     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#14     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#15     StatelessElement.update (package:flutter/src/widgets/framework.dart:4746:5)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#18     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#19     ProxyElement.update (package:flutter/src/widgets/framework.dart:5020:5)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#22     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#23     ProxyElement.update (package:flutter/src/widgets/framework.dart:5020:5)
#24     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#25     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5700:32)
#26     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6356:17)
#27     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#29     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#30     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#31     StatefulElement.update (package:flutter/src/widgets/framework.dart:4872:5)
#32     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#34     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#35     ProxyElement.update (package:flutter/src/widgets/framework.dart:5020:5)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#38     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#39     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#40     StatefulElement.update (package:flutter/src/widgets/framework.dart:4872:5)
#41     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#42     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6202:14)
#43     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#45     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#46     StatelessElement.update (package:flutter/src/widgets/framework.dart:4746:5)
#47     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#48     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6202:14)
#49     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#51     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#52     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#53     StatefulElement.update (package:flutter/src/widgets/framework.dart:4872:5)
#54     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#56     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#57     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#58     StatefulElement.update (package:flutter/src/widgets/framework.dart:4872:5)
#59     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#61     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#62     ProxyElement.update (package:flutter/src/widgets/framework.dart:5020:5)
#63     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#64     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#65     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#66     StatelessElement.update (package:flutter/src/widgets/framework.dart:4746:5)
#67     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#69     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#70     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#71     StatefulElement.update (package:flutter/src/widgets/framework.dart:4872:5)
#72     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#74     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#75     ProxyElement.update (package:flutter/src/widgets/framework.dart:5020:5)
#76     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#77     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#78     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#79     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#80     StatefulElement.update (package:flutter/src/widgets/framework.dart:4872:5)
#81     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#82     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#83     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#84     StatelessElement.update (package:flutter/src/widgets/framework.dart:4746:5)
#85     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#86     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6202:14)
#87     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#89     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#90     StatelessElement.update (package:flutter/src/widgets/framework.dart:4746:5)
#91     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#92     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6202:14)
#93     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#94     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6202:14)
#95     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#96     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#97     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#98     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#99     StatefulElement.update (package:flutter/src/widgets/framework.dart:4872:5)
#100    Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#101    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6202:14)
#102    Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#103    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6202:14)
#104    Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#105    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#106    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#107    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#108    StatefulElement.update (package:flutter/src/widgets/framework.dart:4872:5)
#109    Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#110    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#111    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#112    StatelessElement.update (package:flutter/src/widgets/framework.dart:4746:5)
#113    Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#114    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#115    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#116    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#117    StatefulElement.update (package:flutter/src/widgets/framework.dart:4872:5)
#118    Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#119    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6202:14)
#120    Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#121    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6202:14)
#122    Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#123    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#124    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#125    ProxyElement.update (package:flutter/src/widgets/framework.dart:5020:5)
#126    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:181:11)
#127    Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#128    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6202:14)
#129    Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#130    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#131    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#132    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#133    StatefulElement.update (package:flutter/src/widgets/framework.dart:4872:5)
#134    Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#135    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#136    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#137    ProxyElement.update (package:flutter/src/widgets/framework.dart:5020:5)
#138    Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#139    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#140    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#141    ProxyElement.update (package:flutter/src/widgets/framework.dart:5020:5)
#142    Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#143    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#144    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#145    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#146    StatefulElement.update (package:flutter/src/widgets/framework.dart:4872:5)
#147    Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#148    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#149    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#150    StatelessElement.update (package:flutter/src/widgets/framework.dart:4746:5)
#151    Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#152    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#153    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#154    StatelessElement.update (package:flutter/src/widgets/framework.dart:4746:5)
#155    Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#156    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6202:14)
#157    Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#158    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#159    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#160    ProxyElement.update (package:flutter/src/widgets/framework.dart:5020:5)
#161    Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#162    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#163    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#164    ProxyElement.update (package:flutter/src/widgets/framework.dart:5020:5)
#165    Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#166    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#167    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#168    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#169    StatefulElement.update (package:flutter/src/widgets/framework.dart:4872:5)
#170    Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#171    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#172    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#173    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#174    StatefulElement.update (package:flutter/src/widgets/framework.dart:4872:5)
#175    Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#176    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#177    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#178    Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#179    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2620:33)
#180    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#181    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
#182    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
#183    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1080:9)
#184    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:863:7)
(elided 4 frames from class _RawReceivePortImpl, class _Timer, and dart:async-patch)
====================================================================================================

Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 5131 pos 14: '_dependents.isEmpty': is not true.

======== Exception caught by widgets library =======================================================
The following assertion was thrown building Overlay-[LabeledGlobalKey<OverlayState>#90485](state: OverlayState#cf2c9(entries: [OverlayEntry#22444(opaque: true; maintainState: false), OverlayEntry#fe4b3(opaque: false; maintainState: true)])):
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5131 pos 14: '_dependents.isEmpty': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  MaterialApp MaterialApp:file:///Users/user/Documents/Developer/medlog/lib/src/app.dart:59:12
When the exception was thrown, this was the stack: 
#2      InheritedElement.debugDeactivated.<anonymous closure> (package:flutter/src/widgets/framework.dart:5131:14)
#3      InheritedElement.debugDeactivated (package:flutter/src/widgets/framework.dart:5133:6)
#4      _InactiveElements._deactivateRecursively.<anonymous closure> (package:flutter/src/widgets/framework.dart:1905:15)
#5      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1907:6)
#6      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#7      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1903:13)
#8      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
#9      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1903:13)
#10     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#11     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1903:13)
#12     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
#13     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1903:13)
#14     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#15     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1903:13)
#16     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#17     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1903:13)
#18     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#19     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1903:13)
#20     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#21     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1903:13)
#22     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#23     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1903:13)
#24     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#25     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1903:13)
#26     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#27     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1903:13)
#28     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#29     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1903:13)
#30     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
#31     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1903:13)
#32     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#33     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1903:13)
#34     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
#35     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1903:13)
#36     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
#37     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1903:13)
#38     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#39     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1903:13)
#40     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
#41     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1903:13)
#42     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
#43     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1903:13)
#44     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#45     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1903:13)
#46     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#47     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1903:13)
#48     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#49     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1903:13)
#50     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
#51     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1903:13)
#52     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
#53     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1903:13)
#54     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#55     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1903:13)
#56     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
#57     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1903:13)
#58     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#59     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1903:13)
#60     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#61     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1903:13)
#62     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#63     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1903:13)
#64     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#65     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1903:13)
#66     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#67     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1903:13)
#68     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#69     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1903:13)
#70     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
#71     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1903:13)
#72     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#73     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1903:13)
#74     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#75     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1903:13)
#76     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#77     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1903:13)
#78     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#79     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1903:13)
#80     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#81     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1903:13)
#82     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
#83     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1903:13)
#84     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#85     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1903:13)
#86     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#87     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1903:13)
#88     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#89     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1903:13)
#90     _InactiveElements.add (package:flutter/src/widgets/framework.dart:1915:7)
#91     Element.deactivateChild (package:flutter/src/widgets/framework.dart:3709:30)
#92     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5793:11)
#93     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6356:17)
#94     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#95     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#96     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#97     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#98     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2620:33)
#99     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#100    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
#101    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
#102    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1080:9)
#103    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#107    _invoke (dart:ui/hooks.dart:166:10)
#108    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#109    _drawFrame (dart:ui/hooks.dart:129:31)
(elided 5 frames from class _AssertionError and dart:async)
====================================================================================================
```
</details>

The IntelliJ debugger - inspire being buggy sometimes, always marks the getter as the throwing instruction. But I really don't see a null check operator.
I cannot explain this issue.

**Comment by darshankawar** [comment]
@Hu1buerger 
Since the error log shows:

```
`The following assertion was thrown while applying parent data.:
Incorrect use of ParentDataWidget.

The ParentDataWidget Expanded(flex: 1) wants to apply ParentData of type FlexParentData to a RenderObject, which has been set up to accept ParentData of incompatible type BoxParentData.

Usually, this means that the Expanded widget has the wrong ancestor RenderObjectWidget. Typically, Expanded widgets are placed directly inside Flex widgets.
The offending Expanded is currently placed inside a Padding widget.`
```

Did you try to fix based on above message ?

If issue still persists, please provide a complete minimal reproducible code sample that shows the issue.
Thanks.

**Comment by darshankawar** [comment]
The log also shows below error:

```
`======== Exception caught by widgets library =======================================================
The following assertion was thrown building Overlay-[LabeledGlobalKey<OverlayState>#90485](state: OverlayState#cf2c9(entries: [OverlayEntry#22444(opaque: true; maintainState: false), OverlayEntry#fe4b3(opaque: false; maintainState: true)])):
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5131 pos 14: '_dependents.isEmpty': is not true.
`
```

Would be helpful if a minimal code sample is provided, so that we can address it properly.
