### ISSUE TITLE
Flutter crash report.

### ISSUE THREAD

**Issue by ajbgdj** [flutter/flutter#91565]
## command

flutter run

## exception

```
RPCError: ext.flutter.debugDumpRenderTree: (-32603) ext.flutter.debugDumpRenderTree: Unexpected error from chrome devtools:
text: Uncaught (in promise)
exception:
  description: null
  type: string
  value: Unexpected null value.
attempted JS eval: `require("dart_sdk").developer.invokeExtension(
    "ext.flutter.debugDumpRenderTree", JSON.stringify({}));
`

#0      handleErrorIfPresent (package:dwds/src/utilities/shared.dart:56:5)
#1      ChromeProxyService.callServiceExtension (package:dwds/src/services/chrome_proxy_service.dart:353:5)
<asynchronous suspension>
#2      VmServerConnection._delegateRequest (package:vm_service/src/vm_service.dart:1592:24)
<asynchronous suspension>

#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1626:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2109:21)
#2      VmService.callServiceExtension (package:vm_service/src/vm_service.dart:2080:14)
#3      FlutterVmService._checkedCallServiceExtension (package:flutter_tools/src/vmservice.dart:773:28)
#4      FlutterVmService.invokeFlutterExtensionRpcRaw (package:flutter_tools/src/vmservice.dart:792:48)
#5      FlutterVmService.flutterDebugDumpRenderTree (package:flutter_tools/src/vmservice.dart:554:48)
#6      ResidentHandlers.debugDumpRenderTree (package:flutter_tools/src/resident_runner.dart:661:52)
<asynchronous suspension>
#7      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1659:7)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel stable, 2.5.2, on Manjaro Linux 5.14.7-2-MANJARO, locale pt_BR.UTF-8)
    • Flutter version 2.5.2 at /home/ajbg/.programas/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (7 days ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/ajbg/.programas/android-sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /home/ajbg/.programas/android-sdk
    • Java binary at: /home/ajbg/.programas/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/ajbg/.programas/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 94.0.4606.81

• No issues found!
```

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
