### ISSUE TITLE
TextField is looking for a ticker and can't find it...

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#9158]
```
[00034.730] 02493.02530> The following NoSuchMethodError was thrown while handling a gesture:
[00034.730] 02493.02530> The method 'createTicker' was called on null.
[00034.730] 02493.02530> Receiver: null
[00034.730] 02493.02530> Tried calling: createTicker(Closure: (Duration) => void from Function '_tick@58066280':.)
[00034.730] 02493.02530> 
[00034.730] 02493.02530> When the exception was thrown, this was the stack:
[00034.734] 02493.02530> #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
[00034.734] 02493.02530> #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
[00034.734] 02493.02530> #2      AnimationController.AnimationController (package:flutter/src/animation/animation_controller.dart:93)
[00034.734] 02493.02530> #3      TextSelectionOverlay.TextSelectionOverlay (package:flutter/src/widgets/text_selection.dart:103)
[00034.734] 02493.02530> #4      EditableTextState._handleSelectionChanged (package:flutter/src/widgets/editable_text.dart:334)
[00034.735] 02493.02530> #5      RenderEditable._handleTap (package:flutter/src/rendering/editable.dart:329)
[00034.735] 02493.02530> #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:65)
[00034.735] 02493.02530> #7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:148)
[00034.735] 02493.02530> #8      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:119)
[00034.735] 02493.02530> #9      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:119)
[00034.735] 02493.02530> #10     BindingBase&SchedulerBinding&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:126)
[00034.735] 02493.02530> #11     BindingBase&SchedulerBinding&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:100)
[00034.735] 02493.02530> #12     BindingBase&SchedulerBinding&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:81)
[00034.735] 02493.02530> #13     BindingBase&SchedulerBinding&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:40)
[00034.735] 02493.02530> #14     BindingBase&SchedulerBinding&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:33)
[00034.735] 02493.02530> #15     _dispatchPointerDataPacket (~/fuchsia/flutter/lib/ui/hooks.dart:73)
[00034.735] 02493.02530> 
```

**Comment by apwilson** [comment]
Hmm, looks like a TextField needs to be a child of an Overlay?

**Comment by abarth** [comment]
Yes, it needs an overlay.

**Comment by Hixie** [comment]
We should also have it assert that wants an Overlay if that's really the cause of that exception. The current failure mode is absurd and horrible.

**Comment by apwilson** [comment]
It does assert.  I was running in release mode though so I didn't hit the assert.

**Comment by eseidelGoogle** [comment]
Sounds like we're keeping this to provide a better failure mode in the Framework?

**Comment by Hixie** [comment]
If you were running in release mode I don't think there's much we can do to help you.
