### ISSUE TITLE
[tool_crash] OSError: OS Error: Operation not supported on socket, errno = 102

### ISSUE THREAD

**Issue by wedersonrsouza** [flutter/flutter#91714]
## Command
```
flutter attach --machine -d 97562573-4A7D-4860-A93F-8B4F8F90BD51 --devtools-server-address http://127.0.0.1:9100/
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
OSError: OS Error: Operation not supported on socket, errno = 102
```
#0      _NativeSocket.nativeSetRawOption (dart:io-patch/socket_patch.dart:1564:35)
#1      _NativeSocket.setRawOption (dart:io-patch/socket_patch.dart:1485:5)
#2      _RawDatagramSocket.setRawOption (dart:io-patch/socket_patch.dart:2379:56)
#3      MDnsClient.start (package:multicast_dns/multicast_dns.dart:138:16)
<asynchronous suspension>
#4      MDnsObservatoryDiscovery.query (package:flutter_tools/src/mdns_discovery.dart:66:7)
<asynchronous suspension>
#5      MDnsObservatoryDiscovery.getObservatoryUri (package:flutter_tools/src/mdns_discovery.dart:153:51)
<asynchronous suspension>
#6      AttachCommand._attachToDevice (package:flutter_tools/src/commands/attach.dart:271:11)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#8      AttachCommand.runCommand (package:flutter_tools/src/commands/attach.dart:220:5)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.5.2, on macOS 11.6 20G165 darwin-x64, locale en-US)
    • Flutter version 2.5.2 at /Users/wederson/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (12 days ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/wederson/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.61.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (2 available)
    • iPhone 13 Pro Max (mobile) • 97562573-4A7D-4860-A93F-8B4F8F90BD51 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 94.0.4606.81

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.1+13
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: b1395592de68cc8ac4522094ae59956dd21a91db
### Plugins
flutter_plugin_android_lifecycle-2.0.2
google_mobile_ads-0.13.4
image_cropper-1.4.1
image_picker-0.8.3+1
image_picker_for_web-2.1.2
onesignal_flutter-3.2.3
package_info_plus-1.0.6
package_info_plus_macos-1.1.1
package_info_plus_web-1.0.4
path_provider-2.0.2
path_provider_linux-2.0.2
path_provider_macos-2.0.2
path_provider_windows-2.0.3
purchases_flutter-3.4.3
sentry_flutter-6.0.0
shared_preferences-2.0.6
shared_preferences_linux-2.0.2
shared_preferences_macos-2.0.2
shared_preferences_web-2.0.1
shared_preferences_windows-2.0.2
sqflite-2.0.0+3
uni_links-0.5.1
uni_links_web-0.1.0

**Comment by maheshmnj** [comment]
Hi @wedersonrsouza Thanks for filing the issue. Please share the complete logs by running the same command with a verbose flag 

```
flutter attach --machine -d 97562573-4A7D-4860-A93F-8B4F8F90BD51 --devtools-server-address http://127.0.0.1:9100/ -v
```

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
