### ISSUE TITLE
StreamBuilder calls `setState()` after `dispose()`

### ISSUE THREAD

**Issue by rbellens** [flutter/flutter#91814]
Certain `StreamSubscriptions` may call the `onDone` callback after `cancel` has been called. I am not sure if this is a bug in dart or if this is actually allowed (the documentation of `StreamSubscription.cancel` says "After this call, the subscription no longer receives events.", but does that mean as soon as `cancel` is called or only after the future it returns is completed). 
Anyway, as a result, the `setState` on a `StreamBuilder`, might get called after  `dispose` is called.

## Steps to Reproduce

A broadcast stream controller that is already closed or a stream on which you call `.take(0)` will return a `_DoneStreamSubscription`. This stream subscription might call the `onDone` callback even after `cancel` is called. Not sure if there are maybe other types of stream subscriptions with the same behavior.

<details>
<summary>Code sample</summary>

This code reproduces the issue

```dart
void main() async {
  var value = ValueNotifier(true);

  runZoned(() {
    runApp(ValueListenableBuilder(
        valueListenable: value,
        builder: (context, v, child) {
          if (v) {
            return StreamBuilder(
              stream: Stream.value(null).take(0),
              builder: (context, snapshot) {
                SchedulerBinding.instance.addPostFrameCallback((v) {
                  value.value = false;
                });
                return Container(color: Colors.red);
              },
            );
          }
          return Container(color: Colors.blue);
        }));
  }, zoneSpecification:
      ZoneSpecification(scheduleMicrotask: (self, parent, zone, f) {
    if (StackTrace.current.toString().contains('_DoneStreamSubscription')) {
      // as the problem only happens when microtasks are executed in a specific order, we similate it here by delaying the execution of the onDone callback
      Future.delayed(Duration(milliseconds: 1000)).then((_) { 
        parent.scheduleMicrotask(zone, f);
      });
    } else {
      parent.scheduleMicrotask(zone, f);
    }
  }));
}
```

</details>

<details>
  <summary>Logs</summary>

This throws the following error:

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: setState() called after dispose(): _StreamBuilderBaseState<Null, AsyncSnapshot<Null>>#4aa5c(lifecycle state: defunct, not mounted)
This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
#0      State.setState.<anonymous closure>
package:flutter/…/widgets/framework.dart:1052
#1      State.setState
package:flutter/…/widgets/framework.dart:1087
#2      _StreamBuilderBaseState._subscribe.<anonymous closure>
package:flutter/…/widgets/async.dart:143
#3      _rootRun (dart:async/zone.dart:1420:47)
#4      _CustomZone.run (dart:async/zone.dart:1328:19)
#5      _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#6      _DoneStreamSubscription._sendDone (dart:async/stream_impl.dart:785:36)
#7      _rootRun (dart:async/zone.dart:1428:13)
#8      _CustomZone.run (dart:async/zone.dart:1328:19)
#9      _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#10     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
#11     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
````

Output of `flutter doctor -v`

```
[✓] Flutter (Channel stable, 2.5.2, on macOS 11.5.2 20G95 darwin-arm, locale nl-BE)
    • Flutter version 2.5.2 at /Users/rikbellens/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (2 weeks ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/rikbellens/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] VS Code (version 1.62.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.5.2 20G95 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 94.0.4606.81

• No issues found!
```

</details>

**Comment by tirth-patel-nc** [comment]
# Triage Report

I was **not** able to reproduce the issue using the provided code sample on either the `stable (3.29.3)` or `master (3.32.0-1.0.pre.514)` channels.

Since no logs or exceptions were produced during testing, I'm closing this issue.

<details>
<summary>Code Sample (Same as OP)</summary>

```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter/scheduler.dart';

void main() async {
  var value = ValueNotifier(true);

  runZoned(
    () {
      runApp(
        ValueListenableBuilder<bool>(
          valueListenable: value,
          builder: (context, v, child) {
            if (v) {
              return StreamBuilder(
                stream: Stream.value(null).take(0),
                builder: (context, snapshot) {
                  SchedulerBinding.instance.addPostFrameCallback((v) {
                    value.value = false;
                  });
                  return Container(color: Colors.red);
                },
              );
            }
            return Container(color: Colors.blue);
          },
        ),
      );
    },
    zoneSpecification: ZoneSpecification(
      scheduleMicrotask: (self, parent, zone, f) {
        if (StackTrace.current.toString().contains('_DoneStreamSubscription')) {
          // as the problem only happens when microtasks are executed in a specific order, we similate it here by delaying the execution of the onDone callback
          Future.delayed(const Duration(milliseconds: 1000)).then((_) {
            parent.scheduleMicrotask(zone, f);
          });
        } else {
          parent.scheduleMicrotask(zone, f);
        }
      },
    ),
  );
}
```

</details>

<details>
  <summary>stable (3.29.3) - flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.29.3, on macOS 15.4.1 24E263 darwin-arm64, locale
    en-IN) [970ms]
    • Flutter version 3.29.3 on channel stable at
      /Users/tirthpatel/Development/flutter_stable/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ea121f8859 (4 weeks ago), 2025-04-11 19:10:07 +0000
    • Engine revision cf56914b32
    • Dart version 3.7.2
    • DevTools version 2.42.3

[✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0)
    [855ms]
    • Android SDK at /Users/tirthpatel/Library/Android/sdk
    • Platform android-36, build-tools 36.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on
      this machine.
      To manually set the JDK path, use: `flutter config
      --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13355223-b631.42)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.3) [556ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16E140
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [9ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.3) [9ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13355223-b631.42)

[✓] VS Code (version 1.99.3) [8ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available) [5.5s]
    • macOS (desktop)                 • macos                 • darwin-arm64   •
      macOS 15.4.1 24E263 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         •
      macOS 15.4.1 24E263 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript •
      Google Chrome 135.0.7049.115

[✓] Network resources [559ms]
    • All expected network resources are available.

• No issues found!
```

</details>

<details>
  <summary>master (3.32.0-1.0.pre.514) - flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 3.32.0-1.0.pre.514, on macOS 15.4.1 24E263 darwin-arm64, locale en-IN) [1,266ms]
    • Flutter version 3.32.0-1.0.pre.514 on channel master at /Users/tirthpatel/Development/flutter_master/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 149ac49583 (3 hours ago), 2025-05-12 22:41:39 -0400
    • Engine revision 149ac49583
    • Dart version 3.9.0 (build 3.9.0-114.0.dev)
    • DevTools version 2.46.0

[✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0) [784ms]
    • Android SDK at /Users/tirthpatel/Library/Android/sdk
    • Emulator version 35.4.9.0 (build_id 13025442) (CL:N/A)
    • Platform android-36, build-tools 36.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13355223-b631.42)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.3) [434ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16E140
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [7ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.3) [7ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13355223-b631.42)

[✓] VS Code (version 1.100.0) [6ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.110.0

[✓] Connected device (2 available) [5.6s]
    • macOS (desktop) • macos  • darwin-arm64   • macOS 15.4.1 24E263 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 136.0.7103.93

[✓] Network resources [553ms]
    • All expected network resources are available.

• No issues found!
```

</details>
