### ISSUE TITLE
Luci status handler failing with http status 500

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#91825]
```
RangeError (millisecondsSinceEpoch): Invalid value: Not in inclusive range -8640000000000000..8640000000000000: -62135596800000000
#0      RangeError.checkValueInInterval (dart:core/errors.dart:282:7)
#1      DateTime._validateMilliseconds (dart:core-patch/date_patch.dart:63:18)
#2      new DateTime.fromMillisecondsSinceEpoch (dart:core-patch/date_patch.dart:42:13)
#3      MillisecondsSinceEpochConverter.fromJson (package:cocoon_service/src/model/common/json_converters.dart:98:21)
#4      _$BuildFromJson (package:cocoon_service/src/model/luci/push_message.g.dart:92:71)
#5      Build.fromJson (package:cocoon_service/src/model/luci/push_message.dart:128:55)
#6      _$BuildPushMessageFromJson (package:cocoon_service/src/model/luci/push_message.g.dart:54:51)
#7      BuildPushMessage.fromJson (package:cocoon_service/src/model/luci/push_message.dart:84:66)
#8      LuciStatusHandler.post (package:cocoon_service/src/request_handlers/luci_status.dart:66:64)
<asynchronous suspension>
#9      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:49:22)
<asynchronous suspension>
#10     main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:254:9)
<asynchronous suspension>
```

**Comment by CaseyHillers** [comment]
As a quick action, I rolled back to yesterday's version. I suspect this is an upstream issue. The current impact is it's blocking presubmit tests in flutter

**Comment by CaseyHillers** [comment]
Errors have subsided, but I'm going to roll forward to today's version. I'm unable to find any differences in the Cocoon codebase that would have caused this.

**Comment by godofredoc** [comment]
This is now failing consistently, more context:

Pubsub message has an invalid  timestamps in status_changed_ts
```
{"build": {"bucket": "luci.flutter.try", "canary": false, "canary_preference": "PROD", "created_by": "user:flutter-dashboard@appspot.gserviceaccount.com", "created_ts": "1634615299259058", "experimental": false, "id": "8832975343922909681", "parameters_json": "{\"builder_name\": \"Linux Web Engine\", \"properties\": {\"git_ref\": \"refs/pull/29237/head\", \"git_url\": \"https://github.com/flutter/engine\"}}", "project": "flutter", "result_details_json": "{\"properties\": {}}", "retry_of": "0", "service_account": "flutter-try-builder@chops-service-accounts.iam.gserviceaccount.com", "started_ts": "1634615316415275", "status": "STARTED", "status_changed_ts": "-62135596800000000", "tags": ["build_address:luci.flutter.try/Linux Web Engine/20646", "builder:Linux Web Engine", "buildset:pr/git/29237", "buildset:sha/git/0312b81bb97f5697f0bbb25da03538e7462544a3", "github_checkrun:3934606375", "github_link:https://github.com/flutter/engine/pull/29237", "swarming_hostname:chromium-swarm.appspot.com", "swarming_tag:log_location:logdog://logs.chromium.org/flutter/buildbucket/cr-buildbucket/8832975343922909681/+/annotations", "swarming_tag:luci_project:flutter", "swarming_tag:recipe_name:web_engine", "swarming_tag:recipe_package:flutter/recipe_bundles/flutter.googlesource.com/recipes", "swarming_task_id:56af7b9a66dd6410", "user_agent:flutter-cocoon"], "updated_ts": "1634615316415470", "url": "https://ci.chromium.org/b/8832975343922909681", "utcnow_ts": "1634615316665540"}, "hostname": "cr-buildbucket.appspot.com", "user_data": "{\"repo_owner\":\"flutter\",\"repo_name\":\"engine\",\"user_agent\":\"flutter-cocoon\",\"check_run_id\":3934606375}"}```

**Comment by godofredoc** [comment]
For context this started happening on: 2021-10-14 10:30:27.476 PDT
