### ISSUE TITLE
"Connection closed before test suite loaded." when running unit tests

### ISSUE THREAD

**Issue by casvanluijtelaar** [flutter/flutter#91895]
I'm running into an issue when attempting to run a test file. seems similar to https://github.com/flutter/flutter/issues/16398 but on a personal flutter app instead of the framework. 

``` powershell
flutter test -v .\test\features\device_list\repository\device_list_repository_impl_test.dart
[ +112 ms] executing: [D:\Android\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +818 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 3595343e20a61ff16d14e8ecc25f364276bb1b8b
[   +1 ms] executing: [D:\Android\flutter/] git tag --points-at 3595343e20a61ff16d14e8ecc25f364276bb1b8b
[ +138 ms] Exit code 0 from: git tag --points-at 3595343e20a61ff16d14e8ecc25f364276bb1b8b
[   +1 ms] 2.5.2
[  +13 ms] executing: [D:\Android\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +69 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [D:\Android\flutter/] git ls-remote --get-url origin
[  +63 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +178 ms] executing: [D:\Android\flutter/] git rev-parse --abbrev-ref HEAD
[  +66 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +72 ms] Found 1 files which will be executed as Widget Tests.
[  +11 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +8 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +76 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +77 ms] Skipping pub get: version match.
[  +47 ms] Found plugin bitsdojo_window at C:\Users\casva\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\bitsdojo_window-0.1.1+1\
[   +6 ms] Found plugin bitsdojo_window_linux at C:\Users\casva\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\bitsdojo_window_linux-0.1.1\
[   +3 ms] Found plugin bitsdojo_window_macos at C:\Users\casva\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\bitsdojo_window_macos-0.1.0\
[   +6 ms] Found plugin bitsdojo_window_windows at C:\Users\casva\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\bitsdojo_window_windows-0.1.0\
[  +74 ms] Found plugin path_provider at C:\Users\casva\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider-2.0.5\
[   +3 ms] Found plugin path_provider_linux at C:\Users\casva\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_linux-2.1.0\
[   +2 ms] Found plugin path_provider_macos at C:\Users\casva\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_macos-2.0.2\
[   +3 ms] Found plugin path_provider_windows at C:\Users\casva\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_windows-2.0.3\
[  +30 ms] Found plugin url_launcher at C:\Users\casva\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher-6.0.12\
[   +2 ms] Found plugin url_launcher_linux at C:\Users\casva\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_linux-2.0.2\
[   +1 ms] Found plugin url_launcher_macos at C:\Users\casva\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_macos-2.0.2\
[   +2 ms] Found plugin url_launcher_web at C:\Users\casva\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_web-2.0.4\
[   +2 ms] Found plugin url_launcher_windows at C:\Users\casva\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_windows-2.0.2\
[   +7 ms] Found plugin webview_flutter at C:\Users\casva\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\webview_flutter-2.0.14\
[ +217 ms] Found plugin bitsdojo_window at C:\Users\casva\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\bitsdojo_window-0.1.1+1\
[   +3 ms] Found plugin bitsdojo_window_linux at C:\Users\casva\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\bitsdojo_window_linux-0.1.1\
[   +2 ms] Found plugin bitsdojo_window_macos at C:\Users\casva\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\bitsdojo_window_macos-0.1.0\
[   +3 ms] Found plugin bitsdojo_window_windows at C:\Users\casva\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\bitsdojo_window_windows-0.1.0\
[  +50 ms] Found plugin path_provider at C:\Users\casva\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider-2.0.5\
[   +5 ms] Found plugin path_provider_linux at C:\Users\casva\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_linux-2.1.0\
[   +2 ms] Found plugin path_provider_macos at C:\Users\casva\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_macos-2.0.2\
[   +2 ms] Found plugin path_provider_windows at C:\Users\casva\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_windows-2.0.3\
[  +21 ms] Found plugin url_launcher at C:\Users\casva\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher-6.0.12\
[   +2 ms] Found plugin url_launcher_linux at C:\Users\casva\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_linux-2.0.2\
[   +2 ms] Found plugin url_launcher_macos at C:\Users\casva\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_macos-2.0.2\
[   +3 ms] Found plugin url_launcher_web at C:\Users\casva\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_web-2.0.4\
[   +1 ms] Found plugin url_launcher_windows at C:\Users\casva\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_windows-2.0.2\
[   +5 ms] Found plugin webview_flutter at C:\Users\casva\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\webview_flutter-2.0.14\
[  +21 ms] Generating D:\werk\wled_app\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +285 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
[  +14 ms] running test package with arguments: [-r, compact, --timeout, 30s, --concurrency=2, --chain-stack-traces, --,
D:\werk\wled_app\test\features\device_list\repository\device_list_repository_impl_test.dart]
00:00 +0: loading D:\werk\wled_app\test\features\device_list\repository\device_list_repository_impl_test.dart                                                                      [ +277 ms] test 0: starting test D:\werk\wled_app\test\features\device_list\repository\device_list_repository_impl_test.dart
[  +23 ms] Stopping scan for flutter_test_config.dart; found project root at D:\werk\wled_app
[   +6 ms] Compiler will use the following file as its incremental dill file: C:\Users\casva\AppData\Local\Temp\flutter_tools.7eada4f6\flutter_test_compiler.47a0db67\output.dill
[        ] Listening to compiler controller...
[  +16 ms] Compiling file:///C:/Users/casva/AppData/Local/Temp/flutter_tools.7eada4f6/flutter_test_listener.3e55ae51/listener.dart
[  +16 ms] D:\Android\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev D:\Android\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
D:\Android\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --no-print-incremental-dependencies --target=flutter --debugger-module-names
--experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill C:\Users\casva\AppData\Local\Temp\flutter_tools.7eada4f6\flutter_test_compiler.47a0db67\output.dill 
--packages D:\werk\wled_app\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --initialize-from-dill
D:\werk\wled_app\build\test_cache\build\c075001b96339384a97db4862b8ab8db.cache.dill.track.dill
[  +91 ms] <- compile file:///D:/werk/wled_app/.dart_tool/flutter_build/generated_main.dart
00:02 +0: loading D:\werk\wled_app\test\features\device_list\repository\device_list_repository_impl_test.dart                                                                      [+2330 ms] <- accept
[   +2 ms] <- reset
[   +1 ms] Compiling file:///C:/Users/casva/AppData/Local/Temp/flutter_tools.7eada4f6/flutter_test_listener.3e55ae51/listener.dart took 2441ms
[   +1 ms] test 0: starting test device
[   +9 ms] test 0: awaiting connection to test device
[   +5 ms] test 0: Observatory uri is not available
[  +10 ms] test 0: test harness socket server is running at port:54958
[  +17 ms] Using this directory for fonts configuration: C:\Users\casva\AppData\Local\Temp\flutter_tools.7eada4f6\flutter_test_fonts.2c967f2b
[  +23 ms] test 0: Starting flutter_tester process with command=[D:\Android\flutter\bin\cache\artifacts\engine\windows-x64\flutter_tester.exe, --disable-observatory,
--enable-checked-mode, --verify-entry-points, --enable-software-rendering, --skia-deterministic-rendering, --enable-dart-profiling, --non-interactive, --use-test-fonts,
--packages=D:\werk\wled_app\.dart_tool\package_config.json, C:\Users\casva\AppData\Local\Temp\flutter_tools.7eada4f6\flutter_test_listener.3e55ae51\listener.dart.dill],
environment={FLUTTER_TEST: true, FONTCONFIG_FILE: C:\Users\casva\AppData\Local\Temp\flutter_tools.7eada4f6\flutter_test_fonts.2c967f2b/fonts.conf, SERVER_PORT: 54958, APP_NAME:    
wled, UNIT_TEST_ASSETS: D:\werk\wled_app\build\unit_test_assets}
[  +37 ms] test 0: Started flutter_tester process at pid 15088
00:03 +0: loading D:\werk\wled_app\test\features\device_list\repository\device_list_repository_impl_test.dart                                                                      [ +556 ms] test 0: flutter_tester process at pid 15088 exited with code=0
[   +1 ms] test 0: cleaning up...
[   +1 ms] test 0: ensuring test device is terminated.
[   +1 ms] test 0: Terminating flutter_tester process
[   +1 ms] test 0: Shutting down test harness socket server
[   +3 ms] test 0: deleting temporary directory
[   +8 ms] test 0: waiting for controller sink to close
[   +3 ms] test 0: finished
00:03 +0 -1: loading D:\werk\wled_app\test\features\device_list\repository\device_list_repository_impl_test.dart [E]
  Failed to load "D:\werk\wled_app\test\features\device_list\repository\device_list_repository_impl_test.dart": Connection closed before test suite loaded.
00:03 +0 -1: Some tests failed.
[  +26 ms] Deleting C:\Users\casva\AppData\Local\Temp\flutter_tools.7eada4f6\flutter_test_compiler.47a0db67...
[   +6 ms] killing pid 636
[  +53 ms] Deleting C:\Users\casva\AppData\Local\Temp\flutter_tools.7eada4f6\flutter_test_fonts.2c967f2b...
[   +4 ms] test package returned with exit code 1
[  +13 ms] "flutter test" took 4,606ms.
[   +7 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      TestCommand.runCommand (package:flutter_tools/src/commands/test.dart:468:7)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>


[  +88 ms] ensureAnalyticsSent: 78ms
[   +2 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1
```

<details>
<summary>pubspec and doctor</summary>

``` yaml
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_route: ^2.3.0
  bitsdojo_window: ^0.1.1+1
  bloc: ^7.2.0
  bloc_concurrency: ^0.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  flutter_feather_icons: ^2.0.0+1
  flutter_localizations:
    sdk: flutter
  formz: ^0.4.0
  freezed_annotation: ^0.14.3
  get_it: ^7.2.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  http: ^0.13.3
  injectable: ^1.5.0
  json_annotation: ^4.1.0
  multicast_dns: ^0.3.1
  rive: ^0.7.28
  rxdart: ^0.27.2
  tutorial_coach_mark: ^1.1.1
  url_launcher: ^6.0.12
  webview_flutter: ^2.0.14
  xml: ^5.1.0

dev_dependencies:
  auto_route_generator: ^2.3.0
  build_runner: ^2.1.2
  flutter_app_name: ^0.1.0
  flutter_launcher_icons: 
    git: https://github.com/dirkbo/flutter_launcher_icons.git
  flutter_native_splash: ^1.2.3
  flutter_test:
    sdk: flutter
  freezed: 
    git:
      url: https://github.com/casvanluijtelaar/freezed.git
      path: packages/freezed
  hive_generator: ^1.1.1
  injectable_generator: ^1.5.1
  json_serializable: ^5.0.2
  mocktail: ^0.2.0
  very_good_analysis: ^2.3.0

dependency_overrides:
  meta: ^1.7.0
```

``` powershell
   [√] Flutter (Channel stable, 2.5.2, on Microsoft Windows [Version 10.0.19043.1266], locale en-GB)
      • Flutter version 2.5.2 at D:\Android\flutter
      • Upstream repository https://github.com/flutter/flutter.git
      • Framework revision 3595343e20 (2 weeks ago), 2021-09-30 12:58:18 -0700
      • Engine revision 6ac856380f
      • Dart version 2.14.3
  
  [√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
      • Android SDK at D:\Android\
      • Platform android-30, build-tools 29.0.2
      • ANDROID_HOME = D:\Android
      • Java binary at: D:\Android\openjdk\bin\java
      • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_202-b08)
      • All Android licenses accepted.
  
  [√] Chrome - develop for the web
      • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe
  
  [√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.2)
      • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
      • Visual Studio Build Tools 2019 version 16.11.31624.102
      • Windows 10 SDK version 10.0.19041.0
  
  [!] Android Studio (not installed)
      • Android Studio not found; download from https://developer.android.com/studio/index.html
        (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
  
  [√] Connected device (4 available)
      • GM1925 (mobile)   • 686db41d • android-arm64  • Android 10 (API 29)
      • Windows (desktop) • windows  • windows-x64    • Microsoft Windows [Version 10.0.19043.1266]
      • Chrome (web)      • chrome   • web-javascript • Google Chrome 94.0.4606.71
      • Edge (web)        • edge     • web-javascript • Microsoft Edge 94.0.992.31
  
  ! Doctor found issues in 1 category.
```
</details>

**Comment by danagbemava-nc** [comment]
Hi @casvanluijtelaar, please provide a complete minimal reproducible code sample.

Thank you

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
