### ISSUE TITLE
Can make the Date and time pickers demo (and text field demo) get stuck scrolled up

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#9221]
To repro:

Open gallery, open Date and time pickers. (or, the Text fields demo)

* Put cursor into "Event name"
* Scroll up, placing finger into the demo (NOT the keyboard)
* Lift finger

Expected: Not entirely sure, but I don't expect the screen to not be able to scroll back down.

Actual: keyboard disappears, can't scroll the screen vertically.

Here's how the screen gets stuck, after I lift my finger from the scroll, and after the keyboard disappears.

![screenshot_20170405-105949](https://cloud.githubusercontent.com/assets/5479/24719671/6edfc676-19ef-11e7-8ae1-d6443ec3d364.png)

**Comment by sethladd** [comment]
cc @abarth not sure if this is related to the new keyboard work?

cc @cbracken

**Comment by cbracken** [comment]
Unlikely to be related to the keyboard work; the only bits landed so far have been related to string encoding. I've seen overscrolls get stuck on iOS (#8476) but this looks like Android.

**Comment by sethladd** [comment]
Correct, this is Android.

**Comment by eseidelGoogle** [comment]
Seth believes this should block an updated release of the gallery.  The next build is slated to being release verification next week, so we'd need to fix this by then.

**Comment by sethladd** [comment]
This behavior does not trigger on the version of the Gallery in the Play Store.

**Comment by eseidelGoogle** [comment]
As a workaround for M2 we could turn off scrolling for this demo?  @HansMuller maybe could do that?

**Comment by eseidelGoogle** [comment]
My understanding is this needs to be resolved this week to make our Gallery release.

**Comment by HansMuller** [comment]
Turning off scrolling would prevent the demo from working as-is in landscape mode.

Interacting with the demo causes lots of debug messages and some exceptions.

```
E/SpannableStringBuilder(  856): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder(  856): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder(  856): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder(  856): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
W/IInputConnectionWrapper(  856): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(  856): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(  856): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper(  856): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(  856): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(  856): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(  856): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(  856): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper(  856): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(  856): endBatchEdit on inactive InputConnection
E/SpannableStringBuilder(  856): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder(  856): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder(  856): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder(  856): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder(  856): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder(  856): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder(  856): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder(  856): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
I/flutter (  856): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (  856): The following assertion was thrown during performLayout():
I/flutter (  856): SliverGeometry has a layoutExtent that exceeds its paintExtent.
I/flutter (  856): The paintExtent is 437.65200913114626, but the layoutExtent is 437.6520091311463. Maybe you have
I/flutter (  856): fallen prey to floating point rounding errors, and should explicitly apply the min() or max()
I/flutter (  856): functions, or the clamp() method, to the layoutExtent?
I/flutter (  856): When the exception was thrown, this was the stack:
I/flutter (  856): #0      SliverGeometry.debugAssertIsValid.<anonymous closure> (package:flutter/src/rendering/sliver.dart:539)
I/flutter (  856): #2      SliverGeometry.debugAssertIsValid (package:flutter/src/rendering/sliver.dart:537)
I/flutter (  856): #3      RenderSliver.debugAssertDoesMeetConstraints (package:flutter/src/rendering/sliver.dart:798)
I/flutter (  856): #4      RenderObject.layout.<anonymous closure> (package:flutter/src/rendering/object.dart:1833)
I/flutter (  856): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1833)
I/flutter (  856): #7      RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:182)
I/flutter (  856): #8      RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:792)
I/flutter (  856): #9      RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:716)
I/flutter (  856): #10     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1707)
I/flutter (  856): #11     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1030)
I/flutter (  856): #12     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding.beginFrame (package:flutter/src/rendering/binding.dart:225)
I/flutter (  856): #13     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.beginFrame (package:flutter/src/widgets/binding.dart:354)
I/flutter (  856): #14     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:170)
I/flutter (  856): #15     BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:645)
I/flutter (  856): #16     BindingBase&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:580)
I/flutter (  856): #17     _beginFrame (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:83)
I/flutter (  856): (elided 2 frames from class _AssertionError)
I/flutter (  856): The following RenderObject was being processed when the exception was fired:
I/flutter (  856):   RenderSliverPadding#144713131 relayoutBoundary=up1
I/flutter (  856):   creator: SliverPadding ← Viewport ← _ScrollableScope ← IgnorePointer-[GlobalKey#112001875] ←
I/flutter (  856):   Listener ← _GestureSemantics ←
I/flutter (  856):   RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#215526897] ← RepaintBoundary ←
I/flutter (  856):   CustomPaint ← RepaintBoundary ← NotificationListener<ScrollNotification> ←
I/flutter (  856):   GlowingOverscrollIndicator ← ⋯
I/flutter (  856):   parentData: paintOffset=Offset(0.0, 0.0)
I/flutter (  856):   constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle,
I/flutter (  856):   scrollOffset: 0.3, remainingPaintExtent: 511.0, crossAxisExtent: 360.0, viewportMainAxisExtent:
I/flutter (  856):   511.0)
I/flutter (  856):   geometry: SliverGeometry(scrollExtent: 438.0, paintExtent: 437.7, layoutExtent: 437.7,
I/flutter (  856):   maxPaintExtent: 438.0, hitTestExtent: 437.7, scrollOffsetCorrection: 0.0)
I/flutter (  856): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (  856):   RenderSliverList#103797371 relayoutBoundary=up2
I/flutter (  856):     RenderRepaintBoundary#125866034 relayoutBoundary=up3
I/flutter (  856):       RenderSemanticsGestureHandler#142540573 relayoutBoundary=up4
I/flutter (  856):         RenderPointerListener#633400085 relayoutBoundary=up5
I/flutter (  856):           RenderConstrainedBox#867365586 relayoutBoundary=up6
I/flutter (  856):     RenderRepaintBoundary#746828210 relayoutBoundary=up3
I/flutter (  856):       RenderSemanticsGestureHandler#87603060 relayoutBoundary=up4
I/flutter (  856):         RenderPointerListener#1002829340 relayoutBoundary=up5
I/flutter (  856):           RenderConstrainedBox#145933795 relayoutBoundary=up6
I/flutter (  856):     RenderRepaintBoundary#1042487839 relayoutBoundary=up3
I/flutter (  856):       RenderFlex#505349875 relayoutBoundary=up4
I/flutter (  856):         RenderSemanticsGestureHandler#215778521 relayoutBoundary=up5
I/flutter (  856):           RenderPointerListener#32840024 relayoutBoundary=up6
I/flutter (  856):         RenderConstrainedBox#687344973 relayoutBoundary=up5
I/flutter (  856):         RenderSemanticsGestureHandler#905486955 relayoutBoundary=up5
I/flutter (  856):           RenderPointerListener#873567131 relayoutBoundary=up6
I/flutter (  856):     RenderRepaintBoundary#347630081 relayoutBoundary=up3
I/flutter (  856):       RenderFlex#775262294 relayoutBoundary=up4
I/flutter (  856):         RenderSemanticsGestureHandler#597119883 relayoutBoundary=up5
I/flutter (  856):           RenderPointerListener#874871911 relayoutBoundary=up6
I/flutter (  856):         RenderConstrainedBox#357836631 relayoutBoundary=up5
I/flutter (  856):         RenderSemanticsGestureHandler#187785188 relayoutBoundary=up5
I/flutter (  856):           RenderPointerListener#1053656418 relayoutBoundary=up6
I/flutter (  856):     RenderRepaintBoundary#356801633 relayoutBoundary=up3
I/flutter (  856):       RenderConstrainedBox#670958616 relayoutBoundary=up4
I/flutter (  856):         RenderStack#132659746 relayoutBoundary=up5
I/flutter (  856):           RenderTransform#777711538 relayoutBoundary=up6
I/flutter (  856):           RenderOpacity#415796379 relayoutBoundary=up6
I/flutter (  856):           RenderPadding#226042933 relayoutBoundary=up6
I/flutter (  856): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (  856): Another exception was thrown: SliverGeometry has a layoutExtent that exceeds its paintExtent.
E/SpannableStringBuilder(  856): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder(  856): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder(  856): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder(  856): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
```

**Comment by HansMuller** [comment]
I'm looking into the freeze issue however we seem to have more problems than just that.

**Comment by HansMuller** [comment]
The source of the problem appears to be that in this case scrollPosition.applyContentDimensions() effectvely calls setCanDrag(false). Will try and sort that out tomorrow.

**Comment by HansMuller** [comment]
I have a fix.
