### ISSUE TITLE
NullPointerException in TextInputPlugin.clearTextInputClient(TextInputPlugin.java:527)

### ISSUE THREAD

**Issue by hello-soon** [flutter/flutter#92241]
<details>
<summary>crash report</summary>

```console
E/MethodChannel#flutter/textinput: Failed to handle method call
    java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.editing.ListenableEditingState.removeEditingStateListener(io.flutter.plugin.editing.ListenableEditingState$EditingStateWatcher)' on a null object reference
        at io.flutter.plugin.editing.TextInputPlugin.clearTextInputClient(TextInputPlugin.java:527)
        at io.flutter.plugin.editing.TextInputPlugin$1.clearClient(TextInputPlugin.java:148)
        at io.flutter.embedding.engine.systemchannels.TextInputChannel$1.onMethodCall(TextInputChannel.java:114)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loop(Looper.java:183)
        at android.app.ActivityThread.main(ActivityThread.java:7664)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```

</details>

<details>
<summary>flutter doctor -v</summary>

```console
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1052], locale zh-CN)
    • Flutter version 2.2.3 at C:\Android\flutter
    • Framework revision f4abaa0735 (4 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Android\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Android\SDK
    • Java binary at: C:\Android\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.2)
    • Visual Studio at c:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31624.102
    • Windows 10 SDK version 10.0.19041.0
    X Visual Studio requires a reboot of your system to complete installation.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] IntelliJ IDEA Ultimate Edition (version 2020.2)
    • IntelliJ at C:\Android\IntelliJIDEA
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (4 available)
    • Pixel 4 (mobile)  • 9B071FFAZ00B4K • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows        • windows-x64    • Microsoft Windows [Version 10.0.19042.1052]
    • Chrome (web)      • chrome         • web-javascript • Google Chrome 92.0.4515.159
    • Edge (web)        • edge           • web-javascript • Microsoft Edge 94.0.992.50

! Doctor found issues in 2 categories.
```
</details>

**Comment by danagbemava-nc** [comment]
Hi @hello-soon, you appear to be on an older version of flutter. 

Please upgrade to the latest version of flutter and see if you still experience this issue.

If you do, please provide a complete minimal reproducible code sample and output of `flutter doctor -v`. 

Thank you

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by eggfly** [comment]
PlatformException(error, Attempt to invoke virtual method 'void io.flutter.plugin.editing.ListenableEditingState.setEditingState(io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState)' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.editing.ListenableEditingState.setEditingState(io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState)' on a null object reference
at io.flutter.plugin.editing.TextInputPlugin.setTextInputEditingState(SourceFile:441)
at io.flutter.plugin.editing.TextInputPlugin$1.setEditingState(SourceFile:141)
at io.flutter.embedding.engine.systemchannels.TextInputChannel$1.onMethodCall(SourceFile:99)
at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(SourceFile:233)
at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(SourceFile:85)
at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(SourceFile:972)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:336)
at android.os.Looper.loop(Looper.java:174)
at android.app.ActivityThread.main(ActivityThread.java:7356)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
)
#0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:158)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:306)
#2      _getZoneSpecification.<anonymous closure>.<anonymous closure> (package:bd_vessel/extension/errortrace/internal/error_trace_utils.dart:90)
#3      _rootRunUnary (dart:async/zone.dart:1362)
#4      _CustomZone.runUnary (dart:async/zone.dart:1265)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:152)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:717)
#7      Future._propagateToListeners (dart:async/future_impl.dart:746)
#8      Future._completeWithValue (dart:async/future_impl.dart:552)
#9      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:590)
#10     _getZoneSpecification.<anonymous closure>.<anonymous closure> (package:bd_vessel/extension/errortrace/internal/error_trace_utils.dart:83)
#11     _rootRun (dart:async/zone.dart:1354)
#12     _CustomZone.run (dart:async/zone.dart:1258)
#13     _CustomZone.runGuarded (dart:async/zone.dart:1162)
#14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)

**Comment by eggfly** [comment]
@hello-soon Maybe your app are reusing same flutter engine, and a new FlutterView?

**Comment by eggfly** [comment]
https://github.com/flutter/engine/pull/30145 this can fix this issue.
