### ISSUE TITLE
how to solve this Exception: Gradle task assembleDebug failed with exit code 1

### ISSUE THREAD

**Issue by Pratham180** [flutter/flutter#92323]
Launching lib\main.dart on sdk gphone x86 in debug mode...
Running Gradle task 'assembleDebug'...

```
FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the User Manual chapter on the daemon at https://docs.gradle.org/6.7/userguide/gradle_daemon.html
Process command line: C:\Program Files\Android\Android Studio\jre\bin\java.exe --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED -Xmx1G -Dfile.encoding=windows-1252 -Duser.country=US -Duser.language=en -Duser.variant -cp C:\Users\ilapa\.gradle\wrapper\dists\gradle-6.7-all\cuy9mc7upwgwgeb72wkcrupxe\gradle-6.7\lib\gradle-launcher-6.7.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 6.7
Please read the following process output to find out more:
-----------------------

FAILURE: Build failed with an exception.

* What went wrong:
java.net.BindException: Address already in use: Cannot bind

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.UncheckedIOException: java.net.BindException: Address already in use: Cannot bind
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:61)
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:41)
	at org.gradle.cache.internal.locklistener.FileLockCommunicator.<init>(FileLockCommunicator.java:51)
	at org.gradle.cache.internal.locklistener.DefaultFileLockContentionHandler.getCommunicator(DefaultFileLockContentionHandler.java:263)
	at org.gradle.cache.internal.locklistener.DefaultFileLockContentionHandler.reservePort(DefaultFileLockContentionHandler.java:255)
	at org.gradle.cache.internal.DefaultFileLockManager.lock(DefaultFileLockManager.java:108)
	at org.gradle.cache.internal.DefaultFileLockManager.lock(DefaultFileLockManager.java:95)
	at org.gradle.cache.internal.DefaultFileLockManager.lock(DefaultFileLockManager.java:90)
	at org.gradle.cache.internal.OnDemandFileAccess.updateFile(OnDemandFileAccess.java:51)
	at org.gradle.cache.internal.SimpleStateCache.update(SimpleStateCache.java:87)
	at org.gradle.cache.internal.FileIntegrityViolationSuppressingPersistentStateCacheDecorator$1.create(FileIntegrityViolationSuppressingPersistentStateCacheDecorator.java:50)
	at org.gradle.cache.internal.FileIntegrityViolationSuppressingPersistentStateCacheDecorator.doUpdate(FileIntegrityViolationSuppressingPersistentStateCacheDecorator.java:67)
	at org.gradle.cache.internal.FileIntegrityViolationSuppressingPersistentStateCacheDecorator.update(FileIntegrityViolationSuppressingPersistentStateCacheDecorator.java:47)
	at org.gradle.launcher.daemon.registry.PersistentDaemonRegistry.store(PersistentDaemonRegistry.java:232)
	at org.gradle.launcher.daemon.server.DaemonRegistryUpdater.onStart(DaemonRegistryUpdater.java:80)
	at org.gradle.launcher.daemon.server.Daemon.start(Daemon.java:171)
	at org.gradle.launcher.daemon.bootstrap.DaemonMain.doAction(DaemonMain.java:125)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:50)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
	at org.gradle.launcher.daemon.bootstrap.GradleDaemon.main(GradleDaemon.java:22)
Caused by: java.net.BindException: Address already in use: Cannot bind
	at java.base/java.net.DualStackPlainDatagramSocketImpl.socketBind(Native Method)
	at java.base/java.net.DualStackPlainDatagramSocketImpl.bind0(DualStackPlainDatagramSocketImpl.java:84)
	at java.base/java.net.AbstractPlainDatagramSocketImpl.bind(AbstractPlainDatagramSocketImpl.java:131)
	at java.base/java.net.DatagramSocket.bind(DatagramSocket.java:394)
	at java.base/java.net.DatagramSocket.<init>(DatagramSocket.java:244)
	at java.base/java.net.DatagramSocket.<init>(DatagramSocket.java:301)
	at org.gradle.cache.internal.locklistener.FileLockCommunicator.<init>(FileLockCommunicator.java:49)
	... 22 more


* Get more help at https://help.gradle.org


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
Exception: Gradle task assembleDebug failed with exit code 1
```

**Comment by jtmcdole** [comment]
Same problem for me:

```
[√] Flutter (Channel master, 2.6.0-12.0.pre.717, on Microsoft Windows [Version 10.0.19043.1288], locale en-US)
    • Flutter version 2.6.0-12.0.pre.717 at C:\tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0411e76551 (14 hours ago), 2021-11-13 05:21:03 -0500
    • Engine revision 140bd9399e
    • Dart version 2.16.0 (build 2.16.0-10.0.dev)
    • DevTools version 2.8.0

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at G:\Android\
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31624.102
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.62.2)
    • VS Code at C:\Users\pii\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.27.0

[√] Connected device (4 available)
    • Pixel 6 Pro (mobile) • pii • android-arm64  • Android 12 (API 31)
    • Windows (desktop)    • windows        • windows-x64    • Microsoft Windows [Version 10.0.19043.1288]
    • Chrome (web)         • chrome         • web-javascript • Google Chrome 95.0.4638.69
    • Edge (web)           • edge           • web-javascript • Microsoft Edge 95.0.1020.40
```

**Comment by Pratham180** [comment]
if u are using a laptop and using a mobile hotspot from your laptop turn it off and run the program i hope this will solve your problem it worked for me.

**Comment by darshankawar** [comment]
Closing this as resolved based on above comment. If anybody else still see this, please provide concrete steps to replicate.
