### ISSUE TITLE
Failed assertion: line 1706 pos 12: '!_debugDoingThisLayout': is not true.

### ISSUE THREAD

**Issue by 971586331** [flutter/flutter#92346]
```
======== Exception caught by rendering library =====================================================
The following assertion was thrown during performLayout():
'package:flutter/src/rendering/object.dart': Failed assertion: line 1706 pos 12: '!_debugDoingThisLayout': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  TimeSeriesChart file:///D:/gitee/voco_flutter/lib/page/home/data_collection.dart:453:21
When the exception was thrown, this was the stack: 
#2      RenderObject.layout (package:flutter/src/rendering/object.dart:1706:12)
#3      MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
#4      WidgetLayoutDelegate.performLayout (package:charts_flutter/src/widget_layout_delegate.dart:80:7)
#5      MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
#6      RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:404:14)
...
The following RenderObject was being processed when the exception was fired: RenderCustomMultiChildLayoutBox#adc44 NEEDS-LAYOUT
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=392.7, h=296.5)
...  size: Size(392.7, 296.5)
RenderObject: RenderCustomMultiChildLayoutBox#adc44 NEEDS-LAYOUT
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=392.7, h=296.5)
  size: Size(392.7, 296.5)
...  child 1: RenderSemanticsGestureHandler#1fa9a
...    parentData: offset=Offset(0.0, 0.0); id=chartContainer (can use size)
...    constraints: BoxConstraints(w=392.7, h=296.5)
...    size: Size(392.7, 344.5)
...    behavior: deferToChild
...    gestures: tap
...    child: RenderPointerListener#9047c NEEDS-LAYOUT
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=392.7, h=296.5)
...      size: Size(392.7, 296.5)
...      behavior: deferToChild
...      listeners: down
...      child: ChartContainerRenderObject<DateTime>#d6095 NEEDS-LAYOUT
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=392.7, h=296.5)
...        semantic boundary
...        size: Size(392.7, 296.5)
====================================================================================================
```

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
