### ISSUE TITLE
[android] Use existing FlutterJNI by default instead of creating one.

### ISSUE THREAD

**Issue by 0xZOne** [flutter/flutter#92479]
We should use existing FlutterJNI by default instead of creating one.

```
10-26 17:01:01.300 32694 32694 E xlog    : java.lang.Throwable
10-26 17:01:01.300 32694 32694 E xlog    : 	at io.flutter.embedding.engine.FlutterJNI.<init>(FlutterJNI.java:296)
10-26 17:01:01.300 32694 32694 E xlog    : 	at io.flutter.embedding.engine.FlutterJNI$Factory.provideFlutterJNI(FlutterJNI.java:1373)
10-26 17:01:01.300 32694 32694 E xlog    : 	at io.flutter.FlutterInjector$Builder.fillDefaults(FlutterInjector.java:169)
10-26 17:01:01.300 32694 32694 E xlog    : 	at io.flutter.FlutterInjector$Builder.build(FlutterInjector.java:179)
10-26 17:01:01.300 32694 32694 E xlog    : 	at io.flutter.FlutterInjector.instance(FlutterInjector.java:57)
10-26 17:01:01.300 32694 32694 E xlog    : 	at io.flutter.app.FlutterApplication.onCreate(FlutterApplication.java:24)
10-26 17:01:01.300 32694 32694 E xlog    : 	at com.idlefish.flutterboost.example.MyApplication.onCreate(MyApplication.java:13)
10-26 17:01:01.300 32694 32694 E xlog    : 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190)
10-26 17:01:01.300 32694 32694 E xlog    : 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6723)
10-26 17:01:01.300 32694 32694 E xlog    : 	at android.app.ActivityThread.access$1400(ActivityThread.java:231)
10-26 17:01:01.300 32694 32694 E xlog    : 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1959)
10-26 17:01:01.300 32694 32694 E xlog    : 	at android.os.Handler.dispatchMessage(Handler.java:107)
10-26 17:01:01.300 32694 32694 E xlog    : 	at android.os.Looper.loop(Looper.java:214)
10-26 17:01:01.300 32694 32694 E xlog    : 	at android.app.ActivityThread.main(ActivityThread.java:7660)
10-26 17:01:01.300 32694 32694 E xlog    : 	at java.lang.reflect.Method.invoke(Native Method)
10-26 17:01:01.300 32694 32694 E xlog    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
10-26 17:01:01.300 32694 32694 E xlog    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:938)
10-26 17:01:01.325 32694 32694 E xlog    : #FlutterJNI: io.flutter.embedding.engine.FlutterJNI@2a3168a
10-26 17:01:01.328 32694 32694 E xlog    : java.lang.Throwable
10-26 17:01:01.328 32694 32694 E xlog    : 	at io.flutter.embedding.engine.FlutterJNI.<init>(FlutterJNI.java:296)
10-26 17:01:01.328 32694 32694 E xlog    : 	at io.flutter.embedding.engine.FlutterJNI$Factory.provideFlutterJNI(FlutterJNI.java:1373)
10-26 17:01:01.328 32694 32694 E xlog    : 	at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:291)
10-26 17:01:01.328 32694 32694 E xlog    : 	at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:262)
10-26 17:01:01.328 32694 32694 E xlog    : 	at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:242)
10-26 17:01:01.328 32694 32694 E xlog    : 	at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:162)
10-26 17:01:01.328 32694 32694 E xlog    : 	at com.idlefish.flutterboost.FlutterBoost.setup(FlutterBoost.java:66)
10-26 17:01:01.328 32694 32694 E xlog    : 	at com.idlefish.flutterboost.example.MyApplication.onCreate(MyApplication.java:18)
10-26 17:01:01.328 32694 32694 E xlog    : 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190)
10-26 17:01:01.328 32694 32694 E xlog    : 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6723)
10-26 17:01:01.328 32694 32694 E xlog    : 	at android.app.ActivityThread.access$1400(ActivityThread.java:231)
10-26 17:01:01.328 32694 32694 E xlog    : 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1959)
10-26 17:01:01.328 32694 32694 E xlog    : 	at android.os.Handler.dispatchMessage(Handler.java:107)
10-26 17:01:01.328 32694 32694 E xlog    : 	at android.os.Looper.loop(Looper.java:214)
10-26 17:01:01.328 32694 32694 E xlog    : 	at android.app.ActivityThread.main(ActivityThread.java:7660)
10-26 17:01:01.328 32694 32694 E xlog    : 	at java.lang.reflect.Method.invoke(Native Method)
10-26 17:01:01.328 32694 32694 E xlog    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
10-26 17:01:01.328 32694 32694 E xlog    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:938)
```

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel master, 2.6.0-12.0.pre.470, on macOS 11.6 20G165 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.6.0-12.0.pre.470 at /Users/zero/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9350a149a6 (10 hours ago), 2021-10-25 16:33:05 -0700
    • Engine revision f9bd71bf13
    • Dart version 2.15.0 (build 2.15.0-250.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/zero/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/zero/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/zero/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.61.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 95.0.4638.54

• No issues found!
```

</details>

**Comment by dnfield** [comment]
It's already possible to override the way `FlutterInjector` creates FlutterJNI instances. But it's not safe to reuse a `FlutterJNI` class that has the wrong pointer to the native shell. For that reason, we should not do this.

**Comment by dnfield** [comment]
(The linked issue is about getting rid of hard-to-test statics from `FlutterJNI`, which also probably aren't entirely safe to keep as static)
