### ISSUE TITLE
pub run - i18n with Intl

### ISSUE THREAD

**Issue by dbacinski** [flutter/flutter#9251]
I am trying to do i18n with Intl as in example project https://github.com/flutter/flutter/tree/master/examples/stocks/lib/i18n and Intl docs https://pub.dartlang.org/packages/intl

But I am unable to generate .arb files.

```
Dariuszs-MacBook-Pro:wms-flutter dariuszbacinski$ pub run intl_translation:extract_to_arb --output-dir=lib/i18n lib/strings.dart 
Bad state: Flutter is not available.
package:pub/src/flutter.dart 29       packagePath
package:pub/src/source/sdk.dart 108   BoundSdkSource.getDirectory
package:pub/src/system_cache.dart 97  SystemCache.load
package:pub/src/entrypoint.dart 589   Entrypoint._assertLockFileUpToDate
package:pub/src/entrypoint.dart 521   Entrypoint.assertUpToDate
package:pub/src/entrypoint.dart 106   Entrypoint.packageGraph
package:pub/src/executable.dart 43    runExecutable.<async>
This is an unexpected error. Please run

    pub --trace run intl_translation:extract_to_arb --output-dir=lib/i18n lib/strings.dart

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
```

How can I use `pub run` with Flutter project?

**Comment by hundeva** [comment]
If I'm right, this means that `flutter` is not exported in your path, for example `flutter doctor` would fail too.

Consider adding something like this to your `.bash_profile`, note: I have flutter cloned in my home folder:

```
export PATH="/Users/your_user_name/Flutter/flutter/bin:$PATH"
export PATH="/Users/your_user_name/Flutter/flutter/bin/cache/dart-sdk/bin:$PATH"
```

**Comment by eseidelGoogle** [comment]
`Bad state: Flutter is not available.` would be from pub and likely indicates that pub sees a pubspec.yaml with a flutter sdk dependency but doesn't have FLUTTER_ROOT set.

I'd recommend we move this to the pub issue tracker.

**Comment by dbacinski** [comment]
After adding Flutter to `PATH` I am getting an error:

```
Dariuszs-MacBook-Pro:wms-flutter dariuszbacinski$ pub run intl_translation:extract_to_arb --output-dir=lib/i18n lib/strings.dart 
Flutter is not available. If this is a Flutter project, make sure to always run
pub through the "flutter" executable.
```


Flutter doctor output:
```
Dariuszs-MacBook-Pro:wms-flutter dariuszbacinski$ flutter doctor
[✓] Flutter (on Mac OS X 10.11.6 15G1217, channel master)
    • Flutter at /Users/dariuszbacinski/Library/flutter
    • Framework revision 5541d71b11 (2 days ago), 2017-04-04 13:03:06
    • Engine revision 878f0ff09d
    • Tools Dart version 1.23.0-dev.10.0

[✓] Host Executable Compatibility
    • Downloaded executables execute on host

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/dariuszbacinski/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/bin/java
    • Java version: Java(TM) SE Runtime Environment (build 1.8.0_101-b13)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.0

[✗] Android Studio (not installed)
    • Android Studio not found. Download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] Gradle (3.2)
    • gradle-dir = /Applications/Android Studio 2.3.app/Contents/gradle/gradle-3.2/
    • Flutter supports building with Gradle from Android Studio.
      Consider removing your gradle-dir setting by running:
      flutter config --gradle-dir=

[-] IntelliJ IDEA Community Edition (version 2016.2.4)
    • Dart plugin not installed; this adds Dart specific functionality.
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/managing-plugins.html

[✓] IntelliJ IDEA Ultimate Edition (version 2016.3.4)
    • Dart plugin version 163.13137
    • Flutter plugin version 12.0

[-] WebStorm (version 2016.3.3)
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/managing-plugins.html

[✓] Connected devices
    • iPhone SE  • ios • iOS 10.2 (simulator)
```

**Comment by eseidelGoogle** [comment]
FLUTTER_ROOT is the special variable which `pub` uses to figure out how to resolve `sdk: flutter` dependencies.  You can see how we pass it every time we invoke pub from `flutter` here:
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/dart/pub.dart#L59

**Comment by dbacinski** [comment]
`pub run` has started working after exporting `FLUTTER_ROOT` and adding dependency `intl_translation:` to `pubspec.yaml` :)

Moving forward. Now I have error  from `intl_translation`
```Dariuszs-MacBook-Pro:wms-flutter dariuszbacinski$ pub run intl_translation:extract_to_arb --output-dir=lib/i18n lib/strings.dart 
Unhandled exception:
FileSystemException: Cannot open file, path = 'lib/i18n/intl_messages.arb' (OS Error: No such file or directory, errno = 2)
#0      _File.throwIfError (dart:io/file_impl.dart:599)
#1      _File.openSync (dart:io/file_impl.dart:454)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:568)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:592)
#4      main (http://localhost:57084/extract_to_arb.dart:63:8)
#5      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```
I thought that this script is suppose to create *.arb files...

**Comment by dbacinski** [comment]
I guess this is more like an issue to be reported at https://github.com/dart-lang/intl. Thanks for support!

**Comment by dbacinski** [comment]
Follow up: https://github.com/dart-lang/intl_translation/issues/8
