### ISSUE TITLE
Chrome console (if selected iphone) shows [Error from backend: Error: Bad state: Not connected to an application.] and no VM

### ISSUE THREAD

**Issue by Cemique** [flutter/flutter#92567]
I used chrome on windows to run the app. The problem happens in device mode on chrome and for any iphone. But it works fine if I choose other phones like galaxy S5.

## Steps to Reproduce

1. `flutter create sample_project && cd sample_project`
2. `flutter run -d chrome`
3. In developer console select device mode then select any apple device (like iphone x)
4. Refresh the page

**Expected results:** 
Connecting to VM to be able to hot reload & stuff

**Actual results:** 
No connection to VM and error : Not connected to an application

<details>
  <summary><b>flutter run --verbose -d chrome</b> (I added comments)</summary>

```
[ +423 ms] executing: [D:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +411 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +3 ms] 18116933e77adc82f80866c928266a5b4f1ed645
[   +3 ms] executing: [D:\flutter/] git tag --points-at 18116933e77adc82f80866c928266a5b4f1ed645
[ +356 ms] Exit code 0 from: git tag --points-at 18116933e77adc82f80866c928266a5b4f1ed645
[   +3 ms] 2.5.3
[  +51 ms] executing: [D:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +240 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +2 ms] origin/stable
[   +1 ms] executing: [D:\flutter/] git ls-remote --get-url origin
[ +209 ms] Exit code 0 from: git ls-remote --get-url origin
[   +2 ms] https://github.com/flutter/flutter.git
[ +639 ms] executing: [D:\flutter/] git rev-parse --abbrev-ref HEAD
[ +255 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +2 ms] stable
[ +404 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +26 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +508 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +14 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +7 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +449 ms] Skipping pub get: version match.
[ +649 ms] Generating D:\dvp\my_project\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +674 ms] Launching lib\main.dart on Chrome in debug mode...
[ +738 ms] Updating assets
[ +431 ms] Waiting for connection from debug service on Chrome...
[ +527 ms] <- reset
[  +49 ms] D:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
D:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root D:\flutter\bin\cache\flutter_web_sdk/ --incremental
--target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
C:\Users\WinUs\AppData\Local\Temp\flutter_tools.e2ffa870\flutter_tool.e48c0928\app.dill --libraries-spec
file:///D:/flutter/bin/cache/flutter_web_sdk/libraries.json --packages D:\dvp\my_project\.dart_tool\package_config.json
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root
C:\Users\WinUs\AppData\Local\Temp\flutter_tools.e2ffa870\flutter_tools.9e806a58 --filesystem-scheme org-dartlang-app --initialize-from-dill
build\b1b715402d823b7fd5c2b68d2edcb2ce.cache.dill.track.dill --platform file:///D:/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk_sound.dill
--sound-null-safety
[  +76 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+88423 ms] Waiting for connection from debug service on Chrome... (completed in 89.0s)
[  +12 ms] Synced 26.2MB.
[   +7 ms] <- accept
[  +10 ms] Caching compiled dill
[+1930 ms] [CHROME]:
[  +10 ms] [CHROME]:DevTools listening on ws://127.0.0.1:13477/devtools/browser/81354596-dada-4e25-a842-19f82fad6df3
[+3028 ms] DwdsInjector: Received request for entrypoint at http://localhost:13460/main_module.bootstrap.js
[  +89 ms] MetadataProvider: Loading debug metadata...
[ +158 ms] MetadataProvider: Loaded debug metadata (sound null safety)
[  +61 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:13460/main_module.bootstrap.js
[+18189 ms] ChromeProxyService: Initializing expression compiler for main_module.bootstrap.js with sound null safety: true
[ +361 ms] DevHandler: Debug service listening on ws://127.0.0.1:13501/XrVwyEdQQd8=/ws

[ +127 ms] This app is linked to the debug service: ws://127.0.0.1:13501/XrVwyEdQQd8=/ws
[  +62 ms] Debug service listening on ws://127.0.0.1:13501/XrVwyEdQQd8=/ws
[   +9 ms]  Running with sound null safety
[  +28 ms]   To hot restart changes while running, press "r" or "R".
[   +4 ms] For a more detailed help message, press "h". To quit, press "q".
[  +12 ms] An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:13501/XrVwyEdQQd8=
[+3423 ms] DevTools activation throttled until 2021-10-27 20:54:23.252308.
[+6458 ms] The Flutter DevTools debugger and profiler on Chrome is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:13501/XrVwyEdQQd8=



##################################### Now I select iphone & press refresh



[+46449 ms] DwdsInjector: Received request for entrypoint at http://localhost:13460/main_module.bootstrap.js
[  +17 ms] MetadataProvider: Loading debug metadata...
[  +89 ms] MetadataProvider: Loaded debug metadata (sound null safety)
[  +37 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:13460/main_module.bootstrap.js


##################################### Chrome console error is shown like 40 times

##################################### Hot restart


[+49398 ms] Performing hot restart...
[  +27 ms] Initializing file store
[  +62 ms] Skipping target: gen_localizations
[  +27 ms] Skipping target: gen_dart_plugin_registrant
[  +10 ms] Skipping target: _composite
[  +25 ms] complete
[ +255 ms] Scanned through 522 files in 230ms
[   +6 ms] Waiting for connection from debug service on Chrome...
[  +12 ms] <- recompile org-dartlang-app:/web_entrypoint.dart 2a83f41f-f8ec-48f7-a6b5-7cee9597b5cd
[   +3 ms] <- 2a83f41f-f8ec-48f7-a6b5-7cee9597b5cd
[  +80 ms] Waiting for connection from debug service on Chrome... (completed in 87ms)
[   +5 ms] Synced 0.0MB.
[   +4 ms] <- accept
[  +19 ms] DwdsVmClient: Attempting a hot restart
[   +9 ms] DwdsVmClient: Attempting to disable breakpoints and resume the isolate


##################################### Nothing happens & no restart performed
```

</details>

<details>
  <summary>Error in chrome console</summary>

```
client.js:24134 Error from backend:

Error: Bad state: Not connected to an application.

Stack Trace:
#0      DevHandler._handleConnection.<anonymous closure> (package:dwds/src/handlers/dev_handler.dart:255:13)
#1      DevHandler._handleConnection.<anonymous closure> (package:dwds/src/handlers/dev_handler.dart:242:38)
#2      _rootRunUnary (dart:async/zone.dart:1436:47)
#3      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#7      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
#8      _MapStream._handleData (dart:async/stream_pipe.dart:218:10)
#9      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
#10     _rootRunUnary (dart:async/zone.dart:1436:47)
#11     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#12     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#14     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#15     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#16     _StreamController._add (dart:async/stream_controller.dart:607:7)
#17     _StreamController.add (dart:async/stream_controller.dart:554:5)
#18     new WebSocketImpl.fromSocket.<anonymous closure> (package:web_socket_channel/src/copy/web_socket_impl.dart:730:21)
#19     _rootRunUnary (dart:async/zone.dart:1436:47)
#20     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#22     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#23     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#24     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#25     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#26     _WebSocketProtocolTransformer._messageFrameEnd (package:web_socket_channel/src/copy/web_socket_impl.dart:319:23)
#27     _WebSocketProtocolTransformer.add (package:web_socket_channel/src/copy/web_socket_impl.dart:218:46)
#28     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#29     _rootRunUnary (dart:async/zone.dart:1436:47)
#30     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#31     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#32     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#33     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#34     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#35     _StreamController._add (dart:async/stream_controller.dart:607:7)
#36     _StreamController.add (dart:async/stream_controller.dart:554:5)
#37     _Socket._onData (dart:io-patch/socket_patch.dart:2166:41)
#38     _rootRunUnary (dart:async/zone.dart:1444:13)
#39     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#40     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#41     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#42     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#43     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#44     _StreamController._add (dart:async/stream_controller.dart:607:7)
#45     _StreamController.add (dart:async/stream_controller.dart:554:5)
#46     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1702:33)
#47     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1213:14)
#48     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#49     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#50     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
#51     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)

(anonymous) @ client.js:24134
(anonymous) @ client.js:4461
call$2 @ client.js:11511
_asyncStartSync @ client.js:4425
$call$body$main__closure @ client.js:24142
call$1 @ client.js:24069
_rootRunUnary @ client.js:4823
runUnary$2$2 @ client.js:12879
runUnaryGuarded$1$2 @ client.js:12826
_sendData$1 @ client.js:12416
_add$1 @ client.js:12362
_add$1 @ client.js:12695
_handleData$2 @ client.js:12756
_handleData$1 @ client.js:12721
eval @ VM1618:3
_rootRunUnary @ client.js:4823
runUnary$2$2 @ client.js:12879
runUnaryGuarded$1$2 @ client.js:12826
_sendData$1 @ client.js:12416
_add$1 @ client.js:12362
_sendData$1 @ client.js:12201
add$1 @ client.js:12082
eval @ VM1624:3
_rootRunUnary @ client.js:4823
runUnary$2$2 @ client.js:12879
runUnaryGuarded$1$2 @ client.js:12826
_sendData$1 @ client.js:12416
_add$1 @ client.js:12362
_sendData$1 @ client.js:12201
add$1 @ client.js:12082
add$1 @ client.js:23581
call$1 @ client.js:23874
call$1 @ client.js:18042
_rootRunUnary @ client.js:4829
runUnary$2$2 @ client.js:12879
runUnaryGuarded$1$2 @ client.js:12826
call$1 @ client.js:13016
invokeClosure @ client.js:1524
(anonymous) @ client.js:1543
Show 9 more frames
```

</details>

<details>
  <summary><b>flutter doctor -v</b></summary>

```
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19043.1237], locale en-US)
    • Flutter version 2.5.3 at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (12 days ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at D:\AndroidSdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Connected device (2 available)
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 95.0.4638.54
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 95.0.1020.30

! Doctor found issues in 1 category.
```

</details>

**Comment by kalismeras61** [comment]
I have also same issue.

**Comment by annagrin** [comment]
Found a cause: we use `window.navigator.userAgent` in the injected client to detect the browser it is running in. The value changes in iPhone simulation mode to Safari:)

Working on a fix.
