### ISSUE TITLE
[PictureRecorder] Allow PictureRecorder to draw inside of an isolate

### ISSUE THREAD

**Issue by danielgomezrico** [flutter/flutter#92575]
Currently, you can not use `PictureRecorder` inside an `isolate` or it ends up in:

```dart
Exception: UI actions are only available on root isolate.
	#0      PictureRecorder._constructor (dart:ui/painting.dart:4458:59)
	#1      new PictureRecorder (dart:ui/painting.dart:4457:23)
	#2      IconGenerator._drawCircle (package:client/src/common/utils/map/icon_generator.dart:87:32)
	#3      IconGenerator.buildCircle (package:client/src/common/utils/map/icon_generator.dart:51:26)
	#4      MarkerGenerator._buildDots.<anonymous closure> (package:client/src/common/utils/map/marker_generator.dart:62:37)
	#5      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
	#6      ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
	#7      Future.wait (dart:async/future.dart:406:26)
	#8      MarkerGenerator._buildDots (package:client/src/common/utils/map/marker_generator.dart:68:19)
	#9      MarkerGenerator.build (package:client/src/common/utils/map/marker_generator.dart:30:22)
	#10     buildMarkers (package:client/src/widget
```

## Use case
In my app we have a lot of markers and building them every time is causing some UI freezes, it would be useful to be able to create them on an `isolate` so the UI does not freeze.

An example of what we do to create a marker using a `PictureRecorder`:

```dart
// https://stackoverflow.com/a/56534916/273119
  Future<Uint8List> _drawColoredMarker(String text, Color color) async {
    final pictureRecorder = ui.PictureRecorder();
    final canvas = Canvas(pictureRecorder);

    final paint = Paint()..color = color;
    canvas.drawRRect(_rect, paint);

    final textPainter = TextPainter(
      textDirection: TextDirection.ltr,
      text: TextSpan(text: text, style: _textStyle),
    );
    textPainter.layout();
    final offset = Offset(
      (_width * 0.5) - textPainter.width * 0.5,
      (_height * 0.5) - textPainter.height * 0.5,
    );
    textPainter.paint(canvas, offset);

    final image = await pictureRecorder
        .endRecording()
        .toImage(_width.floor(), _height.floor());

    final data = await image.toByteData(format: ui.ImageByteFormat.png);
    return data!.buffer.asUint8List();
  }
```

Which ends up drawing markers like this:
![image](https://user-images.githubusercontent.com/76348/139327400-d0ee81e5-628b-49bc-abe2-3d260a1f2fd6.png)

## Proposal
I'm not really sure how to do it that, but it is related to this: https://github.com/flutter/flutter/issues/30604

**Comment by jonahwilliams** [comment]
There are already multiple issues for this feature/bug
