### ISSUE TITLE
If you have an old commit, you can't build flutter_gallery for Android

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#9262]
I'm on 249bbac362a1e2dec133a8772a1b90cacbd06fd9 (with one 6 month old commit on top).

## command

```
flutter build flx --target /src/flutter/examples/flutter_gallery/lib/main.dart --output-file /src/flutter/examples/flutter_gallery/build/app/intermediates/flutter/debug/app.flx --snapshot /src/flutter/examples/flutter_gallery/build/app/intermediates/flutter/debug/snapshot_blob.bin --depfile /src/flutter/examples/flutter_gallery/build/app/intermediates/flutter/debug/snapshot_blob.bin.d --working-dir /src/flutter/examples/flutter_gallery/build/app/intermediates/flutter/debug/flx
```

## exception
```
StateError: Bad state: The current process does not own the lock for the cache directory. This is a bug in Flutter CLI tools.

#0      Cache.checkLockAcquired (package:flutter_tools/src/cache.dart:81)
#1      FlutterVersion._getLatestAvailableFlutterVersion (package:flutter_tools/src/version.dart:215)
<asynchronous suspension>
#2      FlutterVersion.checkFlutterVersionFreshness.newerFrameworkVersionAvailable (package:flutter_tools/src/version.dart:180)
<asynchronous suspension>
#3      FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart:188)
<asynchronous suspension>
#4      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:239)
<asynchronous suspension>
#5      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#6      Future.Future.sync (dart:async/future.dart:208)
#7      CommandRunner.run (package:args/command_runner.dart:109)
#8      FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:157)
#9      run.<anonymous closure> (package:flutter_tools/executable.dart:140)
<asynchronous suspension>
#10     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#11     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#12     _rootRun (dart:async/zone.dart:1120)
#13     _CustomZone.run (dart:async/zone.dart:1001)
#14     runZoned (dart:async/zone.dart:1465)
#15     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#16     run (package:flutter_tools/executable.dart:113)
<asynchronous suspension>
#17     main (package:flutter_tools/executable.dart:66)
<asynchronous suspension>
#18     main (file:///src/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#19     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

## flutter doctor

```
[✓] Flutter (on Mac OS X 10.12.3 16D32, channel master)
    • Flutter at /src/flutter
    • Framework revision e3c7501c4d (6 months ago), 2016-10-19 16:17:55 -0700
    • Engine revision 5d9a642257
    • Tools Dart version 1.23.0-dev.11.5

[✓] Host Executable Compatibility
    • Downloaded executables execute on host

[✗] Android toolchain - develop for Android devices
    ✗ ANDROID_HOME = /Users/eseidel/Library/Android/sdk
      but Android SDK not found at this location.

[✓] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.0

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2016.3.4)
    • Dart plugin version 163.13137
    • Flutter plugin version 0.1.11.1

[✓] Connected devices
    • Nexus 10  • R32CA05JT2E                          • android-arm • Android 5.1 (API 22)
    • iPhone 6s • FF0E5127-3490-4297-9313-C4776D7950D4 • ios         • iOS 10.0 (simulator)
```

**Comment by eseidelGoogle** [comment]
@yjbanov is this a bug when building under gradle (with an old commit)?  @jakobr-google

**Comment by eseidelGoogle** [comment]
It appears to be related to the old commit triggering the version check logic at a bad time during the gradel build.

**Comment by yjbanov** [comment]
I was hoping that requiring a lock would make it more robust, but it seems our locking strategy is too complicate to facilitate robustness. Let's not require a lock for version checking and see what happens: https://github.com/flutter/flutter/pull/9272

**Comment by Hixie** [comment]
It could be that this is being triggered by a re-entrant flutter process. Those don't get a lock. You can check if you're in one of those and just not do the version check.

**Comment by yjbanov** [comment]
@Hixie how about https://github.com/flutter/flutter/pull/9272/commits/3cd9e201d02b177b3808c550b21797a8d982b46d?
