### ISSUE TITLE
ghost "android-arm • Android null (API null)" device causes "flutter run" to fail once

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#9265]
Sometimes, I get this "More than one device connected" message despite only having one device connected. The other "device" seems to be a ghost of adb?

```
ianh@ianh:~/dev/flutter/examples/flutter_gallery$ flutter --verbose --local-engine=android_debug_unopt run --pid-file=/tmp/run.pid 
[  +20 ms] [/usr/local/google/home/ianh/dev/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +18 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] upstream/master
[        ] [/usr/local/google/home/ianh/dev/flutter/] git ls-remote --get-url upstream
[   +2 ms] Exit code 0 from: git ls-remote --get-url upstream
[        ] git@github.com:flutter/flutter.git
[        ] [/usr/local/google/home/ianh/dev/flutter/] git log -n 1 --pretty=format:%H
[   +3 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 5014bf0ef07b199b1533447dcbb9e88f4e7bc39a
[        ] [/usr/local/google/home/ianh/dev/flutter/] git log -n 1 --pretty=format:%ar
[   +4 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 41 minutes ago
[ +127 ms
] /usr/local/google/home/ianh/Android/Sdk/platform-tools/adb devices -l
[+5008 ms
] Exit code 0 from: /usr/local/google/home/ianh/Android/Sdk/platform-tools/adb devices -l
[        ] List of devices attached
           adb server version (32) doesn't match this client (36); killing...
           * daemon started successfully *
           ZX1G22KJ3C             device usb:3-2.4 product:shamu model:Nexus_6 device:shamu
[  +19 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag.

[   +1 ms] /usr/local/google/home/ianh/Android/Sdk/platform-tools/adb -s adb shell getprop
[   +4 ms] Error retrieving device properties for ro.build.characteristics.

[   +9 ms] /usr/local/google/home/ianh/Android/Sdk/platform-tools/adb -s ZX1G22KJ3C shell getprop
[ +117 ms
] adb     • adb        • android-arm • Android null (API null)

[        ] Nexus 6 • ZX1G22KJ3C • android-arm • Android 7.1.1 (API 25)

[   +1 ms] 'flutter run' took 5253ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:29)
#1      RunCommand.verifyThenRunCommand (package:flutter_tools/src/commands/run.dart:195)
<asynchronous suspension>
#2      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:121)
#3      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#4      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:262)
<asynchronous suspension>
#5      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#6      Future.Future.sync (dart:async/future.dart:208)
#7      CommandRunner.run (package:args/command_runner.dart:109)
#8      FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:157)
#9      run.<anonymous closure> (package:flutter_tools/executable.dart:140)
<asynchronous suspension>
#10     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#11     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#12     _rootRun (dart:async/zone.dart:1120)
#13     _CustomZone.run (dart:async/zone.dart:1001)
#14     runZoned (dart:async/zone.dart:1465)
#15     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#16     run (package:flutter_tools/executable.dart:113)
<asynchronous suspension>
#17     main (package:flutter_tools/executable.dart:66)
<asynchronous suspension>
#18     main (file:///usr/local/google/home/ianh/dev/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#19     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)


[ +142 ms
] ensureAnalyticsSent: 128ms
[   +4 ms] exiting with code 1
ianh@ianh:~/dev/flutter/examples/flutter_gallery$
```

cc @johnmccutchan

**Comment by chinmaygarde** [comment]
This happens to me too when I have an old version of ADB running. This happened to me when I had the older version in my `PATH` and used it directly for `logcat`. `adb kill-server` fixed it.

**Comment by zoechi** [comment]
Looks like a dup of #8424, #4123 and there are no similar reports in a long time. 
Assuming stale.
