### ISSUE TITLE
[tool][dart] Crash in kernel compiler when building

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#92679]
I recently updated to framework commit `ca788d8941abc469ee6cac70daff3dfd67d9e47e` (engine commit `c9dda84396f287720d82249b0a1571e0ad9b6a82`) on the main branch and triggered a windows build of an app. This appears to reproducibly crash with the same issue on any app, but I used [tvolkert/flutter_desktop_bug](https://github.com/tvolkert/flutter_desktop_bug).

During the kernel compile phase, the kernel compiler reproducibly crashes with the following details:

```
cbracken@cbracken0 MINGW64 /c/src/flutter_desktop_bug (main)
$ flutter run -d windows
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine c9dda84396f287720d82249b0a1571e0ad9b6a82...
Expanding downloaded archive...
Building flutter tool...
Running pub upgrade...
Downloading package sky_engine...                                  482ms
Downloading flutter_patched_sdk tools...                           454ms
Downloading flutter_patched_sdk_product tools...                   361ms
Downloading windows-x64 tools...                                 2,885ms
Downloading windows-x64/font-subset tools...                       268ms
Downloading windows-x64/windows-x64-flutter tools...                5.6s
Downloading windows-x64/flutter-cpp-client-wrapper tools...        166ms
Downloading windows-x64-profile/windows-x64-flutter tools...         4.7s
Downloading windows-x64-release/windows-x64-flutter tools...         4.7s
Running "flutter pub get" in flutter_desktop_bug...                636ms
Launching lib\main.dart on Windows in debug mode...
Unhandled exception:
Crash when compiling null,
at character offset null:
type 'StaticGet' is not a subtype of type 'ConstructorTearOff' in type cast
#0      getRedirectingFactories
(package:front_end/src/fasta/kernel/redirecting_factory_body.dart:41:43)
#4      LazyLibraryScope.ensureScope
(package:front_end/src/fasta/dill/dill_library_builder.dart:61:21)
#5      LazyScope._local (package:front_end/src/fasta/scope.dart:630:5)
#6      Scope.lookupLocalMember (package:front_end/src/fasta/scope.dart:408:38)
#7      DillLibraryBuilder.finalizeExports
(package:front_end/src/fasta/dill/dill_library_builder.dart:414:35)
#8      DillLibraryBuilder.ensureLoaded
(package:front_end/src/fasta/dill/dill_library_builder.dart:127:7)
#9      LazyLibraryScope.ensureScope
(package:front_end/src/fasta/dill/dill_library_builder.dart:61:21)
#10     LazyScope._local (package:front_end/src/fasta/scope.dart:630:5)
#11     Scope.forEach (package:front_end/src/fasta/scope.dart:528:5)
#12     SourceLoader.computeLibraryScopes
(package:front_end/src/fasta/source/source_loader.dart:1103:30)
#13     KernelTarget.buildOutlines.<anonymous closure>
(package:front_end/src/fasta/kernel/kernel_target.dart:408:14)
<asynchronous suspension>
#14     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#15     IncrementalCompiler.computeDelta.<anonymous closure>
(package:front_end/src/fasta/incremental_compiler.dart:316:38)
<asynchronous suspension>
#16     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:69:29)
<asynchronous suspension>
#17     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:521:11)
<asynchronous suspension>
#18     listenAndCompile.<anonymous closure>
(package:frontend_server/frontend_server.dart:1135:11)
<asynchronous suspension>
the Dart compiler exited unexpectedly.
the Dart compiler exited unexpectedly.
Building Windows application...                                        |
```

Doctor:
<details>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 2.6.0-12.0.pre.511, on Microsoft Windows [Version 10.0.18363.1854], locale en-CA)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Professional 2019 16.11.3)
[√] Android Studio (version 4.1)
[√] VS Code (version 1.58.2)
[√] Connected device (4 available)

! Doctor found issues in 1 category.
```
</details>

**Comment by johnniwinther** [comment]
cc @jensjoha

**Comment by jensjoha** [comment]
Generally the sdk-hash built into the dill should have caught this. It seems that the flutter platform does include it, but that the creation of the flutter_frontend_server snapshot does not, meaning that it's not enabled.
@mkustermann wasn't the dill sdk-hash thing mostly build for flutters benefit?

**Comment by mkustermann** [comment]
> @mkustermann wasn't the dill sdk-hash thing mostly build for flutters benefit?

Not that I know of - it's for the benefit of everyone. We've had g3 users uploading dill files to storage and using them on different versions of VM - causing hard to debug crashes. Similarly `pub` was caching dill files in the `.dart_tool` folder on and re-used them with incompatible VM versions.

If any dill files are missing the SDK hash we should just add it!

**Comment by mkustermann** [comment]
> It seems that the flutter platform does include it, but that the creation of the flutter_frontend_server snapshot
> does not, meaning that it's not enabled.

So for me it seems that giving dill files with incorrect SDK hash to the `frontend_server` will make it error: I use two checkouts of the Dart SDK (`$HOME/sdk3` from which I'll use an old platform dill and `$HOME/sdk4` from which I build frontend-server):
```
% out/ReleaseX64/dart-sdk/bin/dart out/ReleaseX64/dart-sdk/bin/snapshots/frontend_server.dart.snapshot
    --train \
    --sdk-root=$HOME/sdk3/out/ReleaseX64 \
    --platform=$HOME/sdk3/out/ReleaseX64/vm_platform_strong.dill \
    hello.dart
result 48ab6858-b277-4712-87d8-1794dd8457ab
Unhandled exception:
Unexpected Kernel SDK Version 14bcf0f3d4 (expected 065b5bc9f9).
#0      BinaryBuilder._readAndVerifySdkHash (package:kernel/binary/ast_from_binary.dart:611:7)
#1      BinaryBuilder.readComponent.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:643:7)
#2      Timeline.timeSync (dart:developer/timeline.dart:163:22)
#3      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:627:21)
#4      IncrementalCompiler.prepareSummary (package:front_end/src/fasta/incremental_compiler.dart:1747:12)
#5      IncrementalCompiler.ensurePlatformAndInitialize (package:front_end/src/fasta/incremental_compiler.dart:1232:23)
<asynchronous suspension>
#6      IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:248:11)
<asynchronous suspension>
#7      IncrementalCompiler.compile (package:vm/incremental_compiler.dart:69:29)
<asynchronous suspension>
#8      FrontendCompiler.compile (file:///.../sdk4/pkg/frontend_server/lib/frontend_server.dart:521:11)
<asynchronous suspension>
#9      starter (file:///.../sdk4/pkg/frontend_server/lib/frontend_server.dart:1342:7)
<asynchronous suspension>
#10     main (file:///.../sdk4/pkg/frontend_server/bin/frontend_server_starter.dart:9:14)
<asynchronous suspension>
```

=> The frontend server we build as part of the Dart SDK (which I believe is what Flutter uses) seems to have the right SDK hash in it and validates dill files given to it correctly.

The only way it would not error is if the dill file given to it has `0000000000` as it's SDK hash (which only happens if a build opts explicitly out by setting the `verify_sdk_hash` GN setting to `false` - see https://github.com/dart-lang/sdk/blob/main/sdk_args.gni#L31)

**Comment by jensjoha** [comment]
Flutter doesn't use the dart frontend_server snapshot -- it rolls it's own flutter_frontend_server (`https://github.com/flutter/engine/tree/master/flutter_frontend_server`). My guess would be that it isn't compiled with the hash. Namely I dug this out of the `toolchain.ninja` file in my engine out host directory:

```
  command = python3 ../../third_party/dart/build/gn_run_binary.py compiled_action dart --disable-dart-dev --deterministic --packages=/path/to/flutter/engine/src/flutter/flutter_frontend_server/.dart_tool/package_config.json --snapshot=/path/to/flutter/engine/src/out/host_debug/gen/frontend_server.dart.snapshot --snapshot-depfile=/path/to/flutter/engine/src/out/host_debug/gen/frontend_server.dart.snapshot.d --depfile-output-filename=gen/frontend_server.dart.snapshot --snapshot-kind=app-jit /path/to/flutter/engine/src/flutter/flutter_frontend_server/bin/starter.dart --train --sdk-root=/path/to/flutter/engine/src/out/host_debug/flutter_patched_sdk /path/to/flutter/engine/src/flutter/flutter_frontend_server/bin/starter.dart
```

which does not contain `-Dsdk_hash=whatnot`.

**Comment by mkustermann** [comment]
> Flutter doesn't use the dart frontend_server snapshot  ...

Actually it does seem it uses Dart SDK's frontend_server (e.g. [here](https://github.com/flutter/engine/blob/master/testing/testing.gni#L74)) as well as it's own.

Have made a PR to add this to Flutter's build of it's own frontend-server in https://github.com/flutter/engine/pull/29497

**Comment by jensjoha** [comment]
It was caused by a change in the expectation of how redirecting factories was encoded without a bump of the actual kernel version. As such, yeah, the sdk hash would have stopped it from crashing by serving as an implicit version number that mismatched.

**Comment by Piinks** [comment]
Ran into this today as well on Mac. `flutter doctor` is not as helpful since the version tag is off. v2.8 shipped yesterday, but on master flutter doctor reports 2.6 because of the last dev tag.

<details>
  <summary>Console error</summary>

```
Unhandled exception:
type 'StaticGet' is not a subtype of type 'ConstructorTearOff' in type cast
#0      getRedirectingFactories (package:front_end/src/fasta/kernel/redirecting_factory_body.dart:41:43)
#1      DillLibraryBuilder.addClass (package:front_end/src/fasta/dill/dill_library_builder.dart:196:34)
#2      List.forEach (dart:core-patch/growable_array.dart:410:8)
#3      DillLibraryBuilder.ensureLoaded (package:front_end/src/fasta/dill/dill_library_builder.dart:105:21)
#4      LazyLibraryScope.ensureScope (package:front_end/src/fasta/dill/dill_library_builder.dart:61:21)
#5      LazyScope._local (package:front_end/src/fasta/scope.dart:630:5)
#6      Scope.lookupLocalMember (package:front_end/src/fasta/scope.dart:408:38)
#7      DillLibraryBuilder.finalizeExports (package:front_end/src/fasta/dill/dill_library_builder.dart:414:35)

#8      DillLibraryBuilder.ensureLoaded (package:front_end/src/fasta/dill/dill_library_builder.dart:127:7)
#9      LazyLibraryScope.ensureScope (package:front_end/src/fasta/dill/dill_library_builder.dart:61:21)
#10     LazyScope._local (package:front_end/src/fasta/scope.dart:630:5)
#11     new ScopeLocalDeclarationIterator (package:front_end/src/fasta/scope.dart:847:23)
#12     Scope.iterator (package:front_end/src/fasta/scope.dart:132:16)
#13     new LibraryLocalDeclarationIterator (package:front_end/src/fasta/builder/library_builder.dart:450:34)
#14     LibraryBuilderImpl.iterator (package:front_end/src/fasta/builder/library_builder.dart:236:16)
#15     IncrementalCompiler._initializeExperimentalInvalidation (package:front_end/src/fasta/incremental_compiler.dart:1091:44)
#16     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:301:17)
<asynchronous suspension>

#17     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:69:50)
<asynchronous suspension>
#18     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:531:11)
<asynchronous suspension>
#19     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1150:11)
<asynchronous suspension>

2
the Dart compiler exited unexpectedly.

```

</details>


<details>
  <summary>flutter doctor</summary>

```
[✓] Flutter (Channel master, 2.6.0-12.0.pre.979, on macOS 12.0.1 21A559 darwin-x64,
    locale en-US)
    • Flutter version 2.6.0-12.0.pre.979 at /Users/katelovett/github/flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision be0e388687 (37 minutes ago), 2021-12-09 12:04:06 -0500
    • Engine revision 59778ae91c
    • Dart version 2.16.0 (build 2.16.0-85.0.dev)
    • DevTools version 2.9.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
    • Android SDK at /Users/katelovett/Library/Android/sdk
    • Platform android-31, build-tools 32.0.0-rc1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! CocoaPods 1.8.4 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that
        responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.3)
    • IntelliJ at /Applications/IntelliJ UE (stable).app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.63.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • 9ADA8097-18C9-4827-8861-9B725FFAF705 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • macOS
      12.0.1 21A559 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript •
      Google Chrome 96.0.4664.93

! Doctor found issues in 1 category.
```

</details>
