### ISSUE TITLE
[image_picker][Android] ImagePicker crashes with `IllegalStateException: Only owner is able to interact with pending media` when selecting images in certain directories

### ISSUE THREAD

**Issue by TennisAndy** [flutter/flutter#92707]
`image_picker: 0.8.3+3`

Device:
Huawei nova 8 ANG-AN00
HarmonyOS 2.0.0.168

Code:

```dart
Future<File> onChooseAndCropImage(BuildContext context, int value) async {
        ImagePicker _picker = ImagePicker();
        final imageFile = await _picker.getImage(
                 source: value == 0 ? ImageSource.camera : ImageSource.gallery);
        fdLogi("[onChooseAndCropImage]选取图片: ${imageFile.path}");
        return await XRouter.push(Routes.appImageCropper,
                queryParams: {'filePath': imageFile.path});
 }
```

Reproduce:
1.Pick a image from album
2.It will crash when I choose the 3rd image in video.

Here is the video log:

https://user-images.githubusercontent.com/9261741/139398382-28a264ec-adcd-44f8-be29-d91994a59414.mp4

The path of test imge 1 is: /sdcard/Pictures/Screenshots/Screenshot_20211013_154253_com.fdage.turn.dual.jpg
The path of test imge 2 is: /sdcard/Pictures/Screenshots/helios-icon.JPG
The path of test imge 3 is: /sdcard/Pictures/com.baidu.input_huawei/helios/helios-icon.JPG

Tips: The image 2 was copied form image 3 to /sdcard/Pictures/, and it is ok.

<details>
<summary>Stack</summary>

```console
2021-10-29 15:53:09
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2342, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/image:30 flg=0x1 }} to activity {com.fdage.turn.dual/com.fdage.turn.dual.page.MainActivity}: java.lang.IllegalStateException: Only owner is able to interact with pending media content://media/external/images/media/30
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5782)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5823)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
Caused by: java.lang.IllegalStateException: Only owner is able to interact with pending media content://media/external/images/media/30
	at android.os.Parcel.createException(Parcel.java:2098)
	at android.os.Parcel.readException(Parcel.java:2058)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:188)
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:705)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1698)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1514)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:1198)
	at io.flutter.plugins.imagepicker.FileUtils.getPathFromUri(FileUtils.java:45)
	at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseImageResult(ImagePickerDelegate.java:482)
	at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:459)
	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:741)
	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:426)
	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:749)
	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:651)
	at com.fdage.turn.dual.page.MainActivity.onActivityResult(MainActivity.kt:416)
	at android.app.Activity.dispatchActivityResult(Activity.java:8541)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5775)
	... 11 more
```
</details>

Dev env:
<details>
<summary>flutter doctor -v</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19042.1165], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
[√] VS Code (version 1.54.3)
[√] Connected device (3 available)

• No issues found!
```
</details>

**Comment by TennisAndy** [comment]
> Hi @TennisAndy, thanks for filing this issue.
> 
> Can you check with the latest version of `image_picker` to see if you still experience this issue?
> 
> Also, do you have any other devices that you can check if you experience this issue with?
> 
> Thank you

Hi @danagbemava-nc, I updated to image_picker: ^0.8.4+4, but still crash. Please help to check:
`2021-11-01 09:18:00.548 32176-32176/com.fdage.turn.dual I/Flutter拦截: [onAvatarEdit]相册权限isGranted: true, isDenied: false
2021-11-01 09:18:00.573 32176-32176/com.fdage.turn.dual D/CrashReport: >>> com.fdage.turn.dual.MainActivity onPaused <<<
2021-11-01 09:18:00.574 32176-32176/com.fdage.turn.dual I/CrashReport-Native: jni_setNativeInfo: key is 14
2021-11-01 09:18:00.574 32176-32176/com.fdage.turn.dual I/CrashReport-Native: Set native info: isAppForeground(false)
2021-11-01 09:18:00.620 32176-32176/com.fdage.turn.dual D/DecorView: showOrHideHighlightView: hasFocus=false; winMode=1; isMrgNull=true
2021-11-01 09:18:00.794 32176-32176/com.fdage.turn.dual I/RmeSchedManager: init Rme, version is: v1.0
2021-11-01 09:18:01.051 32176-32259/com.fdage.turn.dual W/libEGL: EGLNativeWindowType 0x74d7de8010 disconnect failed
2021-11-01 09:18:01.055 32176-32229/com.fdage.turn.dual W/libEGL: EGLNativeWindowType 0x75793f5cd0 disconnect failed
2021-11-01 09:18:01.463 32176-32211/com.fdage.turn.dual D/ZrHung.AppEyeUiProbe: not watching, wait.
2021-11-01 09:18:02.465 32176-32176/com.fdage.turn.dual D/ActivityThread: Won't deliver top position change in state=5
2021-11-01 09:18:02.508 32176-32176/com.fdage.turn.dual I/BlockMonitor: dispatchingThrewException In MainThread
2021-11-01 09:18:02.508 32176-32176/com.fdage.turn.dual D/AndroidRuntime: Shutting down VM
2021-11-01 09:18:02.508 32176-32176/com.fdage.turn.dual I/QarthLog: [PatchStore] createDisableExceptionQarthFile
2021-11-01 09:18:02.508 32176-32176/com.fdage.turn.dual I/QarthLog: [PatchStore] create disable file for com.fdage.turn.dual uid is 10224
2021-11-01 09:18:02.511 32176-32176/com.fdage.turn.dual E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.fdage.turn.dual, PID: 32176
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2342, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/image:30 flg=0x1 }} to activity {com.fdage.turn.dual/com.fdage.turn.dual.MainActivity}: java.lang.IllegalStateException: Only owner is able to interact with pending media content://media/external/images/media/30
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5782)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5823)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8668)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
     Caused by: java.lang.IllegalStateException: Only owner is able to interact with pending media content://media/external/images/media/30
        at android.os.Parcel.createException(Parcel.java:2098)
        at android.os.Parcel.readException(Parcel.java:2058)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:188)
        at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
        at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:705)
        at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1698)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1514)
        at android.content.ContentResolver.openInputStream(ContentResolver.java:1198)
        at io.flutter.plugins.imagepicker.FileUtils.getPathFromUri(FileUtils.java:45)
        at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseImageResult(ImagePickerDelegate.java:487)
        at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:464)
        at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:741)
        at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:426)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:749)
        at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:651)
        at com.fdage.turn.dual.MainActivity.onActivityResult(MainActivity.kt:161)
        at android.app.Activity.dispatchActivityResult(Activity.java:8541)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5775)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5823) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613) 
        at android.os.Handler.dispatchMessage(Handler.java:110) 
        at android.os.Looper.loop(Looper.java:219) 
        at android.app.ActivityThread.main(ActivityThread.java:8668) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109) 
2021-11-01 09:18:02.511 32176-32176/com.fdage.turn.dual E/CrashReport: Java Crash Happen cause by main(1)
2021-11-01 09:18:02.514 32176-32176/com.fdage.turn.dual W/CrashReport: no read_log permission!
2021-11-01 09:18:02.514 32176-32176/com.fdage.turn.dual I/CrashReport: user log size:0
2021-11-01 09:18:02.514 32176-32176/com.fdage.turn.dual E/CrashReport: stack frame :12, has cause true
2021-11-01 09:18:02.517 32176-32176/com.fdage.turn.dual E/CrashReport: #++++++++++Record By Bugly++++++++++#
2021-11-01 09:18:02.517 32176-32176/com.fdage.turn.dual E/CrashReport: # You can use Bugly(http:\\bugly.qq.com) to get more Crash Detail!
2021-11-01 09:18:02.517 32176-32176/com.fdage.turn.dual E/CrashReport: # PKG NAME: com.fdage.turn.dual
2021-11-01 09:18:02.517 32176-32176/com.fdage.turn.dual E/CrashReport: # APP VER: 1.0.2.2
2021-11-01 09:18:02.517 32176-32176/com.fdage.turn.dual E/CrashReport: # SDK VER: 3.4.12(1.5.23)-3.9.0
2021-11-01 09:18:02.517 32176-32176/com.fdage.turn.dual E/CrashReport: # LAUNCH TIME: 2021-11-01 09:17:44
2021-11-01 09:18:02.517 32176-32176/com.fdage.turn.dual E/CrashReport: # CRASH TYPE: JAVA_CRASH
2021-11-01 09:18:02.517 32176-32176/com.fdage.turn.dual E/CrashReport: # CRASH TIME: 2021-11-01 09:18:02
2021-11-01 09:18:02.517 32176-32176/com.fdage.turn.dual E/CrashReport: # CRASH PROCESS: com.fdage.turn.dual
2021-11-01 09:18:02.517 32176-32176/com.fdage.turn.dual E/CrashReport: # CRASH THREAD: main
2021-11-01 09:18:02.517 32176-32176/com.fdage.turn.dual E/CrashReport: # REPORT ID: ee0bd169-2f69-4789-aaad-80c44e681009
2021-11-01 09:18:02.517 32176-32176/com.fdage.turn.dual E/CrashReport: # CRASH DEVICE: ANG-AN00 UNROOT
2021-11-01 09:18:02.517 32176-32176/com.fdage.turn.dual E/CrashReport: # RUNTIME AVAIL RAM:3204898816 ROM:92243234816 SD:92222255104
2021-11-01 09:18:02.517 32176-32176/com.fdage.turn.dual E/CrashReport: # RUNTIME TOTAL RAM:7888637952 ROM:116725383168 SD:116704411648
2021-11-01 09:18:02.517 32176-32176/com.fdage.turn.dual E/CrashReport: # CRASH STACK: 
2021-11-01 09:18:02.517 32176-32176/com.fdage.turn.dual E/CrashReport: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2342, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/image:30 flg=0x1 }} to activity {com.fdage.turn.dual/com.fdage.turn.dual.MainActivity}: java.lang.IllegalStateException: Only owner is able to interact with pending media content://media/external/images/media/30
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5782)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5823)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8668)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
     Caused by: java.lang.IllegalStateException: Only owner is able to interact with pending media content://media/external/images/media/30
        at android.os.Parcel.createException(Parcel.java:2098)
        at android.os.Parcel.readException(Parcel.java:2058)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:188)
        at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
        at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:705)
        at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1698)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1514)
        at android.content.ContentResolver.openInputStream(ContentResolver.java:1198)
        at io.flutter.plugins.imagepicker.FileUtils.getPathFromUri(FileUtils.java:45)
        at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseImageResult(ImagePickerDelegate.java:487)
        at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:464)
        at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:741)
        at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:426)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:749)
        at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:651)
        at com.fdage.turn.dual.MainActivity.onActivityResult(MainActivity.kt:161)
        at android.app.Activity.dispatchActivityResult(Activity.java:8541)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5775)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5823) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613) 
        at android.os.Handler.dispatchMessage(Handler.java:110) 
        at android.os.Looper.loop(Looper.java:219) 
        at android.app.ActivityThread.main(ActivityThread.java:8668) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109) `

**Comment by danagbemava-nc** [comment]
Hi @TennisAndy, I can't seem to reproduce this issue and from what I've seen, it seems to indicate an issue with the particular image you're selecting rather than the path, see this [SO](https://stackoverflow.com/a/66812986/10630669) comment. 

Can you try wrapping your image picking code in a `try/catch` to see whether or not the exception is handled properly? 

Thank you

**Comment by TennisAndy** [comment]
> Hi @TennisAndy, I can't seem to reproduce this issue and from what I've seen, it seems to indicate an issue with the particular image you're selecting rather than the path, see this [SO](https://stackoverflow.com/a/66812986/10630669) comment.
> 
> Can you try wrapping your image picking code in a `try/catch` to see whether or not the exception is handled properly?
> 
> Thank you

Hi @danagbemava-nc , it should be an issue about the selecting file path, because the 2rd image from video is the same file copied from the 3th image. They are the same file but in different paths. I tried a try/catch around the code, but fail:
![image](https://user-images.githubusercontent.com/9261741/139632594-5d62231b-1aab-4189-b3e7-ac4048b8e8e5.png)
It throws exception at onActivityResult of FlutterActivity. 
![image](https://user-images.githubusercontent.com/9261741/139633055-cd7a03c5-12e0-4926-89b6-f80646640f8a.png)
And I also try/catch here and handle it no crash, but image picker return no result.

**Comment by danagbemava-nc** [comment]
Thanks for confirming that it still crashes with the image picking code wrapped in a `try/catch`. 

> Tips: The image 2 was copied form image 3 to /sdcard/Pictures/, and it is ok.

I somehow missed this from your initial comment. 

Labelling for further investigation as I cannot reproduce on my end.

**Comment by TennisAndy** [comment]
Well，can we add a try/catch here and invoke `this.finishWithSuccess((String)null);` to flutter
![image](https://user-images.githubusercontent.com/9261741/140241741-4981faa7-0947-4e96-9a4e-33e3ea9d50a5.png)
so that we can handle this exception and hint user choose image failed.

**Comment by parthpatel-simbiotik** [comment]
is Flutter apps run on HarmonyOS? How we can publish the Flutter App on Harmony OS AppGallary?

**Comment by TennisAndy** [comment]
@parthpatel-simbiotik yes, we can install apk on Harmony OS, just like in Android.

**Comment by danagbemava-nc** [comment]
@TennisAndy, have you resolved this issue on your end?
