### ISSUE TITLE
CallbackShortcuts with SingleActivator does not work as expected

### ISSUE THREAD

**Issue by teemu-kemppainen** [flutter/flutter#92717]
## Steps to Reproduce

1. Modify `test/widgets/shortcuts_test.dart` file as shown in the code sample.
2. Execute `flutter test test/widgets/shortcuts_test.dart` where the file is modified as shown in the code sample 

**Expected results:** 
- CallbackShortcuts with SingleActivator is expected to call a callback if a key or a key with modifiers (e.g. ctrl + c) is pressed.
- The modified tests pass.

**Actual results:** 
- CallbackShortcuts with SingleActivator calls the callback with any key, including the modifier key.
- The modified tests fail.

This code sample is a modified copy of the tests in `packages/flutter/test/widgets/shortcuts_test.dart` -> `group('CallbackShortcuts')`
<details>
<summary>Code sample</summary>

```dart
testWidgets('trigger on key events', (WidgetTester tester) async {
  // This test is modified

  int invoked = 0;
  await tester.pumpWidget(
    CallbackShortcuts(
      bindings: <ShortcutActivator, VoidCallback>{
        const SingleActivator(LogicalKeyboardKey.keyA): () { // Should invoke only with key 'a'
          invoked += 1;
        },
      },
      child: const Focus(
        autofocus: true,
        child: Placeholder(),
      ),
    ),
  );
  await tester.pump();
  
  await tester.sendKeyDownEvent(LogicalKeyboardKey.keyA);
  expect(invoked, equals(1));
  await tester.sendKeyUpEvent(LogicalKeyboardKey.keyA);
  expect(invoked, equals(1));

  // The following should NOT trigger
  await tester.sendKeyDownEvent(LogicalKeyboardKey.keyB);
  expect(invoked, equals(1)); // This fails
  await tester.sendKeyUpEvent(LogicalKeyboardKey.keyB);
  expect(invoked, equals(1));
});

testWidgets('trigger on key events with modifiers', (WidgetTester tester) async {
  // This test is added

  int invoked = 0;
  await tester.pumpWidget(
  CallbackShortcuts(
    bindings: <ShortcutActivator, VoidCallback>{
      const SingleActivator(LogicalKeyboardKey.keyA, control: true): () { // Should invoke only with 'ctrl + a'
        invoked += 1;
      },
    },
    child: const Focus(
      autofocus: true,
      child: Placeholder(),
    ),
  ),
  );
  await tester.pump();
  
  await tester.sendKeyDownEvent(LogicalKeyboardKey.controlLeft);
  await tester.sendKeyDownEvent(LogicalKeyboardKey.keyA);
  expect(invoked, equals(1)); // This fails
  await tester.sendKeyUpEvent(LogicalKeyboardKey.keyA);
  await tester.sendKeyUpEvent(LogicalKeyboardKey.controlLeft);
  expect(invoked, equals(1));
});
```

</details>

<details>
  <summary>Logs</summary>

```
00:04 +32: CallbackShortcuts trigger on key events                                                                                                                                                                                          
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
  Expected: <1>
  Actual: <2>

When the exception was thrown, this was the stack:
#4      main.<anonymous closure>.<anonymous closure> (file:///home/xxx/flutter/packages/flutter/test/widgets/shortcuts_test.dart:1147:7)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///home/xxx/flutter/packages/flutter/test/widgets/shortcuts_test.dart line 1147
The test description was:
  trigger on key events
════════════════════════════════════════════════════════════════════════════════════════════════════
00:04 +32 -1: CallbackShortcuts trigger on key events [E]                                                                                                                                                                                   
  Test failed. See exception logs above.
  The test description was: trigger on key events
```
```
00:04 +32 -1: CallbackShortcuts trigger on key events with modifiers                                                                                                                                                                        
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
  Expected: <1>
  Actual: <2>

When the exception was thrown, this was the stack:
#4      main.<anonymous closure>.<anonymous closure> (file:///home/xxx/flutter/packages/flutter/test/widgets/shortcuts_test.dart:1171:7)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///home/xxx/flutter/packages/flutter/test/widgets/shortcuts_test.dart line 1171
The test description was:
  trigger on key events with modifiers
════════════════════════════════════════════════════════════════════════════════════════════════════
00:04 +32 -2: CallbackShortcuts trigger on key events with modifiers [E]                                                                                                                                                                    
  Test failed. See exception logs above.
  The test description was: trigger on key events with modifiers
  
00:04 +35 -2: Some tests failed.                                               
```
</details>

## Likely issue
`CallbackShortcuts` implementation triggers on every key event and checks `activator.accepts`:
```dart
  bool _applyKeyBinding(ShortcutActivator activator, RawKeyEvent event) {
    if (activator.accepts(event, RawKeyboard.instance)) { // This only checks if the activator accepts
      bindings[activator]!.call();
      return true;
    }
    return false;
  }

  @override
  Widget build(BuildContext context) {
    return Focus(
      canRequestFocus: false,
      skipTraversal: true,
      onKey: (FocusNode node, RawKeyEvent event) { // This fires on any key event
        KeyEventResult result = KeyEventResult.ignored;
        // Activates all key bindings that match, returns "handled" if any handle it.
        for (final ShortcutActivator activator in bindings.keys) {
          result = _applyKeyBinding(activator, event) ? KeyEventResult.handled : result;
        }
        return result;
      },
      child: child,
    );
  }
```
And `SingleActivator::accepts` implementation only checks if a modifier key is pressed (as should per `ShortcutActivator` documentation, see below). 
```dart
  @override
  bool accepts(RawKeyEvent event, RawKeyboard state) {
    final Set<LogicalKeyboardKey> pressed = state.keysPressed;
    return event is RawKeyDownEvent
      && (control == (pressed.contains(LogicalKeyboardKey.controlLeft) || pressed.contains(LogicalKeyboardKey.controlRight)))
      && (shift == (pressed.contains(LogicalKeyboardKey.shiftLeft) || pressed.contains(LogicalKeyboardKey.shiftRight)))
      && (alt == (pressed.contains(LogicalKeyboardKey.altLeft) || pressed.contains(LogicalKeyboardKey.altRight)))
      && (meta == (pressed.contains(LogicalKeyboardKey.metaLeft) || pressed.contains(LogicalKeyboardKey.metaRight)));
  }
```
`ShortcutActivator` documentation says:
```dart
  /// Whether the triggering `event` and the keyboard `state` at the time of the
  /// event meet required conditions, providing that the event is a triggering
  /// event.
  ///
  /// For example, for `Ctrl-A`, it has to check if the event is a
  /// [KeyDownEvent], if either side of the Ctrl key is pressed, and none of
  /// the Shift keys, Alt keys, or Meta keys are pressed; it doesn't have to
  /// check if KeyA is pressed, since it's already guaranteed.
  ///
  /// This method must not cause any side effects for the `state`. Typically
  /// this is only used to query whether [HardwareKeyboard.logicalKeysPressed]
  /// contains a key.
  ///
  /// Since [ShortcutActivator] accepts all event types, subclasses might want
  /// to check the event type in [accepts].
  ///
  /// See also:
  ///
  ///  * [LogicalKeyboardKey.collapseSynonyms], which helps deciding whether a
  ///    modifier key is pressed when the side variation is not important.
  bool accepts(RawKeyEvent event, RawKeyboard state);
```

It seems that `CallbackShortcuts` should check the activator triggers, and only after that call `ShortcutActivator::accepts`, as it should be guaranteed that the triggering key is pressed when checking `accepts`. Alternatively, `SingleActivator::accepts` could check if the event is a triggering key, but that seems to go against the documentation.

**Comment by esDotDev** [comment]
This can be shown very simply with a `CallbackShortcuts` widget. No matter what key you press, both actions are fired off.
```
CallbackShortcuts(
  bindings: {
    const SingleActivator(LogicalKeyboardKey.digit1): () => print(1),
    const SingleActivator(LogicalKeyboardKey.digit2): () => print(2),
  },
  child: Focus(
    autofocus: true,
    child: ... )
)
```

**Comment by csells** [comment]
adding this for desktop stable consideration based on feedback from @whiplashoo:

> While I found [the Shortcuts tutorial](https://flutter.dev/docs/development/ui/advanced/actions_and_shortcuts) really useful, I came across this issue that wouldn't let me use a simpler version of the Shortcuts API (CallbackShortcuts). It was also pretty frustrating to troubleshoot this (any key press activates the Shortcut!) before I found there exists an issue with the framework there.

**Comment by gspencergoog** [comment]
Thanks for the report!  This is indeed broken.  See the above PR for a fix.
