### ISSUE TITLE
HardwareKeyboard issues on Windows

### ISSUE THREAD

**Issue by SuhailAlhegry** [flutter/flutter#92746]
Try holding a modifier key and unfocusing the window (by switching to another
window or clicking outside of the window region) the key will still be reported
as being repeated (held) even though it is not, this crashes the app sometimes
due to HardwareKeyboard asserting that logical keys have corresponding physical 
keys. Additionally, pressing 'shift' and 'ctrl' together or holding 'alt' crashes
the app regardless.

This issue (as reported by HardwareKeyboard diagnostics) is a result of improper
physical key events handling (up, down, and repeat). And will show itself when
pressing any key then holding the modifier key 'right shift' for about a second,
letting down of the modifier WILL NOT fire a 'key up' event, and thus result in
all-caps text, and some other annoying issues, like backspace not working.

A simple workaround to this particular problem is pressing the 'left shift'
resulting in logical key 'shift' firing a 'key up' event and releasing the modifier.

This is interesting, because it may mean that the problem relies within the code
that maps physical key events to logical key events (or vice versa).

## Steps to Reproduce

1. Execute `flutter run -d windows` on the code sample 
2. Press ```right shift``` + ```right ctrl```

**Expected results:** nothing happens

**Actual results:** app crashes

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(App());
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Invistigating keyboard issues',
      home: TextFieldPage(initialText: 'Flutter Demo Home Page'),
    );
  }
}

class TextFieldPage extends StatefulWidget {
  final String initialText;

  const TextFieldPage({Key? key, required this.initialText}) : super(key: key);

  @override
  State<TextFieldPage> createState() => _TextFieldPageState();
}

class _TextFieldPageState extends State<TextFieldPage> {
  late TextEditingController controller;

  @override
  void initState() {
    super.initState();
    controller = TextEditingController(text: widget.initialText);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.initialText),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              '''
Try holding a modifier key and unfocusing the window (by switching to another
window or clicking outside of the window region) the key will still be reported
as being repeated (held) even though it is not, this crashes the app sometimes
due to HardwareKeyboard asserting that logical keys have corresponding physical 
keys. Additionally, pressing 'shift' and 'ctrl' together or holding 'alt' crashes
the app regardless.

This issue (as reported by HardwareKeyboard diagnostics) is a result of improper
physical key events handling (up, down, and repeat). And will show itself when
pressing any key then holding the modifier key 'right shift' for about a second,
letting down of the modifier WILL NOT fire a 'key up' event, and thus result in
all-caps text, and some other annoying issues, like backspace not working.

A simple workaround to this particular problem is pressing the 'left shift'
resulting in logical key 'shift' firing a 'key up' event and releasing the modifier.

This is interesting, because it may mean that the problem relies within the code
that maps physical key events to logical key events (or vice versa).
              ''',
            ),
            TextField(
              controller: controller,
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```The following assertion was thrown during a platform message callback:
A KeyRepeatEvent is dispatched, but the state shows that the physical key is not pressed. If this
occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please
ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This
was the event: KeyRepeatEvent#eeaf9(physicalKey: PhysicalKeyboardKey#700e2(usbHidUsage:
"0x000700e2", debugName: "Alt Left"), logicalKey: LogicalKeyboardKey#00104(keyId: "0x200000104",
keyLabel: "Alt Left", debugName: "Alt Left"), character: null, timeStamp: 273:24:21.384659)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 441 pos 16: '_pressedKeys.containsKey(event.physicalKey)'

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack:
#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:441:16)
#3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:452:6)
#4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:543:5)
#5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:821:35)
#6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:73:49)
#7      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:72:47)
#8      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:379:35)
#9      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:376:46)
#10     _invoke2.<anonymous closure> (dart:ui/hooks.dart:205:15)
#14     _invoke2 (dart:ui/hooks.dart:204:10)
#15     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#16     _Channel.push (dart:ui/channel_buffers.dart:132:31)
#17     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#18     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:544:22)
#19     _dispatchPlatformMessage (dart:ui/hooks.dart:92:31)
(elided 5 frames from class _AssertionError and dart:async)
```

```
[√] Flutter (Channel stable, 2.5.2, on Microsoft Windows [Version 10.0.19042.545], locale en-US)
    • Flutter version 2.5.2 at C:\mobile\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (4 weeks ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\android\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\android\sdk
    • Java binary at: C:\Java\jdk1.8.0_111\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31727.386
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.61.2)
    • VS Code at C:\Users\RYUK\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.27.0

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.545]
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 94.0.992.50

! Doctor found issues in 2 categories.
```

</details>

**Comment by darshankawar** [comment]
@SuhailAlhegry 
This is a known issue at the moment and there's an open issue for tracking, https://github.com/flutter/flutter/issues/89982
Please follow-up in it for further updates.
Closing this as a duplicate.

**Comment by dkwingsmt** [comment]
Regarding the main issue you described (RCtrl + RShift), I tested that it was reproducible on your revision, but not on master. It's like fixed by https://github.com/flutter/engine/pull/29282.

I see you seem to have other issues. Can you try if they persist on master and if so, reopen this issue with their reproduction steps? Thank you.

**Comment by darshankawar** [comment]
I also verified this on latest master and it doesn't seem to replicate anymore.
