### ISSUE TITLE
Textfield callback called twice on emulator

### ISSUE THREAD

**Issue by Mayank-9018** [flutter/flutter#92782]
## Steps to Reproduce

1. Run this code on Android Emulator:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: Scaffold(
      body: Center(
        child: TextField(
          onChanged: callback,
        ),
      ),
    ));
  }

  void callback(String s) {
    print(s);
  }
}
```
2. Start typing in the textfield.

**Expected results:** 

The callback method should be called only once on value change.

**Actual results:** 

The callback method is called twice when typing from the keyboard and not the soft keyboard.

https://user-images.githubusercontent.com/77046231/139575604-b1a0daee-d785-483c-a675-daac5e790236.mp4

When typing from the soft keyboard, the callback method is called only once, but twice when typing from physical keyboard.
<details>

Android Studio Vesion: 2020.3.1 Patch 3
Android Emulator Version: 30.9.5
System Image: Android 12 x86_64

<details>

```
[✓] Flutter (Channel stable, 2.5.3, on Pop!_OS 21.04 5.13.0-7620-generic, locale
    en_US.UTF-8)
    • Flutter version 2.5.3 at /home/mayank-pop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (2 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/mayank-pop/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 12.0.0-3ubuntu1~21.04.2
    • cmake version 3.18.4
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2020.3)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 61.2.2
    • Dart plugin version 203.8430
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.61.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.27.0

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12
      (API 31) (emulator)
    • Linux (desktop)              • linux         • linux-x64      • Pop!_OS
      21.04 5.13.0-7620-generic
    • Chrome (web)                 • chrome        • web-javascript • Google
      Chrome 95.0.4638.69

• No issues found!

```

</details>

**Comment by maheshmnj** [comment]
Hi @Mayank-9018,  thanks for filing the issue I was able to reproduce the issue on the latest stable 2.5.3 and the 
`master 2.6.0-12.0.pre.536` channel. This issue is specific to Android 12.  

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.5.3, on Ubuntu 20.04.3 LTS 5.11.0-38-generic, locale en_GB.UTF-8)
    • Flutter version 2.5.3 at /home/mahesh/flutter_sdk/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (2 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/mahesh/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /snap/android-studio/115/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /snap/android-studio/115/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.27.0

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Linux (desktop)              • linux         • linux-x64      • Ubuntu 20.04.3 LTS 5.11.0-38-generic
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 94.0.4606.81

• No issues found!
```

```
[✓] Flutter (Channel master, 2.6.0-12.0.pre.536, on Ubuntu 20.04.3 LTS 5.11.0-38-generic, locale en_GB.UTF-8)
    • Flutter version 2.6.0-12.0.pre.536 at /home/mahesh/flutter_sdk/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7b507f6f6e (2 hours ago), 2021-11-01 11:40:48 +0100
    • Engine revision 3a0a63c2d2
    • Dart version 2.15.0 (build 2.15.0-262.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/mahesh/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /snap/android-studio/115/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /snap/android-studio/115/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.27.0

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Linux (desktop)              • linux         • linux-x64      • Ubuntu 20.04.3 LTS 5.11.0-38-generic
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 94.0.4606.81

• No issues found!
````
</details>

<details>
<summary>logs</summary>

```console
Launching lib/main.dart on sdk gphone64 x86 64 in debug mode...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
W/FlutterActivityAndFragmentDelegate( 4464): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
Connecting to VM Service at ws://127.0.0.1:44805/38y_aqyr5lA=/ws
D/InputMethodManager( 4464): showSoftInput() view=io.flutter.embedding.android.FlutterView{66d42b3 VFE...... .F....ID 0,0-1080,2148 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
D/EGL_emulation( 4464): app_time_stats: avg=239.71ms min=0.74ms max=4303.10ms count=31
D/EGL_emulation( 4464): app_time_stats: avg=1836.77ms min=128.38ms max=3545.15ms count=2
W/IInputConnectionWrapper( 4464): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4464): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 4464): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper( 4464): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper( 4464): endBatchEdit on inactive InputConnection
D/InputMethodManager( 4464): showSoftInput() view=io.flutter.embedding.android.FlutterView{66d42b3 VFE...... .F...... 0,0-1080,2148 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
W/IInputConnectionWrapper( 4464): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4464): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4464): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4464): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4464): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4464): endBatchEdit on inactive InputConnection
D/EGL_emulation( 4464): app_time_stats: avg=255.37ms min=122.91ms max=497.37ms count=5
D/InsetsController( 4464): show(ime(), fromIme=true)
D/EGL_emulation( 4464): app_time_stats: avg=2926.50ms min=2926.50ms max=2926.50ms count=1
D/EGL_emulation( 4464): app_time_stats: avg=630.89ms min=427.77ms max=905.83ms count=3
D/InputMethodManager( 4464): showSoftInput() view=io.flutter.embedding.android.FlutterView{66d42b3 VFE...... .F...... 0,0-1080,2148 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
I/flutter ( 4464): a
D/InsetsController( 4464): show(ime(), fromIme=true)
D/InputMethodManager( 4464): showSoftInput() view=io.flutter.embedding.android.FlutterView{66d42b3 VFE...... .F...... 0,0-1080,2148 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
D/InsetsController( 4464): show(ime(), fromIme=true)
I/flutter ( 4464): as
I/TextInputPlugin( 4464): Composing region changed by the framework. Restarting the input method.
W/IInputConnectionWrapper( 4464): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4464): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 4464): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper( 4464): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper( 4464): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4464): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4464): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 4464): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4464): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4464): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 4464): endBatchEdit on inactive InputConnection
D/EGL_emulation( 4464): app_time_stats: avg=325.94ms min=38.87ms max=663.26ms count=4
I/flutter ( 4464): as
D/EGL_emulation( 4464): app_time_stats: avg=362.58ms min=81.14ms max=518.09ms count=3
D/InsetsController( 4464): show(ime(), fromIme=true)
D/InputMethodManager( 4464): showSoftInput() view=io.flutter.embedding.android.FlutterView{66d42b3 VFE...... .F...... 0,0-1080,2148 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
I/flutter ( 4464): asd
I/TextInputPlugin( 4464): Composing region changed by the framework. Restarting the input method.
D/InsetsController( 4464): show(ime(), fromIme=true)
D/InsetsController( 4464): show(ime(), fromIme=true)
I/flutter ( 4464): asd
D/InputMethodManager( 4464): showSoftInput() view=io.flutter.embedding.android.FlutterView{66d42b3 VFE...... .F...... 0,0-1080,2148 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
I/flutter ( 4464): asdf
I/TextInputPlugin( 4464): Composing region changed by the framework. Restarting the input method.
D/InsetsController( 4464): show(ime(), fromIme=true)
W/IInputConnectionWrapper( 4464): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4464): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 4464): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper( 4464): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper( 4464): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4464): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4464): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 4464): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4464): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4464): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 4464): endBatchEdit on inactive InputConnection
D/EGL_emulation( 4464): app_time_stats: avg=373.87ms min=186.95ms max=480.28ms count=3
I/flutter ( 4464): asdf
D/InsetsController( 4464): show(ime(), fromIme=true)
D/EGL_emulation( 4464): app_time_stats: avg=352.86ms min=125.03ms max=505.64ms count=3
D/EGL_emulation( 4464): app_time_stats: avg=500.11ms min=495.90ms max=504.32ms count=2
D/InputMethodManager( 4464): showSoftInput() view=io.flutter.embedding.android.FlutterView{66d42b3 VFE...... .F...... 0,0-1080,2148 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
I/flutter ( 4464): asdfg
I/TextInputPlugin( 4464): Composing region changed by the framework. Restarting the input method.
W/IInputConnectionWrapper( 4464): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4464): getTextBeforeCursor on inactive InputConnection
D/InsetsController( 4464): show(ime(), fromIme=true)
W/IInputConnectionWrapper( 4464): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper( 4464): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper( 4464): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4464): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4464): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 4464): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4464): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4464): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 4464): endBatchEdit on inactive InputConnection
I/flutter ( 4464): asdfg
D/InsetsController( 4464): show(ime(), fromIme=true)
D/EGL_emulation( 4464): app_time_stats: avg=291.75ms min=63.15ms max=519.64ms count=4
D/InputMethodManager( 4464): showSoftInput() view=io.flutter.embedding.android.FlutterView{66d42b3 VFE...... .F...... 0,0-1080,2148 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
I/flutter ( 4464): asdfgh
I/TextInputPlugin( 4464): Composing region changed by the framework. Restarting the input method.
W/ListenableEditingState( 4464): a listener was added to EditingState while a batch edit was in progress
W/IInputConnectionWrapper( 4464): getSelectedText on inactive InputConnection
D/InsetsController( 4464): show(ime(), fromIme=true)
W/IInputConnectionWrapper( 4464): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4464): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4464): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4464): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4464): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 4464): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper( 4464): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper( 4464): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4464): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4464): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 4464): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4464): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4464): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 4464): endBatchEdit on inactive InputConnection
D/InsetsController( 4464): show(ime(), fromIme=true)
D/EGL_emulation( 4464): app_time_stats: avg=518.33ms min=461.17ms max=580.54ms count=3
I/flutter ( 4464): asdfgh
D/EGL_emulation( 4464): app_time_stats: avg=351.52ms min=79.07ms max=499.38ms count=3
D/InputMethodManager( 4464): showSoftInput() view=io.flutter.embedding.android.FlutterView{66d42b3 VFE...... .F...... 0,0-1080,2148 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
I/flutter ( 4464): asdfghj
I/TextInputPlugin( 4464): Composing region changed by the framework. Restarting the input method.
W/IInputConnectionWrapper( 4464): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4464): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 4464): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper( 4464): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper( 4464): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4464): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4464): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 4464): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4464): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4464): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 4464): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper( 4464): getSelectedText on inactive InputConnection
D/InsetsController( 4464): show(ime(), fromIme=true)
W/IInputConnectionWrapper( 4464): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4464): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4464): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 4464): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4464): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4464): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 4464): endBatchEdit on inactive InputConnection
I/flutter ( 4464): asdfghj
D/InsetsController( 4464): show(ime(), fromIme=true)
D/EGL_emulation( 4464): app_time_stats: avg=382.75ms min=197.19ms max=484.24ms count=3
D/EGL_emulation( 4464): app_time_stats: avg=501.33ms min=444.16ms max=558.51ms count=2
D/EGL_emulation( 4464): app_time_stats: avg=498.86ms min=480.92ms max=518.06ms count=3
D/EGL_emulation( 4464): app_time_stats: avg=511.54ms min=505.41ms max=517.68ms count=2
D/InputMethodManager( 4464): showSoftInput() view=io.flutter.embedding.android.FlutterView{66d42b3 VFE...... .F...... 0,0-1080,2148 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
I/flutter ( 4464): asdfghjk
I/TextInputPlugin( 4464): Composing region changed by the framework. Restarting the input method.
W/ListenableEditingState( 4464): a listener was added to EditingState while a batch edit was in progress
W/IInputConnectionWrapper( 4464): endBatchEdit on inactive InputConnection
D/InsetsController( 4464): show(ime(), fromIme=true)
W/IInputConnectionWrapper( 4464): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4464): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4464): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4464): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 4464): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper( 4464): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper( 4464): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4464): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4464): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 4464): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4464): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4464): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 4464): endBatchEdit on inactive InputConnection
I/flutter ( 4464): asdfghjk
D/InsetsController( 4464): show(ime(), fromIme=true)
D/EGL_emulation( 4464): app_time_stats: avg=303.01ms min=21.45ms max=554.54ms count=5
D/EGL_emulation( 4464): app_time_stats: avg=487.93ms min=478.23ms max=499.12ms count=3
D/InputMethodManager( 4464): showSoftInput() view=io.flutter.embedding.android.FlutterView{66d42b3 VFE...... .F...... 0,0-1080,2148 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
D/InsetsController( 4464): show(ime(), fromIme=true)
I/flutter ( 4464): asdfghjkl
I/TextInputPlugin( 4464): Composing region changed by the framework. Restarting the input method.
W/IInputConnectionWrapper( 4464): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4464): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 4464): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper( 4464): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper( 4464): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4464): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4464): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 4464): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4464): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4464): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 4464): endBatchEdit on inactive InputConnection
D/InsetsController( 4464): show(ime(), fromIme=true)
D/EGL_emulation( 4464): app_time_stats: avg=421.29ms min=282.58ms max=500.19ms count=3
I/flutter ( 4464): asdfghjkl
W/InputMethodSessionWrapper( 4464): IME died
W/InputMethodSessionWrapper( 4464): android.os.DeadObjectException
W/InputMethodSessionWrapper( 4464): 	at android.os.BinderProxy.transactNative(Native Method)
W/InputMethodSessionWrapper( 4464): 	at android.os.BinderProxy.transact(BinderProxy.java:571)
W/InputMethodSessionWrapper( 4464): 	at com.android.internal.view.IInputMethodSession$Stub$Proxy.updateSelection(IInputMethodSession.java:323)
W/InputMethodSessionWrapper( 4464): 	at android.view.inputmethod.InputMethodSessionWrapper.updateSelection(InputMethodSessionWrapper.java:138)
W/InputMethodSessionWrapper( 4464): 	at android.view.inputmethod.InputMethodManager.updateSelection(InputMethodManager.java:2245)
W/InputMethodSessionWrapper( 4464): 	at io.flutter.plugin.editing.InputConnectionAdaptor.didChangeEditingState(InputConnectionAdaptor.java:488)
W/InputMethodSessionWrapper( 4464): 	at io.flutter.plugin.editing.ListenableEditingState.notifyListener(ListenableEditingState.java:214)
W/InputMethodSessionWrapper( 4464): 	at io.flutter.plugin.editing.ListenableEditingState.notifyListenersIfNeeded(ListenableEditingState.java:222)
W/InputMethodSessionWrapper( 4464): 	at io.flutter.plugin.editing.ListenableEditingState.endBatchEdit(ListenableEditingState.java:113)
W/InputMethodSessionWrapper( 4464): 	at io.flutter.plugin.editing.InputConnectionAdaptor.endBatchEdit(InputConnectionAdaptor.java:144)
W/InputMethodSessionWrapper( 4464): 	at android.view.inputmethod.BaseInputConnection.finishComposingText(BaseInputConnection.java:481)
W/InputMethodSessionWrapper( 4464): 	at io.flutter.plugin.editing.InputConnectionAdaptor.finishComposingText(InputConnectionAdaptor.java:191)
W/InputMethodSessionWrapper( 4464): 	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:673)
W/InputMethodSessionWrapper( 4464): 	at com.android.internal.view.IInputConnectionWrapper.dispatchMessage(IInputConnectionWrapper.java:344)
W/InputMethodSessionWrapper( 4464): 	at com.android.internal.view.IInputConnectionWrapper.finishComposingText(IInputConnectionWrapper.java:270)
W/InputMethodSessionWrapper( 4464): 	at android.view.inputmethod.InputMethodManager$DelegateImpl.finishComposingText(InputMethodManager.java:703)
W/InputMethodSessionWrapper( 4464): 	at android.view.ImeFocusController.checkFocus(ImeFocusController.java:166)
W/InputMethodSessionWrapper( 4464): 	at android.view.inputmethod.InputMethodManager$H.handleMessage(InputMethodManager.java:936)
W/InputMethodSessionWrapper( 4464): 	at android.os.Handler.dispatchMessage(Handler.java:106)
W/InputMethodSessionWrapper( 4464): 	at android.os.Looper.loopOnce(Looper.java:201)
W/InputMethodSessionWrapper( 4464): 	at android.os.Looper.loop(Looper.java:288)
W/InputMethodSessionWrapper( 4464): 	at android.app.ActivityThread.main(ActivityThread.java:7839)
W/InputMethodSessionWrapper( 4464): 	at java.lang.reflect.Method.invoke(Native Method)
W/InputMethodSessionWrapper( 4464): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
W/InputMethodSessionWrapper( 4464): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
I/flutter ( 4464): asdfghjkl
D/EGL_emulation( 4464): app_time_stats: avg=361.51ms min=25.95ms max=550.61ms count=3
D/EGL_emulation( 4464): app_time_stats: avg=499.42ms min=483.53ms max=516.90ms count=3
D/EGL_emulation( 4464): app_time_stats: avg=564.09ms min=415.36ms max=707.41ms count=3
D/InsetsController( 4464): show(ime(), fromIme=true)
D/EGL_emulation( 4464): app_time_stats: avg=1386.13ms min=0.93ms max=23334.62ms count=17
D/EGL_emulation( 4464): app_time_stats: avg=223.43ms min=107.10ms max=340.54ms count=5
D/EGL_emulation( 4464): app_time_stats: avg=269.21ms min=24.29ms max=509.49ms count=4

```
</details>
