### ISSUE TITLE
[tool_crash] YamlException

### ISSUE THREAD

**Issue by Pedrobertucci** [flutter/flutter#92798]
## Command
```
flutter gen-l10n
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
YamlException
```
#0      Loader._loadMapping (package:yaml/src/loader.dart:168:9)
#1      Loader._loadNode (package:yaml/src/loader.dart:89:16)
#2      Loader._loadDocument (package:yaml/src/loader.dart:65:20)
#3      Loader.load (package:yaml/src/loader.dart:57:20)
#4      loadYamlDocument (package:yaml/yaml.dart:69:25)
#5      loadYamlNode (package:yaml/yaml.dart:54:5)
#6      loadYaml (package:yaml/yaml.dart:41:5)
#7      FlutterManifest.createFromString (package:flutter_tools/src/flutter_manifest.dart:42:47)
#8      FlutterManifest.createFromPath (package:flutter_tools/src/flutter_manifest.dart:36:28)
#9      generateLocalizations (package:flutter_tools/src/localizations/gen_l10n.dart:27:60)
#10     GenerateLocalizationsCommand.runCommand (package:flutter_tools/src/commands/generate_localizations.dart:210:7)
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1274:12)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-arm, locale en-PT)
    • Flutter version 2.5.3 at /Users/pedrobertucci/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (2 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/pedrobertucci/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.60.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (2 available)
    • iPhone 13 (mobile) • 8E17A94D-07A0-4F90-9752-F9A479582CC7 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 95.0.4638.54

• No issues found!

```

## Flutter Application Metadata
Exception: Please correct the pubspec.yaml file at /Users/pedrobertucci/development/appointment-app/pubspec.yaml

**Comment by danagbemava-nc** [comment]
Hi @Pedrobertucci, can you please share your `pubspec.yaml`?

**Comment by maheshmnj** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
