### ISSUE TITLE
ubuntu Check failed: gl_version_string The GL proc resolver's glGetString(GL_VERSION) failed

### ISSUE THREAD

**Issue by fayfive** [flutter/flutter#92814]
I started the app with `flutter create myapp --platforms=linux`.
When I run it `flutter run --verbose`, it shows that

```
[ +229 ms] [FATAL:flutter/shell/gpu/gpu_surface_gl_delegate.cc(50)] Check failed: gl_version_string. The GL proc
resolver's glGetString(GL_VERSION) failed
[ +131 ms] Error waiting for a debug connection: The log reader stopped unexpectedly.
[   +2 ms] Error launching application on Linux.
[   +2 ms] "flutter run" took 4,004ms.
[   +8 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:669:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1125:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>
[  +85 ms] ensureAnalyticsSent: 78ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```
My graphics card is nvidia GT730(too old). 
Flutter version is 2.5.3
Any suggestions?

**Comment by maheshmnj** [comment]
Hi @fayfive, Thanks for filing the issu. I verified on ubuntu and I was able to build and run the application created specifically for linux platform using `flutter create myapp --platforms=linux`.

>Flutter version is 2.5.3

 Please share the complete output of `flutter doctor -v`.


<details>
<summary>flutter doctor -v</summary>

```
\[✓] Flutter (Channel stable, 2.5.3, on Ubuntu 20.04.3 LTS 5.11.0-38-generic, locale en_GB.UTF-8)
    • Flutter version 2.5.3 at /home/mahesh/flutter_sdk/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/mahesh/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /snap/android-studio/115/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /snap/android-studio/115/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.28.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.3 LTS 5.11.0-38-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 94.0.4606.81

• No issues found!
```
</details>


Thanks

**Comment by fayfive** [comment]
Here is it.
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on Ubuntu 18.04.6 LTS 5.4.0-89-generic, locale zh_CN.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.61.2)
[✓] Connected device (2 available)

• No issues found!

**Comment by maheshmnj** [comment]
Hi @fayfive

There is a similar issue describing this case https://github.com/flutter/flutter/issues/85460, Please follow up there for further updates, Closing this issue as a duplicate. If you disagree feel free to write in the comments and I will reopen it.

Thank you.

**Comment by fayfive** [comment]
@maheshmnj 
I see. But the problem seems to have not been solved.

**Comment by fayfive** [comment]
@maheshmnj 
I found that the driver causes this phenomenon.
If I installed the open source nvidia  driver.  Flutter works well.

**Comment by maheshmnj** [comment]
> I found that the driver causes this phenomenon.

@fayfive thanks for the input,  if you have any further info on the issue you may share it on the linked issue as it might help resolve the issue.
