### ISSUE TITLE
Camera problem when app was in background and started again

### ISSUE THREAD

**Issue by benyaminbeyzaie** [flutter/flutter#92825]
I have a app that has a camera preview on the home page and use camera ^0.9.4+1 for that like this:
```

class HomePage extends StatefulWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> with WidgetsBindingObserver {
  CameraController? cameraController;
  bool _cameraLoading = false;
  bool _cameraError = false;

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (cameraController == null || !cameraController!.value.isInitialized) {
      return;
    }
    if (state == AppLifecycleState.inactive ||
        state == AppLifecycleState.paused ||
        state == AppLifecycleState.detached) {
      dPrint('app state changed');
      cameraController?.dispose();
    } else if (state == AppLifecycleState.resumed) {
      if (cameraController != null) {
        _setUpCamera();
      }
    }
  }

  @override
  void initState() {
    _setUpCamera();
    super.initState();
  }

  @override
  void dispose() {
    if (cameraController != null) {
      dPrint('camera controller is null or not initialized');
      try {
        cameraController?.dispose();
      } catch (e) {
        dPrint(e.toString());
      }
    }

    super.dispose();
  }

  Future<void> _setUpCamera() async {
    setState(() {
      _cameraError = false;
      _cameraLoading = true;
    });
    try {
      if (cameraController != null) {
        // if (cameraController!.value.isInitialized) {
        cameraController!.dispose();
        // }
      }
      cameraController = CameraController(
        cameras![0],
        kIsWeb ? ResolutionPreset.max : ResolutionPreset.high,
        imageFormatGroup: ImageFormatGroup.jpeg,
        enableAudio: false,
      );

      cameraController!.addListener(() {
        if (mounted) setState(() {});
      });

      await cameraController!.initialize();
      dPrint('-----------> camera set up success!');

      setState(() {
        _cameraLoading = false;
        _cameraError = false;
      });
    } catch (e) {
      dPrint('-----------> camera set up failed!');
      dPrint(e.toString());

      setState(() {
        _cameraError = true;
        _cameraLoading = false;
      });
    }
  }

  @override
  Widget build(BuildContext context) {

 ...

return Builder(
                    builder: (context) {
                      if (_cameraError) {
                        return _cameraErrorWidget();
                      }
                      if (_cameraLoading) {
                        return const Center(child: LoadingIndicator());
                      } else {
                        return Transform.scale(
                          scale: 1.2,
                          child: AspectRatio(
                            aspectRatio:
                                1 / cameraController!.value.aspectRatio,
                            child: SizedBox(
                                width:
                                    cameraController!.value.previewSize!.width <
                                            MediaQuery.of(context).size.width
                                        ? double.infinity
                                        : cameraController!
                                            .value.previewSize!.width,
                                height: double.infinity,
                                child: CameraPreview(cameraController!)),
                          ),
                        );
                    
                ),....

    );
  }

```
and I get this error for example when app is running but user turns off the screen for few seconds and turned back on after a while: 
```
3
W/System  (22196): A resource failed to call release.
I/Camera  (22196): open | onError
I/Camera  (22196): close
I/Camera  (22196): closeCaptureSession
E/CameraCaptureSession(22196): Session 0: Exception while stopping repeating:
E/CameraCaptureSession(22196): android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): The camera device has encountered a serious error
E/CameraCaptureSession(22196): 	at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:2239)
E/CameraCaptureSession(22196): 	at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1249)
E/CameraCaptureSession(22196): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:578)
E/CameraCaptureSession(22196): 	at io.flutter.plugins.camera.Camera.closeCaptureSession(Camera.java:1085)
E/CameraCaptureSession(22196): 	at io.flutter.plugins.camera.Camera.close(Camera.java:1092)
E/CameraCaptureSession(22196): 	at io.flutter.plugins.camera.Camera$1.onError(Camera.java:291)
E/CameraCaptureSession(22196): 	at android.hardware.camera2.impl.CameraDeviceImpl.notifyError(CameraDeviceImpl.java:1637)
E/CameraCaptureSession(22196): 	at android.hardware.camera2.impl.CameraDeviceImpl.lambda$oDs27OTfKFfK18rUW2nQxxkPdV0(Unknown Source:0)
E/CameraCaptureSession(22196): 	at android.hardware.camera2.impl.-$$Lambda$CameraDeviceImpl$oDs27OTfKFfK18rUW2nQxxkPdV0.accept(Unknown Source:8)
E/CameraCaptureSession(22196): 	at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:278)
E/CameraCaptureSession(22196): 	at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:201)
E/CameraCaptureSession(22196): 	at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:97)
E/CameraCaptureSession(22196): 	at android.os.Handler.handleCallback(Handler.java:938)
E/CameraCaptureSession(22196): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/CameraCaptureSession(22196): 	at android.os.Looper.loop(Looper.java:246)
E/CameraCaptureSession(22196): 	at android.os.HandlerThread.run(HandlerThread.java:67)
I/CameraManagerGlobal(22196): Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_IDLE for client com.example.bedoon API Level 2
```

then the camera preview freezes and I must restart the app...

**Comment by benyaminbeyzaie** [comment]
```flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-arm, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.61.2)```

**Comment by danagbemava-nc** [comment]
Hi @benyaminbeyzaie, there's a new version of the `camera` plugin out, can you try upgrading to the latest version to see whether or not you still experience this issue? 

Also, what device(s) are you experiencing this issue with?

Thank you

**Comment by benyaminbeyzaie** [comment]
Yes I still have the problem I use Samsung A50 with android 11

**Comment by danagbemava-nc** [comment]
Hi @benyaminbeyzaie, I can't seem to reproduce it. I tested on `Poco X3 NFC` running `android 11`. 

See video below. 

Is there more to the reproduction steps or is bringing it from the background enough to reproduce it?

<details>
<summary>video</summary>

https://user-images.githubusercontent.com/88313112/139795857-85c043cf-3275-4e69-ad57-6d864082488c.mp4

</details>

**Comment by benyaminbeyzaie** [comment]
Thanks for your response for reproducing try this things too:
make another page in the app and navigate to it and come back to the camera page few times
then go to background and come back to the app few times

also I forgot to add this lines on init and dispose so app state change is not completely working... so add this lines:
```
init:
    (WidgetsBinding.instance)?.addObserver(this);

dispose:
    (WidgetsBinding.instance)?.removeObserver(this);
```

I think the camera library have some concurrency problems! I kinda solve the problem with creating on instance in camera controller and moving it to another bloc... I will share my way if I'm sure that it is working!

**Comment by danagbemava-nc** [comment]
> make another page in the app and navigate to it and come back to the camera page few times
then go to background and come back to the app few times

I tried this too and I was unable to reproduce, see video below.

<details>
<summary>video</summary>



https://user-images.githubusercontent.com/88313112/139834840-b7c766da-b104-49ad-8940-47b8f0234269.mp4

</details>

**Comment by benyaminbeyzaie** [comment]
Can I see the exact code of yours?

**Comment by danagbemava-nc** [comment]
Sure, find the sample below. 

<details>
<summary>code sample</summary>

```dart
import 'package:camera/camera.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';

List<CameraDescription>? cameras;

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  cameras = await availableCameras();

  runApp(
    const MaterialApp(
      home: HomePage(),
    ),
  );
}

class HomePage extends StatefulWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> with WidgetsBindingObserver {
  CameraController? cameraController;
  bool _cameraLoading = false;
  bool _cameraError = false;

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (cameraController == null || !cameraController!.value.isInitialized) {
      return;
    }
    if (state == AppLifecycleState.inactive ||
        state == AppLifecycleState.paused ||
        state == AppLifecycleState.detached) {
      debugPrint('app state changed');
      cameraController?.dispose();
    } else if (state == AppLifecycleState.resumed) {
      if (cameraController != null) {
        _setUpCamera();
      }
    }
  }

  @override
  void initState() {
    _setUpCamera();
    super.initState();
    WidgetsBinding.instance?.addObserver(this);
  }

  @override
  void dispose() {
    if (cameraController != null) {
      debugPrint('camera controller is null or not initialized');
      try {
        cameraController?.dispose();
      } catch (e) {
        debugPrint(e.toString());
      }
    }

    WidgetsBinding.instance?.removeObserver(this);
    super.dispose();
  }

  Future<void> _setUpCamera() async {
    setState(() {
      _cameraError = false;
      _cameraLoading = true;
    });
    try {
      if (cameraController != null) {
        // if (cameraController!.value.isInitialized) {
        cameraController!.dispose();
        // }
      }
      cameraController = CameraController(
        cameras![0],
        kIsWeb ? ResolutionPreset.max : ResolutionPreset.high,
        imageFormatGroup: ImageFormatGroup.jpeg,
        enableAudio: false,
      );

      cameraController!.addListener(() {
        if (mounted) setState(() {});
      });

      await cameraController!.initialize();
      debugPrint('-----------> camera set up success!');

      setState(() {
        _cameraLoading = false;
        _cameraError = false;
      });
    } catch (e) {
      debugPrint('-----------> camera set up failed!');
      debugPrint(e.toString());

      setState(() {
        _cameraError = true;
        _cameraLoading = false;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Builder(
        builder: (context) {
          if (_cameraError) {
            return const Center(
              child: Text('Error initializing camera'),
            );
          }
          if (_cameraLoading) {
            return const Center(child: CircularProgressIndicator());
          } else {
            return Transform.scale(
              scale: 1.2,
              child: AspectRatio(
                aspectRatio: 1 / cameraController!.value.aspectRatio,
                child: SizedBox(
                  width: cameraController!.value.previewSize!.width <
                          MediaQuery.of(context).size.width
                      ? double.infinity
                      : cameraController!.value.previewSize!.width,
                  height: double.infinity,
                  child: CameraPreview(cameraController!),
                ),
              ),
            );
          }
        },
      ),
      floatingActionButton: FloatingActionButton(onPressed: () {
        Navigator.of(context).push(
          MaterialPageRoute(
            builder: (context) => const SecondPage(),
          ),
        );
      }),
    );
  }
}

class SecondPage extends StatelessWidget {
  const SecondPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
    );
  }
}

```
</details>

**Comment by benyaminbeyzaie** [comment]
Aha OK yes it has no problem but consider this: you want to push the home page from another page again and you may initialize the state of the home page again but don't dispose other one! for example in second page you may have this:
```
class SecondPage extends StatelessWidget {
  const SecondPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return WillPopScope(
      onWillPop: () {
        Navigator.of(context).push(
          MaterialPageRoute(
            builder: (context) => const HomePage(),
          ),
        );
        return Future.value(true);
      },
      child: Scaffold(
        appBar: AppBar(),
      ),
    );
  }
}
```
and you will get the problem with navigation...
How we can handle this? we should change our navigation system to a better one?

**Comment by danagbemava-nc** [comment]
Oddly enough, I still don't get the error even with the code in this [comment](https://github.com/flutter/flutter/issues/92825#issuecomment-957477255)

<details>
<summary>video</summary>

https://user-images.githubusercontent.com/88313112/139854602-e9952724-bdcd-447e-8d9e-dfd6349dbe27.mp4

</details>

Kindly provide output of `flutter run -v`, the output will be huge so kindly put it into a .txt file and attach it.

It's possible this doesn't occur on every device

**Comment by benyaminbeyzaie** [comment]
I think yo will get the error if you set app on background and open it again after changing screens for many times. It is logical though because we don't kill the cameras but we open new camera controllers and this would cause memory leak for device and device will kill the process itself. it is the output of ``flutter run -v`` on an emulator: 
[run.txt](https://github.com/flutter/flutter/files/7466892/run.txt)

**Comment by danagbemava-nc** [comment]
```console
Handler (android.os.Handler) {9635d03} sending message to a Handler on a dead thread
[        ] W/MessageQueue(22899): java.lang.IllegalStateException: Handler (android.os.Handler) {9635d03} sending
message to a Handler on a dead thread
```

I believe this is the error that you're referring to.

It's quite different from the error you stated in your initial comment. 

>  ```console
> Handler (android.os.Handler) {9635d03} sending message to a Handler on a dead thread
> [        ] W/MessageQueue(22899): java.lang.IllegalStateException: Handler (android.os.Handler) {9635d03} sending
> message to a Handler on a dead thread
> ```

If this is the issue you're running into, that issue is being tracked in #90070 and I would advise that you follow up there

**Comment by benyaminbeyzaie** [comment]
I found a way to resolve this issue not quite efficient but it is working fine! using bloc and creating just one CameraController and also making the bloc acts like a synchronized block and not initialize the camera if there is an active event on it is solving the problem but I guess I can found a better navigation system to not create and listen to the life cycle change in app many times. Thanks for your advices.
