### ISSUE TITLE
[animation] SharedAxisTransition throws error on Flutter web

### ISSUE THREAD

**Issue by tomosullivan8** [flutter/flutter#92830]
## Steps to Reproduce

I've used Flutter Upgrade to get the below (Flutter Doctor output) version of Flutter, and I have the issue where an exception is thown when using SharedAxisTransition to animate between widgets.

**Expected results:** 

To see the animation from Widget A to Widget B.

**Actual results:** 

Error message appears, and app crashes.

```

══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
Assertion failed:
org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/canvaskit/skia_object_cache.dart:248:12
!browserSupportsFinalizationRegistry
is not true

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3    assertFailed
lib/_engine/engine/canvaskit/skia_object_cache.dart 248:13                    [_doResurrect]
lib/_engine/engine/canvaskit/skia_object_cache.dart 245:40                    get skiaObject
lib/_engine/engine/canvaskit/canvas.dart 210:33                               drawPicture
lib/_engine/engine/canvaskit/layer.dart 467:17                                paint
lib/_engine/engine/canvaskit/layer.dart 141:14                                paintChildren
lib/_engine/engine/canvaskit/layer.dart 337:5                                 paint
lib/_engine/engine/canvaskit/layer.dart 141:14                                paintChildren
lib/_engine/engine/canvaskit/layer.dart 368:5                                 paint
lib/_engine/engine/canvaskit/layer.dart 141:14                                paintChildren
lib/_engine/engine/canvaskit/layer.dart 368:5                                 paint
lib/_engine/engine/canvaskit/layer.dart 141:14                                paintChildren
lib/_engine/engine/canvaskit/layer.dart 368:5                                 paint
lib/_engine/engine/canvaskit/layer.dart 141:14                                paintChildren
lib/_engine/engine/canvaskit/layer.dart 537:5                                 paint
lib/_engine/engine/canvaskit/layer.dart 141:14                                paintChildren
lib/_engine/engine/canvaskit/layer.dart 368:5                                 paint
lib/_engine/engine/canvaskit/layer.dart 141:14                                paintChildren
lib/_engine/engine/canvaskit/layer.dart 368:5                                 paint
lib/_engine/engine/canvaskit/layer.dart 141:14                                paintChildren
lib/_engine/engine/canvaskit/layer.dart 368:5                                 paint
lib/_engine/engine/canvaskit/layer.dart 141:14                                paintChildren
lib/_engine/engine/canvaskit/layer.dart 368:5                                 paint
lib/_engine/engine/canvaskit/layer.dart 141:14                                paintChildren
lib/_engine/engine/canvaskit/layer.dart 368:5                                 paint
lib/_engine/engine/canvaskit/layer.dart 141:14                                paintChildren
lib/_engine/engine/canvaskit/layer.dart 368:5                                 paint
lib/_engine/engine/canvaskit/layer.dart 141:14                                paintChildren
lib/_engine/engine/canvaskit/layer.dart 368:5                                 paint
lib/_engine/engine/canvaskit/layer.dart 141:14                                paintChildren
lib/_engine/engine/canvaskit/layer.dart 154:5                                 paint
lib/_engine/engine/canvaskit/layer_tree.dart 56:17                            paint
lib/_engine/engine/canvaskit/layer_tree.dart 99:16                            <fn>
lib/_engine/engine/profiler.dart 37:18                                        timeAction
lib/_engine/engine/canvaskit/layer_tree.dart 98:5                             raster
lib/_engine/engine/canvaskit/rasterizer.dart 33:22                            draw
lib/_engine/engine/platform_dispatcher.dart 577:7                             render
lib/ui/src/ui/window.dart 93:50                                               render
packages/flutter/src/rendering/view.dart 229:15                               compositeFrame
packages/flutter/src/rendering/binding.dart 457:18                            drawFrame
packages/flutter/src/widgets/binding.dart 883:13                              drawFrame
packages/flutter/src/rendering/binding.dart 319:5                             [_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1148:15                           [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1084:9                            handleDrawFrame
packages/flutter/src/scheduler/binding.dart 996:5                             [_handleDrawFrame]
lib/_engine/engine/platform_dispatcher.dart 1003:13                           invoke
lib/_engine/engine/platform_dispatcher.dart 157:5                             invokeOnDrawFrame
lib/_engine/engine.dart 440:45                                                <fn>
════════════════════════════════════════════════════════════════════════════════════════════════════

```

<details>
<summary>Code sample</summary>

I use the following and change the index via either a onTap or onHover function and the error occurs.

```
PageTransitionSwitcher(
          duration: const Duration(milliseconds: 400),
          reverse: false,
          transitionBuilder: (
            Widget child,
            Animation<double> animation,
            Animation<double> secondaryAnimation,
          ) {
            return SharedAxisTransition(
              child: child,
              animation: animation,
              secondaryAnimation: secondaryAnimation,
              transitionType: SharedAxisTransitionType.vertical,
            );
          },
          child: Container(
            alignment: Alignment.centerLeft,
            height: 100.0,
            width: 100.0,
            key: ValueKey<int>(index),
            child: index == 1
                ? Container(
                    color: Colors.red,
                   ),
                : Container(
                    color: Colors.blue,
                   ),
          ),
```

</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel dev, 2.6.0-11.0.pre, on macOS 11.5.2 20G95 darwin-x64, locale en-GB)
    • Flutter version 2.6.0-11.0.pre at /Users/tomosullivan/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4b330ddbed (7 weeks ago), 2021-09-16 17:29:58 -0700
    • Engine revision 5b81c6d615
    • Dart version 2.15.0 (build 2.15.0-116.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/tomosullivan/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.5.2 20G95 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 95.0.4638.54

• No issues found!


```

</details>

**Comment by tomosullivan8** [comment]
To confirm, the issue has gone when changing to channel stable, 2.5.3. I'll close, although appreciated if this could be investigated.

**Comment by jonaird** [comment]
I also have this issue. I'm not able to switch to stable channel because of some dependencies in beta. I think this should be reopened.

**Comment by darshankawar** [comment]
@jonaird @tomosullivan8 
I tried the code sample on latest stable but didn't notice any errors.

<details>
<summary>complete code sample</summary>

```

import 'package:animations/animations.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {


  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    int index = 0;
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: Scaffold(
        appBar: AppBar(),
        body: PageTransitionSwitcher(
          duration: const Duration(milliseconds: 400),
          reverse: false,
          transitionBuilder: (
              Widget child,
              Animation<double> animation,
              Animation<double> secondaryAnimation,
              ) {
            return SharedAxisTransition(
              child: child,
              animation: animation,
              secondaryAnimation: secondaryAnimation,
              transitionType: SharedAxisTransitionType.vertical,
            );
          },
          child: Container(
            alignment: Alignment.centerLeft,
            height: 100.0,
            width: 100.0,
            key: ValueKey<int>(index),
            child: index == 1
                ? Container(
              color: Colors.red,
            )
                : Container(
            color: Colors.blue,
          ),
        ),
      ),
    ));
  }
}



```

</details>

![Screenshot 2021-11-11 at 3 37 41 PM](https://user-images.githubusercontent.com/67046386/141279697-f2f60667-d781-459e-9a49-570839273a3c.png)


If this doesn't correctly represent the case, please provide a complete code sample that shows the error.
Thanks.

**Comment by tomosullivan8** [comment]
Hi @darshankawar thanks for testing the above. 

I think as @jonaird mentioned this issue occurs in Dev or Master, appears to be fine in stable and why I closed previously but looks like it's impacting others. 

Thanks!

**Comment by jonaird** [comment]
I experienced the issue on the beta channel. I haven't tried others.

**Comment by darshankawar** [comment]
@jonaird 
I verified the code sample on latest beta `(Channel beta, 2.7.0-3.1.pre)`, but didn't notice the issue. Can you confirm if this is still the case using the code sample above I shared ?
Thanks.

**Comment by peerwaya** [comment]
This happens using the canvaskit backend on master instead of html

**Comment by peerwaya** [comment]
in my case it was closing a drawer that causes the error to be thrown. 

```

════════ Exception caught by scheduler library ═════════════════════════════════
Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/canvaskit/skia_object_cache.dart:248:12
!browserSupportsFinalizationRegistry
is not true
```

**Comment by sgehrman** [comment]
I'm on dev channel:

Exception has occurred.
"Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/canvaskit/skia_object_cache.dart:248:12
!browserSupportsFinalizationRegistry
is not true
    at Object.throw_ [as throw] (http://localhost:8084/dart_sdk.js:5081:11)
    at Object.assertFailed (http://localhost:8084/dart_sdk.js:5006:15)
    at _engine.CkPicture.new.[_doResurrect] (http://localhost:8084/dart_sdk.js:142052:65)
    at _engine.CkPicture.new.get skiaObject [as skiaObject] (http://localhost:8084/dart_sdk.js:142049:49)
    at _engine.CkCanvas.new.drawPicture (http://localhost:8084/dart_sdk.js:139673:41)
    at _engine.PictureLayer.new.paint (http://localhost:8084/dart_sdk.js:145692:52)
    at _engine.OffsetEngineLayer.new.paintChildren (http://localhost:8084/dart_sdk.js:145227:17)
    at _engine.OffsetEngineLayer.new.paint (http://localhost:8084/dart_sdk.js:145518:12)
    at _engine.ClipRectEngineLayer.new.paintChildren (http://localhost:8084/dart_sdk.js:145227:17)
    at _engine.ClipRectEngineLayer.new.paint (http://localhost:8084/dart_sdk.js:145382:12)
    at _engine.OffsetEngineLayer.new.paintChildren (http://localhost:8084/dart_sdk.js:145227:17)
    at _engine.OffsetEngineLayer.new.paint (http://localhost:8084/dart_sdk.js:145518:12)
    at _engine.OffsetEngineLayer.new.paintChildren (http://localhost:8084/dart_sdk.js:145227:17)
    at _engine.OffsetEngineLayer.new.paint (http://localhost:8084/dart_sdk.js:145518:12)
    at _engine.OffsetEngineLayer.new.paintChildren (http://localhost:8084/dart_sdk.js:145227:17)
    at _engine.OffsetEngineLayer.new.paint (http://localhost:8084/dart_sdk.js:145518:12)

**Comment by slmarcos** [comment]
Hi, I had this problem and change to stable channel and I don't had more the error. I was using the Master channel
