### ISSUE TITLE
[tool_crash] _CastError: (#0      FlutterManifest._extractFonts (package:flutter_tools/src/flutter_manifest.dart:360:38))

### ISSUE THREAD

**Issue by rukhiddinov2102** [flutter/flutter#92831]
## Command
```
flutter --quiet assemble --no-version-check --depfile C:\Users\Rukhiddinov\Desktop\flutter\sizeconfig\build\app\intermediates\flutter\debug/flutter_build.d --output C:\Users\Rukhiddinov\Desktop\flutter\sizeconfig\build\app\intermediates\flutter\debug -dTargetFile=C:\Users\Rukhiddinov\Desktop\flutter\sizeconfig\lib\main.dart -dTargetPlatform=android -dBuildMode=debug -dTrackWidgetCreation=true --DartDefines=Zmx1dHRlci5pbnNwZWN0b3Iuc3RydWN0dXJlZEVycm9ycz10cnVl,RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== debug_android_application
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_CastError: (#0      FlutterManifest._extractFonts (package:flutter_tools/src/flutter_manifest.dart:360:38))
```
#0      FlutterManifest._extractFonts (package:flutter_tools/src/flutter_manifest.dart:360:38)
#1      FlutterManifest.fonts (package:flutter_tools/src/flutter_manifest.dart:330:33)
#2      FlutterManifest.fonts (package:flutter_tools/src/flutter_manifest.dart)
#3      ManifestAssetBundle._parseAssets (package:flutter_tools/src/asset.dart:706:45)
#4      ManifestAssetBundle.build (package:flutter_tools/src/asset.dart:246:53)
<asynchronous suspension>
#5      copyAssets (package:flutter_tools/src/build_system/targets/assets.dart:53:26)
<asynchronous suspension>
#6      AndroidAssetBundle.build (package:flutter_tools/src/build_system/targets/android.dart:65:34)
<asynchronous suspension>
#7      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:836:9)
<asynchronous suspension>
#8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:603:16)
<asynchronous suspension>
#9      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:314:32)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
```
```
[✓] Flutter (Channel stable, 2.5.2, on Microsoft Windows [Version 10.0.17763.2237], locale en-US)
    • Flutter version 2.5.2 at C:\flutter\flutter_windows_2.5.2-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (5 weeks ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Rukhiddinov\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.61.2)
    • VS Code at C:\Users\Rukhiddinov\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.27.0

[✓] Connected device (2 available)
    • M2003J15SC (mobile) • 105a5e6e0410 • android-arm64  • Android 11 (API 30)
    • Chrome (web)        • chrome       • web-javascript • Google Chrome 95.0.4638.54

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 3595343e20a61ff16d14e8ecc25f364276bb1b8b

**Comment by darshankawar** [comment]
@rukhiddinov2102 
Can you upgrade to latest stable and try again to see if you still get same error or not ?

**Comment by maheshmnj** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
