### ISSUE TITLE
(Android) doctor check crash in flutter

### ISSUE THREAD

**Issue by El-nonny** [flutter/flutter#92867]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

<details>
<summary>Logs</summary>

```
√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.18362.267], locale en-US)
    • Flutter version 2.5.3 at C:\Flutter\flutter_windows_2.5.3-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (2 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[☠] Android toolchain - develop for Android devices (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    X Null check operator used on a null value
    • #0      AndroidValidator.validate (package:flutter_tools/src/android/android_workflow.dart:205:40)
      #1      GroupedValidator.validate.<anonymous closure> (package:flutter_tools/src/doctor_validator.dart:87:56)
      #2      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #3      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #4      _rootRun (dart:async/zone.dart:1428:13)
      #5      _CustomZone.run (dart:async/zone.dart:1328:19)
      #6      _runZoned (dart:async/zone.dart:1863:10)
      #7      runZonedGuarded (dart:async/zone.dart:1851:12)
      #8      runZoned (dart:async/zone.dart:1782:12)
      #9      asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #10     GroupedValidator.validate (package:flutter_tools/src/doctor_validator.dart:87:11)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #12     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #13     _rootRun (dart:async/zone.dart:1428:13)
      #14     _CustomZone.run (dart:async/zone.dart:1328:19)
      #15     _runZoned (dart:async/zone.dart:1863:10)
      #16     runZonedGuarded (dart:async/zone.dart:1851:12)
      #17     runZoned (dart:async/zone.dart:1782:12)
      #18     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #19     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:200:9)
      #20     Doctor.diagnose (package:flutter_tools/src/doctor.dart:304:47)
      #21     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:47)
      #22     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1274:12)
      <asynchronous suspension>
      #23     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
      <asynchronous suspension>
      #24     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #25     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #26     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
      <asynchronous suspension>
      #27     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #28     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
      <asynchronous suspension>
      #29     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #31     main (package:flutter_tools/executable.dart:92:3)
      <asynchronous suspension>


[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.61.2)
    • VS Code at C:\Users\USER\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.27.0

[√] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 95.0.4638.69

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment]
@El-nonny 
This was fixed per [this](https://github.com/flutter/flutter/issues/90042) issue. You'll need to switch to latest master to see it fixed.
Closing from here as this is already fixed and available on master. If you still get same crash on master, write in comments and I'll reopen it.

**Comment by El-nonny** [comment]
It has been fixed by changing the path using
flutter config --android-sdk [path]
Thank you
