### ISSUE TITLE
No signature of method: build_1i5iqn7wh90lwjd36gc5mcmai.android() is applicable for argument types

### ISSUE THREAD

**Issue by naqash-smrt-is** [flutter/flutter#92974]
![image](https://user-images.githubusercontent.com/84722271/140051657-79fd8820-1932-477c-b028-35ed1565e6e2.png)

```
I'm stuck while building flutter release build, flutter throw me 
**No signature of method: build_1i5iqn7wh90lwjd36gc5mcmai.android() is applicable for argument types: (build_1i5iqn7wh90lwjd36gc5mcmai$_run_closure2) values: [build_1i5iqn7wh90lwjd36gc5mcmai$_run_closure2@2e774a04]**
error while creating build, As i now its caused by the **useProguard true** option in release section, without useProguard option it works fine, any solution

```
android/app/build.gradle

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

 def keystoreProperties = new Properties()
   def keystorePropertiesFile = rootProject.file('key.properties')
   if (keystorePropertiesFile.exists()) {
       keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
   }

   android {
    compileSdkVersion 31

    compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    // For Kotlin projects
    kotlinOptions {
      jvmTarget = "11"
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
        checkDependencies true
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "test.dev.develop.com"
        minSdkVersion 21
        targetSdkVersion 30
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        // multiDexEnabled true
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            storePassword keystoreProperties['storePassword']
        }
    }
    
    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            shrinkResources true        
            useProguard true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro' 
        }

        debug {
            signingConfig signingConfigs.debug
        }
    }
   
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.google.firebase:firebase-messaging:23.0.0'
    implementation 'com.google.firebase:firebase-auth:21.0.1'
    implementation 'com.google.firebase:firebase-firestore:24.0.0'
    implementation 'com.google.firebase:firebase-crashlytics:18.2.4'
    implementation "androidx.browser:browser:1.3.0"
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.1.5'
}

apply plugin: 'com.google.gms.google-services'  // Google Services plugin
apply plugin: 'com.google.firebase.crashlytics'
```

android/build.gradle
```
buildscript {
    ext.kotlin_version = '1.5.31'
    ext.multidex_version = "2.0.1"

    repositories {
        google()
        jcenter()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.0.3'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.10'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.7.1'
    }
}

allprojects {
    repositories {
       google()
        jcenter()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```
flutter doctor -v
```
[✓] Flutter (Channel stable, 2.5.3, on Ubuntu 20.04.3 LTS 5.11.0-38-generic, locale en_US.UTF-8)
    • Flutter version 2.5.3 at /home/saim/sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/saim/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /home/saim/Android/Sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 61.2.2
    • Dart plugin version 203.8452
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.61.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.28.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 95.0.4638.54

• No issues found!
```

**Comment by darshankawar** [comment]
@naqash-smrt-is 
Check below links for possible solutions and see if they work for you:

https://stackoverflow.com/questions/61807520/how-to-fix-error-no-signature-of-method-build-ap86oam3dut3pxce3x49rdtma-androi


https://exerror.com/no-signature-of-method-android-is-applicable-for-argument-types-exception-in-build-gradle-app/

**Comment by naqash-smrt-is** [comment]
@darshankawar thanks for your time, I have resolved this issue as per suggested in this warning, 
Removed the **useProguard** option, 
Thanks, closing...

```
Configure project :app
[        ] WARNING:DSL element 'useProguard' is obsolete and should be removed.
[        ] It will be removed in version 8.0 of the Android Gradle plugin.
[  +88 ms] FAILURE: Build failed with an exception.
[   +2 ms] * Where:
[        ] Build file '/home/saim/Desktop/gharse-mobile/android/app/build.gradle' line: 34
[        ] * What went wrong:
[   +4 ms] A problem occurred evaluating project ':app'.
[        ] > No signature of method: build_1i5iqn7wh90lwjd36gc5mcmai.android() is applicable for argument types: (build_1i5iqn7wh90lwjd36gc5mcmai$_run_closure2) values:
[build_1i5iqn7wh90lwjd36gc5mcmai$_run_closure2@438fae02]
[   +1 ms] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[   +1 ms] BUILD FAILED in 1s
[   +2 ms] Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
[   +1 ms] You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
[   +1 ms] See https://docs.gradle.org/7.2/userguide/command_line_interface.html#sec:command_line_warnings
[ +366 ms] Running Gradle task 'bundleRelease'... (completed in 2,343ms)
[   +3 ms] "flutter appbundle" took 3,072ms.
[   +3 ms] Gradle task bundleRelease failed with exit code 1
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:383:9)
           <asynchronous suspension>
           #2      AndroidGradleBuilder.buildAab (package:flutter_tools/src/android/gradle.dart:196:5)
           <asynchronous suspension>
           #3      BuildAppBundleCommand.runCommand (package:flutter_tools/src/commands/build_appbundle.dart:148:5)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #12     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>
```
