### ISSUE TITLE
Bidirectional dismissible causes a framework exception when routing away after it is dismissed

### ISSUE THREAD

**Issue by dlatikay-myneva** [flutter/flutter#92976]
## Steps to Reproduce

1. Execute `flutter run` on the code sample
2. Dismiss the dismissible by fully swiping left right
3. Tap on the "Trigger... " text and exception occurs whilst popup is opened
4. Close the popup and see the crash report

**Expected results:** 

No error.

**Actual results:**

The error message is 

> **A dismissed Dismissible widget is still part of the tree.**

StackOverflow answers recommended to use a UniqueKey for the dismissible, which we did (no change).
The widget tree after dismissing shows, that there is one residual Container with one of the icons in it, which prevents the dismissible from being completely removed from the widget tree.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const BiDiDisMiss());

class BiDiDisMiss extends StatelessWidget {
  const BiDiDisMiss({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      routes: {
        '/': (context) => const BiDiDisMissLayout(),
      },
    );
  }
}

class BiDiDisMissLayout extends StatelessWidget {
  const BiDiDisMissLayout({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(backgroundColor: Colors.grey[200], body: const BiDiDisMissWidget());
  }
}

class BiDiDisMissWidget extends StatefulWidget {
  const BiDiDisMissWidget({Key? key}) : super(key: key);

  @override
  _BiDiDismissState createState() => _BiDiDismissState();
}

class _BiDiDismissState extends State<BiDiDisMissWidget> {
  @override
  Widget build(BuildContext context) {
    return Padding(
        padding: const EdgeInsets.only(top: 50),
        child: Column(mainAxisSize: MainAxisSize.min, children: [
          Dismissible(
              key: UniqueKey(),
              child: const ListTile(title: Text("Swipe this to dismiss first")),
              direction: DismissDirection.horizontal,
              background: Container(
                  color: Colors.green,
                  padding: const EdgeInsets.symmetric(horizontal: 20),
                  alignment: AlignmentDirectional.centerStart,
                  child: const Icon(
                    Icons.check,
                    color: Colors.black54,
                  )),
              secondaryBackground: Container(
                  color: Colors.orange,
                  padding: const EdgeInsets.symmetric(horizontal: 20),
                  alignment: AlignmentDirectional.centerEnd,
                  child: const Icon(
                    Icons.not_interested,
                    color: Colors.black54,
                  ))),
          TextButton(
              child: const Text("Tap to trigger after dismissing"),
              onPressed: () {
                Navigator.of(context).push(MaterialPageRoute(builder: (context) => const Popup()));
              })
        ]));
  }
}

class Popup extends StatelessWidget {
  const Popup({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: GestureDetector(
            child: Container(
                height: 300,
                alignment: Alignment.center,
                child: const Text("POPUP\ntap to redeem the error message", textAlign: TextAlign.center)),
            onTap: () {
              Navigator.of(context).pop();
            }));
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
======== Exception caught by widgets library =======================================================
The following assertion was thrown building Dismissible-[#dff9a](dirty, dependencies: [_EffectiveTickerMode, Directionality], state: _DismissibleState#adbb5(tickers: tracking 2 tickers)):
A dismissed Dismissible widget is still part of the tree.


Make sure to implement the onDismissed handler and to immediately remove the Dismissible widget from the application once that handler has fired.

The relevant error-causing widget was: 
  Dismissible-[#dff9a] Dismissible:file:///E:/test/test/lib/main.dart:40:11
When the exception was thrown, this was the stack: 
#0      _DismissibleState.build.<anonymous closure> (package:flutter/src/widgets/dismissible.dart:571:11)
#1      _DismissibleState.build (package:flutter/src/widgets/dismissible.dart:580:8)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4782:27)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4665:15)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#6      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2620:33)
#7      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#8      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
#9      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
#10     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1080:9)
#11     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#15     _invoke (dart:ui/hooks.dart:166:10)
#16     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#17     _drawFrame (dart:ui/hooks.dart:129:31)
(elided 3 frames from dart:async)
====================================================================================================
```

```
E:\test\test>flutter analyze
Analyzing test...
No issues found! (ran in 0.9s)
```

```
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19043.1288], locale en-AT)
    • Flutter version 2.5.3 at C:\Users\dlatikay\Documents\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\dlatikay\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Connected device (4 available)
    • BE2013 (mobile)                    • 1cec7f13      • android-arm64  • Android 10 (API 29)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 95.0.4638.54
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 95.0.1020.30

• No issues found!
```

</details>

**Comment by dlatikay-myneva** [comment]
Widget tree before crash:
![image](https://user-images.githubusercontent.com/93655960/140060457-0bbdf827-6c54-436b-893b-d3027e92ea16.png)

Widget tree after crash, vestigial remains highlighted
![image](https://user-images.githubusercontent.com/93655960/140060708-ed0be466-b6cc-441e-946c-cbaec5117422.png)

![image](https://user-images.githubusercontent.com/93655960/140060779-9903b98b-36c3-439c-b83c-c82ef35052eb.png)

**Comment by danagbemava-nc** [comment]
Hi @dlatikay-myneva, I took a look at your logs and it seems the error message has provided you with a solution, ie, you need to implement the `onDismissed` of the `Dismissible` before the item can be removed from the Widget tree. 
Kindly see https://api.flutter.dev/flutter/widgets/Dismissible-class.html for more information on the `Dismissible` widget. 

PS: I combined your sample with the example from the docs and no exception was thrown after navigating away

**Comment by dlatikay-myneva** [comment]
Thanks for taking your time to answer.

The documentation states,

“If the Dismissible is a list item, it must have a key that distinguishes it from the other items and its onDismissed<https://api.flutter.dev/flutter/widgets/Dismissible/onDismissed.html> callback must remove the item from the list.”

My Dismissible is not (part of) a list item.
I had been under the wrong assumption that in such cases, the Dismissible takes care of removing itself, which is obviously not the case.

I’ll do some more investigation and will likely close the issue.


BR
Daniel Latikaynen

**Comment by danagbemava-nc** [comment]
The typical use case of the `swipe to dismiss` feature is a list so that was my immediate assumption, however, if you want are using it outside of a list, you'll need to find a way to remove it from the widget tree after the Dismissible is done. 
I used a boolean value to decide whether the `Dismissible` item should be in the tree afterwards and updated it's state after the widget it dismissed, kindly let me know if that works for you, however, if you have multiple items that you need to use as `Dismissible` outside of a list, it might not scale well.

<details>
<summary>updated sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const BiDiDisMiss());

class BiDiDisMiss extends StatelessWidget {
  const BiDiDisMiss({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      routes: {
        '/': (context) => const BiDiDisMissLayout(),
      },
    );
  }
}

class BiDiDisMissLayout extends StatelessWidget {
  const BiDiDisMissLayout({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        backgroundColor: Colors.grey[200], body: const BiDiDisMissWidget());
  }
}

class BiDiDisMissWidget extends StatefulWidget {
  const BiDiDisMissWidget({Key? key}) : super(key: key);

  @override
  _BiDiDismissState createState() => _BiDiDismissState();
}

class _BiDiDismissState extends State<BiDiDisMissWidget> {
  bool visible = true;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.only(top: 50),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          if (visible)
            Dismissible(
              key: UniqueKey(),
              onDismissed: (DismissDirection direction) {
                setState(() {
                  visible = false;
                });
              },
              child: const ListTile(title: Text("Swipe this to dismiss first")),
              direction: DismissDirection.horizontal,
              background: Container(
                color: Colors.green,
                padding: const EdgeInsets.symmetric(horizontal: 20),
                alignment: AlignmentDirectional.centerStart,
                child: const Icon(
                  Icons.check,
                  color: Colors.black54,
                ),
              ),
              secondaryBackground: Container(
                color: Colors.orange,
                padding: const EdgeInsets.symmetric(horizontal: 20),
                alignment: AlignmentDirectional.centerEnd,
                child: const Icon(
                  Icons.not_interested,
                  color: Colors.black54,
                ),
              ),
            ),
          TextButton(
            child: const Text("Tap to trigger after dismissing"),
            onPressed: () {
              Navigator.of(context)
                  .push(MaterialPageRoute(builder: (context) => const Popup()));
            },
          )
        ],
      ),
    );
  }
}

class Popup extends StatelessWidget {
  const Popup({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: GestureDetector(
        child: Container(
            height: 300,
            alignment: Alignment.center,
            child: const Text("POPUP\ntap to redeem the error message",
                textAlign: TextAlign.center)),
        onTap: () {
          Navigator.of(context).pop();
        },
      ),
    );
  }
}

```
</details>

**Comment by maheshmnj** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
