### ISSUE TITLE
[foundation] unreadable error from apparently web related debugging on android

### ISSUE THREAD

**Issue by aoatmon** [flutter/flutter#92985]
disclosures: 
- I cannot share the code because is production
- I'd be happy to produce a code sample, but the logs don't seem to point at my code

```
I/flutter (30619): ----------------FIREBASE CRASHLYTICS----------------
I/flutter (30619): 'package:flutter/src/foundation/stack_frame.dart': Failed assertion: line 114 pos 12: 'match != null': Expected {platform: android, securityPatch: 2021-10-05, sdkInt: 31, release: 12, previewSdkInt: 0, incremental: 7679548, codename: REL, baseOS: , board: sargo, bootloader: b4s4-0.4-7617386, brand: google, device: sargo, display: SP1A.210812.015, fingerprint: google/sargo/sargo:12/SP1A.210812.015/7679548:user/release-keys, hardware: sargo, host: abfarm-release-rbe-64-00096, id: SP1A.210812.015, manufacturer: Google, model: Pixel 3a, product: sargo, supported32BitAbis: [armeabi-v7a, armeabi], supported64BitAbis: [arm64-v8a], supportedAbis: [arm64-v8a, armeabi-v7a, armeabi], tags: release-keys, type: user, isPhysicalDevice: true, androidId: b311e35cfc6e843a, systemFeatures: [android.hardware.sensor.proximity, com.verizon.hardware.telephony.lte, com.verizon.hardware.telephony.ehrpd, android.hardware.sensor.accelerometer, android.software.controls, android.hardware.faketouch, com.google.android.feature.D2D_CABLE
I/flutter (30619): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
I/flutter (30619): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
I/flutter (30619): #2      StackFrame._parseWebDebugFrame (package:flutter/src/foundation/stack_frame.dart:114:12)
I/flutter (30619): #3      StackFrame._parseWebFrame (package:flutter/src/foundation/stack_frame.dart:100:14)
I/flutter (30619): #4      StackFrame.fromStackTraceLine (package:flutter/src/foundation/stack_frame.dart:202:14)
I/flutter (30619): #5      MappedIterator.moveNext (dart:_internal/iterable.dart:391:20)
I/flutter (30619): #6      WhereTypeIterator.moveNext (dart:_internal/iterable.dart:869:20)
I/flutter (30619): #7      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:198:26)
I/flutter (30619): #8      new _GrowableList.of (dart:core-patch/growable_array.dart:152:26)
I/flutter (30619): #9      new List.of (dart:core-patch/array_patch.dart:50:28)
I/flutter (30619): #10     Iterable.toList (dart:core/iterable.dart:388:12)
I/flutter (30619): #11     StackFrame.fromStackString (package:flutter/src/foundation/stack_frame.dart:95:10)
I/flutter (30619): #12     FlutterError.defaultStackFilter (package:flutter/src/foundation/assertion
I/flutter (30619): ----------------------------------------------------
I/flutter (30619): ----------------FIREBASE CRASHLYTICS----------------
I/flutter (30619): 'package:flutter/src/foundation/stack_frame.dart': Failed assertion: line 114 pos 12: 'match != null': Expected {platform: android, securityPatch: 2021-10-05, sdkInt: 31, release: 12, previewSdkInt: 0, incremental: 7679548, codename: REL, baseOS: , board: sargo, bootloader: b4s4-0.4-7617386, brand: google, device: sargo, display: SP1A.210812.015, fingerprint: google/sargo/sargo:12/SP1A.210812.015/7679548:user/release-keys, hardware: sargo, host: abfarm-release-rbe-64-00096, id: SP1A.210812.015, manufacturer: Google, model: Pixel 3a, product: sargo, supported32BitAbis: [armeabi-v7a, armeabi], supported64BitAbis: [arm64-v8a], supportedAbis: [arm64-v8a, armeabi-v7a, armeabi], tags: release-keys, type: user, isPhysicalDevice: true, androidId: b311e35cfc6e843a, systemFeatures: [android.hardware.sensor.proximity, com.verizon.hardware.telephony.lte, com.verizon.hardware.telephony.ehrpd, android.hardware.sensor.accelerometer, android.software.controls, android.hardware.faketouch, com.google.android.feature.D2D_CABLE
I/flutter (30619): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
I/flutter (30619): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
I/flutter (30619): #2      StackFrame._parseWebDebugFrame (package:flutter/src/foundation/stack_frame.dart:114:12)
I/flutter (30619): #3      StackFrame._parseWebFrame (package:flutter/src/foundation/stack_frame.dart:100:14)
I/flutter (30619): #4      StackFrame.fromStackTraceLine (package:flutter/src/foundation/stack_frame.dart:202:14)
I/flutter (30619): #5      MappedIterator.moveNext (dart:_internal/iterable.dart:391:20)
I/flutter (30619): #6      WhereTypeIterator.moveNext (dart:_internal/iterable.dart:869:20)
I/flutter (30619): #7      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:198:26)
I/flutter (30619): #8      new _GrowableList.of (dart:core-patch/growable_array.dart:152:26)
I/flutter (30619): #9      new List.of (dart:core-patch/array_patch.dart:50:28)
I/flutter (30619): #10     Iterable.toList (dart:core/iterable.dart:388:12)
I/flutter (30619): #11     StackFrame.fromStackString (package:flutter/src/foundation/stack_frame.dart:95:10)
I/flutter (30619): #12     StackFrame.fromStackTrace (package:flutter/src/foundation/stack_frame.dar
I/flutter (30619): ----------------------------------------------------
```
the [ referenced line (https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/foundation/stack_frame.dart#L114) points at this [issue](https://github.com/flutter/flutter/issues/52685) which at first sight seems to be web related,
but I'm running the app in debug mode on a pixel 3a

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale en-EE)
    • Flutter version 2.5.3 at /Users/francesco/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/francesco/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (3 available)
    • Pixel 3a (mobile) • 965AY0WP5C • android-arm64  • Android 12 (API 31)
    • macOS (desktop)   • macos      • darwin-x64     • macOS 11.6 20G165 darwin-x64
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 95.0.4638.69

• No issues found!
```

**Comment by maheshmnj** [comment]
Hi @aoatmon, Thanks for filing the issue.

> I'd be happy to produce a code sample, but the logs don't seem to point at my code

please share the minimal and complete reproducible code along with the steps to reproduce the issue. This will help to replicate the issue and eventually find the cause of the bug.

Thanks

**Comment by aoatmon** [comment]
@maheshmnj 
as I mentioned above
> - I cannot share the code because is production
> - I'd be happy to produce a code sample, but the logs don't seem to point at my code

this error is completely unreadable to me it doesn't point at any part of my code
and as it happens in production app with a relatively large codebase I cannot just "make a similar one"

I see you renamed the issue title
from
> [foundation] unreadable error from apparently web related debugging on android 

to
> [Android web] package:flutter/src/foundation/stack_frame.dart': Failed assertion: line 114 pos 12: 'match != null'

I'm not asking to fix the bug, my point is
why am I seeing an error that comes from an "apparently" web only assertion running on android?
I am not encountering the issue on web!

**Comment by maheshmnj** [comment]
> this error is completely unreadable to me it doesn't point at any part of my code
and as it happens in production app with a relatively large codebase I cannot just "make a similar one"

@aoatmon By just sharing a partial error log its not possible to find the cause of the bug, Inorder for this issue to be actionable at least some sort of code sample or reproducible steps are required along with the complete 
log of `flutter run -v`.

> I see you renamed the issue title

`[foundation] unreadable error from apparently web-related debugging on android` is not an easily searchable title but the assertion error is, when a similar exception occurs most of the developers generally search for the error. When the cause of the bug is known someone from the team might update the title if required. But at this point, I believe it is the appropriate title.

**Comment by aoatmon** [comment]
@maheshmnj 
my issue is not about the source of the error,
my problem is that the `assertion error for stacktrace potentially hides flutter error`
here is my [flutter run -v.txt](https://github.com/flutter/flutter/files/7473526/issue.92985.flutter.run.-v.txt)

once more, I'm don't need any help to fix the error,  I just want
### the error message originating the stack trace 
### to be shown along with the stack trace assertion error

**Comment by maheshmnj** [comment]
@aoatmon thanks for the clarification, I ran both the code sample and I see assertion error and stack trace in both the logs. 

> the assertion message is shown, but not the details

I am not sure what details are you referring to, can you please clarify that?



<details>
<summary>code sample 1</summary>

```dart
import 'package:flutter/material.dart';

void setError() {
  FlutterError.onError = (details) async {
    // ignore: avoid_print
    print(details.copyWith(
      stack: StackTrace.fromString(
          'details{"device_model": "iphone 18 pro max ultra super multi"},'
          '\nstack${details.stack}'),
    ));
  };
}

void main() {
  setError();
  runApp(
    MaterialApp(
      home: Material(
        child: Center(
          child: MaterialButton(
            child: const Text('tap me'),
            onPressed: () {
              assert(false, 'YOU SHOULD BE ABLE TO READ THIS MESSAGE');
            },
          ),
        ),
      ),
    ),
  );
}

```

</details>


<details>
<summary>logs 1</summary>

```console
Restarted application in 284ms.

════════ Exception caught by gesture ═══════════════════════════════════════════
The following assertion was thrown while handling a gesture:
YOU SHOULD BE ABLE TO READ THIS MESSAGE
'package:counter_app/main.dart':
Failed assertion: line 23 pos 22: 'false'


When the exception was thrown, this was the stack
#2      main.<anonymous closure>
#3      _InkResponseState._handleTap
#4      GestureRecognizer.invokeCallback
#5      TapGestureRecognizer.handleTapUp
#6      BaseTapGestureRecognizer._checkUp
#7      BaseTapGestureRecognizer.handlePrimaryPointer
#8      PrimaryPointerGestureRecognizer.handleEvent
#9      PointerRouter._dispatch
#10     PointerRouter._dispatchEventToRoutes.<anonymous closure>
#11     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:400:8)
#12     PointerRouter._dispatchEventToRoutes
#13     PointerRouter.route
#14     GestureBinding.handleEvent
#15     GestureBinding.dispatchEvent
#16     RendererBinding.dispatchEvent
#17     GestureBinding._handlePointerEventImmediately
#18     GestureBinding.handlePointerEvent
#19     GestureBinding._flushPointerEventQueue
#20     GestureBinding._handlePointerDataPacket
#24     _invoke1 (dart:ui/hooks.dart:185:10)
#25     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
#26     _dispatchPointerDataPacket (dart:ui/hooks.dart:98:31)
(elided 5 frames from class _AssertionError and dart:async)
Handler: "onTap"
Recognizer: TapGestureRecognizer#e6e80
    debugOwner: GestureDetector
    state: possible
    won arena
    finalPosition: Offset(184.7, 422.7)
    finalLocalPosition: Offset(33.7, 18.7)
    button: 1
    sent tap down
════════════════════════════════════════════════════════════════════════════════

```
</details>



<details>
<summary>code sample 2</summary>

```dart
import 'package:flutter/material.dart';

void setError() {
  FlutterError.onError = (details) async {
    // ignore: avoid_print
    print(details);
    print(details.copyWith(
      stack: StackTrace.fromString(
          'details{"device_model": "iphone 18 pro max ultra super multi"},'
          '\nstack${details.stack}'),
    ));
  };
}

void main() {
  runApp(
    MaterialApp(
      home: Builder(
        builder: (context) {
          /// SETTING ERROR INSIDE `runApp`
          setError();
          return Material(
            child: Center(
              child: MaterialButton(
                child: const Text('tap me'),
                onPressed: () {
                  assert(false, 'YOU SHOULD BE ABLE TO READ THIS MESSAGE');
                },
              ),
            ),
          );
        },
      ),
    ),
  );
}

```
</details>


<details>
<summary>logs2</summary>

```console
Restarted application in 359ms.
flutter: ══╡ EXCEPTION CAUGHT BY GESTURE ╞════════════════════════════════
The following assertion was thrown while handling a gesture:
YOU SHOULD BE ABLE TO READ THIS MESSAGE
'package:counter_app/main.dart':
Failed assertion: line 24 pos 22: 'false'
When the exception was thrown, this was the stack:
#2      main.<anonymous closure>
#3      _InkResponseState._handleTap
#4      GestureRecognizer.invokeCallback
#5      TapGestureRecognizer.handleTapUp
#6      BaseTapGestureRecognizer._checkUp
#7      BaseTapGestureRecognizer.handlePrimaryPointer
#8      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:563:9<…>
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: 'package:flutter/src/foundation/stack_frame.dart': Failed assertion: line 114 pos 12: 'match != null': Expected details{"device_model": "iphone 18 pro max ultra super multi"}, to match RegExp: pattern=^(.+) (\d+):(\d+)\s+(.+)$ flags=.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:47:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      StackFrame._parseWebDebugFrame
#3      StackFrame._parseWebFrame
#4      StackFrame.fromStackTraceLine
#5      MappedIterator.moveNext (dart:_internal/iterable.dart:391:20)
#6      WhereTypeIterator.moveNext (dart:_internal/iterable.dart:869:20)
#7      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:198:26)
#8      new _GrowableList.of (dart:core-patch/growable_array.dart:1<…>

```
</details>

**Comment by aoatmon** [comment]
@maheshmnj 
that's because you added a print in the second code sample

import 'package:flutter/material.dart';
```dart
void setError() {
  FlutterError.onError = (details) async {
    // ignore: avoid_print
    print(details); ///! <==== THIS
    print(details.copyWith(
      stack: StackTrace.fromString(
          'details{"device_model": "iphone 18 pro max ultra super multi"},'
          '\nstack${details.stack}'),
    ));
  };
}
```
print is not the real world usage, it's just a way to reproduce the behavior

could you please try with the code sample I provided?

**Comment by maheshmnj** [comment]
thanks, @aoatmon, I can reproduce the issue on stable and the master channel. The assertion message is not shown along with the stacktrace. Keeping this issue open for further insights from the team.
 
 <details>
<summary>code sample 1</summary>

```dart
import 'package:flutter/material.dart';

void setError() {
  FlutterError.onError = (details) async {
    print(details.copyWith(
      stack: StackTrace.fromString(
          'details{"device_model": "iphone 18 pro max ultra super multi"},'
          '\nstack${details.stack}'),
    ));
  };
}

void main() {
  setError();
  runApp(
    MaterialApp(
      home: Material(
        child: Center(
          child: MaterialButton(
            child: const Text('tap me'),
            onPressed: () {
              assert(false, 'YOU SHOULD BE ABLE TO READ THIS MESSAGE');
            },
          ),
        ),
      ),
    ),
  );
}

```

</details>


<details>
<summary>logs 1</summary>

```console
E/flutter (15822): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: 'package:flutter/src/foundation/stack_frame.dart': Failed assertion: line 114 pos 12: 'match != null': Expected details{"device_model": "iphone 18 pro max ultra super multi"}, to match RegExp: pattern=^(.+) (\d+):(\d+)\s+(.+)$ flags=.
E/flutter (15822): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:47:61)
E/flutter (15822): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter (15822): #2      StackFrame._parseWebDebugFrame
E/flutter (15822): #3      StackFrame._parseWebFrame
E/flutter (15822): #4      StackFrame.fromStackTraceLine
E/flutter (15822): #5      MappedIterator.moveNext (dart:_internal/iterable.dart:391:20)
E/flutter (15822): #6      WhereTypeIterator.moveNext (dart:_internal/iterable.dart:869:20)
E/flutter (15822): #7      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:198:26)
E/flutter (15822): #8      new _GrowableList.of (dart:core-patch/growable_array.dart:152:26)
E/flutter (15822): #9      new List.of (dart:core-patch/array_patch.dart:51:28)
E/flutter (15822): #10     Iterable.toList (dart:core/iterable.dart:388:12)
E/flutter (15822): #11     StackFrame.fromStackString
E/flutter (15822): #12     StackFrame.fromStackTrace
E/flutter (15822): #13     FlutterErrorDetails.debugFillProperties
E/flutter (15822): #14     DiagnosticableNode.builder.<anonymous closure>
E/flutter (15822): #15     DiagnosticableNode.builder
E/flutter (15822): #16     _FlutterErrorDetailsNode.builder
E/flutter (15822): #17     DiagnosticableNode.getProperties
E/flutter (15822): #18     TextTreeRenderer._debugRender
E/flutter (15822): #19     TextTreeRenderer.render
E/flutter (15822): #20     DiagnosticsNode.toStringDeep.<anonymous closure>
E/flutter (15822): #21     DiagnosticsNode.toStringDeep
E/flutter (15822): #22     FlutterErrorDetails.toString
E/flutter (15822): #23     _StringBase._interpolateSingle (dart:core-patch/string_patch.dart:831:17)
E/flutter (15822): #24     print (dart:core/print.dart:9:26)
E/flutter (15822): #25     setError.<anonymous closure>
E/flutter (15822): #26     setError.<anonymous closure>
E/flutter (15822): #27     FlutterError.reportError
E/flutter (15822): #28     GestureRecognizer.invokeCallback
E/flutter (15822): #29     TapGestureRecognizer.handleTapUp
E/flutter (15822): #30     BaseTapGestureRecognizer._checkUp
E/flutter (15822): #31     BaseTapGestureRecognizer.handlePrimaryPointer
E/flutter (15822): #32     PrimaryPointerGestureRecognizer.handleEvent
E/flutter (15822): #33     PointerRouter._dispatch
E/flutter (15822): #34     PointerRouter._dispatchEventToRoutes.<anonymous closure>
E/flutter (15822): #35     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:538:8)
E/flutter (15822): #36     PointerRouter._dispatchEventToRoutes
E/flutter (15822): #37     PointerRouter.route
E/flutter (15822): #38     GestureBinding.handleEvent
E/flutter (15822): #39     GestureBinding.dispatchEvent
E/flutter (15822): #40     RendererBinding.dispatchEvent
E/flutter (15822): #41     GestureBinding._handlePointerEventImmediately
E/flutter (15822): #42     GestureBinding.handlePointerEvent
E/flutter (15822): #43     GestureBinding._flushPointerEventQueue
E/flutter (15822): #44     GestureBinding._handlePointerDataPacket
E/flutter (15822): #45     _rootRunUnary (dart:async/zone.dart:1444:13)
E/flutter (15822): #46     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (15822): #47     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter (15822): #48     _invoke1 (dart:ui/hooks.dart:169:10)
E/flutter (15822): #49     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
E/flutter (15822): #50     _dispatchPointerDataPacket (dart:ui/hooks.dart:88:31)
E/flutter (15822):

```
</details>



<details>
<summary>code sample 2</summary>

```dart
import 'package:flutter/material.dart';

void setError() {
  FlutterError.onError = (details) async {
    // ignore: avoid_print
    print(details);
    print(details.copyWith(
      stack: StackTrace.fromString(
          'details{"device_model": "iphone 18 pro max ultra super multi"},'
          '\nstack${details.stack}'),
    ));
  };
}

void main() {
  runApp(
    MaterialApp(
      home: Builder(
        builder: (context) {
          /// SETTING ERROR INSIDE `runApp`
          setError();
          return Material(
            child: Center(
              child: MaterialButton(
                child: const Text('tap me'),
                onPressed: () {
                  assert(false, 'YOU SHOULD BE ABLE TO READ THIS MESSAGE');
                },
              ),
            ),
          );
        },
      ),
    ),
  );
}

```
</details>


<details>
<summary>logs2</summary>

```console
Restarted application in 715ms.
I/flutter (15822): ══╡ EXCEPTION CAUGHT BY GESTURE ╞════════════════════════════════
I/flutter (15822): The following assertion was thrown while handling a gesture:
I/flutter (15822): YOU SHOULD BE ABLE TO READ THIS MESSAGE
I/flutter (15822): 'package:counter_app/main.dart':
I/flutter (15822): Failed assertion: line 27 pos 26: 'false'
I/flutter (15822):
I/flutter (15822): When the exception was thrown, this was the stack:
I/flutter (15822): #2      main.<anonymous closure>.<anonymous closure>
I/flutter (15822): #3      _InkResponseState._handleTap
I/flutter (15822): #4      GestureRecognizer.invokeCallback
I/flutter (15822): #5      TapGestureRecognizer.handleTapUp
I/flutter (15822): #6      BaseTapGestureRecognizer._checkUp
I/flutter (15822): #7      BaseTapGestureRecognizer.handlePrimaryPointer
I/flutter (15822): #8      PrimaryPointerGestureRecognizer.handleEvent
I/flutter (15822): #
E/flutter (15822): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: 'package:flutter/src/foundation/stack_frame.dart': Failed assertion: line 114 pos 12: 'match != null': Expected details{"device_model": "iphone 18 pro max ultra super multi"}, to match RegExp: pattern=^(.+) (\d+):(\d+)\s+(.+)$ flags=.
E/flutter (15822): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:47:61)
E/flutter (15822): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter (15822): #2      StackFrame._parseWebDebugFrame
E/flutter (15822): #3      StackFrame._parseWebFrame
E/flutter (15822): #4      StackFrame.fromStackTraceLine
E/flutter (15822): #5      MappedIterator.moveNext (dart:_internal/iterable.dart:391:20)
E/flutter (15822): #6      WhereTypeIterator.moveNext (dart:_internal/iterable.dart:869:20)
E/flutter (15822): #7      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:198:26)
E/flutter (15822): #8      new _GrowableList.of (dart:core-patch/growable_array.dart:152:26)
E/flutter (15822): #9      new List.of (dart:core-patch/array_patch.dart:51:28)
E/flutter (15822): #10     Iterable.toList (dart:core/iterable.dart:388:12)
E/flutter (15822): #11     StackFrame.fromStackString
E/flutter (15822): #12     StackFrame.fromStackTrace
E/flutter (15822): #13     FlutterErrorDetails.debugFillProperties
E/flutter (15822): #14     DiagnosticableNode.builder.<anonymous closure>
E/flutter (15822): #15     DiagnosticableNode.builder
E/flutter (15822): #16     _FlutterErrorDetailsNode.builder
E/flutter (15822): #17     DiagnosticableNode.getProperties
E/flutter (15822): #18     TextTreeRenderer._debugRender
E/flutter (15822): #19     TextTreeRenderer.render
E/flutter (15822): #20     DiagnosticsNode.toStringDeep.<anonymous closure>
E/flutter (15822): #21     DiagnosticsNode.toStringDeep
E/flutter (15822): #22     FlutterErrorDetails.toString
E/flutter (15822): #23     _StringBase._interpolateSingle (dart:core-patch/string_patch.dart:831:17)
E/flutter (15822): #24     print (dart:core/print.dart:9:26)
E/flutter (15822): #25     setError.<anonymous closure>
E/flutter (15822): #26     setError.<anonymous closure>
E/flutter (15822): #27     FlutterError.reportError
E/flutter (15822): #28     GestureRecognizer.invokeCallback
E/flutter (15822): #29     TapGestureRecognizer.handleTapUp
E/flutter (15822): #30     BaseTapGestureRecognizer._checkUp
E/flutter (15822): #31     BaseTapGestureRecognizer.handlePrimaryPointer
E/flutter (15822): #32     PrimaryPointerGestureRecognizer.handleEvent
E/flutter (15822): #33     PointerRouter._dispatch
E/flutter (15822): #34     PointerRouter._dispatchEventToRoutes.<anonymous closure>
E/flutter (15822): #35     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:538:8)
E/flutter (15822): #36     PointerRouter._dispatchEventToRoutes
E/flutter (15822): #37     PointerRouter.route
E/flutter (15822): #38     GestureBinding.handleEvent
E/flutter (15822): #39     GestureBinding.dispatchEvent
E/flutter (15822): #40     RendererBinding.dispatchEvent
E/flutter (15822): #41     GestureBinding._handlePointerEventImmediately
E/flutter (15822): #42     GestureBinding.handlePointerEvent
E/flutter (15822): #43     GestureBinding._flushPointerEventQueue
E/flutter (15822): #44     GestureBinding._handlePointerDataPacket
E/flutter (15822): #45     _rootRunUnary (dart:async/zone.dart:1444:13)
E/flutter (15822): #46     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (15822): #47     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter (15822): #48     _invoke1 (dart:ui/hooks.dart:169:10)
E/flutter (15822): #49     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
E/flutter (15822): #50     _dispatchPointerDataPacket (dart:ui/hooks.dart:88:31)
E/flutter (15822):

```
</details>

 
 

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.5.3 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • B622CBB7-F906-4FA7-8F49-FACEAAC905AB • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5
      (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.0.1 21A559 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 95.0.4638.69

• No issues found!
```

```
[✓] Flutter (Channel master, 2.6.0-12.0.pre.555, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.6.0-12.0.pre.555 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 067386d706 (3 days ago), 2021-11-02 05:13:04 -0400
    • Engine revision 76b4caeafe
    • Dart version 2.15.0 (build 2.15.0-268.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • B622CBB7-F906-4FA7-8F49-FACEAAC905AB • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5
      (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.0.1 21A559 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 95.0.4638.69

• No issues found!
```
</details>

cc: @christopherfujino
