### ISSUE TITLE
Flake auto bot fails to deflake PRs

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#92999]
For example: https://ci.chromium.org/p/flutter/builders/staging/Linux%20web_canvaskit_tests_7_last?limit=50

This is due to recent logic change to run `bringup: true` tests in staging, but our deflake bot is using executions from prod.

We need to collect staging test runs and point deflake bot there.

**Comment by keyonghan** [comment]
Related backend API error:
```
Null check operator used on a null value
#0      BigqueryService.listRecentBuildRecordsForBuilder (package:cocoon_service/src/service/bigquery.dart:142:45)
<asynchronous suspension>
#1      DeflakeFlakyBuilders.get (package:cocoon_service/src/request_handlers/deflake_flaky_builders.dart:58:11)
<asynchronous suspension>
#2      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:46:22)
<asynchronous suspension>
#3      ApiRequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/api_request_handler.dart:149:7)
<asynchronous suspension>
#4      ApiRequestHandler.service (package:cocoon_service/src/request_handling/api_request_handler.dart:148:5)
<asynchronous suspension>
#5      main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:255:9)
<asynchronous suspension>
```

**Comment by keyonghan** [comment]
cl/407390665 to create staging table.

**Comment by keyonghan** [comment]
Fixed in https://github.com/flutter/cocoon/pull/1437.
