### ISSUE TITLE
API /api/file_flaky_issue_and_pr fails due to RangeError

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#93000]
The flake auto bot fails to call API `/api/file_flaky_issue_and_pr`, with error:

```
RangeError (end): Invalid value: Not in inclusive range 0..1: 3
#0      RangeError.checkValidRange (dart:core/errors.dart:338:9)
#1      List.sublist (dart:core-patch/growable_array.dart:84:38)
#2      IssueBuilder.issueBody (package:cocoon_service/src/request_handlers/flaky_handler_utils.dart:80:80)
#3      FileFlakyIssueAndPR._fileIssueAndPR (package:cocoon_service/src/request_handlers/file_flaky_issue_and_pr.dart:85:28)
#4      FileFlakyIssueAndPR.get (package:cocoon_service/src/request_handlers/file_flaky_issue_and_pr.dart:49:13)
<asynchronous suspension>
#5      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:46:22)
<asynchronous suspension>
#6      ApiRequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/api_request_handler.dart:149:7)
<asynchronous suspension>
#7      ApiRequestHandler.service (package:cocoon_service/src/request_handling/api_request_handler.dart:148:5)
<asynchronous suspension>
#8      main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:255:9)
<asynchronous suspension>
```

**Comment by CaseyHillers** [comment]
FYI this may be blocked on https://github.com/flutter/flutter/issues/90139 as the tests are disabled since the NNBD migration.

**Comment by keyonghan** [comment]
> FYI this may be blocked on #90139 as the tests are disabled since the NNBD migration.

Thanks for the info. Created https://github.com/flutter/cocoon/pull/1439 to land the changes. To make sure test coverage, I added a test as well, but we may need to validate until NNBBD migration.

**Comment by keyonghan** [comment]
Issue has been fixed, and API is running okay.
