### ISSUE TITLE
BottomSheet drag Gesture throws Exception: Null check operator used on a null value. 

### ISSUE THREAD

**Issue by j787701730** [flutter/flutter#93049]
showModalBottomSheet -> CupertinoPicker -> only one item.

```dart
CupertinoPicker(
       // scrollController: _regionController,
      // selectionOverlay: selectionOverlay(),
      // backgroundColor: CFColors.white,
      itemExtent: 44,
      onSelectedItemChanged: (index) {
          // widget.getArea(selectArea);
       },
       children: [
          Container(
          color: Colors.white,
          height: 44,
          alignment: Alignment.center,
          child: Text('1'),
          )
      ],
     )
```

```
======== Exception caught by gesture ===============================================================
The following _CastError was thrown while handling a gesture:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      _BottomSheetState._dismissUnderway (package:flutter/src/material/bottom_sheet.dart:211:58)
#1      _BottomSheetState._handleDragEnd (package:flutter/src/material/bottom_sheet.dart:226:9)
#2      DragGestureRecognizer._checkEnd.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:486:47)
#3      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
#4      DragGestureRecognizer._checkEnd (package:flutter/src/gestures/monodrag.dart:486:5)
#5      DragGestureRecognizer.didStopTrackingLastPointer (package:flutter/src/gestures/monodrag.dart:393:9)
#6      OneSequenceGestureRecognizer.stopTrackingPointer (package:flutter/src/gestures/recognizer.dart:392:9)
#7      DragGestureRecognizer._giveUpPointer (package:flutter/src/gestures/monodrag.dart:402:5)
#8      DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:321:7)
#9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:94:12)
#10     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:139:9)
#11     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:525:8)
#12     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:137:18)
#13     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:123:7)
#14     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:440:19)
#15     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:420:22)
#16     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:278:11)
#17     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
#18     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
#19     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#20     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#24     _invoke1 (dart:ui/hooks.dart:169:10)
#25     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
#26     _dispatchPointerDataPacket (dart:ui/hooks.dart:88:31)
(elided 3 frames from dart:async)
Handler: "onEnd"
Recognizer: VerticalDragGestureRecognizer#607c1
  debugOwner: GestureDetector
  start behavior: start
====================================================================================================
```
```
[√] Flutter (Channel beta, 2.7.0-3.1.pre, on Microsoft Windows [Version 10.0.19043.1288], locale zh-CN)
    • Flutter version 2.7.0-3.1.pre at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fc7015e35a (7 days ago), 2021-10-27 15:18:41 -0700
    • Engine revision a75e3b80f9
    • Dart version 2.15.0 (build 2.15.0-178.1.beta)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\Android\Sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31729.503
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\AndroidStudio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Android Studio
    • Android Studio at C:/AndroidStudio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:/AndroidStudio
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.61.2)
    • VS Code at C:\Users\aoc\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.23.1

[√] Connected device (4 available)
    • VOG AL00 (mobile) • 127.0.0.1:21503 • android-x86    • Android 7.1.2 (API 25)
    • Windows (desktop) • windows         • windows-x64    • Microsoft Windows [Version 10.0.19043.1288]
    • Chrome (web)      • chrome          • web-javascript • Google Chrome 95.0.4638.69
    • Edge (web)        • edge            • web-javascript • Microsoft Edge 95.0.1020.40

! Doctor found issues in 1 category.
Process finished with exit code 0
```

**Comment by maheshmnj** [comment]
Hi @j787701730, thanks for filing the issue. I tried running your code sample but I could not reporduce any error, verified on stable, beta, and the master channel. Are there any specific steps to reproduce the issue?
 
 <details>
 <summary>complete code sample</summary>
 
 ```dart
 import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

Future<void> main() async {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            CupertinoPicker(
              // scrollController: _regionController,
              // selectionOverlay: selectionOverlay(),
              // backgroundColor: CFColors.white,
              itemExtent: 44,
              onSelectedItemChanged: (index) {
                // widget.getArea(selectArea);
              },
              children: [
                Container(
                  color: Colors.white,
                  height: 44,
                  alignment: Alignment.center,
                  child: Text('1'),
                )
              ],
            )
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {},
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}

 ```
 </details>

 <details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel beta, 2.7.0-3.1.pre, on Microsoft Windows [Version 10.0.19042.1288], locale en-US)
    • Flutter version 2.7.0-3.1.pre at C:\flutter_sdk\beta
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fc7015e35a (8 days ago), 2021-10-27 15:18:41 -0700
    • Engine revision a75e3b80f9
    • Dart version 2.15.0 (build 2.15.0-178.1.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\mahesh\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31727.386
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.61.2)
    • VS Code at C:\Users\mahesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.28.0

[√] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.1288]       
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 95.0.4638.69
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 95.0.1020.40

• No issues found 
```

```
[√] Flutter (Channel beta, 2.7.0-3.1.pre, on Microsoft Windows [Version 10.0.19042.1288], locale en-US)
    • Flutter version 2.7.0-3.1.pre at C:\flutter_sdk\beta
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fc7015e35a (8 days ago), 2021-10-27 15:18:41 -0700
    • Engine revision a75e3b80f9
    • Dart version 2.15.0 (build 2.15.0-178.1.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\mahesh\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31727.386
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.61.2)
    • VS Code at C:\Users\mahesh\AppData\Local\Programs\Microsoft VS Code
PS C:\Users\mahesh\Desktop\ads> flutter doctor -v 
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19042.1288], locale en-US)
    • Flutter version 2.5.3 at C:\flutter_sdk\stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\mahesh\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java      
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)    
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)      
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31727.386
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.61.2)
    • VS Code at C:\Users\mahesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.28.0

[√] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.1288]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 95.0.4638.69
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 95.0.1020.40

• No issues found!
```
 </details>

**Comment by j787701730** [comment]
@maheshmnj my drag CupertinoPicker item in android emulators. and CupertinoPicker is in showModalBottomSheet ,  android studio  report this errors.

**Comment by maheshmnj** [comment]
@j787701730 Please share a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example).

Thanks

**Comment by j787701730** [comment]
```
ElevatedButton(
          onPressed: () {
            showModalBottomSheet(
              context: context,
              builder: (context) => BottomSheet(
                onClosing: () {},
                builder: (context) => SizedBox(
                  height: 250.0,
                  child: CupertinoPicker(
                      // scrollController: _regionController,
                      // selectionOverlay: selectionOverlay(),
                      backgroundColor: CFColors.white,
                      itemExtent: 44,
                      onSelectedItemChanged: (index) {
                        // String val = regionData.keys.toList()[index];
                        // setState(() {
                        //   selectArea['region'] = val;
                        // });
                        // widget.getArea(selectArea);
                      },
                      children: [1].map<Widget>((key) {
                        return Container(
                          color: Colors.white,
                          height: 44,
                          alignment: Alignment.center,
                          child: Text('$key'),
                        );
                      }).toList()),
                ),
              ),
            );
          },
          child: const Text("CupertinoPicker"))
```this has the error. If I remove BottomSheet widget, I won't report an error.  @maheshmnj thank you.

**Comment by maheshmnj** [comment]
Thanks for the code sample @j787701730, I was able to reproduce the issue. It looks like this issue is specifically with BottomSheet when the user just makes a drag gesture on the bottom sheet the null check error is thrown. On the master channel, the error logs are different.

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

Future<void> main() async {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            ElevatedButton(
                onPressed: () {
                  showModalBottomSheet(
                    context: context,
                    enableDrag: false,
                    builder: (context) => BottomSheet(
                      onClosing: () {},
                      builder: (context) => SizedBox(
                          height: 250.0, child: Container()

                          /// Error can be reproduced wtthout CupertinoPicker
                          // CupertinoPicker(
                          //     backgroundColor: Colors.white,
                          //     itemExtent: 44,
                          //     onSelectedItemChanged: (index) {},
                          //     children: [1].map<Widget>((key) {
                          //       return Container(
                          //         color: Colors.white,
                          //         height: 44,
                          //         alignment: Alignment.center,
                          //         child: Text('$key'),
                          //       );
                          //     }).toList()),
                          ),
                    ),
                  );
                },
                child: const Text("CupertinoPicker"))
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {},
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}

```
</details>



<details>
<summary>logs(stable)</summary>

```
Launching lib/main.dart on sdk gphone arm64 in debug mode...
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
W/FlutterActivityAndFragmentDelegate(16205): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
Connecting to VM Service at ws://127.0.0.1:53072/VLj0PwY0XyA=/ws

════════ Exception caught by gesture ═══════════════════════════════════════════
The following _CastError was thrown while handling a gesture:
Null check operator used on a null value

When the exception was thrown, this was the stack
#0      _BottomSheetState._dismissUnderway
#1      _BottomSheetState._handleDragUpdate
#2      DragGestureRecognizer._checkUpdate.<anonymous closure>
#3      GestureRecognizer.invokeCallback
#4      DragGestureRecognizer._checkUpdate
#5      DragGestureRecognizer.handleEvent
#6      PointerRouter._dispatch
#7      PointerRouter._dispatchEventToRoutes.<anonymous closure>
#8      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:400:8)
#9      PointerRouter._dispatchEventToRoutes
#10     PointerRouter.route
#11     GestureBinding.handleEvent
#12     GestureBinding.dispatchEvent
#13     RendererBinding.dispatchEvent
#14     GestureBinding._handlePointerEventImmediately
#15     GestureBinding.handlePointerEvent
#16     GestureBinding._flushPointerEventQueue
#17     GestureBinding._handlePointerDataPacket
#21     _invoke1 (dart:ui/hooks.dart:185:10)
#22     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
#23     _dispatchPointerDataPacket (dart:ui/hooks.dart:98:31)
(elided 3 frames from dart:async)
Handler: "onUpdate"
Recognizer: VerticalDragGestureRecognizer#b3277
    debugOwner: GestureDetector
    start behavior: start
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gesture ═══════════════════════════════════════════
Null check operator used on a null value
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gesture ═══════════════════════════════════════════
Null check operator used on a null value
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gesture ═══════════════════════════════════════════
Null check operator used on a null value
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gesture ═══════════════════════════════════════════
Null check operator used on a null value
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gesture ═══════════════════════════════════════════
Null check operator used on a null value
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gesture ═══════════════════════════════════════════
Null check operator used on a null value
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gesture ═══════════════════════════════════════════
Null check operator used on a null value
════════════════════════════════════════════════════════════════════════════════

```
</details>

<details>
<summary>logs(master)</summary>

```
Launching lib/main.dart on sdk gphone arm64 in debug mode...
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
W/FlutterActivityAndFragmentDelegate(16426): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
Connecting to VM Service at ws://127.0.0.1:53663/sr-KvYPeH2A=/ws

════════ Exception caught by gesture ═══════════════════════════════════════════
The following assertion was thrown while handling a gesture:
'BottomSheet.animationController' can not be null when 'BottomSheet.enableDrag' is true. Use 'BottomSheet.createAnimationController' to create one, or provide another AnimationController.
'package:flutter/src/material/bottom_sheet.dart':
Failed assertion: line 219 pos 7: 'widget.enableDrag && widget.animationController != null'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack
#2      _BottomSheetState._handleDragUpdate
#3      DragGestureRecognizer._checkUpdate.<anonymous closure>
#4      GestureRecognizer.invokeCallback
#5      DragGestureRecognizer._checkUpdate
#6      DragGestureRecognizer.handleEvent
#7      PointerRouter._dispatch
#8      PointerRouter._dispatchEventToRoutes.<anonymous closure>
#9      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:538:8)
#10     PointerRouter._dispatchEventToRoutes
#11     PointerRouter.route
#12     GestureBinding.handleEvent
#13     GestureBinding.dispatchEvent
#14     RendererBinding.dispatchEvent
#15     GestureBinding._handlePointerEventImmediately
#16     GestureBinding.handlePointerEvent
#17     GestureBinding._flushPointerEventQueue
#18     GestureBinding._handlePointerDataPacket
#22     _invoke1 (dart:ui/hooks.dart:169:10)
#23     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
#24     _dispatchPointerDataPacket (dart:ui/hooks.dart:88:31)
(elided 5 frames from class _AssertionError and dart:async)
Handler: "onUpdate"
Recognizer: VerticalDragGestureRecognizer#eb897
    debugOwner: GestureDetector
    start behavior: start
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gesture ═══════════════════════════════════════════
'BottomSheet.animationController' can not be null when 'BottomSheet.enableDrag' is true. Use 'BottomSheet.createAnimationController' to create one, or provide another AnimationController.
'package:flutter/src/material/bottom_sheet.dart':
Failed assertion: line 219 pos 7: 'widget.enableDrag && widget.animationController != null'

════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gesture ═══════════════════════════════════════════
'BottomSheet.animationController' can not be null when 'BottomSheet.enableDrag' is true. Use 'BottomSheet.createAnimationController' to create one, or provide another AnimationController.
'package:flutter/src/material/bottom_sheet.dart':
Failed assertion: line 219 pos 7: 'widget.enableDrag && widget.animationController != null'

════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gesture ═══════════════════════════════════════════
'BottomSheet.animationController' can not be null when 'BottomSheet.enableDrag' is true. Use 'BottomSheet.createAnimationController' to create one, or provide another AnimationController.
'package:flutter/src/material/bottom_sheet.dart':
Failed assertion: line 219 pos 7: 'widget.enableDrag && widget.animationController != null'

════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gesture ═══════════════════════════════════════════
'BottomSheet.animationController' can not be null when 'BottomSheet.enableDrag' is true. Use 'BottomSheet.createAnimationController' to create one, or provide another AnimationController.
'package:flutter/src/material/bottom_sheet.dart':
Failed assertion: line 219 pos 7: 'widget.enableDrag && widget.animationController != null'

════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gesture ═══════════════════════════════════════════
'BottomSheet.animationController' can not be null when 'BottomSheet.enableDrag' is true. Use 'BottomSheet.createAnimationController' to create one, or provide another AnimationController.
'package:flutter/src/material/bottom_sheet.dart':
Failed assertion: line 219 pos 7: 'widget.enableDrag && widget.animationController != null'

════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gesture ═══════════════════════════════════════════
'BottomSheet.animationController' can not be null when 'BottomSheet.enableDrag' is true. Use 'BottomSheet.createAnimationController' to create one, or provide another AnimationController.
'package:flutter/src/material/bottom_sheet.dart':
Failed assertion: line 219 pos 7: 'widget.enableDrag && widget.animationController != null'

════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gesture ═══════════════════════════════════════════
'BottomSheet.animationController' can not be null when 'BottomSheet.enableDrag' is true. Use 'BottomSheet.createAnimationController' to create one, or provide another AnimationController.
'package:flutter/src/material/bottom_sheet.dart':
Failed assertion: line 219 pos 7: 'widget.enableDrag && widget.animationController != null'

════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gesture ═══════════════════════════════════════════
'BottomSheet.animationController' can not be null when 'BottomSheet.enableDrag' is true. Use 'BottomSheet.createAnimationController' to create one, or provide another AnimationController.
'package:flutter/src/material/bottom_sheet.dart':
Failed assertion: line 219 pos 7: 'widget.enableDrag && widget.animationController != null'

════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gesture ═══════════════════════════════════════════
'BottomSheet.animationController' can not be null when 'BottomSheet.enableDrag' is true. Use 'BottomSheet.createAnimationController' to create one, or provide another AnimationController.
'package:flutter/src/material/bottom_sheet.dart':
Failed assertion: line 219 pos 7: 'widget.enableDrag && widget.animationController != null'

════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gesture ═══════════════════════════════════════════
'BottomSheet.animationController' can not be null when 'BottomSheet.enableDrag' is true. Use 'BottomSheet.createAnimationController' to create one, or provide another AnimationController.
'package:flutter/src/material/bottom_sheet.dart':
Failed assertion: line 219 pos 7: 'widget.enableDrag && widget.animationController != null'

════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gesture ═══════════════════════════════════════════
'BottomSheet.animationController' can not be null when 'BottomSheet.enableDrag' is true. Use 'BottomSheet.createAnimationController' to create one, or provide another AnimationController.
'package:flutter/src/material/bottom_sheet.dart':
Failed assertion: line 219 pos 7: 'widget.enableDrag && widget.animationController != null'

════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gesture ═══════════════════════════════════════════
'BottomSheet.animationController' can not be null when 'BottomSheet.enableDrag' is true. Use 'BottomSheet.createAnimationController' to create one, or provide another AnimationController.
'package:flutter/src/material/bottom_sheet.dart':
Failed assertion: line 230 pos 7: 'widget.enableDrag && widget.animationController != null'

════════════════════════════════════════════════════════════════════════════════

```
</details>

**Comment by maheshmnj** [comment]
cc: @darrenaustin

**Comment by xu-baolin** [comment]
As the master error says,
```
The following assertion was thrown while handling a gesture:
'BottomSheet.animationController' can not be null when 'BottomSheet.enableDrag' is true. Use 'BottomSheet.createAnimationController' to create one, or provide another AnimationController.
'package:flutter/src/material/bottom_sheet.dart':
Failed assertion: line 219 pos 7: 'widget.enableDrag && widget.animationController != null'
```

We should disable the drag or provide a controller to support the gesture.

**Comment by maheshmnj** [comment]
> We should disable the drag or provide a controller to support the gesture.

@xu-baolin I did provide `enableDrag: false` in my code sample, yet the error is thrown.

**Comment by xu-baolin** [comment]
@maheshmnj 
```dart
  builder: (context) => BottomSheet(
                      onClosing: () {},
                      enableDrag: false,
```
The `BottomSheet.enableDrag` should be false.

**Comment by maheshmnj** [comment]
> The BottomSheet.enableDrag should be false.

I see sorry about that, It's working.

**Comment by j787701730** [comment]
@maheshmnj , @xu-baolin think you.
