### ISSUE TITLE
RawKeyboardListener doesn't register events in --release mode on Android TV

### ISSUE THREAD

**Issue by jugbeep** [flutter/flutter#93079]
## Steps to Reproduce

1. Build basic flutter app
2. Add a RawKeyboardListener widget
3. Build app with ```flutter run --release``` to an Android TV device

**Expected results:**  The RawKeyboardListener registers the events

**Actual results:** The RawKeyboardListener does not register the events.

<details>
<summary>code sample</summary>

```dart

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Flutter Demo',
        theme: ThemeData(
          primarySwatch: Colors.blue,
        ),
        home: const AppWrapper());
  }
}

class AppWrapper extends StatefulWidget {
  const AppWrapper({Key? key}) : super(key: key);

  @override
  _AppWrapperState createState() => _AppWrapperState();
}

class _AppWrapperState extends State<AppWrapper> {
  FocusNode pageFocus = FocusNode();

  @override
  Widget build(BuildContext context) {
    return RawKeyboardListener(
      focusNode: pageFocus,
      autofocus: true,
      onKey: (RawKeyEvent event) {
        developer.log(event.data.toString());
        // In another (production level) attempt, I've tried to do more than just log the event.
        
      },
      child: Scaffold(
        appBar: AppBar(
          title: const Text('Raw Keyboard Test'),
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
Analyzing raw_keyboard_listener...                                      
No issues found! (ran in 1.6s)
```

```
[✓] Flutter (Channel stable, 2.5.2, on macOS 11.6 20G165 darwin-x64, locale en-US)
    • Flutter version 2.5.2 at /Applications/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (5 weeks ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/patrickbotkins/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (4 available)
    • Chromecast (mobile)     • 192.168.44.126:5555 • android-arm    • Android 10 (API 29)
    • AOSP TV on x86 (mobile) • emulator-5554       • android-x86    • Android 11 (API 30) (emulator)
    • macOS (desktop)         • macos               • darwin-x64     • macOS 11.6 20G165 darwin-x64
    • Chrome (web)            • chrome              • web-javascript • Google Chrome 95.0.4638.69
```

</details>

**Comment by maheshmnj** [comment]
Hi @jugbeep, thanks for filing the issue, I could not reproduce the issue I could see the Raw key events in the cosole, Could you please try again after upgrading to the latest `stable 2.5.3`?
Also, are you using any external keyboard?

<details>
<summary>flutter doctor -v</summary>

```
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19042.1288], locale en-US)
    • Flutter version 2.5.3 at C:\flutter_sdk\stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\mahesh\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java      
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)    
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31727.386
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.61.2)
    • VS Code at C:\Users\mahesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.28.0

[√] Connected device (4 available)
    • AOSP TV on x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.1288]       
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 95.0.4638.69
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 95.0.1020.40

• No issues found!
```

</details>

<details>
<summary>logs</summary>

```
Running "flutter pub get" in ads...
Launching lib\main.dart on AOSP TV on x86 in debug mode...
√  Built build\app\outputs\flutter-apk\app-debug.apk.
W/FlutterActivityAndFragmentDelegate( 5078): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
Connecting to VM Service at ws://127.0.0.1:50809/kBKVJAUiHLY=/ws
W/ConnectionTracker( 5078): Exception thrown while unbinding
W/ConnectionTracker( 5078): java.lang.IllegalArgumentException: Service not registered: lq@62c10b3
W/ConnectionTracker( 5078): 	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1757)
W/ConnectionTracker( 5078): 	at android.app.ContextImpl.unbindService(ContextImpl.java:1874)
W/ConnectionTracker( 5078): 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:792)
W/ConnectionTracker( 5078): 	at ci.f(:com.google.android.gms.dynamite_measurementdynamite@204217162@20.42.17 (080706-0):1)
W/ConnectionTracker( 5078): 	at ci.d(:com.google.android.gms.dynamite_measurementdynamite@204217162@20.42.17 (080706-0):2)
W/ConnectionTracker( 5078): 	at lr.D(:com.google.android.gms.dynamite_measurementdynamite@204217162@20.42.17 (080706-0):10)
W/ConnectionTracker( 5078): 	at ld.a(:com.google.android.gms.dynamite_measurementdynamite@204217162@20.42.17 (080706-0):2)
W/ConnectionTracker( 5078): 	at ef.run(:com.google.android.gms.dynamite_measurementdynamite@204217162@20.42.17 (080706-0):3)
W/ConnectionTracker( 5078): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
W/ConnectionTracker( 5078): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/ConnectionTracker( 5078): 	at iy.run(:com.google.android.gms.dynamite_measurementdynamite@204217162@20.42.17 (080706-0):6)
[log] RawKeyEventDataAndroid#b743f(flags: 8, codePoint: 97, plainCodePoint: 97, keyCode: 29, scanCode: 30, metaState: 0)
[log] RawKeyEventDataAndroid#0fe46(flags: 520, codePoint: 97, plainCodePoint: 97, keyCode: 29, scanCode: 30, metaState: 0)
[log] RawKeyEventDataAndroid#9cbea(flags: 8, codePoint: 115, plainCodePoint: 115, keyCode: 47, scanCode: 31, metaState: 0)
[log] RawKeyEventDataAndroid#18484(flags: 520, codePoint: 115, plainCodePoint: 115, keyCode: 47, scanCode: 31, metaState: 0)
[log] RawKeyEventDataAndroid#db987(flags: 8, codePoint: 100, plainCodePoint: 100, keyCode: 32, scanCode: 32, metaState: 0)
[log] RawKeyEventDataAndroid#e785d(flags: 520, codePoint: 100, plainCodePoint: 100, keyCode: 32, scanCode: 32, metaState: 0)
[log] RawKeyEventDataAndroid#20b50(flags: 8, codePoint: 102, plainCodePoint: 102, keyCode: 34, scanCode: 33, metaState: 0)
[log] RawKeyEventDataAndroid#021a6(flags: 520, codePoint: 102, plainCodePoint: 102, keyCode: 34, scanCode: 33, metaState: 0)
[log] RawKeyEventDataAndroid#eaf27(flags: 8, codePoint: 103, plainCodePoint: 103, keyCode: 35, scanCode: 34, metaState: 0)
[log] RawKeyEventDataAndroid#8b875(flags: 520, codePoint: 103, plainCodePoint: 103, keyCode: 35, scanCode: 34, metaState: 0)
[log] RawKeyEventDataAndroid#eaf27(flags: 8, codePoint: 103, plainCodePoint: 103, keyCode: 35, scanCode: 34, metaState: 0)
[log] RawKeyEventDataAndroid#8b875(flags: 520, codePoint: 103, plainCodePoint: 103, keyCode: 35, scanCode: 34, metaState: 0)
[log] RawKeyEventDataAndroid#068c4(flags: 8, codePoint: 104, plainCodePoint: 104, keyCode: 36, scanCode: 35, metaState: 0)
[log] RawKeyEventDataAndroid#e9c8e(flags: 520, codePoint: 104, plainCodePoint: 104, keyCode: 36, scanCode: 35, metaState: 0)
[log] RawKeyEventDataAndroid#068c4(flags: 8, codePoint: 104, plainCodePoint: 104, keyCode: 36, scanCode: 35, metaState: 0)
[log] RawKeyEventDataAndroid#e9c8e(flags: 520, codePoint: 104, plainCodePoint: 104, keyCode: 36, scanCode: 35, metaState: 0)
[log] RawKeyEventDataAndroid#2aa90(flags: 8, codePoint: 106, plainCodePoint: 106, keyCode: 38, scanCode: 36, metaState: 0)
[log] RawKeyEventDataAndroid#bbb4c(flags: 520, codePoint: 106, plainCodePoint: 106, keyCode: 38, scanCode: 36, metaState: 0)
[log] RawKeyEventDataAndroid#58c42(flags: 8, codePoint: 107, plainCodePoint: 107, keyCode: 39, scanCode: 37, metaState: 0)
[log] RawKeyEventDataAndroid#04895(flags: 520, codePoint: 107, plainCodePoint: 107, keyCode: 39, scanCode: 37, metaState: 0)
[log] RawKeyEventDataAndroid#58c42(flags: 8, codePoint: 107, plainCodePoint: 107, keyCode: 39, scanCode: 37, metaState: 0)
[log] RawKeyEventDataAndroid#04895(flags: 520, codePoint: 107, plainCodePoint: 107, keyCode: 39, scanCode: 37, metaState: 0)
[log] RawKeyEventDataAndroid#82d1c(flags: 8, codePoint: 108, plainCodePoint: 108, keyCode: 40, scanCode: 38, metaState: 0)
[log] RawKeyEventDataAndroid#f0823(flags: 520, codePoint: 108, plainCodePoint: 108, keyCode: 40, scanCode: 38, metaState: 0)
[log] RawKeyEventDataAndroid#82d1c(flags: 8, codePoint: 108, plainCodePoint: 108, keyCode: 40, scanCode: 38, metaState: 0)
[log] RawKeyEventDataAndroid#f0823(flags: 520, codePoint: 108, plainCodePoint: 108, keyCode: 40, scanCode: 38, metaState: 0)
[log] RawKeyEventDataAndroid#4f42f(flags: 8, codePoint: 59, plainCodePoint: 59, keyCode: 74, scanCode: 39, metaState: 0)
[log] RawKeyEventDataAndroid#a2c12(flags: 520, codePoint: 59, plainCodePoint: 59, keyCode: 74, scanCode: 39, metaState: 0)
[log] RawKeyEventDataAndroid#4f42f(flags: 8, codePoint: 59, plainCodePoint: 59, keyCode: 74, scanCode: 39, metaState: 0)
[log] RawKeyEventDataAndroid#a2c12(flags: 520, codePoint: 59, plainCodePoint: 59, keyCode: 74, scanCode: 39, metaState: 0)
[log] RawKeyEventDataAndroid#4f42f(flags: 8, codePoint: 59, plainCodePoint: 59, keyCode: 74, scanCode: 39, metaState: 0)
[log] RawKeyEventDataAndroid#a2c12(flags: 520, codePoint: 59, plainCodePoint: 59, keyCode: 74, scanCode: 39, metaState: 0)
[log] RawKeyEventDataAndroid#fd834(flags: 8, codePoint: 39, plainCodePoint: 39, keyCode: 75, scanCode: 40, metaState: 0)
[log] RawKeyEventDataAndroid#ae3b8(flags: 520, codePoint: 39, plainCodePoint: 39, keyCode: 75, scanCode: 40, metaState: 0)
[log] RawKeyEventDataAndroid#fd834(flags: 8, codePoint: 39, plainCodePoint: 39, keyCode: 75, scanCode: 40, metaState: 0)
[log] RawKeyEventDataAndroid#ae3b8(flags: 520, codePoint: 39, plainCodePoint: 39, keyCode: 75, scanCode: 40, metaState: 0)
[log] RawKeyEventDataAndroid#fd834(flags: 8, codePoint: 39, plainCodePoint: 39, keyCode: 75, scanCode: 40, metaState: 0)
[log] RawKeyEventDataAndroid#ae3b8(flags: 520, codePoint: 39, plainCodePoint: 39, keyCode: 75, scanCode: 40, metaState: 0)
[log] RawKeyEventDataAndroid#fd834(flags: 8, codePoint: 39, plainCodePoint: 39, keyCode: 75, scanCode: 40, metaState: 0)
[log] RawKeyEventDataAndroid#ae3b8(flags: 520, codePoint: 39, plainCodePoint: 39, keyCode: 75, scanCode: 40, metaState: 0)
[log] RawKeyEventDataAndroid#89db9(flags: 8, codePoint: 109, plainCodePoint: 109, keyCode: 41, scanCode: 50, metaState: 0)
[log] RawKeyEventDataAndroid#74cd1(flags: 520, codePoint: 109, plainCodePoint: 109, keyCode: 41, scanCode: 50, metaState: 0)
[log] RawKeyEventDataAndroid#597b4(flags: 8, codePoint: 110, plainCodePoint: 110, keyCode: 42, scanCode: 49, metaState: 0)
[log] RawKeyEventDataAndroid#44bc1(flags: 520, codePoint: 110, plainCodePoint: 110, keyCode: 42, scanCode: 49, metaState: 0)
[log] RawKeyEventDataAndroid#53cf2(flags: 8, codePoint: 98, plainCodePoint: 98, keyCode: 30, scanCode: 48, metaState: 0)
[log] RawKeyEventDataAndroid#e83a7(flags: 520, codePoint: 98, plainCodePoint: 98, keyCode: 30, scanCode: 48, metaState: 0)
[log] RawKeyEventDataAndroid#98a2c(flags: 8, codePoint: 118, plainCodePoint: 118, keyCode: 50, scanCode: 47, metaState: 0)
[log] RawKeyEventDataAndroid#5a55b(flags: 520, codePoint: 118, plainCodePoint: 118, keyCode: 50, scanCode: 47, metaState: 0)
[log] RawKeyEventDataAndroid#974c9(flags: 8, codePoint: 99, plainCodePoint: 99, keyCode: 31, scanCode: 46, metaState: 0)
[log] RawKeyEventDataAndroid#970f6(flags: 520, codePoint: 99, plainCodePoint: 99, keyCode: 31, scanCode: 46, metaState: 0)
[log] RawKeyEventDataAndroid#9ed71(flags: 8, codePoint: 120, plainCodePoint: 120, keyCode: 52, scanCode: 45, metaState: 0)
[log] RawKeyEventDataAndroid#2f1c1(flags: 520, codePoint: 120, plainCodePoint: 120, keyCode: 52, scanCode: 45, metaState: 0)
[log] RawKeyEventDataAndroid#b743f(flags: 8, codePoint: 97, plainCodePoint: 97, keyCode: 29, scanCode: 30, metaState: 0)
[log] RawKeyEventDataAndroid#0fe46(flags: 520, codePoint: 97, plainCodePoint: 97, keyCode: 29, scanCode: 30, metaState: 0)
[log] RawKeyEventDataAndroid#9cbea(flags: 8, codePoint: 115, plainCodePoint: 115, keyCode: 47, scanCode: 31, metaState: 0)
[log] RawKeyEventDataAndroid#18484(flags: 520, codePoint: 115, plainCodePoint: 115, keyCode: 47, scanCode: 31, metaState: 0)
[log] RawKeyEventDataAndroid#db987(flags: 8, codePoint: 100, plainCodePoint: 100, keyCode: 32, scanCode: 32, metaState: 0)
[log] RawKeyEventDataAndroid#e785d(flags: 520, codePoint: 100, plainCodePoint: 100, keyCode: 32, scanCode: 32, metaState: 0)
[log] RawKeyEventDataAndroid#20b50(flags: 8, codePoint: 102, plainCodePoint: 102, keyCode: 34, scanCode: 33, metaState: 0)
[log] RawKeyEventDataAndroid#021a6(flags: 520, codePoint: 102, plainCodePoint: 102, keyCode: 34, scanCode: 33, metaState: 0)
[log] RawKeyEventDataAndroid#eaf27(flags: 8, codePoint: 103, plainCodePoint: 103, keyCode: 35, scanCode: 34, metaState: 0)
[log] RawKeyEventDataAndroid#8b875(flags: 520, codePoint: 103, plainCodePoint: 103, keyCode: 35, scanCode: 34, metaState: 0)

```
</details>

Thanks

**Comment by jugbeep** [comment]
Hi @maheshmnj. Thanks for the reply. I think I've figured out what is going on. I added a SnackBar to print out the values when pressing buttons on the remote, and it looks like the value for event.physicalKey.debugName is null, and that was what I was trying to use. Let me double check, and if everything looks good, I'll close the issue.

**Comment by maheshmnj** [comment]
> Let me double check, and if everything looks good, I'll close the issue.

Sure.

**Comment by maheshmnj** [comment]
@jugbeep is this resolved?

**Comment by jugbeep** [comment]
@maheshmnj Yes, it is. Thank you.

**Comment by maheshmnj** [comment]
> @maheshmnj Yes, it is. Thank you.

It would have been great if you could share what was the cause of the issue (if you don't mind ). This will help someone who might stumble on this issue in the future.
