### ISSUE TITLE
WebView makes app crash if it is too big

### ISSUE THREAD

**Issue by mateusfccp** [flutter/flutter#93115]
This is the same #28978, because the former was closed without any proper solution.

I think the only difference is that, apparently, in #28978 the crash would result in the device restarting, which does not happen here.

## Steps to Reproduce

1. Consider the following, minimal, reproducible example:

```dart
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  runApp(
    const MaterialApp(
      home: CrashingWebViewExample(),
    ),
  );
}

class CrashingWebViewExample extends StatelessWidget {
  const CrashingWebViewExample({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const SingleChildScrollView(
      child: SizedBox(
        // If the crash does not happens with 10000, try increasing it. The size required to reproduce may vary from device to device.
        height: 10000,
        child: WebView(
          initialUrl: 'https://en.wikipedia.org/wiki/Cephalopod_size',
        ),
      ),
    );
  }
}
```

2. Try running it on Android.

**Expected results:**

The app runs and shows a webview that has the passed height, showing all the content of the rendered URL.

**Actual results:**

The app crashes with a warning.
This warning was introduced in https://github.com/flutter/engine/pull/8704 and https://github.com/flutter/engine/pull/9110.

```
W/PlatformViewsController(19084): Creating a virtual display of size: [1080, 25500] may result in problems(https://github.com/flutter/flutter/issues/2897).It is larger than the device screen size: [1080, 2065].
E/InputMethodManager(19084): b/117267690: Failed to get fallback IMM with expected displayId=44 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{9c12899 VFEDHVC.. ........ 0,0-1080,4316}
```

**Comment by mateusfccp** [comment]
GitHub won't allow me to place the logs in the main comment because of a characters number limitation, so I am going to attach them here...

[flutter doctor -v.txt](https://github.com/flutter/flutter/files/7483756/flutter.doctor.-v.txt)
[flutter run --verbose.txt](https://github.com/flutter/flutter/files/7483770/flutter.run.--verbose.txt)

**Comment by Binozo** [comment]
This issue is related to the [web_view ](https://pub.dev/packages/webview_flutter) package

**Comment by danagbemava-nc** [comment]
Hi @mateusfccp, have you tried running your sample with `HybridComposition` enabled?

**Comment by mateusfccp** [comment]
@danagbemava-nc 

In HybridComposition mode it seems to work. I am going to update the issue with this additional information.

However, in our case using HybridComposition is non desirable, as we support down to Android SDK 22 (5.1), and, according to the documentation, the HybridComposition mode has performance issues for versions less than Android 10.

**Comment by danagbemava-nc** [comment]
> However, in our case using HybridComposition is non desirable, as we support down to Android SDK 22 (5.1), and, according to the documentation, the HybridComposition mode has performance issues for versions less than Android 10.

Thanks for the extra information. 

I can reproduce the crash with `webview_flutter: ^2.3.0`. In my case however, it does restart my device. 

<details>
<summary>crash logs</summary>

```console
Launching lib/main.dart on M2007J20CG in debug mode...
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:63408/WJii8GF8UMo=/ws
W/PlatformViewsController(30698): Creating a virtual display of size: [1080, 22000] may result in problems(https://github.com/flutter/flutter/issues/2897).It is larger than the device screen size: [1080, 2205].
I/WebViewFactory(30698): Loading com.google.android.webview version 95.0.4638.74 (code 463807433)
W/m.example.emoj(30698): Accessing hidden method Landroid/os/Trace;->isTagEnabled(J)Z (greylist, reflection, allowed)
W/m.example.emoj(30698): Accessing hidden method Landroid/os/Trace;->traceBegin(JLjava/lang/String;)V (greylist, reflection, allowed)
W/m.example.emoj(30698): Accessing hidden method Landroid/os/Trace;->traceEnd(J)V (greylist, reflection, allowed)
W/m.example.emoj(30698): Accessing hidden method Landroid/os/Trace;->asyncTraceBegin(JLjava/lang/String;I)V (greylist, reflection, allowed)
W/m.example.emoj(30698): Accessing hidden method Landroid/os/Trace;->asyncTraceEnd(JLjava/lang/String;I)V (greylist, reflection, allowed)
I/cr_WVCFactoryProvider(30698): Loaded version=95.0.4638.74 minSdkVersion=29 isBundle=true multiprocess=true packageId=2
I/cr_LibraryLoader(30698): Successfully loaded native library
I/cr_CachingUmaRecorder(30698): Flushed 8 samples from 8 histograms.
W/BpBinder(30698): Slow Binder: BpBinder transact took 215ms, interface=, code=50 oneway=false
E/AndroidRuntime(30698): FATAL EXCEPTION: Chrome_ProcessLauncherThread
E/AndroidRuntime(30698): Process: com.example.emoji, PID: 30698
E/AndroidRuntime(30698): DeadSystemException: The system died; earlier logs will point to the root cause
W/BpBinder(30698): Slow Binder: BpBinder transact took 217ms, interface=, code=148 oneway=false
E/MethodChannel#flutter/platform_views(30698): Failed to handle method call
E/MethodChannel#flutter/platform_views(30698): DeadSystemException: The system died; earlier logs will point to the root cause
W/BpBinder(30698): Slow Binder: BpBinder transact took 220ms, interface=, code=29 oneway=false
E/AndroidRuntime(23198): FATAL EXCEPTION: main
E/AndroidRuntime(23198): Process: com.google.android.gms.persistent, PID: 23198
E/AndroidRuntime(23198): DeadSystemException: The system died; earlier logs will point to the root cause
E/AndroidRuntime(30698): FATAL EXCEPTION: Thread-5
E/AndroidRuntime(30698): Process: com.example.emoji, PID: 30698
E/AndroidRuntime(30698): DeadSystemException: The system died; earlier logs will point to the root cause
E/AccessibilityManager(30698): Error during sending EventType: TYPE_WINDOW_STATE_CHANGED; EventTime: 105121032; PackageName: com.example.emoji; MovementGranularity: 0; Action: 0; ContentChangeTypes: [CONTENT_CHANGE_TYPE_PANE_TITLE]; WindowChangeTypes: [] [ ClassName: android.widget.FrameLayout; Text: [ ]; ContentDescription: null; ItemCount: -1; CurrentItemIndex: -1; Enabled: true; Password: false; Checked: false; FullScreen: false; Scrollable: false; BeforeText: null; FromIndex: -1; ToIndex: -1; ScrollX: 0; ScrollY: 0; MaxScrollX: 0; MaxScrollY: 0; ScrollDeltaX: -1; ScrollDeltaY: -1; AddedCount: -1; RemovedCount: -1; ParcelableData: null ]; recordCount: 0
E/AccessibilityManager(30698): android.os.DeadObjectException
E/AccessibilityManager(30698): 	at android.os.BinderProxy.transactNative(Native Method)
E/AccessibilityManager(30698): 	at android.os.BinderProxy.transact(BinderProxy.java:540)
E/AccessibilityManager(30698): 	at android.view.accessibility.IAccessibilityManager$Stub$Proxy.sendAccessibilityEvent(IAccessibilityManager.java:580)
E/AccessibilityManager(30698): 	at android.view.accessibility.AccessibilityManager.sendAccessibilityEvent(AccessibilityManager.java:606)
E/AccessibilityManager(30698): 	at android.view.ViewRootImpl.requestSendAccessibilityEvent(ViewRootImpl.java:8821)
E/AccessibilityManager(30698): 	at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:1103)
E/AccessibilityManager(30698): 	at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:1103)
E/AccessibilityManager(30698): 	at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:1103)
E/AccessibilityManager(30698): 	at android.view.View.notifyViewAccessibilityStateChangedIfNeeded(View.java:13830)
E/AccessibilityManager(30698): 	at android.view.View.setAccessibilityPaneTitle(View.java:8294)
E/AccessibilityManager(30698): 	at io.flutter.view.AccessibilityBridge.setAccessibilityPaneTitle(AccessibilityBridge.java:1872)
E/AccessibilityManager(30698): 	at io.flutter.view.AccessibilityBridge.onWindowNameChange(AccessibilityBridge.java:1860)
E/AccessibilityManager(30698): 	at io.flutter.view.AccessibilityBridge.updateSemantics(AccessibilityBridge.java:1624)
E/AccessibilityManager(30698): 	at io.flutter.view.AccessibilityBridge$1.updateSemantics(AccessibilityBridge.java:318)
E/AccessibilityManager(30698): 	at io.flutter.embedding.engine.FlutterJNI.updateSemantics(FlutterJNI.java:686)
E/AccessibilityManager(30698): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AccessibilityManager(30698): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/AccessibilityManager(30698): 	at android.os.Looper.loop(Looper.java:193)
E/AccessibilityManager(30698): 	at android.app.ActivityThread.main(ActivityThread.java:7889)
E/AccessibilityManager(30698): 	at java.lang.reflect.Method.invoke(Native Method)
E/AccessibilityManager(30698): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
E/AccessibilityManager(30698): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
I/Choreographer(30698): Skipped 46 frames!  The application may be doing too much work on its main thread.
W/System.err(30698): android.os.DeadObjectException
W/System.err(30698): 	at android.os.BinderProxy.transactNative(Native Method)
W/System.err(30698): 	at android.os.BinderProxy.transact(BinderProxy.java:540)
W/System.err(30698): 	at android.app.IActivityTaskManager$Stub$Proxy.handleFreeformModeRequst(IActivityTaskManager.java:7825)
W/System.err(30698): 	at android.app.Activity.getWindowingMode(Activity.java:7417)
W/System.err(30698): 	at android.util.MiuiMultiWindowUtils.updatewindowConfiguration(MiuiMultiWindowUtils.java:1456)
W/System.err(30698): 	at com.android.internal.policy.DecorView.getResources(DecorView.java:2062)
W/System.err(30698): 	at com.android.internal.policy.DecorView.onDraw(DecorView.java:368)
W/System.err(30698): 	at android.view.View.draw(View.java:22518)
W/System.err(30698): 	at com.android.internal.policy.DecorView.draw(DecorView.java:819)
W/System.err(30698): 	at android.view.View.updateDisplayListIfDirty(View.java:21386)
W/System.err(30698): 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
W/System.err(30698): 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
W/System.err(30698): 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:642)
W/System.err(30698): 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4219)
W/System.err(30698): 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3933)
W/System.err(30698): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3204)
W/System.err(30698): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2046)
W/System.err(30698): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8349)
W/System.err(30698): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1058)
W/System.err(30698): 	at android.view.Choreographer.doCallbacks(Choreographer.java:880)
W/System.err(30698): 	at android.view.Choreographer.doFrame(Choreographer.java:813)
W/System.err(30698): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1043)
W/System.err(30698): 	at android.os.Handler.handleCallback(Handler.java:938)
W/System.err(30698): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err(30698): 	at android.os.Looper.loop(Looper.java:236)
W/System.err(30698): 	at android.app.ActivityThread.main(ActivityThread.java:7889)
W/System.err(30698): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(30698): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
W/System.err(30698): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
W/System.err(30698): android.os.DeadObjectException
W/System.err(30698): 	at android.os.BinderProxy.transactNative(Native Method)
W/System.err(30698): 	at android.os.BinderProxy.transact(BinderProxy.java:540)
W/System.err(30698): 	at android.app.IActivityTaskManager$Stub$Proxy.handleFreeformModeRequst(IActivityTaskManager.java:7825)
W/System.err(30698): 	at android.app.Activity.getWindowingMode(Activity.java:7417)
W/System.err(30698): 	at android.util.MiuiMultiWindowUtils.updatewindowConfiguration(MiuiMultiWindowUtils.java:1456)
W/System.err(30698): 	at com.android.internal.policy.DecorView.getResources(DecorView.java:2062)
W/System.err(30698): 	at com.android.internal.policy.DecorView.onPostDraw(DecorView.java:2416)
W/System.err(30698): 	at android.view.ViewRootImpl.onPostDraw(ViewRootImpl.java:3771)
W/System.err(30698): 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:591)
W/System.err(30698): 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:642)
W/System.err(30698): 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4219)
W/System.err(30698): 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3933)
W/System.err(30698): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3204)
W/System.err(30698): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2046)
W/System.err(30698): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8349)
W/System.err(30698): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1058)
W/System.err(30698): 	at android.view.Choreographer.doCallbacks(Choreographer.java:880)
W/System.err(30698): 	at android.view.Choreographer.doFrame(Choreographer.java:813)
W/System.err(30698): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1043)
W/System.err(30698): 	at android.os.Handler.handleCallback(Handler.java:938)
W/System.err(30698): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err(30698): 	at android.os.Looper.loop(Looper.java:236)
W/System.err(30698): 	at android.app.ActivityThread.main(ActivityThread.java:7889)
W/System.err(30698): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(30698): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
W/System.err(30698): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
E/ProcessInjector(30698): error while reportKillProcessEvent to system server!
E/ProcessInjector(30698): java.lang.reflect.InvocationTargetException
E/ProcessInjector(30698): 	at java.lang.reflect.Method.invoke(Native Method)
E/ProcessInjector(30698): 	at android.os.ProcessInjector.reportKillProcessEvent(ProcessInjector.java:24)
E/ProcessInjector(30698): 	at android.os.Process.killProcess(Process.java:1146)
E/ProcessInjector(30698): 	at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:180)
E/ProcessInjector(30698): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
E/ProcessInjector(30698): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
E/ProcessInjector(30698): 	at java.lang.Thread.dispatchUncaughtException(Thread.java:2203)
E/ProcessInjector(30698): Caused by: android.os.DeadObjectException
E/ProcessInjector(30698): 	at android.os.BinderProxy.transactNative(Native Method)
E/ProcessInjector(30698): 	at android.os.BinderProxy.transact(BinderProxy.java:540)
E/ProcessInjector(30698): 	at android.app.IActivityManager$Stub$Proxy.reportKillProcessEvent(IActivityManager.java:10344)
E/ProcessInjector(30698): 	... 7 more
I/Process (30698): Sending signal. PID: 30698 SIG: 9
E/AndroidRuntime(30932): FATAL EXCEPTION: main
E/AndroidRuntime(30932): PID: 30932
E/AndroidRuntime(30932): DeadSystemException: The system died; earlier logs will point to the root cause
Lost connection to device.
Exited (sigterm)
```
</details>

<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.5.3 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (4 available)
    • M2007J20CG (mobile)    • 5dd3be00                  • android-arm64  • Android 11 (API 30)
    • Nexus’ IPhone (mobile) • 00008020-001875E83A38002E • ios            • iOS 15.0.2 19A404
    • macOS (desktop)        • macos                     • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 95.0.4638.69

• No issues found!
```

```console
[✓] Flutter (Channel master, 2.6.0-12.0.pre.603, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.6.0-12.0.pre.603 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 058dfd49a0 (12 hours ago), 2021-11-05 03:37:55 +0200
    • Engine revision 3364409b91
    • Dart version 2.15.0 (build 2.15.0-268.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (4 available)
    • M2007J20CG (mobile)    • 5dd3be00                  • android-arm64  • Android 11 (API 30)
    • Nexus’ IPhone (mobile) • 00008020-001875E83A38002E • ios            • iOS 15.0.2 19A404
    • macOS (desktop)        • macos                     • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 95.0.4638.69

• No issues found!
```
</details>

**Comment by andychan06** [comment]
Hello, is there any workaround for this issue? Also, I found that the scroll performance of the WebView with large height inside scroll view was very laggy. Is it only the case to me?

**Comment by mateusfccp** [comment]
> Hello, is there any workaround for this issue? Also, I found that the scroll performance of the WebView with large height inside scroll view was very laggy. Is it only the case to me?

The workaround for me was to use hybrid mode, which is now default anyway...

**Comment by andychan06** [comment]
@mateusfccp thanks, how about if you have the laggy scroll when wrapping the WebView inside SingleChildScrollView.

**Comment by mateusfccp** [comment]
> @mateusfccp thanks, how about if you have the laggy scroll when wrapping the WebView inside SingleChildScrollView. 

I don't know, I didn't experience this... Maybe check if there's an issue about it or open one

**Comment by dnfield** [comment]
@bparrishMines @cyanglaz this is what we were just talking about

**Comment by mateusfccp** [comment]
@danagbemava-nc We used to have this issue when using virtual mode, and switching to hybrid mode resolved it.

However, we starting seeing this again in our production app for some time, now.

We are using `webview_flutter: ^3.0.1` and Flutter 3.0.4.

This means that, for some reason, this issue is now also happening in hybrid mode. Maybe this was a regression caused by some update? Do you want me to open a different issue or do we update this one?

**Comment by danagbemava-nc** [comment]
Hi @mateusfccp, kindly file a new issue and provide all the relevant information that you can provide. 

Kindly also check for duplicates as well. You may also want to upgrade to the latest version of stable to see if the bug still occurs.

**Comment by monssurkijo6-ops** [comment]
> This is the same as #28978,  but I opened another issue because the former was closed and locked without any proper solution.
> 
> In my device, differently from #28978, the app crashed and closed, but the device did not restart.
> 
> As noted by @danagbemava-nc, this issue does not happen when in hybrid composition mode.
> 
> ## Steps to Reproduce
> 
> 1. Consider the following, minimal, reproducible example:
> 
> ```dart
> import 'package:flutter/material.dart';
> import 'package:webview_flutter/webview_flutter.dart';
> 
> void main() {
>   runApp(
>     const MaterialApp(
>       home: CrashingWebViewExample(),
>     ),
>   );
> }
> 
> class CrashingWebViewExample extends StatelessWidget {
>   const CrashingWebViewExample({Key? key}) : super(key: key);
> 
>   @override
>   Widget build(BuildContext context) {
>     return const SingleChildScrollView(
>       child: SizedBox(
>         // If the crash does not happens with 10000, try increasing it. The size required to reproduce may vary from device to device.
>         height: 10000,
>         child: WebView(
>           initialUrl: 'https://en.wikipedia.org/wiki/Cephalopod_size',
>         ),
>       ),
>     );
>   }
> }
> ```
> 
> 2. Try running it on Android.
> 
> **Expected results:**
> 
> The app runs and shows a webview that has the passed height, showing all the content of the rendered URL.
> 
> **Actual results:**
> 
> The app crashes with a warning.
> This warning was introduced in https://github.com/flutter/engine/pull/8704 and https://github.com/flutter/engine/pull/9110.
> 
> ```
> W/PlatformViewsController(19084): Creating a virtual display of size: [1080, 25500] may result in problems(https://github.com/flutter/flutter/issues/2897).It is larger than the device screen size: [1080, 2065].
> E/InputMethodManager(19084): b/117267690: Failed to get fallback IMM with expected displayId=44 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{9c12899 VFEDHVC.. ........ 0,0-1080,4316}
> ```
