### ISSUE TITLE
type 'X' is not a subtype of type 'X'

### ISSUE THREAD

**Issue by lejard-h** [flutter/flutter#9319]
Run on Android device, the repo is public
https://github.com/dart-flitter/flitter/tree/bug
https://github.com/dart-flitter/flitter/blob/bug/lib/app.dart

## Logs

```
I/flutter ( 3524): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 3524): The following assertion was thrown building FutureBuilder<List<Room>>(dirty; state:
I/flutter ( 3524): _FutureBuilderState<List<Room>>#103010518()):
I/flutter ( 3524): type 'AppState' is not a subtype of type 'AppState' of 'app' where
I/flutter ( 3524):   AppState is from file:///Users/lejard_h/github/flitter/lib/app.dart
I/flutter ( 3524):   App is from file:///Users/lejard_h/github/flitter/lib/app.dart
I/flutter ( 3524):   AppState is from package:flitter/app.dart
I/flutter ( 3524):   App is from package:flitter/app.dart
I/flutter ( 3524): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 3524): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 3524): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 3524):   https://github.com/flutter/flutter/issues/new
I/flutter ( 3524): When the exception was thrown, this was the stack:
I/flutter ( 3524): #0      HomeView.HomeView (package:flitter/widgets/routes/home.dart:18)
I/flutter ( 3524): #1      AppState.getRoomsAndBuidlHome.<anonymous closure> (file:///Users/lejard_h/github/flitter/lib/app.dart:77)
I/flutter ( 3524): #2      _FutureBuilderState.build (package:flutter/src/widgets/async.dart:432)
I/flutter ( 3524): #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:3180)
I/flutter ( 3524): #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3090)
I/flutter ( 3524): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:2991)
I/flutter ( 3524): #6      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:1866)
I/flutter ( 3524): #7      BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.beginFrame (package:flutter/src/widgets/binding.dart:353)
I/flutter ( 3524): #8      BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:170)
I/flutter ( 3524): #9      BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:645)
I/flutter ( 3524): #10     BindingBase&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:580)
I/flutter ( 3524): #11     _beginFrame (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:83)
I/flutter ( 3524): ════════════════════════════════════════════════════════════════════════════════════════════════════

```

## Flutter Doctor

```
[✓] Flutter (on Mac OS X 10.12.3 16D32, channel master)
    • Flutter at /Users/lejard_h/flutter
    • Framework revision ff23a1ebfe (3 hours ago), 2017-04-10 10:51:31 -0700
    • Engine revision 5d9a642257
    • Tools Dart version 1.23.0-dev.11.6

[✓] Host Executable Compatibility
    • Downloaded executables execute on host

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/lejard_h/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b05)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.1, Build version 8E1000a
    • ios-deploy 1.9.0
    • CocoaPods version 1.2.0

[✓] Android Studio (version 2.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 2.14.1
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b05)

[✓] Gradle (2.14.1)
    • gradle-dir = /Applications/Android Studio.app/Contents/gradle/gradle-2.14.1/
    • Flutter supports building with Gradle from Android Studio.
      Consider removing your gradle-dir setting by running:
      flutter config --gradle-dir=

[✓] IntelliJ IDEA Ultimate Edition (version 2016.3.4)
    • Dart plugin version 163.13137
    • Flutter plugin version 12.0

[✓] WebStorm (version 2016.3.3)
    • Flutter plugin version 0.1.10

[✓] Connected devices
    • F3111 • RQ3003LTVT • android-arm • Android 6.0 (API 23)

```

**Comment by lejard-h** [comment]
resolved

I was importing my file in 2 different ways:

`import "app.dart"; // bad`
`import "package:flitter/app.dart; // good`
