### ISSUE TITLE
Flutter apps crashes on older version of Android e.g 4.4.2 

### ISSUE THREAD

**Issue by mohadel92** [flutter/flutter#93239]
## Steps to Reproduce

my flutter apps that is available on the store always crashes on older version of android for example Android Kitkat 4.4.2
i tried to do somework around for this isssue and i managed to keep my app away from crashing but after a google play services update on my android kitkat device the app came back to crashing again
this issue affect many android apps , i tried to install showcases android apps build with flutter all of them kept crashing 
e.g (Reflectly app ,Postmuse – Instagram photo editing app,Flutter Gallery,...)

**Expected results:** 
flutter apps should run on older version of android with no issues if they match minSdkversion

**Actual results:** 
apps always crashes on older version of android

<details>
<summary>Code sample</summary>

```dart
```

</details>

```
```

```
```

```
 Flutter (Channel stable, 2.5.3, on macOS 11.3 20E232 darwin-x64, locale en-EG)
    • Flutter version 2.5.3 at /Users/mohammedadelalisorour/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/mohammedadelalisorour/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (3 available)
    • Redmi Note 5 (mobile)      • 47c30211                             • android-arm64  • Android 9 (API 28)
    • iPhone 12 Pro Max (mobile) • 8F7515DF-628E-479C-A28F-DD43AED409ED • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome
      95.0.4638.69
```

</details>

**Comment by mohadel92** [comment]
new flutter doctor results
` Flutter (Channel stable, 2.5.3, on macOS 11.3 20E232 darwin-x64, locale en-EG)
    • Flutter version 2.5.3 at /Users/mohammedadelalisorour/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/mohammedadelalisorour/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

⢿^[[1;2⣟^[[1;2⣯^[[1;2B^[[1;2B^[[1;2⣷^[[1;2B^[[1;2[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • 8F7515DF-628E-479C-A28F-DD43AED409ED • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome
      95.0.4638.69`

**Comment by darshankawar** [comment]
@mohadel92 
Does the crash occur in debug or in release mode ?
Can you provide the entire crash log in properly formatted text ?

**Comment by mohadel92** [comment]
> @mohadel92 Does the crash occur in debug or in release mode ? Can you provide the entire crash log in properly formatted text ?

it used to crash in the debug mode with the same scenrio
i did some modification to the android app : 
   1- added to`android/build.gradle`

`        classpath 'com.google.gms:google-services:4.3.10'
`
  2- added to`android/app/build.gradle`
        a-  `implementation 'com.android.support:multidex:1.0.3'`
        b-  `apply plugin: 'com.google.gms.google-services'`
 3- Created a file called `MyApplication.java`

with the next code 
   `package com.-------------.------------;

import android.app.Application;
import android.content.Context;

import androidx.multidex.MultiDex;

public class MyApplication extends Application {

    @Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        MultiDex.install(this);
    }

}`

in this stage the app worked fine but i couldn't do any Api call `{POST,GET,DELETE}`  although i was using the lastest version of my `dio package`

i have created a new dart file with the next implementation
   `import 'dart:io';

class MyHttpOverrides extends HttpOverrides{
  @override
  HttpClient createHttpClient(SecurityContext context){
    return super.createHttpClient(context)
      ..badCertificateCallback = (X509Certificate cert, String host, int port)=> true;
  }
}

`
at this situation the app worked fine no crashes and api calls are working fine
so i tested my app on a local Lenovo tablet A5000 and uploaded my app to android app testing site
called `https://appetize.io/` to test on multiple android 4.4.2 devices and both environment worked very good

4- in this stage i uploaded my app to the play store and the app worked good **BUT IT ASKED FOR UPADTING THE GOOGLE PLAY SERVICES ON MY OLDER DEVICE , WHEN I DID SO THE APP KEPT CRAHSING AFTER UPDATING GOOGLE PLAY SERVICES **

all apps built with flutter that i have tested undergo the same issue

**Comment by mohadel92** [comment]
<a href="https://ibb.co/gD1yxXH"><img src="https://i.ibb.co/9qXn7fz/Screenshot-2021-11-09-11-40-01.png" alt="Screenshot-2021-11-09-11-40-01" border="0"></a>

**Comment by darshankawar** [comment]
@mohadel92 
Please provide the crash log in text format instead of in screenshots, for better readability.
Also, since you are using very old version of Android (4.4.2), I am not sure if the device handles update of Google play service, so the crash doesn't seem to be specific to Flutter, but combination of old version's compatibility with Google play. For some reason, the device and OS you are using doesn't seem to be capable or handle the update properly which is leading to crashes in your app. You'll need to search over internet any solutions on it or use a bit recent OS version.

**Comment by mohadel92** [comment]
`
java.lang.NoClassDefFoundError: io.flutter.FlutterInjector$Builder
at io.flutter.FlutterInjector.instance(FlutterInjector.java:55)
at io.flutter.app.Flutter Application.onCreate(Flutter Application.java:24)
at
android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1
007)
at
android.app.ActivityThread.handleBindApplication(ActivityThread.java:4541
)
at android.app.ActivityThread.access$1500(ActivityThread.java:151)
at
android.app.Activity Thread$H.handleMessage(ActivityThread.java:1381)
at android.os.Handler.dispatchMessage(Handler.java:110)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:5299)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.jav
a:836)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)
at dalvik.system.NativeStart.main(Native Method)
`
okay i will consider my self as a source of the problem , what about other 'show case' flutter apps they all crash(at least in my trials' on older version of flutter , in my case supporting older version of flutter is mandatory in my app use case 

thanks

**Comment by darshankawar** [comment]
@mohadel92 
Can you provide us a complete minimal reproducible code sample without any 3rd party plugins, that we can use to verify ?

**Comment by darshankawar** [comment]
The least OS emulator version I've is 4.5.1 on which the counter app runs properly. Keeping it open for further investigation.

OP's Crash log: https://github.com/flutter/flutter/issues/93239#issuecomment-964925904
