### ISSUE TITLE
Flutter could not download and/or extract [...]

### ISSUE THREAD

**Issue by MelbourneDeveloper** [flutter/flutter#93269]
Flutter is completely broken on my computer. I cannot do anything. This happened after running 'flutter upgrade' yesterday

Other people have had [this issue](https://github.com/flutter/flutter/issues/27024) in the past.

I do have network connectivity and I can directly download this file from the browser (https://storage.googleapis.com/flutter_infra_release/flutter/d3ea636dc5d16b56819f3266241e1f708979c233/windows-x64/artifacts.zip).

## Steps to Reproduce

`Flutter doctor`

`Flutter pub get`

## Logs

<details>
<summary>Logs</summary>

```
flutter pub get --verbose
[  +58 ms] executing: [C:\Flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +208 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 18116933e77adc82f80866c928266a5b4f1ed645
[        ] executing: [C:\Flutter/] git tag --points-at 18116933e77adc82f80866c928266a5b4f1ed645
[  +50 ms] Exit code 0 from: git tag --points-at 18116933e77adc82f80866c928266a5b4f1ed645
[        ] 2.5.3
[   +7 ms] executing: [C:\Flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +32 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\Flutter/] git ls-remote --get-url origin
[  +30 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +95 ms] executing: [C:\Flutter/] git rev-parse --abbrev-ref HEAD
[  +34 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +45 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +8 ms] Downloading package sky_engine...
[ +183 ms] Content https://storage.googleapis.com/flutter_infra_release/flutter/d3ea636dc5d16b56819f3266241e1f708979c233/sky_engine.zip md5 hash: z731zO6Wn9VeJXVyRC1r+A==[ +221 ms] Downloading package sky_engine... (completed in 397ms)
[ +286 ms] Downloading flutter_patched_sdk tools...
[  +32 ms] Content https://storage.googleapis.com/flutter_infra_release/flutter/d3ea636dc5d16b56819f3266241e1f708979c233/flutter_patched_sdk.zip md5 hash:
ElflqjJ2TKahkWP9JfTRiQ==
[ +565 ms] Downloading flutter_patched_sdk tools... (completed in 598ms)
[ +323 ms] Downloading flutter_patched_sdk_product tools...
[  +25 ms] Content https://storage.googleapis.com/flutter_infra_release/flutter/d3ea636dc5d16b56819f3266241e1f708979c233/flutter_patched_sdk_product.zip md5 hash:        
e+XU23C0dXw1lnVXhqv1rg==
[ +534 ms] Downloading flutter_patched_sdk_product tools... (completed in 559ms)
[ +320 ms] Downloading windows-x64 tools...
[ +228 ms] Content https://storage.googleapis.com/flutter_infra_release/flutter/d3ea636dc5d16b56819f3266241e1f708979c233/windows-x64/artifacts.zip md5 hash:
yppLSDDc/km6/GEGxoW0Hg==
[+4360 ms] Downloading windows-x64 tools... (completed in 4.6s)
[  +44 ms] Downloading windows-x64 tools...
[ +241 ms] Content https://storage.googleapis.com/flutter_infra_release/flutter/d3ea636dc5d16b56819f3266241e1f708979c233/windows-x64/artifacts.zip md5 hash:
yppLSDDc/km6/GEGxoW0Hg==
[+4253 ms] Downloading windows-x64 tools... (completed in 4.5s)
[  +45 ms] "flutter get" took 11,691ms.
[  +20 ms] Flutter could not download and/or extract
https://storage.googleapis.com/flutter_infra_release/flutter/d3ea636dc5d16b56819f3266241e1f708979c233/windows-x64/artifacts.zip.
           Ensure you have network connectivity and all of the required dependencies listed at flutter.dev/setup.
           The original exception was: Exception: Flutter failed to write to a file at "C:\Flutter\bin\cache\artifacts\engine\windows-x64\icudtl.dat". The file is being
used by
           another program.
           FileSystemException: Cannot open file, path = 'C:\Flutter\bin\cache\artifacts\engine\windows-x64\icudtl.dat' (OS Error: The requested operation cannot be    
           file with a user-mapped section open.
           , errno = 1224)
           Do you have an antivirus program running? Try disabling your antivirus program and try again..
[   +2 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      ArtifactUpdater._downloadArchive (package:flutter_tools/src/cache.dart:984:11)
           <asynchronous suspension>
           #2      EngineCachedArtifact.updateInner (package:flutter_tools/src/cache.dart:786:7)
           <asynchronous suspension>
           #3      CachedArtifact.update (package:flutter_tools/src/cache.dart:688:5)
           <asynchronous suspension>
           #4      Cache.updateAll (package:flutter_tools/src/cache.dart:557:9)
           <asynchronous suspension>
           #5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1227:7)
           <asynchronous suspension>
           #6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>


[ +228 ms] ensureAnalyticsSent: 225ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

```
flutter doctor -v
Downloading package sky_engine...                                  407ms
Downloading flutter_patched_sdk tools...                           566ms
Downloading flutter_patched_sdk_product tools...                   555ms
Downloading windows-x64 tools...                                    4.5s
Downloading windows-x64 tools...                                    4.6s
Flutter could not download and/or extract https://storage.googleapis.com/flutter_infra_release/flutter/d3ea636dc5d16b56819f3266241e1f708979c233/windows-x64/artifacts.zip.Ensure you have network connectivity and all of the required dependencies listed at flutter.dev/setup.
The original exception was: Exception: Flutter failed to write to a file at "C:\Flutter\bin\cache\artifacts\engine\windows-x64\icudtl.dat". The file is being used by     
another program.
FileSystemException: Cannot open file, path = 'C:\Flutter\bin\cache\artifacts\engine\windows-x64\icudtl.dat' (OS Error: The requested operation cannot be performed on a  
file with a user-mapped section open.
, errno = 1224)
Do you have an antivirus program running? Try disabling your antivirus program and try again..

#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      ArtifactUpdater._downloadArchive (package:flutter_tools/src/cache.dart:984:11)
<asynchronous suspension>
#2      EngineCachedArtifact.updateInner (package:flutter_tools/src/cache.dart:786:7)
<asynchronous suspension>
#3      CachedArtifact.update (package:flutter_tools/src/cache.dart:688:5)
<asynchronous suspension>
#4      Cache.updateAll (package:flutter_tools/src/cache.dart:557:9)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1227:7)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
<asynchronous suspension>
#12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     main (package:flutter_tools/executable.dart:92:3)
<asynchronous suspension>
```

</details>

**Comment by darshankawar** [comment]
@MelbourneDeveloper 
The main error seems to be:

```
`Flutter could not download and/or extract
https://storage.googleapis.com/flutter_infra_release/flutter/d3ea636dc5d16b56819f3266241e1f708979c233/windows-x64/artifacts.zip.
           Ensure you have network connectivity and all of the required dependencies listed at flutter.dev/setup.
           The original exception was: Exception: Flutter failed to write to a file at "C:\Flutter\bin\cache\artifacts\engine\windows-x64\icudtl.dat". The file is being
used by
           another program.
           FileSystemException: Cannot open file, path = 'C:\Flutter\bin\cache\artifacts\engine\windows-x64\icudtl.dat' (OS Error: The requested operation cannot be    
           file with a user-mapped section open.
           , errno = 1224)
           Do you have an antivirus program running? Try disabling your antivirus program and try again..`
```

Which seems to indicate the file is being used elsewhere or is open and hence cannot be copied until it is closed. Also the message asks this `Do you have an antivirus program running? Try disabling your antivirus program and try again..`. See if you have Antivirus enabled which may be preventing the files being copied properly.

**Comment by maheshmnj** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
