### ISSUE TITLE
Stack frame filtering should collapse long tree walks

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#9329]
It feels like a simple message saying "Failed host lookup: 'd3rt1990lpmkn.cloudfront.net' (OS Error: Non-recoverable error, errno = -4)"  "Can't load image"

would be sufficient.  The stack trace doesn't add much of value.

```
[00094.792] 18313.18355>  EXCEPTION CAUGHT BY SERVICES 
[00094.796] 18313.18355> The following SocketException was thrown resolving a single-frame image stream:
[00094.796] 18313.18355> Failed host lookup: 'd3rt1990lpmkn.cloudfront.net' (OS Error: Non-recoverable error, errno = -4)
[00094.811] 18313.18355> 
[00094.811] 18313.18355> When the exception was thrown, this was the stack:
[00094.820] 18313.18355> #0      IOClient.send (package:http/src/io_client.dart:30)
[00094.820] 18313.18355> <asynchronous suspension>
[00094.820] 18313.18355> #1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:171)
[00094.820] 18313.18355> <asynchronous suspension>
[00094.820] 18313.18355> #2      BaseClient.get (package:http/src/base_client.dart:34)
[00094.820] 18313.18355> #3      NetworkImage._loadAsync (package:flutter/src/services/image_provider.dart:342)
[00094.820] 18313.18355> <asynchronous suspension>
[00094.820] 18313.18355> #4      NetworkImage.load (package:flutter/src/services/image_provider.dart:328)
[00094.820] 18313.18355> #5      ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/services/image_provider.dart:169)
[00094.821] 18313.18355> #6      ImageCache.putIfAbsent (package:flutter/src/services/image_cache.dart:82)
[00094.821] 18313.18355> #7      ImageProvider.resolve.<anonymous closure> (package:flutter/src/services/image_provider.dart:169)
[00094.821] 18313.18355> #8      SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:38)
[00094.821] 18313.18355> #9      ImageProvider.resolve (package:flutter/src/services/image_provider.dart:167)
[00094.821] 18313.18355> #10     _ImageState._resolveImage (package:flutter/src/widgets/image.dart:259)
[00094.821] 18313.18355> #11     _ImageState.didChangeDependencies (package:flutter/src/widgets/image.dart:241)
[00094.821] 18313.18355> #12     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3193)
[00094.821] 18313.18355> #13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3052)
[00094.821] 18313.18355> #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2474)
[00094.821] 18313.18355> #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2277)
[00094.821] 18313.18355> #16     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4018)
[00094.821] 18313.18355> #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2474)
[00094.821] 18313.18355> #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2277)
[00094.821] 18313.18355> #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4018)
[00094.821] 18313.18355> #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2474)
[00094.821] 18313.18355> #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2277)
[00094.821] 18313.18355> #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3089)
[00094.821] 18313.18355> #23     Element.rebuild (package:flutter/src/widgets/framework.dart:2978)
[00094.821] 18313.18355> #24     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3057)
[00094.821] 18313.18355> #25     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3052)
[00094.821] 18313.18355> #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2474)
[00094.821] 18313.18355> #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2277)
[00094.821] 18313.18355> #28     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4018)
[00094.821] 18313.18355> #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2474)
[00094.821] 18313.18355> #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2277)
[00094.821] 18313.18355> #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3089)
[00094.821] 18313.18355> #32     Element.rebuild (package:flutter/src/widgets/framework.dart:2978)
[00094.821] 18313.18355> #33     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3057)
[00094.821] 18313.18355> #34     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3052)
[00094.821] 18313.18355> #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2474)
[00094.821] 18313.18355> #36     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4121)
[00094.821] 18313.18355> #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2474)
[00094.821] 18313.18355> #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2277)
[00094.821] 18313.18355> #39     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4018)
[00094.821] 18313.18355> #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2474)
[00094.822] 18313.18355> #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2277)
[00094.822] 18313.18355> #42     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4018)
[00094.822] 18313.18355> #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2474)
[00094.822] 18313.18355> #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2277)
[00094.822] 18313.18355> #45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3089)
[00094.822] 18313.18355> #46     Element.rebuild (package:flutter/src/widgets/framework.dart:2978)
[00094.822] 18313.18355> #47     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3057)
[00094.822] 18313.18355> #48     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3195)
[00094.822] 18313.18355> #49     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3052)
[00094.822] 18313.18355> #50     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2474)
[00094.822] 18313.18355> #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2277)
[00094.822] 18313.18355> #52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3089)
[00094.822] 18313.18355> #53     Element.rebuild (package:flutter/src/widgets/framework.dart:2978)
[00094.822] 18313.18355> #54     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3057)
[00094.822] 18313.18355> #55     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3052)
[00094.822] 18313.18355> #56     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2474)
[00094.822] 18313.18355> #57     Element.updateChild (package:flutter/src/widgets/framework.dart:2277)
[00094.822] 18313.18355> #58     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4018)
[00094.822] 18313.18355> #59     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2474)
[00094.822] 18313.18355> #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2277)
[00094.822] 18313.18355> #61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3089)
[00094.822] 18313.18355> #62     Element.rebuild (package:flutter/src/widgets/framework.dart:2978)
[00094.822] 18313.18355> #63     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3057)
[00094.822] 18313.18355> #64     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3052)
[00094.822] 18313.18355> #65     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2474)
[00094.822] 18313.18355> #66     Element.updateChild (package:flutter/src/widgets/framework.dart:2277)
[00094.822] 18313.18355> #67     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4018)
[00094.822] 18313.18355> #68     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2474)
[00094.822] 18313.18355> #69     Element.updateChild (package:flutter/src/widgets/framework.dart:2277)
[00094.822] 18313.18355> #70     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4018)
[00094.822] 18313.18355> #71     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2474)
[00094.822] 18313.18355> #72     Element.updateChild (package:flutter/src/widgets/framework.dart:2277)
[00094.822] 18313.18355> #73     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4018)
[00094.822] 18313.18355> #74     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2474)
[00094.822] 18313.18355> #75     Element.updateChild (package:flutter/src/widgets/framework.dart:2277)
[00094.823] 18313.18355> #76     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3089)
[00094.823] 18313.18355> #77     Element.rebuild (package:flutter/src/widgets/framework.dart:2978)
[00094.823] 18313.18355> #78     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3057)
[00094.823] 18313.18355> #79     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3052)
[00094.823] 18313.18355> #80     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2474)
[00094.823] 18313.18355> #81     Element.updateChild (package:flutter/src/widgets/framework.dart:2277)
[00094.823] 18313.18355> #82     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3089)
[00094.823] 18313.18355> #83     Element.rebuild (package:flutter/src/widgets/framework.dart:2978)
[00094.823] 18313.18355> #84     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3057)
[00094.823] 18313.18355> #85     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3052)
[00094.823] 18313.18355> #86     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2474)
[00094.823] 18313.18355> #87     Element.updateChild (package:flutter/src/widgets/framework.dart:2277)
[00094.823] 18313.18355> #88     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4025)
[00094.823] 18313.18355> #89     Element.updateChild (package:flutter/src/widgets/framework.dart:2266)
[00094.823] 18313.18355> #90     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4025)
[00094.823] 18313.18355> #91     Element.updateChild (package:flutter/src/widgets/framework.dart:2266)
[00094.823] 18313.18355> #92     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3089)
[00094.823] 18313.18355> #93     Element.rebuild (package:flutter/src/widgets/framework.dart:2978)
[00094.823] 18313.18355> #94     ProxyElement.update (package:flutter/src/widgets/framework.dart:3325)
[00094.823] 18313.18355> #95     Element.updateChild (package:flutter/src/widgets/framework.dart:2266)
[00094.823] 18313.18355> #96     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:3751)
[00094.823] 18313.18355> #97     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4131)
[00094.823] 18313.18355> #98     Element.updateChild (package:flutter/src/widgets/framework.dart:2266)
[00094.823] 18313.18355> #99     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4025)
[00094.823] 18313.18355> #100    Element.updateChild (package:flutter/src/widgets/framework.dart:2266)
[00094.823] 18313.18355> #101    SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:507)
[00094.823] 18313.18355> #102    SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:480)
[00094.823] 18313.18355> #103    Element.updateChild (package:flutter/src/widgets/framework.dart:2266)
[00094.823] 18313.18355> #104    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:3751)
[00094.823] 18313.18355> #105    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4131)
[00094.823] 18313.18355> #106    ViewportElement.update (package:flutter/src/widgets/viewport.dart:83)
[00094.823] 18313.18355> #107    Element.updateChild (package:flutter/src/widgets/framework.dart:2266)
[00094.823] 18313.18355> #108    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4025)
[00094.823] 18313.18355> #109    Element.updateChild (package:flutter/src/widgets/framework.dart:2266)
[00094.823] 18313.18355> #110    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4025)
[00094.823] 18313.18355> #111    Element.updateChild (package:flutter/src/widgets/framework.dart:2266)
[00094.823] 18313.18355> #112    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4025)
[00094.823] 18313.18355> #113    Element.updateChild (package:flutter/src/widgets/framework.dart:2266)
[00094.824] 18313.18355> #114    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3089)
[00094.824] 18313.18355> #115    Element.rebuild (package:flutter/src/widgets/framework.dart:2978)
[00094.824] 18313.18355> #116    StatefulElement.update (package:flutter/src/widgets/framework.dart:3214)
[00094.824] 18313.18355> #117    Element.updateChild (package:flutter/src/widgets/framework.dart:2266)
[00094.824] 18313.18355> #118    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4025)
[00094.824] 18313.18355> #119    Element.updateChild (package:flutter/src/widgets/framework.dart:2266)
[00094.824] 18313.18355> #120    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4025)
[00094.824] 18313.18355> #121    Element.updateChild (package:flutter/src/widgets/framework.dart:2266)
[00094.824] 18313.18355> #122    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4025)
[00094.824] 18313.18355> #123    Element.updateChild (package:flutter/src/widgets/framework.dart:2266)
[00094.824] 18313.18355> #124    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3089)
[00094.824] 18313.18355> #125    Element.rebuild (package:flutter/src/widgets/framework.dart:2978)
[00094.824] 18313.18355> #126    StatelessElement.update (package:flutter/src/widgets/framework.dart:3139)
[00094.824] 18313.18355> #127    Element.updateChild (package:flutter/src/widgets/framework.dart:2266)
[00094.824] 18313.18355> #128    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3089)
[00094.824] 18313.18355> #129    Element.rebuild (package:flutter/src/widgets/framework.dart:2978)
[00094.824] 18313.18355> #130    StatefulElement.update (package:flutter/src/widgets/framework.dart:3214)
[00094.824] 18313.18355> #131    Element.updateChild (package:flutter/src/widgets/framework.dart:2266)
[00094.824] 18313.18355> #132    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3089)
[00094.824] 18313.18355> #133    Element.rebuild (package:flutter/src/widgets/framework.dart:2978)
[00094.824] 18313.18355> #134    StatefulElement.update (package:flutter/src/widgets/framework.dart:3214)
[00094.824] 18313.18355> #135    Element.updateChild (package:flutter/src/widgets/framework.dart:2266)
[00094.824] 18313.18355> #136    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3089)
[00094.824] 18313.18355> #137    Element.rebuild (package:flutter/src/widgets/framework.dart:2978)
[00094.824] 18313.18355> #138    StatelessElement.update (package:flutter/src/widgets/framework.dart:3139)
[00094.824] 18313.18355> #139    Element.updateChild (package:flutter/src/widgets/framework.dart:2266)
[00094.824] 18313.18355> #140    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4025)
[00094.824] 18313.18355> #141    Element.updateChild (package:flutter/src/widgets/framework.dart:2266)
[00094.824] 18313.18355> #142    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4025)
[00094.824] 18313.18355> #143    Element.updateChild (package:flutter/src/widgets/framework.dart:2266)
[00094.824] 18313.18355> #144    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3089)
[00094.824] 18313.18355> #145    Element.rebuild (package:flutter/src/widgets/framework.dart:2978)
[00094.824] 18313.18355> #146    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:1866)
[00094.824] 18313.18355> #147    BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.beginFrame (package:flutter/src/widgets/binding.dart:353)
[00094.824] 18313.18355> #148    BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:170)
[00094.824] 18313.18355> #149    BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:645)
[00094.824] 18313.18355> #150    BindingBase&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:580)
[00094.824] 18313.18355> #151    _beginFrame (file:///Users/freiling/workspace/fuchsia/flutter/lib/ui/hooks.dart:83)
[00094.827] 18313.18355> 
```

**Comment by Hixie** [comment]
You won't get it at all in release builds. It's just a debug mode message.
Sometimes the problem is that the filename is wrong, and you need the stack to figure out where it's being generated.

**Comment by oliverjanik** [comment]
This is my gripe with flutter as well. Instead of producing clear error messages it just explodes with stacktraces hundreds of lines of code. Makes debugging experience poor.

Can we perhaps have a flag to just hide or skip over frames that are internal to Flutter? Or maybe just anything related to rendering? The amount of updateChild and inflateChild is useless.  It obscures the real issue.

**Comment by Hixie** [comment]
Unfortunately sometimes the updateChild and inflateChild calls are important...

The framework already removes some frames (e.g. private frames in dart:async). But we do need to do more.
