### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument(s): Cannot find executable for /Users/freashadams/Documents/flutter/bin/cache/artifacts/engine/android-arm-release/darwin-x64/gen_snapshot.

### ISSUE THREAD

**Issue by franklobsty25** [flutter/flutter#93315]
## Command
```
flutter --quiet assemble --depfile /Users/freashadams/Desktop/Flutter_Tutorials/great_places/build/app/intermediates/flutter/release/flutter_build.d --output /Users/freashadams/Desktop/Flutter_Tutorials/great_places/build/app/intermediates/flutter/release -dTargetFile=lib/main.dart -dTargetPlatform=android -dBuildMode=release -dTrackWidgetCreation=true android_aot_bundle_release_android-arm android_aot_bundle_release_android-arm64 android_aot_bundle_release_android-x64
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for /Users/freashadams/Documents/flutter/bin/cache/artifacts/engine/android-arm-release/darwin-x64/gen_snapshot.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:124:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:40:30)
#2      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:638:33)
#3      _run (package:flutter_tools/src/base/error_handling_io.dart:532:20)
#4      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:638:12)
#5      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:472:28)
#6      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:491:35)
#7      GenSnapshot.run (package:flutter_tools/src/base/build.dart:73:26)
#8      AOTSnapshotter.build (package:flutter_tools/src/base/build.dart:194:56)
#9      AndroidAot.build (package:flutter_tools/src/build_system/targets/android.dart:232:52)
#10     _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:796:27)
<asynchronous suspension>
#11     Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#12     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:734:32)
<asynchronous suspension>
#13     Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#14     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:734:32)
<asynchronous suspension>
#15     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:563:16)
<asynchronous suspension>
#16     AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:220:32)
<asynchronous suspension>
#17     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
```
```
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.5 20G71 darwin-x64, locale en-GH)
    • Flutter version 2.0.3 at /Users/freashadams/Documents/flutter
    • Framework revision 4d7946a68d (8 months ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/freashadams/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 95.0.4638.69

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 4d7946a68d26794349189cf21b3f68cc6fe61dcb
### Plugins
flutter_plugin_android_lifecycle-2.0.3
google_maps_flutter-2.0.8
image_picker-0.8.4
image_picker_for_web-2.1.3
location-4.3.0
location_web-3.1.1
path_provider-2.0.3
path_provider_linux-2.0.2
path_provider_macos-2.0.2
path_provider_windows-2.0.3
sqflite-2.0.0+4

**Comment by danagbemava-nc** [comment]
Hi @muhammadrizwaan 
This issue was fixed as part of https://github.com/flutter/flutter/issues/68475.
I recommend you to upgrade to the latest stable (2.5.3) or the latest master and try again to see it work properly.

Closing as this is already fixed. If after upgrading to the latest versions, you still see the issue, write in comments and I'll reopen.
