### ISSUE TITLE
exception from flutter_tools while reloading

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#9334]
After a reload followed quickly by a restart, I saw:

```
Unhandled exception:
Bad state: Future already completed
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:39)
#1      FlutterView.runFromSource.<anonymous closure> (package:flutter_tools/src/vmservice.dart:1064)
#2      _rootRunUnary (dart:async/zone.dart:1132)
#3      _CustomZone.runUnary (dart:async/zone.dart:1012)
#4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#6      _DelayedData.perform (dart:async/stream_impl.dart:578)
#7      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:694)
#8      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:654)
#9      _rootRun (dart:async/zone.dart:1120)
#10     _CustomZone.run (dart:async/zone.dart:1001)
#11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:928)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)
../../runtime/vm/dart_api_impl.cc: 1871: error: Dart_GetMainPortId expects there to be a current isolate. Did you forget to call Dart_CreateIsolate or Dart_EnterIsolate?
/Users/devoncarew/projects/flutter/flutter/bin/flutter: line 91: 21807 Abort trap: 6           "$DART" $FLUTTER_TOOL_ARGS "$SNAPSHOT_PATH" "$@"
```

**Comment by eseidelGoogle** [comment]
I'm going to assume this is non-urgent for now.  FYI @johnmccutchan
