### ISSUE TITLE
FormatException: FormatException: Unterminated string (at character 32)

### ISSUE THREAD

**Issue by congfandi** [flutter/flutter#93385]
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter --no-color run --machine --track-widget-creation --device-id=B71AB40C-A83B-4FD1-BBA0-1115E04E18B9 --start-paused --dart-define=flutter.inspector.structuredErrors=true --devtools-server-address=http://127.0.0.1:9100 lib/main.dart

## exception

```
FormatException: FormatException: Unterminated string (at character 32)
"flutter:       \"content\": \"
                               ^
```

```
#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1405:5)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:516:9)
#2      _parseJson (dart:convert-patch/convert_patch.dart:41:10)
#3      JsonDecoder.convert (dart:convert/json.dart:506:36)
#4      JsonCodec.decode (dart:convert/json.dart:157:41)
#5      jsonDecode (dart:convert/json.dart:96:10)
#6      _rootRunUnary (dart:async/zone.dart:1436:47)
#7      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#10     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#11     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#12     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#13     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#14     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:151:13)
#15     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:126:5)
#16     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#17     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#18     _rootRunUnary (dart:async/zone.dart:1436:47)
#19     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#21     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#22     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#23     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#24     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#25     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#26     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#27     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:317:20)
#28     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)
#29     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#30     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#31     _rootRunUnary (dart:async/zone.dart:1436:47)
#32     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#33     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#34     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#35     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#36     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#37     _StreamController._add (dart:async/stream_controller.dart:607:7)
#38     _StreamController.add (dart:async/stream_controller.dart:554:5)
#39     _Socket._onData (dart:io-patch/socket_patch.dart:2166:41)
#40     _rootRunUnary (dart:async/zone.dart:1444:13)
#41     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#42     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#43     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#44     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#45     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#46     _StreamController._add (dart:async/stream_controller.dart:607:7)
#47     _StreamController.add (dart:async/stream_controller.dart:554:5)
#48     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1702:33)
#49     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1213:14)
#50     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#51     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#52     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
#53     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.5.2 20G95 darwin-x64, locale en-ID)
    • Flutter version 2.5.3 at /Users/congfandi/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (4 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/congfandi/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/congfandi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (2 available)
    • iPhone 8 (mobile) • B71AB40C-A83B-4FD1-BBA0-1115E04E18B9 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • Chrome (web)      • chrome                               • web-javascript • Google Chrome 95.0.4638.69

• No issues found!
```

**Comment by maheshmnj** [comment]
Hi @congfandi, Thanks for filing the issue. Can you please provide the steps to reproduce the issue?
Also can you please confirm if your json is valid by entering your json data https://jsonlint.com/?

Thanks

**Comment by congfandi** [comment]
its really weird issue. in my doc, i got this json 

```json
{
    "diagnostic": {
        "message": "Success",
        "statusCode": 200,
        "timesTamp": "2021-11-10 12:44:24"
    },
    "result": [
        {
            "id": 2,
            "title": "Järn",
            "description": null,
            "published_at": "2021-11-04T02:57:09.000Z",
            "created_at": "2021-11-04T02:57:08.000Z",
            "updated_at": "2021-11-04T02:57:09.000Z",
            "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dui purus sagittis cras ipsum. Morbi donec vehicula amet, nulla sit diam condimentum erat ut. Sollicitudin sed odio arcu purus. Aliquam senectus faucibus enim ullamcorper velit enim vitae gravida molestie.  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dui purus sagittis cras ipsum. Morbi donec vehicula amet, nulla sit diam condimentum erat ut. Sollicitudin sed odio arcu purus. Aliquam senectus faucibus enim ullamcorper velit enim vitae gravida molestie."
        },
        {
            "id": 3,
            "title": "Gluten",
            "description": null,
            "published_at": "2021-11-04T02:57:31.000Z",
            "created_at": "2021-11-04T02:57:29.000Z",
            "updated_at": "2021-11-04T02:57:31.000Z",
            "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dui purus sagittis cras ipsum. Morbi donec vehicula amet, nulla sit diam condimentum erat ut. Sollicitudin sed odio arcu purus. Aliquam senectus faucibus enim ullamcorper velit enim vitae gravida molestie.  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dui purus sagittis cras ipsum. Morbi donec vehicula amet, nulla sit diam condimentum erat ut. Sollicitudin sed odio arcu purus. Aliquam senectus faucibus enim ullamcorper velit enim vitae gravida molestie."
        },
        {
            "id": 4,
            "title": "Allergier",
            "description": null,
            "published_at": "2021-11-04T02:57:49.000Z",
            "created_at": "2021-11-04T02:57:47.000Z",
            "updated_at": "2021-11-04T02:57:49.000Z",
            "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dui purus sagittis cras ipsum. Morbi donec vehicula amet, nulla sit diam condimentum erat ut. Sollicitudin sed odio arcu purus. Aliquam senectus faucibus enim ullamcorper velit enim vitae gravida molestie.  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dui purus sagittis cras ipsum. Morbi donec vehicula amet, nulla sit diam condimentum erat ut. Sollicitudin sed odio arcu purus. Aliquam senectus faucibus enim ullamcorper velit enim vitae gravida molestie."
        }
    ]
}
```

**Comment by congfandi** [comment]
Hi @maheshmnj i close this issues because after i check every single line, its not flutter issue this issue its because i use wrog parameter to the endpoint. Thank you.
