### ISSUE TITLE
Platform view hasn’t been initialized from the platform view channel.

### ISSUE THREAD

**Issue by Tom3652** [flutter/flutter#93388]
**Expected results:** 

The app is crashing.

**Actual results:** 

The app should not crash. 

This only happened twice and in ```debug``` mode.   
I am sorry i can't reproduce this as i don't know what the cause is and doesn't seem to be related to my code.

Please feel free to correct me if you have more information from the logs.

<details>
  <summary>Logs</summary>

```
E/flutter (23542): [ERROR:flutter/fml/platform/android/jni_util.cc(182)] java.lang.IllegalStateException: Platform view hasn’t been initialized from the platform view channel.
E/flutter (23542): 	at io.flutter.plugin.platform.PlatformViewsController.initializePlatformViewIfNeeded(PlatformViewsController.java:733)
E/flutter (23542): 	at io.flutter.plugin.platform.PlatformViewsController.onDisplayPlatformView(PlatformViewsController.java:792)
E/flutter (23542): 	at io.flutter.embedding.engine.FlutterJNI.onDisplayPlatformView(FlutterJNI.java:1245)
E/flutter (23542): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (23542): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/flutter (23542): 	at android.os.Looper.loop(Looper.java:184)
E/flutter (23542): 	at android.app.ActivityThread.main(ActivityThread.java:7864)
E/flutter (23542): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (23542): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:512)
E/flutter (23542): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:998)
E/flutter (23542):
F/flutter (23542): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1384)] Check failed: fml::jni::CheckException(env).
F/libc    (23542): Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 23542 (myapp.android), pid 23542 (myapp.android)
Process name is com.myapp.android, not key_process
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: ‘OPPO/CPH1931EEA/OP4B79L1:10/QKQ1.200209.002/2021090000:user/release-keys’
Revision: ‘0’
ABI: ‘arm64’
Timestamp: 2021-11-06 12:57:30+0100
pid: 23542, tid: 23542, name: myapp.android  >>> com.myapp.android <<<
uid: 10505
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: ‘[FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1384)] Check failed: fml::jni::CheckException(env).
’
    x0  0000000000000000  x1  0000000000005bf6  x2  0000000000000006  x3  0000007fdab97b90
    x4  0000000000000000  x5  0000000000000000  x6  0000000000000000  x7  8000000000000000
    x8  00000000000000f0  x9  f4ef672cfa6cf48b  x10 0000000000000001  x11 0000000000000000
    x12 fffffff0fffffbdf  x13 0000000000000003  x14 0000000000000001  x15 0000000000000010
    x16 00000077f29f0740  x17 00000077f29ce6d0  x18 00000077f52ba000  x19 0000000000005bf6
    x20 0000000000005bf6  x21 00000000ffffffff  x22 000000776fccfe00  x23 00000076b77f18b8
    x24 00000000000002d0  x25 00000000000005b0  x26 0000000000000000  x27 0000007fdab97e98
    x28 0000000000000085  x29 0000007fdab97c30
    sp  0000007fdab97b70  lr  00000077f297e484  pc  00000077f297e4b0
backtrace:
      #00 pc 00000000000744b0  /apex/com.android.runtime/lib64/bionic/libc.so (abort+160) (BuildId: ccae2a11ae566ea10c37d2e226f845f4)
      #01 pc 000000000145a29c  /data/app/com.myapp.android-9rxiPXs1EqOZlTe6r9Btgw==/base.apk!libflutter.so (offset 0xae49000) (BuildId: 0e38af2b797f8f0407f485c629490ad99b418f86)
```

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-x64, locale fr-FR)
    • Flutter version 2.5.3 at /Users/foxtom/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (4 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/foxtom/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.0)
    • VS Code at /Users/foxtom/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (3 available)
    • CPH1931 (mobile) • ee9b32b5 • android-arm64  • Android 10 (API 29)
    • macOS (desktop)  • macos    • darwin-x64     • macOS 12.0.1 21A559 darwin-x64
    • Chrome (web)     • chrome   • web-javascript • Google Chrome 95.0.4638.69

• No issues found!
```

</details>

**Comment by stuartmorgan** [comment]
What plugin were you trying to show when this crash happened?

**Comment by Tom3652** [comment]
It's actually very hard to tell.  
A member of my team sent me this issue that he got few days back...

If i had to guess according to my app, it's more likely to be linked to the ```camera``` as it is opened at runtime in our app.

**Comment by Tom3652** [comment]
Alright then, i will provide more details next time this happens, if this happens. 
Thanks for your time
