### ISSUE TITLE
Exception: CocoaPods not installed or not in valid state.

### ISSUE THREAD

**Issue by mortifactor** [flutter/flutter#93475]
## Steps to Reproduce

Hello. I'm trying to start debugging IOS app from VS Code (with F5) with SSH-Remote extension (i'm connecting with my vs code from windows to remote mac os). But it's failing on command "which pod".
My launch.json:
```
        {
            "name": "Flutter_debug",
            "request": "launch",
            "type": "dart",
            "program": "lib/main_dev.dart",
            "console": "terminal",
            "args": [
                "--flavor",
                "xxx",
                "--dart-define",
                "DEFINE_FLUTTER_FLAVOR=xxx",
                "--verbose"
            ]
        },
```

In the same time when I run similar debug command from terminal (also from vs code remote) then it's ok.
Command:
```
flutter run -t lib/main_dev.dart --flavor xxx --dart-define DEFINE_FLUTTER_FLAVOR=xxx
```

"which pod" result from terminal:
```
dev@Mac-mini / % which pod 
/usr/local/bin/pod
```

So in summary:
In VS Code connecting with SSH to remote macos.
running debug with F5 - fail
running same command from terminal (remote ssh session as far as I understand) - success

## Logs

<details>
<summary>Logs</summary>

last strings from "DEBUG CONSOLE" tab in vs code on F5:

```
[  +14 ms] executing: which pod
[   +6 ms] Warning: CocoaPods not installed. Skipping pod install.
             CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
             Without CocoaPods, plugins will not work on iOS or macOS.
             For more info, see https://flutter.dev/platform-plugins
           To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[+3378 ms] Exception: CocoaPods not installed or not in valid state.
Exited (sigterm)
[   +6 ms]
#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:571:9)
           <asynchronous suspension>
#2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
           <asynchronous suspension>
#3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
#4      CommandRunner.runCommand
           <asynchronous suspension>
#5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
#7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
#8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
#10     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>
```

```
flutter doctor -v
[✓] Flutter (Channel stable, 2.5.3, on Mac OS X 10.15.7 19H1323 darwin-x64, locale en-RU)
    • Flutter version 2.5.3 at /Users/dev/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (4 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dev/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.62.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (3 available)
    • iPhone (Developer) (mobile) • 0e9f985eae570203d6775ed2798716f81399393e • ios            • iOS 14.5.1 18E212
    • macOS (desktop)             • macos                                    • darwin-x64     • Mac OS X 10.15.7 19H1323 darwin-x64
    • Chrome (web)                • chrome                                   • web-javascript • Google Chrome 95.0.4638.69
    ! Error: iPhone (Developer) is busy: Making iPhone (Developer) ready for development. Xcode will continue when iPhone (Developer) is finished. (code -10)

! Doctor found issues in 1 category.
```

</details>

**Comment by mortifactor** [comment]
Wierd. Reviewed my .zshrc file. Removed unused lines and it worked. Sorry, closing.
