### ISSUE TITLE
 Unable to run flutter build ipa  Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by gmediard** [flutter/flutter#93494]
Greetings,

If possible, and hoping I'm in the right space to mount it. I want to show you my "flutter build ipa --verbose", hoping you can provide me with a possible help or solution.

Very grateful for any help you can provide. Thank you.

Log File:
[output.txt](https://github.com/flutter/flutter/files/7521831/output.txt)

Moved to: 
_Originally posted by @gmediard in https://github.com/flutter/flutter/issues/91142#issuecomment-966447122_

**Comment by darshankawar** [comment]
@gmediard 
From your log, it's failing due to below errors:

```
`../../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_math_fork-0.3.3+1/lib/src/widgets/selectable.dart:407:7: Error: The non-abstract class 'InternalSelectableMathState' is missing implementations for these members:
               [   +8 ms]  - TextSelectionDelegate.copySelection
               [        ]  - TextSelectionDelegate.cutSelection
               [        ]  - TextSelectionDelegate.pasteText
               [        ]  - TextSelectionDelegate.selectAll
               [        ] Try to either
               [        ]  - provide an implementation,
               [        ]  - inherit an implementation from a superclass or mixin,
               [        ]  - mark the class as abstract, or
               [        ]  - provide a 'noSuchMethod' implementation.
               [        ] class InternalSelectableMathState extends State<InternalSelectableMath>
               [        ]       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
               [        ] ../../../flutter/packages/flutter/lib/src/services/text_input.dart:1034:8: Context: 'TextSelectionDelegate.copySelection' is defined here.
               [        ]   void copySelection(SelectionChangedCause cause);
               [        ]        ^^^^^^^^^^^^^
               [        ] ../../../flutter/packages/flutter/lib/src/services/text_input.dart:1014:8: Context: 'TextSelectionDelegate.cutSelection' is defined here.
               [        ]   void cutSelection(SelectionChangedCause cause);
               [        ]        ^^^^^^^^^^^^
               [        ] ../../../flutter/packages/flutter/lib/src/services/text_input.dart:1022:16: Context: 'TextSelectionDelegate.pasteText' is defined here.
               [        ]   Future<void> pasteText(SelectionChangedCause cause);
               [        ]                ^^^^^^^^^
               [        ] ../../../flutter/packages/flutter/lib/src/services/text_input.dart:1028:8: Context: 'TextSelectionDelegate.selectAll' is defined here.
               [        ]   void selectAll(SelectionChangedCause cause);
               [        ]        ^^^^^^^^^
               [+5597 ms] ../../../flutter/.pub-cache/hosted/pub.dartlang.org/photo_view-0.11.1/lib/src/core/photo_view_gesture_detector.dart:106:29: Error: The argument type 'PointerEvent' can't be assigned to the parameter type 'PointerDownEvent'.
               [        ]  - 'PointerEvent' is from 'package:flutter/src/gestures/events.dart' ('../../../flutter/packages/flutter/lib/src/gestures/events.dart').
               [        ]  - 'PointerDownEvent' is from 'package:flutter/src/gestures/events.dart' ('../../../flutter/packages/flutter/lib/src/gestures/events.dart').
               [        ]     super.addAllowedPointer(event);
               [        ]                             ^
               [   +5 ms] Target kernel_snapshot failed: Exception
                          #0      KernelSnapshot.build (package:flutter_tools/src/build_system/targets/common.dart:241:7)
                          <asynchronous suspension>
                          #1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:839:9)
                          <asynchronous suspension>
                          #2      Future.wait.<anonymous closure> (dart:async/future.dart)
                          <asynchronous suspension>
                          #3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:777:32)
                          <asynchronous suspension>
                          #4      Future.wait.<anonymous closure> (dart:async/future.dart)
                          <asynchronous suspension>
                          #5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:777:32)
                          <asynchronous suspension>
                          #6      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:606:16)
                          <asynchronous suspension>
                          #7      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:317:32)
                          <asynchronous suspension>
                          #8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1150:27)
                          <asynchronous suspension>
                          #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                          <asynchronous suspension>
                          #10     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
                          <asynchronous suspension>
                          #11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
                          <asynchronous suspension>
                          #12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                          <asynchronous suspension>
                          #13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
                          <asynchronous suspension>
                          #14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
                          <asynchronous suspension>
                          #15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                          <asynchronous suspension>
                          #16     main (package:flutter_tools/executable.dart:93:3)
                          <asynchronous suspension>

               [   +5 ms] 
                          #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
                          #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:334:7)
                          <asynchronous suspension>
                          #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1150:27)
                          <asynchronous suspension>
                          #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                          <asynchronous suspension>
                          #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
                          <asynchronous suspension>
                          #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
                          <asynchronous suspension>
                          #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                          <asynchronous suspension>
                          #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
                          <asynchronous suspension>
                          #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
                          <asynchronous suspension>
                          #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                          <asynchronous suspension>
                          #10     main (package:flutter_tools/executable.dart:93:3)
                          <asynchronous suspension>
               Failed to package /Users/jorgemartinez/Documents/app/cirilla.
               Command PhaseScriptExecution failed with a nonzero exit code`
```

pointing to a 3rd party plugin `flutter_math_fork` and probably conflicting with framework's updates. You'll need to upgrade that plugin to latest and try again to see if it works.

**Comment by gmediard** [comment]
Greetings!

Thank you, I did indeed have a number of 3rd Party bugs that were fixed once they were updated. 

Thank you very much!

**Comment by darshankawar** [comment]
Closing this as resolved based on above comment.

**Comment by eliasjtg** [comment]
@darshankawar I have the same issue but in android

I don't using `flutter_math_fork`

```
[+12401 ms] [+12388 ms] Persisting file store
[        ] [  +14 ms] Done persisting file store
[        ] [  +19 ms] "flutter assemble" took 27,308ms.
[   +2 ms] [  +17 ms] Target debug_android_application failed: FileSystemException: Creation failed, path = '/Users/imac/development/projects/boraevolta-flutter/android/app/build/intermediates/flutter/debug/flutter_assets/android/app/build/intermediates/merged_assets/debug/out/flutter_assets/android/app/build/intermediates/flutter/debug/flutter_assets/android/app/build/intermediates/merged_assets/debug/out/flutter_assets/android/app/build/intermediates/merged_assets/debug/out/flutter_assets/android/app/build/intermediates/merged_assets/debug/out/flutter_assets/android/app/build/intermediates/merged_assets/debug/out/flutter_assets/android/app/build/intermediates/merged_assets/debug/out/flutter_assets/android/app/build/intermediates/merged_assets/debug/out/flutter_assets/android/app/build/intermediates/merged_assets/debug/out/flutter_assets/android/app/build/intermediates/merged_assets/debug/out/flutter_assets/android/app/build/intermediates/merged_assets/debug/out/flutter_assets/android/app/build/intermediates/merged_assets/debug/out/flutter_assets/android/app/build/intermediates/merged_assets/debug/out/flutter_assets' (OS Error: File name too long, errno = 63)
[   +1 ms]            #0      _Directory.createSync (dart:io/directory_impl.dart:133:7)
[        ]            #1      ForwardingDirectory.createSync (package:file/src/forwarding/forwarding_directory.dart:20:16)
[        ]            #2      ErrorHandlingDirectory.createSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:433:22)
[        ]            #3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:597:14)
[        ]            #4      ErrorHandlingDirectory.createSync (package:flutter_tools/src/base/error_handling_io.dart:432:12)
[        ]            #5      copyAssets.<anonymous closure> (package:flutter_tools/src/build_system/targets/assets.dart:99:21)
[        ]            <asynchronous suspension>
[        ]            #6      Future.wait.<anonymous closure> (dart:async/future.dart)
[        ]            <asynchronous suspension>
[        ]            #7      copyAssets (package:flutter_tools/src/build_system/targets/assets.dart:87:3)
[        ]            <asynchronous suspension>
[        ]            #8      AndroidAssetBundle.build (package:flutter_tools/src/build_system/targets/android.dart:65:34)
[        ]            <asynchronous suspension>
[        ]            #9      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:836:9)
[        ]            <asynchronous suspension>
[        ]            #10     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:603:16)
[        ]            <asynchronous suspension>
[        ]            #11     AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:314:32)
[        ]            <asynchronous suspension>
[        ]            #12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
[        ]            <asynchronous suspension>
[        ]            #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #14     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
[        ]            <asynchronous suspension>
[        ]            #15     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
[        ]            <asynchronous suspension>
[        ]            #16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #17     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
[        ]            <asynchronous suspension>
[        ]            #18     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
[        ]            <asynchronous suspension>
[        ]            #19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #20     main (package:flutter_tools/executable.dart:92:3)
[        ]            <asynchronous suspension>
[        ] [   +7 ms] 
[        ]            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
[        ]            #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:331:7)
[        ]            <asynchronous suspension>
[        ]            #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
[        ]            <asynchronous suspension>
[        ]            #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
[        ]            <asynchronous suspension>
[        ]            #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
[        ]            <asynchronous suspension>
[        ]            #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
[        ]            <asynchronous suspension>
[        ]            #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
[        ]            <asynchronous suspension>
[        ]            #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #10     main (package:flutter_tools/executable.dart:92:3)
[        ]            <asynchronous suspension>
[ +287 ms] [ +261 ms] ensureAnalyticsSent: 260ms
[        ] [   +3 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 1
[+6101 ms] > Task :app:compileFlutterBuildDebug FAILED
[ +110 ms] FAILURE: Build failed with an exception.
[        ] * Where:
[        ] Script '/Users/imac/development/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1005
[        ] * What went wrong:
[  +87 ms] Execution failed for task ':app:compileFlutterBuildDebug'.
[        ] > Process 'command '/Users/imac/development/flutter/bin/flutter'' finished with non-zero exit value 1
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 42s
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
[        ] 26 actionable tasks: 2 executed, 24 up-to-date
[{"event":"app.progress","params":{"appId":"ec178082-86d1-4d98-889a-fdc290166595","id":"0","progressId":null,"finished":true}}]
[+4360 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +4 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:571:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>
```
