### ISSUE TITLE
[tool_crash] ProcessException: Process exited abnormally:Command line invocation:    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -listxcodebuild: error: Unable to read project 'Runner.xcodeproj'.	Reason: Project /Users/mingchunhu/Documents/ws/learning/flutter-demo/flutter_app/gallery/example/ios/Runner.xcodeproj cannot be opened because it is missing its project.pbxproj file. Command: xcrun, OS error code: 74

### ISSUE THREAD

**Issue by 337240552** [flutter/flutter#93545]
## Command
```
flutter create .
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Process exited abnormally:
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -list

xcodebuild: error: Unable to read project 'Runner.xcodeproj'.
	Reason: Project /Users/mingchunhu/Documents/ws/learning/flutter-demo/flutter_app/gallery/example/ios/Runner.xcodeproj cannot be opened because it is missing its project.pbxproj file. Command: xcrun, OS error code: 74
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:124:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:276:19)
<asynchronous suspension>
#2      XcodeProjectInterpreter.getInfo (package:flutter_tools/src/ios/xcodeproj.dart:470:30)
<asynchronous suspension>
#3      IosProject.projectInfo (package:flutter_tools/src/project.dart:619:29)
<asynchronous suspension>
#4      IosProject.buildSettingsForBuildInfo (package:flutter_tools/src/project.dart:601:35)
<asynchronous suspension>
#5      IosProject._parseProductBundleIdentifier (package:flutter_tools/src/project.dart:543:50)
<asynchronous suspension>
#6      IosProject.productBundleIdentifier (package:flutter_tools/src/project.dart:520:41)
<asynchronous suspension>
#7      FlutterProject.organizationNames (package:flutter_tools/src/project.dart:135:9)
<asynchronous suspension>
#8      CreateBase.getOrganization (package:flutter_tools/src/commands/create_base.dart:236:49)
<asynchronous suspension>
#9      CreateCommand.runCommand (package:flutter_tools/src/commands/crea

**Comment by darshankawar** [comment]
@337240552 
What flutter version are you on ?
This is already fixed and merged, https://github.com/flutter/flutter/issues/63280.
You can upgrade to latest stable or master to see the fix.
Closing for now as this is already fixed. If on latest versions, you still see this error, write in comments and I'll reopen it.
Thanks.
