### ISSUE TITLE
Crash InputAwareWebView.java line 42 on Android 10

### ISSUE THREAD

**Issue by radomir9720** [flutter/flutter#93641]
I used `webview_flutter: ^2.0.9`. In that version i was getting `InputAwareWebView.java line 26` crashes on android 10, production:

```
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'android.view.WindowManager$LayoutParams android.view.ViewRootImpl.mWindowAttributes' on a null object reference
       at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1662)
       at android.view.inputmethod.InputMethodManager.checkFocus(InputMethodManager.java:1901)
       at android.view.inputmethod.InputMethodManager.isActive(InputMethodManager.java:1220)
       at io.flutter.plugins.webviewflutter.InputAwareWebView$1.run(InputAwareWebView.java:26)
       at android.os.Handler.handleCallback(Handler.java:888)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:213)
       at android.app.ActivityThread.main(ActivityThread.java:8178)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
```

Then i saw that #78405 was closed, i updated plugin version to `^2.3.1` and i thought that crash should gone, and indeed it was gone, but instead appeared the following one `InputAwareWebView.java line 42`:

```
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'android.view.WindowManager$LayoutParams android.view.ViewRootImpl.mWindowAttributes' on a null object reference
       at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1662)
       at android.view.inputmethod.InputMethodManager.checkFocus(InputMethodManager.java:1901)
       at android.view.inputmethod.InputMethodManager.isActive(InputMethodManager.java:1220)
       at io.flutter.plugins.webviewflutter.InputAwareWebView$1.run(InputAwareWebView.java:42)
       at android.os.Handler.handleCallback(Handler.java:888)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:213)
       at android.app.ActivityThread.main(ActivityThread.java:8178)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
```

Details are completely the same: only android 10, production.

**Comment by mamuseferha** [comment]
Hi @radomir9720 
Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by radomir9720** [comment]
Hi @mamuseferha.

In the comments of #78405 already was said that locally no one was able to reproduce this crash, including me, so, i think, there is no reason to provide "reproducible code sample".

I can only tell the way how i use webview: i have a `Scaffold` with `TabBar` and `TabBarView`. In `TabBarView` i have 3 `WebView`'s, that i keep alive with `AutomaticKeepAliveClientMixin`.

Flutter doctor:
```dart
[✓] Flutter (Channel stable, 2.5.3, on Mac OS X 10.15.7 19H2 darwin-x64, locale ru-RU)
    • Flutter version 2.5.3 at /Users/radomir/development/flutter/2.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (4 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/radomir/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.62.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0
```

**Comment by hiennv92** [comment]
I use this package: https://github.com/shah-xad/flutter_tex which using webview_flutter_plus
and I have the same crash like this. Only on Android 10. 
I have to add `try/catch` to the code on line 195 file InputAwareWebView.java to prevent crash temporarily:
```
            try {
              imm.isActive(containerView);
            } catch (Exception e) {}
```

**Comment by blasten** [comment]
`InputAwareWebView` should be removed from the webview plugin
