### ISSUE TITLE
Failing camera tests on Android

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#93686]
Result: https://firebase.corp.google.com/u/0/project/flutter-cirrus/testlab/histories/bh.a4615392b31c422b/matrices/6218121754841754569/executions/bs.5e94df04f68376bb/test-cases

The following tests are failing:

1. Capture specific image resolutions

Logs: 
```
The following CameraException was thrown running a test:
CameraException(error, Attempt to invoke virtual method 'int
android.hardware.camera2.CameraCaptureSession.capture(android.hardware.camera2.CaptureRequest,
android.hardware.camera2.CameraCaptureSession$CaptureCallback,
android.os.Handler)' on a null object reference)
When the exception was thrown, this was the stack:
#0 CameraController.takePicture (package:camera/src/camera_controller.dart:392:7)
<asynchronous suspension>
#1 main.testCaptureImageResolution (file:///tmp/cirrus-ci-build/packages/camera/camera/example/integration_test/camera_test.dart:62:18)
<asynchronous suspension>
#2 main.<anonymous closure> (file:///tmp/cirrus-ci-build/packages/camera/camera/example/integration_test/camera_test.dart:88:13)
<asynchronous suspension>
#3 testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:176:15)
<asynchronous suspension>
#4 TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:817:5)
```
2. Capture specific video resolutions
Logs:

```
java.lang.Exception: ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following CameraException was thrown running a test:
CameraException(error, stop failed.)
When the exception was thrown, this was the stack:
#0 CameraController.stopVideoRecording (package:camera/src/camera_controller.dart:531:7)
<asynchronous suspension>
#1 main.testCaptureVideoResolution (file:///tmp/cirrus-ci-build/packages/camera/camera/example/integration_test/camera_test.dart:109:18)
<asynchronous suspension>
#2 main.<anonymous closure> (file:///tmp/cirrus-ci-build/packages/camera/camera/example/integration_test/camera_test.dart:139:13)
<asynchronous suspension>
#3 testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:176:15)
<asynchronous suspension>
#4 TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:817:5)
<asynchronous suspension>
The test description was:
Capture specific video resolutions
═════════════════════════════════════════════════════════════════
at dev.flutter.plugins.integration_test.FlutterTestRunner.run(FlutterTestRunner.java:81)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:392)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2205)
```

cc @camsim99, @stuartmorgan

**Comment by gmackall** [comment]
We believe these tests are all currently succeeding on physical devices. Closing as fixed.

**Comment by stuartmorgan** [comment]
The tests are being skipped:
https://github.com/flutter/packages/blob/d7dc0a00db2e198579150b9cc9540407d4b8bd89/packages/camera/camera_android/example/integration_test/camera_test.dart#L97-L98
https://github.com/flutter/packages/blob/d7dc0a00db2e198579150b9cc9540407d4b8bd89/packages/camera/camera/example/integration_test/camera_test.dart#L95-L96
https://github.com/flutter/packages/blob/d7dc0a00db2e198579150b9cc9540407d4b8bd89/packages/camera/camera_android/example/integration_test/camera_test.dart#L151-L152
https://github.com/flutter/packages/blob/d7dc0a00db2e198579150b9cc9540407d4b8bd89/packages/camera/camera/example/integration_test/camera_test.dart#L148-L149


If they pass, they should be re-enabled before this is closed.

**Comment by gmackall** [comment]
> The tests are being skipped: https://github.com/flutter/packages/blob/d7dc0a00db2e198579150b9cc9540407d4b8bd89/packages/camera/camera_android/example/integration_test/camera_test.dart#L97-L98 https://github.com/flutter/packages/blob/d7dc0a00db2e198579150b9cc9540407d4b8bd89/packages/camera/camera/example/integration_test/camera_test.dart#L95-L96 https://github.com/flutter/packages/blob/d7dc0a00db2e198579150b9cc9540407d4b8bd89/packages/camera/camera_android/example/integration_test/camera_test.dart#L151-L152 https://github.com/flutter/packages/blob/d7dc0a00db2e198579150b9cc9540407d4b8bd89/packages/camera/camera/example/integration_test/camera_test.dart#L148-L149
> 
> If they pass, they should be re-enabled before this is closed.

Ah I see, sorry we missed that in the meeting. Thanks!

**Comment by reidbaker** [comment]
@camsim99 can you try to run these tests? I doubt that tests that have been disabled for 2 years are passing. Also the pattern of skipping tests such that they look like they pass is dangerous and this bug shows why.

**Comment by stuartmorgan** [comment]
> Also the pattern of skipping tests such that they look like they pass is dangerous

Where do they look like they pass? I don't see them in the FTL console of tests run at all. (Or do you mean the fact that they don't show up there explicitly as skipped tests? If so, that may be a bug in our `espresso` plugin.)

**Comment by camsim99** [comment]
Ran these locally and saw that the `camera` and `camera_android` `Capture specific image resolutions` tests pass (those related to https://github.com/flutter/packages/blob/d7dc0a00db2e198579150b9cc9540407d4b8bd89/packages/camera/camera_android/example/integration_test/camera_test.dart#L97-L98 and https://github.com/flutter/packages/blob/d7dc0a00db2e198579150b9cc9540407d4b8bd89/packages/camera/camera/example/integration_test/camera_test.dart#L95-L96), so drafted a PR to re-enable them.

The others are the `Capture specific video resolutions` tests, which still fail with the following errors:
**`camera/camera_android`**
```
01:42 +1: Capture specific video resolutions                                                                                
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following PlatformException was thrown running a test:
PlatformException(error, stop failed., null, java.lang.RuntimeException: stop failed.
	at android.media.MediaRecorder.stop(Native Method)
	at io.flutter.plugins.camera.Camera.stopVideoRecording(Camera.java:799)
	at io.flutter.plugins.camera.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:129)
	at
io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
	at
io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
)

When the exception was thrown, this was the stack:
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
<asynchronous suspension>
#2      AndroidCamera.stopVideoRecording (package:camera_android/src/android_camera.dart:275:26)
<asynchronous suspension>
#3      CameraController.stopVideoRecording (package:camera_example/camera_controller.dart:350:9)
<asynchronous suspension>
#4      main.testCaptureVideoResolution (file:///Users/camillesimon/packages/packages/camera/camera_android/example/integration_test/camera_test.dart:111:24)
<asynchronous suspension>
#5      main.<anonymous closure> (file:///Users/camillesimon/packages/packages/camera/camera_android/example/integration_test/camera_test.dart:143:15)
<asynchronous suspension>
#6      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:168:15)
<asynchronous suspension>
#7      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1017:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

The test description was:
  Capture specific video resolutions
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**`camera/camera`**
```
02:48 +1: Capture specific video resolutions                                                                                
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following CameraException was thrown running a test:
CameraException(error, stop failed.)

When the exception was thrown, this was the stack:
#0      CameraController.stopVideoRecording (package:camera/src/camera_controller.dart:579:7)
<asynchronous suspension>
#1      main.testCaptureVideoResolution (file:///Users/camillesimon/packages/packages/camera/camera/example/integration_test/camera_test.dart:109:24)
<asynchronous suspension>
#2      main.<anonymous closure> (file:///Users/camillesimon/packages/packages/camera/camera/example/integration_test/camera_test.dart:140:15)
<asynchronous suspension>
#3      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:168:15)
<asynchronous suspension>
#4      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1017:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

The test description was:
  Capture specific video resolutions
════════════════════════════════════════════════════════════════════════════════════════════════════
02:48 +1 -1: Capture specific video resolutions [E]                                                                         
  Test failed. See exception logs above.
  The test description was: Capture specific video resolutions
```

**Comment by camsim99** [comment]
Lowering priority to P2 as I won't actively be working on fixing the `Capture specific video resolutions` tests.
