### ISSUE TITLE
A SemanticsNode with action "increase" needs to be annotated with either both "value" and "decreasedValue" or neither

### ISSUE THREAD

**Issue by xialideng** [flutter/flutter#93696]
<details>
<summary> error log </summary>

```
======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
A SemanticsNode with action "increase" needs to be annotated with either both "value" and "decreasedValue" or neither
'package:flutter/src/semantics/semantics.dart':
Failed assertion: line 2193 pos 7: '!_canPerformAction(SemanticsAction.decrease) || (value == '') == (decreasedValue == '')'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      SemanticsNode.updateWith (package:flutter/src/semantics/semantics.dart:2193:7)
#3      _RenderCupertinoPickerSemantics.assembleSemanticsNode (package:flutter/src/cupertino/picker.dart:507:10)
#4      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3822:13)
#5      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3814:16)
#6      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3768:18)
#7      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3768:18)
#8      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3768:18)
#9      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3814:16)
#10     _RootSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3692:16)
#11     RenderObject._updateSemantics (package:flutter/src/rendering/object.dart:2731:25)
#12     PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1080:16)
#13     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:458:21)
#14     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#15     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
#16     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
#17     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1080:9)
#18     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#22     _invoke (dart:ui/hooks.dart:166:10)
#23     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#24     _drawFrame (dart:ui/hooks.dart:129:31)
(elided 5 frames from class _AssertionError and dart:async)
====================================================================================================

```
</details>

**Comment by darshankawar** [comment]
@xialideng 
Can you provide `flutter doctor -v` and a complete minimal code sample that shows this error ?
Thanks.
