### ISSUE TITLE
Getting `Assertion Error` while switching in between `Bottom Sheets`

### ISSUE THREAD

**Issue by mzdm** [flutter/flutter#93717]
## Steps to Reproduce

1. Run code sample & quickly switch Bottom Sheet by clicking to the buttons

**Expected results:** 
no error

**Actual results:** 
```dart
======== Exception caught by gesture ===============================================================
The following assertion was thrown while handling a gesture:
'package:flutter/src/material/scaffold.dart': Failed assertion: line 2715 pos 14: '_currentBottomSheet!._widget == bottomSheet': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      ScaffoldState._buildBottomSheet._removeCurrentBottomSheet (package:flutter/src/material/scaffold.dart:2715:14)
#3      ScaffoldState._buildBottomSheet.<anonymous closure> (package:flutter/src/material/scaffold.dart:2734:13)
#4      LocalHistoryEntry._notifyRemoved (package:flutter/src/widgets/routes.dart:454:15)
#5      LocalHistoryRoute.removeLocalHistoryEntry (package:flutter/src/widgets/routes.dart:619:11)
#6      LocalHistoryEntry.remove (package:flutter/src/widgets/routes.dart:449:13)
#7      _SheetButtonState._closeSheet (package:sheet_bug/main.dart:85:29)
#8      _SheetButtonState._showInfoSheet (package:sheet_bug/main.dart:48:5)
#9      _SheetButtonState.build.<anonymous closure> (package:sheet_bug/main.dart:42:24)
#10     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989:21)
#11     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:193:24)
#12     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:608:11)
#13     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
#14     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:230:7)
#15     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:558:9)
#16     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:94:12)
#17     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:139:9)
#18     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:400:8)
#19     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:137:18)
#20     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:123:7)
#21     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:440:19)
#22     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:420:22)
#23     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:278:11)
#24     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
#25     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
#26     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#27     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#31     _invoke1 (dart:ui/hooks.dart:185:10)
#32     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
#33     _dispatchPointerDataPacket (dart:ui/hooks.dart:98:31)
(elided 5 frames from class _AssertionError and dart:async)
Handler: "onTap"
Recognizer: TapGestureRecognizer#dc201
  debugOwner: GestureDetector
  state: possible
  won arena
  finalPosition: Offset(58.3, 43.0)
  finalLocalPosition: Offset(58.3, 13.0)
  button: 1
  sent tap down
```

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  PersistentBottomSheetController? sheetController1;
  PersistentBottomSheetController? sheetController2;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Builder(builder: (context) {
          return SafeArea(
            child: Column(
              children: [
                ElevatedButton(
                  child: const Text('show 1'),
                  onPressed: () {
                    if (sheetController1 != null) {
                      sheetController1!.close();
                      sheetController1 = null;
                    }
                    sheetController1 =
                        Scaffold.of(context).showBottomSheet<void>(
                      (BuildContext context) => const Text('BottomSheet 1'),
                    );
                  },
                ),
                ElevatedButton(
                  child: const Text('show 2'),
                  onPressed: () {
                    if (sheetController2 != null) {
                      sheetController2!.close();
                      sheetController2 = null;
                    }
                    sheetController2 =
                        Scaffold.of(context).showBottomSheet<void>(
                      (BuildContext context) => const Text('BottomSheet 2'),
                    );
                  },
                ),
              ],
            ),
          );
        }),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

flutter doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19042.1348], locale cs-CZ)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.3)
[√] Android Studio (version 2020.3)
[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
[√] Connected device (4 available)

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report. I see the same behavior on latest stable and master.

<details>
<summary>console error log</summary>

```
======== Exception caught by gesture ===============================================================
The following assertion was thrown while handling a gesture:
'package:flutter/src/material/scaffold.dart': Failed assertion: line 2344 pos 14: '_currentBottomSheet!._widget == bottomSheet': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      ScaffoldState._buildBottomSheet._removeCurrentBottomSheet (package:flutter/src/material/scaffold.dart:2344:14)
#3      ScaffoldState._buildBottomSheet.<anonymous closure> (package:flutter/src/material/scaffold.dart:2363:13)
#4      LocalHistoryEntry._notifyRemoved (package:flutter/src/widgets/routes.dart:468:15)
#5      LocalHistoryRoute.removeLocalHistoryEntry (package:flutter/src/widgets/routes.dart:633:11)
#6      LocalHistoryEntry.remove (package:flutter/src/widgets/routes.dart:463:13)
#7      _SheetButtonState._closeSheet (package:ios_bug/main.dart:85:29)
#8      _SheetButtonState._showInfoSheet (package:ios_bug/main.dart:48:5)
#9      _SheetButtonState.build.<anonymous closure> (package:ios_bug/main.dart:42:24)
#10     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989:21)
#11     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
#12     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:608:11)
#13     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
#14     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:230:7)
#15     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:563:9)
#16     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:94:12)
#17     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:139:9)
#18     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:539:8)
#19     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:137:18)
#20     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:123:7)
#21     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:439:19)
#22     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:419:22)
#23     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:322:11)
#24     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
#25     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
#26     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#27     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#31     _invoke1 (dart:ui/hooks.dart:169:10)
#32     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
#33     _dispatchPointerDataPacket (dart:ui/hooks.dart:88:31)
(elided 5 frames from class _AssertionError and dart:async)
Handler: "onTap"
Recognizer: TapGestureRecognizer#545e1
  debugOwner: GestureDetector
  state: possible
  won arena
  finalPosition: Offset(79.0, 72.7)
  finalLocalPosition: Offset(78.0, 19.7)
  button: 1
  sent tap down
====================================================================================================

```


</details>

<details>
<summary> stable, master flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.5.3, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.5.3 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (2 days ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dhs/Library/Android/sdk
    • Java binary at: /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.    

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 93.0.4577.82


• No issues found!

[✓] Flutter (Channel master, 2.6.0-12.0.pre.723, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.6.0-12.0.pre.723 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 245168f85c (11 hours ago), 2021-11-15 12:55:32 -0800
    • Engine revision 2962099077
    • Dart version 2.16.0 (build 2.16.0-14.0.dev)
    • DevTools version 2.8.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dhs/Library/Android/sdk
    • Java binary at: /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.    

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 93.0.4577.82


• No issues found!




```

</details>

**Comment by chunhtai** [comment]
It feels like a user error shouldn't the code be like this?
<detail>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  PersistentBottomSheetController? sheetController1;
  PersistentBottomSheetController? sheetController2;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Builder(builder: (context) {
          return SafeArea(
            child: Column(
              children: [
                ElevatedButton(
                  child: const Text('show 1'),
                  onPressed: () {
                    if (sheetController2 != null) {
                      sheetController2!.close();
                      sheetController2 = null;
                    }

                    sheetController1 ??=
                        Scaffold.of(context).showBottomSheet<void>(
                              (BuildContext context) => const Text('BottomSheet 1'),
                        );
                  },
                ),
                ElevatedButton(
                  child: const Text('show 2'),
                  onPressed: () {
                    if (sheetController1 != null) {
                      sheetController1!.close();
                      sheetController1 = null;
                    }
                    sheetController2 ??=
                        Scaffold.of(context).showBottomSheet<void>(
                              (BuildContext context) => const Text('BottomSheet 2'),
                        );
                  },
                ),
              ],
            ),
          );
        }),
      ),
    );
  }
}
```
</detail>

**Comment by mzdm** [comment]
> It feels like a user error shouldn't the code be like this?

Then I think the assertion message should be more descriptive to the user
