### ISSUE TITLE
Installing flutter stable from git not working on macOS Big Sur

### ISSUE THREAD

**Issue by samandmoore** [flutter/flutter#93739]
Hi there. Happy long-time user of Flutter here 👋🏻 

Me and several of my teammates have started seeing an issue with installing Flutter through [`fvm`](https://github.com/leoafarias/fvm/) in the last few days. We thought it might be an issue with `fvm` and how it installs flutter versions but we ruled that out by attempting the standard "install from git" steps (that `fvm` uses) manually and we've reproduced the issue.

TLDR: Install is not working and it's reporting a checksum mismatch. 

```
Downloading Material fonts...                                      836ms
Failed to download https://storage.googleapis.com/flutter_infra_release/flutter/fonts/bd151aa3c2f7231344411a01dba4ef61b3cd56b2/fonts.zip. Ensure you have network connectivity and then try again.
Exception: Expected https://storage.googleapis.com/flutter_infra_release/flutter/fonts/bd151aa3c2f7231344411a01dba4ef61b3cd56b2/fonts.zip to have md5 checksum VF/LGEVR6qaggyU/Ekykeg==, but was rAJgFN+kv13pjIw42PmKmQ==. This may
indicate a problem with your connection to the Flutter backend servers. Please re-try the download after confirming that your network connection is stable.
```

## Steps to Reproduce

Follow the instructions for downloading stable flutter from git [here](https://docs.flutter.dev/get-started/install/macos#downloading-straight-from-github-instead-of-using-an-archive)

1.  `git clone https://github.com/flutter/flutter.git -b stable`
2. `cd flutter`
3. `bin/flutter precache -v`

## Logs

<details>
<summary>Logs</summary>

**Logs from `flutter precache -v`**
```
bin/flutter precache -v
Downloading Dart SDK from Flutter engine d3ea636dc5d16b56819f3266241e1f708979c233...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  219M  100  219M    0     0  12.7M      0  0:00:17  0:00:17 --:--:-- 13.2M
Building flutter tool...
[ +412 ms] executing: sysctl hw.optional.arm64
[  +19 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[   +7 ms] executing: [/Users/sammoore/fvm/versions/dummy/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +26 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 18116933e77adc82f80866c928266a5b4f1ed645
[        ] executing: [/Users/sammoore/fvm/versions/dummy/flutter/] git tag --points-at 18116933e77adc82f80866c928266a5b4f1ed645
[ +104 ms] Exit code 0 from: git tag --points-at 18116933e77adc82f80866c928266a5b4f1ed645
[        ] 2.5.3
[   +9 ms] executing: [/Users/sammoore/fvm/versions/dummy/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/sammoore/fvm/versions/dummy/flutter/] git ls-remote --get-url origin
[  +10 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +595 ms] executing: [/Users/sammoore/fvm/versions/dummy/flutter/] git rev-parse --abbrev-ref HEAD
[  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[   +6 ms] executing: sw_vers -productName
[  +27 ms] Exit code 0 from: sw_vers -productName
[        ] macOS
[        ] executing: sw_vers -productVersion
[  +19 ms] Exit code 0 from: sw_vers -productVersion
[        ] 11.6
[        ] executing: sw_vers -buildVersion
[  +20 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 20G165
[  +68 ms]   ╔════════════════════════════════════════════════════════════════════════════╗
             ║                 Welcome to Flutter! - https://flutter.dev                  ║
             ║                                                                            ║
             ║ The Flutter tool uses Google Analytics to anonymously report feature usage ║
             ║ statistics and basic crash reports. This data is used to help improve      ║
             ║ Flutter tools over time.                                                   ║
             ║                                                                            ║
             ║ Flutter tool analytics are not sent on the very first run. To disable      ║
             ║ reporting, type 'flutter config --no-analytics'. To display the current    ║
             ║ setting, type 'flutter config'. If you opt out of analytics, an opt-out    ║
             ║ event will be sent, and then no further information will be sent by the    ║
             ║ Flutter tool.                                                              ║
             ║                                                                            ║
             ║ By downloading the Flutter SDK, you agree to the Google Terms of Service.  ║
             ║ Note: The Google Privacy Policy describes how data is handled in this      ║
             ║ service.                                                                   ║
             ║                                                                            ║
             ║ Moreover, Flutter includes the Dart SDK, which may send usage metrics and  ║
             ║ crash reports to Google.                                                   ║
             ║                                                                            ║
             ║ Read about data we send with crash reports:                                ║
             ║ https://flutter.dev/docs/reference/crash-reporting                         ║
             ║                                                                            ║
             ║ See Google's privacy policy:                                               ║
             ║ https://policies.google.com/privacy                                        ║
             ╚════════════════════════════════════════════════════════════════════════════╝

[  +56 ms] Downloading Material fonts...
[ +879 ms] Content https://storage.googleapis.com/flutter_infra_release/flutter/fonts/bd151aa3c2f7231344411a01dba4ef61b3cd56b2/fonts.zip md5 hash: VF/LGEVR6qaggyU/Ekykeg==
[ +485 ms] Exception: Expected https://storage.googleapis.com/flutter_infra_release/flutter/fonts/bd151aa3c2f7231344411a01dba4ef61b3cd56b2/fonts.zip to have md5 checksum VF/LGEVR6qaggyU/Ekykeg==, but was rAJgFN+kv13pjIw42PmKmQ==.
This may indicate a problem with your connection to the Flutter backend servers. Please re-try the download after confirming that your network connection is stable.
[  +15 ms] Downloading Material fonts... (completed in 1,368ms)
[        ] Downloading Material fonts...
[ +674 ms] Content https://storage.googleapis.com/flutter_infra_release/flutter/fonts/bd151aa3c2f7231344411a01dba4ef61b3cd56b2/fonts.zip md5 hash: VF/LGEVR6qaggyU/Ekykeg==
[ +225 ms] Exception: Expected https://storage.googleapis.com/flutter_infra_release/flutter/fonts/bd151aa3c2f7231344411a01dba4ef61b3cd56b2/fonts.zip to have md5 checksum VF/LGEVR6qaggyU/Ekykeg==, but was rAJgFN+kv13pjIw42PmKmQ==.
This may indicate a problem with your connection to the Flutter backend servers. Please re-try the download after confirming that your network connection is stable.
[   +1 ms] Downloading Material fonts... (completed in 900ms)
[        ] "flutter precache" took 2,356ms.
[   +4 ms] Failed to download https://storage.googleapis.com/flutter_infra_release/flutter/fonts/bd151aa3c2f7231344411a01dba4ef61b3cd56b2/fonts.zip. Ensure you have network connectivity and then try again.
           Exception: Expected https://storage.googleapis.com/flutter_infra_release/flutter/fonts/bd151aa3c2f7231344411a01dba4ef61b3cd56b2/fonts.zip to have md5 checksum VF/LGEVR6qaggyU/Ekykeg==, but was rAJgFN+kv13pjIw42PmKmQ==.
This may
           indicate a problem with your connection to the Flutter backend servers. Please re-try the download after confirming that your network connection is stable.
[   +3 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      ArtifactUpdater._downloadArchive (package:flutter_tools/src/cache.dart:931:11)
           <asynchronous suspension>
           #2      CachedArtifact.update (package:flutter_tools/src/cache.dart:688:5)
           <asynchronous suspension>
           #3      Cache.updateAll (package:flutter_tools/src/cache.dart:557:9)
           <asynchronous suspension>
           #4      PrecacheCommand.runCommand (package:flutter_tools/src/commands/precache.dart:171:7)
           <asynchronous suspension>
           #5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #13     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>


[   +2 ms] ensureAnalyticsSent: 0ms
[        ] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

I've tried fetching the fonts.zip directly via curl and computing the `md5` sum and I get the **expected** value, does that mean the flutter command is calculating the md5 sum differently?

```
curl https://storage.googleapis.com/flutter_infra_release/flutter/fonts/bd151aa3c2f7231344411a01dba4ef61b3cd56b2/fonts.zip -o fonts.zip
cat fonts.zip | openssl dgst -md5 -binary | openssl enc -base64
VF/LGEVR6qaggyU/Ekykeg==
```

Can't run this because running any `flutter` subcommand errors.

System information

```
Model Name:	MacBook Pro
Model Identifier:	MacBookPro16,1
Processor Name:	6-Core Intel Core i7
MacOS 11.6 (20G165)
```

</details>

**Comment by danagbemava-nc** [comment]
This is a rather strange issue, my colleague and I both tested this and there was no issue. 

My colleague tried on `Catalina` and I tried on `Big Sur`.

See the output of running `bin/flutter precache -v` below. 

@samandmoore, does it always fail at `Downloading Material fonts... (completed in 900ms)` or are there other points of failure?

FWIW: I tested on MacOS 11.5, will also test on 11.6 and tried to feedback.

If there's any more information that you can provide, it would be much appreciated. 

Thank you

[precache_log.txt](https://github.com/flutter/flutter/files/7555191/precache_log.txt)

**Comment by samandmoore** [comment]
> This is a rather strange issue, my colleague and I both tested this and there was no issue.

@danagbemava-nc interesting! It does always fail on the downloading material fonts, but I'm pretty sure that it's when the flutter tool tries to download any of the packaged deps, e.g. here's another way it can fail:

```
flutter run lib/main.dart 
Downloading Web SDK...                                             12.3s
Downloading Web SDK...                                             11.6s
Failed to download https://storage.googleapis.com/flutter_infra_release/flutter/d3ea636dc5d16b56819f3266241e1f708979c233/flutter-web-sdk-darwin-x64.zip. Ensure you have network connectivity and then try again.
Exception: Expected https://storage.googleapis.com/flutter_infra_release/flutter/d3ea636dc5d16b56819f3266241e1f708979c233/flutter-web-sdk-darwin-x64.zip to have md5 checksum PHsJDH46tS0kDFndw6xdYA==, but was
S0pdWEKqoukCSf7dEDBkwQ==. This may indicate a problem with your connection to the Flutter backend servers. Please re-try the download after confirming that your network connection is stable.
```

Also, I noticed that your precache logs have a lot more detail than the ones I submitted. Is there a way to get that extra detail?

**Comment by samandmoore** [comment]
One thing I did want to highlight is that if I manually fetch that fonts.zip and checksum it, I get a matching value. So I'm not sure how the flutter tool is computing the invalid checksum:

I've tried fetching the fonts.zip directly via curl and computing the `md5` sum and I get the **expected** value, does that mean the flutter command is calculating the md5 sum differently?

```
curl https://storage.googleapis.com/flutter_infra_release/flutter/fonts/bd151aa3c2f7231344411a01dba4ef61b3cd56b2/fonts.zip -o fonts.zip
cat fonts.zip | openssl dgst -md5 -binary | openssl enc -base64
VF/LGEVR6qaggyU/Ekykeg==
```

**Comment by samandmoore** [comment]
I'm doing more investigating and I've found the downloaded file and compared it to the manually downloaded file:

```
$ curl https://storage.googleapis.com/flutter_infra_release/flutter/fonts/bd151aa3c2f7231344411a01dba4ef61b3cd56b2/fonts.zip -o fonts-good.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2145k  100 2145k    0     0  8903k      0 --:--:-- --:--:-- --:--:-- 8903k

$ cp ~/fvm/versions/dummy/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra_release/flutter/fonts/bd151aa3c2f7231344411a01dba4ef61b3cd56b2/fonts.zip .

$ cat fonts.zip | openssl dgst -md5 -binary | openssl enc -base64
rAJgFN+kv13pjIw42PmKmQ==

$ cat fonts-good.zip | openssl dgst -md5 -binary | openssl enc -base64
VF/LGEVR6qaggyU/Ekykeg==
```

**but when I diff the zips, they have the same files but the timestamps are different on some of the files!**

```
$ /usr/bin/diff <(unzip -l fonts.zip) <(unzip -l fonts-good.zip)
1c1
< Archive:  fonts.zip
---
> Archive:  fonts-good.zip
4,26c4,26
<     18531  03-11-2021 13:43   MaterialIcons_LICENSE.txt
<    169800  12-14-2017 20:00   RobotoCondensed-Bold.ttf
<    171904  12-14-2017 20:00   Roboto-Thin.ttf
<    175888  12-14-2017 20:00   RobotoCondensed-BoldItalic.ttf
<     11358  03-11-2021 13:43   RobotoCondensed_LICENSE.txt
<    175380  12-14-2017 20:00   RobotoCondensed-LightItalic.ttf
<    170760  12-14-2017 20:00   Roboto-Bold.ttf
<    177552  12-14-2017 20:00   Roboto-BlackItalic.ttf
<    168004  12-14-2017 20:00   RobotoCondensed-Light.ttf
<    171676  12-14-2017 20:00   Roboto-Regular.ttf
<    171480  12-14-2017 20:00   Roboto-Black.ttf
<    170284  12-14-2017 20:00   RobotoCondensed-Regular.ttf
<    176616  12-14-2017 20:00   Roboto-LightItalic.ttf
<   1299300  03-12-2021 11:52   MaterialIcons-Regular.otf
<    172064  12-14-2017 20:00   Roboto-Medium.ttf
<    176864  12-14-2017 20:00   Roboto-MediumItalic.ttf
<    175188  12-14-2017 20:00   RobotoCondensed-Italic.ttf
<    174952  12-14-2017 20:00   Roboto-BoldItalic.ttf
<    172368  03-16-2021 06:09   codepoints
<    173932  12-14-2017 20:00   Roboto-Italic.ttf
<    176300  12-14-2017 20:00   Roboto-ThinItalic.ttf
<     11358  03-11-2021 13:43   Roboto_LICENSE.txt
<    170420  12-14-2017 20:00   Roboto-Light.ttf
---
>     18531  03-11-2021 18:43   MaterialIcons_LICENSE.txt
>    169800  12-15-2017 01:00   RobotoCondensed-Bold.ttf
>    171904  12-15-2017 01:00   Roboto-Thin.ttf
>    175888  12-15-2017 01:00   RobotoCondensed-BoldItalic.ttf
>     11358  03-11-2021 18:43   RobotoCondensed_LICENSE.txt
>    175380  12-15-2017 01:00   RobotoCondensed-LightItalic.ttf
>    170760  12-15-2017 01:00   Roboto-Bold.ttf
>    177552  12-15-2017 01:00   Roboto-BlackItalic.ttf
>    168004  12-15-2017 01:00   RobotoCondensed-Light.ttf
>    171676  12-15-2017 01:00   Roboto-Regular.ttf
>    171480  12-15-2017 01:00   Roboto-Black.ttf
>    170284  12-15-2017 01:00   RobotoCondensed-Regular.ttf
>    176616  12-15-2017 01:00   Roboto-LightItalic.ttf
>   1299300  03-12-2021 16:52   MaterialIcons-Regular.otf
>    172064  12-15-2017 01:00   Roboto-Medium.ttf
>    176864  12-15-2017 01:00   Roboto-MediumItalic.ttf
>    175188  12-15-2017 01:00   RobotoCondensed-Italic.ttf
>    174952  12-15-2017 01:00   Roboto-BoldItalic.ttf
>    172368  03-16-2021 10:09   codepoints
>    173932  12-15-2017 01:00   Roboto-Italic.ttf
>    176300  12-15-2017 01:00   Roboto-ThinItalic.ttf
>     11358  03-11-2021 18:43   Roboto_LICENSE.txt
>    170420  12-15-2017 01:00   Roboto-Light.ttf
```

**Comment by samandmoore** [comment]
now i'm kinda at the edge of my understanding of zip files and checksums, but the contents within the zips _appear_ to be the same

1. they both have the same 23 files (see above)
2. the md5sum of each file matches
```
for FILE in $(ls fonts-good);
do
  REGULAR=$(cat "fonts/$FILE" | openssl dgst -md5 -binary | openssl enc -base64)
  GOOD=$(cat "fonts-good/$FILE" | openssl dgst -md5 -binary | openssl enc -base64)
  echo "==============" >> results.txt
  echo "$FILE" >> results.txt
  echo "$REGULAR" >> results.txt
  echo "$GOOD" >> results.txt
done
```

**results.txt**
```
==============
MaterialIcons-Regular.otf
TmRHaRyVCfes2/ipMahcoQ==
TmRHaRyVCfes2/ipMahcoQ==
==============
MaterialIcons_LICENSE.txt
knLcpG4TvXPcVhfkzihS/A==
knLcpG4TvXPcVhfkzihS/A==
==============
Roboto-Black.ttf
7EyZYrpU65F4eqk9NhwQqA==
7EyZYrpU65F4eqk9NhwQqA==
==============
Roboto-BlackItalic.ttf
UHBcXtEgW2Pv2/7pQaa2VQ==
UHBcXtEgW2Pv2/7pQaa2VQ==
==============
Roboto-Bold.ttf
7nuW+oXY/bjBJkCTJqwtKw==
7nuW+oXY/bjBJkCTJqwtKw==
==============
Roboto-BoldItalic.ttf
Hreok1id3Oidgc2yKjVmYA==
Hreok1id3Oidgc2yKjVmYA==
==============
Roboto-Italic.ttf
Qrvk7vzeEpexHcS2SR6XRg==
Qrvk7vzeEpexHcS2SR6XRg==
==============
Roboto-Light.ttf
/ITpmLwpspfqIDIeTJC27Q==
/ITpmLwpspfqIDIeTJC27Q==
==============
Roboto-LightItalic.ttf
0e/NTRJoN/4Nz5ts86ANZA==
0e/NTRJoN/4Nz5ts86ANZA==
==============
Roboto-Medium.ttf
0IhAWZ4F23NFZS09QXV0qQ==
0IhAWZ4F23NFZS09QXV0qQ==
==============
Roboto-MediumItalic.ttf
vRmtYGAKFTfADTtJI6Xl3g==
vRmtYGAKFTfADTtJI6Xl3g==
==============
Roboto-Regular.ttf
Phrz71Rrnm7O+fO6GXv30g==
Phrz71Rrnm7O+fO6GXv30g==
==============
Roboto-Thin.ttf
ieJmbCTTcFW8tg6dLZ9+NQ==
ieJmbCTTcFW8tg6dLZ9+NQ==
==============
Roboto-ThinItalic.ttf
D8JThiIKWCA5lM5F+0rlcA==
D8JThiIKWCA5lM5F+0rlcA==
==============
RobotoCondensed-Bold.ttf
NrXaAzM4kwZmllWhPyIJrQ==
NrXaAzM4kwZmllWhPyIJrQ==
==============
RobotoCondensed-BoldItalic.ttf
pruJTu4V7aVG9eYIIhY1Pw==
pruJTu4V7aVG9eYIIhY1Pw==
==============
RobotoCondensed-Italic.ttf
mtzvZqzM9ZwpC+2xq28qsQ==
mtzvZqzM9ZwpC+2xq28qsQ==
==============
RobotoCondensed-Light.ttf
EX9odwOeQQqL4hchQ+TI0g==
EX9odwOeQQqL4hchQ+TI0g==
==============
RobotoCondensed-LightItalic.ttf
UGsVXP0zoKkNOyyVhMsL+w==
UGsVXP0zoKkNOyyVhMsL+w==
==============
RobotoCondensed-Regular.ttf
paa3ElXcgy2lhdXJT6GhFQ==
paa3ElXcgy2lhdXJT6GhFQ==
==============
RobotoCondensed_LICENSE.txt
O4Pvljh/FGVfyFTdw8a9Vw==
O4Pvljh/FGVfyFTdw8a9Vw==
==============
Roboto_LICENSE.txt
O4Pvljh/FGVfyFTdw8a9Vw==
O4Pvljh/FGVfyFTdw8a9Vw==
==============
codepoints
ts9i/m/AHPHbDFYQxq9zsA==
ts9i/m/AHPHbDFYQxq9zsA==
```

here's the two zips if it helps anyone!
[fonts-good.zip](https://github.com/flutter/flutter/files/7556436/fonts-good.zip)
[fonts.zip](https://github.com/flutter/flutter/files/7556437/fonts.zip)

**Comment by samandmoore** [comment]
I also just made a reproduction of the dart code from flutter that is doing the download to show that it doesn't download the file with the same result as `curl` does on my machine:

<details>
<summary>Dart reproduction script</summary>

**pubspec.yaml**
```
name: download

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  crypto: any
```

**download.dart**
```dart
import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:crypto/crypto.dart';

Future<void> main() async {
  Download().download(
    Uri.parse(
      'https://storage.googleapis.com/flutter_infra_release/flutter/fonts/bd151aa3c2f7231344411a01dba4ef61b3cd56b2/fonts.zip',
    ),
    File('dart-script-fonts.zip')..createSync(),
  );
}

class Download {
  final _httpClient = HttpClient();

  Future<void> download(Uri url, File file) async {
    final HttpClientRequest request = await _httpClient.getUrl(url);
    final HttpClientResponse response = await request.close();
    if (response.statusCode != HttpStatus.ok) {
      throw Exception(response.statusCode);
    }

    final String? md5Hash = _expectedMd5(response.headers);
    ByteConversionSink? inputSink;
    late StreamController<Digest> digests;
    if (md5Hash != null) {
      print('Content $url md5 hash: $md5Hash');
      digests = StreamController<Digest>();
      inputSink = md5.startChunkedConversion(digests);
    }
    final RandomAccessFile randomAccessFile =
        file.openSync(mode: FileMode.writeOnly);
    await response.forEach((List<int> chunk) {
      inputSink?.add(chunk);
      randomAccessFile.writeFromSync(chunk);
    });
    randomAccessFile.closeSync();
    if (inputSink != null) {
      inputSink.close();
      final Digest digest = await digests.stream.last;
      final String rawDigest = base64.encode(digest.bytes);
      print('Computed md5 hash: $rawDigest');
      if (rawDigest != md5Hash) {
        throw Exception(
            'Expected $url to have md5 checksum $md5Hash, but was $rawDigest. This '
            'may indicate a problem with your connection to the Flutter backend servers. '
            'Please re-try the download after confirming that your network connection is '
            'stable.');
      }
    }
  }

  String? _expectedMd5(HttpHeaders httpHeaders) {
    final List<String>? values = httpHeaders['x-goog-hash'];
    if (values == null) {
      return null;
    }
    String? rawMd5Hash;
    for (final String value in values) {
      if (value.startsWith('md5=')) {
        rawMd5Hash = value;
        break;
      }
    }
    if (rawMd5Hash == null) {
      return null;
    }
    final List<String> segments = rawMd5Hash.split('md5=');
    if (segments.length < 2) {
      return null;
    }
    final String md5Hash = segments[1];
    if (md5Hash.isEmpty) {
      return null;
    }
    return md5Hash;
  }
}
```
</details>

my results (depends on having a working version of dart 2.14+ installed):

```
$ dart download.dart
Content https://storage.googleapis.com/flutter_infra_release/flutter/fonts/bd151aa3c2f7231344411a01dba4ef61b3cd56b2/fonts.zip md5 hash: VF/LGEVR6qaggyU/Ekykeg==
Computed md5 hash: rAJgFN+kv13pjIw42PmKmQ==
Unhandled exception:
Exception: Expected https://storage.googleapis.com/flutter_infra_release/flutter/fonts/bd151aa3c2f7231344411a01dba4ef61b3cd56b2/fonts.zip to have md5 checksum VF/LGEVR6qaggyU/Ekykeg==, but was rAJgFN+kv13pjIw42PmKmQ==. This may indicate a problem with your connection to the Flutter backend servers. Please re-try the download after confirming that your network connection is stable.
#0      Download.download (file:///Users/sammoore/fvm/versions/dummy/download/download.dart:47:9)
<asynchronous suspension>
```

**Comment by samandmoore** [comment]
okay, we've tracked this down to a workstation management tool deployed on our machines by our IT department. 

it must be modifying the files in-flight. surprisingly, this hasn't been an issue for us until just recently. that probably indicates a change in the configuration of this IT security tooling. 

i'm going to close this for now.

Thank you for your patience 😄
