### ISSUE TITLE
Error running flutter doctor: "ProcessException: invalid directory name"

### ISSUE THREAD

**Issue by giorgiofran** [flutter/flutter#93792]
## Steps to Reproduce

In windows 10
> flutter doctor

**This is the stdout:**
```
C:\Users\gfran>flutter doctor
Impossibile trovare il file specificato.
Running "flutter pub get" in flutter_tools...

Oops; flutter has exited unexpectedly: "ProcessException: Nome di directory non valido.

  Command: C:\Users\gfran\flutter\bin\cache\dart-sdk\bin\pub.BAT --verbosity=warning get --no-precompile".
A crash report has been written to C:\Users\gfran\flutter_12.log.
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+ProcessException%3A+Nome+di+directory+non+valido.%0D%0A%0A++Command%3A+C%3A%5CUsers%5Cgfran%5Cflutter%5Cbin%5Ccache%5Cdart-sdk%5Cbin%5Cpub.BAT+--verbosity%3Dwarning+get+--no-precompile

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
https://git.io/J1RcE
```

## Logs

**this is the log:**

Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception

ProcessException: ProcessException: Nome di directory non valido.

  Command: C:\Users\gfran\flutter\bin\cache\dart-sdk\bin\pub.BAT --verbosity=warning get --no-precompile

```
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:390:33)
#1      Process.start (dart:io-patch/process_patch.dart:36:20)
#2      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:44:22)
#3      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:691:24)
#4      _run (package:flutter_tools/src/base/error_handling_io.dart:567:20)
#5      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:690:12)
#6      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:425:28)
#7      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:444:35)
#8      _DefaultPub.batch (package:flutter_tools/src/dart/pub.dart:308:34)
<asynchronous suspension>
#9      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:248:7)
<asynchronous suspension>
#10     PubDependencies.update (package:flutter_tools/src/flutter_cache.dart:119:5)
<asynchronous suspension>
#11     Cache.updateAll (package:flutter_tools/src/cache.dart:557:9)
<asynchronous suspension>
#12     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1227:7)
<asynchronous suspension>
#13     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
<asynchronous suspension>
#17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#18     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
<asynchronous suspension>
#19     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#20     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#21     main (package:flutter_tools/executable.dart:92:3)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Versione 10.0.19043.1348], locale it-IT)
    • Flutter version 2.5.3 at C:\Users\gfran\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (5 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\gfran\AppData\Local\Android\sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 95.0.4638.69
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 95.0.1020.53

! Doctor found issues in 1 category.
```

**Comment by giorgiofran** [comment]
I got the problem.
It seems that in windows 10 there is a new functionality that locks all files downloaded from another computer (in my case the internet). I installed flutter downloading the zip file. Now, the zip file was locked and, extracting the content all executable files (and also those without an extension... AFAIK) were locked too. It is easy to unlock them, going in the property tab, at the bottom there is a check-box that allows you to unlock the file. The problem is that there are a lot of file to unlock, and I couldn't find any way to do this for a folder, only one by one.
Finally, I discovered googling that if you unlock the zip file before extracting the content, all executable are created correctly..
So I deleted the old flutter folder, unlocked the zip file and extracted everything a second time. 

Now ` flutter doctor` works fine.

It is probably better to update the documentation on flutter.dev
