### ISSUE TITLE
[camera] Problem when using camera plugin with image picker

### ISSUE THREAD

**Issue by innerk** [flutter/flutter#93888]
Is anyone having this problem?

when the camera is active and take a picture or select an image from the gallery this error appears instantly, i think the error comes on didChangeAppLifecycleState after inactive state.

`
I/flutter (28192): camara state  AppLifecycleState.inactive
W/MessageQueue(17618): 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:567)
W/MessageQueue(17618): 	at android.os.Handler.enqueueMessage(Handler.java:778)
W/MessageQueue(17618): 	at android.os.Handler.sendMessageAtTime(Handler.java:727)
W/MessageQueue(17618): 	at android.os.Handler.sendMessageDelayed(Handler.java:697)
W/MessageQueue(17618): 	at android.os.Handler.post(Handler.java:427)
W/MessageQueue(17618): 	at android.hardware.camera2.impl.CameraDeviceImpl$CameraHandlerExecutor.execute(CameraDeviceImpl.java:2212)
W/MessageQueue(17618): 	at android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.onResultReceived(CameraDeviceImpl.java:2120)
W/MessageQueue(17618): 	at android.hardware.camera2.ICameraDeviceCallbacks$Stub.onTransact(ICameraDeviceCallbacks.java:180)
W/MessageQueue(17618): 	at android.os.Binder.execTransactInternal(Binder.java:1173)
W/MessageQueue(17618): 	at android.os.Binder.execTransact(Binder.java:1132)
E/CameraManagerGlobal(17618): Camera 3 is not available. Ignore physical camera status change
W/MessageQueue(17618): Handler (android.os.Handler) {1b4b05e} sending message to a Handler on a dead thread
W/MessageQueue(17618): java.lang.IllegalStateException: Handler (android.os.Handler) {1b4b05e} sending message to a Handler on a dead thread
W/MessageQueue(17618): 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:567)
W/MessageQueue(17618): 	at android.os.Handler.enqueueMessage(Handler.java:778)
W/MessageQueue(17618): 	at android.os.Handler.sendMessageAtTime(Handler.java:727)
W/MessageQueue(17618): 	at android.os.Handler.sendMessageDelayed(Handler.java:697)
W/MessageQueue(17618): 	at android.os.Handler.post(Handler.java:427)
W/MessageQueue(17618): 	at android.hardware.camera2.impl.CameraDeviceImpl$CameraHandlerExecutor.execute(CameraDeviceImpl.java:2212)
W/MessageQueue(17618): 	at android.hardware.camera2.impl.CameraDeviceImpl.close(CameraDeviceImpl.java:1331)
W/MessageQueue(17618): 	at io.flutter.plugins.camera.Camera.close(Camera.java:1096)
W/MessageQueue(17618): 	at io.flutter.plugins.camera.Camera.dispose(Camera.java:1119)
W/MessageQueue(17618): 	at io.flutter.plugins.camera.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:361)
W/MessageQueue(17618): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
W/MessageQueue(17618): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
W/MessageQueue(17618): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
W/MessageQueue(17618): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/MessageQueue(17618): 	at android.os.MessageQueue.next(MessageQueue.java:342)
W/MessageQueue(17618): 	at android.os.Looper.loop(Looper.java:197)
W/MessageQueue(17618): 	at android.app.ActivityThread.main(ActivityThread.java:7803)
W/MessageQueue(17618): 	at java.lang.reflect.Method.invoke(Native Method)
W/MessageQueue(17618): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
W/MessageQueue(17618): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
`

**Comment by maheshmnj** [comment]
Hi @innerk, Thanks for filing the issue. I did not see any such logs when using `camera: ^0.9.4+3` or 
`image_picker: ^0.8.4+3`, Could you please share the steps to reproduce those logs? Which IDE are you using?  Please share the output of `flutter doctor -v`.

Thanks

**Comment by innerk** [comment]
@maheshmnj hey thanks for the response, already solve it, it was missing a listener

` void onNewCameraSelected(CameraDescription cameraDescription) async {
    if (controladorCam != null) {
      await controladorCam!.dispose();
    }

    final CameraController cameraController = CameraController(
      cameraDescription,
      ResolutionPreset.high,
      enableAudio: false,
      imageFormatGroup: ImageFormatGroup.jpeg,
    );

    // If the controller is updated then update the UI.
    cameraController.addListener(() {
      if (mounted) setState(() {});
      if (cameraController.value.hasError) {
        print('Camera error ${cameraController.value.errorDescription}');
      }
    });

    try {
      await cameraController.initialize();
    } on CameraException catch (e) {
      print(e);
    }

    if (mounted) {
      setState(() {});
    }
  }`

**Comment by innerk** [comment]
@maheshmnj i create an example with the actual issue, here it is https://github.com/innerk/cameratest

**Comment by maheshmnj** [comment]
Thanks for the reproducible code sample @innerk, I was able to reproduce the same behavior the logs are infinitely sent to the console even when image_picker / camera is not active. I upgrade the plugins to the latest versions and this seems to have resolved the issue. 
Could you please try upgrading the plugin ?

```yaml
  camera: ^0.9.4+5
  image_picker: ^0.8.4+4
```

<details>
<summary>logs(post upgrade)</summary>

```console
Launching lib/main.dart on Redmi K20 Pro in debug mode...
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
/Users/mahesh/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.9.4+5/android/src/main/java/io/flutter/plugins/camera/features/resolution/ResolutionFeature.java:154: warning: [deprecation] get(int,int) in CamcorderProfile has been deprecated
          return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_HIGH);
                                 ^
/Users/mahesh/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.9.4+5/android/src/main/java/io/flutter/plugins/camera/features/resolution/ResolutionFeature.java:158: warning: [deprecation] get(int,int) in CamcorderProfile has been deprecated
          return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_2160P);
                                 ^
/Users/mahesh/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.9.4+5/android/src/main/java/io/flutter/plugins/camera/features/resolution/ResolutionFeature.java:162: warning: [deprecation] get(int,int) in CamcorderProfile has been deprecated
          return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_1080P);
                                 ^
/Users/mahesh/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.9.4+5/android/src/main/java/io/flutter/plugins/camera/features/resolution/ResolutionFeature.java:166: warning: [deprecation] get(int,int) in CamcorderProfile has been deprecated
          return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_720P);
                                 ^
/Users/mahesh/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.9.4+5/android/src/main/java/io/flutter/plugins/camera/features/resolution/ResolutionFeature.java:170: warning: [deprecation] get(int,int) in CamcorderProfile has been deprecated
          return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_480P);
                                 ^
/Users/mahesh/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.9.4+5/android/src/main/java/io/flutter/plugins/camera/features/resolution/ResolutionFeature.java:174: warning: [deprecation] get(int,int) in CamcorderProfile has been deprecated
          return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_QVGA);
                                 ^
/Users/mahesh/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.9.4+5/android/src/main/java/io/flutter/plugins/camera/features/resolution/ResolutionFeature.java:178: warning: [deprecation] get(int,int) in CamcorderProfile has been deprecated
          return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_LOW);
                                 ^

7 warnings
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
W/FlutterActivityAndFragmentDelegate(25052): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
Connecting to VM Service at ws://127.0.0.1:51689/nGBf7tOY5GE=/ws
I/mple.camerates(25052): ProcessProfilingInfo new_methods=557 is saved saved_to_disk=1 resolve_classes_delay=8000
D/SurfaceView(25052): UPDATE null, mIsCastMode = false
W/MirrorManager(25052): this model don't Support
I/CameraManagerGlobal(25052): Connecting to camera service
W/CameraManagerGlobal(25052): [soar.cts] ignore the status update of camera: 100
W/CameraManagerGlobal(25052): [soar.cts] ignore the status update of camera: 101
W/CameraManagerGlobal(25052): [soar.cts] ignore the status update of camera: 120
W/CameraManagerGlobal(25052): [soar.cts] ignore the status update of camera: 20
W/CameraManagerGlobal(25052): [soar.cts] ignore the status update of camera: 21
W/CameraManagerGlobal(25052): [soar.cts] ignore the status update of camera: 60
W/CameraManagerGlobal(25052): [soar.cts] ignore the status update of camera: 61
W/CameraManagerGlobal(25052): [soar.cts] ignore the status update of camera: 62
W/CameraManagerGlobal(25052): [soar.cts] ignore the status update of camera: 63
W/CameraManagerGlobal(25052): ignore the torch status update of camera: 100
W/CameraManagerGlobal(25052): ignore the torch status update of camera: 120
W/CameraManagerGlobal(25052): ignore the torch status update of camera: 20
W/CameraManagerGlobal(25052): ignore the torch status update of camera: 21
W/CameraManagerGlobal(25052): ignore the torch status update of camera: 60
W/CameraManagerGlobal(25052): ignore the torch status update of camera: 61
W/CameraManagerGlobal(25052): ignore the torch status update of camera: 62
W/CameraManagerGlobal(25052): ignore the torch status update of camera: 63
I/flutter (25052): [CameraDescription(0, CameraLensDirection.back, 90), CameraDescription(1, CameraLensDirection.front, 270)]
W/Camera  (25052): The selected imageFormatGroup is not supported by Android. Defaulting to yuv420
E/libc    (25052): Access denied finding property "persist.vendor.camera.privapp.list"
W/mple.cameratest(25052): type=1400 audit(0.0:748420): avc: denied { read } for name="u:object_r:vendor_persist_camera_prop:s0" dev="tmpfs" ino=29870 scontext=u:r:untrusted_app:s0:c142,c259,c512,c768 tcontext=u:object_r:vendor_persist_camera_prop:s0 tclass=file permissive=0 app=com.jio.myjio
I/Camera  (25052): startPreview
I/Camera  (25052): CameraCaptureSession onConfigured
I/Camera  (25052): Updating builder settings
D/Camera  (25052): Updating builder with feature: ExposureLockFeature
D/Camera  (25052): Updating builder with feature: ExposurePointFeature
D/Camera  (25052): Updating builder with feature: ZoomLevelFeature
D/Camera  (25052): Updating builder with feature: AutoFocusFeature
D/Camera  (25052): Updating builder with feature: NoiseReductionFeature
I/Camera  (25052): updateNoiseReduction | currentSetting: fast
D/Camera  (25052): Updating builder with feature: FocusPointFeature
D/Camera  (25052): Updating builder with feature: ResolutionFeature
D/Camera  (25052): Updating builder with feature: SensorOrientationFeature
D/Camera  (25052): Updating builder with feature: FlashFeature
D/Camera  (25052): Updating builder with feature: ExposureOffsetFeature
D/Camera  (25052): Updating builder with feature: FpsRangeFeature
I/Camera  (25052): refreshPreviewCaptureSession
I/flutter (25052): CameraController#cf2a9(CameraValue(isRecordingVideo: false, isInitialized: true, errorDescription: null, previewSize: Size(1280.0, 720.0), isStreamingImages: false, flashMode: FlashMode.auto, exposureMode: ExposureMode.auto, focusMode: FocusMode.auto, exposurePointSupported: true, focusPointSupported: true, deviceOrientation: DeviceOrientation.portraitUp, lockedCaptureOrientation: null, recordingOrientation: null, isPreviewPaused: false, previewPausedOrientation: null))
I/Timeline(25052): Timeline: Activity_launch_request time:148450098
I/flutter (25052): imagen picker : null
I/flutter (25052): asdsas caputara
I/Camera  (25052): runPictureAutoFocus
I/Camera  (25052): lockAutoFocus
D/CameraCaptureCallback(25052): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 2 | aeState: 2
D/CameraCaptureCallback(25052): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 2 | aeState: 2
D/CameraCaptureCallback(25052): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 2 | aeState: 2
D/CameraCaptureCallback(25052): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 2 | aeState: 2
D/CameraCaptureCallback(25052): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 2 | aeState: 2
D/CameraCaptureCallback(25052): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 2 | aeState: 2
D/CameraCaptureCallback(25052): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 2 | aeState: 2
D/CameraCaptureCallback(25052): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 2 | aeState: 2
D/CameraCaptureCallback(25052): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 2 | aeState: 2
D/CameraCaptureCallback(25052): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 2 | aeState: 2
D/CameraCaptureCallback(25052): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 2 | aeState: 2
D/CameraCaptureCallback(25052): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 2 | aeState: 2
D/CameraCaptureCallback(25052): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 2 | aeState: 2
D/CameraCaptureCallback(25052): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 2 | aeState: 2
D/CameraCaptureCallback(25052): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 2 | aeState: 2
D/CameraCaptureCallback(25052): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 2 | aeState: 2
D/CameraCaptureCallback(25052): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 2 | aeState: 2
D/CameraCaptureCallback(25052): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 2 | aeState: 2
D/CameraCaptureCallback(25052): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 2 | aeState: 2
D/CameraCaptureCallback(25052): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 2 | aeState: 2
D/CameraCaptureCallback(25052): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 4 | aeState: 2
I/Camera  (25052): captureStillPicture
D/Camera  (25052): Updating builder with feature: ExposureLockFeature
D/Camera  (25052): Updating builder with feature: ExposurePointFeature
D/Camera  (25052): Updating builder with feature: ZoomLevelFeature
D/Camera  (25052): Updating builder with feature: AutoFocusFeature
D/Camera  (25052): Updating builder with feature: NoiseReductionFeature
I/Camera  (25052): updateNoiseReduction | currentSetting: fast
D/Camera  (25052): Updating builder with feature: FocusPointFeature
D/Camera  (25052): Updating builder with feature: ResolutionFeature
D/Camera  (25052): Updating builder with feature: SensorOrientationFeature
D/Camera  (25052): Updating builder with feature: FlashFeature
D/Camera  (25052): Updating builder with feature: ExposureOffsetFeature
D/Camera  (25052): Updating builder with feature: FpsRangeFeature
I/Camera  (25052): sending capture request
D/CameraCaptureCallback(25052): CameraCaptureCallback | state: STATE_CAPTURING | afState: 2 | aeState: 2
I/Camera  (25052): unlockAutoFocus
I/Camera  (25052): refreshPreviewCaptureSession
D/CameraCaptureCallback(25052): CameraCaptureCallback | state: STATE_CAPTURING | afState: 2 | aeState: 2
I/Camera  (25052): onImageAvailable
D/qdgralloc(25052): GetYUVPlaneInfo: Invalid format passed: 0x21
I/Timeline(25052): Timeline: Activity_launch_request time:148457619
I/flutter (25052): imagen picker : null
D/MIUIInput(25052): [KeyEvent] ViewRootImpl KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x48, repeatCount=0, eventTime=148461458, downTime=148461458, deviceId=-1, source=0x101, displayId=0 }
D/MIUIInput(25052): [KeyEvent] ViewRootImpl KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x48, repeatCount=0, eventTime=148461548, downTime=148461458, deviceId=-1, source=0x101, displayId=0 }
Application finished.
Exited (sigterm)
```
</details>
   
   
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.5.3 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (5 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:5555 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos            • darwin-arm64   • macOS 12.0.1 21A559 darwin-arm
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 96.0.4664.55

• No issues found!
```
</details>

**Comment by innerk** [comment]
yes, problem solved :) @maheshmnj thanks
