### ISSUE TITLE
Failed assertion: line 2747 pos 12: '!_needsLayout'

### ISSUE THREAD

**Issue by ycg520520** [flutter/flutter#93918]
```bash
flutter: ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞══════════════════════
flutter: The following assertion was thrown during a scheduler callback:
flutter: Updated layout information required for
flutter: RenderIndexedSemantics#9ecae NEEDS-LAYOUT to calculate semantics.
flutter: 'package:flutter/src/rendering/object.dart':
flutter: Failed assertion: line 2747 pos 12: '!_needsLayout'
flutter:
flutter: Either the assertion indicates an error in the framework itself,
flutter: or we should provide substantially more information in this error
flutter: message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on
flutter: GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=2_bug.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2747:12)
flutter: #3      RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2759:61)
flutter: #4      Iterable.forEach (dart:core/iterable.dart:279:35)
flutter: #5      RenderSliverVariableSizeBoxAdaptor.visitChildren (package:flutter_staggered_grid_view/src/rendering/sliver_variable_size_box_adaptor.dart:296:29)
flutter: #6      RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2836:5)
flutter: #7      RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2757:5)
flutter: #8      RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2759:61)
flutter: #9      RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3128:14)
flutter: #10     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2836:5)
flutter: #11     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2757:5)
flutter: #12     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2759:61)
flutter: #13     Iterable.forEach (dart:core/iterable.dart:279:35)
flutter: #14     RenderViewportBase.visitChildrenForSemantics (package:flutter/src/rendering/viewport.dart:222:10)
flutter: #15     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2757:5)
flutter: #16     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2759:61)
flutter: #17     RenderIgnorePointer.visitChildrenForSemantics (package:flutter/src/rendering/proxy_box.dart:3309:14)
flutter: #18     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2757:5)
flutter: #19     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2759:61)
flutter: #20     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3128:14)
flutter: #21     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2836:5)
flutter: #22     RenderSemanticsAnnotations.visitChildrenForSemantics (package:flutter/src/rendering/proxy_box.dart:4706:11)
flutter: #23     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2757:5)
flutter: #24     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2759:61)
flutter: #25     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3128:14)
flutter: #26     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2836:5)
flutter: #27     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2757:5)
flutter: #28     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2759:61)
flutter: #29     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3128:14)
flutter: #30     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2836:5)
flutter: #31     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2757:5)
flutter: #32     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2759:61)
flutter: #33     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3128:14)
flutter: #34     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2836:5)
flutter: #35     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2757:5)
flutter: #36     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2759:61)
flutter: #37     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3128:14)
flutter: #38     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2836:5)
flutter: #39     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2757:5)
flutter: #40     RenderObject._updateSemantics (package:flutter/src/rendering/object.dart:2725:41)
flutter: #41     PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1080:16)
flutter: #42     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:458:21)
flutter: #43     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
flutter: #44     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
flutter: #45     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
flutter: #46     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
flutter: #47     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
flutter: #51     _invoke (dart:ui/hooks.dart:150:10)
flutter: #52     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
flutter: #53     _drawFrame (dart:ui/hooks.dart:114:31)
flutter: (elided 5 frames from class _AssertionError and dart:async)
flutter: ═════════════════════════════════════════════════════════════════
```

```bash
flutter doctor -v

[✓] Flutter (Channel beta, 2.7.0-3.1.pre, on macOS 12.0.1 21A559 darwin-x64,
    locale zh-Hans-CN)
    • Flutter version 2.7.0-3.1.pre at /Users/yangchaoguo/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fc7015e35a (3 weeks ago), 2021-10-27 15:18:41 -0700
    • Engine revision a75e3b80f9
    • Dart version 2.15.0 (build 2.15.0-178.1.beta)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/yangchaoguo/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/yangchaoguo/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.62.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (2 available)
    • iPhone 13 (mobile) • DE52EF27-8F7E-4131-8CDB-5DCF25C10285 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 96.0.4664.55
```

**Comment by danagbemava-nc** [comment]
Hi @ycg520520, please provide a complete minimal reproducible code sample. 

Thank you
