### ISSUE TITLE
ci.yaml validation failed due to github token generation failing

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#93923]
Happened on https://github.com/flutter/flutter/pull/93086 - [Internal server logs](https://pantheon.corp.google.com/logs/query;cursorTimestamp=2021-11-19T00:37:26.357Z;query=93086%0Atimestamp%3D%222021-11-19T00:33:07.876Z%22%0AinsertId%3D%221l63a67f4lm6cb%22;timeRange=2021-11-18T20:41:15.825Z%2F2021-11-19T17:41:15.825200Z?project=flutter-dashboard)

```
#0      Config.generateGithubToken (package:cocoon_service/src/service/config.dart:302:30)
<asynchronous suspension>
#1      Config.createGitHubClient (package:cocoon_service/src/service/config.dart:307:32)
<asynchronous suspension>
#2      GithubChecksUtil._createCheckRun (package:cocoon_service/src/foundation/github_checks_util.dart:126:40)
<asynchronous suspension>
#3      RetryOptions.retry (package:retry/retry.dart:131:16)
<asynchronous suspension>
#4      LuciBuildService._createBuildRequest (package:cocoon_service/src/service/luci_build_service.dart:168:40)
<asynchronous suspension>
#5      Future.wait.<anonymous closure> (dart:async/future.dart:473:21)
<asynchronous suspension>
#6      LuciBuildService._scheduleTryBuilds (package:cocoon_service/src/service/luci_build_service.dart:281:36)
<asynchronous suspension>
#7      LuciBuildService.scheduleTryBuilds (package:cocoon_service/src/service/luci_build_service.dart:214:36)
<asynchronous suspension>
#8      Scheduler.triggerPresubmitTargets (package:cocoon_service/src/service/scheduler.dart:268:7)
<asynchronous suspension>
#9      GithubWebhook._scheduleIfMergeable (package:cocoon_service/src/request_handlers/github_webhook.dart:163:5)
<asynchronous suspension>
#10     GithubWebhook._handlePullRequest (package:cocoon_service/src/request_handlers/github_webhook.dart:125:9)
<asynchronous suspension>
#11     GithubWebhook.post (package:cocoon_service/src/request_handlers/github_webhook.dart:66:11)
<asynchronous suspension>
#12     RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:49:22)
<asynchronous suspension>
#13     main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:255:9)
```

**Comment by CaseyHillers** [comment]
In general, ci.yaml check should be retrying in several places (like to get the config in case the network bytes come back malformed). I'm not sure we want to retry authing with github.

**Comment by Hixie** [comment]
happened again, same PR: https://github.com/flutter/flutter/pull/93086/checks?check_run_id=4268784341

**Comment by CaseyHillers** [comment]
Another PR https://github.com/flutter/flutter/pull/93427

**Comment by CaseyHillers** [comment]
This started to flake in the past 24 hours
