### ISSUE TITLE
`flutter` does not like it when you're offline

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#9393]
I had done a git pull --rebase in my flutter checkout but then lost my network connection before using `flutter run`.  This may not affect users as much since `flutter upgrade` is how they typically would update their copy of flutter.

```
Building flutter tool...
Downloading package sky_engine...                         

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Failed to send crash report due to a network error: SocketException: Failed host lookup: 'clients2.google.com' (OS Error: nodename nor servname provided, or not known, errno = 8)
Crash report written to /src/flutter/examples/stocks/flutter_02.log;
please let us know at https://github.com/flutter/flutter/issues.
```

flutter_02.log:

## command

flutter run

## exception

SocketException: SocketException: Failed host lookup: 'storage.googleapis.com' (OS Error: nodename nor servname provided, or not known, errno = 8)

```
#0      fetchUrl (package:flutter_tools/src/base/net.dart:18)
<asynchronous suspension>
#1      Cache._downloadFileToCache (package:flutter_tools/src/cache.dart:207)
<asynchronous suspension>
#2      FlutterEngine._downloadItem (package:flutter_tools/src/cache.dart:389)
#3      FlutterEngine.download (package:flutter_tools/src/cache.dart:351)
<asynchronous suspension>
#4      Cache.updateAll (package:flutter_tools/src/cache.dart:197)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:140)
<asynchronous suspension>
#6      RunCommand.verifyThenRunCommand (package:flutter_tools/src/commands/run.dart:205)
<asynchronous suspension>
#7      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:121)
#8      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:262)
<asynchronous suspension>
#10     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#11     Future.Future.sync (dart:async/future.dart:208)
#12     CommandRunner.run (package:args/command_runner.dart:109)
#13     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:157)
#14     run.<anonymous closure> (package:flutter_tools/executable.dart:140)
<asynchronous suspension>
#15     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#16     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#17     _rootRun (dart:async/zone.dart:1120)
#18     _CustomZone.run (dart:async/zone.dart:1001)
#19     runZoned (dart:async/zone.dart:1465)
#20     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#21     run (package:flutter_tools/executable.dart:113)
<asynchronous suspension>
#22     main (package:flutter_tools/executable.dart:66)
<asynchronous suspension>
#23     main (file:///src/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#24     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

## flutter doctor

```
[✓] Flutter (on Mac OS X 10.12.4 16E195, channel master)
    • Flutter at /src/flutter
    • Framework revision 54e3da5d69 (6 months ago), 2016-10-19 16:17:55 -0700
    • Engine revision 5c4e20c4c5
    • Tools Dart version 1.23.0-dev.11.6

[✓] Host Executable Compatibility
    • Downloaded executables execute on host

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/eseidel/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • ANDROID_HOME = /Users/eseidel/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.0

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1.1)
    • Dart plugin version 171.4073.40
    • Flutter plugin version 12.1

[✓] Connected devices
    • iPhone 6s • FF0E5127-3490-4297-9313-C4776D7950D4 • ios • iOS 10.0 (simulator)

```

**Comment by branflake2267** [comment]
I noticed a flutter plugin can not be created when offline.

**Comment by rock3r** [comment]
I was trying to work on the Flutter framework yesterday while flying and I couldn't even run tests offline, even though there should've been a cached version of everything since I had worked on the same code/branch already:

![image](https://user-images.githubusercontent.com/153802/32506707-2ebeab00-c3dd-11e7-839a-92bbf141ac99.png)

**Comment by sethladd** [comment]
Thanks for the report!

cc @devoncarew @mit-mit

**Comment by filiph** [comment]
This is something for which we need a workaround or fix for the I/O interactive exhibit. 

The workaround doesn't have to be pretty.

**Comment by mit-mit** [comment]
We are planning on doing https://github.com/flutter/flutter/issues/15717. Closing his as 15717 should cover it (if not, reactivate explaining why not)
