### ISSUE TITLE
MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider)

### ISSUE THREAD

**Issue by Cnikhil7** [flutter/flutter#93968]
Reproducible bug repo at :  https://github.com/Cnikhil7/samples/tree/master/add_to_app/fullscreen
Forked from https://github.com/flutter/samples/tree/master/add_to_app/fullscreen

I'm following the flutter add_to_app/fullscreen sample to include a flutter module into existing projects. 
I've added path_provider as a dependency.

What Doesn't work : 
- When flutter activity is launched from native iOS I'm receiving the error posted below.

What's Working :
- Flutter run works in both iOS and Android simulators in flutter_module.
- FlutterActivity launched from native Android is also working.

```
Error : 2021-11-20 17:03:07.978331+0530 IOSFullScreen[21925:142965] Metal API Validation Enabled
2021-11-20 17:03:08.003637+0530 IOSFullScreen[21925:142965] Writing analzed variants.
2021-11-20 17:03:08.047793+0530 IOSFullScreen[21925:143147] flutter: Observatory listening on http://127.0.0.1:56244/yiQtMamZ4VU=/
2021-11-20 17:03:08.218824+0530 IOSFullScreen[21925:143130] [VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
<asynchronous suspension>
#1      getTemporaryDirectory (package:path_provider/path_provider.dart:78:24)
<asynchronous suspension>
#2      main (package:flutter_module/main.dart:20:3)
<asynchronous suspension>

```

## Steps to Reproduce

1. Please checkout https://github.com/Cnikhil7/samples/tree/master/add_to_app/fullscreen forked from flutter/samples
2. then
```

  cd samples/add_to_app/fullscreen/flutter_module/
  flutter pub get

  # For iOS builds:
  cd ../ios_fullscreen
  pod install
  open IOSFullScreen.xcworkspace
  select iOS device and run app from Xcode
  click 'launch flutter viewController' when app runs.


```
 

**Expected results:**  getTemporaryDirectory() to return the directory

**Actual results:**  MissingPluginException

<details>
<summary>Code sample</summary>

1. main.dart

```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:path_provider/path_provider.dart';
import 'package:provider/provider.dart';

Future<void> main() async {

  WidgetsFlutterBinding.ensureInitialized();

  final model = CounterModel();

  await getTemporaryDirectory(); // line that breaks <==================

  runApp(
    ChangeNotifierProvider.value(
      value: model,
      child: const MyApp(),
    ),
  );
}

class CounterModel extends ChangeNotifier {
  CounterModel() {
    _channel.setMethodCallHandler(_handleMessage);
    _channel.invokeMethod<void>('requestCounter');
  }

  final _channel = const MethodChannel('dev.flutter.example/counter');

  int _count = 0;

  int get count => _count;

  void increment() {
    _channel.invokeMethod<void>('incrementCounter');
  }

  Future<dynamic> _handleMessage(MethodCall call) async {
    if (call.method == 'reportCounter') {
      _count = call.arguments as int;
      notifyListeners();
    }
  }
}
class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Module Title',
      routes: {
        '/': (context) => const FullScreenView(),
        '/mini': (context) => const Contents(),
      },
    );
  }
}

class FullScreenView extends StatelessWidget {
  const FullScreenView({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Full-screen Flutter'),
      ),
      body: const Contents(showExit: true),
    );
  }
}
class Contents extends StatelessWidget {
  final bool showExit;

  const Contents({this.showExit = false, Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final mediaInfo = MediaQuery.of(context);

    return SizedBox.expand(
      child: Stack(
        children: [
          Positioned.fill(
            child: DecoratedBox(
              decoration: BoxDecoration(
                color: Theme.of(context).scaffoldBackgroundColor,
              ),
            ),
          ),
          const Positioned.fill(
            child: Opacity(
              opacity: .25,
              child: FittedBox(
                fit: BoxFit.cover,
                child: FlutterLogo(),
              ),
            ),
          ),
          Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Text(
                  'Window is ${mediaInfo.size.width.toStringAsFixed(1)} x '
                  '${mediaInfo.size.height.toStringAsFixed(1)}',
                  style: Theme.of(context).textTheme.headline5,
                ),
                const SizedBox(height: 16),
                Consumer<CounterModel>(
                  builder: (context, model, child) {
                    return Text(
                      'Taps: ${model.count}',
                      style: Theme.of(context).textTheme.headline5,
                    );
                  },
                ),
                const SizedBox(height: 16),
                Consumer<CounterModel>(
                  builder: (context, model, child) {
                    return ElevatedButton(
                      onPressed: () => model.increment(),
                      child: const Text('Tap me!'),
                    );
                  },
                ),
                if (showExit) ...[
                  const SizedBox(height: 16),
                  ElevatedButton(
                    onPressed: () => SystemNavigator.pop(animated: true),
                    child: const Text('Exit this screen'),
                  ),
                ],
              ],
            ),
          ),
        ],
      ),
    );
  }
}

```

2. pubspec.yaml... 

```
name: flutter_module
description: An example Flutter module.

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.7
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  espresso: ^0.1.0+2
  flutter_lints: ^1.0.3

flutter:
  uses-material-design: true

  # This section identifies your Flutter project as a module meant for
  # embedding in a native host app.  These identifiers should _not_ ordinarily
  # be changed after generation - they are used to ensure that the tooling can
  # maintain consistency when adding or modifying assets and plugins.
  # They also do not have any bearing on your native host application's
  # identifiers, which may be completely independent or the same as these.
  module:
    androidX: true
    androidPackage: dev.flutter.example.flutter_module
    iosBundleIdentifier: dev.flutter.example.flutterModule

```

3. app delegate.swift

```
import UIKit
import Flutter

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {
    var window: UIWindow?

    var flutterEngine : FlutterEngine?

    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        // Instantiate Flutter engine
        self.flutterEngine = FlutterEngine(name: "io.flutter", project: nil)
        self.flutterEngine?.run(withEntrypoint: nil)

        return true
    }
}

```

4 viewcontroller.swift

```
import UIKit
import Flutter

class ViewController: UIViewController {

    @IBOutlet weak var counterLabel: UILabel!

    var methodChannel : FlutterMethodChannel?
    var count = 0

    override func viewDidLoad() {
        super.viewDidLoad()

        if let flutterEngine = (UIApplication.shared.delegate as? AppDelegate)?.flutterEngine {
            methodChannel = FlutterMethodChannel(name: "dev.flutter.example/counter",
                                                 binaryMessenger: flutterEngine.binaryMessenger)
            methodChannel?.setMethodCallHandler({ [weak self]
                (call: FlutterMethodCall, result: @escaping FlutterResult) -> Void in
                if let strongSelf = self {
                    switch(call.method) {
                    case "incrementCounter":
                        strongSelf.count += 1
                        strongSelf.counterLabel.text = "Current counter: \(strongSelf.count)"
                        strongSelf.reportCounter()
                    case "requestCounter":
                        strongSelf.reportCounter()
                    default:
                        // Unrecognized method name
                        print("Unrecognized method name: \(call.method)")
                    }
                }
            })
        }
    }

    func reportCounter() {
        methodChannel?.invokeMethod("reportCounter", arguments: count)
    }

    @IBAction func buttonWasTapped(_ sender: Any) {
        if let flutterEngine = (UIApplication.shared.delegate as? AppDelegate)?.flutterEngine {
            let flutterViewController = FlutterViewController(engine: flutterEngine, nibName: nil, bundle: nil)
            self.present(flutterViewController, animated: true, completion: nil)
        }
    }
}

```

</details>

<details>
  <summary>Logs</summary>

```

Error : 2021-11-20 17:03:07.978331+0530 IOSFullScreen[21925:142965] Metal API Validation Enabled
2021-11-20 17:03:08.003637+0530 IOSFullScreen[21925:142965] Writing analzed variants.
2021-11-20 17:03:08.047793+0530 IOSFullScreen[21925:143147] flutter: Observatory listening on http://127.0.0.1:56244/yiQtMamZ4VU=/
2021-11-20 17:03:08.218824+0530 IOSFullScreen[21925:143130] [VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
<asynchronous suspension>
#1      getTemporaryDirectory (package:path_provider/path_provider.dart:78:24)
<asynchronous suspension>
#2      main (package:flutter_module/main.dart:20:3)
<asynchronous suspension>

```

```
Analyzing flutter_module...                                             
No issues found! (ran in 1.8s)

```

```

✓] Flutter (Channel beta, 2.8.0-3.2.pre, on macOS 12.0.1 21A559 darwin-arm, locale en-IN)
    • Flutter version 2.8.0-3.2.pre at /Users/mac/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2901cd7208 (2 days ago), 2021-11-18 11:15:09 -0800
    • Engine revision bcc2b7f12c
    • Dart version 2.15.0 (build 2.15.0-268.18.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mac/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[!] Android Studio
    • Android Studio at /Users/mac/Downloads/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2021.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

! Doctor found issues in 1 category.

```

Configuration:

- Xcode Version 13.1 (13A1030d)
- Apple Silicon M1Pro

What I've Tried:

- Using different versions of path_provider
- Flutter switch channel and upgrades on  beta/stable/master. 

</details>

**Comment by danagbemava-nc** [comment]
Hi @Cnikhil7, you need to modify your `AppDelegate.swift` file to include `GeneratedPluginRegistrant` like below. 

Alternatively, you can just clone/fork the add2app plugin sample located here https://github.com/flutter/samples/tree/master/add_to_app/plugin.

Kindly try out either of them and let me know how it goes for you.

<details>
<summary>AppDelegate.swift</summary>

```swift
import UIKit
import Flutter
import FlutterPluginRegistrant

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {
    var window: UIWindow?

    var flutterEngine : FlutterEngine?

    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        // Instantiate Flutter engine
        self.flutterEngine = FlutterEngine(name: "io.flutter", project: nil)
        self.flutterEngine?.run(withEntrypoint: nil)
        
        GeneratedPluginRegistrant.register(with: self.flutterEngine!)
        
        return true
    }
}

```
</details>

Thank you

**Comment by Cnikhil7** [comment]
Hi @danagbemava-nc, Thanks for quick response. I added the `GeneratedPluginRegistrant` and it's working for `path_provider` plugin I was trying to implement.

However when I tried running the repo https://github.com/flutter/samples/tree/master/add_to_app/plugin. This fails for both plugins that are added as example.

```
ld: warning: ignoring file /Users/mac/Library/Developer/Xcode/DerivedData/IOSUsingPlugin-dnrgqtjirrbhxkgilypwbacwykev/Build/Products/Debug-iphonesimulator/sensors_plus/sensors_plus.framework/sensors_plus, building for iOS Simulator-arm64 but attempting to link with file built for iOS Simulator-x86_64
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_FLTSensorsPlusPlugin", referenced from:
      objc-class-ref in FlutterPluginRegistrant(GeneratedPluginRegistrant.o)
```


I found out that this is knows issue as arm64 simulators aren't supported yet. Similar to recently posted #93908 but as per #85642 this should be resolved on master channel ? Are all plugins not supported yet as after updating to latest version of plugins from sample, one stopped giving error?

I'm using workaround for now, would love an update on this before you close this issue. Thanks.

**Comment by danagbemava-nc** [comment]
Hi @Cnikhil7, did you run the sample as is or you updated the dependencies in the flutter project before running the sample?

**Comment by Cnikhil7** [comment]
Hi @danagbemava-nc I first ran it as it is and received error for both plugin in GeneratedPluginRegistrant on iOS. Then I upgraded `url_launcher: ^5.2.5` to `url_launcher: ^6.0.15` and  ` sensors: ^0.4.2` to `sensors: ^2.0.3` then to changed plugin to `sensors_plus: ^1.2.1` due to deprecation notice on 2.0.3 https://pub.dev/packages/sensors/versions/2.0.3.

`url_launcher: ^6.0.15` solved the issue for this plugin. but sensors and sensors_plus stayed. 

Then I excluded architecture arm64 from Xcode. Followed from https://flutter.dev/docs/development/add-to-app/ios/project-setup#apple-silicon-arm64-macs.and ran the project and it worked.

**Comment by danagbemava-nc** [comment]
> this should be resolved on master channel

I believe so, It will probably land in the next stable version

> Are all plugins not supported yet as after updating to latest version of plugins from sample, one stopped giving error?

`sensors_plus` is maintained by the flutter community so there's a chance that the plugin hasn't been updated yet, I can't say for sure. 

For now, there's a chance that the authors may have to do some work to get it supported on the arm64 simulators, but once flutter itself supports it, I don't believe that will be necessary. 

> Then I excluded architecture arm64 from Xcode. Followed from flutter.dev/docs/development/add-to-app/ios/project-setup#apple-silicon-arm64-macs.and ran the project and it worked.

Based on this comment above, I feel it is safe to close the issue. Closing as solved.

Thank you
