### ISSUE TITLE
Flutter web : what is the substitute of dart.io.Socket

### ISSUE THREAD

**Issue by redDwarf03** [flutter/flutter#93970]
With flutter web, how to use import.io.Socket
```
import 'dart:io';
            
Socket _socket;
_socket = await Socket.connect(ip, port);
_socket.listen((data) {
   if (data != null) {
      // Do something
   }, onError: ((error, StackTrace trace) {
      // Do something
   }), onDone: () {
      _socket.destroy();
   }, cancelOnError: false);
}
```

thank you

**Comment by iapicca** [comment]
https://stackoverflow.com/a/60268090/9836706

**Comment by redDwarf03** [comment]
Thank you. 
I add it but I have these messages

```
Uncaught Bad state: Origin is only applicable to schemes http and https: chrome-extension://lckohjicjkiidfncodlnoeggkedbjpbp/
    at Object.d (chrome-extension://lckohjicjkiidfncodlnoeggkedbjpbp/main.dart.js:11809:3)
    at ku.gAE (chrome-extension://lckohjicjkiidfncodlnoeggkedbjpbp/main.dart.js:47912:14)
    at chrome-extension://lckohjicjkiidfncodlnoeggkedbjpbp/main.dart.js:103029:5
    at aW4.a (chrome-extension://lckohjicjkiidfncodlnoeggkedbjpbp/main.dart.js:18866:62)
    at aW4.$2 (chrome-extension://lckohjicjkiidfncodlnoeggkedbjpbp/main.dart.js:44269:14)
    at Object.x (chrome-extension://lckohjicjkiidfncodlnoeggkedbjpbp/main.dart.js:18852:10)
    at arn.hM (chrome-extension://lckohjicjkiidfncodlnoeggkedbjpbp/main.dart.js:103045:10)
    at chrome-extension://lckohjicjkiidfncodlnoeggkedbjpbp/main.dart.js:7675:14
    at aW4.a (chrome-extension://lckohjicjkiidfncodlnoeggkedbjpbp/main.dart.js:18866:62)
    at aW4.$2 (chrome-extension://lckohjicjkiidfncodlnoeggkedbjpbp/main.dart.js:44269:14)

WebSocket connection to 'ws://62.112.10.156:8150/' failed: 
bon @ main.dart.js:29248
```

**Comment by redDwarf03** [comment]
when I catch the exception for 
```_webSocket = HtmlWebSocketChannel.connect('ws://' +
              serverWalletLegacyResponse.ip +
              ':' +
              serverWalletLegacyResponse.port.toString());
```

i have this message: NoSuchMethodError : method not found "e3" on null
