### ISSUE TITLE
[multicast_dns] Unhandled Exception: SocketException

### ISSUE THREAD

**Issue by tomasbaran** [flutter/flutter#94023]
## Steps to Reproduce
I have an app that needs to connect to Philips Hue bridge, so I use [mulitcast_dns](https://pub.dev/packages/multicast_dns) package. I ran my mDNS as I always do (and usually - about 95% it works well) and got this error:
`Unhandled Exception: SocketException: Send failed (OS Error: No route to host, errno = 65), address = 0.0.0.0, port = 5353`What stroke me is the IP address. Why is it 0.0.0.0? It seems something is wrong.

**Expected results:** 
```

flutter: mDNS: 1
flutter: bridgeStatus: BridgeStatus.scanningLocalNetwork, extraNote: mDNS step 1, extraNote2: null
flutter: mDNS: 2: 12; _hue._tcp.local; Philips Hue - 7B1A6F._hue._tcp.local
flutter: bridgeStatus: BridgeStatus.scanningLocalNetwork, extraNote: mDNS step 2, extraNote2: Philips Hue - 7B1A6F._hue._tcp.local
flutter: mDNS: 2: Philips Hue - 7B1A6F
flutter: mDNS: 3: SrvResourceRecord{Philips Hue - 7B1A6F._hue._tcp.local, validUntil: 2021-11-22 12:31:18.367, target: Philips-hue-2.local, port: 443, priority: 0, weight: 0}
flutter: bridgeStatus: BridgeStatus.scanningLocalNetwork, extraNote: mDNS step 3, extraNote2: SrvResourceRecord{Philips Hue - 7B1A6F._hue._tcp.local, validUntil: 2021-11-22 12:31:18.367, target: Philips-hue-2.local, port: 443, priority: 0, weight: 0}
flutter: mDNS: Dart observatory instance found at Philips-hue-2.local:443 for "Philips Hue - 7B1A6F._hue._tcp.local".
flutter: mDNS: 4: Found address (192.168.0.11; 192.168.0.11).
flutter: bridgeStatus: BridgeStatus.scanningLocalNetwork, extraNote: mDNS step 4, extraNote2: address: 192.168.0.11; host: 192.168.0.11
flutter: mDNS: 5: url: https://192.168.0.11/api/0/config
flutter: mDNS: 5: response: {"name":"Philips hue 2","datastoreversion":"113","swversion":"1948086000","apiversion":"1.48.0","mac":"00:17:88:7b:1a:6f","bridgeid":"001788FFFE7B1A6F","factorynew":false,"replacesbridgeid":null,"modelid":"BSB002","starterkitid":""}
flutter: bridgeStatus: BridgeStatus.scanningLocalNetwork, extraNote: mDNS step 5, extraNote2: bridgeResponse: {"name":"Philips hue 2","datastoreversion":"113","swversion":"1948086000","apiversion":"1.48.0","mac":"00:17:88:7b:1a:6f","bridgeid":"001788FFFE7B1A6F","factorynew":false,"replacesbridgeid":null,"modelid":"BSB002","starterkitid":""}
flutter: mDNS: 6: serialNo: 0017887b1a6f
flutter: bridgeStatus: BridgeStatus.scanningLocalNetwork, extraNote: mDNS step 6, extraNote2: ipAddress: https://192.168.0.11/; serialNo: 0017887b1a6f;

```
**Actual results:** 
```

mDNS: 1
flutter: bridgeStatus: BridgeStatus.scanningLocalNetwork, extraNote: mDNS step 1, extraNote2: null
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: SocketException: Send failed (OS Error: No route to host, errno = 65), address = 0.0.0.0, port = 5353
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1142:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2302:15)
#2      MDnsClient.lookup
package:multicast_dns/multicast_dns.dart:221
#3      BridgeData.scanLocalNetwork
package:ambee2/…/lights/bridge_data.dart:299
<asynchronous suspension>
#4      BridgeData.confirmBridgeConnection
package:ambee2/…/lights/bridge_data.dart:157
<asynchronous suspension>
[connection] nw_resolver_start_query_timer_block_invoke [C5] Query fired: did not receive all answers in time for app-measurement.com:443
[connection] nw_resolver_start_query_timer_block_invoke [C6] Query fired: did not receive all answers in time for firebaseinstallations.googleapis.com:443
flutter: bridgeStatus: BridgeStatus.scanningLocalNetwork, extraNote: mDNS step 7, extraNote2: discoveredBridge: false
flutter: mDNS: 99


```

<details>
<summary>Code sample</summary>

```dart
await client.start();
    print('mDNS: 1');
    // Get the PTR record for the service.
    await for (final PtrResourceRecord ptr in client.lookup<PtrResourceRecord>(ResourceRecordQuery.serverPointer(bonjourServiceName),
        timeout: Duration(seconds: searchForBridgeTimeWindow))) {
      print('mDNS: 2: ${ptr.resourceRecordType}; ${ptr.name}; ${ptr.domainName}');
      String bridgeId = ptr.domainName.substring(0, 20);
      print('mDNS: 2: $bridgeId');

      // Use the domainName from the PTR record to get the SRV record,
      // which will have the port and local hostname.
      // Note that duplicate messages may come through, especially if any
      // other mDNS queries are running elsewhere on the machine.
      await for (final SrvResourceRecord srv in client.lookup<SrvResourceRecord>(ResourceRecordQuery.service(ptr.domainName))) {
        print('mDNS: 3: $srv');
        // Domain name will be something like "io.flutter.example@some-iphone.local._dartobservatory._tcp.local"
        final String bundleId = ptr.domainName; //.substring(0, ptr.domainName.indexOf('@'));
        print('mDNS: Dart observatory instance found at '
            '${srv.target}:${srv.port} for "$bundleId".');
        hostname = srv.target;

        await for (final IPAddressResourceRecord record in client.lookup<IPAddressResourceRecord>(ResourceRecordQuery.addressIPv4(hostname))) {
          print('mDNS: 4: Found address (${record.address.address}; ${record.address.host}).');
          String ipAddress = 'https://' + record.address.address.toString() + '/';
          url = ipAddress + 'api/0/config';
          print('mDNS: 5: url: $url');
          String bridgeResponse = await getResponse(url);
          print('mDNS: 5: response: $bridgeResponse');
          Map jsonResponse = jsonDecode(bridgeResponse);
          String serialNo = jsonResponse['mac'].toString().replaceAll(RegExp(":"), "");
          print('mDNS: 6: serialNo: $serialNo');
        }
      }
    }

    client.stop();

    print('mDNS: 99');
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.5.2 20G95 darwin-arm, locale
    en-US)
    • Flutter version 2.5.3 at /Users/tomasbaran/code/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (5 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/tomasbaran/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (3 available)
    • iPhone (mobile)    • 00008020-000415840E50003A            • ios
      • iOS 15.1 19B74
    • iPhone 13 (mobile) • 2E82BA27-306B-4011-B9A3-265D4732604D • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 95.0.4638.69

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @tomasbaran, is a "Philips Hue bridge" necessary for the reproduction of this issue?

**Comment by tomasbaran** [comment]
@danagbemava-nc good question however I'm not sure. It would be definitely better but is it necessary? I'd say most likely not since the error popped out even before it could find the bridge (in other words before the step in the log:  `mDNS: 2`)

I also tried running it without the Bridge plugged in and it seems it has no effect on the Exception. Currently, I get no exception. I only get this from the console:

```
flutter: mDNS: 1
flutter: bridgeStatus: BridgeStatus.scanningLocalNetwork, extraNote: mDNS step 1, extraNote2: null
```

**Comment by danagbemava-nc** [comment]
Hi @tomasbaran, it appears that your sample is incomplete. 

There are certain classes and methods that I do not have access to, so I cannot test your sample.

Kindly update your sample. 

Thank you

**Comment by tomasbaran** [comment]
@danagbemava-nc I just did. Please, take a look if it's okay now.

**Comment by danagbemava-nc** [comment]
Hi @tomasbaran, there are still a couple of variables missing

<img width="1354" alt="Screenshot 2021-11-26 at 06 06 35" src="https://user-images.githubusercontent.com/88313112/143534736-1c126db8-0b6e-4eb1-9e31-ef16038b9383.png">
