### ISSUE TITLE
[Windows] Failed to launch browser. Make sure you are using an up-to-date Chrome or Edge

### ISSUE THREAD

**Issue by Flickerko** [flutter/flutter#94070]
## Steps to Reproduce

1. Execute `flutter run` on the code sample - I'm trying to run it on default new Flutter Demo project 
2. Same result whether I run it from Android Studio top bar, AS Terminal with `flutter run -d chrome` or -d edge command or navigate to project folder through Command Prompt and try to run from there. 
3. ... 

**Expected results:** 
Application in web browser.

**Actual results:** 
 **Flutter error in Android Studio** (or Command prompt): Failed to launch browser. Make sure you are using an up-to-date Chrome or Edge. Otherwise, consider using -d web-server instead and filing an issue at https://github.com/flutter/flutter/issues.

**What I've tried and didn't work:**

- Restarting Android Studio, PC, clearing AS cache.
- Checking if both browsers are up to date ->they were.
- Switching to Beta channel, running upgrade, enable-web
- `flutter run --release`
- Turning off IPv6 or trying to add chrome as exception in ESET antivirus protection (https://www.youtube.com/watch?v=7OmhNcrdijY&t=13s&ab_channel=WebDevelopment) - not sure if successfully or if it can really cause this type of problem.
- Reading through 10+ Issue reports when this error was reported (mostly between Oct '20 - Feb '21. 

**3-4 localhost windows open in chrome, all stating:**
This site can’t be reached
localhost refused to connect.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
flutter doctor -v
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19041.1348], locale en-US)
    • Flutter version 2.5.3 at C:\Projects\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (5 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Flicker\AppData\Local\Android\sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 96.0.4664.45
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 96.0.1054.29

• No issues found!


flutter run -v
[  +67 ms] executing: [C:\Projects\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +77 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 18116933e77adc82f80866c928266a5b4f1ed645
[   +1 ms] executing: [C:\Projects\flutter/] git tag --points-at 18116933e77adc82f80866c928266a5b4f1ed645
[  +68 ms] Exit code 0 from: git tag --points-at 18116933e77adc82f80866c928266a5b4f1ed645
[        ] 2.5.3
[   +9 ms] executing: [C:\Projects\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +141 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[        ] executing: [C:\Projects\flutter/] git ls-remote --get-url origin
[  +44 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +109 ms] executing: [C:\Projects\flutter/] git rev-parse --abbrev-ref HEAD
[  +36 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +67 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +57 ms] executing: C:\Users\Flicker\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +52 ms] List of devices attached
[   +5 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +76 ms] Multiple devices found:
[  +23 ms] Chrome (web) • chrome • web-javascript • Google Chrome 96.0.4664.45
[   +1 ms] Edge (web)   • edge   • web-javascript • Microsoft Edge 96.0.1054.29
[   +1 ms] [1]: Chrome (chrome)
[   +1 ms] [2]: Edge (edge)
[   +1 ms] Please choose one (To quit, press "q/Q")
[        ] : 
[+3262 ms] 1
[  +41 ms] Skipping pub get: version match.
[ +130 ms] Generating C:\Projects\Production\finance\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +84 ms] Launching lib\main.dart on Chrome in debug mode...
[ +118 ms] Updating assets
[  +74 ms] Waiting for connection from debug service on Chrome...
[ +100 ms] <- reset
[   +6 ms] C:\Projects\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\Projects\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\Projects\flutter\bin\cache\flutter_web_sdk/
--incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
C:\Users\Flicker\AppData\Local\Temp\flutter_tools.558cf187\flutter_tool.c4c1700\app.dill --libraries-spec
file:///C:/Projects/flutter/bin/cache/flutter_web_sdk/libraries.json --packages C:\Projects\Production\finance\.dart_tool\package_config.json
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root
C:\Users\Flicker\AppData\Local\Temp\flutter_tools.558cf187\flutter_tools.bf9bc163 --filesystem-scheme org-dartlang-app --initialize-from-dill
build\b1b715402d823b7fd5c2b68d2edcb2ce.cache.dill.track.dill --platform
file:///C:/Projects/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk_sound.dill --sound-null-safety
[   +8 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+15821 ms] Waiting for connection from debug service on Chrome... (completed in 15.9s)
[   +1 ms] Synced 26.2MB.
[        ] <- accept
[        ] Caching compiled dill
[  +52 ms] Failed to launch browser after 3 tries. Command used to launch it: C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
--user-data-dir=C:\Users\Flicker\AppData\Local\Temp\flutter_tools.558cf187\flutter_tools_chrome_device.37fd9de9 --remote-debugging-port=8902
--disable-background-timer-throttling --disable-extensions --disable-popup-blocking --bwsi --no-first-run --no-default-browser-check
--disable-default-apps --disable-translate http://localhost:8887
[   +6 ms] "flutter run" took 19,976ms.
[   +3 ms] Failed to launch browser. Make sure you are using an up-to-date Chrome or Edge. Otherwise, consider using -d web-server instead and filing
an issue at
           https://github.com/flutter/flutter/issues.
[   +2 ms] 
           #0      ChromiumLauncher._spawnChromiumProcess.<anonymous closure> (package:flutter_tools/src/web/chrome.dart:291:13)
           #1      _runUserCode (dart:async/stream_pipe.dart:11:23)
           #2      Stream.firstWhere.<anonymous closure> (dart:async/stream.dart:1338:9)
           #3      _rootRun (dart:async/zone.dart:1420:47)
           #4      _CustomZone.run (dart:async/zone.dart:1328:19)
           #5      _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
           #6      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:394:13)
           #7      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:7)
           #8      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #9      _ForwardingStream._handleDone (dart:async/stream_pipe.dart:99:10)
           #10     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:161:13)
           #11     _rootRun (dart:async/zone.dart:1420:47)
           #12     _CustomZone.run (dart:async/zone.dart:1328:19)
           #13     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
           #14     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:394:13)
           #15     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:7)
           #16     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #17     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
           #18     _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
           #19     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
           #20     _LineSplitterSink.close (dart:convert/line_splitter.dart:135:11)
           #21     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
           #22     _rootRun (dart:async/zone.dart:1420:47)
           #23     _CustomZone.run (dart:async/zone.dart:1328:19)
           #24     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
           #25     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:394:13)
           #26     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:7)
           #27     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #28     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
           #29     _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
           #30     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
           #31     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:305:20)
           #32     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:81:18)
           #33     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
           #34     _rootRun (dart:async/zone.dart:1420:47)
           #35     _CustomZone.run (dart:async/zone.dart:1328:19)
           #36     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
           #37     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:394:13)
           #38     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:7)
           #39     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #40     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:741:19)
           #41     _StreamController._closeUnchecked (dart:async/stream_controller.dart:596:7)
           #42     _StreamController.close (dart:async/stream_controller.dart:589:5)
           #43     _Socket._onData (dart:io-patch/socket_patch.dart:2173:21)
           #44     _rootRunUnary (dart:async/zone.dart:1444:13)
           #45     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
           #46     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
           #47     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
           #48     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
           #49     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
           #50     _StreamController._add (dart:async/stream_controller.dart:607:7)
           #51     _StreamController.add (dart:async/stream_controller.dart:554:5)
           #52     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1709:35)
           #53     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1206:18)
           #54     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
           #55     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
           #56     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
           #57     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
           
           
[ +111 ms] ensureAnalyticsSent: 109ms
[   +8 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1


```

</details>

**Comment by maheshmnj** [comment]
Hi @Flickerko, thanks for filing the issue

> What I've tried and didn't work:
>
Restarting Android Studio, PC, clearing AS cache.
Checking if both browsers are up to date ->they were.
Switching to Beta channel, running upgrade, enable-web
flutter run --release
Turning off IPv6 or trying to add chrome as exception in ESET antivirus protection (https://www.youtube.com/watch?v=7OmhNcrdijY&t=13s&ab_channel=WebDevelopment) - not sure if successfully or if it can really cause this type of problem.
Reading through 10+ Issue reports when this error was reported (mostly between Oct '20 - Feb '21.
 
Can you please try starting a webserver from the command line by running `flutter run -d web-server`  and then check if this works in the browser?

**Comment by Flickerko** [comment]
Hi @maheshmnj, yes running web-server works. Never had problem with that one.

**Comment by maheshmnj** [comment]
Provided you have tried all the above things indicated in the main Post I can't think of any other reason why you might be hitting this issue. Keeping this issue open for further investigation from the team.

**Comment by annagrin** [comment]
Hi @Flickerko, are flutter and chrome running as an administrator by any chance, ie launched from an elevated command prompt? The error reminds me of another issue I’ve seen where a user was running android studio as administrator and running into similar problems. I think the problem was that chrome’s user directory was not accessible to the administrator account in that case. I will try to find that issue and link it here for information later.
