### ISSUE TITLE
 Cannot find executable for pub from dart sdk

### ISSUE THREAD

**Issue by iNoles** [flutter/flutter#9410]
## command

flutter --no-color upgrade

## exception

ArgumentError: Invalid argument(s): Cannot find executable for /flutter/bin/cache/dart-sdk/bin/pub.

```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:115)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:43)
#2      runCommand (package:flutter_tools/src/base/process.dart:107)
<asynchronous suspension>
#3      runCommandAndStreamOutput (package:flutter_tools/src/base/process.dart:126)
<asynchronous suspension>
#4      pubGet (package:flutter_tools/src/dart/pub.dart:55)
<asynchronous suspension>
#5      UpgradeCommand.runCommand (package:flutter_tools/src/commands/upgrade.dart:77)
<asynchronous suspension>
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:151)
<asynchronous suspension>

**Comment by Hixie** [comment]
This is not actionable — it doesn't happen for everyone, but we don't know what exactly is special about this setup to trigger it.

If anyone runs into this, I recommend trying `git clean -xffd; git rebase` followed by `flutter upgrade`.
