### ISSUE TITLE
[iOS] Disconnecting Internet doesn't disconnect socket connection

### ISSUE THREAD

**Issue by MahmoodBakhshayesh** [flutter/flutter#94115]
i have a socket connection in my application 
when i turn off the wifi and therefore the connection is lost noting happens and there is no way to detect disconnecting
this problem is only in ios app in android version the method onDone from socket.listen is called so we know that connection is lost

the following is my function code to connect i even tried to set KeepAlive mode but no changes

```dart
Future<bool> tryConnectSocket() async {
/*Some Ip and Port that  can be connect to */
  String ip = "192.168.9.101"; 
  int port = 35000;

  try {
    late RawSocketOption option ;
    if (Platform.isAndroid) {
      option = RawSocketOption.fromBool(/* SOL_SOCKET */ 0x1, /* SO_KEEPALIVE */ 0x0009, true);
    } else {
      option = RawSocketOption.fromBool(/* SOL_SOCKET */ 0xffff, /* SO_KEEPALIVE */ 0x0008, true);
    }
    Socket s = await Socket.connect(ip, 35000, timeout: const Duration(seconds: 10)).timeout(const Duration(seconds: 10),
        onTimeout: () {
          log("ERROR ON SOCKET TIMEOUT");
          return Socket.connect(ip, port);
        }).catchError((e) {
      log("ERROR ON SOCKET $e");
      return Socket.connect(ip, port);
    }).onError((error, stackTrace) {
      log("ERROR ON SOCKET $error");
      return Socket.connect(ip, port);
    });
    
    s.listen((msg) {}, cancelOnError: false, onError: (e) {
      log("ERROR ON SOCKET $e");
    }, onDone: () {
      log("Socket DONE");
    });
    log("DONE");
    return true;
  } catch (e) {
    log("ERROR ON LISTENING TO SOCKET $e");
    return false;
  }
}
```

**Expected results:**  when i disconnect phone from internet the method onDone should be called and log Socket Done

**Actual results:** in android app work as expected but in IOS nothing happend

<details>
<summary>flutter doctor -v</summary>

```console
 [✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-arm, locale en-CA)
    • Flutter version 2.5.3 at /Library/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (6 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/fps/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (2 available)
    • My’s iPhone (mobile) • 59662ebcb89b7a76ebab58eec2d397eb3d5ac41a • ios            • iOS 14.6 18F72
    • Chrome (web)              • chrome                                   • web-javascript • Google Chrome 96.0.4664.55

• No issues found!
```
</details>

**Comment by MahmoodBakhshayesh** [comment]
I guess it a bug or some IOS limitation because it work just fine on Android

**Comment by danagbemava-nc** [comment]
Hi @MahmoodBakhshayesh, thanks for filing the issue. 

Please provide the output of `flutter doctor -v` and a complete minimal reproducible code sample. 

Thank you

**Comment by MahmoodBakhshayesh** [comment]
Hi @danagbemava-nc , thanks for response 
i added flutter doctor result and i already put the function i use to connect to socket
Thanks

**Comment by danagbemava-nc** [comment]
Hi @MahmoodBakhshayesh, the function alone is not enough to reproduce the issue, how you're using the function also counts, so please provide a complete minimal reproducible code sample. 

Thank you

**Comment by MahmoodBakhshayesh** [comment]
Hi @danagbemava-nc  and thanks again for response
Here is my main.dart file and a way to reproduce code 
just use a valid ip and port for test after connection with ios devices turn off wife you see nothing happens but i android onDone method is called

```
import 'dart:async';
import 'dart:developer';
import 'dart:io';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runZonedGuarded(() {
    runApp(const MyApp());
  }, (error, stackTrace) {
    log('runZonedGuarded:  $error');
  });
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  TextEditingController ipC = TextEditingController(text: "192.168.1.248");
  TextEditingController portC = TextEditingController(text: "35000");

  bool loading = false;
  bool connecting = false;

  Future<bool> tryConnectSocket() async {
    String ip = "192.168.9.101";
    int port = 35000;
    try {
      RawSocketOption option = RawSocketOption.fromBool(/* SOL_SOCKET */ 0xffff, /* SO_KEEPALIVE */ 0x0008, true);
      if (Platform.isAndroid) {
        option = RawSocketOption.fromBool(/* SOL_SOCKET */ 0x1, /* SO_KEEPALIVE */ 0x0009, true);
      } else {
        option = RawSocketOption.fromBool(/* SOL_SOCKET */ 0xffff, /* SO_KEEPALIVE */ 0x0008, true);
      }

      Socket s = await Socket.connect(ip, 35000, timeout: const Duration(seconds: 10)).timeout(const Duration(seconds: 10),
          onTimeout: () {
        log("ERROR ON SOCKET TIMEOUT");
        return Socket.connect(ip, port);
      }).catchError((e) {
        log("ERROR ON SOCKET $e");
        return Socket.connect(ip, port);
      }).onError((error, stackTrace) {
        log("ERROR ON SOCKET $error");
        return Socket.connect(ip, port);
      }).then((value) {
        value.setRawOption(option);
        return value;
      });

      log("DONE");
      s.listen((msg) {}, cancelOnError: false, onError: (e) {
        log("ERROR ON SOCKET $e");
      }, onDone: () {
        log("Socket DONE");
      });
      log("DONE");
      return true;
    } catch (e) {
      log("ERROR ON LISTENING TO SOCKET $e");
      return false;
    }
  }

  @override
  Widget build(BuildContext context) {
    ThemeData theme = Theme.of(context);

    return Scaffold(
      appBar: AppBar(
        title: const Text("APP"),
      ),
      body: Column(
        children: [
          const Divider(),
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 24),
            width: MediaQuery.of(context).size.width,
            color: Colors.white,
            child: Column(
              children: [
                Row(
                  children: [
                    Expanded(
                        flex: 4,
                        child: CupertinoTextField(
                          keyboardType: const TextInputType.numberWithOptions(signed: true, decimal: true),
                          controller: ipC,
                          placeholder: "ip e.g. 192.168.1.7",
                        )),
                    const SizedBox(width: 12),
                    Expanded(
                        flex: 2,
                        child: CupertinoTextField(
                          keyboardType: const TextInputType.numberWithOptions(signed: true),
                          controller: portC,
                          placeholder: "port e.g. 7535",
                        )),
                    const SizedBox(width: 12),
                    TextButton(
                        onPressed: () async {
                          tryConnectSocket().then((value) {
                            print(value);
                          });
                        },
                        child: connecting ? const Text("...") : const Text("Connect")),
                  ],
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
```

**Comment by danagbemava-nc** [comment]
Issue is reproducible using sample provided by OP. 

On `android`, turning off the internet connection instantly throws a `SocketException`, however on `iOS`, nothing happens. 

##  Steps to reproduce
1. Create a socket and establish a connection, I used the socket io sample app to create a local connection.
https://github.com/socketio/chat-example.git
2. Run the dart sample below on both android and ios
3. Toggle off the wifi connection on both devices

Note: The ios device I used doesn't have a mobile data connection, so Wifi is the only internet connection I have.

<details>
<summary>videos</summary>

`android`

https://user-images.githubusercontent.com/88313112/143597906-ce61dc9a-0c40-4467-bd84-39debfaf4618.mov

`iOS`

https://user-images.githubusercontent.com/88313112/143598051-2ef0f6fc-f0ea-4b06-9da3-70f6c97c9050.MP4



</details>

<details>
<summary>updated sample</summary>

```dart
import 'dart:async';
import 'dart:developer';
import 'dart:io';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runZonedGuarded(() {
    runApp(const MyApp());
  }, (error, stackTrace) {
    log('runZonedGuarded:  $error');
  });
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  TextEditingController ipC = TextEditingController(text: "192.168.1.248");
  TextEditingController portC = TextEditingController(text: "35000");

  bool loading = false;
  bool connecting = false;

  String? connectionErrorMessage;

  Future<bool> tryConnectSocket() async {
    setState(() {
      connectionErrorMessage = null;
    });

    String ip = ipC.text;
    int port = int.tryParse(portC.text)!;
    try {
      RawSocketOption option = RawSocketOption.fromBool(
          /* SOL_SOCKET */ 0xffff, /* SO_KEEPALIVE */ 0x0008, true);
      if (Platform.isAndroid) {
        option = RawSocketOption.fromBool(
            /* SOL_SOCKET */ 0x1, /* SO_KEEPALIVE */ 0x0009, true);
      } else {
        option = RawSocketOption.fromBool(
            /* SOL_SOCKET */ 0xffff, /* SO_KEEPALIVE */ 0x0008, true);
      }

      Socket s =
          await Socket.connect(ip, port, timeout: const Duration(seconds: 10))
              .timeout(const Duration(seconds: 10), onTimeout: () {
        log("ERROR ON SOCKET TIMEOUT");
        return Socket.connect(ip, port);
      }).catchError((e) {
        log("ERROR ON SOCKET $e");
        return Socket.connect(ip, port);
      }).onError((error, stackTrace) {
        log("ERROR ON SOCKET $error");
        return Socket.connect(ip, port);
      }).then((value) {
        value.setRawOption(option);
        return value;
      });

      log("DONE");
      s.listen(
          (msg) {
            log("RECEIVED $msg");
          },
          cancelOnError: false,
          onError: (e) {
            log("ERROR ON SOCKET $e");
            connectionErrorMessage = e.toString();
            setState(() {});
          },
          onDone: () {
            log("Socket DONE");
          });
      log("DONE");
      return true;
    } catch (e) {
      log("ERROR ON LISTENING TO SOCKET $e");
      connectionErrorMessage = e.toString();
      setState(() {});

      return false;
    }
  }

  @override
  Widget build(BuildContext context) {
    ThemeData theme = Theme.of(context);

    return Scaffold(
      appBar: AppBar(
        title: const Text("APP"),
      ),
      body: Column(
        children: [
          const Divider(),
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 24),
            width: MediaQuery.of(context).size.width,
            color: Colors.white,
            child: Column(
              children: [
                Row(
                  children: [
                    Expanded(
                        flex: 4,
                        child: CupertinoTextField(
                          keyboardType: const TextInputType.numberWithOptions(
                              signed: true, decimal: true),
                          controller: ipC,
                          placeholder: "ip e.g. 192.168.1.7",
                        )),
                    const SizedBox(width: 12),
                    Expanded(
                        flex: 2,
                        child: CupertinoTextField(
                          keyboardType: const TextInputType.numberWithOptions(
                              signed: true),
                          controller: portC,
                          placeholder: "port e.g. 7535",
                        )),
                    const SizedBox(width: 12),
                    TextButton(
                        onPressed: () async {
                          tryConnectSocket().then((value) {
                            print(value);
                          });
                        },
                        child: connecting
                            ? const Text("...")
                            : const Text("Connect")),
                  ],
                ),
              ],
            ),
          ),
          if (connectionErrorMessage != null) Text(connectionErrorMessage!),
        ],
      ),
    );
  }
}

```
</details>

<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-arm, locale
    en-GB)
    • Flutter version 2.5.3 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (6 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message
      below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle
      (dart:convert-patch/convert_patch.dart:1788:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:318:42)
      #2      InputStream.readString
      (package:archive/src/util/input_stream.dart:199:30)
      #3      new ZipDirectory.read
      (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer
      (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes
      (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml
      (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion
      (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage
      (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate
      (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure>
      (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure>
      (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1428:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1863:10)
      #15     runZonedGuarded (dart:async/zone.dart:1851:12)
      #16     runZoned (dart:async/zone.dart:1782:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks
      (package:flutter_tools/src/doctor.dart:200:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:304:47)
      #20     DoctorCommand.runCommand
      (package:flutter_tools/src/commands/doctor.dart:50:47)
      #21     FlutterCommand.verifyThenRunCommand
      (package:flutter_tools/src/runner/flutter_command.dart:1274:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure>
      (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure>
      (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure>
      (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure>
      (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand
      (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure>
      (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure>
      (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:92:3)
      <asynchronous suspension>


[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (4 available)
    • sdk gphone arm64 (mobile) • emulator-5554             • android-arm64  •
      Android 11 (API 30) (emulator)
    • Nexus’ IPhone (mobile)    • 00008020-001875E83A38002E • ios            •
      iOS 15.0.2 19A404
    • macOS (desktop)           • macos                     • darwin-arm64   •
      macOS 11.6 20G165 darwin-arm
    • Chrome (web)              • chrome                    • web-javascript •
      Google Chrome 96.0.4664.55

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel master, 2.6.0-12.0.pre.837, on macOS 11.6 20G165
    darwin-arm, locale en-GB)
    • Flutter version 2.6.0-12.0.pre.837 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 341e771b12 (2 days ago), 2021-11-24 19:33:04 -0500
    • Engine revision e99aba6a38
    • Dart version 2.16.0 (build 2.16.0-46.0.dev)
    • DevTools version 2.8.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message
      below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle
      (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      InputStream.readString
      (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read
      (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer
      (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes
      (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml
      (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion
      (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage
      (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate
      (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure>
      (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure>
      (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1426:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1861:10)
      #15     runZonedGuarded (dart:async/zone.dart:1849:12)
      #16     runZoned (dart:async/zone.dart:1780:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks
      (package:flutter_tools/src/doctor.dart:198:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:302:47)
      #20     DoctorCommand.runCommand
      (package:flutter_tools/src/commands/doctor.dart:50:48)
      #21     FlutterCommand.verifyThenRunCommand
      (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure>
      (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure>
      (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure>
      (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure>
      (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand
      (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure>
      (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure>
      (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (4 available)
    • sdk gphone arm64 (mobile) • emulator-5554             • android-arm64  •
      Android 11 (API 30) (emulator)
    • Nexus’ IPhone (mobile)    • 00008020-001875E83A38002E • ios            •
      iOS 15.0.2 19A404
    • macOS (desktop)           • macos                     • darwin-arm64   •
      macOS 11.6 20G165 darwin-arm
    • Chrome (web)              • chrome                    • web-javascript •
      Google Chrome 96.0.4664.55

! Doctor found issues in 1 category.
```
</details>

**Comment by jmagman** [comment]
@danagbemava-nc thanks for the work reproducing.  Can you re-file this to https://github.com/dart-lang/sdk/issues ?  Socket code lives in dart, not Flutter.  Unfortunately I don't think the issue can be moved without write permissions in both repos, it can only be copied.

**Comment by danagbemava-nc** [comment]
Issue has been filed https://github.com/dart-lang/sdk/issues/47807. 

@MahmoodBakhshayesh, kindly follow up there. 

Closing from here based on https://github.com/flutter/flutter/issues/94115#issuecomment-981920209. 

Thank you
