### ISSUE TITLE
[tool_crash] StateError: Bad state: Future already completed

### ISSUE THREAD

**Issue by jinjf553** [flutter/flutter#94193]
## Command
```
flutter run --machine --start-paused -d chrome --dart-define=flutter.inspector.structuredErrors=true --web-allow-expose-url --target lib\main.dart -d web-server --web-hostname 127.0.0.1 --web-port 8989 --web-renderer html
```

## Steps to Reproduce

```console
Launching lib\main.dart on Web Server in debug mode...
lib\main.dart:1
Waiting for connection from Dart debug extension at http://127.0.0.1:8989
The web-server device requires the Dart Debug Chrome extension for debugging. Consider using the Chrome or Edge devices for an improved development workflow.
Please click the Dart Debug extension button in the spawned browser window

This app is linked to the debug service: ws://127.0.0.1:58532/QrOhOj4GuR8%3D/ws
Debug service listening on ws://127.0.0.1:58532/QrOhOj4GuR8=/ws
 Running with sound null safety
Connecting to VM Service at ws://127.0.0.1:58532/QrOhOj4GuR8=/ws
Error running hot-reload: app '939de10a-0c93-47be-8442-906402e2d07c' not found
Failed to send crash report due to a network error: SocketException: OS Error: 信号灯超时时间已到
, errno = 121, address = clients2.google.com, port = 58539
Oops; flutter has exited unexpectedly: "Bad state: Future already completed".
A crash report has been written to D:\jinjf\code\flu\flutter_01.log.
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+Bad+state%3A+Future+already+completed
To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports
Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
```

## Logs
StateError: Bad state: Future already completed
```
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:45:31)
#1      WebDevFS.connect.<anonymous closure> (package:flutter_tools/src/isolated/devfs_web.dart:691:16)
<asynchronous suspension>
```

```
[✓] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19041.1237], locale zh-CN)
    • Flutter version 2.5.3 at C:\Program Files\software\flutter
    • Upstream repository https://mirrors.tuna.tsinghua.edu.cn/git/flutter-sdk.git
    • Framework revision 18116933e7 (6 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4
    • Pub download mirror https://mirrors.tuna.tsinghua.edu.cn/dart-pub
    • Flutter download mirror https://mirrors.tuna.tsinghua.edu.cn/flutter

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\jWX1069279\Downloads\android-sdk_r24.4.1-windows\android-sdk_r24.4.1-windows\android-sdk-windows
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Stu

**Comment by danagbemava-nc** [comment]
Hi @jinjf553, the output of `flutter doctor -v` appears to be incomplete, kindly update your initial post with the complete `flutter doctor -v`. 

Kindly share the crash log in `D:\jinjf\code\flu\flutter_01.log` as well.

Thank you
