### ISSUE TITLE
Dismissible doesn't work. 

### ISSUE THREAD

**Issue by saurabhdhingra** [flutter/flutter#94240]
I have written this code by following the Flutter documentation cookbook but still I am getting this error when I go to another screen and comeback (Navigator.pop) This is my code -
<img width="481" alt="Screenshot 2021-11-26 at 4 25 27 PM" src="https://user-images.githubusercontent.com/75309640/143570409-cb54cc68-657c-4b23-8069-f0fc9f252c90.png">
And this is my error 
![Simulator Screen Shot - iPhone 13 - 2021-11-26 at 16 24 46](https://user-images.githubusercontent.com/75309640/143570519-9c084379-2612-4fe0-91cc-0433efb5c22e.png)
-

**Comment by danagbemava-nc** [comment]
Hi @saurabhdhingra,

Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Do not post screenshots of the code, copy and paste the code sample here.

Thank you

**Comment by saurabhdhingra** [comment]
Hi @danagbemava-nc 
Thanks for replying. Sorry for posting my issue like this. 
Here's my  `flutter doctor -v` log -
```
saurabhdhingra@Saurabhs-Mac brawnly % flutter doctor -v
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-arm, locale en-IN)
    • Flutter version 2.5.3 at /usr/local/Caskroom/flutter/2.2.3/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (6 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/saurabhdhingra/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • 4964DD09-41F3-4904-BA07-05958FC3E6E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 12.0.1 21A559 darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 96.0.4664.55

! Doctor found issues in 1 category.
```

And here's my  minimal complete reproducible code sample -
db.dart
```
import 'dart:io';
import 'package:path/path.dart';
import 'package:path_provider/path_provider.dart';
import 'package:sqflite/sqflite.dart';

class DatabaseHelper {
  static const _dbName = 'myDatabase.db';
  static const _dbVersion = 1;
  static const _table = 'myTable';
  static const colField1 = 'field1';
  static const colField2 = 'field2';

  static final DatabaseHelper instance = DatabaseHelper._init();
  DatabaseHelper._init();

  static Database? _database;
  Future<Database> get database async {
    if (_database != null) return _database!;

    _database = await _initiateDatabase();
    return _database!;
  }

  _initiateDatabase() async {
    Directory directory = await getApplicationDocumentsDirectory();
    String path = join(directory.path, _dbName);
    return await openDatabase(path, version: _dbVersion, onCreate: _onCreate);
  }

  Future _onCreate(Database db, int version) async {
    await db.execute('''CREATE TABLE $_table( 
    $colField1 TEXT,
    $colField2 TEXT)''');
    await db.insert(
      _table,
      {colField1: 'Data1', colField2: 'Data2'},
    );
  }

  Future<List<Map<String, dynamic>>> queryAll() async {
    Database db = await instance.database;
    List<Map<String, dynamic>> item = await db.query(_table);
    return item;
  }

  Future<int> delete(String data) async {
    Database db = await instance.database;
    String dataField2 = 'Data2';
    return await db.delete(_table,
        where: 'colField1 = ? AND colField2 = ?',
        whereArgs: [data, dataField2]);
  }
}


```

home.dart
```
import 'package:flutter/material.dart';
import 'package:github/db.dart';

class Home extends StatefulWidget {
  const Home({Key? key}) : super(key: key);

  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  late List<Map<String, dynamic>> data;
  bool isLoading = false;

  @override
  void initState() {
    super.initState();
    checkData();
  }

  Future checkData() async {
    setState(() {
      isLoading = true;
    });
    List<Map<String, dynamic>> data = await DatabaseHelper.instance.queryAll();
    this.data = data;
    setState(() {
      isLoading = false;
    });
  }

  @override
  Widget build(BuildContext context) {
    return isLoading
        ? const Center(
            child: CircularProgressIndicator(
              color: Color(0xFF403F3C),
            ),
          )
        : Scaffold(
            appBar: AppBar(),
            body: SafeArea(
              child: ListView.builder(
                itemCount: data.length,
                itemBuilder: (context, i) {
                  final item = data[i];
                  return Center(
                    child: Dismissible(
                      background: Container(
                          color: Colors.red, child: const Icon(Icons.delete)),
                      key: Key(item['field1']),
                      direction: DismissDirection.endToStart,
                      onDismissed: (direction) async {
                        setState(() {
                          data.removeAt(i);
                        });
                        await DatabaseHelper.instance.delete(item['']);
                      },
                      child: ListTile(
                          title: Text(data[i]['field1']),
                          subtitle: Text(data[i]['field2'])),
                    ),
                  );
                },
              ),
            ),
          );
  }
}

```

And here's my `flutter run --verbose` log
```
[+9103 ms] [VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: Unsupported operation: read-only
                    #0      QueryResultSet.length= (package:sqflite_common/src/collection_utils.dart:109:5)
                    #1      ListMixin._closeGap (dart:collection/list.dart:312:10)
                    #2      ListMixin.removeAt (dart:collection/list.dart:539:5)
                    #3      _GithubIssueState.build.<anonymous closure>.<anonymous closure>.<anonymous
closure> (package:github/github.dart:55:32)
                    #4      State.setState (package:flutter/src/widgets/framework.dart:1088:30)
                    #5      _GithubIssueState.build.<anonymous closure>.<anonymous closure>
(package:github/github.dart:54:25)
                    #6      _GithubIssueState.build.<anonymous closure>.<anonymous closure>
(package:github/github.dart:53:36)
                    #7      _DismissibleState._handleResizeProgressChanged
(package:flutter/src/widgets/dismissible.dart:547:27)
                    #8      AnimationLocalListenersMixin.notifyListeners
(package:flutter/src/animation/listener_helpers.dart:155:19)
                    #9      AnimationController._tick (package:flutter/src/animation/animation_<…>
```

**Comment by danagbemava-nc** [comment]
The error you message in your post above points to an error in the `sqflite` package. 
For this to be addressed as an actual issue with the `Dismissible` widget, kindly provide a sample that doesn't include any third-party packages. 

Thank you

**Comment by saurabhdhingra** [comment]
Ok, thanks.
