### ISSUE TITLE
[Android][webview_flutter] App crashes with `PlatformException(error, java.lang.IllegalStateException: Trying to create a platform view of unregistered type: plugins.flutter.io/webview`

### ISSUE THREAD

**Issue by AlekseyMelikov** [flutter/flutter#94247]
I am trying to run the example from the [flutter webview documentation](https://pub.flutter-io.cn/packages/webview_flutter)

```dart
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  runApp(WebViewExample());
}

class WebViewExample extends StatefulWidget {
  @override
  WebViewExampleState createState() => WebViewExampleState();
}

class WebViewExampleState extends State<WebViewExample> {
  @override
  void initState() {
    super.initState();
    // Enable hybrid composition.
    if (Platform.isAndroid) WebView.platform = SurfaceAndroidWebView();
  }

  @override
  Widget build(BuildContext context) {
    return WebView(
      initialUrl: 'https://flutter.dev',
    );
  }
}

```

but I get an error
```console
$ flutter run
Using hardware rendering with device sdk gphone x86 64. If you notice graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on sdk gphone x86 64 in debug mode...
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Running Gradle task 'assembleDebug'...                              4.5s
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
W/FlutterActivityAndFragmentDelegate( 8108): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
E/flutter ( 8108): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 8108): #0      WebViewHostApi.create (package:webview_flutter_android/src/android_webview.pigeon.dart:89:7)
E/flutter ( 8108): <asynchronous suspension>
E/flutter ( 8108): 
E/flutter ( 8108): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 8108): #0      WebSettingsHostApi.create (package:webview_flutter_android/src/android_webview.pigeon.dart:672:7)
E/flutter ( 8108): <asynchronous suspension>
E/flutter ( 8108): 
E/flutter ( 8108): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 8108): #0      WebSettingsHostApi.setDomStorageEnabled (package:webview_flutter_android/src/android_webview.pigeon.dart:722:7)
E/flutter ( 8108): <asynchronous suspension>
E/flutter ( 8108): 
E/flutter ( 8108): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 8108): #0      WebSettingsHostApi.setJavaScriptCanOpenWindowsAutomatically (package:webview_flutter_android/src/android_webview.pigeon.dart:749:7)
E/flutter ( 8108): <asynchronous suspension>
E/flutter ( 8108): 
E/flutter ( 8108): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 8108): #0      WebSettingsHostApi.setSupportMultipleWindows (package:webview_flutter_android/src/android_webview.pigeon.dart:776:7)
E/flutter ( 8108): <asynchronous suspension>
E/flutter ( 8108): 
E/flutter ( 8108): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 8108): #0      WebSettingsHostApi.setLoadWithOverviewMode (package:webview_flutter_android/src/android_webview.pigeon.dart:906:7)
E/flutter ( 8108): <asynchronous suspension>
E/flutter ( 8108): 
E/flutter ( 8108): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 8108): #0      WebSettingsHostApi.setUseWideViewPort (package:webview_flutter_android/src/android_webview.pigeon.dart:931:7)
E/flutter ( 8108): <asynchronous suspension>
E/flutter ( 8108): 
E/flutter ( 8108): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 8108): #0      WebSettingsHostApi.setDisplayZoomControls (package:webview_flutter_android/src/android_webview.pigeon.dart:957:7)
E/flutter ( 8108): <asynchronous suspension>
E/flutter ( 8108): 
E/flutter ( 8108): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 8108): #0      WebSettingsHostApi.setBuiltInZoomControls (package:webview_flutter_android/src/android_webview.pigeon.dart:983:7)
E/flutter ( 8108): <asynchronous suspension>
E/flutter ( 8108): 
E/flutter ( 8108): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 8108): #0      WebViewClientHostApi.create (package:webview_flutter_android/src/android_webview.pigeon.dart:1124:7)
E/flutter ( 8108): <asynchronous suspension>
E/flutter ( 8108): 
E/flutter ( 8108): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 8108): #0      WebSettingsHostApi.setUserAgentString (package:webview_flutter_android/src/android_webview.pigeon.dart:828:7)
E/flutter ( 8108): <asynchronous suspension>
E/flutter ( 8108): #1      Future.wait.<anonymous closure> (dart:async/future.dart)
E/flutter ( 8108): <asynchronous suspension>
E/flutter ( 8108): #2      WebViewAndroidPlatformController.updateSettings (package:webview_flutter_android/webview_android_widget.dart:182:5)
E/flutter ( 8108): <asynchronous suspension>
E/flutter ( 8108): 
E/flutter ( 8108): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 8108): #0      WebSettingsHostApi.setMediaPlaybackRequiresUserGesture (package:webview_flutter_android/src/android_webview.pigeon.dart:855:7)
E/flutter ( 8108): <asynchronous suspension>
E/flutter ( 8108): 
E/flutter ( 8108): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 8108): #0      DownloadListenerHostApi.create (package:webview_flutter_android/src/android_webview.pigeon.dart:1398:7)
E/flutter ( 8108): <asynchronous suspension>
E/flutter ( 8108): 
E/flutter ( 8108): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 8108): #0      WebViewHostApi.setDownloadListener (package:webview_flutter_android/src/android_webview.pigeon.dart:603:7)
E/flutter ( 8108): <asynchronous suspension>
E/flutter ( 8108): 
E/flutter ( 8108): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 8108): #0      WebChromeClientHostApi.create (package:webview_flutter_android/src/android_webview.pigeon.dart:1511:7)
E/flutter ( 8108): <asynchronous suspension>
E/flutter ( 8108): 
E/flutter ( 8108): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 8108): #0      WebViewHostApi.setWebChromeClient (package:webview_flutter_android/src/android_webview.pigeon.dart:630:7)
E/flutter ( 8108): <asynchronous suspension>
E/flutter ( 8108): 
E/flutter ( 8108): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 8108): #0      WebViewHostApi.loadUrl (package:webview_flutter_android/src/android_webview.pigeon.dart:141:7)
E/flutter ( 8108): <asynchronous suspension>
E/flutter ( 8108): 
E/flutter ( 8108): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to create a platform view of unregistered type: plugins.flutter.io/webview
E/flutter ( 8108):      at io.flutter.plugin.platform.PlatformViewsController$1.createAndroidViewForPlatformView(PlatformViewsController.java:142)
E/flutter ( 8108):      at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:104)
E/flutter ( 8108):      at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
E/flutter ( 8108):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter ( 8108):      at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/flutter ( 8108):      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
E/flutter ( 8108):      at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter ( 8108):      at android.os.MessageQueue.next(MessageQueue.java:335)
E/flutter ( 8108):      at android.os.Looper.loop(Looper.java:183)
E/flutter ( 8108):      at android.app.ActivityThread.main(ActivityThread.java:7656)
E/flutter ( 8108):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 8108):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/flutter ( 8108):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter ( 8108): , null, null)
E/flutter ( 8108): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter ( 8108): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter ( 8108): <asynchronous suspension>
E/flutter ( 8108): #2      AndroidViewController.create (package:flutter/src/services/platform_views.dart:771:5)
E/flutter ( 8108): <asynchronous suspension>
E/flutter ( 8108):
```
and I see a black screen in the Android Emulator.

More details:

```console
$ flutter --version
Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 18116933e7 (6 weeks ago) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4
```

```console
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on Debian GNU/Linux 11 (bullseye) 5.14.0-2-amd64, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[!] Android Studio (not installed)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories
```

pubspec.yaml
```yaml
...
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  webview_flutter: ^2.3.1
...
```

pubspec.lock
```lock
# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  async:
    dependency: transitive
    description:
      name: async
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.8.1"
  boolean_selector:
    dependency: transitive
    description:
      name: boolean_selector
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
  characters:
    dependency: transitive
    description:
      name: characters
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  charcode:
    dependency: transitive
    description:
      name: charcode
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.1"
  clock:
    dependency: transitive
    description:
      name: clock
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  collection:
    dependency: transitive
    description:
      name: collection
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.15.0"
  cupertino_icons:
    dependency: "direct main"
    description:
      name: cupertino_icons
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.4"
  fake_async:
    dependency: transitive
    description:
      name: fake_async
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.0"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_lints:
    dependency: "direct dev"
    description:
      name: flutter_lints
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.4"
  flutter_test:
    dependency: "direct dev"
    description: flutter
    source: sdk
    version: "0.0.0"
  lints:
    dependency: transitive
    description:
      name: lints
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.1"
  matcher:
    dependency: transitive
    description:
      name: matcher
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.12.10"
  meta:
    dependency: transitive
    description:
      name: meta
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.7.0"
  path:
    dependency: transitive
    description:
      name: path
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.8.0"
  plugin_platform_interface:
    dependency: transitive
    description:
      name: plugin_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.2"
  sky_engine:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.99"
  source_span:
    dependency: transitive
    description:
      name: source_span
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.8.1"
  stack_trace:
    dependency: transitive
    description:
      name: stack_trace
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.10.0"
  stream_channel:
    dependency: transitive
    description:
      name: stream_channel
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
  string_scanner:
    dependency: transitive
    description:
      name: string_scanner
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  term_glyph:
    dependency: transitive
    description:
      name: term_glyph
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.0"
  test_api:
    dependency: transitive
    description:
      name: test_api
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.4.2"
  typed_data:
    dependency: transitive
    description:
      name: typed_data
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.0"
  vector_math:
    dependency: transitive
    description:
      name: vector_math
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
  webview_flutter:
    dependency: "direct main"
    description:
      name: webview_flutter
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.3.1"
  webview_flutter_android:
    dependency: transitive
    description:
      name: webview_flutter_android
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.3.0"
  webview_flutter_platform_interface:
    dependency: transitive
    description:
      name: webview_flutter_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.5.1"
  webview_flutter_wkwebview:
    dependency: transitive
    description:
      name: webview_flutter_wkwebview
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.4.0"
sdks:
  dart: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"
```

**Comment by sanjaya-sena** [comment]
Getting the same issue

**Comment by danagbemava-nc** [comment]
Hi @AlekseyMelikov, I attempted to reproduce this, but I'm able to run the sample code of the `webview_flutter` plugin just fine. 

Is there any more additional information that you can provide?

![Screenshot 2021-11-29 at 09 09 08](https://user-images.githubusercontent.com/88313112/143839848-7f80beb9-b1b3-4414-8f84-4c57f964cdbd.png)

**Comment by NinoBass** [comment]
Also getting the same issue

**Comment by NinoBass** [comment]
> Also getting the same issue

I was able to fix it by just hot restarting

**Comment by AlekseyMelikov** [comment]
It looks like I managed to find a solution to the problem. However, I do not fully understand what exactly is the reason for this behavior.

In short, my project directory contains an example directory, into which I often insert code that contains errors. If I delete this directory, the webview application starts successfully.

In addition, I see that after starting the webview application, two files are created in the project directory - .flutter-plugins and .flutter-plugins-dependencies. These files were not created until I deleted the example directory.

After the first successful launch (when the two files .flutter-plugins and .flutter-plugins-dependencies were created), I return the example directory. And now, even though my project contains a directory of examples (with code that contains errors), the webview application starts successfully.

**Comment by danagbemava-nc** [comment]
> my project directory contains an example directory

Did you create this directory yourself or was it generated when you created your project? 
If it was the latter, how did you generate your project?

**Comment by AlekseyMelikov** [comment]
> Did you create this directory yourself or was it generated when you created your project?
> If it was the latter, how did you generate your project?

I created the example directory myself. I have a habit of collecting code examples there that I can use in the future.

**Comment by danagbemava-nc** [comment]
Can you share what your current project structure looks like?

> I have a habit of collecting code examples there that I can use in the future.

I wouldn't recommend doing this in an actual project that you're working on. Perhaps you can create a samples project and put them there
