### ISSUE TITLE
How to fixed this issue ValueChangeObserver multi value changing.

### ISSUE THREAD

**Issue by aungnianghtay** [flutter/flutter#94273]
**How to fixed this ValueChangeObserver multi value changing. fist value keylanguage change is ok. but second value getCurrentThemeMode change is async problem.**

```

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  // This widget is the root of your application.

  @override
  Widget build(BuildContext context) {
    // final isDarkMode =
    //     Settings.getValue<int,String>(ProfileSettings.keyThemeMode);

    return ValueChangeObserver<int>(
      cacheKey: ProfileSettings.keyLanguage,
      defaultValue: 1, //System Theme
      builder: (BuildContext context, getLanguage, child) =>
          ValueChangeObserver<int>(
        cacheKey: ProfileSettings.keyThemeMode,
        defaultValue: 0, //System Theme
        builder: (BuildContext context, getCurrentThemeMode, child) {
          return MaterialApp(
            onGenerateTitle: (BuildContext context) =>
                AppLocalizations.of(context)!.appTitle,
            debugShowCheckedModeBanner: false,
            theme: (getLanguage == 1)
                ? ThemeConfig.lightTheme
                : ThemeConfig.lightTheme.copyWith(
                    textTheme: Theme.of(context).textTheme.apply(
                          // fontFamily: CustomFonts.roboto,
                          fontSizeFactor: 0.95,
                          fontSizeDelta: 1.0,
                        ),
                  ),
            darkTheme: (getLanguage == 1)
                ? ThemeConfig.darkTheme
                : ThemeConfig.darkTheme.copyWith(
                    textTheme: Theme.of(context).textTheme.apply(
                          // fontFamily: CustomFonts.roboto,
                          bodyColor: Colors.white,
                          fontSizeFactor: 0.95,
                          fontSizeDelta: 1.0,
                        ),
                  ),
            themeMode: (getCurrentThemeMode == 0)
                ? ThemeMode.system
                : (getCurrentThemeMode == 1)
                    ? ThemeMode.light
                    : ThemeMode.dark,
            localizationsDelegates: const [
              GlobalMaterialLocalizations.delegate,
              GlobalWidgetsLocalizations.delegate,
              GlobalCupertinoLocalizations.delegate,
              AppLocalizations.delegate,
            ],
            supportedLocales: L10n.all,
            locale: (getLanguage == 1)
                ? const Locale.fromSubtags(languageCode: 'en')
                : const Locale.fromSubtags(languageCode: 'my'),
            initialRoute: '/',
            onGenerateRoute: AppRouter.generateRoute,
          );
        },
      ),
    );
  }
}
```

```
**Error Log Message** 
Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  MaterialApp MaterialApp:file:///C:/*****/main.dart:57:18
When the exception was thrown, this was the stack: 

#2      TextStyle.lerp (package:flutter/src/painting/text_style.dart:1031:12)
#3      TextTheme.lerp (package:flutter/src/material/text_theme.dart:432:28)
#4      ThemeData.lerp (package:flutter/src/material/theme_data.dart:1688:28)
#5      ThemeDataTween.lerp (package:flutter/src/material/theme.dart:174:41)
#6      Tween.transform (package:flutter/src/animation/tween.dart:327:12)
#7      Animatable.evaluate (package:flutter/src/animation/tween.dart:53:46)
#8      _AnimatedThemeState.build (package:flutter/src/material/theme.dart:230:20)
#9      StatefulElement.build (package:flutter/src/widgets/framework.dart:4782:27)
#10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4665:15)
#11     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#12     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#13     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2620:33)
#14     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#15     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
#16     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
#17     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1080:9)
#18     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#22     _invoke (dart:ui/hooks.dart:166:10)
#23     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#24     _drawFrame (dart:ui/hooks.dart:129:31)
(elided 5 frames from class _AssertionError and dart:async)
```
====================================================================================================

**Comment by darshankawar** [comment]
@aungnianghtay 
Can you provide `flutter doctor -v` and a minimal complete code sample without any 3rd party plugins that'll just be enough to replicate this exception ?
