### ISSUE TITLE
A crash in plugin: image_picker

### ISSUE THREAD

**Issue by CoolCsf** [flutter/flutter#94283]
In the plug-in: image_picker, the same code, Android11 is no problem, Android10 crashed：

E/AndroidRuntime(25213): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2342, result=-1, data=Intent { dat=content://media/external/images/media/26103 (has extras) }} to activity {com.coolcsf.fastrecord.fastrecord/com.coolcsf.fastrecord.fastrecord.MainActivity}: java.lang.SecurityException: com.coolcsf.fastrecord.fastrecord has no access to content://media/external/images/media/26103
E/AndroidRuntime(25213): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5353)
E/AndroidRuntime(25213): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5394)
E/AndroidRuntime(25213): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime(25213): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(25213): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(25213): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
E/AndroidRuntime(25213): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(25213): 	at android.os.Looper.loop(Looper.java:217)
E/AndroidRuntime(25213): 	at android.app.ActivityThread.main(ActivityThread.java:7993)
E/AndroidRuntime(25213): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(25213): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:502)
E/AndroidRuntime(25213): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:955)
E/AndroidRuntime(25213): Caused by: java.lang.SecurityException: com.coolcsf.fastrecord.fastrecord has no access to content://media/external/images/media/26103
E/AndroidRuntime(25213): 	at android.os.Parcel.createException(Parcel.java:2071)
E/AndroidRuntime(25213): 	at android.os.Parcel.readException(Parcel.java:2039)
E/AndroidRuntime(25213): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:188)
E/AndroidRuntime(25213): 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
E/AndroidRuntime(25213): 	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:705)
E/AndroidRuntime(25213): 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1689)
E/AndroidRuntime(25213): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1505)
E/AndroidRuntime(25213): 	at android.content.ContentResolver.openInputStream(ContentResolver.java:1189)
E/AndroidRuntime(25213): 	at io.flutter.plugins.imagepicker.FileUtils.getPathFromUri(FileUtils.java:45)
E/AndroidRuntime(25213): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseImageResult(ImagePickerDelegate.java:487)
E/AndroidRuntime(25213): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:464)
E/AndroidRuntime(25213): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:741)
E/AndroidRuntime(25213): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:426)
E/AndroidRuntime(25213): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:749)
E/AndroidRuntime(25213): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:651)
E/AndroidRuntime(25213): 	at android.app.Activity.dispatchActivityResult(Activity.java:8429)
E/AndroidRuntime(25213): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5346)
E/AndroidRuntime(25213): 	... 11 more

plugin version is ：image_picker: ^0.8.4+4

flutter doctor：
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.2, on macOS 11.6 20G165 darwin-arm, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.3)
[✓] VS Code (version 1.62.3)
[✓] Connected device (2 available)

**Comment by mamuseferha** [comment]
Hi @CoolCsf 
Could you please update to the latest flutter stable version `2.5.3` and try again? 
If the issue persists, please provide your updated `flutter doctor -v`, your `flutter run --verbose` and a minimal reproducible code sample.
Thank you

**Comment by deepak786** [comment]
We also have the same issue
```
Fatal Exception: java.lang.RuntimeException
Failure delivering result ResultInfo{who=null, request=2342, result=-1, data=Intent { dat=content://media/external/images/media/1186 }} to activity {com.agendaboa.app/com.agendaboa.app.MainActivity}: java.lang.SecurityException: com.agendaboa.app has no access to content://media/external/images/media/1186

Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2342, result=-1, data=Intent { dat=content://media/external/images/media/1186 }} to activity {com.agendaboa.app/com.agendaboa.app.MainActivity}: java.lang.SecurityException: com.agendaboa.app has no access to content://media/external/images/media/1186
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4873)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4914)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2041)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7386)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)


-------------------------------------------


Caused by java.lang.SecurityException
com.agendaboa.app has no access to content://media/external/images/media/1186

Caused by java.lang.SecurityException: com.agendaboa.app has no access to content://media/external/images/media/1186
       at android.os.Parcel.createException(Parcel.java:2071)
       at android.os.Parcel.readException(Parcel.java:2039)
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:188)
       at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
       at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderProxy.java:705)
       at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1687)
       at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1503)
       at android.content.ContentResolver.openInputStream(ContentResolver.java:1187)
       at io.flutter.plugins.imagepicker.FileUtils.getPathFromUri(FileUtils.java:10)
       at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseImageResult(ImagePickerDelegate.java:13)
       at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:38)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:25)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:15)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:51)
       at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:10)
       at android.app.Activity.dispatchActivityResult(Activity.java:8110)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4866)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4914)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2041)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7386)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
```

<details>
<summary>flutter doctor</summary>

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale
    en-US)
    • Flutter version 2.5.3 at /Library/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (7 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/appleapple/Library/Android/sdk
    • Platform android-31, build-tools 30.0.2
    • ANDROID_HOME = /Users/appleapple/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Community Edition (version 2019.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 96.0.4664.55

• No issues found!
```
</details>

**Comment by AdarshAPT** [comment]
Same issue with me. Could not reproduce the error, but my crashlytics logs is increasingly reflecting this error.

**Comment by CoolCsf** [comment]
@AdarshAPT Try to run your application on Android 10 to reproduce it ?

**Comment by darshankawar** [comment]
@AdarshAPT 
As requested earlier, we would need a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) to analyze this behavior further. Also provide the steps to replicate that leads to this crash.
