### ISSUE TITLE
NavigationRail -- Exception if Text exceeds icon width

### ISSUE THREAD

**Issue by fudgemasterultra** [flutter/flutter#94294]
## Steps to Reproduce

At a seemingly random amount of clicks(Usually between 5-20) between the different NavigationRailDestination objects. It will crash if the string's total width is more than the icon's width. 

To reproduce the bug you can actually use the provided code on the [example documents](https://api.flutter.dev/flutter/material/NavigationRail-class.html) it will crash on the page. 
I have also provides some code as well. 
```dart
NavigationRail(
      backgroundColor: Colors.green[200],
      selectedIndex: _sellectedIndex,
      onDestinationSelected: (int index) {
        setState(() {
          _sellectedIndex = index;
        });
      },
      labelType: NavigationRailLabelType.selected,
      destinations: const <NavigationRailDestination>[
        NavigationRailDestination(
          icon: Icon(Icons.favorite_border),
          selectedIcon: Icon(Icons.favorite),
          label: Text("test1"),
        ),
        NavigationRailDestination(
          icon: Icon(Icons.bookmark_border),
          selectedIcon: Icon(Icons.book),
          label: Text("test2"),
        ),
        NavigationRailDestination(
          icon: Icon(Icons.star_border),
          selectedIcon: Icon(Icons.star),
          label: Text("test3"),
        ),
      ],
    );
  }
}
```

**Expected results:** 
Highlighted the NavigationRailDestination, and shown the text, and changed the index.

**Actual results:** 
It will highlight the selected option, but crash before the text generates. 
<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
Error: Assertion failed: file:///C:/Users/Michael/Documents/flutter/packages/flutter/lib/src/painting/text_painter.dart:900:12
                    !_needsLayout
                    is not true
                        at Object.throw_ [as throw] (http://localhost:56298/dart_sdk.js:5061:11)
                        at Object.assertFailed (http://localhost:56298/dart_sdk.js:4986:15)
                        at text_painter.TextPainter.new.getPositionForOffset (http://localhost:56298/packages/flutter/src/painting/placeholder_span.dart.lib.js:2225:38)
                        at paragraph.RenderParagraph.new.hitTestChildren (http://localhost:56298/packages/flutter/src/rendering/paragraph.dart.lib.js:584:45)
                        at paragraph.RenderParagraph.new.hitTest (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:4211:18)
                        at proxy_box.RenderOpacity.new.hitTestChildren (http://localhost:56298/packages/flutter/src/rendering/proxy_box.dart.lib.js:403:56)
                        at proxy_box.RenderOpacity.new.hitTest (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:4211:18)
                        at http://localhost:56298/packages/flutter/src/rendering/shifted_box.dart.lib.js:150:47
                        at box.BoxHitTestResult.wrap.addWithPaintOffset (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:7418:19)
                        at shifted_box.RenderPositionedBox.new.hitTestChildren (http://localhost:56298/packages/flutter/src/rendering/shifted_box.dart.lib.js:148:23)
                        at shifted_box.RenderPositionedBox.new.hitTest (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:4211:18)
                        at http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:7665:44
                        at box.BoxHitTestResult.wrap.addWithPaintOffset (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:7418:19)
                        at flex$.RenderFlex.new.defaultHitTestChildren (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:7663:30)
                        at flex$.RenderFlex.new.hitTestChildren (http://localhost:56298/packages/flutter/src/rendering/flex.dart.lib.js:1079:19)
                        at flex$.RenderFlex.new.hitTest (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:4211:18)
                        at proxy_box.RenderClipRect.new.hitTestChildren (http://localhost:56298/packages/flutter/src/rendering/proxy_box.dart.lib.js:403:56)
                        at proxy_box.RenderClipRect.new.hitTest (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:4211:18)
                        at proxy_box.RenderClipRect.new.hitTest (http://localhost:56298/packages/flutter/src/rendering/proxy_box.dart.lib.js:1656:20)
                        at http://localhost:56298/packages/flutter/src/rendering/shifted_box.dart.lib.js:150:47
                        at box.BoxHitTestResult.wrap.addWithPaintOffset (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:7418:19)
                        at shifted_box.RenderPadding.new.hitTestChildren (http://localhost:56298/packages/flutter/src/rendering/shifted_box.dart.lib.js:148:23)
                        at shifted_box.RenderPadding.new.hitTest (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:4211:18)
                        at proxy_box.RenderConstrainedBox.new.hitTestChildren (http://localhost:56298/packages/flutter/src/rendering/proxy_box.dart.lib.js:403:56)
                        at proxy_box.RenderConstrainedBox.new.hitTest (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:4211:18)
                        at proxy_box.RenderPointerListener.new.hitTestChildren (http://localhost:56298/packages/flutter/src/rendering/proxy_box.dart.lib.js:403:56)
                        at proxy_box.RenderPointerListener.new.hitTest (http://localhost:56298/packages/flutter/src/rendering/proxy_box.dart.lib.js:493:26)
                        at proxy_box.RenderSemanticsAnnotations.new.hitTestChildren (http://localhost:56298/packages/flutter/src/rendering/proxy_box.dart.lib.js:403:56)
                        at proxy_box.RenderSemanticsAnnotations.new.hitTest (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:4211:18)
                        at proxy_box.RenderMouseRegion.new.hitTestChildren (http://localhost:56298/packages/flutter/src/rendering/proxy_box.dart.lib.js:403:56)
                        at proxy_box.RenderMouseRegion.new.hitTest (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:4211:18)
                        at proxy_box.RenderMouseRegion.new.hitTest (http://localhost:56298/packages/flutter/src/rendering/proxy_box.dart.lib.js:3057:20)
                        at proxy_box.RenderSemanticsAnnotations.new.hitTestChildren (http://localhost:56298/packages/flutter/src/rendering/proxy_box.dart.lib.js:403:56)
                        at proxy_box.RenderSemanticsAnnotations.new.hitTest (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:4211:18)
                        at material._RenderInkFeatures.new.hitTestChildren (http://localhost:56298/packages/flutter/src/rendering/proxy_box.dart.lib.js:403:56)
                        at material._RenderInkFeatures.new.hitTest (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:4211:18)
                        at custom_paint.RenderCustomPaint.new.hitTestChildren (http://localhost:56298/packages/flutter/src/rendering/proxy_box.dart.lib.js:403:56)
                        at custom_paint.RenderCustomPaint.new.hitTestChildren (http://localhost:56298/packages/flutter/src/rendering/custom_paint.dart.lib.js:306:20)
                        at custom_paint.RenderCustomPaint.new.hitTest (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:4211:18)
                        at http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:7665:44
                        at box.BoxHitTestResult.wrap.addWithPaintOffset (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:7418:19)
                        at stack.RenderStack.new.defaultHitTestChildren (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:7663:30)
                        at stack.RenderStack.new.hitTestChildren (http://localhost:56298/packages/flutter/src/rendering/stack.dart.lib.js:633:19)
                        at stack.RenderStack.new.hitTest (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:4211:18)
                        at proxy_box.RenderSemanticsAnnotations.new.hitTestChildren (http://localhost:56298/packages/flutter/src/rendering/proxy_box.dart.lib.js:403:56)
                        at proxy_box.RenderSemanticsAnnotations.new.hitTest (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:4211:18)
                        at http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:7665:44
                        at box.BoxHitTestResult.wrap.addWithPaintOffset (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:7418:19)
                        at flex$.RenderFlex.new.defaultHitTestChildren (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:7663:30)
                        at flex$.RenderFlex.new.hitTestChildren (http://localhost:56298/packages/flutter/src/rendering/flex.dart.lib.js:1079:19)
                        at flex$.RenderFlex.new.hitTest (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:4211:18)
                        at http://localhost:56298/packages/flutter/src/rendering/shifted_box.dart.lib.js:150:47
                        at box.BoxHitTestResult.wrap.addWithPaintOffset (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:7418:19)
                        at shifted_box.RenderPositionedBox.new.hitTestChildren (http://localhost:56298/packages/flutter/src/rendering/shifted_box.dart.lib.js:148:23)
                        at shifted_box.RenderPositionedBox.new.hitTest (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:4211:18)
                        at http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:7665:44
                        at box.BoxHitTestResult.wrap.addWithPaintOffset (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:7418:19)
                        at flex$.RenderFlex.new.defaultHitTestChildren (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:7663:30)
                        at flex$.RenderFlex.new.hitTestChildren (http://localhost:56298/packages/flutter/src/rendering/flex.dart.lib.js:1079:19)
                        at flex$.RenderFlex.new.hitTest (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:4211:18)
                        at material._RenderInkFeatures.new.hitTestChildren (http://localhost:56298/packages/flutter/src/rendering/proxy_box.dart.lib.js:403:56)
                        at material._RenderInkFeatures.new.hitTest (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:4211:18)
                        at proxy_box.RenderPhysicalModel.new.hitTestChildren (http://localhost:56298/packages/flutter/src/rendering/proxy_box.dart.lib.js:403:56)
                        at proxy_box.RenderPhysicalModel.new.hitTest (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:4211:18)
                        at proxy_box.RenderPhysicalModel.new.hitTest (http://localhost:56298/packages/flutter/src/rendering/proxy_box.dart.lib.js:2049:20)
                        at proxy_box.RenderSemanticsAnnotations.new.hitTestChildren (http://localhost:56298/packages/flutter/src/rendering/proxy_box.dart.lib.js:403:56)
                        at proxy_box.RenderSemanticsAnnotations.new.hitTest (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:4211:18)
                        at http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:7665:44
                        at box.BoxHitTestResult.wrap.addWithPaintOffset (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:7418:19)
                        at flex$.RenderFlex.new.defaultHitTestChildren (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:7663:30)
                        at flex$.RenderFlex.new.hitTestChildren (http://localhost:56298/packages/flutter/src/rendering/flex.dart.lib.js:1079:19)
                        at flex$.RenderFlex.new.hitTest (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:4211:18)
                        at http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:7665:44
                        at box.BoxHitTestResult.wrap.addWithPaintOffset (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:7418:19)
                        at custom_layout.RenderCustomMultiChildLayoutBox.new.defaultHitTestChildren (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:7663:30)
                        at custom_layout.RenderCustomMultiChildLayoutBox.new.hitTestChildren (http://localhost:56298/packages/flutter/src/rendering/custom_layout.dart.lib.js:275:19)
                        at custom_layout.RenderCustomMultiChildLayoutBox.new.hitTest (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:4211:18)
                        at material._RenderInkFeatures.new.hitTestChildren (http://localhost:56298/packages/flutter/src/rendering/proxy_box.dart.lib.js:403:56)
                        at material._RenderInkFeatures.new.hitTest (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:4211:18)
                        at proxy_box.RenderPhysicalModel.new.hitTestChildren (http://localhost:56298/packages/flutter/src/rendering/proxy_box.dart.lib.js:403:56)
                        at proxy_box.RenderPhysicalModel.new.hitTest (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:4211:18)
                        at proxy_box.RenderPhysicalModel.new.hitTest (http://localhost:56298/packages/flutter/src/rendering/proxy_box.dart.lib.js:2049:20)
                        at proxy_box.RenderSemanticsAnnotations.new.hitTestChildren (http://localhost:56298/packages/flutter/src/rendering/proxy_box.dart.lib.js:403:56)
                        at proxy_box.RenderSemanticsAnnotations.new.hitTest (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:4211:18)
                        at proxy_box.RenderRepaintBoundary.new.hitTestChildren (http://localhost:56298/packages/flutter/src/rendering/proxy_box.dart.lib.js:403:56)
                        at proxy_box.RenderRepaintBoundary.new.hitTest (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:4211:18)
                        at proxy_box.RenderIgnorePointer.new.hitTestChildren (http://localhost:56298/packages/flutter/src/rendering/proxy_box.dart.lib.js:403:56)
                        at proxy_box.RenderIgnorePointer.new.hitTest (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:4211:18)
                        at proxy_box.RenderIgnorePointer.new.hitTest (http://localhost:56298/packages/flutter/src/rendering/proxy_box.dart.lib.js:3271:38)
                        at proxy_box.RenderAnimatedOpacity.new.hitTestChildren (http://localhost:56298/packages/flutter/src/rendering/proxy_box.dart.lib.js:403:56)
                        at proxy_box.RenderAnimatedOpacity.new.hitTest (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:4211:18)
                        at proxy_box.RenderFractionalTranslation.new.hitTestChildren (http://localhost:56298/packages/flutter/src/rendering/proxy_box.dart.lib.js:403:56)
                        at http://localhost:56298/packages/flutter/src/rendering/proxy_box.dart.lib.js:2873:244
                        at box.BoxHitTestResult.wrap.addWithPaintOffset (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:7418:19)
                        at proxy_box.RenderFractionalTranslation.new.hitTestChildren (http://localhost:56298/packages/flutter/src/rendering/proxy_box.dart.lib.js:2873:21)
                        at proxy_box.RenderFractionalTranslation.new.hitTest (http://localhost:56298/packages/flutter/src/rendering/proxy_box.dart.lib.js:2868:19)
                        at proxy_box.RenderRepaintBoundary.new.hitTestChildren (http://localhost:56298/packages/flutter/src/rendering/proxy_box.dart.lib.js:403:56)
                        at proxy_box.RenderRepaintBoundary.new.hitTest (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:4211:18)
                        at routes._RenderFocusTrap.new.hitTestChildren (http://localhost:56298/packages/flutter/src/rendering/proxy_box.dart.lib.js:403:56)
                        at routes._RenderFocusTrap.new.hitTest (http://localhost:56298/packages/flutter/src/widgets/widget_inspector.dart.lib.js:15648:26)
                        at proxy_box.RenderSemanticsAnnotations.new.hitTestChildren (http://localhost:56298/packages/flutter/src/rendering/proxy_box.dart.lib.js:403:56)
                        at proxy_box.RenderSemanticsAnnotations.new.hitTest (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:4211:18)
                        at proxy_box.RenderOffstage.new.hitTestChildren (http://localhost:56298/packages/flutter/src/rendering/proxy_box.dart.lib.js:403:56)
                        at proxy_box.RenderOffstage.new.hitTest (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:4211:18)
                        at proxy_box.RenderOffstage.new.hitTest (http://localhost:56298/packages/flutter/src/rendering/proxy_box.dart.lib.js:3365:38)
                        at proxy_box.RenderSemanticsAnnotations.new.hitTestChildren (http://localhost:56298/packages/flutter/src/rendering/proxy_box.dart.lib.js:403:56)
                        at proxy_box.RenderSemanticsAnnotations.new.hitTest (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:4211:18)
                        at http://localhost:56298/packages/flutter/src/widgets/widget_inspector.dart.lib.js:25199:42
                        at box.BoxHitTestResult.wrap.addWithPaintOffset (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:7418:19)
                        at overlay$._RenderTheatre.new.hitTestChildren (http://localhost:56298/packages/flutter/src/widgets/widget_inspector.dart.lib.js:25197:28)
                        at overlay$._RenderTheatre.new.hitTest (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:4211:18)
                        at proxy_box.RenderSemanticsAnnotations.new.hitTestChildren (http://localhost:56298/packages/flutter/src/rendering/proxy_box.dart.lib.js:403:56)
                        at proxy_box.RenderSemanticsAnnotations.new.hitTest (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:4211:18)
                        at proxy_box.RenderAbsorbPointer.new.hitTestChildren (http://localhost:56298/packages/flutter/src/rendering/proxy_box.dart.lib.js:403:56)
                        at proxy_box.RenderAbsorbPointer.new.hitTest (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:4211:18)
                        at proxy_box.RenderAbsorbPointer.new.hitTest (http://localhost:56298/packages/flutter/src/rendering/proxy_box.dart.lib.js:3433:68)
                        at proxy_box.RenderPointerListener.new.hitTestChildren (http://localhost:56298/packages/flutter/src/rendering/proxy_box.dart.lib.js:403:56)
                        at proxy_box.RenderPointerListener.new.hitTest (http://localhost:56298/packages/flutter/src/rendering/proxy_box.dart.lib.js:493:26)
                        at custom_paint.RenderCustomPaint.new.hitTestChildren (http://localhost:56298/packages/flutter/src/rendering/proxy_box.dart.lib.js:403:56)
                        at custom_paint.RenderCustomPaint.new.hitTestChildren (http://localhost:56298/packages/flutter/src/rendering/custom_paint.dart.lib.js:306:20)
                        at custom_paint.RenderCustomPaint.new.hitTest (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:4211:18)
                        at proxy_box.RenderSemanticsAnnotations.new.hitTestChildren (http://localhost:56298/packages/flutter/src/rendering/proxy_box.dart.lib.js:403:56)
                        at proxy_box.RenderSemanticsAnnotations.new.hitTest (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:4211:18)
                        at proxy_box.RenderSemanticsAnnotations.new.hitTestChildren (http://localhost:56298/packages/flutter/src/rendering/proxy_box.dart.lib.js:403:56)
                        at proxy_box.RenderSemanticsAnnotations.new.hitTest (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:4211:18)
                        at proxy_box.RenderSemanticsAnnotations.new.hitTestChildren (http://localhost:56298/packages/flutter/src/rendering/proxy_box.dart.lib.js:403:56)
                        at proxy_box.RenderSemanticsAnnotations.new.hitTest (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:4211:18)
                        at proxy_box.RenderSemanticsAnnotations.new.hitTestChildren (http://localhost:56298/packages/flutter/src/rendering/proxy_box.dart.lib.js:403:56)
                        at proxy_box.RenderSemanticsAnnotations.new.hitTest (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:4211:18)
                        at view.RenderView.new.hitTest (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:4480:58)
                        at binding$5.WidgetsFlutterBinding.new.hitTest (http://localhost:56298/packages/flutter/src/rendering/layer.dart.lib.js:5214:23)
                        at binding$5.WidgetsFlutterBinding.new.[_handlePointerEventImmediately] (http://localhost:56298/packages/flutter/src/gestures/binding.dart.lib.js:302:14)
                        at binding$5.WidgetsFlutterBinding.new.handlePointerEvent (http://localhost:56298/packages/flutter/src/gestures/binding.dart.lib.js:295:43)
                        at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue] (http://localhost:56298/packages/flutter/src/gestures/binding.dart.lib.js:285:14)
                        at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket] (http://localhost:56298/packages/flutter/src/gestures/binding.dart.lib.js:276:54)
                        at Object.invoke1 (http://localhost:56298/dart_sdk.js:179667:7)
                        at _engine.EnginePlatformDispatcher.__.invokeOnPointerDataPacket (http://localhost:56298/dart_sdk.js:160119:15)
                        at _engine.PointerBinding.__.[_onPointerData] (http://localhost:56298/dart_sdk.js:160965:49)
                        at http://localhost:56298/dart_sdk.js:161373:26
                        at http://localhost:56298/dart_sdk.js:161340:16
                        at loggedHandler (http://localhost:56298/dart_sdk.js:161058:11)
```

```
```

```
```

</details>

**Comment by mamuseferha** [comment]
Hi @fudgemasterultra, this issue looks similar to this https://github.com/flutter/flutter/issues/85383, can you confirm what platform this occurs (android, ios, web, macos, windows)? Also, please provide your `flutter doctor -v`.
