### ISSUE TITLE
[tool_crash] FileSystemException: Failed to decode data using encoding 'utf-8', null

### ISSUE THREAD

**Issue by VencentYChen** [flutter/flutter#94321]
## Command
```
flutter build apk
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Failed to decode data using encoding 'utf-8', null
```
#0      _File._tryDecode (dart:io/file_impl.dart:564:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:584:7)
#2      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:96:16)
#3      AndroidPlugin._getSupportedEmbeddings (package:flutter_tools/src/platform_plugins.dart:158:53)
#4      AndroidPlugin._supportedEmbeddings (package:flutter_tools/src/platform_plugins.dart:112:71)
#5      AndroidPlugin.toMap (package:flutter_tools/src/platform_plugins.dart:104:30)
#6      _extractPlatformMaps (package:flutter_tools/src/flutter_plugins.dart:341:40)
#7      _writeAndroidPluginRegistrant (package:flutter_tools/src/flutter_plugins.dart:357:5)
#8      injectPlugins (package:flutter_tools/src/flutter_plugins.dart:1065:11)
<asynchronous suspension>
#9      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:338:5)
<asynchronous suspension>
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1260:7)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
```
```
[✓] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19041.685], locale zh-CN)
    • Flutter version 2.5.3 at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (6 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\SDK
    • Platform android-31, build-tools 30.0.3
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 2020.3)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.62.3)
    • VS Code at C:\Users\chen\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.28.0

[✓] Connected device (3 available)
    • Redmi K30 Pro Zoom Edition (mobile) • 511fdff5 • android-arm64  • Android 11 (API 30)
    • Chrome (web)                        • chrome   • web-javascript • Google Chrome 93.0.4577.82
    • Edge (web)                          • edge     • web-javascript • Microsoft Edge 96.0.1054.29

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 18116933e77adc82f80866c928266a5b4f1ed645
### Plugins
amap_flutter_map
camera-0.9.4+3
camera_web-0.2.1+1
connectivity-3.0.6
connectivity_for_web-0.4.0+1
connectivity_macos-0.2.1+2
device_info_plus-3.1.1
device_info_plus_macos-2.2.0
device_info_plus_web-2.1.0
flutter_plugin_android_lifecycle-2.0.4
fluttertoast-8.0.8
heic_to_jpg-0.2.0
image_picker-0.8.4+4
image_picker_for_web-2.1.4
jpush_flutter-2.1.5
package_info-2.0.2
path_provider-2.0.7
path_provider_android-2.0.6
path_provider_ios-2.0.6
path_provider_linux-2.1.1
path_provider_macos-2.0.2
path_provider_windows-2.0.4
permission_handler-8.3.0
photo_manager-1.3.10
shared_preferences-2.0.8
shared_preferences_linux-2.0.3
shared_preferences_macos-2.0.2
shared_preferences_web-2.0.2
shared_preferences_windows-2.0.3
sqflite-2.0.0+4
url_launcher-6.0.12
url_launcher_linux-2.0.2
url_launcher_macos-2.0.2
url_launcher_web-2.0.4
url_launcher_windows-2.0.2
video_player-2.2.7
video_player_web-2.0.4
webview_flutter-2.3.1
webview_flutter_android-2.2.1
webview_flutter_wkwebview-2.4.0
wechat_kit-3.0.1

**Comment by danagbemava-nc** [comment]
Hi @VencentYChen, thanks for filing the issue, there is already a similar issue describing this case https://github.com/flutter/flutter/issues/65021, You may follow up there for further updates. Closing this issue as a duplicate if you disagree feel free to comment and I will reopen it.

Thank you.
