### ISSUE TITLE
Windows app crashes when pressing "Insert" key.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#94502]
When I run a Windows app, and press "Insert" using the master channel, it crashes the app.

When it crashes, in the (Dart) exception, it gives the key event as:

```
RawKeyDownEvent#a2ba8(logicalKey: LogicalKeyboardKey#000ff(keyId: "0x16000000ff", keyLabel: "",
debugName: "Key with ID 0x016000000ff"), physicalKey: PhysicalKeyboardKey#70053(usbHidUsage:
"0x00070053", debugName: "Num Lock")) and its data: RawKeyEventDataWindows#f7e83(keyCode: 255,
scanCode: 57413, characterCodePoint: 0, modifiers: 0)
```

Which is weird to me, since it isn't the NumLock key, it's the Insert key.

The keycode for Insert should be 0x2d, not 0xff.

It's might be crashing because it looks at "NumLock" and thinks it needs to synchronize modifiers, but no modifier flags are set (because it's not a modifier).

Reproduction steps:

1) `flutter create --platform=windows foo`
2) `cd foo`
2) `flutter run -d windows`
2) Press "Insert" key.
3) Crash.

I was able to repro this with the b865e23 master build.

cc @dkwingsmt

**Comment by gspencergoog** [comment]
It doesn't appear to matter what the application is: just pressing Insert in a Windows app crashes, even if a text field isn't focused.

**Comment by dkwingsmt** [comment]
I still can't trigger it somehow... Can you investigate it for me? Specifically, can you try lifting the limitation in https://github.com/flutter/flutter/pull/93897?

**Comment by gspencergoog** [comment]
Sure.  It might have to do with the fact that I access the Windows machine over remote desktop (it's a cloudtop machine).

**Comment by timsneath** [comment]
Do we need to do some key input fuzzing here? I wonder if we should have a test that pumps lots of random keycodes and sees if we can get crashes?

**Comment by dkwingsmt** [comment]
I think @gspencergoog has tested and concluded that this is only happening using a remote from a specific platform.

**Comment by gspencergoog** [comment]
I've done some testing, but I'm not done yet: I'd like to find out the root cause.  In any case, it seems like some fuzzing might not be a bad idea: we do have some weird cases where crashes are occuring, and I would like to feel comfortable that pressing a key can't crash a (non-debug) app.

**Comment by darkalfx** [comment]
This happens to me with the SHIFT key and not on remote desktop, but just normally on Windows 10 with Flutter 3.3

All I have to do is open a command prompt, type:
`flutter create `

Then add
`TextFormField(),` in the `column`.

Then run the app in debug, focus the textfield and press the right and left shift a couple of times and then boom:
```

════════ Exception caught by services library ══════════════════════════════════
A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#b8065(physicalKey: PhysicalKeyboardKey#00036(usbHidUsage: "0x1600000036", debugName: "Key with ID 0x1600000036"), logicalKey: LogicalKeyboardKey#00103(keyId: "0x200000103", keyLabel: "Shift Right", debugName: "Shift Right"), character: null, timeStamp: 12:23:19.108656)
'package:flutter/src/services/hardware_keyboard.dart':
package:flutter/…/services/hardware_keyboard.dart:1
Failed assertion: line 432 pos 16: '_pressedKeys.containsKey(event.physicalKey)'

════════════════════════════════════════════════════════════════════════════════
Unable to parse JSON message:
The document is empty.
```

**Comment by gspencergoog** [comment]
@darkalfx I'm unable to reproduce this anymore on master.  Can you please try it on the master channel and see if you still have this problem?

If you do, then please post the output of `flutter doctor -v` with your response.

**Comment by apinprastya** [comment]
@gspencergoog  Still happening on my side
```
════════ Exception caught by services library ══════════════════════════════════
A KeyRepeatEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyRepeatEvent#702be(physicalKey: PhysicalKeyboardKey#700e1(usbHidUsage: "0x000700e1", debugName: "Shift Left"), logicalKey: LogicalKeyboardKey#00102(keyId: "0x200000102", keyLabel: "Shift Left", debugName: "Shift Left"), character: null, timeStamp: 59:22:47.707541)
'package:flutter/src/services/hardware_keyboard.dart':
package:flutter/…/services/hardware_keyboard.dart:1
Failed assertion: line 432 pos 16: '_pressedKeys.containsKey(event.physicalKey)'
```

Flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.2, on Microsoft Windows [Version 10.0.19044.2006], locale en-ID)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.17) 
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.71.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

**Comment by apinprastya** [comment]
Just realize that this issue is P4. So I don't expect this to be fixed in the near future.

**Comment by Rutik7066** [comment]
Same thing happening with me as well on flutter 3.3.2 on window.
after starting the app in debug mode when i try to type anything in textformfield it give me error saying 
Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack
#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> 
in HardwareKeyboard.dart
i have restared the app 4 times and each time flutter runner also calling the abort() and closes the app

**Comment by Antunees** [comment]
I'm having the same problem in Android TV, using the remote, when i press "OK". I tried with some different hardware.
This one https://www.zte.com.cn/global/products/cocloud/201707261551/IP-STB/ZXV10-B866V2_H

This issue occurs in debug and installed

Another exception was thrown: A KeyDownEvent is dispatched, but the state shows that the physical key is already pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyDownEvent#bc829(physicalKey: PhysicalKeyboardKey#700e4(usbHidUsage: "0x000700e4", debugName: "Control Right"), logicalKey: LogicalKeyboardKey#0050c(keyId: "0x10000050c", keyLabel: "Select", debugName: "Select"), character: null, timeStamp: 0:00:20.436081)

[✓] Flutter (Channel master, 3.5.0-1.0.pre, on Ubuntu 22.04.1 LTS 5.15.0-48-generic, locale en_US.UTF-8)
    • Flutter version 3.5.0-1.0.pre on channel master at /home/technobox/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5c381254e3 (4 hours ago), 2022-10-05 08:58:20 -0400
    • Engine revision 6232980336
    • Dart version 2.19.0 (build 2.19.0-273.0.dev)
    • DevTools version 2.18.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /home/technobox/Android/Sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /snap/android-studio/123/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.2)
    • Android Studio at /snap/android-studio/123/android-studio
    • Flutter plugin version 68.1.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • B866V2F (mobile) • 10.20.1.72:5555 • android-arm    • Android 11 (API 30)
    • Linux (desktop)  • linux           • linux-x64      • Ubuntu 22.04.1 LTS 5.15.0-48-generic
    • Chrome (web)     • chrome          • web-javascript • Google Chrome 106.0.5249.91

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by darkalfx** [comment]
Honestly, this is a critical bug, it prevents Windows app for using any form of text inputs as it crashes the app.

The only solution is to rollback to an earlier Flutter version.

**Comment by Crudude** [comment]
Hi I am having the same issue, and get the below error message: 

A KeyRepeatEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyRepeatEvent#0bd35(physicalKey: PhysicalKeyboardKey#700e1(usbHidUsage: "0x000700e1", debugName: "Shift Left"), logicalKey: LogicalKeyboardKey#00102(keyId: "0x200000102", keyLabel: "Shift Left", debugName: "Shift Left"), character: null, timeStamp: 204:53:12.026529)
'package:flutter/src/services/hardware_keyboard.dart':
package:flutter/…/services/hardware_keyboard.dart:1
Failed assertion: line 432 pos 16: '_pressedKeys.containsKey(event.physicalKey)'

Is there any progressing on fixing it?

**Comment by joelvarghesejoy** [comment]
The same issue happens to me when I press the Shift key. Windows 10 Flutter version is 3.3.9

```
A KeyRepeatEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyRepeatEvent#93990(physicalKey: PhysicalKeyboardKey#700e1(usbHidUsage: "0x000700e1", debugName: "Shift Left"), logicalKey: LogicalKeyboardKey#00102(keyId: "0x200000102", keyLabel: "Shift Left", debugName: "Shift Left"), character: null, timeStamp: 46:19:25.033420)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 432 pos 16: '_pressedKeys.containsKey(event.physicalKey)'

```
A KeyRepeatEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyRepeatEvent#93990(physicalKey: PhysicalKeyboardKey#700e1(usbHidUsage: "0x000700e1", debugName: "Shift Left"), logicalKey: LogicalKeyboardKey#00102(keyId: "0x200000102", keyLabel: "Shift Left", debugName: "Shift Left"), character: null, timeStamp: 46:19:25.033420)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 432 pos 16: '_pressedKeys.containsKey(event.physicalKey)'

```

**Comment by rickypid** [comment]
The same issue. Windows 10 Flutter version is 3.3.10.

```shell
======== Exception caught by services library ======================================================
The following assertion was thrown during a platform message callback:
A KeyRepeatEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyRepeatEvent#f6ca2(physicalKey: PhysicalKeyboardKey#700e1(usbHidUsage: "0x000700e1", debugName: "Shift Left"), logicalKey: LogicalKeyboardKey#00102(keyId: "0x200000102", keyLabel: "Shift Left", debugName: "Shift Left"), character: null, timeStamp: 197:14:30.651642)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 432 pos 16: '_pressedKeys.containsKey(event.physicalKey)'
```

**Comment by Raviteja11122** [comment]
The same issue. Windows 10 Flutter version is 3.3.10.


======== Exception caught by services library ======================================================
The following assertion was thrown during a platform message callback:
A KeyRepeatEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyRepeatEvent#9894c(physicalKey: PhysicalKeyboardKey#700e1(usbHidUsage: "0x000700e1", debugName: "Shift Left"), logicalKey: LogicalKeyboardKey#00102(keyId: "0x200000102", keyLabel: "Shift Left", debugName: "Shift Left"), character: null, timeStamp: 30:58:20.918846)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 432 pos 16: '_pressedKeys.containsKey(event.physicalKey)'

**Comment by dragonDScript** [comment]
Instead of saying 'same issue', as long as it doesn't contain relevant info like an older flutter version affected by the issue, or a different but similar error, just react with 👍

**Comment by DanielusG** [comment]
I confirm, the problem persists.
`flutter doctor`:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.6, on Microsoft Windows [Versione 10.0.22631.2428], locale it-IT)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop Windows apps (Visual Studio Enterprise 2022 17.6.5)
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.84.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

While debugging my application, I accidentally pressed the combination 'Ctrl + NumLock' and long exceptions were thrown:

```
[ERROR] | 8:16:05 784ms | ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞═══════════════════════
The following assertion was thrown during a platform message
callback:
A KeyDownEvent is dispatched, but the state shows that the
physical key is already pressed. If this occurs in real
application, please report this bug to Flutter. If this occurs in
unit tests, please ensure that simulated events follow Flutter's
event model as documented in `HardwareKeyboard`. This was the
event: KeyDownEvent#466d0(physicalKey:
PhysicalKeyboardKey#5b142(usbHidUsage: "0x00070053", debugName:
"Num Lock"), logicalKey: LogicalKeyboardKey#40188(keyId:
"0x100000509", keyLabel: "Pause", debugName: "Pause"), character:
null, timeStamp: 0:25:24.232737)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 467 pos 16:
'!_pressedKeys.containsKey(event.physicalKey)'

Either the assertion indicates an error in the framework itself,
or we should provide substantially more information in this error
message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on
GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack:
#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:467:16)
#3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:482:6)
#4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:601:5)
#5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:1021:37)
#6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:212:49)
#7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:567:35)
#8      _invoke2 (dart:ui/hooks.dart:202:13)
#9      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
#10     _Channel.push (dart:ui/channel_buffers.dart:135:31)
#11     ChannelBuffers.push (dart:ui/channel_buffers.dart:331:17)
#12     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:736:22)
#13     _dispatchPlatformMessage (dart:ui/hooks.dart:114:31)
(elided 2 frames from class _AssertionError)
═════════════════════════════════════════════════════════════════

StackTrace: #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:467:16)
#3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:482:6)
#4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:601:5)
#5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:1021:37)
#6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:212:49)
#7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:567:35)
#8      _invoke2 (dart:ui/hooks.dart:202:13)
#9      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
#10     _Channel.push (dart:ui/channel_buffers.dart:135:31)
#11     ChannelBuffers.push (dart:ui/channel_buffers.dart:331:17)
#12     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:736:22)
#13     _dispatchPlatformMessage (dart:ui/hooks.dart:114:31)
}
```
After this exception has been thrown, it is no longer possible to delete text from the TextFields, only to insert it.

The problem occurs anywhere in the app, even if no TextField is in the focus state.

Can anyone confirm that creating a default flutter and pressing Ctrl + NumLock causes problems in the app?

**Comment by faob-dev** [comment]
======== Exception caught by services library ======================================================
The following assertion was thrown during a platform message callback:
A KeyDownEvent is dispatched, but the state shows that the physical key is already pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyDownEvent#3a776(physicalKey: PhysicalKeyboardKey#1a9eb(usbHidUsage: "0x160000000d", debugName: "Key with ID 0x160000000d"), logicalKey: LogicalKeyboardKey#d23af(keyId: "0x000000ff", keyLabel: "Ÿ", debugName: "Key Ÿ"), character: null, timeStamp: 96:35:13.954939)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 467 pos 16: '!_pressedKeys.containsKey(event.physicalKey)'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack: 
#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:467:16)
#3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:482:6)
#4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:605:5)
#5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:1053:37)
#6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:223:49)
#7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:567:35)
#8      _invoke2 (dart:ui/hooks.dart:344:13)
#9      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
#10     _Channel._drainStep (dart:ui/channel_buffers.dart:228:31)
(elided 4 frames from class _AssertionError and dart:async)
====================================================================================================

**Comment by faob-dev** [comment]
======== Exception caught by services library ======================================================
The following assertion was thrown during a platform message callback:
A KeyDownEvent is dispatched, but the state shows that the physical key is already pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyDownEvent#3a776(physicalKey: PhysicalKeyboardKey#1a9eb(usbHidUsage: "0x160000000d", debugName: "Key with ID 0x160000000d"), logicalKey: LogicalKeyboardKey#d23af(keyId: "0x000000ff", keyLabel: "Ÿ", debugName: "Key Ÿ"), character: null, timeStamp: 96:35:13.954939)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 467 pos 16: '!_pressedKeys.containsKey(event.physicalKey)'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack: 
#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:467:16)
#3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:482:6)
#4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:605:5)
#5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:1053:37)
#6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:223:49)
#7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:567:35)
#8      _invoke2 (dart:ui/hooks.dart:344:13)
#9      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
#10     _Channel._drainStep (dart:ui/channel_buffers.dart:228:31)
(elided 4 frames from class _AssertionError and dart:async)
====================================================================================================

**Comment by abnerh69** [comment]
Hi, Why you removed `team-desktop` if it appears not only on `windows` but in macos too?
