### ISSUE TITLE
Unhandled Exception: type 'Null' is not a subtype of type 'FutureOr<bool> to buy InAppPurchaseIosPlatform.buyNonConsumable

### ISSUE THREAD

**Issue by sumitrvi** [flutter/flutter#94532]
**Flutter doctor**
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.1 20C69 darwin-x64, locale
    en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.58.2)
[✓] Connected device (1 available)

**I got this exception when I'm trying to purchase consumable items. which are already purchased.**
    Some time showing below exception and some time show popup(popup shown you've already subscribed this plan).
    I've also defined the in-app purchase code .

**Exception**
```
Unhandled Exception: type 'Null' is not a subtype of type 'FutureOr<bool>'
#0      _FutureListener.handleError (dart:async/future_impl.dart:172:20)
#1      Future._propagateToListeners.handleError (dart:async/future_impl.dart:719:47)
#2      Future._propagateToListeners (dart:async/future_impl.dart:740:24)
#3      Future._completeError (dart:async/future_impl.dart:550:5)
#4      _completeOnAsyncError (dart:async-patch/async_patch.dart:274:13)
#5      InAppPurchaseIosPlatform.buyNonConsumable (package:in_app_purchase_ios/src/in_app_purchase_ios_platform.dart)
<asynchronous suspension>
```

<details>
<summary> code sample </summary>

```
class UserSubscriptionScreen extends StatefulWidget {

  int? userEnterKey = 0;
  UserSubscriptionScreen({this.userEnterKey});

  @override
  _UserSubscriptionScreenState createState() => _UserSubscriptionScreenState();
}

class _UserSubscriptionScreenState extends State<UserSubscriptionScreen> {


  /// Is the API available on the device
  bool _available = true;

  /// The In App Purchase plugin
  final InAppPurchase _inAppPurchase = InAppPurchase.instance;

  /// Products for sale
  ProductDetails? _products;

  /// Past purchases
  PurchaseDetails? _purchases;

  Datum? planList;

  /// Updates to purchases
  StreamSubscription? _subscription;

  ProductDetails? getProductData;

  var inAppData;

  @override
  void initState() {
    // TODO: implement initState
    callSubsStatusApi();
    _initialize();
    final Stream purchaseUpdates = InAppPurchase.instance.purchaseStream;
    _subscription = purchaseUpdates.listen((purchases) {
      _handlePurchaseUpdates(purchases);
    }, onDone: () {
      print('done');
      _subscription!.cancel();
    }, onError: (error) {
      print('onError');
      // handle error here.
    });
    super.initState();
  }


  @override
  Widget build(BuildContext context) {
    Size size = MediaQuery
        .of(context)
        .size;
    return SafeArea(
      child: Scaffold(
        appBar: AppBar(
          backgroundColor: AppColors.white,
          elevation: 0.0,
          centerTitle: true,
          title: Text("Subscription",
            style: TextStyle(
              color: AppColors.toolBarTitleColor,
              fontWeight: FontWeight.w500,
              fontSize: Common.displayWidth(context) * 0.068,
            ),),
          leading: widget.userEnterKey == 0
              ? Platform.isIOS
              ? IconButton(
              onPressed: () {
                Navigator.pop(context);
              },
              icon: Icon(
                Icons.arrow_back_ios_outlined,
                color: AppColors.toolBarTitleColor,
              ))
              : Padding(
            padding: EdgeInsets.only(left: 12),
            child: IconButton(
                onPressed: () {
                  Navigator.pop(context);
                },
                icon: Icon(
                  Icons.arrow_back_outlined,
                  color: AppColors.toolBarTitleColor,
                )),
          )
              : widget.userEnterKey == null
              ? Platform.isIOS
              ? IconButton(
              onPressed: () {
                Navigator.pop(context);
              },
              icon: Icon(
                Icons.arrow_back_ios_outlined,
                color: AppColors.toolBarTitleColor,
              ))
              : Padding(
            padding: EdgeInsets.only(left: 12),
            child: IconButton(
                onPressed: () {
                  Navigator.pop(context);
                },
                icon: Icon(
                  Icons.arrow_back_outlined,
                  color: AppColors.toolBarTitleColor,
                )),
          )
              : SizedBox(),
        ),
        bottomSheet: Padding(
          padding: const EdgeInsets.only(bottom: 20, left: 20, right: 20),
          child: Container(
              alignment: Alignment.center,
              height: size.height * 0.2,
              width: size.width,
              child: Column(
                mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                children: [
                      inAppData != null &&
                      inAppData['data'] != null &&
                      inAppData['data']['is_premium'] != null &&
                      inAppData['data']['is_premium'] == "1"
                      ? Common().buildMaterialButton(
                      size, () =>{
                         Common.inAppLoading(context),
                        _inAppPurchase.restorePurchases().then((value) => {
                          print('restor close')
                        })
              }
                          ,
                      Constants.restoreTxt)
                      : MaterialButton(
                    shape: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(5),
                        borderSide: BorderSide(color: Colors.grey)),
                    height: size.height * 0.07,
                    color: Colors.grey,
                    onPressed: () {
                      Common.showSnackBar(
                          Constants.doNotHavePlan, context,
                          AppColors.snackBarBackErrorColor);
                    },
                    minWidth: size.width * 0.8,
                    child: Center(
                      child: Text(
                        Constants.restoreTxt,
                        style: TextStyle(
                            color: Colors.white,
                            fontWeight: FontWeight.w400,
                            fontSize: size.width * 0.043,
                            fontFamily: FontFamily.Roboto),
                      ),
                    ),
                  ),
                  Common().buildMaterialButton(size, () {
                    _buyProduct();
                  }, Constants.buyTxt),
                ],
              )),
        ),
        body: Container(
          height: Common.displayHeight(context),
          width: Common.displayWidth(context),
          child: Consumer<SubscriptionProvider>(
            builder: (context, modal, child) {
              return Column(
                mainAxisAlignment: MainAxisAlignment.start,
                children: [
                  modal.loading ?
                  modal.subscriptionPlanListData.data != null &&
                      modal.subscriptionPlanListData.data!.length > 0
                      ? Container(
                    margin: EdgeInsets.only(left: 15, right: 15),
                    width: size.width,
                    height: size.height * 0.53,
                    child: Card(
                      elevation: 5,
                      child: Column(
                        mainAxisAlignment: MainAxisAlignment.start,
                        crossAxisAlignment: CrossAxisAlignment.center,
                        children: [
                          Center(
                            child: Container(
                              margin: EdgeInsets.only(
                                top: size.width * 0.06,
                                bottom: size.width * 0.01,
                              ),
                              width: size.width * 0.65,
                              height: size.height * 0.32,
                              decoration: BoxDecoration(
                                image: DecorationImage(
                                  image: AssetImage(
                                      "assets/Images/subscription.png"),
                                  fit: BoxFit.cover,
                                ),
                              ),
                            ),
                          ),
                          // Cena Prime
                          Text(modal.subscriptionPlanListData.data![1].name !=
                              null
                              ? modal.subscriptionPlanListData.data![1].name
                              .toString()
                              : "",
                              style: TextStyle(
                                color: const Color(0xff6a6a6a),
                                fontWeight: FontWeight.w700,
                                fontStyle: FontStyle.normal,
                                fontSize: size.width * 0.055,
                              ),
                              textAlign: TextAlign.center),
                          Common.sizeBoxHeight(5),
                          Text(_products != null &&
                              _products!.rawPrice != null &&
                              _products!.currencySymbol != null
                              ? _products!.currencySymbol +
                              _products!.rawPrice.toString() + "/month"
                              : "",
                              style: TextStyle(
                                color: const Color(0xffd35b0f),
                                fontWeight: FontWeight.w700,
                                fontSize: size.width * 0.065,
                              ),
                              textAlign: TextAlign.center),
                          Common.sizeBoxHeight(8),
                          // Pay $Y/month to enjoy unlimited service.
                          Container(
                            alignment: Alignment.center,
                            width: size.width * 0.7,
                            child: Text(modal.subscriptionPlanListData.data![1]
                                .description != null
                                ? modal.subscriptionPlanListData.data![1]
                                .description.toString()
                                : "",
                                style: TextStyle(
                                  color: const Color(0xff000000),
                                  fontWeight: FontWeight.w400,
                                  fontSize: size.width * 0.03,
                                ),
                                textAlign: TextAlign.justify),
                          ),
                        ],
                      ),
                    ),
                  )
                      : Common.noRecordFound(context, "No Plans Available.")
                      : Container(
                    alignment: Alignment.center,
                    width: size.width,
                    height: size.height * 0.53,
                    child: Common.loadingIndicator(AppColors.primaryColor),
                  ),
                  // Terms & Condition and Privacy Policy
                  Container(
                    margin: EdgeInsets.only(
                      top: size.width * 0.10,
                    ),
                    child: RichText(
                        text: TextSpan(children: [
                          TextSpan(
                              recognizer: TapGestureRecognizer()
                                ..onTap = () {
                                  Navigator.push(
                                      context,
                                      MaterialPageRoute(
                                          builder: (context) => TermsCondition()));
                                },
                              style: const TextStyle(
                                  color: const Color(0xff6a6a6a),
                                  fontWeight: FontWeight.w400,
                                  fontFamily: "SFProDisplay",
                                  decoration: TextDecoration.underline,
                                  fontStyle: FontStyle.normal,
                                  fontSize: 15.0),
                              text: "Terms & Condition "),
                          TextSpan(
                              style: const TextStyle(
                                  color: const Color(0xff6a6a6a),
                                  fontWeight: FontWeight.w400,
                                  fontFamily: "SFProDisplay",
                                  fontStyle: FontStyle.normal,
                                  fontSize: 15.0),
                              text: " and "),
                          TextSpan(
                              recognizer: TapGestureRecognizer()
                                ..onTap = () {
                                  Navigator.push(
                                      context,
                                      MaterialPageRoute(
                                          builder: (context) => PrivacyPolicy()));
                                },
                              style: const TextStyle(
                                  color: const Color(0xff6a6a6a),
                                  fontWeight: FontWeight.w400,
                                  fontFamily: "SFProDisplay",
                                  fontStyle: FontStyle.normal,
                                  decoration: TextDecoration.underline,
                                  fontSize: 15.0),
                              text: "Privacy Policy")
                        ])),
                  )
                ],
              );
            },
          ),
        ),
      ),
    );
  }


  /// Initialize data and get product list
  void _initialize() async {
    // Check availability of In App Purchases
    _available = await _inAppPurchase.isAvailable();
    if (_available) {
      Common.showLoading(context);
      await _getProducts();
      Provider
          .of<SubscriptionProvider>(context, listen: false)
          .loading = false;
      Provider.of<SubscriptionProvider>(context, listen: false)
          .subscriptionPlanList(context);
    }
  }


  /// Get all products available for sale
  Future<void> _getProducts() async {
    Set<String> ids = Set.from([
      Urls.subscriptionPlanId,
    ]);
    ProductDetailsResponse response = await _inAppPurchase.queryProductDetails(ids);
    Common.hideLoading(context);
    if(mounted){
      setState(() {
        _products = response.productDetails[0];
      });
    }

    print('places $_products');
  }


  ///*************  Handle purchase events  **************///
  Future<void> _handlePurchaseUpdates(purchases) async {
    print('purchase data: $purchases');
    if (purchases != null)
    {
      if (purchases[0].status  == PurchaseStatus.pending) {
        Common.inAppLoading(context);
        print('waiting');
      }else{
        Common.hideLoading(context);
        if (purchases[0].status == PurchaseStatus.purchased ||
            purchases[0].status == PurchaseStatus.restored) {
          print('purchase data: $purchases');
          print('purchase purchaseID: ${purchases[0].purchaseID}');
          print('purchase receipt: ${purchases[0].verificationData
              .localVerificationData}');
          _inAppPurchase.completePurchase(purchases[0]);
          Common.showLoading(context);
          try {
            var data = await RemoteServices.inAppPurchaseApi(
                "2",
                purchases[0].purchaseID,
                _products != null ? _products!.price : '',
                purchases[0].verificationData.localVerificationData,
                purchases[0].transactionDate,
                purchases[0].status == PurchaseStatus.purchased?'0':'1');
            if (data != null) {
              if (data['status'] == true) {
                Common.hideLoading(context);
                if (data['data'] != null) {
                  successShowPopup(context, "Success", data['message']);
                }
              } else if (data['status'] == false) {
                Common.hideLoading(context);
                Common.showSnackBar(
                    Constants.somethingWrongError, context,
                    AppColors.snackBarBackErrorColor);
              } else {
                Common.hideLoading(context);
                Common.showSnackBar(
                    Constants.somethingWrongError, context,
                    AppColors.snackBarBackErrorColor);
              }
            }
          } on SocketException {
            Common.hideLoading(context);
          } catch (e) {
            Common.hideLoading(context);
            Common.showSnackBar(
                Constants.somethingWrongError, context,
                AppColors.snackBarBackErrorColor);
          }
        }
        /*else if (purchases[0].status == PurchaseStatus.restored) {
          print('purchase data: $purchases');
          print('purchase purchaseID: ${purchases[0].purchaseID}');
          print('purchase receipt: ${purchases[0].verificationData
              .localVerificationData}');
          _inAppPurchase.completePurchase(purchases[0]);
          Common.showLoading(context);
          try {
            var data = await RemoteServices.inAppPurchaseApi(
                "2",
                purchases[0].purchaseID,
                _products != null ? _products!.price : '',
                purchases[0].verificationData.localVerificationData,
                purchases[0].transactionDate,
                '1');
            if (data != null) {
              if (data['status'] == true) {
                Common.hideLoading(context);
                if (data['data'] != null) {
                  successShowPopup(context, "Success", data['message']);
                }
              } else if (data['status'] == false) {
                Common.hideLoading(context);
                Common.showSnackBar(
                    Constants.somethingWrongError, context,
                    AppColors.snackBarBackErrorColor);
              } else {
                Common.hideLoading(context);
                Common.showSnackBar(
                    Constants.somethingWrongError, context,
                    AppColors.snackBarBackErrorColor);
              }
            }
          } on SocketException {
            Common.hideLoading(context);
          } catch (e) {
            Common.hideLoading(context);
            Common.showSnackBar(
                Constants.somethingWrongError, context,
                AppColors.snackBarBackErrorColor);
          }
        }*/
        else if (purchases[0].status == PurchaseStatus.error) {
          _inAppPurchase.completePurchase(purchases[0]);
          Common.showSnackBar(
              Constants.paymentFailed, context, AppColors.snackBarBackErrorColor);
        }
        if (purchases[0].pendingCompletePurchase) {
          await InAppPurchase.instance
              .completePurchase(purchases[0]);
        }
      }
    }
  }


  ///*************** Purchase a product ***************///
  void _buyProduct() async {
    if (_products != null) {
      var transactions = await SKPaymentQueueWrapper().transactions();
      transactions.forEach((skPaymentTransactionWrapper) {
        SKPaymentQueueWrapper().finishTransaction(skPaymentTransactionWrapper);
      });
      final PurchaseParam purchaseParam = PurchaseParam(
          productDetails: _products!);
      await _inAppPurchase.buyConsumable(
          purchaseParam: purchaseParam, autoConsume: true)
          .catchError((e) {

        /*if(e is FutureOr) {
         throw("error");
        }*/

        if (e is PlatformException &&
            e.code == "storekit_duplicate_product_object") {
          //throw('error');
          Common.viewDialog(context,
              "Subscription plan already purchased, Please restore plan");
        }
      })
          .then((value) => {
            print('inapp success values $value')});
    }
  }

  successShowPopup(BuildContext context, String title, String message) {
    showDialog(
        context: context,
        barrierDismissible: false,
        builder: (context) {
          return AlertDialog(
            shape: OutlineInputBorder(
              borderRadius: BorderRadius.circular(25),
            ),
            contentPadding: EdgeInsets.symmetric(horizontal: 20, vertical: 15),
            content: Container(
              height: MediaQuery
                  .of(context)
                  .size
                  .height * 0.19,
              child: Column(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                crossAxisAlignment: CrossAxisAlignment.center,
                children: [
                  Common.sizeBoxHeight(5),
                  Text(title.toString(), style: TextStyle(
                      fontWeight: FontWeight.w700,
                      fontSize: MediaQuery
                          .of(context)
                          .size
                          .height * 0.021,
                      color: AppColors.primaryColor
                  ),),
                  Common.sizeBoxHeight(12),
                  Padding(
                    padding: const EdgeInsets.symmetric(horizontal: 10),
                    child: Align(
                        alignment: Alignment.center,
                        child: Text("Congratulations! " + message.toString())),
                  ),
                  Common.sizeBoxHeight(15),
                  MaterialButton(
                    shape: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(15),
                      borderSide: BorderSide(
                          color: Colors.transparent
                      ),
                    ),
                    color: AppColors.primaryColor,
                    height: MediaQuery
                        .of(context)
                        .size
                        .height * 0.053,
                    minWidth: MediaQuery
                        .of(context)
                        .size
                        .width * 0.24,
                    textColor: Theme
                        .of(context)
                        .primaryColor,
                    onPressed: () {
                      Navigator.pop(context);
                      widget.userEnterKey == 1
                          ? Navigator.pushAndRemoveUntil(
                          context,
                          MaterialPageRoute(
                              builder: (context) =>
                                  UserBottomNavigationBar(
                                    selected: Provider
                                        .of<UserLoginProvider>(
                                        context, listen: false)
                                        .userPrefVal,
                                  )),
                              (Route<dynamic> route) => false)
                          : Navigator.pop(context);
                    },
                    child: Text("Ok", style: TextStyle(
                      color: AppColors.white,
                      fontWeight: FontWeight.w700,
                    ),
                    ),
                  ),
                ],
              ),
            ),
          );
        });
  }

  callSubsStatusApi() async {
    inAppData = await RemoteServices.checkInAppStatus();
    print(inAppData.toString());
    if(mounted){
      setState(() {
      });
    }
  }

```
</details>

**Comment by darshankawar** [comment]
@sumitrvi 
What plugin version are you using ?
Can you upgrade to latest stable (2.5.3) and check if you still get same exception using latest plugin version ?

**Comment by sumitrvi** [comment]
@darshankawar webview version:- webview_flutter:^2.0.13

**Comment by darshankawar** [comment]
@sumitrvi 
Not sure how `webview_flutter` could be related to this. The error seems to be coming from `in_app_purchase` plugin.
Also, did you try to upgrade to latest stable (2.5.3) and check if you still get same exception using latest plugin version ?

**Comment by sumitrvi** [comment]
@darshankawar It's related to in-app purchase.

**Comment by darshankawar** [comment]
@sumitrvi 
Yes. Did you try to upgrade to latest stable (2.5.3) and check if you still get same exception using latest plugin version ?

**Comment by sumitrvi** [comment]
@darshankawar Yes I upgrade my flutter/dart version but still shows this error when I'm in sandbox mode.

Unhandled Exception: Invalid argument(s) (onError): The error handler of Future.catchError must return a value of the future's type
#0      _FutureListener.handleError (dart:async/future_impl.dart:194:7)
#1      Future._propagateToListeners.handleError (dart:async/future_impl.dart:779:47)
#2      Future._propagateToListeners (dart:async/future_impl.dart:800:13)
#3      Future._completeError (dart:async/future_impl.dart:610:5)
#4      _completeOnAsyncError (dart:async-patch/async_patch.dart:274:13)
#5      InAppPurchaseStoreKitPlatform.buyNonConsumable (package:in_app_purchase_storekit/src/in_app_purchase_storekit_platform.dart)
<asynchronous suspension>

**Comment by darshankawar** [comment]
@sumitrvi 
Please check using the latest plugin version that has gone through quite a few updates (https://pub.dev/packages/in_app_purchase/install) and see if you still get the same error or not.
