### ISSUE TITLE
[tool_crash] ProcessException: Failed to find "C:\src\flutter\engine\src\out\host_debug_unopt\dart-sdk\bin\dart.exe" in the search path. Command: C:\src\flutter\engine\src\out\host_debug_unopt\dart-sdk\bin\dart.exe, OS error code: 0

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#94574]
## Command
```
flutter run --verbose -d windows --local-engine host_debug_unopt
```

## Steps to Reproduce
1. Create new flutter project
2. On Windows, run `flutter run --verbose -d windows --local-engine host_debug_unopt`

I suspect that due to https://github.com/flutter/flutter/issues/94492, I had a prebuilt dart SDK that was only partially extracted into the engine's `prebuilt/windows-x64/dart-sdk` directory, and that during the build, this partially extracted dart SDK was then copied in. 

This seems pretty low priority given the audience it affects (people running with a local engine who are also affected by the above bug), but we should handle this scenario a bit more gracefully.

## Logs
ProcessException: Failed to find "C:\src\flutter\engine\src\out\host_debug_unopt\dart-sdk\bin\dart.exe" in the search path. Command: C:\src\flutter\engine\src\out\host_debug_unopt\dart-sdk\bin\dart.exe, OS error code: 0
```
#0      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:56:7)
#1      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:691:24)
#2      _run (package:flutter_tools/src/base/error_handling_io.dart:567:20)
#3      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:690:12)
#4      DefaultResidentCompiler._compile (package:flutter_tools/src/compile.dart:762:37)
#5      DefaultResidentCompiler._recompile (package:flutter_tools/src/compile.dart:657:14)
#6      _RecompileRequest._run (package:flutter_tools/src/compile.dart:367:16)
#7      _CompilationRequest.run (package:flutter_tools/src/compile.dart:345:30)
#8      DefaultResidentCompiler._handleCompilationRequest (package:flutter_tools/src/compile.dart:694:23)
#9      _rootRunUnary (dart:async/zone.dart:1434:47)
#10     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#11     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#13     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#14     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
#15     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
#16     _rootRun (dart:async/zone.dart:1418:47)
#17     _CustomZone.run (dart:async/zone.dart:1328:19)
#18     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
#20     _rootRun (dart:async/zone.dart:1426:13)
#21     _CustomZone.run (dart:async/zone.dart:1328:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
```
```
[✓] Flutter (Channel master, 2.6.0-12.0.pre.854, on Microsoft Windows [Version 10.0.18363.1916], locale
    en-CA)
    • Flutter version 2.6.0-12.0.pre.854 at C:\src\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 361d416e6a (3 days ago), 2021-11-29 22:01:32 -0800
    • Engine revision 7ba215c2c6
    • Dart version 2.16.0 (build 2.16.0-55.0.dev)
    • DevTools version 2.8.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\cbracken\AppData\Local\Android\sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Professional 2022 17.0.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Professional
    • Visual Studio Professional 2022 version 17.0.31912.275
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.58.2)
    • VS Code at C:\Users\cbracken\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[✓] Connected device (4 available)
    • Windows (desktop)       • windows • windows-x64     • Microsoft Windows [Version 10.0.18363.1916]
    • Windows (UWP) (desktop) • winuwp  • windows-uwp-x64 • 
    • Chrome (web)            • chrome  • web-javascript  • Google Chrome 96.0.4664.45
    • Edge (web)              • edge    • web-javascript  • Microsoft Edge 95.0.1020.40

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: d962c8f2a2c9a1ec7d0b87adf9d4bd92bad1c525

**Comment by christopherfujino** [comment]
@cbracken does this mean that https://github.com/flutter/flutter/issues/94492 is a general bug (to anyone compiling the engine), and not CI-specific?

**Comment by christopherfujino** [comment]
Also, this does not seem like a tool bug perse; if I'm understanding the issue correctly, this would only happen if the user points the tool at an incomplete local engine, right?

**Comment by cbracken** [comment]
> a general bug (to anyone compiling the engine), and not CI-specific?

This appears to be the case. This happened to me on my local machine this morning.

> this does not seem like a tool bug perse

The bug is that rather than crashing, the tool should report the error as something like "You appear to have a corrupt Dart SDK, please take the following steps to correct." 

I'd _guess_ that in the tool, this is the same code path as with a local engine (just against a different SDK path). So, for example the user had manually deleted dart.exe from our cached Dart SDK, I bet we'd get this crash too.

**Comment by namangor04** [comment]
+1 on this one, facing the same issue. There is neither dart.exe, nor dart-sdk directory in the out/host_debug_unopt directory.

**Comment by namangor04** [comment]
Any updates on this one? I am unable to build/test our custom engine due to this

**Comment by cbracken** [comment]
@namangor04 this should only really happen if the local engine ends up with an incomplete Dart SDK (e.g. network failure during download, or user pressed Ctrl-C). To get things working around, you should delete the `out/host_unopt_debug/dart-sdk` directory and do a rebuild. That will trigger a re-download of the Dart SDK.

**Comment by namangor04** [comment]
I deleted the `out/host_unopt_debug/dart-sdk` directory and did a rebuild. But i am still left with the same problem. I can confirm that I did not press `Ctrl-c`, but might be some network issue. I am trying to set this up again from scratch. Hope it works this time!.

**Comment by dkter** [comment]
I'm facing the same issue here. I'm building the engine on Linux and trying to use it with the `flutter` tool on Windows, but it seems to have only generated Linux binaries for the Dart SDK.

Where is the Dart SDK being downloaded from? The `version` file in `out/host_unopt_debug/dart-sdk` says `3.0.0-60.0-dev`, which doesn't seem to be present on [this page](https://dart.dev/get-dart/archive).
