### ISSUE TITLE
Build failed after flutter upgrade v 2.5.3

### ISSUE THREAD

**Issue by yy1300326388** [flutter/flutter#94598]
## Steps to Reproduce
1. Flutter `v1.22.6` to `v2.5.3`
2. Running in Xcode will work
3. Using `flutter run` fails

## Logs

<details>
<summary>Logs</summary>
```
。。。

                    --- xcodebuild: WARNING: Using the first of multiple matching destinations:
                    { platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
                    { platform:iOS Simulator, id:4177487D-299A-4880-949D-6EA036E6DE75, OS:12.4, name:iPad (5th generation) }
                    { platform:iOS Simulator, id:1563497F-4EAA-4480-93EF-247758283933, OS:12.4, name:iPad (6th generation) }
                    { platform:iOS Simulator, id:8D1F4375-72F8-4BFB-B4E0-20496B470116, OS:15.0, name:iPad (9th generation) }
                    { platform:iOS Simulator, id:B9D05046-ECD0-47F3-89AC-FFB62EB08ECD, OS:12.4, name:iPad Air }
                    { platform:iOS Simulator, id:2B8DB858-E6BB-4B2F-8894-645A96667F1B, OS:12.4, name:iPad Air (3rd generation) }
                    { platform:iOS Simulator, id:DEDBAF3D-7699-4B40-BEDE-15EC0B3C3300, OS:15.0, name:iPad Air (4th generation) }
                    { platform:iOS Simulator, id:8B16F713-E90E-4824-B556-20CDED1A8C12, OS:12.4, name:iPad Air 2 }
                    { platform:iOS Simulator, id:ADE35E26-927F-48FF-ABC3-D5D55E3E1F3D, OS:12.4, name:iPad Pro (9.7-inch) }
                    { platform:iOS Simulator, id:0E93A6BC-E30F-4543-905D-C071F104FA29, OS:15.0, name:iPad Pro (9.7-inch) }
                    { platform:iOS Simulator, id:D4F4EC4D-CBC4-462E-930E-BDEFC9789FE0, OS:12.4, name:iPad Pro (10.5-inch) }
                    { platform:iOS Simulator, id:A887B7AF-FF65-4032-8002-EC4194F114E5, OS:12.4, name:iPad Pro (11-inch) (1st generation) }
                    { platform:iOS Simulator, id:73892239-17C0-4A33-96EE-FE090F015EB3, OS:15.0, name:iPad Pro (11-inch) (3rd generation) }
                    { platform:iOS Simulator, id:CF7AF77E-2AEC-4274-8E0A-31CC4B517A3D, OS:12.4, name:iPad Pro (12.9-inch) (1st generation) }
                    { platform:iOS Simulator, id:61904EFD-3DFC-4CBA-B1D2-E8C9052CCA61, OS:12.4, name:iPad Pro (12.9-inch) (2nd generation) }
                    { platform:iOS Simulator, id:97891139-FED8-47F3-AF94-832E333B50F7, OS:12.4, name:iPad Pro (12.9-inch) (3rd generation) }
                    { platform:iOS Simulator, id:3F11DE57-09BD-4774-9EB0-3EB55D47C020, OS:15.0, name:iPad Pro (12.9-inch) (5th generation) }
                    { platform:iOS Simulator, id:4C9DD5AC-8B14-47AA-9B4E-726860A890C1, OS:15.0, name:iPad mini (6th generation) }
                    { platform:iOS Simulator, id:512D70CB-9089-4555-85C0-F6C1839467CA, OS:12.4, name:iPhone 5s }
                    { platform:iOS Simulator, id:E25570D4-9C4C-42C5-AC5A-F42CACD3ACDB, OS:12.4, name:iPhone 6 }
                    { platform:iOS Simulator, id:37D705D9-D3B0-459E-989F-520E266C1155, OS:12.4, name:iPhone 6 Plus }
                    { platform:iOS Simulator, id:B1A58E7A-FD12-4DF4-BE9A-6A5900CCE200, OS:12.4, name:iPhone 6s }
                    { platform:iOS Simulator, id:39656A78-D9E1-4C54-BF5A-11D7602B75F6, OS:12.4, name:iPhone 6s Plus }
                    { platform:iOS Simulator, id:C75AAEAE-AE3E-41A8-BD7C-13595D04685B, OS:12.4, name:iPhone 7 }
                    { platform:iOS Simulator, id:081C64CC-AA10-4C52-8B2E-7CD595F4A0C5, OS:12.4, name:iPhone 7 Plus }
                    { platform:iOS Simulator, id:85F54902-E1D6-47B5-A4F6-88259039FE3A, OS:12.4, name:iPhone 8 }
                    { platform:iOS Simulator, id:3FCCF92D-FCF8-4B6E-8F4F-1E1D534B82B1, OS:15.0, name:iPhone 8 }
                    { platform:iOS Simulator, id:200BBECE-E7BD-45AF-8E47-57414BC8097C, OS:12.4, name:iPhone 8 Plus }
                    { platform:iOS Simulator, id:4B471919-166C-4DE7-B51D-88E4EE73E324, OS:15.0, name:iPhone 8 Plus }
                    { platform:iOS Simulator, id:54719C99-D60A-469E-9ADF-577EA7ED5FD9, OS:15.0, name:iPhone 11 }
                    { platform:iOS Simulator, id:40E48C72-122D-4533-B54E-1527876FDF49, OS:15.0, name:iPhone 11 Pro }
                    { platform:iOS Simulator, id:E5007FA9-2111-464F-BB53-19C098D95E21, OS:15.0, name:iPhone 11 Pro Max }
                    { platform:iOS Simulator, id:52499D98-4E4C-423D-8961-BB823BE15158, OS:15.0, name:iPhone 12 }
                    { platform:iOS Simulator, id:BEB4CE66-3D27-4C73-A8F3-5814AFC823ED, OS:15.0, name:iPhone 12 Pro }
                    { platform:iOS Simulator, id:F69720D4-60AA-478E-993A-5DAA33B8259A, OS:15.0, name:iPhone 12 Pro Max }
                    { platform:iOS Simulator, id:E7564BC7-DA6E-4018-B637-C20117D7FB54, OS:15.0, name:iPhone 12 mini }
                    { platform:iOS Simulator, id:77BFB1B7-45A7-4050-B958-1BCBCBD0E25F, OS:15.0, name:iPhone 13 }
                    { platform:iOS Simulator, id:C622A98E-9A12-471F-B4E0-7F4932A70147, OS:15.0, name:iPhone 13 Pro }
                    { platform:iOS Simulator, id:1EB9E700-5FD7-4522-801B-1A1573AADDDA, OS:15.0, name:iPhone 13 Pro Max }
                    { platform:iOS Simulator, id:53840202-A47C-4B7A-8E72-33E36B947235, OS:15.0, name:iPhone 13 mini }
                    { platform:iOS Simulator, id:48048179-4834-4C16-B41C-4575CEEA35D1, OS:12.4, name:iPhone SE (1st generation) }
                    { platform:iOS Simulator, id:07274B24-96A1-4844-A9B6-D8D9A62BB22D, OS:15.0, name:iPhone SE (2nd generation) }
                    { platform:iOS Simulator, id:21503AA8-2747-401B-A6F3-20A9C878D6FB, OS:12.4, name:iPhone X }
                    { platform:iOS Simulator, id:6DA41975-185F-455E-B350-5810A90E161A, OS:12.4, name:iPhone Xs }
                    { platform:iOS Simulator, id:326A242C-227A-4275-8C35-61F143DA8CFB, OS:12.4, name:iPhone Xs Max }
                    { platform:iOS Simulator, id:1810CE32-9C7E-489B-BFA7-5F714EF3DADC, OS:12.4, name:iPhone Xʀ }
                    { platform:iOS Simulator, id:EB2BEB50-7278-40E9-AA3F-876B7CE6B5C4, OS:15.0, name:iPod touch (7th generation) }
                    { platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
。。。

[ +145 ms] Could not build the application for the simulator.
[        ] Error launching application on iPhone 13.
[   +7 ms] "flutter run" took 139,525ms.
[  +13 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:669:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>

```

```
[✓] Flutter (Channel unknown, 2.5.3, on macOS 12.0.1 21A559 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.5.3 at /Users/xxx/fvm/versions/2.5.3
    • Upstream repository unknown
    • Framework revision 18116933e7 (7 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/xxx/sdk/android-sdk-macosx
    • Platform android-31, build-tools 30.0.2
    • ANDROID_HOME = /Users/xxx/sdk/android-sdk-macosx
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_251.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • 77BFB1B7-45A7-4050-B958-1BCBCBD0E25F • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 96.0.4664.55
```

</details>

**Comment by yy1300326388** [comment]
The following configuration in `ios/Podfile` solved the problem for me
``` 
target.build_configurations.each do |config|
    config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64 i386'
end
```

![image](https://user-images.githubusercontent.com/8764899/144578112-4a20221a-70c8-43e2-8180-eb3d5c6bbf32.png)
