### ISSUE TITLE
[google_sign_in] Unhandled Exception: Missing Plugin Exception (No implementation found for method init on channel plugins.flutter.io/google_sign_in)

### ISSUE THREAD

**Issue by AliYar-Khan** [flutter/flutter#94621]
## Steps to Reproduce

1.  add google sign in to flutter project.
2.  try to login

## Logs

<details>
<summary>Logs</summary>

```
E/flutter ( 5747): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method init on channel plugins.flutter.io/google_sign_in)
E/flutter ( 5747): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter ( 5747): <asynchronous suspension>
E/flutter ( 5747): #1      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:242:5)
E/flutter ( 5747): <asynchronous suspension>
E/flutter ( 5747): #2      GoogleSignIn.signIn.isCanceled (package:google_sign_in/google_sign_in.dart)
E/flutter ( 5747): <asynchronous suspension>
E/flutter ( 5747): 

```

```
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19044.1348], locale en-US)
    • Flutter version 2.5.3 at C:\Flutter_SDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (7 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\acer\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\acer\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.61.2)
    • VS Code at C:\Users\acer\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.27.0

[√] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 96.0.4664.45
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 95.0.1020.40

• No issues found!
```

</details>

**Comment by AliYar-Khan** [comment]
I tried flutter clean and then re run the app now it is giving this exception:
```

E/flutter ( 7549): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null, null)
E/flutter ( 7549): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter ( 7549): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter ( 7549): <asynchronous suspension>
E/flutter ( 7549): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:356:43)
E/flutter ( 7549): <asynchronous suspension>
E/flutter ( 7549): #3      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:244:30)
E/flutter ( 7549): <asynchronous suspension>
E/flutter ( 7549): #4      GoogleSignIn.signIn.isCanceled (package:google_sign_in/google_sign_in.dart)
E/flutter ( 7549): <asynchronous suspension>
E/flutter ( 7549): 

```

**Comment by danagbemava-nc** [comment]
> [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null, null)

Hi @AliYar-Khan, the above error indicates that perhaps your project has not been properly configured. 

See [this SO](https://stackoverflow.com/questions/47437678/why-do-i-get-com-google-android-gms-common-api-apiexception-10) on why you're getting the error and ways to resolve it. 

Thank you
