### ISSUE TITLE
[macOS] Backspace key issues on EditableText

### ISSUE THREAD

**Issue by tiloc** [flutter/flutter#94633]
## Steps to Reproduce
I am only seeing this behaviour on macOS. The same application on web works perfect. I have seen it on the stable, dev, and master channel of Flutter (have not tried beta).

I have built a desktop application which overlays two EditableText fields through a Stack. In the video below, the black and the white field are the two EditableText fields in question.

The following happens when typing text into the top field:
1. I type letters. They appear -> OK
2. I hit the backspace key. The letters get deleted from the current cursor position backwards -> OK
3. I continue typing letters. The previously deleted letters reappear and the newly typed letters are appended to them -> NOT OK

4. at a later point, when I dispose the top EditableText it throws on an assertion:
at the end of the EditableText.dispose() method:
` assert(_batchEditDepth <= 0, 'unfinished batch edits: $_batchEditDepth');`

The reported _batchEditDepth is typically 4-7 unfinished edits.

**Expected results:**
In step 3, letters should remain deleted
The assert as described in step 4 should not trigger.

**Actual results:**
The faulty behaviour as described in steps 3 and 4.

<details>
<summary>Code sample</summary>

https://github.com/tiloc/faiadashu/tree/main/faiabench

```dart
import 'dart:convert';

import 'package:code_text_field/code_text_field.dart';
import 'package:faiabench/fhir_resource.dart';
import 'package:fhir/r4/resource/resource.dart';
import 'package:fhir_path/fhir_path.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_highlight/themes/github.dart';
import 'package:flutter_highlight/themes/monokai-sublime.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:highlight/languages/javascript.dart';
import 'package:highlight/languages/json.dart';

import 'fhir_resource_notifier.dart';

class FhirResourceEditor extends ConsumerStatefulWidget {
  final String title;
  final bool showSubmitButton;
  final bool showFhirPath;
  final StateNotifierProvider<FhirResourceNotifier, AsyncValue<FhirResource>>
      fhirResourceProvider;

  final int fhirPathOutputMinLines;
  final int fhirPathOutputMaxLines;

  const FhirResourceEditor(
    this.title,
    this.fhirResourceProvider, {
    this.showSubmitButton = true,
    this.showFhirPath = true,
    this.fhirPathOutputMinLines = 3,
    this.fhirPathOutputMaxLines = 3,
    Key? key,
  }) : super(key: key);

  @override
  _FhirResourceEditorState createState() => _FhirResourceEditorState();
}

class _FhirResourceEditorState extends ConsumerState<FhirResourceEditor> {
  ScrollController? _scrollController;
  CodeController? _codeController;
  CodeController? _fhirPathController;
  CodeController? _fhirPathOutputController;

  bool _fhirPathVisible = false;

  void _fhirPathChanged(String newPath) {
    setState(() {
      try {
        final newResource = Resource.fromJson(
          jsonDecode(_codeController!.rawText) as Map<String, dynamic>,
        );
        final pathResult = walkFhirPath(newResource.toJson(), newPath);
        const encoder = JsonEncoder.withIndent('  ');
        _fhirPathOutputController!.text =
            encoder.convert(jsonDecode(jsonEncode(pathResult)));
      } catch (e) {
        _fhirPathOutputController!.text = e.toString();
      }
    });
  }

  @override
  void initState() {
    super.initState();

    _scrollController = ScrollController();
    _codeController = CodeController(
      text: '',
      language: json,
      theme: monokaiSublimeTheme,
    );

    _fhirPathController = CodeController(
      text: '',
      language: javascript,
      theme: githubTheme,
      onChange: _fhirPathChanged,
    );

    _fhirPathOutputController = CodeController(
      text: '',
      language: json,
      theme: githubTheme,
    );
  }

  @override
  void dispose() {
    _codeController?.dispose();
    _fhirPathController?.dispose();
    _fhirPathOutputController?.dispose();
    _scrollController?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final fhirResource = ref.watch(widget.fhirResourceProvider);

    return fhirResource.when(
      data: (value) {
        final codeController = ArgumentError.checkNotNull(_codeController);
        final fhirPathController =
            ArgumentError.checkNotNull(_fhirPathController);

        final fhirPathOutputController =
            ArgumentError.checkNotNull(_fhirPathOutputController);

        codeController.text = value.jsonString;

        return Stack(
          children: [
            SingleChildScrollView(
              controller: _scrollController,
              child: CodeField(
                controller: codeController,
                textStyle: const TextStyle(fontFamily: 'SourceCode'),
              ),
            ),
            Row(
              children: [
                SizedBox(
                  width: 40,
                  height: 120,
                  child: Stack(
                    children: [
                      Container(
                        color: Colors.black54,
                        child: const SizedBox.expand(),
                      ),
                      Column(
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          IconButton(
                            tooltip: 'Open FHIRPath editor.',
                            onPressed: () {
                              setState(() {
                                _fhirPathVisible = !_fhirPathVisible;
                              });
                            },
                            icon: _fhirPathVisible
                                ? const Icon(
                                    Icons.local_fire_department,
                                    color: Colors.white,
                                    semanticLabel: 'Close FHIRPath editor.',
                                  )
                                : const Icon(
                                    Icons.local_fire_department,
                                    color: Colors.deepOrange,
                                  ),
                          ),
                          IconButton(
                            onPressed: () async {
                              await Clipboard.setData(
                                ClipboardData(
                                  text: codeController.rawText.trim(),
                                ),
                              );

                              if (!mounted) {
                                return;
                              }

                              ScaffoldMessenger.of(context).showSnackBar(
                                SnackBar(
                                  content: Text(
                                    '${widget.title} copied to clipboard.',
                                  ),
                                ),
                              );
                            },
                            icon: const Icon(
                              Icons.copy,
                              color: Colors.tealAccent,
                            ),
                            tooltip: 'Send to clipboard.',
                          ),
                          IconButton(
                            onPressed: () async {
                              final clipboardData =
                                  await Clipboard.getData('text/plain');

                              if (!mounted) {
                                return;
                              }

                              if (clipboardData != null) {
                                codeController.text = clipboardData.text ?? '';
                                ScaffoldMessenger.of(context).showSnackBar(
                                  SnackBar(
                                    content: Text(
                                      '${widget.title} pasted from clipboard.',
                                    ),
                                  ),
                                );
                              } else {
                                ScaffoldMessenger.of(context).showSnackBar(
                                  const SnackBar(
                                    content: Text('Clipboard is empty.'),
                                  ),
                                );
                              }
                            },
                            icon: const Icon(
                              Icons.paste,
                              color: Colors.tealAccent,
                            ),
                            tooltip: 'Paste from clipboard.',
                          ),
                        ],
                      ),
                    ],
                  ),
                ),
                const Expanded(child: SizedBox.shrink()),
                if (widget.showSubmitButton)
                  IconButton(
                    onPressed: () {
                      final rawText = codeController.rawText.trim();

                      final fhirResource = (rawText.isNotEmpty)
                          ? FhirResource.fromJsonString(rawText)
                          : emptyFhirResource;

                      if (fhirResource.hasError) {
                        ScaffoldMessenger.of(context).showSnackBar(
                          SnackBar(
                            backgroundColor: Theme.of(context).errorColor,
                            content: Text(fhirResource.errorMessage!),
                          ),
                        );
                      }

                      ref
                          .read(widget.fhirResourceProvider.notifier)
                          .updateFhirResource(fhirResource);
                    },
                    icon: const Icon(
                      Icons.drive_file_move,
                      color: Colors.white,
                    ),
                    tooltip: 'Send to next step.',
                  ),
              ],
            ),
            AnimatedSwitcher(
              duration: const Duration(milliseconds: 500),
              child: _fhirPathVisible
                  ? Column(
                      mainAxisAlignment: MainAxisAlignment.end,
                      children: [
                        Container(
                          padding: const EdgeInsets.all(4.0),
                          child: CodeField(
                            minLines: 1,
                            maxLines: 1,
                            controller: fhirPathController,
                          ),
                        ),
                        Container(
                          padding: const EdgeInsets.all(4.0),
                          child: CodeField(
                            minLines: widget.fhirPathOutputMinLines,
                            maxLines: widget.fhirPathOutputMaxLines,
                            enabled: false,
                            controller: fhirPathOutputController,
                          ),
                        ),
                      ],
                    )
                  : const SizedBox.shrink(),
            ),
          ],
        );
      },
      error: (error, stack) => Text('Error: $error'),
      loading: () => const CircularProgressIndicator(),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
_AssertionError._doThrowNew (errors_patch.dart:51)
_AssertionError._throwNew (errors_patch.dart:40)
EditableTextState.dispose (editable_text.dart:1825)
StatefulElement.unmount (framework.dart:4818)
_InactiveElements._unmount (framework.dart:1883)
_InactiveElements._unmount.<anonymous closure> (framework.dart:1881)
ComponentElement.visitChildren (framework.dart:4642)
_InactiveElements._unmount (framework.dart:1879)
_InactiveElements._unmount.<anonymous closure> (framework.dart:1881)
SingleChildRenderObjectElement.visitChildren (framework.dart:6110)
_InactiveElements._unmount (framework.dart:1879)
_InactiveElements._unmount.<anonymous closure> (framework.dart:1881)
Iterable.forEach (iterable.dart:279)
_DecorationElement.visitChildren (input_decorator.dart:1683)
_InactiveElements._unmount (framework.dart:1879)
_InactiveElements._unmount.<anonymous closure> (framework.dart:1881)
ComponentElement.visitChildren (framework.dart:4642)
_InactiveElements._unmount (framework.dart:1879)
_InactiveElements._unmount.<anonymous closure> (framework.dart:1881)
ComponentElement.visitChildren (framework.dart:4642)
_InactiveElements._unmount (framework.dart:1879)
_InactiveElements._unmount.<anonymous closure> (framework.dart:1881)
SingleChildRenderObjectElement.visitChildren (framework.dart:6110)
_InactiveElements._unmount (framework.dart:1879)
_InactiveElements._unmount.<anonymous closure> (framework.dart:1881)
ComponentElement.visitChildren (framework.dart:4642)
_InactiveElements._unmount (framework.dart:1879)
_InactiveElements._unmount.<anonymous closure> (framework.dart:1881)
ComponentElement.visitChildren (framework.dart:4642)
_InactiveElements._unmount (framework.dart:1879)
_InactiveElements._unmount.<anonymous closure> (framework.dart:1881)
SingleChildRenderObjectElement.visitChildren (framework.dart:6110)
_InactiveElements._unmount (framework.dart:1879)
_InactiveElements._unmount.<anonymous closure> (framework.dart:1881)
ComponentElement.visitChildren (framework.dart:4642)
_InactiveElements._unmount (framework.dart:1879)
_InactiveElements._unmount.<anonymous closure> (framework.dart:1881)
SingleChildRenderObjectElement.visitChildren (framework.dart:6110)
_InactiveElements._unmount (framework.dart:1879)
_InactiveElements._unmount.<anonymous closure> (framework.dart:1881)
SingleChildRenderObjectElement.visitChildren (framework.dart:6110)
_InactiveElements._unmount (framework.dart:1879)
_InactiveElements._unmount.<anonymous closure> (framework.dart:1881)
ComponentElement.visitChildren (framework.dart:4642)
_InactiveElements._unmount (framework.dart:1879)
_InactiveElements._unmount.<anonymous closure> (framework.dart:1881)
SingleChildRenderObjectElement.visitChildren (framework.dart:6110)
_InactiveElements._unmount (framework.dart:1879)
_InactiveElements._unmount.<anonymous closure> (framework.dart:1881)
ComponentElement.visitChildren (framework.dart:4642)
_InactiveElements._unmount (framework.dart:1879)
_InactiveElements._unmount.<anonymous closure> (framework.dart:1881)
MultiChildRenderObjectElement.visitChildren (framework.dart:6225)
_InactiveElements._unmount (framework.dart:1879)
_InactiveElements._unmount.<anonymous closure> (framework.dart:1881)
SingleChildRenderObjectElement.visitChildren (framework.dart:6110)
_InactiveElements._unmount (framework.dart:1879)
_InactiveElements._unmount.<anonymous closure> (framework.dart:1881)
SingleChildRenderObjectElement.visitChildren (framework.dart:6110)
_InactiveElements._unmount (framework.dart:1879)
_InactiveElements._unmount.<anonymous closure> (framework.dart:1881)
SingleChildRenderObjectElement.visitChildren (framework.dart:6110)
_InactiveElements._unmount (framework.dart:1879)
_InactiveElements._unmount.<anonymous closure> (framework.dart:1881)
SingleChildRenderObjectElement.visitChildren (framework.dart:6110)
_InactiveElements._unmount (framework.dart:1879)
_InactiveElements._unmount.<anonymous closure> (framework.dart:1881)
SingleChildRenderObjectElement.visitChildren (framework.dart:6110)
_InactiveElements._unmount (framework.dart:1879)
_InactiveElements._unmount.<anonymous closure> (framework.dart:1881)
SingleChildRenderObjectElement.visitChildren (framework.dart:6110)
_InactiveElements._unmount (framework.dart:1879)
_InactiveElements._unmount.<anonymous closure> (framework.dart:1881)
SingleChildRenderObjectElement.visitChildren (framework.dart:6110)
_InactiveElements._unmount (framework.dart:1879)
_InactiveElements._unmount.<anonymous closure> (framework.dart:1881)
ComponentElement.visitChildren (framework.dart:4642)
_InactiveElements._unmount (framework.dart:1879)
_InactiveElements._unmount.<anonymous closure> (framework.dart:1881)
SingleChildRenderObjectElement.visitChildren (framework.dart:6110)
_InactiveElements._unmount (framework.dart:1879)
_InactiveElements._unmount.<anonymous closure> (framework.dart:1881)
ComponentElement.visitChildren (framework.dart:4642)
_InactiveElements._unmount (framework.dart:1879)
_InactiveElements._unmount.<anonymous closure> (framework.dart:1881)
SingleChildRenderObjectElement.visitChildren (framework.dart:6110)
_InactiveElements._unmount (framework.dart:1879)
_InactiveElements._unmount.<anonymous closure> (framework.dart:1881)
ComponentElement.visitChildren (framework.dart:4642)
_InactiveElements._unmount (framework.dart:1879)
_InactiveElements._unmount.<anonymous closure> (framework.dart:1881)
ComponentElement.visitChildren (framework.dart:4642)
_InactiveElements._unmount (framework.dart:1879)
_InactiveElements._unmount.<anonymous closure> (framework.dart:1881)
ComponentElement.visitChildren (framework.dart:4642)
_InactiveElements._unmount (framework.dart:1879)
_InactiveElements._unmount.<anonymous closure> (framework.dart:1881)
_LayoutBuilderElement.visitChildren (layout_builder.dart:71)
_InactiveElements._unmount (framework.dart:1879)
_InactiveElements._unmount.<anonymous closure> (framework.dart:1881)
ComponentElement.visitChildren (framework.dart:4642)
_InactiveElements._unmount (framework.dart:1879)
_InactiveElements._unmount.<anonymous closure> (framework.dart:1881)
ComponentElement.visitChildren (framework.dart:4642)
_InactiveElements._unmount (framework.dart:1879)
_InactiveElements._unmount.<anonymous closure> (framework.dart:1881)
ComponentElement.visitChildren (framework.dart:4642)
_InactiveElements._unmount (framework.dart:1879)
_InactiveElements._unmount.<anonymous closure> (framework.dart:1881)
ComponentElement.visitChildren (framework.dart:4642)
_InactiveElements._unmount (framework.dart:1879)
_InactiveElements._unmount.<anonymous closure> (framework.dart:1881)
ComponentElement.visitChildren (framework.dart:4642)
_InactiveElements._unmount (framework.dart:1879)
_InactiveElements._unmount.<anonymous closure> (framework.dart:1881)
ComponentElement.visitChildren (framework.dart:4642)
_InactiveElements._unmount (framework.dart:1879)
_InactiveElements._unmount.<anonymous closure> (framework.dart:1881)
ComponentElement.visitChildren (framework.dart:4642)
_InactiveElements._unmount (framework.dart:1879)
_InactiveElements._unmount.<anonymous closure> (framework.dart:1881)
MultiChildRenderObjectElement.visitChildren (framework.dart:6225)
_InactiveElements._unmount (framework.dart:1879)
_InactiveElements._unmount.<anonymous closure> (framework.dart:1881)
SingleChildRenderObjectElement.visitChildren (framework.dart:6110)
_InactiveElements._unmount (framework.dart:1879)
_InactiveElements._unmount.<anonymous closure> (framework.dart:1881)
ComponentElement.visitChildren (framework.dart:4642)
_InactiveElements._unmount (framework.dart:1879)
_InactiveElements._unmount.<anonymous closure> (framework.dart:1881)
ComponentElement.visitChildren (framework.dart:4642)
_InactiveElements._unmount (framework.dart:1879)
_InactiveElements._unmount.<anonymous closure> (framework.dart:1881)
SingleChildRenderObjectElement.visitChildren (framework.dart:6110)
_InactiveElements._unmount (framework.dart:1879)
_InactiveElements._unmount.<anonymous closure> (framework.dart:1881)
ComponentElement.visitChildren (framework.dart:4642)
_InactiveElements._unmount (framework.dart:1879)
_InactiveElements._unmount.<anonymous closure> (framework.dart:1881)
MultiChildRenderObjectElement.visitChildren (framework.dart:6225)
_InactiveElements._unmount (framework.dart:1879)
_InactiveElements._unmount.<anonymous closure> (framework.dart:1881)
SingleChildRenderObjectElement.visitChildren (framework.dart:6110)
_InactiveElements._unmount (framework.dart:1879)
_InactiveElements._unmount.<anonymous closure> (framework.dart:1881)
ComponentElement.visitChildren (framework.dart:4642)
_InactiveElements._unmount (framework.dart:1879)
ListIterable.forEach (iterable.dart:39)
_InactiveElements._unmountAll (framework.dart:1892)
BuildOwner.finalizeTree.<anonymous closure> (framework.dart:2837)
BuildOwner.lockState (framework.dart:2468)
BuildOwner.finalizeTree (framework.dart:2836)
WidgetsBinding.drawFrame (binding.dart:884)
RendererBinding._handlePersistentFrameCallback (binding.dart:363)
SchedulerBinding._invokeFrameCallback (binding.dart:1145)
SchedulerBinding.handleDrawFrame (binding.dart:1082)
SchedulerBinding._handleDrawFrame (binding.dart:996)
_rootRun (zone.dart:1426)
_CustomZone.run (zone.dart:1328)
_CustomZone.runGuarded (zone.dart:1236)
_invoke (hooks.dart:151)
PlatformDispatcher._drawFrame (platform_dispatcher.dart:308)
_drawFrame (hooks.dart:115)
```

```
flutter analyze              
Analyzing faiabench...                                                  

   info • Depend on referenced packages • lib/fhir_resource_editor.dart:9:8 • depend_on_referenced_packages
   info • Depend on referenced packages • lib/fhir_resource_editor.dart:10:8 • depend_on_referenced_packages
   info • Depend on referenced packages • lib/fhir_resource_editor.dart:12:8 • depend_on_referenced_packages
   info • Depend on referenced packages • lib/fhir_resource_editor.dart:13:8 • depend_on_referenced_packages
   info • Avoid `print` calls in production code • lib/questionnaire_scroller_panel.dart:55:5 • avoid_print

5 issues found. (ran in 4.1s)
```

```
flutter doctor -v
[✓] Flutter (Channel master, 2.6.0-12.0.pre.894, on macOS 12.0.1 21A559 darwin-arm, locale en-DE)
    • Flutter version 2.6.0-12.0.pre.894 at /Users/tilo/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ff65ca5690 (25 hours ago), 2021-12-02 15:24:04 -0500
    • Engine revision 128fd65b00
    • Dart version 2.16.0 (build 2.16.0-56.0.dev)
    • DevTools version 2.8.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/tilo/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = /Users/tilo/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1426:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1861:10)
      #15     runZonedGuarded (dart:async/zone.dart:1849:12)
      #16     runZoned (dart:async/zone.dart:1780:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:198:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:302:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.0.1 21A559 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 96.0.4664.55

! Doctor found issues in 1 category.
```

</details>

![Screen Recording 2021-12-03 at 22 30 09](https://user-images.githubusercontent.com/16414047/144675512-04097c74-6b24-4a34-b0e4-e8f775bd754a.gif)

**Comment by darshankawar** [comment]
@tiloc 
Thanks for the report. The code sample you provided seems to contain lot of customized / third party code. Is it possible to shrink it down to the steps you mentioned that'll be just enough to replicate this behavior ?

**Comment by tiloc** [comment]
@darshankawar thanks, I am aware how much it helps to have a minimal example, have done so for previous
 reports and tried it as well for this one. But so far unfortunately only the full-fledged code misbehaves very reproducibly, whereas any stripped down version so far works as intended.

**Comment by darshankawar** [comment]
@tiloc 
Thanks for the update. Please see if [this](https://github.com/flutter/flutter/issues/78061) issue resembles your case.

**Comment by tiloc** [comment]
@darshankawar I have looked at the item you have linked to. I am not sure, the other item seems to be related to the composition of Asian characters. Mine, however is definitely happening on regular Western ASCII characters.

**Comment by darshankawar** [comment]
> I have built a desktop application which overlays two EditableText fields through a Stack. In the video below, the black and the white field are the two EditableText fields in question.
> 
> The following happens when typing text into the top field:
> 
> 1. I type letters. They appear -> OK
> 2. I hit the backspace key. The letters get deleted from the current cursor position backwards -> OK
> 3. I continue typing letters. The previously deleted letters reappear and the newly typed letters are appended to them -> NOT OK

Based on above scenario, I tried to come up with a minimal example and ran it on macOS, but didn't notice the behavior, but I am not sure if it correctly represents your case. Maybe you can update it per your case to be able to replicate it properly:


<details>
<summary> code sample </summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    home: Example1(),
  ));
}

class Example1 extends StatefulWidget {

  @override
  _Example1State createState() => _Example1State();
}

class _Example1State extends State<Example1> {
  void _showOverlay(BuildContext context) async {
    OverlayState? overlayState = Overlay.of(context);
    OverlayEntry overlayEntry;
    overlayEntry = OverlayEntry(builder: (context) {

      return Scaffold(
        body: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Stack(
              children: [
                Column(
                  children: [
                    TextField(
                      decoration: InputDecoration(
                          hintText: 'first'
                      ),
                    ),
                    TextField(
                      decoration: InputDecoration(
                          hintText: 'second'
                      ),
                    )
                  ],
                )
              ],
            ),
          ],
        )
      );
    });
    overlayState?.insert(overlayEntry);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(
          'Example',
          style: TextStyle(fontWeight: FontWeight.bold),
        ),
      ),
      body: SafeArea(
          child: Center(
              child: MaterialButton(
                color: Colors.green,
                minWidth: MediaQuery.of(context).size.width * 0.4,
                height: MediaQuery.of(context).size.height * 0.06,
                child: Text(
                  'show Overlay',
                  style: TextStyle(color: Colors.white),
                ),
                onPressed: () {
                  _showOverlay(context);
                },
              ))),
    );
  }
}

```
</details>

**Comment by tiloc** [comment]
Not so far. I have seriously tried, but no luck so far.

**Comment by darshankawar** [comment]
We would need a reproducible code in order to properly address this issue.
