### ISSUE TITLE
[Video player] Playback error MediaCodecVideoRenderer error

### ISSUE THREAD

**Issue by alectogeek** [flutter/flutter#94655]
## Steps to Reproduce

There are no steps to definitely reproduce the error. Sometimes it happens, sometimes it doesn't. It happens for both iOS and Android. I play mp4 videos from assets.
Here are the error logs captured:

```
E/ExoPlayerImplInternal( 5663): Playback error
E/ExoPlayerImplInternal( 5663):   com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.64001F, -1, null, [1280, 528, 23.973846], [-1, -1]), format_supported=YES
E/ExoPlayerImplInternal( 5663):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:555)
E/ExoPlayerImplInternal( 5663):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal( 5663):       at android.os.Looper.loop(Looper.java:223)
E/ExoPlayerImplInternal( 5663):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal( 5663):   Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: c2.android.avc.decoder
E/ExoPlayerImplInternal( 5663):       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1410)
E/ExoPlayerImplInternal( 5663):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:864)
E/ExoPlayerImplInternal( 5663):       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:945)
E/ExoPlayerImplInternal( 5663):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:478)
E/ExoPlayerImplInternal( 5663):       ... 3 more
E/ExoPlayerImplInternal( 5663):   Caused by: java.lang.IllegalStateException
E/ExoPlayerImplInternal( 5663):       at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
E/ExoPlayerImplInternal( 5663):       at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2855)
E/ExoPlayerImplInternal( 5663):       at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.dequeueInputBufferIndex(SynchronousMediaCodecAdapter.java:93)
E/ExoPlayerImplInternal( 5663):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1209)
E/ExoPlayerImplInternal( 5663):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:845)
E/ExoPlayerImplInternal( 5663):       ... 5 more
E/ExoPlayerImplInternal( 5663): Disable failed.
E/ExoPlayerImplInternal( 5663):   java.lang.IllegalStateException
E/ExoPlayerImplInternal( 5663):       at android.media.MediaCodec.native_flush(Native Method)
E/ExoPlayerImplInternal( 5663):       at android.media.MediaCodec.flush(MediaCodec.java:2298)
E/ExoPlayerImplInternal( 5663):       at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.flush(SynchronousMediaCodecAdapter.java:160)
E/ExoPlayerImplInternal( 5663):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushCodec(MediaCodecRenderer.java:912)
E/ExoPlayerImplInternal( 5663):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:905)
E/ExoPlayerImplInternal( 5663):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:761)
E/ExoPlayerImplInternal( 5663):       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:483)
E/ExoPlayerImplInternal( 5663):       at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:176)
E/ExoPlayerImplInternal( 5663):       at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1609)
E/ExoPlayerImplInternal( 5663):       at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:1351)
E/ExoPlayerImplInternal( 5663):       at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:1314)
E/ExoPlayerImplInternal( 5663):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:571)
E/ExoPlayerImplInternal( 5663):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal( 5663):       at android.os.Looper.loop(Looper.java:223)
E/ExoPlayerImplInternal( 5663):       at android.os.HandlerThread.run(HandlerThread.java:67)
```

```dart
```

`flutter run --verbose` result:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-arm, locale en-RU)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS
[✓] Android Studio (version 4.1)
[✓] Android Studio (version 2020.3)
[✓] Connected device (3 available)
    ! Error: Starlink is not connected. Xcode will continue when Starlink is connected. (code -13)

! Doctor found issues in 1 category.
Human-3:learnlanguage-mobile alectogeek$ flutter doctor --verbose
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-arm, locale en-RU)
    • Flutter version 2.5.3 at /Users/alectogeek/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (7 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/alectogeek/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/alectogeek/Downloads/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64 • Android 11 (API 30) (emulator)
    • sdk gphone arm64 (mobile) • emulator-5556 • android-arm64 • Android 11 (API 30) (emulator)
    • sdk gphone arm64 (mobile) • emulator-5558 • android-arm64 • Android 11 (API 30) (emulator)
    ! Error: Starlink is not connected. Xcode will continue when Starlink is connected. (code -13)


```

**Comment by maheshmnj** [comment]
Hi @alectogeek, Thanks for filing the issue. Please share the minimal and complete code sample along with the output of `flutter run -v` in a text file. Can you please also check if this error occurs with a specific video asset or all assets? if former, attach the video assets to investigate further.

**Comment by cmdelri13** [comment]
I get the same error. I am implementing an app with amplify, the videos that I upload to amplify from the console play them, those that I upload from the device do not.

**Comment by anhdhq** [comment]
i got same error when run on Android (device: SM J600G)

final _storedVideoMerge = '${dir.path}/videos/output_video_merge.mp4';
    video = File(_storedVideoMerge);
    videoPlayerController = VideoPlayerController.file(
      video,
);

E/ExoPlayerImplInternal( 8544):   Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.Exynos.mpeg4.dec, Format(1, null, null, video/mp4v-es, null, -1, null, [1920, 1080, 23.83503], [-1, -1])
E/ExoPlayerImplInternal( 8544):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1051)
E/ExoPlayerImplInternal( 8544):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:606)
E/ExoPlayerImplInternal( 8544):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1465)
E/ExoPlayerImplInternal( 8544):       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:713)
E/ExoPlayerImplInternal( 8544):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:998)
E/ExoPlayerImplInternal( 8544):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:830)
E/ExoPlayerImplInternal( 8544):       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:945)
E/ExoPlayerImplInternal( 8544):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:478)
E/ExoPlayerImplInternal( 8544):       ... 3 more
E/ExoPlayerImplInternal( 8544):   Caused by: android.media.MediaCodec$CodecException: Error 0xffffec77
E/ExoPlayerImplInternal( 8544):       at android.media.MediaCodec.native_configure(Native Method)
E/ExoPlayerImplInternal( 8544):       at android.media.MediaCodec.configure(MediaCodec.java:1935)

**Comment by maheshmnj** [comment]
Everyone who is facing a similar issue please share the video source (a video URL or asset), output of `flutter doctor -v`, `flutter run -v`, and the device name on which the video fails to play.
