### ISSUE TITLE
[tool_crash] FileSystemException: Creation of temporary directory failed, OS Error: No such file or directory, errno = 2

### ISSUE THREAD

**Issue by Kerimkullov** [flutter/flutter#94684]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Creation of temporary directory failed, OS Error: No such file or directory, errno = 2
```
#0      _Directory.createTempSync (dart:io/directory_impl.dart:181:7)
#1      ForwardingDirectory.createTempSync (package:file/src/forwarding/forwarding_directory.dart:28:21)
#2      LocalFileSystem.systemTempDirectory (package:flutter_tools/src/base/file_system.dart:221:47)
#3      ForwardingFileSystem.systemTempDirectory (package:file/src/forwarding/forwarding_file_system.dart:33:49)
#4      new ResidentRunner (package:flutter_tools/src/resident_runner.dart:1014:24)
#5      new HotRunner (package:flutter_tools/src/run_hot.dart:103:8)
#6      RunCommand.createRunner (package:flutter_tools/src/commands/run.dart:488:14)
<asynchronous suspension>
#7      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:627:35)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
<asynchronous suspension>
#14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
```
```
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.5.2 20G95 darwin-arm, locale ru-KG)
    • Flutter version 2.5.3 at /Users/user/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (7 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • iPhone 12 Pro (mobile) • C317B1DE-249B-4B09-A202-50B341DDF152 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 96.0.4664.55

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.4+01
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: adc687823a831bbebe28bdccfac1a628ca621513
### Plugins
device_info_plus-2.2.0
device_info_plus_macos-2.2.0
device_info_plus_web-2.1.0
file_picker-4.2.6
firebase_analytics-8.3.4
firebase_analytics_web-0.3.0+1
firebase_core-1.10.0
firebase_core_web-1.2.0
firebase_crashlytics-2.3.0
firebase_dynamic_links-3.0.1
flutter_plugin_android_lifecycle-2.0.4
flutter_secure_storage-4.2.1
image_picker-0.8.4+4
image_picker_for_web-2.1.4
integration_test
local_auth-1.1.8
package_info_plus-1.3.0
package_info_plus_macos-1.3.0
package_info_plus_web-1.0.4
path_provider-2.0.7
path_provider_android-2.0.7
path_provider_ios-2.0.7
path_provider_linux-2.1.2
path_provider_macos-2.0.3
path_provider_windows-2.0.4
sqflite-2.0.0+4
url_launcher-6.0.13
url_launcher_linux-2.0.2
url_launcher_macos-2.0.2
url_launcher_web-2.0.4
url_launcher_windows-2.0.2
webview_cookie_manager-2.0.6
webview_flutter-2.3.1
webview_flutter_android-2.2.1
webview_flutter_wkwebview-2.4.0

**Comment by danagbemava-nc** [comment]
Hi @Kerimkullov, thanks for filing the issue.

There's a similar issue open #74042.

Kindly follow up there for more information, and if you can provide any more information over there, that will be appreciated.

Closing from here as duplicate.

Thank you
