### ISSUE TITLE
_CastError: Null check operator used on a null value

### ISSUE THREAD

**Issue by tandacedric** [flutter/flutter#94726]
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter --no-color pub get

## exception

_CastError: Null check operator used on a null value

```
#0      describeLocale (package:flutter_tools/src/localizations/localizations_utils.dart:219:49)
#1      LocalizationsGenerator._generateBaseClassFile (package:flutter_tools/src/localizations/gen_l10n.dart:1137:34)
#2      LocalizationsGenerator._generateCode (package:flutter_tools/src/localizations/gen_l10n.dart:1238:46)
#3      LocalizationsGenerator.writeOutputFiles (package:flutter_tools/src/localizations/gen_l10n.dart:1313:47)
#4      generateLocalizations (package:flutter_tools/src/localizations/gen_l10n.dart:69:9)
#5      GenerateLocalizationsTarget.build (package:flutter_tools/src/build_system/targets/localizations.dart:56:5)
#6      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:839:27)
<asynchronous suspension>
#7      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:606:16)
<asynchronous suspension>
#8      generateLocalizationsSyntheticPackage (package:flutter_tools/src/dart/generate_synthetic_packages.dart:58:30)
<asynchronous suspension>
#9      PackagesGetCommand._runPubGet (package:flutter_tools/src/commands/packages.dart:134:7)
<asynchronous suspension>
#10     PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:176:5)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#19     main (package:flutter_tools/executable.dart:94:3)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel master, 2.6.0-12.0.pre.925, on macOS 12.0.1 21A559 darwin-x64, locale fr-FR)
    • Flutter version 2.6.0-12.0.pre.925 at /Users/henvino/flutter_2.2.3/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bb906b6b4f (6 hours ago), 2021-12-06 10:34:56 +0100
    • Engine revision 68d320d449
    • Dart version 2.16.0 (build 2.16.0-80.0.dev)
    • DevTools version 2.9.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/henvino/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/henvino/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.58.2)
    • VS Code at /Users/henvino/Downloads/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.0.1 21A559 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 96.0.4664.55

• No issues found!
```

**Comment by danagbemava-nc** [comment]
Hi @tandacedric, thanks for reporting this. 

Is this an isolated event or does it occur frequently? 

If it does, kindly provide steps to reproduce. 

Please provide your `pubspec.yaml` as well.

Thank you
