### ISSUE TITLE
[webview_flutter] Android background test times out on FTL

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#94748]
https://github.com/flutter/plugins/pull/4569 adds a native UI test using espresso, but it doesn't seem to run correctly in FTL (see https://github.com/flutter/plugins/pull/4569/files#r762446578 for background):

```
androidx.test.espresso.AppNotIdleException: Looped for 5404 iterations over 60 SECONDS. The following Idle Conditions failed .
at dalvik.system.VMStack.getThreadStackTrace(Native Method)
at java.lang.Thread.getStackTrace(Thread.java:1736)
at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:96)
at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:59)
at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:322)
at androidx.test.espresso.ViewInteraction.desugaredPerform(ViewInteraction.java:178)
at androidx.test.espresso.ViewInteraction.perform(ViewInteraction.java:119)
at androidx.test.espresso.flutter.EspressoFlutter$WidgetInteraction.performInternal(EspressoFlutter.java:142)
at androidx.test.espresso.flutter.EspressoFlutter$WidgetInteraction.perform(EspressoFlutter.java:107)
at io.flutter.plugins.webviewflutterexample.BackgroundColorTest.backgroundColor(BackgroundColorTest.java:38)
at java.lang.reflect.Method.invoke(Native Method)
```

It runs fine when run locally via `native-test`, and it's failing on the very first line (nothing obscure related to the thing being tested), so it seems like the problem here is that something is wrong with our ability to run this kind of test on our CI at the moment, rather than an issue with the test itself.

/cc @blasten @bparrishMines

**Comment by stuartmorgan** [comment]
The setup was based on `android_alarm_manager`; its test was disabled for flake, but did at least sometimes work, so it should be possible. Maybe there's something we missed in the setup for webview? (If that turns out to be the case, we should make sure to document the process of setting it up on https://github.com/flutter/flutter/wiki/Plugin-Tests)

**Comment by blasten** [comment]
Do you have the result of the invocation in FTL? 

I couldn't find it in the linked PR nor https://firebase.corp.google.com/u/0/project/flutter-infra/testlab/histories/bh.3578c8014094ec11

Some online answers suggest that a UI element is being created indefinitely.

**Comment by stuartmorgan** [comment]
https://console.firebase.google.com/project/flutter-cirrus/testlab/histories/bh.50da00dd1c44684a/matrices/9189702378796104285 is one of the failed runs.
