### ISSUE TITLE
[webview_flutter] 'Auto media playback' test flaked on Android

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#94750]
```
java.lang.Exception: ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞═══════════════════════
The following StateError was thrown during a platform message
callback:
Bad state: Future already completed
When the exception was thrown, this was the stack:
#1 main.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///tmp/cirrus-ci-build/packages/webview_flutter/webview_flutter_android/example/integration_test/webview_flutter_test.dart:488:34)
#2 JavascriptChannelRegistry.onJavascriptChannelMessage (package:webview_flutter_platform_interface/src/platform_interface/javascript_channel_registry.dart:28:40)
#3 WebViewAndroidJavaScriptChannel.postMessage (package:webview_flutter_android/webview_android_widget.dart:373:31)
#4 JavaScriptChannelFlutterApiImpl.postMessage (package:webview_flutter_android/src/android_webview_api_impls.dart:471:15)
#5 JavaScriptChannelFlutterApi.setup.<anonymous closure> (package:webview_flutter_android/src/android_webview.pigeon.dart:1156:15)
#6 JavaScriptChannelFlutterApi.setup.<anonymous closure> (package:webview_flutter_android/src/android_webview.pigeon.dart:1146:35)
#7 BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:73:49)
#8 BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:72:47)
#9 _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:379:35)
#10 _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:376:46)
#11 _invoke2.<anonymous closure> (dart:ui/hooks.dart:205:15)
#15 _invoke2 (dart:ui/hooks.dart:204:10)
#16 _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#17 _Channel.push (dart:ui/channel_buffers.dart:132:31)
#18 ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#19 PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:544:22)
#20 _dispatchPlatformMessage (dart:ui/hooks.dart:92:31)
(elided 4 frames from dart:async)
═════════════════════════════════════════════════════════════════
at dev.flutter.plugins.integration_test.FlutterTestRunner.run(FlutterTestRunner.java:81)
```

**Comment by stuartmorgan** [comment]
I just hit what looks like the same exception flake in `Video plays inline when allowsInlineMediaPlayback is true`
