### ISSUE TITLE
Image.network images seem to be swallowing root cert errors

### ISSUE THREAD

**Issue by HankG** [flutter/flutter#94758]
I was having a problem on a Windows 10 test machine where network images never seemed to be loading. The expected images never rendered, nor were there any reported errors. It turns out the problem was that the root certificates on that machine had expired, in the case of the test app to LetsEncrypt. [This link by LetsEncrypt](https://docs.certifytheweb.com/docs/kb/kb-202109-letsencrypt/) discusses how to fix that. The larger issue I'm documenting here is the fact that there were no errors, exceptions, timeouts etc. The request just never returned. This is unexpected behavior and not consistent with the way other network errors fail compared to a direct http request. Below is code which goes to the link via http.get as well as the Image.network constructor. On a machine with a root certificate problem for the corresponding server the http path throws an exception while the Image.network path does not, nor ever returns. In instances of bad domains, 404 errors, etc., the behavior of http and the Image.network code is consistent. 

## Steps to Reproduce

1. Change the site/path data in the example code to point to a server whose root certificate your system does not trust
2. Execute the code. Whether it calls the info (thus inducing the network resolution on text update rather than the UI to definitively show the hang) is configurable in the code or by the first CLI parameter.

**Expected results:** 
The call should report an exception and return immediately consistent with what a direct http request returns to the same URL. For example if the domain is wrong:

```bash
flutter: SocketException: Failed host lookup: 'nequalsonelifestyle1.com' (OS Error: No such host is known.

, errno = 11001)

======== Exception caught by image resource service ================================================
The following SocketException was thrown resolving an image codec:
Failed host lookup: 'nequalsonelifestyle1.com' (OS Error: No such host is known.
, errno = 11001)

When the exception was thrown, this was the stack: 
#0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:677:35)
...
#44     _dispatchPointerDataPacket (dart:ui/hooks.dart:98:31)
(elided 6 frames from dart:async)
Image provider: NetworkImage("https://nequalsonelifestyle1.com/assets/avatars/current_150x150.jpg", scale: 1.0)
Image key: NetworkImage("https://nequalsonelifestyle1.com/assets/avatars/current_150x150.jpg", scale: 1.0)
====================================================================================================
```

**Actual results:** 
While the direct http request correctly returns the certificate error the Image network request throws no errors and never returns:

```bash
flutter: HandshakeException: Handshake error in client (OS Error:
        CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(../../third_party/boringssl/src/ssl/handshake.cc:359))
```

There should be a comparable exception from the `await _getImageData()` or the direct image load from attempting to load the image to draw the widget but there is nothing.

<details>
<summary>Code sample</summary>

```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'dart:ui' as ui;

bool useImageInfoQuery = true;
final siteName = 'nequalsonelifestyle.com';
final path = '/assets/avatars/current_150x1150.jpg';
final url = 'https://$siteName$path';

void main(List<String> args) async {
  useImageInfoQuery = args.isEmpty
      ? true
      : args[0].toLowerCase() == 'true'
          ? true
          : false;
  print('Use Image Info Query? $useImageInfoQuery');
  try {
    final response = await http.get(Uri.https(siteName, path));
    print('${response.statusCode} code w/${response.bodyBytes.length} bytes');
  } catch (e) {
    print(e);
  }
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Image.network Cert Bug',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(
          title: 'Image.network Cert Bug'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  Image? image;

  Future<void> _loadImage() async {
    image = Image.network(url);
    if (useImageInfoQuery) {
      final info = await _getImageData();
      print('Info = ${info?.width}, ${info?.height}');
    }

    setState(() {
      print('SetState');
    });
  }

  Future<ui.Image?> _getImageData() {
    final completer = Completer<ui.Image>();
    final listener = ImageStreamListener(
        (ImageInfo info, bool _) => completer.complete(info.image));
    image!.image.resolve(const ImageConfiguration()).addListener(listener);
    return completer.future;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            image == null
                ? const Text(
                    'Push Button to load image',
                  )
                : Image(
                    image: image!.image,
                    fit: BoxFit.fill,
                  ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _loadImage,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

</details>

**Comment by maheshmnj** [comment]
Hi @HankG, thanks for filing the issue, Can you please share the output of `flutter doctor -v`?
I ran your code sample on `stable 2.5.3` and I can see the exception as expected.


<details>
<summary>logs</summary>

```
Launching lib\main.dart on sdk gphone x86 in debug mode...
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:53648/THYmgKJCotE=/ws
I/flutter (27547): Use Image Info Query? true
I/flutter (27547): 404 code w/162 bytes

════════ Exception caught by image resource service ════════════════════════════
The following NetworkImageLoadException was thrown resolving an image codec:
HTTP request failed, statusCode: 404, https://nequalsonelifestyle.com/assets/avatars/current_150x1150.jpg

When the exception was thrown, this was the stack
#0      NetworkImage._loadAsync
<asynchronous suspension>
Image provider: NetworkImage("https://nequalsonelifestyle.com/assets/avatars/current_150x1150.jpg", scale: 1.0)
Image key: NetworkImage("https://nequalsonelifestyle.com/assets/avatars/current_150x1150.jpg", scale: 1.0)
════════════════════════════════════════════════════════════════════════════════

```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19042.1348], locale en-US)
    • Flutter version 2.5.3 at C:\flutter_sdk\stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (8 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\mahesh\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java      
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)    
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31727.386
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.61.2)
    • VS Code at C:\Users\mahesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.29.0

[√] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version
      10.0.19042.1348]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 96.0.4664.45
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 95.0.1020.44

• No issues found!
```
</details>
Thanks

**Comment by HankG** [comment]
@maheshmnj I can do that for the build (output below) machine but the machine that generates the error is just running the release binary and has no dev environment. I can't get a debug binary running on it because it is missing some debug dependency libraries. I've cloned that machine to setup a dev environment to see if I can reproduce it in debug/dev mode as well although you may be ahead of me on that. I'll report back what I find here.

```
[✓] Flutter (Channel stable, 2.5.3, on Linux Mint 20.2 5.4.0-91-generic, locale
    en_US.UTF-8)
    • Flutter version 2.5.3 at /home/hankgrabowski/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (8 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/hankgrabowski/Android/Sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/hankgrabowski/apps/android-studio
    • Flutter plugin version 61.2.2
    • Dart plugin version 203.8430
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at /home/hankgrabowski/apps/idea-IU-212.4746.92
    • Flutter plugin version 58.0.4
    • Dart plugin version 212.4746.57

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux Mint 20.2 5.4.0-91-generic
    • Chrome (web)    • chrome • web-javascript • Chromium 96.0.4664.45 for Linux Mint
```

**Comment by HankG** [comment]
I've diagnosed the difference in behavior but it looks very intentional. I created a branch with a commit to confirm the behavior which you can find here: https://github.com/HankG/flutter/commit/bcc07d13cc6f627476a3cb942f7eeda9437d2c4c

Essentially the codec handler in MultiFrameImageStreamCompleter has an error function which then creates a FlutterErrorDetails object that propagates over to FlutterError.reportError method. The onError object for that is the dumpErrorToConsole method. It only dumps it to the console if the "silent" flag is set to false *or* if it is in debug mode. Any exception thrown within the code NetworkImage._loadAsync method will get intercepted by this and will be reported in debug mode but otherwise be swallowed. In my branch I disable the silent mode. I'm not sure if we only want certain errors to propagate or maybe the _loadAsync method should be reporting individually since other codec exceptions we do want to be silent in release mode. 

I did prove that my original assertion that the failure modes were different in debug/release besides the reporting was not accurate. The Widget drawing fails differently in that in debug mode it draws a big X with the exception and in release mode it just never renders. The _getImageInfo block however never returns in any mode. To do that one needs to pass in an `onError` function to the completer which then propagates the exceptions as expected in all modes (snippet below). Ironically for the info case the completer default error handler dumps the network errors to the console in debug and release mode.

```dart
  final listener = ImageStreamListener((ImageInfo info, bool _) {
    completer.complete(info.image);
  }, onError: (error, stack) => completer.completeError(error, stack));
```

I'm not sure what the path forward is but debugging the problem was next to impossible since there were no errors reported anywhere. One option is to make this not silent. The other option is if we want that behavior to implement our own FlutterExceptionHandler to send into the onError object. I suppose this is how one would divert exceptions to logging systems etc. too.

**Comment by maheshmnj** [comment]
Thanks for the info @HankG, Leaving this issue open for further investigation from the team.
