### ISSUE TITLE
`felt ios-safari test` is flaky because an iOS simulator could not be started.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#94766]
An [instance of the failure](https://ci.chromium.org/p/flutter/builders/try/Mac%20Web%20Engine/21475?) is here on [this patches presubmit](https://github.com/flutter/engine/pull/30171/checks?check_run_id=4437179983).

The stack trace is:

```
Unhandled exception:
Exception: Failed to boot iOS simulators with id: 0E7178C3-FD7C-471E-983C-686C3AE87248.
#0      IosSimulator.boot (package:simulators/simulator_manager.dart:212:7)
<asynchronous suspension>
#1      initIosSimulator (file:///opt/s/w/ir/cache/builder/src/flutter/lib/web_ui/dev/safari_installation.dart:56:5)
<asynchronous suspension>
#2      SafariIosEnvironment.prepare (file:///opt/s/w/ir/cache/builder/src/flutter/lib/web_ui/dev/safari_ios.dart:32:5)
<asynchronous suspension>
#3      RunTestsStep.run (file:///opt/s/w/ir/cache/builder/src/flutter/lib/web_ui/dev/steps/run_tests_step.dart:80:5)
<asynchronous suspension>
#4      Pipeline.run (file:///opt/s/w/ir/cache/builder/src/flutter/lib/web_ui/dev/pipeline.dart:128:9)
<asynchronous suspension>
#5      TestCommand.run (file:///opt/s/w/ir/cache/builder/src/flutter/lib/web_ui/dev/test_runner.dart:156:5)
<asynchronous suspension>
#6      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#7      main (file:///opt/s/w/ir/cache/builder/src/flutter/lib/web_ui/dev/felt.dart:43:26)
<asynchronous suspension>
```

**Comment by Hixie** [comment]
cc @yjbanov

**Comment by yjbanov** [comment]
@jmagman is this related to the iOS simulator upgrade in the infrastructure?

**Comment by jmagman** [comment]
No, that has only happened on a few staging bots via `led`.

**Comment by yjbanov** [comment]
Looking at the last 100 LUCI builds, there weren't any iOS simulator failures. Assuming this is fixed now.
