### ISSUE TITLE
[Android] NullPointerException in TextInputPlugin.setTextInputEditingState

### ISSUE THREAD

**Issue by eggfly** [flutter/flutter#94794]
Similar issue:
* https://github.com/flutter/flutter/issues/92241

But in setTextInputEditingState
PlatformException(error, Attempt to invoke virtual method 'void io.flutter.plugin.editing.ListenableEditingState.setEditingState(io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState)' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.editing.ListenableEditingState.setEditingState(io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState)' on a null object reference
at io.flutter.plugin.editing.TextInputPlugin.setTextInputEditingState(SourceFile:441)
at io.flutter.plugin.editing.TextInputPlugin$1.setEditingState(SourceFile:141)
at io.flutter.embedding.engine.systemchannels.TextInputChannel$1.onMethodCall(SourceFile:99)
at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(SourceFile:233)
at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(SourceFile:85)
at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(SourceFile:972)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:336)
at android.os.Looper.loop(Looper.java:174)
at android.app.ActivityThread.main(ActivityThread.java:7356)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
)
#0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:158)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:306)
#2      _getZoneSpecification.<anonymous closure>.<anonymous closure> (package:bd_vessel/extension/errortrace/internal/error_trace_utils.dart:90)
#3      _rootRunUnary (dart:async/zone.dart:1362)
#4      _CustomZone.runUnary (dart:async/zone.dart:1265)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:152)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:717)
#7      Future._propagateToListeners (dart:async/future_impl.dart:746)
#8      Future._completeWithValue (dart:async/future_impl.dart:552)
#9      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:590)
#10     _getZoneSpecification.<anonymous closure>.<anonymous closure> (package:bd_vessel/extension/errortrace/internal/error_trace_utils.dart:83)
#11     _rootRun (dart:async/zone.dart:1354)
#12     _CustomZone.run (dart:async/zone.dart:1258)
#13     _CustomZone.runGuarded (dart:async/zone.dart:1162)
#14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)

**Comment by eggfly** [comment]
No demo code here temporarily. Assign to myself and digging the reason for it.
