### ISSUE TITLE
Failed assertion: line 270 pos 12: 'firstIndex == 0 || childScrollOffset(firstChild!)! - scrollOffset <= precisionErrorTolerance': is not true.

### ISSUE THREAD

**Issue by michep** [flutter/flutter#94859]
I have this error, but cannot isolate the same exception with simple example application.

doctor -v output:

```
PS D:\Projects\schoosch> flutter doctor -v
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.22000.348], locale ru-RU)
    • Flutter version 2.5.3 at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (8 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at d:\AndroidSDK
    • Platform android-30, build-tools 29.0.2
    • ANDROID_SDK_ROOT = d:\AndroidSDK
    • Java binary at: d:\java\jdk\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.62.3)
    • VS Code at C:\Users\mchep\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.29.0

[√] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 96.0.4664.93
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 96.0.1054.43

! Doctor found issues in 1 category.
```

run --verbose output:

```
PS D:\Projects\schoosch> flutter run --verbose
[ +106 ms] executing: [D:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +529 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 18116933e77adc82f80866c928266a5b4f1ed645
[   +1 ms] executing: [D:\flutter/] git tag --points-at 18116933e77adc82f80866c928266a5b4f1ed645
[ +271 ms] Exit code 0 from: git tag --points-at 18116933e77adc82f80866c928266a5b4f1ed645
[   +1 ms] 2.5.3
[  +13 ms] executing: [D:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +45 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [D:\flutter/] git ls-remote --get-url origin
[  +36 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +135 ms] executing: [D:\flutter/] git rev-parse --abbrev-ref HEAD
[  +39 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable

... skip ...

[+1002 ms] Activating Dart DevTools... (completed in 15,4s)
[+1088 ms] The Flutter DevTools debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:62537/hyXqHE69qBc=/
[+16489 ms] I/michep.schoosc(12161): Background young concurrent copying GC freed 46731(1828KB) AllocSpace objects, 0(0B) LOS objects, 20% free, 4626KB/5848KB, paused 2.605ms total 110.189ms
[ +603 ms] W/michep.schoosc(12161): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
[ +533 ms] I/michep.schoosc(12161): Background young concurrent copying GC freed 29950(1302KB) AllocSpace objects, 0(0B) LOS objects, 22% free, 4525KB/5848KB, paused 4.011ms total 120.991ms
[+19532 ms] 
                     ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
                     The following assertion was thrown during performLayout():
                     'package:flutter/src/rendering/sliver_fixed_extent_list.dart': Failed assertion: line 270 pos 12:
                     'firstIndex == 0 || childScrollOffset(firstChild!)! - scrollOffset <= precisionErrorTolerance': is
                     not true.

                     Either the assertion indicates an error in the framework itself, or we should provide substantially
                     more information in this error message to help you determine and fix the underlying cause.
                     In either case, please report this assertion by filing a bug on GitHub:
                       https://github.com/flutter/flutter/issues/new?template=2_bug.md

                     The relevant error-causing widget was:
                       PageView PageView:file:///D:/Projects/schoosch/lib/widgets/teacher_schedule_switcher.dart:26:27

                     When the exception was thrown, this was the stack:
                     #2      RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:270:12)
                     #3      RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
                     #4      RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:137:12)
                     #5      _RenderSliverFractionalPadding.performLayout (package:flutter/src/widgets/sliver_fill.dart:167:11)
                     #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
                     #7      RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:510:13)
                     #8      RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1580:12)
                     #9      RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1489:20)
                     #10     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1713:7)
                     #11     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:885:18)
                     #12     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:453:19)
                     #13     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
                     #14     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
                     #15     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
                     #16     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1080:9)
                     #17     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
                     #21     _invoke (dart:ui/hooks.dart:166:10)
                     #22     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
                     #23     _drawFrame (dart:ui/hooks.dart:129:31)
                     (elided 5 frames from class _AssertionError and dart:async)

                     The following RenderObject was being processed when the exception was fired: RenderSliverFillViewport#ef75c relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE:
                       needs compositing
                       creator: _SliverFillViewportRenderObjectWidget ← _SliverFractionalPadding ← SliverFillViewport ←
                         Viewport ← IgnorePointer-[GlobalKey#19ef6] ← Semantics ← Listener ← _GestureSemantics ←
                         RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#5cc28] ← Listener ← _ScrollableScope
                         ← _ScrollSemantics-[GlobalKey#d57c1] ← ⋯
                       parentData: paintOffset=Offset(0.0, 0.0) (can use size)
                       constraints: SliverConstraints(AxisDirection.right, GrowthDirection.forward, ScrollDirection.idle,
                         scrollOffset: 83170697.1, remainingPaintExtent: 411.4, crossAxisExtent: 559.4, crossAxisDirection:
                         AxisDirection.down, viewportMainAxisExtent: 411.4, remainingCacheExtent: 411.4, cacheOrigin: 0.0)
                       geometry: SliverGeometry(scrollExtent: Infinity, paintExtent: 411.4, maxPaintExtent: Infinity,
                         hasVisualOverflow: true, cacheExtent: 411.4)
                       currently live children: 202151 to 202151
                     This RenderObject had the following descendants (showing up to depth 5):
                         child with index 202151: RenderIndexedSemantics#0a460
                           child: RenderRepaintBoundary#9595f
                             child: RenderRepaintBoundary#3a76a
                               child: RenderCustomPaint#e27c9
                                 child: RenderRepaintBoundary#1c78c
                     ════════════════════════════════════════════════════════════════════════════════════════════════════
[+24943 ms] W/System  (12161): Ignoring header X-Firebase-Locale because its value was null.
[ +379 ms] D/FirebaseAuth(12161): Notifying id token listeners about user ( IHXhRkUcHWRfk1JGusDI3os4IvU2 ).
```

**Comment by danagbemava-nc** [comment]
Hi @michep, there are various reasons as to why this can happen, kindly provide a complete minimal reproducible code sample to help better address the issue. 

Thank you

**Comment by nt4f04uNd** [comment]
See https://github.com/flutter/flutter/issues/95101 which has a description of the problem and reproduction steps

**Comment by Piinks** [comment]
Closing per last comment as a duplicate, please follow up there. Thanks!
