### ISSUE TITLE
[Crash] Error during updateTexImage

### ISSUE THREAD

**Issue by AlexV525** [flutter/flutter#94916]
This is the most frequent crash on our published apps. It affects 50+ devices with more than 300 times crashes, but we can't reproduce this when testing. For some security reasons, I can't provide the core part of our project at present. Please let me know if there is further information needed.

## Related issues
#53497, #87635

## Context

We're using `PlatformView` to serve the camera native view. This problem, as I observed, mostly happened when users tried to release the `PlatformView` by quitting the page.

## Devices
![image](https://user-images.githubusercontent.com/15884415/145356344-0d81f03e-28a2-4279-b661-ca8aec67cc17.png)

## Environment
Flutter: 2.5.3

## Logcat

Below logs show different stack traces when crashed.

<details>
<summary>First sample</summary>

```
12-09 15:39:21.880 7370 25541 E ConsumerBase: [SurfaceTexture-0-7370-0] New fence has invalid state
12-09 15:39:21.880 7370 25541 E OpenGLRenderer: [SurfaceTexture-0-7370-0] syncForReleaseLocked: error adding release fence: Invalid argument (-22)
12-09 15:39:21.881 7370 25541 E flutter : [ERROR:flutter/fml/platform/android/jni_util.cc(182)] java.lang.RuntimeException: Error during updateTexImage (see logcat for details)
12-09 15:39:21.881 7370 25541 E flutter : at android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
12-09 15:39:21.881 7370 25541 E flutter : at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:248)
12-09 15:39:21.881 7370 25541 E flutter : at io.flutter.embedding.engine.renderer.SurfaceTextureWrapper.updateTexImage(Unknown Source:7)
12-09 15:39:21.881 7370 25541 E flutter :
12-09 15:39:21.881 7370 25541 F flutter : [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1247)] Check failed: fml::jni::CheckException(env).
12-09 15:39:21.884 7370 25534 E fdsan : attempted to close file descriptor 239, expected to be unowned, actually owned by unique_fd 0x7270bf699c
12-09 15:39:22.011 11727 11727 F DEBUG : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
12-09 15:39:22.012 11727 11727 F DEBUG : Build fingerprint: 'HUAWEI/SEA-AL10/HWSEA-A:10/HUAWEISEA-AL10/102.0.0.210C00:user/release-keys'
12-09 15:39:22.012 11727 11727 F DEBUG : Revision: '0'
12-09 15:39:22.012 11727 11727 F DEBUG : ABI: 'arm64'
12-09 15:39:22.012 11727 11727 F DEBUG : SYSVMTYPE: Maple
12-09 15:39:22.012 11727 11727 F DEBUG : APPVMTYPE: Unknown
12-09 15:39:22.016 11727 11727 F DEBUG : Timestamp: 2021-12-09 15:39:22+0800
12-09 15:39:22.016 11727 11727 F DEBUG : pid: 7370, tid: 25534, name: Binder:7370_8 >>> com.our.package <<<
12-09 15:39:22.016 11727 11727 F DEBUG : uid: 10205
12-09 15:39:22.016 11727 11727 F DEBUG : signal 35 (<debuggerd signal>), code -1 (SI_QUEUE), fault addr --------
12-09 15:39:22.016 11727 11727 F DEBUG : Abort message: 'attempted to close file descriptor 239, expected to be unowned, actually owned by unique_fd 0x7270bf699c'
12-09 15:39:22.016 11727 11727 F DEBUG : x0 0000000000000000 x1 00000000000063be x2 0000000000000023 x3 000000730d64d760
12-09 15:39:22.016 11727 11727 F DEBUG : x4 3936666230373237 x5 3936666230373237 x6 3936666230373237 x7 6339393666623037
12-09 15:39:22.016 11727 11727 F DEBUG : x8 00000000000000f0 x9 a41198a25933b29f x10 0000000000000000 x11 00000073f38efa13
12-09 15:39:22.016 11727 11727 F DEBUG : x12 00000073f38ef9b9 x13 000000730d64d32a x14 0000000000000000 x15 0000000000000030
12-09 15:39:22.016 11727 11727 F DEBUG : x16 00000073f39afa08 x17 00000073f398f7c0 x18 00000072fab8a000 x19 0000000000001cca
12-09 15:39:22.016 11727 11727 F DEBUG : x20 00000000000063be x21 000000730d64e020 x22 00000073f57b1974 x23 0000000000000001
12-09 15:39:22.016 11727 11727 F DEBUG : x24 000000730d64d550 x25 000000730d64d4d0 x26 000000730d64d490 x27 0000000000000000
12-09 15:39:22.016 11727 11727 F DEBUG : x28 0000000000000000 x29 000000730d64d840
12-09 15:39:22.016 11727 11727 F DEBUG : sp 000000730d64d410 lr 00000073f3947ce4 pc 00000073f3947d04
12-09 15:39:22.034 11727 11727 F DEBUG :
12-09 15:39:22.034 11727 11727 F DEBUG : backtrace:
12-09 15:39:22.034 11727 11727 F DEBUG : #00 pc 0000000000073d04 /apex/com.android.runtime/lib64/bionic/libc.so (fdsan_error(char const*, ...)+388) (BuildId: b91c775ccc9b0556e91bc575a2511cd0)
12-09 15:39:22.034 11727 11727 F DEBUG : #01 pc 0000000000073b1c /apex/com.android.runtime/lib64/bionic/libc.so (android_fdsan_close_with_tag+728) (BuildId: b91c775ccc9b0556e91bc575a2511cd0)
12-09 15:39:22.034 11727 11727 F DEBUG : #02 pc 0000000000074288 /apex/com.android.runtime/lib64/bionic/libc.so (close+16) (BuildId: b91c775ccc9b0556e91bc575a2511cd0)
12-09 15:39:22.034 11727 11727 F DEBUG : #03 pc 000000000006d570 /system/lib64/libbinder.so (android::release_object(android::sp<android::ProcessState> const&, flat_binder_object const&, void const*, unsigned long*)+396) (BuildId: 7de369077bc2b209f78d8c95a30df153)
12-09 15:39:22.034 11727 11727 F DEBUG : #04 pc 000000000006de94 /system/lib64/libbinder.so (android::Parcel::freeDataNoInit()+132) (BuildId: 7de369077bc2b209f78d8c95a30df153)
12-09 15:39:22.034 11727 11727 F DEBUG : #05 pc 00000000000658a4 /system/lib64/libbinder.so (android::IPCThreadState::executeCommand(int)+1556) (BuildId: 7de369077bc2b209f78d8c95a30df153)
12-09 15:39:22.034 11727 11727 F DEBUG : #06 pc 00000000000651dc /system/lib64/libbinder.so (android::IPCThreadState::getAndExecuteCommand()+156) (BuildId: 7de369077bc2b209f78d8c95a30df153)
12-09 15:39:22.034 11727 11727 F DEBUG : #07 pc 0000000000065a78 /system/lib64/libbinder.so (android::IPCThreadState::joinThreadPool(bool)+60) (BuildId: 7de369077bc2b209f78d8c95a30df153)
12-09 15:39:22.034 11727 11727 F DEBUG : #08 pc 000000000008bba8 /system/lib64/libbinder.so (android::PoolThread::threadLoop()+24) (BuildId: 7de369077bc2b209f78d8c95a30df153)
12-09 15:39:22.034 11727 11727 F DEBUG : #09 pc 00000000000136d8 /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+288) (BuildId: b586b93b2a903478a0591b572d330c87)
12-09 15:39:22.034 11727 11727 F DEBUG : #10 pc 0000000000104fec /system/lib64/libandroid_runtime.so (android::AndroidRuntime::javaThreadShell(void*)+140) (BuildId: a92c351fcfda20f10ff25c04ed924f5f)
12-09 15:39:22.034 11727 11727 F DEBUG : #11 pc 00000000000cf7c0 /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+36) (BuildId: b91c775ccc9b0556e91bc575a2511cd0)
12-09 15:39:22.034 11727 11727 F DEBUG : #12 pc 00000000000721a8 /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: b91c775ccc9b0556e91bc575a2511cd0)
```
</details>

<details>
<summary>Second sample</summary>

```
12-07 13:48:24.445 11516 11541 E GLConsumer: [SurfaceTexture-0-11516-0] doGLFenceWait: error dup'ing fence fd: 9
12-07 13:48:24.451 11516 11541 E flutter : [ERROR:flutter/fml/platform/android/jni_util.cc(182)] java.lang.RuntimeException: Error during updateTexImage (see logcat for details)
12-07 13:48:24.451 11516 11541 E flutter : at android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
12-07 13:48:24.451 11516 11541 E flutter : at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:243)
12-07 13:48:24.451 11516 11541 E flutter : at io.flutter.embedding.engine.renderer.SurfaceTextureWrapper.updateTexImage(Unknown Source:7)
12-07 13:48:24.451 11516 11541 E flutter :
12-07 13:48:24.451 11516 11541 F flutter : [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1247)] Check failed: fml::jni::CheckException(env).
```
</details>

**Comment by AlexV525** [comment]
cc @chinmaygarde @jason-simmons

**Comment by stuartmorgan** [comment]
It looks like this was Virtual Display; does it still happen with the new platform view implementation?

**Comment by AlexV525** [comment]
Couldn't switch to it since the project is outdated. Closing,
