### ISSUE TITLE
Exception: "Multiple widgets used the same GlobalKey."

### ISSUE THREAD

**Issue by rohansohonee** [flutter/flutter#95009]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Tap on fab button to see the exception

**Expected results:** 
The fab button should not cause this exception. The fab button's exit animation transition should handle for widgets which use the keys.

**Actual results:** 
This exception is thrown: "Multiple widgets used the same GlobalKey".

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final String title;

  const MyHomePage({
    Key? key,
    required this.title,
  }) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final _formKey = GlobalKey<FormState>();
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });

    // simulate receiving some async data
    Future.delayed(const Duration(milliseconds: 50), () {
      setState(() {
        _counter++;
      });
    });
  }

  @override
  Widget build(BuildContext context) {
    Widget fabButton = FloatingActionButton(
      onPressed: _incrementCounter,
      tooltip: 'Increment',
      child: const Icon(Icons.add),
    );

    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: _counter % 2 == 0
          ? // eg: say we needed a form widget here to validate some info
          Form(key: _formKey, child: fabButton)
          : fabButton,
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
======== Exception caught by widgets library =======================================================
The following assertion was thrown while finalizing the widget tree:
Multiple widgets used the same GlobalKey.

The key [LabeledGlobalKey<FormState>#6b9ff] was used by multiple widgets. The parents of those widgets were:
- Transform(dependencies: [Directionality], renderObject: RenderTransform#13d34 relayoutBoundary=up3)
- Transform(dependencies: [Directionality], renderObject: RenderTransform#c9b44 relayoutBoundary=up3)
A GlobalKey can only be specified on one widget at a time in the widget tree.
When the exception was thrown, this was the stack: 
#0      BuildOwner._debugVerifyGlobalKeyReservation.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:flutter/src/widgets/framework.dart:2774:13)
#1      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:539:8)
#2      BuildOwner._debugVerifyGlobalKeyReservation.<anonymous closure>.<anonymous closure> (package:flutter/src/widgets/framework.dart:2721:20)
#3      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:539:8)
#4      BuildOwner._debugVerifyGlobalKeyReservation.<anonymous closure> (package:flutter/src/widgets/framework.dart:2717:35)
#5      BuildOwner._debugVerifyGlobalKeyReservation (package:flutter/src/widgets/framework.dart:2782:6)
#6      BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2841:11)
#7      BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2922:8)
#8      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:884:19)
#9      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#10     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
#11     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#12     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#16     _invoke (dart:ui/hooks.dart:150:10)
#17     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#18     _drawFrame (dart:ui/hooks.dart:114:31)
(elided 3 frames from dart:async)
====================================================================================================
```

```
[√] Flutter (Channel stable, 2.8.0, on Microsoft Windows [Version 10.0.19043.1348], locale en-IN)
    • Flutter version 2.8.0 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (2 days ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Rohan Sohonee\AppData\Local\Android\Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.62.3)
    • VS Code at C:\Users\Rohan Sohonee\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 96.0.4664.93
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 96.0.1054.43

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Looking at the code, you are passing global key to a `Form` widget, which might be leading to the exception you are getting, which indicates it's the same issue as https://github.com/flutter/flutter/issues/80927, so please follow-up in it for further updates.
Closing this as a duplicate. If you disagree, write in comments and I'll reopen.
