### ISSUE TITLE
Dart compiler randomly crashes when making changes to Flutter source code for contribution

### ISSUE THREAD

**Issue by TahaTesser** [flutter/flutter#95014]
Often I am seeing dart compiler crash messages especially on the desktop for macOS & Windows, haven't tried Linux yet

The crash is inconsistent, sometimes it crashes on the first change, and other times, it requires changing value multiple times for the crash to occur.

This issue crashes the app so many times in my workflow, I switched to Windows machine since launch time on Windows is faster than macOS (at least for me).

### Preview for when the first change on launch crashes the app

https://user-images.githubusercontent.com/48603081/145588897-abb779ad-ed1a-4582-9813-283ba16ebc92.mov

### Preview for when same changes don't crash the app

https://user-images.githubusercontent.com/48603081/145590879-898cdd83-b734-45fd-9ffc-996ec490c7ca.mov

and sometimes the app doesn't crash even if do the same which crashed the app previously, it is very random, unfortunately, sometimes crashes are back to back which makes me launch the app again and again. 

Also, this is not just ElevatedButton, the same thing happens in `icon_button.dart` etc.

```
Restarted application in 897ms.
Reloaded 2 of 582 libraries in 298ms.
Reloaded 1 of 582 libraries in 235ms.
Unhandled exception:
package:flutter/src/material/elevated_button.dart: Internal problem: Unhandled null in accessor.
#0      internalProblem (package:front_end/src/fasta/problems.dart:52:5)
#1      unhandled (package:front_end/src/fasta/problems.dart:71:10)
#2      SourceLoader.read (package:front_end/src/fasta/source/source_loader.dart:507:9)

#3      IncrementalCompiler._experimentalInvalidationCreateRebuildBodiesBuilders (package:front_end/src/fasta/incremental_compiler.dart:762:64)
#4      IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:339:11)
<asynchronous suspension>
#5      IncrementalCompiler.compile (package:vm/incremental_compiler.dart:69:50)
<asynchronous suspension>
#6      FrontendCompiler.recompileDelta (package:frontend_server/frontend_server.dart:788:9)
<asynchronous suspension>

the Dart compiler exited unexpectedly.
the Dart compiler exited unexpectedly.
Exited (1)

```

**Comment by TahaTesser** [comment]
@mraleph 
Do you think this is something actually related to Dart itself? Thanks

**Comment by mraleph** [comment]
@johnniwinther seems like a crash in the incremental compiler?

**Comment by johnniwinther** [comment]
It seems to be an incremental compiler problem. I'll take a look.

**Comment by johnniwinther** [comment]
@TahaTesser what Dart version are you using?

**Comment by TahaTesser** [comment]
@johnniwinther 
Thanks for taking a look
```
[✓] Flutter (Channel master, 2.6.0-12.0.pre.984, on macOS 12.0.1 21A559
    darwin-x64, locale en-EE)
    • Flutter version 2.6.0-12.0.pre.984 at /Users/tahatesser/Code/flutter
    • Upstream repository git@github.com:NevercodeHQ/flutter.git
    • Framework revision 6b51924de3 (17 hours ago), 2021-12-09 16:49:10 -0500
    • Engine revision 2516ea636d
    • Dart version 2.16.0 (build 2.16.0-85.0.dev)
    • DevTools version 2.9.1
```

**Comment by maheshmnj** [comment]
Hi @TahaTesser, Thanks for filing the issue. I can reproduce the issue on the latest master channel but not on `stable 2.8.0`.

<details>
<summary>logs</summary>

```
Launching lib/main.dart on macOS in debug mode...
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:x86_64, id:6A745C96-D83E-5C8D-8EE9-5958E598001B }
{ platform:macOS, name:Any Mac }
Connecting to VM Service at ws://127.0.0.1:51577/xQPiehLHMN0=/ws
Reloaded 2 of 582 libraries in 880ms.
Reloaded 1 of 582 libraries in 481ms.
Unhandled exception:
package:flutter/src/material/list_tile.dart: Internal problem: Unhandled null in accessor.
#0      internalProblem (package:front_end/src/fasta/problems.dart:52:5)
#1      unhandled (package:front_end/src/fasta/problems.dart:71:10)
#2      SourceLoader.read (package:front_end/src/fasta/source/source_loader.dart:507:9)
#3      IncrementalCompiler._experimentalInvalidationCreateRebuildBodiesBuilders (package:front_end/src/fasta/incremental_compiler.dart:762:64)
#4      IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:339:11)
<asynchronous suspension>
#5      IncrementalCompiler.compile (package:vm/incremental_compiler.dart:69:50)

<asynchronous suspension>
#6      FrontendCompiler.recompileDelta (package:frontend_server/frontend_server.dart:788:9)
<asynchronous suspension>

the Dart compiler exited unexpectedly.
the Dart compiler exited unexpectedly.
Exited (1)

```
</details>



<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.8.0, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.8.0 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (5 days ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • iPhone 11 (mobile) • FC644E6C-7F02-40E5-9998-1F0CD162FBD8 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 12.0.1 21A559
      darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome
      96.0.4664.93

• No issues found!
```

```
[✓] Flutter (Channel master, 2.6.0-12.0.pre.1002, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.6.0-12.0.pre.1002 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9de8849905 (9 hours ago), 2021-12-12 20:54:15 -0500
    • Engine revision f16c96c31f
    • Dart version 2.16.0 (build 2.16.0-85.0.dev)
    • DevTools version 2.9.1

⢿
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • iPhone 11 (mobile) • FC644E6C-7F02-40E5-9998-1F0CD162FBD8 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 12.0.1 21A559
      darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome
      96.0.4664.93

• No issues found!
```

</details>

**Comment by TahaTesser** [comment]
I am seeing this on Android 
```console
Launching lib\main.dart on Android SDK built for x86 in debug mode...
lib\main.dart:1
Unhandled exception:
package:flutter/src/material/dropdown.dart: Internal problem: Unhandled null in accessor.
package:flutter/…/material/dropdown.dart:1
#0      internalProblem (package:front_end/src/fasta/problems.dart:52:5)
#1      unhandled (package:front_end/src/fasta/problems.dart:71:10)
#2      SourceLoader.read (package:front_end/src/fasta/source/source_loader.dart:507:9)
#3      IncrementalCompiler._experimentalInvalidationCreateRebuildBodiesBuilders (package:front_end/src/fasta/incremental_compiler.dart:762:64)
#4      IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:339:11)
<asynchronous suspension>
#5      IncrementalCompiler.compile (package:vm/incremental_compiler.dart:69:50)


```

**Comment by johnniwinther** [comment]
I have a fix in progress: https://dart-review.googlesource.com/c/sdk/+/223420

**Comment by TahaTesser** [comment]
@johnniwinther 
This seems to have gotten worse on the latest Flutter `master` since last time (Friday).
Now app crashes on launch

https://user-images.githubusercontent.com/48603081/145801177-96fb5852-7878-4b58-a179-314191a166aa.mp4

**Comment by mraleph** [comment]
Note that the fix has not landed yet.

**Comment by TahaTesser** [comment]
@mraleph @johnniwinther 
Appreciate such a fast fix, waiting for it to land.
I wanted to report it got worse for some reason, now it crashes on launch. Repeating it few times launches the app then crashes on change again

**Comment by johnniwinther** [comment]
The crash can be triggered by a change in order in which the files are given to the incremental compiler, which makes this potentially non-deterministic.

**Comment by TahaTesser** [comment]
Thanks! Looks like this has landed in Flutter, closing as fixed
