### ISSUE TITLE
kIsWeb tree shaking not working correctly

### ISSUE THREAD

**Issue by vendelin8** [flutter/flutter#95018]
## Steps to Reproduce
Minimal example:
```dart
library cross_image;

import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:extended_image/extended_image.dart';

dynamic imgWidget(String imPath) => kIsWeb ? imPath : File(imPath);
```

1. I start a debug session in vscode

**Expected results:** 
Compile, work as expected

**Actual results:** 
At first it was inlined in the bigger flutter application, where I wanted to use `ExtendedImage.network` for web and `ExtendedImage.file` for mobile, but it didn't compile, same error as below. Then I created this tiny package I import. When I used `Image` instead of `ExtendedImage`, it worked, but I couldn't crop it. With `ExtendedImage` when I try to build it on web, I get the following:
```Launching lib/main.dart on Chrome in debug mode...
lib/main.dart:1
: Error: The class 'File' is abstract and can't be instantiated.
../…/lib/cross_image.dart:7
dynamic imgWidget(String imPath) => kIsWeb ? imPath : File(imPath);
                                                      ^^^^
Failed to compile application.
Exited (sigterm)
```
Above, the `^` signs are under `File`.

<details>
  <summary>Logs</summary>

```
flutter run --verbose
[  +81 ms] executing: uname -m
[  +34 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +7 ms] executing: [/opt/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +6 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 18116933e77adc82f80866c928266a5b4f1ed645
[        ] executing: [/opt/flutter/] git tag --points-at 18116933e77adc82f80866c928266a5b4f1ed645
[  +17 ms] Exit code 0 from: git tag --points-at 18116933e77adc82f80866c928266a5b4f1ed645
[        ] 2.5.3
[  +13 ms] executing: [/opt/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/opt/flutter/] git ls-remote --get-url origin
[   +5 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] git@github.com:flutter/flutter.git
[ +121 ms] executing: [/opt/flutter/] git rev-parse --abbrev-ref HEAD
[   +9 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +80 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +100 ms] executing: /opt/android-sdk/platform-tools/adb devices -l
[  +63 ms] List of devices attached
[   +7 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +116 ms] Skipping pub get: version match.
```
Then about 100 lines of `Found plugin`, the following lines in between:
```
[  +17 ms] Generating /home/panda/og/src/gitlab.com/vendelin/pacmin/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +678 ms] Launching lib/main.dart on Chrome in debug mode...
[ +125 ms] Updating assets
[ +177 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
[  +11 ms] Waiting for connection from debug service on Chrome...
```
Finally:
```
[  +67 ms] <- reset
[  +11 ms] /opt/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /opt/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/opt/flutter/bin/cache/flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true
--output-dill /tmp/flutter_tools.ITVQNP/flutter_tool.YSKOKD/app.dill --libraries-spec file:///opt/flutter/bin/cache/flutter_web_sdk/libraries.json --packages
/home/panda/og/src/gitlab.com/vendelin/pacmin/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation
--filesystem-root /tmp/flutter_tools.ITVQNP/flutter_tools.HPHSPH --filesystem-scheme org-dartlang-app --initialize-from-dill
build/b1b715402d823b7fd5c2b68d2edcb2ce.cache.dill.track.dill --platform file:///opt/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk_sound.dill
--sound-null-safety
[  +15 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+10168 ms] ../cross_image/lib/cross_image.dart:7:55: Error: The class 'File' is abstract and can't be instantiated.
[   +1 ms] dynamic imgWidget(String imPath) => kIsWeb ? imPath : File(imPath);
[        ]                                                       ^^^^
[+30904 ms] Waiting for connection from debug service on Chrome... (completed in 41,3s)
[   +1 ms] Synced 0.0MB.
[        ] Failed to compile application.
[   +5 ms] "flutter run" took 43 453ms.
[   +7 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:669:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>
           
           
[ +235 ms] ensureAnalyticsSent: 232ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

```
```
`flutter analyze` prints some warnings, none of them is about this part of the project.

```
```
```
flutter doctor -v
[✓] Flutter (Channel stable, 2.5.3, on Arch Linux 5.15.6-arch2-1, locale hu_HU.UTF-8)
    • Flutter version 2.5.3 at /opt/flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision 18116933e7 (8 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /opt/android-sdk
    • Platform android-31, build-tools 30.0.2
    • ANDROID_HOME = /opt/android-sdk
    • Java binary at: /usr/lib/jvm/java-11-openjdk/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+8)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/chromium

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Chromium 96.0.4664.93 Arch Linux

! Doctor found issues in 1 category.
```

```
```

</details>

**Comment by vendelin8** [comment]
When I removed `extended_image` dependency and import from my tiny library package, it compiles, but still, there's something going on, why I need to add a library package to compile a project like this.

**Comment by darshankawar** [comment]
@vendelin8 
Are you referring to https://pub.dev/packages/extended_image plugin ? If so, that's a third party plugin which seem to have been published just recently, so any issue with using it, should be reported in dedicated plugin repo.

**Comment by vendelin8** [comment]
I replaced that code part not to rely on this, closing for now, thanks for looking.
