### ISSUE TITLE
SIGABRT on TimeToFirstNativeMessageFromIsolateInNewVM benchmark

### ISSUE THREAD

**Issue by WasserEsser** [flutter/flutter#95064]
The `DartNativeBenchmarks/TimeToFirstNativeMessageFromIsolateInNewVM` benchmark exited with a SIGABRT signal for an unknown reason during a PR check. A previous run with no significant code changes as well as a rerun with the same code both ran successfully.

Full logs available here: https://cirrus-ci.com/task/4928706098495488?logs=test_host#L10859

```
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>2021-12-11T01:30:45+00:00
Running /tmp/clean_engine/src/out/host_debug_unopt/exe.unstripped/shell_benchmarks
Run on (32 X 2200 MHz CPU s)
CPU Caches:
  L1 Data 32 KiB (x16)
  L1 Instruction 32 KiB (x16)
  L2 Unified 256 KiB (x16)
  L3 Unified 56320 KiB (x1)
Load Average: 1.66, 8.92, 9.40
***WARNING*** Library was built as DEBUG. Timings may be affected.
----------------------------------------------------------------------------------------------------------
Benchmark                                                                Time             CPU   Iterations
----------------------------------------------------------------------------------------------------------
DartNativeBenchmarks/TimeToFirstNativeMessageFromIsolateInNewVM   50296446 ns      4612579 ns          100
[ERROR:flutter/fml/backtrace.cc(116)] Caught signal SIGABRT during program execution.
Frame 0: 0x7fe6bd58642a abort
Frame 1: 0x21148b9 Unknown
Frame 2: 0x2333393 std::__1::__function::__value_func<>::operator()()
Frame 3: 0x2333324 std::__1::function<>::operator()()
Frame 4: 0x2332a5a fml::tracing::(anonymous namespace)::FlutterTimelineEvent()
Frame 5: 0x2332afe fml::tracing::TraceEvent0()
Frame 6: 0x230b33f fml::ConcurrentMessageLoop::WorkerMain()
Frame 7: 0x230c110 fml::ConcurrentMessageLoop::ConcurrentMessageLoop()::$_0::operator()()
Frame 8: 0x230c06d std::__1::__invoke<>()
Frame 9: 0x230c015 std::__1::__thread_execute<>()
Frame 10: 0x230bde8 std::__1::__thread_proxy<>()
Frame 11: 0x7fe6bde044a4 start_thread
Frame 12: 0x7fe6bd63ad0f __clone

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>


Running command "/tmp/clean_engine/src/out/host_debug_unopt/exe.unstripped/shell_benchmarks --icu-data-file-path=/tmp/clean_engine/src/out/host_debug_unopt/icudtl.dat"


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


Failed Command:

/tmp/clean_engine/src/out/host_debug_unopt/exe.unstripped/shell_benchmarks --icu-data-file-path=/tmp/clean_engine/src/out/host_debug_unopt/icudtl.dat

Exit Code: -6



!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


Traceback (most recent call last):
  File "/tmp/clean_engine/src/flutter/testing/run_tests.py", line 635, in <module>
    sys.exit(main())
  File "/tmp/clean_engine/src/flutter/testing/run_tests.py", line 628, in main
    RunEngineBenchmarks(build_dir, engine_filter)
  File "/tmp/clean_engine/src/flutter/testing/run_tests.py", line 242, in RunEngineBenchmarks
    RunEngineExecutable(build_dir, 'shell_benchmarks', filter, icu_flags)
  File "/tmp/clean_engine/src/flutter/testing/run_tests.py", line 143, in RunEngineExecutable
    RunCmd(test_command, cwd=cwd, forbidden_output=forbidden_output, expect_failure=expect_failure, env=env)
  File "/tmp/clean_engine/src/flutter/testing/run_tests.py", line 62, in RunCmd
    raise Exception('Command "%s" exited with code %d.' % (command_string, process.returncode))
Exception: Command "/tmp/clean_engine/src/out/host_debug_unopt/exe.unstripped/shell_benchmarks --icu-data-file-path=/tmp/clean_engine/src/out/host_debug_unopt/icudtl.dat" exited with code -6.
````

**Comment by maheshmnj** [comment]
HI @WasserEsser, Thanks for filing the issue. Please share the output of `flutter doctor -v` and are there any known reproducible steps?

Thanks

**Comment by WasserEsser** [comment]
It just seems to be some weird edge case that is difficult to debug.

**Comment by maheshmnj** [comment]
Thanks for the info will leave this open for further investigation from the team.

**Comment by jonahwilliams** [comment]
This is not likely to be actionable
