### ISSUE TITLE
Precision error in RenderSliverFixedExtentBoxAdaptor

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#95101]
https://github.com/flutter/flutter/pull/30979 fixed the index detection error, but it didn't consider that doing so in its turn also creates another precision error on this line.

https://github.com/flutter/flutter/blob/a3dc90c4f51523fd3f8df6eee3d79239a3c8de52/packages/flutter/lib/src/rendering/sliver_fixed_extent_list.dart#L270

Consider an example where:
```
scrollOffset = 392.7272727256901
itemExtent = 392.72727272727275
```

In this case `getMinChildIndexForScrollOffset` already returns 1 because of the `scrollOffset / itemExtent` and the precision error is taken from this.

But later the assertion in question checks for precision of  `childScrollOffset(firstChild!)! - itemExtent`, where `childScrollOffset` (I assume in this case in particular, not always, but I'm not sure) returns `itemExtent`, which gives us a value bigger than `precisionErrorTolerance` and fails the assertion.

## Steps to Reproduce

1. Execute `flutter test` on the code sample

**Expected results:** Test passes

**Actual results:** Test fails

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('PageView rounding issue', (WidgetTester tester) async {
    final PageController controller = PageController(initialPage: 152);

    await tester.pumpWidget(
      Center(
        child: SizedBox(
          width: 392.72727272727275,
          child: Directionality(
            textDirection: TextDirection.ltr,
            child: PageView.builder(
              controller: controller,
              itemCount: 366,
              itemBuilder: (BuildContext context, int index) {
                return const SizedBox();
              },
            ),
          ),
        ),
      ),
    );

    controller.jumpToPage(365);
    await tester.pump();
  });
}
```
</details>

<details>
  <summary>Logs</summary>

```
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
'package:flutter/src/rendering/sliver_fixed_extent_list.dart': Failed assertion: line 270 pos 12:
'firstIndex == 0 || childScrollOffset(firstChild!)! - scrollOffset <= precisionErrorTolerance': is
not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack:
#2      RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:270:12)
#3      RenderObject.layout (package:flutter/src/rendering/object.dart:1882:7)
#4      RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:137:12)
#5      _RenderSliverFractionalPadding.performLayout (package:flutter/src/widgets/sliver_fill.dart:167:11)
#6      RenderObject.layout (package:flutter/src/rendering/object.dart:1882:7)
#7      RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:510:13)
#8      RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1580:12)
#9      RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1489:20)
#10     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1729:7)
#11     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:887:18)
#12     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1131:23)
#13     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#14     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
#15     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#16     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:995:9)
#19     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#20     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:982:27)
#21     WidgetTester.pump.<anonymous closure> (package:flutter_test/src/widget_tester.dart:608:53)
#24     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#25     WidgetTester.pump (package:flutter_test/src/widget_tester.dart:608:27)
#26     main.<anonymous closure> (file:///C:/dev/src/flutter/packages/flutter/test/widgets/page_view_test.dart:1123:18)
<asynchronous suspension>
<asynchronous suspension>
(elided 7 frames from class _AssertionError, dart:async, and package:stack_trace)

The following RenderObject was being processed when the exception was fired: RenderSliverFillViewport#4cfb6 relayoutBoundary=up2:
  needs compositing
  creator: _SliverFillViewportRenderObjectWidget ← _SliverFractionalPadding ← SliverFillViewport ←
    Viewport ← IgnorePointer-[GlobalKey#e98c5] ← Semantics ← Listener ← _GestureSemantics ←
    RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#78667] ← Listener ← _ScrollableScope
    ← _ScrollSemantics-[GlobalKey#80202] ← ⋯
  parentData: paintOffset=Offset(0.0, 0.0) (can use size)
  constraints: SliverConstraints(AxisDirection.right, GrowthDirection.forward, ScrollDirection.idle,
    scrollOffset: 143345.5, remainingPaintExtent: 392.7, crossAxisExtent: 600.0, crossAxisDirection:
    AxisDirection.down, viewportMainAxisExtent: 392.7, remainingCacheExtent: 392.7, cacheOrigin: 0.0)
  geometry: SliverGeometry(scrollExtent: 143738.2, paintExtent: 392.7, maxPaintExtent: 143738.2,
    hasVisualOverflow: true, cacheExtent: 392.7)
  currently live children: 365 to 365
This RenderObject had the following descendants (showing up to depth 5):
    child with index 365: RenderIndexedSemantics#922dc
      child: RenderRepaintBoundary#e581e
        child: RenderConstrainedBox#3f624
════════════════════════════════════════════════════════════════════════════════════════════════════
Test failed. See exception logs above.
The test description was: PageView rounding issue

✖ PageView rounding issue
Exited (1)
```

```
[√] Flutter (Channel unknown, 2.6.0-12.0.pre.999, on Microsoft Windows [Version 10.0.19041.1348], locale ru-RU)
    • Flutter version 2.6.0-12.0.pre.999 at C:\dev\src\flutter
    • Upstream repository unknown
    • FLUTTER_GIT_URL = git@github.com:nt4f04und/flutter.git
    • Framework revision 895beb04bb (23 hours ago), 2021-12-10 18:54:10 -0800
    • Engine revision 79f750d4a5
    • Dart version 2.16.0 (build 2.16.0-85.0.dev)
    • DevTools version 2.9.1

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\danya\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.63.0)
    • VS Code at C:\Users\danya\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.29.0

[√] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19041.1348]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 96.0.4664.93
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 96.0.1054.34

! Doctor found issues in 1 category
```
</details>

**Comment by nt4f04uNd** [comment]
The test was inspired by https://github.com/flutter/flutter/issues/83770 - @ngdangnhat thank you!

**Comment by nt4f04uNd** [comment]
Also /cc @chunhtai - in case you have some thoughts for how to change this assert better

**Comment by maheshmnj** [comment]
Hi @nt4f04uNd, Thanks for filing the issue. I am able to reproduce the issue on stable and the master channel. With reduced precision, the test passes and fails with high precision.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.8.0, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.8.0 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (5 days ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • iPhone 11 (mobile) • FC644E6C-7F02-40E5-9998-1F0CD162FBD8 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 12.0.1 21A559
      darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 96.0.4664.93

• No issues found!
```

```
[✓] Flutter (Channel master, 2.6.0-12.0.pre.1002, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.6.0-12.0.pre.1002 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9de8849905 (9 hours ago), 2021-12-12 20:54:15 -0500
    • Engine revision f16c96c31f
    • Dart version 2.16.0 (build 2.16.0-85.0.dev)
    • DevTools version 2.9.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • iPhone 11 (mobile) • FC644E6C-7F02-40E5-9998-1F0CD162FBD8 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 12.0.1 21A559
      darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome
      96.0.4664.93

• No issues found!
```
</details>



<details>
<summary>logs</summary>

```console
mahesh@Maheshs-MacBook-Air-M1 hello % flutter test
00:02 +1: All tests passed!     
mahesh@Maheshs-MacBook-Air-M1 hello % flutter test
Running "flutter pub get" in hello...                            1,437ms
00:11 +0: PageView rounding issue                                                                                         
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
'package:flutter/src/rendering/sliver_fixed_extent_list.dart': Failed assertion: line 270 pos 12:
'firstIndex == 0 || childScrollOffset(firstChild!)! - scrollOffset <= precisionErrorTolerance': is
not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was:
  PageView PageView:file:///Users/mahesh/Desktop/hello/test/widget_test.dart:14:29

When the exception was thrown, this was the stack:
#2      RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:270:12)
#3      RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#4      RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:137:12)
#5      _RenderSliverFractionalPadding.performLayout (package:flutter/src/widgets/sliver_fill.dart:167:11)
#6      RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#7      RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:510:13)
#8      RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1580:12)
#9      RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1489:20)
#10     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1731:7)
#11     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:887:18)
#12     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1131:23)
#13     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#14     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#15     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
#16     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:995:9)
#19     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#20     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:982:27)
#21     WidgetTester.pump.<anonymous closure> (package:flutter_test/src/widget_tester.dart:608:53)
#24     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#25     WidgetTester.pump (package:flutter_test/src/widget_tester.dart:608:27)
#26     main.<anonymous closure> (file:///Users/mahesh/Desktop/hello/test/widget_test.dart:27:18)
<asynchronous suspension>
<asynchronous suspension>
(elided 7 frames from class _AssertionError, dart:async, and package:stack_trace)

The following RenderObject was being processed when the exception was fired: RenderSliverFillViewport#3eeec relayoutBoundary=up2:
  needs compositing
  creator: _SliverFillViewportRenderObjectWidget ← _SliverFractionalPadding ← SliverFillViewport ←
    Viewport ← IgnorePointer-[GlobalKey#58c13] ← Semantics ← Listener ← _GestureSemantics ←
    RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#1faa6] ← Listener ← _ScrollableScope
    ← _ScrollSemantics-[GlobalKey#a5b61] ← ⋯
  parentData: paintOffset=Offset(0.0, 0.0) (can use size)
  constraints: SliverConstraints(AxisDirection.right, GrowthDirection.forward, ScrollDirection.idle,
    scrollOffset: 143345.5, remainingPaintExtent: 392.7, crossAxisExtent: 600.0, crossAxisDirection:
    AxisDirection.down, viewportMainAxisExtent: 392.7, remainingCacheExtent: 392.7, cacheOrigin: 0.0)
  geometry: SliverGeometry(scrollExtent: 143738.2, paintExtent: 392.7, maxPaintExtent: 143738.2,
    hasVisualOverflow: true, cacheExtent: 392.7)
  currently live children: 365 to 365
This RenderObject had the following descendants (showing up to depth 5):
    child with index 365: RenderIndexedSemantics#52f02
      child: RenderRepaintBoundary#06449
        child: RenderConstrainedBox#838b6
════════════════════════════════════════════════════════════════════════════════════════════════════
00:11 +0 -1: PageView rounding issue [E]                                                                                  
  Test failed. See exception logs above.
  The test description was: PageView rounding issue
  
00:11 +0 -1: Some tests failed.                                                                                           
mahesh@Maheshs-MacBook-Air-M1 hello % 
```
</details>

**Comment by Piinks** [comment]
https://github.com/flutter/flutter/issues/58305 was de-duped to resolve here. Please check there if more context is needed. :)

**Comment by nt4f04uNd** [comment]
Thanks @Piinks, can you also dedup the other 3? (see mentions above)

**Comment by chunhtai** [comment]
It looks like getMinChildIndexForScrollOffset allows bigger precision error than the assert does, we should probably fix getMinChildIndexForScrollOffset to only allow smaller precision error so that we don't get caught in between

**Comment by Piinks** [comment]
> can you also dedup the other 3? (see mentions above)

Done! :)
