### ISSUE TITLE
Security exception: Permission Denial: starting Intent

### ISSUE THREAD

**Issue by carlfost** [flutter/flutter#95134]
## Steps to Reproduce

1. Upgrade to the latest VSCode and Flutter
2.  Run Flutter Clean 
3. Flutter Pub Get
4.  Flutter Run

## Logs

<details>
<summary>Logs</summary>

```
```

√  Built build\app\outputs\flutter-apk\app-debug.apk.
ProcessException: Process exited abnormally:
Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.outafire.church_events/.MainActivity (has extras) }
Security exception: Permission Denial: starting Intent { act=android.intent.action.RUN flg=0x30000000 cmp=com.outafire.church_events/.MainActivity (has extras) } from null (pid=18176, uid=2000) not exported from uid 10150
java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.RUN flg=0x30000000 cmp=com.outafire.church_events/.MainActivity (has extras) } from null (pid=18176, uid=2000) not exported from uid 10150
	at com.android.server.wm.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1043)
	at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:760)
	at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:583)
	at com.android.server.wm.ActivityStarter.startActivityMayWait(ActivityStarter.java:1288)
	at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:514)
	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1058)
	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1032)
	at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:3504)
	at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:518)
	at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:172)
	at android.os.ShellCommand.exec(ShellCommand.java:104)
	at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:9774)
	at android.os.Binder.shellCommand(Binder.java:881)
	at android.os.Binder.onTransact(Binder.java:765)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:4498)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2741)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)
	
flutter doctor -v
[√] Flutter (Channel stable, 2.8.0, on Microsoft Windows [Version 10.0.19043.1348], locale en-US)
    • Flutter version 2.8.0 at C:\src\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (4 days ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\carlfost\AppData\Local\Android\Sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = C:\Users\carlfost\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java      
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)    
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code
    • VS Code at C:\Users\carlfost\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[√] VS Code, 64-bit edition (version 1.62.3)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.22.0

[√] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 96.0.4664.45
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 96.0.1054.43

• No issues found!
```
```

</details>

**Comment by carlfost** [comment]
Fixed:  By changing setting in the AndroidManifest - android:exported="false" to "true" fixed this issue.

**Comment by carlfost** [comment]
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
      ....
        <activity
            ....
            android:exported="true">
