### ISSUE TITLE
flutter run fails to deploy to (physical) iOS devices

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#9514]
~~May have started with the recent Xcode 8.3.2 update.~~ It looks like the `ios-deploy` step is failing.

## Steps to Reproduce

In the flutter repo:
1. `cd examples/flutter_gallery`
1. `open ios/Runner.xcodeproj`
1. In build settings, set development team for signing.
1. `flutter run -d <devicename>` (using a physical device)

Expected: application deploys to phone and launches
Actual: failure with the following message:
```
% flutter run -d the
Launching lib/main.dart on PhoneName in debug mode...
Running Xcode build...                               11.6s
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named lldb.embedded_interpreter
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
error: python failed attempting to evaluate 'fruitstrap_device_app="/private/var/containers/Bundle/Application/49CF1134-0F09-4154-ACF5-16AF55468C39/Runner.app"'
Unhandled exception:
Exception: Timeout while attempting to retrieve Uri for Observatory
#0      throwToolExit (package:flutter_tools/src/base/common.dart:29)
#1      ProtocolDiscovery.nextUri.<anonymous closure> (package:flutter_tools/src/protocol_discovery.dart:55)
#2      _rootRun (dart:async/zone.dart:1116)
#3      _CustomZone.run (dart:async/zone.dart:1001)
#4      _Future.timeout.<anonymous closure> (dart:async/future_impl.dart:720)
#5      _rootRun (dart:async/zone.dart:1116)
#6      _CustomZone.run (dart:async/zone.dart:1001)
#7      _CustomZone.runGuarded (dart:async/zone.dart:901)
#8      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:926)
#9      _rootRun (dart:async/zone.dart:1120)
#10     _CustomZone.run (dart:async/zone.dart:1001)
#11     _CustomZone.runGuarded (dart:async/zone.dart:901)
#12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:926)
#13     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21)
#14     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:366)
#15     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:394)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

## Logs

Verbose log:

```
[  +13 ms] Debugging is enabled, connecting to observatory and the diagnostic server
[   +4 ms] /usr/bin/env ios-deploy --id 9999999999999999999999999999999999999999 --bundle build/ios/Release-iphoneos/Runner.app --no-wifi --justlaunch --args --enable-dart-profiling --enable-checked-mode
[  +13 ms] [....] Waiting for iOS device to be connected
[  +10 ms] [....] Using 9999999999999999999999999999999999999999 (N66mAP, iPhone 6s Plus, iphoneos, arm64) a.k.a. 'PhoneName'.
[        ] ------ Install phase ------
[        ] [  0%] Found 9999999999999999999999999999999999999999 (N66mAP, iPhone 6s Plus, iphoneos, arm64) a.k.a. 'PhoneName' connected through USB, beginning install
[ +193 ms] [  5%] Copying /Users/cbracken/src/flutter/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app/META-INF/ to device
[        ] [  5%] Copying /Users/cbracken/src/flutter/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app/META-INF/com.apple.ZipMetadata.plist to device
[        ] [  5%] Copying /Users/cbracken/src/flutter/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app/_CodeSignature/ to device
[        ] [  6%] Copying /Users/cbracken/src/flutter/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app/_CodeSignature/CodeResources to device
[        ] [  6%] Copying /Users/cbracken/src/flutter/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app/app.flx to device
[ +233 ms] [ 11%] Copying /Users/cbracken/src/flutter/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app/AppFrameworkInfo.plist to device
[        ] [ 11%] Copying /Users/cbracken/src/flutter/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app/AppIcon20x20@2x.png to device
[        ] [ 12%] Copying /Users/cbracken/src/flutter/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app/AppIcon20x20@2x~ipad.png to device
[        ] [ 12%] Copying /Users/cbracken/src/flutter/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app/AppIcon20x20@3x.png to device
[        ] [ 13%] Copying /Users/cbracken/src/flutter/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app/AppIcon20x20~ipad.png to device
[        ] [ 13%] Copying /Users/cbracken/src/flutter/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app/AppIcon29x29.png to device
[        ] [ 14%] Copying /Users/cbracken/src/flutter/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app/AppIcon29x29@2x.png to device
[        ] [ 14%] Copying /Users/cbracken/src/flutter/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app/AppIcon29x29@2x~ipad.png to device
[        ] [ 14%] Copying /Users/cbracken/src/flutter/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app/AppIcon29x29@3x.png to device
[        ] [ 15%] Copying /Users/cbracken/src/flutter/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app/AppIcon29x29~ipad.png to device
[        ] [ 15%] Copying /Users/cbracken/src/flutter/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app/AppIcon40x40@2x.png to device
[        ] [ 16%] Copying /Users/cbracken/src/flutter/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app/AppIcon40x40@2x~ipad.png to device
[        ] [ 16%] Copying /Users/cbracken/src/flutter/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app/AppIcon40x40@3x.png to device
[        ] [ 17%] Copying /Users/cbracken/src/flutter/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app/AppIcon40x40~ipad.png to device
[        ] [ 17%] Copying /Users/cbracken/src/flutter/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app/AppIcon60x60@2x.png to device
[        ] [ 18%] Copying /Users/cbracken/src/flutter/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app/AppIcon60x60@3x.png to device
[        ] [ 18%] Copying /Users/cbracken/src/flutter/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app/AppIcon76x76@2x~ipad.png to device
[        ] [ 18%] Copying /Users/cbracken/src/flutter/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app/AppIcon76x76~ipad.png to device
[        ] [ 19%] Copying /Users/cbracken/src/flutter/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app/AppIcon83.5x83.5@2x~ipad.png to device
[        ] [ 19%] Copying /Users/cbracken/src/flutter/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app/Base.lproj/ to device
[        ] [ 20%] Copying /Users/cbracken/src/flutter/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app/Base.lproj/LaunchScreen.storyboardc/ to device
[        ] [ 20%] Copying /Users/cbracken/src/flutter/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app/Base.lproj/LaunchScreen.storyboardc/01J-lp-oVM-view-Ze5-6b-2t3.nib to device
[        ] [ 21%] Copying /Users/cbracken/src/flutter/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app/Base.lproj/LaunchScreen.storyboardc/Info.plist to device
[        ] [ 21%] Copying /Users/cbracken/src/flutter/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app/Base.lproj/LaunchScreen.storyboardc/UIViewController-01J-lp-oVM.nib to device
[        ] [ 22%] Copying /Users/cbracken/src/flutter/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app/Base.lproj/Main.storyboardc/ to device
[        ] [ 22%] Copying /Users/cbracken/src/flutter/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app/Base.lproj/Main.storyboardc/BYZ-38-t0r-view-8bC-Xf-vdC.nib to device
[        ] [ 22%] Copying /Users/cbracken/src/flutter/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app/Base.lproj/Main.storyboardc/Info.plist to device
[        ] [ 23%] Copying /Users/cbracken/src/flutter/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app/Base.lproj/Main.storyboardc/UIViewController-BYZ-38-t0r.nib to device
[        ] [ 23%] Copying /Users/cbracken/src/flutter/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app/embedded.mobileprovision to device
[        ] [ 24%] Copying /Users/cbracken/src/flutter/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app/Flutter.xcconfig to device
[        ] [ 24%] Copying /Users/cbracken/src/flutter/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app/Frameworks/ to device
[        ] [ 25%] Copying /Users/cbracken/src/flutter/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app/Frameworks/App.framework/ to device
[        ] [ 25%] Copying /Users/cbracken/src/flutter/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app/Frameworks/App.framework/_CodeSignature/ to device
[        ] [ 26%] Copying /Users/cbracken/src/flutter/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app/Frameworks/App.framework/_CodeSignature/CodeResources to device
[        ] [ 26%] Copying /Users/cbracken/src/flutter/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app/Frameworks/App.framework/App to device
[ +115 ms] [ 27%] Copying /Users/cbracken/src/flutter/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app/Frameworks/App.framework/Info.plist to device
[        ] [ 28%] Copying /Users/cbracken/src/flutter/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app/Frameworks/Flutter.framework/ to device
[        ] [ 28%] Copying /Users/cbracken/src/flutter/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app/Frameworks/Flutter.framework/_CodeSignature/ to device
[        ] [ 28%] Copying /Users/cbracken/src/flutter/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app/Frameworks/Flutter.framework/_CodeSignature/CodeResources to device
[   +2 ms] [ 29%] Copying /Users/cbracken/src/flutter/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app/Frameworks/Flutter.framework/Flutter to device
[ +579 ms] [ 43%] Copying /Users/cbracken/src/flutter/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app/Frameworks/Flutter.framework/icudtl.dat to device
[ +141 ms] [ 47%] Copying /Users/cbracken/src/flutter/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app/Frameworks/Flutter.framework/Info.plist to device
[        ] [ 48%] Copying /Users/cbracken/src/flutter/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app/Generated.xcconfig to device
[        ] [ 48%] Copying /Users/cbracken/src/flutter/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app/Info.plist to device
[        ] [ 49%] Copying /Users/cbracken/src/flutter/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app/PkgInfo to device
[        ] [ 49%] Copying /Users/cbracken/src/flutter/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app/Runner to device
[ +146 ms] [ 52%] CreatingStagingDirectory
[        ] [ 57%] ExtractingPackage
[        ] [ 60%] InspectingPackage
[   +8 ms] [ 60%] TakingInstallLock
[  +12 ms] [ 65%] PreflightingApplication
[   +8 ms] [ 65%] InstallingEmbeddedProfile
[   +6 ms] [ 70%] VerifyingApplication
[ +426 ms] [ 75%] CreatingContainer
[  +10 ms] [ 80%] InstallingApplication
[   +6 ms] [ 85%] PostflightingApplication
[   +6 ms] [ 90%] SandboxingApplication
[  +16 ms] [ 95%] GeneratingApplicationMap
[ +118 ms] [100%] Installed package build/ios/Release-iphoneos/Runner.app
[ +252 ms] ------ Debug phase ------
[        ] Starting debug of 9999999999999999999999999999999999999999 (N66mAP, iPhone 6s Plus, iphoneos, arm64) a.k.a. 'PhoneName' connected through USB...
[ +153 ms] [  0%] Looking up developer disk image
[  +14 ms] [ 95%] Developer disk image mounted successfully
[+1117 ms] [100%] Connecting to remote debug server
[        ] -------------------------
[  +21 ms] (lldb) command source -s 0 '/tmp/1D4DCC4D-2461-4FCA-997B-AC587CB3D551/fruitstrap-lldb-prep-cmds-9999999999999999999999999999999999999999'
[        ] Executing commands in '/tmp/1D4DCC4D-2461-4FCA-997B-AC587CB3D551/fruitstrap-lldb-prep-cmds-9999999999999999999999999999999999999999'.
[        ] (lldb)     platform select remote-ios --sysroot '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/10.3 (14E269)/Symbols'
[        ]   Platform: remote-ios
[        ]  Connected: no
[        ]   SDK Path: "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/10.3 (14E269)/Symbols"
[        ] (lldb)     target create "/Users/cbracken/src/flutter/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app"
[  +18 ms] Traceback (most recent call last):
[        ]   File "<string>", line 1, in <module>
[        ] ImportError: No module named lldb.embedded_interpreter
[        ] Traceback (most recent call last):
[        ]   File "<string>", line 1, in <module>
[        ] NameError: name 'run_one_line' is not defined
[        ] Traceback (most recent call last):
[        ]   File "<string>", line 1, in <module>
[        ] NameError: name 'run_one_line' is not defined
[        ] Traceback (most recent call last):
[        ]   File "<string>", line 1, in <module>
[        ] NameError: name 'run_one_line' is not defined
[        ] Traceback (most recent call last):
[        ]   File "<string>", line 1, in <module>
[        ] NameError: name 'run_one_line' is not defined
[        ] Traceback (most recent call last):
[        ]   File "<string>", line 1, in <module>
[        ] NameError: name 'run_one_line' is not defined
[        ] Traceback (most recent call last):
[        ]   File "<string>", line 1, in <module>
[        ] NameError: name 'run_one_line' is not defined
[  +41 ms] Traceback (most recent call last):
[        ]   File "<string>", line 1, in <module>
[        ] NameError: name 'run_one_line' is not defined
[ +110 ms] Traceback (most recent call last):
[        ]   File "<string>", line 1, in <module>
[        ] NameError: name 'run_one_line' is not defined
[   +4 ms] Current executable set to '/Users/cbracken/src/flutter/flutter/examples/flutter_gallery/build/ios/Release-iphoneos/Runner.app' (arm64).
[        ] (lldb)     script fruitstrap_device_app="/private/var/containers/Bundle/Application/41763A68-74B9-4AA9-A80C-142E6470D2FE/Runner.app"
[        ] Traceback (most recent call last):
[        ]   File "<string>", line 1, in <module>
[        ] NameError: name 'run_one_line' is not defined
[        ] error: python failed attempting to evaluate 'fruitstrap_device_app="/private/var/containers/Bundle/Application/41763A68-74B9-4AA9-A80C-142E6470D2FE/Runner.app"'
```

## Flutter Doctor

```
[✓] Flutter (on Mac OS X 10.12.4 16E195, channel master)
    • Flutter at /Users/cbracken/src/flutter/flutter
    • Framework revision 9b250cb6e8 (2 hours ago), 2017-04-20 15:06:56 -0700
    • Engine revision a5b64899c9
    • Tools Dart version 1.23.0-dev.11.7

[✓] Host Executable Compatibility
    • Downloaded executables execute on host

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/cbracken/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b05)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.2, Build version 8E2002
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 2.14.1
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b05)

[✓] IntelliJ IDEA Community Edition (version 2017.1.1)
    • Dart plugin version 171.4249.16
    • Flutter plugin version 12.1

[✓] Connected devices
    • PhoneName • 9999999999999999999999999999999999999999 • ios • iOS 10.3.1 (14E304)
```

**Comment by cbracken** [comment]
Root cause was that I had a custom `lldb` build with higher priority on my `$PATH` than the `lldb` installed with the Xcode tools. Reverting to the system default toolchain linked from `/usr/bin` resolved the issue.

Potentially worth adding a doctor check for this, though not super high-priority as I suspect this is relatively edge-casey.

Also see #9134
