### ISSUE TITLE
[tool_crash] ProcessException: No such file or directory Command: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome, OS error code: 2 when using custom devices

### ISSUE THREAD

**Issue by jwinarske** [flutter/flutter#95142]
It assumes Google Chrome is installed on MacOS when issuing `v Open Flutter DevTools` from CLI debug interface.  Installing Google Chrome resolves the crash.

## Command
```
flutter run -d stm32mp1-disco
```

## Steps to Reproduce
1. Setup flutter config on MacOSX to reflect:
```
Settings:
enable-custom-devices: true
enable-linux-desktop: false
enable-android: false
enable-ios: false
enable-macos-desktop: true
enable-web: false
```
2. acquire stm32mp157f-disco device
3. Flash SD card using image from -> https://github.com/meta-flutter/meta-flutter/actions/workflows/dunfell-stm32mp15.yml
4. configure custom-device  -> https://github.com/meta-flutter/meta-flutter/wiki/STM32MP1-Disco-Notes#debugging-with-custom-device
5. `flutter run -d stm32mp1-disco`
6. type `v` to Open Flutter DevTools`

## Logs
ProcessException: No such file or directory Command: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome, OS error code: 2
```
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:401:33)
#1      Process.start (dart:io-patch/process_patch.dart:38:20)
#2      Chrome._startProcess (package:browser_launcher/src/chrome.dart:145:26)
#3      Chrome.start (package:browser_launcher/src/chrome.dart:137:18)
#4      FlutterResidentDevtoolsHandler._launchDevToolsForDevices (package:flutter_tools/src/resident_devtools_handler.dart:134:24)
#5      FlutterResidentDevtoolsHandler.launchDevToolsInBrowser (package:flutter_tools/src/resident_devtools_handler.dart:122:7)
#6      TerminalHandler._commonTerminalInputHandler (package:flutter_tools/src/resident_runner.dart:1662:55)
#7      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1680:13)
#8      _rootRunUnary (dart:async/zone.dart:1434:47)
#9      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#10     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#12     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#13     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:378:25)
#14     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:244:5)
#15     _AsBroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:475:11)
#16     _rootRunUnary (dart:async/zone.dart:1434:47)
#17     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#20     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#21     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#22     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#23     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#24     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
```
```
[✓] Flutter (Channel master, 2.6.0-12.0.pre.1001, on macOS 12.0.1 21A559 darwin-arm, locale en-US)
    • Flutter version 2.6.0-12.0.pre.1001 at /Users/joel/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 36709264b5 (4 hours ago), 2021-12-12 18:50:50 -0500
    • Engine revision 368e3cc505
    • Dart version 2.16.0 (build 2.16.0-85.0.dev)
    • DevTools version 2.9.1

[!] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] VS Code (version 1.64.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • macOS (desktop)         • macos          • darwin-arm64 • macOS 12.0.1 21A559 darwin-arm
    • STM32MP1 Disco (mobile) • stm32mp1-disco • linux-arm64  • STM32MP1 Discovery Board

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: malformed
**Version**: null
**Material**: false
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null

**Comment by christopherfujino** [comment]
This definitely seems like a bug :) I haven't looked at the code, but I suspect we have some explicit Chrome detection logic that either isn't getting called here or is doing the wrong thing.

**Comment by christopherfujino** [comment]
Also, it's interesting that `flutter doctor -v` did not run any web validators for this user. I wonder if that is because the user explicitly opted out of the web setting.

**Comment by Jasguerrero** [comment]
Seems like the issue is related to custom device and the actual fix should be before the actual stack trace provided because the runCommand method is classifying the device as a web/chromium therefore assumes that chrome is installed https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/drive.dart#L220

**Comment by NANASHI0X74** [comment]
having the same issue with:
```
Operating System: NixOS 22.05 (Quokka)
Kernel: Linux 5.15.34
Architecture: x86-64
```
```
[ +171 ms] executing: /nix/store/k12ncgasy9zglj2hg723sn18bcn9amzw-androidsdk/libexec/android-sdk/platform-tools/adb devices -l
[  +32 ms] [✓] Flutter (Channel stable, 2.10.1, on NixOS 22.05 (Quokka) 5.15.34, locale en_GB.utf8)
[   +1 ms]     • Flutter version 2.10.1 at /nix/store/n2xf2zn9yc9awqmrg0r2zdpl9bx25z0a-flutter-2.10.1-unwrapped
[        ]     • Upstream repository git@github.com:flutter/flutter.git
[        ]     • Framework revision db747aa133 (3 months ago), 2022-02-09 13:57:35 -0600
[        ]     • Engine revision ab46186b24
[        ]     • Dart version 2.16.1
[        ]     • DevTools version 2.9.2
[  +62 ms] List of devices attached
           R9WR30FARMJ            device usb:3-3 product:gta4lwifieea model:SM_T500 device:gta4lwifi transport_id:3
[   +9 ms] /nix/store/k12ncgasy9zglj2hg723sn18bcn9amzw-androidsdk/libexec/android-sdk/platform-tools/adb -s R9WR30FARMJ shell getprop
[  +58 ms] [!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[        ]     • Android SDK at /nix/store/k12ncgasy9zglj2hg723sn18bcn9amzw-androidsdk/libexec/android-sdk
[        ]     ✗ cmdline-tools component is missing
[        ]       Run `path/to/sdkmanager --install "cmdline-tools;latest"`
[        ]       See https://developer.android.com/studio/command-line for more details.
[        ]     ✗ Android license status unknown.
[        ]       Run `flutter doctor --android-licenses` to accept the SDK licenses.
[        ]       See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.
[   +1 ms] [✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
[        ]     ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[        ] [✓] Android Studio (version 2021.1)
[        ]     • Android Studio at /nix/store/7h2cj0pmlh4mmf260nsqrrfqgc6vbdvi-android-studio-stable-2021.1.1.21-unwrapped
[        ]     • Flutter plugin version 66.0.1
[        ]     • Dart plugin version 211.7817
[        ]     • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
[  +60 ms] ro.hardware = qcom
[   +4 ms] executing: /nix/store/k12ncgasy9zglj2hg723sn18bcn9amzw-androidsdk/libexec/android-sdk/platform-tools/adb devices -l
[  +29 ms] List of devices attached
           R9WR30FARMJ            device usb:3-3 product:gta4lwifieea model:SM_T500 device:gta4lwifi transport_id:3
[   +2 ms] [✓] Connected device (1 available)
[        ]     • SM T500 (mobile) • R9WR30FARMJ • android-arm64 • Android 11 (API 30)
[+1617 ms] [✓] HTTP Host Availability
[        ]     • All required HTTP hosts are available
[        ] ! Doctor found issues in 2 categories.
[   +9 ms] "flutter doctor" took 2,554ms.
```
(yes, the android sdk packaging isn't great)

**Comment by viseztrance** [comment]
This solved the issue for me on linux (I'm serious):

```sh
sudo ln -s /usr/bin/firefox /usr/bin/google-chrome
```

**Comment by mdebbar** [comment]
Is this still an issue?
