### ISSUE TITLE
path_provider package always show Null check operator error

### ISSUE THREAD

**Issue by StitchC** [flutter/flutter#95155]
## Steps to Reproduce

just call the **getApplicationDocumentsDirectory** function

path_provider version: 2.0.8

futter version: 2.5.3

**Expected results:** 
no error emit

**Actual results:** 
show Null check operator error

<details>
<summary>Code sample</summary>

```dart
void main() async {
  FlutterError.onError = (FlutterErrorDetails errorDetails) {
    Log.error('=========flutter error ${errorDetails.exception.toString()}');
  };

  await getApplicationDocumentsDirectory();

  await Global.init();

  await EasyLoadingConfig.init();
}
```

</details>

<details>
  <summary>Logs</summary>

```
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value
#0      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:121:86)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:146:36)
#2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
#3      MethodChannelPathProvider.getApplicationDocumentsPath (package:path_provider_platform_interface/src/method_channel_path_provider.dart:50:10)
#4      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:115:40)

```

```
info • Name types using UpperCamelCase • lib/i18n/en_US.dart:1:7 • camel_case_types
   info • Name types using UpperCamelCase • lib/i18n/zh_CN.dart:1:7 • camel_case_types
   info • Name non-constant identifiers using lowerCamelCase • lib/models/PickingListSku.dart:7:14 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/PickingListSku.dart:9:14 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/PickingListSku.dart:11:14 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/PickingListSku.dart:13:14 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/PickingListSku.dart:15:14 • non_constant_identifier_names
   info • Name types using UpperCamelCase • lib/pages/account/login/state.dart:1:7 • camel_case_types
   info • Use `;` instead of `{}` for empty constructor bodies • lib/pages/account/login/state.dart:2:16 • empty_constructor_bodies
   info • The declaration '_generateSkuFloor' isn't referenced • lib/pages/locateSku/logic.dart:174:10 • unused_element
   info • Unused import: 'package:erp_app/models/ContainerDetailPageBackResult.dart' • lib/pages/warehouse/picking/containerDetail/logic.dart:1:8 • unused_import
   info • Name non-constant identifiers using lowerCamelCase • lib/pages/warehouse/picking/containerDetail/logic.dart:30:9 • non_constant_identifier_names
   info • Unused import: 'package:flutter/material.dart' • lib/pages/warehouse/picking/detail/state.dart:3:8 • unused_import
   info • Unused import: 'dart:math' • lib/pages/warehouse/picking/preview/view.dart:1:8 • unused_import
   info • Name non-constant identifiers using lowerCamelCase • lib/utils/Log.dart:18:20 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/utils/Log.dart:19:15 • non_constant_identifier_names
   info • The declaration 'write' isn't referenced • lib/utils/Log.dart:40:23 • unused_element
   info • A value for optional parameter 'duplicate' isn't ever given • lib/utils/Log.dart:77:13 • unused_element
   info • Name non-constant identifiers using lowerCamelCase • lib/widgets/Counter.dart:30:20 • non_constant_identifier_names
   info • Avoid empty statements • lib/widgets/ReceivingItem.dart:130:5 • empty_statements
   info • Dead code • lib/widgets/ReceivingItem.dart:130:5 • dead_code
   info • Unused import: 'package:flutter/material.dart' • test/widget_test.dart:8:8 • unused_import
   info • Unused import: 'package:flutter_test/flutter_test.dart' • test/widget_test.dart:9:8 • unused_import
   info • Unused import: 'package:erp_app/main.dart' • test/widget_test.dart:11:8 • unused_import

```

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.3.1 20E241 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.5.3 at /Users/chenrunsheng/flutter-home/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (8 周前), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/chenrunsheng/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Connected device (2 available)
    • iPhone 12 (mobile) • E182FCBE-DC49-4879-B920-72AB94E52D6B • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 96.0.4664.93

• No issues found!

```

</details>

**Comment by StitchC** [comment]
i found that when i change my code position of call **await getApplicationDocumentsDirectory();**  like this

`
void main() async {
  FlutterError.onError = (FlutterErrorDetails errorDetails) {
    Log.error('=========flutter error ${errorDetails.exception.toString()}');
  };

  await Global.init();

  await getApplicationDocumentsDirectory();

  await EasyLoadingConfig.init();
}
`

everything is ok! are there any magic is it ?

**Comment by ookami-kb** [comment]
`getApplicationDocumentsDirectory` uses binary messenger. For it to work you need to explicitly call `WidgetsFlutterBinding.ensureInitialized();`, if it's used before `runApp`. I guess `Global.init()` does this under the hood.

There's an issue to add a better error description: #78028

**Comment by StitchC** [comment]
> `getApplicationDocumentsDirectory` uses binary messenger. For it to work you need to explicitly call `WidgetsFlutterBinding.ensureInitialized();`, if it's used before `runApp`. I guess `Global.init()` does this under the hood.
> 
> There's an issue to add a better error description: #78028

thank you! i know
