### ISSUE TITLE
App crashes when using `url_launcher` on latest stable

### ISSUE THREAD

**Issue by CripyIce** [flutter/flutter#95249]
## Steps to Reproduce

1. Use Flutter 2.8.0 with `url_launcher` to launch an AliExpress item with their app (this is my case).
2. Immediately after launching AliExpress app my Flutter app crashes.
3. Downgrade Flutter to version 2.5.3 and everything will work as should be.

**Expected results:** AliExpress app launches without my app getting crashed.

**Actual results:** AliExpress app launches and my app crashes.

<details>
<summary>Code sample</summary>

```dart
launch(
            'some_aliexpress_link',
            forceSafariVC: false,
            forceWebView: false,
          );
```

</details>

<details>
  <summary>Logs</summary>

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.dispatchWindowVisibilityChanged(int)' on a null object reference
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1632)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1632)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1632)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1632)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1632)
       at com.android.internal.policy.DecorView.dispatchWindowVisibilityChanged(DecorView.java:4221)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3151)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2618)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9971)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1010)
       at android.view.Choreographer.doCallbacks(Choreographer.java:809)
       at android.view.Choreographer.doFrame(Choreographer.java:744)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8633)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

```
```

```
```

</details>

Note: This happens in Android only.

**Comment by mamuseferha** [comment]
Hi @CripyIce, thank you for filing this issue. I tested this on the latest stable and master channel using `url_launcher 6.0.17` and the issue is not reproducible. I had the AliExpress app installed and tested this on a Samsung S10 android device but there was no crash in the app when the link is launched. 

What device did you test this on? Does this only occur with an AliExpress url? Also, can you please provide your `flutter doctor -v` and `url_launcher` version used?


<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';

void main() {
  runApp(const MaterialApp(home: MyApp()));
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Center(
        child: ElevatedButton(
          onPressed: _launchURL,
          child: Text('Show Flutter homepage'),
        ),
      ),
    );
  }
}

void _launchURL() async {
  if (!await launch(
    'https://a.aliexpress.com/_m0aNdEI',
    forceSafariVC: false,
    forceWebView: false,
  )) throw 'Could not launch';
}


```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 2.8.0, on macOS 11.6.1 20G224 darwin-x64, locale en-US)
    • Flutter version 2.8.0 at /Users/flo/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (6 days ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/flo/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (5 available)
    • SM G975U (mobile)                  • R58M95MA95E                          • android-arm64  • Android 11 (API 30)
    • Android SDK built for x86 (mobile) • emulator-5556                        • android-x86    • Android 11 (API 30)
      (emulator)
    • iPhone 13 (mobile)                 • EF1251D3-C9C4-475E-9F91-58CD010FDA48 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)                    • macos                                • darwin-x64     • macOS 11.6.1 20G224
      darwin-x64
    • Chrome (web)                       • chrome                               • web-javascript • Google Chrome 93.0.4577.63

! Doctor found issues in 1 category.
```
```bash
[✓] Flutter (Channel master, 2.6.0-12.0.pre.1027, on macOS 11.6.1 20G224 darwin-x64, locale en-US)
    • Flutter version 2.6.0-12.0.pre.1027 at /Users/flo/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 31d366a051 (4 hours ago), 2021-12-14 00:59:08 -0500
    • Engine revision 30f048de39
    • Dart version 2.16.0 (build 2.16.0-85.0.dev)
    • DevTools version 2.9.1

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/flo/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (5 available)
    • SM G975U (mobile)                  • R58M95MA95E                          • android-arm64  • Android 11 (API 30)
    • Android SDK built for x86 (mobile) • emulator-5556                        • android-x86    • Android 11 (API 30) (emulator)
    • iPhone 13 (mobile)                 • EF1251D3-C9C4-475E-9F91-58CD010FDA48 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)                    • macos                                • darwin-x64     • macOS 11.6.1 20G224 darwin-x64
    • Chrome (web)                       • chrome                               • web-javascript • Google Chrome 93.0.4577.63

! Doctor found issues in 1 category.
```

</details>

Thank you
