### ISSUE TITLE
flutter upgrade to 2.8.0 error

### ISSUE THREAD

**Issue by eggysudianto** [flutter/flutter#95255]
I'm want to upgrade flutter from 2.5.3 to 2.8.0, but I face error 

```
C:\Users\user>flutter upgrade
Building flutter tool...
Running pub upgrade...
kernel-service: Error: Unhandled exception:
Invalid argument(s): Exception when reading 'file:///D:/#SDK/flutter/packages/flutter_tools/.packages': Unsupported operation: Cannot extract a file path from a URI with a fragment component
#0      ProcessedOptions._readFile (package:front_end/src/base/processed_options.dart:609:7)
#1      ProcessedOptions._createPackagesFromFile (package:front_end/src/base/processed_options.dart:623:33)
#2      ProcessedOptions.createPackagesFromFile (package:front_end/src/base/processed_options.dart:691:20)
#3      ProcessedOptions._getPackages (package:front_end/src/base/processed_options.dart:557:32)
#4      ProcessedOptions.getUriTranslator (package:front_end/src/base/processed_options.dart:510:38)
<asynchronous suspension>
#5      languageVersionForUri.<anonymous closure> (package:front_end/src/api_prototype/language_version.dart:57:35)
<asynchronous suspension>
#6      languageVersionForUri (package:front_end/src/api_prototype/language_version.dart:36:10)
<asynchronous suspension>
#7      uriUsesLegacyLanguageVersion (package:front_end/src/api_prototype/language_version.dart:148:7)
<asynchronous suspension>
#8      autoDetectNullSafetyMode (package:vm/kernel_front_end.dart:573:18)
<asynchronous suspension>
#9      _processLoadRequest (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:842:5)
<asynchronous suspension>

Unhandled exception:
Invalid argument(s): Exception when reading 'file:///D:/#SDK/flutter/packages/flutter_tools/.packages': Unsupported operation: Cannot extract a file path from a URI with a fragment component
#0      ProcessedOptions._readFile (package:front_end/src/base/processed_options.dart:609:7)
#1      ProcessedOptions._createPackagesFromFile (package:front_end/src/base/processed_options.dart:623:33)
#2      ProcessedOptions.createPackagesFromFile (package:front_end/src/base/processed_options.dart:691:20)
#3      ProcessedOptions._getPackages (package:front_end/src/base/processed_options.dart:557:32)
#4      ProcessedOptions.getUriTranslator (package:front_end/src/base/processed_options.dart:510:38)
<asynchronous suspension>
#5      languageVersionForUri.<anonymous closure> (package:front_end/src/api_prototype/language_version.dart:57:35)
<asynchronous suspension>
#6      languageVersionForUri (package:front_end/src/api_prototype/language_version.dart:36:10)
<asynchronous suspension>
#7      uriUsesLegacyLanguageVersion (package:front_end/src/api_prototype/language_version.dart:148:7)
<asynchronous suspension>
#8      autoDetectNullSafetyMode (package:vm/kernel_front_end.dart:573:18)
<asynchronous suspension>
#9      _processLoadRequest (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:842:5)
<asynchronous suspension>
```

and I try to run `flutter doctor` and it's not success because when `flutter doctor` run, the `flutter upgrade` is automatic running too

**Comment by mraleph** [comment]
@eggysudianto Renaming your folder from `#SDK` to `SDK` should fix this. 

/cc @lrhn @johnniwinther

**Comment by maheshmnj** [comment]
Hi @eggysudianto, Thanks for filing the issue. Can you please confirm if the above solution works?

Thanks

**Comment by eggysudianto** [comment]
> @eggysudianto Did the folder name `#SDK` work with `2.5.3` ? The error comes from parsing the `Uri` and we haven't changed that code in a long time AFAIK.

yes it works with `#SDK ` folder

**Comment by eggysudianto** [comment]
oh it's work rename folder `#SDK` to `SDK`. thanks @mraleph @johnniwinther @maheshmnj

**Comment by maheshmnj** [comment]
Thanks for the confirmation. Closing based on the above response.

**Comment by mraleph** [comment]
@johnniwinther @lrhn do we want to file a Dart SDK issue around CFE not working when directory has `#` in its name? I'd think that this is still a bug in how we use URLs in CFE.
