### ISSUE TITLE
Using Chrome on Windows from WSL does not work

### ISSUE THREAD

**Issue by NLstn** [flutter/flutter#95279]
Hi,

I try to use the chrome installation on windows, while flutter runs in my WSL instance. I have two issue (which seem to have a similar cause):
- When running flutter doctor, after checking my Android Studio installation, the command seems to be stuck. Chrome opens up in windows, but nothing happens.
- When running flutter run in one of my projects which has only web added, the error "Oops; flutter has exited unexpectedly: "FormatException: Invalid UTF-8 byte (at offset 41)"." is printed to the console (chrome is opnening as well, but does not do anything.

It would be great to use chrome on Windows rather than wsl, because the browser runs much smoother native vs WSLg

EDIT:
Actually flutter doctor crashes after some time with this error + stack trace:

```
[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Missing extension byte (at offset 202)
    • #0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1893:7)
      #1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:28)
      #2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)
      #3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
      #4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
      #5      _rootRunUnary (dart:async/zone.dart:1436:47)
      #6      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
      #7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
      #8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
      #9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
      #10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
      #11     _StreamController._add (dart:async/stream_controller.dart:607:7)
      #12     _StreamController.add (dart:async/stream_controller.dart:554:5)
      #13     _Socket._onData (dart:io-patch/socket_patch.dart:2302:41)
      #14     _rootRunUnary (dart:async/zone.dart:1444:13)
      #15     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
      #16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
      #17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
      #18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
      #19     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
      #20     _StreamController._add (dart:async/stream_controller.dart:607:7)
      #21     _StreamController.add (dart:async/stream_controller.dart:554:5)
      #22     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1830:33)
      #23     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1314:14)
      #24     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
      #25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
      #26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:122:13)
      #27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:193:5)
```

**Comment by darshankawar** [comment]
> * When running flutter doctor, after checking my Android Studio installation, the command seems to be stuck. Chrome opens up in windows, but nothing happens.

Does it throw any error log when this happens ?



> Actually flutter doctor crashes after some time with this error + stack trace:

Is it pointing to `IntelliJ IDEA Community Edition` ?

**Comment by NLstn** [comment]
This is the full output of flutter doctor -v:

➜  ~ flutter doctor -v
[✓] Flutter (Channel stable, 2.8.0, on Debian GNU/Linux 9 (stretch) 5.10.74.3-microsoft-standard-WSL2, locale
    en_US.UTF-8)
    • Flutter version 2.8.0 at /home/nlstn/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (7 days ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/nlstn/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /mnt/c/Program Files/Google/Chrome/Application/chrome.exe

[✓] Android Studio (version 2020.3)
    • Android Studio at /usr/local/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Missing extension byte (at offset 202)
    • #0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1893:7)
      #1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:28)
      #2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)
      #3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
      #4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
      #5      _rootRunUnary (dart:async/zone.dart:1436:47)
      #6      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
      #7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
      #8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
      #9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
      #10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
      #11     _StreamController._add (dart:async/stream_controller.dart:607:7)
      #12     _StreamController.add (dart:async/stream_controller.dart:554:5)
      #13     _Socket._onData (dart:io-patch/socket_patch.dart:2302:41)
      #14     _rootRunUnary (dart:async/zone.dart:1444:13)
      #15     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
      #16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
      #17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
      #18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
      #19     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
      #20     _StreamController._add (dart:async/stream_controller.dart:607:7)
      #21     _StreamController.add (dart:async/stream_controller.dart:554:5)
      #22     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1830:33)
      #23     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1314:14)
      #24     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
      #25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
      #26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:122:13)
      #27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:193:5)


! Doctor found issues in 1 category.

I don't have IntelliJ installed, i don't know what you mean by that question.

**Comment by darshankawar** [comment]
> i don't know what you mean by that question.

I wanted to know if you have Intellij IDE installed,but that's fine.

Keeping it open for further insights on this, since I don't have WSL setup to verify this scenario.

/cc @stuartmorgan

**Comment by darshankawar** [comment]
@NLstn 
Can you confirm if you are still facing this issue using latest stable version of the framework ? (3.3.4)

**Comment by Marty** [comment]
@darshankawar The same thing is happening to me on latest stable. Could you reopen this?

**Comment by darshankawar** [comment]
Thanks for the feedback. Reopening.

**Comment by maxcruz** [comment]
I have the same issue on Windows with WSL Ubuntu

```
➜  ~ flutter doctor -v
[✓] Flutter (Channel stable, 3.3.8, on Ubuntu 22.04.1 LTS 5.10.16.3-microsoft-standard-WSL2, locale C.UTF-8)
    • Flutter version 3.3.8 on channel stable at /home/max/flutter/sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (9 days ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/max/android
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /home/max/.sdkman/candidates/java/current/bin/java
    • Java version OpenJDK Runtime Environment 18.9 (build 11.0.12+7)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /mnt/c/Program Files/Google/Chrome/Application/chrome.exe

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Missing extension byte (at offset 7)
    • #0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1859:7)
      #1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:28)
      #2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)
      #3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
      #4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
      #5      _rootRunUnary (dart:async/zone.dart:1399:47)
      #6      _CustomZone.runUnary (dart:async/zone.dart:1300:19)
      #7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1209:7)
      #8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
      #9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
      #10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
      #11     _StreamController._add (dart:async/stream_controller.dart:648:7)
      #12     _StreamController.add (dart:async/stream_controller.dart:596:5)
      #13     _Socket._onData (dart:io-patch/socket_patch.dart:2324:41)
      #14     _rootRunUnary (dart:async/zone.dart:1407:13)
      #15     _CustomZone.runUnary (dart:async/zone.dart:1300:19)
      #16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1209:7)
      #17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
      #18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
      #19     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
      #20     _StreamController._add (dart:async/stream_controller.dart:648:7)
      #21     _StreamController.add (dart:async/stream_controller.dart:596:5)
      #22     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1849:33)
      #23     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1322:14)
      #24     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
      #25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
      #26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:122:13)
      #27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:193:5)


[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

**Comment by willxie** [comment]
Also running into the same issue:
```
[✗] Chrome - develop for the web (Cannot find Chrome executable at  '/mnt/c/Program Files/Google/Chrome/Application/chrome.exe')
    !  '/mnt/c/Program Files/Google/Chrome/Application/chrome.exe' is not executable.
```

**Comment by christopherfujino** [comment]
Assigning to myself to investigate what's going on.

**Comment by GkIgor** [comment]
Continuing the dialogue in #147946.

In my WSL, the number of exception is 20 `FormatException: Missing extension byte (at offset 20)`
What does each number mean?
And how can we resolve each issue present at the doctor?

For example, `adb`, which is present in the PATH variable, is recognized by wsl but not by flutter.

## flutter doctor -v
```bash
[✓] Flutter (Channel stable, 3.19.6, on Debian GNU/Linux 12 (bookworm) 5.15.146.1-microsoft-standard-WSL2, locale
    en_US.UTF-8)
    • Flutter version 3.19.6 on channel stable at /usr/bin/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (3 weeks ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /mnt/c/Users/gkirxzin/AppData/Local/Android/Sdk
    • Platform android-34-ext8, build-tools 34.0.0
    ✗ Android SDK file not found: adb.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /mnt/c/Program Files/Google/Chrome/Application/chrome.exe

[✓] Linux toolchain - develop for Linux desktop
    • Debian clang version 14.0.6
    • cmake version 3.25.1
    • ninja version 1.11.1
    • pkg-config version 1.8.1

[!] Android Studio (version unknown)
    • Android Studio at /mnt/c/Program Files/Android/Android Studio/
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    ✗ android-studio-dir = /mnt/c/Program Files/Android/Android Studio/
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.
    • Consider removing your android-studio-dir setting by running:
      flutter config --android-studio-dir=

[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Missing extension byte (at offset 20)
    • #0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1845:7)
      #1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:304:28)
      #2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:300:5)
      #3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:69:18)
      #4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
      #5      _rootRunUnary (dart:async/zone.dart:1407:47)
      #6      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
      #7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
      #8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
      #9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
      #10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
      #11     _StreamController._add (dart:async/stream_controller.dart:658:7)
      #12     _StreamController.add (dart:async/stream_controller.dart:606:5)
      #13     _Socket._onData (dart:io-patch/socket_patch.dart:2447:41)
      #14     _rootRunUnary (dart:async/zone.dart:1415:13)
      #15     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
      #16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
      #17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
      #18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
      #19     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
      #20     _StreamController._add (dart:async/stream_controller.dart:658:7)
      #21     _StreamController.add (dart:async/stream_controller.dart:606:5)
      #22     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1936:33)
      #23     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1379:14)
      #24     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
      #25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
      #26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
      #27     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)


[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
```

**Comment by zhaoxing-zstar** [comment]
Hi @NLstn @GkIgor ,

I came across the same issue and found a workaround using WSL2. You can install a Google Chrome for Ubuntu instead of linking the webserver to chrome.exe in the Windows Program Files directory. Here's a helpful guide on how to do that: [Use Chrome in Ubuntu WSL2](https://scottspence.com/posts/use-chrome-in-ubuntu-wsl)

With this setup, you should be able to run your application just like on a normal Linux system, and forward ports to open it in Windows Chrome if needed.

**Comment by GkIgor** [comment]
> Hi @NLstn @GkIgor ,
> 
> I came across the same issue and found a workaround using WSL2. You can install a Google Chrome for Ubuntu instead of linking the webserver to chrome.exe in the Windows Program Files directory. Here's a helpful guide on how to do that: [Use Chrome in Ubuntu WSL2](https://scottspence.com/posts/use-chrome-in-ubuntu-wsl)
> 
> With this setup, you should be able to run your application just like on a normal Linux system, and forward ports to open it in Windows Chrome if needed.



Hello, I hope you are well.
I used the same alternative to get the framework working on WSL.
But it causes a small loss of performance in development, in addition to bugs and crashes.
The closest solution to solving this problem was using idx.google.com as the IDE.
WSL cannot instantiate the emulators.

**Comment by mdebbar** [comment]
This looks like an issue in the flutter tool on Windows/WSL.

**Comment by HBUzxl** [comment]
I encountered the same problem when connecting to Chrome on Windows using WSL.

**Comment by 1e4DouWine** [comment]
## Still reproducible on Flutter 3.47.1 / Ubuntu 26.04 WSL2

I can reproduce this issue on the latest stable version of Flutter before August 22, 2026.

### Environment

* Windows Chrome: 151.0.7922.174
* Windows version: 11 25H2 26200.9168

```text
cope@Nope:~$ flutter doctor -v
[✓] Flutter (Channel stable, 3.47.1, on Ubuntu 26.04 LTS 6.18.33.2-microsoft-standard-WSL2, locale C.UTF-8) [77ms]
    • Flutter version 3.47.1 on channel stable at /home/cope/develop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6655482ec0 (2 days ago), 2026-08-19 10:07:23 -0700
    • Engine revision 5d53178869
    • Dart version 3.13.1
    • DevTools version 2.60.0
    • Feature flags: enable-web, enable-linux-desktop, enable-macos-desktop, enable-windows-desktop, enable-android,
      enable-ios, cli-animations, enable-native-assets, enable-record-use, enable-swift-package-manager,
      omit-legacy-version-file, enable-lldb-debugging, enable-uiscene-migration

[✓] Android toolchain - develop for Android devices (Android SDK version 37.0.0) [1,622ms]
    • Android SDK at /home/cope/Android/Sdk
    • Emulator version unknown
    • Platform android-37.1, build-tools 37.0.0
    • Java binary at: /home/cope/.local/share/mise/installs/java/25.0.2/bin/java
      This JDK is specified by the JAVA_HOME environment variable.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 25.0.2+10-69)
    • All Android licenses accepted.

[✓] Chrome - develop for the web [104ms]
    • CHROME_EXECUTABLE = /mnt/c/Program Files/Google/Chrome/Application/chrome.exe

[✓] Linux toolchain - develop for Linux desktop [389ms]
    • Ubuntu clang version 21.1.8 (6ubuntu1)
    • cmake version 4.2.3
    • ninja version 1.13.2
    • pkg-config version 2.5.1
    ! Unable to access driver information using 'eglinfo'.
      It is likely available from your distribution (e.g.: apt install mesa-utils)

[!] Proxy Configuration [117ms]
    • HTTP_PROXY is set
    • NO_PROXY is
      172.31.*,172.30.*,172.29.*,172.28.*,172.27.*,172.26.*,172.25.*,172.24.*,172.23.*,172.22.*,172.21.*,172.20.*,172.19
      .*,172.18.*,172.17.*,172.16.*,10.*,192.168.*,127.*,localhost,<local>
    • NO_PROXY contains localhost
    ! NO_PROXY does not contain 127.0.0.1
    ! NO_PROXY does not contain ::1

[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Missing extension byte (at offset 1)
    • #0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1963:7)
      #1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:313:28)
      #2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:309:5)
      #3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:70:18)
      #4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:115:24)
      #5      _rootRunUnary (dart:async/zone_root.dart:48:47)
      #6      _CustomZone.runUnary (dart:async/zone.dart:816:35)
      #7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:710:7)
      #8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:381:11)
      #9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:312:7)
      #10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:798:19)
      #11     _StreamController._add (dart:async/stream_controller.dart:663:7)
      #12     _StreamController.add (dart:async/stream_controller.dart:618:5)
      #13     _Socket._onData (dart:io-patch/socket_patch.dart:2906:41)
      #14     _rootRunUnary (dart:async/zone_root.dart:56:13)
      #15     _CustomZone.runUnary (dart:async/zone.dart:816:35)
      #16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:710:7)
      #17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:381:11)
      #18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:312:7)
      #19     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:798:19)
      #20     _StreamController._add (dart:async/stream_controller.dart:663:7)
      #21     _StreamController.add (dart:async/stream_controller.dart:618:5)
      #22     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:2344:31)
      #23     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1679:14)
      #24     _microtaskLoop (dart:async/schedule_microtask.dart:40:35)
      #25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
      #26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:127:13)
      #27     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:193:5)


[✓] Network resources [674ms]
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```
