### ISSUE TITLE
http.get Invalid character   "[" 

### ISSUE THREAD

**Issue by welldone217** [flutter/flutter#9529]
```
I/flutter ( 5092): https://d.apicloud.com/mcm/api/customers?filter={"fields":{"id":true,"uname":true,"uphone":true,"usfz":true},"where":{"ubirthday":{"between":["2017-04-20 09:00:13.155657","2017-04-24 09:00:13.155657"]}},"order":"updatedAt Desc,createdAt Desc","skip":0,"limit":10}
E/flutter ( 5092): [ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter ( 5092): FormatException: Invalid character (at character 142)
E/flutter ( 5092): ...ue},"where":{"ubirthday":{"between":["2017-04-20 09:00:13.155657","2017-...
E/flutter ( 5092):&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^
E/flutter ( 5092): 
E/flutter ( 5092): #0      _Uri._fail (dart:core/uri.dart:1602)
E/flutter ( 5092): #1      _Uri._normalize (dart:core/uri.dart:2306)
E/flutter ( 5092): #2      _Uri._normalizeOrSubstring (dart:core/uri.dart:2262)
E/flutter ( 5092): #3      _Uri._makeQuery (dart:core/uri.dart:2143)
E/flutter ( 5092): #4      _Uri._Uri.notSimple (dart:core/uri.dart:1461)
E/flutter ( 5092): #5      Uri.parse (dart:core/uri.dart:1011)
E/flutter ( 5092): #6      BaseClient._sendUnstreamed (package:http/src/base_client.dart:154:34)
E/flutter ( 5092): <asynchronous suspension>
E/flutter ( 5092): #7      BaseClient.get (package:http/src/base_client.dart:34:5)
E/flutter ( 5092): #8      get.<anonymous closure> (package:http/http.dart:47:34)
E/flutter ( 5092): #9      _withClient (package:http/http.dart:167:20)
E/flutter ( 5092): <asynchronous suspension>
E/flutter ( 5092): #10     get (package:http/http.dart:47:3)
E/flutter ( 5092): #11     NetworkApi.query (/data/user/0/com.yourcompany.customers/cache/customers7UetAe/customers/lib/pub/network_api.dart:168:42)
E/flutter ( 5092): <asynchronous suspension>
E/flutter ( 5092): #12     GalleryHomeState._galleryListItems (/data/user/0/com.yourcompany.customers/cache/customers7UetAe/customers/lib/initd/home.dart: 100 : 7)
E/flutter ( 5092): #13     GalleryHomeState.build (/data/user/0/com.yourcompany.customers/cache/customers7UetAe/customers/lib/initd/home.dart:163:68)
E/flutter ( 5092): #14     StatefulElement.build (package:flutter/src/widgets/framework.dart:3234:27)
E/flutter ( 5092): #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3144:15)
E/flutter ( 5092): #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
E/flutter ( 5092): #17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3124:5)
E/flutter ( 5092): #18     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3262:22)
E/flutter ( 5092): #19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3119:5)
E/flutter ( 5092): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2506:14)
E/flutter ( 5092): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2309:12)
E/flutter ( 5092): #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
E/flutter ( 5092): #23     Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
E/flutter ( 5092): #24     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3124:5)
E/flutter ( 5092): #25     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3119:5)
E/flutter ( 5092): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2506:14)
E/flutter ( 5092): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2309:12)
E/flutter ( 5092): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
E/flutter ( 5092): #29     Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
E/flutter ( 5092): #30     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3124:5)
E/flutter ( 5092): #31     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3119:5)
E/flutter ( 5092): #32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2506:14)
E/flutter ( 5092): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2309:12)
E/flutter ( 5092): #34     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4085:14)
E/flutter ( 5092): #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2506:14)
E/flutter ( 5092): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2309:12)
E/flutter ( 5092): #37     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4085:14)
E/flutter ( 5092): #38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2506:14)
E/flutter ( 5092): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2309:12)
E/flutter ( 5092): #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3156:16)
E/flutter ( 5092): #41     Element.rebuild (package:flutter/src/widgets/framework.dart:3045:5)
E/flutter ( 5092): #42     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3124:5)
E/flutter ( 5092): #43     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3262:22)
E/flutter ( 5092): #44     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3119:5)
E/flutter ( 5092): #45     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2506:14)
E/flutter ( 5092): #46     Elem

Restarted in 1923 ms.
Restarted app in 1.9s.
```

**Comment by eseidelGoogle** [comment]
Looks like you're making a network request from within build() (which you may not want to do, since build is attempting to build the next frame to display).

Regardless, it looks like you're attempting to pass a URI to Uri.parse which it believes is invalid (hence the FormatException).

`https://d.apicloud.com/mcm/api/customers?filter={"fields":{"id":true,"uname":true,"uphone":true,"usfz":true},"where":{"ubirthday":{"between":["2017-04-20 09:00:13.155657","2017-04-24 09:00:13.155657"]}},"order":"updatedAt Desc,createdAt Desc","skip":0,"limit":10}`

You can see the issue reproduce here:
https://dartpad.dartlang.org/83e73a85001a07032d5937d1a4cd8f00

**Comment by eseidelGoogle** [comment]
It looks like it's the space in "updatedAt Desc" which is invalid.  Try wrapping in Uri.encodeFull:

Uri.parse(Uri.encodeFull('https://d.apicloud.com/mcm/api/customers?filter={"fields":{"id":true,"uname":true,"uphone":true,"usfz":true},"where":{"ubirthday":{"between":["2017-04-20 09:00:13.155657","2017-04-24 09:00:13.155657"]}},"order":"updatedAt Desc,createdAt Desc","skip":0,"limit":10}'));

**Comment by eseidelGoogle** [comment]
Actually turns out the [ ] are also not valid Uri characters it's just I thought they were since browsers are so forgiving about them. :)

**Comment by eseidelGoogle** [comment]
Looks like it's actually possibly a conformance bug in Dart's Uri parser and I've filed https://github.com/dart-lang/sdk/issues/29420 to track.  You can workaround by encoding before parsing.
