### ISSUE TITLE
[flutter_conductor] verify binaries signed test can fail to check out a ref

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#95297]
For example: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20beta%20verify_binaries_codesigned/361/overview

```
Exception on command "checkout master": Command "git checkout master" failed in directory "/opt/s/w/ir/x/w/flutter_conductor_checkouts/framework" to Checking out initialRef master. Git exited with error code 1.
stderr from git:
15:38:49.276694 exec-cmd.c:139          trace: resolved executable path from Darwin stack: /opt/s/w/ir/cipd_bin_packages/bin/git
15:38:49.277143 exec-cmd.c:238          trace: resolved executable dir: /opt/s/w/ir/cipd_bin_packages/bin
15:38:49.277813 git.c:455               trace: built-in: git checkout master
error: pathspec 'master' did not match any file(s) known to git




#0      Git._reportFailureAndExit (package:conductor_core/src/git.dart:77:5)
#1      Git.run (package:conductor_core/src/git.dart:43:7)
<asynchronous suspension>
#2      Repository.lazilyInitialize (package:conductor_core/src/repository.dart:184:7)
<asynchronous suspension>
#3      Repository.checkoutDirectory (package:conductor_core/src/repository.dart:132:5)
<asynchronous suspension>
#4      CodesignCommand.run (package:conductor_core/src/codesign.dart:116:28)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#6      main (file:///opt/s/w/ir/x/w/flutter%20sdk/dev/conductor/core/bin/cli.dart:78:5)
<asynchronous suspension>
```

I think the issue is that the given ref (here `master`) does not exist on the upstream (which is hte main framework repo LUCI clones).

**Comment by christopherfujino** [comment]
For example:

LUCI Build: https://ci.chromium.org/p/flutter/builders/prod/Mac%20stable%20verify_binaries_codesigned/105?
Stderr: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8803040626938017825/+/u/Verify_binaries_codesigned/verify_binaries_codesigned/test_stderr

**Comment by keyonghan** [comment]
Bumping to P2 based on https://github.com/flutter/flutter/issues/111772.

**Comment by XilaiZhang** [comment]
> Bumping to P2 based on #111772.

right, this is tracked in https://github.com/flutter/flutter/pull/111934
