### ISSUE TITLE
[tool_crash] ProcessException: Failed to find "which" in the search path. Command: which, OS error code: 0

### ISSUE THREAD

**Issue by whisper540** [flutter/flutter#95313]
## Command
```
flutter --version --verbose
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Failed to find "which" in the search path. Command: which, OS error code: 0
```
#0      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:118:7)
#1      ErrorHandlingProcessManager.runSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:712:24)
#2      _runSync (package:flutter_tools/src/base/error_handling_io.dart:597:14)
#3      ErrorHandlingProcessManager.runSync (package:flutter_tools/src/base/error_handling_io.dart:711:12)
#4      _PosixUtils._which (package:flutter_tools/src/base/os.dart:212:50)
#5      OperatingSystemUtils.whichAll (package:flutter_tools/src/base/os.dart:101:43)
#6      AndroidSdk.locateAndroidSdk.findAndroidHomeDir (package:flutter_tools/src/android/android_sdk.dart:122:46)
#7      AndroidSdk.locateAndroidSdk (package:flutter_tools/src/android/android_sdk.dart:146:36)
#8      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#9      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:453:23)
#10     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#11     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#12     AppContext.get (package:flutter_tools/src/base/context.dart:119:24)
#13     androidSdk (package:flutter_tools/src/globals_null_migrated.dart:66:39)
#14     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:191:29)
#15     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#16     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:453:23)
#17     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#18     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#19     AppContext.get (package:flutter_tools/src/base/context.dart:119:24)
#20     deviceManager (package:flutter_tools/src/globals_null_migrated.dart:58:45)
#21     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:266:17)
<asynchronous suspension>
#22     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
encountered exception: ProcessException: Failed to find "which" in the search path.
  Command: which 

#0      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:118:7)
#1      ErrorHandlingProcessManager.runSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:712:24)
#2      _runSync (package:flutter_tools/src/base/error_handling_io.dart:597:14)
#3      ErrorHandlingProcessManager.runSync (package:flutter_tools/src/base/error_handling_io.dart:711:12)
#4      _PosixUtils._which (package:flutter_tools/src/base/os.dart:212:50)
#5      OperatingSystemUtils.whichAll (package:flutter_tools/src/base/os.dart:101:43)
#6      AndroidSdk.locateAndroidSdk.findAndroidHomeDir (package:flutter_tools/src/android/android_sdk.dart:122:46)
#7      AndroidSdk.locateAndroidSdk (package:flutter_tools/src/android/android_sdk.dart:146:36)
#8      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#9      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:453:23)
#10     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#11     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#12     androidSdk (package:flutter_tools/src/globals_null_migrated.dart:66:39)
#13     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:122:29)
#14     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#15     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:453:23)
#16     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#17     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#18     androidWorkflow (package:flutter_tools/src/android/android_workflow.dart:26:49)
#19     _DefaultDoctorValidatorsProvider.validators (package:flutter_tools/src/doctor.dart:77:11)
#20     Doctor.validators (package:flutter_tools/src/doctor.dart:184:47)
#21     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:190:45)
#22     Doctor.diagnose (package:flutter_tools/src/doctor.dart:301:47)
#23     _doctorText (package:flutter_tools/runner.dart:232:18)
#24     _handleToolError (package:flutter_tools/runner.dart:156:27)
<asynchronous suspension>
#25     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#26     main (package:flutter_tools/executable.dart:94:3)
<asynchronous suspension>

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by danagbemava-nc** [comment]
Hi @whisper540, thanks for reporting this. 

What OS are you using and are you able to run any other flutter commands? If you are able to run other flutter commands, please provide the output of `flutter doctor -v`. 

Thank you
