### ISSUE TITLE
Exception caught by image resource service

### ISSUE THREAD

**Issue by masreplay** [flutter/flutter#95332]
The following ArgumentError was thrown resolving an image codec:
Invalid argument(s): No host specified in URI file:///

When the exception was thrown, this was the stack: 
#0      _HttpClient._openUrl (dart:_http/http_impl.dart:2666:9)
#1      _HttpClient.getUrl (dart:_http/http_impl.dart:2574:48)
#2      NetworkImage._loadAsync (package:flutter/src/painting/_network_image_io.dart:89:59)
#3      NetworkImage.load (package:flutter/src/painting/_network_image_io.dart:50:14)
#4      ImageProvider.resolveStreamForKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:505:13)
#5      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:380:22)
#6      ImageProvider.resolveStreamForKey (package:flutter/src/painting/image_provider.dart:503:83)
#7      ScrollAwareImageProvider.resolveStreamForKey (package:flutter/src/widgets/scroll_aware_image_provider.dart:106:19)

**Comment by darshankawar** [comment]
@masreplay 
Can you provide `flutter doctor -v`, steps to replicate this along with a minimal code sample that throws this exception ?
Thanks.
