### ISSUE TITLE
FormatException: FormatException: Missing extension byte (at offset 1)

### ISSUE THREAD

**Issue by AbnerZS** [flutter/flutter#95368]
Flutter crash report.

## command

flutter build ios --debug

## exception

FormatException: FormatException: Missing extension byte (at offset 1)

```
#0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1893:7)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:28)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#5      _rootRunUnary (dart:async/zone.dart:1436:47)
#6      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#11     _StreamController._add (dart:async/stream_controller.dart:607:7)
#12     _StreamController.add (dart:async/stream_controller.dart:554:5)
#13     _Socket._onData (dart:io-patch/socket_patch.dart:2302:41)
#14     _rootRunUnary (dart:async/zone.dart:1444:13)
#15     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#19     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#20     _StreamController._add (dart:async/stream_controller.dart:607:7)
#21     _StreamController.add (dart:async/stream_controller.dart:554:5)
#22     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1830:33)
#23     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1314:14)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:122:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:193:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, 2.8.0, on macOS 11.3 20E232 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.8.0 at /Users/zs/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (7 days ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/Android/sdk
    • Platform android-29, build-tools 32.0.0
    • ANDROID_HOME = /Users/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.63.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • zs的 iPhone (mobile)    • 47d4ffae43b28e01e7266102430d3a5234ca45re • ios • iOS 15.0.2 19A404
    • iPhone 8-13.6 (mobile) • 2B4E262A-511D-43E1-9FAD-F9E3C4A73BFE     • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-6
      (simulator)

• No issues found!
```

**Comment by maheshmnj** [comment]
Hi @AbnerZS, Thanks for filing the issue.

There is a similar issue describing this case https://github.com/flutter/flutter/issues/81666, Please follow up there for further updates, Closing this issue as a duplicate. If you disagree feel free to write in the comments and I will reopen it.

Thank you.
