### ISSUE TITLE
Flutter driver integration test unable to scroll DropdownButton items

### ISSUE THREAD

**Issue by omatt** [flutter/flutter#95384]
I'm unable to find the Scrollable of the DropdownButton after using `widgetTester.tap()` using `find.byType(Scrollable);`. I'm following this [guide](https://docs.flutter.dev/cookbook/testing/widget/scrolling).

## Steps to Reproduce

Test

```dart
testWidgets("Test DropdownButton", (WidgetTester widgetTester) async {
  await widgetTester.pumpWidget(MyApp());
  final dropdownButtonFinder = find.byKey(const ValueKey('DropdownButton'));
  final dropdownItemFinder = find.textContaining('Item 10');
  
  // Tap on the DropdownButton
  await widgetTester.tap(dropdownButtonFinder);
  final dropdownListFinder = find.byType(Scrollable);  // Doesn't find any Scrollable

  // Scroll until the item to be found appears. Doesn't work for DropdownButton
  await widgetTester.scrollUntilVisible(dropdownItemFinder, 500.0,
     scrollable: dropdownListFinder);
  await widgetTester.tap(dropdownItemFinder);

  // Verify that the item contains the correct text.
  expect(dropdownItemFinder, findsOneWidget);
});
```

1. Run the test for the sample app with flutter driver
2. Error from the test finding the Scrollable

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following StateError was thrown running a test:
Bad state: No element

When the exception was thrown, this was the stack:
#0      Iterable.single (dart:core/iterable.dart:520:25)
#1      WidgetController.widget (package:flutter_test/src/controller.dart:69:30)
#2      WidgetController.scrollUntilVisible.<anonymous closure> (package:flutter_test/src/controller.dart:1192:15)
#3      WidgetController.scrollUntilVisible.<anonymous closure> (package:flutter_test/src/controller.dart:1190:39)
#6      TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#7      WidgetController.scrollUntilVisible (package:flutter_test/src/controller.dart:1190:27)
#8      main.<anonymous closure> (file:///Users/Downloads/dev/flutter/sampletest/integration_test/sample_test.dart:74:24)
<asynchronous suspension>
#9      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:176:15)
<asynchronous suspension>
#10     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:817:5)
<asynchronous suspension>
(elided 2 frames from dart:async)

```

**Expected results:** 

Flutter test should be able to find the Scrollable from DropdownButton after `widgetTester.tap()`

**Actual results:** 

Integration test returns `Bad state: No element` error looking for the Scrollable. Skipping the part of looking for a Scrollable and just using `find.textContaining(String)` to find the Dropdown item works fine though.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<String> mockList() => List<String>.generate(100, (i) => 'Item $i');
  String? dropdownValue;

  @override
  Widget build(BuildContext context) {
    // debugPrint('${foo!}');
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
        key: Key('Widget1'),
      ),
      body: Center(
        child: DropdownButton(
          key: Key('DropdownButton'),
          value: dropdownValue,
          onChanged: (String? newValue) {
            setState(() {
              dropdownValue = newValue!;
            });
          },
          items: mockList()
              .map<DropdownMenuItem<String>>(
                (String value) => DropdownMenuItem<String>(
                  value: value,
                  child: Text(value),
                  key: Key('item$value'),
                ),
              )
              .toList(),
      )
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-x64)
    • Flutter version 2.5.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (9 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.63.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

! Doctor found issues in 1 category.
Process finished with exit code 0
```

</details>

**Comment by mamuseferha** [comment]
Hi @omatt, this doesn't seem like the right way to test a DropdownButton, see links below for more information

https://stackoverflow.com/a/64496868
https://github.com/flutter/flutter/blob/master/packages/flutter/test/material/dropdown_test.dart
https://github.com/flutter/flutter/issues/89905

Please let me know if this works for you.

Thank you.

**Comment by omatt** [comment]
Hi @mamuseferha thanks for providing these references. However, upon checking, the issues on the references you've shared doesn't have the scrolling issue I've mentioned. Let me know on how I can apply the references you've shared to solve this issue.

Note that `find.textContaining('Item 10');` works fine if I skipped `find.byType(Scrollable);` after `widgetTester.tap(dropdownButtonFinder);`. So I can seem to find DropdownButton items, just not the scrolling part.

**Comment by mamuseferha** [comment]
Hi @omatt, I tested this on the latest stable and master channel and it is reproducible. Dropdown button test is unable to find a scrollable when tapped.

<details>
<summary>logs</summary>

```bash

══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following StateError was thrown running a test:
Bad state: No element

When the exception was thrown, this was the stack:
#0      Iterable.single (dart:core/iterable.dart:654:25)
#1      WidgetController.widget (package:flutter_test/src/controller.dart:69:30)
#2      WidgetController.scrollUntilVisible.<anonymous closure> (package:flutter_test/src/controller.dart:1190:15)
#3      WidgetController.scrollUntilVisible.<anonymous closure> (package:flutter_test/src/controller.dart:1188:39)
#6      TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#7      WidgetController.scrollUntilVisible (package:flutter_test/src/controller.dart:1188:27)
#8      main.<anonymous closure> (file:///Users/flo/projects/oos/flutter_master/test/main_test.dart:17:24)
<asynchronous suspension>
<asynchronous suspension>
(elided 3 frames from dart:async and package:stack_trace)

The test description was:
  Test DropdownButton
════════════════════════════════════════════════════════════════════════════════════════════════════
Test failed. See exception logs above.
The test description was: Test DropdownButton

✖ Test DropdownButton
Exited (1)

```
</details>



<details>
<summary>code sample</summary>

```dart

import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<String> mockList() => List<String>.generate(100, (i) => 'Item $i');
  String? dropdownValue;

  @override
  Widget build(BuildContext context) {
    // debugPrint('${foo!}');
    return Scaffold(
        appBar: AppBar(
          title: Text(widget.title),
          key: Key('Widget1'),
        ),
        body: Center(
            child: DropdownButton(
          key: Key('DropdownButton'),
          value: dropdownValue,
          onChanged: (String? newValue) {
            setState(() {
              dropdownValue = newValue!;
            });
          },
          items: mockList()
              .map<DropdownMenuItem<String>>(
                (String value) => DropdownMenuItem<String>(
                  value: value,
                  child: Text(value),
                  key: Key('item$value'),
                ),
              )
              .toList(),
        )));
  }
}

```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6.1 20G224 darwin-x64, locale en-US)
    • Flutter version 2.8.1 at /Users/flo/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (18 hours ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/flo/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554                        • android-x86    • Android 11 (API 30)
      (emulator)
    • iPhone 13 (mobile)                 • EF1251D3-C9C4-475E-9F91-58CD010FDA48 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)                    • macos                                • darwin-x64     • macOS 11.6.1 20G224
      darwin-x64
    • Chrome (web)                       • chrome                               • web-javascript • Google Chrome 93.0.4577.63

• No issues found!
```
```bash
[✓] Flutter (Channel master, 2.9.0-1.0.pre.123, on macOS 11.6.1 20G224 darwin-x64, locale en-US)
    • Flutter version 2.9.0-1.0.pre.123 at /Users/flo/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5087f2de4c (5 hours ago), 2021-12-17 00:29:09 -0500
    • Engine revision 9177b32b75
    • Dart version 2.16.0 (build 2.16.0-118.0.dev)
    • DevTools version 2.9.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/flo/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554                        • android-x86    • Android 11 (API 30) (emulator)
    • iPhone 13 (mobile)                 • EF1251D3-C9C4-475E-9F91-58CD010FDA48 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)                    • macos                                • darwin-x64     • macOS 11.6.1 20G224 darwin-x64
    • Chrome (web)                       • chrome                               • web-javascript • Google Chrome 93.0.4577.63

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

Thank you

**Comment by werainkhatri** [comment]
Hi @omatt. This is working as intended. The popup list, and hence the `Scrollable` is not a part of the tree unless the `DropdownButton` is tapped and the animation completes. To test it, you have to wait after tapping it for the animation to complete, and then you'll be able to locate the `Scrollable`. Lemme know if this resolves your issue.

```dart
testWidgets("Test DropdownButton", (WidgetTester widgetTester) async {
  await widgetTester.pumpWidget(MyApp());
  final dropdownButtonFinder = find.byKey(const ValueKey('DropdownButton'));
  final dropdownItemFinder = find.textContaining('Item 10');
  
  // Tap on the DropdownButton
  await widgetTester.tap(dropdownButtonFinder);

  await tester.pumpAndSettle(); // wait for the dropdown animation to complete
  expect(find.byType(Scrollable), findsOneWidget); // expectation is met

  final dropdownListFinder = find.byType(Scrollable);

  // Scroll until the item to be found appears. Doesn't work for DropdownButton
  await widgetTester.scrollUntilVisible(dropdownItemFinder, 500.0,
     scrollable: dropdownListFinder);
  await widgetTester.tap(dropdownItemFinder);

  // Verify that the item contains the correct text.
  expect(dropdownItemFinder, findsOneWidget);
});
```

**Comment by omatt** [comment]
Thanks! Adding `widgetTester.pumpAndSettle()` worked for me and pointed me to the right direction. I'm now able to scroll on the List popup from the DropdownButton. Though oddly `find.textContaining(String)` doesn't seem to work for Text on List Items. I had to use `find.widgetWithText(InkWell, String)`.

```dart
testWidgets("Test DropdownButton", (WidgetTester widgetTester) async {
    await widgetTester.pumpWidget(MyApp());
    final dropdownButtonFinder = find.byKey(const ValueKey('DropdownButton'));
    final dropdownItemFinder = find.widgetWithText(InkWell, 'Item 50'); // find.textContaining() doesn't seem to work

    // Tap on the DropdownButton
    await widgetTester.tap(dropdownButtonFinder);
    await widgetTester.pumpAndSettle(const Duration(seconds: 2));
    final dropdownListFinder = find.byType(Scrollable);
    expect(dropdownListFinder, findsOneWidget); // Finds Scrollable from tapping DropDownButton

    // Scroll until the item to be found appears.
    await widgetTester.scrollUntilVisible(dropdownItemFinder, 500.0,
        scrollable: dropdownListFinder);
    await widgetTester.tap(dropdownItemFinder);
    await widgetTester.pumpAndSettle(const Duration(seconds: 2));

    // Verify that the item contains the correct text.
    expect(find.textContaining('Item 50'), findsOneWidget);
  });
```
