### ISSUE TITLE
[web][release] Throws `Uncaught TypeError: Cannot read properties of undefined (reading 'j')` trying to access `Map` value

### ISSUE THREAD

**Issue by haohd** [flutter/flutter#95380]
## Steps to Reproduce

1. Build web project using:  flutter build web
2. Deploy web release folder to a real server 
3. Connect to web using Chrome: https://192.168.96.102:1443/#/ 

**Expected results:** 
Below should be printed: 

```
Doing JSON POST ...
{success: true}
true
xxx
POST Done!
```

**Actual results:** 

```console
Navigated to https://192.168.96.102:1443/
main.dart.js:6459 XHR finished loading: GET "https://192.168.96.102:1443/assets/FontManifest.json".
main.dart.js:1741 Fetch finished loading: GET "https://192.168.96.102:1443/assets/packages/cupertino_icons/assets/CupertinoIcons.ttf".
main.dart.js:1741 Fetch finished loading: GET "https://192.168.96.102:1443/assets/fonts/MaterialIcons-Regular.otf".
main.dart.js:15357 Doing JSON POST ...
main.dart.js:1741 Fetch finished loading: GET "https://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf".
main.dart.js:15357 {success: true}
main.dart.js:3671 Uncaught TypeError: Cannot read properties of undefined (reading 'j')
    at a_l.$2 (main.dart.js:46822)
    at main.dart.js:14958
    at ZL.a (main.dart.js:4846)
    at ZL.$2 (main.dart.js:26907)
    at YQ.$1 (main.dart.js:26901)
    at XI.TZ (main.dart.js:27546)
    at XI.uA (main.dart.js:27548)
    at Wm.$0 (main.dart.js:27163)
    at Object.nz (main.dart.js:4957)
    at U.hy (main.dart.js:27087)
main.dart.js:29613 XHR finished loading: POST "https://reqbin.com/echo/post/json".
```

**Code sample**

```dart
import 'package:flutter/material.dart';
import 'dart:async';
import 'dart:convert';
import 'package:http/http.dart' as http;

void main() async {
  Map<String, dynamic> payload = {
    "Id": 78912,
    "Customer": "Jason Sweet",
    "Quantity": 1,
    "Price": 18.00
  };
  print("Doing JSON POST ...");
  await request(
      "https://reqbin.com/echo/post/json",
      payload,
      (error, Map<String, dynamic> resp) {
        print(resp);
        print(resp["success"]);    // Crashed at this line 
        print("xxx");
      });
  print("JSON POST Done!");
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
	// Codes are ommited for simple 
}

Future<void> request(uri, payload, callback) async {
  var _resp;
  int errorCode = -1;

  Map<String, String> _headers = {
    'Content-type': 'application/json'
  };
  try {
    http.Response response;
    response = await http.post(
        Uri.parse(uri),
        body: json.encode(payload),
        headers: _headers).timeout(const Duration(seconds: 20));

    if (response.statusCode == 200 || response.statusCode == 204) {
      errorCode = 0;
    }

    if (response.body != "") {
      try {
        _resp = (json.decode(response.body) as Map<String, dynamic>);
      } catch (_) {
        try {
          _resp = (json.decode(response.body) as List<dynamic>);
        } catch (_) {
          errorCode = -1;
          _resp = {}.cast<String, dynamic>();
        }
      }
    }
    return;
  } catch (e) {
    errorCode = -1;
  } finally {
    callback(errorCode, _resp); // *** May be invoke "callback" funtion in "finally" block caused issue?????? 
  }
}
```

<details>
  <summary>Logs</summary>

```console
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.8.0, on Microsoft Windows [Version 10.0.19043.1348], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.3.1)
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.63.1)
[√] Connected device (3 available)

• No issues found!

```

</details>

**Comment by danagbemava-nc** [comment]
Issue is reproducible on `stable` and `master`. 

## Observations

- Just reading the value in the `finally` block isn't enough to reproduce this issue. Tested with sample below. 

<details>
<summary>sample</summary>

```dart
import 'dart:convert';

import 'package:flutter/material.dart';

void main() async {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          someFunction();
        },
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

void someFunction() {
  final map = {'a': 1, 'b': 'Nexus', 'c': true};

  try {
    print('in try');
  } catch (_) {
    print('ex');
  } finally {
    print(map);
    print(map['c']);
  }
}
```

</details>

- The error did not reproduce for me when I put the callback calls inside the try/catch block, instead of finally 

<details>
<summary>sample used</summary>

```dart
import 'package:flutter/material.dart';
import 'dart:async';
import 'dart:convert';
import 'package:http/http.dart' as http;

void main() async {
  Map<String, dynamic> payload = {
    'Id': 78912,
    'Customer': 'Jason Sweet',
    'Quantity': 1,
    'Price': 18.00
  };
  print('Doing JSON POST ...');
  await request('https://reqbin.com/echo/post/json', payload,
      (error, Map<String, dynamic> resp) {
    print(resp);
    print(resp['success']); // Crashed at this line
    print('xxx');
  });
  print('JSON POST Done!');
  runApp(const MyApp());
}

Future<void> request(uri, payload, callback) async {
  var _resp;
  int errorCode = -1;

  Map<String, String> _headers = {'Content-type': 'application/json'};
  try {
    http.Response response;
    response = await http
        .post(Uri.parse(uri), body: json.encode(payload), headers: _headers)
        .timeout(const Duration(seconds: 20));

    if (response.statusCode == 200 || response.statusCode == 204) {
      errorCode = 0;
    }

    if (response.body != '') {
      try {
        _resp = (json.decode(response.body) as Map<String, dynamic>);
        callback(0, _resp);
      } catch (_) {
        try {
          _resp = (json.decode(response.body) as List<dynamic>);
          callback(0, {'success': _resp});
        } catch (_) {
          errorCode = -1;
          _resp = {}.cast<String, dynamic>();
          callback(errorCode, {});
        }
      }
    }
    return;
  } catch (e) {
    errorCode = -1;
    callback(errorCode, {});
  }
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () async {},
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

```
</details>

- Issue can be reproduced using the sample provided by OP above 

<details>
<summary>complete sample</summary>

```dart
import 'package:flutter/material.dart';
import 'dart:async';
import 'dart:convert';
import 'package:http/http.dart' as http;

void main() async {
  Map<String, dynamic> payload = {
    'Id': 78912,
    'Customer': 'Jason Sweet',
    'Quantity': 1,
    'Price': 18.00
  };
  print('Doing JSON POST ...');
  await request('https://reqbin.com/echo/post/json', payload,
      (error, Map<String, dynamic> resp) {
    print(resp);
    print(resp['success']); // Crashed at this line
    print('xxx');
  });
  print('JSON POST Done!');
  runApp(const MyApp());
}

Future<void> request(uri, payload, callback) async {
  var _resp;
  int errorCode = -1;

  Map<String, String> _headers = {'Content-type': 'application/json'};
  try {
    http.Response response;
    response = await http
        .post(Uri.parse(uri), body: json.encode(payload), headers: _headers)
        .timeout(const Duration(seconds: 20));

    if (response.statusCode == 200 || response.statusCode == 204) {
      errorCode = 0;
    }

    if (response.body != '') {
      try {
        _resp = (json.decode(response.body) as Map<String, dynamic>);
        callback(0, _resp);
      } catch (_) {
        try {
          _resp = (json.decode(response.body) as List<dynamic>);
          callback(0, {'success': _resp});
        } catch (_) {
          errorCode = -1;
          _resp = {}.cast<String, dynamic>();
          callback(errorCode, {});
        }
      }
    }
    return;
  } catch (e) {
    errorCode = -1;
  } finally {
    callback(errorCode,
        _resp); // *** May be invoke 'callback' funtion in 'finally' block caused issue??????
  }
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () async {},
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

```
</details>

# Steps to reproduce

- Use the complete sample 
- Build for web and deploy to any site
- Open the page


<details>
<summary> screenshot of log from brave console</summary>

<img width="1151" alt="Screenshot 2021-12-16 at 12 46 49" src="https://user-images.githubusercontent.com/88313112/146375034-0534c175-6939-4605-8b74-f2b9be8fda3f.png">

</details>

<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.8.0, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.8.0 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (8 days ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:318:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1428:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1863:10)
      #15     runZonedGuarded (dart:async/zone.dart:1851:12)
      #16     runZoned (dart:async/zone.dart:1782:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:197:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:301:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:53:47)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1290:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.63.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 96.0.4664.110

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel master, 2.9.0-1.0.pre.107, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.9.0-1.0.pre.107 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 048e28ab3d (9 hours ago), 2021-12-15 22:59:12 -0500
    • Engine revision a05c4d23ec
    • Dart version 2.16.0 (build 2.16.0-115.0.dev)
    • DevTools version 2.9.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1426:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1861:10)
      #15     runZonedGuarded (dart:async/zone.dart:1849:12)
      #16     runZoned (dart:async/zone.dart:1780:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:198:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:302:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.63.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 96.0.4664.110

! Doctor found issues in 1 category.
```
</details>


SN: I will try to create a sample that doesn't have the `http` package in it, as I don't believe this is an issue with the `http` package, considering the response is successfully retrieved and subsequently logged. It's most likely an issue with minification.

**Comment by haohd** [comment]
@danagbemava-nc  Thank you for trying to reproduce this issue. I also see that the error does not occur when putting the callback calls inside the try/catch block, instead of finally.

**Comment by annagrin** [comment]
I believe the crash happens due to type mismatch between caller of `callback` (resp can be null or a list) and the actual callback value (resp is expected to me a map). So this works as intended - and moving your callback call to a try/catch block catches the runtime exception.

Adding types will make the failure static and help clarify the code - not that it does not compile and will force you to pass the argument with the correct type to the callback:

```dart

import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'package:http/http.dart' as http;

HttpServer? server;

void main() async {
  
  serve();
  Map<String, dynamic> payload = {
    "Id": 78912,
    "Customer": "Jason Sweet",
    "Quantity": 1,
    "Price": 18.00
  };
  print("Doing JSON POST ...");
  await request(
      "http://localhost:8080/json",
      payload,
      // Expecting a non-null map as a second parameter
      (Object error, Map<String, dynamic> resp) {
        print(resp);
        print(resp["success"]);    // Crashed at this line 
        print("xxx");
      });
  print("JSON POST Done!");
  
  await stop();
  print('Done');
}

Future<void> serve() async {
  server = await HttpServer.bind(InternetAddress.loopbackIPv4, 8080);
  server?.listen((HttpRequest request) { 
    var response = request.response;
    response.statusCode = HttpStatus.ok;
    response.write(json.encode({ "Success": true }));
    response.close();
  });
}

Future<dynamic>? stop() => server?.close();

Future<void> request(String uri, Map<String, dynamic> payload, void Function(Object error, Map<String, dynamic> resp) callback) async {
  // resp has to be a map
  Map<String, dynamic>? _resp;
  int errorCode = -1;

  Map<String, String> _headers = {
    'Content-type': 'application/json'
  };
  try {
    http.Response response;
    response = await http.post(
        Uri.parse(uri),
        body: json.encode(payload),
        headers: _headers).timeout(const Duration(seconds: 20));

    if (response.statusCode == 200 || response.statusCode == 204) {
      errorCode = 0;
    }

    if (response.body != "") {
      try {
        _resp = json.decode(response.body) as Map<String, dynamic>;
      } catch (_) {
        try {
          var t = json.decode(response.body) as List<dynamic>;
          // has to be a map
          _resp = {}.cast<String, dynamic>();
        } catch (_) {
          errorCode = -1;
          _resp = {}.cast<String, dynamic>();
        }
      }
    }
    return;
  } catch (e) {
    errorCode = -1;
  } finally {
   // _resp has to be a non-null map so this should not compile.
    callback(errorCode, _resp); // *** May be invoke "callback" funtion in "finally" block caused issue?????? 
  }
}
```

**Comment by annagrin** [comment]
@haohd let me know if this helps.

**Comment by haohd** [comment]
Thanks @annagrin but this does not help to solve the issue. My sample, the `_resp` is not null and a `Map<>`, but also caused the issue. The root cause I think due to invoke a callback in finally block. 

Code will OK if calling `callback(errorCode, _resp)` outside finally block.

**Comment by rakudrama** [comment]
Quick update.

**dart2js** has a bug in accounting correctly for all the possible values of `_resp` in the nested try-catch-finally statements.
It 'believes' that `_resp` is always the `CastMap` from `{}.cast<String, dynamic>()`. It then generates bad code for `resp["success"]` which crashes.

We will create a smaller reproduction, open a bug report in the Dart sdk, and link it to this report.

**Comment by fishythefish** [comment]
https://github.com/dart-lang/sdk/issues/48422 is our SDK issue.

**Comment by nshahan** [comment]
The change by @fishythefish has been rolled into the engine and that version of the engine has now been rolled into flutter.
