### ISSUE TITLE
[video_player]Playback error com.google.android.exoplayer2.ExoPlaybackException: Source error after setting httpHeaders  

### ISSUE THREAD

**Issue by wtjperi2003** [flutter/flutter#95385]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 
play video 
**Actual results:** 
stop playing.
<details>
<summary>Code sample</summary>

```dart
//I have to set referer to httpHeaders. At the begining,it plays well. but about 15 minutes later, video player throws a error,and it stops playing. It seems that video player forgets to take httpheaders from second request to datasource
// I have tried many times. I find the season. Because ts url in the m3u8 file   is expired after 15 minutes. How can I solve this problem? 
VideoPlayerController.network(
        url,
        formatHint: VideoFormat.hls,
        httpHeaders: const {"referer":"https://www.someurl.com/"}
    )..initialize().then((_) {
        // Ensure the first frame is shown after the video is initialized, even before the play button has been pressed.
        controller.play();
        notifyListeners();
      });
```

</details>

<details>
  <summary>Logs</summary>

```dart
E/ExoPlayerImplInternal(18820): Playback error
E/ExoPlayerImplInternal(18820):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal(18820):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
E/ExoPlayerImplInternal(18820):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal(18820):       at android.os.Looper.loop(Looper.java:193)
E/ExoPlayerImplInternal(18820):       at android.os.HandlerThread.run(HandlerThread.java:65)
E/ExoPlayerImplInternal(18820):   Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
E/ExoPlayerImplInternal(18820):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:383)
E/ExoPlayerImplInternal(18820):       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
E/ExoPlayerImplInternal(18820):       at com.google.android.exoplayer2.source.hls.HlsMediaChunk.prepareExtraction(HlsMediaChunk.java:482)
E/ExoPlayerImplInternal(18820):       at com.google.android.exoplayer2.source.hls.HlsMediaChunk.feedDataToExtractor(HlsMediaChunk.java:456)
E/ExoPlayerImplInternal(18820):       at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:431)
E/ExoPlayerImplInternal(18820):       at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:387)
E/ExoPlayerImplInternal(18820):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:417)
E/ExoPlayerImplInternal(18820):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal(18820):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal(18820):       at java.lang.Thread.run(Thread.java:764)
```

```
```

```
```

</details>

**Comment by maheshmnj** [comment]
Hi @wtjperi2003, Thanks for filing the issue. Is this issue on Android or IOS or both? Is it possible for you to share the video source and headers that you are passing? Also Is this issue reproducible only with a specific video source or any video source. Here are some sample video URLs  to verify with https://gist.github.com/jsturgis/3b19447b304616f18657

Please share your output of `flutter doctor -v`.

Thanks
