### ISSUE TITLE
"Failed to find target with hash string 'android-25'" when building hello_world example

### ISSUE THREAD

**Issue by kirbyfan64** [flutter/flutter#9543]
```
ryan@DevPC-LX ~/stuff/flutter/examples/hello_world master $ flutter build apk --verbose
[  +31 ms] [/media/ryan/stuff/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +33 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] [/media/ryan/stuff/flutter/] git ls-remote --get-url origin
[   +6 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] [/media/ryan/stuff/flutter/] git log -n 1 --pretty=format:%H
[   +5 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] ad496e142b9a1c114dea65e7d87e474cd85dd5c2
[        ] [/media/ryan/stuff/flutter/] git log -n 1 --pretty=format:%ar
[  +18 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 12 hours ago
[ +521 ms] Using gradle from /media/ryan/stuff/android-studio/gradle/gradle-2.14.1/bin/gradle.
[  +12 ms] Running 'gradle assembleRelease'...
[   +3 ms] [android/] /media/ryan/stuff/android-studio/gradle/gradle-2.14.1/bin/gradle -Ptarget=lib/main.dart assembleRelease
[ +925 ms] To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/2.14.1/userguide/gradle_daemon.html.
[+7349 ms] Observed package id 'tools' in inconsistent location '/media/ryan/stuff/android-studio/tools' (Expected '/media/ryan/stuff/android-studio/tools/tools')
[  +11 ms] Observed package id 'tools' in inconsistent location '/media/ryan/stuff/android-studio/tools' (Expected '/media/ryan/stuff/android-studio/tools/tools')
[  +35 ms] Observed package id 'tools' in inconsistent location '/media/ryan/stuff/android-studio/tools' (Expected '/media/ryan/stuff/android-studio/tools/tools')
[   +2 ms] File /media/ryan/stuff/android-sdk-home/.android/repositories.cfg could not be loaded.
[+1451 ms] Checking the license for package Android SDK Build-Tools 25.0.2 in /media/ryan/stuff/android-studio/tools/licenses
[   +8 ms] License for package Android SDK Build-Tools 25.0.2 accepted.
[  +13 ms] Preparing "Install Android SDK Build-Tools 25.0.2".
[+5646 ms] "Install Android SDK Build-Tools 25.0.2" ready.
[        ] Finishing "Install Android SDK Build-Tools 25.0.2"
[  +11 ms] Installing Android SDK Build-Tools 25.0.2 in /media/ryan/stuff/android-studio/tools/build-tools/25.0.2
[ +259 ms] "Install Android SDK Build-Tools 25.0.2" complete.
[   +1 ms] Checking the license for package Android SDK Platform 25 in /media/ryan/stuff/android-studio/tools/licenses
[   +1 ms] License for package Android SDK Platform 25 accepted.
[   +2 ms] Preparing "Install Android SDK Platform 25".
[+10017 ms] "Install Android SDK Platform 25" ready.
[        ] Finishing "Install Android SDK Platform 25"
[        ] Installing Android SDK Platform 25 in /media/ryan/stuff/android-studio/tools/platforms/android-25
[+3193 ms] "Install Android SDK Platform 25" complete.
[  +14 ms] Observed package id 'tools' in inconsistent location '/media/ryan/stuff/android-studio/tools' (Expected '/media/ryan/stuff/android-studio/tools/tools')
[  +38 ms] FAILURE: Build failed with an exception.
[   +1 ms] * Where:
[        ] Build file '/media/ryan/stuff/flutter/examples/hello_world/android/build.gradle' line: 20
[        ] * What went wrong:
[        ] A problem occurred evaluating root project 'android'.
[        ] > A problem occurred configuring project ':app'.
[        ]    > Failed to notify project evaluation listener.
[        ]       > Failed to find target with hash string 'android-25' in: /media/ryan/stuff/android-studio/tools
[        ]       > Could not get unknown property 'compileDebugJavaWithJavac' for project ':app' of type org.gradle.api.Project.
[        ] * Try:
[   +2 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
[   +1 ms] BUILD FAILED
[        ] Total time: 28.909 secs
[ +985 ms] 'flutter apk' took 30443ms.
Gradle build failed: 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:29)
#1      buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:233)
<asynchronous suspension>
#2      buildGradleProject (package:flutter_tools/src/android/gradle.dart:179)
<asynchronous suspension>
#3      buildApk (package:flutter_tools/src/commands/build_apk.dart:78)
<asynchronous suspension>
#4      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:50)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:151)
<asynchronous suspension>
#6      BuildSubCommand.verifyThenRunCommand (package:flutter_tools/src/commands/build.dart:50)
<asynchronous suspension>
#7      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:121)
#8      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:262)
<asynchronous suspension>
#10     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#11     Future.Future.sync (dart:async/future.dart:208)
#12     CommandRunner.run (package:args/command_runner.dart:109)
#13     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:157)
#14     run.<anonymous closure> (package:flutter_tools/executable.dart:140)
<asynchronous suspension>
#15     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#16     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#17     _rootRun (dart:async/zone.dart:1120)
#18     _CustomZone.run (dart:async/zone.dart:1001)
#19     runZoned (dart:async/zone.dart:1465)
#20     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#21     run (package:flutter_tools/executable.dart:113)
<asynchronous suspension>
#22     main (package:flutter_tools/executable.dart:66)
<asynchronous suspension>
#23     main (file:///media/ryan/stuff/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#24     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)


[ +265 ms] ensureAnalyticsSent: 253ms
[   +3 ms] exiting with code 1
ryan@DevPC-LX ~/stuff/flutter/examples/hello_world master $ 
```

Both `build-tools;25.0.2` and `platforms;android-25` have been installed.

## Flutter Doctor

```
[✓] Flutter (on Linux, channel master)
    • Flutter at /media/ryan/stuff/flutter
    • Framework revision ad496e142b (12 hours ago), 2017-04-22 10:27:03 +0200
    • Engine revision a5b64899c9
    • Tools Dart version 1.23.0-dev.11.11

[✓] Host Executable Compatibility
    • Downloaded executables execute on host

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /media/ryan/stuff/android-studio/tools
    • Platform android-25, build-tools 25.0.2
    • Java binary at: /media/ryan/stuff/android-studio/jre/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_76-release-b03)

[✓] Android Studio (version 2.2)
    • Android Studio at /media/ryan/stuff/android-studio
    • Gradle version 2.14.1
    • Java version: OpenJDK Runtime Environment (build 1.8.0_76-release-b03)

[✓] Connected devices
    • None
```

**Comment by kirbyfan64** [comment]
Found the problem! After reinstalling the SDK, it seems Gradle expects the SDK directory to be symlinked as `android-studio-directory/tools`, even if `ANDROID_HOME` is set correctly.

Fix: `ln -s $ANDROID_HOME android-studio/tools`

TBH though Gradle shouldn't assume that...

**Comment by Morpheous7** [comment]
I'm gettin the same error. Still don't know how you fixed this

**Comment by kirbyfan64** [comment]
@Morpheous7 Where is your Android SDK located, relative to the studio?

**Comment by Morpheous7** [comment]
On my c:/programs directory. I just started with a reinstall of my SDK to ver 25.3. It all started with me trying to work on a project I'd built on my old pc that used that version. After downloading the app to my current desktop I started getting the same error you had but couldn't work around it. I'm currently reinstalling my SDK (Closing android to do the install) and I'm hoping that fixes it

**Comment by kirbyfan64** [comment]
FWIW try moving your SDK to `android-studio/tools`, or letting Studio install it itself.

**Comment by mit-mit** [comment]
Closing this issue; I believe this is all gradle, and not in flutter

**Comment by Hixie** [comment]
@mit-mit Shouldn't we handle this more gracefully though?

**Comment by mit-mit** [comment]
It's my understanding that we already fixed that recently. I just tried to introduce an error in my gradle file, and I see:

```
mit-macbookpro2:gtest mit$ flutter build apk
Initializing gradle...                                0.9s
Resolving dependencies...
* Error running Gradle:
Exit code 1 from: /Users/mit/tmp/gtest/android/gradlew app:properties:

BUILD FAILED

Total time: 0.768 secs


FAILURE: Build failed with an exception.

* Where:
Build file '/Users/mit/tmp/gtest/android/app/build.gradle' line: 11

* What went wrong:
A problem occurred evaluating project ':app'.
> Flutter SDK not found. Define location with flutter.sdk in the local.properties file.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

Please review your Gradle project setup in the android/ folder.
mit-macbookpro2:gtest mit$
```

**Comment by Mnemoth42** [comment]
So I'm on a new computer, fresh install of Android Studio and am getting this message on my very first build.  It is staggeringly dumbfounding to me that I'd get this after letting AS handle all the installation, and I can't make heads or tails out of these fixes.
The only thing I can think of is that I created my new project on my E: drive, because I'm thinking saving my data on my small SSD system drive in users/docs is a terribly bad use of resources

**Comment by sssheridan5** [comment]
Same. I installed a fresh install 2 days ago, tried to do the android.developer.com's official tutorial for a first app, and I'm getting this error. Windows 10; Android Studio 3.0.1, build #AI-171.4443003, built on November 9, 2017, so it's not brand new.

When I go to the Run menu, the Run option is greyed out. When I go to Build > Make project, I get the following error:

```
Configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Failed to find target with hash string 'android-26' in: C:\Users\_____\AppData\Local\Android\Sdk
```

**Comment by ShineHtetAungSourcecode** [comment]
Try download SDK for API 25 from Android SDK Manager or by launching Android standalone SDK manager.
