### ISSUE TITLE
PageStorage.of(context)?.readState returns ItemPosition instead of double

### ISSUE THREAD

**Issue by Zfinix** [flutter/flutter#95454]
## Steps to Reproduce

1. Navigate to `/flutter/lib/src/widgets/scroll_position.dart`
2. Printing out `PageStorage` state shows returns `ItemPosition` instead of `double`
```dart
 @protected
  void restoreScrollOffset() {
    if (!hasPixels) {
      print(PageStorage.of(context.storageContext)
          ?.readState(context.storageContext));
          
       final double? value = PageStorage.of(context.storageContext)
          ?.readState(context.storageContext) as double?;

      if (value != null) correctPixels(value); 
    }
  }

````
## Logs

<details>
<summary>Logs</summary>

```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following _CastError was thrown building GridView(scrollDirection: vertical,
flutter: ScrollController#82dae(no clients), dependencies: [MediaQuery]):
flutter: type 'ItemPosition' is not a subtype of type 'double?' in type cast
flutter:
flutter: The relevant error-causing widget was:
flutter:   GridView
flutter:   GridView:file:///Users/chiziaruhoma/flutter/.pub-cache/hosted/pub.dartlang.org/stream_chat_flutter-3.3.2/lib/src/media_list_view.dart:49:25
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      ScrollPosition.restoreScrollOffset (package:flutter/src/widgets/scroll_position.dart:424:103)
flutter: #1      new ScrollPosition (package:flutter/src/widgets/scroll_position.dart:108:7)
flutter: #2      new ScrollPositionWithSingleContext (package:flutter/src/widgets/scroll_position_with_single_context.dart:56:8)
flutter: #3      ScrollController.createScrollPosition (package:flutter/src/widgets/scroll_controller.dart:233:12)
flutter: #4      ScrollableState._updatePosition (package:flutter/src/widgets/scrollable.dart:423:44)
flutter: #5      ScrollableState.didChangeDependencies (package:flutter/src/widgets/scrollable.dart:455:5)
flutter: #6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4749:11)
flutter: #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4561:5)
flutter: ...     Normal element mounting (29 frames)
flutter: #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3631:14)
flutter: #37     Element.updateChild (package:flutter/src/widgets/framework.dart:3380:20)
flutter: #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
flutter: #39     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
flutter: #40     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
flutter: #41     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2578:33)
flutter: #42     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
flutter: #43     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
flutter: #44     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
flutter: #45     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
flutter: #46     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
flutter: #50     _invoke (dart:ui/hooks.dart:150:10)
flutter: #51     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
flutter: #52     _drawFrame (dart:ui/hooks.dart:114:31)
flutter: (elided 3 frames from dart:async)
flutter:
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following _CastError was thrown building GridView(scrollDirection: vertical,
flutter: ScrollController#82dae(no clients), dependencies: [MediaQuery]):
flutter: type 'ItemPosition' is not a subtype of type 'double?' in type cast
flutter:
flutter: The relevant error-causing widget was:
flutter:   GridView
flutter:   GridView:file:///Users/chiziaruhoma/flutter/.pub-cache/hosted/pub.dartlang.org/stream_chat_flutter-3.3.2/lib/src/media_list_view.dart:49:25
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      ScrollPosition.restoreScrollOffset (package:flutter/src/widgets/scroll_position.dart:424:103)
flutter: #1      new ScrollPosition (package:flutter/src/widgets/scroll_position.dart:108:7)
flutter: #2      new ScrollPositionWithSingleContext (package:flutter/src/widgets/scroll_position_with_single_context.dart:56:8)
flutter: #3      ScrollController.createScrollPosition (package:flutter/src/widgets/scroll_controller.dart:233:12)
flutter: #4      ScrollableState._updatePosition (package:flutter/src/widgets/scrollable.dart:423:44)
flutter: #5      ScrollableState.didChangeDependencies (package:flutter/src/widgets/scrollable.dart:455:5)
flutter: #6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4749:11)
flutter: #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4561:5)
flutter: #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3631:14)
flutter: #9      Element.updateChild (package:flutter/src/widgets/framework.dart:3380:20)
flutter: #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
flutter: #11     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
flutter: #12     StatelessElement.update (package:flutter/src/widgets/framework.dart:4669:5)
flutter: #13     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
flutter: #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
flutter: #15     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
flutter: #16     StatelessElement.update (package:flutter/src/widgets/framework.dart:4669:5)
flutter: #17     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
flutter: #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
flutter: #19     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
flutter: #20     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
flutter: #21     StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
flutter: #22     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
flutter: #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
flutter: #24     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
flutter: #25     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
flutter: #26     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2578:33)
flutter: #27     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
flutter: #28     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
flutter: #29     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
flutter: #30     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
flutter: #31     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
flutter: #35     _invoke (dart:ui/hooks.dart:150:10)
flutter: #36     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
flutter: #37     _drawFrame (dart:ui/hooks.dart:114:31)
flutter: (elided 3 frames from dart:async)
```

```
➜ flutter doctor -v
[✓] Flutter (Channel beta, 2.8.0-3.3.pre, on macOS 12.1 21C5021h darwin-x64, locale en-NG)
    • Flutter version 2.8.0-3.3.pre at /Users/chiziaruhoma/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 262b70ece1 (2 weeks ago), 2021-12-01 13:00:48 -0800
    • Engine revision 06a7363b0c
    • Dart version 2.15.0 (build 2.15.0-268.18.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/chiziaruhoma/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.62.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] VS Code (version 1.64.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • iPhone 13 Pro Max (mobile) • 488776EB-0DF5-42DE-82DC-5EF4B07AE7DF • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0
      (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 12.1 21C5021h darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Brave Browser 96.1.32.113

• No issues found!
```

</details>

**Comment by mamuseferha** [comment]
Hi @Zfinix, thank you for filing this issue. I tried to reproduce this on the latest master and stable channel using the sample code below and it is not reproducible. PageStorage returns a double. 

Can you please provide a sample code that accurately captures the issue and does not include any third party package. You can also test again on the latest channels to see if issue persists.

<details>
<summary>output</summary>

<img width="899" alt="Screen Shot 2021-12-17 at 11 37 18 AM" src="https://user-images.githubusercontent.com/92717368/146532736-91166b87-29b2-48e9-9a7c-4ef820a3766b.png">

</details>

<details>
<summary>code sample</summary>

```dart

import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final List<Widget> pages = const <Widget>[
    ColorBoxPage(
      key: PageStorageKey<String>('pageOne'),
    ),
    ColorBoxPage(
      key: PageStorageKey<String>('pageTwo'),
    )
  ];
  int currentTab = 0;
  final PageStorageBucket _bucket = PageStorageBucket();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Persistence Example'),
      ),
      body: PageStorage(
        bucket: _bucket,
        child: pages[currentTab],
      ),
      bottomNavigationBar: BottomNavigationBar(
        currentIndex: currentTab,
        onTap: (int index) {
          setState(() {
            currentTab = index;
          });
        },
        items: const <BottomNavigationBarItem>[
          BottomNavigationBarItem(
            icon: Icon(Icons.home),
            label: 'page 1',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.settings),
            label: 'page2',
          ),
        ],
      ),
    );
  }
}

class ColorBoxPage extends StatelessWidget {
  const ColorBoxPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ListView.builder(
      itemExtent: 250.0,
      itemBuilder: (BuildContext context, int index) => Container(
        padding: const EdgeInsets.all(10.0),
        child: Material(
          color: index.isEven ? Colors.cyan : Colors.deepOrange,
          child: Center(
            child: Text(index.toString()),
          ),
        ),
      ),
    );
  }
}
```

</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6.1 20G224 darwin-x64, locale en-US)
    • Flutter version 2.8.1 at /Users/flo/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (18 hours ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/flo/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554                        • android-x86    • Android 11 (API 30)
      (emulator)
    • iPhone 13 (mobile)                 • EF1251D3-C9C4-475E-9F91-58CD010FDA48 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)                    • macos                                • darwin-x64     • macOS 11.6.1 20G224
      darwin-x64
    • Chrome (web)                       • chrome                               • web-javascript • Google Chrome 93.0.4577.63

• No issues found!
```
```bash
[✓] Flutter (Channel master, 2.9.0-1.0.pre.123, on macOS 11.6.1 20G224 darwin-x64, locale en-US)
    • Flutter version 2.9.0-1.0.pre.123 at /Users/flo/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5087f2de4c (5 hours ago), 2021-12-17 00:29:09 -0500
    • Engine revision 9177b32b75
    • Dart version 2.16.0 (build 2.16.0-118.0.dev)
    • DevTools version 2.9.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/flo/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554                        • android-x86    • Android 11 (API 30) (emulator)
    • iPhone 13 (mobile)                 • EF1251D3-C9C4-475E-9F91-58CD010FDA48 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)                    • macos                                • darwin-x64     • macOS 11.6.1 20G224 darwin-x64
    • Chrome (web)                       • chrome                               • web-javascript • Google Chrome 93.0.4577.63

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

Thank you

**Comment by Zfinix** [comment]
> Hi @Zfinix, thank you for filing this issue. I tried to reproduce this on the latest master and stable channel using the sample code below and it is not reproducible. PageStorage returns a double.
> 
> Can you please provide a sample code that accurately captures the issue and does not include any third party package. You can also test again on the latest channels to see if issue persists.
> 
> output
> code sample
> flutter doctor -v
> Thank you

A little digging shows that it's from a third party package, i think the docs for PageStorage should be clearer.
