### ISSUE TITLE
[webview_flutter] WebView blank screen

### ISSUE THREAD

**Issue by Okladnoj** [flutter/flutter#95475]
blank screen on Android(((

``` dart

  @override
  Widget build(BuildContext context) {
    final initialUrl = Uri.encodeFull('https://www.google.com');
    return SafeArea(
      child: Scaffold(
        body: Column(
          children: [
            Container(
              height: 50,
              color: Colors.black26,
            ),
            Expanded(
              child: WebView(
                key: UniqueKey(),
                initialUrl: initialUrl,
                javascriptMode: JavascriptMode.unrestricted,
              ),
            ),
          ],
        ),
      ),
    );
  }
```

**AndroidManifest**
``` xml
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
    <uses-permission android:name="android.permission.INTERNET" />

   <application
        android:label="CoffeesUP"
        android:icon="@mipmap/ic_launcher"
        android:requestLegacyExternalStorage="true"
        android:usesCleartextTraffic="true">
```
## flutter doctor -v

``` bash
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.0.1 21A559 darwin-arm, locale ru-UA)
    • Flutter version 2.8.1 at /Users/okji/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (27 hours ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/okji/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Redmi Note 8 Pro (mobile) • gubexwivz5e6eyt8 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)           • macos            • darwin-arm64   • macOS 12.0.1 21A559 darwin-arm
    • Chrome (web)              • chrome           • web-javascript • Google Chrome 96.0.4664.110
    ! Error: iPad (Dmytrij) is not connected. Xcode will continue when iPad (Dmytrij) is connected. (code -13)

• No issues found!
```

**Dubug console**
``` dart
Reloaded 1 of 1995 libraries in 1 297ms.
E/flutter ( 1580): [ERROR:flutter/shell/common/shell.cc(93)] Dart Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null), stack trace: #0      WebViewHostApi.create
E/flutter ( 1580): <asynchronous suspension>
E/flutter ( 1580):
E/flutter ( 1580): [ERROR:flutter/shell/common/shell.cc(93)] Dart Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null), stack trace: #0      WebSettingsHostApi.create
E/flutter ( 1580): <asynchronous suspension>
E/flutter ( 1580):
E/flutter ( 1580): [ERROR:flutter/shell/common/shell.cc(93)] Dart Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null), stack trace: #0      WebSettingsHostApi.setDomStorageEnabled
E/flutter ( 1580): <asynchronous suspension>
E/flutter ( 1580):
E/flutter ( 1580): [ERROR:flutter/shell/common/shell.cc(93)] Dart Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null), stack trace: #0      WebSettingsHostApi.setJavaScriptCanOpenWindowsAutomatically
E/flutter ( 1580): <asynchronous suspension>
E/flutter ( 1580):
E/flutter ( 1580): [ERROR:flutter/shell/common/shell.cc(93)] Dart Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null), stack trace: #0      WebSettingsHostApi.setSupportMultipleWindows
E/flutter ( 1580): <asynchronous suspension>
E/flutter ( 1580):
E/flutter ( 1580): [ERROR:flutter/shell/common/shell.cc(93)] Dart Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null), stack trace: #0      WebSettingsHostApi.setLoadWithOverviewMode
E/flutter ( 1580): <asynchronous suspension>
E/flutter ( 1580):
E/flutter ( 1580): [ERROR:flutter/shell/common/shell.cc(93)] Dart Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null), stack trace: #0      WebSettingsHostApi.setUseWideViewPort
E/flutter ( 1580): <asynchronous suspension>
E/flutter ( 1580):
E/flutter ( 1580): [ERROR:flutter/shell/common/shell.cc(93)] Dart Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null), stack trace: #0      WebSettingsHostApi.setDisplayZoomControls
E/flutter ( 1580): <asynchronous suspension>
E/flutter ( 1580):
E/flutter ( 1580): [ERROR:flutter/shell/common/shell.cc(93)] Dart Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null), stack trace: #0      WebSettingsHostApi.setBuiltInZoomControls
E/flutter ( 1580): <asynchronous suspension>
E/flutter ( 1580):
E/flutter ( 1580): [ERROR:flutter/shell/common/shell.cc(93)] Dart Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null), stack trace: #0      WebViewClientHostApi.create
E/flutter ( 1580): <asynchronous suspension>
E/flutter ( 1580):
E/flutter ( 1580): [ERROR:flutter/shell/common/shell.cc(93)] Dart Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null), stack trace: #0      WebSettingsHostApi.setUserAgentString
E/flutter ( 1580): <asynchronous suspension>
E/flutter ( 1580): #1      Future.wait.<anonymous closure> (dart:async/future.dart)
E/flutter ( 1580): <asynchronous suspension>
E/flutter ( 1580): #2      WebViewAndroidPlatformController.updateSettings
E/flutter ( 1580): <asynchronous suspension>
E/flutter ( 1580):
E/flutter ( 1580): [ERROR:flutter/shell/common/shell.cc(93)] Dart Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null), stack trace: #0      WebSettingsHostApi.setMediaPlaybackRequiresUserGesture
E/flutter ( 1580): <asynchronous suspension>
E/flutter ( 1580):
E/flutter ( 1580): [ERROR:flutter/shell/common/shell.cc(93)] Dart Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null), stack trace: #0      DownloadListenerHostApi.create
E/flutter ( 1580): <asynchronous suspension>
E/flutter ( 1580):
E/flutter ( 1580): [ERROR:flutter/shell/common/shell.cc(93)] Dart Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null), stack trace: #0      WebViewHostApi.setDownloadListener
E/flutter ( 1580): <asynchronous suspension>
E/flutter ( 1580):
E/flutter ( 1580): [ERROR:flutter/shell/common/shell.cc(93)] Dart Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null), stack trace: #0      WebChromeClientHostApi.create
E/flutter ( 1580): <asynchronous suspension>
E/flutter ( 1580):
E/flutter ( 1580): [ERROR:flutter/shell/common/shell.cc(93)] Dart Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null), stack trace: #0      WebViewHostApi.setWebChromeClient
E/flutter ( 1580): <asynchronous suspension>
E/flutter ( 1580):
E/flutter ( 1580): [ERROR:flutter/shell/common/shell.cc(93)] Dart Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null), stack trace: #0      WebViewHostApi.loadUrl
E/flutter ( 1580): <asynchronous suspension>
E/flutter ( 1580):
E/flutter ( 1580): [ERROR:flutter/shell/common/shell.cc(93)] Dart Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to create a platform view of unregistered type: plugins.flutter.io/webview
E/flutter ( 1580): 	at io.flutter.plugin.platform.PlatformViewsController$1.createAndroidViewForPlatformView(PlatformViewsController.java:142)
E/flutter ( 1580): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:104)
E/flutter ( 1580): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
E/flutter ( 1580): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter ( 1580): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/flutter ( 1580): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
E/flutter ( 1580): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter ( 1580): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/flutter ( 1580): 	at android.os.Looper.loop(Looper.java:193)
E/flutter ( 1580): 	at android.app.ActivityThread.main(ActivityThread.java:8057)
E/flutter ( 1580): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 1580): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
E/flutter ( 1580): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
E/flutter ( 1580): , null, null), stack trace: #0      StandardMethodCodec.decodeEnvelope
E/flutter ( 1580): #1      MethodChannel._invokeMethod
E/flutter ( 1580): <asynchronous suspension>
E/flutter ( 1580): #2      AndroidViewController.create
E/flutter ( 1580): <asynchronous suspension>
E/flutter ( 1580):
E/flutter ( 1580): [ERROR:flutter/shell/common/shell.cc(93)] Dart Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null), stack trace: #0      WebSettingsHostApi.dispose
E/flutter ( 1580): <asynchronous suspension>
E/flutter ( 1580):
E/flutter ( 1580): [ERROR:flutter/shell/common/shell.cc(93)] Dart Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null), stack trace: #0      WebViewHostApi.dispose
E/flutter ( 1580): <asynchronous suspension>
E/flutter ( 1580): #1      WebViewHostApiImpl.disposeFromInstance
E/flutter ( 1580): <asynchronous suspension>
E/flutter ( 1580):


```
![image](https://user-images.githubusercontent.com/36802187/146597064-bfcbb165-13ab-494b-8636-83d8aeceb372.png)

**Comment by danagbemava-nc** [comment]
Hi @Okladnoj, please provide the version of `webview_flutter` you're experiencing this issue what and what devices you're experiencing this issue on.

Thank you

**Comment by Okladnoj** [comment]
Conflict with:
`flutter_stripe: ^2.0.2`

!!!!
if commit - web view work
```
  #flutter_stripe: ^2.0.2
  webview_flutter: ^3.0.0
```

**Comment by danagbemava-nc** [comment]
If the introduction of `flutter_stripe` is what is causing the issue, an issue may need to be filed on their repo so an investigation can be conducted so we know why this happens.

**Comment by Okladnoj** [comment]
[Thank you for the offer. the story continues here](https://github.com/flutter-stripe/flutter_stripe/issues/490)
