### ISSUE TITLE
[tool_crash] _CastError: (#0      AppResourceBundle.translationFor (package:flutter_tools/src/localizations/gen_l10n_types.dart:509:76))

### ISSUE THREAD

**Issue by dstavy** [flutter/flutter#95534]
## Command
```
flutter --no-color pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_CastError: (#0      AppResourceBundle.translationFor (package:flutter_tools/src/localizations/gen_l10n_types.dart:509:76))
```
#0      AppResourceBundle.translationFor (package:flutter_tools/src/localizations/gen_l10n_types.dart:509:76)
#1      LocalizationsGenerator._generateBaseClassFile.<anonymous closure> (package:flutter_tools/src/localizations/gen_l10n.dart:1101:18)
#2      MappedIterator.moveNext (dart:_internal/iterable.dart:391:20)
#3      Iterable.join (dart:core/iterable.dart:364:23)
#4      LocalizationsGenerator._generateBaseClassFile (package:flutter_tools/src/localizations/gen_l10n.dart:1118:41)
#5      LocalizationsGenerator._generateCode (package:flutter_tools/src/localizations/gen_l10n.dart:1200:46)
#6      LocalizationsGenerator.writeOutputFiles (package:flutter_tools/src/localizations/gen_l10n.dart:1275:47)
#7      generateLocalizations (package:flutter_tools/src/localizations/gen_l10n.dart:69:9)
#8      GenerateLocalizationsTarget.build (package:flutter_tools/src/build_system/targets/localizations.dart:56:5)
#9      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:839:27)
<asynchronous suspension>
#10     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:606:16)
<asynchronous suspension>
#11     generateLocalizationsSyntheticPackage (package:flutter_tools/src/dart/generate_synthetic_packages.dart:58:30)
<asynchronous suspension>
#12     PackagesGetCommand._runPubGet (package:flutter_tools/src/commands/packages.dart:134:7)
<asynchronous suspension>
#13     PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:176:5)
<asynchronous suspension>
#14     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#16     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.0.1 21A559 darwin-x64, locale en-IL)
    • Flutter version 2.8.1 at /usr/local/Caskroom/flutter/2.2.3/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 days ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/dan/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/dan/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 96.0.4664.110

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+3
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 9b2d32b605630f28625709ebd9d78ab3016b2bf6

**Comment by danagbemava-nc** [comment]
Hi @dstavy , thanks for reporting this.

Is this an isolated event or does it occur frequently?

If it does, kindly provide steps to reproduce.

Please provide your pubspec.yaml as well.

Thank you
