### ISSUE TITLE
[Android] build.gradle defaultConfig with local.properties not working properly.

### ISSUE THREAD

**Issue by brunotacca** [flutter/flutter#95533]
Hello,

After coming back to an old flutter project and upgrading to 2.8 I found that there is a new configuration required at android/local.properties and the android/app/build.gradle is supposed to use these config variables.

However by creating a new flutter project and adding a dependency that requires minSdkVersion higher than 16, somehow, graddle doesn't recognize these properties and doesn't add them to the compiled src/debug/AndroidManifest.xml.

When I keep this configuration, it doesn't compile.

```
android/app/build.gradle:
  defaultConfig {
      // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
      applicationId "com.example.test_localconfig"
      minSdkVersion flutter.minSdkVersion
      targetSdkVersion flutter.targetSdkVersion
      versionCode flutterVersionCode.toInteger()
      versionName flutterVersionName
  }

android/local.properties
  sdk.dir=/home/tacca/Android/Sdk
  flutter.sdk=/home/tacca/tools/flutter
  flutter.buildMode=debug
  flutter.versionName=1.0.0
  flutter.versionCode=1
  flutter.minSdkVersion=21
  flutter.targetSdkVersion=30
  flutter.compileSdkVersion=30
```

However, by changing minSdkVersion and targetSdkVersion directly at build.gradle to 21 and 30, it works. 

## Steps to Reproduce

1. Create a new flutter project
2. Add a dependency that requires minSdkVersion higher than 16 (flutter_blue in my case)
3. Add the following lines to android/local.properties 

> flutter.minSdkVersion=21
> flutter.targetSdkVersion=30
> flutter.compileSdkVersion=30

4. Run the flutter project.

## Logs

<details>
<summary>flutter run -v (using flutter.minSdkVersion, not working)</summary>

```
tacca@tacca:~/Development/github/test_localconfig$ flutter run -v
[  +55 ms] executing: uname -m
[  +26 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +5 ms] executing: [/home/tacca/tools/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +4 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 262b70ece1aebf84f132c51ec4cf90be605ce61b
[        ] executing: [/home/tacca/tools/flutter/] git tag --points-at 262b70ece1aebf84f132c51ec4cf90be605ce61b
[  +10 ms] Exit code 0 from: git tag --points-at 262b70ece1aebf84f132c51ec4cf90be605ce61b
[        ] 2.8.0-3.3.pre
[   +7 ms] executing: [/home/tacca/tools/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/home/tacca/tools/flutter/] git ls-remote --get-url origin
[   +3 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +64 ms] executing: [/home/tacca/tools/flutter/] git rev-parse --abbrev-ref HEAD
[   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[  +44 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +46 ms] executing: /home/tacca/Android/Sdk/platform-tools/adb devices -l
[  +31 ms] List of devices attached
           ce06160611747d2705     device usb:1-3 product:heroltexx model:SM_G930F device:herolte transport_id:2
[   +6 ms] /home/tacca/Android/Sdk/platform-tools/adb -s ce06160611747d2705 shell getprop
[  +93 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +61 ms] Skipping pub get: version match.
[  +17 ms] Found plugin flutter_blue at /home/tacca/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_blue-0.8.0/
[  +89 ms] Found plugin flutter_blue at /home/tacca/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_blue-0.8.0/
[  +15 ms] Generating /home/tacca/Development/github/test_localconfig/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +43 ms] ro.hardware = samsungexynos8890
[  +30 ms] Initializing file store
[   +8 ms] Skipping target: gen_localizations
[   +3 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents:
/home/tacca/Development/github/test_localconfig/.dart_tool/package_config_subset}
[  +11 ms] Found plugin flutter_blue at /home/tacca/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_blue-0.8.0/
[  +10 ms] gen_dart_plugin_registrant: Complete
[   +1 ms] Skipping target: _composite
[   +1 ms] complete
[   +4 ms] Launching lib/main.dart on SM G930F in debug mode...
[   +4 ms] /home/tacca/tools/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /home/tacca/tools/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/tacca/tools/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata
-DFLUTTER_WEB_AUTO_DETECT=true --output-dill /tmp/flutter_tools.OFUBRI/flutter_tool.ITPGKQ/app.dill --packages
/home/tacca/Development/github/test_localconfig/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme
org-dartlang-root --initialize-from-dill build/c075001b96339384a97db4862b8ab8db.cache.dill.track.dill --enable-experiment=alternative-invalidation-strategy
[   +8 ms] executing: /home/tacca/Android/Sdk/build-tools/30.0.3/aapt dump xmltree /home/tacca/Development/github/test_localconfig/build/app/outputs/flutter-apk/app.apk
AndroidManifest.xml
[   +4 ms] Exit code 0 from: /home/tacca/Android/Sdk/build-tools/30.0.3/aapt dump xmltree /home/tacca/Development/github/test_localconfig/build/app/outputs/flutter-apk/app.apk
AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1f
               A: android:compileSdkVersionCodename(0x01010573)="12" (Raw: "12")
               A: package="com.example.test_localconfig" (Raw: "com.example.test_localconfig")
               A: platformBuildVersionCode=(type 0x10)0x1f
               A: platformBuildVersionName=(type 0x10)0xc
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x15
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1e
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: uses-permission (line=15)
                 A: android:name(0x01010003)="android.permission.BLUETOOTH" (Raw: "android.permission.BLUETOOTH")
               E: uses-permission (line=16)
                 A: android:name(0x01010003)="android.permission.BLUETOOTH_ADMIN" (Raw: "android.permission.BLUETOOTH_ADMIN")
               E: uses-permission (line=17)
                 A: android:name(0x01010003)="android.permission.ACCESS_FINE_LOCATION" (Raw: "android.permission.ACCESS_FINE_LOCATION")
               E: application (line=19)
                 A: android:label(0x01010001)="test_localconfig" (Raw: "test_localconfig")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="android.app.Application" (Raw: "android.app.Application")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=25)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.test_localconfig.MainActivity" (Raw: "com.example.test_localconfig.MainActivity")
                   A: android:exported(0x01010010)=(type 0x12)0xffffffff
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=40)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: intent-filter (line=44)
                     E: action (line=45)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=47)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=54)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +5 ms] executing: /home/tacca/Android/Sdk/platform-tools/adb -s ce06160611747d2705 shell -x logcat -v time -t 1
[  +12 ms] <- compile package:test_localconfig/main.dart
[ +134 ms] --------- beginning of main
                    12-19 19:34:40.990 E/adbd    (28387): service_to_fd: shell:logcat -v time -t 1
[   +7 ms] executing: /home/tacca/Android/Sdk/platform-tools/adb version
[   +4 ms] Android Debug Bridge version 1.0.41
           Version 31.0.2-7242960
           Installed as /home/tacca/Android/Sdk/platform-tools/adb
[   +1 ms] executing: /home/tacca/Android/Sdk/platform-tools/adb start-server
[   +5 ms] Building APK
[  +13 ms] Running Gradle task 'assembleDebug'...
[   +2 ms] Using gradle from /home/tacca/Development/github/test_localconfig/android/gradlew.
[  +30 ms] executing: /usr/local/android-studio/jre/bin/java -version
[  +80 ms] Exit code 0 from: /usr/local/android-studio/jre/bin/java -version
[        ] openjdk version "11.0.8" 2020-07-14
           OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
           OpenJDK 64-Bit Server VM (build 11.0.8+0-b944-6842174, mixed mode)
[   +1 ms] executing: [/home/tacca/Development/github/test_localconfig/android/] /home/tacca/Development/github/test_localconfig/android/gradlew -Pverbose=true
-Ptarget-platform=android-arm64 -Ptarget=/home/tacca/Development/github/test_localconfig/lib/main.dart -Pbase-application-name=android.app.Application
-Pdart-defines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== -Pdart-obfuscation=false -Ptrack-widget-creation=true -Ptree-shake-icons=false -Pfilesystem-scheme=org-dartlang-root assembleDebug
[+2786 ms] > Task :app:compileFlutterBuildDebug
[        ] [  +56 ms] executing: uname -m
[        ] [  +28 ms] Exit code 0 from: uname -m
[        ] [        ] x86_64
[        ] [   +4 ms] executing: [/home/tacca/tools/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [   +4 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] 262b70ece1aebf84f132c51ec4cf90be605ce61b
[        ] [        ] executing: [/home/tacca/tools/flutter/] git tag --points-at 262b70ece1aebf84f132c51ec4cf90be605ce61b
[        ] [  +10 ms] Exit code 0 from: git tag --points-at 262b70ece1aebf84f132c51ec4cf90be605ce61b
[        ] [        ] 2.8.0-3.3.pre
[        ] [   +8 ms] executing: [/home/tacca/tools/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/beta
[        ] [        ] executing: [/home/tacca/tools/flutter/] git ls-remote --get-url origin
[        ] [   +3 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +45 ms] executing: [/home/tacca/tools/flutter/] git rev-parse --abbrev-ref HEAD
[        ] [   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] beta
[        ] [  +42 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [  +74 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [  +32 ms] Initializing file store
[        ] [  +16 ms] Skipping target: gen_localizations
[        ] [  +10 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents:
/home/tacca/Development/github/test_localconfig/.dart_tool/package_config_subset}
[   +1 ms] [  +20 ms] Found plugin flutter_blue at /home/tacca/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_blue-0.8.0/
[        ] [  +20 ms] gen_dart_plugin_registrant: Complete
[   +1 ms] [        ] kernel_snapshot: Starting due to {}
[        ] [   +8 ms] /home/tacca/tools/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /home/tacca/tools/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot
--sdk-root /home/tacca/tools/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --target=flutter --no-print-incremental-dependencies -DFLUTTER_WEB_AUTO_DETECT=true
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --no-link-platform --packages
/home/tacca/Development/github/test_localconfig/.dart_tool/package_config.json --output-dill
/home/tacca/Development/github/test_localconfig/.dart_tool/flutter_build/c3b98f338088a311713415eb8cf1a73a/app.dill --depfile
/home/tacca/Development/github/test_localconfig/.dart_tool/flutter_build/c3b98f338088a311713415eb8cf1a73a/kernel_snapshot.d package:test_localconfig/main.dart
[+6386 ms] [+7740 ms] kernel_snapshot: Complete
[ +300 ms] [ +335 ms] debug_android_application: Starting due to {}
[ +299 ms] [ +282 ms] debug_android_application: Complete
[ +400 ms] [ +409 ms] Persisting file store
[        ] [   +5 ms] Done persisting file store
[        ] [   +3 ms] build succeeded.
[        ] [   +8 ms] "flutter assemble" took 8,991ms.
[ +199 ms] [ +153 ms] ensureAnalyticsSent: 150ms
[        ] [        ] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 0
[  +99 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[        ] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :flutter_blue:preBuild UP-TO-DATE
[        ] > Task :flutter_blue:preDebugBuild UP-TO-DATE
[        ] > Task :flutter_blue:compileDebugAidl NO-SOURCE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Task :flutter_blue:packageDebugRenderscript NO-SOURCE
[        ] > Task :app:compileDebugRenderscript NO-SOURCE
[        ] > Task :app:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :flutter_blue:writeDebugAarMetadata UP-TO-DATE
[  +98 ms] > Task :app:checkDebugAarMetadata UP-TO-DATE
[        ] > Task :app:cleanMergeDebugAssets
[        ] > Task :app:mergeDebugShaders UP-TO-DATE
[        ] > Task :app:compileDebugShaders NO-SOURCE
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[        ] > Task :flutter_blue:mergeDebugShaders UP-TO-DATE
[        ] > Task :flutter_blue:compileDebugShaders NO-SOURCE
[        ] > Task :flutter_blue:generateDebugAssets UP-TO-DATE
[        ] > Task :flutter_blue:packageDebugAssets UP-TO-DATE
[        ] > Task :app:mergeDebugAssets
[ +100 ms] > Task :app:copyFlutterAssetsDebug
[        ] > Task :app:generateDebugResValues UP-TO-DATE
[        ] > Task :app:generateDebugResources UP-TO-DATE
[        ] > Task :flutter_blue:compileDebugRenderscript NO-SOURCE
[        ] > Task :flutter_blue:generateDebugResValues UP-TO-DATE
[        ] > Task :flutter_blue:generateDebugResources UP-TO-DATE
[        ] > Task :flutter_blue:packageDebugResources UP-TO-DATE
[  +96 ms] > Task :app:createDebugCompatibleScreenManifests
[        ] > Task :app:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :flutter_blue:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :flutter_blue:processDebugManifest UP-TO-DATE
[        ] > Task :app:mergeDebugResources
[        ] > Task :app:processDebugMainManifest FAILED
[        ] See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.
[        ] /home/tacca/Development/github/test_localconfig/android/app/src/debug/AndroidManifest.xml Error:
[   +1 ms]      uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library [:flutter_blue]
/home/tacca/Development/github/test_localconfig/build/flutter_blue/intermediates/library_manifest/debug/AndroidManifest.xml as the library might be using APIs not available in 16
[        ]      Suggestion: use a compatible library with a minSdk of at most 16,
[        ]              or increase this project's minSdk version to at least 19,
[        ]              or use tools:overrideLibrary="com.pauldemarco.flutter_blue" to force usage (may lead to runtime failures)
[        ] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Execution failed for task ':app:processDebugMainManifest'.
[        ] > Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library [:flutter_blue]
/home/tacca/Development/github/test_localconfig/build/flutter_blue/intermediates/library_manifest/debug/AndroidManifest.xml as the library might be using APIs not available in 16
[        ]      Suggestion: use a compatible library with a minSdk of at most 16,
[        ]              or increase this project's minSdk version to at least 19,
[        ]              or use tools:overrideLibrary="com.pauldemarco.flutter_blue" to force usage (may lead to runtime failures)
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 10s
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
[        ] 20 actionable tasks: 7 executed, 13 up-to-date
[ +322 ms] Running Gradle task 'assembleDebug'... (completed in 11.2s)
[   +1 ms] 
           The plugin flutter_blue requires a higher Android SDK version.
           Fix this issue by adding the following to the file /home/tacca/Development/github/test_localconfig/android/app/build.gradle:
           android {
             defaultConfig {
               minSdkVersion 19
             }
           }
           
           
           Note that your app won't be available to users running Android SDKs below 19.
           Alternatively, try to find a version of this plugin that supports these lower versions of the Android SDK.
[   +2 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +1 ms] "flutter run" took 11,939ms.
[   +2 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:674:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>
           
           
[  +68 ms] ensureAnalyticsSent: 67ms
[        ] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
tacca@tacca:~/Development/github/test_localconfig$ flutter doctor -v
[✓] Flutter (Channel beta, 2.8.0-3.3.pre, on Ubuntu 20.04.1 LTS 5.11.0-36-generic, locale en_US.UTF-8)
    • Flutter version 2.8.0-3.3.pre at /home/tacca/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 262b70ece1 (3 weeks ago), 2021-12-01 13:00:48 -0800
    • Engine revision 06a7363b0c
    • Dart version 2.15.0 (build 2.15.0-268.18.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/tacca/Android/Sdk
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /home/tacca/Android/Sdk
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/brave-browser

[✓] Android Studio (version 4.2)
    • Android Studio at /usr/local/android-studio
    • Flutter plugin version 57.0.2
    • Dart plugin version 202.8488
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] VS Code (version 1.63.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • SM G930F (mobile) • ce06160611747d2705 • android-arm64  • Android 8.0.0 (API 26)
    • Chrome (web)      • chrome             • web-javascript • Brave Browser 93.1.29.81

• No issues found!
```

**Comment by serendipity1004** [comment]
I was wondering about this too. It would be great if instruction could be included in the migration guide.

**Comment by cyanlink** [comment]
I review the flutter.gradle in the SDK, and found neither property definition nor reading of local.properties. There are only hardcoded minSdkVersion 16. Setting said property in gradle.properties does not work also.

`/** Sets the minSdkVersion used by default in Flutter app projects. */
    static int minSdkVersion = 16`

Maybe hardcoding is the only solution at hand.

**Comment by maheshmnj** [comment]
HI @brunotacca, Thanks for filing the issue. I could not find it either from where these constants (`flutter.minSdkVersion`) were being read, I searched through the newly created project couldn't find any references at all. Probably these need to be documented. Considering this as a documentation bug.

cc: @blasten

**Comment by tranvannhat** [comment]
same issue

**Comment by zerobytes** [comment]
Looks the 16 version is defined here
https://github.com/flutter/flutter/blob/stable/packages/flutter_tools/gradle/flutter.gradle

**Comment by brunotacca** [comment]
> HI @brunotacca, Thanks for filing the issue. I could not find it either from where these constants (`flutter.minSdkVersion`) were being read, I searched through the newly created project couldn't find any references at all. Probably these need to be documented. Considering this as a documentation bug.
> 
> cc: @blasten

I don't think it's just a documentation problem, the local variables are also not being read.
I will try to send a PR later today.

**Comment by fernando-s97** [comment]
Any updates on that?

**Comment by TahaTesser** [comment]
https://github.com/flutter/flutter/pull/95684 should fix this

**Comment by brunotacca** [comment]
> #95684 should fix this After this lands, it should be documented in https://docs.flutter.dev/deployment/android#reviewing-the-build-configuration

@TahaTesser May I go ahead and make a PR beforehand for that too? Thanks.

**Comment by TahaTesser** [comment]
@brunotacca 
Sure, it would be really helpful, thanks

**Comment by maheshmnj** [comment]
Thanks for the PR @brunotacca

**Comment by blasten** [comment]
Sorry, I can see that this might have broken older projects. 

Was the issue that `flutter.minSdkVersion` looks like something that a user should not change?  If this is the case, we could have fixed this problem by adding comments.

local.properties is not the standard way of configuring these values in Android or AGP convention.

**Comment by maheshmnj** [comment]
The issue was those constants were not configurable e.g value of `flutter.minSdkVersion` could not be changed and user had to hardcode the values in `app/build.gradle`

**Comment by blasten** [comment]
@maheshmnj sorry, the intention was to make the default value a constant defined by Flutter, but developers can still change  Android's Gradle `minSdkVersion`.  

would it help if we add comments to the generated build.gradle to clarify this?

**Comment by maheshmnj** [comment]
If those comments could explain how to modify the default constants, I believe this will resolve the issue.

**Comment by carepollo** [comment]
I have the same issue, but at the time of hardcoding those variables I have many errors like these:

`
Execution failed for task ':app:processDebugResources'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform play-services-base-17.1.0.aar (com.google.android.gms:play-services-base:17.1.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /home/hgc/.gradle/caches/transforms-2/files-2.1/7dd77388cce3f359ce455eec9aaa3ec9/jetified-play-services-base-17.1.0.
         > AAPT2 aapt2-4.1.0-6503028-linux Daemon #0: Unexpected error during compile '/home/hgc/.gradle/caches/transforms-2/files-2.1/7dd77388cce3f359ce455eec9aaa3ec9/jetified-play-services-base-17.1.0/res/drawable-xxhdpi-v4/common_google_signin_btn_icon_dark_normal_background.9.png', attempting to stop daemon.
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform play-services-base-17.1.0.aar (com.google.android.gms:play-services-base:17.1.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /home/hgc/.gradle/caches/transforms-2/files-2.1/7dd77388cce3f359ce455eec9aaa3ec9/jetified-play-services-base-17.1.0.
         > AAPT2 aapt2-4.1.0-6503028-linux Daemon #0: Unexpected error during compile '/home/hgc/.gradle/caches/transforms-2/files-2.1/7dd77388cce3f359ce455eec9aaa3ec9/jetified-play-services-base-17.1.0/res/drawable-xxhdpi-v4/common_google_signin_btn_icon_dark_normal_background.9.png', attempting to stop daemon.
`

**Comment by maheshmnj** [comment]
@carepollo Please file that as a separate issue with all the details requested in the issue template.

**Comment by dtodt** [comment]
Hello, I've made a quick fix, that seems to solved the problem.
Mine was with Firebase Analytics, that required minSdkVersion @ 19.

Here's my [commit diff](https://github.com/dtodt/todo_1st/commit/4fa447b33389cccb9b432480fbdd63a66bb9f983).
Now my `build.gradle` aknowledge the `local.properties` overrides.

I hope it helps someone.

Cheers.
