### ISSUE TITLE
Flutter tool crashes with `app.dill.incremental.dill' (OS Error: No such file or directory, errno = 2)` on macOS 12.1 

### ISSUE THREAD

**Issue by glebosotov** [flutter/flutter#95561]
# Description
After upgrading to the latest stable macOS, I notice that flutter tool crashes after some time of using it normally. Nothing in particular like restarting the app or doing any particular actions seems to trigger it. Looks like cache/file access issue to me. Happens usually after a couple of minutes since latest start of the app. Works on both real device and the emulator. Does not seem to be Flutter 2.8 issue since I had some time working on 2.8 before the macOS update.

# Logs

```
Unhandled exception:
FileSystemException: Cannot open file, path = '/var/folders/z8/_krfbvmd7jv5m8gjbpqrfc900000gn/T/flutter_tools.wHlmh9/flutter_tool.ltavvE/app.dill.incremental.dill' (OS Error: No such file or directory, errno = 2)
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356:9)
<asynchronous suspension>

2
the Dart compiler exited unexpectedly.
Exited (1)

```

# Doctor
```

❯ flutter doctor -v
[✓] Flutter (Channel stable, 2.8.0, on macOS 12.1 21C52 darwin-x64, locale en-US)
    • Flutter version 2.8.0 at /usr/local/Caskroom/flutter/2.5.3/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (12 days ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed
      instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed
      instructions).

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • Gleb’s  iPhone 11 (mobile) • 00008030-000D4994020B802E • ios            • iOS 15.3 19D5026g
    • Chrome (web)                • chrome                    • web-javascript • Google Chrome
      96.0.4664.110
    ! Error: Gleb’s  iPhone 11 is busy: Fetching debug symbols for Gleb’s  iPhone 11. Xcode will
      continue when Gleb’s  iPhone 11 is finished. (code -10)

! Doctor found issues in 2 categories.
```

**Comment by darshankawar** [comment]
@glebosotov 
Can you provide us the entire error log ?

**Comment by glebosotov** [comment]
```
Launching lib/main.dart on iPhone 11 in debug mode...
lib/main.dart:1
Xcode build done.                                           31.5s
Unhandled exception:
FileSystemException: Cannot open file, path = '/var/folders/z8/_krfbvmd7jv5m8gjbpqrfc900000gn/T/flutter_tools.UMTv4L/flutter_tool.Icwl41/app.dill' (OS Error: No such file or directory, errno = 2)
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356:9)
<asynchronous suspension>

the Dart compiler exited unexpectedly.
Exited (sigterm)
the Dart compiler exited unexpectedly.

```

**Comment by darshankawar** [comment]
@glebosotov 
Can you confirm if `/var/folders/z8/_krfbvmd7jv5m8gjbpqrfc900000gn/T/flutter_tools.UMTv4L/flutter_tool.Icwl41/app.dill` file exists or not ?
Also can you switch to latest master and try ?

```
flutter channel master
flutter upgrade
```

**Comment by glebosotov** [comment]
The file does not exist after the crash, folder is also restricted on macOS, even with `sudo`
I will try **master** version and report back as soon as I get results.

**Comment by glebosotov** [comment]
Can confirm crashes on the master channel
<img width="1211" alt="Screen Shot 2022-01-04 at 17 55 32" src="https://user-images.githubusercontent.com/34625367/148062244-3671832c-4758-482d-b021-446a63b3c7a9.png">

**Comment by darshankawar** [comment]
@glebosotov 
Can you provide us the pattern or steps to replicate when this exception occurs, that'll be helpful to verify further.
Thanks.

**Comment by glebosotov** [comment]
Basically on my macOS version which is stated above in the doctor command output start debugging any app and wait a couple of minutes. It probably has to do with wrong file permissions.

**Comment by darshankawar** [comment]
Thanks. I tried the same, but didn't get the said exception:

```
Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Running pod install...
Running Xcode build...
Xcode build done.                                           34.3s
Debug service listening on ws://127.0.0.1:50558/HDN66IQEGuQ=/ws
Syncing files to device iPhone 12 Pro Max...
```

Maybe it has to do something with the file it is pointing to:  `/var/folders/z8/_krfbvmd7jv5m8gjbpqrfc900000gn/T/flutter_tools.UMTv4L/flutter_tool.Icwl41/app.dill`

Labeling it for further input from the team.

/cc @christopherfujino

**Comment by glebosotov** [comment]
Since the issue persisted, I have reinstalled macOS fresh. Seems to solve the issue, will report if it returns
