### ISSUE TITLE
Tests containing group() cause "flutter test" to hang

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#956]
Attempting to use `group()` in a Flutter test causes `flutter test` to hang. For example, the test below works when run using `flutter test`, but it hangs if you uncomment the two lines that are commented out.

````
void main() {
  //group("Example Group", () {
  test('equality', () {
    var seamOne = buildSeam(1);
    var seamTwo = buildSeam(1);
    expect(seamOne, equals(seamTwo));
    expect(seamOne.hashCode, equals(seamTwo.hashCode));
  });

  test('inequality', () {
    var seamOne = buildSeam(1);
    var seamTwo = buildSeam(314);
    expect(seamOne, isNot(equals(seamTwo)));
  });
 //});
}
```

**Comment by Hixie** [comment]
(See also #248.)

**Comment by jimbeveridge** [comment]
Following the procedure described in Hixie's comment, the Sky VM is crashing with the following error:

```
$ ~/flutter/bin/cache/artifacts/sky_engine/487d3565f67f258b1d3c9ebd0c9bddb884cbd3fa/Release/linux-x64/sky_shell --enable-checked-mode --non-interactive --package-root=/media/jimbe/mojossd/sysui/src/widgets/packages /tmp/dart_test_listeneraREmZl/listener.dart
[1216/113112:ERROR:dart_error.cc(16)] Unhandled exception:
type 'Group' is not a subtype of type 'Test' of 'test'.
#0      RemoteListener._listen (/media/jimbe/mojossd/sysui/src/widgets/packages/flutter_tools/src/test/remote_listener.dart:107:39)
#1      RemoteListener.start.<start_async_body> (/media/jimbe/mojossd/sysui/src/widgets/packages/flutter_tools/src/test/remote_listener.dart:91:41)
#2      _RootZone.runUnary (dart:async/zone.dart:1149)
#3      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:502)
#4      _Future._propagateToListeners (dart:async/future_impl.dart:585)
#5      _Future._completeWithValue (dart:async/future_impl.dart:376)
#6      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:430)
#7      _rootRun (dart:async/zone.dart:907)
#8      _CustomZone.run (dart:async/zone.dart:802)
#9      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:735)
#10     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#11     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
```

**Comment by jimbeveridge** [comment]
Tracked to comment in remote_listener.dart that says:
```
  // TODO(ianh): entries[] might return a Group instead of a Test. We don't
  // currently support nested groups.
```

**Comment by abarth** [comment]
This works now.
