### ISSUE TITLE
Error in service hardware_keyboard.dart throws Null check operator used on a null value. 

### ISSUE THREAD

**Issue by ne3Vubeki** [flutter/flutter#95630]
In our application, for production, we caught an error in the service
hardware_keyboard.dart:

flutter 2.8

Null check operator used on a null value

#0      KeyEventManager._convertRawEventAndStore (package:flutter/src/services/hardware_keyboard.dart:902)\n#1      RawKeyboard.handleRawKeyEvent (package:flutter/src/services/raw_keyboard.dart:678)\n#2      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:818)\n#3      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:77)\n#4      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:76)\n#5      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:389)\n#6      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:386)\n#7      _invoke2.<anonymous closure> (dart:ui/hooks.dart:189)\n#8      _rootRun (dart:async/zone.dart:1428)\n#9      _CustomZone.run (dart:async/zone.dart:1328)\n#10     _CustomZone.runGuarded (dart:async/zone.dart:1236)\n#11     _invoke2 (dart:ui/hooks.dart:188)\n#12     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42)\n#13     _Channel.push (dart:ui/channel_buffers.dart:132)\n#14     ChannelBuffers.push (dart:ui/channel_buffers.dart:329)\n#15     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:544)\n#16     _dispatchPlatformMessage (dart:ui/hooks.dart:83)

**Comment by etienn01** [comment]
Same issue appeared for me after upgrading from Flutter 2.5.2 to 2.8.1.

**Comment by maheshmnj** [comment]
HI @ne3Vubeki, Thanks for filing the issue. Please share the output of `flutter doctor -v` and what platform were you targeting? Are there any known steps to reproduce the issue?

Thank you

**Comment by ne3Vubeki** [comment]
We have no replay capability. The error occurs in production and is handled by the firebase crashlytics logging.

> flutter doctor -v

[✓] Flutter (Channel stable, 2.8.0, on macOS 12.0.1 21A559 darwin-x64, locale ru-RU)
    • Flutter version 2.8.0 at 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (13 дней назад), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at 
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

**Comment by maheshmnj** [comment]
Thanks for the info. Can you share what target platform was this issue reproduced on Android or IOS or both?

**Comment by ne3Vubeki** [comment]
> Спасибо за информацию. Не могли бы вы рассказать, на какой целевой платформе эта проблема была воспроизведена на Android, IOS или на обоих устройствах?



> Thanks for the info. Can you share what target platform was this issue reproduced on Android or IOS or both?

"model": "SCG02 SCG02", "platform": "Android 7.1.2(25)"
"model": "octopus_cheets octopus", "platform": "Android 9(28)"
"model": "dream2lteks SM-G955N", "platform": "Android 7.1.2(25)"
