### ISSUE TITLE
Crash when deploying app with same name

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#9566]
On machine 1 I ran the following commands to deploy an app to my Android phone:
```
flutter create foo_test
flutter run
```
I then unplugged the phone and plugged it into a different machine. On this machine I ran the exact same sequence of commands. This results in the following crash on machine 2:

```
C:\src\crashTest> flutter run
Updating flutter tool...
Running 'flutter packages get' in crashTest...        0.7s
Launching lib/main.dart on Nexus 6P in debug mode...
Running 'gradle assembleDebug'...                    13.0s
Built build\app/outputs/apk/app-debug.apk (21.9MB).
Installing build\app/outputs/apk/app.apk...              |
Oops; flutter has exited unexpectedly: "Exit code 1 from: C:\Users\goderbauer\AppData\Local\Android\sdk\platform-tools\adb -s 84B5T15A10012703 install -r build\app/outputs/apk/app.apk".
Sending crash report to Google.
Crash report sent (report ID: 6c4b43f930000000)
Crash report written to C:\src\crashTest\flutter_04.log;
please let us know at https://github.com/flutter/flutter/issues.
```

The crash report is reproduced  at the bottom of this report. I believe the problem here is that an app with the same name is already installed on my phone (from machine 1) and flutter is unable to deploy a different app (with the same name) to the phone (from machine 2). Instead of crashing, it should give a more helpful error message explaining this.

Uninstalling the app and trying again fixes the problem.

------------

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run

## exception

String: Exit code 1 from: C:\Users\goderbauer\AppData\Local\Android\sdk\platform-tools\adb -s 84B5T15A10012703 install -r build\app/outputs/apk/app.apk

```
#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:211)
<asynchronous suspension>
#1      AndroidDevice.installApp (package:flutter_tools/src/android/android_device.dart:236)
<asynchronous suspension>
#2      AndroidDevice._installLatestApp (package:flutter_tools/src/android/android_device.dart:276)
<asynchronous suspension>
#3      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:330)
<asynchronous suspension>
#4      HotRunner.run (package:flutter_tools/src/run_hot.dart:202)
<asynchronous suspension>
#5      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:291)
<asynchronous suspension>
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:151)
<asynchronous suspension>
#7      RunCommand.verifyThenRunCommand (package:flutter_tools/src/commands/run.dart:205)
<asynchronous suspension>
#8      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:121)
#9      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:262)
<asynchronous suspension>
#11     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#12     Future.Future.sync (dart:async/future.dart:208)
#13     CommandRunner.run (package:args/command_runner.dart:109)
#14     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:157)
#15     run.<anonymous closure> (package:flutter_tools/executable.dart:140)
<asynchronous suspension>
#16     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#17     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#18     _rootRun (dart:async/zone.dart:1120)
#19     _CustomZone.run (dart:async/zone.dart:1001)
#20     runZoned (dart:async/zone.dart:1465)
#21     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#22     run (package:flutter_tools/executable.dart:113)
<asynchronous suspension>
#23     main (package:flutter_tools/executable.dart:66)
<asynchronous suspension>
#24     main (file:///C:/src/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#25     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

## flutter doctor

```
[âœ“] Flutter (on Microsoft Windows [Version 10.0.14393], channel master)
    â€¢ Flutter at C:\src\flutter
    â€¢ Framework revision 55f334681b (5 hours ago), 2017-04-24 09:46:49 -0700
    â€¢ Engine revision a5b64899c9
    â€¢ Tools Dart version 1.23.0-dev.11.11

[âœ“] Host Executable Compatibility
    â€¢ Downloaded executables execute on host

[âœ“] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    â€¢ Android SDK at C:\Users\goderbauer\AppData\Local\Android\sdk
    â€¢ Platform android-25, build-tools 25.0.2
    â€¢ Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    â€¢ Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[âœ“] Android Studio (version 2.3)
    â€¢ Android Studio at C:\Program Files\Android\Android Studio
    â€¢ Gradle version 3.2
    â€¢ Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[âœ“] IntelliJ IDEA Community Edition (version 2017.1)
    â€¢ Dart plugin version 171.4249.16
    â€¢ Flutter plugin version 13.0

[âœ“] Connected devices
    â€¢ Nexus 6P â€¢ 84B5T15A10012703 â€¢ android-arm â€¢ Android 7.1.1 (API 25)

```

**Comment by jonahwilliams** [comment]
I tried to do this by giving a flutter test app the same applicationId as an already installed application (in this case, com.discord).  The result was the Discord app was uninstalled and replaced with the flutter app. Cue arrested developement i_dont_know_what_i_expected.gif

```
jonahwilliams-macbookpro:discord jonahwilliams$ flutter run
Launching lib/main.dart on Pixel 2 in debug mode...
Initializing gradle...                                       0.9s
Resolving dependencies...                                    2.1s
Gradle task 'assembleDebug'...                                   
Gradle task 'assembleDebug'... Done                         14.8s
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...                  2.7s
Error: ADB exited with exit code 1
adb: failed to install /Users/jonahwilliams/Documents/discord/build/app/outputs/apk/app.apk: Failure [INSTALL_FAILED_VERSION_DOWNGRADE]
Uninstalling old version...
Installing build/app/outputs/apk/app.apk...                  3.7s
Syncing files to device Pixel 2...                           1.5s

🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on Pixel 2 is available at: http://127.0.0.1:63124/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
```

I think its safe to say that this has been fixed
