### ISSUE TITLE
help me ？ idea error

### ISSUE THREAD

**Issue by dd9913762113** [flutter/flutter#95664]
<details>
<summary> error log </summary>

```


[  +15 ms] executing: which pod
[   +6 ms] executing: pod --version
[ +788 ms] 1.11.2

           /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin20/rbconfig.rb:229: warning: Insecure world writable dir /Users/dd in PATH, mode 040777
               WARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
               Consider adding the following to ~/.profile:

               export LANG=en_US.UTF-8
   
Running pod install...
[{"event":"app.progress","params":{"appId":"0e2222ff-5597-4952-ae39-dcd7b3adaa96","id":"0","progressId":null,"message":"Running pod install...","finished":false}}]
[{"event":"app.progress","params":{"appId":"0e2222ff-5597-4952-ae39-dcd7b3adaa96","id":"0","progressId":null,"finished":true}}]
[+1268 ms] CocoaPods' output:
           ↳
[        ]       CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only performed in repo update

[        ] Error output from CocoaPods:
           ↳
[        ]     /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin20/rbconfig.rb:229: warning: Insecure world writable dir /Users/dd in PATH, mode 040777
                   WARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
                   Consider adding the following to ~/.profile:

                   export LANG=en_US.UTF-8
                   
               /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/unicode_normalize/normalize.rb:141:in `normalize': Unicode Normalization not appropriate for ASCII-8BIT (Encoding::CompatibilityError)
               	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/config.rb:166:in `unicode_normalize'
               	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/config.rb:166:in `installation_root'
               	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/config.rb:226:in `podfile_path'
               	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface/error_report.rb:105:in `markdown_podfile'
               	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface/error_report.rb:30:in `report'
               	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:66:in `report_error'
               	from /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:396:in `handle_exception'
               	from /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:337:in `rescue in run'
               	from /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:324:in `run'
               	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run'
               	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
               	from /usr/local/bin/pod:23:in `load'
               	from /usr/local/bin/pod:23:in `<main>'
               /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/unicode_normalize/normalize.rb:141:in `normalize': Unicode Normalization not appropriate for ASCII-8BIT (Encoding::CompatibilityError)
               	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/config.rb:166:in `unicode_normalize'
               	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/config.rb:166:in `installation_root'
               	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/config.rb:226:in `podfile_path'
               	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/config.rb:205:in `podfile'
               	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:160:in `verify_podfile_exists!'
               	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command/install.rb:46:in `run'
               	from /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
               	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run'
               	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
               	from /usr/local/bin/pod:23:in `load'
               	from /usr/local/bin/pod:23:in `<main>'

[   +5 ms] Exception: Error running pod install
[   +5 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:576:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>


[{"event":"app.stop","params":{"appId":"0e2222ff-5597-4952-ae39-dcd7b3adaa96"}}]
[  +21 ms] "flutter run" took 15,226ms.
[{"id":0,"error":"app '0e2222ff-5597-4952-ae39-dcd7b3adaa96' not found","trace":"#0      AppDomain.stop (package:flutter_tools/src/commands/daemon.dart:721:7)\n#1      Domain.handleCommand.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:224:34)\n#2      new Future.sync (dart:async/future.dart:296:31)\n#3      Domain.handleCommand (package:flutter_tools/src/commands/daemon.dart:222:5)\n#4      Daemon._handleRequest (package:flutter_tools/src/commands/daemon.dart:148:28)\n#5      _rootRunUnary (dart:async/zone.dart:1436:47)\n#6      _CustomZone.runUnary (dart:async/zone.dart:1335:19)\n#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)\n#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)\n#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)\n#10     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)\n#11     _MapStream._handleData (dart:async/stream_pipe.dart:218:10)\n#12     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)\n#13     _rootRunUnary (dart:async/zone.dart:1436:47)\n#14     _CustomZone.runUnary (dart:async/zone.dart:1335:19)\n#15     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)\n#16     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)\n#17     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)\n#18     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)\n#19     _WhereStream._handleData (dart:async/stream_pipe.dart:195:12)\n#20     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)\n#21     _rootRunUnary (dart:async/zone.dart:1436:47)\n#22     _CustomZone.runUnary (dart:async/zone.dart:1335:19)\n#23     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)\n#24     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)\n#25     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)\n#26     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)\n#27     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)\n#28     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)\n#29     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:151:13)\n#30     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:126:5)\n#31     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)\n#32     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)\n#33     _rootRunUnary (dart:async/zone.dart:1436:47)\n#34     _CustomZone.runUnary (dart:async/zone.dart:1335:19)\n#35     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)\n#36     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)\n#37     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)\n#38     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)\n#39     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)\n#40     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)\n#41     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)\n#42     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:317:20)\n#43     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)\n#44     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)\n#45     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)\n#46     _rootRunUnary (dart:async/zone.dart:1436:47)\n#47     _CustomZone.runUnary (dart:async/zone.dart:1335:19)\n#48     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)\n#49     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)\n#50     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)\n#51     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)\n#52     _StreamController._add (dart:async/stream_controller.dart:607:7)\n#53     _StreamController.add (dart:async/stream_controller.dart:554:5)\n#54     _Socket._onData (dart:io-patch/socket_patch.dart:2302:41)\n#55     _rootRunUnary (dart:async/zone.dart:1444:13)\n#56     _CustomZone.runUnary (dart:async/zone.dart:1335:19)\n#57     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)\n#58     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)\n#59     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)\n#60     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)\n#61     _StreamController._add (dart:async/stream_controller.dart:607:7)\n#62     _StreamController.add (dart:async/stream_controller.dart:554:5)\n#63     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1830:33)\n#64     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1314:14)\n#65     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)\n#66     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)\n#67     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:122:13)\n#68     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:193:5)\n"}]
[  +87 ms] ensureAnalyticsSent: 86ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

```
</details>

**Comment by darshankawar** [comment]
@dd9913762113 
The failure is coming from cocoapods as below:

`WARNING: CocoaPods requires your terminal to be using UTF-8 encoding.`

```
`Error output from CocoaPods:
           ↳
[        ]     /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin20/rbconfig.rb:229: warning: Insecure world writable dir /Users/dd in PATH, mode 040777
                   WARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
                   Consider adding the following to ~/.profile:

                   export LANG=en_US.UTF-8
                   
               /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/unicode_normalize/normalize.rb:141:in `normalize': Unicode Normalization not appropriate for ASCII-8BIT (Encoding::CompatibilityError)`
```

Check [this](https://stackoverflow.com/questions/69070537/getting-error-while-run-flutter-app-in-ios) similar SO link and see if it helps to resolve. If not, you can ask the same there or look for similar solutions.
Closing from here as this isn't a Flutter issue.
