### ISSUE TITLE
Using values from `MediaQuery` for `viewPortFraction` in `PageController` constructor may result widgets not rendering in release mode. 

### ISSUE THREAD

**Issue by ecin-tpk** [flutter/flutter#95710]
Hello!
I want to set the viewPortFraction to something like this
`PageController(
                viewportFraction: (MediaQuery.of(context).size.width - 16) /
                    MediaQuery.of(context).size.width)`
but when I build the release version, the app shows only a white screen even though it works fine in debug mode

**Comment by danagbemava-nc** [comment]
Hi @ecin-tpk, thanks for filing the issue. 

Please provide a complete minimal reproducible code sample as well as the output of `flutter doctor -v`. 

Also, please show what it looks like in `debug` mode vs `release` as well as any relevant logs. 

Thank you

**Comment by ecin-tpk** [comment]
This is my code

```
class OldCarousel extends StatefulWidget {
  const OldCarousel({Key? key}) : super(key: key);

  @override
  State<OldCarousel> createState() => _OldCarouselState();
}

class _OldCarouselState extends State<OldCarousel> {
  late final _pageController = PageController(
      viewportFraction: ((MediaQuery.of(context).size.width - 16) /
          MediaQuery.of(context).size.width));

  @override
  void dispose() {
    _pageController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      height: 135,
      child: Stack(
        alignment: Alignment.bottomCenter,
        children: [
          PageView.builder(
            physics: const BouncingScrollPhysics(),
            padEnds: false,
            controller: _pageController,
            itemBuilder: (_, index) => Container(
              width: MediaQuery.of(context).size.width - 32,
              margin: const EdgeInsets.only(left: 16),
              height: 135,
              decoration: BoxDecoration(
                color: Colors.red,
                borderRadius: BorderRadius.circular(12),
              ),
            ),
          ),
        ],
      ),
    );
  }
}
```

Debug log
`Launching lib/main.dart on SM A037F in debug mode...
lib/main.dart:1
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:52975/Tedr7rPJsw0=/ws
D/PhoneWindow(13947): forceLight changed to false [com.example.skybeat/com.example.skybeat.MainActivity] from com.android.internal.policy.PhoneWindow.updateForceLightNavigationBar:4229 com.android.internal.policy.PhoneWindow.setNavigationBarColor:4029 io.flutter.plugin.platform.PlatformPlugin.setSystemChromeSystemUIOverlayStyle:429 io.flutter.plugin.platform.PlatformPlugin.access$700:30 io.flutter.plugin.platform.PlatformPlugin$1.setSystemUiOverlayStyle:108
I/SurfaceControl(13947): nativeRelease nativeObject s[-5476376657535439424]
I/SurfaceControl(13947): nativeRelease nativeObject e[-5476376657535439424]
I/SurfaceControl(13947): assignNativeObject: nativeObject = 0 Surface(name=null)/@0xd698a85 / android.view.SurfaceControl.readFromParcel:1117 android.view.IWindowSession$Stub$Proxy.relayout:1820 android.view.ViewRootImpl.relayoutWindow:9005 android.view.ViewRootImpl.performTraversals:3360 android.view.ViewRootImpl.doTraversal:2618 android.view.ViewRootImpl$TraversalRunnable.run:9971 android.view.Choreographer$CallbackRecord.run:1010 android.view.Choreographer.doCallbacks:809 android.view.Choreographer.doFrame:744 android.view.Choreographer$FrameDisplayEventReceiver.run:995
I/SurfaceControl(13947): nativeRelease nativeObject s[-5476376654884488256]
I/SurfaceControl(13947): nativeRelease nativeObject e[-5476376654884488256]
I/SurfaceControl(13947): nativeRelease nativeObject s[-5476376654884487200]
I/SurfaceControl(13947): nativeRelease nativeObject e[-5476376654884487200]
I/ViewRootImpl@76805ce[MainActivity](13947): Relayout returned: old=(0,0,720,1600) new=(0,0,720,1600) req=(720,1600)0 dur=15 res=0x3 s={true -5476376658957238272} ch=false fn=1
I/ViewRootImpl@76805ce[MainActivity](13947): updateBoundsLayer: shouldReparent = false t = android.view.SurfaceControl$Transaction@602b0da sc = Surface(name=Bounds for - com.example.skybeat/com.example.skybeat.MainActivity@0)/@0x3a3e90b frame = 1
I/SurfaceView(13947): applySurfaceTransforms: t = android.view.SurfaceControl$Transaction@74dc3e8 surfaceControl = Surface(name=SurfaceView - com.example.skybeat/com.example.skybeat.MainActivity@96063fc@0)/@0xb3d4a01 frame = 1
I/ViewRootImpl@76805ce[MainActivity](13947): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager(13947): prepareNavigationBarInfo() DecorView@c063382[MainActivity]
D/InputMethodManager(13947): getNavigationBarColor() -16777216
D/InputMethodManager(13947): prepareNavigationBarInfo() DecorView@c063382[MainActivity]
D/InputMethodManager(13947): getNavigationBarColor() -16777216
V/InputMethodManager(13947): Starting input: tba=com.example.skybeat ic=null mNaviBarColor -16777216 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager(13947): startInputInner - Id : 0
I/InputMethodManager(13947): startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport(13947): Input channel constructed: 'ClientS', fd=126
D/InputMethodManager(13947): prepareNavigationBarInfo() DecorView@c063382[MainActivity]
D/InputMethodManager(13947): getNavigationBarColor() -16777216
V/InputMethodManager(13947): Starting input: tba=com.example.skybeat ic=null mNaviBarColor -16777216 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager(13947): startInputInner - Id : 0
I/SurfaceControl(13947): nativeRelease nativeObject s[-5476376657535449024]
I/SurfaceControl(13947): nativeRelease nativeObject e[-5476376657535449024]
I/SurfaceControl(13947): nativeRelease nativeObject s[-5476376657535439424]
I/SurfaceControl(13947): nativeRelease nativeObject e[-5476376657535439424]`

In release I also get those warnings about mapping new ns to old ns but I think it's not the problem

The flutter doctor -v show no issues

The app works fine in debug, this is a screenshot
![debug](https://imgur.com/YQc6Eys)
in release it just shows a white screen

**Comment by danagbemava-nc** [comment]
Hi @ecin-tpk, is this issue only on `android` or it affects other platforms as well?

**Comment by ecin-tpk** [comment]
Unfortunately I don't have a real iOS device to test right now. By the way here is the ```flutter doctor -v``` output
```
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6.1 20G224 darwin-x64, locale
    en-VN)
    • Flutter version 2.8.1 at /Users/khuong/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (7 days ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/khuong/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/khuong/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • SM A037F (mobile)     • R9HRA0EJW0M  • android-arm64  • Android 11 (API
      30)
    • Redmi Note 4 (mobile) • b328e7a69904 • android-arm64  • Android 7.0 (API
      24)
    • Chrome (web)          • chrome       • web-javascript • Google Chrome
      96.0.4664.110

• No issues found!
```

**Comment by danagbemava-nc** [comment]
Hi @ecin-tpk, can you try with the sample below and let me know if you still experience this issue? 

<details>
<summary>updated sample</summary>

```dart
class OldCarousel extends StatefulWidget {
  const OldCarousel({Key? key}) : super(key: key);

  @override
  State<OldCarousel> createState() => _OldCarouselState();
}

class _OldCarouselState extends State<OldCarousel> {
  late final PageController _pageController;

  @override
  void dispose() {
    _pageController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    _pageController = PageController(
        viewportFraction: ((MediaQuery.of(context).size.width - 16) /
            MediaQuery.of(context).size.width));
    return SizedBox(
      height: 135,
      child: Stack(
        alignment: Alignment.bottomCenter,
        children: [
          PageView.builder(
            physics: const BouncingScrollPhysics(),
            padEnds: false,
            controller: _pageController,
            itemBuilder: (_, index) => Container(
              width: MediaQuery.of(context).size.width - 32,
              margin: const EdgeInsets.only(left: 16),
              height: 135,
              decoration: BoxDecoration(
                color: Colors.red,
                borderRadius: BorderRadius.circular(12),
              ),
            ),
          ),
        ],
      ),
    );
  }
}
```
</details>

**Comment by ecin-tpk** [comment]
Hi @danagbemava-nc,
Thanks for your help but it seems the issue is still there. It works in the first run (in release mode) but when I close and open  again, the app shows only a white screen.

**Comment by danagbemava-nc** [comment]
Hi @ecin-tpk, can you provide a sample that shows how the `OldCarousel` widget is being used in your application?

**Comment by ecin-tpk** [comment]
Hi @danagbemava-nc, here is the sample app which is very simple. As I said it works in the first run but not in the subsequent
<details>
  <summary>Sample</summary>

```
void main() {
  SystemChrome.setSystemUIOverlayStyle(
    SystemUiOverlayStyle.dark.copyWith(
      statusBarColor: Colors.transparent,
    ),
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: OldCarousel(),
      ),
    );
  }
}
```
</details>

**Comment by danagbemava-nc** [comment]
Hi @ecin-tpk, it looks like the reason you're running into this error is that there's a chance that the value from 

```dart
((MediaQuery.of(context).size.width - 16) /
            MediaQuery.of(context).size.width)
```

can be `-Infinity`. It seems like it is always `-Infinity` before the widget has completely loaded. 

You should be able to work around it by checking if it is less than zero then changing it to 1. Once the widget is completely built, it should update the value with the correct one. Kindly try the sample below and let me know if it works for you. 

<details>
<summary>updated sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  SystemChrome.setSystemUIOverlayStyle(
    SystemUiOverlayStyle.dark.copyWith(
      statusBarColor: Colors.transparent,
    ),
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: OldCarousel(),
      ),
    );
  }
}

class OldCarousel extends StatefulWidget {
  const OldCarousel({Key? key}) : super(key: key);

  @override
  State<OldCarousel> createState() => _OldCarouselState();
}

class _OldCarouselState extends State<OldCarousel> {
  PageController? _pageController;

  @override
  void dispose() {
    super.dispose();
  }

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    double vpf = ((MediaQuery.of(context).size.width - 16) /
        MediaQuery.of(context).size.width);

    print(
        "+=============================+\nviewportFraction: $vpf\n+=============================+");

    if (vpf < 0) {
      vpf = 1;
    }

    _pageController = PageController(viewportFraction: vpf);
    return SizedBox(
      height: 135,
      child: PageView.builder(
        physics: const BouncingScrollPhysics(),
        padEnds: false,
        controller: _pageController,
        itemBuilder: (_, index) => Container(
          // width: MediaQuery.of(context).size.width - 32,
          margin: const EdgeInsets.only(left: 16),
          height: 135,
          decoration: BoxDecoration(
            color: Colors.red,
            borderRadius: BorderRadius.circular(12),
          ),
        ),
      ),
    );
  }
}
```

</details>

**Comment by ecin-tpk** [comment]
Hi @danagbemava-nc, It works! Thank you so much for your help. May I close this issue?

**Comment by danagbemava-nc** [comment]
> May I close this issue?

No please. This seems like something that should be handled by the framework and this solution is an inelegant hack at best. The initialization of the controller in the `build` method especially is not a good thing. If I'm able to come up with a better fix, I'll update here.

Labeling for further investigation. 

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  SystemChrome.setSystemUIOverlayStyle(
    SystemUiOverlayStyle.dark.copyWith(
      statusBarColor: Colors.transparent,
    ),
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: OldCarousel(),
      ),
    );
  }
}

class OldCarousel extends StatefulWidget {
  const OldCarousel({Key? key}) : super(key: key);

  @override
  State<OldCarousel> createState() => _OldCarouselState();
}

class _OldCarouselState extends State<OldCarousel> {
  late final _pageController = PageController(
      viewportFraction: ((MediaQuery.of(context).size.width - 16) /
          MediaQuery.of(context).size.width));

  @override
  void dispose() {
    _pageController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      height: 135,
      child: Stack(
        alignment: Alignment.bottomCenter,
        children: [
          PageView.builder(
            physics: const BouncingScrollPhysics(),
            padEnds: false,
            controller: _pageController,
            itemBuilder: (_, index) => Container(
              width: MediaQuery.of(context).size.width - 32,
              margin: const EdgeInsets.only(left: 16),
              height: 135,
              decoration: BoxDecoration(
                color: Colors.red,
                borderRadius: BorderRadius.circular(12),
              ),
            ),
          ),
        ],
      ),
    );
  }
}

```

</details>

<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.8.1 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (12 days ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:318:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1428:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1863:10)
      #15     runZonedGuarded (dart:async/zone.dart:1851:12)
      #16     runZoned (dart:async/zone.dart:1782:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:197:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:301:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:53:47)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1290:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12 (API 31) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 96.0.4664.110

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel master, 2.9.0-1.0.pre.205, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.9.0-1.0.pre.205 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6ec059c994 (5 hours ago), 2021-12-28 00:29:08 -0500
    • Engine revision 31fcaf3ce4
    • Dart version 2.16.0 (build 2.16.0-134.0.dev)
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1426:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1861:10)
      #15     runZonedGuarded (dart:async/zone.dart:1849:12)
      #16     runZoned (dart:async/zone.dart:1780:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:205:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:309:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12 (API 31) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 96.0.4664.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>

**Comment by goderbauer** [comment]
The problem with the code is that it is not responding to MediaQuery changes. You need to implement a `didUpdateDependencies` method (which is called whenever MediaQuery changes) and re-read the values you're interested in from MediaQuery.
