### ISSUE TITLE
Google Maps is showing blank background and google logo with zoom control

### ISSUE THREAD

**Issue by sitatec** [flutter/flutter#95749]
## Steps to Reproduce

 1. Create a new flutter application and add `google_maps_flutter: ^2.1.1` in pubspec.yaml
 2. Replace the content of the `lib/main.dart` file by the `google_maps_flutter` [code sample](https://stackoverflow.com/questions/70418198/google-map-not-loading-java-util-concurrent-java-lang-securityexception-googlec)
 3. Add this tag `<meta-data android:name="com.google.android.geo.API_KEY"
               android:value="VALIDE_API_KEY_HERE"/>`  in  `android\app\src\main\AndroidManifest.xml` under `<application>`
 4. Set minSdkVersion to 20
 5. Run the app

## Result 
<img src="https://user-images.githubusercontent.com/62622509/147294897-3a76a8d5-6b8c-4d77-9960-367bc60d4f59.jpg" width="400"/>

### Logs
```
W/DynamiteModule(23554): Local module descriptor class for com.google.android.gms.googlecertificates not found.
I/DynamiteModule(23554): Considering local module com.google.android.gms.googlecertificates:0 and remote module com.google.android.gms.googlecertificates:6
I/DynamiteModule(23554): Selected remote version of com.google.android.gms.googlecertificates, version >= 6
W/ProtoDataStoreFlagStore(23554): Unable to retrieve flag snapshot for com.google.android.libraries.consentverifier#com.example.google_map_test, using defaults.
W/ProtoDataStoreFlagStore(23554): Unable to update local snapshot for com.google.android.libraries.consentverifier#com.example.google_map_test, may result in stale flags.
W/ProtoDataStoreFlagStore(23554): java.util.concurrent.ExecutionException: java.lang.SecurityException: GoogleCertificatesRslt: Package signed with unknown certificate (go/gsrlt)
W/ProtoDataStoreFlagStore(23554): 	at age.s(:com.google.android.gms.dynamite_mapsdynamite@214815081@21.48.15 (150400-0):3)
W/ProtoDataStoreFlagStore(23554): 	at age.get(:com.google.android.gms.dynamite_mapsdynamite@214815081@21.48.15 (150400-0):2)
W/ProtoDataStoreFlagStore(23554): 	at aii.a(:com.google.android.gms.dynamite_mapsdynamite@214815081@21.48.15 (150400-0):1)
W/ProtoDataStoreFlagStore(23554): 	at aho.g(:com.google.android.gms.dynamite_mapsdynamite@214815081@21.48.15 (150400-0):1)
W/ProtoDataStoreFlagStore(23554): 	at wn.d(:com.google.android.gms.dynamite_mapsdynamite@214815081@21.48.15 (150400-0):1)
W/ProtoDataStoreFlagStore(23554): 	at xu.run(:com.google.android.gms.dynamite_mapsdynamite@214815081@21.48.15 (150400-0):0)
W/ProtoDataStoreFlagStore(23554): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
W/ProtoDataStoreFlagStore(23554): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/ProtoDataStoreFlagStore(23554): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
W/ProtoDataStoreFlagStore(23554): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/ProtoDataStoreFlagStore(23554): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/ProtoDataStoreFlagStore(23554): 	at java.lang.Thread.run(Thread.java:923)
W/ProtoDataStoreFlagStore(23554): Caused by: java.lang.SecurityException: GoogleCertificatesRslt: Package signed with unknown certificate (go/gsrlt)
W/ProtoDataStoreFlagStore(23554): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2385)
W/ProtoDataStoreFlagStore(23554): 	at android.os.Parcel.createException(Parcel.java:2369)
W/ProtoDataStoreFlagStore(23554): 	at android.os.Parcel.readException(Parcel.java:2352)
W/ProtoDataStoreFlagStore(23554): 	at android.os.Parcel.readException(Parcel.java:2294)
W/ProtoDataStoreFlagStore(23554): 	at dx.aZ(:com.google.android.gms.dynamite_mapsdynamite@214815081@21.48.15 (150400-0):2)
W/ProtoDataStoreFlagStore(23554): 	at ql.a(:com.google.android.gms.dynamite_mapsdynamite@214815081@21.48.15 (150400-0):4)
W/ProtoDataStoreFlagStore(23554): 	at id.e(:com.google.android.gms.dynamite_mapsdynamite@214815081@21.48.15 (150400-0):2)
W/ProtoDataStoreFlagStore(23554): 	at jc.t(:com.google.android.gms.dynamite_mapsdynamite@214815081@21.48.15 (150400-0):2)
W/ProtoDataStoreFlagStore(23554): 	at jc.u(:com.google.android.gms.dynamite_mapsdynamite@214815081@21.48.15 (150400-0):3)
W/ProtoDataStoreFlagStore(23554): 	at jc.e(:com.google.android.gms.dynamite_mapsdynamite@214815081@21.48.15 (150400-0):2)
W/ProtoDataStoreFlagStore(23554): 	at jg.handleMessage(:com.google.android.gms.dynamite_mapsdynamite@214815081@21.48.15 (150400-0):69)
W/ProtoDataStoreFlagStore(23554): 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/ProtoDataStoreFlagStore(23554): 	at android.os.Looper.loop(Looper.java:246)
W/ProtoDataStoreFlagStore(23554): 	at android.os.HandlerThread.run(HandlerThread.java:67)
D/InputMethodManager(23554): prepareNavigationBarInfo() DecorView@6cce408[MainActivity]
D/InputMethodManager(23554): getNavigationBarColor() -16711423
V/InputMethodManager(23554): Starting input: tba=com.example.google_map_test ic=null mNaviBarColor -16711423 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager(23554): startInputInner - Id : 0
I/InputMethodManager(23554): startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport(23554): Input channel constructed: 'ClientS', fd=154
D/InputTransport(23554): Input channel destroyed: 'ClientS', fd=99
I/ViewRootImpl@75038b4[MainActivity](23554): stopped(true) old=false
I/SurfaceView(23554): windowStopped(true) false io.flutter.embedding.android.FlutterSurfaceView{fc7a052 V.E...... ........ 0,0-1080,2214} of ViewRootImpl@75038b4[MainActivity]
I/SurfaceView(23554): surfaceDestroyed callback.size 1 #1 io.flutter.embedding.android.FlutterSurfaceView{fc7a052 V.E...... ........ 0,0-1080,2214}
W/libEGL  (23554): EGLNativeWindowType 0x78ebe32010 disconnect failed
I/SurfaceView(23554): remove() io.flutter.embedding.android.FlutterSurfaceView{fc7a052 V.E...... ........ 0,0-1080,2214} Surface(name=SurfaceView - com.example.google_map_test/com.example.google_map_test.MainActivity@fc7a052@0)/@0xeeb9d9

```

# flutter doctor -v
```
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19043.1348], locale en-US)
    • Flutter version 2.8.1 at C:\Development\Tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (7 days ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\sitab\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java      
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)    
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] IntelliJ IDEA Community Edition (version 2021.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.2.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (2 available)
    • SM A305F (mobile) • R58M353C5ZN • android-arm64  • Android 11 (API 30)
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 96.0.4664.110 

• No issues found!
```
I have tried using "Hybrid Composition":
```dart
if (defaultTargetPlatform == TargetPlatform.android) {
  AndroidGoogleMapsFlutter.useAndroidViewSurface = true;
}
```
But it doesn't work.
I have tested on both emulator and real device (only on android). And it seems that I'm not the only one who recently faced this [issue](https://stackoverflow.com/questions/70418198/google-map-not-loading-java-util-concurrent-java-lang-securityexception-googlec)

**Comment by darshankawar** [comment]
@sitatec 
I tried the plugin example and followed the steps you mentioned and ran it on Android Samsung A2Core device (OS 8) on which the map rendered and zoomed (in and out) properly without any issues.

<img width="344" alt="Screenshot 2021-12-27 at 12 43 21 PM" src="https://user-images.githubusercontent.com/67046386/147446326-5ffe78ac-bc5e-4901-a679-8b75ac7a861c.png">
<img width="362" alt="Screenshot 2021-12-27 at 12 43 29 PM" src="https://user-images.githubusercontent.com/67046386/147446338-08bd0163-1c00-4a4a-ae2b-7839b81415da.png">

Are there any specific steps from the plugin example that leads to the behavior you are seeing ?

**Comment by sitatec** [comment]
Problem fixed!

The problem was because I was using a VPN, maybe Google Play Services wasn't able to establish connection through the VPN, or was considering it unsafe. 
And it seems to happen only for the first time you are trying to load the map,  once you load it the first time without VPN,  it will then works with or without VPN. 

Thanks for your reply @darshankawar .
