### ISSUE TITLE
When a system process is killed, it cannot be started again

### ISSUE THREAD

**Issue by lovachen** [flutter/flutter#95767]
<details>
<summary> log </summary>

```
  
E/AndroidRuntime(16462): FATAL EXCEPTION: main
E/AndroidRuntime(16462): Process: com.huawei.android.launcher, PID: 16462
E/AndroidRuntime(16462): java.lang.IllegalArgumentException: unknown client android.os.BinderProxy@834a6cf
E/AndroidRuntime(16462): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2394)
E/AndroidRuntime(16462): 	at android.os.Parcel.createException(Parcel.java:2374)
E/AndroidRuntime(16462): 	at android.os.Parcel.readException(Parcel.java:2357)
E/AndroidRuntime(16462): 	at android.os.Parcel.readException(Parcel.java:2299)
E/AndroidRuntime(16462): 	at com.android.internal.view.IInputMethodManager$Stub$Proxy.removeImeSurfaceFromWindow(IInputMethodManager.java:985)
E/AndroidRuntime(16462): 	at android.view.inputmethod.InputMethodManager.removeImeSurface(InputMethodManager.java:2270)
E/AndroidRuntime(16462): 	at android.view.ImeInsetsSourceConsumer.removeSurface(ImeInsetsSourceConsumer.java:142)
E/AndroidRuntime(16462): 	at android.view.InsetsSourceConsumer.setControl(InsetsSourceConsumer.java:175)
E/AndroidRuntime(16462): 	at android.view.ImeInsetsSourceConsumer.setControl(ImeInsetsSourceConsumer.java:149)
E/AndroidRuntime(16462): 	at android.view.InsetsController.onControlsChanged(InsetsController.java:804)
E/AndroidRuntime(16462): 	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:5854)
E/AndroidRuntime(16462): 	at android.os.Handler.dispatchMessage(Handler.java:109)
E/AndroidRuntime(16462): 	at android.os.Looper.loop(Looper.java:228)
E/AndroidRuntime(16462): 	at android.app.ActivityThread.main(ActivityThread.java:9013)
E/AndroidRuntime(16462): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16462): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:614)
E/AndroidRuntime(16462): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1129)
E/AndroidRuntime(16462): Caused by: android.os.RemoteException: Remote stack trace:
E/AndroidRuntime(16462): 	at com.android.server.inputmethod.HwSecureInputMethodManagerService.hideSoftInput(HwSecureInputMethodManagerService.java:1878)
E/AndroidRuntime(16462): 	at com.android.server.inputmethod.HwInputMethodManagerService.showSoftInput(HwInputMethodManagerService.java:497)
E/AndroidRuntime(16462): 	at com.android.server.inputmethod.HwInputMethodManagerService$ShowSoftInputDelayTask.runTask(HwInputMethodManagerService.java:731)
E/AndroidRuntime(16462): 	at com.android.server.inputmethod.HwInputMethodManagerService.removeImeSurfaceFromWindow(HwInputMethodManagerService.java:546)
E/AndroidRuntime(16462): 	at com.android.internal.view.IInputMethodManager$Stub.onTransact(IInputMethodManager.java:499)
E/AndroidRuntime(16462): callee: null 1636/4878
E/AndroidRuntime(16462): 
I/flutter (26842): [INFO:ace_font_jni.cpp(263)] InitSystemFonts: langs is null
I/flutter (26842): [INFO:ace_font_jni.cpp(263)] InitSystemFonts: langs is null
I/flutter (26842): [INFO:ace_font_jni.cpp(263)] InitSystemFonts: langs is null
I/flutter (26842): [INFO:ace_font_jni.cpp(263)] InitSystemFonts: langs is null
I/flutter (26842): [INFO:ace_font_jni.cpp(526)] InitSystemFonts: no axesSize
I/flutter (26842): [INFO:ace_font_jni.cpp(526)] InitSystemFonts: no axesSize
I/flutter (26842): [INFO:ace_font_jni.cpp(526)] InitSystemFonts: no axesSize
I/flutter (26842): [INFO:ace_font_jni.cpp(526)] InitSystemFonts: no axesSize
I/flutter (26842): [INFO:ace_font_jni.cpp(526)] InitSystemFonts: no axesSize
I/flutter (26842): [INFO:ace_font_jni.cpp(526)] InitSystemFonts: no axesSize
I/flutter (26842): [INFO:ui_dart_state.cc(43)] SetCurStateItem id:1
I/flutter (26842): [INFO:ui_dart_state.cc(43)] SetCurStateItem id:2
E/AndroidRuntime(26842): FATAL EXCEPTION: UiWorker-8
E/AndroidRuntime(26842): Process: com.huawei.android.launcher, PID: 26842
E/AndroidRuntime(26842): java.lang.NullPointerException: Attempt to invoke interface method 'ohos.utils.PacMap com.huawei.ohos.suggestion.cardmanagement.cardinteraction.RecommendInterface.requestRecServices(ohos.utils.PacMap)' on a null object reference
E/AndroidRuntime(26842): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2396)
E/AndroidRuntime(26842): 	at android.os.Parcel.createException(Parcel.java:2374)
E/AndroidRuntime(26842): 	at android.os.Parcel.readException(Parcel.java:2357)
E/AndroidRuntime(26842): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
E/AndroidRuntime(26842): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
E/AndroidRuntime(26842): 	at android.content.ContentProviderProxy.call(ContentProviderNative.java:732)
E/AndroidRuntime(26842): 	at android.content.ContentResolver.call(ContentResolver.java:2465)
E/AndroidRuntime(26842): 	at android.content.ContentResolver.call(ContentResolver.java:2445)
E/AndroidRuntime(26842): 	at com.huawei.android.launcher.abilityform.external.FormUpdateNotifier.lambda$requestUpdateXiaoyiAbilityForm$2$FormUpdateNotifier(FormUpdateNotifier.java:211)
E/AndroidRuntime(26842): 	at com.huawei.android.launcher.abilityform.external.-$$Lambda$FormUpdateNotifier$zOOAbvxcn0RIu5TzkcRXCuvRX1g.run(Unknown Source:6)
 
```
</details>

**Comment by darshankawar** [comment]
@lovachen 
The error `java.lang.NullPointerException: Attempt to invoke interface method 'ohos.utils.PacMap com.huawei.ohos.suggestion.cardmanagement.cardinteraction.RecommendInterface.requestRecServices(ohos.utils.PacMap)' on a null object reference`
Seems to be pointing to a `ohos.utils.PacMap com.huawei.ohos.suggestion` method or setting from your phone.
Can you provide your `flutter doctor -v`, steps to replicate this error along with [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example
)
