### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: No such file or directory, errno = 2

### ISSUE THREAD

**Issue by rbozan** [flutter/flutter#95784]
Oops; flutter has exited unexpectedly: "FileSystemException: Cannot open file, path =
'/home/rbozan/bin/cache/artifacts/material_fonts/MaterialIcons-Regular.otf' (OS Error: No such file or directory, errno = 2)".

## Command
```
flutter --no-version-check run --verbose
```

## Steps to Reproduce
1. `flutter run` (as above)

## Logs
FileSystemException: Cannot open file, OS Error: No such file or directory, errno = 2
```
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356:9)
#1      _rootRunUnary (dart:async/zone.dart:1436:47)
#2      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
<asynchronous suspension>
#3      writeBundle.<anonymous closure> (package:flutter_tools/src/bundle_builder.dart:164:33)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#5      writeBundle (package:flutter_tools/src/bundle_builder.dart:153:3)
<asynchronous suspension>
#6      WebDevFS.update (package:flutter_tools/src/isolated/devfs_web.dart:830:9)
<asynchronous suspension>
#7      ResidentWebRunner._updateDevFS (package:flutter_tools/src/isolated/resident_web_runner.dart:514:35)
<asynchronous suspension>
#8      ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:287:41)
<asynchronous suspension>
#9      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.8.0, on NixOS 21.11 (Porcupine) 5.10.81, locale en_US.UTF-8)
    • Flutter version 2.8.0 at /nix/store/2gwwa3x10zxgvlm4i9zs2f0f64p7picf-flutter-2.8.0-unwrapped
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (2 weeks ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/rbozan/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /nix/store/cky82lx7843lcp5n8bqf6i21nspl532a-android-studio-stable-2020.3.1.25-unwrapped/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = chromium

[✓] Android Studio (version 2020.3)
    • Android Studio at /nix/store/cky82lx7843lcp5n8bqf6i21nspl532a-android-studio-stable-2020.3.1.25-unwrapped
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Android Studio (version 4.2)
    • Android Studio at /nix/store/r79czjs1m6nlbp4sqynjxxibwdxibrns-android-studio-stable-4.2.1.0-unwrapped
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Chromium 96.0.4664.93

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.2.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: bbfbf1770cca2da7c82e887e4e4af910034800b6
### Plugins
connectivity_plus-1.4.0
connectivity_plus_linux-1.1.1
connectivity_plus_macos-1.2.1
connectivity_plus_web-1.1.0+1
connectivity_plus_windows-1.2.0
firebase_auth-3.3.4
firebase_auth_web-3.3.5
firebase_core-1.10.6
firebase_core_web-1.5.3
flutter_facebook_auth-3.5.7
flutter_facebook_auth_web-2.6.0+2
google_sign_in-5.2.1
google_sign_in_web-0.10.0+3
package_info_plus-1.3.0
package_info_plus_macos-1.3.0
package_info_plus_web-1.0.4
path_provider-2.0.8
path_provider_android-2.0.11
path_provider_ios-2.0.7
path_provider_linux-2.1.4
path_provider_macos-2.0.4
path_provider_windows-2.0.4
sentry_flutter-6.2.2
sqflite-2.0.1
url_launcher-6.0.17
url_launcher_android-6.0.13
url_launcher_ios-6.0.13
url_launcher_linux-2.0.2
url_launcher_macos-2.0.2
url_launcher_web-2.0.5
url_launcher_windows-2.0.2

**Comment by danagbemava-nc** [comment]
I see a similar issue is already open in https://github.com/flutter/flutter/issues/68958. 

Kindly follow up there for more information.

Closing from here as duplicate. 

Thank you
