### ISSUE TITLE
Null check operator used on a null value; #0      TextPainter.getPositionForOffset (package:flutter/src/painting/text_painter.dart:953)#1

### ISSUE THREAD

**Issue by kirill-21** [flutter/flutter#95818]
```
Null check operator used on a null value; #0      TextPainter.getPositionForOffset (package:flutter/src/painting/text_painter.dart:953)#1      RenderParagraph.hitTestChildren (package:flutter/src/rendering/paragraph.dart:444)#2      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2411)#3      _RenderLayoutBuilder.hitTestChildren (package:flutter/src/widgets/layout_builder.dart:335)#4      RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:178)#5      _RenderLayoutBuilder.hitTestChildren (package:flutter/src/widgets/layout_builder.dart:335)#6      RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:178)#7      _RenderLayoutBuilder.hitTestChildren (package:flutter/src/widgets/layout_builder.dart:335)#8      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2411)#9      RenderMouseRegion.hitTest (package:flutter/src/rendering/proxy_box.dart:2964)#10     _RenderLayoutBuilder.hitTestChildren (package:flutter/src/widgets/layout_builder.dart:335)#11     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2411)#12     RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2772)#13     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:784)#14     RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2767)#15     RenderStack.hitTestChildren (package:flutter/src/rendering/stack.dart:620)#16     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2411)#17     _RenderSingleChildViewport.hitTestChildren.<anonymous closure> (package:flutter/src/widgets/single_child_scroll_view.dart:590)#18     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:784)#19     RenderShiftedBox.hitTestChildren (package:flutter/src/rendering/shifted_box.dart:87)#20     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2411)#21     RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2772)#22     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:784)#23     RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2767)#24     RenderWrap.hitTestChildren (package:flutter/src/rendering/wrap.dart:756)#25     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2411)#26     _RenderLayoutBuilder.hitTestChildren (package:flutter/src/widgets/layout_builder.dart:335)#27     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2411)#28     _RenderSingleChildViewport.hitTestChildren.<anonymous closure> (package:flutter/src/widgets/single_child_scroll_view.dart:590)#29     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:784)#30     RenderShiftedBox.hitTestChildren (package:flutter/src/rendering/shifted_box.dart:87)#31     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2411)#32     RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2772)#33     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:784)#34     RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2767)#35     RenderStack.hitTestChildren (package:flutter/src/rendering/stack.dart:620)#36     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2411)#37     _RenderLayoutBuilder.hitTestChildren (package:flutter/src/widgets/layout_builder.dart:335)#38     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2411)#39     _RenderLayoutBuilder.hitTestChildren (package:flutter/src/widgets/layout_builder.dart:335)#40     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2411)#41     RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2772)#42     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:784)#43     RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2767)#44     RenderStack.hitTestChildren (package:flutter/src/rendering/stack.dart:620)#45     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2411)#46     _RenderLayoutBuilder.hitTestChildren (package:flutter/src/widgets/layout_builder.dart:335)#47     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2411)#48     RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2772)#49     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:784)#50     RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2767)#51     RenderWrap.hitTestChildren (package:flutter/src/rendering/wrap.dart:756)#52     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2411)#53     _RenderLayoutBuilder.hitTestChildren (package:flutter/src/widgets/layout_builder.dart:335)#54     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2411)#55     RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2772)#56     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:784)#57     RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2767)#58     RenderStack.hitTestChildren (package:flutter/src/rendering/stack.dart:620)#59     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2411)#60     RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2772)#61     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:784)#62     RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2767)#63     RenderStack.hitTestChildren (package:flutter/src/rendering/stack.dart:620)#64     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2411)#65     RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2772)#66     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:784)#67     RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2767)#68     RenderCustomMultiChildLayoutBox.hitTestChildren (package:flutter/src/rendering/custom_layout.dart:413)#69     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2411)#70     _RenderLayoutBuilder.hitTestChildren (package:flutter/src/widgets/layout_builder.dart:335)#71     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2411)#72     _RenderLayoutBuilder.hitTestChildren (package:flutter/src/widgets/layout_builder.dart:335)#73     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2411)#74     RenderPhysicalModel.hitTest (package:flutter/src/rendering/proxy_box.dart:1896)#75     _RenderLayoutBuilder.hitTestChildren (package:flutter/src/widgets/layout_builder.dart:335)#76     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:178)#77     _RenderLayoutBuilder.hitTestChildren (package:flutter/src/widgets/layout_builder.dart:335)#78     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2411)#79     _RenderLayoutBuilder.hitTestChildren (package:flutter/src/widgets/layout_builder.dart:335)#80     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2411)#81     _RenderLayoutBuilder.hitTestChildren (package:flutter/src/widgets/layout_builder.dart:335)#82     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2411)#83     RenderOffstage.hitTest (package:flutter/src/rendering/proxy_box.dart:3434)#84     _RenderLayoutBuilder.hitTestChildren (package:flutter/src/widgets/layout_builder.dart:335)#85     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2411)#86     _RenderLayoutBuilder.hitTestChildren (package:flutter/src/widgets/layout_builder.dart:335)#87     RenderFollowerLayer.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/proxy_box.dart:5305)#88     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:784)#89     RenderFractionalTranslation.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:2767)#90     RenderFractionalTranslation.hitTest (package:flutter/src/rendering/proxy_box.dart:2753)#91     _RenderLayoutBuilder.hitTestChildren (package:flutter/src/widgets/layout_builder.dart:335)#92     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2411)#93     _RenderLayoutBuilder.hitTestChildren (package:flutter/src/widgets/layout_builder.dart:335)#94     _RenderFocusTrap.hitTest (package:flutter/src/widgets/routes.dart:2136)#95     _RenderLayoutBuilder.hitTestChildren (package:flutter/src/widgets/layout_builder.dart:335)#96     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2411)#97     _RenderLayoutBuilder.hitTestChildren (package:flutter/src/widgets/layout_builder.dart:335)#98     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2411)#99     RenderOffstage.hitTest (package:flutter/src/rendering/proxy_box.dart:3434)#100    _RenderLayoutBuilder.hitTestChildren (package:flutter/src/widgets/layout_builder.dart:335)#101    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2411)#102    _RenderTheatre.hitTestChildren.<anonymous closure> (package:flutter/src/widgets/overlay.dart:773)#103    BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:784)#104    _RenderTheatre.hitTestChildren (package:flutter/src/widgets/overlay.dart:768)#105    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2411)#106    _RenderLayoutBuilder.hitTestChildren (package:flutter/src/widgets/layout_builder.dart:335)#107    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2411)#108    _RenderLayoutBuilder.hitTestChildren (package:flutter/src/widgets/layout_builder.dart:335)#109    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2411)#110    RenderAbsorbPointer.hitTest (package:flutter/src/rendering/proxy_box.dart:3532)#111    _RenderLayoutBuilder.hitTestChildren (package:flutter/src/widgets/layout_builder.dart:335)#112    RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:178)#113    _RenderLayoutBuilder.hitTestChildren (package:flutter/src/widgets/layout_builder.dart:335)#114    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2411)#115    _RenderLayoutBuilder.hitTestChildren (package:flutter/src/widgets/layout_builder.dart:335)#116    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2411)#117    _RenderLayoutBuilder.hitTestChildren (package:flutter/src/widgets/layout_builder.dart:335)#118    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2411)#119    _RenderLayoutBuilder.hitTestChildren (package:flutter/src/widgets/layout_builder.dart:335)#120    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2411)#121    RenderView.hitTest (package:flutter/src/rendering/view.dart:185)#122    RendererBinding.hitTest (package:flutter/src/rendering/binding.dart:527)#123    GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:346)#124    GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338)#125    GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296)#126    GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279)#127    _rootRunUnary (dart:async/zone.dart:1444)#128    _CustomZone.runUnary (dart:async/zone.dart:1335)#129    _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244)#130    _invoke1 (dart:ui/hooks.dart:169)#131    PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293)#132    _dispatchPointerDataPacket (dart:ui/hooks.dart:88)
```

Flutter version: 2.8.1 from stable channel. Platform where i face this issue: Windows

I catch this error with runZonedGuarded(strange that it's not caught by FlutterError.onError) method and send it to the app server and i do not where it happens because error and stackTrace do not show the place where it happens so i can't provide you any reproducible code, just the error.

**Comment by kirill-21** [comment]
I have other similar errors(with exception+stack but without reproducible code) about _TooltipState, AnimationController, RenderBox.size, will it be useful to publish them in separate issues if i can not provide reproducible code because i have no idea when they happen?

**Comment by darshankawar** [comment]
@kirill-21 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/84650
Please follow-up in it for further updates.
Closing this as a duplicate.
