### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: The filename, directory name, or volume label syntax is incorrect., errno = 123

### ISSUE THREAD

**Issue by iragaba** [flutter/flutter#95823]
## Command
```
flutter run -d chrome
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot open file, OS Error: The filename, directory name, or volume label syntax is incorrect.
, errno = 123
```
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356:9)
#1      _rootRunUnary (dart:async/zone.dart:1436:47)
#2      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
<asynchronous suspension>
#3      ForwardingFile.writeAsBytes (package:file/src/forwarding/forwarding_file.dart:112:12)
<asynchronous suspension>
#4      ErrorHandlingFile.writeAsBytes.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:208:24)
<asynchronous suspension>
#5      _run (package:flutter_tools/src/base/error_handling_io.dart:567:12)
<asynchronous suspension>
#6      writeBundle.<anonymous closure> (package:flutter_tools/src/bundle_builder.dart:166:9)
<asynchronous suspension>
#7      Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#8      writeBundle (package:flutter_tools/src/bundle_builder.dart:155:3)
<asynchronous suspension>
#9      WebDevFS.update (package:flutter_tools/src/isolated/devfs_web.dart:830:9)
<asynchronous suspension>
#10     ResidentWebRunner._updateDevFS (package:flutter_tools/src/isolated/resident_web_runner.dart:510:35)
<asynchronous suspension>
#11     ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:283:41)
<asynchronous suspension>
#12     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.18363.476], locale
    en-US)
    • Flutter version 2.5.3 at E:\softs\flutter_windows_2.5.1-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (2 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\user\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.63.2)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.29.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 96.0.4664.110

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: bbfbf1770cca2da7c82e887e4e4af910034800b6
### Plugins
path_provider-1.6.17
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+4
path_provider_windows-0.0.4+1
sqflite-1.3.1+1

**Comment by danagbemava-nc** [comment]
Hi @iragaba, thanks for filing the issue. 

Can you please provide the crash log that was generated with the crash? It should have a name similar to `flutter_01.log`?

Thank you
