### ISSUE TITLE
flutter module can not set IPHONEOS_DEPLOYMENT_TARGET to 10.0 

### ISSUE THREAD

**Issue by dujj** [flutter/flutter#95841]
I want to set 'IPHONEOS_DEPLOYMENT_TARGET' to 10.0, can tell me how to do it .

1. flutter create -t module do_what
2. cd do_what
3. flutter pub add flutter_sound
4. flutter build ios-framework --no-debug --no-profile

## Logs
```
Running "flutter pub get" in do_what...                          1,947ms

💪 Building with sound null safety 💪

Building frameworks for com.example.doWhat in release mode...
 ├─Copying Flutter.xcframework...                                1,522ms
 ├─Building App.xcframework...                                     63.5s
Running pod install...                                           1,470ms
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `FlutterPluginRegistrant` from
    `Flutter/FlutterPluginRegistrant`
    -> Fetching podspec for `flutter_sound` from
    `.symlinks/plugins/flutter_sound/ios`
    -> Fetching podspec for `path_provider_ios` from
    `.symlinks/plugins/path_provider_ios/ios`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local
      because checking is only performed in repo update
    [!] CocoaPods could not find compatible versions for pod "flutter_sound":
      In Podfile:
        flutter_sound (from `.symlinks/plugins/flutter_sound/ios`)

    Specs satisfying the `flutter_sound (from
    `.symlinks/plugins/flutter_sound/ios`)` dependency were found, but they
    required a higher minimum deployment target.

    /usr/local/Cellar/cocoapods/1.11.2_1/libexec/gems/molinillo-0.8.0/lib/molini
    llo/resolution.rb:317:in `raise_error_unless_state'
    /usr/local/Cellar/cocoapods/1.11.2_1/libexec/gems/molinillo-0.8.0/lib/molini
    llo/resolution.rb:299:in `block in unwind_for_conflict'
    /usr/local/Cellar/cocoapods/1.11.2_1/libexec/gems/molinillo-0.8.0/lib/molini
    llo/resolution.rb:297:in `tap'
    /usr/local/Cellar/cocoapods/1.11.2_1/libexec/gems/molinillo-0.8.0/lib/molini
    llo/resolution.rb:297:in `unwind_for_conflict'
    /usr/local/Cellar/cocoapods/1.11.2_1/libexec/gems/molinillo-0.8.0/lib/molini
    llo/resolution.rb:682:in `attempt_to_activate'
    /usr/local/Cellar/cocoapods/1.11.2_1/libexec/gems/molinillo-0.8.0/lib/molini
    llo/resolution.rb:254:in `process_topmost_state'
    /usr/local/Cellar/cocoapods/1.11.2_1/libexec/gems/molinillo-0.8.0/lib/molini
    llo/resolution.rb:182:in `resolve'
    /usr/local/Cellar/cocoapods/1.11.2_1/libexec/gems/molinillo-0.8.0/lib/molini
    llo/resolver.rb:43:in `resolve'
    /usr/local/Cellar/cocoapods/1.11.2_1/libexec/gems/cocoapods-1.11.2/lib/cocoa
    pods/resolver.rb:94:in `resolve'
    /usr/local/Cellar/cocoapods/1.11.2_1/libexec/gems/cocoapods-1.11.2/lib/cocoa
    pods/installer/analyzer.rb:1078:in `block in resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.11.2_1/libexec/gems/cocoapods-1.11.2/lib/cocoa
    pods/user_interface.rb:64:in `section'
    /usr/local/Cellar/cocoapods/1.11.2_1/libexec/gems/cocoapods-1.11.2/lib/cocoa
    pods/installer/analyzer.rb:1076:in `resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.11.2_1/libexec/gems/cocoapods-1.11.2/lib/cocoa
    pods/installer/analyzer.rb:124:in `analyze'
    /usr/local/Cellar/cocoapods/1.11.2_1/libexec/gems/cocoapods-1.11.2/lib/cocoa
    pods/installer.rb:416:in `analyze'
    /usr/local/Cellar/cocoapods/1.11.2_1/libexec/gems/cocoapods-1.11.2/lib/cocoa
    pods/installer.rb:241:in `block in resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.11.2_1/libexec/gems/cocoapods-1.11.2/lib/cocoa
    pods/user_interface.rb:64:in `section'
    /usr/local/Cellar/cocoapods/1.11.2_1/libexec/gems/cocoapods-1.11.2/lib/cocoa
    pods/installer.rb:240:in `resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.11.2_1/libexec/gems/cocoapods-1.11.2/lib/cocoa
    pods/installer.rb:161:in `install!'
    /usr/local/Cellar/cocoapods/1.11.2_1/libexec/gems/cocoapods-1.11.2/lib/cocoa
    pods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in
    `run'
    /usr/local/Cellar/cocoapods/1.11.2_1/libexec/gems/cocoapods-1.11.2/lib/cocoa
    pods/command.rb:52:in `run'
    /usr/local/Cellar/cocoapods/1.11.2_1/libexec/gems/cocoapods-1.11.2/bin/pod:5
    5:in `<top (required)>'
    /usr/local/Cellar/cocoapods/1.11.2_1/libexec/bin/pod:23:in `load'
    /usr/local/Cellar/cocoapods/1.11.2_1/libexec/bin/pod:23:in `<main>'

Error running pod install
```

```
[✓] Flutter (Channel stable, 2.8.0, on macOS 12.0.1 21A559 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 2.8.0 at /usr/local/Caskroom/flutter/2.5.1/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (3 周前), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/dujianjie/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • iPhone 7 Plus (mobile) • 6c5b20c0164d794f0e3ad79f52b9ce59d4540689 • ios
      • iOS 15.1 19B74
    • iPhone 13 (mobile)     • 691D3EDE-7DD1-4A0B-82E2-DC86CAABEBEF     • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)           • chrome                                   •
      web-javascript • Google Chrome 96.0.4664.110

• No issues found!
```
</details>

**Comment by dujj** [comment]
flutter_sound plugin is support for iOS 10.0 or later

**Comment by dujj** [comment]
As a library, it should be possible to specify the supported iOS version, otherwise the plug-in library is higher than the supported version, and problems will occur.

**Comment by maheshmnj** [comment]
Hi @dujj,  Thanks for filing the issue.

You may try something like this 
1. create iOS app and module
2. Add whatever package to module `pubpsec.yaml`
3. modify ios target in your native iOS app
4. Register plugin like this  in the native iOS app as [mentioned here](https://github.com/flutter/flutter/issues/69024#issuecomment-869139468)

There is a similar issue describing this case https://github.com/flutter/flutter/issues/78862, Please follow up there for further updates, Closing this issue as a duplicate. If you disagree feel free to write in the comments and I will reopen it.

Thank you.
