### ISSUE TITLE
Camera ANR at Android (at dispose)

### ISSUE THREAD

**Issue by ajw227** [flutter/flutter#95921]
Hi. flutter.
Please check below.

 <summary> Related codes</summary>

[Camera Android Code](https://github.com/flutter/plugins/blob/master/packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/Camera.java#L620)
```
  /** Stops the background thread and its {@link Handler}. */
  public void stopBackgroundThread() {
    if (backgroundHandlerThread != null) {
      backgroundHandlerThread.quitSafely();
      try {
        backgroundHandlerThread.join();
      } catch (InterruptedException e) {
        dartMessenger.error(flutterResult, "cameraAccess", e.getMessage(), null);
      }
    }
    backgroundHandlerThread = null;
    backgroundHandler = null;
  }
```

 <summary> Related links</summary>

[Stop HandlerThread](https://stackoverflow.com/questions/8907626/is-this-a-prefect-way-to-stop-handlerthread)

```
thread.quitSafely(); // not call join();
```

<summary>Logs</summary>

```
java.lang.Object.wait (Object.java)
java.lang.Object.wait (Object.java:442)
java.lang.Thread.join (Thread.java:1438)
java.lang.Thread.join (Thread.java:1519)
io.flutter.plugins.camera.Camera.stopBackgroundThread (Camera.java)
io.flutter.plugins.camera.Camera.close (Camera.java)
io.flutter.plugins.camera.Camera.dispose (Camera.java)
io.flutter.plugins.camera.MethodCallHandlerImpl.onMethodCall (MethodCallHandlerImpl.java)
io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage (MethodChannel.java)
io.flutter.embedding.engine.dart.DartMessenger.invokeHandler (DartMessenger.java)
io.flutter.embedding.engine.dart.DartMessenger.lambda$handleMessageFromDart$0 (DartMessenger.java)
io.flutter.embedding.engine.dart.DartMessenger.$r8$lambda$6ZD1MYkhaLxyPjtoFDxe45u43DI (DartMessenger.java)
io.flutter.embedding.engine.dart.DartMessenger$$InternalSyntheticLambda$0$75ebfcfd53b0b0a884b1e22267a97587635cd2630d2f814c3024af8922adcf72$0.run (DartMessenger.java)
android.os.Handler.handleCallback (Handler.java:938)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loop (Looper.java:246)
android.app.ActivityThread.main (ActivityThread.java:8633)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:602)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)
```

<summary>Crashlytics Screenshot</summary>
<img width="973" alt="ANR" src="https://user-images.githubusercontent.com/52198265/147623318-7211a7ce-8986-497d-97bb-87fb4808fab6.png">

**Comment by darshankawar** [comment]
@ajw227 
Can you provide `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) if possible that replicates this behavior along with camera plugin version you are using ?
Also provide the crash log in text format for better readability and steps to replicate so that we can properly address this issue.
Thanks.

**Comment by ajw227** [comment]
@darshankawar 

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.0.1 21A559 darwin-x64, locale
    ko-KR)
    • Flutter version 2.8.1 at /Users/user/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (13 days ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)

```


`camera version is ^0.9.4+5`

**Comment by darshankawar** [comment]
> and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) if possible that replicates this behavior 
> Also provide the crash log in text format for better readability and steps to replicate

@ajw227

**Comment by Anubhav-Roy** [comment]
Were you able to solve this ? I am also getting the same ANR on Android 11 phones. I think this is happening when the camera is being created since this code is called from two places - while creating and on stopping the camera.

**Comment by Surya-ufours** [comment]
@ajw227 @Anubhav-Roy Are you solve this issue?? If you solve let me know.

**Comment by Tom3652** [comment]
I am having the same crash : 

```
main (waiting): tid=1 systid=29866
       at java.lang.Object.wait(Object.java)
       at java.lang.Object.wait(Object.java:442)
       at java.lang.Thread.join(Thread.java:1438)
       at java.lang.Thread.join(Thread.java:1519)
       at io.flutter.plugins.camera.Camera.stopBackgroundThread(Camera.java)
       at io.flutter.plugins.camera.Camera.close(Camera.java)
       at io.flutter.plugins.camera.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java)
       at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java)
       at io.flutter.embedding.engine.dart.DartMessenger.lambda$handleMessageFromDart$0(DartMessenger.java)
       at io.flutter.embedding.engine.dart.DartMessenger.$r8$lambda$6ZD1MYkhaLxyPjtoFDxe45u43DI(DartMessenger.java)
       at io.flutter.embedding.engine.dart.DartMessenger$$InternalSyntheticLambda$0$75ebfcfd53b0b0a884b1e22267a97587635cd2630d2f814c3024af8922adcf72$0.run(DartMessenger.java)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:233)
       at android.app.ActivityThread.main(ActivityThread.java:8010)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```

And with the same below code i am also getting this ANR but i am willing to fill a new issue to track if needed but it may be related : 

```
main (native): tid=1 systid=23678
#00 pc 0x9b274 libc.so 
#01 pc 0x57da0 libc.so 
#02 pc 0x51d94 libbinder.so 
#03 pc 0x52d80 libbinder.so 
#04 pc 0x52af0 libbinder.so 
#05 pc 0x4b010 libbinder.so 
#06 pc 0x1261a8 libandroid_runtime.so 
       at android.os.BinderProxy.transactNative(BinderProxy.java)
       at android.os.BinderProxy.transact(BinderProxy.java:591)
       at android.hardware.ICameraService$Stub$Proxy.connectDevice(ICameraService.java:655)
       at android.hardware.camera2.CameraManager.openCameraDeviceUserAsync(CameraManager.java:567)
       at android.hardware.camera2.CameraManager.openCameraForUid(CameraManager.java:799)
       at android.hardware.camera2.CameraManager.openCamera(CameraManager.java:709)
       at io.flutter.plugins.camera.Camera.open(Camera.java)
       at io.flutter.plugins.camera.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java)
       at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java)
       at io.flutter.embedding.engine.dart.DartMessenger.lambda$handleMessageFromDart$0(DartMessenger.java)
       at io.flutter.embedding.engine.dart.DartMessenger.$r8$lambda$6ZD1MYkhaLxyPjtoFDxe45u43DI(DartMessenger.java)
       at io.flutter.embedding.engine.dart.DartMessenger$$InternalSyntheticLambda$0$75ebfcfd53b0b0a884b1e22267a97587635cd2630d2f814c3024af8922adcf72$0.run(DartMessenger.java)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:233)
       at android.app.ActivityThread.main(ActivityThread.java:8010)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```

on Android 11. 

The lifecycle handling is done this way : 

```
@override
  void initState() {
    super.initState();
    // Allows to listen to the application lifecycle states.
    WidgetsBinding.instance!.addObserver(this);
    WidgetsBinding.instance!.addPostFrameCallback((Duration timeStamp) {
      _cameraViewModel.initCamera();
    });
  }

  @override
  void dispose() {
    _cameraViewModel.disposeCamera();
    WidgetsBinding.instance!.removeObserver(this);
    super.dispose();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    super.didChangeAppLifecycleState(state);
    switch (state) {
      case AppLifecycleState.resumed:
        _cameraViewModel.resumeCamera();
        break;
      case AppLifecycleState.inactive:
        _cameraViewModel.pauseCamera();
        break;
      case AppLifecycleState.paused:
        break;
      case AppLifecycleState.detached:
        break;
    }
  }
```

And in ```CameraViewModel``` : 

```

Future<void> initCamera() async {
    PermissionStatus status = await Permission.camera.request();
    if (status.isGranted) {
      List<CameraDescription> availableCams = await availableCameras();
      _cameras.clear();
      _cameras.addAll(availableCams);
      cameraController = CameraController(_cameras.first, ResolutionPreset.veryHigh, enableAudio: false);
      if (!cameraController!.value.isInitialized) {
        await cameraController!.initialize();
        cameraController!.setFlashMode(FlashMode.off);
      }
    } else {
      if (status.isPermanentlyDenied) {
        AppSettings.openAppSettings();
      }
    }
  }

  void disposeCamera() {
    if (cameraController != null && cameraController!.value.isInitialized) {
      cameraController!.dispose();
      cameraController = null;
    }
  }

  void resumeCamera() {
    if (cameraController != null) {
      if (cameraController!.value.isPreviewPaused) {
        cameraController!.resumePreview();
      } else {
        initCamera();
      }
    }
  }

  void pauseCamera() {
    if (cameraController != null && cameraController!.value.isInitialized) {
      cameraController!.pausePreview();
    }
  }
```

**Comment by a8851625** [comment]
> Hi. flutter. Please check below.
> 
> Related codes
> [Camera Android Code](https://github.com/flutter/plugins/blob/master/packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/Camera.java#L620)
> 
> ```
>   /** Stops the background thread and its {@link Handler}. */
>   public void stopBackgroundThread() {
>     if (backgroundHandlerThread != null) {
>       backgroundHandlerThread.quitSafely();
>       try {
>         backgroundHandlerThread.join();
>       } catch (InterruptedException e) {
>         dartMessenger.error(flutterResult, "cameraAccess", e.getMessage(), null);
>       }
>     }
>     backgroundHandlerThread = null;
>     backgroundHandler = null;
>   }
> ```
> 
> Related links
> [Stop HandlerThread](https://stackoverflow.com/questions/8907626/is-this-a-prefect-way-to-stop-handlerthread)
> 
> ```
> thread.quitSafely(); // not call join();
> ```
> 
> Logs
> ```
> java.lang.Object.wait (Object.java)
> java.lang.Object.wait (Object.java:442)
> java.lang.Thread.join (Thread.java:1438)
> java.lang.Thread.join (Thread.java:1519)
> io.flutter.plugins.camera.Camera.stopBackgroundThread (Camera.java)
> io.flutter.plugins.camera.Camera.close (Camera.java)
> io.flutter.plugins.camera.Camera.dispose (Camera.java)
> io.flutter.plugins.camera.MethodCallHandlerImpl.onMethodCall (MethodCallHandlerImpl.java)
> io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage (MethodChannel.java)
> io.flutter.embedding.engine.dart.DartMessenger.invokeHandler (DartMessenger.java)
> io.flutter.embedding.engine.dart.DartMessenger.lambda$handleMessageFromDart$0 (DartMessenger.java)
> io.flutter.embedding.engine.dart.DartMessenger.$r8$lambda$6ZD1MYkhaLxyPjtoFDxe45u43DI (DartMessenger.java)
> io.flutter.embedding.engine.dart.DartMessenger$$InternalSyntheticLambda$0$75ebfcfd53b0b0a884b1e22267a97587635cd2630d2f814c3024af8922adcf72$0.run (DartMessenger.java)
> android.os.Handler.handleCallback (Handler.java:938)
> android.os.Handler.dispatchMessage (Handler.java:99)
> android.os.Looper.loop (Looper.java:246)
> android.app.ActivityThread.main (ActivityThread.java:8633)
> java.lang.reflect.Method.invoke (Method.java)
> com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:602)
> com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)
> ```
> 
> Crashlytics Screenshot
> <img alt="ANR" width="973" src="https://user-images.githubusercontent.com/52198265/147623318-7211a7ce-8986-497d-97bb-87fb4808fab6.png">

Have you solved this problem?

**Comment by lizubing1992** [comment]
I found a callback method onError of CameraDevice.StateCallback to reproduce the scene. After opening the custom camera page and then returning to the desktop to open the system camera app to take pictures, the onError method may be called back. It is easier to reproduce the Max cameras in use This error, in this case, will call back the close method, and the close method will call the stopBackgroundThread() method and call backgroundHandlerThread.join(); let the main thread wait and generate ANR

~~~
 @Override
          public void onError(@NonNull CameraDevice cameraDevice, int errorCode) {
            Log.i(TAG, "open | onError");

            close();
            String errorDescription;
            switch (errorCode) {
              case ERROR_CAMERA_IN_USE:
                errorDescription = "The camera device is in use already.";
                break;
              case ERROR_MAX_CAMERAS_IN_USE:
                errorDescription = "Max cameras in use";
                break;
              case ERROR_CAMERA_DISABLED:
                errorDescription = "The camera device could not be opened due to a device policy.";
                break;
              case ERROR_CAMERA_DEVICE:
                errorDescription = "The camera device has encountered a fatal error";
                break;
              case ERROR_CAMERA_SERVICE:
                errorDescription = "The camera service has encountered a fatal error.";
                break;
              default:
                errorDescription = "Unknown camera error";
            }
            dartMessenger.sendCameraErrorEvent(errorDescription);
          }
          
          
          
  public void close() {
    Log.i(TAG, "close");
    closeCaptureSession();

    if (cameraDevice != null) {
      cameraDevice.close();
      cameraDevice = null;
    }
    if (pictureImageReader != null) {
      pictureImageReader.close();
      pictureImageReader = null;
    }
    if (imageStreamReader != null) {
      imageStreamReader.close();
      imageStreamReader = null;
    }
    if (mediaRecorder != null) {
      mediaRecorder.reset();
      mediaRecorder.release();
      mediaRecorder = null;
    }

    stopBackgroundThread();
  }
         
 
 public void stopBackgroundThread() {
    if (backgroundHandlerThread != null) {
      backgroundHandlerThread.quitSafely();
      try {
        backgroundHandlerThread.join();
      } catch (InterruptedException e) {
        dartMessenger.error(flutterResult, "cameraAccess", e.getMessage(), null);
      }
    }
    backgroundHandlerThread = null;
    backgroundHandler = null;
  }       
~~~

The solution is that the close method does not call stopBackgroundThread() in the onError callback. I tried this method to solve ANR

**Comment by lizubing1992** [comment]
![image](https://user-images.githubusercontent.com/13564344/149615598-03190b7a-53c5-4609-aedc-579224ee9098.png)
The above picture is to view the life cycle of the corresponding thread. When the App is placed in the background, the first CameraBackground will quit. When the page is opened again, the second CameraBackground thread will be generated, but in the sleeping state, the callback function reports an error. Call close() -> stopBackgroundThread()
->backgroundHandlerThread.join(), which causes the main thread to wait for CameraBackground to exit, so ANR occurs.

**Comment by darshankawar** [comment]
Everyone facing / reporting ANR in this thread, please provide a concrete and isolated reproducible code sample along with exact steps to replicate that clearly throws the error, that way we'll be able to verify and address this issue properly.
