### ISSUE TITLE
On iOS, WebView not loading initialUrl if WebView is not visible

### ISSUE THREAD

**Issue by jmgeffroy** [flutter/flutter#95938]
Hi there,

We are facing an issue on iOS: we are displaying webviews ([webview_flutter](https://pub.dev/packages/webview_flutter)) that are placed inside a [PreloadPageView](https://pub.dev/packages/preload_page_view). Each WebView can have arbitrary width: they contain chapters of a book. The project can be found [here](https://github.com/Mantano/iridium/tree/feature/monorepo).

- On Android, no problem at all. Thanks to some JS + Flutter event management tricks, the swipe works perfectly both inside a chapter and across chapters;
- On iOS, only the first visible webview does load its content, set through "initialUrl".

We have tested on iOS 15.2 with webview_flutter 2.8.0 and 3.0.0.

Here are 2 screenshots from the Android version:

![intra_chap](https://user-images.githubusercontent.com/4281439/147682899-45b35e50-4962-47cc-a8b9-08bc3e9188c5.png)

![inter_chap](https://user-images.githubusercontent.com/4281439/147682900-1111abf4-679a-4478-9394-e2483304fbce.png)

On iOS, only the first webview in the PreloadPageView is visible, and displays the book cover, as expected. However, the other webviews are empty, as can be seen in the dev tools:

<img width="416" alt="Capture d’écran 2021-12-29 à 16 27 07" src="https://user-images.githubusercontent.com/4281439/147683297-816b5744-2ca7-48e0-977c-2b1bfa5e291b.png">
It used to work (on previous versions of iOS), but after many many attempts, we failed at reverting back to a state where it did. We'll continue trying to find a working config, but any clue would be highly appreciated.

Flutter doctor - v provides the following output:

```
[✓] Flutter (Channel dev, 2.9.0-0.1.pre, on macOS 12.0.1 21A559 darwin-arm, locale fr-FR)
    • Flutter version 2.9.0-0.1.pre at /Applications/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8f1f9c10f0 (il y a 2 semaines), 2021-12-14 13:41:48 -0800
    • Engine revision 234aca678a
    • Dart version 2.16.0 (build 2.16.0-80.1.beta)
    • DevTools version 2.9.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Applications/android-sdk-macosx
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Applications/android-sdk-macosx
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-11.0.7.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment 18.9 (build 11.0.7+8-LTS)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/jmgeffroy/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7678000/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[☠] IntelliJ IDEA Ultimate Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1426:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1861:10)
      #15     runZonedGuarded (dart:async/zone.dart:1849:12)
      #16     runZoned (dart:async/zone.dart:1780:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:198:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:302:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] IntelliJ IDEA Ultimate Edition (version 2021.3)
    • IntelliJ at /Users/jmgeffroy/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/213.5744.223/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.3)
    • IntelliJ at /Users/jmgeffroy/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/212.5457.46/IntelliJ IDEA.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] Connected device (3 available)
    • iPhone de Jean-Marie Geffroy (mobile) • 88cdde3d1155888acfb6f781da596113d3b49f9a • ios            • iOS 15.1 19B74
    • macOS (desktop)                       • macos                                    • darwin-arm64   • macOS 12.0.1 21A559 darwin-arm
    • Chrome (web)                          • chrome                                   • web-javascript • Google Chrome 96.0.4664.110

! Doctor found issues in 1 category.
```

**Comment by jmgeffroy** [comment]
Workaround: following [this suggestion](https://github.com/flutter/flutter/issues/31191#issuecomment-504337877), I added:
```
viewportFraction: 0.99 
```

in PageController. It works perfectly...

**Comment by darshankawar** [comment]
@jmgeffroy 
I cloned the project and tried to run from `app` root level but getting below error:

```
dhs@Dhss-MacBook-Pro app % flutter run
Because iridium_app depends on mno_streamer from path which doesn't exist (could not find package mno_streamer at "../../bookari_for_flutter/mno_streamer_dart"), version solving failed.
Running "flutter pub get" in app...                                     
pub get failed (66; Because iridium_app depends on mno_streamer from path which
doesn't exist (could not find package mno_streamer at
"../../bookari_for_flutter/mno_streamer_dart"), version solving failed.)
```

Also, since you are using third party plugin, have you also confirmed with the plugin owner if it could be an issue from their side on iOS ?
Moreover, to properly address this issue, can you provide us only a minimal code sample that'll be enough to replicate this behavior ?
Thanks.

**Comment by jmgeffroy** [comment]
Hello @darshankawar thanks a lot for examining our issue! Make sure that you are on the `project/monorepo` branch. This project is currently being pretty heavily refactored, I apologize for that. 
In the `feature/monorepo` branch, `mno_streamer` is inside the `modules`directory.
The PreloadPageView is a 3rd-party plugin, but 100% Flutter. There is no iOS-specific code inside.
I am working on preparing a simpler test project for you and notify you when ready. 
Very best regards

**Comment by jmgeffroy** [comment]
Here is a small test project: [https://github.com/Mantano/pagination_tests](https://github.com/Mantano/pagination_tests). It exhibits the issue *on both platforms*. 

- Description: 
    - The UI contains a first Webview which is stacked behind a PreloadPageView (this aims at testing whether it will be pre-rendered or not while hidden by the other component)
    - The PreloadPageView contains many webviews. The `preloadPageCount` is 3
- Observations:
    - As expected, the first Webview, behind the PreloadPageView, is created, his contents is rendered and has the proper dimensions. 
    - As expected, 3 webviews in the PreloadPageView are created
    - For each of these WebViews: 
        - onPageFinished is called
        - the initialUrl content is loaded, parsed and can be accessed through the DevTools (screenshot)
  - ISSUE (on Android and iOS): The preloaded webviews contents are not pre-rendered, and hence have dimensions equal to 0. Their document DOM is available through the Chrome DevTools.

<img width="504" alt="Capture d’écran 2021-12-30 à 12 01 01" src="https://user-images.githubusercontent.com/4281439/147751059-c9fe2466-c6d2-4e42-869c-dfb94023d95d.png">

DOM of preloaded webviews contents:

<img width="574" alt="Capture d’écran 2021-12-30 à 12 18 09" src="https://user-images.githubusercontent.com/4281439/147751375-5847184c-9bf2-4853-8c2c-0dc7dddc4c1b.png">

The execution trace shows the following:
```
I/flutter ( 2284): D	_PaginatingWebViewState.build:	 ============= Device screen width: 411.42857142857144
I/flutter ( 2284): D	_PaginatingWebViewState.build:	 ============= Device screen width: 411.42857142857144
I/flutter ( 2284): D	_PaginatingWebViewState.build:	 ============= Device screen width: 411.42857142857144
I/flutter ( 2284): D	_PaginatingWebViewState.build:	 ============= Device screen width: 411.42857142857144
I/flutter ( 2284): D	_PaginatingWebViewState._onPageFinished:	 ============== _onPageFinished[0]
I/flutter ( 2284): D	_PaginatingWebViewState._onPageFinished:	 ============== _onPageFinished[1]
I/flutter ( 2284): D	_PaginatingWebViewState._onPageFinished:	 ============== _onPageFinished[3]
I/flutter ( 2284): D	_PaginatingWebViewState._onPageFinished:	 ============== _onPageFinished[2]
I/flutter ( 2284): D	_PaginatingWebViewState._onPageFinished:	 ============== _onPageFinished[0]
I/flutter ( 2284): D	_PaginatingWebViewState._onPageFinished:	 ============== _onPageFinished[1]
I/flutter ( 2284): D	_PaginatingWebViewState._onPageFinished:	 ============== _onPageFinished[3]
I/flutter ( 2284): D	_PaginatingWebViewState._onPageFinished:	 ============== _onPageFinished[2]
```
I don't know why onPageFinished is called twice for each, but it doesn't seem to be the cause of the problem...

I tried (as we do in our reader app) to retrieve the width of the content in a $(window).on('load',...) script, but we get 0 exactly as in the DevTools... The contents is definitely not rendered.

**Comment by jmgeffroy** [comment]
Important update! I understand why the issue now occurs also on Android: I have upgraded to 3.0.0, and as a consequence the WebView is using Hybrid Composition which is now default. If I explicitly select Virtual display, by adding:
```
@override
   void initState() {
     super.initState();
     if (Platform.isAndroid) WebView.platform = AndroidWebView();
   }
```
Then the WebViewsare correctly pre-rendered, as we can see on the following screenshots:

<img width="448" alt="Capture d’écran 2021-12-30 à 13 47 03" src="https://user-images.githubusercontent.com/4281439/147757669-b344c06c-05db-459b-b6e1-3816cfef9220.png">

<img width="490" alt="Capture d’écran 2021-12-30 à 13 49 24" src="https://user-images.githubusercontent.com/4281439/147757735-aa078bd4-bf0a-4708-901e-4721b861cbf8.png">

iOS has always been relying on Hybrid Composition, if I read correctly, so this explains why the issue initially occurred only on iOS.

So the question can probably be summarized as: is it possible to have prerendering with Hybrid Composition exactly like when using Virtual Displays? I would prefer using Hybrid Composition since I have noticed a significantly smoother scrolling...

**Comment by darshankawar** [comment]
@jmgeffroy 
Thanks for coming with a sample project and providing further details. I cloned and ran the app using latest master and stable on iOS simulator on which I do see the webview being rendered properly initially (ie, on app launch) and then after navigating, as below:

<img width="375" alt="Screenshot 2021-12-31 at 10 34 13 AM" src="https://user-images.githubusercontent.com/67046386/147804577-21e6c788-9000-4524-8590-577c14a9dfda.png">
<img width="370" alt="Screenshot 2021-12-31 at 10 39 08 AM" src="https://user-images.githubusercontent.com/67046386/147804580-132081d6-fea6-4c3a-972e-9274f092e0f8.png">

I tried with both platform views (ie, with SurfaceAndroidView and AndroidVew) and result has been same.

Let me know if I missed anything to replicate the case properly.

<details>
<summary> stable, master flutter doctor -v </summary>

```
[[✓] Flutter (Channel stable, 2.8.1, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.8.1 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (13 hours ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dhs/Library/Android/sdk
    • Java binary at: /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.    

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 93.0.4577.82


• No issues found!

[✓] Flutter (Channel master, 2.9.0-1.0.pre.213, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.9.0-1.0.pre.213 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 59af5755e8 (5 hours ago), 2021-12-30 19:14:10 -0500
    • Engine revision 548a272fb2
    • Dart version 2.16.0 (build 2.16.0-134.0.dev)
    • DevTools version 2.9.2
    
[✓] Android toolchain - develop for Android devices (Android SDK version 30)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dhs/Library/Android/sdk
    • Java binary at: /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.    

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 93.0.4577.82


• No issues found!




```

</details>

**Comment by jmgeffroy** [comment]
Hello, @darshankawar ! First of all I wish you a happy new year!
Thanks a lot for your testing. However, I was probably not clear enough in my explanation: the problem isn't the webview not rendering properly. The problem is _when_ the rendering occurs. In our case, what we need is to get a few WebViews in the PageView to be pre-rendered before being visible (at least 1). This can only be checked by inspecting with the developer tools, like what I showcased in my screenshots.
