### ISSUE TITLE
[Google maps Android] Error: `MissingPluginException(No implementation found for method` 

### ISSUE THREAD

**Issue by danielgomezrico** [flutter/flutter#95945]
This only happens on android devices

## Environment

<details>
<summary>Environment</summary>
- Pubspec:

```yaml
environment:
  sdk: 2.15.1
  flutter: 2.8.1

dependencies:
  flutter:
    sdk: flutter
...
  google_maps_flutter: 2.0.10
```

- Flutter doctor:
```bash
$ flutter doctor -v

[✓] Flutter (Channel unknown, 2.8.1, on macOS 11.6 20G165 darwin-x64, locale en-US)
    • Flutter version 2.8.1 at /Users/xxxx/projects/dev/flutter
    • Upstream repository unknown
    • Framework revision 77d935af4d (13 days ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1
```

- build.gradle:
```groovy
buildscript {
    ext.kotlin_version = '1.5.10'
    repositories {
        google()
        jcenter()
        maven { url 'https://plugins.gradle.org/m2/' } // OneSignal
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.4'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.4.1'
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:0.13.4'
    }
}
```
</details>

## Steps to Reproduce

Im not sure how to reproduce the error, it is happening on production, I have 1.1k occurrences of this kind of errors.

I already tried a workaround https://github.com/flutter/flutter/issues/79039#issuecomment-806682279 from https://github.com/flutter/flutter/issues/79039 but it does not fix the issue

1. I use the `GoogleMapController` that I get from `onMapCreated` to `getZoomLevel`,  `getVisibleRegion` and `setMapStyle`, like this:

```dart
GoogleMap(
          onMapCreated: (GoogleMapController controller) async {
            await controller?.setMapStyle(myStyle);

            final zoomLevel = await controller?.getZoomLevel();
            final region = await controller?.getVisibleRegion();
...
```

## Logs

<details>
<summary>Logs</summary>

```dart
MissingPluginException(No implementation found for method tileOverlays#update on channel plugins.flutter.io/google_maps_0)
	#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154)
	<asynchronous suspension>
```

```dart
MissingPluginException(No implementation found for method map#getZoomLevel on channel plugins.flutter.io/google_maps_1)
	#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165)
	<asynchronous suspension>
	#1      MethodChannelGoogleMapsFlutter.getZoomLevel (package:google_maps_flutter_platform_interface/src/method_channel/method_channel_google_maps_flutter.dart:435)
	<asynchronous suspension>
```

```dart
MissingPluginException(No implementation found for method map#setStyle on channel plugins.flutter.io/google_maps_0)
	#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154)
	<asynchronous suspension>
	#1      MethodChannelGoogleMapsFlutter.setMapStyle (package:google_maps_flutter_platform_interface/src/method_channel/method_channel_google_maps_flutter.dart:358)
	<asynchronous suspension>
```

```
```

</details>

**Comment by maheshmnj** [comment]
Hi @danielgomezrico, Thanks for filing the issue. Please share the complete output of `flutter doctor -v` on which the app was compiled. Would it be possible to share the complete logs?

This issue looks similar to https://github.com/flutter/flutter/issues/78625 (closed)

**Comment by danielgomezrico** [comment]
@maheshmnj sorry for taking too long, I cant find more logs related to google maps, 

this is the flutter doctor for the CI:

```bash
Running "flutter pub get" in flutter_tools...                       3.6s
[✓] Flutter (Channel stable, 2.8.1, on Mac OS X 10.15.7 19H15 darwin-x64, locale en)
• Flutter version 2.8.1 at /Users/vagrant/flutter-sdk/flutter
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision 77d935af4d (6 weeks ago), 2021-12-16 08:37:33 -0800
• Engine revision 890a5fca2e
• Dart version 2.15.1
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
• Android SDK at /usr/local/share/android-sdk
• Platform android-30, build-tools 30.0.3
• ANDROID_HOME = /usr/local/share/android-sdk
• ANDROID_SDK_ROOT = /usr/local/share/android-sdk
• Java binary at: /Users/vagrant/.jenv/versions/11/bin/java
• Java version OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
✗ Android license status unknown.
Run `flutter doctor --android-licenses` to accept the SDK licenses.
See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[!] Xcode - develop for iOS and macOS (Xcode 12.4)
• Xcode at /Applications/Xcode-12.4.app/Contents/Developer
! Flutter recommends a minimum Xcode version of 13.0.0.
Download the latest version or update via the Mac App Store.
✗ CocoaPods installed but not working.
You appear to have CocoaPods installed but it is not working.
This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
This can usually be fixed by re-installing CocoaPods.
To re-install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[!] Android Studio (not installed)
• Android Studio not found; download from https://developer.android.com/studio/index.html
(or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
[!] Connected device
! No devices available
! Doctor found issues in 5 categories.
```

**Comment by maheshmnj** [comment]
Hi @danielgomezrico, thanks for the info will take a look at it tomorrow.

**Comment by maheshmnj** [comment]
Provided that you have tried adding pro guard rules, I am labeling this issue for further investigation. The maps are working fine locally but have an error in production.

**Comment by danielgomezrico** [comment]
@maheshmnj can you show me which proguard rules should I use?

One thing I have noticed is that it does not happen every time, I mean, If a user gets the error then after he goes and go back (without updating the app or changing the implementation) it starts working, so it looks like its some kind of runtime exception that happens sometimes, but I can't find a reason

**Comment by maheshmnj** [comment]
I was referring to this https://github.com/flutter/flutter/issues/78625#issuecomment-803243381, Lets wait for the team's insights on this, however, if you have further logs from the Play console feel free to add it in the description.
