### ISSUE TITLE
Crashed when set layout direction to a hybrid composition platform view 

### ISSUE THREAD

**Issue by wangying3426** [flutter/flutter#96003]
When [set layout direction](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/services/platform_views.dart#L855) to a hybrid composition platform view,  an NullPointerException will be thrown.

```js
E/MethodChannel#flutter/platform_views: Failed to handle method call
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View io.flutter.plugin.platform.VirtualDisplayController.getView()' on a null object reference
        at io.flutter.plugin.platform.PlatformViewsController$1.setDirection(PlatformViewsController.java:334)
        at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.setDirection(PlatformViewsChannel.java:189)
        at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:71)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
        at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:178)
        at io.flutter.embedding.engine.dart.DartMessenger.lambda$handleMessageFromDart$0(DartMessenger.java:206)
        at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$R4HPk6oFVb-i-YR_PN9YE6kqx1I.run(Unknown Source:12)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7838)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'android.view.View io.flutter.plugin.platform.VirtualDisplayController.getView()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View io.flutter.plugin.platform.VirtualDisplayController.getView()' on a null object reference
        at io.flutter.plugin.platform.PlatformViewsController$1.setDirection(PlatformViewsController.java:334)
        at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.setDirection(PlatformViewsChannel.java:189)
        at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:71)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
        at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:178)
        at io.flutter.embedding.engine.dart.DartMessenger.lambda$handleMessageFromDart$0(DartMessenger.java:206)
        at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$R4HPk6oFVb-i-YR_PN9YE6kqx1I.run(Unknown Source:12)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7838)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
    )
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
    <asynchronous suspension>
    #2      AndroidViewController.setLayoutDirection (package:flutter/src/services/platform_views.dart:855:5)
    <asynchronous suspension>


````

**Comment by maheshmnj** [comment]
Hi @wangying3426, Thanks for filing the issue. Please share the output of `flutter doctor -v ` and steps to reproduce the issue.

**Comment by wangying3426** [comment]
> Hi @wangying3426, Thanks for filing the issue. Please share the output of `flutter doctor -v ` and steps to reproduce the issue.

C02D56F2MD6R:bin wangying$ flutter doctor -v
[✓] Flutter (Channel unknown, 2.8.0, on macOS 12.0.1 21A559 darwin-x64, locale en-CN)
    • Flutter version 2.8.0 at /Users/wangying/Desktop/flutter/flutter
    • Upstream repository unknown
    • Framework revision cf44000065 (4 weeks ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0
    • Pub download mirror http://dart-pub.byted.org
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/wangying/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] Android Studio
    • Android Studio at /Applications/Android/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Android Studio not found at /Applications/Android/Contents
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.31.20211214

[✓] Connected device (4 available)
    • Pixel 4 (mobile)   • 9A191FFAZ0051B                       • android-arm64  • Android 12 (API 31)
    • iPhone 13 (mobile) • B525205B-409B-462D-9632-BF70EAA7D97B • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • macOS 12.0.1 21A559 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 93.0.4577.63

! Doctor found issues in 2 categories.
 
fixes it at [#30611](https://github.com/flutter/engine/pull/30611)

**Comment by maheshmnj** [comment]
Thanks for the doctor output @wangying3426, But I am not sure I understand the issue. Can you please share a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the above exception?

**Comment by maheshmnj** [comment]
Looks like this was merged.
