### ISSUE TITLE
[Desktop][Windows]: flutter run throws `Target kernel_snapshot failed: Exception` 

### ISSUE THREAD

**Issue by charlesmjohnson0** [flutter/flutter#96011]
## Steps to Reproduce

`flutter run -d windows -v`

## Logs

<details>
<summary>Logs</summary>

```
[  +30 ms] Building Windows application... (completed in 14.5s)
[+3610 ms] Error waiting for a debug connection: The log reader stopped unexpectedly, or never started.
[   +3 ms] Error launching application on Windows.
[   +3 ms] "flutter run" took 18,845ms.
[   +5 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:674:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>


[ +257 ms] ensureAnalyticsSent: 253ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

 `flutter doctor -v`
```
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19044.1415], locale zh-CN)
    • Flutter version 2.8.1 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (2 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.8)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.32002.261
    • Windows 10 SDK version 10.0.22000.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.63.2)
    • VS Code at C:\Users\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.29.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1415]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 90.0.4430.72
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 96.0.1054.62

! Doctor found issues in 2 categories.
```

</details>

**Comment by darshankawar** [comment]
@charlesmjohnson0 
Do you get this error every time consistently while running the said command ?
Can you switch to latest master and see if you get same behavior or not ?
There's a [similar](https://github.com/flutter/flutter/issues/91830) issue open but for mac platform, but just try on master and confirm.

**Comment by charlesmjohnson0** [comment]
@darshankawar 
Do you get this error every time consistently while running the said command ?
**yes,every time**
Can you switch to latest master and see if you get same behavior or not ?
**After I switched the master, error occurred while compiling** 

## Logs

<details>
<summary>Logs</summary>

`flutter channel master`
`flutter upgrade`
`flutter run -d windows -v`

```
[        ]   [+6759 ms] /C:/flutter/.pub-cache/hosted/pub.dartlang.org/platform-3.0.2/lib/src/interface/local_platform.dart(46,19): error G9EFD8EEC: Member not found: 'packageRoot'.
[D:\workspace\project\build\windows\flutter\flutter_assemble.vcxproj]
[        ]   C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066:
“D:\workspace\project\build\windows\CMakeFiles\dff807cde259a938714adfc119b26da2\flutter_windows.dll.rule;D:\workspace\project\build\windows\CMakeFiles\7ddc0b877fe6228c6740866c43e74e84\flutter_assemble.rule” exit，code 1。 [D:\workspace\project\build\windows\flutter\flutter_assemble.vcxproj]
[        ]     2 Errors
[        ] used time 00:00:49.73
[  +27 ms] Building Windows application... (completed in 67.9s)
[   +1 ms] Exception: Build process failed.
[   +1 ms] "flutter run" took 68,593ms.
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:687:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>
```


`flutter doctor -v`
```
[√] Flutter (Channel master, 2.9.0-1.0.pre.244, on Microsoft Windows [Version 10.0.19044.1415], locale zh-CN)
    • Flutter version 2.9.0-1.0.pre.244 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7444ad8da4 (3 hours ago), 2022-01-04 22:00:40 -0800
    • Engine revision a6ce607b13
    • Dart version 2.16.0 (build 2.16.0-134.0.dev)
    • DevTools version 2.9.2

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.8)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.32002.261
    • Windows 10 SDK version 10.0.22000.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.63.2)
    • VS Code at C:\Users\恒联科技\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.32.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1415]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 90.0.4430.72
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 96.0.1054.62

[√] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

**Comment by darshankawar** [comment]
Thanks for the logs. Can you please try running `flutter run -v` and see if it shows us more meaningful log ?

**Comment by charlesmjohnson0** [comment]
Of course, thanks for reply. After change to master channel , I created  new project using `flutter create test` , and running `flutter run -v` successfully ,everything works fine. But my project running `flutter run -v` , error occurred. 



## Logs

<details>
<summary>Logs</summary>

 `flutter run -v`

```
.......

[+2670 ms] /C:/flutter/.pub-cache/hosted/pub.dartlang.org/platform-3.0.2/lib/src/interface/local_platform.dart:46:19: Error: Member not found: 'packageRoot'.
[        ]       io.Platform.packageRoot; // ignore: deprecated_member_use
[        ]                   ^^^^^^^^^^^
[ +306 ms]   [+2979 ms] Found plugin path_provider_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-2.1.0\
[   +4 ms]   [   +4 ms] Found plugin path_provider_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-2.0.3\
[   +6 ms]   [   +6 ms] Found plugin shared_preferences at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-2.0.11\
[   +1 ms]   [   +1 ms] Found plugin shared_preferences_android at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_android-2.0.9\
[   +2 ms]   [   +2 ms] Found plugin shared_preferences_ios at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_ios-2.0.8\
[   +3 ms]   [   +2 ms] Found plugin shared_preferences_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_linux-2.0.2\
[   +2 ms]   [   +2 ms] Found plugin shared_preferences_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-2.0.2\
[   +4 ms]   [   +4 ms] Found plugin shared_preferences_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-2.0.2\
[   +1 ms]   [   +1 ms] Found plugin shared_preferences_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_windows-2.0.2\
[   +5 ms]   [   +5 ms] Found plugin url_launcher at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-6.0.17\
[   +1 ms]   [   +1 ms] Found plugin url_launcher_android at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_android-6.0.13\
[   +2 ms]   [   +1 ms] Found plugin url_launcher_ios at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_ios-6.0.13\
[   +1 ms]   [   +2 ms] Found plugin url_launcher_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-2.0.2\
[   +1 ms]   [   +1 ms] Found plugin url_launcher_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-2.0.2\
[   +3 ms]   [   +3 ms] Found plugin url_launcher_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-2.0.4\
[   +1 ms]   [   +1 ms] Found plugin url_launcher_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_windows-2.0.2\
[  +18 ms]   [  +18 ms] gen_dart_plugin_registrant: Complete
[   +1 ms]   [   +2 ms] kernel_snapshot: Starting due to {}
[   +9 ms]   [   +8 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --target=flutter --no-print-incremental-dependencies -DFLUTTER_WEB_AUTO_DETECT=true -Ddart.vm.profile=false -Ddart.vm.product=false 
--enable-asserts --track-widget-creation --packages D:\workspace\fastway_vpn\.dart_tool\package_config.json --output-dill
D:\workspace\fastway_vpn\.dart_tool\flutter_build\cf8f598f8e45898d6f273d3e1aee6d99\app.dill --depfile
D:\workspace\fastway_vpn\.dart_tool\flutter_build\cf8f598f8e45898d6f273d3e1aee6d99\kernel_snapshot.d D:\workspace\fastway_vpn\.dart_tool\flutter_build\generated_main.dart
[+6758 ms] [+6753 ms] /C:/flutter/.pub-cache/hosted/pub.dartlang.org/platform-3.0.2/lib/src/interface/local_platform.dart(46,19): error G9EFD8EEC: Member not found: 'packageRoot'.
[D:\workspace\fastway_vpn\build\windows\flutter\flutter_assemble.vcxproj]
[   +1 ms]   [   +1 ms]       io.Platform.packageRoot; // ignore: deprecated_member_use
[        ]   [        ]                   ^^^^^^^^^^^
[+3870 ms]   [+3876 ms] Persisting file store
[   +4 ms]   [   +4 ms] Done persisting file store
[  +23 ms]   [  +22 ms] Target kernel_snapshot failed: Exception
[        ]              #0      KernelSnapshot.build (package:flutter_tools/src/build_system/targets/common.dart:241:7)
[        ]              <asynchronous suspension>
[        ]              #1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:839:9)
[        ]              <asynchronous suspension>
[        ]              #2      Future.wait.<anonymous closure> (dart:async/future.dart:473:21)
[        ]              <asynchronous suspension>
[        ]              #3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:777:32)
[        ]              <asynchronous suspension>
[        ]              #4      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:606:16)
[        ]              <asynchronous suspension>
[        ]              #5      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:317:32)
[        ]              <asynchronous suspension>
[        ]              #6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
[        ]              <asynchronous suspension>
[        ]              #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]              <asynchronous suspension>
[        ]              #8      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
[        ]              <asynchronous suspension>
[        ]              #9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
[        ]              <asynchronous suspension>
[        ]              #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]              <asynchronous suspension>
[        ]              #11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
[        ]              <asynchronous suspension>
[        ]              #12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
[        ]              <asynchronous suspension>
[        ]              #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]              <asynchronous suspension>
[        ]              #14     main (package:flutter_tools/executable.dart:94:3)
[        ]              <asynchronous suspension>
[        ]   [  +10 ms] "flutter assemble" took 14,258ms.
[   +4 ms]   [   +5 ms] 
[        ]              #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
[        ]              #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:334:7)
[        ]              <asynchronous suspension>
[        ]              #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
[        ]              <asynchronous suspension>
[        ]              #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]              <asynchronous suspension>
[        ]              #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
[        ]              <asynchronous suspension>
[        ]              #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
[        ]              <asynchronous suspension>
[        ]              #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]              <asynchronous suspension>
[        ]              #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
[        ]              <asynchronous suspension>
[        ]              #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
[        ]              <asynchronous suspension>
[        ]              #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]              <asynchronous suspension>
[        ]              #10     main (package:flutter_tools/executable.dart:94:3)
[        ]              <asynchronous suspension>
[ +261 ms]   [ +265 ms] ensureAnalyticsSent: 264ms
[   +1 ms]   [   +3 ms] Running shutdown hooks
[        ]   [        ] Shutdown hooks complete
[        ]   [        ] exiting with code 1
[  +57 ms] C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066:
“D:\workspace\fastway_vpn\build\windows\CMakeFiles\dff807cde259a938714adfc119b26da2\flutter_windows.dll.rule;D:\workspace\fastway_vpn\build\windows\CMakeFiles\7ddc0b877fe6228c6740866c43e74e84\flutter_assemble.rule” exit code 1。 [D:\workspace\fastway_vpn\build\windows\flutter\flutter_assemble.vcxproj]

......

[        ]   [+6753 ms] /C:/flutter/.pub-cache/hosted/pub.dartlang.org/platform-3.0.2/lib/src/interface/local_platform.dart(46,19): error G9EFD8EEC: Member not found: 'packageRoot'.
[D:\workspace\fastway_vpn\build\windows\flutter\flutter_assemble.vcxproj]
[        ]   C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066:
“D:\workspace\fastway_vpn\build\windows\CMakeFiles\dff807cde259a938714adfc119b26da2\flutter_windows.dll.rule;D:\workspace\fastway_vpn\build\windows\CMakeFiles\7ddc0b877fe6228c6740866c43e74e84\flutter_assemble.rule” exit code 1。 [D:\workspace\fastway_vpn\build\windows\flutter\flutter_assemble.vcxproj]
[   +1 ms]     5 warning
[        ]     2 errors
[        ] used times 00:00:26.97
[  +16 ms] Building Windows application... (completed in 29.1s)
[        ] Exception: Build process failed.
[   +1 ms] "flutter run" took 44,668ms.
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:687:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>


[ +259 ms] ensureAnalyticsSent: 256ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

 `flutter doctor -v` 

```
[√] Flutter (Channel master, 2.9.0-1.0.pre.268, on Microsoft Windows [Version 10.0.19044.1415], locale zh-CN)
    • Flutter version 2.9.0-1.0.pre.268 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bc54c2fdfe (2 hours ago), 2022-01-07 01:55:11 -0800
    • Engine revision 594238c308
    • Dart version 2.16.0 (build 2.16.0-144.0.dev)
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.8)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.32002.261
    • Windows 10 SDK version 10.0.22000.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.63.2)
    • VS Code at C:\Users\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.32.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1415]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 90.0.4430.72
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 96.0.1054.62

[√] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

**Comment by darshankawar** [comment]
Thanks for the logs. I tried running a sample windows app on Windows 10, but didn't get such exception.

From the log, it's failing with below 2 errors throwing `Target kernel_snapshot failed: Exception` eventually:

```
[+6753 ms] /C:/flutter/.pub-cache/hosted/pub.dartlang.org/platform-3.0.2/lib/src/interface/local_platform.dart(46,19): error G9EFD8EEC: Member not found: 'packageRoot'.
[D:\workspace\fastway_vpn\build\windows\flutter\flutter_assemble.vcxproj]
[        ]   C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066:
“D:\workspace\fastway_vpn\build\windows\CMakeFiles\dff807cde259a938714adfc119b26da2\flutter_windows.dll.rule;D:\workspace\fastway_vpn\build\windows\CMakeFiles\7ddc0b877fe6228c6740866c43e74e84\flutter_assemble.rule” exit code 1。 [D:\workspace\fastway_vpn\build\windows\flutter\flutter_assemble.vcxproj]
[   +1 ms]     5 warning
[        ]     2 errors
[        ] used times 00:00:26.97
[  +16 ms] Building Windows application... (completed in 29.1s)
[        ] Exception: Build process failed.
```

**Comment by stuartmorgan** [comment]
The kernel_snapshot failure is just the tool failure that results from the Dart compilation failures that are reported in the log you posted:

> [+2670 ms] /C:/flutter/.pub-cache/hosted/pub.dartlang.org/platform-3.0.2/lib/src/interface/local_platform.dart:46:19: Error: Member not found: 'packageRoot'.
> [        ]       io.Platform.packageRoot; // ignore: deprecated_member_use

Your version of `package` is too old for the version of Flutter you are using; see https://pub.dev/packages/platform/changelog.

**Comment by stuartmorgan** [comment]
It's not clear to me whether this issue is currently intended to track the original crash on launch, or the build failure. If it's the latter, it should be closed as it's just the project not being updated correctly to run on master. If it's the former, it should be renamed.

(@darshankawar For future reference: "flutter run throws Target kernel_snapshot failed: Exception" isn't a good title for an issue, because it's equivalent to "Dart code doesn't compile", which could be anything.)

**Comment by darshankawar** [comment]
> Your version of `package` is too old for the version of Flutter you are using; see https://pub.dev/packages/platform/changelog.

@charlesmjohnson0 Upgrade the package to latest and try again to check if you still get the error or not.

**Comment by charlesmjohnson0** [comment]
After updating the platform version, there is no `packageRoot` error, but still can't debug.
By the way, the project was created on macos .
## Logs

<details>
<summary>Logs</summary>



```

[        ]     0 error
[   +1 ms] used time 00:00:46.87
[  +30 ms] Building Windows application... (completed in 48.3s)
[+7412 ms] Error waiting for a debug connection: The log reader stopped unexpectedly, or never started.
[   +1 ms] Error launching application on Windows.
[   +2 ms] "flutter run" took 56,428ms.
[   +5 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:687:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>


[ +267 ms] ensureAnalyticsSent: 263ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

 `flutter doctor -v` 

```
[√] Flutter (Channel master, 2.9.0-1.0.pre.268, on Microsoft Windows [Version 10.0.19044.1415], locale zh-CN)
    • Flutter version 2.9.0-1.0.pre.268 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bc54c2fdfe (11 days ago), 2022-01-07 01:55:11 -0800
    • Engine revision 594238c308
    • Dart version 2.16.0 (build 2.16.0-144.0.dev)
    • DevTools version 2.9.2
    • PATH = C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\nodejs\;C:\Program Files\CMake\bin;C:\Program
      Files\WireGuard\;C:\Program Files\Git\cmd;C:\Users\AppData\Local\Microsoft\WindowsApps;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.2\bin;;C:\Users\AppData\Local\Programs\Microsoft VS
      Code\bin;C:\Users\AppData\Roaming\npm;C:\flutter\bin;;C:\flutter\bin\mingit\cmd

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.8)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.32002.261
    • Windows 10 SDK version 10.0.22000.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.63.2)
    • VS Code at C:\Users\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.32.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1415]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 96.0.4664.110
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 97.0.1072.55

[√] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

**Comment by darshankawar** [comment]
@charlesmjohnson0 
Per your above comment that the project was created on mac, I believe you are hitting https://github.com/flutter/flutter/issues/91830, so please follow-up in it for further updates.
Closing this as a duplicate.
