### ISSUE TITLE
Test key simulator doesn't support exclamation marks

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#96022]
When I try to press the exclamation logical keyboard key using `WidgetTester`, I get the following error:

```
Error: 'package:flutter_test/src/event_simulation.dart': Failed assertion: line 243 pos 12: 'result != null': Physical key for LogicalKeyboardKey#00021(keyId: "0x00000021", keyLabel: "!", debugName: "Exclamation") not found in macos physical key map
```

Flutter version:
```
Flutter 2.8.1 • channel stable • git@github.com:flutter/flutter.git
Framework • revision 77d935af4d (2 weeks ago) • 2021-12-16 08:37:33 -0800
Engine • revision 890a5fca2e
Tools • Dart 2.15.1
```

**Comment by matthew-carroll** [comment]
CC @justinmc @gspencergoog

**Comment by maheshmnj** [comment]
Hi @matthew-carroll, Thanks for filing the issue. Can you please share a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) to better address the issue.

Thanks

**Comment by matthew-carroll** [comment]
Here's repro code:

```dart
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets("Can't type !", (tester) async {
    await tester.sendKeyDownEvent(LogicalKeyboardKey.exclamation, platform: "macos");
  });
}
```

**Comment by maheshmnj** [comment]
Thanks for the sample code @matthew-carroll, I am able to reproduce the same exception on both stable and the master channel. The tests are only failing when simulating key events which require a shift key e.g *, !, ( etc so simulating the below key events the test fails 
`LogicalKeyboardKey.asterisk`
`LogicalKeyboardKey.exclamation`
`LogicalKeyboardKey.braceLeft`  etc

This seems to be related to https://github.com/flutter/flutter/issues/90167 

<details>
<summary>flutter doctor -v</summary>

```
mahesh@Maheshs-MacBook-Air-M1 counter % flutter test
00:15 +0: Can't type !                                                                           
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
Physical key for LogicalKeyboardKey#00021(keyId: "0x00000021", keyLabel: "!", debugName:
"Exclamation") not found in macos physical key map
'package:flutter_test/src/event_simulation.dart':
Failed assertion: line 243 pos 12: 'result != null'

When the exception was thrown, this was the stack:
#2      KeyEventSimulator._findPhysicalKeyByPlatform (package:flutter_test/src/event_simulation.dart:243:12)
#3      KeyEventSimulator.getKeyData (package:flutter_test/src/event_simulation.dart:260:21)
#4      KeyEventSimulator.simulateKeyDownEvent._simulateByRawEvent.<anonymous closure> (package:flutter_test/src/event_simulation.dart:763:16)
#5      KeyEventSimulator._simulateKeyEventByRawEvent.<anonymous closure> (package:flutter_test/src/event_simulation.dart:685:65)
#6      KeyEventSimulator._simulateKeyEventByRawEvent.<anonymous closure> (package:flutter_test/src/event_simulation.dart:681:39)
#9      TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#10     KeyEventSimulator._simulateKeyEventByRawEvent (package:flutter_test/src/event_simulation.dart:681:27)
#11     KeyEventSimulator.simulateKeyDownEvent._simulateByRawEvent (package:flutter_test/src/event_simulation.dart:761:14)
#12     KeyEventSimulator.simulateKeyDownEvent (package:flutter_test/src/event_simulation.dart:768:16)
#13     simulateKeyDownEvent (package:flutter_test/src/event_simulation.dart:904:28)
#14     WidgetController.sendKeyDownEvent (package:flutter_test/src/controller.dart:1034:12)
#15     main.<anonymous closure> (file:///Users/mahesh/Desktop/counter/test/widget_test.dart:6:18)
#16     main.<anonymous closure> (file:///Users/mahesh/Desktop/counter/test/widget_test.dart:5:31)
#17     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:170:29)
<asynchronous suspension>
<asynchronous suspension>
(elided 5 frames from class _AssertionError, dart:async, and package:stack_trace)

The test description was:
  Can't type !
════════════════════════════════════════════════════════════════════════════════════════════════════
00:15 +0 -1: Can't type ! [E]                                                                    
  Test failed. See exception logs above.
  The test description was: Can't type !
  
00:15 +0 -1: Some tests failed.
``` 
</details>

**Comment by justinmc** [comment]
@dkwingsmt Is this related to your keyboard work?

**Comment by dkwingsmt** [comment]
This is behaving as designed, because there is no "!" key on the keyboard, but only Shift-Digit1. You should dispatch a "ShiftLeft down, Digit1 down, Digit1 up, ShiftLeft up".

**Comment by matthew-carroll** [comment]
@dkwingsmt if this is intended behavior, then how are developers expected to input arbitrary characters when testing keyboard input?

Unless I'm missing some other set of Flutter test APIs, the only thing that I can think of is that every app will need to maintain their own mapping that connects every logical key to its physical key + shift status, per keyboard type, and then use that to construct the "intended" key event.

If that's the intended behavior, it creates identical work for every app, forces app developers to educate themselves on the various keyboard configurations, and it forces them to figure out how the test system utilizes key events. I think that's a pretty strong argument that Flutter should not expect developers to interact with keyboards in this manner within their tests. I think that this is probably disincentivizing testing, rather than promoting it.

Here's a test tool in Super Editor where we need to allow our users to enter arbitrary text into the field:
https://github.com/superlistapp/super_editor/blob/main/super_editor/lib/src/infrastructure/super_textfield/_test_tools.dart#L44

That method will blow up if the user tries to type any shift-based character.

It would be nice if Flutter didn't require each developer to know every character that requires shift to be pressed. However, I went ahead and wrote all of them down in the aforementioned tool.

What I didn't map out was the relationship between every logical key and its associated shift-based value. That's another mapping that it sure would be nice if Flutter handled for us.

Can Flutter introduce APIs that represent the way that app developers think about keyboard input, rather than APIs that strictly adhere to internal Flutter details? I think that would be much more valuable when we're talking about top-level testing APIs.

---

On a related node, is there a reason that the [`sendKeyDownEvent()`](https://api.flutter.dev/flutter/flutter_test/WidgetController/sendKeyDownEvent.html) method supports a `character` argument, but [`sendKeyEvent()`](https://api.flutter.dev/flutter/flutter_test/WidgetController/sendKeyEvent.html) doesn't?

This API difference requires explicit "down" and "up" events when specifying a `character`, even though those two events constitute a single "key event".

**Comment by matthew-carroll** [comment]
Update: I just merged in a contribution from someone else that went ahead and added that shift mapping for a US English keyboard. Everything in my previous response remains the same, except the Super Editor code now works for US English use-cases.

**Comment by dkwingsmt** [comment]
I think you've mixed "having this feature in production" with "testing this feature".

## Use keyboard events

For how to develop a keyboard feature that deals with characters: The native macOS API provides two kinds of information regarding the character: `characters`, which would be "@" in your example, and `charactersIgnoringModifiers`, which would be "2" in your example. Flutter converts the former to `KeyEvent.character`, and the latter (roughly) to `KeyEvent.logicalKey`. (I'm not that sure with the legacy `RawKeyboard` API but I would assume it's similar; let me know if not.) So you if you want the user to input arbitrary text, append the `KeyEvent.character` value to your state. Or maybe you should checkout the text input API, which also handles IME?

## Test keybaord events

First off, instead of `WidgetController.sendKeyEvent` (and siblings), you might want to check out `simulateKeyDownEvent` (and siblings.) They allow customizing `physicalKey` and `character`. Yes, the `WidgetController.sendKeyEvent` methods are just wraps over them, and it's an oversight that these APIs are not exposed. We should fix it.

Now, if that solves your problem, great. If not, I'll continue explaining.

The mapping between physical keys, logical keys, and characters, is completely arbitrary. It's entirely possible to have a `LogicalKeyboardKey("@")`. Sure, create it on your own, and maybe it will be sent by some embedding.

The problem is, it will never be sent by a macOS embedding. Simulating a keyboard event (for the `RawKeyboard` API) requires converting your key event back to a macOS native key event, sends it to `RawKeyboard`, which then converts it again to `RawKeyEvent` API. But if macOS never sends a `LogicalKeyboardKey("@")` value, what native event can it even be converted to?

(This will be easier to understand once we migrate everything to the `HardwareKeyboard` API, whose framework part knows nothing about the native information.)

Furthermore, what indeed do you want to test? The user can input "@" via a variety of ways:
- macOS, US keyboard, Shift-2.
- macOS, ASERTY keyboard, 2.
- Windows, US keyboard, Shift-2.
- macOS, custom keyboard layout, CapsLock (for random reasons.)

Do you really want to test out all cases? Or do you only care about processing key events where `KeyEvent.character` equals to `"@"`, no matter what their `physicalKey` and `logicalKey` are?

That's why the key event simulation API provides customizing all 3 fields: `logicalKey`, `physicalKey`, and `character`. The latter 2 fields are derived by default for convenience, but you shouldn't assume that the default behavior is all that Flutter assumes.

**Comment by matthew-carroll** [comment]
@dkwingsmt to make sure that I'm not misunderstanding you, can you write an example `WidgetTester` invocation that sends the "@" character in the manner that you think a Flutter developer should use in their tests?

**Comment by dkwingsmt** [comment]
Is this something that might suit you?

```dart
  testWidgets('Test @ on US keybaord', (WidgetTester tester) async {
    const String platform = 'macos';
    final FocusNode focusNode = FocusNode();
    final List<RawKeyEvent> events = <RawKeyEvent>[];
    await tester.pumpWidget(
      RawKeyboardListener(
        focusNode: focusNode,
        autofocus: true,
        onKey: (RawKeyEvent event) {
          events.add(event);
        },
        child: const SizedBox(width: 100, height: 100),
      )
    );
    await simulateKeyDownEvent(LogicalKeyboardKey.shiftLeft, platform: platform);
    await simulateKeyDownEvent(LogicalKeyboardKey.at, physicalKey: PhysicalKeyboardKey.digit2, platform: platform);
    await simulateKeyUpEvent(LogicalKeyboardKey.at, physicalKey: PhysicalKeyboardKey.digit2, platform: platform);
    await simulateKeyUpEvent(LogicalKeyboardKey.shiftLeft, platform: platform);
    expect(events[1].logicalKey, LogicalKeyboardKey.at);
    expect(events[1].character, '@');
  });
```

**Comment by matthew-carroll** [comment]
@dkwingsmt I think that would technically be work-able. 

I think it's worth considering whether Flutter should provide some common keyboard configurations so that app developers don't need to manually connect the "@" character to the "2" key. That level of control might be good at the ground level, but I think it's going to feel out of place in the common case.

In fact, I think it might make sense for Flutter to support the actual use-case that I'm dealing with, which is pressing keys that correspond to arbitrary characters. If that's not something that Flutter wants to offer, then it would be helpful to know where Flutter sees the boundary between the built-in test capabilities vs individual app developer test responsibilities.

One last point, the use of the word "simulate" in these calls makes them seem fundamentally different from existing `WidgetTester` calls, e.g., "sendKeyEvent". Are these calls fundamentally different? If so, please be sure to clearly describe those differences in the API docs for any new methods.

**Comment by dkwingsmt** [comment]
A bit of heads up: I've mostly decided to unify the behavior regarding Shift'ed keys and logical keys. We're changing the behavior on macOS and Linux (and later Web) to align with that on Windows. Generally speaking, the new behavior will be more predictable and intuitive. See below: 

| When pressing physical keys...| on layout | Previous logical keys | New logical keys |
|---|---|---|---|
| 1 | US | `digit1` | `digit1` |
| Shift-1 | US | `shiftLeft + exclamation` | `shiftLeft + digit1` |
| 1 | French | `ampersand` | `digit1` | 
| Shift-1 | French | `shiftLeft + digit1` | `digit1` |
| a | Russian | `ф` | `keyA` |

This means that you will be able to write test for `shiftLeft + digit1` and expect it to work.

This will probably be a breaking change, but I'm still evaluating options.

**Comment by han1548772930** [comment]
I also encountered the same problem on Android phones with buttons
When listening for keyboard events, I am unable to listen for F12 function buttons
But when I press any number key, I can listen to F12
So when I don't press the number keys, I can't listen to buttons like F12
