### ISSUE TITLE
[tool_crash] ProcessException: %1 is not a valid Win32 application. Command: C:\Users\DELL\AppData\Local\Google\Chrome\Application\chrome.exe, OS error code: 193

### ISSUE THREAD

**Issue by Sephoratchangai** [flutter/flutter#96131]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: %1 n’est pas une application Win32 valide.
 Command: C:\Users\DELL\AppData\Local\Google\Chrome\Application\chrome.exe, OS error code: 193
```
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:401:33)
#1      Process.start (dart:io-patch/process_patch.dart:38:20)
#2      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:42:22)
#3      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:691:24)
#4      _run (package:flutter_tools/src/base/error_handling_io.dart:567:20)
#5      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:690:12)
#6      ChromiumLauncher._spawnChromiumProcess (package:flutter_tools/src/web/chrome.dart:256:53)
#7      ChromiumLauncher.launch (package:flutter_tools/src/web/chrome.dart:221:36)
<asynchronous suspension>
#8      ChromiumDevice.startApp (package:flutter_tools/src/web/web_device.dart:134:17)
<asynchronous suspension>
#9      ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:307:9)
<asynchronous suspension>
#10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.8.1, on Microsoft Windows [version 10.0.19043.1415], locale fr-FR)
    • Flutter version 2.8.1 at D:\ProjetApp\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\DELL\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Users\DELL\AppData\Local\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] VS Code (version 1.63.2)
    • VS Code at C:\Users\DELL\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 96.0.4664.110
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 96.0.1054.62

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 77d935af4db863f6abd0b9c31c7e6df2a13de57b

**Comment by SPiercer** [comment]
Please elaborate with us and show us how can we reproduce this error
and show us your code.

**Comment by danagbemava-nc** [comment]
Hi @Sephoratchangai, can you provide the crash log that was written to the project directory? 
It should have a name similar to `flutter_01.log`.

Thank you
