### ISSUE TITLE
MaterialApp.router Null check exception crash by anonymous route 

### ISSUE THREAD

**Issue by rhymelph** [flutter/flutter#96166]
Flutter SDK version : Flutter (Channel stable, 2.8.0, on macOS 12.1 21C52 darwin-arm, locale zh-Hans-CN)

I want to use MaterialApp.router anonymous route ,such as dialog show, it will crash in null check. This is sdk code:
route.dart
```dart
class PlatformRouteInformationProvider extends RouteInformationProvider with WidgetsBindingObserver, ChangeNotifier {
  /// Create a platform route information provider.
  ///
  /// Use the [initialRouteInformation] to set the default route information for this
  /// provider.
  PlatformRouteInformationProvider({
    required RouteInformation initialRouteInformation,
  }) : _value = initialRouteInformation;

  @override
  void routerReportsNewRouteInformation(RouteInformation routeInformation, {required RouteInformationReportingType type}) {
    final bool replace =
      type == RouteInformationReportingType.neglect ||
      (type == RouteInformationReportingType.none &&
       _valueInEngine.location == routeInformation.location);
    SystemNavigator.selectMultiEntryHistory();
    SystemNavigator.routeInformationUpdated(
      location: routeInformation.location!,  //  will crash this
      state: routeInformation.state,
      replace: replace,
    );
    _value = routeInformation;
    _valueInEngine = routeInformation;
  }
//....
```
crash info:
```
The following _CastError was thrown during a scheduler callback:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      PlatformRouteInformationProvider.routerReportsNewRouteInformation (package:flutter/src/widgets/router.dart:1359:42)
#1      _RouterState._reportRouteInformation (package:flutter/src/widgets/router.dart:538:40)
#2      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
#3      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1090:9)
#4      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#8      _invoke (dart:ui/hooks.dart:150:10)
#9      PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#10     _drawFrame (dart:ui/hooks.dart:114:31)
(elided 3 frames from dart:async)
====================================================================================================
```
My idea is edit this code:
```dart

class PlatformRouteInformationProvider extends RouteInformationProvider with WidgetsBindingObserver, ChangeNotifier {
  /// Create a platform route information provider.
  ///
  /// Use the [initialRouteInformation] to set the default route information for this
  /// provider.
  PlatformRouteInformationProvider({
    required RouteInformation initialRouteInformation,
  }) : _value = initialRouteInformation;

  @override
  void routerReportsNewRouteInformation(RouteInformation routeInformation, {required RouteInformationReportingType type}) {
    final bool replace =
      type == RouteInformationReportingType.neglect ||
      (type == RouteInformationReportingType.none &&
       _valueInEngine.location == routeInformation.location);
    SystemNavigator.selectMultiEntryHistory();
// edit start
    if(routeInformation.location!= null){
    SystemNavigator.routeInformationUpdated(
      location: routeInformation.location!
      state: routeInformation.state,
      replace: replace,
    );
   }
// edit end
    _value = routeInformation;
    _valueInEngine = routeInformation;
  }
//....
```
and then , [RouteSettings] There can indeed be empty cases.
router.dart
```dart
/// Data that might be useful in constructing a [Route].
@immutable
class RouteSettings {
  /// Creates data used to construct routes.
  const RouteSettings({
    this.name,
    this.arguments,
  });

  /// Creates a copy of this route settings object with the given fields
  /// replaced with the new values.
  RouteSettings copyWith({
    String? name,
    Object? arguments,
  }) {
    return RouteSettings(
      name: name ?? this.name,
      arguments: arguments ?? this.arguments,
    );
  }

  /// The name of the route (e.g., "/settings").
  /// 👇👇👇👇👇👇👇👇👇👇👇👇👇👇  here
  /// If null, the route is anonymous.  
  final String? name;

  /// The arguments passed to this route.
  ///
  /// May be used when building the route, e.g. in [Navigator.onGenerateRoute].
  final Object? arguments;

  @override
  String toString() => '${objectRuntimeType(this, 'RouteSettings')}("$name", $arguments)';
}
```

**Comment by maheshmnj** [comment]
Hi @rhymelph, Thanks for filing the issue. Can you please share a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the above null exception?

**Comment by rhymelph** [comment]
I try to fix my error,and add this code in my information parser, issues solving, @maheshmnj thanks for your reply.
```dart
  @override
  RouteInformation? restoreRouteInformation(Page<dynamic> configuration) {
    if (configuration.name == null) return null;
    return RouteInformation(
        location: configuration.name, state: configuration.arguments);
  }
```
