### ISSUE TITLE
Calling localToGlobal for a RenderBox inside ListView with padding yields wrong and inconsistent results

### ISSUE THREAD

**Issue by saibotma** [flutter/flutter#96171]
## Steps to Reproduce

1. Execute `flutter run` on the code sample
2. Recognize that the vertical padding of the `ListView` is 56 and that the sticky header should also respect the padding and stick at a top offset of 56.
3. Scroll down then scroll up multiple times with different speeds and watch the sticky header glitching.
4. Remove padding from `ListView` and notice that the glitch disappears.
5. Uncomment code below TODO at line 71 to see that the sticky header implementation works flawlessly with a second header.

**Expected results:**
`localToGlobal` `dy` should always be 0.0 when scrolled to top.

**Actual results:** 
`localToGlobal` `dy` is never 0.0 when scrolled to top, and it differs from scroll to scroll how close to 0.0 it gets.
This causes the sticky header to glitch.

See the video and example console logs for clarification:
https://user-images.githubusercontent.com/26022902/148198873-b9e260ba-2daa-46eb-84e0-1686ffd6bcf9.mov

```
flutter: -252.0
flutter: -254.0
flutter: -255.0
flutter: -252.0
flutter: -228.0
flutter: -119.0
flutter: -56.0
```

```
flutter: -115.0
flutter: -114.0
flutter: -103.0
flutter: -78.0
flutter: -56.0
flutter: -44.0
flutter: -6.0
```

```
flutter: -137.0
flutter: -113.0
flutter: -79.0
flutter: -56.0
flutter: -43.0
flutter: -19.0
```

<details>
<summary>Code sample</summary>

```dart
import 'dart:math';

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    const padding = EdgeInsets.symmetric(vertical: 56);
    return MaterialApp(
      home: Scaffold(
        body: ListView(
          // TODO: Remove the padding and see that it does not glitch anymore.
          padding: padding,
          children: [
            StickyHeader(
              stickOffset: padding.top,
              header: Container(height: 56, color: Colors.orange.withOpacity(0.5)),
              content: Column(
                children: const [
                  SizedBox(height: 200, child: Placeholder()),
                  SizedBox(height: 200, child: Placeholder()),
                  SizedBox(height: 200, child: Placeholder()),
                  SizedBox(height: 200, child: Placeholder()),
                ],
              ),
            ),
            // TODO: Uncomment this to see that the sticky header effect works correctly.
            /*
            StickyHeader(
              stickOffset: padding.top,
              header: Container(height: 56, color: Colors.orange.withOpacity(0.5)),
              content: Column(
                children: const [
                  SizedBox(height: 200, child: Placeholder()),
                  SizedBox(height: 200, child: Placeholder()),
                  SizedBox(height: 200, child: Placeholder()),
                  SizedBox(height: 200, child: Placeholder()),
                ],
              ),
            )*/
          ],
        ),
      ),
    );
  }
}

class StickyHeader extends MultiChildRenderObjectWidget {
  final Widget header;
  final Widget content;
  final double stickOffset;

  StickyHeader({
    Key? key,
    required this.header,
    required this.content,
    this.stickOffset = 0,
  }) : super(
          key: key,
          children: [content, header],
        );

  @override
  RenderStickyHeader createRenderObject(BuildContext context) {
    final scrollPosition = Scrollable.of(context)!.position;
    return RenderStickyHeader(stickOffset: stickOffset, scrollPosition: scrollPosition);
  }

  @override
  void updateRenderObject(BuildContext context, RenderStickyHeader renderObject) {
    final scrollPosition = Scrollable.of(context)!.position;
    renderObject.scrollPosition = scrollPosition;
  }
}

class RenderStickyHeader extends RenderBox
    with
        ContainerRenderObjectMixin<RenderBox, MultiChildLayoutParentData>,
        RenderBoxContainerDefaultsMixin<RenderBox, MultiChildLayoutParentData> {
  final double stickOffset;

  ScrollPosition _scrollPosition;

  RenderStickyHeader({
    required ScrollPosition scrollPosition,
    this.stickOffset = 0.0,
    RenderBox? header,
    RenderBox? content,
  }) : _scrollPosition = scrollPosition {
    if (content != null) add(content);
    if (header != null) add(header);
  }

  set scrollPosition(ScrollPosition newValue) {
    if (_scrollPosition == newValue) {
      return;
    }
    final ScrollPosition oldValue = _scrollPosition;
    _scrollPosition = newValue;
    markNeedsLayout();
    if (attached) {
      oldValue.removeListener(markNeedsLayout);
      newValue.addListener(markNeedsLayout);
    }
  }

  @override
  void attach(PipelineOwner owner) {
    super.attach(owner);
    _scrollPosition.addListener(markNeedsLayout);
  }

  @override
  void detach() {
    _scrollPosition.removeListener(markNeedsLayout);
    super.detach();
  }

  // short-hand to access the child RenderObjects
  RenderBox get _headerBox => lastChild!;

  RenderBox get _contentBox => firstChild!;

  @override
  void performLayout() {
    // layout both header and content widget
    final childConstraints = constraints.loosen();
    _headerBox.layout(childConstraints, parentUsesSize: true);
    _contentBox.layout(childConstraints, parentUsesSize: true);

    final headerHeight = _headerBox.size.height;
    final contentHeight = _contentBox.size.height;

    // determine size of ourselves based on content widget
    final width = max(constraints.minWidth, _contentBox.size.width);
    final height = max(constraints.minHeight, headerHeight + contentHeight);
    size = Size(width, height);

    // place content underneath header
    final contentParentData = _contentBox.parentData! as MultiChildLayoutParentData;
    contentParentData.offset = Offset(0.0, headerHeight);

    final double headerOffset = determineHeaderOffset(stickOffset);
    final double maxOffset = height - headerHeight;

    // TODO: Scroll down then scroll up multiple times.
    // The value varies and it never reaches 0.0 as expected.
    print("$headerOffset");

    final headerParentData = _headerBox.parentData! as MultiChildLayoutParentData;
    headerParentData.offset = Offset(0.0, max(0, min(-headerOffset, maxOffset)));
  }

  double determineHeaderOffset(double padding) {
    final scrollBox = _scrollPosition.context.notificationContext!.findRenderObject();
    if (scrollBox?.attached ?? false) {
      try {
        return localToGlobal(Offset(0, -padding), ancestor: scrollBox).dy;
      } catch (e) {
        // ignore and fall-through and return 0.0
      }
    }
    return 0.0;
  }

  @override
  void setupParentData(RenderObject child) {
    super.setupParentData(child);
    if (child.parentData is! MultiChildLayoutParentData) {
      child.parentData = MultiChildLayoutParentData();
    }
  }

  @override
  double computeMinIntrinsicWidth(double height) {
    return _contentBox.getMinIntrinsicWidth(height);
  }

  @override
  double computeMaxIntrinsicWidth(double height) {
    return _contentBox.getMaxIntrinsicWidth(height);
  }

  @override
  double computeMinIntrinsicHeight(double width) {
    return _headerBox.getMinIntrinsicHeight(width) + _contentBox.getMinIntrinsicHeight(width);
  }

  @override
  double computeMaxIntrinsicHeight(double width) {
    return _headerBox.getMaxIntrinsicHeight(width) + _contentBox.getMaxIntrinsicHeight(width);
  }

  @override
  double? computeDistanceToActualBaseline(TextBaseline baseline) {
    return defaultComputeDistanceToHighestActualBaseline(baseline);
  }

  @override
  bool hitTestChildren(HitTestResult result, {required Offset position}) {
    return defaultHitTestChildren(result as BoxHitTestResult, position: position);
  }

  @override
  bool get isRepaintBoundary => true;

  @override
  void paint(PaintingContext context, Offset offset) {
    context.pushClipRect(false, offset, Offset.zero & size, defaultPaint);
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6.1 20G224 darwin-x64, locale en-DE)
    • Flutter version 2.8.1 at /Users/tobias/Documents/Dev/Tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/tobias/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Users/tobias/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7784292/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Android Studio (version 4.2)
    • Android Studio at /Users/tobias/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/tobias/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7784292/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.3)
    • IntelliJ at /Users/tobias/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-1/212.5457.46/IntelliJ IDEA.app
    • Flutter plugin version 62.0.3
    • Dart plugin version 212.5632

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.6.1 20G224 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 96.0.4664.110

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @saibotma, I can reproduce the glitch, I do, however, have a question. 

When I remove the padding, the glitch does disappear, however, the offset never gets to 0.0, it always ends at `-56.0`, is this expected?

**Comment by saibotma** [comment]
There was a small error in the example code which did not update the render object when the `stickOffset` changed. I fixed it. Please take another look.

**Comment by danagbemava-nc** [comment]
Hi @saibotma, I also noticed one other thing, if the padding is not set to zero, and I add in step 5, the glitch of the first sticky header is still visible. 
Is this within your expectations?

**Comment by saibotma** [comment]
> Hi @saibotma, I also noticed one other thing, if the padding is not set to zero, and I add in step 5, the glitch of the first sticky header is still visible. 
> Is this within your expectations? 

Yes, this is expected and even makes the issue more clear.

**Comment by danagbemava-nc** [comment]
The glitch can be reproduced on both stable and master. It looks like it only occurs when using the trackpad to scroll. It looked fine when using the drag scroll, however, the value rarely reached 0.0 even though it was at the top. 

Leaving this for further insights from the team. 

<details>
<summary>videos</summary>

`padding: 56`
| trackpad scroll | drag |
| -- | -- |
| <video src="https://user-images.githubusercontent.com/88313112/148922075-51ad26f2-73a2-4d05-9cb2-2923691463be.mov" /> | <video src="https://user-images.githubusercontent.com/88313112/148922312-63985ff2-dd02-4779-893e-53fcc91eac15.mov" />


`padding: 0`
| trackpad scroll | drag | 
| -- | -- | 
| <video src="https://user-images.githubusercontent.com/88313112/148922556-90ec1d5f-d8ff-498b-9c90-b898bcf82e5f.mov" /> | <video src="https://user-images.githubusercontent.com/88313112/148922728-1f4c2fc3-93e6-4335-b6fd-d8f08cfbd3cb.mov" /> |


</details>

<details>
<summary>code sample</summary>

```dart
import 'dart:math';

import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

class MyCustomScrollBehavior extends MaterialScrollBehavior {
  // Override behavior methods and getters like dragDevices
  @override
  Set<PointerDeviceKind> get dragDevices => {
        PointerDeviceKind.touch,
        PointerDeviceKind.mouse,
        // etc.
      };
}

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    // TODO: Set padding to zero and see that it does not glitch anymore.
    const padding = EdgeInsets.symmetric(vertical: 56);
    return MaterialApp(
      scrollBehavior: MyCustomScrollBehavior(),
      home: Scaffold(
        body: ListView(
          padding: padding,
          children: [
            StickyHeader(
              stickOffset: padding.top,
              header:
                  Container(height: 56, color: Colors.orange.withOpacity(0.5)),
              content: Column(
                children: const [
                  SizedBox(height: 200, child: Placeholder()),
                  SizedBox(height: 200, child: Placeholder()),
                  SizedBox(height: 200, child: Placeholder()),
                  SizedBox(height: 200, child: Placeholder()),
                ],
              ),
            ),
            // TODO: Uncomment this to see that the sticky header effect works correctly.

            // StickyHeader(
            //   stickOffset: padding.top,
            //   header:
            //       Container(height: 56, color: Colors.orange.withOpacity(0.5)),
            //   content: Column(
            //     children: const [
            //       SizedBox(height: 200, child: Placeholder()),
            //       SizedBox(height: 200, child: Placeholder()),
            //       SizedBox(height: 200, child: Placeholder()),
            //       SizedBox(height: 200, child: Placeholder()),
            //     ],
            //   ),
            // )
          ],
        ),
      ),
    );
  }
}

class StickyHeader extends MultiChildRenderObjectWidget {
  final Widget header;
  final Widget content;
  final double stickOffset;

  StickyHeader({
    Key? key,
    required this.header,
    required this.content,
    this.stickOffset = 0,
  }) : super(
          key: key,
          children: [content, header],
        );

  @override
  RenderStickyHeader createRenderObject(BuildContext context) {
    final scrollPosition = Scrollable.of(context)!.position;
    return RenderStickyHeader(
        stickOffset: stickOffset, scrollPosition: scrollPosition);
  }

  @override
  void updateRenderObject(
      BuildContext context, RenderStickyHeader renderObject) {
    final scrollPosition = Scrollable.of(context)!.position;
    renderObject
      ..scrollPosition = scrollPosition
      ..stickOffset = stickOffset;
  }
}

class RenderStickyHeader extends RenderBox
    with
        ContainerRenderObjectMixin<RenderBox, MultiChildLayoutParentData>,
        RenderBoxContainerDefaultsMixin<RenderBox, MultiChildLayoutParentData> {
  double _stickOffset;
  ScrollPosition _scrollPosition;

  RenderStickyHeader({
    required ScrollPosition scrollPosition,
    double stickOffset = 0.0,
    RenderBox? header,
    RenderBox? content,
  })  : _stickOffset = stickOffset,
        _scrollPosition = scrollPosition {
    if (content != null) add(content);
    if (header != null) add(header);
  }

  set stickOffset(double value) {
    if (value == _stickOffset) {
      return;
    }
    _stickOffset = value;
    markNeedsLayout();
  }

  set scrollPosition(ScrollPosition newValue) {
    if (_scrollPosition == newValue) {
      return;
    }
    final ScrollPosition oldValue = _scrollPosition;
    _scrollPosition = newValue;
    markNeedsLayout();
    if (attached) {
      oldValue.removeListener(markNeedsLayout);
      newValue.addListener(markNeedsLayout);
    }
  }

  @override
  void attach(PipelineOwner owner) {
    super.attach(owner);
    _scrollPosition.addListener(markNeedsLayout);
  }

  @override
  void detach() {
    _scrollPosition.removeListener(markNeedsLayout);
    super.detach();
  }

  // short-hand to access the child RenderObjects
  RenderBox get _headerBox => lastChild!;

  RenderBox get _contentBox => firstChild!;

  @override
  void performLayout() {
    // layout both header and content widget
    final childConstraints = constraints.loosen();
    _headerBox.layout(childConstraints, parentUsesSize: true);
    _contentBox.layout(childConstraints, parentUsesSize: true);

    final headerHeight = _headerBox.size.height;
    final contentHeight = _contentBox.size.height;

    // determine size of ourselves based on content widget
    final width = max(constraints.minWidth, _contentBox.size.width);
    final height = max(constraints.minHeight, headerHeight + contentHeight);
    size = Size(width, height);

    // place content underneath header
    final contentParentData =
        _contentBox.parentData! as MultiChildLayoutParentData;
    contentParentData.offset = Offset(0.0, headerHeight);

    final double headerOffset = determineHeaderOffset(_stickOffset);
    final double maxOffset = height - headerHeight;

    // TODO: Scroll down then scroll up multiple times.
    // The value varies and it never reaches 0.0 as expected.
    print("$headerOffset");

    final headerParentData =
        _headerBox.parentData! as MultiChildLayoutParentData;
    headerParentData.offset =
        Offset(0.0, max(0, min(-headerOffset, maxOffset)));
  }

  double determineHeaderOffset(double padding) {
    final scrollBox =
        _scrollPosition.context.notificationContext!.findRenderObject();
    if (scrollBox?.attached ?? false) {
      try {
        return localToGlobal(Offset(0, -padding), ancestor: scrollBox).dy;
      } catch (e) {
        // ignore and fall-through and return 0.0
      }
    }
    return 0.0;
  }

  @override
  void setupParentData(RenderObject child) {
    super.setupParentData(child);
    if (child.parentData is! MultiChildLayoutParentData) {
      child.parentData = MultiChildLayoutParentData();
    }
  }

  @override
  double computeMinIntrinsicWidth(double height) {
    return _contentBox.getMinIntrinsicWidth(height);
  }

  @override
  double computeMaxIntrinsicWidth(double height) {
    return _contentBox.getMaxIntrinsicWidth(height);
  }

  @override
  double computeMinIntrinsicHeight(double width) {
    return _headerBox.getMinIntrinsicHeight(width) +
        _contentBox.getMinIntrinsicHeight(width);
  }

  @override
  double computeMaxIntrinsicHeight(double width) {
    return _headerBox.getMaxIntrinsicHeight(width) +
        _contentBox.getMaxIntrinsicHeight(width);
  }

  @override
  double? computeDistanceToActualBaseline(TextBaseline baseline) {
    return defaultComputeDistanceToHighestActualBaseline(baseline);
  }

  @override
  bool hitTestChildren(HitTestResult result, {required Offset position}) {
    return defaultHitTestChildren(result as BoxHitTestResult,
        position: position);
  }

  @override
  bool get isRepaintBoundary => true;

  @override
  void paint(PaintingContext context, Offset offset) {
    context.pushClipRect(false, offset, Offset.zero & size, defaultPaint);
  }
}

```
</details>

<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.8.1 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (4 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:318:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1428:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1863:10)
      #15     runZonedGuarded (dart:async/zone.dart:1851:12)
      #16     runZoned (dart:async/zone.dart:1782:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:197:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:301:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:53:47)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1290:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (3 available)
    • M2007J20CG (mobile) • 5dd3be00 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)     • macos    • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 97.0.4692.71

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel master, 2.9.0-1.0.pre.316, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.9.0-1.0.pre.316 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 79025d4567 (5 hours ago), 2022-01-10 23:40:18 -0500
    • Engine revision b5a9cfd537
    • Dart version 2.16.0 (build 2.16.0-149.0.dev)
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 213.5744.122

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (3 available)
    • M2007J20CG (mobile) • 5dd3be00 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)     • macos    • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 97.0.4692.71

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

<details>
<summary>logs</summary>

`padding: 0`, `trackpad`

```log
Restarted application in 436ms.
flutter: 0.0
flutter: -40.0
flutter: -79.0
flutter: -101.0
flutter: -136.0
flutter: -155.0
flutter: -169.0
flutter: -187.0
flutter: -206.0
flutter: -212.0
flutter: -211.0
flutter: -205.0
flutter: -199.0
flutter: -190.0
flutter: -177.0
flutter: -163.0
flutter: -149.0
flutter: -133.0
flutter: -107.0
flutter: -87.0
flutter: -67.0
flutter: -48.0
flutter: -29.0
flutter: -10.0
flutter: 0.0
```

`padding: 0`, `drag scroll`

```log
Restarted application in 336ms.
flutter: 0.0
flutter: -12.096354166666668
flutter: -46.78385416666667
flutter: -65.35807291666667
flutter: -65.35807291666674
flutter: -175.1215711768075
flutter: -226.25145309335284
flutter: -287.7627682117005
flutter: -285.3973433860644
flutter: -280.82213892164907
flutter: -275.1282533503208
flutter: -269.01415815186556
flutter: -262.9140697652347
flutter: -257.08496788653974
flutter: -251.66895971925075
flutter: -246.73288860052466
flutter: -242.29509419052783
flutter: -238.345645741919
flutter: -234.85756891870844
flutter: -231.79436997556093
flutter: -229.1164486636076
flutter: -226.78360030239017
flutter: -224.7566473660807
flutter: -222.9993734799318
flutter: -221.47857463615767
flutter: -220.164049697135
flutter: -214.0225404042806
flutter: -195.15011569901588
flutter: -166.18527194901588
flutter: -137.76730319901594
flutter: -107.30643244680914
flutter: -77.8436280844553
flutter: -49.3479264457319
flutter: -21.789208985826008
flutter: 0.0
flutter: 4.653169924878341
flutter: 23.051276923651912
flutter: 33.01003933862916
flutter: 37.51534515433911
flutter: 38.57887655877677
flutter: 37.54745644969144
flutter: 35.31314018508162
flutter: 32.459063199071366
flutter: 29.359338476106185
flutter: 26.24682105710931
flutter: 23.261104535046403
flutter: 20.47988028698792
flutter: 17.940157059202086
flutter: 15.653914533140494
flutter: 13.617358751847725
flutter: 11.817149510151296
flutter: 10.23541489605335
flutter: 8.852087165405253
flutter: 7.646449089170381
flutter: 6.598681635960487
flutter: 5.690170468855436
flutter: 4.903687676175062
flutter: 4.223830772309043
flutter: 3.636826227384254
flutter: 3.1303789226813254
flutter: 2.693770226981453
flutter: 2.317603228338098
flutter: 1.9936187304741144
flutter: 1.7146974858788189
flutter: 1.4746551796348715
flutter: 1.268096183486008
flutter: 1.090395016769659
flutter: 0.9375517682723059
flutter: 0.8060894416626021
flutter: 0.6930355480714313
flutter: 0.5958254998855228
flutter: 0.5122341608462421

```

`padding: 56.0`, `trackpad`

```log
Restarted application in 323ms.
flutter: -56.0
flutter: 0.0
flutter: -69.0
flutter: -101.0
flutter: -149.0
flutter: -178.0
flutter: -195.0
flutter: -216.0
flutter: -239.0
flutter: -263.0
flutter: -286.0
flutter: -309.0
flutter: -324.0
flutter: -323.0
flutter: -317.0
flutter: -308.0
flutter: -290.0
flutter: -278.0
flutter: -263.0
flutter: -248.0
flutter: -232.0
flutter: -216.0
flutter: -198.0
flutter: -179.0
flutter: -158.0
flutter: -118.0
flutter: -89.0
flutter: -56.0
flutter: -54.0
flutter: -19.0
flutter: 0.0
flutter: -9.0
flutter: -18.0
flutter: -32.0
flutter: -46.0
flutter: -77.0
flutter: -97.0
flutter: -115.0
flutter: -136.0
flutter: -150.0
flutter: -169.0
flutter: -193.0
flutter: -219.0
flutter: -245.0
flutter: -271.0
flutter: -296.0
flutter: -320.0
flutter: -324.0
flutter: -323.0
flutter: -316.0
flutter: -305.0
flutter: -291.0
flutter: -275.0
flutter: -253.0
flutter: -214.0
flutter: -186.0
flutter: -158.0
flutter: -127.0
flutter: -78.0
flutter: -56.0
flutter: -42.0
```

`padding: 56`, `drag scroll`

```log
Restarted application in 357ms.
flutter: -56.0
flutter: 0.0
flutter: -3.9010416666666643
flutter: -16.51041666666667
flutter: -19.48697916666667
flutter: -28.143229166666668
flutter: -68.20442708333336
flutter: -99.27107888754227
flutter: -105.86679461762257
flutter: -112.2456326808388
flutter: -118.41546477278784
flutter: -124.38277502237985
flutter: -130.15387058089846
flutter: -135.73587316973664
flutter: -141.13464914373583
flutter: -146.35590474161825
flutter: -151.40608316421344
flutter: -156.29049185059324
flutter: -161.01429337874129
flutter: -165.5833170748328
flutter: -170.00236471275696
flutter: -174.27610700692537
flutter: -164.40631534025871
flutter: -144.90240909025871
flutter: -127.64459659025871
flutter: -107.54303409025871
flutter: -88.14459659025871
flutter: -74.37897159025871
flutter: -56.0
flutter: -49.918034090258715
flutter: -35.871159090258715
flutter: -13.718815340258715
flutter: -3.996159090258743
flutter: 12.99735137625214
flutter: 22.67188807387032
flutter: 27.454052729628827
flutter: 29.116578711947568
flutter: 28.850050294515256
flutter: 27.446465194309
flutter: 25.426446611833285
flutter: 23.126724014970932
flutter: 20.75948697730749
flutter: 18.454281395648508
flutter: 16.285605967076478
flutter: 14.291593782067253
flutter: 12.487697152242845
flutter: 10.874923268333447
flutter: 9.445381258992455
flutter: 8.186679520363413
flutter: 7.084069138226155
flutter: 6.121867687363228
flutter: 5.284825288843869
flutter: 4.55846014110967
flutter: 3.9292652760988886
flutter: 3.385102107754136
flutter: 2.9150726697944407
flutter: 2.5094191469608447
flutter: 2.159616310286495
flutter: 1.8581770945113192
flutter: 1.5985117599350431
flutter: 1.3749342608600514
flutter: 1.1825011112002173
flutter: 1.0168963313438795
flutter: 0.8744181005157685
flutter: 0.7518638969572677
flutter: 0.6464489113573606
flutter: 0.5557917892320745
```

</details>

**Comment by saibotma** [comment]
@danagbemava-nc It kind of works with drag scrolling when it is set to iOS physics. However, with Android physics it does not work either.
