### ISSUE TITLE
onPageFinished in Webview not working properly

### ISSUE THREAD

**Issue by bermanapps** [flutter/flutter#96186]
Hi,

I use the callback method 'onPageFinished' to control the visibility of a progress dialer, but the behaviour is not working on android.

This callback method is called three time on Android device, when start page loading and finish page loading, 

Version: - webview_flutter: ^3.0.0

I see it was raised here, and closed:
https://github.com/flutter/flutter/issues/35787

Here is my code:

class _MyHomePageState extends State<MyHomePage> {

  final Completer<WebViewController> _controller =
  Completer<WebViewController>();
  bool isLoading=true;

  @override
  void initState() {
    super.initState();
    if (Platform.isAndroid) {
      WebView.platform = SurfaceAndroidWebView();
    }
  }

  @override
  Widget build(BuildContext context) {

    return SafeArea(
      child: Scaffold(

        body: Stack(
          children: [

          Builder(builder: (BuildContext context) {
            return WebView(
              initialUrl: 'https://google.com/',
              javascriptMode: JavascriptMode.unrestricted,
              onWebViewCreated: (WebViewController webViewController) {
                _controller.complete(webViewController);
              },
              onProgress: (int progress) {
                print('WebView is loading (progress : $progress%)');

              },
              javascriptChannels: <JavascriptChannel>{
                _toasterJavascriptChannel(context),
              },
              navigationDelegate: (NavigationRequest request) {
                if (request.url.startsWith('https://www.youtube.com/')) {
                  print('blocking navigation to $request}');
                  return NavigationDecision.prevent;
                }
                print('allowing navigation to $request');
                return NavigationDecision.navigate;
              },
              onPageStarted: (String url) {
                print('Page started loading: $url');
              },
              onPageFinished: (String url) {
                print('Page finished loading: $url');
                setState(() {
                  isLoading = false;
                });
              },
              gestureNavigationEnabled: true,
              backgroundColor: const Color(0x00000000),
            );
          }),
            isLoading ? Center( child: CircularProgressIndicator(),)
                : Stack(),
          ]
        ),

      ),
    );
  }

  JavascriptChannel _toasterJavascriptChannel(BuildContext context) {
    return JavascriptChannel(
        name: 'Toaster',
        onMessageReceived: (JavascriptMessage message) {
          // ignore: deprecated_member_use
          Scaffold.of(context).showSnackBar(
            SnackBar(content: Text(message.message)),
          );
        });
  }

}

**Comment by danagbemava-nc** [comment]
This is a rather interesting issue. 
It seems to occur for certain websites based on whether or not `navigationDelegate` is defined. 
But on some other sites, regardless of whether or not `navigationDelegate` is defined, `onPageFinished` is called multiple times. `iOS` didn't seem to have this problem. 

I also noticed that in the instances where `onPageFinished` was called twice, it looks like the website was loaded twice. Small excerpt from `log_android_flutter_dev_nav_delegate.txt`

```log
I/flutter ( 4718): WebView is loading (progress : 10%)
I/flutter ( 4718): allowing navigation to NavigationRequest(url: https://flutter.dev/, isForMainFrame: true)
I/flutter ( 4718): +=================================+
I/flutter ( 4718):
I/flutter ( 4718):  [android] onPageFinishCalled
I/flutter ( 4718):
I/flutter ( 4718): +=================================+
I/flutter ( 4718): WebView is loading (progress : 100%)
D/EGL_emulation( 4718): eglMakeCurrent: 0xb400007536eaa450: ver 3 0 (tinfo 0x7750d73080) (first time)
I/flutter ( 4718): WebView is loading (progress : 10%)
I/flutter ( 4718): Page started loading: https://flutter.dev/
I/flutter ( 4718): WebView is loading (progress : 22%)
I/flutter ( 4718): WebView is loading (progress : 70%)
I/flutter ( 4718): WebView is loading (progress : 100%)
I/flutter ( 4718): WebView is loading (progress : 100%)
``` 

Tested with www.google.com and www.flutter.dev

<details>
<summary>logs</summary>

[log_android_flutter_dev_nav_delegate.txt](https://github.com/flutter/flutter/files/7820945/log_android_flutter_dev_nav_delegate.txt)

[log_android_flutter_dev_no_nav_delegate.txt](https://github.com/flutter/flutter/files/7820946/log_android_flutter_dev_no_nav_delegate.txt)

[log_android_google_no_nav_delegate.txt](https://github.com/flutter/flutter/files/7820947/log_android_google_no_nav_delegate.txt)

[log_android_google.txt](https://github.com/flutter/flutter/files/7820948/log_android_google.txt)

[log_ios_flutter_dev.txt](https://github.com/flutter/flutter/files/7820949/log_ios_flutter_dev.txt)

[log_ios_google.txt](https://github.com/flutter/flutter/files/7820950/log_ios_google.txt)

</details>

<details>
<summary>complete code sample</summary>

```dart
import 'dart:async';
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const WebViewExample(),
    );
  }
}

class WebViewExample extends StatefulWidget {
  const WebViewExample({Key? key}) : super(key: key);

  @override
  _WebViewExampleState createState() => _WebViewExampleState();
}

class _WebViewExampleState extends State<WebViewExample> {
  final Completer<WebViewController> _controller =
      Completer<WebViewController>();

  bool isLoading = true;

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Stack(
          children: [
            WebView(
              // TODO: switch between the urls to see the differences
              // initialUrl: 'https://www.google.com',
              initialUrl: 'https://www.flutter.dev',
              javascriptMode: JavascriptMode.unrestricted,
              onWebViewCreated: (WebViewController webViewController) {
                _controller.complete(webViewController);
                print(
                  "+=================================+\n\n [${Platform.operatingSystem}] onWebViewCreated\n\n+=================================+",
                );
              },
              onProgress: (int progress) {
                print('WebView is loading (progress : $progress%)');
              },
              // TODO: uncomment to see the differences for both websites
              navigationDelegate: (NavigationRequest request) {
                print('allowing navigation to $request');
                return NavigationDecision.navigate;
              },
              onPageStarted: (String url) {
                print('Page started loading: $url');
              },
              onPageFinished: (String url) {
                print(
                  "+=================================+\n\n [${Platform.operatingSystem}] onPageFinishCalled\n\n+=================================+",
                );
                setState(() {
                  isLoading = false;
                });
              },
              javascriptChannels: <JavascriptChannel>{
                _toasterJavascriptChannel(context),
              },
            ),
            isLoading
                ? Center(
                    child: CircularProgressIndicator(),
                  )
                : Stack()
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Container(
          color: Colors.orange,
        ),
        onPressed: () {},
      ),
    );
  }

  JavascriptChannel _toasterJavascriptChannel(BuildContext context) {
    return JavascriptChannel(
      name: 'Toaster',
      onMessageReceived: (JavascriptMessage message) {
        // ignore: deprecated_member_use
        Scaffold.of(context).showSnackBar(
          SnackBar(content: Text(message.message)),
        );
      },
    );
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.8.1 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:318:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1428:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1863:10)
      #15     runZonedGuarded (dart:async/zone.dart:1851:12)
      #16     runZoned (dart:async/zone.dart:1782:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:197:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:301:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:53:47)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1290:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12 (API 31) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 96.0.4664.110

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel master, 2.9.0-1.0.pre.256, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.9.0-1.0.pre.256 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 45726a8458 (9 hours ago), 2022-01-05 20:00:17 -0500
    • Engine revision 36eafae59d
    • Dart version 2.16.0 (build 2.16.0-144.0.dev)
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1426:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1861:10)
      #15     runZonedGuarded (dart:async/zone.dart:1849:12)
      #16     runZoned (dart:async/zone.dart:1780:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:205:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:309:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12 (API 31) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 96.0.4664.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>

**Comment by a83988029** [comment]
same problem

**Comment by micaelcid** [comment]
Same!

**Comment by chinloyal** [comment]
Still having this issue on ^4.2.2

```
[log] Page finished
[log] Loading 100%
[log] Loading 10%
[log] Loading 24%
[log] Loading 54%
2
[log] Loading 100%
[log] Page finished
[log] Loading 10%
[log] Page finished
2
[log] Loading 100%
```

**Comment by stuartmorgan** [comment]
It appears that the Android webview has some surprising `onPageFinished` behavior, in particular around redirects. For instance, here's the set of native callbacks for loading `https://google.com` as in the original example:

```
shouldOverrideUrlLoading: https://www.google.com/
onPageFinished: https://www.google.com/
onPageStarted: https://www.google.com/
onPageFinished: https://www.google.com/
onPageFinished: https://www.google.com/
```

That directly corresponds to the confusing set of calls on the Dart side, so this is a WebView issue rather than a plugin issue. I'm guessing that `finished` call before `started` is actually about the redirect from `https://google.com` being "finished" (i.e., it's no longer loading that, and instead loading the redirect target), but for some reason has a misleading URL. (I have no idea why the end is two calls to `finished` rather than one.)

I'm not sure the plugin has enough information to reliably filter out the unexpected calls. If someone is able to identify a robust mechanism for getting output that's more like what we would expect, we can add that, but if we aren't confident that whatever we do is robust it will be arguably worse, because it will destroy information and still not be correct.

**Comment by foxmind1** [comment]
@stuartmorgan this answer could be helpful
https://stackoverflow.com/a/25547544

**Comment by stuartmorgan** [comment]
Describing a workaround that would handle this exact sequence of calls is easy; the hard part is demonstrating that it won't break anything else; that answer unfortunately only does the first part.

**Comment by foxmind1** [comment]
is it possible to expose `shouldOverrideUrlLoading` at the very least?

**Comment by stuartmorgan** [comment]
> is it possible to expose `shouldOverrideUrlLoading` at the very least?

That information is already exposed via `onNavigationRequest`.

**Comment by foxmind1** [comment]
> @stuartmorgan this answer could be helpful https://stackoverflow.com/a/25547544

i can confirm this "solution" doesn't work with every case
