### ISSUE TITLE
[google_sign_in] iOS PlatformException (PlatformException(missing-config, GoogleService-Info.plist file not found, null, null)) after CLI initialization migration

### ISSUE THREAD

**Issue by tr-stan** [flutter/flutter#96248]
I have FirebaseAuth set up in my app with Google Sign In amongst other social login options enabled. I had no problems with siging in and managing users/sessions until I followed the steps in the official flutter firebase docs for migrating to the flutterfire CLI initialization and removing old files such as the `GoogleService-Info.plist` file in the iOS project. The issue I'm facing is only for iOS simulators, not for android.

## Steps to Reproduce

The steps to reproduce this would be to:

1. Follow flutterfire docs instructions on migrating to CLI dart initialization : https://firebase.flutter.dev/docs/overview#initializing-flutterfire
2. Call on the GoogleSignIn().signIn() method

**Expected results:**
I expect to be able to sign in with Google using this package without having the GoogleService-Info.plist in my project, since the firebase docs say it is not longer needed and is backwards compatible.

**Actual results:** 
My function no longer works as it used to, and hits an exception:

```
flutter: error signing in with google: PlatformException(missing-config, GoogleService-Info.plist file not found, null, null)
stack:
#0      StandardMethodCodec.decodeEnvelope
#1      MethodChannel._invokeMethod
<asynchronous suspension>
#2      GoogleSignIn._callMethod
<asynchronous suspension>
#3      GoogleSignIn.signIn.isCanceled (package:google_sign_in/google_sign_in.dart)
<asynchronous suspension>
```
I think this might possibly be because something is not updated with the google_sign_in package to account for the new dart initialization with the flutterfire CLI, such as its looking in the wrong place or for the wrong file now that I'm pulling from the `firebase_options.dart` file and do not have a `GoogleService-Info.plist` file that was manually added to Xcode anymore. I'm pretty stumped because I followed all the migration directions, which say the file is no longer necessary, and I did not get any errors from the flutterfire CLI when I configured my project and added my firebase_options.dart file. I feel like using google_sign_in with firebase_auth is one of the most basic things users of either this package or the firebase suite of packages will want to do, so I don't know if there's just something else I completely missed to make these not work together maybe?
<details>

<summary>Code sample</summary>

A sample of the function that is the source of the PlatformException is:

```dart
  Future<UserCredential> signInWithGoogle() async {
    try {
      // Trigger the authentication flow
      final GoogleSignInAccount googleUser = await GoogleSignIn().signIn();

      // Obtain the auth details from the request
      final GoogleSignInAuthentication googleAuth =
          await googleUser.authentication;

      // Create a new credential
      final oAuthCredential = GoogleAuthProvider.credential(
        accessToken: googleAuth.accessToken,
        idToken: googleAuth.idToken,
      );

      UserCredential userCred;
      // try to link Google credential to current anonymous user
      // if google cred is already linked to another acct, sign in to that acct
      try {
        userCred = await _user.linkWithCredential(oAuthCredential);
      } on FirebaseAuthException catch (e) {
        print(
            'Error linking Google cred to anonymous credential: ${e.message}');
        print('Error code: ${e.code}');
        if (e.code == 'credential-already-in-use') {
          final String userId = _user.uid;
          final FirebaseFunctions cloudFunctions = FirebaseFunctions.instance;
          final HttpsCallable callable =
              cloudFunctions.httpsCallable('deleteAnonymousUser');

          // UserCredential that will be returned at end of function
          userCred =
              await FirebaseAuth.instance.signInWithCredential(oAuthCredential);

          callable.call<String>(userId).catchError((error) {
            print('Error calling `deleteAnonymousUser` from Google sign in.');
            print('Error:$error');
          });
          return userCred;
        }
      } catch (e, s) {
        print('Error signing in returning user:\n$e\n$s');
      }
      return userCred;
    } catch (error, stack) {
      print('error signing in with google: $error\nstack:\n$stack');
      return null;
    }
  }
```

</details>

<details>
  <summary>Logs</summary>

logs from `flutter run --verbose`:
```
[   +4 ms] executing: xcrun simctl launch 9754F6BE-6127-4D71-8DB1-0FD01F41860D com.wordbud.wordbud --enable-dart-profiling
--enable-checked-mode --verify-entry-points --observatory-port=0
[ +244 ms] com.wordbud.wordbud: 27572
[        ] Waiting for observatory port to be available...
[+2550 ms] Observatory URL on device: http://127.0.0.1:51365/QDnCuZpjiHA=/
[  +15 ms] Caching compiled dill
[ +140 ms] Connecting to service protocol: http://127.0.0.1:51365/QDnCuZpjiHA=/
[ +255 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at
http://127.0.0.1:51365/QDnCuZpjiHA=/.
[ +250 ms] DDS is listening at http://127.0.0.1:51373/BxpNe6XiX0Q=/.
[  +73 ms] Successfully connected to service protocol: http://127.0.0.1:51365/QDnCuZpjiHA=/
[  +47 ms] DevFS: Creating new filesystem on the device (null)
[  +30 ms] DevFS: Created new filesystem on the device
(file:///Users/tristan/Library/Developer/CoreSimulator/Devices/9754F6BE-6127-4D71-8DB1-0FD01F41860D/data/Containers/Data/App
lication/31066D9F-F21D-41A2-BA85-F6C6D706A09C/tmp/wordbud1HZDQO/wordbud/)
[   +4 ms] Updating assets
[ +406 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information
see #56466.
[  +12 ms] Syncing files to device iPhone 13...
[   +5 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +7 ms] <- recompile file:///Users/tristan/Wordbud/wordbud/.dart_tool/flutter_build/generated_main.dart
dbe80397-b265-4fb4-bc71-d52ad4c98851
[        ] <- dbe80397-b265-4fb4-bc71-d52ad4c98851
[   +2 ms] flutter: appDocumentDirectory: Directory:
'/Users/tristan/Library/Developer/CoreSimulator/Devices/9754F6BE-6127-4D71-8DB1-0FD01F41860D/data/Containers/Data/Applicatio
n/31066D9F-F21D-41A2-BA85-F6C6D706A09C/Documents'
[ +415 ms] Updating files.
[        ] DevFS: Sync finished
[   +2 ms] Syncing files to device iPhone 13... (completed in 431ms)
[        ] Synced 0.0MB.
[   +4 ms] <- accept
[   +7 ms] Connected to _flutterView/0x7f8722826220.
[   +7 ms] Flutter run key commands.
[   +2 ms] r Hot reload. 🔥🔥🔥
[   +1 ms] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[   +1 ms] An Observatory debugger and profiler on iPhone 13 is available at: http://127.0.0.1:51373/BxpNe6XiX0Q=/
[   +2 ms] The Flutter DevTools debugger and profiler on iPhone 13 is available at:
           http://127.0.0.1:9102?uri=http://127.0.0.1:51373/BxpNe6XiX0Q=/
[+2179 ms] flutter: LineSDK Prepared
[+69125 ms] flutter: error signing in with google: PlatformException(missing-config, GoogleService-Info.plist file not
found, null, null)
                     stack:
                     #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
                     #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
                     <asynchronous suspension>
                     #2      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:242:5)
                     <asynchronous suspension>
                     #3      GoogleSignIn.signIn.isCanceled (package:google_sign_in/google_sign_in.dart)
                     <asynchronous suspension>

```

logs from `flutter analyze`:
```
n/a
```

logs from `flutter doctor -v`:
```
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6 20G165 darwin-x64, locale en)
    • Flutter version 2.8.1 at /Users/tristan/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/tristan/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Users/tristan/Library/Java/JavaVirtualMachines/corretto-11.0.12/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Corretto-11.0.12.7.2 (build 11.0.12+7-LTS)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • 9754F6BE-6127-4D71-8DB1-0FD01F41860D • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • macOS 11.6 20G165 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 97.0.4692.71

• No issues found!
```

</details>

**Comment by SuhwanCha** [comment]
Can you provider your `pubspec.yaml`?
And isn't it only worked for `firebase_auth` or whole firebase libraries?

**Comment by darshankawar** [comment]
@tr-stan 
`google_sign_in` plugin currently doesn't support dart-only initialization and for mean time, you'll need to fallback on manual installation.
See this merged PR in flutterfire repo to indicate the same: https://github.com/FirebaseExtended/flutterfire/pull/7745
Closing this from here, as above should answer your question.

**Comment by tr-stan** [comment]
Hi @darshankawar thank you for the clarification! I saw in one of the linked issues that documentation clarifications are already in the works. 😄
