### ISSUE TITLE
[web] unexpected StackTrace format discrepancy in dart2js

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#96298]
In https://github.com/flutter/engine/pull/30720/files#diff-2a7dc8b44d978299b2050364e7cf364626ef0b4e7e72d25ce33b25df957f3222R65 I have the `CkPicture` class remember the stack trace of the invocation of the `dispose` method. This stack trace is later interpolated into a string.

When running locally (`felt test test/canvaskit/picture_test.dart`), the stack trace gets stringified into this:

```
Error
    at Object.StackTrace_current (http://localhost:36929/test/canvaskit/picture_test.dart.browser_test.dart.js:7075:40)
    at CkPicture_dispose_closure.call$0 (http://localhost:36929/test/canvaskit/picture_test.dart.browser_test.dart.js:39803:47)
    at CkPicture.dispose$0 (http://localhost:36929/test/canvaskit/picture_test.dart.browser_test.dart.js:39743:61)
    at Object.dispose$0$x (http://localhost:36929/test/canvaskit/picture_test.dart.browser_test.dart.js:16382:43)
    at testMain___closure.call$0 (http://localhost:36929/test/canvaskit/picture_test.dart.browser_test.dart.js:43528:9)
    at http://localhost:36929/test/canvaskit/picture_test.dart.browser_test.dart.js:36318:53
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:36929/test/canvaskit/picture_test.dart.browser_test.dart.js:4698:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:36929/test/canvaskit/picture_test.dart.browser_test.dart.js:20184:12)
    at _awaitOnObject_closure.call$1 (http://localhost:36929/test/canvaskit/picture_test.dart.browser_test.dart.js:20172:32)
    at StaticClosure._rootRunUnary (http://localhost:36929/test/canvaskit/picture_test.dart.browser_test.dart.js:5317:18)
```

The same code running on [LUCI](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8825741235332258465/+/u/felt_test:_firefox-unit-linux/stdout) produces this:

```
StackTrace_current@http://localhost:46801/test/canvaskit/picture_test.dart.browser_test.dart.js:7075:40
call$0@http://localhost:46801/test/canvaskit/picture_test.dart.browser_test.dart.js:39711:47
dispose$0@http://localhost:46801/test/canvaskit/picture_test.dart.browser_test.dart.js:39651:61
dispose$0$x@http://localhost:46801/test/canvaskit/picture_test.dart.browser_test.dart.js:16350:43
call$0@http://localhost:46801/test/canvaskit/picture_test.dart.browser_test.dart.js:43436:9
call$0/$async$call$0<@http://localhost:46801/test/canvaskit/picture_test.dart.browser_test.dart.js:36226:53
_wrapJsFunctionForAsync/$protected</<@http://localhost:46801/test/canvaskit/picture_test.dart.browser_test.dart.js:4698:17
call$2@http://localhost:46801/test/canvaskit/picture_test.dart.browser_test.dart.js:20152:12
call$1@http://localhost:46801/test/canvaskit/picture_test.dart.browser_test.dart.js:20140:32
_rootRunUnary@http://localhost:46801/test/canvaskit/picture_test.dart.browser_test.dart.js:5317:18
runUnary$2$2@http://localhost:46801/test/canvaskit/picture_test.dart.browser_test.dart.js:22509:39
handleValue$1@http://localhost:46801/test/canvaskit/picture_test.dart.browser_test.dart.js:20808:31
call$0@http://localhost:46801/test/canvaskit/picture_test.dart.browser_test.dart.js:21241:47
_Future__propagateToListeners@http://localhost:46801/test/canvaskit/picture_test.dart.browser_test.dart.js:4983:93
_completeWithValue$1@http://localhost:46801/test/canvaskit/picture_test.dart.browser_test.dart.js:21077:9
complete$1@http://localhost:46801/test/canvaskit/picture_test.dart.browser_test.dart.js:20120:14
_asyncReturn@http://localhost:46801/test/canvaskit/picture_test.dart.browser_test.dart.js:4671:17
_runSetUps$0/$async$_runSetUps$0<@http://localhost:46801/test/canvaskit/picture_test.dart.browser_test.dart.js:36158:24
_wrapJsFunctionForAsync/$protected</<@http://localhost:46801/test/canvaskit/picture_test.dart.browser_test.dart.js:4698:17
call$2@http://localhost:46801/test/canvaskit/picture_test.dart.browser_test.dart.js:20152:12
call$1@http://localhost:46801/test/canvaskit/picture_test.dart.browser_test.dart.js:20140:32
_rootRunUnary@http://localhost:46801/test/canvaskit/picture_test.dart.browser_test.dart.js:5317:18
runUnary$2$2@http://localhost:46801/test/canvaskit/picture_test.dart.browser_test.dart.js:22509:39
handleValue$1@http://localhost:46801/test/canvaskit/picture_test.dart.browser_test.dart.js:20808:31
call$0@http://localhost:46801/test/canvaskit/picture_test.dart.browser_test.dart.js:21241:47
_Future__propagateToListeners@http://localhost:46801/test/canvaskit/picture_test.dart.browser_test.dart.js:4983:93
call$0@http://localhost:46801/test/canvaskit/picture_test.dart.browser_test.dart.js:21129:9
_rootRun@http://localhost:46801/test/canvaskit/picture_test.dart.browser_test.dart.js:5303:16
run$1$1@http://localhost:46801/test/canvaskit/picture_test.dart.browser_test.dart.js:22501:39
runGuarded$1@http://localhost:46801/test/canvaskit/picture_test.dart.browser_test.dart.js:22433:14
call$0@http://localhost:46801/test/canvaskit/picture_test.dart.browser_test.dart.js:22652:25
_microtaskLoop@http://localhost:46801/test/canvaskit/picture_test.dart.browser_test.dart.js:5036:24
_startMicrotaskLoop@http://localhost:46801/test/canvaskit/picture_test.dart.browser_test.dart.js:5042:11
call$1@http://localhost:46801/test/canvaskit/picture_test.dart.browser_test.dart.js:20024:9
invokeClosure@http://localhost:46801/test/canvaskit/picture_test.dart.browser_test.dart.js:1684:26
convertDartClosureToJS/$function</<@http://localhost:46801/test/canvaskit/picture_test.dart.browser_test.dart.js:1703:18
```

We should find a way to make stack traces consistent and actionable.

**Comment by yjbanov** [comment]
@sigmundch This is another example of a stack trace confusion where it's not clear why we're getting different stack traces in different environments.

**Comment by sigmundch** [comment]
Oh, I forgot to ask you more about it this morning. 

Is LUCI here running Firefox? 

Dart2js simply exposes what the browser gives us, and we purposely wanted to stay away from processing the stacktrace in the client. In fact, my preference would be for DDC to stop processing stack traces too, and instead expose JS stack traces and not try to find the equivalent Dart trace.

The idea would be to then to extract the conversion of stack traces to be done offline/server-side. This is what apps today use for error logging. We also apply a similar technique in our test framework in the Dart SDK, for example: https://dart-ci.appspot.com/log/any/dart2js-minified-linux-d8/16279/language_2/const/switch_test/02 (notice there are 2 stack traces, one in JS the other in Dart)

**Comment by yjbanov** [comment]
Ah, it does run in Firefox! Ok, this explains it.
