### ISSUE TITLE
The following assertion was thrown during paint()

### ISSUE THREAD

**Issue by iNoles** [flutter/flutter#9642]
```
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during paint():
type 'Point' is not a subtype of type 'Offset' of 'offset' where
  Point is from dart:ui
  Offset is from dart:ui
Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new
When the exception was thrown, this was the stack:
#0      TextPainter.paint (package:flutter/src/painting/text_painter.dart:276:36)
#1      BannerPainter.paint (package:flutter/src/widgets/banner.dart:102:18)
#2      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/proxy_box.dart:2068:13)
#3      RenderCustomPaint.paint (package:flutter/src/rendering/proxy_box.dart:2109:7)
#4      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2284:7)
#5      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:117:13)
#6      RenderView.paint (package:flutter/src/rendering/view.dart:148:15)
#7      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2284:7)
#8      PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:97:11)
#9      PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:1116:29)
#10     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding.beginFrame (package:flutter/src/rendering/binding.dart:227:19)
#11     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.beginFrame (package:flutter/src/widgets/binding.dart:354:23)
#12     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:170:5)
#13     BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:645:15)
#14     BindingBase&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:580:9)
The following RenderObject was being processed when the exception was fired:
  RenderCustomPaint#124921072
  creator: CustomPaint ← Banner ← CheckedModeBanner ← WidgetsApp-[GlobalObjectKey
  _MaterialAppState#908934258] ← Theme ← AnimatedTheme ← ScrollConfiguration ← MaterialApp ← [root]
  parentData: <none>
  constraints: BoxConstraints(w=320.0, h=568.0)
  size: Size(320.0, 568.0)
This RenderObject had the following descendants (showing up to depth 5):
  RenderPointerListener#792113853
    RenderAbsorbPointer#212059661
      RenderSemanticsAnnotations#702459010
        _RenderTheatre#476559677
          RenderStack#128764024
════════════════════════════════════════════════════════════════════════════════════════════════════
```

## Flutter Doctor

```
[✓] Flutter (on Mac OS X 10.12.4 16E195, channel master)
    • Flutter at /Users/jonathansteele/flutter
    • Framework revision 2e194d5b44 (20 hours ago), 2017-04-27 10:30:53 -0700
    • Engine revision 3211d2fca2
    • Tools Dart version 1.23.0-dev.11.11

[✓] Host Executable Compatibility
    • Downloaded executables execute on host

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/jonathansteele/Desktop/sdk
    • Platform android-25, build-tools 25.0.2
    • ANDROID_HOME = /Users/jonathansteele/Desktop/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[-] iOS toolchain - develop for iOS devices (Xcode 8.3.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.2, Build version 8E2002
    ✗ Brew not installed; use this to install tools for iOS device development.
      Download brew at http://brew.sh/.

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1.2)
    • Dart plugin version 171.4424
    • Flutter plugin version 13.0

[✓] Connected devices
    • iPhone SE • A5FC79FB-2D37-4C3E-ACC4-3D3ACFE12956 • ios • iOS 10.3 (simulator)
```

**Comment by eseidelGoogle** [comment]
Looks like this was caused by:
https://groups.google.com/forum/#!searchin/flutter-dev/offset%7Csort:relevance/flutter-dev/yKlK6wLqFf8/4HzsvxlzAAAJ

**Comment by eseidelGoogle** [comment]
As part of attempting to reach API stability last week we removed the Point class in favor of the Offset class.  All mentions of Point should now just be Offset as it notes in the above mail.
