### ISSUE TITLE
dart.global.window.CanvasKitInit is not a function

### ISSUE THREAD

**Issue by mkbblr** [flutter/flutter#96463]
This is same as https://github.com/flutter/flutter/issues/79963
Creating new thread as asked in closing comment for the above issue. Also attached is output of `flutter doc -v` and `flutter run -v`. 
[flutter_doc_out.txt](https://github.com/flutter/flutter/files/7845704/flutter_doc_out.txt)
[flutter_run_out.txt](https://github.com/flutter/flutter/files/7845707/flutter_run_out.txt)

**Comment by darshankawar** [comment]
@mkbblr 
So if you run `flutter run -d chrome` from terminal, you see the said exception ? Or are you running from IDE ? If so, is it VSCode ?

**Comment by mkbblr** [comment]
its same in both cases

**Comment by darshankawar** [comment]
@mkbblr 
Does it occur everytime you run `flutter run` ? Is is specific to while running on a device on or web or desktop ?

**Comment by PrithiviRajG** [comment]
@darshankawar I am also getting the same issue. It's coming only when I try to run the app in web but It's running fine in Android emulator. Please let me know if you need more details

**Comment by Adevill20** [comment]
I have the exact same issue. 

**Expected results:**

Application runs in a Chrome / Edge browser

**Actual results:**

Terminal throws the following error

```
TypeError: dart.global.window.CanvasKitInit is not a function
     at [http://localhost:56716/dart_sdk.js:188043:55]()
     at _RootZone.runUnary ([http://localhost:56716/dart_sdk.js:40441:59]())
     at _FutureListener.then.handleValue ([http://localhost:56716/dart_sdk.js:35363:29]())
     at handleValueCallback ([http://localhost:56716/dart_sdk.js:35931:49]())
     at Function._propagateToListeners ([http://localhost:56716/dart_sdk.js:35969:17]())
     at _Future.new.[_completeWithValue] ([http://localhost:56716/dart_sdk.js:35817:23]())
     at async._AsyncCallbackEntry.new.callback ([http://localhost:56716/dart_sdk.js:35838:35]())
     at Object._microtaskLoop ([http://localhost:56716/dart_sdk.js:40708:13]())
     at _startMicrotaskLoop ([http://localhost:56716/dart_sdk.js:40714:13]())
     at [http://localhost:56716/dart_sdk.js:36191:9]()
Application finished.
```

**Flutter docter -v output:**

```
> [√] Flutter (Channel stable, 2.10.1, on Microsoft Windows [Version 10.0.19044.1526], locale en-ZA)
>     • Flutter version 2.10.1 at C:\Users\QW5314\Downloads\flutter\flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision db747aa133 (5 days ago), 2022-02-09 13:57:35 -0600
>     • Engine revision ab46186b24
>     • Dart version 2.16.1
>     • DevTools version 2.9.2
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
>     • Android SDK at C:\Users\QW5314\AppData\Local\Android\sdk
>     • Platform android-32, build-tools 32.1.0-rc1
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
>     • All Android licenses accepted.
> 
> [√] Chrome - develop for the web
>     • CHROME_EXECUTABLE = C:\Program Files\Google\Chrome\Application\chrome.exe
> 
> [√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.6)
>     • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
>     • Visual Studio Community 2022 version 17.0.32126.317
>     • Windows 10 SDK version 10.0.19041.0
> 
> [√] Android Studio (version 2021.1)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
> 
> [√] VS Code, 64-bit edition (version 1.64.2)
>     • VS Code at C:\Program Files\Microsoft VS Code
>     • Flutter extension version 3.34.0
> 
> [√] Connected device (3 available)
>     • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1526]
>     • Chrome (web)      • chrome  • web-javascript • Google Chrome 98.0.4758.82
>     • Edge (web)        • edge    • web-javascript • Microsoft Edge 98.0.1108.50
> 
> [√] HTTP Host Availability
>     • All required HTTP hosts are available
> 
> • No issues found!
```

**Comment by HarrisonKhannah** [comment]
Any updates here?

**Comment by PrithiviRajG** [comment]
On running flutter in web, one flutter JS file is retrieved from unpkg.com which is used by flutter for rendering it seems. In my company unpkg.com was blocked so this file was not loaded and got the error. It got resolved once we are able to unblock that site. please check if the JS file is loaded properly on App startup in web.

**Comment by HarrisonKhannah** [comment]
Ah it is not. Same issue, blocked by the company. Will resolve. Thanks @PrithiviRajG
