### ISSUE TITLE
[tool_crash] ProcessException: No such file or directory Command: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome, OS error code: 2

### ISSUE THREAD

**Issue by TuanVu1905** [flutter/flutter#96515]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: No such file or directory Command: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome, OS error code: 2
```
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:401:33)
#1      Process.start (dart:io-patch/process_patch.dart:38:20)
#2      Chrome._startProcess (package:browser_launcher/src/chrome.dart:145:26)
#3      Chrome.start (package:browser_launcher/src/chrome.dart:137:18)
#4      FlutterResidentDevtoolsHandler._launchDevToolsForDevices (package:flutter_tools/src/resident_devtools_handler.dart:124:24)
#5      FlutterResidentDevtoolsHandler.launchDevToolsInBrowser (package:flutter_tools/src/resident_devtools_handler.dart:112:7)
#6      TerminalHandler._commonTerminalInputHandler (package:flutter_tools/src/resident_runner.dart:1662:55)
#7      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1680:13)
#8      _rootRunUnary (dart:async/zone.dart:1434:47)
#9      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#10     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#12     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#13     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:378:25)
#14     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:244:5)
#15     _AsBroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:475:11)
#16     _rootRunUnary (dart:async/zone.dart:1434:47)
#17     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#20     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#21     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#22     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#23     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#24     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
```
```
[✓] Flutter (Channel master, 2.6.0-12.0.pre.806, on macOS 11.6.1 20G224 darwin-x64, locale en)
    • Flutter version 2.6.0-12.0.pre.806 at /Users/vungo/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fa100d23d3 (7 weeks ago), 2021-11-23 05:08:07 -0500
    • Engine revision 2cc81657bc
    • Dart version 2.16.0 (build 2.16.0-36.0.dev)
    • DevTools version 2.8.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/vungo/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.1)
    • VS Code at /Users/vungo/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • D6D5D367-E6E2-4906-915D-BF1DECB11074 • ios        • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64 • macOS 11.6.1 20G224 darwin-x64

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 4cc385b4b84ac2f816d939a49ea1f328c4e0b48e
### Plugins
amplify_analytics_pinpoint-0.2.10
amplify_auth_cognito-0.2.10
amplify_core-0.2.10
amplify_flutter-0.2.10
camera-0.9.4+1
camera_web-0.2.1+1
device_info-2.0.2
flutter_plugin_android_lifecycle-2.0.3
flutter_qr_reader-1.0.5
image_picker-0.8.4+2
image_picker_for_web-2.1.3
local_auth-1.1.8
OneSignal-Flutter-SDK-952e78c1c6f7ace65082914f4e90f6667b6b382c
path_provider-2.0.5
path_provider_linux-2.1.0
path_provider_macos-2.0.2
path_provider_windows-2.0.3
qr_code_scanner-0.5.2
shared_preferences-2.0.8
shared_preferences_linux-2.0.2
shared_preferences_macos-2.0.2
shared_preferences_web-2.0.2
shared_preferences_windows-2.0.2

**Comment by danagbemava-nc** [comment]
Hi @TuanVu1905, can you install `Google Chrome` to see whether or not you still experience this issue?
