### ISSUE TITLE
Difficulty to run Flutter doctor on a fresh install in Mac air M1 chip

### ISSUE THREAD

**Issue by melchorlapinigjr** [flutter/flutter#96519]
Hi, I've been trying to figure out the reason causing this error. I followed https://docs.flutter.dev/get-started/install/macos and search other possible solutions in the internet but no luck. A help would be appreciated. Thanks.

**Note: I can run "Flutter" or "Flutter --version" command, but not "Flutter doctor".**

Device: Macbook Air M1
OS: BigSur (tried update to Montery still the same)
Applied : https://github.com/flutter/flutter/wiki/Developing-with-Flutter-on-Apple-Silicon 

Tried:
> Switching from stable - beta - stable and different stable versions releases
> Setting - re-setting path. 
> Moving Flutter sdk to different locations
> Changing permissions

```
melchorlapinig@Melchors-MacBook-Air development % flutter doctor -v

The flutter tool cannot access the file or directory.
Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current user.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      _throwFileSystemException (package:flutter_tools/src/base/error_handling_io.dart:820:3)
#2      _handlePosixException (package:flutter_tools/src/base/error_handling_io.dart:761:3)
#3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:614:7)
#4      ErrorHandlingProcessManager.runSync (package:flutter_tools/src/base/error_handling_io.dart:711:12)
#5      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:373:51)
#6      AndroidStudio._init (package:flutter_tools/src/android/android_studio.dart:458:39)
#7      new AndroidStudio (package:flutter_tools/src/android/android_studio.dart:40:5)
#8      AndroidStudio.fromMacOSBundle (package:flutter_tools/src/android/android_studio.dart:90:12)
#9      AndroidStudio._allMacOS.<anonymous closure> (package:flutter_tools/src/android/android_studio.dart:316:68)
#10     MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
#11     ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
#12     WhereTypeIterator.moveNext (dart:_internal/iterable.dart:869:20)
#13     new _GrowableList._ofOther (dart:core-patch/growable_array.dart:198:26)
#14     new _GrowableList.of (dart:core-patch/growable_array.dart:152:26)
#15     new List.of (dart:core-patch/array_patch.dart:51:28)
#16     Iterable.toList (dart:core/iterable.dart:388:12)
#17     AndroidStudio._allMacOS (package:flutter_tools/src/android/android_studio.dart:318:10)
#18     AndroidStudio.allInstalled (package:flutter_tools/src/android/android_studio.dart:247:34)
#19     AndroidStudio.latestValid (package:flutter_tools/src/android/android_studio.dart:232:41)
#20     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#21     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:453:23)
#22     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#23     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#24     AppContext.get (package:flutter_tools/src/base/context.dart:119:24)
#25     AppContext.get (package:flutter_tools/src/base/context.dart:119:24)
#26     androidStudio (package:flutter_tools/src/globals_null_migrated.dart:65:45)
#27     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:104:32)
#28     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#29     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:453:23)
#30     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#31     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#32     AppContext.get (package:flutter_tools/src/base/context.dart:119:24)
#33     AppContext.get (package:flutter_tools/src/base/context.dart:119:24)
#34     androidLicenseValidator (package:flutter_tools/src/android/android_workflow.dart:28:65)
#35     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:56:32)
#36     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1290:12)
<asynchronous suspension>
#37     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
<asynchronous suspension>
#38     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#39     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#40     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
<asynchronous suspension>
#41     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#42     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
<asynchronous suspension>
#43     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#44     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#45     main (package:flutter_tools/executable.dart:94:3)
<asynchronous suspension>```

**Comment by yashjani01** [comment]
What is the Flutter SDK version installed?

**Comment by melchorlapinigjr** [comment]
Hi. Sdk for mac https://docs.flutter.dev/get-started/install/macos.

**Comment by melchorlapinigjr** [comment]
It's weird because I can run "Flutter" or "Flutter doctor" but not "Flutter doctor".

**Comment by melchorlapinigjr** [comment]
```

melchorlapinig@Melchors-MacBook-Air ~ % flutter doctor
The flutter tool cannot access the file or directory.
Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current user.

melchorlapinig@Melchors-MacBook-Air ~ % flutter --version
Flutter 2.8.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 77d935af4d (4 weeks ago) • 2021-12-16 08:37:33 -0800
Engine • revision 890a5fca2e
Tools • Dart 2.15.1
melchorlapinig@Melchors-MacBook-Air ~ % flutter
Manage your Flutter app development.

Common commands:

  flutter create <output directory>
    Create a new Flutter project in the specified directory.

  flutter run [options]
    Run your Flutter application on an attached device or in an emulator.

Usage: flutter <command> [arguments]

Global options:
-h, --help                  Print this usage information.
-v, --verbose               Noisy logging, including all shell commands executed.
                            If used with "--help", shows hidden options. If used with "flutter doctor", shows additional
                            diagnostic information. (Use "-vv" to force verbose logging in those cases.)
-d, --device-id             Target device id or name (prefixes allowed).
    --version               Reports the version of this tool.
    --suppress-analytics    Suppress analytics reporting when this command runs.

Available commands:

Flutter SDK
  bash-completion   Output command line shell completion setup scripts.
  channel           List or switch Flutter channels.
  config            Configure Flutter settings.
  doctor            Show information about the installed tooling.
  downgrade         Downgrade Flutter to the last active version for the current channel.
  precache          Populate the Flutter tool's cache of binary artifacts.
  upgrade           Upgrade your copy of Flutter.

Project
  analyze           Analyze the project's Dart code.
  assemble          Assemble and build Flutter resources.
  build             Build an executable app or install bundle.
  clean             Delete the build/ and .dart_tool/ directories.
  create            Create a new Flutter project.
  drive             Run integration tests for the project on an attached device or emulator.
  format            Format one or more Dart files.
  gen-l10n          Generate localizations for the current project.
  pub               Commands for managing Flutter packages.
  run               Run your Flutter app on an attached device.
  test              Run Flutter unit tests for the current project.

Tools & Devices
  attach            Attach to a running app.
  custom-devices    List, reset, add and delete custom devices.
  devices           List all connected devices.
  emulators         List, launch and create emulators.
  install           Install a Flutter app on an attached device.
  logs              Show log output for running Flutter apps.
  screenshot        Take a screenshot from a connected device.
  symbolize         Symbolize a stack trace from an AOT-compiled Flutter app.

Run "flutter help <command>" for more information about a command.
Run "flutter help -v" for verbose help output, including less commonly used options.
melchorlapinig@Melchors-MacBook-Air ~ % 
```

**Comment by yashjani01** [comment]
According to me it needs permission to run.

**Comment by yashjani01** [comment]
Have you placed the SDK in correct Directory?

**Comment by yashjani01** [comment]
Try below command in terminal

export PATH="$PATH: pwd /flutter/bin"

**Comment by melchorlapinigjr** [comment]
Yeah, here is my $HOME/.zshrc content:
``` 
export PATH="$PATH:/Users/melchorlapinig/Development/flutter/bin"

```
This is also where my SDK is : /Users/melchorlapinig/Development/flutter/bin

**Comment by melchorlapinigjr** [comment]
> According to me it needs permission to run.

Yes, what do I do here? I've been trying to change user permissions but no lack.

**Comment by yashjani01** [comment]
Run the below command in terminal

which flutter

**Comment by melchorlapinigjr** [comment]
Here:
```
melchorlapinig@Melchors-MacBook-Air ~ % which flutter dart
/Users/melchorlapinig/Development/flutter/bin/flutter
/Users/melchorlapinig/Development/flutter/bin/dart
melchorlapinig@Melchors-MacBook-Air ~ % 
```

**Comment by yashjani01** [comment]
@Hixie

**Comment by yashjani01** [comment]
@Hixie, @domesticmouse have a look.

**Comment by melchorlapinigjr** [comment]
> @Hixie, @domesticmouse have a look.

Please, thanks.

**Comment by maheshmnj** [comment]
Hi @melchorlapinigjr, Thanks for filing the issue. Could you please check if `flutter doctor -v`  works, I am suspecting this issue to be same as https://github.com/flutter/flutter/issues/70216

**Comment by melchorlapinigjr** [comment]
Yeah, sure.

```

melchorlapinig@Melchors-MacBook-Air ~ % flutter doctor -v
The flutter tool cannot access the file or directory.
Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current user.



#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      _throwFileSystemException (package:flutter_tools/src/base/error_handling_io.dart:820:3)
#2      _handlePosixException (package:flutter_tools/src/base/error_handling_io.dart:761:3)
#3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:614:7)
#4      ErrorHandlingProcessManager.runSync (package:flutter_tools/src/base/error_handling_io.dart:711:12)
#5      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:373:51)
#6      AndroidStudio._init (package:flutter_tools/src/android/android_studio.dart:458:39)
#7      new AndroidStudio (package:flutter_tools/src/android/android_studio.dart:40:5)
#8      AndroidStudio.fromMacOSBundle (package:flutter_tools/src/android/android_studio.dart:90:12)
#9      AndroidStudio._allMacOS.<anonymous closure> (package:flutter_tools/src/android/android_studio.dart:316:68)
#10     MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
#11     ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
#12     WhereTypeIterator.moveNext (dart:_internal/iterable.dart:869:20)
#13     new _GrowableList._ofOther (dart:core-patch/growable_array.dart:198:26)
#14     new _GrowableList.of (dart:core-patch/growable_array.dart:152:26)
#15     new List.of (dart:core-patch/array_patch.dart:51:28)
#16     Iterable.toList (dart:core/iterable.dart:388:12)
#17     AndroidStudio._allMacOS (package:flutter_tools/src/android/android_studio.dart:318:10)
#18     AndroidStudio.allInstalled (package:flutter_tools/src/android/android_studio.dart:247:34)
#19     AndroidStudio.latestValid (package:flutter_tools/src/android/android_studio.dart:232:41)
#20     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#21     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:453:23)
#22     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#23     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#24     AppContext.get (package:flutter_tools/src/base/context.dart:119:24)
#25     AppContext.get (package:flutter_tools/src/base/context.dart:119:24)
#26     androidStudio (package:flutter_tools/src/globals_null_migrated.dart:65:45)
#27     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:104:32)
#28     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#29     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:453:23)
#30     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#31     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#32     AppContext.get (package:flutter_tools/src/base/context.dart:119:24)
#33     AppContext.get (package:flutter_tools/src/base/context.dart:119:24)
#34     androidLicenseValidator (package:flutter_tools/src/android/android_workflow.dart:28:65)
#35     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:56:32)
#36     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1290:12)
<asynchronous suspension>
#37     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
<asynchronous suspension>
#38     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#39     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#40     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
<asynchronous suspension>
#41     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#42     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
<asynchronous suspension>
#43     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#44     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#45     main (package:flutter_tools/executable.dart:94:3)
<asynchronous suspension>



melchorlapinig@Melchors-MacBook-Air ~ % 
``

**Comment by maheshmnj** [comment]
Thanks for the info @melchorlapinigjr. This issue seems to be due to a broken version of Android Studio on your machine as per this issue https://github.com/flutter/flutter/issues/70216 and flutter is sending an incorrect message in the console. To fix this issue you may try reinstalling a stable version of Android studio. You may follow up on the linked issue for further updates, Closing this issue as a duplicate.

**Comment by melchorlapinigjr** [comment]
Yes, I already tried installing different versions of android studio but same. :(

**Comment by maheshmnj** [comment]
@melchorlapinigjr could you please share the android studio version that you are using?

**Comment by melchorlapinigjr** [comment]
@maheshmnj Tried 2 version. Currently installed is the latest version:

Android Studio Arctic Fox | 2020.3.1 Patch 4
Build #AI-203.7717.56.2031.7935034, built on November 21, 2021
Runtime version: 11.0.10+0-b96-7249189 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.1
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 8
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: Dart, io.flutter

**Comment by melchorlapinigjr** [comment]
I'll keep trying switching different versions.

**Comment by maheshmnj** [comment]
May be you can try this version, which works fine (at least for me ) on the M1.

```
Android Studio 4.2
Build #AI-202.7660.26.42.7322048, built on April 29, 2021
Runtime version: 11.0.8+10-b944.6916264 x86_64
VM: OpenJDK 64-Bit Server VM by N/A
macOS 10.16
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 8
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: Dart, org.jetbrains.kotlin, io.flutter
```

**Comment by melchorlapinigjr** [comment]
Okay thanks. What is your flutter SDK version by the way?

**Comment by maheshmnj** [comment]
stable, 2.8.1

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.8.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (4 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:5555 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos            • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 97.0.4692.71

• No issues found!
```

**Comment by yashjani01** [comment]
Great!

**Comment by melchorlapinigjr** [comment]
@maheshmnj did you download release that is specific to Mac (Apple Silicon)?

**Comment by melchorlapinigjr** [comment]
@maheshmnj  I deleted flutter and android including private config data created inside $Home directory. Downloaded Android Studio 4.2.2 android-studio-ide-202.7486908-mac.dmg release. Thanks a lot, works now. :)

**Comment by maheshmnj** [comment]
> @maheshmnj did you download release that is specific to Mac (Apple Silicon)?

I don't think there any such specific release though https://docs.flutter.dev/get-started/install/macos, btw I just cloned it from the repo.

**Comment by maheshmnj** [comment]
Glad it works.
