### ISSUE TITLE
[tool_crash] RPCError

### ISSUE THREAD

**Issue by ginhoor** [flutter/flutter#96510]
## Command
```
flutter screenshot --type=skia --observatory-url=http://127.0.0.1:58856/saNCml2ec4g=/
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs

[VERBOSE-2:rasterizer.cc(669)] Last layer tree was null when screenshotting.

RPCError
```
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1626:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2109:21)
#2      VmService.callServiceExtension (package:vm_service/src/vm_service.dart:2072:14)
#3      FlutterVmService._checkedCallServiceExtension (package:flutter_tools/src/vmservice.dart:773:28)
#4      FlutterVmService.screenshotSkp (package:flutter_tools/src/vmservice.dart:930:12)
#5      ScreenshotCommand.runSkia (package:flutter_tools/src/commands/screenshot.dart:140:53)
<asynchronous suspension>
#6      ScreenshotCommand.runCommand (package:flutter_tools/src/commands/screenshot.dart:112:19)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
<asynchronous suspension>
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.1 21C52 darwin-arm, locale zh-Hans-CN)
    • Flutter version 2.5.3 at /Users/ginhoor/fvm/versions/2.5.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.2.1, Build version 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for d

**Comment by maheshmnj** [comment]
Hi @ginhoor, Thanks for filing the issue. I see that you are on an older version of flutter, Could you please try upgrading to `stable 2.8.1`  and see if the issue is resolved? If the issue persists please write back with reproducible steps and the updated output of `flutter doctor -v`.

Thanks
