### ISSUE TITLE
IndexedStack doesn't respect index in Flutter Inspector

### ISSUE THREAD

**Issue by Albert221** [flutter/flutter#96581]
This is because `RenderIndexedStack` does not override the `debugDescribeChildren` so the one from `ContainerRenderObjectMixin` is used that describes all the children instead of just the one that's actually displayed.

In this line, we can see as the Flutter Inspector hit tests using `debugDescribeChildren`: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/widget_inspector.dart#L2275 

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale
    en-PL)
    • Flutter version 2.8.1 at /Users/albert/fvm/versions/2.8.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (4 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1
```

## Reproduction

Steps: Run the code below, launch Flutter Inspector and click exactly at the center of the first tab contents text.
Expected: A text from tab 1 is selected.
Actual: A text from tab 2 is selected.

<img src="https://user-images.githubusercontent.com/4085280/149308374-13443c70-e742-4501-8b85-a834208690b3.png" width="300">

<details>
<summary> Code for reproduction</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    const MaterialApp(
      home: Screen(),
    ),
  );
}

class Screen extends StatefulWidget {
  const Screen({Key? key}) : super(key: key);

  @override
  _ScreenState createState() => _ScreenState();
}

class _ScreenState extends State<Screen> {
  int tab = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      bottomNavigationBar: BottomNavigationBar(
        onTap: (index) => setState(() => tab = index),
        currentIndex: tab,
        items: const [
          BottomNavigationBarItem(
            icon: Icon(Icons.filter_1),
            label: 'Tab 1',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.filter_2),
            label: 'Tab 2',
          ),
        ],
      ),
      body: IndexedStack(
        index: tab,
        sizing: StackFit.expand,
        children: const [
          Center(child: Text('This is long text in tab 1')),
          Center(child: Text('This is tab 2')),
        ],
      ),
    );
  }
}

```

**Comment by Albert221** [comment]
Here's a temporary widget-fix:

```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/widgets.dart';

// Remove it and replace with IndexedStack once
// https://github.com/flutter/flutter/issues/96581 is fixed.
class CustomIndexedStack extends IndexedStack {
  CustomIndexedStack({
    Key? key,
    AlignmentGeometry alignment = AlignmentDirectional.topStart,
    TextDirection? textDirection,
    StackFit sizing = StackFit.loose,
    int? index = 0,
    List<Widget> children = const <Widget>[],
  }) : super(
          key: key,
          alignment: alignment,
          textDirection: textDirection,
          sizing: sizing,
          index: index,
          children: children,
        );

  @override
  RenderCustomIndexedStack createRenderObject(BuildContext context) {
    return RenderCustomIndexedStack(
      index: index,
      alignment: alignment,
      textDirection: textDirection ?? Directionality.maybeOf(context),
    );
  }

  @override
  void updateRenderObject(
    BuildContext context,
    RenderCustomIndexedStack renderObject,
  ) {
    renderObject
      ..index = index
      ..alignment = alignment
      ..textDirection = textDirection ?? Directionality.maybeOf(context);
  }
}

class RenderCustomIndexedStack extends RenderIndexedStack {
  RenderCustomIndexedStack({
    List<RenderBox>? children,
    AlignmentGeometry alignment = AlignmentDirectional.topStart,
    TextDirection? textDirection,
    int? index = 0,
  })  : _index = index,
        super(
          children: children,
          alignment: alignment,
          textDirection: textDirection,
          index: index,
        );

  final int? _index;

  @override
  List<DiagnosticsNode> debugDescribeChildren() {
    final children = super.debugDescribeChildren().asMap().entries.map((entry) {
      final index = entry.key;
      final child = entry.value as DiagnosticableTreeNode;

      if (index == _index) {
        return child;
      }

      return DiagnosticableTreeNode(
        name: child.name,
        value: child.value,
        style: DiagnosticsTreeStyle.offstage,
      );
    }).toList();

    return children;
  }
}

```

**Comment by danagbemava-nc** [comment]
Reproducible on stable and master.

## Steps to reproduce
1. Run the code sample in https://github.com/flutter/flutter/issues/96581#issue-1101467733
2. Toggle widget selector in devtools
3. Tap the text In Tab 1 ("This is a long text in tab 1"). Ideally, tap the center of the text
4. Observe that the text in Tab 2 is highlighted instead of the text in Tab 1.

I can also confirm that the CustomIndexedStack in https://github.com/flutter/flutter/issues/96581#issuecomment-1012015857 works as expected. 

<details>
<summary>complete code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/rendering.dart';

void main() {
  runApp(
    const MaterialApp(
      home: Screen(),
    ),
  );
}

class Screen extends StatefulWidget {
  const Screen({Key? key}) : super(key: key);

  @override
  _ScreenState createState() => _ScreenState();
}

class _ScreenState extends State<Screen> {
  int tab = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      bottomNavigationBar: BottomNavigationBar(
        onTap: (index) => setState(() => tab = index),
        currentIndex: tab,
        items: const [
          BottomNavigationBarItem(
            icon: Icon(Icons.filter_1),
            label: 'Tab 1',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.filter_2),
            label: 'Tab 2',
          ),
        ],
      ),
      body: IndexedStack(
        index: tab,
        sizing: StackFit.expand,
        children: const [
          Center(child: Text('This is long text in tab 1')),
          Center(child: Text('This is tab 2')),
        ],
      ),
    );
  }
}

// import 'package:flutter/widgets.dart';

// Remove it and replace with IndexedStack once
// https://github.com/flutter/flutter/issues/96581 is fixed.
class CustomIndexedStack extends IndexedStack {
  CustomIndexedStack({
    Key? key,
    AlignmentGeometry alignment = AlignmentDirectional.topStart,
    TextDirection? textDirection,
    StackFit sizing = StackFit.loose,
    int? index = 0,
    List<Widget> children = const <Widget>[],
  }) : super(
          key: key,
          alignment: alignment,
          textDirection: textDirection,
          sizing: sizing,
          index: index,
          children: children,
        );

  @override
  RenderCustomIndexedStack createRenderObject(BuildContext context) {
    return RenderCustomIndexedStack(
      index: index,
      alignment: alignment,
      textDirection: textDirection ?? Directionality.maybeOf(context),
    );
  }

  @override
  void updateRenderObject(
    BuildContext context,
    RenderCustomIndexedStack renderObject,
  ) {
    renderObject
      ..index = index
      ..alignment = alignment
      ..textDirection = textDirection ?? Directionality.maybeOf(context);
  }
}

class RenderCustomIndexedStack extends RenderIndexedStack {
  RenderCustomIndexedStack({
    List<RenderBox>? children,
    AlignmentGeometry alignment = AlignmentDirectional.topStart,
    TextDirection? textDirection,
    int? index = 0,
  })  : _index = index,
        super(
          children: children,
          alignment: alignment,
          textDirection: textDirection,
          index: index,
        );

  final int? _index;

  @override
  List<DiagnosticsNode> debugDescribeChildren() {
    return super.debugDescribeChildren().asMap().entries.map((entry) {
      final index = entry.key;
      final child = entry.value as DiagnosticableTreeNode;

      if (index == _index) {
        return child;
      }

      return DiagnosticableTreeNode(
        name: child.name,
        value: child.value,
        style: DiagnosticsTreeStyle.offstage,
      );
    }).toList();
  }
}

```
</details>


<details>
<summary>video</summary>

| IndexedStack | CustomIndexedStack |
| -- | -- |
| <video src="https://user-images.githubusercontent.com/88313112/149319057-7544c5dd-d8f6-4248-8b91-4cd04d780c7d.mov" /> | <video src="https://user-images.githubusercontent.com/88313112/149319633-8d4eb4a4-fb30-4bf1-ba59-0dbde941bfc9.mov" /> |


</details>


<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.8.1 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (4 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:318:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1428:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1863:10)
      #15     runZonedGuarded (dart:async/zone.dart:1851:12)
      #16     runZoned (dart:async/zone.dart:1782:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:197:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:301:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:53:47)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1290:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (4 available)
    • Nexus (mobile)     • 00008020-001875E83A38002E            • ios            • iOS 15.0.2 19A404
    • iPhone 13 (mobile) • 7515F01A-C1B6-456E-8559-8D2383D3719D • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 97.0.4692.71

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel master, 2.9.0-1.0.pre.335, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.9.0-1.0.pre.335 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 40a2689b9c (5 hours ago), 2022-01-12 21:10:19 -0800
    • Engine revision 91fe85e8cd
    • Dart version 2.16.0 (build 2.16.0-159.0.dev)
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 213.5744.122

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (4 available)
    • Nexus (mobile)     • 00008020-001875E83A38002E            • ios            • iOS 15.0.2 19A404
    • iPhone 13 (mobile) • 7515F01A-C1B6-456E-8559-8D2383D3719D • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 97.0.4692.71

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>
