### ISSUE TITLE
Auto quarantine bot when failing tests consistently

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#96616]
We need to auto quarantine bot when tests consistently failing on a bot. Related https://github.com/flutter/flutter/issues/96613

Suggestions: 

- quarantine a bot if >1 consecutive infra failures
- quarantine a bot if >[19 consecutive test failures](https://chrome-internal.git.corp.google.com/infradata/config/+/refs/heads/main/configs/chromium-swarm/scripts/bot_config.py#752)

**Comment by keyonghan** [comment]
A side effect is when a whole row fails (due to some unexpected issues) it may cause most bots quarantined:
<img width="1179" alt="Screen Shot 2022-01-13 at 10 01 38 AM" src="https://user-images.githubusercontent.com/54558023/149384682-858484d0-36a3-458a-82cf-5f9e990f8d47.png">

**Comment by keyonghan** [comment]
https://chrome-internal-review.googlesource.com/c/infradata/config/+/4681381 for flutter devicelab staging bots.
https://chrome-internal-review.googlesource.com/c/infradata/config/+/4732106 for flutter devicelab prod bots.

For bots configured by `fuchsia.py`, this is blocked on fork version to `flutter.py`.

**Comment by keyonghan** [comment]
https://chrome-internal-review.googlesource.com/c/infradata/config/+/4776848 implemented new logic to quarantine bot based on a local file. But it caused failure to start swarming bot service:
```
cmd: ['/opt/s/swarming_bot.1.zip', 'start_bot']
22454 2022-05-25 19:19:51.395 E: ts_mon monitoring is disabled because the endpoint provided is invalid or not supported: 
22454 2022-05-25 19:19:52.104 E: Failed to run start_bot
Traceback (most recent call last):
  File "/opt/s/swarming_bot.1.zip/__main__.py", line 287, in main
    return fn(args)
  File "/opt/s/swarming_bot.1.zip/__main__.py", line 202, in CMDstart_bot
    result = bot_main.main(args)
  File "/opt/s/swarming_bot.1.zip/bot_code/bot_main.py", line 1532, in main
    return _run_bot(error)
  File "/opt/s/swarming_bot.1.zip/bot_code/bot_main.py", line 1074, in _run_bot
    return _run_bot_inner(arg_error, quit_bit)
  File "/opt/s/swarming_bot.1.zip/bot_code/bot_main.py", line 1147, in _run_bot_inner
    _do_handshake(botobj, quit_bit)
  File "/opt/s/swarming_bot.1.zip/bot_code/bot_main.py", line 1236, in _do_handshake
    _register_extra_bot_config(content, rev, script)
  File "/opt/s/swarming_bot.1.zip/bot_code/bot_main.py", line 256, in _register_extra_bot_config
    exec(compiled, _EXTRA_BOT_CONFIG.__dict__)
  File "injected.py", line 16, in <module>
ModuleNotFoundError: No module named 'flutter_script_utils'
22454 2022-05-25 19:19:52.107 E: Files in /opt/s/swarming_bot.
```

**Comment by keyonghan** [comment]
Swarming sees only one config file per their design, making shared module not applicable.
https://chrome-internal-review.googlesource.com/c/infradata/config/+/4780310 applied changes for ios staging bot. From the log, we are correctly tracking passing builds, but the logic is not being picked up when task fails.
https://chrome-internal-review.googlesource.com/c/infradata/config/+/4782346 added more logs to debug, but no log is being recorded.
Filed https://bugs.chromium.org/p/chromium/issues/detail?id=1329962 to see if there is any bug from swarming side for customized `on_after_task`.

**Comment by keyonghan** [comment]
Seems both default bot_config.py and our customized configs are merged and executed, whereas the former config reboots bot before running our recovery logics.

Actions forward:
- [ ] Remove recovery logic from flutter prod bot configs to avoid breakage
- [ ] Skip reboot from bot_config.py for flutter devicelab bots
- [ ] Validate reboot+recovery in staging bot configs
- [ ] Push logics to prod bot configs.
