### ISSUE TITLE
[Web] dart:web_gl NoSuchMethodError: method not found: 'get$TEXTURE_MAX_ANISOTROPY_EXT' 

### ISSUE THREAD

**Issue by wasabia** [flutter/flutter#96659]
EXTTextureFilterAnisotropic object can not call TEXTURE_MAX_ANISOTROPY_EXT when profile & release mode.

debug mode is ok.

```
 _ext: Instance of 'EXTTextureFilterAnisotropic' 
js_primitives.dart:47 NoSuchMethodError: method not found: 'get$TEXTURE_MAX_ANISOTROPY_EXT' (J.getInterceptor$z(...).get$TEXTURE_MAX_ANISOTROPY_EXT is not a function)
js_primitives.dart:47     at Object.get$TEXTURE_MAX_ANISOTROPY_EXT$z (http://localhost:63651/main.dart.js:27909:43)
```

[https://github.com/wasabia/three_dart/issues/14](https://github.com/wasabia/three_dart/issues/14)

reproduce example code

click render will throw error in chrome console

<details>
<summary>code sample</summary>

```dart
import 'dart:html';
import 'dart:ui' as ui;
import 'package:flutter/material.dart';


class app_debug2 extends StatefulWidget {
  String fileName;

  app_debug2({Key? key, required this.fileName}) : super(key: key);

  createState() => webgl_debugState();
}

class webgl_debugState extends State<app_debug2> {

  CanvasElement? element;
  dynamic gl;
  String divId = DateTime.now().microsecondsSinceEpoch.toString();

  @override
  void initState() {
    super.initState();


    init();
  }

  init() {
    ui.platformViewRegistry.registerViewFactory(divId, (int viewId) {
      this.element = CanvasElement(width: 300, height: 300)
      ..id = 'canvas-id';

      print(" set element ");
      print(" set gl ");
      
      this.gl = this.element!.getContext("webgl2", {"alpha": true, "antialias": true});
      return this.element!;
    });

    
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text(widget.fileName),
        ),
        body: Container(
          child: HtmlElementView(viewType: divId),
        ),
        floatingActionButton: FloatingActionButton(
          child: Text("render"),
          onPressed: () {
            render();
          },
        ),
      ),
    );
  }

  render() {
    print(" render gl: ${gl} ");

    var _ext = gl.getExtension("EXT_texture_filter_anisotropic");

    print(" _ext: ${_ext} ");
    print(" _ext: ${_ext.TEXTURE_MAX_ANISOTROPY_EXT} ");

  }

}

```
</details>

**Comment by maheshmnj** [comment]
Hi @wasabia, Thanks for filing the issue. I tried running your code sample but method `platformViewRegistry` is not found in `dart:ui`, So I used `univeral_ui` instead of `dart:ui` in the below code sample due to this issue https://github.com/flutter/flutter/issues/41563. I do see a similar error in debug mode though. Could you please share your output of `flutter doctor -v` and also check if this is the same error you are referring to? 
 
<details>
<summary>code sample</summary>

```dart
import 'dart:html';
import 'package:flutter/material.dart';
import 'package:universal_ui/universal_ui.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: AppDebug(
      fileName: 'Some file name',
    ));
  }
}

class AppDebug extends StatefulWidget {
  String fileName;

  AppDebug({Key? key, required this.fileName}) : super(key: key);

  createState() => WebGLDebugState();
}

class WebGLDebugState extends State<AppDebug> {
  CanvasElement? element;
  dynamic gl;
  String divId = DateTime.now().microsecondsSinceEpoch.toString();

  @override
  void initState() {
    super.initState();
    init();
  }

  init() {
    ui.platformViewRegistry.registerViewFactory(divId, (int viewId) {
      element = CanvasElement(width: 300, height: 300)..id = 'canvas-id';
      gl = element!.getContext("webgl2", {"alpha": true, "antialias": true});
      return element!;
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text(widget.fileName),
        ),
        body: Container(
          child: HtmlElementView(viewType: divId),
        ),
        floatingActionButton: FloatingActionButton(
          child: Text("render"),
          onPressed: () {
            render();
          },
        ),
      ),
    );
  }

  render() {
    print(" render gl: ${gl} ");

    var _ext = gl.getExtension("EXT_texture_filter_anisotropic");

    print(" _ext: ${_ext} ");
    print(" _ext: ${_ext.TEXTURE_MAX_ANISOTROPY_EXT} ");
  }
}

```
</details>
 
 <details>
<summary>logs</summary>

```
mahesh@Maheshs-MacBook-Air-M1 counter % flutter run -d chrome --no-sound-null-safety
Running "flutter pub get" in counter...                          2,759ms
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             31.6s
This app is linked to the debug service: ws://127.0.0.1:59677/V-NqTJL5Kwk=/ws
Debug service listening on ws://127.0.0.1:59677/V-NqTJL5Kwk=/ws

Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

🔥  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".

An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:59677/V-NqTJL5Kwk=
Height of Platform View type: [1642409947577000] may not be set. Defaulting to `height: 100%`.
Set `style.height` to any appropriate value to stop this message.
Width of Platform View type: [1642409947577000] may not be set. Defaulting to `width: 100%`.
Set `style.width` to any appropriate value to stop this message.
The Flutter DevTools debugger and profiler on Chrome is available at: http://127.0.0.1:9102?uri=http://127.0.0.1:59677/V-NqTJL5Kwk=
 render gl: [object WebGL2RenderingContext] 
 _ext: [object EXTTextureFilterAnisotropic] 
 _ext: 34046 

Performing hot restart...                                        1,282ms
Restarted application in 1,292ms.
Height of Platform View type: [1642410066549000] may not be set. Defaulting to `height: 100%`.
Set `style.height` to any appropriate value to stop this message.
Width of Platform View type: [1642410066549000] may not be set. Defaulting to `width: 100%`.
Set `style.width` to any appropriate value to stop this message.
 render gl: [object WebGL2RenderingContext] 
 _ext: [object EXTTextureFilterAnisotropic] 
 _ext: 34046 
```
</details>


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.8.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.3:5555                     • android-arm64  • Android 11 (API 30)
    • iPhone 13 Pro (mobile) • 0FA2FB93-2A89-4FDB-8293-DF66188F1E54 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0
      (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 96.0.4664.110

• No issues found!
```
</details>

**Comment by wasabia** [comment]
only profile & release mode not work

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.8.1 at /Users/zhaolei/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (5 周前), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1
```

**Comment by maheshmnj** [comment]
Could you please clarify How were you able to compile the app despite `platformViewRegistry` not being available in `dart:ui`?

Can you please clarify this? I am using a third party plugin `univeral_ui` and I was able to reproduce the above error in debug mode too.

> and also check if this is the same error you are referring to?

**Comment by wasabia** [comment]
i did't know, how this happen, 
i just can run it with dart:ui.


my problem is in profile & release mode
dart:web_gl NoSuchMethodError: method not found: 'get$TEXTURE_MAX_ANISOTROPY_EXT'

**Comment by maheshmnj** [comment]
@wasabia could you please share the reproducible sample project with the above code sample?

**Comment by wasabia** [comment]
[demo_project.zip](https://github.com/flutter/flutter/files/7919762/demo_project.zip)

**Comment by maheshmnj** [comment]
Thanks for the sample project @wasabia, I am still getting the same error  when compiling your project on `stable 2.8.1`

> The name 'platformViewRegistry' is being referenced through the prefix 'ui', but it isn't defined in any of the libraries imported using that prefix.
Try correcting the prefix or importing the library that defines 'platformViewRegistry'.dartundefined_prefixed_name

Here is a [demo_project.zip](https://github.com/flutter/flutter/files/7923061/demo_project.zip) which uses `universal_ui` instead of `dart:ui` to access platformviewRegistry and I am getting a no such method error in release mode but the error doesn't look same as yours.

<details>
<summary>chrome console logs(release mode)</summary>

```​
Installed new service worker.
js_primitives.dart:47  set element 
js_primitives.dart:47  set gl 
html_dart2js.dart:39958 Height of Platform View type: [1643004164906000] may not be set. Defaulting to `height: 100%`.
Set `style.height` to any appropriate value to stop this message.
TH @ html_dart2js.dart:39958
html_dart2js.dart:39958 Width of Platform View type: [1643004164906000] may not be set. Defaulting to `width: 100%`.
Set `style.width` to any appropriate value to stop this message.
TH @ html_dart2js.dart:39958
js_primitives.dart:47  render gl: Instance of 'minified:Q1' 
js_primitives.dart:47  _ext: Instance of 'EXTTextureFilterAnisotropic' 
js_primitives.dart:47 NoSuchMethodError: method not found: 'gTS' (J.l0(...).gTS is not a function)
js_primitives.dart:47     at Object.aa3 (http://localhost:60551/main.dart.js:15882:23)
js_primitives.dart:47     at Zh.$0 (http://localhost:60551/main.dart.js:31312:22)
js_primitives.dart:47     at tn.x0 (http://localhost:60551/main.dart.js:34336:7)
js_primitives.dart:47     at tear_off.<anonymous> (http://localhost:60551/main.dart.js:3881:79)
js_primitives.dart:47     at eR.AT (http://localhost:60551/main.dart.js:32981:9)
js_primitives.dart:47     at eR.f8 (http://localhost:60551/main.dart.js:32985:21)
js_primitives.dart:47     at eR.Ay (http://localhost:60551/main.dart.js:33138:17)
js_primitives.dart:47     at eR.w_ (http://localhost:60551/main.dart.js:33111:3)
js_primitives.dart:47     at eR.Aw (http://localhost:60551/main.dart.js:33074:3)
js_primitives.dart:47     at eR.h0 (http://localhost:60551/main.dart.js:33039:16)
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.8.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.3:5555                     • android-arm64  • Android 11 (API 30)
    • iPhone 13 Pro (mobile) • 0FA2FB93-2A89-4FDB-8293-DF66188F1E54 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0
      (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 96.0.4664.110

• No issues found!
```
</details>

Labeling this issue for further investigation.

**Comment by wasabia** [comment]
why i can run demo project ....

you should use profile mode will get same error.

**Comment by annagrin** [comment]
[dart rotation] Opened a bug for dart2js to investigate: https://github.com/dart-lang/sdk/issues/48240

**Comment by yjbanov** [comment]
Deduplicating into the Dart SDK issue.
