### ISSUE TITLE
flutter/plugins tree rolled blocked due to persistent test failures in Android webview

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#96661]
Filing for tracking since the plugin tree is closed.

Capturing from discussion in Discord, the failure is not a test failure but an engine exception:
```
[ERROR:flutter/fml/platform/android/jni_util.cc(211)] java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: 1.raster
01-13 13:15:51.647: E/flutter(26324):     at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:1405)
01-13 13:15:51.647: E/flutter(26324):     at io.flutter.embedding.engine.FlutterJNI.destroyOverlaySurfaces(FlutterJNI.java:1174)
```

From @blasten:
> it's coming from https://github.com/flutter/engine/blob/2db35079836e4bdd173f5228ffd18c47789e2113/shell/common/rasterizer.cc#L102 . At the end, we change the thread configuration, and causes this issue

and

> https://github.com/flutter/engine/pull/30724/files made this issue more likely to occur

**Comment by stuartmorgan** [comment]
Downgrading to P1; I've pinned `master` to allow us to re-open the tree. This is blocking us from rolling to new version of `master` though, so is still a significant issue.

**Comment by stuartmorgan** [comment]
PR was reverted; re-opening

**Comment by chinmaygarde** [comment]
The reland PR is here https://github.com/flutter/engine/pull/31122

**Comment by stuartmorgan** [comment]
With the 2.10 release, we're now seeing what is almost certainly this bug on the stable branch, which we can't reasonably fix with pinning, so we very much need a fix for this in 2.10 in order to get the flutter/plugins tree into a good state. (For now we'll need to turn of webview tests on stable which is a significant coverage gap.)

**Comment by Giuspepe** [comment]
Can you estimate when the fix for this issue will land in Flutter 2.10?

**Comment by blasten** [comment]
In the next few days. This week for sure.

**Comment by ebot64** [comment]
When the admob widget is commented out, this problem disappears. 

This has affected an update to an app in production. I only realised this morning. Quick fix urgently needed.

**Comment by itsjustkevin** [comment]
Fix landed in flutter 2.10.1 release.
