### ISSUE TITLE
SSLV3_ALERT_HANDSHAKE_FAILURE when using Ed25519

### ISSUE THREAD

**Issue by MousyBusiness** [flutter/flutter#96674]
I'm attempting to use websockets over TLS using a certificate signed with Ed25519. 

I receive the following error:
```
flutter: HandshakeException: Handshake error in client (OS Error: 
	SSLV3_ALERT_HANDSHAKE_FAILURE(tls_record.cc:594)
	HANDSHAKE_FAILURE_ON_CLIENT_HELLO(handshake.cc:603))
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: HandshakeException: Handshake error in client (OS Error: 
	SSLV3_ALERT_HANDSHAKE_FAILURE(tls_record.cc:594)
	HANDSHAKE_FAILURE_ON_CLIENT_HELLO(handshake.cc:603))
#0      _SecureFilterImpl._handshake (dart:io-patch/secure_socket_patch.dart:104:46)
#1      _SecureFilterImpl.handshake (dart:io-patch/secure_socket_patch.dart:147:25)
#2      _RawSecureSocket._secureHandshake (dart:io/secure_socket.dart:803:54)
#3      _RawSecureSocket._closeHandler (dart:io/secure_socket.dart:796:15)
#4      _RawSecureSocket._eventDispatcher (dart:io/secure_socket.dart:739:9)
#5      _rootRunUnary (dart:async/zone.dart:1444:13)
#6      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#11     _StreamController._add (dart:async/stream_controller.dart:607:7)
#12     _StreamController.add (dart:async/stream_controller.dart:554:5)
#13     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1837:35)
#14     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1307:18)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```

In my Go backend: 
```
2022/01/15 08:09:57 http: TLS handshake error from 127.0.0.1:60355: EOF
2022/01/15 08:09:57 http: TLS handshake error from [::1]:60354: tls: peer doesn't support any of the certificate's signature algorithms
```

I'm using HttpOverrides to provide the certs but this is never hit. I believe the issue is located in secure_socket.dart and believe that Ed25519 is not yet supported.

Is Ed25519 supported in Flutter? Is it in the pipeline? Is my issue a red herring and not related to Ed25519?

```
 flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6 20G165 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.3)
[✓] VS Code (version 1.63.2)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by danagbemava-nc** [comment]
Hi @MousyBusiness, please provide a complete minimal reproducible code sample. 

Also, what platforms are you experiencing this issue on? 

Thank you

**Comment by MousyBusiness** [comment]
MacOS, my conclusion is ED25519 is not implemented as the flow works with ECDSA keys. 
Unfortunately a minimum reproducable example would be exceedingly difficult.

**Comment by danagbemava-nc** [comment]
Without a minimal reproducible sample, the issue is not actionable. 

Also, seeing as socket code lives in dart, I believe it would be best if this issue is filed on the dart-lang/sdk repo.
