### ISSUE TITLE
[camera] App crashes with Camera  ( 3492): close

### ISSUE THREAD

**Issue by tuanhwing** [flutter/flutter#96730]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Tap floating button to navigate camera_page 
3. Tap floating button to navigate barcode_page 
4. Tap back button on AppBar to back first page 
5. Tap floating button to navigate camera_page => App 

**Expected results:** 
- App can reopen camera page normally.

**Actual results:** 
- When I back to first page and reopen camera_page ,the whole app freezes
<details>
<summary>Code sample</summary>

https://github.com/tuanhwing/ScanditSample

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel stable, 2.5.3, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-VN)
    • Flutter version 2.5.3 at /Users/TuanHwing/Desktop/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/TuanHwing/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Connected device (2 available)
    • SM A315G (mobile) • RF8N401N6EZ • android-arm64  • Android 10 (API 29)
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 97.0.4692.71

```

</details>

**Comment by ramanjitsingh-hub** [comment]
I would like to work on this issue can anyone assign me this? Thanks!

**Comment by tuanhwing** [comment]
I tried using `camera : 0.8.1+5`. It seems to work fine.
Something is wrong on `0.9.0++` .

Any solution for this problem? Hope to hear from you soon

**Comment by tuanhwing** [comment]
When I navigate to barcode page, logcat will show bellow exception: 
```
2022-01-18 13:52:22.517 24410-26175/com.scandit.barcodecapturesimplesample E/CameraCaptureSession: Session 0: Exception while stopping repeating: 
    android.hardware.camera2.CameraAccessException: CAMERA_DISCONNECTED (2): cancelRequest:518: Camera device no longer alive
        at android.hardware.camera2.CameraManager.throwAsPublicException(CameraManager.java:1149)
        at android.hardware.camera2.impl.ICameraDeviceUserWrapper.cancelRequest(ICameraDeviceUserWrapper.java:97)
        at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1151)
        at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:526)
        at android.hardware.camera2.impl.CameraCaptureSessionImpl$2.onDisconnected(CameraCaptureSessionImpl.java:737)
        at android.hardware.camera2.impl.CameraDeviceImpl$7.run(CameraDeviceImpl.java:244)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: android.os.ServiceSpecificException: cancelRequest:518: Camera device no longer alive (code 4)
        at android.os.Parcel.createException(Parcel.java:2102)
        at android.os.Parcel.readException(Parcel.java:2056)
        at android.os.Parcel.readException(Parcel.java:2004)
        at android.hardware.camera2.ICameraDeviceUser$Stub$Proxy.cancelRequest(ICameraDeviceUser.java:676)
```

I hope these help you

**Comment by maheshmnj** [comment]
Hi @tuanhwing, Thanks for filing the issue.
I tried to run your app and it failed with the following error. 

```
Launching lib/main.dart on Redmi K20 Pro in debug mode...
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Failed to create parent directory '/Users/TuanHwing' when creating directory '/Users/TuanHwing/Downloads/datacapture-flutter-samples-master/BarcodeCaptureSimpleSample/build/app/intermediates/flutter/debug/flutter_assets'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

```

 it would be great if you can remove the third-party plugins from your sample code and share a minimal and complete reproducible code.

Thanks

**Comment by tuanhwing** [comment]
@maheshmnj 
Thx for your response.
I adjusted the git repo `https://github.com/tuanhwing/ScanditSample`. Now, it can run on another computer.

Please try again

**Comment by maheshmnj** [comment]
Thanks for the sample code @tuanhwing, I was able to reproduce the issue the app was completely frozen when navigating to the camera. But It looks like the issue could be due to the third-party barcode plugin, I removed the plugin and I did not see that issue. Please take a look at this [modified sample project](https://github.com/flutter/flutter/files/7895658/ScanditSample.zip)

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.8.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.3:5555                     • android-arm64  • Android 11 (API 30)
    • iPhone 13 Pro (mobile) • 0FA2FB93-2A89-4FDB-8293-DF66188F1E54 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0
      (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 96.0.4664.110

• No issues found!
```
</details>

**Comment by tuanhwing** [comment]
@maheshmnj 
Thx for your response. 
I confirmed when I removed the plugin and the problem didn't appear.
But I tried camera version `camera : 0.8.1+5` and the problem doesn't happen. What is different between 0.8 and 0.9?

I guess the problem could be: Application should only have one Camera object active at a time.
The camera needs to be released before it can be used elsewhere. I'm trying it

**Comment by maheshmnj** [comment]
> The camera needs to be released before it can be used elsewhere. I'm trying it

Sure please check and let us know.

**Comment by tuanhwing** [comment]
@maheshmnj 

I have tried releasing the `camera_controller` with the following:
1. Call `await controller.dispose()` before navigate to barcode screen. But the problem still occurs (Even if I delay 2 seconds before calling `Navigator.push`)
```
await controller.dispose();
Navigator.of(context).pushReplacement(MaterialPageRoute(builder: (_) => const BarcodePage()));
```
2. When `controller?.takePicture();` done, I'll replace the `camera_widget` with another widget and call `controller.dispose()` in the dispose function of the `camera_widget`.
=> By this way `camera_widget` will be removed from the tree permanently and `camera_controller` will also release (When nothing points to an object, it is considered to be dead). I tried on git repo `https://github.com/tuanhwing/ScanditSample`  and it seems to work fine.

**Comment by maheshmnj** [comment]
Thanks for the update. Glad you were able to resolve the issue.

> I tried on git repo https://github.com/tuanhwing/ScanditSample and it seems to work fine.

Provided you last message I feel its safe to close the issue.  

Thank you.
