### ISSUE TITLE
Assertions failed while running the Test

### ISSUE THREAD

**Issue by akagupta9** [flutter/flutter#96738]
I am getting below error while running integration Test - 

The following assertion was thrown running a test:
'package:flutter/src/rendering/object.dart': Failed assertion:
line 2215 pos 12: '!_debugDisposed': is not true.

Either the assertion indicates an error in the framework itself,
or we should provide substantially more information in this error
message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on
GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack:
#2      RenderObject.markNeedsPaint (package:flutter/src/rendering/object.dart:2281:14)
#3      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:199:5)
<asynchronous suspension>
(elided 2 frames from class _AssertionError)

**Comment by darshankawar** [comment]
@akagupta9 
Can you provide `flutter doctor -v` and a complete minimal reproducible code sample, ie, your main.dart and `app_test.dart` that shows this behavior.
Thanks.

**Comment by akagupta9** [comment]
My flutter doctor -v

**Comment by darshankawar** [comment]
> complete minimal reproducible code sample, ie, your main.dart and `app_test.dart` that shows this behavior.

@akagupta9
