### ISSUE TITLE
Asset Images do not load on fuchsia

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#9675]
```
[00036.200] 02619.02643>  EXCEPTION CAUGHT BY SERVICES 
[00036.204] 02619.02643> The following message was thrown resolving a single-frame image stream:
[00036.204] 02619.02643> Unable to decode image data
[00036.204] 02619.02643> 
[00036.204] 02619.02643> When the exception was thrown, this was the stack:
[00036.210] 02619.02643> #0      AssetBundleImageProvider.loadAsync (package:flutter/src/services/image_provider.dart:290)
[00036.210] 02619.02643> <asynchronous suspension>
[00036.210] 02619.02643> #1      AssetBundleImageProvider.load (package:flutter/src/services/image_provider.dart:271)
[00036.210] 02619.02643> #2      ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/services/image_provider.dart:170)
[00036.210] 02619.02643> #3      ImageCache.putIfAbsent (package:flutter/src/services/image_cache.dart:82)
[00036.210] 02619.02643> #4      ImageProvider.resolve.<anonymous closure> (package:flutter/src/services/image_provider.dart:170)
[00036.211] 02619.02643> (elided 8 frames from package dart:async)
[00036.213] 02619.02643> 
[00036.213] 02619.02643> Image provider: AssetImage(bundle: null, name: "packages/userpicker_device_shell/res/bg.jpg")
[00036.213] 02619.02643> Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#620848777(), name:
[00036.213] 02619.02643> "packages/userpicker_device_shell/res/bg.jpg", scale: 1.0)
[00036.213] 02619.02643> 

```

**Comment by Hixie** [comment]
Have you verified that the image exists and is valid?

**Comment by apwilson** [comment]
Yes
nothing has changed on that front

**Comment by apwilson** [comment]
ALthough even if it was missing, I'd expect a different message than "Unable to decode image data"  If it doesn't say "Image file doesn't exist" then it probably should

**Comment by apwilson** [comment]
THis happens whether or not vulkan is enabled.

**Comment by apwilson** [comment]
Also, it seems network loaded images don't load but also don't emit a failure message, assert, or exception.

**Comment by chinmaygarde** [comment]
This makes me suspect something in the Skia BUILD.gn used by Fuchsia changed in such a way that the image decoding codecs are no longer registered. For example, `SK_HAS_JPEG_LIBRARY ` in [this file](https://github.com/google/skia/blob/master/src/codec/SkCodec.cpp#L31) may not be set anymore. Can you try breaking in the debugger on `SkCodec::NewFromStream` and see if this is indeed the case? You can also try loading a BMP or GIF image. Those always seem to have registrations.

**Comment by apwilson** [comment]
Hey good call, this bad boy works:

http://cd.textfiles.com/clubsoftware/CLIPART/BMP/WILDBOAR.BMP

**Comment by apwilson** [comment]
![bg](https://cloud.githubusercontent.com/assets/142874/25549368/4575da5c-2c26-11e7-8771-e51d75987a01.jpg)
As does this guy:
https://media.giphy.com/media/l3zoKeX8bMG5sMP4s/giphy.gif

**Comment by apwilson** [comment]
We found the issue.  Not flutter.

**Comment by chinmaygarde** [comment]
TIL we support animated GIFs.

**Comment by apwilson** [comment]
Hehe, well the first frame anyway 👍

For future reference if anyone finds this bug, the issue was fuchsia was disabling some image decoding codecs just like @chinmaygarde suspected.
