### ISSUE TITLE
play video with fittedBox and VideoPlay error

### ISSUE THREAD

**Issue by nocsg** [flutter/flutter#96764]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 
```
child: FutureBuilder(
                future: _initializeVideoPlayerFuture,
                builder: (BuildContext context, AsyncSnapshot<dynamic> snapshot) {
                  return FittedBox(
                    fit: BoxFit.cover,
                    child: VideoPlayer(_controller),
                  );
                },
              ),
```

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

```
======== Exception caught by rendering library =====================================================
The following assertion was thrown during paint():
'package:flutter/src/rendering/proxy_box.dart': Failed assertion: line 2639 pos 14: '_transform!.storage.every((double value) => value.isFinite)': is not true.
```

```
The relevant error-causing widget was: 
  FittedBox FittedBox:file:///Users/songgaocao/gitlab/flutter_notta/lib/page/sign/sign_guide_page.dart:124:26
When the exception was thrown, this was the stack: 
#2      RenderFittedBox._updatePaintData (package:flutter/src/rendering/proxy_box.dart:2639:14)
#3      RenderFittedBox.paint (package:flutter/src/rendering/proxy_box.dart:2662:5)
#4      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
#5      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#6      RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2792:15)
#7      RenderStack.paintStack (package:flutter/src/rendering/stack.dart:629:5)
#8      RenderStack.paint (package:flutter/src/rendering/stack.dart:645:7)
#9      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
#10     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#11     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#12     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:392:12)
#13     RenderAnnotatedRegion.paint (package:flutter/src/rendering/proxy_box.dart:5422:13)
#14     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
#15     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#16     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#17     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
#18     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#19     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#20     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
#21     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:141:11)
#22     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
#23     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:973:29)
#24     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:499:19)
#25     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#26     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#27     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
#28     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#29     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#33     _invoke (dart:ui/hooks.dart:150:10)
#34     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#35     _drawFrame (dart:ui/hooks.dart:114:31)
(elided 5 frames from class _AssertionError and dart:async)
The following RenderObject was being processed when the exception was fired: RenderFittedBox#5fbd0
...  needs compositing
...  parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...  constraints: BoxConstraints(w=414.0, h=736.0)
...  size: Size(414.0, 736.0)
...  fit: cover
...  alignment: Alignment.center
...  textDirection: ltr
  child: TextureBox#77aa6 NEEDS-PAINT
    needs compositing
    parentData: <none> (can use size)
    constraints: BoxConstraints(unconstrained)
    size: Size(Infinity, Infinity)
RenderObject: RenderFittedBox#5fbd0
  needs compositing
  parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
  constraints: BoxConstraints(w=414.0, h=736.0)
  size: Size(414.0, 736.0)
  fit: cover
  alignment: Alignment.center
  textDirection: ltr
  child: TextureBox#77aa6 NEEDS-PAINT
    needs compositing
    parentData: <none> (can use size)
    constraints: BoxConstraints(unconstrained)
    size: Size(Infinity, Infinity)
====================================================================================================
```

**Comment by darshankawar** [comment]
@nocsg 
This seems to be happening due to the way FittedBox works. See [this](https://github.com/flutter/flutter/issues/31911) similar open issue and underlying comments / solutions on how to properly use `FittedBox` and see if that helps.
