### ISSUE TITLE
Pluggable network layer to allow for retry, progress reporting, etc, for image downloads

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#9676]
```
[00036.034] 02660.02697>  EXCEPTION CAUGHT BY SERVICES 
[00036.038] 02660.02697> The following SocketException was thrown resolving a single-frame image stream:
[00036.038] 02660.02697> Failed host lookup: 'static.pexels.com' (OS Error: Name does not resolve, errno = -2)
[00036.052] 02660.02697> 
[00036.052] 02660.02697> When the exception was thrown, this was the stack:
[00036.061] 02660.02697> #0      IOClient.send (package:http/src/io_client.dart:30)
[00036.061] 02660.02697> <asynchronous suspension>
[00036.061] 02660.02697> #1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:171)
[00036.061] 02660.02697> <asynchronous suspension>
[00036.061] 02660.02697> #2      BaseClient.get (package:http/src/base_client.dart:34)
[00036.061] 02660.02697> #3      NetworkImage._loadAsync (package:flutter/src/services/image_provider.dart:344)
[00036.061] 02660.02697> <asynchronous suspension>
[00036.061] 02660.02697> #4      NetworkImage.load (package:flutter/src/services/image_provider.dart:330)
[00036.061] 02660.02697> #5      ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/services/image_provider.dart:170)
[00036.061] 02660.02697> #6      ImageCache.putIfAbsent (package:flutter/src/services/image_cache.dart:82)
[00036.062] 02660.02697> #7      ImageProvider.resolve.<anonymous closure> (package:flutter/src/services/image_provider.dart:170)
[00036.062] 02660.02697> #8      SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:38)
[00036.062] 02660.02697> #9      ImageProvider.resolve (package:flutter/src/services/image_provider.dart:168)
[00036.062] 02660.02697> #10     _ImageState._resolveImage (package:flutter/src/widgets/image.dart:276)
[00036.062] 02660.02697> #11     _ImageState.didChangeDependencies (package:flutter/src/widgets/image.dart:257)
[00036.062] 02660.02697> #12     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3260)

```

**Comment by eseidelGoogle** [comment]
This presumably affects all customers, not just fuschia.

**Comment by Hixie** [comment]
To fix this IMHO we should make the network layer pluggable, and have a version of the network layer that knows how to retry on failure. This shouldn't actually require any changes to NetworkImage itself.

**Comment by Hixie** [comment]
see also https://github.com/flutter/flutter/issues/1051

**Comment by tvolkert** [comment]
Superseded by the bugs listed above.

**Comment by tvolkert** [comment]
Actually re-opening, since some of the bugs above lead back to here.  We still need a way to get notified when download or decode is complete on `NetworkImage`

**Comment by tvolkert** [comment]
@Hixie for use cases such as wanting to fade-in images, it seems like the pluggable network layer doesn't really help.

**Comment by jonahwilliams** [comment]
For the case of images (not assets) this could potentially be addressed by the changes in https://github.com/flutter/flutter/pull/17614.

**Comment by zoechi** [comment]
https://github.com/flutter/flutter/issues/16592#issuecomment-427179863 shows some code for `precacheImage`

**Comment by kf6gpe** [comment]
All of the pieces are in place; closing.
