### ISSUE TITLE
[Web] Error: default SecurityContext getter

### ISSUE THREAD

**Issue by jayjah** [flutter/flutter#96773]
My flutter application runs fine on Desktop and Mobile, but lately crashing on Web.

Following crash is visible during startup:

```
[ +172 ms] Using Google Chrome 97.0.4692.71 

[  +20 ms] executing: sysctl hw.optional.arm64
[   +6 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[ +346 ms] [CHROME]:
[        ] [CHROME]:DevTools listening on ws://127.0.0.1:60651/devtools/browser/6cccaf53-6841-4d21-8434-a050070c4e87
[{"event":"app.webLaunchUrl","params":{"url":"http://localhost:60625","launched":true}}]
[+1189 ms] DwdsInjector: Received request for entrypoint at http://localhost:60625/main_module.bootstrap.js
[   +5 ms] MetadataProvider: Loading debug metadata...
[  +29 ms] MetadataProvider: Loaded debug metadata (sound null safety)
[  +17 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:60625/main_module.bootstrap.js
[+5080 ms] ChromeProxyService: Initializing expression compiler for main_module.bootstrap.js with sound null safety: true
[ +140 ms] DevHandler: Debug service listening on ws://127.0.0.1:60683/q3W8grug7K4=/ws

[  +20 ms] This app is linked to the debug service: ws://127.0.0.1:60683/q3W8grug7K4=/ws
[   +6 ms] Debug service listening on ws://127.0.0.1:60683/q3W8grug7K4=/ws
[        ] 💪 Running with sound null safety 💪
[{"event":"app.started","params":{"appId":"0d893112-03d4-4741-a141-2eded6a13319"}}]
Debug service listening on ws://127.0.0.1:60683/q3W8grug7K4=/ws
[{"event":"app.debugPort","params":{"appId":"0d893112-03d4-4741-a141-2eded6a13319","port":60683,"wsUri":"ws://127.0.0.1:60683/q3W8grug7K4=/ws"}}]
[+2067 ms] Error: Unsupported operation: default SecurityContext getter
               at Object.throw_ [as throw] (http://localhost:60625/dart_sdk.js:5063:11)
               at Function.get defaultContext [as defaultContext] (http://localhost:60625/dart_sdk.js:59329:17)
               at main$ (http://localhost:60625/packages/app_template_flutter/src/init_widget.dart.lib.js:46361:26)
               at main$.next (<anonymous>)
               at http://localhost:60625/dart_sdk.js:40192:33
               at _RootZone.runUnary (http://localhost:60625/dart_sdk.js:40062:59)
               at _FutureListener.thenAwait.handleValue (http://localhost:60625/dart_sdk.js:34983:29)
               at handleValueCallback (http://localhost:60625/dart_sdk.js:35551:49)
               at Function._propagateToListeners (http://localhost:60625/dart_sdk.js:35589:17)
               at _Future.new.[_completeWithValue] (http://localhost:60625/dart_sdk.js:35437:23)
               at async._AsyncCallbackEntry.new.callback (http://localhost:60625/dart_sdk.js:35458:35)
               at Object._microtaskLoop (http://localhost:60625/dart_sdk.js:40330:13)
               at _startMicrotaskLoop (http://localhost:60625/dart_sdk.js:40336:13)
               at http://localhost:60625/dart_sdk.js:35811:9
ERROR - 2022-01-18 13:48:07.366442
GET /dart_sdk.js:59329:17
Error thrown by handler.
FormatException: Illegal scheme character (at character 5)
dart_sdk.js:59329:17
    ^

dart:core                                                 _Uri.resolve
package:flutter_tools/src/isolated/devfs_web.dart 525:57  WebAssetServer._resolveDartFile
package:flutter_tools/src/isolated/devfs_web.dart 410:17  WebAssetServer.handleRequest
package:dwds/src/handlers/injector.dart 124:32            DwdsInjector.middleware.<fn>.<fn>
```

Flutter doctor output: 
```
flutter doctor -v
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.4 20F71 darwin-x64, locale en-DE)
    • Flutter version 2.8.1 at /Users/markuskrebs/.asdf/installs/flutter/2.8.1-stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (5 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/markuskrebs/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/markuskrebs/Library/Android/sdk
    • Java binary at: /Users/markuskrebs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.7628.21.2111.8005941/Android Studio Preview.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.0.0.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Users/markuskrebs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.7628.21.2111.8005941/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[☠] IntelliJ IDEA Ultimate Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:318:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1428:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1863:10)
      #15     runZonedGuarded (dart:async/zone.dart:1851:12)
      #16     runZoned (dart:async/zone.dart:1782:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:197:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:301:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:53:47)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1290:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.1)
    • IntelliJ at /Users/markuskrebs/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/213.6461.79/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.60.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • SM A105FN (mobile) • RF8M72GR8RR • android-arm    • Android 11 (API 30)
    • macOS (desktop)    • macos       • darwin-x64     • macOS 11.4 20F71 darwin-x64
    • Chrome (web)       • chrome      • web-javascript • Google Chrome 97.0.4692.71
    ! Error: iPhone Alex (2) is not connected. Xcode will continue when iPhone Alex (2) is connected. (code -13)

! Doctor found issues in 2 categories.
```

**Comment by jayjah** [comment]
Well, actually my fault.. I forgot a bridge for the web platform.
So I am closing this issue as it is resolved for me.
