### ISSUE TITLE
FlutterDriver commands result in null on certain devices.

### ISSUE THREAD

**Issue by mankey2021** [flutter/flutter#96796]
I am currently testing a Flutter app using Appium-Flutter-Driver both locally and on AWS Device Farm. On some of the phones on Device Farm, Appium-Flutter-Driver has been unable to interact with elements. When I checked the Appium logs I noticed that all of the 'click' commands for FlutterDriver result in a null response, such as in the below example

```
2022-01-18 16:43:14:002 - [debug] [35m[W3C (acee1730)][39m Calling AppiumDriver.click() with args: ["eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlVHlwZSI6IlN0cmluZyIsImtleVZhbHVlU3RyaW5nIjoiY29ubmVjdFdpdGhQYXNzd29yZEJ1dHRvbktleSJ9","acee1730-88f2-438c-a867-565109f8b3e2"]
2022-01-18 16:43:14:003 - [debug] [35m[FlutterDriver][39m Executing Flutter driver command 'click'
2022-01-18 16:43:14:003 - [debug] [35m[FlutterDriver][39m >>> {"command":"tap","finderType":"ByValueKey","keyValueType":"String","keyValueString":"connectWithPasswordButtonKey"}
2022-01-18 16:43:14:009 - [debug] [35m[FlutterDriver][39m <<< {"type":"Sentinel","kind":"Collected","valueAsString":"<collected>"} | previous command tap
2022-01-18 16:43:14:009 - [debug] [35m[W3C (acee1730)][39m Responding to client with driver.click() result: null

Also when I try to get the render tree on this device I am met with this error

2022-01-18 16:43:14:024 - [debug] [35m[FlutterDriver][39m Executing Flutter driver command 'execute'
2022-01-18 16:43:14:024 - [debug] [35m[FlutterDriver][39m >>> {"command":"get_render_tree"}
2022-01-18 16:43:14:030 - [debug] [35m[FlutterDriver][39m <<< {"type":"Sentinel","kind":"Collected","valueAsString":"<collected>"} | previous command get_render_tree
2022-01-18 16:43:14:046 - [debug] [35m[W3C (acee1730)][39m Encountered internal error running command: TypeError: Cannot read property 'tree' of undefined
2022-01-18 16:43:14:046 - [debug] [35m[W3C (acee1730)][39m     at getRenderTree (/usr/local/avm/versions/1.22.2/node_modules/appium/node_modules/appium-flutter-driver/lib/commands/execute.ts:70:57)
2022-01-18 16:43:14:046 - [debug] [35m[W3C (acee1730)][39m     at processTicksAndRejections (internal/process/task_queues.js:97:5)

[Here is the full Appium log for this phone](https://gist.github.com/mankey2021/803e28c7b045a1ec0f70d6859f8a66a4)
[And here is the Appium log for a phone I tested locally that didn't have this problem](https://gist.github.com/mankey2021/245bcc007d9a8fb9c4f3d59cd611e82b)
```

I am currently using Appium 1.22.2 and Appium-Flutter-Driver 0.0.34. I believe that this issue is possibly related to [this one](https://github.com/appium-userland/appium-flutter-driver/issues/152) on the Appium-Flutter-Driver page.

**Comment by darshankawar** [comment]
@mankey2021 
Since you mentioned that the behavior is occuring on device farm, you may need to reach out to the device farm support for this. Also, you can share this behavior on the issue you linked related to appium-flutter-driver dedicated repo.
Closing from here. If you think this behavior persists by running locally on devices, then write in comments and I'll reopen the issue.

**Comment by mankey2021** [comment]
@darshankawar 
I reached out to the device farm support team prior to opening this issue and I was told that it looks like a bug with the underlying Flutter Driver and not the device farm environment. I was able to get my hands on a Google Pixel 4a and reproduce this issue locally ([Here are the logs for that device](https://gist.github.com/mankey2021/8c545a4976d22382d9c2a5306611ae5e)). I have also found that this issue only seems to happen on the first install of the app. My test suite is set up so that the app is uninstalled and reinstalled between test cases, and I only had this issue on the first test case and none of the subsequent ones.

**Comment by darshankawar** [comment]
@mankey2021 
Thanks for the update. Since you are using flutter driver, now `integration_test` is now recommended way to write automated, integrated tests. See these documentation: https://docs.flutter.dev/testing/integration-tests. So can you try to use this instead of flutter driver and see if you still get same behavior ?
