### ISSUE TITLE
iOS app stopped running in Simulator from Android Studio after updating to Flutter dev channel (M1 chip)

### ISSUE THREAD

**Issue by dark-chocolate** [flutter/flutter#96802]
I just updated my Flutter SDK, and it suddenly stopped running iOS app in Simulator through Play Button in the Android Studio. 

### What's working: 
- ```flutter build ios```
- ```flutter build ipa```
- Running the app from Xcode

### What's NOT working: 
Running the app from Android studio in iOS simulator (not the physical device) neither from the Play button nor from the command flutter run. Here's the `flutter run -v` stacktrace: 

```
[  +71 ms] Uncategorized (Xcode): Command CompileSwiftSources failed with a nonzero exit code
           
[   +1 ms] Error (Xcode): Undefined symbol: _OBJC_CLASS_$_FlutterStandardTypedData
           
[        ] Error (Xcode): Undefined symbol: _OBJC_CLASS_$_FlutterDartProject
           
[        ] Error (Xcode): Undefined symbol: _OBJC_CLASS_$_FlutterStandardMessageCodec
           
[        ] Error (Xcode): Undefined symbol: _OBJC_CLASS_$_FlutterError
           
[        ] Error (Xcode): Undefined symbol: _FlutterMethodNotImplemented
           
[        ] Error (Xcode): Undefined symbol: _OBJC_CLASS_$_FlutterMethodChannel
           
[   +2 ms] Could not build the application for the simulator.
[        ] Error launching application on iPhone 8.
[   +5 ms] "flutter run" took 13,687ms.
[   +9 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:687:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>
           
           
[  +42 ms] ensureAnalyticsSent: 40ms
[  +61 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

### Flutter doctor : 

```
[✓] Flutter (Channel dev, 2.10.0-0.1.pre, on macOS 12.0.1 21A559 darwin-arm, locale en-US)
    • Flutter version 2.10.0-0.1.pre
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 628f0e3f3a (7 days ago), 2022-01-11 19:50:05 -0600
    • Engine revision 63ca99584a
    • Dart version 2.16.0 (build 2.16.0-134.1.beta)
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK
    • Platform android-31, build-tools 31.0.0
    • Java binary at: 
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)


[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device
    • iPhone 8 (mobile) • 00EE6FDC-5A71-405E-9D9C-CB7472E15BED • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

### Platform:

- [ ] Android
- [x] iOS (only simulator)

**Comment by darshankawar** [comment]
@dark-chocolate 
Can you provide complete `flutter run -v` log ? It'll be huge so put that in a text file and share it here.
Also provide `ios/Runner.xcodeproj/project.pbxproj` and `ios/podfile`.

Moreover, the error log you provided seems to indicate that the error is coming from Xcode:

```
`[  +71 ms] Uncategorized (Xcode): Command CompileSwiftSources failed with a nonzero exit code
           
[   +1 ms] Error (Xcode): Undefined symbol: _OBJC_CLASS_$_FlutterStandardTypedData
           
[        ] Error (Xcode): Undefined symbol: _OBJC_CLASS_$_FlutterDartProject
           
[        ] Error (Xcode): Undefined symbol: _OBJC_CLASS_$_FlutterStandardMessageCodec
           
[        ] Error (Xcode): Undefined symbol: _OBJC_CLASS_$_FlutterError
           
[        ] Error (Xcode): Undefined symbol: _FlutterMethodNotImplemented
           
[        ] Error (Xcode): Undefined symbol: _OBJC_CLASS_$_FlutterMethodChannel`
```

Have you added any share extension for your build phases through Xcode ?
Do you see Run Script or Thin Binary build phases in Xcode ?

**Comment by dark-chocolate** [comment]
As there were over 30,000 lines in `flutter run -v` output, I'm sharing the `.txt` file. 

[logs.txt](https://github.com/flutter/flutter/files/7895692/logs.txt)

**Comment by darshankawar** [comment]
@dark-chocolate 
Looking at the verbose log, it seems to be failing due to:  `Undefined symbols for architecture i386:` which seem to have been fixed recently with this issue: https://github.com/flutter/flutter/issues/94914. Since you are dev which will be de-commissioned, can you switch to latest master and try again and see if it works ?

**Comment by dark-chocolate** [comment]
@dark-chocolate  Thanks for pointing that out. I already had

```
config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64 
```

and after adding `i386` to it, helped me fixed that:

```
config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64 i386 
```
