### ISSUE TITLE
Post-submit `Windows Unopt` is 6.64% flaky for past 30 days

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#96808]
(This is generated by manually scanning through the [engine flakiness dashboard](https://data.corp.google.com/sites/flutter_infra_metrics_datasite/flutter_flakiness_overview_dashboard/?p=BUILDER_NAME:%22Mac%20module_test_ios%22&p=REPO:%22engine%22&p=DAYS:30))

Recent four flaky builds:
https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20Unopt/3160/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20Unopt/3159/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20Unopt/3155/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20Unopt/3148/overview

All are due to test step flake: `test: Host Tests for host_debug_unopt`

```
Failed Command:

C:\b\s\w\ir\cache\builder\src\out\host_debug_unopt\flutter_windows_unittests.exe --gtest_repeat=2 --gtest_shuffle

Exit Code: 1



!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


Traceback (most recent call last):
  File "C:\b\s\w\ir\cache\builder\src\flutter\testing\run_tests.py", line 636, in <module>
    sys.exit(main())
  File "C:\b\s\w\ir\cache\builder\src\flutter\testing\run_tests.py", line 597, in main
    RunCCTests(build_dir, engine_filter, args.coverage, args.engine_capture_core_dump)
  File "C:\b\s\w\ir\cache\builder\src\flutter\testing\run_tests.py", line 187, in RunCCTests
    RunEngineExecutable(build_dir, 'flutter_windows_unittests', filter, shuffle_flags, coverage=coverage)
  File "C:\b\s\w\ir\cache\builder\src\flutter\testing\run_tests.py", line 143, in RunEngineExecutable
    RunCmd(test_command, cwd=cwd, forbidden_output=forbidden_output, expect_failure=expect_failure, env=env)
  File "C:\b\s\w\ir\cache\builder\src\flutter\testing\run_tests.py", line 62, in RunCmd
    raise Exception('Command "%s" exited with code %d.' % (command_string, process.returncode))
Exception: Command "C:\b\s\w\ir\cache\builder\src\out\host_debug_unopt\flutter_windows_unittests.exe --gtest_repeat=2 --gtest_shuffle" exited with code 1.
```

/cc @zanderso and current gardener @gaaclarke

**Comment by keyonghan** [comment]
First flake happened on commit https://github.com/flutter/engine/commit/9e9522c1692a62934d586992eb779e13b61bf55b on 10/12/2021 [internal dashboard](https://data.corp.google.com/sites/flutter_infra_metrics_datasite/flutter_check_test_flakiness_status_dashboard/?p=BUILDER_NAME:%22Windows%20Unopt%22&p=DAYS:30&p=REPO:%22engine%22&p=END_TIME:%222022-01-18%22&p=LIMIT:1500), since then flake happened almost a couple of times daily.

**Comment by zanderso** [comment]
@bdero It looks like your fix here might not have entirely de-flaked the test https://github.com/flutter/engine/commit/4e6f1ded152e933fefd1350b4502dbc4994ccc58. Any thoughts about what might be happening? /cc @moko256 

/cc @cbracken

**Comment by moko256** [comment]
@zanderso The test used system clock and it was the reason in #92928. The flutter/engine#29500 remove the usage completely.

**Comment by bdero** [comment]
I went ahead and merged flutter/engine#29500 as it lgtm and I agree it likely fixes this.

**Comment by zanderso** [comment]
Closing as presumed fixed.

**Comment by keyonghan** [comment]
The above PR was merged in Nov., but we are still seeing the flakes frequently (twice yesterday 01/18: https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20Unopt/3160/overview, https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20Unopt/3159/overview). Seems the fix was not deflaking the test completely?

**Comment by zanderso** [comment]
The PR was merged at 4pm PST yesterday. The flakes are from ~9 and ~10 am PST yesterday.

**Comment by keyonghan** [comment]
> The PR was merged at 4pm PST yesterday. The flakes are from ~9 and ~10 am PST yesterday.

Ah, miss-read the merge date. Thanks for the update!

**Comment by keyonghan** [comment]
Validated no flake after the the fix. Thanks!
