### ISSUE TITLE
TextButton render error when scrolling web page

### ISSUE THREAD

**Issue by galki** [flutter/flutter#96883]
```
════════ Exception caught by rendering library ═════════════════════════════════
The following assertion was thrown during paint():
Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/html/path/path_ref.dart:903:12
isValid
is not true


The relevant error-causing widget was
TextButton
lib\pages\landing_page.dart:462
When the exception was thrown, this was the stack
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3    assertFailed
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/html/path/path_ref.dart 903:12             debugValidate
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/html/path/path_ref.dart 414:5              shiftedFrom
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/html/path/path.dart 64:27                  shiftedFrom
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/html/path/path.dart 1285:19                shift
packages/flutter/src/rendering/proxy_box.dart 2004:31                                                                      paint
packages/flutter/src/rendering/object.dart 2403:7                                                                          [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                                                          paintChild
packages/flutter/src/rendering/proxy_box.dart 140:14                                                                       paint
packages/flutter/src/rendering/object.dart 2403:7                                                                          [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                                                          paintChild
packages/flutter/src/rendering/shifted_box.dart 79:14                                                                      paint
packages/flutter/src/rendering/object.dart 2403:7                                                                          [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                                                          paintChild
packages/flutter/src/rendering/proxy_box.dart 140:14                                                                       paint
packages/flutter/src/rendering/object.dart 2403:7                                                                          [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                                                          paintChild
packages/flutter/src/rendering/shifted_box.dart 79:14                                                                      paint
packages/flutter/src/rendering/object.dart 2403:7                                                                          [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                                                          paintChild
packages/flutter/src/rendering/box.dart 2792:14                                                                            defaultPaint
packages/flutter/src/rendering/flex.dart 1078:7                                                                            paint
packages/flutter/src/rendering/object.dart 2403:7                                                                          [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                                                          paintChild
packages/flutter/src/rendering/proxy_box.dart 140:14                                                                       paint
packages/flutter/src/rendering/proxy_box.dart 2169:11                                                                      paint
packages/flutter/src/rendering/object.dart 2403:7                                                                          [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                                                          paintChild
packages/flutter/src/rendering/proxy_box.dart 140:14                                                                       paint
packages/flutter/src/rendering/object.dart 2403:7                                                                          [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                                                          paintChild
packages/flutter/src/rendering/shifted_box.dart 79:14                                                                      paint
packages/flutter/src/rendering/object.dart 2403:7                                                                          [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                                                          paintChild
packages/flutter/src/rendering/box.dart 2792:14                                                                            defaultPaint
packages/flutter/src/rendering/stack.dart 629:5                                                                            paintStack
packages/flutter/src/rendering/object.dart 392:12                                                                          pushLayer
packages/flutter/src/rendering/object.dart 448:7                                                                           pushClipRect
packages/flutter/src/rendering/stack.dart 635:37                                                                           paint
packages/flutter/src/rendering/object.dart 2403:7                                                                          [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                                                          paintChild
packages/flutter/src/rendering/proxy_box.dart 140:14                                                                       paint
packages/flutter/src/rendering/object.dart 392:12                                                                          pushLayer
packages/flutter/src/rendering/object.dart 520:7                                                                           pushClipPath
packages/flutter/src/rendering/proxy_box.dart 1697:22                                                                      paint
packages/flutter/src/rendering/object.dart 2403:7                                                                          [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                                                          paintChild
packages/flutter/src/rendering/box.dart 2792:14                                                                            defaultPaint
packages/flutter/src/rendering/flex.dart 1078:7                                                                            paint
packages/flutter/src/rendering/object.dart 2403:7                                                                          [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                                                          paintChild
packages/flutter/src/rendering/box.dart 2792:14                                                                            defaultPaint
packages/flutter/src/rendering/flex.dart 1078:7                                                                            paint
packages/flutter/src/rendering/object.dart 2403:7                                                                          [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                                                          paintChild
packages/flutter/src/rendering/proxy_box.dart 140:14                                                                       paint
packages/flutter/src/rendering/object.dart 2403:7                                                                          [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                                                          paintChild
packages/flutter/src/rendering/shifted_box.dart 79:14                                                                      paint
packages/flutter/src/rendering/object.dart 2403:7                                                                          [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                                                          paintChild
packages/flutter/src/rendering/box.dart 2792:14                                                                            defaultPaint
packages/flutter/src/rendering/stack.dart 629:5                                                                            paintStack
packages/flutter/src/rendering/stack.dart 645:7                                                                            paint
packages/flutter/src/rendering/object.dart 2403:7                                                                          [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                                                          paintChild
packages/flutter/src/rendering/shifted_box.dart 79:14                                                                      paint
packages/flutter/src/rendering/object.dart 2403:7                                                                          [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                                                          paintChild
packages/flutter/src/widgets/basic.dart 7530:14                                                                            paint
```

## Steps to Reproduce

1) Scroll the page (web)

```dart
return Scaffold(
      backgroundColor: darkestGrey,
      endDrawer: smallScreen ? const CustomerDrawer() : null,
      body: SafeArea(
        child: SingleChildScrollView(
          controller: _scrollController,
          child: Column(
             ...
               ...
                  ...
                     TextButton(
                        child: const Text('Press'),
                        onPressed: () {}
                     )
             
```

</details>

<details>
  <summary>Logs</summary>

```
[  +68 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +69 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 77d935af4db863f6abd0b9c31c7e6df2a13de57b
[   +1 ms] executing: [C:\src\flutter/] git tag --points-at 77d935af4db863f6abd0b9c31c7e6df2a13de57b
[  +58 ms] Exit code 0 from: git tag --points-at 77d935af4db863f6abd0b9c31c7e6df2a13de57b
[        ] 2.8.1
[  +10 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +40 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\src\flutter/] git ls-remote --get-url origin
[  +37 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +126 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +44 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +105 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +69 ms] executing: C:\Users\laptop\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +61 ms] List of devices attached
[   +9 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +37 ms] Changing current working directory to: C:\Users\laptop\projects\cosmic_indicators_website
[  +59 ms] Multiple devices found:
[  +32 ms] Chrome (web) • chrome • web-javascript • Google Chrome 97.0.4692.71
[   +1 ms] Edge (web)   • edge   • web-javascript • Microsoft Edge 96.0.1054.34
[   +3 ms] [1]: Chrome (chrome)
[        ] [2]: Edge (edge)
[   +2 ms] Please choose one (To quit, press "q/Q")
[        ] : 
[+1927 ms] q
[  +11 ms] "flutter run" took 2,289ms.
[  +27 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      DeviceManager._chooseOneOfAvailableDevices (package:flutter_tools/src/device.dart:292:7)
           <asynchronous suspension>
           #2      DeviceManager.findTargetDevices (package:flutter_tools/src/device.dart:280:37)
           <asynchronous suspension>
           #3      FlutterCommand.findAllTargetDevices (package:flutter_tools/src/runner/flutter_command.dart:1326:28)
           <asynchronous suspension>
           #4      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:463:15)
           <asynchronous suspension>
           #5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1248:5)
           <asynchronous suspension>
           #6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>


[ +264 ms] ensureAnalyticsSent: 253ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +3 ms] exiting with code 1
```

```
No issues found! (ran in 2.6s)
```

```
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.22000.434], locale en-CA)
    • Flutter version 2.8.1 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (5 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\laptop\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code, 64-bit edition (version 1.63.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.32.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 97.0.4692.71
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 96.0.1054.34

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @galki, thanks for reporting this. 

Please provide a complete minimal reproducible code sample without any third-party dependencies and the output of `flutter run -v` that shows the error in question. 

Is this only an issue when you use `canvaskit` or is the `html` renderer affected as well? 

Thank you

**Comment by galki** [comment]
`html` render. `canvaskit` had too many errors going

**Comment by danagbemava-nc** [comment]
Please provide a complete minimal reproducible code sample.
