### ISSUE TITLE
codesign validation fails consistently on release builders

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#96889]
I believe this happens because we never call `git fetch` on the checkouts:

```
Got dependencies!
Exception on command "checkout master": Command "git checkout master" failed in directory "/opt/s/w/ir/x/w/flutter_conductor_checkouts/framework" to Checking out initialRef master. Git exited with error code 1.
stderr from git:
15:43:26.907490 exec-cmd.c:139          trace: resolved executable path from Darwin stack: /opt/s/w/ir/cipd_bin_packages/bin/git
15:43:26.908132 exec-cmd.c:238          trace: resolved executable dir: /opt/s/w/ir/cipd_bin_packages/bin
15:43:26.909069 git.c:455               trace: built-in: git checkout master
error: pathspec 'master' did not match any file(s) known to git

#0      Git._reportFailureAndExit (package:conductor_core/src/git.dart:77:5)
#1      Git.run (package:conductor_core/src/git.dart:43:7)
<asynchronous suspension>
#2      Repository.lazilyInitialize (package:conductor_core/src/repository.dart:184:7)
<asynchronous suspension>
#3      Repository.checkoutDirectory (package:conductor_core/src/repository.dart:132:5)
<asynchronous suspension>
#4      CodesignCommand.run (package:conductor_core/src/codesign.dart:116:28)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#6      main (file:///opt/s/w/ir/x/w/flutter%20sdk/dev/conductor/core/bin/cli.dart:78:5)
<asynchronous suspension>
```

**Comment by godofredoc** [comment]
\cc @itsjustkevin

**Comment by godofredoc** [comment]
Link to a failure:

https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20beta%20verify_binaries_codesigned/372/overview

**Comment by godofredoc** [comment]
CL ready for review: https://flutter-review.googlesource.com/c/recipes/+/25501

**Comment by godofredoc** [comment]
Test is now fixed:

https://flutter-review.googlesource.com/c/recipes/+/25640
https://flutter-review.googlesource.com/c/recipes/+/25602
https://flutter-review.googlesource.com/c/recipes/+/25602
