### ISSUE TITLE
[tool_crash] StateError: Bad state: Stream has already been listened to.

### ISSUE THREAD

**Issue by xhcoding** [flutter/flutter#96894]
## Command
```
flutter run --machine --start-paused --target lib\\main.dart
```

## Steps to Reproduce
1. `flutter create hello_flutter`
2. `cd hello_flutter`
3. `flutter run --machine --start-paused --target lib\\main.dart`

## Logs
StateError: Bad state: Stream has already been listened to.
```
#0      _StreamController._subscribe (dart:async/stream_controller.dart:676:7)
#1      _ControllerStream._createSubscription (dart:async/stream_controller.dart:827:19)
#2      _StreamImpl.listen (dart:async/stream_impl.dart:473:9)
#3      _Socket.listen (dart:io-patch/socket_patch.dart:2174:31)
#4      _StdStream.listen (dart:io/stdio.dart:22:20)
#5      new _SinkTransformerStreamSubscription (dart:async/stream_transformers.dart:49:16)
#6      _BoundSinkStream.listen (dart:async/stream_transformers.dart:171:9)
#7      new _SinkTransformerStreamSubscription (dart:async/stream_transformers.dart:49:16)
#8      _BoundSinkStream.listen (dart:async/stream_transformers.dart:171:9)
#9      new _ForwardingStreamSubscription (dart:async/stream_pipe.dart:114:10)
#10     _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:86:16)
#11     _ForwardingStream.listen (dart:async/stream_pipe.dart:81:12)
#12     new _ForwardingStreamSubscription (dart:async/stream_pipe.dart:114:10)
#13     _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:86:16)
#14     _ForwardingStream.listen (dart:async/stream_pipe.dart:81:12)
#15     new _ForwardingStreamSubscription (dart:async/stream_pipe.dart:114:10)
#16     _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:86:16)
#17     _ForwardingStream.listen (dart:async/stream_pipe.dart:81:12)
#18     CastStream.listen (dart:_internal/async_cast.dart:17:17)
#19     new DaemonConnection (package:flutter_tools/src/daemon.dart:118:54)
#20     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:561:9)
<asynchronous suspension>
#21     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1165:27)
<asynchronous suspension>
#22     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
```
```
[✓] Flutter (Channel master, 2.9.0-1.0.pre.398, on Microsoft Windows [Version 10.0.19044.1466], locale zh-CN)
    • Flutter version 2.9.0-1.0.pre.398 at D:\Applications\Scoop\apps\flutter-cn\current
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8017883a5d (25 hours ago), 2022-01-18 23:04:01 -0500
    • Engine revision 7a33b4b3fb
    • Dart version 2.17.0 (build 2.17.0-27.0.dev)
    • DevTools version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at D:\Applications\Scoop\apps\android-sdk\current
    • Platform android-32, build-tools 32.0.0
    • ANDROID_HOME = D:\Applications\Scoop\apps\android-sdk\current
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.0.31912.275
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be

**Comment by darshankawar** [comment]
There was similar issue with stacktrace but got closed due to no response: https://github.com/flutter/flutter/issues/73931

/cc @christopherfujino

**Comment by xhcoding** [comment]
Explicitly specifying the device ID solves this problem

eg.
```
flutter run -d windows --machine --start-paused --target lib/main.dart
```
