### ISSUE TITLE
RangeError (index): Invalid value: Valid value range is empty: 0 While fatching the data from local json file

### ISSUE THREAD

**Issue by SavanRajyaguru** [flutter/flutter#96909]
when I run my app the first time it is showing a red screen error and then after 2 seconds automatically it is loading the screen and display the data.

### **Error Message**

```
======== Exception caught by widgets library =======================================================
The following RangeError was thrown building HomeScreen(dirty, state: _HomeScreenState#2c9da):
RangeError (index): Invalid value: Valid value range is empty: 0

The relevant error-causing widget was: 
  HomeScreen HomeScreen:file:///D:/DE_Project/startupbits/lib/main.dart:17:13
When the exception was thrown, this was the stack: 
#0      List.[] (dart:core-patch/growable_array.dart:281:36)
#1      _HomeScreenState.build (package:startupbits/screen/homeScreen.dart:35:24)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4870:27)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4754:15)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735:5)
#7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4919:11)
#8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729:5)
...     Normal element mounting (171 frames)
#179    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790:14)
#180    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6422:36)
#181    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6433:32)
...     Normal element mounting (362 frames)
#543    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790:14)
#544    Element.updateChild (package:flutter/src/widgets/framework.dart:3540:18)
#545    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1198:16)
#546    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1167:5)
#547    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1112:18)
#548    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2600:19)
#549    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1111:13)
#550    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:944:7)
#551    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:924:7)
(elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
====================================================================================================

======== Exception caught by widgets library =======================================================
The following RangeError was thrown building HomeScreen(dirty, state: _HomeScreenState#2c9da):
RangeError (index): Invalid value: Valid value range is empty: 0

The relevant error-causing widget was: 
  HomeScreen HomeScreen:file:///D:/DE_Project/startupbits/lib/main.dart:17:13
When the exception was thrown, this was the stack: 
#0      List.[] (dart:core-patch/growable_array.dart:281:36)
#1      _HomeScreenState.build (package:startupbits/screen/homeScreen.dart:35:24)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4870:27)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4754:15)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#6      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2659:19)
#7      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#8      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#9      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#10     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
#11     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:862:7)
(elided 4 frames from class _RawReceivePortImpl, class _Timer, and dart:async-patch)
====================================================================================================
```

### **HomoScreen.dart**

```
import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

class HomeScreen extends StatefulWidget {
  const HomeScreen({Key? key}) : super(key: key);

  @override
  _HomeScreenState createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  List _data = [];

  // Fetch content from the json file
  Future<void> readJson() async {
    final String response = await rootBundle.loadString('assets/StartUpData.json');
    final data = await json.decode(response);
    setState(() {
      if (data != null){
        _data = data;
      }
    });
  }

  @override
  void initState() {
    super.initState();
    readJson();
  }

  @override
  Widget build(BuildContext context) {
    final items = _data[0]["Sector"];
    return Scaffold(
      appBar: AppBar(
        title: Text(
          'StartUpBitz',
          style: TextStyle(fontSize: 25),
        ),
        centerTitle: true,
        backgroundColor: Colors.red,
      ),
      body: _data.isNotEmpty
      ? ListView.builder(
        itemCount: items['Food & Beverages'].length != null ? items['Food & Beverages'].length : 0,
        itemBuilder: (BuildContext context, int index) {
          return Container(
              height: 100,
              margin: EdgeInsets.only(bottom: 5.0),
              color: Colors.amber,
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Text(items['Food & Beverages'][index]['Companies'],style: TextStyle(fontSize: 25),),
                  Text('${index}',style: TextStyle(fontSize: 30),)
                ],
              )
          );
        }
      )
      : Center(child: Text("Error"),)
    );
  }
}

```

**Comment by maheshmnj** [comment]
@SavanRajyaguru This is an issue with your code you need to handle for the case when data is null or empty.

> HomeScreen HomeScreen:file:///D:/DE_Project/startupbits/lib/main.dart:17:13

Take a look at the logs and you should be able to find where exactly the error is.

Closing as this is not an issue with flutter but with your code.If you disagree feel free to write in the comments with complete runnable code, and we will reopen it.

Thank you.

**Comment by maheshmnj** [comment]
> body: _data.isNotEmpty

>   final items = _data[0]["Sector"];

Notice these two statements they can be null at some point in time before `_data` is loaded.

**Comment by maheshmnj** [comment]
>   final items = _data[0]["Sector"];
I think this statement is causing this issue `_data` can be empty at some point before it is assigned a value.
