### ISSUE TITLE
Flutter disables OpenGL / WebGL when starting via Chrome / Broken layout

### ISSUE THREAD

**Issue by golane-august** [flutter/flutter#96919]
## Steps to Reproduce

This issue already was filed here: #95127 and #91223
But it was classified as a WebGL issue. (Without referencing any issue)

1. Execute `flutter run -d chrome` on any flutter application compatible with web
2. Type: `chrome://gpu` in the 
3. Compare the output:
```
Graphics Feature Status
Canvas: Software only, hardware acceleration unavailable
Canvas out-of-process rasterization: Disabled
Compositing: Software only. Hardware acceleration disabled
Multiple Raster Threads: Enabled
Out-of-process Rasterization: Disabled
OpenGL: Disabled
Rasterization: Software only. Hardware acceleration disabled
Raw Draw: Disabled
Skia Renderer: Enabled
Video Decode: Software only. Hardware acceleration disabled
Video Encode: Software only. Hardware acceleration disabled
Vulkan: Disabled
WebGL: Software only, hardware acceleration unavailable
WebGL2: Software only, hardware acceleration unavailable
```

1. Simply start your installed chrome or execute `flutter run -d web-server` on any flutter application compatible with web
2. Type: `chrome://gpu` in the 
3. Compare the output:
```
Graphics Feature Status
Canvas: Hardware accelerated
Canvas out-of-process rasterization: Disabled
Compositing: Hardware accelerated
Multiple Raster Threads: Enabled
Out-of-process Rasterization: Disabled
OpenGL: Enabled
Rasterization: Software only. Hardware acceleration disabled
Raw Draw: Disabled
Skia Renderer: Enabled
Video Decode: Software only. Hardware acceleration disabled
Video Encode: Software only. Hardware acceleration disabled
Vulkan: Disabled
WebGL: Hardware accelerated
WebGL2: Hardware accelerated
```

**Expected results:** 

To have the same output on both commands

**Actual results:** 

OpenGL is disabled when running via `-d chrome`
I think this also affects the execution inside [IntelliJ Flutter](https://github.com/flutter/flutter-intellij) plugin.

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
💪 Running with sound null safety 💪
Debug service listening on ws://127.0.0.1:37143/CSmIhQ2Ot-s=/ws
00:00 +0: Ride Check Out: User checks out and dismisses ride completion dialog
Random network latency applied: 0:00:01.683446
WARNING: failed to attach a stencil buffer. Rendering will be skipped.
WARNING: Falling back to CPU-only rendering. Failed to initialize WebGL context.
```

On hot restart
```
Performing hot restart...
Waiting for connection from debug service on Chrome...
Restarted application in 6,267ms.
00:00 +0: Ride Check Out: User checks out and dismisses ride completion dialog
WARNING: Falling back to CPU-only rendering. WebGL support not detected.
```

```
```

```
```

</details>

<details>
<summary>neofetch</summary>
<p>

        ```
            august@latitude-7400 
            -------------------- 
            OS: Ubuntu 21.10 x86_64 
            Host: Latitude 7400 
            Kernel: 5.13.0-25-generic 
            Uptime: 2 days, 23 hours, 13 mins 
            Packages: 2093 (dpkg), 1 (brew), 15 (snap) 
            Shell: bash 5.1.8 
            Resolution: 2560x1440 
            DE: GNOME 40.5 
            WM: Mutter 
            WM Theme: Adwaita 
            Theme: Yaru-dark [GTK2/3] 
            Icons: Yaru [GTK2/3] 
            Terminal: gnome-terminal 
            CPU: Intel i7-8665U (8) @ 4.800GHz 
            GPU: Intel WhiskeyLake-U GT2 [UHD Graphics 620] 
            Memory: 12911MiB / 15813MiB 
        ```

</p>
</details>

**Comment by golane-august** [comment]
Maybe some setting in chrome flutter_tool leads to this behavior:
https://github.com/flutter/flutter/blob/657830b4c77aecfd0e32ec6504c859213dded97a/packages/flutter_tools/lib/src/web/chrome.dart#L202

**Comment by darshankawar** [comment]
@golane-august 
I verified this behavior using latest master and observed that the details shown by `chrome://gpu` using `-d chrome` and `-d web-server` is same and `OpenGL` is `enabled` for both.

1. With `flutter run -d chrome`:

```
Graphics Feature Status
Canvas: Hardware accelerated
Canvas out-of-process rasterization: Disabled
Compositing: Hardware accelerated
Metal: Disabled
Multiple Raster Threads: Enabled
Out-of-process Rasterization: Hardware accelerated
OpenGL: Enabled
Rasterization: Hardware accelerated
Raw Draw: Disabled
Skia Renderer: Enabled
Video Decode: Hardware accelerated
Video Encode: Hardware accelerated
WebGL: Hardware accelerated
WebGL2: Hardware accelerated
```


2. With `flutter run -d web-server`:

```
Graphics Feature Status
Canvas: Hardware accelerated
Canvas out-of-process rasterization: Disabled
Compositing: Hardware accelerated
Metal: Disabled
Multiple Raster Threads: Enabled
Out-of-process Rasterization: Hardware accelerated
OpenGL: Enabled
Rasterization: Hardware accelerated
Raw Draw: Disabled
Skia Renderer: Enabled
Video Decode: Hardware accelerated
Video Encode: Hardware accelerated
WebGL: Hardware accelerated
WebGL2: Hardware accelerated
```

<details>
<summary> master flutter doctor -v </summary>

```

[✓] Flutter (Channel master, 2.9.0-1.0.pre.427, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.9.0-1.0.pre.427 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6eb3400dc1 (6 hours ago), 2022-01-20 20:25:16 -0500
    • Engine revision cd65368f9d
    • Dart version 2.17.0 (build 2.17.0-31.0.dev)
    • DevTools version 2.9.2

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 14.4.1 18D61
    • macOS (desktop)           • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 97.0.4692.71

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

</details>

Can you try the same on latest master and confirm at your end ?

**Comment by golane-august** [comment]
Same behavior for channel `master`
```
flutter --version
Flutter 2.9.0-1.0.pre.401 • channel master • https://github.com/flutter/flutter.git
Framework • revision 114185f686 (5 days ago) • 2022-01-19 10:20:11 -0800
Engine • revision 31b1a1d058
Tools • Dart 2.17.0 (build 2.17.0-27.0.dev) • DevTools 2.9.2
```

On my other laptop (with Windows) it works fine, too (also Intel UHD Graphics 620). Maybe it depends on the OS. As far as I can see, the other issues were also executed with a Linux machine.

**Comment by maheshmnj** [comment]
HI @golane-august, I verified on ubuntu, OpenGL and WebGL are both enabled on stable and a master channel with both 
`-d chrome` and `-d web-server`. 

### Stable

<table>
<tr>
<td> flutter run -d chrome </td> <td> flutter run -d web-server </td>
</tr>
<tr>
<td>

```xml
Graphics Feature Status
Canvas: Hardware accelerated
Canvas out-of-process rasterization: Disabled
Compositing: Hardware accelerated
Multiple Raster Threads: Enabled
Out-of-process Rasterization: Disabled
OpenGL: Enabled
Rasterization: Software only. Hardware acceleration disabled
Raw Draw: Disabled
Skia Renderer: Enabled
Video Decode: Software only. Hardware acceleration disabled
Vulkan: Disabled
WebGL: Hardware accelerated
WebGL2: Hardware accelerated
```

</td>

<td>

```text
Graphics Feature Status
Canvas: Hardware accelerated
Canvas out-of-process rasterization: Disabled
Compositing: Hardware accelerated
Multiple Raster Threads: Enabled
Out-of-process Rasterization: Disabled
OpenGL: Enabled
Rasterization: Software only. Hardware acceleration disabled
Raw Draw: Disabled
Skia Renderer: Enabled
Video Decode: Software only. Hardware acceleration disabled
Vulkan: Disabled
WebGL: Hardware accelerated
WebGL2: Hardware accelerated
```

</td>
</tr>

</table>


### Master
<table>
<tr>
<td> flutter run -d chrome </td> <td> flutter run -d web-server </td>
</tr>
<tr>
<td>

```text
Graphics Feature Status
Canvas: Hardware accelerated
Canvas out-of-process rasterization: Disabled
Compositing: Hardware accelerated
Multiple Raster Threads: Enabled
Out-of-process Rasterization: Disabled
OpenGL: Enabled
Rasterization: Software only. Hardware acceleration disabled
Raw Draw: Disabled
Skia Renderer: Enabled
Video Decode: Software only. Hardware acceleration disabled
Vulkan: Disabled
WebGL: Hardware accelerated
WebGL2: Hardware accelerated
```

</td>

<td>

```text
Graphics Feature Status
Canvas: Hardware accelerated
Canvas out-of-process rasterization: Disabled
Compositing: Hardware accelerated
Multiple Raster Threads: Enabled
Out-of-process Rasterization: Disabled
OpenGL: Enabled
Rasterization: Software only. Hardware acceleration disabled
Raw Draw: Disabled
Skia Renderer: Enabled
Video Decode: Software only. Hardware acceleration disabled
Vulkan: Disabled
WebGL: Hardware accelerated
WebGL2: Hardware accelerated
```

</td>
</tr>

</table>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.8.1, on Ubuntu 20.04.3 LTS 5.11.0-43-generic, locale en_GB.UTF-8)
    • Flutter version 2.8.1 at /home/mahesh/Development/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (6 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/mahesh/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /home/mahesh/Downloads/android-studio-2020.3.1.25-linux/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/mahesh/Downloads/android-studio-2020.3.1.25-linux/android-studio
    • Flutter plugin version 63.2.1
    • Dart plugin version 203.8452
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.63.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.32.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.3 LTS 5.11.0-43-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 96.0.4664.110

• No issues found!
```

```
[✓] Flutter (Channel master, 2.9.0-1.0.pre.491, on Ubuntu 20.04.3 LTS 5.11.0-43-generic, locale en_GB.UTF-8)
    • Flutter version 2.9.0-1.0.pre.491 at /home/mahesh/Development/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7ec334827a (2 hours ago), 2022-01-24 19:50:10 -0800
    • Engine revision 83cfdcc8f1
    • Dart version 2.17.0 (build 2.17.0-51.0.dev)
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/mahesh/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /home/mahesh/Downloads/android-studio-2020.3.1.25-linux/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/mahesh/Downloads/android-studio-2020.3.1.25-linux/android-studio
    • Flutter plugin version 63.2.1
    • Dart plugin version 203.8452
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.63.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.32.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.3 LTS 5.11.0-43-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 96.0.4664.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by golane-august** [comment]
I now also tried it on my own Desktop-PC (Ubuntu 21.10) which has its own Nvidia Graphics Card. All went fine.
But then I turned of the External Graphics Card and switched to the Intel graphics (Intel® HD Graphics 530) via `sudo prime-select intel` and then the launching Chrome via `-d chrome` resulted in explicitely disabling OpenGL although OpenGL 4.5 is supported and works when launching Chrome as a user (or via `-d web-server`).

![Screenshot from 2022-01-25 11-08-25](https://user-images.githubusercontent.com/86839043/150959222-fba8b81b-e000-4501-9ba1-1118d2c91d34.png)

Tipp:
If Nvidia: do `sudo prime-select query` to first query the existing prime setting.
To switch to default again do `sudo prime-select on-demand` or `sudo prime-select nvidia`
https://wiki.ubuntuusers.de/Hybrid-Grafikkarten/PRIME/
I also had to change my BIOS settings in order to be able to switch to intel only.

**Comment by darshankawar** [comment]
@golane-august 
Thanks for digging in and providing further details. Based on it, it seems like this behavior is specific to external graphics card that comes with machine, ie, with Nvidia graphics card + Ubuntu, it shows the correct behavior, but after turning off external graphics card and switching to Intel + Ubuntu, it shows the behavior you originally reported. Is this a correct interpretation ?

**Comment by Gustl22** [comment]
I tested it on two different machines, one with an external graphics card and one without. Either way, without a dedicated graphics card, means Ubuntu + Intel, this behavior occurs.
So the external Nvidia doesn't play a role. Only wanted to confirm that the issue occurs, if only Intel Graphics is available.

**Comment by golane-august** [comment]
I tested it on two different machines, one with an external graphics card and one without. Either way, without a dedicated graphics card, means Ubuntu + Intel, this behavior occurs.
So the external Nvidia doesn't play a role in that sense. Only wanted to confirm that the issue occurs, if only Intel Graphics is available / enabled.

I think you tested it only with external Graphics Card enabled and not having a machine with only Intel Graphics respectively.

**Comment by rwrz** [comment]
I'm experiencing this exact same problem right now... everything was fine last week, but now it is happening.
The only way for it to work is using the `--web-renderer html` option. It has the hardware-enabled on a normal chrome session (user), but it is not working using a `flutter run -d chrome` (the hardware-accelerated option is enabled on both, but the WebGL seems to be disabled using flutter command).

BTW, I only have one graphics card, AMD RX 570, in an offboard motherboard and it is possible that the driver has been updated recently:
```
Radeon RX 570 Series (POLARIS10, DRM 3.42.0, 5.15.15-76051515-generic, LLVM 12.0.1)
```

I tried to start google-chrome using the same command line as flutter:
```shell
google-chrome --user-data-dir=/tmp/flutter_tools_chrome_device.OIBPLW --remote-debugging-port=42349 --disable-background-timer-throttling --disable-extensions --disable-popup-blocking --bwsi --no-first-run --no-default-brower-check --disable-default-apps --disable-translate --enable-crashpad http://localhost:7357
```
When using the SAME user-data-dir, while flutter is running, it will open a new tab, with the same problem. 
When I run the command after flutter exits, it runs a new window and it has WebGL support.

So, I think the problem may be flutter running a process "indirectly", not as the user (although the process owner is my user). Maybe something new on the Linux kernel, any kind of protection?

I could not find why running chrome over Flutter, disables the WebGL (btw, running with --disable-gpu, show the same results as running with flutter),. I also checked all the system logs, could not find anything related to the issue.
I have updated PopOS to 21.10 recently, but can't remember if it worked right after the update, but could be related.

Let me know if there is anything I can do to help.

<details>
  <summary>flutter doctor -v</summary>
  
```
[✓] Flutter (Channel stable, 2.8.1, on Pop!_OS 21.10 5.15.15-76051515-generic, locale en_US.UTF-8)
    • Flutter version 2.8.1 at /home/rwrz/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (6 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/rwrz/Android/Sdk/
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /home/rwrz/Android/Sdk/
    • Java binary at: /home/rwrz/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.7628.21.2111.8092744/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /home/rwrz/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.7628.21.2111.8092744
    • Flutter plugin version 63.2.2
    • Dart plugin version 211.7798
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 96.0.4664.110

• No issues found!
```
</details>

**Comment by darshankawar** [comment]
> I think you tested it only with external Graphics Card enabled and not having a machine with only Intel Graphics respectively.

My machine has Intel graphics card:

<img width="266" alt="Screenshot 2022-01-27 at 11 14 26 AM" src="https://user-images.githubusercontent.com/67046386/151299101-d5d1a304-9447-4fd1-8cf1-c003afe0b4c3.png">

It seems to be happening on Linux platform that too with canvaskit rendering as mentioned by @rwrz that with html rendering, it seems to be working as expected. Since we are unable to replicate this based on our findings, I am going ahead and labeling it based on above comments and for further insights from web team.

**Comment by DanielArndt** [comment]
I have this same issue. Everything works great if I use `flutter run -d web-server` and connect manually with the browser, but `flutter run -d chrome` causes WebGL to be disabled as described above, and the Flutter Demo app doesn't load properly.

This is my first attempt at using Flutter. I'll do my best to provide useful information.

I am on `stable`, not `master`

```
$ flutter --version                                                            
Flutter 2.8.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 77d935af4d (6 weeks ago) • 2021-12-16 08:37:33 -0800
Engine • revision 890a5fca2e
Tools • Dart 2.15.1
```

OS: Ubuntu 21.10
Hardware:
```
$ inxi -G
Graphics:
  Device-1: Intel TigerLake-LP GT2 [Iris Xe Graphics] driver: i915 v: kernel 
  [...snip irrelevant output...]
  driver: snd-usb-audio,uvcvideo 
  Display: wayland server: X.Org 1.21.1.2 driver: loaded: modesetting 
  unloaded: fbdev,vesa resolution: 1: 3840x2160~60Hz 2: 3840x2160~60Hz 
  OpenGL: renderer: Mesa Intel Xe Graphics (TGL GT2) v: 4.6 Mesa 21.2.2 
```

**Comment by ditman** [comment]
Quick question for everybody on this issue:

**What version of Chrome are you seeing this problem on?**

The fact that somebody is seeing the issue and others aren't is maybe because of different channels of Chrome available to people. For example, [this bug may be related](https://github.com/OSSystems/meta-browser/issues/599).

**Comment by DanielArndt** [comment]
@ditman I'm seeing this on `Version 98.0.4758.80 (Official Build) (64-bit)`

**Comment by rwrz** [comment]
**[WORKAROUND]**
Since I wasn't very clear on my statement, there is a **workaround** you can do until it gets fixed:

1. Start your app as you usually do.
2. After chrome starts, get the URL it started, ex: `http://localhost:7357`
3. **Leave it open** and then open another "chromium" instance running this command:

```shell
rm -rf /tmp/flutter_tmp_workaround && google-chrome --user-data-dir=/tmp/flutter_tmp_workaround --remote-debugging-port=42349 --disable-background-timer-throttling --disable-extensions --disable-popup-blocking --bwsi --no-first-run --no-default-brower-check --disable-default-apps --disable-translate --enable-crashpad URL_FROM_STEP_2
```

It should work as before, including all debug tools.
The main goal here is to keep the flutter process running (with OpenGL issues), but then open another instance of chromium without WebGL issues.
As I mentioned earlier, for some reason, **opening a chromium instance managed by flutter doesn't work**, but if you open another instance yourself (with different user-data-dir), it will work.

Notes:
- I'm using a temp folder `/tmp/flutter_tmp_workaround`, feel free to change it
- I've added the `rm -rf .. &&` to ensure you open a new instance every time, cleaning the previous temp folder
- You may need to use a different executable ("google-chrome") depending on your distro, chrome version (beta/canary) or chrome location
- You can have a static URL by adding the params: `--web-hostname localhost --web-port 7357`

**Comment by ditman** [comment]
@rwrz I think you can get a faster workaround by running: `flutter run -d web-server`? That way flutter will *not* start any Chrome, it'll just give you a hostname and port that you can point any browser to (and that you can override as described on your message above):

```
flutter run -d web-server --web-hostname localhost --web-port 7357
```

**Comment by PaulRudin** [comment]
I am seeing this with chrome 97.0.4692.71 (Official Build) (64-bit) - linux.

**Comment by rwrz** [comment]
It is working again using Flutter 2.10.2 and Chrome Version 98.0.4758.102 (Official Build) (64-bit).

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.10.2, on Pop!_OS 21.10 5.15.23-76051523-generic, locale en_US.UTF-8)
    • Flutter version 2.10.2 at /home/rwrz/Libraries/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (12 days ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/rwrz/Android/Sdk/
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /home/rwrz/Android/Sdk/
    • Java binary at:
      /home/rwrz/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.7628.21.2111.8193401/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 13.0.0-2
    • cmake version 3.18.4
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.1)
    • Android Studio at /home/rwrz/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.7628.21.2111.8193401
    • Flutter plugin version 65.0.2
    • Dart plugin version 211.7798
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] Connected device (3 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64    • Android 9 (API 28) (emulator)
    • Linux (desktop)                       • linux         • linux-x64      • Pop!_OS 21.10 5.15.23-76051523-generic
    • Chrome (web)                          • chrome        • web-javascript • Google Chrome 98.0.4758.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

**Comment by DanielArndt** [comment]
@rwrz Interesting that you would report that, since it still does not work for me with the same versions of Flutter and Chrome.

flutter doctor -v
```
[✓] Flutter (Channel stable, 2.10.2, on Ubuntu 21.10 5.13.0-30-generic, locale en_CA.UTF-8)
    • Flutter version 2.10.2 at /home/darndt/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (13 days ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/darndt/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /home/darndt/Applications/android-studio-2021.1.1.20-linux/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.1)
    • Android Studio at /home/darndt/Applications/android-studio-2021.1.1.20-linux/android-studio
    • Flutter plugin version 65.0.2
    • Dart plugin version 211.7798
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1426:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1861:10)
      #15     runZonedGuarded (dart:async/zone.dart:1849:12)
      #16     runZoned (dart:async/zone.dart:1780:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:205:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:309:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.64.2)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Linux (desktop)              • linux         • linux-x64      • Ubuntu 21.10 5.13.0-30-generic
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 98.0.4758.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

**Comment by rwrz** [comment]
Hmmm... I think I got it!
I was using snapd version of Flutter but since I wanted to try the "Linux build" and one of my packages had issues with the snapd version, I switched to manual installation.

@DanielArndt, could you try to switch to manual installation as well?
I think it makes sense, since snapd does a [partial sandbox](https://snapcraft.io/docs/security-sandboxing) to flutter, possibly blocking some resources (like GPU).

Maybe the flutter team needs to tweak the snap release to allow chrome + GPU access? 
Well, try it first, then we will see if this is the right path to go.

**Comment by DanielArndt** [comment]
@rwrz You are correct, it does appear to work fine with a manual install instead of using the snap package.

**Comment by ditman** [comment]
> I was using snapd version of Flutter but since I wanted to try the "Linux build" and one of my packages had issues with the snapd version, I switched to [manual installation](https://docs.flutter.dev/get-started/install/linux#install-flutter-manually).
>
> @DanielArndt, could you try to switch to manual installation as well?
I think it makes sense, since snapd does a [partial sandbox](https://snapcraft.io/docs/security-sandboxing) to flutter, possibly blocking some resources (like GPU).

Wow, great investigation @rwrz, I'll try to find the right person to handle this!

**Comment by ditman** [comment]
I've created this issue in Canonical's flutter-snap repo: https://github.com/canonical/flutter-snap/issues/74 to see if they can offer some extra insight!

**Comment by ditman** [comment]
@ranvirsahota any chance you can provide the command-line invocations for the chrome process that is being spawned by opening it manually in your web-server case vs when flutter run opens the browser? You may be able to figure the complete command used with `ps -ef | grep chrome` or similar.
