### ISSUE TITLE
WebSocketException: Connection to 'http://127.0.0.1:xxxxx/=xxxxxx/#' was not upgraded to websocket

### ISSUE THREAD

**Issue by ProgUser145** [flutter/flutter#96942]
I am trying to connect to a websocket without any success. It gives the error below: 

1. flutter run

```
flutter: WebSocketException: Connection to http://127.0.0.1:xxxxx/=xxxxxx/# was not upgraded to websocket
flutter: #0      _WebSocketImpl.connect (dart:_http/websocket_impl.dart:1011:41)
#1      WebSocket.connect (dart:_http/websocket.dart:360:22)
#2      vmServiceConnectUri (package:vm_service/vm_service_io.dart:32:44)

```

The only issue of this type raised before that I found was [here](https://github.com/flutter/flutter/issues/11444). However, that issue was closed without any solution provided.

```
❯ flutter analyze
Analyzing ios...                                                        
No issues found! (ran in 1.2s)

```

```
❯ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.0.1 21A559 darwin-arm)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.63.2)
[✓] Connected device (3 available)

• No issues found!

```

**Comment by darshankawar** [comment]
@ProgUser145 
Can you provide a minimal reproducible code sample that shows this exception ?

**Comment by ProgUser145** [comment]
It was a problem in my configurations. Thank you for your prompt response
