### ISSUE TITLE
OverlayState created a Ticker via its TickerProviderStateMixin, but at the time dispose() was called on the mixin, that Ticker was still active

### ISSUE THREAD

**Issue by cedvdb** [flutter/flutter#96971]
Happens in unit tests when calling the following:

```dart
    return showModalBottomSheet<T>(
      context: context,
      builder: builder,
    );
```

Works fine with normal bottom  sheet

```dart
    final controller = material.showBottomSheet<T>(
      context: context,
      builder: builder,
    );
 ```

There is not a single instance of `TickerProviderStateMixin` used in the code base, so the error message is a bit misleading or it's an issue with flutter.

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
OverlayState#e915d(tickers: tracking 1 ticker, entries: [OverlayEntry#757eb(opaque: true;
maintainState: false), OverlayEntry#dbca9(opaque: false; maintainState: true),
OverlayEntry#a9cbc(opaque: false; maintainState: false), OverlayEntry#f1d7e(opaque: false;
maintainState: true)]) was disposed with an active Ticker.
OverlayState created a Ticker via its TickerProviderStateMixin, but at the time dispose() was called
on the mixin, that Ticker was still active. All Tickers must be disposed before calling
super.dispose().
Tickers used by AnimationControllers should be disposed by calling dispose() on the
AnimationController itself. Otherwise, the ticker will leak.
The offending ticker was:
  _WidgetTicker(created by OverlayState#e915d)
  The stack trace when the _WidgetTicker was actually created was:
  #0      new Ticker.<anonymous closure> (package:flutter/src/scheduler/ticker.dart:67:40)
  #1      new Ticker (package:flutter/src/scheduler/ticker.dart:69:6)
  #2      new _WidgetTicker (package:flutter/src/widgets/ticker_provider.dart:271:81)
  #3      TickerProviderStateMixin.createTicker
  (package:flutter/src/widgets/ticker_provider.dart:202:34)
  #4      new AnimationController (package:flutter/src/animation/animation_controller.dart:246:21)
  #5      BottomSheet.createAnimationController
  (package:flutter/src/material/bottom_sheet.dart:193:12)
  #6      _ModalBottomSheetRoute.createAnimationController
  (package:flutter/src/material/bottom_sheet.dart:511:42)
  #7      TransitionRoute.install (package:flutter/src/widgets/routes.dart:217:19)
  #8      ModalRoute.install (package:flutter/src/widgets/routes.dart:1143:11)
  #9      _RouteEntry.handlePush (package:flutter/src/widgets/navigator.dart:2833:11)
  #10     NavigatorState._flushHistoryUpdates (package:flutter/src/widgets/navigator.dart:3804:17)
  #11     NavigatorState._pushEntry (package:flutter/src/widgets/navigator.dart:4395:5)
  #12     NavigatorState.push (package:flutter/src/widgets/navigator.dart:4323:5)
  #13     showModalBottomSheet (package:flutter/src/material/bottom_sheet.dart:695:20)
```

# Reproduction

I do not have a small reproduction (and won't). Still opening for others that might provide one.

Flutter 2.8.1 • channel stable

**Comment by cedvdb** [comment]
Solved by this commit 

https://github.com/flutter/flutter/commit/d77bc51856606551dab3758e0ff866c8a5c4a7d9#diff-89f99a1415c93b2ce9493851c5f7f115752b7af86fa3a414428afccbff660fba
