### ISSUE TITLE
[tool_crash] StateError: Bad state: Future already completed

### ISSUE THREAD

**Issue by mark-apn** [flutter/flutter#96988]
## Steps to Reproduce

When running my Flutter web app in a mobile browser. I get the following error.

![image](https://user-images.githubusercontent.com/62654433/150496352-510349d9-5fd4-4ccf-83a4-800491ef8e86.png)

After digging around in debug mode (-d web-server on mac and connecting to the debug session on mobile) I found the bug in debug mode. 

![image](https://user-images.githubusercontent.com/62654433/150500333-5fb67b12-4863-49d4-ad7a-08c7c59e067c.png)

Searching for old tickets I found this duplicate (https://github.com/flutter/flutter/issues/94193). Hope we can get to the bottom of this. I'll provide as many logs as you need :-)

```dart
StateError: Bad state: Future already completed

#0      _AsyncCompleter.complete (dart:async/future_impl.dart:45:31)
#1      WebDevFS.connect.<anonymous closure> (package:flutter_tools/src/isolated/devfs_web.dart:691:16)
```
## Logs

<details>
<summary>Crash report from web-server</summary>

Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

```
flutter run --machine --start-paused -d chrome --dart-define=flutter.inspector.structuredErrors=true --web-allow-expose-url --devtools-server-address http://127.0.0.1:9100/ --target lib/main.dart -d web-server
```

## exception

StateError: Bad state: Future already completed

```
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:45:31)
#1      WebDevFS.connect.<anonymous closure> (package:flutter_tools/src/isolated/devfs_web.dart:691:16)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.2 21D5039d darwin-x64, locale en-GB)
    • Flutter version 2.8.1 at /Users/mark/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (5 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/mark/Library/Android/sdk
    • Platform android-31, build-tools 30.0.2
    • ANDROID_HOME = /Users/mark/Library/Android/sdk
    • Java binary at: /Users/mark/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7351085/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Users/mark/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7351085/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/mark/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7199119/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 97.0.4692.99
    ! Error: iPad is busy: Fetching debug symbols for iPad. Xcode will continue when iPad is finished. (code -10)

• No issues found!
```

</details>

<details>
<summary>Separate flutter doctor -v output</summary>

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.2 21D5039d darwin-x64, locale en-GB)
    • Flutter version 2.8.1 at /Users/mark/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (5 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/mark/Library/Android/sdk
    • Platform android-31, build-tools 30.0.2
    • ANDROID_HOME = /Users/mark/Library/Android/sdk
    • Java binary at: /Users/mark/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7351085/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Users/mark/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7351085/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/mark/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7199119/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.2 21D5039d darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 97.0.4692.99

• No issues found!

```

</details>

**Comment by mark-apn** [comment]
After looking at the source of [`devfs_web.dart`](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/isolated/devfs_web.dart). I think both errors above are unrelated. 

Im trying to debug on my Android mobile phone using `flutter run -d web-server` and connecting to the server via an ngrok tunnel. After reading what the devfs_web.dart is about I think my debug session is not setup correctly and I'm erroring out before reaching the original error im trying to catch.

Is there a better way to setup such a Flutter web debug session on an actual device?
(See comment for actual setup: https://github.com/flutter/flutter/issues/96978)

**Comment by maks** [comment]
As I reported in #108852 I'm seeing this as well, though in my case I was simply trying to debug the app in VSCode and open the app's url in a Chrome window running with a specific Chrome user profile vs the "clean" profile that's used when you run with `flutter run -d chrome`.

Also happy to provide more info to help debug this.

**Comment by christopherfujino** [comment]
> As I reported in #108852 I'm seeing this as well, though in my case I was simply trying to debug the app in VSCode and open the app's url in a Chrome window running with a specific Chrome user profile vs the "clean" profile that's used when you run with `flutter run -d chrome`.
> 
> Also happy to provide more info to help debug this.

@maks thanks for the details, this will be helpful in root causing this issue!

**Comment by christopherfujino** [comment]
Copying a newer stacktrace from https://github.com/flutter/flutter/issues/108852 on version 3.0.5:

```
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:35:31)
#1      WebDevFS.connect.<anonymous closure> (package:flutter_tools/src/isolated/devfs_web.dart:696:16)
<asynchronous suspension>
```

Which is completing a Completer a few lines after checking that it was not completed--this must be a race condition: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/isolated/devfs_web.dart#L704
