### ISSUE TITLE
Recipe roll failing due to bot_update getting bytes

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#97002]
https://flutter-review.googlesource.com/c/recipes/+/25641

```
Traceback (most recent call last):
  File "C:\b\s\w\ir\kitchen-checkout\depot_tools\recipes\recipe_modules\bot_update\resources\bot_update.py", line 1225, in <module>
    sys.exit(main())
  File "C:\b\s\w\ir\kitchen-checkout\depot_tools\recipes\recipe_modules\bot_update\resources\bot_update.py", line 1209, in main
    checkout(options, git_slns, specs, revisions, step_text)
  File "C:\b\s\w\ir\kitchen-checkout\depot_tools\recipes\recipe_modules\bot_update\resources\bot_update.py", line 1111, in checkout
    synced_solutions = ensure_checkout(**checkout_parameters)
  File "C:\b\s\w\ir\kitchen-checkout\depot_tools\recipes\recipe_modules\bot_update\resources\bot_update.py", line 648, in wrapper
    return fn(*args, **kwargs)
  File "C:\b\s\w\ir\kitchen-checkout\depot_tools\recipes\recipe_modules\bot_update\resources\bot_update.py", line 838, in ensure_checkout
    synced_solutions = git_checkouts(
  File "C:\b\s\w\ir\kitchen-checkout\depot_tools\recipes\recipe_modules\bot_update\resources\bot_update.py", line 658, in git_checkouts
    did_sync = _git_checkout(
  File "C:\b\s\w\ir\kitchen-checkout\depot_tools\recipes\recipe_modules\bot_update\resources\bot_update.py", line 705, in _git_checkout
    git(*populate_cmd)
  File "C:\b\s\w\ir\kitchen-checkout\depot_tools\recipes\recipe_modules\bot_update\resources\bot_update.py", line 278, in git
    return call(*cmd, **kwargs)
  File "C:\b\s\w\ir\kitchen-checkout\depot_tools\recipes\recipe_modules\bot_update\resources\bot_update.py", line 234, in call
    buf = '\r' + buf
TypeError: can only concatenate str (not "bytes") to str
```

This seems to be a windows specific issues

**Comment by yusuf-goog** [comment]
This is potentially due to p2 vs py3 differences in handling of bytes and strs. 

Depending on args to subprocess.Popen, `buf` could be bytes or str, which will cause issues with trying to concatenate the str to bytes if (e.g. '\r' + buf).

buf would needed to be decoded if its a byte stream.

**Comment by yusuf-goog** [comment]
As per @CaseyHillers , looks like the error is due to a py3 issue.

The change was was reverted: https://source.chromium.org/chromium/chromium/tools/depot_tools/+/6bfbe35cce2380773e38bd622b35caed86d8aec0

So closing this issue.
