### ISSUE TITLE
google_maps_flutter W/System: A resource failed to call release. 

### ISSUE THREAD

**Issue by RamsayGit** [flutter/flutter#97008]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Tap on the map action button at the bottom right
3. Once on the map screen, tap the back button at the top left
4. Repeat from step 2 several times until a 'A resource failed to call release' message appears in the console.

**Expected results:** 
No error message should be shown in console

**Actual results:** 
'A resource failed to call release' message is shown in console. In order to get more details I enabled strict mode by following this guide [https://stackoverflow.com/questions/66290732/how-to-identify-what-is-accessing-hidden-methods](url) and I obtained the detailed log shown below in the log section.

<details>
<summary>Code sample</summary>

**dependencies:**
google_maps_flutter: ^2.1.1 [https://pub.dev/packages/google_maps_flutter](url)

**Set the minSdkVersion in android/app/build.gradle:**
```
android {
    defaultConfig {
        minSdkVersion 20
    }
}
```

**Specify your API key in the application manifest android/app/src/main/AndroidManifest.xml:**
```
<manifest ...
  <application ...
    <meta-data android:name="com.google.android.geo.API_KEY"
               android:value="YOUR KEY HERE"/>
```

**Main:**
```
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:memory_leak_bug/map_screen.dart';
import 'package:memory_leak_bug/textScreen.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  MyApp({Key? key}) : super(key: key) {
    if (defaultTargetPlatform == TargetPlatform.android) {
      AndroidGoogleMapsFlutter.useAndroidViewSurface = true;
    }
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      initialRoute: TextScreen.routeName,
      routes: {
        TextScreen.routeName: (context) => const TextScreen(),
        MapScreen.routeName: (context) => const MapScreen(),
      },
    );
  }
}
```

**First page:**
```
import 'package:flutter/material.dart';
import 'package:memory_leak_bug/map_screen.dart';

class TextScreen extends StatefulWidget {
  static const routeName = '/text';

  const TextScreen({Key? key}) : super(key: key);

  @override
  State<TextScreen> createState() => _TextScreenState();
}

class _TextScreenState extends State<TextScreen> {
  @override
  Widget build(BuildContext context) {
    var scaffold = Scaffold(
      body: const Padding(
        padding: EdgeInsets.all(30.0),
        child: Center(
          child: TextField(
            autofocus: true,
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => Navigator.pushNamed(context, MapScreen.routeName),
        child: const Icon(Icons.location_on),
      ),
    );

    return scaffold;
  }
}
```
**Second page:**
```
import 'dart:async';
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

class MapScreen extends StatefulWidget {
  static const routeName = '/map';

  const MapScreen({Key? key}) : super(key: key);

  @override
  State<MapScreen> createState() => _MapScreenState();
}

class _MapScreenState extends State<MapScreen> {
  GoogleMapController? _mapController;
  final Completer<GoogleMapController> _mapControllerCompleter =
      Completer<GoogleMapController>();
  late double _screenHeight;

  @override
  void initState() {
    super.initState();
  }

  @override
  void didChangeDependencies() {
    _screenHeight = MediaQuery.of(context).size.height;
    super.didChangeDependencies();
  }

  @override
  void dispose() {
    _mapController?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: [
        GoogleMap(
          onMapCreated: (controller) {
            _mapControllerCompleter.complete(controller);
          },
          initialCameraPosition: const CameraPosition(
            target: LatLng(0, 0),
          ),
        ),
        Positioned(
            top: 50,
            left: 20,
            child: ElevatedButton(
              child: const Icon(Icons.arrow_back),
              onPressed: () => Navigator.pop(context),
            ))
      ],
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
E/STRICTMODE: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
        at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1987)
        at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:345)
        at android.view.Surface.finalize(Surface.java:310)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:291)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:278)
        at java.lang.Daemons$Daemon.run(Daemons.java:139)
        at java.lang.Thread.run(Thread.java:920)
     Caused by: java.lang.Throwable: Explicit termination method 'release' not called
        at dalvik.system.CloseGuard.openWithCallSite(CloseGuard.java:295)
        at dalvik.system.CloseGuard.open(CloseGuard.java:263)
        at android.view.Surface.setNativeObjectLocked(Surface.java:758)
        at android.view.Surface.<init>(Surface.java:302)
        at android.media.ImageReader.nativeGetSurface(Native Method)
        at android.media.ImageReader.<init>(ImageReader.java:308)
        at android.media.ImageReader.newInstance(ImageReader.java:258)
        at io.flutter.embedding.android.FlutterImageView.createImageReader(FlutterImageView.java:115)
        at io.flutter.embedding.android.FlutterImageView.<init>(FlutterImageView.java:74)
        at io.flutter.plugin.platform.PlatformViewsController.createOverlaySurface(PlatformViewsController.java:960)
        at io.flutter.embedding.engine.FlutterJNI.createOverlaySurface(FlutterJNI.java:1090)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loopOnce(Looper.java:161)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

```
info - The value of the field '_screenHeight' isn't used - lib\map_screen.dart:18:15 - unused_field
info - Name source files using `lowercase_with_underscores` - lib\textScreen.dart:1:1 - file_names
```

```
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.22000.376], locale en-US)
    • Flutter version 2.8.1 at C:\Users\ramsa\Documents\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (5 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\ramsa\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[☠] IntelliJ IDEA Ultimate Edition (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    X FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:318:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[√] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 32) (emulator)
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 

! Doctor found issues in 1 category.
```

</details>

https://user-images.githubusercontent.com/3251763/150558454-3713eeb0-619d-47e8-b809-e9402af3bc51.mp4

**Comment by maheshmnj** [comment]
Hi @RamsayGit, Thanks for filing the issue. I was able to see the same message in the console on the stable channel but does not reproduce on `master  2.9.0-1.0.pre.427`. You may switch to master channel by running 

```
flutter channel master
flutter upgrade
```
and verify this issue.

> A resource failed to call release

 
<details>
<summary>logs</summary>

```
Restarted application in 2,460ms.
D/MIUIInput( 6454): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=698011559, downTime=698011559 } moveCount:0
D/MIUIInput( 6454): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=698011641, downTime=698011559 } moveCount:0
I/Google Maps Android API( 6454): Google Play services package version: 214815037
I/Google Maps Android API( 6454): Google Play services maps renderer version(legacy): 203115000
E/GoogleMapController( 6454): Cannot enable MyLocation layer as location permissions are not granted
W/RenderInspector( 6454): DequeueBuffer time out on com.example.routes_issue/com.example.routes_issue.MainActivity, count=1, avg=17 ms, max=17 ms.
D/MIUIInput( 6454): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=698013326, downTime=698013326 } moveCount:0
D/MIUIInput( 6454): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=698013401, downTime=698013326 } moveCount:0
W/IInputConnectionWrapper( 6454): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 6454): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 6454): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper( 6454): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper( 6454): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 6454): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 6454): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 6454): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 6454): endBatchEdit on inactive InputConnection
D/MIUIInput( 6454): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=698014430, downTime=698014430 } moveCount:0
D/MIUIInput( 6454): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=698014488, downTime=698014430 } moveCount:0
I/Google Maps Android API( 6454): Google Play services package version: 214815037
I/Google Maps Android API( 6454): Google Play services maps renderer version(legacy): 203115000
E/GoogleMapController( 6454): Cannot enable MyLocation layer as location permissions are not granted
W/System  ( 6454): A resource failed to call release.
I/Counters( 6454): exceeded sample count in FrameTime
I/chatty  ( 6454): uid=10985(com.example.routes_issue) androidmapsapi- identical 21 lines
I/Counters( 6454): exceeded sample count in FrameTime
D/MIUIInput( 6454): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=698015914, downTime=698015914 } moveCount:0
D/MIUIInput( 6454): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=698015997, downTime=698015914 } moveCount:0
W/IInputConnectionWrapper( 6454): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 6454): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 6454): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper( 6454): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper( 6454): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 6454): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 6454): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 6454): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 6454): endBatchEdit on inactive InputConnection
I/Counters( 6454): exceeded sample count in FrameTime
I/chatty  ( 6454): uid=10985(com.example.routes_issue) androidmapsapi- identical 3 lines
I/Counters( 6454): exceeded sample count in FrameTime
D/MIUIInput( 6454): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=698017133, downTime=698017133 } moveCount:0
D/MIUIInput( 6454): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=698017224, downTime=698017133 } moveCount:0
I/Google Maps Android API( 6454): Google Play services package version: 214815037
I/Google Maps Android API( 6454): Google Play services maps renderer version(legacy): 203115000
E/GoogleMapController( 6454): Cannot enable MyLocation layer as location permissions are not granted
I/Counters( 6454): exceeded sample count in FrameTime
I/Counters( 6454): exceeded sample count in FrameTime
W/System  ( 6454): A resource failed to call release.
I/Counters( 6454): exceeded sample count in FrameTime
I/chatty  ( 6454): uid=10985(com.example.routes_issue) androidmapsapi- identical 2 lines
I/Counters( 6454): exceeded sample count in FrameTime
I/Counters( 6454): exceeded sample count in FrameTime
I/chatty  ( 6454): uid=10985(com.example.routes_issue) androidmapsapi- identical 14 lines
I/Counters( 6454): exceeded sample count in FrameTime
I/Counters( 6454): exceeded sample count in FrameTime
I/chatty  ( 6454): uid=10985(com.example.routes_issue) androidmapsapi- identical 11 lines
I/Counters( 6454): exceeded sample count in FrameTime
D/MIUIInput( 6454): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=698023638, downTime=698023638 } moveCount:0
D/MIUIInput( 6454): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=698023713, downTime=698023638 } moveCount:0
W/IInputConnectionWrapper( 6454): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 6454): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 6454): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper( 6454): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper( 6454): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 6454): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 6454): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 6454): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 6454): endBatchEdit on inactive InputConnection
I/Counters( 6454): exceeded sample count in FrameTime
I/chatty  ( 6454): uid=10985(com.example.routes_issue) androidmapsapi- identical 1 line
I/Counters( 6454): exceeded sample count in FrameTime
D/MIUIInput( 6454): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=698024740, downTime=698024740 } moveCount:0
D/MIUIInput( 6454): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=698024789, downTime=698024740 } moveCount:0
I/Google Maps Android API( 6454): Google Play services package version: 214815037
I/Google Maps Android API( 6454): Google Play services maps renderer version(legacy): 203115000
E/GoogleMapController( 6454): Cannot enable MyLocation layer as location permissions are not granted
I/Counters( 6454): exceeded sample count in FrameTime
I/Counters( 6454): exceeded sample count in FrameTime
W/System  ( 6454): A resource failed to call release.
I/Counters( 6454): exceeded sample count in FrameTime
I/chatty  ( 6454): uid=10985(com.example.routes_issue) androidmapsapi- identical 1 line
I/Counters( 6454): exceeded sample count in FrameTime
I/Counters( 6454): exceeded sample count in FrameTime
I/Counters( 6454): exceeded sample count in FrameTime
I/chatty  ( 6454): uid=10985(com.example.routes_issue) androidmapsapi- identical 28 lines
I/Counters( 6454): exceeded sample count in FrameTime
D/MIUIInput( 6454): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=698025694, downTime=698025694 } moveCount:0
D/MIUIInput( 6454): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=698025769, downTime=698025694 } moveCount:0
W/IInputConnectionWrapper( 6454): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 6454): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 6454): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper( 6454): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper( 6454): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 6454): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 6454): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 6454): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 6454): endBatchEdit on inactive InputConnection
I/Counters( 6454): exceeded sample count in FrameTime
I/Counters( 6454): exceeded sample count in FrameTime
I/chatty  ( 6454): uid=10985(com.example.routes_issue) androidmapsapi- identical 2 lines
I/Counters( 6454): exceeded sample count in FrameTime
D/MIUIInput( 6454): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=698026693, downTime=698026693 } moveCount:0
D/MIUIInput( 6454): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=698026768, downTime=698026693 } moveCount:0
I/Google Maps Android API( 6454): Google Play services package version: 214815037
I/Google Maps Android API( 6454): Google Play services maps renderer version(legacy): 203115000
E/GoogleMapController( 6454): Cannot enable MyLocation layer as location permissions are not granted
W/System  ( 6454): A resource failed to call release.
I/Counters( 6454): exceeded sample count in FrameTime
I/Counters( 6454): exceeded sample count in FrameTime
I/chatty  ( 6454): uid=10985(com.example.routes_issue) androidmapsapi- identical 8 lines
I/Counters( 6454): exceeded sample count in FrameTime
I/Counters( 6454): exceeded sample count in FrameTime
I/chatty  ( 6454): uid=10985(com.example.routes_issue) androidmapsapi- identical 21 lines
I/Counters( 6454): exceeded sample count in FrameTime
D/MIUIInput( 6454): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=698028408, downTime=698028408 } moveCount:0
D/MIUIInput( 6454): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=698028483, downTime=698028408 } moveCount:0
W/IInputConnectionWrapper( 6454): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 6454): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 6454): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper( 6454): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper( 6454): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 6454): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 6454): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 6454): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 6454): endBatchEdit on inactive InputConnection
I/Counters( 6454): exceeded sample count in FrameTime
I/chatty  ( 6454): uid=10985(com.example.routes_issue) androidmapsapi- identical 4 lines
I/Counters( 6454): exceeded sample count in FrameTime
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.8.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.3:5555                     • android-arm64  • Android 11 (API 30)
    • iPhone 13 Pro (mobile) • 0FA2FB93-2A89-4FDB-8293-DF66188F1E54 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0
      (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 96.0.4664.110

• No issues found!
```

```
[✓] Flutter (Channel master, 2.9.0-1.0.pre.427, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.9.0-1.0.pre.427 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6eb3400dc1 (3 days ago), 2022-01-20 20:25:16 -0500
    • Engine revision cd65368f9d
    • Dart version 2.17.0 (build 2.17.0-31.0.dev)
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • 192.168.1.3:5555 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos            • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 97.0.4692.99

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>
