### ISSUE TITLE
Multiple linux/android tests are flaky on devicelab linux12

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#97023]
Flake happened on four builders:

[ Linux_android fading_child_animation_perf__timeline_summary ](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_android%20fading_child_animation_perf__timeline_summary/265/overview)
[Linux_android backdrop_filter_perf__e2e_summary](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_android%20backdrop_filter_perf__e2e_summary/1535/overview)
[Linux_android cull_opacity_perf__e2e_summary ](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_android%20cull_opacity_perf__e2e_summary/1522/overview)
The above three builds all hit:
```
[  +16 ms] Gradle task assembleProfile failed with exit code 1
[backdrop_filter_perf__e2e_summary] [STDOUT] stderr: [   +1 ms] 
[backdrop_filter_perf__e2e_summary] [STDOUT] stderr:            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
[backdrop_filter_perf__e2e_summary] [STDOUT] stderr:            #1      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:400:9)
[backdrop_filter_perf__e2e_summary] [STDOUT] stderr:            <asynchronous suspension>
[backdrop_filter_perf__e2e_summary] [STDOUT] stderr:            #2      AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:179:5)
[backdrop_filter_perf__e2e_summary] [STDOUT] stderr:            <asynchronous suspension>
[backdrop_filter_perf__e2e_summary] [STDOUT] stderr:            #3      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:578:7)
[backdrop_filter_perf__e2e_summary] [STDOUT] stderr:            <asynchronous suspension>
[backdrop_filter_perf__e2e_summary] [STDOUT] stderr:            #4      FlutterDriverService.start (package:flutter_tools/src/drive/drive_service.dart:179:16)
[backdrop_filter_perf__e2e_summary] [STDOUT] stderr:            <asynchronous suspension>
[backdrop_filter_perf__e2e_summary] [STDOUT] stderr:            #5      DriveCommand.runCommand (package:flutter_tools/src/commands/drive.dart:242:9)
[backdrop_filter_perf__e2e_summary] [STDOUT] stderr:            <asynchronous suspension>
```
[ Linux_android analyzer_benchmark  ](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_android%20analyzer_benchmark/1459/overview)  
Timeout on this build.

**Comment by keyonghan** [comment]
Issues happen only on linux12, manually quarantined for now.

/cc @blasten Do you have any insight regarding the gradle failures, which happened only on linux12?

**Comment by keyonghan** [comment]
[Cl/4524117](https://chrome-internal-review.googlesource.com/c/infradata/config/+/4524117) to move the bot to staging for further triage/validation.

**Comment by keyonghan** [comment]
Removed the quarantine file to let the bot run in staging.

**Comment by godofredoc** [comment]
```
[cull_opacity_perf__e2e_summary] [STDOUT] stdout: [        ] Caused by: javax.crypto.AEADBadTagException: Tag mismatch!
[cull_opacity_perf__e2e_summary] [STDOUT] stdout: [        ] 	at com.sun.crypto.provider.GaloisCounterMode.decryptFinal(GaloisCounterMode.java:578)
[cull_opacity_perf__e2e_summary] [STDOUT] stdout: [        ] 	at com.sun.crypto.provider.CipherCore.finalNoPadding(CipherCore.java:1116)
[cull_opacity_perf__e2e_summary] [STDOUT] stdout: [        ] 	at com.sun.crypto.provider.CipherCore.fillOutputBuffer(CipherCore.java:1053)
[cull_opacity_perf__e2e_summary] [STDOUT] stdout: [        ] 	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:941)
[cull_opacity_perf__e2e_summary] [STDOUT] stdout: [        ] 	at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:491)
[cull_opacity_perf__e2e_summary] [STDOUT] stdout: [        ] 	at javax.crypto.Cipher.doFinal(Cipher.java:2376)
[cull_opacity_perf__e2e_summary] [STDOUT] stdout: [        ] 	at sun.security.ssl.CipherBox.decrypt(CipherBox.java:461)
[cull_opacity_perf__e2e_summary] [STDOUT] stdout: [        ] 	at sun.security.ssl.InputRecord.decrypt(InputRecord.java:172)
[cull_opacity_perf__e2e_summary] [STDOUT] stdout: [        ] 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1017)
[cull_opacity_perf__e2e_summary] [STDOUT] stdout: [        ] 	... 156 more
[cull_opacity_perf__e2e_summary] [STDOUT] stdout: [        ] "Install Android SDK Platform 31 (revision: 1)" failed.
[cull_opacity_perf__e2e_summary] [STDOUT] stdout: [        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[cull_opacity_perf__e2e_summary] [STDOUT] stdout: [        ] Use '--warning-mode all' to show the individual deprecation warnings.
[cull_opacity_perf__e2e_summary] [STDOUT] stderr: [        ] FAILURE: Build failed with an exception.
[cull_opacity_perf__e2e_summary] [STDOUT] stderr: [        ] * What went wrong:
[cull_opacity_perf__e2e_summary] [STDOUT] stderr: [        ] Could not determine the dependencies of task ':app:compileProfileJavaWithJavac'.
[cull_opacity_perf__e2e_summary] [STDOUT] stderr: [        ] > Failed to install the following SDK components:
[cull_opacity_perf__e2e_summary] [STDOUT] stderr: [        ]       platforms;android-31 Android SDK Platform 31
[cull_opacity_perf__e2e_summary] [STDOUT] stderr: [        ]   Install the missing components using the SDK manager in Android Studio.
[cull_opacity_perf__e2e_summary] [STDOUT] stderr: [        ] * Try:
[cull_opacity_perf__e2e_summary] [STDOUT] stderr: [        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[cull_opacity_perf__e2e_summary] [STDOUT] stderr: [        ] * Get more help at https://help.gradle.org/
[cull_opacity_perf__e2e_summary] [STDOUT] stderr: [        ] BUILD FAILED in 17s
[cull_opacity_perf__e2e_summary] [STDOUT] stdout: [        ] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
```

**Comment by godofredoc** [comment]
```
[backdrop_filter_perf__e2e_summary] [STDOUT] stdout: [        ] 	at java.lang.Thread.run(Thread.java:748)
[backdrop_filter_perf__e2e_summary] [STDOUT] stdout: [        ] Caused by: javax.crypto.AEADBadTagException: Tag mismatch!
[backdrop_filter_perf__e2e_summary] [STDOUT] stdout: [        ] 	at com.sun.crypto.provider.GaloisCounterMode.decryptFinal(GaloisCounterMode.java:578)
[backdrop_filter_perf__e2e_summary] [STDOUT] stdout: [        ] 	at com.sun.crypto.provider.CipherCore.finalNoPadding(CipherCore.java:1116)
[backdrop_filter_perf__e2e_summary] [STDOUT] stdout: [        ] 	at com.sun.crypto.provider.CipherCore.fillOutputBuffer(CipherCore.java:1053)
[backdrop_filter_perf__e2e_summary] [STDOUT] stdout: [        ] 	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:941)
[backdrop_filter_perf__e2e_summary] [STDOUT] stdout: [        ] 	at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:491)
[backdrop_filter_perf__e2e_summary] [STDOUT] stdout: [        ] 	at javax.crypto.Cipher.doFinal(Cipher.java:2376)
[backdrop_filter_perf__e2e_summary] [STDOUT] stdout: [        ] 	at sun.security.ssl.CipherBox.decrypt(CipherBox.java:461)
[backdrop_filter_perf__e2e_summary] [STDOUT] stdout: [        ] 	at sun.security.ssl.InputRecord.decrypt(InputRecord.java:172)
[backdrop_filter_perf__e2e_summary] [STDOUT] stdout: [        ] 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1017)
[backdrop_filter_perf__e2e_summary] [STDOUT] stdout: [        ] 	... 156 more
[backdrop_filter_perf__e2e_summary] [STDOUT] stdout: [        ] "Install Android SDK Build-Tools 29.0.2 (revision: 29.0.2)" failed.
````

**Comment by godofredoc** [comment]
The errors are happening when gradle is trying to install the SDK build-tools. @blasten do you know what could be happening here?

**Comment by godofredoc** [comment]
Actually it seems related to a corrupted download of gradle: https://stackoverflow.com/questions/32569189/gradle-wrapper-tag-mismatch-error

**Comment by godofredoc** [comment]
Analyzer benchmarck failure is unrelated to this bug.

**Comment by keyonghan** [comment]
Ran those three flaky tests on linux12 each for 10 times (https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-linux-12), and didn't hit the gradle issue again.

**Comment by godofredoc** [comment]
Sounds good. I'm cleaning the cache and moving the bot back to prod. It seems like the issue was transient and caused by a bad gradle cache.

**Comment by godofredoc** [comment]
Tests are now passing consistently on linux-12
