### ISSUE TITLE
[scheduler] Gracefully fail runIf

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#97152]
https://github.com/flutter/flutter/pull/97144 had a hard fail as Cocoon was unable to get the diff of the PR. Since this occurs so infrequently, we should trigger all the builds and log it as a warning.

```
GitHub Error: Requested Resource was Not Found
#0      GitHub.handleStatusCode (package:github/src/common/github.dart:397:9)
#1      GitHub.request (package:github/src/common/github.dart:367:7)
<asynchronous suspension>
#2      PaginationHelper.fetchStreamed (package:github/src/common/util/pagination.dart:38:20)
<asynchronous suspension>
#3      PaginationHelper.jsonObjects (package:github/src/common/util/pagination.dart:95:5)
<asynchronous suspension>
```

**Comment by CaseyHillers** [comment]
https://github.com/flutter/packages/pull/555 is another instance
