### ISSUE TITLE
`framework_tests_libraries` flakes` on date_picker_test

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#97161]
(part of https://github.com/flutter/flutter/issues/97036)
These data is based Q4 2021 flakes that happened from 10/01/2021 to 01/13/2022

- `Mac framework_tests_libraries`: [1 flake on date_picker_test](https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20framework_tests_libraries/3074/overview)

```
01:22 +2352 ~14: /opt/s/w/ir/x/w/flutter/packages/flutter/test/cupertino/date_picker_test.dart: Date picker DatePicker golden tests                                                                    
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following _Exception was thrown while running async test code:
Exception: Skia Gold received an unapproved image in post-submit
testing. Golden file images in flutter/flutter are triaged
in pre-submit during code review for the given PR.

Visit https://flutter-gold.skia.org/ to view and approve
the image(s), or revert the associated change. For more
information, visit the wiki:
https://github.com/flutter/flutter/wiki/Writing-a-golden-file-test-for-package:flutter

Debug information for Gold:
stdout: Given image with hash 82149302f6a7f444ca82b263480cc947 for test
cupertino.date_picker_test.datetime.initial
Expectation for test: 0eeb47eef65dca3d8a64fb6e65f2ca4d (positive)
Expectation for test: 6799e6f0fc81d60d1fe72afab17eddd5 (positive)
Expectation for test: 68b87a3d1557212339b24f7023c42b19 (positive)
Expectation for test: b3d8b516195bb7ffebca5d7e7efe4efa (positive)
Expectation for test: 48d89017a2272a34408b3cde8ffe6e9a (positive)
Expectation for test: 5aefe0b58dab72c0e8f8c9b41bd67cc9 (positive)
Expectation for test: c45dd1ceae206abca194143fb6ad97e2 (positive)
Expectation for test: 428d3a53ecb3918a7e8ec237c7ea17d0 (positive)
Expectation for test: f507b258a4e73141e3f0d8d74502ddf0 (positive)
Expectation for test: 647463642fd9a38edcd0419da4d94188 (positive)
Expectation for test: 6ee9fed2051d189bfaebcf461ae0e82c (positive)
Expectation for test: 90597edb22dc9acb483e78b29c290279 (positive)
Expectation for test: b674772b19a6d38f15353f4148f52702 (positive)
Expectation for test: c9f08d07320a045d1784c7de4d427a70 (positive)
Expectation for test: e5508d2f1a43a33f584f7a15637c2f40 (positive)
Expectation for test: 0765b31270baab1c4842b04ebb2cc89e (positive)
Expectation for test: 382fa8b67631fa1fb565a14393c90dbb (positive)
Expectation for test: 4058c311b3b9d72640cd3c82e96aac63 (positive)
Expectation for test: 47fc581696de17734c8d65d0d58336f8 (positive)
Expectation for test: 6d9acdfc0671f2663dc751a2dc809f39 (positive)
Expectation for test: 2700c605c481a597fe819b0193feba55 (positive)
Expectation for test: 5a9f6c19a01b886a5e9413963e27dc97 (positive)
Expectation for test: 5d9edb9f588a4ddde7e8c91a8f005d6f (positive)
Expectation for test: a60e7326b58775862b7a35213af289aa (positive)
Expectation for test: b359f8a491bd05bb39e64492329ca0dc (positive)
Expectation for test: 22aea9cc5bbaa0da7a7af0f6ef99dc77 (positive)
Expectation for test: 3214cb4ad0273830294315e09143f421 (positive)
Expectation for test: 4fd0d7d787d69bd27533fecdf7705948 (positive)
Expectation for test: 87599f3dec5b56dc110f1b63dc747182 (positive)
Expectation for test: a7ba699858f119f9641142bf9e503796 (positive)
Untriaged or negative image:
https://flutter-gold.skia.org/detail?test=cupertino.date_picker_test.datetime.initial&digest=82149302f6a7f444ca82b263480cc947


stderr: Test: cupertino.date_picker_test.datetime.initial FAIL

When the exception was thrown, this was the stack:
#0      SkiaGoldClient.imgtestAdd (package:flutter_goldens_client/skia_client.dart:215:7)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)
════════════════════════════════════════════════════════════════════════════════════════════════════

01:22 +2353 ~14: /opt/s/w/ir/x/w/flutter/packages/flutter/test/cupertino/date_picker_test.dart: Date picker DatePicker golden tests                                                                    
01:22 +2354 ~14: /opt/s/w/ir/x/w/flutter/packages/flutter/test/cupertino/date_picker_test.dart: Date picker DatePicker golden tests                                                                    
01:22 +2355 ~14: /opt/s/w/ir/x/w/flutter/packages/flutter/test/cupertino/date_picker_test.dart: Date picker DatePicker golden tests                                                                    
01:22 +2356 ~14: /opt/s/w/ir/x/w/flutter/packages/flutter/test/cupertino/date_picker_test.dart: Date picker DatePicker golden tests                                                                    
01:23 +2356 ~14: /opt/s/w/ir/x/w/flutter/packages/flutter/test/cupertino/date_picker_test.dart: Date picker DatePicker golden tests                                                                    
01:23 +2357 ~14: /opt/s/w/ir/x/w/flutter/packages/flutter/test/cupertino/date_picker_test.dart: Date picker DatePicker golden tests                                                                    
01:23 +2358 ~14: /opt/s/w/ir/x/w/flutter/packages/flutter/test/cupertino/date_picker_test.dart: Date picker DatePicker golden tests                                                                    
01:23 +2359 ~14: /opt/s/w/ir/x/w/flutter/packages/flutter/test/cupertino/date_picker_test.dart: Date picker DatePicker golden tests                                                                    
01:23 +2359 ~14: /opt/s/w/ir/x/w/flutter/packages/flutter/test/cupertino/date_picker_test.dart: Date picker DatePicker golden tests                                                                    
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following _Exception was thrown while running async test code:
Exception: Skia Gold received an unapproved image in post-submit
testing. Golden file images in flutter/flutter are triaged
in pre-submit during code review for the given PR.

Visit https://flutter-gold.skia.org/ to view and approve
the image(s), or revert the associated change. For more
information, visit the wiki:
https://github.com/flutter/flutter/wiki/Writing-a-golden-file-test-for-package:flutter

Debug information for Gold:
stdout: Given image with hash e50886a850bd0214e9f5a239f8847804 for test
cupertino.date_picker_test.datetime.drag
Expectation for test: 2918601bd09078ea60132c2e46a806e4 (positive)
Expectation for test: 2dc15070c7c1c613682778bc34b2637d (positive)
Expectation for test: 43f8ab889961f48c890a2814e16dbb0a (positive)
Expectation for test: 70b636ef4fbbe8f85bdaca623f5bf770 (positive)
Expectation for test: 9545ce0ee130e0602e8f1f9da7fadd5e (positive)
Expectation for test: 0b9795b218a8e367b552dcea55c8d589 (positive)
Expectation for test: 104b81d5634aec660fd1300e4dc8ac63 (positive)
Expectation for test: 65560016d0c3df90512748506389ed31 (positive)
Expectation for test: 007c679a276885ad84777935ac0b63ce (positive)
Expectation for test: 1f1881fe0b2e88e416e3d5a39f47cc7c (positive)
Expectation for test: 7a09093e7f71963f9e02357c09e70ba0 (positive)
Expectation for test: f0a6cea41931cb63d141a7eb67b7f8ca (positive)
Expectation for test: 50ab8e3db4a8a7d3f552a244888a70b7 (positive)
Expectation for test: 5e1fee10924cee463667fb3f5f08f171 (positive)
Expectation for test: 3f2279d0d4b2c9fdec6b50d358a41428 (positive)
Expectation for test: 5ad1651f225018116b59ad898cc15b2d (positive)
Expectation for test: 7d04fc1ef547a8e092495dab4294b4cd (positive)
Expectation for test: aa748136c70cefdda646df5be0ae189d (positive)
Expectation for test: bc9e3f104b8fb41df08dd3bb385718b0 (positive)
Expectation for test: 27a2ee6b082b643d5ff5cf5f61d020a5 (positive)
Expectation for test: 35ab982bfdc166abe415e1a3c099a3b2 (positive)
Expectation for test: cfd121c87912497fe3f60e7ca94bfd41 (positive)
Expectation for test: 24d0b1b915250fc26be3aca836f44bc5 (positive)
Expectation for test: 4f8e9a0c36540790c44b82ce5a654056 (positive)
Expectation for test: f34fa9b2e9aed2f1611d01507803ba31 (positive)
Expectation for test: 466c0c67233adf307f5a1a0626480a28 (positive)
Expectation for test: 6a039a7979a4b4fa369367bc289f2cea (positive)
Expectation for test: c3312ad1479f50caf3754b42a42740c5 (positive)
Expectation for test: d1a97b66a2ba2c3ddf300836554ae7f9 (positive)
Expectation for test: 19c0169ad42f45513aa7a054ef54e894 (positive)
Expectation for test: 351eca00baac019ad7b80529a7545d65 (positive)
Untriaged or negative image:
https://flutter-gold.skia.org/detail?test=cupertino.date_picker_test.datetime.drag&digest=e50886a850bd0214e9f5a239f8847804


stderr: Test: cupertino.date_picker_test.datetime.drag FAIL

When the exception was thrown, this was the stack:
#0      SkiaGoldClient.imgtestAdd (package:flutter_goldens_client/skia_client.dart:215:7)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)
════════════════════════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following message was thrown:
Multiple exceptions (4) were detected during the running of the current test, and at least one was
unexpected.
════════════════════════════════════════════════════════════════════════════════════════════════════

01:23 +2359 ~14 -1: /opt/s/w/ir/x/w/flutter/packages/flutter/test/cupertino/date_picker_test.dart: Date picker DatePicker golden tests [E]                                                             
  Test failed. See exception logs above.
  The test description was: DatePicker golden tests
```

**Comment by keyonghan** [comment]
[One similar flake](https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20framework_tests_libraries/3060/overview) on `Windows framework_tests_libraries`

**Comment by Piinks** [comment]
This was from December. This is not a flake, it is a signal that someone merged a PR without triaging an image change in pre-submit as the error message says. I can see from the Flutter Gold triage log, that on that same day the images in question were updated: https://flutter-gold.skia.org/triagelog

I don't think this is a flake, nor an active issue at this time. The test failed as expected to notify of an image change that was not handled in pre-submit.

**Comment by keyonghan** [comment]
Thanks @Piinks for the clarification!
Closing as the issue has been fixed.
