### ISSUE TITLE
Windows build_tests flakes on `android_aot_release_android-arm64` failure

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#97160]
These data is based Q4 2021 flakes that happened from 10/01/2021 to 01/13/2022

- Windows build_tests_1_3: 1 flake [android_aot_release_android-arm64 failure](https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20build_tests_1_3/2668/overview)
- Windows build_tests_2_3: 2 flakes on android_aot_release_android-arm64 failure ([1](https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20build_tests_2_3/3131/overview), [2](https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20build_tests_2_3/2392/overview))

```
[ +193 ms] [ +249 ms] android_aot_bundle_release_android-arm: Starting due to {}
[        ] [   +6 ms] android_aot_bundle_release_android-arm: Complete
[  +94 ms] [  +65 ms] Dart snapshot generator failed with exit code -1073740940
[   +2 ms] [   +9 ms] Target android_aot_release_android-arm64 failed: Exception: AOT snapshotter exited with code -1073740940
[        ]            #0      AndroidAot.build (package:flutter_tools/src/build_system/targets/android.dart:257:7)
[        ]            <asynchronous suspension>
[        ]            #1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:839:9)
[        ]            <asynchronous suspension>
[        ]            #2      Future.wait.<anonymous closure> (dart:async/future.dart)
[        ]            <asynchronous suspension>
[        ]            #3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:777:32)
[        ]            <asynchronous suspension>
[        ]            #4      Future.wait.<anonymous closure> (dart:async/future.dart)
[        ]            <asynchronous suspension>
[        ]            #5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:777:32)
[        ]            <asynchronous suspension>
[        ]            #6      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:606:16)
[        ]            <asynchronous suspension>
[        ]            #7      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:317:32)
[        ]            <asynchronous suspension>
[        ]            #8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1135:27)
[        ]            <asynchronous suspension>
[        ]            #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #10     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
[        ]            <asynchronous suspension>
[        ] [   +5 ms] Persisting file store
[        ] [  +13 ms] Done persisting file store
[        ]            #11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
[        ]            <asynchronous suspension>
[        ]            #12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
```

**Comment by keyonghan** [comment]
@zanderso Could you help take a further look? We are scanning flakes in shards tests (which contains many unit/integration tests), and want to either fix or skip corresponding flaky tests to try achieving 0 flakes from them.

**Comment by zanderso** [comment]
@a-siva @aam Any idea what that exit code from gen_snapshot means on Windows?

**Comment by zanderso** [comment]
@keyonghan a test that has only flaked three times since the beginning of October is well within our objective, so I am setting the priority of this to P4.

**Comment by aam** [comment]
> [  +94 ms] [  +65 ms] Dart snapshot generator failed with exit code -1073740940

That corresponds to unsigned 0xC0000374 which is a heap corruption exception on Windows.

**Comment by keyonghan** [comment]
One more instance today: https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20build_tests_2_3/3910/overview

**Comment by keyonghan** [comment]
This still keeps happening: https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20build_tests_2_3/4369/overview

**Comment by zanderso** [comment]
@keyonghan can you say anything about the frequency? Without more information, I think it's still the case that this flake is well under the threshold.

**Comment by keyonghan** [comment]
> @keyonghan can you say anything about the frequency? Without more information, I think it's still the case that this flake is well under the threshold.

Yeah, this is happening basically with a rate of 1% for recent 500 commits, so updating here only without promoting the P2/P1. But I'm wondering if we should promote the priority a bit if a test is flaking consistently, though the overall ratio is < 2%.

**Comment by zanderso** [comment]
I don't think this one can be described as failing consistently.

**Comment by godofredoc** [comment]
@ricardoamador can you please take a look?

**Comment by ricardoamador** [comment]
The original issue for the AOT snapshotter error has occurred as recently as 12/01/2022 https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20build_tests_2_3/8148/overview

But it is not happening that frequently. The more frequent issue I have found here is related to this issue: https://github.com/flutter/flutter/issues/103230

**Comment by raycastsant** [comment]
I recently upgraded to the latest version of flutter (**3.7.1**), upgraded my project dependencies and everything runs fine in debug mode, but when trying to build a release apk or appbundle I'm getting this same error:
```
  Dart snapshot generator failed with exit code -1073741819
[ +101 ms] Target android_aot_release_android-arm64 failed: Exception: AOT snapshotter exited with code -1073741819
```

I'm using windows 10. 
I will appreciate any help on this.

**Comment by a-siva** [comment]
@raycastsant do you get a flaky crash or does it crash consistently ? We also need to figure out how we can reproduce this locally.

**Comment by ricardoamador** [comment]
Thank you for taking a look @a-siva!

**Comment by raycastsant** [comment]
> @raycastsant do you get a flaky crash or does it crash consistently ? We also need to figure out how we can reproduce this locally.

Hello

It crashes consistently.
Is there a way to get an error log when creating an app bundle? Maybe that way I can find out what part of my code is causing this.

Thanks for your reply!

**Comment by a-siva** [comment]
> 

Do you see this problem only with the 3.7.1 version and not with 3.7.0 ?

**Comment by raycastsant** [comment]
Yes, the same thing happens with version 3.7.0.

**Comment by raycastsant** [comment]
I have tried version 3.3.10 and everything has gone well, without errors.

**Comment by a-siva** [comment]
@raycastsant would it be possible to build your app on a Linux or Mac host machine using Flutter 3.7.2 and see if the error happens, we get better stack traces on these hosts which might help us root cause the problem. If you do not have access to these host machines would it be possible for you to share your application with us so we can locally reproduce the problem and investigate ... Thanks.

**Comment by raycastsant** [comment]
Hi @a-siva

I tell you that I already discovered the cause of the problem.
It was a call to a **Provider** within another **Provider** (_Obviously a bad practice; this is a rather large project that has been refactored little by little_). The **BuildContext** was being passed to a function and within it the second **Provider** was being instantiated.
To realize this, I had to remove all the packages from the app and gradually add them until the problem package appeared, and then I did the same with the classes inside the package.
Thank you so much!!!

**Comment by a-siva** [comment]
@raycastsant thank you for the update, it is great that you have found the cause of the problem and fixed it. It would still be valuable for us to understand why we crashed when building the application because if there is a problem in the application we are supposed to produce a nice error message not a crash. If you are able to find cycles to help us reproduce the problem locally that would help... Thanks.

**Comment by cbracken** [comment]
We hit this again in: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8787878823601249201/+/u/run_test.dart_for_build_tests_shard_and_subshard_2_3/test_stdout

**Comment by a-siva** [comment]
@rmacnak-google recently added code to dump a stack trace when the `dart/gen_snapshot` process terminates abnormally, this output goes to stderr of the process, does Flutter tool capture this output and list it in the logs? I do not see any stack trace of the `dart/gen_snapshot` process in the log output above.

**Comment by ricardoamador** [comment]
This?
```
[ +300 ms] [ +295 ms] Dart snapshot generator failed with exit code -1073740940
[   +3 ms] [   +6 ms] Persisting file store
[        ] [  +13 ms] Done persisting file store
[  +91 ms] [  +10 ms] Target android_aot_release_android-x64 failed: Exception: AOT snapshotter exited with code -1073740940
[        ]            #0      AndroidAot.build (package:flutter_tools/src/build_system/targets/android.dart:258:7)
[        ]            <asynchronous suspension>
[        ]            #1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:847:9)
[        ]            <asynchronous suspension>
[        ]            #2      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
[        ]            <asynchronous suspension>
[        ]            #3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:785:32)
[        ]            <asynchronous suspension>
[        ]            #4      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
[        ]            <asynchronous suspension>
[        ]            #5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:785:32)
[        ]            <asynchronous suspension>
[        ]            #6      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:614:16)
[        ]            <asynchronous suspension>
[        ]            #7      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:331:32)
[        ]            <asynchronous suspension>
[        ]            #8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1301:27)
[        ]            <asynchronous suspension>
[        ]            #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #10     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
[        ]            <asynchronous suspension>
[        ]            #11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
[        ]            <asynchronous suspension>
[        ]            #12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
[        ]            <asynchronous suspension>
[        ]            #14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
[        ]            <asynchronous suspension>
[        ]            #15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #16     main (package:flutter_tools/executable.dart:91:3)
[        ]            <asynchronous suspension>
[        ] [   +4 ms] 
[        ]            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
[        ]            #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:348:7)
[        ]            <asynchronous suspension>
[        ]            #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1301:27)
[        ]            <asynchronous suspension>
[        ]            #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
[        ]            <asynchronous suspension>
[        ]            #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
[        ]            <asynchronous suspension>
[        ]            #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
[        ]            <asynchronous suspension>
[        ]            #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
[        ]            <asynchronous suspension>
[        ]            #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #10     main (package:flutter_tools/executable.dart:91:3)
[        ]            <asynchronous suspension>
[        ] [  +20 ms] "flutter assemble" took 30,697ms.
[        ] [   +1 ms] ensureAnalyticsSent: 0ms
[        ] [        ] Running 0 shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 1
[  +95 ms] > Task :app:compileFlutterBuildRelease FAILED
[        ] :app:compileFlutterBuildRelease (Thread[included builds,5,main]) completed. Took 31.926 secs.
```

**Comment by a-siva** [comment]
This is the Dart stack traces from Flutter tools, I am looking for the C++ stack dump that the Dart VM would produce from the `gen_snapshot` step invoke as part of the build command.

**Comment by cbracken** [comment]
Looking at [the build](https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20build_tests_2_3/9446/overview), the [reported stderr](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8787878823601249201/+/u/run_test.dart_for_build_tests_shard_and_subshard_2_3/test_stderr) looks empty.

**Comment by aam** [comment]
Potentially gen_snapshot crashes before it installs exception handler in https://github.com/dart-lang/sdk/blob/main/runtime/bin/gen_snapshot.cc#L875.
There is not much happening before that though - only ParseArguments and some other initialization in [PlatformWin::InitOnce](https://github.com/dart-lang/sdk/blob/main/runtime/bin/platform_win.cc#L33) but still.
Perhaps `SetExceptionHandler()` call can be moved closer to the process launch.

**Comment by stuartmorgan** [comment]
Two more recent instances:
https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20plugin_test/13403
https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20plugin_test/13388

I don't see any stderr there either.

**Comment by matanlurey** [comment]
Closing as stale as of 2025.
