### ISSUE TITLE
{Android} Build error on release apk

### ISSUE THREAD

**Issue by eramitsharma957** [flutter/flutter#97200]
<details>
<summary> error log </summary>

```

Unhandled exception:
Unexpected type InvalidType InvalidType(<invalid>)
#0      TypesBuilder.fromStaticType (package:vm/transformations/type_flow/types.dart:103:7)
#1      SummaryCollector._staticType (package:vm/transformations/type_flow/summary_collector.dart:1192:21)
#2      SummaryCollector.visitConditionalExpression (package:vm/transformations/type_flow/summary_collector.dart:1491:27)
#3      ConditionalExpression.accept (package:kernel/ast.dart:6684:44)
#4      SummaryCollector._visit (package:vm/transformations/type_flow/summary_collector.dart:861:44)
#5      SummaryCollector._visitCondition (package:vm/transformations/type_flow/summary_collector.dart:1402:13)
#6      SummaryCollector.visitConditionalExpression (package:vm/transformations/type_flow/summary_collector.dart:1477:5)
#7      ConditionalExpression.accept (package:kernel/ast.dart:6684:44)
#8      SummaryCollector._visit (package:vm/transformations/type_flow/summary_collector.dart:861:44)
#9      SummaryCollector._visitArguments (package:vm/transformations/type_flow/summary_collector.dart:887:21)
#10     SummaryCollector.visitInstanceInvocation (package:vm/transformations/type_flow/summary_collector.dart:1605:18)
#11     InstanceInvocation.accept (package:kernel/ast.dart:5505:44)
#12     SummaryCollector._visit (package:vm/transformations/type_flow/summary_collector.dart:861:44)
#13     SummaryCollector._visitArguments (package:vm/transformations/type_flow/summary_collector.dart:879:16)
#14     SummaryCollector.visitStaticInvocation (package:vm/transformations/type_flow/summary_collector.dart:1849:18)
#15     StaticInvocation.accept (package:kernel/ast.dart:6294:44)
#16     SummaryCollector._visit (package:vm/transformations/type_flow/summary_collector.dart:861:44)
#17     SummaryCollector.visitLet (package:vm/transformations/type_flow/summary_collector.dart:1537:37)
#18     Let.accept (package:kernel/ast.dart:8395:44)
#19     SummaryCollector._visit (package:vm/transformations/type_flow/summary_collector.dart:861:44)
#20     SummaryCollector.visitYieldStatement (package:vm/transformations/type_flow/summary_collector.dart:2203:5)
#21     YieldStatement.accept (package:kernel/ast.dart:10185:43)
#22     SummaryCollector._visitWithoutResult (package:vm/transformations/type_flow/summary_collector.dart:864:10)
#23     SummaryCollector._visitWithoutResult (package:vm/transformations/type_flow/summary_collector.dart)
#24     List.forEach (dart:core-patch/growable_array.dart:410:8)
#25     SummaryCollector.visitBlock (package:vm/transformations/type_flow/summary_collector.dart:1962:21)
#26     Block.accept (package:kernel/ast.dart:8890:43)
#27     SummaryCollector._visitWithoutResult (package:vm/transformations/type_flow/summary_collector.dart:864:10)
#28     SummaryCollector.visitLabeledStatement (package:vm/transformations/type_flow/summary_collector.dart:2090:5)
#29     LabeledStatement.accept (package:kernel/ast.dart:9100:43)
#30     SummaryCollector._visitWithoutResult (package:vm/transformations/type_flow/summary_collector.dart:864:10)
#31     SummaryCollector._visitWithoutResult (package:vm/transformations/type_flow/summary_collector.dart)
#32     List.forEach (dart:core-patch/growable_array.dart:410:8)
#33     SummaryCollector.visitBlock (package:vm/transformations/type_flow/summary_collector.dart:1962:21)
#34     Block.accept (package:kernel/ast.dart:8890:43)
#35     SummaryCollector._visitWithoutResult (package:vm/transformations/type_flow/summary_collector.dart:864:10)
#36     SummaryCollector.visitTryCatch (package:vm/transformations/type_flow/summary_collector.dart:2140:5)
#37     TryCatch.accept (package:kernel/ast.dart:9923:43)
#38     SummaryCollector._visitWithoutResult (package:vm/transformations/type_flow/summary_collector.dart:864:10)
#39     SummaryCollector._handleNestedFunctionNode (package:vm/transformations/type_flow/summary_collector.dart:1274:5)
#40     SummaryCollector.visitFunctionDeclaration (package:vm/transformations/type_flow/summary_collector.dart:2064:5)
#41     FunctionDeclaration.accept (package:kernel/ast.dart:10507:43)
#42     SummaryCollector._visitWithoutResult (package:vm/transformations/type_flow/summary_collector.dart:864:10)
#43     SummaryCollector._visitWithoutResult (package:vm/transformations/type_flow/summary_collector.dart)
#44     List.forEach (dart:core-patch/growable_array.dart:410:8)
#45     SummaryCollector.visitBlock (package:vm/transformations/type_flow/summary_collector.dart:1962:21)
#46     Block.accept (package:kernel/ast.dart:8890:43)
#47     SummaryCollector._visitWithoutResult (package:vm/transformations/type_flow/summary_collector.dart:864:10)
#48     SummaryCollector.createSummary (package:vm/transformations/type_flow/summary_collector.dart:765:9)
#49     TypeFlowAnalysis.getSummary (package:vm/transformations/type_flow/analysis.dart:1533:52)
#50     _DirectInvocation._processFunction (package:vm/transformations/type_flow/analysis.dart:298:42)
#51     _DirectInvocation.process (package:vm/transformations/type_flow/analysis.dart:226:14)
#52     _WorkList.processInvocation (package:vm/transformations/type_flow/analysis.dart:1429:27)
#53     _DispatchableInvocation.process.<anonymous closure> (package:vm/transformations/type_flow/analysis.dart:449:44)
#54     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:539:8)
#55     _DispatchableInvocation.process (package:vm/transformations/type_flow/analysis.dart:423:12)
#56     _WorkList.processInvocation (package:vm/transformations/type_flow/analysis.dart:1429:27)
#57     TypeFlowAnalysis.applyCall (package:vm/transformations/type_flow/analysis.dart:1670:23)
#58     Call.apply (package:vm/transformations/type_flow/summary.dart:268:31)
#59     Summary.apply (package:vm/transformations/type_flow/summary.dart:724:33)
#60     _DirectInvocation._processFunction (package:vm/transformations/type_flow/analysis.dart:307:24)
#61     _DirectInvocation.process (package:vm/transformations/type_flow/analysis.dart:226:14)
#62     _WorkList.processInvocation (package:vm/transformations/type_flow/analysis.dart:1429:27)
#63     _DispatchableInvocation.process.<anonymous closure> (package:vm/transformations/type_flow/analysis.dart:449:44)
#64     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:539:8)
#65     _DispatchableInvocation.process (package:vm/transformations/type_flow/analysis.dart:423:12)
#66     _WorkList.processInvocation (package:vm/transformations/type_flow/analysis.dart:1429:27)
#67     TypeFlowAnalysis.applyCall (package:vm/transformations/type_flow/analysis.dart:1670:23)
#68     Call.apply (package:vm/transformations/type_flow/summary.dart:268:31)
#69     Summary.apply (package:vm/transformations/type_flow/summary.dart:724:33)
#70     _DirectInvocation._processFunction (package:vm/transformations/type_flow/analysis.dart:307:24)
#71     _DirectInvocation.process (package:vm/transformations/type_flow/analysis.dart:226:14)
#72     _WorkList.processInvocation (package:vm/transformations/type_flow/analysis.dart:1429:27)
#73     _DispatchableInvocation.process.<anonymous closure> (package:vm/transformations/type_flow/analysis.dart:449:44)
#74     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:539:8)
#75     _DispatchableInvocation.process (package:vm/transformations/type_flow/analysis.dart:423:12)
#76     _WorkList.processInvocation (package:vm/transformations/type_flow/analysis.dart:1429:27)
#77     TypeFlowAnalysis.applyCall (package:vm/transformations/type_flow/analysis.dart:1670:23)
#78     Call.apply (package:vm/transformations/type_flow/summary.dart:268:31)
#79     Summary.apply (package:vm/transformations/type_flow/summary.dart:724:33)
#80     _DirectInvocation._processFunction (package:vm/transformations/type_flow/analysis.dart:307:24)
#81     _DirectInvocation.process (package:vm/transformations/type_flow/analysis.dart:226:14)
#82     _WorkList.processInvocation (package:vm/transformations/type_flow/analysis.dart:1429:27)
#83     _WorkList.process (package:vm/transformations/type_flow/analysis.dart:1371:7)
#84     TypeFlowAnalysis.process (package:vm/transformations/type_flow/analysis.dart:1551:14)
#85     transformComponent (package:vm/transformations/type_flow/transformer.dart:87:20)
#86     runGlobalTransformations (package:vm/kernel_front_end.dart:454:20)
#87     compileToKernel (package:vm/kernel_front_end.dart:376:11)
<asynchronous suspension>
#88     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:541:17)
<asynchronous suspension>
#89     starter (package:flutter_frontend_server/server.dart:85:12)
<asynchronous suspension>
#90     main (file:///opt/s/w/ir/cache/builder/src/flutter/flutter_frontend_server/bin/starter.dart:13:24)
<asynchronous suspension>



FAILURE: Build failed with an exception.

* Where:
Script '/Users/sudhirarora/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1070

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command '/Users/sudhirarora/flutter/bin/flutter'' finished with non-zero exit value 1

```
</details>

**Comment by darshankawar** [comment]
@eramitsharma957 
Just providing an error log isn't enough to analyze the issue, whenever you open an issue, try to use new issue template and fill out requested details so that we will have enough details to work with.
For now, provide your `flutter doctor -v`, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows the error you are getting. Please provide this in properly formatted text.

**Comment by alexmarkov** [comment]
It looks like crash happens because `ConditionalExpression.getStaticType` returns `InvalidType`. The incorrect `ConditionalExpression` is nested within another `ConditionalExpression` node.

@johnniwinther Do you have any idea how could that happen? Is it possible that in certain cases `ConditionalExpression.condition` is not recursively visited by type inference in the front-end?

**Comment by johnniwinther** [comment]
The `InvalidType` should only be produced for compile-time errors, which doesn't seem to be the case here. We probably need a repo to find out why that invariant doesn't hold in this case.
