### ISSUE TITLE
App runs in debug and release, but NOT profile mode.

### ISSUE THREAD

**Issue by RyanRamchandar** [flutter/flutter#97225]
Using `flutter run --release` or just `flutter run` runs without error. However, using `flutter run --profile` gives an error.

## Steps to Reproduce

1. Execute `flutter run --profile`. The following error is given

```shell
% flutter run --profile
Launching lib/main.dart on iPhone 12 Pro in profile mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: KPUPH2Q2AB
Running Xcode build...                                                  
 └─Compiling, linking and signing...                        628ms
Xcode build done.                                            4.9s
Could not run build/ios/iphoneos/Runner.app on 00008101-00060D321440001E.
Try launching Xcode and selecting "Product > Run" to fix the problem:
  open ios/Runner.xcworkspace

Installing and launching...                                        181ms
Error running application on iPhone 12 Pro.
```

Using `flutter run --verbose --profile` gives more context to the error (see full verbose log below):

```shell
% flutter run --verbose --profile
...
[        ] ------ Install phase ------
[        ] [  0%] Found 00008101-00060D321440001E (D53pAP, iPhone 12 Pro, iphoneos, arm64e, 15.1.1, 19B81) a.k.a. 'iPhone 12 Pro' connected through USB, beginning install
[        ] 2022-01-25 11:33:41.042 ios-deploy[16487:15410388] [ !! ] [ ERROR] Could not determine bundle id.
[        ] Script started, output file is /dev/null
[        ] Script done, output file is /dev/null
[   +1 ms] ios-deploy exited with code 0
[   +5 ms] Could not run build/ios/iphoneos/Runner.app on 00008101-00060D321440001E.
[   +3 ms] Try launching Xcode and selecting "Product > Run" to fix the problem:
[        ]   open ios/Runner.xcworkspace
[        ] Installing and launching... (completed in 196ms)
[        ] Error running application on iPhone 12 Pro.
[   +4 ms] "flutter run" took 12,471ms.
[   +9 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:674:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>
           
           
[  +60 ms] ensureAnalyticsSent: 59ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 2

```

Launching Xcode and selecting "Product > Run", runs the app fine with no error.

<details>
<summary>flutter doctor -v</summary>

```shell
% flutter doctor -v
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-CA)
    • Flutter version 2.8.1 at /Users/ryan/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (6 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/ryan/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Users/ryan/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7784292/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/ryan/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7784292/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at /Users/ryan/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/213.5744.223/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • iPhone 12 Pro (mobile) • 00008101-00060D321440001E • ios            • iOS 15.1.1 19B81
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 97.0.4692.99

• No issues found!
```

</details>

**`flutter run --verbose --profile` (fails)**
https://gist.github.com/RyanRamchandar/42e3ef6a17bf021212a1342a812cc2d0

**`flutter run --verbose --release` (succeeds)**
https://gist.github.com/RyanRamchandar/0ac0b5bed48b5148a9f2cc3145f7a215

**Comment by RyanRamchandar** [comment]
Found the solution. I forgot to add `Info-Profile.plist` variant in Runner. I had followed these instructions to add Local Network Permissions only for debug builds, and forgot to make a plist for Profile also:
https://docs.flutter.dev/development/add-to-app/ios/project-setup#local-network-privacy-permissions
