### ISSUE TITLE
Windows tool_integration_tests_5_5 flakes on tests

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#97234]
(part of https://github.com/flutter/flutter/issues/97036)
These data is based Q4 2021 flakes that happened from 10/01/2021 to 01/13/2022

- [ ] 2 stateless_stateful_hot_reload_test flakes ([2189](https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20tool_integration_tests_5_5/2189/overview), [2188](https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20tool_integration_tests_5_5/2188/overview))
```
01:03 +0 -1: test\integration.shard\stateless_stateful_hot_reload_test.dart: Can switch between stateless and stateful [E]                                                                             
  Hot reload request failed
  
  [{"id":3,"result":{"code":1,"message":"Reloaded 510 of 563 libraries"}}]
  
  Reassembling main.dart$main-777256509026047 failed: ext.flutter.reassemble: (-32000) Server error
  {"exception":"type '_State' is not a subtype of type 'State<StatefulWidget>?' of 'function result'","stack":"#0      StatefulElement._state (package:flutter/src/widgets/framework.dart)\n#1      StatefulElement.state (package:flutter/src/widgets/framework.dart:4712:38)\n#2      StatefulElement.reassemble (package:flutter/src/widgets/framework.dart:4718:7)\n#3      Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#4      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6110:14)\n#5      Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#6      Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#7      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#8      Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#9      Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#10     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6110:14)\n#11     Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#12     Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#13     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6110:14)\n#14     Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#15     Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#16     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#17     Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#18     StatefulElement.reassemble (package:flutter/src/widgets/framework.dart:4720:11)\n#19     Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#20     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6110:14)\n#21     Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#22     Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#23     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6110:14)\n#24     Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#25     Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#26     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#27     Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#28     StatefulElement.reassemble (package:flutter/src/widgets/framework.dart:4720:11)\n#29     Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#30     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#31     Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#32     Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#33     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#34     Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#35     StatefulElement.reassemble (package:flutter/src/widgets/framework.dart:4720:11)\n#36     Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#37     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6110:14)\n#38     Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#39     Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#40     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6110:14)\n#41     Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#42     Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#43     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#44     Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#45     Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#46     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6110:14)\n#47     Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#48     Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#49     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#50     Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#51     StatefulElement.reassemble (package:flutter/src/widgets/framework.dart:4720:11)\n#52     Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#53     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#54     Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#55     Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#56     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#57     Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#58     Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#59     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#60     Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#61     StatefulElement.reassemble (package:flutter/src/widgets/framework.dart:4720:11)\n#62     Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#63     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#64     Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#65     Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#66     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#67     Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#68     Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#69     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6110:14)\n#70     Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#71     Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#72     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#73     Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#74     Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#75     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#76     Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#77     Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#78     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#79     Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#80     StatefulElement.reassemble (package:flutter/src/widgets/framework.dart:4720:11)\n#81     Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#82     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#83     Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#84     StatefulElement.reassemble (package:flutter/src/widgets/framework.dart:4720:11)\n#85     Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#86     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#87     Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#88     StatefulElement.reassemble (package:flutter/src/widgets/framework.dart:4720:11)\n#89     Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#90     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6110:14)\n#91     Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#92     Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#93     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#94     Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#95     Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#96     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#97     Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#98     Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#99     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#100    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#101    StatefulElement.reassemble (package:flutter/src/widgets/framework.dart:4720:11)\n#102    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#103    MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6225:16)\n#104    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#105    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#106    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#107    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#108    StatefulElement.reassemble (package:flutter/src/widgets/framework.dart:4720:11)\n#109    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#110    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#111    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#112    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#113    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#114    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#115    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#116    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6110:14)\n#117    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#118    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#119    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#120    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#121    StatefulElement.reassemble (package:flutter/src/widgets/framework.dart:4720:11)\n#122    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#123    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6110:14)\n#124    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#125    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#126    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6110:14)\n#127    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#128    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#129    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#130    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#131    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#132    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#133    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#134    StatefulElement.reassemble (package:flutter/src/widgets/framework.dart:4720:11)\n#135    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#136    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#137    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#138    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#139    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#140    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#141    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#142    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#143    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#144    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#145    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#146    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#147    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#148    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#149    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#150    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#151    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#152    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#153    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#154    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#155    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#156    StatefulElement.reassemble (package:flutter/src/widgets/framework.dart:4720:11)\n#157    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#158    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#159    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#160    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#161    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#162    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#163    StatefulElement.reassemble (package:flutter/src/widgets/framework.dart:4720:11)\n#164    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#165    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#166    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#167    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#168    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#169    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#170    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#171    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6110:14)\n#172    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#173    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#174    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#175    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#176    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#177    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#178    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#179    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#180    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#181    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#182    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#183    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#184    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#185    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#186    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#187    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#188    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#189    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6110:14)\n#190    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#191    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#192    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#193    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#194    StatefulElement.reassemble (package:flutter/src/widgets/framework.dart:4720:11)\n#195    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#196    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#197    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#198    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#199    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#200    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#201    StatefulElement.reassemble (package:flutter/src/widgets/framework.dart:4720:11)\n#202    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#203    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#204    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#205    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#206    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#207    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#208    StatefulElement.reassemble (package:flutter/src/widgets/framework.dart:4720:11)\n#209    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#210    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#211    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#212    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#213    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#214    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#215    StatefulElement.reassemble (package:flutter/src/widgets/framework.dart:4720:11)\n#216    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#217    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#218    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#219    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#220    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#221    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#222    StatefulElement.reassemble (package:flutter/src/widgets/framework.dart:4720:11)\n#223    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#224    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#225    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#226    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#227    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6110:14)\n#228    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#229    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#230    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#231    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#232    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#233    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#234    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#235    StatefulElement.reassemble (package:flutter/src/widgets/framework.dart:4720:11)\n#236    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#237    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#238    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#239    StatefulElement.reassemble (package:flutter/src/widgets/framework.dart:4720:11)\n#240    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#241    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#242    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#243    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#244    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6110:14)\n#245    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#246    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#247    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#248    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#249    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#250    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#251    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#252    StatefulElement.reassemble (package:flutter/src/widgets/framework.dart:4720:11)\n#253    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#254    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#255    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#256    StatefulElement.reassemble (package:flutter/src/widgets/framework.dart:4720:11)\n#257    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#258    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#259    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#260    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#261    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#262    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#263    StatefulElement.reassemble (package:flutter/src/widgets/framework.dart:4720:11)\n#264    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#265    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#266    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#267    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#268    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#269    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#270    StatefulElement.reassemble (package:flutter/src/widgets/framework.dart:4720:11)\n#271    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#272    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#273    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#274    StatefulElement.reassemble (package:flutter/src/widgets/framework.dart:4720:11)\n#275    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#276    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6110:14)\n#277    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#278    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#279    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#280    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#281    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#282    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#283    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#284    StatefulElement.reassemble (package:flutter/src/widgets/framework.dart:4720:11)\n#285    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#286    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#287    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#288    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#289    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#290    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#291    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#292    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#293    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#294    StatefulElement.reassemble (package:flutter/src/widgets/framework.dart:4720:11)\n#295    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#296    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)\n#297    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#298    Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:13)\n#299    RenderObjectToWidgetElement.visitChildren (package:flutter/src/widgets/binding.dart:1153:14)\n#300    Element.reassemble (package:flutter/src/widgets/framework.dart:3142:5)\n#301    BuildOwner.reassemble (package:flutter/src/widgets/framework.dart:2945:12)\n#302    WidgetsBinding.performReassemble (package:flutter/src/widgets/binding.dart:964:19)\n#303    BindingBase.lockEvents (package:flutter/src/foundation/binding.dart:305:41)\n#304    BindingBase.reassembleApplication (package:flutter/src/foundation/binding.dart:345:12)\n#305    BindingBase.registerSignalServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:382:23)\n#306    BindingBase.registerSignalServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:381:17)\n#307    BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:602:32)\n<asynchronous suspension>\n","method":"ext.flutter.reassemble"}
  test\integration.shard\test_driver.dart 755:5                        FlutterRunTestDriver._throwErrorResponse
  test\integration.shard\test_driver.dart 666:7                        FlutterRunTestDriver._restart
  ===== asynchronous gap ===========================
  test\integration.shard\stateless_stateful_hot_reload_test.dart 46:5  main.<fn>
```

- [ ] 1 timeline_test.dart flake ([2369](https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20tool_integration_tests_5_5/2369/overview))
```
05:34 +29 -1: test\integration.shard\timeline_test.dart: Can connect to the timeline without getting ANR from the application [E]                                                                      
  Expected: 'DartIsolate::HandleMessage'
    Actual: 'MessageLoop::FlushTasks'
     Which: is different.
            Expected: DartIsolat ...
              Actual: MessageLoo ...
                      ^
             Differ at offset 0
  
  package:test_api                                  expect
  test\integration.shard\timeline_test.dart 101:11  main.<fn>
```

**Comment by keyonghan** [comment]
@zanderso Same as https://github.com/flutter/flutter/issues/97160, there are three test flakes on `Windows tool_integration_tests_5_5`. Please help take a look and reassign appropriately. Thanks!

**Comment by zanderso** [comment]
I believe these were both due to bugs that have already been fixed. If these tests flake like this again, we can re-open.
