### ISSUE TITLE
Building for release/profile fails on arm64 raspberry pi 4

### ISSUE THREAD

**Issue by kwiatek91** [flutter/flutter#97281]
I am currently trying to build a flutter application on an ARM64 device (raspberry pi 4) using command `flutter build linux` but I am getting an error when building the release version. 

What is strange is that I can build --debug version on raspberry without any errors. 

On a macos device with an M1 I can easily build an application using docker using command flutter build linux. However using exactly the same docker image on a raspberry no longer works i get error during build.

On raspberry I also try native approach without docker, I added all libraries and tried to build the application natively but I get the same error.

## Steps to Reproduce

1. Install flutter sdk on raspberry pi 
2. Try command `flutter build linux -v` on any default project

## Logs

```
Build process failed
[ +38 ms]
#0 throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1 _runBuild (package:flutter_tools/src/linux/build_linux.dart:185:5)
<asynchronous suspension>
#2 buildLinux (package:flutter_tools/src/linux/build_linux.dart:77:5)
<asynchronous suspension>
#3 BuildLinuxCommand.runCommand
(package:flutter_tools/src/commands/build_linux.dart:88:5)
<asynchronous suspension>
#4 FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1140:27)
<asynchronous suspension>
#5 AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#6 CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#7 FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
<asynchronous suspension>
#8 AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#9 FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
<asynchronous suspension>
#10 run.<anonymous closure>.<anonymous closure>
(package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#11 AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12 main (package:flutter_tools/executable.dart:94:3)
<asynchronous suspension>

[ +186 ms] ensureAnalyticsSent: 162ms
[ +4 ms] Running shutdown hooks
[ +3 ms] Shutdown hooks complete
[ +3 ms] exiting with code 1
```

also flutter doctor info:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on Debian GNU/Linux 10 (buster) 5.10.63-v8+,
    locale C.UTF-8)
[✗] Chrome - develop for the web (Cannot find Chrome executable at
    google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Linux toolchain - develop for Linux desktop
[✗] Flutter IDE Support (No supported IDEs installed)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
```

Flutter doctor and flutter build linux command give exactly the same response on the native machine (raspberry pi 4) and the docker container on raspberry pi 4

</details>

**Comment by danagbemava-nc** [comment]
Hi @kwiatek91, thanks for reporting this. Please provide the full output of `flutter doctor -v` and `flutter build linux -v`. 

The output of `flutter build linux -v`  is likely to be huge so kindly put it into a .txt file and attach it here. 

Thank you

**Comment by kwiatek91** [comment]
Thank you @danagbemava-nc  for interest in the issue
Below output from docker container on raspberry pi 
[flutter-build-linux-v-docker.txt](https://github.com/flutter/flutter/files/7941363/flutter-build-linux-v-docker.txt)
[flutter-doctor-v-from-docker.txt](https://github.com/flutter/flutter/files/7941364/flutter-doctor-v-from-docker.txt)

and output from native raspberry pi 
[flutter-build-linux-v-native.txt](https://github.com/flutter/flutter/files/7941366/flutter-build-linux-v-native.txt)
[flutter-doctor-v-native.txt](https://github.com/flutter/flutter/files/7941368/flutter-doctor-v-native.txt)

**Comment by kwiatek91** [comment]
> Hi @kwiatek91, thanks for reporting this. Please provide the full output of `flutter doctor -v` and `flutter build linux -v`.
> 
> The output of `flutter build linux -v` is likely to be huge so kindly put it into a .txt file and attach it here.
> 
> Thank you



> Hi @kwiatek91, thanks for reporting this. Please provide the full output of `flutter doctor -v` and `flutter build linux -v`.
> 
> The output of `flutter build linux -v` is likely to be huge so kindly put it into a .txt file and attach it here.
> 
> Thank you

Thank you @danagbemava-nc  for interest in the issue
Below output from docker container on raspberry pi 
[flutter-build-linux-v-docker.txt](https://github.com/flutter/flutter/files/7941363/flutter-build-linux-v-docker.txt)
[flutter-doctor-v-from-docker.txt](https://github.com/flutter/flutter/files/7941364/flutter-doctor-v-from-docker.txt)

and output from native raspberry pi 
[flutter-build-linux-v-native.txt](https://github.com/flutter/flutter/files/7941366/flutter-build-linux-v-native.txt)
[flutter-doctor-v-native.txt](https://github.com/flutter/flutter/files/7941368/flutter-doctor-v-native.txt)

**Comment by danagbemava-nc** [comment]
Hi @kwiatek91, from what I can see in your logs (`flutter-build-linux-v-native.txt`)  it seems like there's an issue with where you've installed flutter to 

```
[ +105 ms] Flutter failed to delete a directory at
"/home/pi/Documents/esonel_client/linux/flutter/ephemeral/.plugin_symlinks".
                    Please ensure that the SDK and/or project is installed in a
location that has
                    read/write permissions for the current user.
```

> What is strange is that I can build --debug version on raspberry without any errors.

Can you provide the verbose logs for this? 


Also, what platform was the project initially created on?

**Comment by kwiatek91** [comment]
@danagbemava-nc 
This is a log with fixed permission to read/write
[flutter-build-linux-native - fixed permissions to catalog.log](https://github.com/flutter/flutter/files/7942468/flutter-build-linux-native.-.fixed.permissions.to.catalog.log) 

Here is a log with flutter build linux --debug -v
[flutter-build-linux-debug-v-native.txt](https://github.com/flutter/flutter/files/7942474/flutter-build-linux-debug-v-native.txt)

Project was created on macos but when i try some example project i also get build error.
We created demo project using flutter create. 
I will send the logs from this demo project tomorrow.

**Comment by danagbemava-nc** [comment]
Hi @kwiatek91, can you upgrade to the master channel and try again? 

`flutter channel master`
`flutter upgrade`

Then please provide the updated logs and flutter doctor -v. 

Thank you

**Comment by kwiatek91** [comment]
@danagbemava-nc 
here is updated flutter doctor:
[Uploading flutter-doctor-v-native-updated.txt…]()

I try to do flutter build linux on demo project after flutter upgrade but again it ends with fail
(i will provide logs from this fail asap)

**Comment by danagbemava-nc** [comment]
The error message in the logs aren't very clear. 

Can you please upgrade to the latest master version and create a new project and see if it makes any difference? 

Please share the logs for that as well. 

Thank you

**Comment by kwiatek91** [comment]
@danagbemava-nc  
Here i do upgrade then doctor then new project 
Full log here:
[full-log-from-new-demo-project-with-upgraded-flutter-master-native.txt](https://github.com/flutter/flutter/files/7956866/full-log-from-new-demo-project-with-upgraded-flutter-master-native.txt)

**Comment by danagbemava-nc** [comment]
Hi @kwiatek91, I appreciate your patience.

I assume `flutter build linux --debug` is working just fine. Can you share the output for `flutter build linux --profile -v` and `flutter build linux --debug -v`? 

Perhaps the `--profile` flag might reveal some more information. I'm not able to discern the cause of the build error from the latest logs which is very strange.

**Comment by kwiatek91** [comment]
Sure no problem: 
[flutter-build-linux-debug-v-.txt](https://github.com/flutter/flutter/files/7959360/flutter-build-linux-debug-v-.txt)
[flutter-build-linux-profile-v-.txt](https://github.com/flutter/flutter/files/7959362/flutter-build-linux-profile-v-.txt)

**Comment by danagbemava-nc** [comment]
I do not have a raspberry pi device personally, so I cannot reproduce this. 
Labelling this for further investigation from the team

## Summary
- Building for debug (`flutter build linux --debug`) works just fine on both `master` and `stable`
- Building for release (`flutter build linux --release/profile`) fails on both `master` and `stable`
- Error logs aren't very clear. The only error that seems to appear is `Target kernel_snapshot failed: Exception KernelSnapshot.build`
- Recent logs can be found in https://github.com/flutter/flutter/issues/97281#issuecomment-1024278060, https://github.com/flutter/flutter/issues/97281#issuecomment-1023977410

**Comment by Hixie** [comment]
That this works as much as it does is a little surprising to me to be honest! :-)
I've labeled this for further triage but I don't know when we'll be able to get to it. If you're able to debug this yourself we would be more than happy to help, see our contributing guide for a link to our Discord server.

**Comment by christopherfujino** [comment]
> Thank you @danagbemava-nc for interest in the issue Below output from docker container on raspberry pi [flutter-build-linux-v-docker.txt](https://github.com/flutter/flutter/files/7941363/flutter-build-linux-v-docker.txt) [flutter-doctor-v-from-docker.txt](https://github.com/flutter/flutter/files/7941364/flutter-doctor-v-from-docker.txt)
> 
> and output from native raspberry pi [flutter-build-linux-v-native.txt](https://github.com/flutter/flutter/files/7941366/flutter-build-linux-v-native.txt) [flutter-doctor-v-native.txt](https://github.com/flutter/flutter/files/7941368/flutter-doctor-v-native.txt)

On the native raspberry pi build, this is the actual failure message:

```
[ +105 ms] Flutter failed to delete a directory at

"/home/pi/Documents/esonel_client/linux/flutter/ephemeral/.plugin_symlinks".
                    Please ensure that the SDK and/or project is installed in a
location that has
                    read/write permissions for the current user.
                   
```

**Comment by kwiatek91** [comment]
> > Thank you @danagbemava-nc for interest in the issue Below output from docker container on raspberry pi [flutter-build-linux-v-docker.txt](https://github.com/flutter/flutter/files/7941363/flutter-build-linux-v-docker.txt) [flutter-doctor-v-from-docker.txt](https://github.com/flutter/flutter/files/7941364/flutter-doctor-v-from-docker.txt)
> > and output from native raspberry pi [flutter-build-linux-v-native.txt](https://github.com/flutter/flutter/files/7941366/flutter-build-linux-v-native.txt) [flutter-doctor-v-native.txt](https://github.com/flutter/flutter/files/7941368/flutter-doctor-v-native.txt)
> 
> On the native raspberry pi build, this is the actual failure message:
> 
> ```
> [ +105 ms] Flutter failed to delete a directory at
> 
> "/home/pi/Documents/esonel_client/linux/flutter/ephemeral/.plugin_symlinks".
>                     Please ensure that the SDK and/or project is installed in a
> location that has
>                     read/write permissions for the current user.
>                    
> ```
> 
> This is unrelated to running on a raspberry pi, your app must be in a directory where the user has write permissions for Flutter to work.

Thank you for response, yes there was a problem with permissions but we fix it already and for more clear view to problem we change subject application 
now we are debugging flutter demo app here you can see the logs 
https://github.com/flutter/flutter/files/7949373/flutter-build-linux-v-native-after-flutter-upgrade-on-demo-project-.txt

**Comment by kwiatek91** [comment]
> 

I will try to find time to join Discord server and debug app with Your team.

**Comment by kwiatek91** [comment]
> 

I will try to find time to join Discord server and debug app with Your team.

**Comment by kwiatek91** [comment]
> That this works as much as it does is a little surprising to me to be honest! :-) I've labeled this for further triage but I don't know when we'll be able to get to it. If you're able to debug this yourself we would be more than happy to help, see our contributing guide for a link to our Discord server.

@Hixie 
I will try to find time to join Discord server and debug app with Your team.

**Comment by ookami-kb** [comment]
Hey @kwiatek91 I've got the same problem, did you manage to solve it?

**Comment by kwiatek91** [comment]
@ookami-kb 
We just switch to build on mac mini (M1) and we build our app for deployment on docker environment
