### ISSUE TITLE
Slider in Draggable.feedback does not work as expected and throws an error `LeaderLayer anchor must come before FollowerLayer in paint order, but the reverse was true.` 

### ISSUE THREAD

**Issue by josne** [flutter/flutter#97292]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Drag container around. 
3. This works as expected (Feedback is shown and dragging works).
4. Change state of slider by moving thumb.
5. Drag container around.

**Expected results:** The container remains draggable and feedback is properly shown and no error occurs.

**Actual results:** The feedback is not displayed any more. The child `jumps` to the target position. The following error is thrown:

![draggable_slider](https://user-images.githubusercontent.com/42271940/151171084-13a74cd1-4ea9-454c-b520-a501f96c1e6f.gif)

```dart
[+13303 ms] ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
[   +3 ms] The following assertion was thrown during a scheduler callback:
[   +1 ms] Assertion failed:
[        ] file:///C:/Users/***/tools/flutter/packages/flutter/lib/src/rendering/layer.dart:2498:7
[        ] leader._lastOffset != null
[        ] "LeaderLayer anchor must come before FollowerLayer in paint order, but the reverse was true."
[        ] When the exception was thrown, this was the stack:
[        ] C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_
[        ] C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3    assertFailed
[        ] packages/flutter/src/rendering/layer.dart 2498:13                                                                          [_establishTransform]
[        ] packages/flutter/src/rendering/layer.dart 2557:5                                                                           addToScene
[        ] packages/flutter/src/rendering/layer.dart 546:5                                                                            [_addToSceneWithRetainedRendering]
[        ] packages/flutter/src/rendering/layer.dart 1106:12                                                                          addChildrenToScene
[        ] packages/flutter/src/rendering/layer.dart 1681:5                                                                           addToScene
[        ] packages/flutter/src/rendering/layer.dart 938:5                                                                            buildScene
[        ] packages/flutter/src/rendering/view.dart 226:30                                                                            compositeFrame
[        ] packages/flutter/src/rendering/binding.dart 501:18                                                                         drawFrame
[   +1 ms] packages/flutter/src/widgets/binding.dart 883:13                                                                           drawFrame
[        ] packages/flutter/src/rendering/binding.dart 363:5                                                                          [_handlePersistentFrameCallback]
[        ] packages/flutter/src/scheduler/binding.dart 1145:15                                                                        [_invokeFrameCallback]
[        ] packages/flutter/src/scheduler/binding.dart 1082:9                                                                         handleDrawFrame
[        ] packages/flutter/src/scheduler/binding.dart 996:5                                                                          [_handleDrawFrame]
[        ] C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/platform_dispatcher.dart 1005:13           invoke
[        ] C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/platform_dispatcher.dart 159:5             invokeOnDrawFrame
[        ] C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine.dart 455:45                                <fn>
[        ] ════════════════════════════════════════════════════════════════════════════════════════════════════

```

<details>
<summary>
Code Sample
</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const SampleApp());

final GlobalKey myKey = GlobalKey();

class SampleApp extends StatefulWidget {
  const SampleApp({Key? key}) : super(key: key);

  @override
  _SampleAppState createState() => _SampleAppState();
}

class _SampleAppState extends State<SampleApp> {
  Offset position = Offset.zero;

  @override
  Widget build(BuildContext context) {
    final floatingPanel = Container(
      key: myKey,
      padding: const EdgeInsets.all(20),
      color: Colors.teal,
      child: const ContentWidget(),
    );
    return MaterialApp(
      title: 'Sample',
      home: Scaffold(
          body: Stack(
        children: [
          Positioned(
            left: position.dx,
            top: position.dy,
            child: Draggable<int>(
              data: 1,
              onDragEnd: (DraggableDetails details) {
                setState(() {
                  position = details.offset;
                });
              },
              feedback: floatingPanel,
              childWhenDragging: const SizedBox.shrink(),
              child: floatingPanel,
            ),
          )
        ],
      )),
    );
  }
}

class ContentWidget extends StatefulWidget {
  const ContentWidget({Key? key}) : super(key: key);

  @override
  _ContentWidgetState createState() => _ContentWidgetState();
}

class _ContentWidgetState extends State<ContentWidget> {
  double sliderValue = 0;
  @override
  Widget build(BuildContext context) => Material(
        child: Slider(
            value: sliderValue,
            onChanged: (v) {
              setState(() {
                sliderValue = v;
              });
            }),
      );
}

```

</details>

<details>
  <summary>Logs</summary>

```
Analyzing sample_apps...                                                
No issues found! (ran in 7.5s)
```

```
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19042.867], locale de-DE)
    • Flutter version 2.8.1 at C:\Users\jonscn\tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (6 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\jonscn\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Professional 2019 16.7.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional
    • Visual Studio Professional 2019 version 16.7.30413.136
    • Windows 10 SDK version 10.0.17763.0

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.63.2)
    • VS Code at C:\Users\jonscn\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.32.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.867]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 97.0.4692.71
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 97.0.1072.62

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
This doesn't seem to be specific to web, as running the code on mobile (ios in my case), results in same error as below:

<details>
<summary> console error log </summary>

```

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
LeaderLayer anchor must come before FollowerLayer in paint order, but the reverse was true.
'package:flutter/src/rendering/layer.dart':
Failed assertion: line 2507 pos 7: '_debugCheckLeaderBeforeFollower(forwardLayers, inverseLayers)'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      FollowerLayer._establishTransform (package:flutter/src/rendering/layer.dart:2507:7)
#3      FollowerLayer.addToScene (package:flutter/src/rendering/layer.dart:2554:5)
#4      Layer._addToSceneWithRetainedRendering (package:flutter/src/rendering/layer.dart:546:5)
#5      ContainerLayer.addChildrenToScene (package:flutter/src/rendering/layer.dart:1106:13)
#6      TransformLayer.addToScene (package:flutter/src/rendering/layer.dart:1681:5)
#7      ContainerLayer.buildScene (package:flutter/src/rendering/layer.dart:938:5)
#8      RenderView.compositeFrame (package:flutter/src/rendering/view.dart:228:37)
#9      RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:501:18)
#10     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#11     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#12     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#13     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
#14     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:995:5)
#18     _invoke (dart:ui/hooks.dart:151:10)
#19     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#20     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 5 frames from class _AssertionError and dart:async)
====================================================================================================

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
LeaderLayer anchor must come before FollowerLayer in paint order, but the reverse was true.
'package:flutter/src/rendering/layer.dart':
Failed assertion: line 2507 pos 7: '_debugCheckLeaderBeforeFollower(forwardLayers, inverseLayers)'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      FollowerLayer._establishTransform (package:flutter/src/rendering/layer.dart:2507:7)
#3      FollowerLayer.addToScene (package:flutter/src/rendering/layer.dart:2554:5)
#4      Layer._addToSceneWithRetainedRendering (package:flutter/src/rendering/layer.dart:546:5)
#5      ContainerLayer.addChildrenToScene (package:flutter/src/rendering/layer.dart:1106:13)
#6      TransformLayer.addToScene (package:flutter/src/rendering/layer.dart:1681:5)
#7      ContainerLayer.buildScene (package:flutter/src/rendering/layer.dart:938:5)
#8      RenderView.compositeFrame (package:flutter/src/rendering/view.dart:228:37)
#9      RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:501:18)
#10     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#11     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#12     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#13     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
#14     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:995:5)
#18     _invoke (dart:ui/hooks.dart:151:10)
#19     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#20     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 5 frames from class _AssertionError and dart:async)
====================================================================================================

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
LeaderLayer anchor must come before FollowerLayer in paint order, but the reverse was true.
'package:flutter/src/rendering/layer.dart':
Failed assertion: line 2507 pos 7: '_debugCheckLeaderBeforeFollower(forwardLayers, inverseLayers)'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      FollowerLayer._establishTransform (package:flutter/src/rendering/layer.dart:2507:7)
#3      FollowerLayer.addToScene (package:flutter/src/rendering/layer.dart:2554:5)
#4      Layer._addToSceneWithRetainedRendering (package:flutter/src/rendering/layer.dart:546:5)
#5      ContainerLayer.addChildrenToScene (package:flutter/src/rendering/layer.dart:1106:13)
#6      TransformLayer.addToScene (package:flutter/src/rendering/layer.dart:1681:5)
#7      ContainerLayer.buildScene (package:flutter/src/rendering/layer.dart:938:5)
#8      RenderView.compositeFrame (package:flutter/src/rendering/view.dart:228:37)
#9      RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:501:18)
#10     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#11     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#12     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#13     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
#14     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:995:5)
#18     _invoke (dart:ui/hooks.dart:151:10)
#19     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#20     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 5 frames from class _AssertionError and dart:async)
====================================================================================================

```

</details>

May be related to : https://github.com/flutter/flutter/pull/92598 / https://github.com/flutter/flutter/pull/96144

<details>
<summary> master, stable flutter doctor -v </summary>

```
[✓] Flutter (Channel master, 2.10.0-1.0.pre.307, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.10.0-1.0.pre.307 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b7424c619c (3 hours ago), 2022-01-26 17:25:45 -0800
    • Engine revision c248c6e38e
    • Dart version 2.17.0 (build 2.17.0-63.0.dev)
    • DevTools version 2.10.0-dev.1

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.4 19E2269
      darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 97.0.4692.99

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[✓] Flutter (Channel stable, 2.8.1, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.8.1 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (13 hours ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dhs/Library/Android/sdk
    • Java binary at: /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.    

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 93.0.4577.82


• No issues found!

```

</details>



/cc @goderbauer

**Comment by josne** [comment]
Hi @darshankawar,

true. I only tested it with web, but it seems to be an issue on other platforms as well. 

I tested the same behavior with multiple other widgets but it seems to be slider specific (at least I did not experience this with another widget so far). I have no workaround for the issue and would like to avoid building a custom slider widget just because of this.

**Comment by bbischler** [comment]
I have run into the same problem.
Any news here?

**Comment by SpencerC** [comment]
Same problem here intermittently.

**Comment by Glitchy-Tozier** [comment]
@josne Is one of those other cases related to TextFields?
I'm trying to create dragable `TextFormFields` using `ReorderableListView.builder()`, and everything works fine until android's cursor-handle shows up. Then smooth dragging goes out the window.

**Comment by darshankawar** [comment]
/cc @HansMuller @goderbauer .
There was a similar issue reported : https://github.com/flutter/flutter/issues/102902

**Comment by mano3891** [comment]
> @josne Is one of those other cases related to TextFields? I'm trying to create dragable `TextFormFields` using `ReorderableListView.builder()`, and everything works fine until android's cursor-handle shows up. Then smooth dragging goes out the window.

I get a similar error when I have a TextField inside a ReorderableListView. In my Listview row, I have an icon and a textfield. It works fine as long as I don't focus the textfield and just reorder by clicking the icon. Once the textfield is focused, dragging doesn't work and keeps crashing with "LeaderLayer anchor...." error.

**Comment by gianmarcocalbi** [comment]
> @josne Is one of those other cases related to TextFields? I'm trying to create dragable `TextFormFields` using `ReorderableListView.builder()`, and everything works fine until android's cursor-handle shows up. Then smooth dragging goes out the window.

So far I have resolved by removing the focus when the drag gesture starts:

```dart
ReorderableListView.builder(
  onReorderStart: (_) {
    FocusScope.of(context).unfocus();
  },
  //...
);
```

**Comment by yvs2014** [comment]
btw,
this exception "LeaderLayer anchor must come before FollowerLayer in paint order, but the reverse was true" with Slider looks like caused by its label rendering.
So that, wrapping Slider with ` SliderTheme.of(context).copyWith(showValueIndicator: ShowValueIndicator.never), child: Slider(... `, and fixing forgotten 'if' in
https://github.com/flutter/flutter/blob/df602da850247ffb410a7807e39b93be39cceb1c/packages/flutter/lib/src/material/slider.dart#L1490
with
```
-    _state.showValueIndicator();
+    if (showValueIndicator) _state.showValueIndicator();
```
made it possible to get rid of this annoying exception with ReorderableListView use

**Comment by danieljosua1** [comment]
It seems that this issue has resurfaced. Unfortunately, @gianmarcocalbi  's workaround seems to be not working in the latest version. Any updates or alternative solutions would be appreciated!
