### ISSUE TITLE
Linux web_long_running_tests flakes with error `version info not in JSON`

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#97307]
(part of https://github.com/flutter/flutter/issues/97036)
These data is based on Q4 2021 flakes that happened from 10/01/2021 to 01/13/2022

1 flake when running `cd dev/integration_tests/web_e2e_tests; ../../../bin/flutter drive --target=test_driver/url_strategy_integration.dart --browser-name=chrome --no-sound-null-safety -d web-server --release --web-renderer=html` ([2542](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_long_running_tests_1_5/2542/overview) on 12/28/2021)

```
▌02:30:03▐ RUNNING: cd dev/integration_tests/web_e2e_tests; ../../../bin/flutter drive --target=test_driver/url_strategy_integration.dart --browser-name=chrome --no-sound-null-safety -d web-server --release --web-renderer=html
Running "flutter pub get" in web_e2e_tests...                    1,668ms
Launching test_driver/url_strategy_integration.dart on Web Server in release mode...
Compiling test_driver/url_strategy_integration.dart for the Web...        35.5s
test_driver/url_strategy_integration.dart is being served at http://localhost:36967
The web-server device requires the Dart Debug Chrome extension for debugging. Consider using the Chrome or Edge devices for an improved development workflow.

UnknownException (13): unknown error: version info not in JSON
  (Driver info: chromedriver=84.0.4147.30 (48b3e868b4cc0aa7e8149519690b6f6949e110a8-refs/branch-heads/4147@{#310}),platform=Linux 4.9.0-14-amd64 x86_64)
#0      parseJsonWireResponse (package:webdriver/src/handler/json_wire/utils.dart:82:9)
#1      JsonWireSessionHandler.parseInfoResponse (package:webdriver/src/handler/json_wire/session.dart:27:21)
#2      JsonWireSessionHandler.parseCreateResponse (package:webdriver/src/handler/json_wire/session.dart:18:7)
#3      InferSessionHandler.parseCreateResponse (package:webdriver/src/handler/infer_handler.dart:100:39)
#4      AsyncRequestClient.send (package:webdriver/src/common/request_client.dart:96:32)
<asynchronous suspension>
#5      createDriver (package:webdriver/async_core.dart:64:19)
<asynchronous suspension>
#6      WebDriverService.startTest (package:flutter_tools/src/drive/web_driver_service.dart:141:19)
<asynchronous suspension>
#7      DriveCommand.runCommand (package:flutter_tools/src/commands/drive.dart:272:28)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#16     main (package:flutter_tools/executable.dart:94:3)
<asynchronous suspension>
```

**Comment by keyonghan** [comment]
Another flake on `Linux web_long_running_tests_2_5`: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_long_running_tests_2_5/2263/overview

**Comment by keyonghan** [comment]
Another flake: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_long_running_tests_1_5/2990/overview

**Comment by keyonghan** [comment]
This is still happening: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_long_running_tests_2_5/3291/overview

**Comment by christopherfujino** [comment]
A user filed this as well: https://github.com/flutter/flutter/issues/101041

**Comment by keyonghan** [comment]
One more: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_long_running_tests_1_5/3585/overview

**Comment by keyonghan** [comment]
This happened again: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_long_running_tests_1_5/3845/overview

Marking as P2 as this is consistently happening.

**Comment by yjbanov** [comment]
This is the same as https://github.com/flutter/flutter/issues/102660, no?

**Comment by keyonghan** [comment]
Dup of https://github.com/flutter/flutter/issues/102660.
