### ISSUE TITLE
Linux web_long_running_tests_2_5 flakes on `Unexpected character`

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#97318]
(part of [#97036](https://github.com/flutter/flutter/issues/97036))
These data is based on Q4 2021 flakes that happened from 10/01/2021 to 01/13/2022

1 flake on `timeout`: [2380](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_long_running_tests_2_5/2380/overview) (happened on 12/10/2021)

```
▌22:28:23▐ RUNNING: cd dev/integration_tests/web; ../../../bin/flutter run --debug -d chrome --web-run-headless --dart-define=FLUTTER_WEB_USE_SKIA=false --dart-define=FLUTTER_WEB_AUTO_DETECT=false -t lib/web_directory_loading.dart
Launching lib/web_directory_loading.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             617ms

FormatException: Unexpected character (at character 1)
<!DOCTYPE HTML>
^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1405:5)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1272:9)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:937:22)
#3      _parseJson (dart:convert-patch/convert_patch.dart:40:10)
#4      JsonDecoder.convert (dart:convert/json.dart:612:36)
#5      JsonCodec.decode (dart:convert/json.dart:216:41)
#6      jsonDecode (dart:convert/json.dart:155:10)
#7      ChromeConnection.getTabs (package:webkit_inspection_protocol/webkit_inspection_protocol.dart:44:10)
<asynchronous suspension>
#8      ChromeConnection.getTab (package:webkit_inspection_protocol/webkit_inspection_protocol.dart:57:25)
<asynchronous suspension>
#9      ChromiumLauncher._connect (package:flutter_tools/src/web/chrome.dart:401:9)
<asynchronous suspension>
#10     ChromiumDevice.startApp (package:flutter_tools/src/web/web_device.dart:134:17)
<asynchronous suspension>
#11     ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:307:9)
<asynchronous suspension>
#12     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>

Unable to connect to Chrome debug port: 35881
 FormatException: Unexpected character (at character 1)
<!DOCTYPE HTML>
^
```

**Comment by yjbanov** [comment]
Looks like a WebDriver protocol corruption. We've since upgraded to Chrome 96. I haven't seen anything like it yet.
