### ISSUE TITLE
Linux web_long_running_tests flakes on `Failed to create server socket`

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#97319]
(part of [#97036](https://github.com/flutter/flutter/issues/97036))
These data is based on Q4 2021 flakes that happened from 10/01/2021 to 01/13/2022

1 flake on `timeout`: [1778](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_long_running_tests_2_5/1778/overview) (happened on 10/05/2021)

```
▌03:12:19▐ RUNNING: cd dev/integration_tests/web; ../../../bin/flutter run --debug -d chrome --web-run-headless --dart-define=FLUTTER_WEB_USE_SKIA=false --dart-define=FLUTTER_WEB_AUTO_DETECT=false --dart-define=test.valueA=Example,A --dart-define=test.valueB=Value -t lib/web_define_loading.dart
Launching lib/web_define_loading.dart on Chrome in debug mode...

SocketException: Failed to create server socket (OS Error: The shared flag to bind() needs to be `true` if binding multiple times on the same (address, port) combination.), address = ::1, port = 42399
#0      _NativeSocket.bind (dart:io-patch/socket_patch.dart:966:7)
<asynchronous suspension>
#1      HttpMultiServer._loopback (package:http_multi_server/http_multi_server.dart:183:22)
<asynchronous suspension>
#2      ExtensionBackend.start (package:dwds/src/servers/extension_backend.dart:52:18)
<asynchronous suspension>
#3      Dwds.start (package:dwds/dwds.dart:136:26)
<asynchronous suspension>
#4      WebAssetServer.start (package:flutter_tools/src/isolated/devfs_web.dart:274:23)
<asynchronous suspension>
#5      WebDevFS.create (package:flutter_tools/src/isolated/devfs_web.dart:727:22)
<asynchronous suspension>
#6      ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:285:25)
<asynchronous suspension>
#7      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>

Failed to establish connection with the application instance in Chrome.
This can happen if the websocket connection used by the web tooling is unable to correctly establish a connection, for example due to a firewall.
```

**Comment by keyonghan** [comment]
Another flake on `Linux web_long_running_tests_4_5`: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_long_running_tests_4_5/2317/overview
