### ISSUE TITLE
Linux web_long_running_tests_5_5 flakes on `type 'Null' is not a subtype of type 'Map<String, dynamic>' in type cast`

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#97322]
(part of [#97036](https://github.com/flutter/flutter/issues/97036))
These data is based on Q4 2021 flakes that happened from 10/01/2021 to 01/13/2022

1 flake on `type 'Null' is not a subtype of type 'Map<String, dynamic>' in type cast`: [2676](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_long_running_tests_5_5/2676/overview) (happened on 01/13/2022)

```
▌22:59:16▐ RUNNING: cd dev/integration_tests/web_e2e_tests; ../../../bin/flutter drive --target=test_driver/image_loading_integration.dart --browser-name=chrome --no-sound-null-safety -d web-server --profile --web-renderer=html
Running "flutter pub get" in web_e2e_tests...                    1,594ms
Launching test_driver/image_loading_integration.dart on Web Server in profile mode...
Compiling test_driver/image_loading_integration.dart for the Web...        34.8s
test_driver/image_loading_integration.dart is being served at http://localhost:46373
The web-server device requires the Dart Debug Chrome extension for debugging. Consider using the Chrome or Edge devices for an improved development workflow.
Unhandled exception:
type 'Null' is not a subtype of type 'Map<String, dynamic>' in type cast
#0      WebFlutterDriver.sendCommand (package:flutter_driver/src/driver/web_driver.dart:126:33)
<asynchronous suspension>
#1      FlutterDriver.requestData (package:flutter_driver/src/driver/driver.dart:522:39)
<asynchronous suspension>
#2      integrationDriver (package:integration_test/integration_test_driver.dart:82:29)
<asynchronous suspension>
Application finished.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

**Comment by yjbanov** [comment]
See https://github.com/flutter/flutter/issues/96783
