### ISSUE TITLE
[tool_crash]CastError: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'List<Object?>' in type cast

### ISSUE THREAD

**Issue by dujianchi** [flutter/flutter#97343]
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter run --machine --start-paused -d web-server --dart-define=flutter.inspector.structuredErrors=true --web-server-debug-protocol ws --web-server-debug-backend-protocol ws --web-server-debug-injected-client-protocol ws --web-allow-expose-url --devtools-server-address http://127.0.0.1:9100/ --target lib/main.dart

## exception

_CastError: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'List<Object?>' in type cast

```
#0      BuiltJsonSerializers._deserialize (package:built_value/src/built_json_serializers.dart:134:32)
#1      BuiltJsonSerializers.deserialize (package:built_value/src/built_json_serializers.dart:124:18)
#2      new ExtensionDebugger.<anonymous closure> (package:dwds/src/servers/extension_debugger.dart:70:33)
#3      _rootRunUnary (dart:async/zone.dart:1436:47)
#4      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#8      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
#9      _MapStream._handleData (dart:async/stream_pipe.dart:218:10)
#10     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
#11     _rootRunUnary (dart:async/zone.dart:1444:13)
#12     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#13     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#14     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#15     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#16     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#17     _StreamController._add (dart:async/stream_controller.dart:607:7)
#18     _StreamController.add (dart:async/stream_controller.dart:554:5)
#19     new WebSocketImpl.fromSocket.<anonymous closure> (package:web_socket_channel/src/copy/web_socket_impl.dart:730:21)
#20     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:26)
#21     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:208:15)
#22     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:14)
#23     _rootRunUnary (dart:async/zone.dart:1436:47)
#24     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#25     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#26     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#27     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#28     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#29     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#30     _WebSocketProtocolTransformer._messageFrameEnd (package:web_socket_channel/src/copy/web_socket_impl.dart:319:23)
#31     _WebSocketProtocolTransformer.add (package:web_socket_channel/src/copy/web_socket_impl.dart:218:46)
#32     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#33     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:26)
#34     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:208:15)
#35     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:14)
#36     _rootRunUnary (dart:async/zone.dart:1436:47)
#37     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#38     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#39     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#40     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#41     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#42     _StreamController._add (dart:async/stream_controller.dart:607:7)
#43     _StreamController.add (dart:async/stream_controller.dart:554:5)
#44     _Socket._onData (dart:io-patch/socket_patch.dart:2302:41)
#45     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:26)
#46     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:208:15)
#47     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:14)
#48     _rootRunUnary (dart:async/zone.dart:1444:13)
#49     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#50     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#51     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#52     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#53     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#54     _StreamController._add (dart:async/stream_controller.dart:607:7)
#55     _StreamController.add (dart:async/stream_controller.dart:554:5)
#56     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1830:33)
#57     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1314:14)
#58     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#59     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#60     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:122:13)
#61     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:193:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, 2.8.1, on CentOS Linux 7 (Core) 5.15.1-1.el7.elrepo.x86_64, locale en_US.UTF-8)
    • Flutter version 2.8.1 at /home/vscode/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (6 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools

! Doctor found issues in 3 categories.
```

**Comment by darshankawar** [comment]
Labeling it for further insights from the team.

For reference: `Channel stable, 2.8.1, on CentOS Linux 7 (Core) 5.15.1-1.el7.elrepo.x86_64`

/cc @christopherfujino

**Comment by christopherfujino** [comment]
@dujianchi I believe this is a problem in your app code, due to the stacktrace being in `package:built_value`, which the Flutter SDK does not use. It looks like the schema of your code-generated code is wrong, expecting a list where you actually have a map.

**Comment by dujianchi** [comment]
My mistake. This is indeed a bug for third-party libraries.
