### ISSUE TITLE
[web]FormatException: Unexpected character (at character 1)           

### ISSUE THREAD

**Issue by devdilipstr** [flutter/flutter#97353]
`flutter run -d chrome --v`

<details>
<summary> verbose log </summary>

```

[ +147 ms] executing: uname -m
[  +52 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +8 ms] executing: [/home/dilip/Downloads/flutter/] git -c
log.showSignature=false log -n 1 --pretty=format:%H
[ +201 ms] Exit code 0 from: git -c log.showSignature=false log -n 1
--pretty=format:%H
[        ] 77d935af4db863f6abd0b9c31c7e6df2a13de57b
[        ] executing: [/home/dilip/Downloads/flutter/] git tag --points-at
77d935af4db863f6abd0b9c31c7e6df2a13de57b
[ +338 ms] Exit code 0 from: git tag --points-at
77d935af4db863f6abd0b9c31c7e6df2a13de57b
[        ] 2.8.1
[  +14 ms] executing: [/home/dilip/Downloads/flutter/] git rev-parse
--abbrev-ref --symbolic @{u}
[  +17 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/dilip/Downloads/flutter/] git ls-remote --get-url
origin
[   +5 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +138 ms] executing: [/home/dilip/Downloads/flutter/] git rev-parse
--abbrev-ref HEAD
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +150 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping
update.
[  +19 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[ +578 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[  +12 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[ +128 ms] Skipping pub get: version match.
[ +190 ms] Generating
/home/dilip/testapp/android/app/src/main/java/io/flutter/plugins/GeneratedPlugin
Registrant.java
[ +397 ms] Launching lib/main.dart on Chrome in debug mode...
[ +259 ms] Updating assets
[ +304 ms] Waiting for connection from debug service on Chrome...
[ +137 ms] <- reset
[   +9 ms] /home/dilip/Downloads/flutter/bin/cache/dart-sdk/bin/dart
--disable-dart-dev
/home/dilip/Downloads/flutter/bin/cache/artifacts/engine/linux-x64/frontend_serv
er.dart.snapshot --sdk-root
/home/dilip/Downloads/flutter/bin/cache/flutter_web_sdk/ --incremental
--target=dartdevc --debugger-module-names --experimental-emit-debug-metadata
-DFLUTTER_WEB_AUTO_DETECT=true --output-dill
/tmp/flutter_tools.XTSPTE/flutter_tool.NRCUFR/app.dill --libraries-spec
file:///home/dilip/Downloads/flutter/bin/cache/flutter_web_sdk/libraries.json
--packages /home/dilip/testapp/.dart_tool/package_config.json
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts
--track-widget-creation --filesystem-root
/tmp/flutter_tools.XTSPTE/flutter_tools.FQNQDI --filesystem-scheme
org-dartlang-app --initialize-from-dill
build/b1b715402d823b7fd5c2b68d2edcb2ce.cache.dill.track.dill --platform
file:///home/dilip/Downloads/flutter/bin/cache/flutter_web_sdk/kernel/flutter_dd
c_sdk_sound.dill --sound-null-safety
[  +10 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+33823 ms] Waiting for connection from debug service on Chrome... (completed in
33.5s)
[   +6 ms] Synced 28.4MB.
[   +2 ms] <- accept
[        ] Caching compiled dill
[+9201 ms] Using Google Chrome 97.0.4692.99 

[ +283 ms] executing: uname -m
[  +31 ms] Exit code 0 from: uname -m
[        ] x86_64
[+4690 ms] [CHROME]:
[        ] [CHROME]:DevTools listening on
ws://127.0.0.1:36045/devtools/browser/a355cfe7-4fa1-4d74-ba24-f8c553668844
[ +408 ms] FormatException: Unexpected character (at character 1)
                    Bad Gateway: /json
                    ^
                    
                    #0      _ChunkedJsonParser.fail
                    (dart:convert-patch/convert_patch.dart:1405:5)
                    #1      _ChunkedJsonParser.parseNumber
                    (dart:convert-patch/convert_patch.dart:1272:9)
                    #2      _ChunkedJsonParser.parse
                    (dart:convert-patch/convert_patch.dart:937:22)
                    #3      _parseJson
                    (dart:convert-patch/convert_patch.dart:40:10)
                    #4      JsonDecoder.convert (dart:convert/json.dart:506:36)
                    #5      JsonCodec.decode (dart:convert/json.dart:157:41)
                    #6      jsonDecode (dart:convert/json.dart:96:10)
                    #7      ChromeConnection.getTabs
                    (package:webkit_inspection_protocol/webkit_inspection_protoc
                    ol.dart:44:10)
                    <asynchronous suspension>
                    #8      ChromiumLauncher._connect
                    (package:flutter_tools/src/web/chrome.dart:398:9)
                    <asynchronous suspension>
                    #9      ChromiumDevice.startApp
                    (package:flutter_tools/src/web/web_device.dart:134:17)
                    <asynchronous suspension>
                    #10     ResidentWebRunner.run.<anonymous closure>
                    (package:flutter_tools/src/isolated/resident_web_runner.dart
                    :307:9)
                    <asynchronous suspension>
                    #11     asyncGuard.<anonymous closure>
                    (package:flutter_tools/src/base/async_guard.dart:111:24)
                    <asynchronous suspension>


[+3033 ms] "flutter run" took 53,637ms.
[   +5 ms] Unable to connect to Chrome debug port: 36045
            FormatException: Unexpected character (at character 1)
           Bad Gateway: /json
           ^
           
[        ] 
           #0      throwToolExit
(package:flutter_tools/src/base/common.dart:10:3)
           #1      ChromiumLauncher._connect
           (package:flutter_tools/src/web/chrome.dart:402:9)
           <asynchronous suspension>
           #2      ChromiumDevice.startApp
           (package:flutter_tools/src/web/web_device.dart:134:17)
           <asynchronous suspension>
           #3      ResidentWebRunner.run.<anonymous closure>
           (package:flutter_tools/src/isolated/resident_web_runner.dart:307:9)
           <asynchronous suspension>
           #4      asyncGuard.<anonymous closure>
           (package:flutter_tools/src/base/async_guard.dart:111:24)
           <asynchronous suspension>
           
           
[ +253 ms] ensureAnalyticsSent: 251ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

```

</details>

reproduce the above error and web debug not working with flutter.

`flutter doctor -v`
```
[✓] Flutter (Channel stable, 2.8.1, on Linux Lite 5.6 5.4.0-96-generic, locale
    en_IN)
    • Flutter version 2.8.1 at /home/dilip/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (6 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    • Android SDK at /home/dilip/Android/Sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /home/dilip/Downloads/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /home/dilip/Downloads/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.63.2)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 97.0.4692.99

! Doctor found issues in 1 category.
```

**Comment by darshankawar** [comment]
@devdilipstr 
Looking at the logs, you are probably hitting https://github.com/flutter/flutter/issues/94886, https://github.com/flutter/flutter/issues/97318 and https://github.com/flutter/flutter/issues/97330, so please follow-up in those issues by subscribing to them for further updates.
Closing as a duplicate.
