### ISSUE TITLE
[tool_crash] SocketException: Failed to create datagram socket, OS Error: Address already in use, errno = 48

### ISSUE THREAD

**Issue by yianzhou** [flutter/flutter#97364]
## Command
```
flutter attach
```

## Steps to Reproduce
1. cd path/to/main.dart
2. flutter attach

## Logs
SocketException: Failed to create datagram socket, OS Error: Address already in use, errno = 48
```
#0      _NativeSocket.bindDatagram (dart:io-patch/socket_patch.dart:981:7)
<asynchronous suspension>
#1      MDnsClient.start (package:multicast_dns/multicast_dns.dart:128:40)
<asynchronous suspension>
#2      MDnsObservatoryDiscovery.query (package:flutter_tools/src/mdns_discovery.dart:66:7)
<asynchronous suspension>
#3      MDnsObservatoryDiscovery.getObservatoryUri (package:flutter_tools/src/mdns_discovery.dart:153:51)
<asynchronous suspension>
#4      AttachCommand._attachToDevice (package:flutter_tools/src/commands/attach.dart:271:11)
<asynchronous suspension>
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#6      AttachCommand.runCommand (package:flutter_tools/src/commands/attach.dart:220:5)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
```
```
[✓] Flutter (Channel flutter-2.5-candidate.5, 2.5.3, on macOS 12.1 21C52 darwin-x64, locale en-CN)
    • Flutter version 2.5.3 at /Users/yianzhou/Documents/flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision 18116933e7 (3 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/yianzhou/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.2.1, Build version 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (3 available)
    • iPhone 13 mini (mobile) • 00008110-000119080C42801E            • ios            • iOS 15.1 19B74
    • iPhone 13 (mobile)      • 37399F6A-35C4-4ED8-B460-D6E0C043EBAF • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 97.0.4692.99

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: module
**Version**: 1.0.0+1
**Material**: true
**Android X**: true
**Module**: true
**Plugin**: false
**Android package**: com.example.main
**iOS bundle identifier**: com.example.main
**Creation channel**: stable
**Creation framework version**: 18116933e77adc82f80866c928266a5b4f1ed645
### Plugins
device_info-2.0.3
flutter_plugin_android_lifecycle-2.0.5
image_picker-0.8.4+4
image_picker_for_web-2.1.5
path_provider-2.0.8
path_provider_android-2.0.11
path_provider_ios-2.0.7
path_provider_linux-2.1.5
path_provider_macos-2.0.5
path_provider_windows-2.0.5
permission_handler-7.1.0
shared_preferences-2.0.8
shared_preferences_linux-2.0.4
shared_preferences_macos-2.0.2
shared_preferences_web-2.0.3
shared_preferences_windows-2.0.4
sqflite-2.0.2

**Comment by maheshmnj** [comment]
Hi @yianzhou,

There is a similar issue describing this case https://github.com/flutter/flutter/issues/53477, Please follow up there for further updates, Closing this issue as a duplicate. If you disagree feel free to write in the comments and I will reopen it.

Thank you.
