### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException, Cannot execute operation because FlutterJNI is not attached to native

### ISSUE THREAD

**Issue by RaphaelRevivor** [flutter/flutter#97406]
Hi,

I recently saw crashes with the following error messages:

> Fatal Exception: java.lang.RuntimeException
> Cannot execute operation because FlutterJNI is not attached to native.

From Google crashlytics when I gradually rolled out my app on Google Play Store.

I'm using flutter 2.5.3. It looks like there are similar issues that happened before, but are with much older flutter versions.

So far I can see crashes from Google Pixel 6 and Sumsang Galaxy A21s. Android versions are 11 and 12.

Detailed log from crashlytics:
<details>
Fatal Exception: java.lang.RuntimeException: Cannot execute operation because FlutterJNI is not attached to native.
       at io.flutter.embedding.engine.FlutterJNI.ensureAttachedToNative(FlutterJNI.java:9)
       at io.flutter.embedding.engine.FlutterJNI.dispatchPointerDataPacket(FlutterJNI.java:3)
       at io.flutter.embedding.engine.renderer.FlutterRenderer.a(FlutterRenderer.java:2)
       at io.flutter.embedding.android.AndroidTouchProcessor.a(AndroidTouchProcessor.java:125)
       at io.flutter.embedding.android.AndroidTouchProcessor.b(AndroidTouchProcessor.java:2)
       at io.flutter.embedding.android.FlutterView.onTouchEvent(FlutterView.java:22)
       at android.view.View.dispatchTouchEvent(View.java:15199)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3914)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3578)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3535)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3535)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3535)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3535)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:915)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1957)
       at android.app.Activity.dispatchTouchEvent(Activity.java:4182)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:873)
       at android.view.View.dispatchPointerEvent(View.java:15458)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7457)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7233)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6595)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6652)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6618)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6786)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6626)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6843)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6599)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6652)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6618)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6626)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6599)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9880)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9718)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9671)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10014)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:220)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:335)
       at android.os.Looper.loop(Looper.java:206)
       at android.app.ActivityThread.main(ActivityThread.java:8633)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
</details>

flutter doctor -v results:
<details>
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-arm, locale en-SE)
    • Flutter version 2.5.3 at /Users/raphael/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/raphael/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.64.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 97.0.4692.99

• No issues found!
</details>

Did anyone encounter this recently? Any hints or suggestions are welcome.

Regards,
Raphael

**Comment by darshankawar** [comment]
@RaphaelRevivor 
Is there a way to replicate this crash locally ?
There's similar issue open but your stacktrace looks a bit different from it, so it may or may not be same: https://github.com/flutter/flutter/issues/81830
Also, try to upgrade to latest stable and then see if you still get same crash log or not.
If so, we would need a complete minimal reproducible code sample that replicates the error.

Thanks.

**Comment by RaphaelRevivor** [comment]
@darshankawar Unfortunately right now I don't know how to reproduce the issue locally. When testing locally, the app seemed fine. I only got reports from Crashlytics so far.

**Comment by darshankawar** [comment]
@RaphaelRevivor 
Can you try to upgrade to latest stable (2.8.1) and see if you still get same crash or not ?
