### ISSUE TITLE
Error in Flutter run while downloading gradle behind proxy

### ISSUE THREAD

**Issue by devdilipstr** [flutter/flutter#97414]
I am doing
`Flutter run -v'

-Pfilesystem-scheme=org-dartlang-root assembleDebug
[+1484 ms] Downloading
https://services.gradle.org/distributions/gradle-6.7-all.zip
[+134295 ms] Exception in thread "main" java.net.ConnectException: Connection
timed out (Connection timed out)
[ +220 ms] 	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
[        ] 	at
java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.jav
a:399)
[        ] 	at
java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketI
mpl.java:242)
[        ] 	at
java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:
224)
[        ] 	at
java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[        ] 	at java.base/java.net.Socket.connect(Socket.java:609)
[        ] 	at
java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:289)

**Not working behind proxy??**

**Comment by darshankawar** [comment]
@devdilipstr 
Check [this](https://yamsergey.medium.com/flutter-and-proxy-1e2b6acd24f5) article on Flutter + proxy and see if it helps.
Also check out this community [plugin](https://pub.dev/packages/http_proxy) and see if it helps.
