### ISSUE TITLE
TextEditingController Textspan's recognizer raising error on initializing text

### ISSUE THREAD

**Issue by devaliakbar** [flutter/flutter#97433]
Here I extend TextEditingController to highlight(also clickable) the keyword "ali". It is working perfectly whenever the user types "ali". But when initializing text to the controller, it is showing a lot of errors. Someone pls help me with how I can resolve this error.

Note:  When I remove "recognizer" from "textspan" it is working perfectly without showing any error when I initialize the text. I guess this issue is happening because of "recognizer" in the textspan.

here is my code, pls uncomment line number 15 to see the error.

```
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:kyubook/utils/utility.dart';

class TexspanTap extends StatefulWidget {
  @override
  _TexspanTapState createState() => _TexspanTapState();
}

class _TexspanTapState extends State<TexspanTap> {
  final MyTextEditingcontroller _editingcontroller = MyTextEditingcontroller();

  @override
  void initState() {
    //_editingcontroller.text = "dghali";
    super.initState();
  }

  @override
  void dispose() {
    _editingcontroller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: SafeArea(
        child: Column(
          children: [
            TextField(
              controller: _editingcontroller,
            ),
          ],
        ),
      ),
    );
  }
}

class MyTextEditingcontroller extends TextEditingController {
  @override
  TextSpan buildTextSpan(
      {required BuildContext context,
      TextStyle? style,
      required bool withComposing}) {
    if (text.toLowerCase().contains("ali")) {
      final List<InlineSpan> spans = [];

      final int indexOfAli = text.indexOf("ali");

      spans.add(TextSpan(text: text.substring(0, indexOfAli)));

      spans.add(
        TextSpan(
            text: text.substring(indexOfAli, indexOfAli + 3),
            style: const TextStyle(color: Colors.red),
            recognizer: TapGestureRecognizer()
              ..onTapDown = (final details) {
                commonToast("Touched");
              }),
      );

      spans.add(TextSpan(text: text.substring(indexOfAli + 3, text.length)));

      return TextSpan(children: spans, style: style);
    }

    return TextSpan(text: text, style: style);
  }
}
```

https://user-images.githubusercontent.com/58595897/151553482-d8c685c1-2681-4872-a743-e00932d1e829.mov

**Comment by danagbemava-nc** [comment]
Hi @devaliakbar, thanks for reporting this. 

Please provide the output of `flutter doctor -v`.

Thank you

**Comment by devaliakbar** [comment]
Thanks for responding @danagbemava-nc 

here is the response of `flutter doctor -v` 

```
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-x64, locale en-IN)
    • Flutter version 2.2.2 at /Users/ali/Documents/tools/flutter
    • Framework revision d79295af24 (8 months ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc5)
    • Android SDK at /Users/ali/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0-rc5
    • ANDROID_HOME = /Users/ali/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (2 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 97.0.4692.99

• No issues found!
```

**Comment by danagbemava-nc** [comment]
Hi @devaliakbar, you appear to be on an older version of flutter. 

Kindly upgrade to the latest version of stable to see whether or not you still experience this issue. 

If you still experience this issue after the upgrade, please provide the updated `flutter doctor -v`. 

Thank you

PS: latest stable version is 2.8.1

**Comment by devaliakbar** [comment]
Hi @danagbemava-nc, I upgrade the flutter version and It is still it showing errors. here is the response of flutter doctor -v

`
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.4 20F71 darwin-x64, locale
    en-IN)
    • Flutter version 2.8.1 at /Users/ali/Documents/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (7 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version
    31.0.0-rc5)
    • Android SDK at /Users/ali/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0-rc5
    • ANDROID_HOME = /Users/ali/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.0.0.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 97.0.4692.99

! Doctor found issues in 1 category.
`

**Comment by danagbemava-nc** [comment]
The issue is reproducible using the sample provided by the author.

## Steps to reproduce
- Execute `flutter run` on the code sample 
- Type any word that contains "ali" or 
- Uncomment ` // _editingcontroller.text = "dghali";`
- Execute `flutter run` on the sample

<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6.2 20G314 darwin-arm, locale en-GB)
    • Flutter version 2.8.1 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (7 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:318:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1428:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1863:10)
      #15     runZonedGuarded (dart:async/zone.dart:1851:12)
      #16     runZoned (dart:async/zone.dart:1782:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:197:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:301:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:53:47)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1290:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (5 available)
    • M2007J20CG (mobile) • 5dd3be00                             • android-arm64  • Android 11 (API 30)
    • Nexus (mobile)      • 00008020-001875E83A38002E            • ios            • iOS 15.3 19D50
    • iPhone 13 (mobile)  • 7515F01A-C1B6-456E-8559-8D2383D3719D • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)     • macos                                • darwin-arm64   • macOS 11.6.2 20G314 darwin-arm
    • Chrome (web)        • chrome                               • web-javascript • Google Chrome 97.0.4692.99
    ! Error: Nexus is busy: Preparing Nexus for development. Xcode will continue when Nexus is finished. (code -10)

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel master, 2.10.0-1.0.pre.351, on macOS 11.6.2 20G314 darwin-arm, locale en-GB)
    • Flutter version 2.10.0-1.0.pre.351 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c9073beebc (2 hours ago), 2022-02-01 00:15:14 -0500
    • Engine revision 740d1420c8
    • Dart version 2.17.0 (build 2.17.0-69.0.dev)
    • DevTools version 2.10.0-dev.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 213.5744.122

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (5 available)
    • M2007J20CG (mobile) • 5dd3be00                             • android-arm64  • Android 11 (API 30)
    • Nexus (mobile)      • 00008020-001875E83A38002E            • ios            • iOS 15.3 19D50
    • iPhone 13 (mobile)  • 7515F01A-C1B6-456E-8559-8D2383D3719D • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)     • macos                                • darwin-arm64   • macOS 11.6.2 20G314 darwin-arm
    • Chrome (web)        • chrome                               • web-javascript • Google Chrome 97.0.4692.99
    ! Error: Nexus is busy: Preparing Nexus for development. Xcode will continue when Nexus is finished. (code -10)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

<details>
<summary>flutter run -v</summary>

[log.txt](https://github.com/flutter/flutter/files/7977062/log.txt)

</details>

**Comment by kaboc** [comment]
> 'readOnly && !obscureText': is not true.

I see the same assertion error with my own code. It occurs on iOS simulator but not on a real iOS device nor on Android, Windows and macOS.

**Comment by oliverbytes** [comment]
I'm surprised this is not yet fixed. I just got the error, only when using the iOS Simulator

**Comment by MuhammedKpln** [comment]
Getting same error as well

**Comment by hamishjohnson** [comment]
I get the error on any device, simulator or no

**Comment by hamishjohnson** [comment]
Here is a reproduction of the bug, partial thanks to @shAdow-XJY  (https://github.com/flutter/flutter/issues/127091)

Just uncomment the line with the bug in initState to see the issue.

Workaround: There's also a line in initState to uncomment showing a workaround.

```
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'text_field',
      theme: ThemeData(brightness: Brightness.dark),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final controller = ClickController();

  @override
  void initState() {
    super.initState();

    // uncomment for bug
    // controller.text = 'Ai';

    // uncomment for workaround fix
    // Future.microtask(() => controller.text = 'Ai');
  }

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () => FocusScope.of(context).unfocus(),
      child: Scaffold(
        appBar: AppBar(
          title: const Text('click_text_field'),
        ),
        body: Padding(
          padding: const EdgeInsets.all(8.0),
          child: SingleChildScrollView(
            child: Column(
              children: [
                TextField(
                  maxLines: null,
                  controller: controller,
                )
              ],
            ),
          ),
        ),
      ),
    );
  }
}

class ClickController extends TextEditingController {
  ClickController();

  @override
  TextSpan buildTextSpan(
      {required BuildContext context,
      TextStyle? style,
      required bool withComposing}) {
    var spans = <InlineSpan>[];

    int startIndex = 0;

    for (var i = 0; i < text.length; ++i) {
      if (text[i] == 'A') {
        spans.add(
          TextSpan(
            text: text.substring(startIndex, i),
            mouseCursor: SystemMouseCursors.click,
            recognizer: TapGestureRecognizer()
              ..onTap = () => debugPrint('click A'),
          ),
        );
        spans.add(
          TextSpan(
            text: 'A',
            mouseCursor: SystemMouseCursors.click,
            recognizer: TapGestureRecognizer()
              ..onTap = () => debugPrint('click A'),
          ),
        );
        startIndex = i + 1;
      }
    }
    if (startIndex < text.length) {
      spans.add(
        TextSpan(
          text: text.substring(startIndex, text.length),
          mouseCursor: SystemMouseCursors.text,
        ),
      );
    }

    return TextSpan(
      children: spans,
      mouseCursor: SystemMouseCursors.text,
    );
  }
}

```

**Comment by MaTeS72** [comment]
Still getting this error when initializing the controller with spans with gestures. Any ideas?

**Comment by Vedsaga** [comment]
Can confirm happens on real device on android.

Version, `Flutter 3.27.0-0.1.pre • channel beta`

**Comment by ProfessorX737** [comment]
This is happening for me too. ios issue on real device where if text span has tap guesture and is clicked on it throws exception
