### ISSUE TITLE
Exception caught by widgets library

### ISSUE THREAD

**Issue by ainide2990** [flutter/flutter#97434]
<details>
<summary>logs</summary>

```
======== Exception caught by widgets library =======================================================
The following assertion was thrown building InputChip:
'package:flutter/src/material/chip.dart': Failed assertion: line 1604 pos 12: 'widget.onSelected == null || widget.onPressed == null': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  InputChip InputChip:file:///Users/Shared/flutter_practice/lib/flutter01/Flutter26.dart:29:18
When the exception was thrown, this was the stack: 
#2      _RawChipState.initState (package:flutter/src/material/chip.dart:1604:12)
#3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4728:57)
#4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4561:5)
...     Normal element mounting (34 frames)
#38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3631:14)
#39     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6261:36)
#40     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6272:32)
...     Normal element mounting (253 frames)
#293    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3631:14)
#294    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6261:36)
#295    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6272:32)
...     Normal element mounting (393 frames)
#688    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3631:14)
#689    Element.updateChild (package:flutter/src/widgets/framework.dart:3383:18)
#690    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1198:16)
#691    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1167:5)
#692    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1112:18)
#693    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2531:19)
#694    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1111:13)
#695    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:944:7)
#696    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:924:7)
(elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
====================================================================================================
D/ActivityThread(32512): Won't deliver top position change in state=5
D/mali_winsys(32512): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/mali_winsys(32512): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
I/HwViewRootImpl(32512): removeInvalidNode all the node in jank list is out of time
D/DecorView(32512): showOrHideHighlightView: hasFocus=true; winMode=1; isMrgNull=true
W/InputMethodManager(32512): startInputReason = 1

======== Exception caught by widgets library =======================================================
The following assertion was thrown building InputChip:
'package:flutter/src/material/chip.dart': Failed assertion: line 1604 pos 12: 'widget.onSelected == null || widget.onPressed == null': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  InputChip InputChip:file:///Users/Shared/flutter_practice/lib/flutter01/Flutter26.dart:29:18
When the exception was thrown, this was the stack: 
#2      _RawChipState.initState (package:flutter/src/material/chip.dart:1604:12)
#3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4728:57)
#4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4561:5)
#5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3631:14)
#6      Element.updateChild (package:flutter/src/widgets/framework.dart:3380:20)
#7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#8      Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#9      StatelessElement.update (package:flutter/src/widgets/framework.dart:4669:5)
#10     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#11     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#12     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#14     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#15     StatelessElement.update (package:flutter/src/widgets/framework.dart:4669:5)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#18     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#19     StatelessElement.update (package:flutter/src/widgets/framework.dart:4669:5)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#22     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#23     ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
#24     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#26     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#27     ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
#28     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#29     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5626:32)
#30     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6284:17)
#31     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#33     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#34     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#35     StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#38     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#39     ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
#40     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#42     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#43     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#44     StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#45     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#46     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#47     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#48     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#49     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#50     StatelessElement.update (package:flutter/src/widgets/framework.dart:4669:5)
#51     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#52     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#53     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#55     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#56     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#57     StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#58     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#60     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#61     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#62     StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#63     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#64     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#65     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#66     ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
#67     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#69     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#70     StatelessElement.update (package:flutter/src/widgets/framework.dart:4669:5)
#71     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#72     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#73     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#74     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#75     StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#76     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#77     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#78     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#79     ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
#80     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#82     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#83     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#84     StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#85     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#86     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#87     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#89     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#90     StatelessElement.update (package:flutter/src/widgets/framework.dart:4669:5)
#91     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#92     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#93     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#94     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#95     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#96     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#97     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#98     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#99     StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#100    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#101    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#102    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#103    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#104    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#105    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#106    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#107    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#108    StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#109    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#110    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#111    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#112    StatelessElement.update (package:flutter/src/widgets/framework.dart:4669:5)
#113    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#114    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#115    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#116    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#117    StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#118    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#119    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#120    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#121    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#122    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#123    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#124    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#125    ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
#126    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:111:11)
#127    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#128    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#129    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#130    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#131    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#132    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#133    StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#134    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#135    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#136    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#137    ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
#138    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#139    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#140    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#141    ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
#142    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#143    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#144    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#145    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#146    StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#147    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#148    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#149    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#150    StatelessElement.update (package:flutter/src/widgets/framework.dart:4669:5)
#151    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#152    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#153    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#154    StatelessElement.update (package:flutter/src/widgets/framework.dart:4669:5)
#155    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#156    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#157    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#158    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#159    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#160    ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
#161    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#162    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#163    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#164    ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
#165    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#166    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#167    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#168    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#169    StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#170    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#171    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#172    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#173    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#174    StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#175    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#176    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#177    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#178    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#179    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2578:33)
#180    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#181    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#182    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
#183    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#184    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:863:7)
(elided 6 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, and dart:async-patch)
====================================================================================================
```
</details>

**Comment by danagbemava-nc** [comment]
Hi @ainide2990, when filing an issue please provide all or the majority of the information requested in the template. 

Your error message alone is not enough to make the issue actionable. 

Closing as no relevant information has been provided. 

Thank you
