### ISSUE TITLE
The position being added has a smaller timestamp than its predecessor

### ISSUE THREAD

**Issue by shawnlauzon** [flutter/flutter#97477]
Platform: iOS.

I'm getting this error in the logs. It doesn't seem to be affecting the app much, but after this exception is dumped, none of the other exception stack traces are displayed, so it's difficult to track them down.

```
══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown while routing a pointer event:
The position being added (Offset(63.0, 322.6)) has a smaller timestamp (2:27:14.037711) than its
predecessor: _PointAtTime(Offset(63.0, 327.5) at 456511:43:54.692001).
```

## Steps to Reproduce

Scroll the screen and this happens. I have no idea why. My code is nowhere in the call stack.

**Expected results:** 

No exception

**Actual results:** 

```
══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown while routing a pointer event:
The position being added (Offset(63.0, 322.6)) has a smaller timestamp (2:27:14.037711) than its
predecessor: _PointAtTime(Offset(63.0, 327.5) at 456511:43:54.692001).

When the exception was thrown, this was the stack:
#0      IOSScrollViewFlingVelocityTracker.addPosition.<anonymous closure>
(package:flutter/src/gestures/velocity_tracker.dart:303:7)
#1      IOSScrollViewFlingVelocityTracker.addPosition (package:flutter/src/gestures/velocity_tracker.dart:307:6)
#2      DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:289:15)
#3      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:94:12)
#4      PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:139:9)
#5      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:539:8)
#6      PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:137:18)
#7      PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:123:7)
#8      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:439:19)
#9      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:419:22)
#10     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:322:11)
#11     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
#12     PointerEventResampler._samplePointerPosition (package:flutter/src/gestures/resampler.dart:273:15)
#13     PointerEventResampler.sample (package:flutter/src/gestures/resampler.dart:307:7)
#14     _Resampler.sample (package:flutter/src/gestures/binding.dart:136:17)
#15     GestureBinding._handleSampleTimeChanged (package:flutter/src/gestures/binding.dart:468:20)
#16     _Resampler._onSampleTimeChanged (package:flutter/src/gestures/binding.dart:192:29)
#17     _Resampler.sample.<anonymous closure>.<anonymous closure> (package:flutter/src/gestures/binding.dart:168:59)
(elided 10 frames from class _RawReceivePortImpl, class _Timer, and dart:async)

router: Instance of 'PointerRouter'
route: Closure: (PointerEvent) => void from Function 'handleEvent':.
event: _TransformedPointerMoveEvent#e1fbc(position: Offset(63.0, 398.6))
════════════════════════════════════════════════════════════════════════════════════════════════════
```

<details>
  <summary>Logs</summary>

```
```

```
[+17513 ms] [connection] nw_endpoint_handler_set_adaptive_read_handler [C7.1 216.58.196.10:443 ready channel-flow
(satisfied (Path is satisfied), viable, interface: utun2, ipv4, dns)] unregister notification for read_timeout failed
[   +8 ms] [connection] nw_endpoint_handler_set_adaptive_write_handler [C7.1 216.58.196.10:443 ready channel-flow
(satisfied (Path is satisfied), viable, interface: utun2, ipv4, dns)] unregister notification for write_timeout failed
[+17093 ms]
                     ══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
                     The following assertion was thrown while routing a pointer event:
                     The position being added (Offset(73.2, 309.3)) has a smaller timestamp (2:40:33.959969) than its
                     predecessor: _PointAtTime(Offset(73.5, 318.0) at 456511:57:14.665668).

                     When the exception was thrown, this was the stack:
                     #0      IOSScrollViewFlingVelocityTracker.addPosition.<anonymous closure>
                     (package:flutter/src/gestures/velocity_tracker.dart:303:7)
                     #1      IOSScrollViewFlingVelocityTracker.addPosition
(package:flutter/src/gestures/velocity_tracker.dart:307:6)
                     #2      DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:289:15)
                     #3      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:94:12)
                     #4      PointerRouter._dispatchEventToRoutes.<anonymous closure>
(package:flutter/src/gestures/pointer_router.dart:139:9)
                     #5      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:539:8)
                     #6      PointerRouter._dispatchEventToRoutes
(package:flutter/src/gestures/pointer_router.dart:137:18)
                     #7      PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:123:7)
                     #8      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:439:19)
                     #9      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:419:22)
                     #10     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:322:11)
                     #11     GestureBinding._handlePointerEventImmediately
(package:flutter/src/gestures/binding.dart:374:7)
                     #12     PointerEventResampler._samplePointerPosition
(package:flutter/src/gestures/resampler.dart:273:15)
                     #13     PointerEventResampler.sample (package:flutter/src/gestures/resampler.dart:307:7)
                     #14     _Resampler.sample (package:flutter/src/gestures/binding.dart:136:17)
                     #15     GestureBinding._handleSampleTimeChanged (package:flutter/src/gestures/binding.dart:468:20)
                     #16     _Resampler._onSampleTimeChanged (package:flutter/src/gestures/binding.dart:192:29)
                     #17     _Resampler.sample.<anonymous closure>.<anonymous closure>
(package:flutter/src/gestures/binding.dart:168:59)
                     (elided 10 frames from class _RawReceivePortImpl, class _Timer, and dart:async)

                     router: Instance of 'PointerRouter'
                     route: Closure: (PointerEvent) => void from Function 'handleEvent':.
                     event: _TransformedPointerMoveEvent#ba351(position: Offset(73.2, 385.3))
                     ════════════════════════════════════════════════════════════════════════════════════════════════════
[  +11 ms]
           Another exception was thrown: The position being added (Offset(71.5, 269.5)) has a smaller timestamp
(2:40:34.009970)
           than its predecessor: _PointAtTime(Offset(73.5, 318.0) at 456511:57:14.665668).
[        ]
           Another exception was thrown: The position being added (Offset(70.5, 252.5)) has a smaller timestamp
(2:40:34.009970)
           than its predecessor: _PointAtTime(Offset(73.5, 318.0) at 456511:57:14.665668).
[  +87 ms]
           Another exception was thrown: The position being added (Offset(70.5, 240.5)) has a smaller timestamp
(2:40:34.093305)
           than its predecessor: _PointAtTime(Offset(73.5, 318.0) at 456511:57:14.665668).
[        ]
           Another exception was thrown: The position being added (Offset(70.5, 231.5)) has a smaller timestamp
(2:40:34.093305)
           than its predecessor: _PointAtTime(Offset(73.5, 318.0) at 456511:57:14.665668).
[        ]
           Another exception was thrown: The position being added (Offset(70.5, 226.5)) has a smaller timestamp
(2:40:34.109972)
           than its predecessor: _PointAtTime(Offset(73.5, 318.0) at 456511:57:14.665668).
[        ]
           Another exception was thrown: The position being added (Offset(70.5, 222.5)) has a smaller timestamp
(2:40:34.109972)
           than its predecessor: _PointAtTime(Offset(73.5, 318.0) at 456511:57:14.665668).
[   +1 ms]
           Another exception was thrown: The position being added (Offset(70.5, 221.0)) has a smaller timestamp
(2:40:34.109972)
           than its predecessor: _PointAtTime(Offset(73.5, 318.0) at 456511:57:14.665668).
[ +876 ms]
                    Another exception was thrown: The position being added (Offset(71.0, 222.0)) has a smaller timestamp
(2:40:34.976656)
                    than its predecessor: _PointAtTime(Offset(73.5, 318.0) at 456511:57:14.665668).
```

```
```

</details>

**Comment by darshankawar** [comment]
@shawnlauzon 
Can you provide a sample code that has scrolling on it, specially if you are using `NestedScrollView` or `CustomScrollView` ?
Does this error occur when you start scrolling ? Can you provide us any pattern that leads to this error  along with `flutter doctor -v` ?
