### ISSUE TITLE
[tool_crash] OSError: OS Error: Can't assign requested address, errno = 49

### ISSUE THREAD

**Issue by jonason123** [flutter/flutter#97489]
## Command
```
flutter attach fail
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
OSError: OS Error: Can't assign requested address, errno = 49
```
#0      _NativeSocket.nativeSetRawOption (dart:io-patch/socket_patch.dart:1558:35)
#1      _NativeSocket.setRawOption (dart:io-patch/socket_patch.dart:1480:5)
#2      _RawDatagramSocket.setRawOption (dart:io-patch/socket_patch.dart:2373:56)
#3      MDnsClient.start (package:multicast_dns/multicast_dns.dart:138:16)
<asynchronous suspension>
#4      MDnsObservatoryDiscovery.query (package:flutter_tools/src/mdns_discovery.dart:66:7)
<asynchronous suspension>
#5      MDnsObservatoryDiscovery.getObservatoryUri (package:flutter_tools/src/mdns_discovery.dart:153:51)
<asynchronous suspension>
#6      AttachCommand._attachToDevice (package:flutter_tools/src/commands/attach.dart:278:11)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#8      AttachCommand.runCommand (package:flutter_tools/src/commands/attach.dart:214:5)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.2.0, on macOS 12.0.1 21A559 darwin-arm, locale zh-Hans-CN)
    • Flutter version 2.2.0 at /Users/zhangjiayuan/working/flutter
    • Framework revision b22742018b (9 months ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/zhangjiayuan/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_321-b07)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.2.1, Build version 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2021.2.3)
    • IntelliJ at /Applications/IntelliJ ID

**Comment by danagbemava-nc** [comment]
Hi @jonason123, you appear to be on an older version of flutter, kindly upgrade to the latest version of flutter to see if you still experience this issue. 

If you do, please provide the updated `flutter doctor -v`. 

Thank you

**Comment by jonason123** [comment]
> 

As my company ask  to use 2.2.0, and I have upgrade to 2.8.0stable, but it still happen, so I have revert to 2.2.0。Not all of use have this issue, only three, others still work well，all of us used the same flutter branch.

**Comment by jonason123** [comment]
I can flutter attach android device, but can not attach ios simulater

**Comment by danagbemava-nc** [comment]
Hi @jonason123, the latest version of `stable` is `2.10.0`. Can you check on the version to see if this is still an issue? If it is, please provide the updated `flutter doctor -v`. 

> Not all of us have this issue, only three of us, it works well for others.

That is generally the nature of tool crashes since all environments are different.

**Comment by jonason123** [comment]
> Hi @jonason123, the latest version of `stable` is `2.10.0`. Can you check on the version to see if this is still an issue? If it is, please provide the updated `flutter doctor -v`.
> 
> > Not all of us have this issue, only three of us, it works well for others.
> 
> That is generally the nature of tool crashes since all environments are different.

I have upgraded to 2.10.0, but the issue still happen.

zhangjiayuan@LPT004151 ctrip_flutter % flutter doctor -v
[✓] Flutter (Channel stable, 2.10.0, on macOS 12.0.1 21A559 darwin-arm, locale zh-Hans-CN)
    • Flutter version 2.10.0 at /Users/zhangjiayuan/working/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f105a6ca7 (6 days ago), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/zhangjiayuan/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2021.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5632

[✓] VS Code (version 1.65.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (2 available)
    • iPhone 11 (mobile) • 4D294293-7B79-46CD-B58C-44C1C2D19F45 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by danagbemava-nc** [comment]
Labeling for further investigation

**Comment by jonason123** [comment]
> Hi @jonason123, can you please provide the logs of `flutter attach -v` that fails?
> 
> The output is likely to be huge, so kindly put it into a .txt file and attach it here.
> 
> Thank you

[flutter_attach_v.log](https://github.com/flutter/flutter/files/8021873/flutter_attach_v.log)

I have attached the log

**Comment by danagbemava-nc** [comment]
Labelling for further investigation.

**Comment by jonason123** [comment]
> Labelling for further investigation.

Any update？ I have reinstall xcode and simulater, but the issue still happen

**Comment by jonason123** [comment]
> Labelling for further investigation.

Any update?

**Comment by laity1991** [comment]
I had the same problem ， asked for help

**Comment by jonason123** [comment]
> I had the same problem ， asked for help

I  have fixed the problem, I installed some software, it used socket port, after I uninstall it, the attach work

**Comment by laity1991** [comment]
> > I had the same problem ， asked for help
> 
> I have fixed the problem, I installed some software, it used socket port, after I uninstall it, the attach work
what software have you uninstalled? Please advise

**Comment by jonason123** [comment]
> > > I had the same problem ， asked for help
> > 
> > 
> > I have fixed the problem, I installed some software, it used socket port, after I uninstall it, the attach work
> > what software have you uninstalled? Please advise

company VPN software

**Comment by agan23** [comment]
mac: 12.3 (21E230)
flutter: 2.8.1
Oops; flutter has exited unexpectedly: "OS Error: Can't assign requested address, errno = 49".
and flutter doctor is ok? and i can't find the method to solve this problem

**Comment by agan23** [comment]
My xcode is 13.2.1 
Mac: 12.3
------
before this, my Mac is 11.4 every thing is ok, after update the mac system , it runs error.
So U know this problem or U had resoled this problem , you can help me. Tks a lot

**Comment by tianguanghui** [comment]
I had the same problem， asked for help

Only when I attach to a iOS Simulator or Device, I'll get the error "OS Error: Can't assign requested address, errno = 49".

Strangely enough, it was fine yesterday

**Comment by coderYQC** [comment]
> I had the same problem， asked for help
> 
> Only when I attach to a iOS Simulator or Device, I'll get the error "OS Error: Can't assign requested address, errno = 49".
> 
> Strangely enough, it was fine yesterday

I also encounter the same problem. Have you solved  it?  I‘ve tried all means, but no result.

**Comment by ioschangnan-github** [comment]
> > > > 我也遇到了同样的问题，求助
> > > 
> > > 
> > > 我已经解决了这个问题，我安装了一些软件，它使用socket端口，我卸载它后，附加工作
> > > 你卸载了什么软件？请指教
> 
> 公司VPN软件

我也是这个原因，完美解决

**Comment by trhyl** [comment]
> 

Have you already solved it, I have same issue.

**Comment by trhyl** [comment]
> 

https://www.sangfor.com.cn/product-and-solution/sangfor-security/atrust
公司网络连接时默认安装了深信服的VPN软件——aTrustAgent，它在程序列表中隐藏起来，启动之后就自动开启。可以通过如下方式查找：`lsof -iTCP -sTCP:LISTEN`
结果：
`COMMAND    PID   USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
aTrustAge  641 honglv   18u  IPv4 0x7ecf5c7467460e77      0t0  TCP localhost:56630 (LISTEN)
aTrustAge  653 honglv   13u  IPv4 0x7ecf5c7467467e77      0t0  TCP localhost:54631 (LISTEN)
aTrustAge  653 honglv   15u  IPv4 0x7ecf5c746745ed17      0t0  TCP localhost:54630 (LISTEN)
aTrustAge  653 honglv   61u  IPv4 0x7ecf5c7466741a57      0t0  TCP localhost:55630 (LISTEN)
aTrustAge  653 honglv   79u  IPv4 0x7ecf5c7467443577      0t0  TCP localhost:56641 (LISTEN)
studio    1298 honglv   25u  IPv6 0x7ecf5c6f9aedb5ef      0t0  TCP localhost:6942 (LISTEN)
studio    1298 honglv   27u  IPv6 0x7ecf5c6f9aed5def      0t0  TCP localhost:63342 (LISTEN)
adb       1325 honglv    8u  IPv4 0x7ecf5c7467454097      0t0  TCP localhost:5037 (LISTEN)`
发现aTrustAgent后，可以关掉之后就解决问题了。

**Comment by stuartmorgan** [comment]
It looks like the tool should probably catch this and log a warning explaining that other software may be preventing discovery of devices.

**Comment by z-jack** [comment]
If you have ever used the VPN from school or corporation (i.e. aTrust from SangFor), you may suffer from the error code `OS Error: Can't assign requested address, errno = 49` for debugging on the physical device. The following steps can be used to solve that:

1. Disable the startup services

   * Go to System Preference - General - Login Items
   * Disable the `SANGFOR Technologies Company Limited`, one `launchctl` and two more  `sh`(You could access and check them by click the `i` button. You can further check the contents of other scripts with `i` button to avoid missing any scripts from SangFor.)
2. Disable the `KeepAlive` and `RunAtLoad` aTrust services

   * Go to `/Library/LaunchDaemons/com.sangfor.aTrustTunnel.plist`, `/Library/LaunchAgents/com.sangfor.aTrustCore.plist` and `/Library/LaunchAgents/com.sangfor.aTrustDaemon.plist`, change the value of `KeepAlive` and `RunAtLoad` from `true` to `false`
3. Stop the running services and all daemon processes

   ```bash
   sudo launchctl stop /Library/LaunchDaemons/com.sangfor.aTrustTunnel.plist;
   sudo launchctl stop /Library/LaunchDaemons/com.sangfor.aTrustUninstallMonitor.plist;
   sudo launchctl stop /Library/LaunchAgents/com.sangfor.aTrustCore.plist;
   sudo launchctl stop /Library/LaunchAgents/com.sangfor.aTrustDaemon.plist;
   sudo killall -9 aTrustAgent;
   ```
4. Now it should work, try `flutter run` or `flutter attach`.

**Comment by ruiyangdev** [comment]
> > > > > 我也遇到了同样的问题，求助
> > > > 
> > > > 
> > > > 我已经解决了这个问题，我安装了一些软件，它使用socket端口，我卸载它后，附加工作
> > > > 你卸载了什么软件？请指教
> > 
> > 
> > 公司VPN软件
> 
> 我也是这个原因，完美解决
> 
> **Translation below**
> 
> > > > > Wǒ yě yù dàole tóngyàng de wèntí, qiúzhù > > > > > > > > > wǒ yǐjīng jiějuéle zhège wèntí, wǒ ānzhuāngle yīxiē ruǎnjiàn, tā shǐyòng socket duānkǒu, wǒ xièzài tā hòu, fùjiā gōngzuò > > > nǐ xièzàile shénme ruǎnjiàn? Qǐng zhǐjiào > > gōngsī VPN ruǎnjiàn wǒ yěshì zhège yuányīn, wánměi jiějué
> > > > > Show more
> > > > > 130 / 5,000
> > > > > Translation results
> > > > > I have the same problem, please help
> > > > 
> > > > 
> > > > I have solved the problem, I installed some software and it uses the socket port, after I uninstalled it, the attach works
> > > > What software did you uninstall? Please advise
> > 
> > 
> > Corporate VPN software
> 
> I have the same reason, perfect solution

我也是这个原因，卸载aTrustAgent之后完美解决。

**Comment by zzmps0901** [comment]
> > 
> 
> https://www.sangfor.com.cn/product-and-solution/sangfor-security/atrust 公司网络连接时默认安装了深信服的VPN软件——aTrustAgent，它在程序列表中隐藏起来，启动之后就自动开启。可以通过如下方式查找：`lsof -iTCP -sTCP:LISTEN` 结果：
> 
> > COMMAND    PID   USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
> > aTrustAge  641 honglv   18u  IPv4 0x7ecf5c7467460e77      0t0  TCP localhost:56630 (LISTEN)
> > aTrustAge  653 honglv   13u  IPv4 0x7ecf5c7467467e77      0t0  TCP localhost:54631 (LISTEN)
> > aTrustAge  653 honglv   15u  IPv4 0x7ecf5c746745ed17      0t0  TCP localhost:54630 (LISTEN)
> > aTrustAge  653 honglv   61u  IPv4 0x7ecf5c7466741a57      0t0  TCP localhost:55630 (LISTEN)
> > aTrustAge  653 honglv   79u  IPv4 0x7ecf5c7467443577      0t0  TCP localhost:56641 (LISTEN)
> > studio    1298 honglv   25u  IPv6 0x7ecf5c6f9aedb5ef      0t0  TCP localhost:6942 (LISTEN)
> > studio    1298 honglv   27u  IPv6 0x7ecf5c6f9aed5def      0t0  TCP localhost:63342 (LISTEN)
> > adb       1325 honglv    8u  IPv4 0x7ecf5c7467454097      0t0  TCP localhost:5037 (LISTEN)
> 
> 发现aTrustAgent后，可以关掉之后就解决问题了。

我确实是这个原因，远程以后装了vpn
