### ISSUE TITLE
[camera] CAMERA_ERROR (3): The camera device has encountered a serious error

### ISSUE THREAD

**Issue by Tom3652** [flutter/flutter#97497]
This is exactly the same issue as i have created last year and thought was fixed #81549. 
This is happening on my phone Motorola g 8 under Android 11 while keeping the app open until the phone is automatically locked for inactivity.  
In my case this happens after 15min more or less.  
I can't reproduce it using the ```AppLifeCycleState.inactive``` thought... 
   
I have seen many other issues similar while taking pictures on Android 12 especially, but here it's only after inactivity as you will see in the log. 

<details>
<summary>Code sample</summary>

```dart
import 'dart:ui';

import 'package:camera/camera.dart';
import 'package:flutter/material.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(CameraApp());
}

class CameraApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        resizeToAvoidBottomInset: false,
        body: NewCamera(),
      ),
    );
  }
}

class NewCamera extends StatefulWidget {

  const NewCamera({Key key}) : super(key: key);

  @override
  NewCameraState createState() => NewCameraState();
}

class NewCameraState extends State<NewCamera> with WidgetsBindingObserver {
  
  Future<void> _initializeControllerFuture;

  List cameras;
  CameraController cameraController;

  Future<List> getCameras() async {
    return cameras = await availableCameras();
  }

  @override
  void initState() {
    WidgetsBinding.instance.addObserver(this);
    // Obtain a list of the available cameras on the device.
    getCameras().then((value) => {
      initCamera(cameras.first)
    });
    super.initState();
  }

  @override
  void dispose() {
    // Dispose of the controller when the widget is disposed.
    WidgetsBinding.instance.removeObserver(this);
    cameraController.dispose();
    super.dispose();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.resumed) {
      initCamera(cameras.first);
    }
    super.didChangeAppLifecycleState(state);
  }

  Future initCamera(CameraDescription cameraDescription) async {
    if (cameraController != null) {
      await cameraController.dispose();
      cameraController = null;
    }

    cameraController = CameraController(cameraDescription, ResolutionPreset.high);

    cameraController.addListener(() {
      if (mounted) {
        setState(() {});
      }
    });

    if (cameraController.value.hasError) {
      print('Camera Error ${cameraController.value.errorDescription}');
    }

    try {
      _initializeControllerFuture = cameraController.initialize();
    } catch (e) {
      showCameraException(e);
    }

    if (mounted) {
      setState(() {});
    }
  }

  showCameraException(e) {
    String errorText = 'Error ${e.code} \nError message: ${e.legend}';
    print(errorText);
  }

  // ------------------------------ UI ------------------------------- //

  /// Main Container of all the UI.
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      resizeToAvoidBottomInset: false,
      body: FutureBuilder<void>(
        future: _initializeControllerFuture,
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.done) {
            // If the Future is complete, display the preview.
            return Container(
              child: Center(
                child: cameraPreview(),
              ),
            );
          } else {
            return Container();
          }
        },
      ),

    );
  }

  Widget cameraPreview() {
    final size = MediaQuery.of(context).size;
    final deviceRatio = size.height / size.width;
    if (!cameraController.value.isInitialized) {
      return Container();
    }
    return Scaffold(
      resizeToAvoidBottomInset: false,
      body: ClipRRect(
        child: Container(
          color: Colors.transparent,
          child: Transform.scale(
            scale: deviceRatio / cameraController.value.aspectRatio,
            child: Center(
              child: AspectRatio(
                aspectRatio: 1 / cameraController.value.aspectRatio,
                child: Transform(
                  alignment: Alignment.center,
                  child: CameraPreview(cameraController),
                  transform: Matrix4.rotationY(0),
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }

}
```

</details>

<details>
  <summary>Logs</summary>

```
V/FA      (31077): Inactivity, disconnecting from the service
I/Camera  (31077): open | onError
I/Camera  (31077): close
I/Camera  (31077): closeCaptureSession
E/CameraCaptureSession(31077): Session 4: Exception while stopping repeating: 
E/CameraCaptureSession(31077): android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): The camera device has encountered a serious error
E/CameraCaptureSession(31077): 	at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:2288)
E/CameraCaptureSession(31077): 	at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1250)
E/CameraCaptureSession(31077): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:579)
E/CameraCaptureSession(31077): 	at io.flutter.plugins.camera.Camera.closeCaptureSession(Camera.java:1114)
E/CameraCaptureSession(31077): 	at io.flutter.plugins.camera.Camera.close(Camera.java:1121)
E/CameraCaptureSession(31077): 	at io.flutter.plugins.camera.Camera$1.onError(Camera.java:302)
E/CameraCaptureSession(31077): 	at android.hardware.camera2.impl.CameraDeviceImpl.notifyError(CameraDeviceImpl.java:1686)
E/CameraCaptureSession(31077): 	at android.hardware.camera2.impl.CameraDeviceImpl.lambda$oDs27OTfKFfK18rUW2nQxxkPdV0(Unknown Source:0)
E/CameraCaptureSession(31077): 	at android.hardware.camera2.impl.-$$Lambda$CameraDeviceImpl$oDs27OTfKFfK18rUW2nQxxkPdV0.accept(Unknown Source:8)
E/CameraCaptureSession(31077): 	at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:278)
E/CameraCaptureSession(31077): 	at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:201)
E/CameraCaptureSession(31077): 	at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:97)
E/CameraCaptureSession(31077): 	at android.os.Handler.handleCallback(Handler.java:938)
E/CameraCaptureSession(31077): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/CameraCaptureSession(31077): 	at android.os.Looper.loop(Looper.java:250)
E/CameraCaptureSession(31077): 	at android.os.HandlerThread.run(HandlerThread.java:67)
```

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale fr-FR)
    • Flutter version 2.8.1 at /Users/foxtom/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (6 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/foxtom/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.63.2)
    • VS Code at /Users/foxtom/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (3 available)
    • moto g 8 power (mobile) • ZY22BNDW2C • android-arm64  • Android 11 (API 30)
    • macOS (desktop)         • macos      • darwin-x64     • macOS 12.1 21C52 darwin-x64
    • Chrome (web)            • chrome     • web-javascript • Google Chrome 97.0.4692.99

• No issues found!
```

</details>

**Comment by maheshmnj** [comment]
Hi @Tom3652 ,

There is a similar issue describing this case https://github.com/flutter/flutter/issues/92762, Please follow up there for further updates, Closing this issue as a duplicate. If you disagree feel free to write in the comments and I will reopen it.

Thank you.

**Comment by Tom3652** [comment]
Hi @maheshmnj, i have seen the issue you mentioned, however it seems to be OS specific and on emulator.  
In my case, this happens on 2 of my real Android devices after inactivity. 

My Android devices are : OPPO (Android 10) and Motorola g 8 (Android 11).  
So i am guessing that the issue is potentially on more phones... This is problematic as the user come back on the app and the camera is black completely and there is no way (as far as i know) to "detect" that the camera was destroyed.

**Comment by maheshmnj** [comment]
Thanks for the info @Tom3652, If you have any further info please add it to the linked issue so that it could help the contributors of the issue, comments here might get unnoticed
