### ISSUE TITLE
In macOS Monteray, the "flutter" command keeps creating "~" folder. 

### ISSUE THREAD

**Issue by indyant** [flutter/flutter#97507]
I'm using flutter in my mac quite some time, and one day I found a weird directory in a flutter project directory.

<img width="303" alt="2022-01-31_10-32-21" src="https://user-images.githubusercontent.com/59300194/151727426-dde99607-4459-4cdf-ae59-6bfaa225f770.png">

So I've tested various case to find out when it happens. 

Whenever I execute flutter command like ```flutter doctor``` , ```flutter run``` or other flutter command, "~" (tilde) directory is created in the current directory, and it contains ```.config``` directory in it.

<img width="812" alt="2022-01-31_00-00-06" src="https://user-images.githubusercontent.com/59300194/151705140-bfd27c67-2d28-4272-9269-9482099bd6b3.png">

And, when I tried to run ```flutter doctor``` in the root directory, the following exception occurs.

```
user@MacBook-Pro / % flutter doctor
Unhandled exception:
FileSystemException: Creation failed, path = '~' (OS Error: Read-only file system, errno = 30)
#0      _Directory.createSync (dart:io/directory_impl.dart:133:7)
#1      _Directory.createSync (dart:io/directory_impl.dart:128:16)
#2      ForwardingDirectory.createSync (package:file/src/forwarding/forwarding_directory.dart:20:16)
#3      ErrorHandlingDirectory.createSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:433:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:597:14)
#5      ErrorHandlingDirectory.createSync (package:flutter_tools/src/base/error_handling_io.dart:432:12)
#6      new Config._common (package:flutter_tools/src/base/config.dart:76:17)
#7      new Config (package:flutter_tools/src/base/config.dart:37:19)
#8      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:169:21)
#9      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#10     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:453:23)
#11     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#12     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#13     config (package:flutter_tools/src/globals_null_migrated.dart:56:30)
#14     getBuildDirectory (package:flutter_tools/src/build_info.dart:766:48)
#15     defaultDepfilePath (package:flutter_tools/src/bundle.dart:16:55)
#16     new BuildBundleCommand (package:flutter_tools/src/commands/build_bundle.dart:28:21)
#17     new BuildCommand (package:flutter_tools/src/commands/build.dart:36:20)
#18     generateCommands (package:flutter_tools/executable.dart:150:3)
#19     main.<anonymous closure> (package:flutter_tools/executable.dart:96:11)
#20     run.<anonymous closure> (package:flutter_tools/runner.dart:48:13)
<asynchronous suspension>
#21     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#22     main (package:flutter_tools/executable.dart:94:3)
<asynchronous suspension>
```

If anyone knows what causes this and how to resolve it, please let me know. It's really annoying and I'm wondering it may be a symptom of other bigger problems. 

Thanks in advance.

**Comment by indyant** [comment]
I found the cause of the problem. Some zsh environment variable caused it.
