### ISSUE TITLE
Pressing keyboard letters with the focus on TextEditingController doesn't write anything.

### ISSUE THREAD

**Issue by AvekIA** [flutter/flutter#97571]
```
======== Exception caught by rendering library =====================================================
The following assertion was thrown during layout:
A RenderFlex overflowed by 2.0 pixels on the right.

The overflowing RenderFlex has an orientation of Axis.horizontal.
The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and black striped pattern. This is usually caused by the contents being too big for the RenderFlex.

Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the RenderFlex to fit within the available space instead of being sized to their natural size.
This is considered an error condition because it indicates that there is content that cannot be seen. If the content is legitimately bigger than the available space, consider clipping it with a ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex, like a ListView.

The specific RenderFlex in question is: RenderFlex#b3bd9 OVERFLOWING
...  parentData: offset=Offset(0.0, 0.0) (can use size)
...  constraints: BoxConstraints(w=222.0, h=49.0)
...  size: Size(222.0, 49.0)
...  direction: horizontal
...  mainAxisAlignment: spaceBetween
...  mainAxisSize: min
...  crossAxisAlignment: center
...  textDirection: ltr
...  verticalDirection: down
◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤
====================================================================================================

** (AvekIA:11581): WARNING **: 10:32:29.344: Unable to retrieve framework response: Message is not valid JSON

======== Exception caught by services library ======================================================
The following assertion was thrown during a platform message callback:
A KeyUpEvent is dispatched, but the state shows that the physical key is pressed on a different logical key. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#32ff8(physicalKey: PhysicalKeyboardKey#7001f(usbHidUsage: "0x0007001f", debugName: "Digit 2"), logicalKey: LogicalKeyboardKey#00032(keyId: "0x00000032", keyLabel: "2", debugName: "Digit 2"), character: null, timeStamp: 0:46:10.421000) and the recorded logical key LogicalKeyboardKey#000e9(keyId: "0x000000e9", keyLabel: "É", debugName: "Key É")
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 444 pos 16: '_pressedKeys[event.physicalKey] == event.logicalKey'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:444:16)
#3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:452:6)
#4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:544:5)
#5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:821:35)
#6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:77:49)
#7      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:76:47)
#8      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:389:35)
#9      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:386:46)
#10     _invoke2.<anonymous closure> (dart:ui/hooks.dart:189:15)
#14     _invoke2 (dart:ui/hooks.dart:188:10)
#15     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#16     _Channel.push (dart:ui/channel_buffers.dart:132:31)
#17     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#18     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:544:22)
#19     _dispatchPlatformMessage (dart:ui/hooks.dart:83:31)
(elided 5 frames from class _AssertionError and dart:async)
====================================================================================================
```

**Comment by maheshmnj** [comment]
Hi @AvekIA, Thanks for filing the issue. Please share the output of `flutter doctor -v`, the device on which this issue occurs, and the exact steps to reproduce the issue since there have been several reports of this issue with unknown reproducible steps.
for Instance, this got closed recently https://github.com/flutter/flutter/issues/96277  due to insufficient info.

**Comment by lytrac** [comment]
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [VersiÃ³n 10.0.19044.1503], locale es-ES)
    • Flutter version 2.8.1 at C:\Users\david\Documents\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (7 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc4)
    • Android SDK at C:\Users\david\AppData\Local\Android\Sdk
    • Platform android-31, build-tools 31.0.0-rc4
    • ANDROID_SDK_ROOT = C:\Users\david\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 97.0.4692.99
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 97.0.1072.76

• No issues found!




Happens the same to me. In the friendly chat tutorial, at the end of lesson 7 (https://codelabs.developers.google.com/codelabs/flutter#6) if you write something and press enter typing stops working. You have to click on the text field again. Only happens in web browser, android works fine.

**Comment by lytrac** [comment]
Workaround setting focus to other node with timeouts

Future.delayed(Duration.zero, () => _focusNodeButton.requestFocus());
Future.delayed(Duration.zero, () => _focusNode.requestFocus());

**Comment by maheshmnj** [comment]
@lytrac please share the requested info for this issue to be actionable further.

> the device on which this issue occurs, and the exact steps to reproduce the issue 

Thanks
