### ISSUE TITLE
Flutter Web on Windows; Using Windows Clipboard History Freezes Application With Pasting Text into TextFormField

### ISSUE THREAD

**Issue by longtimedeveloper** [flutter/flutter#97582]
## Steps to Reproduce

1. On a computer running **Windows**, Open Windows Settings
2. Search for Clipboard
3. Enable Clipboard History as seen in this image.

![image](https://user-images.githubusercontent.com/79998776/151980347-c1d29316-3f92-4b73-8860-558a3bb996de.png)

4. Create a new Flutter application.
5. Replace main.dart code with the below Code.
6. Selected Chrome as the device
7. Copy some text into your clipboard
8. Run in the application using Debug mode (Start Debugging in VS Code)
9. Using the mouse, click the TextFormField
10. Press Windows Logo Key + Alt.
11. Click the text you copied into the clipboard
12. **App will freeze.**

If you repeat the above steps and run the application without debugging, assert messages will appear in the terminal Debug Console.

**NOTE:** Windows Clipboard History feature works normally when running on Windows and Andriod. 

**Expected results:** 
Text is pasted into the TextFormField

**Actual results:** 
Chrome application freezes.  You'll be unable to edit any text.  Nothing appears in the terminal Debug Console.  There have been times when I had to restart VS Code after this happens because the keyboard can't be used to edit code.

<details>
<summary>Code</summary>

```dart

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Chrome Issue With Windows Clipboard History',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const MyHomePage(title: 'Chrome Issue With Windows Clipboard History'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            TextFormField(),
          ],
        ),
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
This Chrome log is only rendered when running in NON-DEBUG mode.  In DEBUG mode, applicaiton freezes, no log it outputted.

Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/keyboard_binding.dart:352:16
result != null
"Invalid modifier location: Control, 0"
    at Object.throw_ [as throw] (http://localhost:64409/dart_sdk.js:5063:11)
    at Object.assertFailed (http://localhost:64409/dart_sdk.js:4988:15)
    at http://localhost:64409/dart_sdk.js:170042:39
    at _engine.KeyboardConverter.new.[_handleEvent] (http://localhost:64409/dart_sdk.js:170048:25)
    at _engine.KeyboardConverter.new.handleEvent (http://localhost:64409/dart_sdk.js:170134:27)
    at http://localhost:64409/dart_sdk.js:169775:76
    at loggedHandler (http://localhost:64409/dart_sdk.js:169752:18)
Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/keyboard_binding.dart:352:16
result != null
"Invalid modifier location: Control, 0"
    at Object.throw_ [as throw] (http://localhost:64409/dart_sdk.js:5063:11)
    at Object.assertFailed (http://localhost:64409/dart_sdk.js:4988:15)
    at http://localhost:64409/dart_sdk.js:170042:39
    at _engine.KeyboardConverter.new.[_handleEvent] (http://localhost:64409/dart_sdk.js:170048:25)
    at _engine.KeyboardConverter.new.handleEvent (http://localhost:64409/dart_sdk.js:170134:27)
    at http://localhost:64409/dart_sdk.js:169776:74
    at loggedHandler (http://localhost:64409/dart_sdk.js:169752:18)

```

```
>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19043.1466], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.9)
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.63.2)
[√] Connected device (3 available)

• No issues found!
```

</details>

**Comment by HansMuller** [comment]
@cbracken - can you reproduce this?

**Comment by longtimedeveloper** [comment]
@HansMuller Just checking.  Not sure why you added, the tag, "a:desktop" this only happens when running on a **WEB** project on Windows Desktop.  Best regards, Karl

**Comment by HansMuller** [comment]
@longtimedeveloper - good point; I'll change the label

**Comment by moko256** [comment]
I reproduced this issue and working on it. This is mixed some problems.
- The VSCode stops due to the breakpoint from assertion, but the source file that the assertion failed is not opened. It can continue from debug actions, but it looks like freezed.
- The Clipboard History emulates Ctrl+V, but different from typed from keyboard by hand, the `KeyboardEvent.code` is empty, and `KeyboardEvent.location` is 0 (=no location).
  - The Shift, Control, Alt, Meta keys with no location is not mapped any keys, in [dev/tools/gen_keycodes/data/web_logical_location_mapping.json](https://github.com/flutter/flutter/blob/19a380ffe79f4fa2bc23edf47a39151332f91c6b/dev/tools/gen_keycodes/data/web_logical_location_mapping.json#L29-L32), and the assert will fail. This is on that log.
  - The `KeyboardEvent.code` is used as key of `_pressingRecords` in `engine lib/web_ui/lib/src/engine/keyboard_binding.dart`, and `_pressedKeys` in `packages/flutter/lib/src/services/hardware_keyboard.dart` to store pressed keys, but the `KeyboardEvent.code` of both emulated Ctrl and V are empty and the two will same key on `_pressedKey`. So, [the assert on hardware_keyboard.dart](https://github.com/flutter/flutter/blob/4d9e6d9b3ea2c6d4b9c87a8ae3231961676a4b62/packages/flutter/lib/src/services/hardware_keyboard.dart#L444) will fail.

**Comment by moko256** [comment]
On comment above, I tried on Chrome/98.0.4758.82.
I tried paste from Win+V on Firefox/97.0, both `KeyboardEvent.code` is `ControlLeft` and `KeyboardEvent.location` is `LEFT`, like typeed by hand. It might Chromium problem.

Keyboard Event Viewer: https://w3c.github.io/uievents/tools/key-event-viewer.html

**Comment by moko256** [comment]
cc @dkwingsmt

**Comment by iRevolutionDev** [comment]
Same problem on windows desktop application
