### ISSUE TITLE
[tool_crash] FileSystemException: Creation of temporary directory failed, OS Error: No such file or directory, errno = 2

### ISSUE THREAD

**Issue by brkrtp** [flutter/flutter#97600]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Creation of temporary directory failed, OS Error: No such file or directory, errno = 2
```
#0      _Directory.createTempSync (dart:io/directory_impl.dart:181:7)
#1      ForwardingDirectory.createTempSync (package:file/src/forwarding/forwarding_directory.dart:28:21)
#2      LocalFileSystem.systemTempDirectory (package:flutter_tools/src/base/file_system.dart:221:47)
#3      ForwardingFileSystem.systemTempDirectory (package:file/src/forwarding/forwarding_file_system.dart:33:49)
#4      new ResidentRunner (package:flutter_tools/src/resident_runner.dart:1017:24)
#5      new HotRunner (package:flutter_tools/src/run_hot.dart:104:8)
#6      RunCommand.createRunner (package:flutter_tools/src/commands/run.dart:503:14)
<asynchronous suspension>
#7      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:645:35)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
```
```
[✓] Flutter (Channel master, 2.10.0-1.0.pre.111, on macOS 12.2 21D49 darwin-arm, locale en-TR)
    • Flutter version 2.10.0-1.0.pre.111 at /usr/local/Caskroom/flutter/2.2.3/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 151daec35b (3 weeks ago), 2022-01-11 11:55:14 -0500
    • Engine revision a79a3bac0c
    • Dart version 2.16.0 (build 2.16.0-154.0.dev)
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc4)
    • Android SDK at /Users/burak/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0-rc4
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (2 available)
    • iPhone 13 Pro Max (mobile) • 78EA6EAE-1C10-4AE9-A32E-BE60A814AE36 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2
      (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 97.0.4692.99

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+40
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 02c026b03cd31dd3f867e5faeb7e104cce174c5f
### Plugins
firebase_core-1.11.0
firebase_core_web-1.5.3
firebase_messaging-10.0.9
firebase_messaging_web-2.2.6
flutter_inappwebview-5.3.2
url_launcher-5.4.0
url_launcher_macos-0.0.1+9
url_launcher_web-0.1.3
webview_flutter-2.0.13

**Comment by danagbemava-nc** [comment]
Hi @brkrtp, thanks for filing the issue.

There's a similar issue open #74042.

Kindly follow up there for more information, and if you can provide any more information over there, that will be appreciated.

Closing from here as duplicate.

Thank you
