### ISSUE TITLE
java.lang.NullPointerException io.flutter.plugins.imagepicker.ImagePickerCache.saveDimensionWithMethodCall

### ISSUE THREAD

**Issue by skquo** [flutter/flutter#97649]
Device: TECNO-LD7
Android 10 (SDK 29)
SoC: Mediatek MT6769
<details>
  <summary>Logs</summary>

```
java.lang.RuntimeException: 
  at android.app.ActivityThread.callActivityOnStop (ActivityThread.java:4838)
  at android.app.ActivityThread.performStopActivityInner (ActivityThread.java:4808)
  at android.app.ActivityThread.handleStopActivity (ActivityThread.java:4883)
  at android.app.servertransaction.StopActivityItem.execute (StopActivityItem.java:41)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:181)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:98)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2126)
  at android.os.Handler.dispatchMessage (Handler.java:107)
  at android.os.Looper.loop (Looper.java:264)
  at android.app.ActivityThread.main (ActivityThread.java:7684)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:507)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:980)
Caused by: java.lang.NullPointerException: 
  at io.flutter.plugins.imagepicker.ImagePickerCache.saveDimensionWithMethodCall (Unknown Source:2)
  at io.flutter.plugins.imagepicker.ImagePickerDelegate.saveStateBeforeResult (Unknown Source:16)
  at io.flutter.plugins.imagepicker.ImagePickerPlugin$LifeCycleObserver.onActivityStopped (Unknown Source:10)
  at io.flutter.plugins.imagepicker.ImagePickerPlugin$LifeCycleObserver.onStop (Unknown Source:2)
  at androidx.lifecycle.FullLifecycleObserverAdapter.onStateChanged (FullLifecycleObserverAdapter.java:28)
  at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent (LifecycleRegistry.java:14)
  at androidx.lifecycle.LifecycleRegistry.backwardPass (LifecycleRegistry.java:67)
  at androidx.lifecycle.LifecycleRegistry.sync (LifecycleRegistry.java:41)
  at androidx.lifecycle.LifecycleRegistry.moveToState (LifecycleRegistry.java:19)
  at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent (LifecycleRegistry.java:4)
  at io.flutter.embedding.android.FlutterActivity.onStop (Unknown Source:20)
  at android.app.Instrumentation.callActivityOnStop (Instrumentation.java:1473)
  at android.app.Activity.performStop (Activity.java:8033)
  at android.app.ActivityThread.callActivityOnStop (ActivityThread.java:4830)
  at android.app.ActivityThread.performStopActivityInner (ActivityThread.java:4808)
  at android.app.ActivityThread.handleStopActivity (ActivityThread.java:4883)
  at android.app.servertransaction.StopActivityItem.execute (StopActivityItem.java:41)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:181)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:98)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2126)
  at android.os.Handler.dispatchMessage (Handler.java:107)
  at android.os.Looper.loop (Looper.java:264)
  at android.app.ActivityThread.main (ActivityThread.java:7684)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:507)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:980)
```

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6 20G165 darwin-x64, locale en-VN)
    • Flutter version 2.8.1 at /Users/skqu/Workspace/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (7 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/skqu/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[!] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.0.0.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[!] Connected device
    ! No devices available

! Doctor found issues in 4 categories.
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @skquo, thanks for filing the issue. 

Please provide the output of `flutter doctor -v` as well as the version of `image_picker` you experienced this issue with. 

Also, does this issue occur locally or in production?

If locally, please provide a complete minimal reproducible code sample as well as the output of `flutter run -v` that shows the error, along with steps to reproduce. 

If this occurs in production, kindly provide a list of devices that are affected by this as well as any other relevant crash logs. 

Thank you

**Comment by rkohari** [comment]
am also getting the same error
   StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607)
E/flutter (21518): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167)
E/flutter (21518): <asynchronous suspension>
E/flutter (21518): #2      MethodChannelImagePicker.getImage (package:image_picker_platform_interface/src/method_channel/method_channel_image_picker.dart:187)
E/flutter (21518): <asynchronous suspension>
E/flutter (21518): #3      ImagePickerViewModel.pickImageFromCamera (package:curiumlife/ui/view/image_picker/image_picker_view_model.dart:62)
E/flutter (21518): <asynchronous suspension>
E/flutter (21518):
