### ISSUE TITLE
`Switch`,`Radio`, `Checkbox` don't inherit local theme properties

### ISSUE THREAD

**Issue by SuperPenguin** [flutter/flutter#97691]
## Steps to Reproduce

Current Switch right now doesn't use theme from nearest ancestor SwitchTheme widget, instead it use the theme from ThemeData.switchTheme anyway.

1. Run code below
2. See the switch thumb color

**Expected results:** 2nd switch thumb color should be green

**Actual results:** 2nd switch thumb color still red

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  runApp(const App());
}

class App extends StatelessWidget {
  const App({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Switch demo',
      theme: ThemeData(
        brightness: Brightness.light,
        switchTheme: SwitchThemeData(
          thumbColor: MaterialStateProperty.all(Colors.red),
        ),
      ),
      initialRoute: '/',
      routes: {
        '/': (context) => const HomePage(),
      },
    );
  }
}

class HomePage extends StatefulWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  bool _switch1 = false;
  bool _switch2 = false;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Switch demo'),
      ),
      body: Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Switch(
              value: _switch1,
              onChanged: (value) {
                setState(() {
                  _switch1 = value;
                });
              },
            ),
            SwitchTheme(
              data: SwitchTheme.of(context).copyWith(
                thumbColor: MaterialStateProperty.all(Colors.green),
              ),
              child: Switch(
                value: _switch2,
                onChanged: (value) {
                  setState(() {
                    _switch2 = value;
                  });
                },
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
[√] Flutter (Channel master, 2.10.0-1.0.pre.402, on Microsoft Windows [Version 10.0.22000.434], locale en-001)
    • Flutter version 2.10.0-1.0.pre.402 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ac52901c14 (58 minutes ago), 2022-02-02 19:28:25 -0800
    • Engine revision baadc162a9
    • Dart version 2.17.0 (build 2.17.0-79.0.dev)
    • DevTools version 2.10.0

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\andre\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.9)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.32106.194
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.63.2)
    • VS Code at C:\Users\andre\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.34.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.434]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 97.0.4692.71
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 97.0.1072.76

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

![image](https://user-images.githubusercontent.com/1574722/152281397-9fce1790-1391-4581-9468-64cb9ec4ad11.png)

**Comment by danagbemava-nc** [comment]
Issue is reproducible on `stable` and `master`. 

I also noticed the same behavior for `RadioTheme` and `CheckboxTheme`.
I wonder if this is related to them extending `InheritedWidget` instead of `InheritedTheme`. 

`ListTileTheme` does work as expected and it extends `InheritedTheme`. 

<details>
<summary>screenshots</summary>

| web | ios | android | macOS | 
| -- | -- | -- | -- | 
| <img width="612" alt="Screenshot 2022-02-03 at 08 55 54" src="https://user-images.githubusercontent.com/88313112/152311045-25b2c9d3-ed9d-404a-82bf-f26ed4acddcc.png"> | ![Simulator Screen Shot - iPhone 13 - 2022-02-03 at 08 54 34](https://user-images.githubusercontent.com/88313112/152311055-16050b40-d51a-4633-803a-3255c82b5ad3.png) |  ![Screenshot_1643878363](https://user-images.githubusercontent.com/88313112/152311059-8bb0c7c0-52fb-4d54-8cbf-13fb01271b45.png) | <img width="621" alt="Screenshot 2022-02-03 at 08 48 34" src="https://user-images.githubusercontent.com/88313112/152311060-f5fd4906-373b-4eac-86bf-ee1c75a0b6a0.png"> | 

</details>

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  runApp(const App());
}

class App extends StatelessWidget {
  const App({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Switch demo',
      theme: ThemeData(
        brightness: Brightness.light,
        switchTheme: SwitchThemeData(
          thumbColor: MaterialStateProperty.all(Colors.red),
        ),
        listTileTheme: const ListTileThemeData(tileColor: Colors.blue),
        radioTheme: RadioThemeData(
          fillColor: MaterialStateProperty.all(Colors.green),
        ),
        checkboxTheme: CheckboxThemeData(
          checkColor: MaterialStateProperty.all(Colors.yellow),
          fillColor: MaterialStateProperty.all(Colors.black),
        ),
      ),
      initialRoute: '/',
      routes: {
        '/': (context) => const HomePage(),
      },
    );
  }
}

class HomePage extends StatefulWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  bool _switch1 = true;
  bool _switch2 = true;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Switch demo'),
      ),
      body: Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: [
            Switch(
              value: _switch1,
              onChanged: (value) {
                setState(() {
                  _switch1 = value;
                });
              },
            ),
            SwitchTheme(
              data: SwitchTheme.of(context).copyWith(
                thumbColor: MaterialStateProperty.all(Colors.green),
              ),
              child: Switch(
                value: _switch2,
                onChanged: (value) {
                  setState(() {
                    _switch2 = value;
                  });
                },
              ),
            ),
            const ListTile(
              title: Text('List tile'),
            ),
            ListTileTheme(
              data: ListTileTheme.of(context).copyWith(
                tileColor: Colors.red,
              ),
              child: const ListTile(
                title: Text('List tile'),
              ),
            ),
            Row(
              children: [
                RadioTheme(
                  data: RadioThemeData(
                    fillColor: MaterialStateProperty.all(Colors.blue),
                  ),
                  child: Radio(
                    value: 'Some',
                    groupValue: 'tell',
                    onChanged: (val) {},
                  ),
                ),
                Radio(
                  value: 'Some',
                  groupValue: 'tell',
                  onChanged: (val) {},
                ),
              ],
            ),
            Row(
              children: [
                CheckboxTheme(
                  data: CheckboxThemeData(
                    checkColor:
                        MaterialStateProperty.all(Colors.deepOrangeAccent),
                    fillColor: MaterialStateProperty.all(Colors.white),
                  ),
                  child: Checkbox(value: true, onChanged: (val) {}),
                ),
                Checkbox(value: true, onChanged: (val) {})
              ],
            ),
          ],
        ),
      ),
    );
  }
}

```
</details>

<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.2 21D49 darwin-arm, locale en-GB)
    • Flutter version 2.8.1 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (7 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:318:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1428:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1863:10)
      #15     runZonedGuarded (dart:async/zone.dart:1851:12)
      #16     runZoned (dart:async/zone.dart:1782:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:197:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:301:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:53:47)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1290:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (5 available)
    • M2007J20CG (mobile)         • 5dd3be00                  • android-arm64  • Android 11 (API 30)
    • sdk gphone64 arm64 (mobile) • emulator-5554             • android-arm64  • Android 12 (API 31) (emulator)
    • Nexus (mobile)              • 00008020-001875E83A38002E • ios            • iOS 15.3 19D50
    • macOS (desktop)             • macos                     • darwin-arm64   • macOS 12.2 21D49 darwin-arm
    • Chrome (web)                • chrome                    • web-javascript • Google Chrome 98.0.4758.80

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel master, 2.10.0-1.0.pre.402, on macOS 12.2 21D49 darwin-arm, locale en-GB)
    • Flutter version 2.10.0-1.0.pre.402 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ac52901c14 (5 hours ago), 2022-02-02 19:28:25 -0800
    • Engine revision baadc162a9
    • Dart version 2.17.0 (build 2.17.0-79.0.dev)
    • DevTools version 2.10.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 213.5744.122

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (5 available)
    • M2007J20CG (mobile)         • 5dd3be00                  • android-arm64  • Android 11 (API 30)
    • sdk gphone64 arm64 (mobile) • emulator-5554             • android-arm64  • Android 12 (API 31) (emulator)
    • Nexus (mobile)              • 00008020-001875E83A38002E • ios            • iOS 15.3 19D50
    • macOS (desktop)             • macos                     • darwin-arm64   • macOS 12.2 21D49 darwin-arm
    • Chrome (web)                • chrome                    • web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by SuperPenguin** [comment]
> Issue is reproducible on `stable` and `master`.
> 
> I also noticed the same behavior for `RadioTheme` and `CheckboxTheme`. I wonder if this is related to them extending `InheritedWidget` instead of `InheritedTheme`.
> 
> `ListTileTheme` does work as expected and it extends `InheritedTheme`.
> 
> screenshots
> code sample
> flutter doctor -v

I think the issue is those relevant widget never actually find their related WidgetTheme widget in their build code to begin with.

For example on

Switch only use `Theme.of(context)`, there is no `SwitchTheme.of(context)` in here
https://github.com/flutter/flutter/blob/ac52901c14764a5479c8240bb68d5a1a832a353f/packages/flutter/lib/src/material/switch.dart#L693

Radio, also same issue
https://github.com/flutter/flutter/blob/ac52901c14764a5479c8240bb68d5a1a832a353f/packages/flutter/lib/src/material/radio.dart#L373

Checkbox, same as well
https://github.com/flutter/flutter/blob/ac52901c14764a5479c8240bb68d5a1a832a353f/packages/flutter/lib/src/material/checkbox.dart#L405


However for other widgets like ListTile does find their WidgetTheme first then fallback the value to Theme

ListTile
https://github.com/flutter/flutter/blob/ac52901c14764a5479c8240bb68d5a1a832a353f/packages/flutter/lib/src/material/list_tile.dart#L1171-L1172

AppBar
https://github.com/flutter/flutter/blob/ac52901c14764a5479c8240bb68d5a1a832a353f/packages/flutter/lib/src/material/app_bar.dart#L798-L800

**Comment by TahaTesser** [comment]
@SuperPenguin 
Thank for filing the issue, i am looking into those widgets, just filing Switch fix.

**Comment by TahaTesser** [comment]
### Adding details for PRs

Currently `Switch` widget inherits only global theme ( as a resultlocalized widget theme is not inherited by the widget) and if you look at other widget such as `BottomNavigationBar`, widget-specific theme is inherited.

https://github.com/flutter/flutter/blob/ac52901c14764a5479c8240bb68d5a1a832a353f/packages/flutter/lib/src/material/bottom_navigation_bar.dart#L1000-L1009

```diff
    final BottomNavigationBarThemeData bottomTheme = BottomNavigationBarTheme.of(context);
+  final ThemeData theme = Theme.of(context);   
    final BottomNavigationBarLandscapeLayout layout = widget.landscapeLayout
      ?? bottomTheme.landscapeLayout
      ?? BottomNavigationBarLandscapeLayout.spread;
    final double additionalBottomPadding = MediaQuery.of(context).padding.bottom;

    Color? backgroundColor;
    switch (_effectiveType) {
      case BottomNavigationBarType.fixed:
-       backgroundColor = widget.backgroundColor ?? bottomTheme.backgroundColor;
+       backgroundColor = widget.backgroundColor ?? theme.bottomNavigationBarTheme.backgroundColor;
```

This can be reproduced using following code sample 

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark().copyWith(
        bottomNavigationBarTheme: const BottomNavigationBarThemeData(
          backgroundColor: Colors.purple,
        ),
        switchTheme: SwitchThemeData(
          thumbColor: MaterialStateProperty.all(Colors.purple),
          trackColor: MaterialStateProperty.all(Colors.purple),
        ),
      ),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  Home({Key? key}) : super(key: key);

  final ValueNotifier<int> bottomNavIndex = ValueNotifier<int>(0);

  @override
  Widget build(BuildContext context) {
    return ValueListenableBuilder<int>(
      valueListenable: bottomNavIndex,
      builder: (BuildContext context, int value, Widget? child) {
        return Scaffold(
          appBar: AppBar(
            title: const Text('Material App Bar'),
          ),
          body: Center(
            child: SwitchTheme(
              data: SwitchThemeData(
                thumbColor: MaterialStateProperty.all(Colors.yellow),
                trackColor: MaterialStateProperty.all(Colors.yellow),
              ),
              child: Switch(
                value: true,
                onChanged: (value) {

                },
              ),
            ),
          ),
          bottomNavigationBar: BottomNavigationBarTheme(
            data: const BottomNavigationBarThemeData(
              backgroundColor: Colors.yellow,
            ),
            child: BottomNavigationBar(
              items: const <BottomNavigationBarItem>[
                BottomNavigationBarItem(
                  icon: Icon(Icons.home),
                  label: 'Home',
                ),
                BottomNavigationBarItem(
                  icon: Icon(Icons.business),
                  label: 'Business',
                ),
                BottomNavigationBarItem(
                  icon: Icon(Icons.school),
                  label: 'School',
                ),
              ],
              currentIndex: bottomNavIndex.value,
              selectedItemColor: Colors.blue[300],
              onTap: (int index) => bottomNavIndex.value = index,
            ),
          ),
        );
      },
    );
  }
}
``` 
	
</details>
