### ISSUE TITLE
[tool_crash] ProcessException: Failed to find "*gradlew.bat" in the search path. Command: *android\gradlew.bat, OS error code: 0

### ISSUE THREAD

**Issue by Muhwildanferdiansyah** [flutter/flutter#97739]
## Command
```
flutter --no-color build apk
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Failed to find "C:\Users\user\AndroidStudioProjects\heatlh\android\gradlew.bat" in the search path. Command: C:\Users\user\AndroidStudioProjects\heatlh\android\gradlew.bat, OS error code: 0
```
#0      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:56:7)
#1      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:691:24)
#2      _run (package:flutter_tools/src/base/error_handling_io.dart:567:20)
#3      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:690:12)
#4      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:425:28)
#5      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:444:35)
#6      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:374:38)
#7      AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:179:11)
#8      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:108:26)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
```
```
[✓] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19042.1466], locale en-US)
    • Flutter version 2.8.1 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (7 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[!] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\user\AppData\Local\Android\sdk
    • Platform android-31, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.63.2)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.34.0

[✓] Connected device (3 available)
    • V2030 (mobile) • f5ec5c2e • android-arm64  • Android 11 (API 30)
    • Chrome (web)   • chrome   • web-javascript • Google Chrome 97.0.4692.99
    • Edge (web)     • edge     • web-javascript • Microsoft Edge 97.0.1072.76

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 77d935af4db863f6abd0b9c31c7e6df2a13de57b
### Plugins
fluttertoast-8.0.8

**Comment by maheshmnj** [comment]
Hi @Muhwildanferdiansyah, Thanks for filing the issue. The error seems to suggest that the `gradlew.bat`file is missing from the project could you please check at this location `C:\Users\user\AndroidStudioProjects\heatlh\android\gradlew.bat` and confirm if the file is present?
