### ISSUE TITLE
[web][html] Gradients with `TileMode.mirror` or `TileMode.repeated` are not rendered properly if Alpha is 0

### ISSUE THREAD

**Issue by dennj** [flutter/flutter#97762]
## Steps to Reproduce

1. Execute `flutter run -d chrome --web-renderer html` on the code sample 
2. Compare the result with canvaskit

**Expected results:** 
<img width="205" alt="Screenshot 2022-02-04 at 02 37 14" src="https://user-images.githubusercontent.com/2945710/152463353-45eb4b39-d989-4585-9e3e-eae7fdf023e7.png">

**Actual results:** 
<img width="249" alt="Screenshot 2022-02-04 at 02 37 47" src="https://user-images.githubusercontent.com/2945710/152463402-4a498e68-1bf9-4f19-a105-33acc35dd95b.png">

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(home: MyHomePage());
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Center(
            child: SizedBox(
                width: 100.0,
                height: 100.0,
                child: DecoratedBox(
                    decoration: BoxDecoration(
                        gradient: LinearGradient(
                            begin: Alignment.topLeft,
                            end: Alignment.topRight,
                            colors: <Color>[Colors.blue.withAlpha(0), Colors.blue],
                            tileMode: TileMode.repeated))))));
  }
}
```

</details>

<details>
  <summary>Logs</summary>

`❯ flutter run -d chrome --web-renderer html --verbose`

```console
[ +108 ms] executing: sysctl hw.optional.arm64
[  +21 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[   +6 ms] executing: [/Users/user/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +11 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 77d935af4db863f6abd0b9c31c7e6df2a13de57b
[        ] executing: [/Users/user/flutter/] git tag --points-at 77d935af4db863f6abd0b9c31c7e6df2a13de57b
[  +21 ms] Exit code 0 from: git tag --points-at 77d935af4db863f6abd0b9c31c7e6df2a13de57b
[        ] 2.8.1
[  +26 ms] executing: [/Users/user/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +13 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/user/flutter/] git ls-remote --get-url origin
[  +12 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +147 ms] executing: [/Users/user/flutter/] git rev-parse --abbrev-ref HEAD
[  +12 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[   +6 ms] executing: sw_vers -productName
[  +17 ms] Exit code 0 from: sw_vers -productName
[   +1 ms] macOS
[        ] executing: sw_vers -productVersion
[  +20 ms] Exit code 0 from: sw_vers -productVersion
[        ] 12.2
[        ] executing: sw_vers -buildVersion
[  +65 ms] Exit code 0 from: sw_vers -buildVersion
[   +2 ms] 21D49
[ +101 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +12 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +57 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +31 ms] executing: sysctl hw.optional.arm64
[   +6 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[        ] executing: xcrun xcodebuild -version
[   +8 ms] Exit code 72 from: xcrun xcodebuild -version
[        ] xcrun: error: unable to find utility "xcodebuild", not a developer tool or in PATH
[  +70 ms] Skipping pub get: version match.
[ +229 ms] Launching lib/main.dart on Chrome in debug mode...
[ +135 ms] Updating assets
[  +79 ms] Waiting for connection from debug service on Chrome...
[  +79 ms] <- reset
[   +7 ms] /Users/user/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /Users/user/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root
/Users/user/flutter/bin/cache/flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=false -DFLUTTER_WEB_USE_SKIA=false
--output-dill /var/folders/ms/dbnffgnn5dx2s5wvp5bqmxq40000gr/T/flutter_tools.484R9j/flutter_tool.WdBgy6/app.dill --libraries-spec file:///Users/user/flutter/bin/cache/flutter_web_sdk/libraries.json
--packages /Users/user/AndroidStudioProjects/gradient_bug/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root
/var/folders/ms/dbnffgnn5dx2s5wvp5bqmxq40000gr/T/flutter_tools.484R9j/flutter_tools.awLuYA --filesystem-scheme org-dartlang-app --initialize-from-dill
build/e1ffba66f615b3b54e08e2104bac7ab8.cache.dill.track.dill --platform file:///Users/user/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk_sound.dill --sound-null-safety
[  +14 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+13886 ms] Waiting for connection from debug service on Chrome... (completed in 14.0s)
[        ] Synced 28.4MB.
[        ] <- accept
[        ] Caching compiled dill
[  +92 ms] Using Google Chrome 98.0.4758.80 

[ +104 ms] executing: sysctl hw.optional.arm64
[   +7 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[ +348 ms] [CHROME]:
[        ] [CHROME]:DevTools listening on ws://127.0.0.1:64592/devtools/browser/a95e9b72-1483-4df2-95a9-b1e3a7944263
[ +925 ms] DwdsInjector: Received request for entrypoint at http://localhost:64578/main_module.bootstrap.js
[   +6 ms] MetadataProvider: Loading debug metadata...
[  +12 ms] MetadataProvider: Loaded debug metadata (sound null safety)
[   +5 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:64578/main_module.bootstrap.js
[+2156 ms] ChromeProxyService: Initializing expression compiler for main_module.bootstrap.js with sound null safety: true
[  +70 ms] DevHandler: Debug service listening on ws://127.0.0.1:64620/Y_qDTPjaO1k=/ws

[  +20 ms] This app is linked to the debug service: ws://127.0.0.1:64620/Y_qDTPjaO1k=/ws
[  +10 ms] Debug service listening on ws://127.0.0.1:64620/Y_qDTPjaO1k=/ws
[        ] 💪 Running with sound null safety 💪
[   +3 ms] 🔥  To hot restart changes while running, press "r" or "R".
[        ] For a more detailed help message, press "h". To quit, press "q".
[   +1 ms] An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:64620/Y_qDTPjaO1k=
[ +409 ms] The Flutter DevTools debugger and profiler on Chrome is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:64620/Y_qDTPjaO1k=
[+3515 ms] DevHandler: Stopped debug service on ws://127.0.0.1:44456

[ +488 ms] Application finished.
[   +4 ms] "flutter run" took 22,855ms.
[  +80 ms] ensureAnalyticsSent: 75ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0

```

`❯ flutter analyze`

Analyzing gradient_bug...                                               
No issues found! (ran in 2.1s)

`❯ flutter doctor`

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.2 21D49 darwin-x64, locale en-IE)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.1)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

</details>

**Comment by danagbemava-nc** [comment]
Issue is reproducible on `stable` and `master`. 

Note: In the following screenshots, the results with the `canvaskit` renderer are on the left and the `html` renderer on the right.

<details>
<summary>screenshots [one color has no alpha 0]</summary>

## LinearGradient

`TileMode.mirror`

![tilemode-mirror](https://user-images.githubusercontent.com/88313112/152521234-6e10e3b6-5f32-46ee-9316-76bb2b408222.png)

`TileMode.clamp`

![tilemode-clamp](https://user-images.githubusercontent.com/88313112/152521276-513f8dca-057b-46dd-be71-37adc864a4ca.png)

`TileMode.repeated`

![tilemode-repeated](https://user-images.githubusercontent.com/88313112/152521326-27c08ffe-6600-449b-8e67-bce89bb5d8ec.png)

`TileMode.decal`

![tilemode-decal](https://user-images.githubusercontent.com/88313112/152521357-4ed56890-2519-4231-9373-a9e865903448.png)


## RadialGradient

`TileMode.mirror`

![tilemode-mirror-radial](https://user-images.githubusercontent.com/88313112/152521518-b785439d-207b-4a97-a364-ab6dae66d1bc.png)

`TileMode.clamp`

![tilemode-clamp-radial](https://user-images.githubusercontent.com/88313112/152521572-f96d2c24-9bed-4657-b3ac-66c426b544d0.png)

`TileMode.repeated`

![tilemode-repeated-radial](https://user-images.githubusercontent.com/88313112/152522125-d684db6a-091e-4839-8576-37d11892886f.png)

`TileMode.decal`

![tilemode-decal-radial](https://user-images.githubusercontent.com/88313112/152522176-a697331f-1660-43f9-86a7-f482455d683c.png)

</details>

<details>
<summary>screenshots [no color has 0 alpha] (I used a different color here to make it easily distinguishable ) </summary>

## LinearGradient

`TileMode.mirror`

![tilemode-mirror-linear](https://user-images.githubusercontent.com/88313112/152523562-16209a47-2c30-4ea7-9923-ed163586d79e.png)

`TileMode.clamp`

![tilemode-clamp-linear](https://user-images.githubusercontent.com/88313112/152523655-359ffb3f-2c5d-4a0c-8335-e12c29dfd2c7.png)


`TileMode.repeated`

![tilemode-repeated-linear](https://user-images.githubusercontent.com/88313112/152523688-d09cbfcd-1475-41b2-9abd-cdb331f9981b.png)

`TileMode.decal`

![tilemode-decal-linear](https://user-images.githubusercontent.com/88313112/152523725-913fa57b-c37f-4f8c-8ae3-2d539c3c8a4b.png)


## RadialGradient

`TileMode.mirror`

![tilemode-mirror-radial](https://user-images.githubusercontent.com/88313112/152523752-df2a773d-2569-4d2e-82e2-ecfe1f346353.png)

`TileMode.clamp`

![tilemode-clamp-radial](https://user-images.githubusercontent.com/88313112/152523779-b769dd84-a5ad-4186-8052-5a478ffa759a.png)

`TileMode.repeated`

![tilemode-repeated-radial](https://user-images.githubusercontent.com/88313112/152523817-081c2fda-3940-44b3-b738-604c2c6223e1.png)

`TileMode.decal`

![tilemode-decal-radial](https://user-images.githubusercontent.com/88313112/152523842-7d7d687a-d3b3-4965-a748-54d6d06f34b8.png)


## SweepGradient
Nothing is rendered when using HTML renderer [with or without an alpha channel]

![Screenshot 2022-02-04 at 11 18 34](https://user-images.githubusercontent.com/88313112/152524155-c98b9725-38dc-4c10-adf3-45823ccd3881.png)


</details>

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(home: MyHomePage());
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: SizedBox(
          width: 100.0,
          height: 100.0,
          child: DecoratedBox(
            decoration: BoxDecoration(
              // Todo switch between the various Gradient Types [Nothing is rendered in html when using SweepGradient]
              gradient: LinearGradient(
                // begin: Alignment.topLeft,
                // end: Alignment.topRight,
                colors: <Color>[
                  // Todo switch out red and blue.withAlpha(0) to see the differences
                  // Colors.red,
                  Colors.blue.withAlpha(0),
                  Colors.blue,
                ],
                tileMode: TileMode.decal,
              ),
            ),
          ),
        ),
      ),
    );
  }
}

```

</details>


<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.10.0, on macOS 12.2 21D49 darwin-arm, locale en-GB)
    • Flutter version 2.10.0 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f105a6ca7 (3 days ago), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1426:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1861:10)
      #15     runZonedGuarded (dart:async/zone.dart:1849:12)
      #16     runZoned (dart:async/zone.dart:1780:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:205:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:309:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.64.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (3 available)
    • M2007J20CG (mobile) • 5dd3be00 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)     • macos    • darwin-arm64   • macOS 12.2 21D49 darwin-arm
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel master, 2.10.0-1.0.pre.421, on macOS 12.2 21D49 darwin-arm, locale en-GB)
    • Flutter version 2.10.0-1.0.pre.421 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 58407234f5 (7 hours ago), 2022-02-04 06:40:13 +0200
    • Engine revision dfaad2a2c2
    • Dart version 2.17.0 (build 2.17.0-79.0.dev)
    • DevTools version 2.10.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 213.5744.122

[✓] VS Code (version 1.64.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (3 available)
    • M2007J20CG (mobile) • 5dd3be00 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)     • macos    • darwin-arm64   • macOS 12.2 21D49 darwin-arm
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>
