### ISSUE TITLE
Linux build fails with flutter 2.10

### ISSUE THREAD

**Issue by synchronisator** [flutter/flutter#97788]
## Steps to Reproduce

1. Create a project with Flutter 2.8.1 on Linux Mint 
2. flutter upgrade
```
 Upgrading Flutter to 2.10.0 from 2.8.1 in [...]
``` 
3. flutter build linux
``` 
Because every version of flutter_test from sdk depends on material_color_utilities 0.1.3 which doesn't match any versions, flutter_test from sdk is forbidden.
So, because splitlive depends on flutter_test from sdk, version solving failed.
Running "flutter pub get" in splitlive...                               
pub get failed (1; So, because splitlive depends on flutter_test from sdk, version solving failed.)
``` 
or $ flutter build linux --verbose

```
[  +52 ms] executing: uname -m
[  +26 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +4 ms] executing: [/home/synchron/Entwicklung/sdks/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +4 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 5f105a6ca7a5ac7b8bc9b241f4c2d86f4188cf5c
[        ] executing: [/home/synchron/Entwicklung/sdks/flutter/] git tag --points-at 5f105a6ca7a5ac7b8bc9b241f4c2d86f4188cf5c
[  +10 ms] Exit code 0 from: git tag --points-at 5f105a6ca7a5ac7b8bc9b241f4c2d86f4188cf5c
[        ] 2.10.0
[   +8 ms] executing: [/home/synchron/Entwicklung/sdks/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/synchron/Entwicklung/sdks/flutter/] git ls-remote --get-url origin
[   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +63 ms] executing: [/home/synchron/Entwicklung/sdks/flutter/] git rev-parse --abbrev-ref HEAD
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +42 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +47 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +81 ms] Running "flutter pub get" in splitlive...
[   +4 ms] executing: [/home/synchron/Entwicklung/gitrepos/flutter/splitlive/] /home/synchron/Entwicklung/sdks/flutter/bin/cache/dart-sdk/bin/dart __deprecated_pub --verbose get --no-precompile
[  +62 ms] FINE: Pub 2.16.0
[  +43 ms] MSG : Resolving dependencies...
[  +37 ms] SLVR: fact: splitlive is 1.0.0+1
[   +4 ms] SLVR: derived: splitlive
[  +21 ms] SLVR: fact: splitlive depends on flutter from sdk
[        ] SLVR: fact: splitlive depends on cupertino_icons ^1.0.2
[        ] SLVR: fact: splitlive depends on provider ^6.0.2
[        ] SLVR: fact: splitlive depends on shared_preferences ^2.0.11
[        ] SLVR: fact: splitlive depends on intl ^0.17.0
[        ] SLVR: fact: splitlive depends on material_color_utilities ^0.1.8
[        ] SLVR: fact: splitlive depends on flutter_test from sdk
[        ] SLVR: fact: splitlive depends on flutter_lints ^1.0.0
[        ] SLVR:   selecting splitlive
[        ] SLVR:   derived: flutter_lints ^1.0.0
[        ] SLVR:   derived: flutter_test from sdk
[        ] SLVR:   derived: material_color_utilities ^0.1.8
[        ] SLVR:   derived: intl ^0.17.0
[        ] SLVR:   derived: shared_preferences ^2.0.11
[        ] SLVR:   derived: provider ^6.0.2
[        ] SLVR:   derived: cupertino_icons ^1.0.2
[        ] SLVR:   derived: flutter from sdk
[  +33 ms] IO  : Get versions from https://pub.dartlang.org/api/packages/material_color_utilities.
[  +14 ms] IO  : HTTP GET https://pub.dartlang.org/api/packages/material_color_utilities
[        ]     | Accept: application/vnd.pub.v2+json
[        ]     | X-Pub-OS: linux
[        ]     | X-Pub-Command: get
[        ]     | X-Pub-Session-ID: C6EDE150-1387-4FA0-A9B6-EE59976E6E57
[        ]     | X-Pub-Environment: flutter_cli:verify:linux
[        ]     | X-Pub-Reason: direct
[        ]     | user-agent: Dart pub 2.16.0
[ +303 ms] IO  : HTTP response 200 OK for GET https://pub.dartlang.org/api/packages/material_color_utilities
[        ]     | took 0:00:00.305188
[        ]     | transfer-encoding: chunked
[        ]     | date: Fri, 04 Feb 2022 12:05:01 GMT
[        ]     | content-encoding: gzip
[        ]     | strict-transport-security: max-age=31536000; preload
[        ]     | via: 1.1 google
[        ]     | content-type: application/json; charset="utf-8"
[        ]     | x-frame-options: SAMEORIGIN
[        ]     | x-xss-protection: 1; mode=block
[        ]     | x-content-type-options: nosniff
[        ]     | server: dart:io with Shelf
[  +32 ms] IO  : Writing 3552 characters to text file /home/synchron/.pub-cache/hosted/pub.dartlang.org/.cache/material_color_utilities-versions.json.
[        ] FINE: Contents:
[        ]     | {"name":"material_color_utilities","latest":{"version":"0.1.4","pubspec":{"name":"material_color_utilities","description":"Algorithms and utilities that power the Material Design 3 (M3) color
system, including choosing theme colors from images and creating tones of colors; all in a new color
space.","version":"0.1.4","repository":"https://github.com/material-foundation/material-color-utilities","environment":{"sdk":">=2.13.4
<3.0.0"},"dev_dependencies":{"matcher":"^0.12.0","test":"^1.16.0"}},"archive_url":"https://pub.dartlang.org/packages/material_color_utilities/versions/0.1.4.tar.gz","published":"2022-01-21T17:40:48.050965Z"},"versi
ons":[{"version":"0.1.0","pubspec":{"name":"material_color_utilities","description":"Dart library for Material You
color.","version":"0.1.0","repository":"https://github.com/material-foundation/material-color-utilities","environment":{"sdk":">=2.13.4
<3.0.0"},"dev_dependencies":{"test":"^1.16.0"},"dependencies":{"matcher":"^0.12.11"}},"archive_url":"https://pub.dartlang.org/packages/material_color_utilities/versions/0.1.0.tar.gz","published":"2021-10-28T14:39:4
2.858732Z"},{"version":"0.1.1","pubspec":{"name":"material_color_utilities","description":"Algorithms and utilities that power the Material Design 3 (M3) color system, including choosing theme colors from images
and creating tones of colors; all in a new color space.","version":"0.1.1","repository":"https://github.com/material-foundation/material-color-utilities","environment":{"sdk":">=2.13.4
<3.0.0"},"dev_dependencies":{"test":"^1.16.0"},"dependencies":{"matcher":"^0.12.0"}},"archive_url":"https://pub.dartlang.org/packages/material_color_utilities/versions/0.1.1.tar.gz","published":"2021-10-28T16:05:17
.476202Z"},{"version":"0.1.2","pubspec":{"name":"material_color_utilities","description":"Algorithms and utilities that power the Material Design 3 (M3) color system, including choosing theme colors from images and
creating tones of colors; all in a new color space.","version":"0.1.2","repository":"https://github.com/material-foundation/material-color-utilities","environment":{"sdk":">=2.13.4
<3.0.0"},"dev_dependencies":{"matcher":"^0.12.0","test":"^1.16.0"}},"archive_url":"https://pub.dartlang.org/packages/material_color_utilities/versions/0.1.2.tar.gz","published":"2021-12-02T14:57:25.214933Z"},{"vers
ion":"0.1.3","pubspec":{"name":"material_color_utilities","description":"Algorithms and utilities that power the Material Design 3 (M3) color system, including choosing theme colors from images and creating tones
of colors; all in a new color space.","version":"0.1.3","repository":"https://github.com/material-foundation/material-color-utilities","environment":{"sdk":">=2.13.4
<3.0.0"},"dev_dependencies":{"matcher":"^0.12.0","test":"^1.16.0"}},"archive_url":"https://pub.dartlang.org/packages/material_color_utilities/versions/0.1.3.tar.gz","published":"2021-12-10T12:04:21.996609Z"},{"vers
ion":"0.1.4","pubspec":{"name":"material_color_utilities","description":"Algorithms and utilities that power the Material Design 3 (M3) color system, including choosing theme colors from images and creating tones
of colors; all in a new color space.","version":"0.1.4","repository":"https://github.com/material-foundation/material-color-utilities","environment":{"sdk":">=2.13.4
<3.0.0"},"dev_dependencies":{"matcher":"^0.12.0","test":"^1.16.0"}},"archive_url":"https://pub.dartlang.org/packages/material_color_utilities/versions/0.1.4.tar.gz","published":"2022-01-21T17:40:48.050965Z"}],"_fet
chedAt":"2022-02-04T13:05:01.493261"}
[   +9 ms] SLVR:   fact: no versions of material_color_utilities match ^0.1.8
[        ] SLVR:   conflict: no versions of material_color_utilities match ^0.1.8
[   +1 ms] SLVR:   ! material_color_utilities ^0.1.8 is satisfied by material_color_utilities ^0.1.8
[        ] SLVR:   ! which is caused by "splitlive depends on material_color_utilities ^0.1.8"
[        ] SLVR:   ! thus: version solving failed
[   +2 ms] SLVR: Version solving took 0:00:00.437956 seconds.
[        ]     | Tried 1 solutions.
[        ] FINE: Resolving dependencies finished (0.474s).
[   +9 ms] ERR : Because splitlive depends on material_color_utilities ^0.1.8 which doesn't match any versions, version solving failed.
[        ] FINE: Exception type: SolveFailure
[  +23 ms] FINE: package:pub/src/solver/version_solver.dart 312:5               VersionSolver._resolveConflict
[        ]     | package:pub/src/solver/version_solver.dart 133:27              VersionSolver._propagate
[        ]     | package:pub/src/solver/version_solver.dart 97:11               VersionSolver.solve.<fn>
[        ]     | ===== asynchronous gap ===========================
[        ]     | dart:async                                                     Future.catchError
[        ]     | package:pub/src/utils.dart 109:52                              captureErrors.wrappedCallback
[        ]     | package:stack_trace                                            Chain.capture
[        ]     | package:pub/src/utils.dart 122:11                              captureErrors
[        ]     | package:pub/src/command.dart 180:13                            PubCommand.run
[        ]     | package:args/command_runner.dart 209:27                        CommandRunner.runCommand
[        ]     | package:pub/src/command_runner.dart 173:24                     PubCommandRunner.runCommand
[        ]     | package:pub/src/command_runner.dart 158:20                     PubCommandRunner.run
[        ]     | package:dartdev/dartdev.dart 46:56                             runDartdev
[        ]     | /b/s/w/ir/cache/builder/sdk/pkg/dartdev/bin/dartdev.dart 11:9  main
[  +59 ms] Running "flutter pub get" in splitlive... (completed in 667ms)
[        ] "flutter linux" took 833ms.
[   +3 ms] pub get failed (1;     | /b/s/w/ir/cache/builder/sdk/pkg/dartdev/bin/dartdev.dart 11:9  main)
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _DefaultPub.batch (package:flutter_tools/src/dart/pub.dart:373:7)
           <asynchronous suspension>
           #2      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:254:7)
           <asynchronous suspension>
           #3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1301:7)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #12     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>
           
           
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +1 ms] exiting with code 1

```

flutter doctor -v
```
[✓] Flutter (Channel stable, 2.10.0, on Linux Mint 20 5.4.0-92-generic, locale de_DE.UTF-8)
    • Flutter version 2.10.0 at /home/synchron/Entwicklung/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f105a6ca7 (vor 3 Tagen), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/synchron/Android/Sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 4.0)
    • Android Studio at /home/synchron/Entwicklung/android_studio/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /home/synchron/Entwicklung/intellij/idea-IC-201.7846.76
    • Flutter plugin version 52.1.5
    • Dart plugin version 203.6803

[✓] VS Code (version 1.63.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.17.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux Mint 20 5.4.0-92-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 97.0.4692.71

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

Downgrading to Flutter 2.8.1 is possible and works fine.
There is a issue where the package material_color_utilities is mentioned:  https://github.com/flutter/flutter/issues/95807

**Comment by stuartmorgan** [comment]
From the build error:

> splitlive depends on material_color_utilities ^0.1.8

and:

> fact: no versions of material_color_utilities match ^0.1.8

This had nothing to do with 2.10; you have set a minimum version of one of your dependencies to a version that doesn't exist.
