### ISSUE TITLE
Flutter 2.10 upgrade fails at IntelliJ Plugin step on Linux

### ISSUE THREAD

**Issue by dxps** [flutter/flutter#97792]
Hi everyone,

Just a heads-up about a potential problem (didn't check yet the side effects, but I'll update this ticket with any other findings) that happens when doing the Flutter upgrade from 2.8.1 to 2.10.0.

I'm doing this on a Pop_OS! 21.10 distro, which is up to date (incl IntelliJ plugins) at the time of this writing.
```shell
$ uname -a
Linux dxps 5.15.15-76051515-generic #202201160435~1642693824~21.10~97db1bb SMP Thu Jan 20 17:35:05 U x86_64 x86_64 x86_64 GNU/Linux
$ 
```

## Steps to Reproduce

Just doing `flutter upgrade` and `flutter doctor -v`. See the details in the next section.

## Logs

<details>
<summary>Logs</summary>

#### Flutter Upgrade

```shell
❯ flutter upgrade
Upgrading Flutter to 2.10.0 from 2.8.1 in /home/dxps/apps/flutter...
Downloading Dart SDK from Flutter engine 776efd2034d50af73e2876d703213601df384e88...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 13  211M   13 28.8M    0     0  40.2M      0  0:00:05 --:--:--  0:00:05 40.2M
 58  211M   58  123M    0     0  71.2M      0  0:00:02  0:00:01  0:00:01 71.2M
100  211M  100  211M    0     0  79.6M      0  0:00:02  0:00:02 --:--:-- 79.6M
Building flutter tool...

Upgrading engine...
Downloading android-arm-profile/linux-x64 tools...                 636ms
Downloading android-arm-release/linux-x64 tools...                 262ms
Downloading android-arm64-profile/linux-x64 tools...               386ms
Downloading android-arm64-release/linux-x64 tools...               423ms
Downloading android-x64-profile/linux-x64 tools...                 246ms
Downloading android-x64-release/linux-x64 tools...                 411ms
Downloading android-x86 tools...                                   557ms
Downloading android-x64 tools...                                 1,012ms
Downloading android-arm tools...                                   683ms
Downloading android-arm-profile tools...                           202ms
Downloading android-arm-release tools...                           126ms
Downloading android-arm64 tools...                                 546ms
Downloading android-arm64-profile tools...                         190ms
Downloading android-arm64-release tools...                         129ms
Downloading android-x64-profile tools...                           271ms
Downloading android-x64-release tools...                           137ms
Downloading android-x86-jit-release tools...                       186ms
Downloading Web SDK...                                           1,448ms
Downloading CanvasKit...                                           710ms
Downloading package sky_engine...                                   51ms
Downloading flutter_patched_sdk tools...                           144ms
Downloading flutter_patched_sdk_product tools...                   101ms
Downloading linux-x64 tools...                                     809ms
Downloading linux-x64/linux-x64-flutter-gtk tools...               576ms
Downloading linux-x64-profile/linux-x64-flutter-gtk tools...        509ms
Downloading linux-x64-release/linux-x64-flutter-gtk tools...        355ms
Downloading linux-x64/font-subset tools...                         208ms

Flutter 2.10.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5f105a6ca7 (3 days ago) • 2022-02-01 14:15:42 -0800
Engine • revision 776efd2034
Tools • Dart 2.16.0 • DevTools 2.9.2

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.0, on Pop!_OS 21.10 5.15.15-76051515-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2020.3)
[☠] IntelliJ IDEA Ultimate Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
[✓] VS Code (version 1.63.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
~ took 51s ❯ 
```

### Flutter Doctor

```shell
❯ flutter doctor -v
[✓] Flutter (Channel stable, 2.10.0, on Pop!_OS 21.10 5.15.15-76051515-generic, locale en_US.UTF-8)
    • Flutter version 2.10.0 at /home/dxps/apps/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f105a6ca7 (3 days ago), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/dxps/apps/android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /home/dxps/apps/android/studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 13.0.0-2
    • cmake version 3.18.4
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/dxps/apps/android/studio
    • Flutter plugin version 63.0.1
    • Dart plugin version 203.8452
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[☠] IntelliJ IDEA Ultimate Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1426:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1861:10)
      #15     runZonedGuarded (dart:async/zone.dart:1849:12)
      #16     runZoned (dart:async/zone.dart:1780:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:205:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:309:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.63.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.34.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Pop!_OS 21.10 5.15.15-76051515-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 96.0.4664.93

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
~ took 2s ❯
```

</details>

<br/>

Hope it helps.
To be honest, I shouldn't be that impacted since I prefer using VSCode with Flutter, but others may be, that's why this ticket.

Thank you for providing such goodness to the world! :blush:

**Comment by darshankawar** [comment]
@dxps 
The flutter doctor -v error on intellij plugin you are seeing has nothing to do with 2.10 upgrade. It's a separate issue which has been fixed already and  is currently available on master and will be rolled out in beta and stable per Flutter's release guidelines.
See https://github.com/flutter/flutter/issues/94060#issuecomment-1018801980 issue comment for your reference.
Closing this as a duplicate.
