### ISSUE TITLE
Failed assertion: 'size.isFinite': is not true.

### ISSUE THREAD

**Issue by ashishXenonstack** [flutter/flutter#97795]
## Steps to Reproduce

1. Execute `flutter run` on the code sample ( make a simple viewPort page indicator with the sample code below )

**Expected results:** ( 3 Circle Indicators representing the 3 pages for the View Port )

**Actual results:** ( The viewport was rendered but with the exception as mentioned below. )

<details>
<summary> Sample code </summary>

```

final titles = [
    'Sample 1',
    'Sample 2',
    'Sample 3'
  ];

  final _currentPageNotifier = ValueNotifier<int>(0); // [0,1,2]

return Stack(
          children: [
            _buildCircleIndicator()
          ]
      );

_buildCircleIndicator() {
    return Positioned(
            left: 0.0,
            right: 0.0,
            bottom: 0.0,
              child: Padding(
                padding: const EdgeInsets.all(8.0),
                child: CirclePageIndicator(
                  itemCount: titles.length,
                  currentPageNotifier: _currentPageNotifier,
                ),
              ),
    );
  }

```

<details>
  <summary>Logs</summary>

```

══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
'package:flutter/src/rendering/stack.dart': Failed assertion: line 588 pos 12: 'size.isFinite': is
not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was:
  Stack
  Stack:file:///home/ag/AndroidStudioProjects/dlogin/lib/screens/onboarding_one.screen.dart:59:14

When the exception was thrown, this was the stack:
#2      RenderStack._computeSize (package:flutter/src/rendering/stack.dart:588:12)
#3      RenderStack.performLayout (package:flutter/src/rendering/stack.dart:597:12)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#5      ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
#6      RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:829:43)
#7      RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:931:32)
#8      RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#9      _RenderSingleChildViewport.performLayout (package:flutter/src/widgets/single_child_scroll_view.dart:504:14)
#10     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#11     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#12     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#13     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#14     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#15     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#16     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#17     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#18     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#19     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#20     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#21     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#22     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#23     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#24     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#25     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#26     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:545:11)
#27     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#29     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#30     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#31     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#32     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#33     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#34     RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:240:19)
#35     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#36     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:137:12)
#37     _RenderSliverFractionalPadding.performLayout (package:flutter/src/widgets/sliver_fill.dart:167:11)
#38     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#39     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:510:13)
#40     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1580:12)
#41     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1489:20)
#42     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#43     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#44     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#45     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#46     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#47     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#48     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#49     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#50     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#51     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#52     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#53     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#54     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#55     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#56     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#57     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#58     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:545:11)
#59     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#60     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#61     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#62     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:277:14)
#63     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#64     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
#65     RenderStack._computeSize (package:flutter/src/rendering/stack.dart:570:43)
#66     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:597:12)
#67     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#68     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
#69     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:829:43)
#70     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:931:32)
#71     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#72     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
#73     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1005:7)
#74     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
#75     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:403:14)
#76     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#77     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#78     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#79     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#80     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1376:11)
#81     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#82     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#83     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#84     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#85     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#86     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#87     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#88     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#89     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#90     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#91     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#92     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#93     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#94     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#95     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#96     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#97     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#98     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#99     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3428:13)
#100    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#101    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#102    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#103    _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:751:15)
#104    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#105    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#106    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#107    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#108    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#109    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#110    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#111    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#112    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#113    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#114    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#115    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#116    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#117    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#118    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#119    RenderView.performLayout (package:flutter/src/rendering/view.dart:165:14)
#120    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1707:7)
#121    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:879:18)
#122    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:497:19)
#123    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#124    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#125    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
#126    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#127    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:863:7)
(elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)

The following RenderObject was being processed when the exception was fired: RenderStack#1f60e relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
  creator: Stack ← Column ← _SingleChildViewport ← IgnorePointer-[GlobalKey#147d5] ← Semantics ←
    Listener ← _GestureSemantics ←
    RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#0d7b0] ← Listener ← _ScrollableScope
    ← _ScrollSemantics-[GlobalKey#3c5f1] ← NotificationListener<ScrollMetricsNotification> ← ⋯
  parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
  constraints: BoxConstraints(0.0<=w<=392.7, 0.0<=h<=Infinity)
  size: MISSING
  alignment: AlignmentDirectional.topStart
  textDirection: ltr
  fit: loose
This RenderObject had the following descendants (showing up to depth 5):
    child 1: RenderPadding#b3054 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
      child: RenderWrap#9287f NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        child 1: RenderSemanticsGestureHandler#b7cfd NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
          child: RenderPointerListener#45810 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
            child: RenderConstrainedBox#a2b5e NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        child 2: RenderSemanticsGestureHandler#8bf2d NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
          child: RenderPointerListener#f499a NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
            child: RenderConstrainedBox#7d6e0 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        child 3: RenderSemanticsGestureHandler#ce73a NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
          child: RenderPointerListener#63cfd NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
            child: RenderConstrainedBox#d48b0 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: RenderBox was not laid out: RenderStack#1f60e relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE

Another exception was thrown: RenderBox was not laid out: RenderFlex#41f9f relayoutBoundary=up1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE

Another exception was thrown: RenderBox was not laid out: _RenderSingleChildViewport#84cbb NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE

Another exception was thrown: RenderBox was not laid out: RenderIgnorePointer#0d93d NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE

Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#35050 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE

Another exception was thrown: RenderBox was not laid out: RenderPointerListener#c03a3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE

Another exception was thrown: RenderBox was not laid out: RenderSemanticsGestureHandler#da3fd NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE

Another exception was thrown: RenderBox was not laid out: RenderPointerListener#133b1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE

Another exception was thrown: RenderBox was not laid out: _RenderScrollSemantics#c12ce NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE

Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#e7f88 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE

Another exception was thrown: RenderBox was not laid out: RenderCustomPaint#a60f8 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE

Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#1ab1f NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE

Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#9cfc1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE

Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 544 pos 12: 'child.hasSize': is not true.
Syncing files to device Android SDK built for x86...               545ms


```

</details>

<summary>
     Flutter analyse result
</summary>
All Good. with Flutter analyse
```
```

<summary>  flutter run -v. </summary>
No issues found! 
```
```

**Comment by darshankawar** [comment]
@ashishXenonstack 
Can you provide `flutter doctor -v` ?
Also, please provide a complete minimal reproducible code sample that we can directly run that shows this error.
Moreover, you can check your implementation once and refer [this](https://github.com/flutter/flutter/issues/76972#issuecomment-787790849) to see if it helps to resolve.

**Comment by ashishXenonstack** [comment]
@darshankawar 

I have been dangling a bit with the issue and found a workaround to get the desired result.
So, instead of the Positioned Widget (as i mentioned earlier), i have updated it as : 

 _buildCircleIndicator() {
    return Padding(
        padding: const EdgeInsets.all(60.0),
        child: CirclePageIndicator(
          size: 14.0,
          selectedSize: 16.0,
          itemCount: titles.length,
          currentPageNotifier: _currentPageNotifier,
        ),
      );
  }

which gives me the same result. The issue probably seems due to the use of Stack widget with Positioned, Stack being an unbounded widget  within a Column widget. 
I will try to reproduce the error seperately and update here asap.

Thank you for such fast response.
