### ISSUE TITLE
[tool_crash] UnsupportedError: Unsupported operation: Illegal character in path: assetsD:\Programming\My Work\Flutter Apps\smart_education_   test\assets

### ISSUE THREAD

**Issue by mazap64** [flutter/flutter#97801]
## Command
```
flutter --quiet assemble --no-version-check --depfile D:\Programming\My Work\Flutter Apps\smart_education_   test\build\app\intermediates\flutter\debug/flutter_build.d --output D:\Programming\My Work\Flutter Apps\smart_education_   test\build\app\intermediates\flutter\debug -dTargetFile=D:\Programming\My Work\Flutter Apps\smart_education_   test\lib\main.dart -dTargetPlatform=android -dBuildMode=debug -dTrackWidgetCreation=true --DartDefines=Zmx1dHRlci5pbnNwZWN0b3Iuc3RydWN0dXJlZEVycm9ycz10cnVl,RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== --ExtraFrontEndOptions=--no-sound-null-safety debug_android_application
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
UnsupportedError: Unsupported operation: Illegal character in path: assetsD:\Programming\My Work\Flutter Apps\smart_education_   test\assets
```
#0      _Uri._checkWindowsPathReservedCharacters (dart:core/uri.dart:1644:11)
#1      _Uri._toWindowsFilePath (dart:core/uri.dart:2674:7)
#2      _Uri.toFilePath (dart:core/uri.dart:2646:38)
#3      ManifestAssetBundle._parseAssetsFromFolder (package:flutter_tools/src/asset.dart:744:29)
#4      ManifestAssetBundle._parseAssets (package:flutter_tools/src/asset.dart:685:9)
#5      ManifestAssetBundle.build (package:flutter_tools/src/asset.dart:245:54)
<asynchronous suspension>
#6      copyAssets (package:flutter_tools/src/build_system/targets/assets.dart:50:26)
<asynchronous suspension>
#7      AndroidAssetBundle.build (package:flutter_tools/src/build_system/targets/android.dart:64:34)
<asynchronous suspension>
#8      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:839:9)
<asynchronous suspension>
#9      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:606:16)
<asynchronous suspension>
#10     AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:317:32)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.22000.466], locale en-US)
    • Flutter version 2.8.1 at C:\Users\mazab\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (7 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\mazab\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[✓] VS Code (version 1.63.2)
    • VS Code at C:\Users\mazab\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.32.0

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 97.0.1072.76

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f4abaa0735eba4dfd8f33f73363911d63931fe03
### Plugins
flutter_keyboard_visibility-5.1.1
flutter_keyboard_visibility_web-2.0.0
fluttertoast-8.0.8
hexcolor-2.0.6
path_provider-2.0.8
path_provider_android-2.0.11
path_provider_ios-2.0.7
path_provider_linux-2.1.5
path_provider_macos-2.0.5
path_provider_windows-2.0.5
shared_preferences-2.0.12
shared_preferences_android-2.0.10
shared_preferences_ios-2.0.9
shared_preferences_linux-2.0.4
shared_preferences_macos-2.0.2
shared_preferences_web-2.0.3
shared_preferences_windows-2.0.4
webview_flutter-3.0.0
webview_flutter_android-2.8.2
webview_flutter_wkwebview-2.7.1

**Comment by darshankawar** [comment]
@mazap64 
I see a space in your Flutter app name `smart_education_   test` which could be the reason you are getting the error.
Try to remove the space and see if it helps.
I am going ahead and closing this for now. If not, write in comments and I'll reopen it.
