### ISSUE TITLE
Unable to recover from some bad layouts with hot reload

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#9781]
After fixing the problem described in https://github.com/flutter/flutter/issues/9780 I tried to hot reload my app and got the following exception:

```
I/flutter (14542): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (14542): The following assertion was thrown during performLayout():
I/flutter (14542): 'package:flutter/src/rendering/object.dart': Failed assertion: line 1818 pos 12:
I/flutter (14542): '!_debugDoingThisLayout': is not true.
I/flutter (14542): 
I/flutter (14542): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (14542): more information in this error message to help you determine and fix the underlying cause.
I/flutter (14542): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (14542):   https://github.com/flutter/flutter/issues/new
I/flutter (14542): 
I/flutter (14542): When the exception was thrown, this was the stack:
I/flutter (14542): #2      RenderObject.layout (package:flutter/src/rendering/object.dart:1818:12)
I/flutter (14542): #3      RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:500:15)
I/flutter (14542): #4      RenderObject.layout (package:flutter/src/rendering/object.dart:1872:7)
I/flutter (14542): #5      RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (14542): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1872:7)
I/flutter (14542): #7      RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (14542): #8      _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:980:24)
I/flutter (14542): #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1872:7)
I/flutter (14542): #10     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:124:11)
I/flutter (14542): #11     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:85:7)
I/flutter (14542): #12     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:194:7)
I/flutter (14542): #13     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:338:14)
I/flutter (14542): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1872:7)
I/flutter (14542): #15     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (14542): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1872:7)
I/flutter (14542): #17     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (14542): #18     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:980:24)
I/flutter (14542): #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1872:7)
I/flutter (14542): #20     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (14542): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1872:7)
I/flutter (14542): #22     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (14542): #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1872:7)
I/flutter (14542): #24     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (14542): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1872:7)
I/flutter (14542): #26     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (14542): #27     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2483:26)
I/flutter (14542): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1872:7)
I/flutter (14542): #29     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (14542): #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1872:7)
I/flutter (14542): #31     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:433:15)
I/flutter (14542): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1872:7)
I/flutter (14542): #33     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (14542): #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1872:7)
I/flutter (14542): #35     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (14542): #36     RenderObject.layout (package:flutter/src/rendering/object.dart:1872:7)
I/flutter (14542): #37     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (14542): #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1872:7)
I/flutter (14542): #39     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (14542): #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1872:7)
I/flutter (14542): #41     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (14542): #42     RenderObject.layout (package:flutter/src/rendering/object.dart:1872:7)
I/flutter (14542): #43     RenderView.performLayout (package:flutter/src/rendering/view.dart:120:13)
I/flutter (14542): #44     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1749:7)
I/flutter (14542): #45     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1050:18)
I/flutter (14542): #46     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:232:19)
I/flutter (14542): #47     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:361:22)
I/flutter (14542): #48     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:170:5)
I/flutter (14542): #49     BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:685:15)
I/flutter (14542): #50     BindingBase&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:633:9)
I/flutter (14542): #51     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/rendering/binding.dart:247:20)
I/flutter (14542): #53     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:366)
I/flutter (14542): #54     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:394)
I/flutter (14542): #55     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
I/flutter (14542): (elided 3 frames from class _AssertionError and package dart:async-patch)
I/flutter (14542): 
I/flutter (14542): The following RenderObject was being processed when the exception was fired:
I/flutter (14542):   RenderFlex#806030947 relayoutBoundary=up3 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (14542):   creator: Column ← DefaultTextStyle ← AnimatedDefaultTextStyle ← _InkFeatures-[GlobalKey ink
I/flutter (14542):   renderer] ← NotificationListener<LayoutChangedNotification> ← PhysicalModel ←
I/flutter (14542):   AnimatedPhysicalModel ← Material ← LayoutId-[<_ScaffoldSlot.body>] ← CustomMultiChildLayout ←
I/flutter (14542):   DefaultTextStyle ← AnimatedDefaultTextStyle ← ⋯
I/flutter (14542):   parentData: <none> (can use size)
I/flutter (14542):   constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=603.4)
I/flutter (14542):   size: MISSING
I/flutter (14542):   direction: Axis.vertical
I/flutter (14542):   mainAxisAlignment: MainAxisAlignment.start
I/flutter (14542):   mainAxisSize: MainAxisSize.max
I/flutter (14542):   crossAxisAlignment: CrossAxisAlignment.center
I/flutter (14542):   textBaseline: null
I/flutter (14542): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (14542):   RenderPositionedBox#136573841 relayoutBoundary=up4 NEEDS-PAINT
I/flutter (14542):     RenderParagraph#797100869 relayoutBoundary=up5 NEEDS-PAINT
I/flutter (14542):   RenderFlex#512140980 relayoutBoundary=up4 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (14542):     RenderSemanticsGestureHandler#63515926 relayoutBoundary=up5 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (14542):       RenderPointerListener#823093798 relayoutBoundary=up6 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (14542):         RenderConstrainedBox#987687393 relayoutBoundary=up7 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (14542):           RenderStack#104464218 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (14542):     RenderConstrainedBox#283031430 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (14542):       RenderSemanticsGestureHandler#104138934 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (14542):         RenderPointerListener#195816242 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (14542):           RenderPadding#762296767 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (14542): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

When I restarted my app everything works fine.

There should be better messaging that hot reload doesn't work after a layout problem. Or, ideally, it should just work :)

/cc @Hixie

**Comment by Hixie** [comment]
We could add finallys in more places to maintain our state more aggressively.

**Comment by zoechi** [comment]
I wasn't able to reproduce this issue by running this code and the commenting in the commented out code

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          children: <Widget>[
            Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Text(
                  'foo text',
                ),
                // Flexible(
                  // child: 
                    TextField(),
                //)
              ],
            ),
          ],
        ),
      ),
    );
  }
}
```
```
[✓] Flutter (Channel dev, v1.1.7, on Mac OS X 10.14.1 18B75, locale en-AT)
```

**Comment by goderbauer** [comment]
I am also unable to reproduce this one. Closing.

**Comment by duzenko** [comment]
I've seen this today in 1.9
Saying you can't reproduce != actual fix.

**Comment by jnaval04** [comment]
I just encountered this in debug build on 1.9.1+hotfix.6. Is this something to worry about? The UI performs just fine. I am using CustomScrollView + SliverGrid when a hit a snag after reloading.

**Comment by Hixie** [comment]
This can definitely happen, but I don't know that there's much we can do about it. Once you've hit an exception, the app's internal state could be in any kind of undefined state. It's more luck than anything if hot reload gets you back to a good state at that point, since the whole point of hot reload is that it doesn't change the state.

**Comment by Angeloem** [comment]
@Hixie, It's crazy how hot reload got me into debugging frustrations..
I restarted the app and the bug was gone
