### ISSUE TITLE
Failed assertion: line 2741 pos 12: '!_needsLayout'

### ISSUE THREAD

**Issue by Xiaofeilong666** [flutter/flutter#97895]
```
======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
Updated layout information required for RenderIndexedSemantics#5b6fb NEEDS-LAYOUT to calculate semantics.
'package:flutter/src/rendering/object.dart':
Failed assertion: line 2741 pos 12: '!_needsLayout'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2741:12)
#3      RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2753:61)
#4      Iterable.forEach (dart:core/iterable.dart:279:35)
#5      RenderSliverVariableSizeBoxAdaptor.visitChildren (package:flutter_staggered_grid_view/src/rendering/sliver_variable_size_box_adaptor.dart:296:29)
#6      RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2830:5)
#7      RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2751:5)
#8      RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2753:61)
#9      RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3122:14)
#10     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2830:5)
#11     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2751:5)
#12     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2753:61)
#13     Iterable.forEach (dart:core/iterable.dart:279:35)
#14     RenderViewportBase.visitChildrenForSemantics (package:flutter/src/rendering/viewport.dart:222:10)
#15     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2751:5)
#16     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2753:61)
#17     RenderIgnorePointer.visitChildrenForSemantics (package:flutter/src/rendering/proxy_box.dart:3324:14)
#18     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2751:5)
#19     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2753:61)
#20     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3122:14)
#21     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2830:5)
#22     RenderSemanticsAnnotations.visitChildrenForSemantics (package:flutter/src/rendering/proxy_box.dart:4721:11)
#23     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2751:5)
#24     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2753:61)
#25     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3122:14)
#26     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2830:5)
#27     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2751:5)
#28     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2753:61)
#29     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3122:14)
#30     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2830:5)
#31     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2751:5)
#32     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2753:61)
#33     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3122:14)
#34     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2830:5)
#35     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2751:5)
#36     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2753:61)
#37     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3122:14)
#38     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2830:5)
#39     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2751:5)
#40     RenderObject._updateSemantics (package:flutter/src/rendering/object.dart:2719:41)
#41     PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1074:16)
#42     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:502:21)
#43     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#44     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#45     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
#46     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#47     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#51     _invoke (dart:ui/hooks.dart:150:10)
#52     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#53     _drawFrame (dart:ui/hooks.dart:114:31)
(elided 5 frames from class _AssertionError and dart:async)
```

**Comment by darshankawar** [comment]
@Xiaofeilong666 
Just providing error message isn't helpful. Please provide `flutter doctor -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this error.
