### ISSUE TITLE
_CastError: Null check operator used on a null value

### ISSUE THREAD

**Issue by aumeunier** [flutter/flutter#97918]
This is similar to the issue closed for inactivity here: #94726 [Issue 94726](https://github.com/flutter/flutter/issues/94726).
I may have found why and am hence opening a new bug

## Steps to Reproduce

1. Add localization to the app [following steps from doc](https://docs.flutter.dev/development/accessibility-and-localization/internationalization#loading-and-retrieving-localized-values)
2. Add .arb files in the proper directory
3. Add a file for a locale that is not valid: for example "app_mx.arb"
4. Execute `flutter run` on the code sample 

**Expected results:**
An error code indicate that the locale is invalid

**Actual results:**
Oops; flutter has exited unexpectedly: "Null check operator used on a null value".

Pubspec should contain
```yaml
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 

flutter:
  generate: true
```

## Investigations 

- Flutter doctor is fine
- Flutter analyze is fine

- Removing the incorrect locale file makes it work (even with other files), tried with several configurations

### Logs
 <summary>Logs from `flutter run` (verbose doesn't add much, see below)</summary>
<details>

Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter run

## exception

_CastError: Null check operator used on a null value

```
#0      describeLocale (package:flutter_tools/src/localizations/localizations_utils.dart:219:49)
#1      LocalizationsGenerator._generateBaseClassFile (package:flutter_tools/src/localizations/gen_l10n.dart:1113:34)
#2      LocalizationsGenerator._generateCode (package:flutter_tools/src/localizations/gen_l10n.dart:1200:46)
#3      LocalizationsGenerator.writeOutputFiles (package:flutter_tools/src/localizations/gen_l10n.dart:1275:47)
#4      generateLocalizations (package:flutter_tools/src/localizations/gen_l10n.dart:69:9)
#5      GenerateLocalizationsTarget.build (package:flutter_tools/src/build_system/targets/localizations.dart:56:5)
#6      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:839:27)
<asynchronous suspension>
#7      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:606:16)
<asynchronous suspension>
#8      generateLocalizationsSyntheticPackage (package:flutter_tools/src/dart/generate_synthetic_packages.dart:58:30)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1266:7)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
<asynchronous suspension>
#16     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#18     main (package:flutter_tools/executable.dart:94:3)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.22000.469], locale en-US)
    • Flutter version 2.8.1 at C:\dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (7 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\REMOVED\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: C:\dev\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\dev\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.64.0)
    • VS Code at C:\Users\REMOVED\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.34.0

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 97.0.4692.99
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 97.0.1072.76

• No issues found!
```

</details>

<summary>`flutter logs --verbose` (with some data removed for privacy)</summary>
<details>

```
flutter run --verbose
[  +97 ms] executing: [C:\dev\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +327 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +3 ms] 77d935af4db863f6abd0b9c31c7e6df2a13de57b
[   +2 ms] executing: [C:\dev\flutter/] git tag --points-at 77d935af4db863f6abd0b9c31c7e6df2a13de57b
[  +70 ms] Exit code 0 from: git tag --points-at 77d935af4db863f6abd0b9c31c7e6df2a13de57b
[   +1 ms] 2.8.1
[  +13 ms] executing: [C:\dev\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +50 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[   +1 ms] executing: [C:\dev\flutter/] git ls-remote --get-url origin
[  +47 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +162 ms] executing: [C:\dev\flutter/] git rev-parse --abbrev-ref HEAD
[  +52 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[ +105 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +91 ms] executing: C:\Users\REMOVED\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +78 ms] List of devices attached
           J7AXB760J242ZVV        device product:WW_X00QD model:ASUS_X00QD device:ASUS_X00QD transport_id:3
[  +10 ms] C:\Users\REMOVED\AppData\Local\Android\sdk\platform-tools\adb.exe -s J7AXB760J242ZVV shell getprop
[ +123 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +179 ms] Initializing file store
[  +11 ms] Done initializing file store
[  +51 ms] Skipping target: gen_localizations
[   +3 ms] Persisting file store
[  +10 ms] Done persisting file store
[  +12 ms] Skipping pub get: version match.
[  +66 ms] Found plugin path_provider at C:\Users\REMOVED\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider-2.0.4\
[   +8 ms] Found plugin path_provider_linux at C:\Users\REMOVED\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_linux-2.1.0\
[   +5 ms] Found plugin path_provider_macos at C:\Users\REMOVED\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_macos-2.0.2\
[   +5 ms] Found plugin path_provider_windows at C:\Users\REMOVED\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_windows-2.0.3\
[  +10 ms] Found plugin shared_preferences at C:\Users\REMOVED\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\shared_preferences-2.0.7\
[   +4 ms] Found plugin shared_preferences_linux at C:\Users\REMOVED\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\shared_preferences_linux-2.0.2\
[   +4 ms] Found plugin shared_preferences_macos at C:\Users\REMOVED\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\shared_preferences_macos-2.0.2\
[   +3 ms] Found plugin shared_preferences_web at C:\Users\REMOVED\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\shared_preferences_web-2.0.2\
[   +3 ms] Found plugin shared_preferences_windows at C:\Users\REMOVED\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\shared_preferences_windows-2.0.2\
[ +214 ms] Found plugin path_provider at C:\Users\REMOVED\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider-2.0.4\
[   +3 ms] Found plugin path_provider_linux at C:\Users\REMOVED\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_linux-2.1.0\
[   +2 ms] Found plugin path_provider_macos at C:\Users\REMOVED\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_macos-2.0.2\
[   +3 ms] Found plugin path_provider_windows at C:\Users\REMOVED\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_windows-2.0.3\
[   +6 ms] Found plugin shared_preferences at C:\Users\REMOVED\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\shared_preferences-2.0.7\
[   +3 ms] Found plugin shared_preferences_linux at C:\Users\REMOVED\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\shared_preferences_linux-2.0.2\
[   +2 ms] Found plugin shared_preferences_macos at C:\Users\REMOVED\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\shared_preferences_macos-2.0.2\
[   +4 ms] Found plugin shared_preferences_web at C:\Users\REMOVED\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\shared_preferences_web-2.0.2\
[   +2 ms] Found plugin shared_preferences_windows at C:\Users\REMOVED\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\shared_preferences_windows-2.0.2\
[  +38 ms] Generating C:\dev\REMOVED\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +98 ms] ro.hardware = qcom
[   +1 ms] Found plugin shared_preferences_macos at C:\Users\REMOVED\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\shared_preferences_macos-2.0.2\
[   +2 ms] Found plugin shared_preferences_web at C:\Users\REMOVED\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\shared_preferences_web-2.0.2\
[   +1 ms] Found plugin shared_preferences_windows at C:\Users\REMOVED\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\shared_preferences_windows-2.0.2\
[  +28 ms] gen_dart_plugin_registrant: Complete
[  +19 ms] "flutter run" took 1,452ms.

[  +15 ms] Sending crash report to Google.
[ +919 ms] Crash report sent (report ID: 5cd935afcb6613d8)
[   +2 ms] Oops; flutter has exited unexpectedly: "Null check operator used on a null value".
[  +14 ms] executing: C:\dev\Android Studio\jre\bin\java -version
[ +212 ms] Exit code 0 from: C:\dev\Android Studio\jre\bin\java -version
[        ] openjdk version "11.0.10" 2021-01-19
           OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
           OpenJDK 64-Bit Server VM (build 11.0.10+0-b96-7249189, mixed mode)
[  +18 ms] executing: C:\dev\Android Studio\jre\bin\java -version
[ +220 ms] Exit code 0 from: C:\dev\Android Studio\jre\bin\java -version
[   +1 ms] openjdk version "11.0.10" 2021-01-19
           OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
           OpenJDK 64-Bit Server VM (build 11.0.10+0-b96-7249189, mixed mode)
[   +5 ms] executing: [C:\dev\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%ar
[  +49 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%ar
[        ] 7 weeks ago
[  +63 ms] java -version
[  +70 ms] executing: C:\Users\REMOVED\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +33 ms] List of devices attached
           J7AXB760J242ZVV        device product:WW_X00QD model:ASUS_X00QD device:ASUS_X00QD transport_id:3
[+1992 ms] A crash report has been written to C:\dev\REMOVED\flutter_11.log.
[   +2 ms] This crash may already be reported. Check GitHub for similar crashes.
[   +2 ms] https://github.com/flutter/flutter/issues?q=is%3Aissue+Null+check+operator+used+on+a+null+value

[   +1 ms] To report your crash to the Flutter team, first read the guide to filing a bug.
[   +1 ms] https://flutter.dev/docs/resources/bug-reports

[   +2 ms] Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
[  +26 ms] Attempting git.io shortener:
https://github.com/flutter/flutter/issues/new?title=%5Btool_crash%5D+_CastError%3A+%28%230++++++describeLocale+%28package%3Aflutter_tools%2Fsrc%2Flocalizations%2Flocalizations_utils.dart%3A219%3A49%29%29&body=%23%23+Comman
d%0A%60%60%60%0Aflutter+run+--verbose%0A%60%60%60%0A%0A%23%23+Steps+to+Reproduce%0A1.+...%0A2.+...%0A3.+...%0A%0A%23%23+Logs%0A_CastError%3A+%28%230++++++describeLocale+%28package%3Aflutter_tools%2Fsrc%2Flocalizations%2Flo
calizations_utils.dart%3A219%3A49%29%29%0A%60%60%60%0A%230++++++describeLocale+%28package%3Aflutter_tools%2Fsrc%2Flocalizations%2Flocalizations_utils.dart%3A219%3A49%29%0A%231++++++LocalizationsGenerator._generateBaseClass
File+%28package%3Aflutter_tools%2Fsrc%2Flocalizations%2Fgen_l10n.dart%3A1113%3A34%29%0A%232++++++LocalizationsGenerator._generateCode+%28package%3Aflutter_tools%2Fsrc%2Flocalizations%2Fgen_l10n.dart%3A1200%3A46%29%0A%233++
++++LocalizationsGenerator.writeOutputFiles+%28package%3Aflutter_tools%2Fsrc%2Flocalizations%2Fgen_l10n.dart%3A1275%3A47%29%0A%234++++++generateLocalizations+%28package%3Aflutter_tools%2Fsrc%2Flocalizations%2Fgen_l10n.dart
%3A69%3A9%29%0A%235++++++GenerateLocalizationsTarget.build+%28package%3Aflutter_tools%2Fsrc%2Fbuild_system%2Ftargets%2Flocalizations.dart%3A56%3A5%29%0A%236++++++_BuildInstance._invokeInternal+%28package%3Aflutter_tools%2F
src%2Fbuild_system%2Fbuild_system.dart%3A839%3A27%29%0A%3Casynchronous+suspension%3E%0A%237++++++Future.wait.%3Canonymous+closure%3E+%28dart%3Aasync%2Ffuture.dart%29%0A%3Casynchronous+suspension%3E%0A%238++++++_BuildInstan
ce.invokeTarget+%28package%3Aflutter_tools%2Fsrc%2Fbuild_system%2Fbuild_system.dart%3A777%3A32%29%0A%3Casynchronous+suspension%3E%0A%239++++++FlutterBuildSystem.buildIncremental+%28package%3Aflutter_tools%2Fsrc%2Fbuild_sys
tem%2Fbuild_system.dart%3A680%3A16%29%0A%3Casynchronous+suspension%3E%0A%2310+++++ResidentRunner.runSourceGenerators+%28package%3Aflutter_tools%2Fsrc%2Fresident_runner.dart%3A1174%3A18%29%0A%3Casynchronous+suspension%3E%0A
%2311+++++HotRunner.run+%28package%3Aflutter_tools%2Fsrc%2Frun_hot.dart%3A374%3A7%29%0A%3Casynchronous+suspension%3E%0A%2312+++++RunCommand.runCommand+%28package%3Aflutter_tools%2Fsrc%2Fcommands%2Frun.dart%3A667%3A26%29%0A
%3Casynchronous+suspension%3E%0A%2313+++++FlutterCommand.run.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Frunner%2Fflutter_command.dart%3A1140%3A27%29%0A%3Casynchronous+suspension%3E%0A%2314+++++AppContext.ru
n.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A150%3A19%29%0A%3Casynchronous+suspension%3E%0A%2315+++++CommandRunner.runCommand+%28package%3Aargs%2Fcommand_runner.dart%3A209%3A13%29%0A%6
0%60%60%0A%60%60%60%0A%5B%E2%9C%93%5D+Flutter+%28Channel+stable%2C+2.8.1%2C+on+Microsoft+Windows+%5BVersion+10.0.22000.469%5D%2C+locale+en-US%29%0A++++%E2%80%A2+Flutter+version+2.8.1+at+C%3A%5Cdev%5Cflutter%0A++++%E2%80%A2
+Upstream+repository+https%3A%2F%2Fgithub.com%2Fflutter%2Fflutter.git%0A++++%E2%80%A2+Framework+revision+77d935af4d+%287+weeks+ago%29%2C+2021-12-16+08%3A37%3A33+-0800%0A++++%E2%80%A2+Engine+revision+890a5fca2e%0A++++%E2%80
%A2+Dart+version+2.15.1%0A%0A%5B%E2%9C%93%5D+Android+toolchain+-+develop+for+Android+devices+%28Android+SDK+version+32.0.0%29%0A++++%E2%80%A2+Android+SDK+at+C%3A%5CUsers%5CREMOVED%5CAppData%5CLocal%5CAndroid%5Csdk%0A++++%E2%
80%A2+Platform+android-32%2C+build-tools+32.0.0%0A++++%E2%80%A2+Java+binary+at%3A+C%3A%5Cdev%5CAndroid+Studio%5Cjre%5Cbin%5Cjava%0A++++%E2%80%A2+Java+version+OpenJDK+Runtime+Environment+%28build+11.0.10%2B0-b96-7249189%29%
0D%0A++++%E2%80%A2+All+Android+licenses+accepted.%0A%0A%5B%E2%9C%93%5D+Chrome+-+develop+for+the+web%0A++++%E2%80%A2+Chrome+at+C%3A%5CProgram+Files%5CGoogle%5CChrome%5CApplication%5Cchrome.exe%0A%0A%5B%E2%9C%93%5D+Android+S
tudio+%28version+2020.3%29%0A++++%E2%80%A2+Android+Studio+at+C%3A%5Cdev%5CAndroid+Studio%0A++++%E2%80%A2+Flutter+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F9212-flut
ter%0A++++%E2%80%A2+Dart+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F6351-dart%0A++++%E2%80%A2+Java+version+OpenJDK+Runtime+Environment+%28build+11.0.10%2B0-b96-72491
89%29%0D%0A%0A%5B%E2%9C%93%5D+VS+Code+%28version+1.64.0%29%0A++++%E2%80%A2+VS+Code+at+C%3A%5CUsers%5CREMOVED%5CAppData%5CLocal%5CPrograms%5CMicrosoft+VS+Code%0A++++%E2%80%A2+Flutter+extension+version+3.34.0%0A%0A%5B%E2%9C%93
%5D+Connected+device+%283+available%29%0A++++%E2%80%A2+ASUS+X00QD+%28mobile%29+%E2%80%A2+J7AXB760J242ZVV+%E2%80%A2+android-arm64++%E2%80%A2+Android+9+%28API+28%29%0A++++%E2%80%A2+Chrome+%28web%29++++++++%E2%80%A2+chrome+++
+++++++%E2%80%A2+web-javascript+%E2%80%A2+Google+Chrome+97.0.4692.99%0A++++%E2%80%A2+Edge+%28web%29++++++++++%E2%80%A2+edge++++++++++++%E2%80%A2+web-javascript+%E2%80%A2+Microsoft+Edge+98.0.1108.43%0A%0A%E2%80%A2+No+issues
+found%21%0A%0A%60%60%60%0A%0A%23%23+Flutter+Application+Metadata%0A%2A%2AType%2A%2A%3A+app%0A%2A%2AVersion%2A%2A%3A+0.0.1%2B1%0A%2A%2AMaterial%2A%2A%3A+true%0A%2A%2AAndroid+X%2A%2A%3A+false%0A%2A%2AModule%2A%2A%3A+false%0
A%2A%2APlugin%2A%2A%3A+false%0A%2A%2AAndroid+package%2A%2A%3A+null%0A%2A%2AiOS+bundle+identifier%2A%2A%3A+null%0A%2A%2ACreation+channel%2A%2A%3A+unknown%0A%2A%2ACreation+framework+version%2A%2A%3A+f4abaa0735eba4dfd8f33f733
63911d63931fe03%0A%23%23%23+Plugins%0Apath_provider-2.0.4%0Apath_provider_linux-2.1.0%0Apath_provider_macos-2.0.2%0Apath_provider_windows-2.0.3%0Ashared_preferences-2.0.7%0Ashared_preferences_linux-2.0.2%0Ashared_preferenc
es_macos-2.0.2%0Ashared_preferences_web-2.0.2%0Ashared_preferences_windows-2.0.2%0A%0A&labels=tool%2Csevere%3A+crash
[ +346 ms] Failed to shorten GitHub template URL. Server responded with HTTP status code 422
[   +1 ms]
https://github.com/flutter/flutter/issues/new?title=%5Btool_crash%5D+_CastError%3A+%28%230++++++describeLocale+%28package%3Aflutter_tools%2Fsrc%2Flocalizations%2Flocalizations_utils.dart%3A219%3A49%29%29&body=%23%23+Comman
d%0A%60%60%60%0Aflutter+run+--verbose%0A%60%60%60%0A%0A%23%23+Steps+to+Reproduce%0A1.+...%0A2.+...%0A3.+...%0A%0A%23%23+Logs%0A_CastError%3A+%28%230++++++describeLocale+%28package%3Aflutter_tools%2Fsrc%2Flocalizations%2Flo
calizations_utils.dart%3A219%3A49%29%29%0A%60%60%60%0A%230++++++describeLocale+%28package%3Aflutter_tools%2Fsrc%2Flocalizations%2Flocalizations_utils.dart%3A219%3A49%29%0A%231++++++LocalizationsGenerator._generateBaseClass
File+%28package%3Aflutter_tools%2Fsrc%2Flocalizations%2Fgen_l10n.dart%3A1113%3A34%29%0A%232++++++LocalizationsGenerator._generateCode+%28package%3Aflutter_tools%2Fsrc%2Flocalizations%2Fgen_l10n.dart%3A1200%3A46%29%0A%233++
++++LocalizationsGenerator.writeOutputFiles+%28package%3Aflutter_tools%2Fsrc%2Flocalizations%2Fgen_l10n.dart%3A1275%3A47%29%0A%234++++++generateLocalizations+%28package%3Aflutter_tools%2Fsrc%2Flocalizations%2Fgen_l10n.dart
%3A69%3A9%29%0A%235++++++GenerateLocalizationsTarget.build+%28package%3Aflutter_tools%2Fsrc%2Fbuild_system%2Ftargets%2Flocalizations.dart%3A56%3A5%29%0A%236++++++_BuildInstance._invokeInternal+%28package%3Aflutter_tools%2F
src%2Fbuild_system%2Fbuild_system.dart%3A839%3A27%29%0A%3Casynchronous+suspension%3E%0A%237++++++Future.wait.%3Canonymous+closure%3E+%28dart%3Aasync%2Ffuture.dart%29%0A%3Casynchronous+suspension%3E%0A%238++++++_BuildInstan
ce.invokeTarget+%28package%3Aflutter_tools%2Fsrc%2Fbuild_system%2Fbuild_system.dart%3A777%3A32%29%0A%3Casynchronous+suspension%3E%0A%239++++++FlutterBuildSystem.buildIncremental+%28package%3Aflutter_tools%2Fsrc%2Fbuild_sys
tem%2Fbuild_system.dart%3A680%3A16%29%0A%3Casynchronous+suspension%3E%0A%2310+++++ResidentRunner.runSourceGenerators+%28package%3Aflutter_tools%2Fsrc%2Fresident_runner.dart%3A1174%3A18%29%0A%3Casynchronous+suspension%3E%0A
%2311+++++HotRunner.run+%28package%3Aflutter_tools%2Fsrc%2Frun_hot.dart%3A374%3A7%29%0A%3Casynchronous+suspension%3E%0A%2312+++++RunCommand.runCommand+%28package%3Aflutter_tools%2Fsrc%2Fcommands%2Frun.dart%3A667%3A26%29%0A
%3Casynchronous+suspension%3E%0A%2313+++++FlutterCommand.run.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Frunner%2Fflutter_command.dart%3A1140%3A27%29%0A%3Casynchronous+suspension%3E%0A%2314+++++AppContext.ru
n.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A150%3A19%29%0A%3Casynchronous+suspension%3E%0A%2315+++++CommandRunner.runCommand+%28package%3Aargs%2Fcommand_runner.dart%3A209%3A13%29%0A%6
0%60%60%0A%60%60%60%0A%5B%E2%9C%93%5D+Flutter+%28Channel+stable%2C+2.8.1%2C+on+Microsoft+Windows+%5BVersion+10.0.22000.469%5D%2C+locale+en-US%29%0A++++%E2%80%A2+Flutter+version+2.8.1+at+C%3A%5Cdev%5Cflutter%0A++++%E2%80%A2
+Upstream+repository+https%3A%2F%2Fgithub.com%2Fflutter%2Fflutter.git%0A++++%E2%80%A2+Framework+revision+77d935af4d+%287+weeks+ago%29%2C+2021-12-16+08%3A37%3A33+-0800%0A++++%E2%80%A2+Engine+revision+890a5fca2e%0A++++%E2%80
%A2+Dart+version+2.15.1%0A%0A%5B%E2%9C%93%5D+Android+toolchain+-+develop+for+Android+devices+%28Android+SDK+version+32.0.0%29%0A

[  +14 ms] ensureAnalyticsSent: 1ms
[   +2 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1
```
</details>

**Comment by maheshmnj** [comment]
Hi @aumeunier, Thanks for filing the issue. Please share the output of `flutter doctor -v` to investigate this further.

Thanks

**Comment by maheshmnj** [comment]
HI @aumeunier, Thanks for filing the issue. You seem to be on an older version of flutter. Could you please try upgrading to `stable 2.10`  and see if the issue persists?

Thanks
