### ISSUE TITLE
[google_maps_flutter_web] "Maps cannot be retrieved before calling buildView!"

### ISSUE THREAD

**Issue by despotovski01** [flutter/flutter#97913]
Hello,

I have the following problem with the google_maps_flutter_web plugin:
When I dispose the GoogleMapController in the widget dispose() method, I get the following error afterwards:

`google_maps_flutter_web-0.3.2+1/lib/src/google_maps_flutter_web.dart:31:12
controller != null
"Maps cannot be retrieved before calling buildView!"
    at Object.throw_ [as throw] (http://localhost:55259/dart_sdk.js:5067:11)
    at Object.assertFailed (http://localhost:55259/dart_sdk.js:4992:15)
    at google_maps_flutter_web.GoogleMapsPlugin.new.[_map] (http://localhost:55259/packages/google_maps_flutter_web/src/types.dart.lib.js:239:39)
    at google_maps_flutter_web.GoogleMapsPlugin.new.dispose (http://localhost:55259/packages/google_maps_flutter_web/src/types.dart.lib.js:396:17)
    at google_maps_flutter.GoogleMapController.__.dispose (http://localhost:55259/packages/google_maps_flutter/google_maps_flutter.dart.lib.js:259:71)
    at google_maps_flutter._GoogleMapState.new.dispose$ (http://localhost:55259/packages/google_maps_flutter/google_maps_flutter.dart.lib.js:794:20)
    at dispose$.next (<anonymous>)
    at http://localhost:55259/dart_sdk.js:40571:33
    at _RootZone.runUnary (http://localhost:55259/dart_sdk.js:40441:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:55259/dart_sdk.js:35363:29)
    at handleValueCallback (http://localhost:55259/dart_sdk.js:35931:49)
    at Function._propagateToListeners (http://localhost:55259/dart_sdk.js:35969:17)
    at async._AsyncCallbackEntry.new.callback (http://localhost:55259/dart_sdk.js:35698:27)
    at Object._microtaskLoop (http://localhost:55259/dart_sdk.js:40708:13)
    at _startMicrotaskLoop (http://localhost:55259/dart_sdk.js:40714:13)
    at http://localhost:55259/dart_sdk.js:36191:9` 

Here's my code:
```dart
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

typedef OnPositionUpdated = void Function(LatLng newPosition);

class MapLocationPicker extends StatefulWidget {

  final LatLng? initialPosition;
  final OnPositionUpdated? onPositionUpdated;
  final bool readOnly;

  const MapLocationPicker({
    this.initialPosition,
    this.onPositionUpdated,
    this.readOnly = true,
    Key? key,
  }) : super(key: key);

  @override
  State<StatefulWidget> createState() => _MapLocationPickerState();

}

class _MapLocationPickerState extends State<MapLocationPicker> {

  final String _pickedLocationMarkerId = "pickedLocation";

  final _defaultPosition = const CameraPosition(
    target: LatLng(41.99, 21.42),
    zoom: 7.2373,
  );

  final double _defaultPickedLocationZoom = 14.4746;

  late GoogleMapController _mapController;
  bool _isMapCreated = false;

  LatLng? _position;

  @override
  void initState() {
    super.initState();

    _position = initialPosition;
  }


  @override
  void dispose() {
    if (_isMapCreated) {
      _mapController.dispose();
    }

    super.dispose();
  }

  void _updatePosition(LatLng newPosition) {
    if (readOnly) {
      return;
    }

    onPositionUpdated?.call(newPosition);

    if (mounted) {
      setState(() {
        _position = newPosition;
      });
    }
  }

  Set<Marker> _getMarkers() {
    return {
      if (_position != null)
        Marker(
          draggable: !readOnly,
          onDragEnd: _updatePosition,
          markerId: MarkerId(_pickedLocationMarkerId),
          position: _position!,
          infoWindow: InfoWindow(
          title: "${_position!.latitude}, ${_position!.longitude}",
          ),
        ),
      };
  }

  @override
  Widget build(BuildContext context) {
    return GoogleMap(
      initialCameraPosition: _defaultPosition,
      onMapCreated: (GoogleMapController controller) {
        if (mounted) {
          setState(() {
            _mapController = controller;
            _isMapCreated = true;

            if (_position != null) {
              controller.animateCamera(CameraUpdate.newCameraPosition(
                CameraPosition(
                  target: _position!,
                  zoom: _defaultPickedLocationZoom,
                ),
              ));
            }
          });
        }
      },
      markers: _getMarkers(),
      onTap: (LatLng? location) {
        if (!readOnly && _position == null && location != null) {
          _updatePosition(location);
        }
      },
    );
  }

  LatLng? get initialPosition => widget.initialPosition;
  OnPositionUpdated? get onPositionUpdated => widget.onPositionUpdated;
  bool get readOnly => widget.readOnly;

}
```

From what I see, the JavaScript part of the library tries to dispose the map after it had already been disposed.
Any help would be greatly appreciated!

Flutter version: 2.10.0
Dart version: 2.16.0
DevTools version: 2.9.2

Testing with Chrome on Windows 11.

**Comment by darshankawar** [comment]
@despotovski01 
I although didn't try on window, but running your code sample on chrome + mac didn't throw me any error. Can you provide exact steps to replicate ?

**Comment by despotovski01** [comment]
> @despotovski01 I although didn't try on window, but running your code sample on chrome + mac didn't throw me any error. Can you provide exact steps to replicate ?

The widget is a child of a StatefulWidget, that's a child of a TabBar. This issues occurred when navigating between tabs back-and-forth.

**Comment by piratejoe** [comment]
I have the same error running 2.8.1 on Chrome / Mac M1

**Comment by despotovski01** [comment]
> I have the same error running 2.8.1 on Chrome / Mac M1 when I try to dispose the controller - so I don't. This thread covers it mostly (but doesn't explain why there is a public dispose method for the controller if we are not supposed to call it): #74345

I tried that, but I started getting the following error:
```
Error: Bad state: Cannot add new events after calling close
    at Object.throw_ [as throw] (http://localhost:49687/dart_sdk.js:5067:11)
    at _AsyncBroadcastStreamController.new.add (http://localhost:49687/dart_sdk.js:34356:44)
    at http://localhost:49687/packages/google_maps_flutter_web/src/types.dart.lib.js:567:35
    at _RootZone.runUnaryGuarded (http://localhost:49687/dart_sdk.js:40378:11)
    at _ControllerSubscription.new.[_sendData] (http://localhost:49687/dart_sdk.js:33906:22)
    at _DelayedData.new.perform (http://localhost:49687/dart_sdk.js:37377:28)
    at _StreamImplEvents.new.handleNext (http://localhost:49687/dart_sdk.js:37487:15)
    at async._AsyncCallbackEntry.new.callback (http://localhost:49687/dart_sdk.js:37235:16)
    at Object._microtaskLoop (http://localhost:49687/dart_sdk.js:40708:13)
    at _startMicrotaskLoop (http://localhost:49687/dart_sdk.js:40714:13)
    at http://localhost:49687/dart_sdk.js:36191:9
Error: Bad state: Cannot add new events after calling close
    at Object.throw_ [as throw] (http://localhost:49687/dart_sdk.js:5067:11)
    at _AsyncBroadcastStreamController.new.add (http://localhost:49687/dart_sdk.js:34356:44)
    at http://localhost:49687/packages/google_maps_flutter_web/src/types.dart.lib.js:573:33
    at _RootZone.runUnaryGuarded (http://localhost:49687/dart_sdk.js:40378:11)
    at _ControllerSubscription.new.[_sendData] (http://localhost:49687/dart_sdk.js:33906:22)
    at _DelayedData.new.perform (http://localhost:49687/dart_sdk.js:37377:28)
    at _StreamImplEvents.new.handleNext (http://localhost:49687/dart_sdk.js:37487:15)
    at async._AsyncCallbackEntry.new.callback (http://localhost:49687/dart_sdk.js:37235:16)
    at Object._microtaskLoop (http://localhost:49687/dart_sdk.js:40708:13)
    at _startMicrotaskLoop (http://localhost:49687/dart_sdk.js:40714:13)
    at http://localhost:49687/dart_sdk.js:36191:9
```

**Comment by darshankawar** [comment]
> The widget is a child of a StatefulWidget, that's a child of a TabBar. This issues occurred when navigating between tabs back-and-forth.

I don't see any tabs to navigate back and forth after running your code sample. 

<img width="1201" alt="Screenshot 2022-02-14 at 11 34 08 AM" src="https://user-images.githubusercontent.com/67046386/153808986-65f57d16-3cdf-49ac-8ed8-808dcf6e0818.png">

**Comment by despotovski01** [comment]
> > The widget is a child of a StatefulWidget, that's a child of a TabBar. This issues occurred when navigating between tabs back-and-forth.
> 
> I don't see any tabs to navigate back and forth after running your code sample.
> 
> <img alt="Screenshot 2022-02-14 at 11 34 08 AM" width="1201" src="https://user-images.githubusercontent.com/67046386/153808986-65f57d16-3cdf-49ac-8ed8-808dcf6e0818.png">
Yes, I have only included my map wrapper widget.

**Comment by darshankawar** [comment]
I still am not sure how to replicate the error you are getting using the code sample provided. Can you check the plugin [example](https://github.com/flutter/plugins/tree/master/packages/google_maps_flutter/google_maps_flutter/example) and see if using it, you still get same behavior or not ? Running on web, you will also need to add https://pub.dev/packages/google_maps_flutter_web explicitly.
