### ISSUE TITLE
[tool_crash] NoSuchMethodError: NoSuchMethodError: The method 'cancel' was called on null.Receiver: nullTried calling: cancel()

### ISSUE THREAD

**Issue by wwwuzhongjian** [flutter/flutter#97936]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
NoSuchMethodError: NoSuchMethodError: The method 'cancel' was called on null.
Receiver: null
Tried calling: cancel()
```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      AnsiSpinner.finish (package:flutter_tools/src/base/logger.dart:969:11)
#2      Status.stop (package:flutter_tools/src/base/logger.dart:750:5)
#3      AnsiStatus.stop (package:flutter_tools/src/base/logger.dart:1051:11)
#4      ArtifactUpdater._downloadArchive (package:flutter_tools/src/cache.dart:1506:16)
<asynchronous suspension>
#5      ArtifactUpdater.downloadZipArchive (package:flutter_tools/src/cache.dart:1442:12)
#6      EngineCachedArtifact.updateInner (package:flutter_tools/src/cache.dart:717:29)
<asynchronous suspension>
#7      CachedArtifact.update (package:flutter_tools/src/cache.dart:573:11)
#8      Cache.updateAll (package:flutter_tools/src/cache.dart:452:24)
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:925:27)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:831:33)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#13     _rootRun (dart:async/zone.dart:1190:13)
#14     _CustomZone.run (dart:async/zone.dart:1093:19)
#15     _runZoned (dart:async/zone.dart:1630:10)
#16     runZoned (dart:async/zone.dart:1550:10)
#17     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#18     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:820:20)
#19     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#20     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:335:21)
```
```
[✓] Flutter (Channel flutter-1.22-candidate.13, 1.22.0-10.0.pre.150, on macOS 12.1 21C52, locale zh-Hans-CN)
    • Flutter version 1.22.0-10.0.pre.150 at /Users/zhongjian/flutter
    • Framework revision 5a0e097838 (1 year, 5 months ago), 2020-09-11 21:12:03 -0400
    • Engine revision 545b1b9fcd
    • Dart version 2.10.0 (build 2.10.0-117.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✗] Android toolchain - develop for Android devices
    ✗ ANDROID_HOME = /Users/zhongjian/Library/Android/sdk
      but Android SDK not found at this location.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.64.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (1 available)
    • iPhone 13 Pro Max (mobile) • F7EF3B32-70EE-446C-842E-EB254BE86C80 • ios • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: 34dbee66de8b2ef176ec39d80c3eca5feb70572e

**Comment by jeydi243** [comment]
Hi @wwwuzhongjian ! Thank you for your issue. But please can you provide the link to the project or Can you can explain your problem ?
You didn't provide any text.

**Comment by darshankawar** [comment]
> Channel flutter-1.22-candidate.13,

You are on obsolete version of Flutter. Please upgrade to latest stable (2.10.0) which should have already fixed this issue.
Closing for now. If after upgrade, you still see this issue, write in comments and I'll reopen it.
