### ISSUE TITLE
The 'Pods-Runner' target has frameworks with conflicting names flutter

### ISSUE THREAD

**Issue by Aashu008** [flutter/flutter#98102]
When I try to run pod install this error is thrown in my terminal.

```
pod install
Analyzing dependencies
Adding spec repo `trunk` with CDN `https://cdn.cocoapods.org/`
Downloading dependencies
Installing DKImagePickerController (4.3.2)
Installing DKPhotoGallery (0.0.17)
Installing Flutter (1.0.0)
Installing SDWebImage (5.12.2)
Installing SwiftyGif (5.4.2)
Installing ffmpeg-kit-ios-https (4.5.1)
Installing ffmpeg_kit_flutter (4.5.1)
Installing file_picker (0.0.1)
Installing image_picker (0.0.1)
Installing mobile-ffmpeg-full (4.4)
Installing permission_handler (5.1.0+2)
[!] The 'Pods-Runner' target has frameworks with conflicting names: libavcodec.xcframework, libavdevice.xcframework, libavfilter.xcframework, libavformat.xcframework, libavutil.xcframework, libswresample.xcframework, and libswscale.xcframework.
```

Here's what my podfile looks like:

  

```
platform :ios, '13.0'
  pod 'mobile-ffmpeg-full', '~> 4.4'

  #CocoaPods analytics sends network stats synchronously affecting flutter build latency.
  ENV['COCOAPODS_DISABLE_STATS'] = 'true'

  project 'Runner', {
   'Debug' => :debug,
   'Profile' => :release,
   'Release' => :release,
  }

  def flutter_root
    generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
    unless File.exist?(generated_xcode_build_settings_path)
      raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub 
  get is executed first"
    end

    File.foreach(generated_xcode_build_settings_path) do |line|
      matches = line.match(/FLUTTER_ROOT\=(.*)/)
      return matches[1].strip if matches
    end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

#"fork" of method flutter_install_plugin_pods (in fluttertools podhelpers.rb) to get lts version of ffmpeg
  def flutter_install_plugin_pods(application_path = nil, relative_symlink_dir, platform)
    # defined_in_file is set by CocoaPods and is a Pathname to the Podfile.
    application_path ||= File.dirname(defined_in_file.realpath) if self.respond_to?(:defined_in_file)
    raise 'Could not find application path' unless application_path

    # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
    # referring to absolute paths on developers' machines.

    symlink_dir = File.expand_path(relative_symlink_dir, application_path)
    system('rm', '-rf', symlink_dir) # Avoid the complication of dependencies like FileUtils.

    symlink_plugins_dir = File.expand_path('plugins', symlink_dir)
    system('mkdir', '-p', symlink_plugins_dir)

    plugins_file = File.join(application_path, '..', '.flutter-plugins-dependencies')
    plugin_pods = flutter_parse_plugins_file(plugins_file, platform)
    plugin_pods.each do |plugin_hash|
      plugin_name = plugin_hash['name']
      plugin_path = plugin_hash['path']
      if (plugin_name && plugin_path)
        symlink = File.join(symlink_plugins_dir, plugin_name)
        File.symlink(plugin_path, symlink)

        if plugin_name == 'flutter_ffmpeg'
          pod 'flutter_ffmpeg/videomaker', :path => File.join(relative_symlink_dir, 'plugins', plugin_name, platform)
        else
          pod plugin_name, :path => File.join(relative_symlink_dir, 'plugins', plugin_name, platform)
        end
      end
    end
  end

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end

```

XCODE Version: 13.1
OS Version: 12.0.1  MacOS Monterey

Flutter Doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.1, on macOS 12.0.1 21A559 darwin-arm, locale en-IN)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] Connected device (2 available)

```

PS: Most of applications after adding dependencies stop running on my simulator.

**Comment by Aashu008** [comment]
Even after deleting the podfile and running flutter clean followed by flutter pub get at the root folder and running the app from the android studio I get this error:

Launching lib/main.dart on iPhone 12 in debug mode...
Warning: CocoaPods not installed. Skipping pod install.
  CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
  Without CocoaPods, plugins will not work on iOS or macOS.
  For more info, see https://flutter.dev/platform-plugins
To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

CocoaPods not installed or not in valid state.
Error launching application on iPhone 12.

**Comment by darshankawar** [comment]
> [!] The 'Pods-Runner' target has frameworks with conflicting names:

This could be related with one of third party plugin / pod that you are using in your project. Check this similar issue reported and it was due to a third party plugin: https://github.com/flutter/flutter/issues/76602#issuecomment-785015497.



> Warning: CocoaPods not installed. Skipping pod install.
>   CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
>   Without CocoaPods, plugins will not work on iOS or macOS.

Regarding this, are you using Android Studio BumbleBee version ? If so, then you are hitting https://github.com/flutter/flutter/issues/97251.

**Comment by Aashu008** [comment]
Yes, I use AS BB. I looked at the tickets, and followed what #76602 said and the other tickets too. I am still having the issue. I removed the pod files too and run `flutter pub get` but I got a new issue.
 
```
Launching lib/main.dart on iPhone 12 in debug mode...
Running pod install...                                           1,625ms
CocoaPods' output:
↳
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because
      checking is only performed in repo update

Error output from CocoaPods:
↳
        WARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
        Consider adding the following to ~/.profile:

        export LANG=en_US.UTF-8
        
    /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/unicode
    _normalize/normalize.rb:141:in `normalize': Unicode Normalization not appropriate
    for ASCII-8BIT (Encoding::CompatibilityError)
        from
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/config.rb:166:in
        `unicode_normalize'
        from
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/config.rb:166:in
        `installation_root'
        from
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/config.rb:226:in
        `podfile_path'
        from
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface/erro
        r_report.rb:105:in `markdown_podfile'
        from
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface/erro
        r_report.rb:30:in `report'
        from
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:66:in
        `report_error'
        from /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:396:in
        `handle_exception'
        from /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:337:in
        `rescue in run'
        from /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:324:in
        `run'
        from
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in
        `run'
        from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top
        (required)>'
        from /usr/local/bin/pod:23:in `load'
        from /usr/local/bin/pod:23:in `<main>'
    /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/unicode
    _normalize/normalize.rb:141:in `normalize': Unicode Normalization not appropriate
    for ASCII-8BIT (Encoding::CompatibilityError)
        from
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/config.rb:166:in
        `unicode_normalize'
        from
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/config.rb:166:in
        `installation_root'
        from
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/config.rb:226:in
        `podfile_path'
        from
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/config.rb:205:in
        `podfile'
        from
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:160:in
        `verify_podfile_exists!'
        from
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command/install.rb:
        46:in `run'
        from /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in
        `run'
        from
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in
        `run'
        from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top
        (required)>'
        from /usr/local/bin/pod:23:in `load'
        from /usr/local/bin/pod:23:in `<main>'

Error running pod install
Error launching application on iPhone 12.
```

**Comment by darshankawar** [comment]
> Unicode Normalization not appropriate
>     for ASCII-8BIT (Encoding::CompatibilityError)

This seems to be related to cocoapods and not with Flutter, so you can file this in dedicated repo or ask about solution on it on support channels like StackOverflow. Here is similar [issue](https://stackoverflow.com/questions/68809929/unicode-normalization-not-appropriate-for-ascii-8bit), check if that helps to resolve.

Closing from here as not a Flutter issue.
