### ISSUE TITLE
[Animation] AnimationController.dispose() triggers assert error "Looking up a deactivated widget's ancestor is unsafe."

### ISSUE THREAD

**Issue by Robbendebiene** [flutter/flutter#98104]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Tap the blue area to trigger the widget dispose via animated switcher

**Expected results:**
I would assume that calling `dispose` on an animation controller inside a widget's `dispose` function should work.
This problem did not occur in previous versions of Flutter (before 2.10).

**Actual results:** Exception is thrown: "Looking up a deactivated widget's ancestor is unsafe." on Android. (I don't get this error on DartPad)

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

Future <void> main() async {
  runApp(const MyApp());
}


class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  var _active = true;

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () => setState(() {
         _active = !_active;
      }),
      child: AnimatedSwitcher(
        duration: const Duration(milliseconds: 300),
        child: _active ? const WidgetWithAnimationControllerDispose() : null,
      )
    );
  }
}


class WidgetWithAnimationControllerDispose extends StatefulWidget {
  const WidgetWithAnimationControllerDispose({Key? key}) : super(key: key);

  @override
  _ListInputState createState() => _ListInputState();
}

class _ListInputState extends State<WidgetWithAnimationControllerDispose> with SingleTickerProviderStateMixin {
  late final _controller = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 800),
      reverseDuration: const Duration(milliseconds: 500));

  @override
  Widget build(BuildContext context) {
    return Container(
      color: Colors.blueAccent,
    );
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
                    The following assertion was thrown while finalizing the widget tree:
                    Looking up a deactivated widget's ancestor is unsafe.
                    At this point the state of the widget's element tree is no longer stable.
                    To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by
                    calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.
                    
                    When the exception was thrown, this was the stack:
                    #0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:4153:9)
                    #1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:4167:6)
                    #2      Element.getElementForInheritedWidgetOfExactType (package:flutter/src/widgets/framework.dart:4193:12)
                    #3      TickerMode.getNotifier (package:flutter/src/widgets/ticker_provider.dart:96:50)
                    #4      SingleTickerProviderStateMixin._updateTickerModeNotifier (package:flutter/src/widgets/ticker_provider.dart:246:56)
                    #5      SingleTickerProviderStateMixin.createTicker (package:flutter/src/widgets/ticker_provider.dart:199:5)
                    #6      new AnimationController (package:flutter/src/animation/animation_controller.dart:246:21)
                    #7      _ListInputState._controller (package:bug/main.dart:41:28)
                    #8      _ListInputState._controller (package:bug/main.dart)
                    #9      _ListInputState.dispose (package:bug/main.dart:55:5)
                    #10     StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4983:11)
                    #11     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1926:13)
                    #12     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
                    #13     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6271:14)
                    #14     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
                    #15     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
                    #16     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
                    #17     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
                    #18     ListIterable.forEach (dart:_internal/iterable.dart:39:13)
                    #19     _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:1935:25)
                    #20     BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2519:15)
                    #21     BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2932:7)
                    #22     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:884:19)
                    #23     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
                    #24     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
                    #25     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
                    #26     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:995:5)
                    #30     _invoke (dart:ui/hooks.dart:151:10)
                    #31     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
                    #32     _drawFrame (dart:ui/hooks.dart:115:31)
                    (elided 3 frames from dart:async)
                    ════════════════════════════════════════════════════════════════════════════════════════════════════

```

```
```

```
[✓] Flutter (Channel stable, 2.10.0, on Fedora Linux 35 (Workstation Edition) 5.15.18-200.fc35.x86_64, locale de_DE.UTF-8)
    • Flutter version 2.10.0 at /home/robin/Toolkits/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f105a6ca7 (vor 7 Tagen), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/robin/Toolkits/android
    • Platform android-31, build-tools 29.0.2
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment 18.9 (build 11.0.14+9)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/lib64/chromium-browser/chromium-browser

[✓] Linux toolchain - develop for Linux desktop
    • clang version 13.0.0 (Fedora 13.0.0-3.fc35)
    • cmake version 3.22.2
    • ninja version 1.10.2
    • pkg-config version 1.8.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Linux (desktop)                    • linux         • linux-x64      • Fedora Linux 35 (Workstation Edition) 5.15.18-200.fc35.x86_64
    • Chrome (web)                       • chrome        • web-javascript • Chromium 96.0.4664.110 Fedora Project

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

</details>

**Comment by maheshmnj** [comment]
Hi @Robbendebiene, Thanks for filing the issue. I can reproduce the issue on stable and the master channel and works fine on the `stable 2.8.1`

### Steps to reproduce
- run the code sample in original post
- tap on the screen

<details>
<summary>logs</summary>

```
Could not load custom device from config index 0: Expected enabled to be a boolean.
Running "flutter pub get" in counter...
Launching lib/main.dart on iPhone 12 Pro in debug mode...
Xcode build done.                                           36.5s
Connecting to VM Service at ws://127.0.0.1:52222/PmYOtQS21Ig=/ws

════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
Looking up a deactivated widget's ancestor is unsafe.

At this point the state of the widget's element tree is no longer stable.

To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.

When the exception was thrown, this was the stack
#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure>
#1      Element._debugCheckStateIsActiveForAncestorLookup
#2      Element.getElementForInheritedWidgetOfExactType
#3      TickerMode.getNotifier
#4      SingleTickerProviderStateMixin._updateTickerModeNotifier
#5      SingleTickerProviderStateMixin.createTicker
#6      new AnimationController
#7      _ListInputState._controller
#8      _ListInputState._controller (package:counter/main.dart)
#9      _ListInputState.dispose
#10     StatefulElement.unmount
#11     _InactiveElements._unmount
#12     _InactiveElements._unmount.<anonymous closure>
#13     SingleChildRenderObjectElement.visitChildren
#14     _InactiveElements._unmount
#15     _InactiveElements._unmount.<anonymous closure>
#16     ComponentElement.visitChildren
#17     _InactiveElements._unmount
#18     ListIterable.forEach (dart:_internal/iterable.dart:39:13)
#19     _InactiveElements._unmountAll
#20     BuildOwner.lockState
#21     BuildOwner.finalizeTree
#22     WidgetsBinding.drawFrame
#23     RendererBinding._handlePersistentFrameCallback
#24     SchedulerBinding._invokeFrameCallback
#25     SchedulerBinding.handleDrawFrame
#26     SchedulerBinding._handleDrawFrame
#30     _invoke (dart:ui/hooks.dart:151:10)
#31     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#32     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
════════════════════════════════════════════════════════════════════════════════

```
</details>


<details>
<summary>flutter doctor -v (stable 2.8.1)</summary>

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.8.1 at /Users/mahesh/Documents/flutter_beta
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (8 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 14F40EC6-3B73-469A-A1C0-8CF0B152290F • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.1 21C52
      darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 98.0.4758.80

• No issues found!
```
</details>


<details>
<summary>flutter doctor -v (stable 2.10.0)/master(2.11.0)</summary>

```
[✓] Flutter (Channel stable, 2.10.0, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.10.0 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f105a6ca7 (6 days ago), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 14F40EC6-3B73-469A-A1C0-8CF0B152290F • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.1 21C52
      darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 2.11.0-0.0.pre.452, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.11.0-0.0.pre.452 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba01ec8faa (2 days ago), 2022-02-05 22:05:18 -0500
    • Engine revision 0712096899
    • Dart version 2.17.0 (build 2.17.0-85.0.dev)
    • DevTools version 2.10.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 14F40EC6-3B73-469A-A1C0-8CF0B152290F • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.1 21C52
      darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by goderbauer** [comment]
The bug is in your code.

Since `_controller` is marked `late` and the first time `_controller` is accessed is in the `dispose` method, the `AnimationController` is actually created during `dispose` (and then of course disposed right away). Instantiating an AnimationController with a disposed TickerProvider is not allowed (and also doesn't make much sense). That's why you see the crash.

Either use the `_controller` variable before dispose so it is initialized when dispose is called. Or mark the variable as nullable and instantiate the controller in `initState`.
