### ISSUE TITLE
[Camera] GeneratedPluginRegistrant.m: fatal error: module 'camera' not found on IOS 10

### ISSUE THREAD

**Issue by M123-dev** [flutter/flutter#98139]
## Steps to Reproduce

1. Create a new flutter project (With both target and minimum iOS version 10.0)
2. Add `camera` as dependencies
3. `flutter build ios --release --no-codesign`

**Expected results:** 

It should build

**Actual results:** 

```
[...] fatal error: module 'camera' not found
    @import camera;
```

https://github.com/openfoodfacts/smooth-app/runs/5127814775?check_suite_focus=true

<details>
<summary>Full logs (In case the Github actions logs get removed)</summary>

```
Run cd ./packages/smooth_app && flutter build ios --release --no-codesign
Running "flutter pub get" in smooth_app...                       2,746ms
Warning: Building for device with codesigning disabled. You will have to manually codesign before deploying to device.
Building org.openfoodfacts.app for device (ios-release)...
Running pod install...                                             65.8s
Running Xcode build...                                          
Xcode build done.                                           135.5s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/flutter_tools.IUyZok/flutter_ios_build_temp_dirYk7GMK/temporary_xcresult_bundle

    /Users/runner/work/smooth-app/smooth-app/packages/smooth_app/ios/Runner/GeneratedPluginRegistrant.m:12:9: fatal error: module 'camera' not found
    @import camera;
     ~~~~~~~^~~~~~
    1 error generated.
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order

    Result bundle written to path:
    	/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/flutter_tools.IUyZok/flutter_ios_build_temp_dirYk7GMK/temporary_xcresult_bundle


════════════════════════════════════════════════════════════════════════════════
Building a deployable iOS app requires a selected Development Team with a 
Provisioning Profile. Please ensure that a Development Team is selected by:
  1- Open the Flutter project's Xcode target with
       open ios/Runner.xcworkspace
  2- Select the 'Runner' project in the navigator then the 'Runner' target
     in the project settings
  3- Make sure a 'Development Team' is selected under Signing & Capabilities > Team. 
     You may need to:
         - Log in with your Apple ID in Xcode first
         - Ensure you have a valid unique Bundle ID
         - Register your device with your Apple Developer Account
         - Let Xcode automatically provision a profile for your app
  4- Build or run your project again

For more information, please visit:
  https://flutter.dev/docs/get-started/install/macos#deploy-to-ios-devices

Or run on an iOS simulator without code signing
════════════════════════════════════════════════════════════════════════════════
Encountered error while building for device.
Error: Process completed with exit code 1.
```
</details>

## Solution

After changing the deployment target to 11 it worked again.

## The problem with that

The camera README says:

> The camera plugin functionality works on iOS 10.0 or higher.

It may be that this is just an error in my configuration, which is not unlikely, as I can' t repeat this locally due to a lack of an Apple computer, but I figured sharing a possible error can't hurt.
In addition, the iOS version in the example project is 9.0, which contradicts with the README

#### Other  usefull informations

Flutter 2.10.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5f105a6ca7 (8 days ago) • 2022-02-01 14:15:42 -0800
Engine • revision 776efd2034
Tools • Dart 2.16.0 • DevTools 2.9.2

**Comment by stuartmorgan** [comment]
> In addition, the iOS version in the example project is 9.0, which contradicts with the README

This is not a contradiction; please see the sentence in the README right after the one you quoted.

**Comment by maheshmnj** [comment]
Hi @M123-dev, Thanks for filing the issue. I followed reproducible steps and was unable to reproduce the issue ios app builds successfully even with Deployment target set to 10.0

```
mahesh@Maheshs-MacBook-Air-M1 sample % flutter build ios --release --no-codesign   
Warning: Building for device with codesigning disabled. You will have to manually codesign before deploying to device.
Building com.example.sample for device (ios-release)...
Running Xcode build...                                                  
 └─Compiling, linking and signing...                         5.5s
Xcode build done.                                           11.6s
Built /Users/mahesh/Desktop/sample/build/ios/iphoneos/Runner.app.
mahesh@Maheshs-MacBook-Air-M1 sample % 
``` 

Could  you please try re-reunning the build with a verbose flag and share the logs here

`flutter build ios --release --no-codesign`

**Comment by M123-dev** [comment]
Yes no problem, attached the files since Github won't let me comment them because of the length.


[logs_5338 (10.0).zip](https://github.com/flutter/flutter/files/8042939/logs_5338.10.0.zip)
[logs_5336(11.0).zip](https://github.com/flutter/flutter/files/8042940/logs_5336.11.0.zip)

For seeing them split up in different jobs, here the Github Actions logs:
Working (iOS 11.0): https://github.com/openfoodfacts/smooth-app/runs/5143952443?check_suite_focus=true
Broken (iOS 10.0): https://github.com/openfoodfacts/smooth-app/runs/5144099224?check_suite_focus=true

Additional details:
Latest commit history: https://github.com/openfoodfacts/smooth-app/commits/TEST-iOS-10-instead-of-11
Changing from 11.0 to 10.0 commit: https://github.com/openfoodfacts/smooth-app/commit/e8e7d9cba886cd16c50a331b1092215e355a77f2
project/ios folder: https://github.com/openfoodfacts/smooth-app/tree/e8e7d9cba886cd16c50a331b1092215e355a77f2/packages/smooth_app/ios

**Comment by maheshmnj** [comment]
Thanks for the info, The logs don't seem to say much about the potential cause of the error and are same as in the original post.

```console
Runner/GeneratedPluginRegistrant.m -o /Users/runner/Library/Developer/Xcode/DerivedData/Runner-dvmghaeoumecvqcxesnuvtpvcnpg/Build/Intermediates.noindex/Runner.build/Release-iphoneos/Runner.build/Objects-normal/arm64/GeneratedPluginRegistrant.o
2022-02-10T16:35:58.4607020Z                /Users/runner/work/smooth-app/smooth-app/packages/smooth_app/ios/Runner/GeneratedPluginRegistrant.m:12:9: fatal error: module 'camera' not found
2022-02-10T16:35:58.4607140Z                @import camera;
2022-02-10T16:35:58.4607250Z                 ~~~~~~~^~~~~~
2022-02-10T16:35:58.4607360Z                1 error generated.
2022-02-10T16:35:58.4607380Z 
2022-02-10T16:35:58.4607380Z 
2022-02-10T16:35:58.4607520Z                Result bundle written to path:
2022-02-10T16:35:58.4607790Z                	/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/flutter_tools.dgZK5W/flutter_ios_build_temp_dirjTNfwS/temporary_xcresult_bundle
2022-02-10T16:35:58.4607800Z 
2022-02-10T16:35:58.4607810Z 
2022-02-10T16:35:58.4608300Z [  +21 ms] ════════════════════════════════════════════════════════════════════════════════
2022-02-10T16:35:58.4608510Z            Building a deployable iOS app requires a selected Development Team with a 
2022-02-10T16:35:58.4608720Z            Provisioning Profile. Please ensure that a Development Team is selected by:
2022-02-10T16:35:58.4608980Z              1- Open the Flutter project's Xcode target with
2022-02-10T16:35:58.4609220Z                   open ios/Runner.xcworkspace
2022-02-10T16:35:58.4609580Z              2- Select the 'Runner' project in the navigator then the 'Runner' target
2022-02-10T16:35:58.4609930Z                 in the project settings
2022-02-10T16:35:58.4610290Z              3- Make sure a 'Development Team' is selected under Signing & Capabilities > Team. 
2022-02-10T16:35:58.4610410Z                 You may need to:
2022-02-10T16:35:58.4610670Z                     - Log in with your Apple ID in Xcode first
2022-02-10T16:35:58.4610910Z                     - Ensure you have a valid unique Bundle ID
2022-02-10T16:35:58.4611190Z                     - Register your device with your Apple Developer Account
2022-02-10T16:35:58.4611470Z                     - Let Xcode automatically provision a profile for your app
2022-02-10T16:35:58.4611700Z              4- Build or run your project again
2022-02-10T16:35:58.4611710Z 
2022-02-10T16:35:58.4611860Z            For more information, please visit:
2022-02-10T16:35:58.4612200Z              https://flutter.dev/docs/get-started/install/macos#deploy-to-ios-devices
2022-02-10T16:35:58.4612220Z 
2022-02-10T16:35:58.4612370Z            Or run on an iOS simulator without code signing
2022-02-10T16:35:58.4612730Z            ════════════════════════════════════════════════════════════════════════════════
2022-02-10T16:35:58.4612890Z [   +5 ms] Encountered error while building for device.
2022-02-10T16:35:58.4612990Z [        ] 
2022-02-10T16:35:58.4613180Z            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
2022-02-10T16:35:58.4613410Z            #1      _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:279:7)
2022-02-10T16:35:58.4613540Z            <asynchronous suspension>
2022-02-10T16:35:58.4613780Z            #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
2022-02-10T16:35:58.4613910Z            <asynchronous suspension>
2022-02-10T16:35:58.4614130Z            #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
2022-02-10T16:35:58.4614480Z            <asynchronous suspension>
2022-02-10T16:35:58.4614700Z            #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
2022-02-10T16:35:58.4614820Z            <asynchronous suspension>
2022-02-10T16:35:58.4615090Z            #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
2022-02-10T16:35:58.4615210Z            <asynchronous suspension>
2022-02-10T16:35:58.4615440Z            #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
2022-02-10T16:35:58.4615560Z            <asynchronous suspension>
2022-02-10T16:35:58.4615810Z            #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
2022-02-10T16:35:58.4615930Z            <asynchronous suspension>
2022-02-10T16:35:58.4616140Z            #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
2022-02-10T16:35:58.4616270Z            <asynchronous suspension>
2022-02-10T16:35:58.4616500Z            #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
2022-02-10T16:35:58.4616620Z            <asynchronous suspension>
2022-02-10T16:35:58.4616790Z            #10     main (package:flutter_tools/executable.dart:94:3)
2022-02-10T16:35:58.4616910Z            <asynchronous suspension>
2022-02-10T16:35:58.4616920Z 
2022-02-10T16:35:58.4616930Z 
2022-02-10T16:35:58.4617050Z [   +7 ms] "flutter ios" took 350,692ms.
2022-02-10T16:35:58.4617190Z [   +3 ms] ensureAnalyticsSent: 1ms
2022-02-10T16:35:58.4617300Z [   +1 ms] Running shutdown hooks
2022-02-10T16:35:58.4617420Z [        ] Shutdown hooks complete
2022-02-10T16:35:58.4617530Z [        ] exiting with code 1
2022-02-10T16:35:58.4635170Z ##[error]Process completed with exit code 1.

```
Leaving this issue open for further investigation. All the required details for further investigation can be found in the [above comment](https://github.com/flutter/flutter/issues/98139#issuecomment-1035188661)

cc: @jmagman

**Comment by krel024** [comment]
I have same issue. In my case I am using camera 0.9.4+13.
Any news on this?

**Comment by ncikic** [comment]
Having same issue today building on codemagic. Using camera: ^0.9.4+14
I must say I am first time using codemagic, and in general not much ios experience, more android, but anyway I am getting this also.

**Comment by ncikic** [comment]
If of interest, I managed to build the app on codemagic. After unsuccessful build, I have looged into codemagic VM with ssh, I have deleted the Podfile from clone/ios folder and from clone folder manually  started anothe build with  
`flutter build ios --release --no-codesign -v`  
After that I got Podfile recreated. I copied it locally and just substituted the ios version to 11. I got the hint from  
https://stackoverflow.com/a/55395380/1190487

**Comment by jmagman** [comment]
[ncikic](https://github.com/ncikic) so what was the difference between the one that didn't work and the new one?

**Comment by ncikic** [comment]
As I said I am ios novice so probably got something wrong. This is how it went. I connected my flutter project to codemagic. The build started to fail on this import camera error. I found some info in various places about minimum ios version and set that. But it was still failing. Then I found some example Podfile and used that. I did not realize that when building flutter Podfile would be created. When I realized that I found that ios platform was 9.0 in Podfile. So I retrieved the Podfile and changed to `platform :ios, '11.0'` and inserted that into the flutter project under ios folder. Codemagic build instruction already had the command to copy Podfile where it needed to be. So in short I think that the reason for this import camera error is that the generated Podfile had ios platform 9.0 set. But as I sad, I am new here...

**Comment by jmagman** [comment]
Hopefully https://github.com/flutter/flutter/pull/138097 will make issues like this much easier to diagnose and fix in the future.  If anyone else sees similar issues, please file a new issue and completely fill out the template with reproducible steps and we'll take a look.  Thanks!
