### ISSUE TITLE
The recognizer property of TextSpan does not handle correctly when element is updated

### ISSUE THREAD

**Issue by IO-01** [flutter/flutter#98168]
## Steps to Reproduce

1. Execute `flutter run` on the code sample or copy the code to [dartpad](https://dartpad.dev/) and run.
2. Click `Increment RichText` twice.
3. Click `Increment Button` twice.
4. Click `Increment RichText` twice.
5. View logs.

**Expected results:**
<details>
  <summary>Logs</summary>

```
Click TextSpan：0
Click TextSpan：1
Click Button：2
Click Button：3
Click TextSpan：4
Click TextSpan：5
```

</details>

**Actual results:** 
<details>
  <summary>Logs</summary>

```
Click TextSpan：0
Click TextSpan：0
Click Button：2
Click Button：3
Click TextSpan：0
Click TextSpan：0
```

</details>

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/gestures.dart';

void main() {
  runApp(
    MaterialApp(
      home: Scaffold(
          appBar: AppBar(
            title: const Text('Provider example'),
          ),
          body: Center(
            child: CounterWidget(),
          )),
    ),
  );
}

class CounterWidget extends StatefulWidget {
  @override
  State createState() {
    return CounterState();
  }
}

class CounterState extends State<CounterWidget> {
  int count = 0;

  @override
  Widget build(BuildContext context) {
    int c = count;
    return Column(
      children: [
        Text("$c", style: const TextStyle(fontSize: 32)), // show right value
        RichText(
          // key: UniqueKey(), // set key can print right value
          text: TextSpan(
            text: "Increment RichText",
            style: const TextStyle(color: Colors.green, fontSize: 32),
            recognizer: TapGestureRecognizer()
              ..onTap = () {
                count++;
                setState(() {});
                print("Click TextSpan: $c"); // always 0
              },
          ),
        ),
        const Padding(padding: EdgeInsets.only(top: 20)),
        InkWell(
          child: const Text("Increment Button", style: TextStyle(fontSize: 32)),
          onTap: () {
            count++;
            setState(() {});
            print("Click Button: $c"); // print right value
          },
        )
      ],
    );
  }
}
```

</details>

**Comment by IO-01** [comment]
@danagbemava-nc Thank you for your reply.

In fact, I found the problem when using "Provider" for state management. In order to avoid you thinking that the problem is caused by "Provider", I simplified the sample code.
My real use case will be given below.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:flutter/gestures.dart';

void main() {
  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (context) => LoginModel()),
      ],
      child: const MyApp(),
    ),
  );
}

class LoginModel with ChangeNotifier {
  bool _isAgree = false;
  bool get isAgree => _isAgree;
  void setIsAgree(bool isAgree) {
    _isAgree = isAgree;
    notifyListeners();
  }
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    var _isAgree = context.watch<LoginModel>().isAgree;

    return Scaffold(
        appBar: AppBar(
          title: const Text('Provider example'),
        ),
        body: Center(
          child: Row(
            children: <Widget>[
              GestureDetector(
                  onTap: () {
                    print("Click Button：$_isAgree");
                    context.read<LoginModel>().setIsAgree(!_isAgree);
                  },
                  child: Icon(
                    _isAgree
                        ? Icons.radio_button_checked
                        : Icons.radio_button_unchecked,
                  )),
              RichText(
                text: TextSpan(
                    text: 'Read the ', // read the user agreement
                    recognizer: TapGestureRecognizer()
                      ..onTap = () {
                        print("Click TextSpan：$_isAgree");
                        context.read<LoginModel>().setIsAgree(!_isAgree);
                      },
                    children: [
                      TextSpan(
                          text: 'User License Agreement.',
                          style: const TextStyle(color: Color(0xFF134AED)),
                          recognizer: TapGestureRecognizer()..onTap = () {})
                    ]),
              )
            ],
          ),
        ));
  }
}
```

</details>

Because the icon is small, I want the user to get the same result as when they click on the text to the left of the icon. But when they click on the text, the icon can never be unchecked.

**Comment by IO-01** [comment]
> But may I suggest using a `CheckboxListTile` instead of `Row`? I think that makes more sense for the User Agreement, no?

 In order to make it easier for you to reproduce the error with dartpad, I use `Icons.radio_button_unchecked` and `Icons.radio_button_unchecked` in my sample code, in fact I need to use two images provided by my designer. So I can't use your suggestion, but I thank you for it. 

In any case, you can't provide an alternative to every developer who uses rich text and adds click events, because they have their own unique product needs. 

I think it's better to think about how to fix it rather than how to avoid it.

**Comment by danagbemava-nc** [comment]
> I think it's better to think about how to fix it rather than how to avoid it.

That was not my intention. I am very much interested in getting the bug fixed. I suggested an alternative in the event that a fix doesn't come as soon as possible considering the backlog of issues. 


Issue is reproducible on `stable` and `master`. 

Possibly related https://github.com/flutter/flutter/issues/10623. 


<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/gestures.dart';

void main() {
  runApp(
    MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Provider example'),
        ),
        body: const CounterWidget(),
      ),
    ),
  );
}

class CounterWidget extends StatefulWidget {
  const CounterWidget({Key? key}) : super(key: key);

  @override
  State createState() {
    return CounterState();
  }
}

class CounterState extends State<CounterWidget> {
  int count = 0;

  @override
  Widget build(BuildContext context) {
    int c = count;
    return Column(
      children: [
        Text("$c", style: const TextStyle(fontSize: 32)), // show right value
        RichText(
          //  TODO: uncomment the unique key and see it work as expected
          // key: UniqueKey(), // set key can print right value
          text: TextSpan(
            text: "Increment RichText",
            style: const TextStyle(color: Colors.green, fontSize: 32),
            recognizer: TapGestureRecognizer()
              ..onTap = () {
                count++;
                setState(() {});
                print("Click TextSpan: $c"); // always 0
              },
          ),
        ),
        const Padding(padding: EdgeInsets.only(top: 20)),
        InkWell(
          child: const Text("Increment Button", style: TextStyle(fontSize: 32)),
          onTap: () {
            count++;
            setState(() {});
            print("Click Button: $c"); // print right value
          },
        )
      ],
    );
  }
}

```
</details>

<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.10.1, on macOS 12.2 21D49 darwin-arm, locale en-GB)
    • Flutter version 2.10.1 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (35 hours ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1426:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1861:10)
      #15     runZonedGuarded (dart:async/zone.dart:1849:12)
      #16     runZoned (dart:async/zone.dart:1780:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:205:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:309:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.64.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • 304CA91D-8D77-4AAE-A50F-ECFC57AFD011 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 12.2 21D49 darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel master, 2.11.0-0.0.pre.509, on macOS 12.2 21D49 darwin-arm, locale en-GB)
    • Flutter version 2.11.0-0.0.pre.509 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6656356bbf (3 hours ago), 2022-02-10 20:30:17 -0800
    • Engine revision a57061eda8
    • Dart version 2.17.0 (build 2.17.0-87.0.dev)
    • DevTools version 2.10.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 213.5744.122

[✓] VS Code (version 1.64.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • 304CA91D-8D77-4AAE-A50F-ECFC57AFD011 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 12.2 21D49 darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

<details>
<summary>short logs</summary>

[click_textspan_no_unique_key.txt](https://github.com/flutter/flutter/files/8046759/click_textspan_no_unique_key.txt)

[click_textspan_with_unique_key.txt](https://github.com/flutter/flutter/files/8046760/click_textspan_with_unique_key.txt)


</details>

**Comment by IO-01** [comment]
> I suggested an alternative in the event that a fix doesn't come as soon as possible considering the backlog of issues.

Thanks again for your help, I temporarily avoided the problem using setting UniqueKey.
If need help with testing and reporting, I'd love to do it.
