### ISSUE TITLE
App crash when using google_maps_flutter and webview_flutter

### ISSUE THREAD

**Issue by iulian0512** [flutter/flutter#98182]
## Steps to Reproduce

This crash occurs on flutter 2.10.1 only on android (release + debug).
It does not occur on flutter 2.8.1 .

1. Execute `flutter run --debug` on the code sample 
2.  press next Page button
3. press app bar back button (left arrow button)
4. Crash!

**Expected results:**  Not crash

**Actual results:**  fatal app crash

<details>
<summary>Code sample</summary>

Minimum reproducible example
```

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) =>
      const MaterialApp(home: Scaffold(body: FirstPage()));
}

class FirstPage extends StatelessWidget {
  const FirstPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) => Scaffold(
      appBar: AppBar(title: const Text("first page (gmaps)")),
      body: Column(children: [
        const Expanded(
            child: GoogleMap(
                initialCameraPosition: CameraPosition(target: LatLng(45, 25)))),
        OutlinedButton(
            onPressed: () => Navigator.of(context)
                .push(MaterialPageRoute(builder: (_) => const SecondPage())),
            child: const Text("next Page"))
      ]));
}

class SecondPage extends StatelessWidget {
  const SecondPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) => Scaffold(
      appBar: AppBar(title: const Text("second page (webbrowser)")),
      body: const WebView(initialUrl: "http://www.google.com"));
}

```

pubspec.yaml
```
name: flutter_dummytest
description: A new Flutter project.



publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.1.1
  webview_flutter: ^3.0.0
dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
```

 

```dart
```

</details>

<details>
  <summary>Logs</summary>
complete logfile  see file https://gist.github.com/iulian0512/58800a0ecf6cee3836b1a97bc2a3cc2f

Exception snapshot:

```
E/OpenGLRenderer(12193): [SurfaceTexture-0-12193-0] attachToContext: SurfaceTexture is already attached to a context
[   +1 ms] E/flutter (12193): [ERROR:flutter/fml/platform/android/jni_util.cc(211)] java.lang.RuntimeException: Error during attachToGLContext (see logcat for details)
[        ] E/flutter (12193): 	at android.graphics.SurfaceTexture.attachToGLContext(SurfaceTexture.java:294)
[        ] E/flutter (12193): 	at io.flutter.embedding.engine.renderer.SurfaceTextureWrapper.attachToGLContext(SurfaceTextureWrapper.java:57)
[        ] E/flutter (12193): 	at android.os.MessageQueue.nativePollOnce(Native Method)
[        ] E/flutter (12193): 	at android.os.MessageQueue.next(MessageQueue.java:336)
[        ] E/flutter (12193): 	at android.os.Looper.loop(Looper.java:174)
[        ] E/flutter (12193): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
[        ] E/flutter (12193): 	at java.lang.reflect.Method.invoke(Native Method)
[        ] E/flutter (12193): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
[        ] E/flutter (12193): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
[        ] E/flutter (12193): 
[        ] F/flutter (12193): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1301)] Check failed: fml::jni::CheckException(env). 
[        ] F/libc    (12193): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 12193 (utter_dummytest), pid 12193 (utter_dummytest)
[  +35 ms] *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***

```

flutter doctor -v

```
[✓] Flutter (Channel stable, 2.10.1, on Ubuntu 20.04.3 LTS 5.13.0-28-generic, locale en_US.UTF-8)
    • Flutter version 2.10.1 at /home/iulian/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (14 hours ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/iulian/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /home/iulian/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/iulian/android-studio
    • Flutter plugin version 63.2.1
    • Dart plugin version 203.8452
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.64.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.34.0

[✓] Connected device (2 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64    • Android 10 (API 29) (emulator)
    • Chrome (web)                          • chrome        • web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```
```

```
```

```
```

</details>

<details>
<summary>Video</summary>

https://user-images.githubusercontent.com/16035099/153381549-7907df73-ffd2-4ca2-b96c-f0be505a804c.mp4

</details>

**Comment by maheshmnj** [comment]
Hi @iulian0512, Thanks for filing the issue.

There is a similar issue describing this case https://github.com/flutter/flutter/issues/98155, Please follow up there for further updates, Closing this issue as a duplicate. If you disagree feel free to write in the comments and I will reopen it.

Thank you.
