### ISSUE TITLE
NullPointerException in dispatchWindowVisibilityChanged for Flutter 2.10 app

### ISSUE THREAD

**Issue by ozzy1873** [flutter/flutter#98197]
## Steps to Reproduce

I have not been able to reproduce the crash myself. However, since updating my app to the latest stable version of Flutter (2.10) targeting API 31, I am seeing in Crashlytics a lot of exceptions similar to this. The crash occurs mostly in the background. I saw some other posts about the Google ad control, but I am not serving ads. I do display a Google map control using hybrid composition, but I have no idea if that is even related.

NOTE: The flutter doctor output shows Flutter v2.10.1, but the problem is occurring in v2.10.0. I have not yet published a version of my app built with 2.10.1.

**Expected results:** 
No crash

**Actual results:** 
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.dispatchWindowVisibilityChanged(int)' on a null object reference
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1632)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1632)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1632)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1632)
       at com.android.internal.policy.DecorView.dispatchWindowVisibilityChanged(DecorView.java:4221)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3151)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2618)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9971)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1010)
       at android.view.Choreographer.doCallbacks(Choreographer.java:809)
       at android.view.Choreographer.doFrame(Choreographer.java:744)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8633)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
[√] Flutter (Channel stable, 2.10.1, on Microsoft Windows [Version 10.0.22000.493], locale en-US)
    • Flutter version 2.10.1 at c:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (18 hours ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\john\AppData\Local\Android\Sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = C:\Users\john\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Professional 2019 16.11.9)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional
    • Visual Studio Professional 2019 version 16.11.32106.194
    • Windows 10 SDK version 10.0.19041.0
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include
      these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] Connected device (4 available)
    • SM G950U1 (mobile) • 988b1c35314d344258 • android-arm64  • Android 9 (API 28)
    • Windows (desktop)  • windows            • windows-x64    • Microsoft Windows [Version 10.0.22000.493]
    • Chrome (web)       • chrome             • web-javascript • Google Chrome 95.0.4638.69
    • Edge (web)         • edge               • web-javascript • Microsoft Edge 98.0.1108.43

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.


```

</details>

**Comment by darshankawar** [comment]
@ozzy1873 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/98197
Please follow-up in it for further updates. Closing this as a duplicate.

**Comment by EArminjon** [comment]
You have linked the wrong issue @darshankawar

**Comment by darshankawar** [comment]
@EArminjon Thanks, my bad...copy paste error.  fixed.
