### ISSUE TITLE
Two crashes: Kotlin version and Gradle assembleDebug

### ISSUE THREAD

**Issue by andesappal** [flutter/flutter#98223]
## Steps to Reproduce

1. Define files as shown below
2. Run main.dart
3. See two crashes on Run log on Android Studio, as shown below

**Expected results:** I expected the app to run 

**Actual results:** The app crashed before opening

<details>
<summary>android/build.gradle</summary>

```
buildscript {
    ext.kotlin_version = '1.6.10'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
        classpath 'com.google.gms:google-services:4.3.3'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'

subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

</details>

<details>
  <summary>app/build.gradle</summary>

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
apply plugin: 'com.google.gms.google-services'
apply plugin: 'kotlin-android'

android {
    compileSdkVersion flutter.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        applicationId "com.tvp"
        minSdkVersion flutter.minSdkVersion
        targetSdkVersion flutter.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        multiDexEnabled true
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            storePassword keystoreProperties['storePassword']
        }
    }

    dependencies {
        implementation 'com.android.support:multidex:1.0.3'
        implementation platform('com.google.firebase:firebase-bom:26.1.1')
        implementation 'com.google.firebase:firebase-analytics'
        implementation 'io.card:android-sdk:5.5.1'
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}
```

</details>

<details>
  <summary>AndroidManifest.xml</summary>

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"

    package="com.app">
    <application
        android:name="${applicationName}"
        android:label="app"
        android:icon="@mipmap/app_icon">
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <activity
            android:name="com.braintreepayments.api.BraintreeBrowserSwitchActivity"
            android:launchMode="singleTask"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="com.app.braintree" />
            </intent-filter>
        </activity>
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
        <meta-data android:name="com.google.android.gms.wallet.api.enabled" android:value="true"/>
    </application>
</manifest>

```

</details>

<details>
  <summary>flutter doctor -v</summary>

```
Last login: Thu Feb 10 10:32:06 on console
kevin@Kevins-MacBook-Air ~ % flutter doctor -v
[✓] Flutter (Channel stable, 2.10.0, on macOS 11.6.2 20G314 darwin-arm, locale en-US)
    • Flutter version 2.10.0 at /Users/kevin/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f105a6ca7 (9 days ago), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/kevin/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] Connected device (3 available)
    • SM G996B (mobile) • RQCR1006DCV • android-arm64  • Android 12 (API 31)
    • macOS (desktop)   • macos       • darwin-arm64   • macOS 11.6.2 20G314 darwin-arm
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
kevin@Kevins-MacBook-Air ~ %    
```

</details>

<details>
  <summary>Kotlin version crash</summary>

```
[ +426 ms] FAILURE: Build failed with an exception.
[   +3 ms] * What went wrong:
[        ] A problem occurred configuring root project 'android'.
[        ] > Could not resolve all artifacts for configuration ':classpath'.
[        ]    > Could not find org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version.
[        ]      Searched in the following locations:
[        ]        - https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin/$kotlin_version/kotlin-gradle-plugin-$kotlin_version.pom
[        ]        - https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin/$kotlin_version/kotlin-gradle-plugin-$kotlin_version.pom
[        ]      Required by:
[        ]          project :
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 1s
```

</details>

<details>
  <summary>Gradle task assembleDebug crash</summary>

```
[+8401 ms] Exception: Gradle task assembleDebug failed with exit code 1
[  +14 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:589:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @andesappal, the issue with the kotlin error is because of

```groovy
   classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version'
```

since the value is supposed to be evaluated, you're supposed to use

```groovy
 classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
```

like it is used in 

```groovy
implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
```

As for the second error, we'll need full verbose logs of the operation you were trying to perform, be it `flutter build apk` or `flutter run`. 

Please provide the full verbose logs so we may better address this issue. 

Thank you

**Comment by andesappal** [comment]
@danagbemava-nc what a silly mistake I made on using ' for ''. Thank you. 

Here's `flutter run -t lib/src/main.dart --verbose`: https://gist.github.com/andesappal/b19c55d2a67326bfd4e883dc3b9653c9

**Comment by andesappal** [comment]
@danagbemava-nc  here's an update of the gradles and manifest:

android/build.gradle: https://gist.github.com/andesappal/2b025558b82865bea0fbcf59bd21c298

app/build.gradle: https://gist.github.com/andesappal/810253cb7e7126ef3ee52792074e679a

AndroidManifest.xml: https://gist.github.com/andesappal/4ab70abdbcba52c6ff61aff254c32d34

**Comment by andesappal** [comment]
@danagbemava-nc maybe this could help you further:
![image](https://user-images.githubusercontent.com/54340176/153663140-f918861b-c280-47ad-93c4-8a168d93e1fa.png)

![image](https://user-images.githubusercontent.com/54340176/153663171-8c8c676c-ddc8-4595-8815-235b2ff9984b.png)

![image](https://user-images.githubusercontent.com/54340176/153663194-5c6c4731-ad70-4678-bc43-fd6e7a3c8887.png)

**Comment by andesappal** [comment]
Hi Daniel just bumping this up thank you

**Comment by danagbemava-nc** [comment]
Hi @andesappal, can I get your `pubspec.yaml`? 

I want to see if I can recreate the crash with the rest of the information that you have provided

**Comment by andesappal** [comment]
@danagbemava-nc yes! https://gist.github.com/andesappal/72e65749fb67135deec7344a09b95aba

**Comment by andesappal** [comment]
Daniel, I noticed many other failures prior to assembleDebug. If you search
for the word failure in
https://gist.github.com/andesappal/b19c55d2a67326bfd4e883dc3b9653c9 you'll
see.

**Comment by andesappal** [comment]
Sorry search for 'fail'

**Comment by danagbemava-nc** [comment]
Can you check if this SO thread helps? https://stackoverflow.com/questions/66164771/type-project-com-project-mainactivity-is-defined-multiple-times. 


Also, is your project open-sourced somewhere so I can take a look in case the SO thread doesn't help?

**Comment by andesappal** [comment]
Hi Daniel. If I comment out these Kotlin references:
android build gradle https://gist.github.com/andesappal/e485dad9466cbeb20e3920493d2668f2
app build gradle https://gist.github.com/andesappal/1198ffa0a15980bf46cfae5a33d73217

I get this Build Fail Flutter Fix 
https://gist.github.com/andesappal/007849b5aa2277d94756eff83acaf70e#file-gistfile1-txt-L2854-L2861

My app is not open-sourced, unfortunately. What else can we try? Thank you.

**Comment by andesappal** [comment]
SOLVED! Deleted the Java MainActivity and the app ran again.
