### ISSUE TITLE
ext.flutter.inspector.show: Unexpected error from chrome devtools: text: Uncaught (in promise)

### ISSUE THREAD

**Issue by SailorMax** [flutter/flutter#98237]
## command

flutter run raw/hello_world.dart -d chrome

## exception

RPCError: ext.flutter.inspector.show: (-32603) ext.flutter.inspector.show: Unexpected error from chrome devtools:
text: Uncaught (in promise)
exception:
  description: null
  type: string
  value: Unexpected null value.
attempted JS eval: `require("dart_sdk").developer.invokeExtension(
    "ext.flutter.inspector.show", JSON.stringify({}));
`

```
#0      handleErrorIfPresent (package:dwds/src/utilities/shared.dart:97:5)
#1      ChromeProxyService.callServiceExtension (package:dwds/src/services/chrome_proxy_service.dart:351:5)
<asynchronous suspension>
#2      StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:125:47)
<asynchronous suspension>

#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1718:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2225:21)
#2      VmService.callServiceExtension (package:vm_service/src/vm_service.dart:2196:14)
#3      FlutterVmService._checkedCallServiceExtension (package:flutter_tools/src/vmservice.dart:776:28)
#4      FlutterVmService.invokeFlutterExtensionRpcRaw (package:flutter_tools/src/vmservice.dart:795:49)
#5      FlutterVmService._flutterToggle (package:flutter_tools/src/vmservice.dart:598:41)
#6      FlutterVmService.flutterToggleWidgetInspector (package:flutter_tools/src/vmservice.dart:625:9)
#7      ResidentHandlers.debugToggleWidgetInspector (package:flutter_tools/src/resident_runner.dart:773:32)
<asynchronous suspension>
#8      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1680:7)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel stable, 2.10.1, on Microsoft Windows [Version 10.0.22000.493], locale en-150)
    • Flutter version 2.10.1 at C:\max\GitHub\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (35 hours ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.64.2)
    • VS Code at C:\Users\sailo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.493]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 98.0.4758.82
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 98.0.1108.43

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.
```

**Comment by danagbemava-nc** [comment]
Hi @SailorMax, can you provide the full crash log? 
It should have a name similar to `flutter_01.log`.

Also, does this reproduce for you consistently, or was it just a one-time thing?

If it's consistent, can you please provide steps to reproduce? 

Thank you

**Comment by SailorMax** [comment]
@danagbemava-nc My message is content of this file (flutter_01.log)

**Comment by danagbemava-nc** [comment]
Does this reproduce for you consistently, or was it just a one-time thing?

If it's consistent, can you please provide steps to reproduce?

**Comment by SailorMax** [comment]
Steps:
1. execute flutter_console.bat
2. > cd examples\layers\
3. > flutter run -d chrome raw\hello_world.dart
4. press i

**Comment by maheshmnj** [comment]
Hi @SailorMax, thanks for filing the issue, I was able to reproduce the crash on the stable and the master channel. I believe this is because the inspector tool is for inspecting widgets and the example `hello_world.dart` is painting raw text on the canvas (not a widget), Ofcourse the app shouldn't crash and should fail gracefully. 

<details>
<summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 2.11.0-0.0.pre.452, on Microsoft Windows [Version 10.0.19044.1466], locale en-US)
    • Flutter version 2.11.0-0.0.pre.452 at C:\flutter_sdk\master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba01ec8faa (8 days ago), 2022-02-05 22:05:18 -0500
    • Engine revision 0712096899
    • Dart version 2.17.0 (build 2.17.0-85.0.dev)
    • DevTools version 2.10.0

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\mahesh\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31727.386
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.63.2)
    • VS Code at C:\Users\mahesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.34.0

[√] Connected device (4 available)
    • Windows (desktop)       • windows • windows-x64     • Microsoft Windows [Version 10.0.19044.1466]
    • Windows (UWP) (desktop) • winuwp  • windows-uwp-x64 •
    • Chrome (web)            • chrome  • web-javascript  • Google Chrome 98.0.4758.82
    • Edge (web)              • edge    • web-javascript  • Microsoft Edge 97.0.1072.76

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[√] Flutter (Channel stable, 2.10.1, on Microsoft Windows [Version 10.0.19044.1466], locale en-US)
    • Flutter version 2.10.1 at C:\flutter_sdk\stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (4 days ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\mahesh\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31727.386
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.63.2)
    • VS Code at C:\Users\mahesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.34.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1466]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 98.0.4758.82
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 97.0.1072.76

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
</details>


<details>
<summary>logs</summary>

```

C:\flutter_sdk\master\examples\layers>flutter run -d chrome raw\hello_world.dart

┌─────────────────────────────────────────────────────────┐
│ A new version of Flutter is available!                  │
│                                                         │
│ To update to the latest version, run "flutter upgrade". │
└─────────────────────────────────────────────────────────┘
Running "flutter pub get" in layers...                           2,009ms
This application is not configured to build on the web.
To add web support to a project, run `flutter create .`.
Launching raw\hello_world.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...           1,138ms
This app is linked to the debug service: ws://127.0.0.1:60761/PFF4z08r5kk=/ws
Debug service listening on ws://127.0.0.1:60761/PFF4z08r5kk=/ws

 Running with sound null safety

  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".

An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:60761/PFF4z08r5kk=
A message on the flutter/keyevent channel was discarded before it could be handled.
This happens when a plugin sends messages to the framework side before the framework has had an opportunity to register
a listener. See the ChannelBuffers API documentation for details on how to configure the channel to expect more
messages, or to expect messages to get discarded:
  https://api.flutter.dev/flutter/dart-ui/ChannelBuffers-class.html

ext.flutter.inspector.show: (-32603) ext.flutter.inspector.show: Unexpected error from chrome devtools:
text: Uncaught (in promise)
exception:
  description: null
  type: string
  value: Unexpected null value.
attempted JS eval: `require("dart_sdk").developer.invokeExtension(
    "ext.flutter.inspector.show", JSON.stringify({}));
`

#0      handleErrorIfPresent (package:dwds/src/utilities/shared.dart:97:5)
#1      ChromeProxyService.callServiceExtension (package:dwds/src/services/chrome_proxy_service.dart:351:5)
<asynchronous suspension>
#2      StackZoneSpecification._registerUnaryCallback.<anonymous closure>
(package:stack_trace/src/stack_zone_specification.dart:125:47)
<asynchronous suspension>

#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1718:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2225:21)
#2      VmService.callServiceExtension (package:vm_service/src/vm_service.dart:2196:14)
#3      FlutterVmService._checkedCallServiceExtension (package:flutter_tools/src/vmservice.dart:776:28)
#4      FlutterVmService.invokeFlutterExtensionRpcRaw (package:flutter_tools/src/vmservice.dart:795:49)
#5      FlutterVmService._flutterToggle (package:flutter_tools/src/vmservice.dart:598:41)
#6      FlutterVmService.flutterToggleWidgetInspector (package:flutter_tools/src/vmservice.dart:625:9)
#7      ResidentHandlers.debugToggleWidgetInspector (package:flutter_tools/src/resident_runner.dart:773:32)
<asynchronous suspension>
#8      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1680:7)
<asynchronous suspension>



Application finished.
Oops; flutter has exited unexpectedly: "ext.flutter.inspector.show: (-32603) ext.flutter.inspector.show: Unexpected
error from chrome devtools:
text: Uncaught (in promise)
exception:
  description: null
  type: string
  value: Unexpected null value.
attempted JS eval: `require("dart_sdk").developer.invokeExtension(
    "ext.flutter.inspector.show", JSON.stringify({}));
`

#0      handleErrorIfPresent (package:dwds/src/utilities/shared.dart:97:5)
#1      ChromeProxyService.callServiceExtension (package:dwds/src/services/chrome_proxy_service.dart:351:5)
<asynchronous suspension>
#2      StackZoneSpecification._registerUnaryCallback.<anonymous closure>
(package:stack_trace/src/stack_zone_specification.dart:125:47)
<asynchronous suspension>
".
A crash report has been written to C:\flutter_sdk\master\examples\layers\flutter_01.log.
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+ext.flutter.inspector.show%3A+%28-32603%29+ext.flutter.inspector.show%3A+Unexpected+error+from+chrome+devtools%3A%0Atext%3A+Uncaught+%28in+promise%29%0Aexception%3A%0A++description%3A+null%0A++type%3A+string%0A++value%3A+Unexpected+null+value.%0Aattempted+JS+eval%3A+%60require%28%22dart_sdk%22%29.developer.invokeExtension%28%0A++++%22ext.flutter.inspector.show%22%2C+JSON.stringify%28%7B%7D%29%29%3B%0A%60%0A%0A%230++++++handleErrorIfPresent+%28package%3Adwds%2Fsrc%2Futilities%2Fshared.dart%3A97%3A5%29%0A%231++++++ChromeProxyService.callServiceExtension+%28package%3Adwds%2Fsrc%2Fservices%2Fchrome_proxy_service.dart%3A351%3A5%29%0A%3Casynchronous+suspension%3E%0A%232++++++StackZoneSpecification._registerUnaryCallback.%3Canonymous+closure%3E+%28package%3Astack_trace%2Fsrc%2Fstack_zone_specification.dart%3A125%3A47%29%0A%3Casynchronous+suspension%3E%0A

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
https://github.com/flutter/flutter/issues/new?title=%5Btool_crash%5D+RPCError&body=%23%23+Command%0A%60%60%60%0Aflutter+run+-d+chrome+raw%5Chello_world.dart%0A%60%60%60%0A%0A%23%23+Steps+to+Reproduce%0A1.+...%0A2.+...%0A3.+...%0A%0A%23%23+Logs%0ARPCError%0A%60%60%60%0A%230++++++new+_OutstandingRequest+%28package%3Avm_service%2Fsrc%2Fvm_service.dart%3A1718%3A45%29%0A%231++++++VmService._call+%28package%3Avm_service%2Fsrc%2Fvm_service.dart%3A2225%3A21%29%0A%232++++++VmService.callServiceExtension+%28package%3Avm_service%2Fsrc%2Fvm_service.dart%3A2196%3A14%29%0A%233++++++FlutterVmService._checkedCallServiceExtension+%28package%3Aflutter_tools%2Fsrc%2Fvmservice.dart%3A776%3A28%29%0A%234++++++FlutterVmService.invokeFlutterExtensionRpcRaw+%28package%3Aflutter_tools%2Fsrc%2Fvmservice.dart%3A795%3A49%29%0A%235++++++FlutterVmService._flutterToggle+%28package%3Aflutter_tools%2Fsrc%2Fvmservice.dart%3A598%3A41%29%0A%236++++++FlutterVmService.flutterToggleWidgetInspector+%28package%3Aflutter_tools%2Fsrc%2Fvmservice.dart%3A625%3A9%29%0A%237++++++ResidentHandlers.debugToggleWidgetInspector+%28package%3Aflutter_tools%2Fsrc%2Fresident_runner.dart%3A773%3A32%29%0A%3Casynchronous+suspension%3E%0A%238++++++TerminalHandler.processTerminalInput+%28package%3Aflutter_tools%2Fsrc%2Fresident_runner.dart%3A1680%3A7%29%0A%3Casynchronous+suspension%3E%0A%60%60%60%0A%60%60%60%0A%5B%E2%9C%93%5D+Flutter+%28Channel+master%2C+2.11.0-0.0.pre.452%2C+on+Microsoft+Windows+%5BVersion+10.0.19044.1466%5D%2C+locale+en-US%29%0A++++%E2%80%A2+Flutter+version+2.11.0-0.0.pre.452+at+C%3A%5Cflutter_sdk%5Cmaster%0A++++%E2%80%A2+Upstream+repository+https%3A%2F%2Fgithub.com%2Fflutter%2Fflutter.git%0A++++%E2%80%A2+Framework+revision+ba01ec8faa+%288+days+ago%29%2C+2022-02-05+22%3A05%3A18+-0500%0A++++%E2%80%A2+Engine+revision+0712096899%0A++++%E2%80%A2+Dart+version+2.17.0+%28build+2.17.0-85.0.dev%29%0A++++%E2%80%A2+DevTools+version+2.10.0%0A%0A%5B%E2%9C%93%5D+Android+toolchain+-+develop+for+Android+devices+%28Android+SDK+version+31.0.0%29%0A++++%E2%80%A2+Android+SDK+at+C%3A%5CUsers%5Cmahesh%5CAppData%5CLocal%5CAndroid%5Csdk%0A++++%E2%80%A2+Platform+android-31%2C+build-tools+31.0.0%0A++++%E2%80%A2+Java+binary+at%3A+C%3A%5CProgram+Files%5CAndroid%5CAndroid+Studio%5Cjre%5Cbin%5Cjava%0A++++%E2%80%A2+Java+version+OpenJDK+Runtime+Environment+%28build+11.0.10%2B0-b96-7249189%29%0D%0A++++%E2%80%A2+All+Android+licenses+accepted.%0A%0A%5B%E2%9C%93%5D+Chrome+-+develop+for+the+web%0A++++%E2%80%A2+Chrome+at+C%3A%5CProgram+Files%5CGoogle%5CChrome%5CApplication%5Cchrome.exe%0A%0A%5B%E2%9C%93%5D+Visual+Studio+-+develop+for+Windows+%28Visual+Studio+Community+2019+16.11.4%29%0A++++%E2%80%A2+Visual+Studio+at+C%3A%5CProgram+Files+%28x86%29%5CMicrosoft+Visual+Studio%5C2019%5CCommunity%0A++++%E2%80%A2+Visual+Studio+Community+2019+version+16.11.31727.386%0A++++%E2%80%A2+Windows+10+SDK+version+10.0.19041.0%0A%0A%5B%E2%9C%93%5D+Android+Studio+%28version+2020.3%29%0A++++%E2%80%A2+Android+Studio+at+C%3A%5CProgram+Files%5CAndroid%5CAndroid+Studio%0A++++%E2%80%A2+Flutter+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F9212-flutter%0A++++%E2%80%A2+Dart+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F6351-dart%0A++++%E2%80%A2+Java+version+OpenJDK+Runtime+Environment+%28build+11.0.10%2B0-b96-7249189%29%0D%0A%0A%5B%E2%9C%93%5D+VS+Code+%28version+1.63.2%29%0A++++%E2%80%A2+VS+Code+at+C%3A%5CUsers%5Cmahesh%5CAppData%5CLocal%5CPrograms%5CMicrosoft+VS+Code%0A++++%E2%80%A2+Flutter+extension+version+3.34.0%0A%0A%5B%E2%9C%93%5D+Connected+device+%284+available%29%0A++++%E2%80%A2+Windows+%28desktop%29+++++++%E2%80%A2+windows+%E2%80%A2+windows-x64+++++%E2%80%A2+Microsoft+Windows+%5BVersion+10.0.19044.1466%5D%0A++++%E2%80%A2+Windows+%28UWP%29+%28desktop%29+%E2%80%A2+winuwp++%E2%80%A2+windows-uwp-x64+%E2%80%A2+%0A++++%E2%80%A2+Chrome+%28web%29++++++++++++%E2%80%A2+chrome++%E2%80%A2+web-javascript++%E2%80%A2+Google+Chrome+98.0.4758.82%0A++++%E2%80%A2+Edge+%28web%29++++++++++++++%E2%80%A2+edge++++%E2%80%A2+web-javascript++%E2%80%A2+Microsoft+Edge+97.0.1072.76%0A%0A%5B%E2%9C%93%5D+HTTP+Host+Availability%0A++++%E2%80%A2+All+required+HTTP+hosts+are+available%0A%0A%E2%80%A2+No+issues+found%21%0A%0A%60%60%60%0A%0A%23%23+Flutter+Application+Metadata%0A%2A%2AType%2A%2A%3A+malformed%0A%2A%2AVersion%2A%2A%3A+null%0A%2A%2AMaterial%2A%2A%3A+true%0A%2A%2AAndroid+X%2A%2A%3A+false%0A%2A%2AModule%2A%2A%3A+false%0A%2A%2APlugin%2A%2A%3A+false%0A%2A%2AAndroid+package%2A%2A%3A+null%0A%2A%2AiOS+bundle+identifier%2A%2A%3A+null%0A%2A%2ACreation+channel%2A%2A%3A+null%0A%2A%2ACreation+framework+version%2A%2A%3A+null%0A%0A&labels=tool%2Csevere%3A+crash
```
</details>

**Comment by polina-c** [comment]
Removed devtools label as the issue does not relate to davtools.

**Comment by christopherfujino** [comment]
> Hi @SailorMax, thanks for filing the issue, I was able to reproduce the crash on the stable and the master channel. I believe this is because the inspector tool is for inspecting widgets and the example `hello_world.dart` is painting raw text on the canvas (not a widget), Ofcourse the app shouldn't crash and should fail gracefully.

I think you're right, I can reproduce this, and then when I try it with `//flutter/examples/layers/widgets/hello_world.dart` it works.

**Comment by yjbanov** [comment]
If this is still an issue, consider filing an issue at https://github.com/dart-lang/webdev/issues
