### ISSUE TITLE
Whenever running this project facing this issue

### ISSUE THREAD

**Issue by Aryan3010** [flutter/flutter#98264]
`java.lang.IllegalArgumentException: Cannot find JAR 'failureaccess-1.0.1.jar' required by module 'gradle-launcher' using classpath or distribution directory '[/Users/aryanarora/.gradle/wrapper/dists/gradle-6.7-all/cuy9mc7upwgwgeb72wkcrupxe/gradle-6.7]()'
	at org.gradle.api.internal.classpath.DefaultModuleRegistry.findDependencyJar(DefaultModuleRegistry.java:316)
	at org.gradle.api.internal.classpath.DefaultModuleRegistry.findDependencyJars(DefaultModuleRegistry.java:183)
	at org.gradle.api.internal.classpath.DefaultModuleRegistry.module(DefaultModuleRegistry.java:173)
	at org.gradle.api.internal.classpath.DefaultModuleRegistry.loadOptionalModule(DefaultModuleRegistry.java:153)
	at org.gradle.api.internal.classpath.DefaultModuleRegistry.loadModule(DefaultModuleRegistry.java:137)
	at org.gradle.api.internal.classpath.DefaultModuleRegistry.getModule(DefaultModuleRegistry.java:117)
	at org.gradle.api.internal.DefaultClassPathProvider.findClassPath(DefaultClassPathProvider.java:31)
	at org.gradle.api.internal.DefaultClassPathRegistry.getClassPath(DefaultClassPathRegistry.java:35)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:49)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:31)
	at java.base[/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0]()(Native Method)
	at java.base[/jdk.internal.reflect.NativeMethodAccessorImpl.invoke]()(NativeMethodAccessorImpl.java:62)
	at java.base[/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke]()(DelegatingMethodAccessorImpl.java:43)
	at java.base[/java.lang.reflect.Method.invoke]()(Method.java:566)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Exception: Gradle task assembleDebug failed with exit code 1
`
<img width="1438" alt="Screenshot 2022-02-11 at 10 11 44 PM" src="https://user-images.githubusercontent.com/64428401/153631986-150b33c0-9836-4fe5-8f96-66940862d5fb.png">

**Comment by darshankawar** [comment]
@Aryan3010 
This seems to be coming from gradle itself and may not be specific to Flutter. Check below similar issues and see if they help:

https://github.com/msys2/MSYS2-packages/issues/1913

**Comment by Aryan3010** [comment]
This doesn't seem to resolve that issue

**Comment by darshankawar** [comment]
@Aryan3010 
This seems to be related to gradle and may not be specific to Flutter as Flutter is consuming gradle properties. I suggest you to open this issue in gradle repo.https://github.com/gradle/gradle/issues
Closing from here. If you disagree or think this is specific to Flutter, write in comments and I'll reopen it.
