### ISSUE TITLE
Android emulator black screen

### ISSUE THREAD

**Issue by Amean** [flutter/flutter#98309]
Android emulator just shows a black screen when I try to run my application. I would really appreciate any insight on what some of these warnings are, thanks so much!

Output on flutter run:
```
Using hardware rendering with device sdk gphone x86 arm. If you notice graphics artifacts, consider
enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on sdk gphone x86 arm in debug mode...
Running Gradle task 'assembleDebug'...                             33.0s
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...              1,053ms
I/flutter_weathe( 4447): Late-enabling -Xcheck:jni
I/flutter_weathe( 4447): Unquickening 12 vdex files!
W/flutter_weathe( 4447): Unexpected CPU variant for X86 using defaults: x86
I/flutter_weathe( 4447): The ClassLoaderContext is a special shared library.
W/flutter_weather( 4447): type=1400 audit(0.0:39): avc: denied { read } for name="max_map_count" dev="proc" ino=54144 scontext=u:r:untrusted_app:s0:c153,c256,c512,c768 tcontext=u:object_r:proc_max_map_count:s0 tclass=file permissive=0 app=com.example.flutter_weather
W/flutter_weathe( 4447): Accessing hidden method Landroid/view/accessibility/AccessibilityNodeInfo;->getSourceNodeId()J (greylist,test-api, reflection, allowed)
W/flutter_weathe( 4447): Accessing hidden method Landroid/view/accessibility/AccessibilityRecord;->getSourceNodeId()J (greylist, reflection, allowed)
W/flutter_weathe( 4447): Accessing hidden field Landroid/view/accessibility/AccessibilityNodeInfo;->mChildNodeIds:Landroid/util/LongArray; (greylist, reflection, allowed)
W/flutter_weathe( 4447): Accessing hidden method Landroid/util/LongArray;->get(I)J (greylist, reflection, allowed)
W/flutter_weathe( 4447): Accessing hidden method Landroid/app/ActivityThread;->currentActivityThread()Landroid/app/ActivityThread; (greylist, linking, allowed)
W/flutter_weathe( 4447): Accessing hidden method Landroid/app/ActivityThread;->getActivity(Landroid/os/IBinder;)Landroid/app/Activity; (greylist, linking, allowed)
E/flutter ( 4447): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Binding does not extend BindingBase
E/flutter ( 4447): An instance of ServicesBinding was created but the BindingBase constructor was not called.
E/flutter ( 4447): This could happen because the binding was implemented using "implements" rather than "extends" or "with". Concrete binding classes must extend or mix in BindingBase.
E/flutter ( 4447): #0      BindingBase.checkInstance.<anonymous closure> (package:flutter/src/foundation/binding.dart:350:9)
E/flutter ( 4447): #1      BindingBase.checkInstance (package:flutter/src/foundation/binding.dart:360:6)
E/flutter ( 4447): #2      ServicesBinding.instance (package:flutter/src/services/binding.dart:48:54)
E/flutter ( 4447): #3      MethodChannel.setMethodCallHandler (package:flutter/src/services/platform_channel.dart:387:51)
E/flutter ( 4447): #4      RestorationManager.initChannels (package:flutter/src/services/restoration.dart:169:32)
E/flutter ( 4447): #5      new RestorationManager (package:flutter/src/services/restoration.dart:157:5)
E/flutter ( 4447): #6      ServicesBinding.createRestorationManager (package:flutter/src/services/binding.dart:296:12)
E/flutter ( 4447): #7      ServicesBinding.initInstances (package:flutter/src/services/binding.dart:34:27)
E/flutter ( 4447): #8      new _StandaloneBindingBase (package:flutter_services_binding/src/flutter_services_binding.dart:31:5)
E/flutter ( 4447): #9      new _FlutterServicesBinding&_StandaloneBindingBase&SchedulerBinding (package:flutter_services_binding/src/flutter_services_binding.dart)
E/flutter ( 4447): #10     new _FlutterServicesBinding&_StandaloneBindingBase&SchedulerBinding&ServicesBinding (package:flutter_services_binding/src/flutter_services_binding.dart)
E/flutter ( 4447): #11     new FlutterServicesBinding._ (package:flutter_services_binding/src/flutter_services_binding.dart)
E/flutter ( 4447): #12     new FlutterServicesBinding.ensureInitialized (package:flutter_services_binding/src/flutter_services_binding.dart:22:49)
E/flutter ( 4447): #13     main (package:flutter_weather/main.dart:11:26)
E/flutter ( 4447): #14     main (file:///Users/camin/bloc/examples/flutter_weather/.dart_tool/flutter_build/generated_main.dart:80:42)
E/flutter ( 4447): #15     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:128:38)
E/flutter ( 4447): #16     _rootRun (dart:async/zone.dart:1426:13)
E/flutter ( 4447): #17     _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter ( 4447): #18     _runZoned (dart:async/zone.dart:1861:10)
E/flutter ( 4447): #19     runZonedGuarded (dart:async/zone.dart:1849:12)
E/flutter ( 4447): #20     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:126:5)
E/flutter ( 4447): #21     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
E/flutter ( 4447): #22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
E/flutter ( 4447): 
Syncing files to device sdk gphone x86 arm...                      229ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on sdk gphone x86 arm is available at:
http://127.0.0.1:61143/kxYYQmRYkUA=/
I/Choreographer( 4447): Skipped 32 frames!  The application may be doing too much work on its main thread.
I/Choreographer( 4447): Skipped 44 frames!  The application may be doing too much work on its main thread.
I/Choreographer( 4447): Skipped 34 frames!  The application may be doing too much work on its main thread.
I/Choreographer( 4447): Skipped 33 frames!  The application may be doing too much work on its main thread.
```

Flutter Doctor:

```
[✓] Flutter (Channel master, 2.11.0-0.0.pre.523, on macOS 11.4 20F71 darwin-x64, locale en-US)
    • Flutter version 2.11.0-0.0.pre.523 at /Users/camin/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e8bc5c5ace (2 hours ago), 2022-02-11 12:05:18 -0800
    • Engine revision bed591d394
    • Dart version 2.17.0 (build 2.17.0-87.0.dev)
    • DevTools version 2.10.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/camin/Library/Android/sdk
    • Platform android-31, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.4 20F71 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 98.0.4758.80
    ! Error: Failed to prepare device for development. Please unlock and reconnect the device. (code 806)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by darshankawar** [comment]
> E/flutter ( 4447): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Binding does not extend BindingBase
> E/flutter ( 4447): An instance of ServicesBinding was created but the BindingBase constructor was not called.
> E/flutter ( 4447): This could happen because the binding was implemented using "implements" rather than "extends" or "with". Concrete binding classes must extend or mix in BindingBase.
> E/flutter ( 4447): #0      BindingBase.checkInstance.<anonymous closure> (package:flutter/src/foundation/binding.dart:350:9)

@Amean 
Can you provide a complete minimal reproducible code sample that shows this behavior ?
Is it only happening with emulator or with a device too ? Can you try a different emulator (latest version) and see if you still get same behavior ?
