### ISSUE TITLE
Failed assertion in `MaterialApp` when theme has a non-opaque `primaryColor` 

### ISSUE THREAD

**Issue by ValentinVignal** [flutter/flutter#98327]
## Steps to Reproduce

1. Run `flutter create flutter_app`
2. Run `cd flutter_app`
3. In the `lib/main.dart` change the `primaryColor` of the theme to a non-opaque color (ex: `Color(0xf00000ff)`).
4. Run `flutter run `lib/main.dart`

**Expected results:** 

It should not crash.

**Actual results:** 

The app crashes with the message:

```
'package:flutter/src/widgets/title.dart': Failed assertion: line 24 pos 15: 'color != null &&
color.alpha == 0xFF': is not true.
```

<details>
<summary>Code sample</summary>

`lib/main.dart` :
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primaryColor: const Color(0xf00000ff),
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
Launching lib/main.dart on macOS in debug mode...
Building macOS application...                                           

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building WidgetsApp-[GlobalObjectKey
_MaterialAppState#854f5](dirty, state: _WidgetsAppState#e7321):
'package:flutter/src/widgets/title.dart': Failed assertion: line 24 pos 15: 'color != null &&
color.alpha == 0xFF': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was:
  MaterialApp MaterialApp:file:///Users/valentin/Projects/flutter_app/lib/main.dart:13:12

When the exception was thrown, this was the stack:
#2      new Title (package:flutter/src/widgets/title.dart:24:15)
#3      _WidgetsAppState.build (package:flutter/src/widgets/app.dart:1644:15)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4705:27)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4588:15)
#6      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#7      Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4566:5)
#9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4754:11)
#10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4561:5)
...     Normal element mounting (44 frames)
#54     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3631:14)
#55     Element.updateChild (package:flutter/src/widgets/framework.dart:3383:18)
#56     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1198:16)
#57     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1167:5)
#58     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure>
(package:flutter/src/widgets/binding.dart:1112:18)
#59     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2531:19)
#60     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1111:13)
#61     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:944:7)
#62     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure>
(package:flutter/src/widgets/binding.dart:924:7)
(elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and
dart:async-patch)

════════════════════════════════════════════════════════════════════════════════════════════════════
Syncing files to device macOS...                                    74ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on macOS is available at: http://127.0.0.1:63113/ewl0kPXUAss=/
The Flutter DevTools debugger and profiler on macOS is available at:
http://127.0.0.1:9101?uri=http://127.0.0.1:63113/ewl0kPXUAss=/
```

```
Analyzing flutter_app...                                                
No issues found! (ran in 1.8s)
```

```
✓] Flutter (Channel stable, 2.8.1, on macOS 11.5.1 20G80 darwin-x64, locale en-GB)
    • Flutter version 2.8.1 at /Users/valentin/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (8 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /usr/local/Caskroom/android-sdk/4333796
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[!] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.0.0.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.64.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.5.1 20G80 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 98.0.4758.80

! Doctor found issues in 2 categories.
```

</details>

<details>

<summary>Screenshot</summary>

<img width="799" alt="image" src="https://user-images.githubusercontent.com/32538273/153709889-2ef9d21d-ce7c-4293-93f8-77299475e9bf.png">

</details>

I believe this could be fix by replacing 

https://github.com/flutter/flutter/blob/350e3ee46d7422c4a17001319b5b5d680b11f7a0/packages/flutter/lib/src/material/app.dart#L900

```dart
    final Color materialColor = widget.color ?? widget.theme?.primaryColor.withAlpha(0xff) ?? Colors.blue;
```

**Comment by ValentinVignal** [comment]
It looks like it is a duplicate of https://github.com/flutter/flutter/issues/93052
