### ISSUE TITLE
[google_sign_in] app crashes when disabling the android pop-up menu

### ISSUE THREAD

**Issue by YoavGenish** [flutter/flutter#98336]
## Steps to Reproduce
1. following the exact steps as in flutterfire.com 
2. code used:
```
Future<UserCredential?> signInWithGoogle() async {
    // Trigger the authentication flow
    final GoogleSignInAccount? googleUser;
    try {
      googleUser = await GoogleSignIn().signIn();
    } catch (e) {
      ScaffoldMessenger.maybeOf(context)
          ?.showSnackBar(const SnackBar(content: Text("Hey there, you didn't logged in!")));
      return null;
    }
    // Obtain the auth details from the request
    final GoogleSignInAuthentication? googleAuth = await googleUser?.authentication;

    // Create a new credential
    final credential = GoogleAuthProvider.credential(
      accessToken: googleAuth?.accessToken,
      idToken: googleAuth?.idToken,
    );

    // Once signed in, return the UserCredential
    return await FirebaseAuth.instance.signInWithCredential(credential);
  }
```
3. used in some button onPressed: () async => signInWithGoogle();
4. dont continue with the proccess of the logging in

## Logs
```
E/flutter (24878): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: 'package:firebase_auth_platform_interface/src/providers/google_auth.dart': Failed assertion: line 43 pos 12: 'accessToken != null || idToken != null': At least one of ID token and access token is required
```
<details>
<summary>E/flutter (24878): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: 'package:firebase_auth_platform_interface/src/providers/google_auth.dart': Failed assertion: line 43 pos 12: 'accessToken != null || idToken != null': At least one of ID token and access token is required
package:firebase_auth_platform_interface/…/providers/google_auth.dart:43
E/flutter (24878): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:47:61)
E/flutter (24878): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter (24878): #2      GoogleAuthProvider.credential
package:firebase_auth_platform_interface/…/providers/google_auth.dart:43
E/flutter (24878): #3      _LoginPageState.signInWithGoogle
package:lysts/pages/login_page.dart:31
E/flutter (24878): <asynchronous suspension>
</summary>

```

therealgenish@genishs-mac-mini lysts % flutter doctor -v
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale he-IL)
    • Flutter version 2.8.1 at /Users/therealgenish/Documents/src/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (8 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/therealgenish/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (2 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12 (API 32) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 98.0.4758.80

• No issues found!

```

</details>

**Comment by mozochek** [comment]
Thats your falt, you perform signing in even if popup was dismissed. You need to check 'googleUser' and if it's null, then you shouldn't perform sign in via firebase.

**Comment by maheshmnj** [comment]
Hi @YoavGenish, Thanks for filing the issue. Please share a minimal and complete code sample along with the plugins used in your `pubspec.yaml`. Also, is the crash happening on Android or IOS or both

Thanks

**Comment by mozochek** [comment]
> Hi @YoavGenish, Thanks for filing the issue. Please share a minimal and complete code sample which we can copy and directly run, along with the plugins used in your `pubspec.yaml`. Also, is the crash happening on Android or IOS or both
> 
> Thanks

HI, don't you see this logs? It's not a plugin side issue, it crushes because of this code:
```dart
    final credential = GoogleAuthProvider.credential(
      accessToken: googleAuth?.accessToken,
      idToken: googleAuth?.idToken,
    );
```
Here can be all the values null and then this assertion catch the problem:
```
E/flutter (24878): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: 'package:firebase_auth_platform_interface/src/providers/google_auth.dart': Failed assertion: line 43 pos 12: 'accessToken != null || idToken != null': At least one of ID token and access token is required
package:firebase_auth_platform_interface/…/providers/google_auth.dart:43
```

**Comment by YoavGenish** [comment]
although @mozochek has a point the bug is still there. I'm closing the issue for now and will post a new one with all the required steps to replicate the problem.
