### ISSUE TITLE
java.lang.ClassNotFoundException  androidx.activity.OnBackPressedDispatcherOwner at io.flutter.plugin.platform.PlatformPlugin.popSystemNavigator(Unknown Source:13)

### ISSUE THREAD

**Issue by Wisdozzh** [flutter/flutter#98387]
Root cause:

```console
[+5050 ms] E/AndroidRuntime( 3772): FATAL EXCEPTION: main
[   +2 ms] E/AndroidRuntime( 3772): Process: com.jelly.medianoter, PID: 3772
[   +1 ms] E/AndroidRuntime( 3772): java.lang.NoClassDefFoundError: Failed resolution of:
Landroidx/activity/OnBackPressedDispatcherOwner;
[   +3 ms] E/AndroidRuntime( 3772):     at
io.flutter.plugin.platform.PlatformPlugin.popSystemNavigator(PlatformPlugin.java:318)
[   +1 ms] E/AndroidRuntime( 3772):     at io.flutter.plugin.platform.PlatformPlugin.access$600(PlatformPlugin.java:28)
[   +3 ms] E/AndroidRuntime( 3772):     at
io.flutter.plugin.platform.PlatformPlugin$1.popSystemNavigator(PlatformPlugin.java:101)
[   +1 ms] E/AndroidRuntime( 3772):     at
io.flutter.embedding.engine.systemchannels.PlatformChannel$1.onMethodCall(PlatformChannel.java:123)
[   +2 ms] E/AndroidRuntime( 3772):     at
io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
[   +1 ms] E/AndroidRuntime( 3772):     at
io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
[   +5 ms] E/AndroidRuntime( 3772):     at
io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
[   +4 ms] E/AndroidRuntime( 3772):     at android.os.MessageQueue.nativePollOnce(Native Method)
[   +1 ms] E/AndroidRuntime( 3772):     at android.os.MessageQueue.next(MessageQueue.java:363)
[   +2 ms] E/AndroidRuntime( 3772):     at android.os.Looper.loop(Looper.java:176)
[   +2 ms] E/AndroidRuntime( 3772):     at android.app.ActivityThread.main(ActivityThread.java:8387)
[   +2 ms] E/AndroidRuntime( 3772):     at java.lang.reflect.Method.invoke(Native Method)
[   +1 ms] E/AndroidRuntime( 3772):     at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
[   +1 ms] E/AndroidRuntime( 3772):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
[   +1 ms] E/AndroidRuntime( 3772): Caused by: java.lang.ClassNotFoundException: Didn't find class
"androidx.activity.OnBackPressedDispatcherOwner" on path: DexPathList[[zip file
"/data/app/com.jelly.medianoter-pP8csWG7GHq2NAkix0gG5g==/base.apk"],nativeLibraryDirectories=[/data/app/com.jelly.median
oter-pP8csWG7GHq2NAkix0gG5g==/lib/arm64,
/data/app/com.jelly.medianoter-pP8csWG7GHq2NAkix0gG5g==/base.apk!/lib/arm64-v8a, /system/lib64, /hw_product/lib64,
/system/product/lib64]]
```

I was not able to reproduce this on emulator with Android 11. @sinojelly are you able to reproduce this issue on Emulator?
It would help if you are able to provide a minimal code that reproduces this issue.
Thank you

_Originally posted by @pedromassangocode in https://github.com/flutter/flutter/issues/76183#issuecomment-780580869_

**Comment by Wisdozzh** [comment]
I also met this problem.
finally I solve this problem add implementation in build.gradle
`
implementation 'androidx.activity:activity:1.0.0'
`
but I don't know why did this problem only appear recently?

**Comment by maheshmnj** [comment]
Closing as solved based on the above response, Incase you disagree feel free to write in the comments and we will reopen it.

Thank you.
