### ISSUE TITLE
[flutter_tools] custom devices tests were not running on CI

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#98436]
A test file was not running on CI because it did not end in `_test.dart`: https://github.com/flutter/flutter/blob/024d5f8aaa7a4618fd583563bdbfd42f524c0040/packages/flutter_tools/test/commands.shard/hermetic/custom_devices.dart. When I ran it, 6 tests were failing, such as:

```
00:01 +6: linux custom-devices add command correctly adds ssh device config on linux
Could not load custom device from config index 0: Expected postBuild to be null or array of strings with at least one element.
#0      CustomDevicesConfig.devices (package:flutter_tools/src/custom_devices/custom_devices_config.dart:144:9)
#1      main.<anonymous closure>.<anonymous closure> (file:///Users/fujino/git/flutter/packages/flutter_tools/test/commands.shard/hermetic/custom_devices_test.dart:542:18)
<asynchronous suspension>
#2      testUsingContext.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///Users/fujino/git/flutter/packages/flutter_tools/test/src/context.dart:143:26)
<asynchronous suspension>
#3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#6      testUsingContext.<anonymous closure> (file:///Users/fujino/git/flutter/packages/flutter_tools/test/src/context.dart:104:5)
<asynchronous suspension>
#7      Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:215:9)
<asynchronous suspension>
#8      Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:213:7)
<asynchronous suspension>
#9      Invoker._waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:257:7)
<asynchronous suspension>

00:01 +6 -1: linux custom-devices add command correctly adds ssh device config on linux [E]
  Could not load custom device from config index 0: Expected postBuild to be null or array of strings with at least one element.
  package:flutter_tools/src/custom_devices/custom_devices_config.dart 144:9  CustomDevicesConfig.devices
  test/commands.shard/hermetic/custom_devices_test.dart 542:18               main.<fn>.<fn>
  ===== asynchronous gap ===========================
  test/src/context.dart 143:26                                               testUsingContext.<fn>.<fn>.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  package:flutter_tools/src/base/context.dart 150:19                         AppContext.run.<fn>
  ===== asynchronous gap ===========================
  package:flutter_tools/src/base/context.dart 150:19                         AppContext.run.<fn>
  ===== asynchronous gap ===========================
  package:flutter_tools/src/base/context.dart 150:19                         AppContext.run.<fn>
  ===== asynchronous gap ===========================
  test/src/context.dart 104:5                                                testUsingContext.<fn>
```

I have also seen this error locally, so there may be a real regression with the custom devices system.

**Comment by ardera** [comment]
Oh wow I didn't know the test files need to end in `_test`. I'll look into it

**Comment by christopherfujino** [comment]
> Oh wow I didn't know the test files need to end in `_test`. I'll look into it

it's a fun little easter egg.
