### ISSUE TITLE
Force Close After Run IFRAME on HTML or WEBVIEW FLUTTER ANDROID

### ISSUE THREAD

**Issue by muhamadkautsar** [flutter/flutter#98454]
Maybe you guys can help me with the problem i'm facing.

So the problem is: When the article is first opened and the iframe is run it does not force close but when the article is closed and opened again immediately force close.

And below the error when force close:
```
E/AndroidRuntime(25677): java.lang.NullPointerException: Attempt to read from field 'android.view.WindowManager$LayoutParams android.view.ViewRootImpl.mWindowAttri
butes' on a null object reference
E/AndroidRuntime(25677):        at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1627)
E/AndroidRuntime(25677):        at android.view.inputmethod.InputMethodManager.checkFocus(InputMethodManager.java:1871)
E/AndroidRuntime(25677):        at android.view.inputmethod.InputMethodManager.isActive(InputMethodManager.java:1183)
E/AndroidRuntime(25677):        at io.flutter.plugins.webviewflutter.InputAwareWebView$1.run(InputAwareWebView.java:195)
E/AndroidRuntime(25677):        at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime(25677):        at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(25677):        at android.os.Looper.loop(Looper.java:224)
E/AndroidRuntime(25677):        at android.app.ActivityThread.main(ActivityThread.java:7562)
E/AndroidRuntime(25677):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(25677):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/AndroidRuntime(25677):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

And below is the code from article_details.dart:
```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_icons/flutter_icons.dart';
import 'package:news/blocs/ads_bloc.dart';
import 'package:news/blocs/bookmark_bloc.dart';
import 'package:news/blocs/sign_in_bloc.dart';
import 'package:news/blocs/theme_bloc.dart';
import 'package:news/models/article.dart';
import 'package:news/models/custom_color.dart';
import 'package:news/pages/comments.dart';
import 'package:news/services/app_service.dart';
import 'package:news/utils/cached_image.dart';
import 'package:news/utils/sign_in_dialog.dart';
import 'package:news/widgets/banner_ad_admob.dart';     //admob
import 'package:news/widgets/bookmark_icon.dart';
import 'package:news/widgets/html_body.dart';
import 'package:news/widgets/love_count.dart';
import 'package:news/widgets/love_icon.dart';
import 'package:news/widgets/related_articles.dart';
import 'package:news/widgets/views_count.dart';
import 'package:share/share.dart';
import 'package:provider/provider.dart';
import 'dart:io';
import 'package:easy_localization/easy_localization.dart';
import '../utils/next_screen.dart';

class ArticleDetails extends StatefulWidget {
  final Article? data;
  final String? tag;

  const ArticleDetails({Key? key, required this.data, required this.tag})
      : super(key: key);

  @override
  _ArticleDetailsState createState() => _ArticleDetailsState();
}

class _ArticleDetailsState extends State<ArticleDetails> {


  double rightPaddingValue = 130;

  void _handleShare() {
    final sb = context.read<SignInBloc>();
    final String _shareTextAndroid = '${widget.data!.title}, Check out this app to explore more. App link: https://play.google.com/store/apps/details?id=${sb.packageName}';
    final String _shareTextiOS = '${widget.data!.title}, Check out this app to explore more. App link: https://play.google.com/store/apps/details?id=${sb.packageName}';

    if (Platform.isAndroid) {
      Share.share(_shareTextAndroid);
    } else{
      Share.share(_shareTextiOS);
    }
  }

  handleLoveClick() {
    bool _guestUser = context.read<SignInBloc>().guestUser;

    if (_guestUser == true) {
      openSignInDialog(context);
    } else {
      context.read<BookmarkBloc>().onLoveIconClick(widget.data!.timestamp);
    }
  }

  handleBookmarkClick() {
    bool _guestUser = context.read<SignInBloc>().guestUser;

    if (_guestUser == true) {
      openSignInDialog(context);
    } else {
      context.read<BookmarkBloc>().onBookmarkIconClick(widget.data!.timestamp);
    }
  }

  @override
  void initState() {
    super.initState();
    Future.delayed(Duration(milliseconds: 100)).then((value) {
      setState(() {
        rightPaddingValue = 10;
      });
    });
  }

  @override
  void dispose() {
    super.dispose();
  }


  @override
  Widget build(BuildContext context) {
    final sb = context.watch<SignInBloc>();
    final Article article = widget.data!;

    return Scaffold(
        resizeToAvoidBottomInset: false,
        body: SafeArea(
          bottom: true,
          top: false,
          maintainBottomViewPadding: true,
          child: Column(
            children: [
              Expanded(
                child: CustomScrollView(
                  slivers: <Widget>[
                    _customAppBar(article, context),
                    SliverToBoxAdapter(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: <Widget>[
                          Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: <Widget>[
                                Padding(
                                  padding: const EdgeInsets.fromLTRB(20, 15, 20, 10),
                                  child: Column(
                                    crossAxisAlignment: CrossAxisAlignment.start,
                                    children: [
                                      Row(
                                  children: <Widget>[
                                    Container(
                                        alignment: Alignment.center,
                                        decoration: BoxDecoration(
                                          borderRadius: BorderRadius.circular(5),
                                          color: context.watch<ThemeBloc>().darkTheme == false
                                              ? CustomColor().loadingColorLight
                                              : CustomColor().loadingColorDark,
                                        ),
                                        child: AnimatedPadding(
                                          duration: Duration(milliseconds: 1000),
                                          padding: EdgeInsets.only(
                                              left: 10,
                                              right: rightPaddingValue,
                                              top: 5,
                                              bottom: 5),
                                          child: Text(
                                            article.category!,
                                            style: TextStyle(
                                                fontSize: 15,
                                                fontWeight: FontWeight.w600),
                                          ),
                                        )),
                                    Spacer(),
                                    IconButton(
                                        icon: BuildLoveIcon(
                                            collectionName: 'contents',
                                            uid: sb.uid,
                                            timestamp: article.timestamp),
                                        onPressed: () {
                                          handleLoveClick();
                                        }),
                                    IconButton(
                                        icon: BuildBookmarkIcon(
                                            collectionName: 'contents',
                                            uid: sb.uid,
                                            timestamp: article.timestamp),
                                        onPressed: () {
                                          handleBookmarkClick();
                                        }),
                                  ],
                                ),
                                SizedBox(
                                  height: 10,
                                ),
                                Row(
                                  children: <Widget>[
                                    Icon(CupertinoIcons.time_solid,
                                        size: 18, color: Colors.grey),
                                    SizedBox(
                                      width: 5,
                                    ),
                                    Text(
                                      article.date!,
                                      style: TextStyle(
                                        color: Theme.of(context).secondaryHeaderColor,
                                        fontSize: 12),
                                    ),
                                  ],
                                ),
                                SizedBox(
                                  height: 5,
                                ),
                                Text(
                                  article.title!,
                                  style: TextStyle(
                                    fontSize: 20,
                                    fontWeight: FontWeight.bold,
                                    letterSpacing: -0.6,
                                    wordSpacing: 1
                                  ),
                                ),
                                Divider(
                                  color: Theme.of(context).primaryColor,
                                  endIndent: 200,
                                  thickness: 2,
                                  height: 20,
                                ),

                                TextButton.icon(
                                      style: ButtonStyle(
                                        padding: MaterialStateProperty.resolveWith((states) => EdgeInsets.only(left: 10, right: 10)),
                                        backgroundColor: MaterialStateProperty.resolveWith((states) => Theme.of(context).primaryColor),
                                        shape:MaterialStateProperty.resolveWith((states) => RoundedRectangleBorder(borderRadius:BorderRadius.circular(3))),
                                      ),
                                      icon: Icon(Feather.message_circle,color: Colors.white, size: 20),
                                      label: Text('comments',style: TextStyle(color: Colors.white)).tr(),
                                      onPressed: () {
                                        nextScreen(context,CommentsPage(timestamp: article.timestamp));
                                      },
                                ),

                                SizedBox(height: 10,),

                                Row(
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  children: <Widget>[
                                    
                                    //views feature
                                    ViewsCount(article: article,),
                                    SizedBox(width: 20,),

                                    LoveCount(collectionName: 'contents',timestamp: article.timestamp),
                                    
                                    
                                  ],
                                ),
                                    ],
                                  ),
                                ),
                                
                                HtmlBodyWidget(
                                  content: article.description!,
                                  isIframeVideoEnabled: true,
                                  isVideoEnabled: true,
                                  isimageEnabled: true,
                                ),
                                SizedBox(
                                  height: 20,
                                ),
                              ],
                            ),
                          Container(
                              padding: EdgeInsets.all(20),
                              child: RelatedArticles(
                                category: article.category,
                                timestamp: article.timestamp,
                                replace: true,
                              )),
                        ],
                      ),
                    ),
                  ],
                ),
              ),
              
              

              // -- Banner ads --
              
              context.watch<AdsBloc>().bannerAdEnabled == false ? Container()
              : BannerAdAdmob()   //admob
              //: BannerAdFb()    //fb
            ],
          ),
        ));
  }

  

  SliverAppBar _customAppBar(Article article, BuildContext context) {
    return SliverAppBar(
      expandedHeight: 270,
      flexibleSpace: FlexibleSpaceBar(
          background: widget.tag == null
              ? CustomCacheImage(imageUrl: article.thumbnailImagelUrl, radius: 0.0)
              : Hero(
                  tag: widget.tag!,
                  child: CustomCacheImage(imageUrl: article.thumbnailImagelUrl, radius: 0.0),
                )),
      leading: IconButton(
        icon: const Icon(Icons.keyboard_backspace, size: 22, color: Colors.white),
        onPressed: () {
          Navigator.pop(context);
        },
      ),
      actions: <Widget>[


        article.sourceUrl == null 
        ? Container()
        : IconButton(
          icon: const Icon(Feather.external_link, size: 22, color: Colors.white),
          onPressed: ()=> AppService().openLinkWithCustomTab(context, article.sourceUrl!),
        ), 

        IconButton(
          icon: const Icon(Icons.share, size: 22, color: Colors.white),
          onPressed: () {
            _handleShare();
          },
        ),
        SizedBox(
          width: 5,
        )
      ],
    );
  }
}

```

And below is the code from html_body.dart:
```
import 'package:flutter/material.dart';
import 'package:flutter_html/flutter_html.dart';
import 'package:inspireyou/blocs/theme_bloc.dart';
import 'package:inspireyou/models/custom_color.dart';
import 'package:provider/provider.dart';

  final String demoText = "<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s</p>" +
  '''<iframe width="560" height="315" src="https://www.youtube.com/embed/-WRzl9L4z3g" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'''+
  "<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s</p>";

class HtmlBodyWidget extends StatelessWidget {

  final String content;
  final bool isVideoEnabled;
  final bool isimageEnabled;
  final bool isIframeVideoEnabled;
  final double? fontSize;


  const HtmlBodyWidget({
    Key? key,
    required this.content, required this.isVideoEnabled, required this.isimageEnabled, required this.isIframeVideoEnabled, this.fontSize,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Html(
      // data: '''$content''',
      data: '''$demoText''',
      style: {
        "body": Style(
          margin: EdgeInsets.zero,
          
          padding: EdgeInsets.all(20),
          
          fontSize: fontSize == null ? FontSize(18.0) : FontSize(16.0),
          lineHeight: LineHeight(1.7),
          fontFamily: 'Open Sans',
          fontWeight: FontWeight.w400,
          color: context.watch<ThemeBloc>().darkTheme == false 
            ? CustomColor().bodyTextColorLight 
            : CustomColor().bodyTextColorDark,
        ),
        "figure": Style(margin: EdgeInsets.zero, padding: EdgeInsets.zero),

        "p,h1,h2,h3,h4,h5,h6": Style(margin: EdgeInsets.all(20)),
      },
      );
  }
}
```

**Comment by darshankawar** [comment]
@muhamadkautsar 
Although the crash log you provided is same as https://github.com/flutter/flutter/issues/93641, but we would need a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without any 3rd party plugins, that replicates the crash you reported, along with `flutter doctor -v` and exact steps to replicate.

Thanks.
