### ISSUE TITLE
Flutter Web - Assertion failed: !_debugNeedsLayout for AppBar

### ISSUE THREAD

**Issue by kornha** [flutter/flutter#98463]
This is in 2.10.1 but also in earlier versions.
I cannot reproduce this consistently, it occurs intermittently with the appearance of a page. I have a suspicion that it is related to my app bar code, as it appears to not exist without the code:

```
      appBar: const PreferredSize(
        preferredSize: Size.fromHeight(Constants.BarHeight),
        child: ZLandingMenuBar(),
      ),
```
Which eventually calls - 
```
class ZMenuBar extends StatelessWidget {
  const ZMenuBar({Key? key, required this.children, this.color})
      : super(key: key);

  final List<Widget> children;
  final Color? color;

  @override
  Widget build(BuildContext context) {
    return Container(
      height: Constants.BarHeight,
      decoration: BoxDecoration(color: color ?? context.backgroundColor),
      child: Row(
        children: children,
      ),
    );
  }
}
```
I was curious if the dual height settings could cause a problem but I'm unsure.

<details>
  <summary>logs</summary>
  
```
Assertion failed:
../…/painting/text_painter.dart:953
!_debugNeedsLayout
is not true
    at Object.throw_ [as throw] ([http://localhost:5000/dart_sdk.js:5067:11]())
    at Object.assertFailed ([http://localhost:5000/dart_sdk.js:4992:15]())
at text_painter.TextPainter.new.getPositionForOffset ([http://localhost:5000/packages/flutter/src/painting/placeholder_span.dart.lib.js:2371:43]())
at paragraph.RenderParagraph.new.hitTestChildren ([http://localhost:5000/packages/flutter/src/rendering/paragraph.dart.lib.js:602:45]())
at paragraph.RenderParagraph.new.hitTest ([http://localhost:5000/packages/flutter/src/rendering/layer.dart.lib.js:4452:18]())
at proxy_box.RenderTransform.new.hitTestChildren ([http://localhost:5000/packages/flutter/src/rendering/proxy_box.dart.lib.js:437:56]())
at [http://localhost:5000/packages/flutter/src/rendering/proxy_box.dart.lib.js:2625:179]()
at box.BoxHitTestResult.wrap.addWithRawTransform ([http://localhost:5000/packages/flutter/src/rendering/layer.dart.lib.js:7815:19]())
at box.BoxHitTestResult.wrap.addWithPaintTransform ([http://localhost:5000/packages/flutter/src/rendering/layer.dart.lib.js:7786:19]())
at proxy_box.RenderTransform.new.hitTestChildren ([http://localhost:5000/packages/flutter/src/rendering/proxy_box.dart.lib.js:2625:21]())
at proxy_box.RenderTransform.new.hitTest ([http://localhost:5000/packages/flutter/src/rendering/proxy_box.dart.lib.js:2620:19]())
at proxy_box.RenderAnimatedOpacity.new.hitTestChildren ([http://localhost:5000/packages/flutter/src/rendering/proxy_box.dart.lib.js:437:56]())
at proxy_box.RenderAnimatedOpacity.new.hitTest ([http://localhost:5000/packages/flutter/src/rendering/layer.dart.lib.js:4452:18]())
at [http://localhost:5000/packages/flutter/src/rendering/shifted_box.dart.lib.js:149:47]()
at box.BoxHitTestResult.wrap.addWithPaintOffset ([http://localhost:5000/packages/flutter/src/rendering/layer.dart.lib.js:7798:19]())
at shifted_box.RenderPositionedBox.new.hitTestChildren ([http://localhost:5000/packages/flutter/src/rendering/shifted_box.dart.lib.js:147:23]())
at shifted_box.RenderPositionedBox.new.hitTest ([http://localhost:5000/packages/flutter/src/rendering/layer.dart.lib.js:4452:18]())
at proxy_box.RenderConstrainedBox.new.hitTestChildren ([http://localhost:5000/packages/flutter/src/rendering/proxy_box.dart.lib.js:437:56]())
at proxy_box.RenderConstrainedBox.new.hitTest ([http://localhost:5000/packages/flutter/src/rendering/layer.dart.lib.js:4452:18]())
at [http://localhost:5000/packages/flutter/src/rendering/layer.dart.lib.js:8048:44]()
at box.BoxHitTestResult.wrap.addWithPaintOffset ([http://localhost:5000/packages/flutter/src/rendering/layer.dart.lib.js:7798:19]())
at stack.RenderStack.new.defaultHitTestChildren ([http://localhost:5000/packages/flutter/src/rendering/layer.dart.lib.js:8046:30]())
at stack.RenderStack.new.hitTestChildren ([http://localhost:5000/packages/flutter/src/rendering/stack.dart.lib.js:614:19]())
at stack.RenderStack.new.hitTest ([http://localhost:5000/packages/flutter/src/rendering/layer.dart.lib.js:4452:18]())
at proxy_box.RenderConstrainedBox.new.hitTestChildren ([http://localhost:5000/packages/flutter/src/rendering/proxy_box.dart.lib.js:437:56]())
at proxy_box.RenderConstrainedBox.new.hitTest ([http://localhost:5000/packages/flutter/src/rendering/layer.dart.lib.js:4452:18]())
at proxy_box.RenderRepaintBoundary.new.hitTestChildren ([http://localhost:5000/packages/flutter/src/rendering/proxy_box.dart.lib.js:437:56]())
at proxy_box.RenderRepaintBoundary.new.hitTest ([http://localhost:5000/packages/flutter/src/rendering/layer.dart.lib.js:4452:18]())
at [http://localhost:5000/packages/flutter/src/rendering/shifted_box.dart.lib.js:149:47]()
at box.BoxHitTestResult.wrap.addWithPaintOffset ([http://localhost:5000/packages/flutter/src/rendering/layer.dart.lib.js:7798:19]())
at shifted_box.RenderPositionedBox.new.hitTestChildren ([http://localhost:5000/packages/flutter/src/rendering/shifted_box.dart.lib.js:147:23]())
at shifted_box.RenderPositionedBox.new.hitTest ([http://localhost:5000/packages/flutter/src/rendering/layer.dart.lib.js:4452:18]())
at proxy_box.RenderConstrainedBox.new.hitTestChildren ([http://localhost:5000/packages/flutter/src/rendering/proxy_box.dart.lib.js:437:56]())
at proxy_box.RenderConstrainedBox.new.hitTest ([http://localhost:5000/packages/flutter/src/rendering/layer.dart.lib.js:4452:18]())
at proxy_box.RenderFittedBox.new.hitTestChildren ([http://localhost:5000/packages/flutter/src/rendering/proxy_box.dart.lib.js:437:56]())
at [http://localhost:5000/packages/flutter/src/rendering/proxy_box.dart.lib.js:2935:138]()
at box.BoxHitTestResult.wrap.addWithRawTransform ([http://localhost:5000/packages/flutter/src/rendering/layer.dart.lib.js:7815:19]())
at box.BoxHitTestResult.wrap.addWithPaintTransform ([http://localhost:5000/packages/flutter/src/rendering/layer.dart.lib.js:7786:19]())
at proxy_box.RenderFittedBox.new.hitTestChildren ([http://localhost:5000/packages/flutter/src/rendering/proxy_box.dart.lib.js:2935:21]())
at proxy_box.RenderFittedBox.new.hitTest ([http://localhost:5000/packages/flutter/src/rendering/layer.dart.lib.js:4452:18]())
at proxy_box.RenderConstrainedBox.new.hitTestChildren ([http://localhost:5000/packages/flutter/src/rendering/proxy_box.dart.lib.js:437:56]())
at proxy_box.RenderConstrainedBox.new.hitTest ([http://localhost:5000/packages/flutter/src/rendering/layer.dart.lib.js:4452:18]())
at [http://localhost:5000/packages/flutter/src/rendering/layer.dart.lib.js:8048:44]()
at box.BoxHitTestResult.wrap.addWithPaintOffset ([http://localhost:5000/packages/flutter/src/rendering/layer.dart.lib.js:7798:19]())
at stack.RenderStack.new.defaultHitTestChildren ([http://localhost:5000/packages/flutter/src/rendering/layer.dart.lib.js:8046:30]())
at stack.RenderStack.new.hitTestChildren ([http://localhost:5000/packages/flutter/src/rendering/stack.dart.lib.js:614:19]())
at stack.RenderStack.new.hitTest ([http://localhost:5000/packages/flutter/src/rendering/layer.dart.lib.js:4452:18]())
at proxy_box.RenderRepaintBoundary.new.hitTestChildren ([http://localhost:5000/packages/flutter/src/rendering/proxy_box.dart.lib.js:437:56]())
at proxy_box.RenderRepaintBoundary.new.hitTest ([http://localhost:5000/packages/flutter/src/rendering/layer.dart.lib.js:4452:18]())
at proxy_box.RenderIndexedSemantics.new.hitTestChildren ([http://localhost:5000/packages/flutter/src/rendering/proxy_box.dart.lib.js:437:56]())
at proxy_box.RenderIndexedSemantics.new.hitTest ([http://localhost:5000/packages/flutter/src/rendering/layer.dart.lib.js:4452:18]())
at [http://localhost:5000/packages/flutter/src/rendering/sliver.dart.lib.js:1337:106]()
at box.BoxHitTestResult.wrap.addWithOutOfBandPosition ([http://localhost:5000/packages/flutter/src/rendering/layer.dart.lib.js:7838:19]())
at sliver_list.RenderSliverList.new.hitTestBoxChild ([http://localhost:5000/packages/flutter/src/rendering/sliver.dart.lib.js:1337:21]())
at sliver_list.RenderSliverList.new.hitTestChildren ([http://localhost:5000/packages/flutter/src/rendering/sliver_multi_box_adaptor.dart.lib.js:505:18]())
at sliver_list.RenderSliverList.new.hitTest ([http://localhost:5000/packages/flutter/src/rendering/sliver.dart.lib.js:977:18]())
at sliver$.SliverHitTestResult.wrap.addWithAxisOffset ([http://localhost:5000/packages/flutter/src/rendering/sliver.dart.lib.js:795:19]())
at sliver_padding.RenderSliverPadding.new.hitTestChildren ([http://localhost:5000/packages/flutter/src/rendering/sliver_padding.dart.lib.js:221:16]())
at sliver_padding.RenderSliverPadding.new.hitTest ([http://localhost:5000/packages/flutter/src/rendering/sliver.dart.lib.js:977:18]())
at [http://localhost:5000/packages/flutter/src/rendering/sliver.dart.lib.js:1932:116]()
at box.BoxHitTestResult.wrap.addWithOutOfBandPosition ([http://localhost:5000/packages/flutter/src/rendering/layer.dart.lib.js:7838:19]())
at viewport.RenderShrinkWrappingViewport.new.hitTestChildren ([http://localhost:5000/packages/flutter/src/rendering/sliver.dart.lib.js:1932:30]())
at viewport.RenderShrinkWrappingViewport.new.hitTest ([http://localhost:5000/packages/flutter/src/rendering/layer.dart.lib.js:4452:18]())
at proxy_box.RenderIgnorePointer.new.hitTestChildren ([http://localhost:5000/packages/flutter/src/rendering/proxy_box.dart.lib.js:437:56]())
at proxy_box.RenderIgnorePointer.new.hitTest ([http://localhost:5000/packages/flutter/src/rendering/layer.dart.lib.js:4452:18]())
at proxy_box.RenderIgnorePointer.new.hitTest ([http://localhost:5000/packages/flutter/src/rendering/proxy_box.dart.lib.js:3470:38]())
at proxy_box.RenderSemanticsAnnotations.new.hitTestChildren ([http://localhost:5000/packages/flutter/src/rendering/proxy_box.dart.lib.js:437:56]())
at proxy_box.RenderSemanticsAnnotations.new.hitTest ([http://localhost:5000/packages/flutter/src/rendering/layer.dart.lib.js:4452:18]())
at proxy_box.RenderPointerListener.new.hitTestChildren ([http://localhost:5000/packages/flutter/src/rendering/proxy_box.dart.lib.js:437:56]())
at proxy_box.RenderPointerListener.new.hitTest ([http://localhost:5000/packages/flutter/src/rendering/proxy_box.dart.lib.js:527:26]())
at proxy_box.RenderSemanticsGestureHandler.new.hitTestChildren ([http://localhost:5000/packages/flutter/src/rendering/proxy_box.dart.lib.js:437:56]())
at proxy_box.RenderSemanticsGestureHandler.new.hitTest ([http://localhost:5000/packages/flutter/src/rendering/proxy_box.dart.lib.js:527:26]())
at proxy_box.RenderPointerListener.new.hitTestChildren ([http://localhost:5000/packages/flutter/src/rendering/proxy_box.dart.lib.js:437:56]())
at proxy_box.RenderPointerListener.new.hitTest ([http://localhost:5000/packages/flutter/src/rendering/proxy_box.dart.lib.js:527:26]())
at scrollable$._RenderScrollSemantics.new.hitTestChildren ([http://localhost:5000/packages/flutter/src/rendering/proxy_box.dart.lib.js:437:56]())
at scrollable$._RenderScrollSemantics.new.hitTest ([http://localhost:5000/packages/flutter/src/rendering/layer.dart.lib.js:4452:18]())
at proxy_box.RenderRepaintBoundary.new.hitTestChildren ([http://localhost:5000/packages/flutter/src/rendering/proxy_box.dart.lib.js:437:56]())
at proxy_box.RenderRepaintBoundary.new.hitTest ([http://localhost:5000/packages/flutter/src/rendering/layer.dart.lib.js:4452:18]())
at custom_paint.RenderCustomPaint.new.hitTestChildren ([http://localhost:5000/packages/flutter/src/rendering/proxy_box.dart.lib.js:437:56]())
at custom_paint.RenderCustomPaint.new.hitTestChildren ([http://localhost:5000/packages/flutter/src/rendering/custom_paint.dart.lib.js:325:20]())
at custom_paint.RenderCustomPaint.new.hitTest ([http://localhost:5000/packages/flutter/src/rendering/layer.dart.lib.js:4452:18]())
at proxy_box.RenderMouseRegion.new.hitTestChildren ([http://localhost:5000/packages/flutter/src/rendering/proxy_box.dart.lib.js:437:56]())
at proxy_box.RenderMouseRegion.new.hitTest ([http://localhost:5000/packages/flutter/src/rendering/layer.dart.lib.js:4452:18]())
at proxy_box.RenderMouseRegion.new.hitTest ([http://localhost:5000/packages/flutter/src/rendering/proxy_box.dart.lib.js:3246:20]())
at proxy_box.RenderPointerListener.new.hitTestChildren ([http://localhost:5000/packages/flutter/src/rendering/proxy_box.dart.lib.js:437:56]())
at proxy_box.RenderPointerListener.new.hitTest ([http://localhost:5000/packages/flutter/src/rendering/proxy_box.dart.lib.js:527:26]())
at proxy_box.RenderSemanticsGestureHandler.new.hitTestChildren ([http://localhost:5000/packages/flutter/src/rendering/proxy_box.dart.lib.js:437:56]())
at proxy_box.RenderSemanticsGestureHandler.new.hitTest ([http://localhost:5000/packages/flutter/src/rendering/proxy_box.dart.lib.js:527:26]())
at proxy_box.RenderRepaintBoundary.new.hitTestChildren ([http://localhost:5000/packages/flutter/src/rendering/proxy_box.dart.lib.js:437:56]())
at proxy_box.RenderRepaintBoundary.new.hitTest ([http://localhost:5000/packages/flutter/src/rendering/layer.dart.lib.js:4452:18]())
at [http://localhost:5000/packages/flutter/src/rendering/layer.dart.lib.js:8048:44]()
at box.BoxHitTestResult.wrap.addWithPaintOffset ([http://localhost:5000/packages/flutter/src/rendering/layer.dart.lib.js:7798:19]())
at custom_layout.RenderCustomMultiChildLayoutBox.new.defaultHitTestChildren ([http://localhost:5000/packages/flutter/src/rendering/layer.dart.lib.js:8046:30]())
at custom_layout.RenderCustomMultiChildLayoutBox.new.hitTestChildren ([http://localhost:5000/packages/flutter/src/rendering/custom_layout.dart.lib.js:283:19]())
at custom_layout.RenderCustomMultiChildLayoutBox.new.hitTest ([http://localhost:5000/packages/flutter/src/rendering/layer.dart.lib.js:4452:18]())
at material._RenderInkFeatures.new.hitTestChildren ([http://localhost:5000/packages/flutter/src/rendering/proxy_box.dart.lib.js:437:56]())
at material._RenderInkFeatures.new.hitTest ([http://localhost:5000/packages/flutter/src/rendering/layer.dart.lib.js:4452:18]())
at proxy_box.RenderPhysicalModel.new.hitTestChildren ([http://localhost:5000/packages/flutter/src/rendering/proxy_box.dart.lib.js:437:56]())
at proxy_box.RenderPhysicalModel.new.hitTest ([http://localhost:5000/packages/flutter/src/rendering/layer.dart.lib.js:4452:18]())
at proxy_box.RenderPhysicalModel.new.hitTest ([http://localhost:5000/packages/flutter/src/rendering/proxy_box.dart.lib.js:2163:20]())
at proxy_box.RenderSemanticsAnnotations.new.hitTestChildren ([http://localhost:5000/packages/flutter/src/rendering/proxy_box.dart.lib.js:437:56]())
at proxy_box.RenderSemanticsAnnotations.new.hitTest ([http://localhost:5000/packages/flutter/src/rendering/layer.dart.lib.js:4452:18]())
at proxy_box.RenderRepaintBoundary.new.hitTestChildren ([http://localhost:5000/packages/flutter/src/rendering/proxy_box.dart.lib.js:437:56]())
....
```
</details> 

<details> 
  <summary>flutter doctor -v</summary>
[✓] Flutter (Channel stable, 2.10.1, on macOS 11.6.1 20G224 darwin-x64, locale en-US)
    • Flutter version 2.10.1 at /Users/alexanderkornhauser/Documents/loveleaf/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (5 days ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/alexanderkornhauser/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 98.0.4758.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

</details> 

Similar to #86545 but their issues are not consistent with my own. Any ideas will help. Can share larger code sample.

**Comment by darshankawar** [comment]
@kornha 
Would be good to get a self contained but [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that throws this error. Make sure the code is without any 3rd party plugins.

**Comment by kornha** [comment]
It can be very hard to do so since there is just a massive error printout without indicating where or what the error is, and the printout is intermittent. I am working on it.
