### ISSUE TITLE
App crashes on load in Chromium 56

### ISSUE THREAD

**Issue by mclark4386** [flutter/flutter#98467]
## Steps to Reproduce

For context, we are targeting displays that have Chromium 56 embedded into them, so the target is static and can't be updated.

1. Get a copy of Chromium 56 to test on (Mac: https://sourceforge.net/projects/osxportableapps/files/Chromium/).
2. Build any flutter app for web with any flutter version after 2.5.3 and try to run it from that version of Chromium.
3. Remove the part of the index.html file that would load the service to by pass several errors.
4. Try again.

**Expected results:** 
Would expect the app to load and run.

**Actual results:** 
The window is blank and in the console you fine the following error:
```
Uncaught Error: SyntaxError: Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to parse the rule '    .flt-text-editing::placeholder {
      opacity: 0;
    }
    '.
    at Object.ahp (main.dart.js:415)
    at CE.dH (main.dart.js:21399)
    at Object.fy (main.dart.js:399)
    at Object.av5 (main.dart.js:1215)
    at main.dart.js:7339
    at a8e.a (main.dart.js:5076)
    at a8e.$2 (main.dart.js:30356)
    at Object.L (main.dart.js:5062)
    at Object.rb (main.dart.js:7357)
    at Object.avR (main.dart.js:7334)
```

![](https://cdn.discordapp.com/attachments/530797119389564939/942875199265722491/Screen_Shot_2022-02-14_at_2.07.18_PM.png)

To get it to work you have to revert to flutter version 2.5.3 and build with `--web-renderer html`.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              const Text(
                'You have pushed the button this many times:',
              ),
            ],
          ),
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () {},
          tooltip: 'Increment',
          child: const Icon(Icons.add),
        ), // This trailing comma makes auto-formatting nicer for build methods.
      ),
    );
  }
}
```

modified index.html:
```
<!DOCTYPE html>
<html>
<head>
  <base href="/">

  <meta charset="UTF-8">
  <meta content="IE=Edge" http-equiv="X-UA-Compatible">
  <meta name="description" content="A new Flutter project.">

  <!-- iOS meta tags & icons -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="newthing">
  <link rel="apple-touch-icon" href="icons/Icon-192.png">

  <!-- Favicon -->
  <link rel="icon" type="image/png" href="favicon.png"/>

  <title>newthing</title>
  <link rel="manifest" href="manifest.json">
</head>
<body>
  <script>
    var serviceWorkerVersion = '2146141352';
    var scriptLoaded = false;
    function loadMainDartJs() {
      if (scriptLoaded) {
        return;
      }
      scriptLoaded = true;
      var scriptTag = document.createElement('script');
      scriptTag.src = 'main.dart.js';
      scriptTag.type = 'application/javascript';
      document.body.append(scriptTag);
    }
    loadMainDartJs();
  </script>
</body>
</html>
```

</details>

<details>
  <summary>Logs</summary>

To host the app I'm using `python3 -m http.server` in the `/build/web` folder so that I can test it in a different browser than the default. So no logs from flutter run or the server. However,  there is an error in the console of the browser and I posted it above.

Output of flutter doctor -v:

```
[newthing] flutter doctor -v
[✓] Flutter (Channel stable, 2.10.1, on macOS 12.1 21C52 darwin-arm, locale
    en-US)
    • Flutter version 2.10.1 at /Users/mclark4386/bin/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (5 days ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/mclark4386/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/mclark4386/sdk
    • ANDROID_SDK_ROOT = /Users/mclark4386/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 98.0.4758.80
    ! Error: iPhone is not connected. Xcode will continue when iPhone is
      connected. (code -13)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by maheshmnj** [comment]
Hi @mclark4386, thanks for filing. I was able to reproduce the same error in the chromium console, and the app loads fine in the Google chrome browser.  I also notice that if I don't modify the html file the app still fails to load with

```
Uncaught SyntaxError: Unexpected token )
```

 ![image](https://user-images.githubusercontent.com/31410839/154052831-46eba586-94d2-4481-b7ff-d919566e6749.png)

windows version of `chromium Version 56.0.2902.0 (64-bit)` can be [found here](https://sourceforge.net/projects/crportable/files/) 

<details>
<summary>chromium logs</summary>

```
classes.dart:520 'webkitAudioContext' is deprecated. Please use 'AudioContext' instead.
registerExtension @ classes.dart:520
developer_patch.dart:75 registerExtension() from dart:developer is only supported in build/run/test environments where the developer event method hooks have been set.
_registerExtension @ developer_patch.dart:75
html_dart2js.dart:8734 Uncaught (in promise) DOMException: Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to parse the rule '    .flt-text-editing::placeholder {
      opacity: 0;
    }
    '.
    at CSSStyleSheet.[dartx.insertRule] (http://localhost:61735/dart_sdk.js:79769:54)
    at Object.applyGlobalCssRulesToSheet (http://localhost:61735/dart_sdk.js:188202:26)
    at _engine.FlutterViewEmbedder.new.reset (http://localhost:61735/dart_sdk.js:152686:15)
    at _engine.FlutterViewEmbedder.new (http://localhost:61735/dart_sdk.js:152916:10)
    at Object.ensureFlutterViewEmbedderInitialized (http://localhost:61735/dart_sdk.js:188210:58)
    at Object.initializeEngine (http://localhost:61735/dart_sdk.js:190176:13)
    at _initializePlatform (http://localhost:61735/dart_sdk.js:139627:15)
    at _initializePlatform.next (<anonymous>)
    at runBody (http://localhost:61735/dart_sdk.js:40590:34)
    at Object._async [as async] (http://localhost:61735/dart_sdk.js:40621:7)
    at Object._initializePlatform (http://localhost:61735/dart_sdk.js:139626:18)
    at Object.webOnlyInitializePlatform (http://localhost:61735/dart_sdk.js:139618:35)
    at main (http://localhost:61735/web_entrypoint.dart.js:32:16)
    at main.next (<anonymous>)
    at runBody (http://localhost:61735/dart_sdk.js:40590:34)
    at Object._async [as async] (http://localhost:61735/dart_sdk.js:40621:7)
    at Object.main$ [as main] (http://localhost:61735/web_entrypoint.dart.js:30:18)
    at http://localhost:61735/main_module.bootstrap.js:14:9
    at Object.execCb (http://localhost:61735/require.js:1696:33)
    at Module.check (http://localhost:61735/require.js:883:51)
    at Module.<anonymous> (http://localhost:61735/require.js:1139:34)
    at http://localhost:61735/require.js:134:23
    at http://localhost:61735/require.js:1189:21
    at each (http://localhost:61735/require.js:59:31)
    at Module.emit (http://localhost:61735/require.js:1188:17)
    at Module.check (http://localhost:61735/require.js:938:30)
    at Module.<anonymous> (http://localhost:61735/require.js:1139:34)
    at http://localhost:61735/require.js:134:23
    at http://localhost:61735/require.js:1189:21
    at each (http://localhost:61735/require.js:59:31)
    at Module.emit (http://localhost:61735/require.js:1188:17)
    at Module.check (http://localhost:61735/require.js:938:30)
    at Module.<anonymous> (http://localhost:61735/require.js:1139:34)
    at http://localhost:61735/require.js:134:23
    at http://localhost:61735/require.js:1189:21
    at each (http://localhost:61735/require.js:59:31)
    at Module.emit (http://localhost:61735/require.js:1188:17)
    at Module.check (http://localhost:61735/require.js:938:30)
    at Module.<anonymous> (http://localhost:61735/require.js:1139:34)
    at http://localhost:61735/require.js:134:23
    at http://localhost:61735/require.js:1189:21
    at each (http://localhost:61735/require.js:59:31)
    at Module.emit (http://localhost:61735/require.js:1188:17)
    at Module.check (http://localhost:61735/require.js:938:30)
    at Module.<anonymous> (http://localhost:61735/require.js:1139:34)
    at http://localhost:61735/require.js:134:23
    at http://localhost:61735/require.js:1189:21
    at each (http://localhost:61735/require.js:59:31)
    at Module.emit (http://localhost:61735/require.js:1188:17)
    at Module.check (http://localhost:61735/require.js:938:30)
    at Module.<anonymous> (http://localhost:61735/require.js:1139:34)
    at http://localhost:61735/require.js:134:23
    at http://localhost:61735/require.js:1189:21
    at each (http://localhost:61735/require.js:59:31)
    at Module.emit (http://localhost:61735/require.js:1188:17)
    at Module.check (http://localhost:61735/require.js:938:30)
    at Module.enable (http://localhost:61735/require.js:1176:22)
    at Module.init (http://localhost:61735/require.js:788:26)
    at callGetModule (http://localhost:61735/require.js:1203:63)
    at Object.completeLoad (http://localhost:61735/require.js:1590:21)
    at HTMLScriptElement.onScriptLoad (http://localhost:61735/require.js:1717:29)

```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[√] Flutter (Channel stable, 2.10.1, on Microsoft Windows [Version 10.0.19044.1466], locale        
    en-US)
    • Flutter version 2.10.1 at C:\flutter_sdk\stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (5 days ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\mahesh\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java      
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)    
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31727.386
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.63.2)
    • VS Code at C:\Users\mahesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.34.0

[√] Connected device (5 available)
    • Redmi K20 Pro (mobile)       • 192.168.1.2:5555 • android-arm64  • Android 11 (API 30)       
    • sdk gphone64 x86 64 (mobile) • emulator-5554    • android-x64    • Android 12 (API 31)       
      (emulator)
    • Windows (desktop)            • windows          • windows-x64    • Microsoft Windows [Version      10.0.19044.1466]
    • Chrome (web)                 • chrome           • web-javascript • Google Chrome 98.0.4758.82    • Edge (web)                   • edge             • web-javascript • Microsoft Edge
      97.0.1072.76

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[√] Flutter (Channel master, 2.11.0-0.0.pre.554, on Microsoft Windows [Version 10.0.19044.1526], locale en-US)
    • Flutter version 2.11.0-0.0.pre.554 at C:\flutter_sdk\master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 894ef49c7c (8 hours ago), 2022-02-14 22:15:17 -0500
    • Engine revision 8714a2448f
    • Dart version 2.17.0 (build 2.17.0-105.0.dev)
    • DevTools version 2.10.0

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)    
    • Android SDK at C:\Users\mahesh\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)        
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)      
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31727.386
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)        

[√] VS Code (version 1.63.2)
    • VS Code at C:\Users\mahesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.34.0

[√] Connected device (4 available)
    • Windows (desktop)       • windows • windows-x64     • Microsoft Windows [Version 10.0.19044.1526]
    • Windows (UWP) (desktop) • winuwp  • windows-uwp-x64 • 
    • Chrome (web)            • chrome  • web-javascript  • Google Chrome 98.0.4758.102
    • Edge (web)              • edge    • web-javascript  • Microsoft Edge 97.0.1072.76

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

Is this reproducible with a newer version of chromium too?

**Comment by mclark4386** [comment]
I know it works fine in the latest chrome (what I use for development normally), but I haven't tested the between versions to see if I can figure out when it started for the chromium side of the equation. Do I need to do that?

**Comment by maheshmnj** [comment]
> Do I need to do that?

Not really, I was just curious about any specific reason for using a very old version of `Chromium`.

Labeling this issue for further insights from the team, Reproduction details can be found here https://github.com/flutter/flutter/issues/98467#issuecomment-1040185549

**Comment by mclark4386** [comment]
Oh I put the context for the issue at the top:

> For context, we are targeting displays that have Chromium 56 embedded into them, so the target is static and can't be updated.

Unfortunately, we have no choice but to use that exact version^^;

**Comment by yjbanov** [comment]
Unfortunately we're not set up to support browsers that old. If a fix this does not introduce high complexity to the code, we'd take a contribution, but since we have no test harness for Chromium 56 we cannot guarantee that we won't break it again.
