### ISSUE TITLE
MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences) while getting FCM message in background

### ISSUE THREAD

**Issue by urvesh-educloud** [flutter/flutter#98473]
I'm working on a Flutter app in which I'm using the shared_preferences: ^2.0.13 package.
Flutter version : 2.10.1 (latest)
gradle version: 6.7
Android gradle plugin version: 4.1.3
kotlin version: 1.6.10
flutterEmbedding 2 (in android menifiest)

MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences). 

While getting FCM message received in background.
Kindly refer the below code 

main.dart
`Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  // If you're going to use other Firebase services in the background, such as Firestore,
  // make sure you call `initializeApp` before using other Firebase services.
  await Firebase.initializeApp();

  print('Got a message onBackgroundMessageHandler_');
  //print('${json.encode(message)}');
  print("Handling a background message: ${message.messageId}");

  print('Shared pref process starts');
  SharedPreferences sf = await SharedPreferences.getInstance();
  sf.setString("key", "Value");
  print('${sf.getKeys()}');
  print('Shared pref process ends');
}`

`void main() async{
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();

  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);

  runApp(const MyApp());
}`

MainActivity.kt
`class MainActivity: FlutterActivity() {

}`

**Comment by darshankawar** [comment]
@urvesh-educloud 
Since `firebase_messaging` is third party plugin, can you confirm if the same exception occurs without using that plugin ?
If so, please provide an isolated [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example). You can try the same using counter app using the plugin and see if you still get same error or not.

**Comment by urvesh-educloud** [comment]
@darshankawar i need to call shared_preferences to store some value

**Comment by darshankawar** [comment]
@urvesh-educloud 
There are already many similar issues filed and were solved. You can just try to search in this repo. One among them is [this](https://github.com/flutter/flutter/issues/85965#issuecomment-875457457). See if it helps.
If not, as requested earlier, please provide an isolated [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by kuhnroyal** [comment]
I am suddenly seeing this error as well after running `flutter pub upgrade`. https://github.com/flutter/plugins/commit/08ba6bdd1e2bbfcbbcb888d06c370fff30b87fa7 looks suspicious

**Comment by Gabanelli** [comment]
The problem was solved for me when I used ```SharedPreferences.setMockInitialValues({});``` before call shared preferences. I don't think this is the best fix, but worked.

```dart
Future<dynamic> _onBackground(RemoteMessage message) async {
    SharedPreferences.setMockInitialValues({});
    final sharedPrefs = await SharedPreferences.getInstance();
    // Your code
}
```

**Comment by kuhnroyal** [comment]
@BeMacized Do you have an idea what could be missing regarding the registration in background isolates?

**Comment by kuhnroyal** [comment]
A workaround is freezing `shared_preferences_android: 2.0.10` and `shared_preferences_ios: 2.0.9`

**Comment by maximilienGilet** [comment]
> A workaround is freezing `shared_preferences_android: 2.0.10` and `shared_preferences_ios: 2.0.9`

Confirm working with freezed versions.

Specifying `shared_preferences_android: 2.0.10` was the key as it's an endorsed package

**Comment by stuartmorgan** [comment]
Thanks for filing this; I've filed https://github.com/flutter/flutter/issues/98591 for the general problem (which we weren't aware of when updating the plugins).

While we investigate whether we can adjust Flutter to handle this automatically in the future, here's a workaround that should allow using the current versions of the plugins:
- Add dependencies on `shared_preferences_android` and `shared_preference_ios`.
- At the beginning of your background isolate entry point, add something like:
  ```
  if (Platform.isAndroid) SharedPreferencesAndroid.registerWith();
  if (Platform.isIOS) SharedPreferencesIOS.registerWith();
  ```

**Comment by rahulmawana** [comment]
> Thanks for filing this; I've filed #98591 for the general problem (which we weren't aware of when updating the plugins).
> 
> While we investigate whether we can adjust Flutter to handle this automatically in the future, here's a workaround that should allow using the current versions of the plugins:
> 
> * Add dependencies on `shared_preferences_android` and `shared_preference_ios`.
> * At the beginning of your background isolate entry point, add something like:
>   ```
>   if (Platform.isAndroid) SharedPreferencesAndroid.registerWith();
>   if (Platform.isIOS) SharedPreferencesIOS.registerWith();
>   ```

It is shared_preferences_ios, you missed the 's'

**Comment by darshankawar** [comment]
I re-visited this behavior and ran the code sample provided using `shared_preferences: ^2.0.13` and on latest stable and master versions along with the help of `firebase_messaging` plugin to send a sample push notification when app is in background and do see below exception:

`[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)`

code sample as mentioned in https://github.com/flutter/flutter/issues/98473#issue-1138257758

<details>
<summary> stable, master flutter doctor -v </summary>

```

[✓] Flutter (Channel stable, 2.10.1, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.10.1 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (5 days ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.


[✓] Flutter (Channel master, 2.11.0-0.0.pre.598, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.11.0-0.0.pre.598 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 660c15ef7f (41 minutes ago), 2022-02-16 23:09:13 -0500
    • Engine revision 754478998b
    • Dart version 2.17.0 (build 2.17.0-105.0.dev)
    • DevTools version 2.10.0

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.


```

</details>

**Comment by elFerZur** [comment]
> Thanks for filing this; I've filed #98591 for the general problem (which we weren't aware of when updating the plugins).
> 
> While we investigate whether we can adjust Flutter to handle this automatically in the future, here's a workaround that should allow using the current versions of the plugins:
> 
>     * Add dependencies on `shared_preferences_android` and `shared_preferences_ios`.
> 
>     * At the beginning of your background isolate entry point, add something like:
>       ```
>       if (Platform.isAndroid) SharedPreferencesAndroid.registerWith();
>       if (Platform.isIOS) SharedPreferencesIOS.registerWith();
>       ```

Would you like to explain this solution in more detail?. What does it mean to "add dependencies"?, add in the pubspec.yaml file the following line: shared_preferences_android: ^2.0.12 ?. I try to add this line, but the class SharedPreferencesAndroid is not available for call the method registerWith().

**Comment by stuartmorgan** [comment]
They are packages; you use code from them the way you would any other package: you add it as a pubspec dependency, and you `import` it in the files you want to use it in.

**Comment by jack24254029** [comment]
`shared_preferences: 2.0.6` can work

**Comment by v7lin** [comment]
any news update?

**Comment by sokpheng** [comment]
How to Freez Can someone tell me how?

**Comment by kuhnroyal** [comment]
> How to Freez Can someone tell me how?

https://github.com/flutter/flutter/issues/98473#issuecomment-1040504720

**Comment by utrescu** [comment]
> How to Freez Can someone tell me how?

Edit `pubspec.lock` and change the versions in  `shared_preferences_android` to 2.0.10 and in `shared_preferences_ios` to  2.0.9

**Comment by sokpheng** [comment]
> > How to Freez Can someone tell me how?
> 
> [#98473 (comment)](https://github.com/flutter/flutter/issues/98473#issuecomment-1040504720)

Let's me try. Thank you.

**Comment by sokpheng** [comment]
> > How to Freez Can someone tell me how?
> 
> Edit `pubspec.lock` and change the versions in `shared_preferences_android` to 2.0.10 and in `shared_preferences_ios` to 2.0.9

Let's me try. Thank you.

**Comment by ViniciusSossela** [comment]
> How to Freez Can someone tell me how?

Add something like this on your pubspec.yaml
```
shared_preferences: ^2.0.9
shared_preferences_android: 2.0.10
shared_preferences_ios: 2.0.9
```

**Comment by stuartmorgan** [comment]
The longer-term solution is that anything setting up an isolate where plugins are expected to work should call `DartPluginRegistrant.ensureInitialized()`, which will run all Dart plugin registration (similar to how they already need to call `WidgetsFlutterBinding.ensureInitialized()` to make platform message work in the first place). That's not currently on `stable` yet though, as it only just landed on `master`.

**Comment by pedromassango** [comment]
> where plugins are expected to work should call `DartPluginRegistrant.ensureInitialized()`, which will run all Dart plugin registration

Does that means that we'll need to call both, the `DartPluginRegistrant.ensureInitialized()` and `WidgetsFlutterBinding.ensureInitialized()`? Can we bundle the dart plugin registrant in the already existing `WidgetsFlutterBinding.ensureInitialized()`?

**Comment by stuartmorgan** [comment]
> @stuartmorgan does that means that we'll need to call both, the `DartPluginRegistrant.ensureInitialized()` and `WidgetsFlutterBinding.ensureInitialized()`?

If you want both of those things to be initialized, yes

> Can we bundle the dart plugin registrant in the already existing `WidgetsFlutterBinding.ensureInitialized()`?

Dart plugin registration has nothing to do with `WidgetsFlutterBinding`.

**Comment by proninyaroslav** [comment]
>if (Platform.isAndroid) SharedPreferencesAndroid.registerWith();
>if (Platform.isIOS) SharedPreferencesIOS.registerWith();

Works well

**Comment by tatraef** [comment]
@stuartmorgan hello, do I need to add just that: DartPluginRegistrant.ensureInitialized()?

Because it's not working for me, all packages with exception:
MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
MissingPluginException(No implementation found for method showToast on channel PonnamKarthik/fluttertoast)
MissingPluginException(No implementation found for method createNewNotification on channel awesome_notifications)

**Comment by pedromassango** [comment]
@tatraef your code should look like the image below:

![Screen Shot 2022-03-07 at 11 18 52 AM](https://user-images.githubusercontent.com/33294549/157012458-264c9848-a43c-4382-8548-b698b2edb795.png)

**Comment by stuartmorgan** [comment]
@tatraef Please file a new issue with details about your case. You are using versions of `shared_preferences_*` that this issue doesn't apply to so whatever issue you are having is unrelated to this one.

**Comment by prjmax** [comment]
I'm still having this problem when the ActionType is SilentBackgroundAction, I am basically trying to create a new notification (SNOOZE) from the notification panel without opening the App

`[VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: MissingPluginException(No implementation found for method createNewNotification on channel awesome_notifications)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
<asynchronous suspension>
#1      AwesomeNotifications.createNotification (package:awesome_notifications/src/awesome_notifications_core.dart:229:31)`

If I don't use SilentBackgroundAction, then the action is not triggered until I open the App, but if I use it, then I'm having the MissingPluginException.

Fluter Master Channel
AwesomeNotifications 0.7.0-beta.2 
iOS 15

any help would be appreciated :)

**Comment by stuartmorgan** [comment]
> No implementation found for method createNewNotification on channel awesome_notifications

This issue is about `shared_preferences`, which your logs are not. If you have an issue with a third-party package you should report it to the developers of that package.
