### ISSUE TITLE
[tool_crash] FileSystemException: Directory listing failed, OS Error: Access is denied., errno = 5

### ISSUE THREAD

**Issue by saudahmedbass** [flutter/flutter#98471]
## Command
```
flutter run
```

## Steps to Reproduce
1. Flutter run
2. select chrome/web-javascript

## Logs
FileSystemException: Directory listing failed, OS Error: Access is denied.
, errno = 5
```
#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:42:24)
#1      _Directory.listSync (dart:io/directory_impl.dart:243:5)
#2      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#3      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#4      _AssetDirectoryCache.variantsFor (package:flutter_tools/src/asset.dart:953:78)
#5      ManifestAssetBundle._parseAssetFromFile (package:flutter_tools/src/asset.dart:792:37)
#6      ManifestAssetBundle._parseAssetsFromFolder (package:flutter_tools/src/asset.dart:759:7)
#7      ManifestAssetBundle._parseAssets (package:flutter_tools/src/asset.dart:685:9)
#8      ManifestAssetBundle.build (package:flutter_tools/src/asset.dart:245:54)
<asynchronous suspension>
#9      ResidentWebRunner._updateDevFS (package:flutter_tools/src/isolated/resident_web_runner.dart:496:26)
<asynchronous suspension>
#10     ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:287:41)
<asynchronous suspension>
#11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.22000.493], locale en-US)
    • Flutter version 2.8.1 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (9 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\saud\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.64.2)
    • VS Code at C:\Users\saud\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.34.0

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 98.0.4758.102
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 98.0.1108.43

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 77d935af4db863f6abd0b9c31c7e6df2a13de57b
### Plugins
flutter_keyboard_visibility-5.1.1
flutter_keyboard_visibility_web-2.0.0
path_provider_linux-2.1.5
path_provider_windows-2.0.5
shared_preferences-2.0.13
shared_preferences_android-2.0.11
shared_preferences_ios-2.0.10
shared_preferences_linux-2.1.0
shared_preferences_macos-2.0.3
shared_preferences_web-2.0.3
shared_preferences_windows-2.1.0

**Comment by maheshmnj** [comment]
Hi @saudahmedbass, Thanks for filing the issue. You seem to be on the old version of flutter, Could you please try upgrading to stable 2.10.0 and see if that fixes the issue? 

Please also check [this comment](https://github.com/flutter/flutter/issues/68810#issuecomment-714699148) which explains the reasoning behind the error 

looks like a duplicate of https://github.com/flutter/flutter/issues/92695
