### ISSUE TITLE
[  +24 ms] executing: [C:\src\flutter\] git -c

### ISSUE THREAD

**Issue by xiaodong171** [flutter/flutter#98489]
```
[  +24 ms] executing: [C:\src\flutter\] git -c
log.showSignature=false log -n 1 --pretty=format:%H
[ +135 ms] Exit code 0 from: git -c log.showSignature=false log
-n 1 --pretty=format:%H
[  +10 ms] f139b11009aeb8ed2a3a3aa8b0066e482709dde3
[   +4 ms] executing: [C:\src\flutter\] git describe --match
v*.*.* --first-parent --long --tags
[ +100 ms] Exit code 0 from: git describe --match v*.*.*
--first-parent --long --tags
[   +3 ms] v1.12.13+hotfix.9-0-gf139b1100
[  +11 ms] executing: [C:\src\flutter\] git rev-parse
--abbrev-ref --symbolic @{u}
[  +57 ms] Exit code 0 from: git rev-parse --abbrev-ref
--symbolic @{u}
[   +2 ms] origin/stable
[   +1 ms] executing: [C:\src\flutter\] git ls-remote --get-url
origin
[  +51 ms] Exit code 0 from: git ls-remote --get-url origin
[   +2 ms] https://github.com/flutter/flutter.git
[ +105 ms] executing: [C:\src\flutter\] git rev-parse
--abbrev-ref HEAD
[  +44 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[ +105 ms] executing:
C:\Users\omaro\AppData\Local\Android\Sdk\platform-tools\adb.exe
devices -l
[  +24 ms] Exit code 0 from:
C:\Users\omaro\AppData\Local\Android\Sdk\platform-tools\adb.exe
devices -l
[   +1 ms] List of devices attached
           emulator-5554          device product:sdk_gphone_x86
           model:Android_SDK_built_for_x86 device:generic_x86
           transport_id:2
[  +15 ms]
C:\Users\omaro\AppData\Local\Android\Sdk\platform-tools\adb.exe
-s emulator-5554 shell getprop
[  +78 ms] Artifact Instance of 'AndroidMavenArtifacts' is not
required, skipping update.
[  +10 ms] Artifact Instance of 'AndroidInternalBuildArtifacts'
is not required, skipping update.
[   +2 ms] Artifact Instance of 'IOSEngineArtifacts' is not
required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not
required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not
required, skipping update.
[   +3 ms] Artifact Instance of 'MacOSEngineArtifacts' is not
required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not
required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is
not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is
not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is
not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is
not required, skipping update.
[ +221 ms] Generating
C:\Users\omaro\AndroidStudioProjects\the_first\android\app\src\
main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +40 ms] ro.hardware = ranchu
[  +48 ms] Using hardware rendering with device Android SDK
built for x86.
           If you get graphics artifacts, consider enabling
software
           rendering with "--enable-software-rendering".
[  +23 ms] Launching lib\main.dart on Android SDK built for x86
in debug
           mode...
[  +16 ms] executing:
C:\Users\omaro\AppData\Local\Android\Sdk\platform-tools\adb.exe
-s emulator-5554 shell -x logcat -v time -t 1
[  +61 ms] Exit code 0 from:
C:\Users\omaro\AppData\Local\Android\Sdk\platform-tools\adb.exe
-s emulator-5554 shell -x logcat -v time -t 1
[   +2 ms] --------- beginning of main
           04-13 10:54:50.915 E/GnssHAL_GnssInterface( 1795):
           gnssSvStatusCb: b: input svInfo.flags is 8
[  +11 ms] executing:
C:\Users\omaro\AppData\Local\Android\Sdk\platform-tools\adb.exe
version
[   +4 ms] executing:
C:\Users\omaro\AppData\Local\Android\Sdk\platform-tools\adb.exe
-s emulator-5554 logcat -v time -T 04-13 10:54:50.915
[  +57 ms] Android Debug Bridge version 1.0.41
           Version 29.0.6-6198805
           Installed as
           C:\Users\omaro\AppData\Local\Android\Sdk\platform-to
           ols\adb.exe
[   +8 ms] executing:
C:\Users\omaro\AppData\Local\Android\Sdk\platform-tools\adb.exe
start-server
[  +46 ms] Building APK
[  +25 ms] Running Gradle task 'assembleDebug'...
[   +4 ms] gradle.properties already sets `android.enableR8`
[   +4 ms] Using gradle from
C:\Users\omaro\AndroidStudioProjects\the_first\android\gradlew.
bat.
[  +10 ms] executing: C:\Program Files\Android\Android
Studio\jre\bin\java -version
[ +103 ms] Exit code 0 from: C:\Program Files\Android\Android
Studio\jre\bin\java -version
[   +2 ms] openjdk version "1.8.0_212-release"
           OpenJDK Runtime Environment (build
           1.8.0_212-release-1586-b04)
           OpenJDK 64-Bit Server VM (build 25.212-b04, mixed
           mode)
[   +4 ms] executing:
[C:\Users\omaro\AndroidStudioProjects\the_first\android\]
C:\Users\omaro\AndroidStudioProjects\the_first\android\gradlew.
bat -Pverbose=true
-Ptarget=C:\Users\omaro\AndroidStudioProjects\the_first\lib\mai
n.dart -Ptrack-widget-creation=true
-Pfilesystem-scheme=org-dartlang-root
-Ptarget-platform=android-x86 assembleDebug
[ +174 ms] Unzipping
C:\Users\omaro\.gradle\wrapper\dists\gradle-5.6.2-all\9st6wgf78
h16so49nn74lgtbb\gradle-5.6.2-all.zip to
C:\Users\omaro\.gradle\wrapper\dists\gradle-5.6.2-all\9st6wgf78
h16so49nn74lgtbb
[   +5 ms] Exception in thread "main"
java.util.zip.ZipException: error in opening zip file
[   +2 ms]      at java.util.zip.ZipFile.open(Native Method)
[   +1 ms]      at java.util.zip.ZipFile.<init>(ZipFile.java:225)
[   +5 ms]      at java.util.zip.ZipFile.<init>(ZipFile.java:155)
[   +2 ms]      at java.util.zip.ZipFile.<init>(ZipFile.java:169)
[   +1 ms]      at
org.gradle.wrapper.Install.unzip(Install.java:214)
[   +2 ms]      at
org.gradle.wrapper.Install.access$600(Install.java:27)
[   +3 ms]      at
org.gradle.wrapper.Install$1.call(Install.java:74)
[   +1 ms]      at
org.gradle.wrapper.Install$1.call(Install.java:48)
[   +1 ms]      at
org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveF
ileAccessManager.java:65)
[   +3 ms]      at
org.gradle.wrapper.Install.createDist(Install.java:48)
[   +2 ms]      at
org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java
:128)
[   +1 ms]      at
org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.jav
a:61)
[  +19 ms] Running Gradle task 'assembleDebug'... (completed in
0.3s)
[   +6 ms] [!] Gradle threw an error while trying to update
itself.
           Retrying the update...
[   +9 ms] Running Gradle task 'assembleDebug'...
[   +2 ms] gradle.properties already sets `android.enableR8`
[   +3 ms] Using gradle from
C:\Users\omaro\AndroidStudioProjects\the_first\android\gradlew.
bat.
[   +1 ms] executing:
[C:\Users\omaro\AndroidStudioProjects\the_first\android\]
C:\Users\omaro\AndroidStudioProjects\the_first\android\gradlew.
bat -Pverbose=true
-Ptarget=C:\Users\omaro\AndroidStudioProjects\the_first\lib\mai
n.dart -Ptrack-widget-creation=true
-Pfilesystem-scheme=org-dartlang-root
-Ptarget-platform=android-x86 assembleDebug
[ +182 ms] Unzipping
C:\Users\omaro\.gradle\wrapper\dists\gradle-5.6.2-all\9st6wgf78
h16so49nn74lgtbb\gradle-5.6.2-all.zip to
C:\Users\omaro\.gradle\wrapper\dists\gradle-5.6.2-all\9st6wgf78
h16so49nn74lgtbb
[   +6 ms] Exception in thread "main"
java.util.zip.ZipException: error in opening zip file
[   +3 ms]      at java.util.zip.ZipFile.open(Native Method)
[   +2 ms]      at java.util.zip.ZipFile.<init>(ZipFile.java:225)
[   +3 ms]      at java.util.zip.ZipFile.<init>(ZipFile.java:155)
[   +2 ms]      at java.util.zip.ZipFile.<init>(ZipFile.java:169)
[   +2 ms]      at
org.gradle.wrapper.Install.unzip(Install.java:214)
[   +3 ms]      at
org.gradle.wrapper.Install.access$600(Install.java:27)
[   +2 ms]      at
org.gradle.wrapper.Install$1.call(Install.java:74)
[   +1 ms]      at
org.gradle.wrapper.Install$1.call(Install.java:48)
[   +1 ms]      at
org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveF
ileAccessManager.java:65)
[   +2 ms]      at
org.gradle.wrapper.Install.createDist(Install.java:48)
[   +3 ms]      at
org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java
:128)
[   +2 ms]      at
org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.jav
a:61)
[   +1 ms] Running Gradle task 'assembleDebug'... (completed in
0.2s)
[   +2 ms] [!] Gradle threw an error while trying to update
itself.
           Retrying the update...
[   +6 ms] "flutter run" took 1,495ms.
Gradle task assembleDebug failed with exit code 1

#0      throwToolExit
(package:flutter_tools/src/base/common.dart:28:3)
#1      buildGradleApp
(package:flutter_tools/src/android/gradle.dart:431:7)
#2      _asyncThenWrapperHelper.<anonymous closure>
(dart:async-patch/async_patch.dart:73:64)
#3      _rootRunUnary (dart:async/zone.dart:1134:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#5      _FutureListener.handleValue
(dart:async/future_impl.dart:139:18)
#6      Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:680:45)
#7      Future._propagateToListeners
(dart:async/future_impl.dart:709:32)
#8      Future._completeWithValue
(dart:async/future_impl.dart:524:5)
#9      Future._asyncComplete.<anonymous closure>
(dart:async/future_impl.dart:554:7)
#10     _rootRun (dart:async/zone.dart:1126:13)
#11     _CustomZone.run (dart:async/zone.dart:1023:19)
#12     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#13     _CustomZone.bindCallbackGuarded.<anonymous closure>
(dart:async/zone.dart:965:23)
#14     _microtaskLoop
(dart:async/schedule_microtask.dart:43:21)
#15     _startMicrotaskLoop
(dart:async/schedule_microtask.dart:52:5)
#16     _runPendingImmediateCallback
(dart:isolate-patch/isolate_patch.dart:118:13)
#17     _RawReceivePortImpl._handleMessage
(dart:isolate-patch/isolate_patch.dart:175:5)
```

_Originally posted by @OmarBadwi in https://github.com/flutter/flutter/issues/48159#issuecomment-612819388_

**Comment by darshankawar** [comment]
@xiaodong171 
Please don't use an issue comment to open an issue. Please use new issue template and fill out requested details so that we'll have enough details to work with.
Closing as this isn't actionable without enough details.
