### ISSUE TITLE
[tool_crash] FileSystemException: Cannot create file, path:* (OS Error: The system cannot find the path specified., errno = 3)

### ISSUE THREAD

**Issue by MohamedAlwhaidi** [flutter/flutter#98514]
## Command
```
flutter --no-color pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: FileSystemException: Cannot create file, path = 'D:\Projects\Complete Projects\Work\IHL\masterstudy-lms-mobile-app-flutter-ios-androidر-v1.1.0\masterstudy-application-package\masterstudyapplication-release-1.1.0\masterstudyapplication-release-1.1.0\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java' (OS Error: The system cannot find the path specified.
, errno = 3)
```
#0      _File.throwIfError (dart:io/file_impl.dart:645:7)
#1      _File.createSync (dart:io/file_impl.dart:283:5)
#2      ForwardingFile.createSync (package:file/src/forwarding/forwarding_file.dart:24:16)
#3      ForwardingFile.createSync (package:file/src/forwarding/forwarding_file.dart:24:16)
#4      _renderTemplateToFile (package:flutter_tools/src/plugins.dart:27:8)
#5      _writeAndroidPluginRegistrant (package:flutter_tools/src/plugins.dart:641:3)
#6      injectPlugins (package:flutter_tools/src/plugins.dart:1079:11)
#7      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:232:11)
<asynchronous suspension>
#8      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:128:23)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:723:18)
#10     _rootRunUnary (dart:async/zone.dart:1192:38)
#11     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#15     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#16     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#17     _rootRun (dart:async/zone.dart:1184:13)
```
```
[✓] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.19043.1526], locale en-US)
    • Flutter version 1.17.1 at D:\versions\flutter_windows_1.17.1-stable\flutter
    • Framework revision f7a6a7906b (1 year, 9 months ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Mohamed\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\program files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[!] Android Studio
    • Android Studio at C:\program files\Android\Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • android-studio-dir = C:\program files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[✓] VS Code (version 1.64.2)
    • VS Code at C:\Users\Mohamed\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.34.0

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.1.0+13
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 0b8abb4724aa590dd0f429683339b1e045a1594d
### Plugins
file_picker-1.6.3+2
firebase_crashlytics-0.1.3
flutter_plugin_android_lifecycle-1.0.6
image_picker-0.6.3+4
package_info-0.4.1
path_provider-1.6.9
path_provider_macos-0.0.4+3
share-0.6.3+6
shared_preferences-0.5.6+2
shared_preferences_macos-0.0.1+6
shared_preferences_web-0.1.2+4
sqflite-1.3.0+1
url_launcher-5.4.5
url_launcher_macos-0.0.1+5
url_launcher_web-0.1.1+2
video_player-0.10.9
video_player_web-0.1.2+1
webview_media-0.1.2

**Comment by maheshmnj** [comment]
Hi @MohamedAlwhaidi, Thanks for filing the issue. You seem to be on a very old version of flutter, And This seems to have been fixed in the new releases https://github.com/flutter/flutter/issues/66415 (closed), Please try upgrading flutter to latest stable using `flutter upgrade` and feel free to write back if you still see the crash after the upgrade.
