### ISSUE TITLE
Framework crashes on startup, complains about Z key??

### ISSUE THREAD

**Issue by mihaibulic** [flutter/flutter#98527]
## Steps to Reproduce

everything was working fine then all of the sudden I started getting this error/crash right when I try to compile/run the app.

PS I'm unlikely to report framework bugs in the future since it's a hassle (I had to figure out my github login since I don't use github anymore, then run several commands and copy/paste output into this bug) — why not just have the Flutter AS plugin add a "report bug" option that collects these logs automatically and creates a bug? 

<details>
<summary>Code sample</summary>

```N/A
```

</details>

<details>
  <summary>Logs</summary>

```
======== Exception caught by services library ======================================================
The following assertion was thrown during a platform message callback:
A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#2676d(physicalKey: PhysicalKeyboardKey#7001d(usbHidUsage: "0x0007001d", debugName: "Key Z"), logicalKey: LogicalKeyboardKey#0007a(keyId: "0x0000007a", keyLabel: "Z", debugName: "Key Z"), character: null, timeStamp: 456:12:43.208645)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 441 pos 16: '_pressedKeys.containsKey(event.physicalKey)'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:441:16)
#3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:452:6)
#4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:544:5)
#5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:821:35)
#6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:77:49)
#7      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:76:47)
#8      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:377:35)
#9      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:374:46)
#10     _invoke2.<anonymous closure> (dart:ui/hooks.dart:190:15)
#14     _invoke2 (dart:ui/hooks.dart:189:10)
#15     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#16     _Channel.push (dart:ui/channel_buffers.dart:132:31)
#17     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#18     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:583:22)
#19     _dispatchPlatformMessage (dart:ui/hooks.dart:89:31)
(elided 5 frames from class _AssertionError and dart:async)
====================================================================================================
```

```
Analyzing raw...                                                        
No issues found! (ran in 0.8s)
```

```
[✓] Flutter (Channel beta, 2.10.0-0.3.pre, on macOS 12.0.1 21A559 darwin-arm, locale en-US)
    • Flutter version 2.10.0-0.3.pre at /Users/mihai/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fdd0af78bb (3 weeks ago), 2022-01-25 22:01:33 -0600
    • Engine revision 5ac30ef0c7
    • Dart version 2.16.0 (build 2.16.0-134.5.beta)
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/mihai/Library/Android/sdk
    • Platform android-31, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/mihai/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Pixel 4 XL (mobile) • 96071FFBA00055                       • android-arm64  • Android 11 (API 30)
    • iPhone 13 (mobile)  • 900F5EC7-231D-4E15-9C75-E6B3C458E245 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)        • chrome                               • web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@mihaibulic 
Looking at the error log you shared, it seems to be similar to below reported issues:

https://github.com/flutter/flutter/issues/98071.  -> this is reported on Windows
https://github.com/flutter/flutter/issues/95888. -> this was fixed in December.

Since you are on older version of beta, can you upgrade it to the latest or also try to switch to latest master and try again the scenario to see if you still get the same error or not.
