### ISSUE TITLE
HtmlElementView attached to ShadowRoot doesn't allow JavaScript Element.requestFullscreen() on Flutter Web app

### ISSUE THREAD

**Issue by nori-flutter** [flutter/flutter#98564]
## Steps to Reproduce

1. Create a simple flutter web app and attach DivElement '<div id="video-player"></div>' by using platformViewRegistry.registerViewFactory and HtmlElementView.
2. Run the web app on Google Chrome
3. Call JavaScript Element.requestFullscreen() for the DivElement '<div id="video-player"></div>' from Flutter UI button to request Fullscreen mode on the browser.

**Expected results:**
The Flutter Web app UI should stays with fullscreen mode

**Actual results:**
The Flutter Web app goes to fullscreen mode; however, it exists the fullscreen mode right away.

When I directly attached the div tag via document.body!.append, the JavaScript Element.requestFullscreen() works fine but cannot attach the div inside of Flutter Widget component with this way.
It seems like the issue is because the HtmlElementView with DivElement goes under #shadow-root DOM is outside of main root DOM.

References:
* https://docs.flutter.dev/release/breaking-changes/platform-views-using-html-slots-web
ShadowDOM - The Shadow DOM API provides a way to attach a hidden separated DOM to an element.

* https://docs.google.com/document/d/1U6aCSuzQsFpOP8_OseL-fwl2-MC2bxJAsgt2R_-sC30/edit

The reason of doing this is because we have our own custom video player JavaScript in order to handle DRM and video streaming.

<details>
  <summary>Sample Code</summary>

```dart
// JavaScript requestFullscreen doesn't work with this
Widget videoPlayerSurface(BuildContext context, {required String id}) {
    var divTag = DivElement();
    divTag.id = id;
    // ignore: undefined_prefixed_name
    ui.platformViewRegistry
        .registerViewFactory('$id-view', (int viewId) => divTag);
    return HtmlElementView(key: UniqueKey(), viewType: '$id-view');
}

bool requestFullscreen(DivElement element) {
  var elem = new JsObject.fromBrowserObject(element);

  if (elem.hasProperty("requestFullscreen")) {
    elem.callMethod("requestFullscreen");
    return true;
  } else {
    List<String> vendors = ['moz', 'webkit', 'ms', 'o'];
    for (String vendor in vendors) {
      String vendorFullscreen = "${vendor}RequestFullscreen";
      if (vendor == 'moz') {
        vendorFullscreen = "${vendor}RequestFullScreen";
      }
      if (elem.hasProperty(vendorFullscreen)) {
        elem.callMethod(vendorFullscreen);
        return true;
      }
    }
  }
  return false;
}
```

```dart
// JavaScript requestFullscreen works and the web app stays with fullscreen in this way but cannot make it as Flutter Widget Component.
Widget videoPlayerSurface(BuildContext context, {required String id}) {
    var playerDiv = querySelector('#$id');
    if (playerDiv == null) {
      var divTag = DivElement();
      divTag.id = id;
      document.body!.append(divTag);
    }
// Dummy container
    final Size size = MediaQuery.of(context).size;
    return Container(
      key: Key('$id-container'),
      width: size.width,
      height: ((size.width * 9) / 16),
    );
}
```

</details>

<details>
  <summary>Logs</summary>

Google Chrome console output:
```
WebGL: INVALID_OPERATION: delete: object does not belong to this context
```

</details>

<details>
  <summary>Flutter  Doctor</summary>

```
[✓] Flutter (Channel stable, 2.10.0, on macOS 12.2.1 21D62 darwin-arm, locale en-US)
    • Flutter version 2.10.0 at /Users/user1/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f105a6ca7 (2 weeks ago), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/user1/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = /Users/user1/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.2.1 21D62 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @nori-flutter, please provide a complete sample that we can run without having to make any major modifications so we can verify this. 

Thank you

**Comment by nori-flutter** [comment]
> Hi @nori-flutter, please provide a complete sample that we can run without having to make any major modifications so we can verify this.
> 
> Thank you

Hi @danagbemava-nc ,

I created this sample web app:
https://github.com/nori-flutter/flutter-web-request-fullscreen-issue

Please run on chrome to confirm.

The first fullscreen icon works with document.body!.append(divTag) approach.
The 2nd fullscreen icon has the issue with HtmlElementView approach.

Thanks,
Nori

**Comment by danagbemava-nc** [comment]
Hi @nori-flutter, when I use the `document.body!.append(divTag)` approach, I get just a blank screen although it stays in full screen. 

Is that expected?

**Comment by nori-flutter** [comment]
> Hi @nori-flutter, when I use the `document.body!.append(divTag)` approach, I get just a blank screen although it stays in full screen.
> 
> Is that expected?

Yes, this expected. Full screen stays with `document.body!.append(divTag)` approach which is the correct behavior but we cannot make it this to Flutter Widget.

Thanks,
Nori

**Comment by danagbemava-nc** [comment]
Issue is reproducible on `stable` and `master`.


## Steps to reproduce
1. Clone the code sample in https://github.com/nori-flutter/flutter-web-request-fullscreen-issue (attached below as a zip for convenience)
2. Run the app on web
3. Use the full screen toggle buttons to toggle full screen for both approaches (as shown in the video below)

<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.10.2, on macOS 12.2 21D49 darwin-arm, locale en-GB)
    • Flutter version 2.10.2 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (4 days ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not
      helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml
      (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion
      (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage
      (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate
      (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure>
      (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure>
      (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1426:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1861:10)
      #15     runZonedGuarded (dart:async/zone.dart:1849:12)
      #16     runZoned (dart:async/zone.dart:1780:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:205:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:309:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #21     FlutterCommand.verifyThenRunCommand
      (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure>
      (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure>
      (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure>
      (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure>
      (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand
      (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure>
      (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure>
      (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.2 21D49 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 98.0.4758.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel master, 2.11.0-0.0.pre.650, on macOS 12.2 21D49 darwin-arm, locale en-GB)
    • Flutter version 2.11.0-0.0.pre.650 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cddd5524d4 (4 hours ago), 2022-02-22 20:19:15 -0600
    • Engine revision ef9d407fed
    • Dart version 2.17.0 (build 2.17.0-137.0.dev)
    • DevTools version 2.11.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 213.5744.122

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.2 21D49 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 98.0.4758.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

<details>
<summary>videos</summary>

| document.body!.append(divTag) | HtmlElementView |
| -- | -- |
| <video src="https://user-images.githubusercontent.com/88313112/155272445-e70794cb-905c-46e7-a84d-3b0808474301.mov" /> | <video src="https://user-images.githubusercontent.com/88313112/155272404-1bdc7461-c411-489a-93db-6d4aa7e46d46.mov" /> |

</details>

[flutter-web-request-fullscreen-issue.zip](https://github.com/flutter/flutter/files/8122402/flutter-web-request-fullscreen-issue.zip)

**Comment by ditman** [comment]
I've given this a quick JS test, and in vanilla JS, flutter's slotted content should work:

https://jsfiddle.net/ditman/vL0d9ywo

I'm taking a quick look at why it doesn't.

**Comment by ditman** [comment]
OK, so after a quick inspection, I think this is an engine issue. It seems that the full screen procedure is triggering some repaints on the page that cause the HtmlElementView to be removed from the page, and re-added. Observe the id of the slot before clicking the full-screen button:

<img width="1092" alt="Screen Shot 2022-10-18 at 7 17 56 PM" src="https://user-images.githubusercontent.com/1255594/196582180-0169ebcf-b769-4c12-bd98-abbfc718070b.png">

And after:

<img width="1093" alt="Screen Shot 2022-10-18 at 7 18 09 PM" src="https://user-images.githubusercontent.com/1255594/196582262-3a1896b8-a138-4f29-ade6-ae1c34a82cfa.png">

I suspect the following chain of events is happening:

1. When fullscreen is requested...
2. The browser attempts to animate its viewport to make the fullscreen transition "nice", but...
3. That triggers Flutter Web to re-render...
4. And in the process of re-rendering, the platform-view that requested the fullscreen gets removed from the DOM...
5. Which in turn, aborts the fullscreen requests, and "resets" the screen to normal.

I'm not 100% sure what's the best solution here; if stopping flutter from re-rendering/resizing when the `fullscreenchange` event fires (or monitoring if there's a `fullscreenElement` set), or attempting to keep the platform views longer in the DOM!

I'd say this is a P4, but certainly very annoying for this use case :/
