### ISSUE TITLE
Flutter Exception when first child of `CustomScrollView` changes

### ISSUE THREAD

**Issue by predatorx7** [flutter/flutter#98580]
I'm getting a similar issue as https://github.com/flutter/flutter/issues/55170

## Steps to Reproduce

1. Used riverpod or any other way to update widget  FirstWidgetThatCausedIssue.
```dart
 return CustomScrollView(
      slivers: [
         FirstWidgetThatCausedIssue(),
      ]
);
```
2. This update can either be a replacement of `FirstWidgetThatCausedIssue` with another widget or changing the returned child in FirstWidgetThatCausedIssue.

**Expected results:** 
1. When dependencies cause FirstWidgetThatCausedIssue to update to another widget, the new widget should be rendered properly, for ex. if the new update returns `const SliverToBoxAdapter(child: Text('Hello World'),)`, then `Hello World` must appear on the screen.

**Actual results:** 
1. Blank screen with exceptions in logger.

<details>
<summary>Code sample</summary>

```dart
return CustomScrollView(
      slivers: [
         Consumer(builder: (context, ref, _) {
              final asyncValue = ref.watch(someFutureProvider);
              return asyncValue.when(
                data: (data) { return const SliverToBoxAdapter(child: Text('Hello World'),); },
                loading: () { return const SliverToBoxAdapter(child: SizedBox(),); },
                error: (e, s) { return const SliverToBoxAdapter(child: SizedBox(),); },
              );
         }),
      ]
);
```

</details>

<details>
  <summary>Logs</summary>

```
══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/rendering/viewport.dart': Failed assertion: line 1702 pos 12: 'center!.parent
== this': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack:
#2      RenderViewport.indexOfFirstChild (package:flutter/src/rendering/viewport.dart:1702:12)
#3      RenderViewportBase.debugDescribeChildren (package:flutter/src/rendering/viewport.dart:974:17)
#4      DiagnosticableTreeNode.getChildren (package:flutter/src/foundation/diagnostics.dart:3041:48)
#5      DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1600:32)
#6      DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1641:6)
#7      DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1665:19)
#8      MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
#9      ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
#10     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:206:27)
#11     new _GrowableList.of (dart:core-patch/growable_array.dart:153:28)
#12     new List.of (dart:core-patch/array_patch.dart:51:28)
#13     ListIterable.toList (dart:_internal/iterable.dart:213:44)
#14     DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1666:8)
#15     DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1628:25)
#16     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1641:6)
#17     WidgetInspectorService._nodeToJson (package:flutter/src/widgets/widget_inspector.dart:1513:18)
#18     WidgetInspectorService._reportStructuredError (package:flutter/src/widgets/widget_inspector.dart:922:44)
```

```
[✓] Flutter (Channel stable, 2.10.1, on Microsoft Windows [Version 10.0.22000.493], locale en-IN)
    • Flutter version 2.10.1 at D:\Devel\flutter_2
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (7 days ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at D:\Linux\devel\android-sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31424.327
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at D:\Apps\IntelliJ IDEA 2021.2.3
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.64.2)
    • VS Code at C:\Users\smush\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.34.0

[✓] Connected device (4 available)
    • MiTV AESP0 (mobile) • 192.168.1.182:5555 • android-arm    • Android 9 (API 28)
    • Windows (desktop)   • windows            • windows-x64    • Microsoft Windows [Version 10.0.22000.493]
    • Chrome (web)        • chrome             • web-javascript • Google Chrome 98.0.4758.82
    • Edge (web)          • edge               • web-javascript • Microsoft Edge 98.0.1108.50

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

A workaround to solve this issue for me was:

```dart
return CustomScrollView(
      slivers: [
          /// First widget that does not update
          const SliverToBoxAdapter(
              child: SizedBox(),
          ),
         Consumer(builder: (context, ref, _) {
              final asyncValue = ref.watch(someFutureProvider);
              return asyncValue.when(
                data: (data) { return const SliverToBoxAdapter(child: Text('Hello World'),); },
                loading: () { return const SliverToBoxAdapter(child: SizedBox(),); },
                error: (e, s) { return const SliverToBoxAdapter(child: SizedBox(),); },
              );
         }),
      ]
);
```

**Comment by danagbemava-nc** [comment]
Hi @predatorx7, can you provide a complete sample that we can just run without having to make any major changes? 

Thank you

**Comment by predatorx7** [comment]
Hey @danagbemava-nc,

Here's the code for the sample

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  final String title;

  const MyHomePage({
    Key? key,
    required this.title,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      body: const CustomScrollView(
        slivers: [
          // SliverWidgetThatDoesNotChange(),
          SliverWidgetThatChanges(),
        ],
      ),
    );
  }
}

class SliverWidgetThatDoesNotChange extends StatelessWidget {
  const SliverWidgetThatDoesNotChange({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const SliverToBoxAdapter(
      child: SizedBox(),
    );
  }
}

class SliverWidgetThatChanges extends StatefulWidget {
  const SliverWidgetThatChanges({Key? key}) : super(key: key);

  @override
  State<SliverWidgetThatChanges> createState() =>
      _SliverWidgetThatChangesState();
}

class _SliverWidgetThatChangesState extends State<SliverWidgetThatChanges> {
  bool change = false;

  @override
  void initState() {
    super.initState();
    // Updating state after a few seconds
    Future.delayed(const Duration(seconds: 4), () {
      setState(() {
        change = true;
      });
    });
  }

  @override
  Widget build(BuildContext context) {
    return change ? const SecondSliverWidget() : const FirstSliverWidget();
  }
}

class FirstSliverWidget extends StatelessWidget {
  const FirstSliverWidget({
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const SliverToBoxAdapter(
      child: Text('Before'),
    );
  }
}

class SecondSliverWidget extends StatelessWidget {
  const SecondSliverWidget({
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const SliverList(
      delegate: SliverChildListDelegate.fixed(
        [
          Text('After'),
        ],
      ),
    );
  }
}
``` 

This problem does not happen when you uncomment `SliverWidgetThatDoesNotChange` in `CustomScrollView`.

**Comment by predatorx7** [comment]
Has https://github.com/flutter/flutter/pull/96377 fixed this issue?

**Comment by ezze** [comment]
It also happens to me, guys. I am using MobX for state management.

```dart
class _ProfileNotificationScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final l10n = AppLocalizations.of(context)!;

    return Scaffold(
      appBar: DefaultAppBar(title: l10n.notifications),
      backgroundColor: MColors.white,
      body: SafeArea(
        child: Container(
          padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 0),
          child: const CustomScrollView(
            slivers: [
              ProfileNotificationListContent(),
            ],
          ),
        ),
      ),
    );
  }
}

class ProfileNotificationListContent extends StatelessWidget {
  const ProfileNotificationListContent({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final profileNotificationStore = context.read<ProfileNotificationStore>();
    return Observer(
      builder: (context) {
        if (profileNotificationStore.loading) {
          return const ProfileNotificationListSkeleton();
        }
        if (profileNotificationStore.error) {
          return const ProfileNotificationListError();
        }
        return const ProfileNotificationList();
      },
    );
  }
}
```

`ProfileNotificationListSkeleton`, `ProfileNotificationListError` and `ProfileNotificationList` could be any simple widgets returning sliver, e.g.:

```dart
class ProfileNotificationList extends StatelessWidget {
  const ProfileNotificationList({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const SliverToBoxAdapter(
      child: SizedBox.shrink(),
    );
  }
}
```

I came here from [there](https://github.com/flutter/flutter/issues/55170) and [there](https://github.com/flutter/flutter/pull/96377). So, probably, the referenced PR don't fix the issue.

Adding an empty `SliverToBoxAdapter()` as first child works for me:

```dart
const CustomScrollView(
  slivers: [
    SliverToBoxAdapter(),
    ProfileNotificationListContent(),
  ],
),
```

```$ flutter --version
Flutter 2.10.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision db747aa133 (8 days ago) • 2022-02-09 13:57:35 -0600
Engine • revision ab46186b24
Tools • Dart 2.16.1 • DevTools 2.9.2
```

**Comment by danagbemava-nc** [comment]
Hi @ezze, the referenced PR is available for versions `2.11.0-0.1.pre` and above so you most likely won't see it on the stable channel. Kindly check on either the `beta` or `master` channel

**Comment by predatorx7** [comment]
Hi @danagbemava-nc, I wasn't able to reproduce this problem on beta or master. That PR solved this issue. 🙂

**Comment by danagbemava-nc** [comment]
Hi @predatorx7, thanks for confirming. 

Closing based on https://github.com/flutter/flutter/issues/98580#issuecomment-1044011249 as fixed.

Thank you
