### ISSUE TITLE
flutter run -- throws an exception

### ISSUE THREAD

**Issue by prahalramesh** [flutter/flutter#9866]
List of commands used,

```
1. flutter create Celerity
2. cd Celerity
3. flutter run
```
O/P:
_Oops; flutter has exited unexpectedly.
Sending crash report to Google._

## exception

ArgumentError: Invalid argument(s): join(null, "bin", "gradle"): part 0 was null, but part 1 was not.

```
#0      _validateArgList (package:path/src/context.dart:1054)
#1      Context.join (package:path/src/context.dart:220)
#2      AndroidStudio.gradleExecutable (package:flutter_tools/src/android/android_studio.dart:104)
#3      gradleExecutable (package:flutter_tools/src/android/android_studio.dart:46)
#4      locateSystemGradle (package:flutter_tools/src/android/gradle.dart:108)
#5      ensureGradle (package:flutter_tools/src/android/gradle.dart:135)
#6      _calculateGradleAppOutDirV2 (package:flutter_tools/src/android/gradle.dart:80)
#7      getGradleAppOutDirV2 (package:flutter_tools/src/android/gradle.dart:74)
#8      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:68)
#9      AndroidApk.AndroidApk.fromCurrentDirectory (package:flutter_tools/src/application_package.dart:86)
#10     getApplicationPackageForPlatform (package:flutter_tools/src/application_package.dart:256)
#11     FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:203)
<asynchronous suspension>
#12     HotRunner.run (package:flutter_tools/src/run_hot.dart:183)
<asynchronous suspension>
#13     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:321)
<asynchronous suspension>
#14     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:205)
<asynchronous suspension>
#15     RunCommand.verifyThenRunCommand (package:flutter_tools/src/commands/run.dart:210)
<asynchronous suspension>
#16     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:156)
<asynchronous suspension>
#17     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#18     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:262)
<asynchronous suspension>
#19     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#20     Future.Future.sync (dart:async/future.dart:208)
#21     CommandRunner.run (package:args/command_runner.dart:109)
#22     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:157)
#23     run.<anonymous closure> (package:flutter_tools/executable.dart:140)
<asynchronous suspension>
#24     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#25     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#26     _rootRun (dart:async/zone.dart:1120)
#27     _CustomZone.run (dart:async/zone.dart:1001)
#28     runZoned (dart:async/zone.dart:1465)
#29     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#30     run (package:flutter_tools/executable.dart:113)
<asynchronous suspension>
#31     main (package:flutter_tools/executable.dart:66)
<asynchronous suspension>
#32     main (file:///Users/Prahal/playGround/libs/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#33     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

## flutter doctor

```
[✓] Flutter (on Mac OS X 10.12 16A323, channel master)
    • Flutter at /Users/Prahal/playGround/libs/flutter
    • Framework revision d1e895224e (12 hours ago), 2017-05-05 21:44:46 -0700
    • Engine revision 1b01211ee6
    • Tools Dart version 1.23.0-dev.11.11

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/Prahal/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin/java
    • Java version: Java(TM) SE Runtime Environment (build 1.8.0_121-b13)

[-] iOS toolchain - develop for iOS devices
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Once installed, run 'sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer'.
    ✗ ideviceinstaller not available; this is used to discover connected iOS devices.
      To install, run:
        brew update
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew update
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew update
        brew install cocoapods
        pod setup

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[-] Android Studio (version unknown)
    • Android Studio at /Users/Prahal/Applications/Android/Contents
    ✗ Android Studio not found at /Users/Prahal/Applications/Android/Contents
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2016.3.6)
    • Dart plugin version 163.13137
    • Flutter plugin version 12.1

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)

```

**Comment by eseidelGoogle** [comment]
@tvolkert @jakobr-google

**Comment by mit-mit** [comment]
@tvolkert did this get rolled back?

**Comment by tvolkert** [comment]
Yeah, in https://github.com/flutter/flutter/pull/9934 because it caused https://github.com/flutter/flutter/issues/9929

/cc @jakobr-google

**Comment by mravn-google** [comment]
Android Studio is no longer responsible for providing a Gradle binary.
