### ISSUE TITLE
crash when use cmd "flutter build windows" compile project in flutter desktop

### ISSUE THREAD

**Issue by dengwant** [flutter/flutter#98719]
1、when I compile project use Android studio, debug or release mode all work well
2、use cmd “flutter run” or “flutter build windows”，crash
3、flutter doctor -v
```
[√] Flutter (Channel stable, 2.10.1, on Microsoft Windows [Version 10.0.19042.1526], locale zh-CN)
    • Flutter version 2.10.1 at D:\work\flutter2.10.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (8 days ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at E:\android_sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.9)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.32106.194
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.1526]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 92.0.4515.107
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 98.0.1108.50

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

4、crash information：
flutter build windows
Running "flutter pub get" in xiaohumeng_app...                     12.8s

```
Oops; flutter has exited unexpectedly: "FileSystemException: Cannot create link, path =
'D:\work\xiaohumeng_app\xiaohumeng_app\windows\flutter\ephemeral\.plugin_symlinks\connectivity_plus_windows' (OS Error:
拒绝访问。
, errno = 5)".
A crash report has been written to D:\work\xiaohumeng_app\xiaohumeng_app\flutter_01.log.
```

5、flutter_01.log
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter build windows

## exception

FileSystemException: FileSystemException: Cannot create link, path = 'D:\work\xiaohumeng_app\xiaohumeng_app\windows\flutter\ephemeral\.plugin_symlinks\connectivity_plus_windows' (OS Error: access denied.。
, errno = 5)

```
#0      _Link.throwIfError (dart:io/link.dart:263:7)
#1      _Link.createSync (dart:io/link.dart:184:5)
#2      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#3      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#4      _createPlatformPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:1029:12)
#5      createPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:964:5)
#6      refreshPluginsList (package:flutter_tools/src/flutter_plugins.dart:1055:5)
<asynchronous suspension>
#7      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:316:5)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1306:7)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#17     main (package:flutter_tools/executable.dart:94:3)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel stable, 2.10.1, on Microsoft Windows [Version 10.0.19042.1526], locale zh-CN)
    • Flutter version 2.10.1 at D:\work\flutter2.10.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (8 days ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at E:\android_sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.9)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.32106.194
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.1526]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 92.0.4515.107
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 98.0.1108.50

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
Please Help me!!!!

**Comment by maheshmnj** [comment]
looks similar to https://github.com/flutter/flutter/issues/77561

**Comment by darshankawar** [comment]
Based on the crash log, it looks similar to https://github.com/flutter/flutter/issues/77561, so closing this in favor of linked issue.
