### ISSUE TITLE
Links containing Russian characters do not open

### ISSUE THREAD

**Issue by alexeylopukh** [flutter/flutter#98740]
If you add Russian characters to the link, they stop opening and throw an exception:
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(argument_error, Unable to parse URL, Provided URL: Optional("https://гибдд.рф/"), null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:177:18)
<asynchronous suspension>
#2      launch (package:url_launcher/url_launcher.dart:101:23)
<asynchronous suspension>
#3      _launchURL (package:url_launcher_test/main.dart:33:8)
<asynchronous suspension>
```
Links for test:
1) https://www.google.com/search?q=тест
2) https://гибдд.рф/

Code Sample:
```
import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';

const String _url1 = 'https://www.google.com/search?q=тест';
const String _url2 = 'https://гибдд.рф/';

void main() => runApp(
      MaterialApp(
        home: Material(
          child: Center(
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                RaisedButton(
                  onPressed: () => _launchURL(_url1),
                  child: const Text('Open url 1'),
                ),
                const SizedBox(
                  height: 10,
                ),
                RaisedButton(
                  onPressed: () => _launchURL(_url2),
                  child: const Text('Open url 2'),
                ),
              ],
            ),
          ),
        ),
      ),
    );

void _launchURL(String url) async {
  if (!await launch(url)) throw 'Could not launch $url';
}
```

**Comment by alexeylopukh** [comment]
@stuartmorgan Why did you decide that they are not valid? They are valid, you can check them in the browser and other applications. Users want to open such links, but your solution does not allow them.

**Comment by alexeylopukh** [comment]
@stuartmorgan @danagbemava-nc 
NEW UPDATE!
On Android and Windows it's valid, but on iOS and macOS it's not valid?
I made this conclusion because this code does not work only on macOS and iOS. This is a bug.

**Comment by stuartmorgan** [comment]
> Why did you decide that they are not valid?

I didn't. The authors of the RFCs that define valid URLs decided it.

> They are valid, you can check them in the browser

Browsers accept a lot of non-URL input and then make best-effort attempts to convert it to a valid URL. The `url_launcher` plugin requires valid URLs.

> Users want to open such links, but your solution does not allow them.

Nothing is preventing developers from converting arbitrary input to valid URLs using the heuristics of their choice, then opening those valid URLs.

> I made this conclusion because this code does not work only on macOS and iOS.

`url_launcher` works by passing the input to the OS for handling. Some operating systems have their own logic for attempting to convert arbitrary input to valid URLs. On those operating systems, your invalid input happens to work.

> This is a bug.
> Please reopen the issue.

This is not a bug, and will not be re-opened. The plugin's API contact is that you pass a valid URL, and you are violating that API contract.
