### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Nakshi-Kalolia** [flutter/flutter#98755]
## What happened

(please describe what you were doing when this exception occurred)
I was creating a Flutter project with Kotlin and swift language , created for android iOS and web. As soon as the project was created, this bug showed up by displaying the error message "IDE error occurred"

## Version information

Android Studio `Bumblebee | 2021.1.1 Patch 1` • Flutter plugin `io.flutter 64.1.2` • Dart plugin `211.7798`

Error getting Flutter sdk information.

## Exception

real size = 4096

```
java.nio.file.NoSuchFileException: C:\Users\lenovo\AppData\Local\Google\AndroidStudio2021.1\frameworks\detection\fourscreen.f1cbd5ca\files.len
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:239)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:371)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:422)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
	at java.base/java.nio.file.Files.newInputStream(Files.java:156)
	at com.intellij.util.io.ResizeableMappedFile.readLength(ResizeableMappedFile.java:178)
	at com.intellij.util.io.ResizeableMappedFile.<init>(ResizeableMappedFile.java:66)
	at com.intellij.util.io.PersistentBTreeEnumerator.<init>(PersistentBTreeEnumerator.java:73)
	at com.intellij.util.io.PersistentEnumerator.createDefaultEnumerator(PersistentEnumerator.java:65)
	at com.intellij.util.io.PersistentMapImpl.<init>(PersistentMapImpl.java:131)
	at com.intellij.util.io.PersistentMapBuilder.buildImplementation(PersistentMapBuilder.java:64)
	at com.intellij.util.io.PersistentMapBuilder.build(PersistentMapBuilder.java:41)
	at com.intellij.util.io.PersistentHashMap.<init>(PersistentHashMap.java:39)
	at com.intellij.util.io.PersistentHashMap.<init>(PersistentHashMap.java:60)
	at com.intellij.framework.detection.impl.DetectedFrameworksData.<init>(DetectedFrameworksData.java:37)
	at com.intellij.framework.detection.impl.FrameworkDetectionManager.doInitialize(FrameworkDetectionManager.java:128)
	at com.intellij.framework.detection.impl.FrameworkDetectionManager.<init>(FrameworkDetectionManager.java:72)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:52)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:771)
	at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:35)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:110)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:64)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:57)
	at com.intellij.serviceContainer.ComponentManagerImpl.createComponents(ComponentManagerImpl.kt:340)
	at com.intellij.openapi.project.impl.ProjectExImpl.init(ProjectExImpl.kt:177)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.initProject(ProjectManagerImpl.java:175)
	at com.intellij.openapi.project.impl.ProjectManagerExImpl.newProject(ProjectManagerExImpl.kt:203)
	at com.intellij.openapi.project.impl.ProjectManagerExImpl.createProject(ProjectManagerExImpl.kt:57)
	at com.intellij.ide.util.projectWizard.ProjectBuilder.createProject(ProjectBuilder.java:60)
	at com.intellij.ide.impl.NewProjectUtil.doCreate(NewProjectUtil.java:118)
	at com.intellij.ide.impl.NewProjectUtil.createFromWizard(NewProjectUtil.java:73)
	at com.intellij.ide.impl.NewProjectUtil.createFromWizard(NewProjectUtil.java:68)
	at com.intellij.ide.impl.NewProjectUtil.createNewProject(NewProjectUtil.java:63)
	at io.flutter.actions.FlutterNewProjectAction.actionPerformed(FlutterNewProjectAction.java:40)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAware$5(ActionUtil.java:273)
	at com.intellij.util.SlowOperations.lambda$allowSlowOperations$0(SlowOperations.java:77)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:64)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:76)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:273)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:310)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:286)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:77)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:299)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:110)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:95)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:110)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:515)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:545)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6652)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6417)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:836)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:787)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
[bug-report.md](https://github.com/flutter/flutter/files/8098546/bug-report.md)

**Comment by darshankawar** [comment]
Can you provide `flutter doctor -v` ?
Looking at the log, it is pointing to `AndroidStudio2021.1` Bumblebee version.

**Comment by darshankawar** [comment]
Until we wait for more details, I tried to replicate this behavior by upgrading my Android Studio Arctic Fox to BumbleBee version and then created a new Flutter project with Kotlin, Swift and Web languages, with which the project was created successfully and didn't get the error as reported.

<img width="481" alt="Screenshot 2022-02-22 at 3 03 15 PM" src="https://user-images.githubusercontent.com/67046386/155103875-f8f7368e-4939-40dc-8078-006877d6b29c.png">
<img width="459" alt="Screenshot 2022-02-22 at 3 03 25 PM" src="https://user-images.githubusercontent.com/67046386/155103890-590855f1-30ee-4d2e-abfa-45dd130de43d.png">


<details>
<summary> stable flutter doctor -v </summary>

```

[√] Flutter (Channel stable, 2.10.1, on Microsoft Windows [Version 10.0.19042.1526], locale en-US)
    • Flutter version 2.10.1 at D:\FlutterSDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (13 days ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Win\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31624.102
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.62.3)
    • VS Code at C:\Users\Win\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.28.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.1526]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 98.0.4758.102
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 98.0.1108.56

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
</details>

**Comment by Nakshi-Kalolia** [comment]
My apologies for replying late to this email.
Well, I upgraded my AndroidStudio one more time the day before yesterday. I
have run the command you asked for. I'm attaching it here. And these
commands are executed after I upgraded my Android Studio to the latest
version.

**Comment by darshankawar** [comment]
@Nakshi-Kalolia 
I still don't see the output of your `flutter doctor -v` ? Do you get this error consistently every time ? Can you also provide exact steps to replicate ?

**Comment by Nakshi-Kalolia** [comment]
The output is in the first attachment itself (Screenshot-92), starting from
the line "A flutter upgrade is available " written in the box.
No, I didn't get the error the second time.

**Comment by darshankawar** [comment]
Thanks. Since you didn't get the error next time you tried after upgrading your AS, I suggest you to keep an eye on such exception / pattern. I was also unable to replicate this behavior upon my verification. May be it's coming from the intellij plugin and not a framework issue per se and you'll probably need to report it in https://github.com/flutter/flutter-intellij/issues

I'll close it for now since this isn't replicable always / consistently and author has not seen it after first time.
If you disagree, write in comments and I'll reopen it or you can directly report it in dedicated repo linked above.
