### ISSUE TITLE
 flutter doctor -v  run wrong

### ISSUE THREAD

**Issue by dd9913762113** [flutter/flutter#98785]
```
flutter doctor -v 
The flutter tool cannot access the file or directory.
Please ensure that the SDK and/or project is installed in a location that
has read/write permissions for the current user.



#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      _throwFileSystemException
(package:flutter_tools/src/base/error_handling_io.dart:820:3)
#2      _handlePosixException
(package:flutter_tools/src/base/error_handling_io.dart:761:3)
#3      _runSync
(package:flutter_tools/src/base/error_handling_io.dart:614:7)
#4      ErrorHandlingProcessManager.runSync
(package:flutter_tools/src/base/error_handling_io.dart:711:12)
#5      _DefaultProcessUtils.runSync
(package:flutter_tools/src/base/process.dart:373:51)
#6      AndroidStudio._init
(package:flutter_tools/src/android/android_studio.dart:458:39)
#7      new AndroidStudio
(package:flutter_tools/src/android/android_studio.dart:40:5)
#8      AndroidStudio.fromMacOSBundle
(package:flutter_tools/src/android/android_studio.dart:90:12)
#9      AndroidStudio._allMacOS.<anonymous closure>
(package:flutter_tools/src/android/android_studio.dart:316:68)
#10     MappedListIterable.elementAt
(dart:_internal/iterable.dart:413:31)
#11     ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
#12     WhereTypeIterator.moveNext (dart:_internal/iterable.dart:869:20)
#13     new _GrowableList._ofOther
(dart:core-patch/growable_array.dart:219:26)
#14     new _GrowableList.of (dart:core-patch/growable_array.dart:155:26)
#15     new List.of (dart:core-patch/array_patch.dart:51:28)
#16     Iterable.toList (dart:core/iterable.dart:470:12)
#17     AndroidStudio._allMacOS
(package:flutter_tools/src/android/android_studio.dart:318:10)
#18     AndroidStudio.allInstalled
(package:flutter_tools/src/android/android_studio.dart:247:34)
#19     AndroidStudioValidator.allValidators
(package:flutter_tools/src/android/android_studio_validator.dart:33:55)
#20     _DefaultDoctorValidatorsProvider.validators
(package:flutter_tools/src/doctor.dart:80:35)
#21     Doctor.validators (package:flutter_tools/src/doctor.dart:192:47)
#22     Doctor.startValidatorTasks
(package:flutter_tools/src/doctor.dart:198:45)
#23     Doctor.diagnose (package:flutter_tools/src/doctor.dart:309:47)
#24     DoctorCommand.runCommand
(package:flutter_tools/src/commands/doctor.dart:50:48)
#25     FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:1320:12)
<asynchronous suspension>
#26     FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1161:27)
<asynchronous suspension>
#27     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#28     CommandRunner.runCommand
(package:args/command_runner.dart:209:13)
<asynchronous suspension>
#29     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#31     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#32     run.<anonymous closure>.<anonymous closure>
(package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#33     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#34     main (package:flutter_tools/executable.dart:94:3)
<asynchronous suspension>

```

**Comment by darshankawar** [comment]
@dd9913762113 
As the error message indicates :
`The flutter tool cannot access the file or directory.
Please ensure that the SDK and/or project is installed in a location that
has read/write permissions for the current user.`

So the solution is to `ensure that the SDK and/or project is installed in a location that
has read/write permissions for the current user.`

Closing from here.
