### ISSUE TITLE
When i write to TextField widget i take some error in KeyUpEvent event

### ISSUE THREAD

**Issue by Receporak** [flutter/flutter#98789]
<details>
<summary>Code sample</summary>

```
TextField(
                            autofocus: true,
                            controller: searchAddressInput,
                            textAlign: TextAlign.left,
                            style: TextStyle(
                              color: primaryColor,
                              fontFamily: "VarelaRound",
                            ),
                            decoration: InputDecoration(
                              prefixIcon: Icon(
                                Icons.search,
                                color: primaryColor,
                              ),
                              suffixIcon: Visibility(
                                visible: searchAddressInput.text.length == 0 ? false : true,
                                child: IconButton(
                                    icon: ImageIcon(
                                      AssetImage(
                                        "assets/icons/clearIcon.png",
                                      ),
                                      color: primaryColor,
                                    ),
                                    onPressed: () {
                                      setState(() {
                                        searchAddressInput.clear();
                                      });
                                    }),
                              ),
                              hintText: AppLocalizations.of(context).translate("searchPlace"),
                              hintStyle: TextStyle(
                                color: primaryColor,
                                fontFamily: "VarelaRound",
                              ),
                              disabledBorder: InputBorder.none,
                              border: InputBorder.none,
                              focusedBorder: InputBorder.none,
                              enabledBorder: InputBorder.none,
                              errorBorder: InputBorder.none,
                            ),
                            onChanged: (text) {
                              getLocationResult(text);
                            },
                          ),

```
</details>

<details>
  <summary>Logs</summary>

```

══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
The following assertion was thrown during a platform message callback:
A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs
in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure
that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the
event: KeyUpEvent#3a337(physicalKey: PhysicalKeyboardKey#7002c(usbHidUsage: "0x0007002c", debugName:
"Space"), logicalKey: LogicalKeyboardKey#00020(keyId: "0x00000020", keyLabel: " ", debugName:
"Space"), character: null, timeStamp: 1:43:43.121652)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 441 pos 16: '_pressedKeys.containsKey(event.physicalKey)'

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack:
#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:441:16)
#3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:452:6)
#4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:544:5)
#5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:821:35)
#6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:77:49)
#7      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:76:47)
#8      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:377:35)
#9      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:374:46)
#10     _invoke2.<anonymous closure> (dart:ui/hooks.dart:190:15)
#14     _invoke2 (dart:ui/hooks.dart:189:10)
#15     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#16     _Channel.push (dart:ui/channel_buffers.dart:132:31)
#17     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#18     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:583:22)
#19     _dispatchPlatformMessage (dart:ui/hooks.dart:89:31)
(elided 5 frames from class _AssertionError and dart:async)
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in
real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's
event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#3a337(physicalKey:
PhysicalKeyboardKey#7002c(usbHidUsage: "0x0007002c", debugName: "Space"), logicalKey: LogicalKeyboardKey#00020(keyId: "0x00000020",
keyLabel: " ", debugName: "Space"), character: null, timeStamp: 1:43:43.121652)


```

</details>

**Comment by darshankawar** [comment]
@Receporak 
Can you provide `flutter doctor -v` and exact steps to replicate ?

**Comment by j787701730** [comment]
keydown backspace 
```
Unable to parse JSON message:
The document is empty.

======== Exception caught by services library ======================================================
The following assertion was thrown during a platform message callback:
A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#aef60(physicalKey: PhysicalKeyboardKey#7000c(usbHidUsage: "0x0007000c", debugName: "Key I"), logicalKey: LogicalKeyboardKey#00069(keyId: "0x00000069", keyLabel: "I", debugName: "Key I"), character: null, timeStamp: 7:55:23.287897)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 441 pos 16: '_pressedKeys.containsKey(event.physicalKey)'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:441:16)
#3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:452:6)
#4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:544:5)
#5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:867:35)
#6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:77:49)
#7      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:76:47)
#8      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:377:35)
#9      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:374:46)
#10     _invoke2.<anonymous closure> (dart:ui/hooks.dart:190:15)
#14     _invoke2 (dart:ui/hooks.dart:189:10)
#15     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#16     _Channel.push (dart:ui/channel_buffers.dart:132:31)
#17     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#18     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:583:22)
#19     _dispatchPlatformMessage (dart:ui/hooks.dart:89:31)
(elided 5 frames from class _AssertionError and dart:async)
====================================================================================================
Unable to parse JSON message:
The document is empty.

======== Exception caught by services library ======================================================
The following assertion was thrown during a platform message callback:
A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#aef60(physicalKey: PhysicalKeyboardKey#7000c(usbHidUsage: "0x0007000c", debugName: "Key I"), logicalKey: LogicalKeyboardKey#00069(keyId: "0x00000069", keyLabel: "I", debugName: "Key I"), character: null, timeStamp: 7:55:23.287897)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 441 pos 16: '_pressedKeys.containsKey(event.physicalKey)'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:441:16)
#3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:452:6)
#4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:544:5)
#5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:867:35)
#6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:77:49)
#7      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:76:47)
#8      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:377:35)
#9      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:374:46)
#10     _invoke2.<anonymous closure> (dart:ui/hooks.dart:190:15)
#14     _invoke2 (dart:ui/hooks.dart:189:10)
#15     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#16     _Channel.push (dart:ui/channel_buffers.dart:132:31)
#17     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#18     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:583:22)
#19     _dispatchPlatformMessage (dart:ui/hooks.dart:89:31)
(elided 5 frames from class _AssertionError and dart:async)
====================================================================================================

```

```
 Flutter (Channel beta, 2.11.0-0.1.pre, on Microsoft Windows [Version 10.0.19044.1526], locale zh-CN)
    • Flutter version 2.11.0-0.1.pre at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b101bfe32f (2 weeks ago), 2022-02-16 07:36:54 -0800
    • Engine revision e355993572
    • Dart version 2.17.0 (build 2.17.0-69.2.beta)
    • DevTools version 2.10.0-dev.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
```

**Comment by Receporak** [comment]
> @Receporak Can you provide `flutter doctor -v` and exact steps to replicate ?

[✓] Flutter (Channel stable, 2.10.2, on macOS 12.2 21D49 darwin-x64, locale en-TR)
    • Flutter version 2.10.2 at /Users/fury/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (2 weeks ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/fury/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.65.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • iPhone SE (2nd generation) (mobile) • B089AE64-F6C9-4595-9470-94BF8480F195 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 98.0.4758.109

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

**Comment by darshankawar** [comment]
> and exact steps to replicate ?

Which keys do you press that triggers this error ?

**Comment by Receporak** [comment]
> > and exact steps to replicate ?
> 
> Which keys do you press that triggers this error ?

all keys

**Comment by darshankawar** [comment]
@Receporak 
I tried the code sample you provided and ran it on Windows desktop using latest stable (2.10.3) and pressed keys but it didn't result in triggering the issue you reported.

Although the code you provided was not complete, but I updated it to make the code runnable as below:

<details>
<summary> code sample </summary>

```

import 'package:flutter/material.dart';


void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  late final TextEditingController searchAddressInput = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Web Views',
      theme: ThemeData(
          primarySwatch: Colors.blue,
          fontFamily: "Arial",
          textTheme: TextTheme(
              button: TextStyle(color: Colors.white, fontSize: 18.0),
              subtitle1: TextStyle(color: Colors.red))),
      home: Scaffold(
          body: Center(
              child: TextField(
                autofocus: true,
                controller: searchAddressInput,
                textAlign: TextAlign.left,
                style: TextStyle(
                  color: Colors.amber,
                  fontFamily: "VarelaRound",
                ),
                decoration: InputDecoration(
                  prefixIcon: Icon(
                    Icons.search,
                    color: Colors.amber,
                  ),
                  suffixIcon: Visibility(
                  //  visible: searchAddressInput.text.length == 0 ? false : true,
                    child: IconButton(
                        icon: ImageIcon(
                          AssetImage(
                            "assets/icons/clearIcon.png",
                          ),
                          color: Colors.amber,
                        ),
                        onPressed: () {
                          // setState(() {
                          //   searchAddressInput.clear();
                          // }
                        //  );
                        }),
                  ),
                  hintText: 'AppLocalizations.of(context).translate("searchPlace")',
                  hintStyle: TextStyle(
                    color: Colors.amber,
                    fontFamily: "VarelaRound",
                  ),
                  disabledBorder: InputBorder.none,
                  border: InputBorder.none,
                  focusedBorder: InputBorder.none,
                  enabledBorder: InputBorder.none,
                  errorBorder: InputBorder.none,
                ),
                onChanged: (text) {
                //  getLocationResult(text);
                },
              ),

          )
      ),
    );
  }
}

```

</details>

Pressed on combination of keys, but didn't get the error.  Can you provide us exact steps to replicate ?

`Channel stable, 2.10.3`

**Comment by Receporak** [comment]
> @Receporak I tried the code sample you provided and ran it on Windows desktop using latest stable (2.10.3) and pressed keys but it didn't result in triggering the issue you reported.
> 
> Although the code you provided was not complete, but I updated it to make the code runnable as below:
> 
> code sample
> Pressed on combination of keys, but didn't get the error. Can you provide us exact steps to replicate ?
> 
> `Channel stable, 2.10.3`

I tried on latest stable version (2.10.3) and issue is gone. Thanks for your support
