### ISSUE TITLE
Execution failed for task ':app:compileFlutterBuildDebug'.

### ISSUE THREAD

**Issue by Omar8345** [flutter/flutter#98823]
## Steps to Reproduce

**_1. I sync my project and it works without errors or warnings
2. I start build output and it starts executing commands
3. After a few time and commands, it gets the error_**

```
* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1
```

**Expected results:** 

I expected to see that the application is loaded and installed on the AVD (_Android Virtual Device_). But the process failed and gets an error which makes me stuck here to test my application.

**Actual results:** 
The actual result which I got is here, I will also **_mention the log below!_**
The actual result it just keeps running for some time excusing the other commands, then the error just comes by and then the process fails. This is build output!

<details>
<summary>Code sample</summary>

`local.properties`
```properties
sdk.dir=C\:\\Users\\osedk\\AppData\\Local\\Android\\Sdk
flutter.sdk=C\:\\flutter\\
```

`settings.gradle (android)`
```gradle
include ':app'

def localPropertiesFile = new File(rootProject.projectDir, "local.properties")
def properties = new Properties()

assert localPropertiesFile.exists()
localPropertiesFile.withReader("UTF-8") { reader -> properties.load(reader) }

def flutterSdkPath = properties.getProperty("flutter.sdk")
assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
apply from: "$flutterSdkPath/packages/flutter_tools/gradle/app_plugin_loader.gradle"
```

`build.gradle (Project: android)`
```gradle
buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.1.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```

`build.gradle (Module: android.app)`
```gradle
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    compileSdkVersion 30

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        applicationId "com.devtechnologies.siratemustaqeem"
        minSdkVersion 16
        targetSdkVersion 30
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

     signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            storePassword keystoreProperties['storePassword']
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}

```

`gradle.properties`
```properties
org.gradle.jvmargs=-Xmx1536M
android.useAndroidX=true
android.enableJetifier=true
```

`settings.gradle`
```gradle
include ':app'

def localPropertiesFile = new File(rootProject.projectDir, "local.properties")
def properties = new Properties()

assert localPropertiesFile.exists()
localPropertiesFile.withReader("UTF-8") { reader -> properties.load(reader) }

def flutterSdkPath = properties.getProperty("flutter.sdk")
assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
apply from: "$flutterSdkPath/packages/flutter_tools/gradle/app_plugin_loader.gradle"

```

</details>

<details>
  <summary>Logs</summary>

```
FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1102

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 4s
12 actionable tasks: 2 executed, 10 up-to-date
```

</details>

**Comment by benyaminbeyzaie** [comment]
I'm facing the same issue

**Comment by Omar8345** [comment]
This is mine flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.2, on Microsoft Windows [Version 10.0.22000.493], locale en-AE)
[!] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.1)
[√] VS Code (version 1.64.2)
[√] Connected device (4 available)
[√] HTTP Host Availability

! Doctor found issues in 2 categories.
```

Lemme fix those for now, (errors)

**Comment by benyaminbeyzaie** [comment]
I've tried reinstalling flutter but I can't fix the issue

**Comment by Omar8345** [comment]
Same here, but the one was downloaded before reinstalling it again was installed like 1-2 weeks ago installed.

I fixed and all ticks now when I execute `flutter doctor` in the command prompt
```
[√] Flutter (Channel stable, 2.10.2, on Microsoft Windows [Version 10.0.22000.493], locale en-AE)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.0)
[√] Android Studio (version 2021.1)
[√] VS Code (version 1.64.2)
[√] Connected device (3 available)
[√] HTTP Host Availability

• No issues found!
```

**Comment by Omar8345** [comment]
I'll try building the application again as it's all ticks now

**Comment by Omar8345** [comment]
That error is away now, now I get another error. `Caused by: org.gradle.process.internal.ExecException: Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1` I'll try restarting my PC

**Comment by Omar8345** [comment]
Same new error

**Comment by benyaminbeyzaie** [comment]
Try deleting the android and ios folder and then run `flutter create .`  in the folder again. if you make change in those folders make sure that you git commit them first and after create project again return those files.

**Comment by Omar8345** [comment]
Same same bro Best regards, From: Benyamin BeyzaieSent: Sunday, 20 February 2022 3:51 PMTo: flutter/flutterCc: Omar; AuthorSubject: Re: [flutter/flutter] Execution failed for task ':app:compileFlutterBuildDebug'. (Issue #98823) Try deleting the android and ios folder and then run flutter create . in the folder again. if you make change in those folders make sure that you git commit them first and after create project again return those files.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by benyaminbeyzaie** [comment]
So Please put a emoji on my answer and close the issue Thanks

**Comment by Omar8345** [comment]
No, I meant it does not fix the issue Best regards, From: Benyamin BeyzaieSent: Sunday, 20 February 2022 4:35 PMTo: flutter/flutterCc: Omar; AuthorSubject: Re: [flutter/flutter] Execution failed for task ':app:compileFlutterBuildDebug'. (Issue #98823) So Please put a emoji on my answer and close the issue Thanks—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Omar8345** [comment]
> Try deleting the android and ios folder and then run `flutter create .` in the folder again. if you make change in those folders make sure that you git commit them first and after create project again return those files.

Did that worked well with you?

**Comment by danagbemava-nc** [comment]
Hi @Omar8345, please provide the full log of either `flutter run -v` or `flutter build apk/appbundle -v` depending on which command it is that you are experiencing this issue with. 

Can you also update your `ext.kotlin_version` to `ext.kotlin_version = 1.6.10` and let me know if that helps? 

Thank you

**Comment by Omar8345** [comment]
I don't use Kotlin, I executed the command `flutter run -v` here is the output @danagbemava-nc 

```
[  +81 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +538 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 097d3313d8e2c7f901932d63e537c1acefb87800
[   +1 ms] executing: [C:\flutter/] git tag --points-at 097d3313d8e2c7f901932d63e537c1acefb87800
[ +115 ms] Exit code 0 from: git tag --points-at 097d3313d8e2c7f901932d63e537c1acefb87800
[        ] 2.10.2
[   +7 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +36 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +27 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +109 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +36 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +137 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +13 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +181 ms] executing: C:\Users\osedk\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +69 ms] List of devices attached
[  +13 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +11 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +36 ms] Changing current working directory to: C:\Users\osedk\Desktop\quran\Sirat-E-Mustaqeem
[  +50 ms] No supported devices connected.
[  +22 ms] The following devices were found, but are not supported by this project:
           Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.493]
           Chrome (web)      • chrome  • web-javascript • Google Chrome 98.0.4758.102
           Edge (web)        • edge    • web-javascript • Microsoft Edge 98.0.1108.56
           If you would like your app to run on web or windows, consider running `flutter create .` to generate projects for these platforms.
           
[  +12 ms] "flutter run" took 506ms.
[  +25 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:472:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1276:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>
           
           
[ +269 ms] ensureAnalyticsSent: 264ms
[   +3 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

**Comment by danagbemava-nc** [comment]
Hi @Omar8345, kotlin is defined in your `buildscript`. You may not personally use it, but it is used in your project. 

Can you run `flutter run -v` again with a supported device connected and provide the output of that? 

Please upgrade your kotlin version to what I stated earlier as well before you run the command and provide the output. 

Thank you

**Comment by Omar8345** [comment]
Hi @danagbemava-nc , I changed Kotlin version, I tried first running build output, same error, the `flutter run-v` has the same output I gave yesterday, I am trying to make migrations right now to Kotlin, I saved a copy of my full project. Hope it works

**Comment by Omar8345** [comment]
I made migration, got this message
```
10:43 AM	Kotlin Migration
				Migrations for Kotlin code are available
				Detected migration:
				Standard library: 1.5.31 -> 1.6.10
				Language version: 1.3 -> 1.6
				API version: 1.3 -> 1.6
				Run migrations

10:43 AM	No suspicious code found. 26 files processed in 'Project 'android''.
``` but also same error at build output @danagbemava-nc

**Comment by Omar8345** [comment]
If we can schedule a remote session like if you can access my pc like Anydesk session and help me at 3:30 IST time ? India Standard time, is that okay for you today ? Waiting for your reply

**Comment by danagbemava-nc** [comment]
Unfortunately, I cannot do that. 

Is your code available publicly somewhere that you can share? 

Can you also share the content of your pubspec.yaml and `pubspec.lock`? 

Thank you

**Comment by Omar8345** [comment]
Wait, I'll make commit to gituhb repo and send u

**Comment by Omar8345** [comment]
Done [click here](https://github.com/Omar8345/android-app-sirat)

**Comment by Omar8345** [comment]
You can do changes then send me.

**Comment by Omar8345** [comment]
Any updates ? @danagbemava-nc

**Comment by danagbemava-nc** [comment]
Hi @Omar8345, I've sent a PR to your repo. 

Can you check if it works for you? It seems to work just fine on my end.

**Comment by Omar8345** [comment]
Ok @danagbemava-nc , I just saw your msg now, I'll check your Pull Request and update you, thanks.

**Comment by Omar8345** [comment]
So sad :(, it still did not work, same error exactly.! IDK, maybe the issue in my PC?

**Comment by danagbemava-nc** [comment]
Hmm, kindly connect a supported device and run `flutter run -v` and provide the full logs. The output might be huge so kindly put it into a .txt file and attach it here.

**Comment by Omar8345** [comment]
Okay, so I run my AVD and execute the command, it just started with huge red text, and then some white text, but as I see, I cannot see the application on the AVD. I run the command `flutter run -v`

**Comment by Omar8345** [comment]
Oh, it's executing tasks right now, I'll wait.

**Comment by Omar8345** [comment]
[log.txt](https://github.com/flutter/flutter/files/8121543/log.txt)
I attached the log, and it seems it worked properly, then I build output! IT WORKS! Thanks @danagbemava-nc for your cooperation and help, you were really cooperative.
