### ISSUE TITLE
[camera] Fatal Exception: java.lang.IllegalArgumentException: previewSize must not be taller than activeArray

### ISSUE THREAD

**Issue by carman247** [flutter/flutter#98861]
### Devices
Huawei Mate30 Mini Android 6.0

### Stack trace
```
Fatal Exception: java.lang.IllegalArgumentException: previewSize must not be taller than activeArray
       at android.hardware.camera2.legacy.ParameterUtils.getPreviewCropRectangleUnzoomed(ParameterUtils.java:496)
       at android.hardware.camera2.legacy.ParameterUtils.getClosestAvailableZoomCrop(ParameterUtils.java:395)
       at android.hardware.camera2.legacy.ParameterUtils.convertScalerCropRegion(ParameterUtils.java:767)
       at android.hardware.camera2.legacy.LegacyRequestMapper.convertRequestMetadata(LegacyRequestMapper.java:71)
       at android.hardware.camera2.legacy.LegacyMetadataMapper.convertRequestMetadata(LegacyMetadataMapper.java:1212)
       at android.hardware.camera2.legacy.RequestThreadManager$5.handleMessage(RequestThreadManager.java:760)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:207)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

### Flutter doctor
```console
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale en-GB)
    • Flutter version 2.5.3 at /Users/chris/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (4 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/chris/Library/Android/sdk
    • Platform android-32, build-tools 30.0.3
    • ANDROID_SDK_ROOT = /Users/chris/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.114

• No issues found!
```

**Comment by danagbemava-nc** [comment]
Hi @carman247, what version of `camera` are you experiencing this issue with? 

Is this issue reproducible locally? If it is, kindly provide a complete minimal reproducible code sample as well as steps to reproduce. 

If it is not, can you please provide the full error stack trace? 

Thank you
