### ISSUE TITLE
[google_maps] Map goes blank when moved to background and throws ANRs

### ISSUE THREAD

**Issue by maheshmnj** [flutter/flutter#98865]
## Steps to Reproduce

1. Run the sample app
2. move the app to the background (probably for 10 secs)
3. bring the app to the foreground
4. lock the phone (for another 10 secs)
5. unlock the phone 

**Expected Results**: The app continues to work

**Actual Result**: App has a blank black screen and shows App not responding pop up 

I was able to record this since this happens frequently with the above reproducible steps on the stable channel and it happens on the master channel too with a long delay.

https://user-images.githubusercontent.com/31410839/154945227-af172943-5c28-4bd3-90f8-1a149a8ccb46.mp4

Additionally, on the master channel map isn't displayed full screen for the below code sample there is some padding from the bottom.

Here's a [reproducible sample project](https://github.com/flutter/flutter/files/8108381/maps_sample.zip)(created on stable 2.10.2) to verify this issue. you can run it by adding the maps api key in the Android manifest. 

## Logs

<details>
<summary>Logs</summary>

```
Launching lib/main.dart on Redmi K20 Pro in debug mode...
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Note: /Users/mahesh/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-2.1.1/android/src/main/java/io/flutter/plugins/googlemaps/Convert.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:59800/ClN_nQBZF5Y=/ws
I/zzbz    (15927): Making Creator dynamically
W/ple.maps_sampl(15927): Unsupported class loader
W/ple.maps_sampl(15927): Skipping duplicate class check due to unsupported classloader
W/ple.maps_sampl(15927): Unsupported class loader
I/DynamiteModule(15927): Considering local module com.google.android.gms.maps_dynamite:0 and remote module com.google.android.gms.maps_dynamite:203115000
I/DynamiteModule(15927): Selected remote version of com.google.android.gms.maps_dynamite, version >= 203115000
V/DynamiteModule(15927): Dynamite loader version >= 2, using loadModule2NoCrashUtils
W/ple.maps_sampl(15927): ClassLoaderContext classpath size mismatch. expected=3, found=4 (DLC[];PCL[/data/app/~~HgG0q9kUQG0PIGuCEadKLg==/com.whatsapp-4zjWe0Ygbp7GdPpomnV9Yw==/base.apk*2023969809:/data/app/~~HgG0q9kUQG0PIGuCEadKLg==/com.whatsapp-4zjWe0Ygbp7GdPpomnV9Yw==/base.apk!classes2.dex*1581413119:/data/app/~~HgG0q9kUQG0PIGuCEadKLg==/com.whatsapp-4zjWe0Ygbp7GdPpomnV9Yw==/base.apk!classes3.dex*3045803654]{PCL[/system/framework/org.apache.http.legacy.jar*1721227950]} | DLC[];PCL[/data/app/~~QzIBykjV2SS0vikdzPXoGg==/com.example.maps_sample-Q6jzWADn_WGka_kkITNENQ==/base.apk*2373407578:/data/app/~~QzIBykjV2SS0vikdzPXoGg==/com.example.maps_sample-Q6jzWADn_WGka_kkITNENQ==/base.apk!classes2.dex*4128526065:/data/app/~~QzIBykjV2SS0vikdzPXoGg==/com.example.maps_sample-Q6jzWADn_WGka_kkITNENQ==/base.apk!classes3.dex*1176249800:/data/app/~~QzIBykjV2SS0vikdzPXoGg==/com.example.maps_sample-Q6jzWADn_WGka_kkITNENQ==/base.apk!classes4.dex*2459272281]{PCL[/system/framework/org.apache.http.legacy.jar*1721227950]})
W/ple.maps_sampl(15927): Found duplicate classes, falling back to extracting from APK : /data/user_de/0/com.google.android.gms/app_chimera/m/000002a5/MapsDynamite.apk
W/ple.maps_sampl(15927): NOTE: This wastes RAM and hurts startup performance.
W/ple.maps_sampl(15927): Found duplicated class when checking oat files: 'Landroid/support/v4/app/RemoteActionCompatParcelizer;' in /data/app/~~QzIBykjV2SS0vikdzPXoGg==/com.example.maps_sample-Q6jzWADn_WGka_kkITNENQ==/base.apk and /data/user_de/0/com.google.android.gms/app_chimera/m/000002a5/MapsDynamite.apk
I/Google Maps Android API(15927): Google Play services client version: 12451000
I/Google Maps Android API(15927): Google Play services package version: 214815037
I/Google Maps Android API(15927): Google Play services maps renderer version(legacy): 203115000
W/ProtoDataStoreFlagStore(15927): Unable to retrieve flag snapshot for com.google.android.gms.maps#com.example.maps_sample, using defaults.
I/TetheringManager(15927): registerTetheringEventCallback:com.example.maps_sample
D/SurfaceView(15927): UPDATE null, mIsCastMode = false
W/Looper  (15927): PerfMonitor doFrame : time=42ms vsyncFrame=1435916 latency=458ms procState=2 historyMsgCount=3 (msgIndex=1 wall=473ms seq=168 running=326ms runnable=28ms io=10ms binder=108ms late=2ms h=android.os.Handler c=io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ)
E/GoogleMapController(15927): Cannot enable MyLocation layer as location permissions are not granted
I/ple.maps_sampl(15927): WaitForGcToComplete blocked RunEmptyCheckpoint on ProfileSaver for 9.414ms
I/ple.maps_sampl(15927): ProcessProfilingInfo new_methods=1423 is saved saved_to_disk=1 resolve_classes_delay=8000
I/bf      (15927): Successfully registered with Phenotype.
W/BpBinder(15927): PerfMonitor binderTransact :  time=365ms interface=com.google.android.gms.maps.auth.IApiTokenService code=1
E/libc    (15927): Access denied finding property "ro.vendor.df.effect.conflict"
E/libc    (15927): Access denied finding property "ro.vendor.knock.type"
W/Thread-6(15927): type=1400 audit(0.0:172389): avc: denied { read } for name="u:object_r:vendor_displayfeature_prop:s0" dev="tmpfs" ino=28869 scontext=u:r:untrusted_app:s0:c1,c260,c512,c768 tcontext=u:object_r:vendor_displayfeature_prop:s0 tclass=file permissive=0 app=com.example.maps_sample
W/DynamiteModule(15927): Local module descriptor class for com.google.android.gms.googlecertificates not found.
I/DynamiteModule(15927): Considering local module com.google.android.gms.googlecertificates:0 and remote module com.google.android.gms.googlecertificates:6
I/DynamiteModule(15927): Selected remote version of com.google.android.gms.googlecertificates, version >= 6
W/ProtoDataStoreFlagStore(15927): Unable to retrieve flag snapshot for com.google.android.libraries.consentverifier#com.example.maps_sample, using defaults.
W/ProtoDataStoreFlagStore(15927): Unable to update local snapshot for com.google.android.libraries.consentverifier#com.example.maps_sample, may result in stale flags.
W/ProtoDataStoreFlagStore(15927): java.util.concurrent.ExecutionException: java.lang.SecurityException: GoogleCertificatesRslt: Package signed with unknown certificate (go/gsrlt)
W/ProtoDataStoreFlagStore(15927): 	at age.s(:com.google.android.gms.dynamite_mapsdynamite@214815081@21.48.15 (150400-0):3)
W/ProtoDataStoreFlagStore(15927): 	at age.get(:com.google.android.gms.dynamite_mapsdynamite@214815081@21.48.15 (150400-0):2)
W/ProtoDataStoreFlagStore(15927): 	at aii.a(:com.google.android.gms.dynamite_mapsdynamite@214815081@21.48.15 (150400-0):1)
W/ProtoDataStoreFlagStore(15927): 	at aho.g(:com.google.android.gms.dynamite_mapsdynamite@214815081@21.48.15 (150400-0):1)
W/ProtoDataStoreFlagStore(15927): 	at wn.d(:com.google.android.gms.dynamite_mapsdynamite@214815081@21.48.15 (150400-0):1)
W/ProtoDataStoreFlagStore(15927): 	at xu.run(:com.google.android.gms.dynamite_mapsdynamite@214815081@21.48.15 (150400-0):0)
W/ProtoDataStoreFlagStore(15927): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
W/ProtoDataStoreFlagStore(15927): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/ProtoDataStoreFlagStore(15927): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
W/ProtoDataStoreFlagStore(15927): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/ProtoDataStoreFlagStore(15927): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/ProtoDataStoreFlagStore(15927): 	at java.lang.Thread.run(Thread.java:923)
W/ProtoDataStoreFlagStore(15927): Caused by: java.lang.SecurityException: GoogleCertificatesRslt: Package signed with unknown certificate (go/gsrlt)
W/ProtoDataStoreFlagStore(15927): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2376)
W/ProtoDataStoreFlagStore(15927): 	at android.os.Parcel.createException(Parcel.java:2360)
W/ProtoDataStoreFlagStore(15927): 	at android.os.Parcel.readException(Parcel.java:2343)
W/ProtoDataStoreFlagStore(15927): 	at android.os.Parcel.readException(Parcel.java:2285)
W/ProtoDataStoreFlagStore(15927): 	at dx.aZ(:com.google.android.gms.dynamite_mapsdynamite@214815081@21.48.15 (150400-0):2)
W/ProtoDataStoreFlagStore(15927): 	at ql.a(:com.google.android.gms.dynamite_mapsdynamite@214815081@21.48.15 (150400-0):4)
W/ProtoDataStoreFlagStore(15927): 	at id.e(:com.google.android.gms.dynamite_mapsdynamite@214815081@21.48.15 (150400-0):2)
W/ProtoDataStoreFlagStore(15927): 	at jc.t(:com.google.android.gms.dynamite_mapsdynamite@214815081@21.48.15 (150400-0):2)
W/ProtoDataStoreFlagStore(15927): 	at jc.u(:com.google.android.gms.dynamite_mapsdynamite@214815081@21.48.15 (150400-0):3)
W/ProtoDataStoreFlagStore(15927): 	at jc.e(:com.google.android.gms.dynamite_mapsdynamite@214815081@21.48.15 (150400-0):2)
W/ProtoDataStoreFlagStore(15927): 	at jg.handleMessage(:com.google.android.gms.dynamite_mapsdynamite@214815081@21.48.15 (150400-0):69)
W/ProtoDataStoreFlagStore(15927): 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/ProtoDataStoreFlagStore(15927): 	at android.os.Looper.loop(Looper.java:236)
W/ProtoDataStoreFlagStore(15927): 	at android.os.HandlerThread.run(HandlerThread.java:67)
D/MIUIInput(15927): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=49358260, downTime=49358260 } moveCount:0
W/MirrorManager(15927): this model don't Support
D/MIUIInput(15927): [MotionEvent] ViewRootImpl { action=ACTION_POINTER_DOWN(1), id[0]=0, id[1]=1, pointerCount=2, eventTime=49358268, downTime=49358260 } moveCount:0
D/MIUIInput(15927): [MotionEvent] ViewRootImpl { action=ACTION_POINTER_UP(1), id[0]=0, id[1]=1, pointerCount=2, eventTime=49359255, downTime=49358260 } moveCount:62
D/MIUIInput(15927): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=49359271, downTime=49358260 } moveCount:64
D/MIUIInput(15927): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=49359582, downTime=49359582 } moveCount:0
D/MIUIInput(15927): [MotionEvent] ViewRootImpl { action=ACTION_POINTER_DOWN(1), id[0]=0, id[1]=1, pointerCount=2, eventTime=49359591, downTime=49359582 } moveCount:0
D/MIUIInput(15927): [MotionEvent] ViewRootImpl { action=ACTION_POINTER_UP(1), id[0]=0, id[1]=1, pointerCount=2, eventTime=49360205, downTime=49359582 } moveCount:65
D/MIUIInput(15927): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=49360213, downTime=49359582 } moveCount:66
D/MIUIInput(15927): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=49360497, downTime=49360497 } moveCount:0
D/MIUIInput(15927): [MotionEvent] ViewRootImpl { action=ACTION_POINTER_DOWN(1), id[0]=0, id[1]=1, pointerCount=2, eventTime=49360541, downTime=49360497 } moveCount:0
D/MIUIInput(15927): [MotionEvent] ViewRootImpl { action=ACTION_POINTER_UP(0), id[0]=0, id[1]=1, pointerCount=2, eventTime=49361577, downTime=49360497 } moveCount:102
D/MIUIInput(15927): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=1, pointerCount=1, eventTime=49361577, downTime=49360497 } moveCount:102
D/MIUIInput(15927): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=49361997, downTime=49361997 } moveCount:0
D/MIUIInput(15927): [MotionEvent] ViewRootImpl { action=ACTION_POINTER_DOWN(1), id[0]=0, id[1]=1, pointerCount=2, eventTime=49361997, downTime=49361997 } moveCount:0
D/MIUIInput(15927): [MotionEvent] ViewRootImpl { action=ACTION_POINTER_UP(0), id[0]=0, id[1]=1, pointerCount=2, eventTime=49363136, downTime=49361997 } moveCount:84
D/MIUIInput(15927): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=1, pointerCount=1, eventTime=49363169, downTime=49361997 } moveCount:87
D/MIUIInput(15927): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=49364651, downTime=49364651 } moveCount:0
D/MIUIInput(15927): [MotionEvent] ViewRootImpl { action=ACTION_POINTER_DOWN(1), id[0]=0, id[1]=1, pointerCount=2, eventTime=49364677, downTime=49364651 } moveCount:0
D/MIUIInput(15927): [MotionEvent] ViewRootImpl { action=ACTION_POINTER_UP(1), id[0]=0, id[1]=1, pointerCount=2, eventTime=49365124, downTime=49364651 } moveCount:48
D/MIUIInput(15927): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=49365140, downTime=49364651 } moveCount:50
D/MIUIInput(15927): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=49365905, downTime=49365905 } moveCount:0
D/MIUIInput(15927): [MotionEvent] ViewRootImpl { action=ACTION_POINTER_DOWN(1), id[0]=0, id[1]=1, pointerCount=2, eventTime=49365922, downTime=49365905 } moveCount:0
D/MIUIInput(15927): [MotionEvent] ViewRootImpl { action=ACTION_POINTER_UP(0), id[0]=0, id[1]=1, pointerCount=2, eventTime=49366536, downTime=49365905 } moveCount:49
D/MIUIInput(15927): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=1, pointerCount=1, eventTime=49366536, downTime=49365905 } moveCount:49
D/MIUIInput(15927): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=49375374, downTime=49375374 } moveCount:0
W/Choreographer(15927): Frame time is 0.049284 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
D/MIUIInput(15927): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=49376017, downTime=49375374 } moveCount:50
W/PlatformViewsController(15927): Creating a virtual display of size: [1080, 2340] may result in problems(https://github.com/flutter/flutter/issues/2897).It is larger than the device screen size: [1080, 2210].
D/SurfaceView(15927): UPDATE Surface(name=SurfaceView - Sys2030:com.example.maps_sample/com.example.maps_sample.MainActivity)/@0x6a7bdcc, mIsCastMode = false
D/SurfaceView(15927): UPDATE null, mIsCastMode = false
D/SurfaceView(15927): UPDATE Surface(name=SurfaceView - Sys2030:com.example.maps_sample/com.example.maps_sample.MainActivity)/@0xf2f54f5, mIsCastMode = false
D/SurfaceView(15927): UPDATE null, mIsCastMode = false
D/MIUIInput(15927): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=49390841, downTime=49390841 } moveCount:0
D/MIUIInput(15927): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=49392038, downTime=49390841 } moveCount:100
D/MIUIInput(15927): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=49392539, downTime=49392539 } moveCount:0
D/MIUIInput(15927): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=49393229, downTime=49392539 } moveCount:42
D/MIUIInput(15927): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=49399056, downTime=49399056 } moveCount:0
W/Choreographer(15927): Frame time is 0.223018 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
D/MIUIInput(15927): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=49399518, downTime=49399056 } moveCount:43
D/MIUIInput(15927): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=49399550, downTime=49399550 } moveCount:0
D/MIUIInput(15927): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=49399727, downTime=49399550 } moveCount:7
I/ple.maps_sampl(15927): Thread[5,tid=15937,WaitingInMainSignalCatcherLoop,Thread*=0xb400007108ad6c00,peer=0x13300260,"Signal Catcher"]: reacting to signal 3
I/ple.maps_sampl(15927):
I/ple.maps_sampl(15927): Wrote stack traces to tombstoned
Lost connection to device.
Exited (sigterm)
```

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.10.2, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.10.2 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (2 days ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:5555 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos            • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 98.0.4758.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 2.11.0-0.0.pre.582, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.11.0-0.0.pre.582 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9514106108 (5 days ago), 2022-02-16 00:00:11 -0500
    • Engine revision b09cf53269
    • Dart version 2.17.0 (build 2.17.0-105.0.dev)
    • DevTools version 2.10.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:5555 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos            • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 98.0.4758.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details> 

Here's a similar issue https://github.com/flutter/flutter/issues/40284 but the logs don't look similar

**Comment by danagbemava-nc** [comment]
Hi @maheshmnj, I attempted to reproduce this on my `Poco X3 NFC` and `Pixel 4a`  but it did not reproduce, on both `master` and `stable`. 
Kindly see video below and let me know if I missed something about the steps to reproduce. 

https://user-images.githubusercontent.com/88313112/154968613-a195c982-b061-49dc-970d-216d80f4d08c.mov

**Comment by danagbemava-nc** [comment]
I've been attempting to reproduce this but with no luck. Considering you were not able to reproduce on the emulator as well, I think this might be affecting a group of devices. 

Since I'm unable to reproduce this locally, I'm going to label this for further investigation. 

I'll keep looking into it and update if I'm able to reproduce this.

**Comment by PollexLee** [comment]
I reproduce this issue in debug mode.

**Comment by Tim-HNK** [comment]
I can recreate it on Android 12 by repeatedly locking and unlocking my phone. 
(might take 10-15mins of trying)
- Samsung Galaxy S20 FE, flutter 2.10.5, Google_maps_flutter 2.1.4 

This error keeps repeating in logcat when my map disappears. 

```
2022-04-29 10:39:56.223 27141-28899/com.XXX.YYY E/BufferQueueProducer: [SurfaceTexture-0-27141-2](id:6a0500000024,api:0,p:-1,c:27141) dequeueBuffer: BufferQueue has no connected producer
2022-04-29 10:39:56.223 1132-1132/? E/CompositionEngine: ANativeWindow::dequeueBuffer failed for display [flutter-vd] with error: -19
2022-04-29 10:39:56.223 1132-1132/? W/CompositionEngine: Dequeuing buffer for display [flutter-vd] failed, bailing out of client composition for this frame
```

Some things i've noticed:
- The map is transparent, you can see widgets behind it.
- It still catches touch events, you can't press a button behind it.
- Touch events on (now invisible) markers still work if you manage to find them.
- Occasionally the map restores after resuming the app again. The same actions causing the bug can sometimes revert it.


#40284 Looks the same but probably has a different cause.
Their workaround of `controller.setStyle` on application resume works for my older android devices, but I get this (nearly identical?) bug on Android 12.

A workaround is removing the GoogleMap widget from the widget tree for 1 frame.
But I haven't found a good way to detect that the bug has occurred, so this needs to be triggered manually for now.
```
Widget build(BuildContext context) {
  ...
  if(_includeMap)
    GoogleMap(key: .., ),
  ...
}

//Build a new google map widget
 void _resetMap() {
    // set true after the build that handles setting it false
   WidgetsBinding.instance!.addPostFrameCallback((_) {
      setState(() {
        _includeMap = true;
      });
  });
  setState(() {
    _includeMap = false;
  });
}

```

**Comment by kldMohammed** [comment]
I also have this issue every time I locked phone and unlocked it. 
on:
 Android 12 Poco F3 GT
Redmi note 10 pro

**Comment by note11g** [comment]
This Problem reproduced on Emulator (Android 11, 12)

log include this line.
```
dequeueBuffer: BufferQueue has no connected producer
```

and maybe TLHC cause this issue.
not reproduce on HC(`PlatformViewsService.initExpensiveAndroidView`).

**Comment by johnmccutchan** [comment]
I can't reproduce this issue at flutter head using version 2.5.3 of google_maps_flutter.

**Comment by note11g** [comment]
hey, it's very critical issue.

 Interaction with the map screen becomes impossible.

 Just closing it just because it can't be reproduced ignores the function of the community.

 Please review it again. Intermittent, but it is judged that there are enough reproduction steps.

**Comment by johnmccutchan** [comment]
This bug is multiple years old and isn't getting a lot of attention from users. Given those facts, I don't see why this should be considered a "critical" issue. Most of the comments on the bug are people confirming they cannot reproduce the issue and some suggestions that it is device-specific.

I spent a lot of time trying to reproduce this issue yesterday and couldn't. If a bug can't be reliably reproduced it won't get fixed and keeping bugs open without reliable reproduction steps doesn't serve anyone.

That being said, I encourage you to file a new bug with reliable reproduction steps against the latest releases of Flutter and the Google Maps plugin.
