### ISSUE TITLE
[tool_crash] FormatException

### ISSUE THREAD

**Issue by dk3030** [flutter/flutter#98905]
## Command
```
flutter --quiet assemble --no-version-check --depfile D:\DHRUMI\Projects\Projects_Gatistavam_Softect\GP----DialPad\CODE\DIALPAD_SVN\build\app\intermediates\flutter\debug/flutter_build.d --output D:\DHRUMI\Projects\Projects_Gatistavam_Softect\GP----DialPad\CODE\DIALPAD_SVN\build\app\intermediates\flutter\debug -dTargetFile=D:\DHRUMI\Projects\Projects_Gatistavam_Softect\GP----DialPad\CODE\DIALPAD_SVN\lib\main.dart -dTargetPlatform=android -dBuildMode=debug -dTrackWidgetCreation=true --DartDefines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== debug_android_application
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FormatException
```
#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1405:5)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1272:9)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:937:22)
#3      _parseJson (dart:convert-patch/convert_patch.dart:40:10)
#4      JsonDecoder.convert (dart:convert/json.dart:612:36)
#5      JsonCodec.decode (dart:convert/json.dart:216:41)
#6      FlutterBuildSystem.trackSharedBuildDirectory (package:flutter_tools/src/build_system/build_system.dart:737:44)
#7      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:630:5)
<asynchronous suspension>
#8      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:317:32)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.10.1, on Microsoft Windows [Version 10.0.19043.1526], locale en-IN)
    • Flutter version 2.10.1 at D:\DHRUMI\Flutter_SDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (12 days ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at D:\DHRUMI\Android_SDK
    • Platform android-31, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.10)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.32126.315
    • Windows 10 SDK version 10.0.19041.0
    ✗ The current Visual Studio installation is incomplete. Please reinstall Visual Studio.

[✓] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[!] Android Studio
    • Android Studio at D:\DHRUMI\Android_SDK
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ android-studio-dir = D:\DHRUMI\Android_SDK
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.
    • Consider removing your android-studio-dir setting by running:
      flutter config --android-studio-dir=

[✓] Connected device (4 available)
    • RMX3370 (mobile)  • ce0b2e80 • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows  • windows-x64    • Microsoft Windows [Version 10.0.19043.1526]
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 98.0.4758.102
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 98.0.1108.56

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 77d935af4db863f6abd0b9c31c7e6df2a13de57b
### Plugins
audioplayers-0.20.1
firebase_auth-3.3.7
firebase_auth_web-3.3.7
firebase_core-1.12.0
firebase_core_web-1.5.4
firebase_messaging-11.2.6
firebase_messaging_web-2.2.7
google_sign_in-5.2.3
google_sign_in_web-0.10.0+4
path_provider-2.0.9
path_provider_android-2.0.11
path_provider_ios-2.0.7
path_provider_linux-2.1.5
path_provider_macos-2.0.5
path_provider_windows-2.0.5
shared_preferences-2.0.13
shared_preferences_android-2.0.11
shared_preferences_ios-2.0.10
shared_preferences_linux-2.1.0
shared_preferences_macos-2.0.3
shared_preferences_web-2.0.3
shared_preferences_windows-2.1.0
twilio_voice-0.0.9

**Comment by danagbemava-nc** [comment]
Labelling for further investigation as I cannot see any similar opened issues.

**Comment by christopherfujino** [comment]
as a breadcrumb, this is the line (near) the top of the stacktrace: https://github.com/flutter/flutter/blob/stable/packages/flutter_tools/lib/src/build_system/build_system.dart#L737

**Comment by aboutmydreams** [comment]
Check to see if it's due to an external browser plugin writing malformed json to localstorage

https://github.com/flutter/packages/pull/5813

**Comment by christopherfujino** [comment]
> Check to see if it's due to an external browser plugin writing malformed json to localstorage
> 
> [flutter/packages#5813](https://github.com/flutter/packages/pull/5813)

The Flutter CLI tool doesn't run in the browser
