### ISSUE TITLE
Custom icons alignment is inconsistent between iOS and Android

### ISSUE THREAD

**Issue by mattcianna** [flutter/flutter#98909]
The icon font baseline is different between iOS and Android, creating an inconsistent behaviour between these platforms. Specifically, the Android icon is misaligned.

<img src="https://user-images.githubusercontent.com/10003040/155090554-c7d6b2f6-2588-4a2a-ba91-95bff76fa7ca.png" width="200" height="auto">
<img src="https://user-images.githubusercontent.com/10003040/155090589-a492eeaf-a6b4-41a7-b1c1-d3a3df7ee268.png" width="200" height="auto">

This is the example project containing the icon font.
[icon_test.zip](https://github.com/flutter/flutter/files/8114878/icon_test.zip)

### Steps to reproduce
```
    return const Center(
      child: Icon(
        UiIcons.checkmark_circle,
        size: 200,
      ),
    );
```

The misalignment seems to be related to the `SizedBox` inside the `Icon` widget, since wrapping a simple `Text` inside a `SizedBox` with the same height of the `Text` size causes a misalignment to the label and since removing the `SizedBox` from the `Icon` fixes the problem.

```
[✓] Flutter (Channel stable, 2.10.2, on macOS 12.1 21C52 darwin-x64, locale en-IT)
    • Flutter version 2.10.2 at /Users/mciannavei/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (3 days ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mciannavei/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mciannavei/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5556                            • android-x64    • Android 12 (API 31) (emulator)
    • iPad di Matteo (mobile)      • 9cbe715e4d9a7ce865b366c0fc4483071a7af3e3 • ios            • iOS 12.5.5 16H62
    • iPhone 8 (mobile)            • 2B15CA33-6619-46F7-8B5C-BB8352239A79     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • Chrome (web)                 • chrome                                   • web-javascript • Google Chrome 98.0.4758.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by danagbemava-nc** [comment]
Reproducible on `stable` and `master`. 

See screenshots below

## Steps to reproduce
1. Run the code sample below (run `flutter pub get first`)
2. Switch between the Custom icon and the in-built icons to see the differences.

<details>
<summary>screenshots</summary>

### Custom Icons

| iOS | android | macOS | chrome(HTML) | chrome(canvaskit) | 
| -- | -- | -- | -- | -- | 
| ![Simulator Screen Shot - iPhone 13 - 2022-02-22 at 08 50 35](https://user-images.githubusercontent.com/88313112/155107149-6cf54a0c-f343-493e-bfd4-5128a5a8c44a.png) | ![Screenshot_1645520157](https://user-images.githubusercontent.com/88313112/155107199-08bede2e-f5f9-45ff-81cd-322134aa482c.png) | <img width="551" alt="Screenshot 2022-02-22 at 09 11 34" src="https://user-images.githubusercontent.com/88313112/155107327-772b442c-4401-4326-9a34-69ed15d862fe.png"> | <img width="612" alt="Screenshot 2022-02-22 at 09 12 55" src="https://user-images.githubusercontent.com/88313112/155107373-b259cbae-e407-42aa-a32f-1e4204b8031e.png"> | <img width="612" alt="Screenshot 2022-02-22 at 09 13 46" src="https://user-images.githubusercontent.com/88313112/155107435-74aaab7a-6f6a-4a7e-836f-881721495ef9.png"> | 



### Inbuilt icons
| iOS | android | macOS | chrome (HTML) | chrome (canvaskit) |
| -- | -- | -- | -- | -- |
| ![Simulator Screen Shot - iPhone 13 - 2022-02-22 at 09 46 50](https://user-images.githubusercontent.com/88313112/155107647-5adf941c-61da-470b-ab4b-2fb76e406325.png) | ![Screenshot_1645522075](https://user-images.githubusercontent.com/88313112/155107717-6fd1a718-8750-482b-a54c-cb968a15dd56.png) | <img width="572" alt="Screenshot 2022-02-22 at 09 57 48" src="https://user-images.githubusercontent.com/88313112/155108402-53fa97b9-b6ca-48c5-86a6-974be1c098f3.png"> | <img width="612" alt="Screenshot 2022-02-22 at 09 56 44" src="https://user-images.githubusercontent.com/88313112/155108453-d3d17cd8-2bc3-4459-a81b-13576576b9c8.png"> | <img width="612" alt="Screenshot 2022-02-22 at 09 55 55" src="https://user-images.githubusercontent.com/88313112/155108481-4630b6f1-f924-4475-aafb-544625a185c6.png"> |

The inbuilt icons seem to be consistent across platforms

</details>

<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.10.2, on macOS 12.2 21D49 darwin-arm, locale en-GB)
    • Flutter version 2.10.2 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (3 days ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not
      helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml
      (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion
      (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage
      (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate
      (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure>
      (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure>
      (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1426:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1861:10)
      #15     runZonedGuarded (dart:async/zone.dart:1849:12)
      #16     runZoned (dart:async/zone.dart:1780:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:205:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:309:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #21     FlutterCommand.verifyThenRunCommand
      (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure>
      (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure>
      (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure>
      (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure>
      (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand
      (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure>
      (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure>
      (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.2 21D49 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 98.0.4758.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel master, 2.11.0-0.0.pre.634, on macOS 12.2 21D49 darwin-arm, locale en-GB)
    • Flutter version 2.11.0-0.0.pre.634 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 617de91198 (18 hours ago), 2022-02-21 11:04:12 -0500
    • Engine revision f6ea6186ee
    • Dart version 2.17.0 (build 2.17.0-125.0.dev)
    • DevTools version 2.11.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 213.5744.122

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.2 21D49 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 98.0.4758.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

[icon_test 2.zip](https://github.com/flutter/flutter/files/8115600/icon_test.2.zip)

**Comment by HansMuller** [comment]
CC @guidezpl

**Comment by yjbanov** [comment]
@danagbemava-nc How did you determine that this is a canvaskit issue? By default iOS and Android run in HTML mode. If this is in HTML mode, let's switch the label to web_html.

**Comment by danagbemava-nc** [comment]
Hi @yjbanov, I should have provided more context in my response. In my testing, this reproduced on native `android` and the web but only when using `canvaskit`, the `html` renderer, as well as the other platforms that I tested on, did not have this issue. 

So the issue is more like it affects native android and the web platform but only when using canvaskit

**Comment by cmc5788** [comment]
@danagbemava-nc -- I'm having this same issue, so to troubleshoot I duplicated the source code of the `Icon` widget into a `TestIcon` and changed the internal `RichText` of the `Icon` widget as follows:

Added 

```dart
textHeightBehavior: const mat.TextHeightBehavior(
        applyHeightToFirstAscent: false,
      ),
```

 ... so ...

```dart

    Widget iconWidget = RichText(
      textHeightBehavior: const mat.TextHeightBehavior(
        applyHeightToFirstAscent: false,
      ),
      overflow: TextOverflow.visible, // Never clip.
      textDirection:
          textDirection, // Since we already fetched it for the assert...
      text: TextSpan(
        text: String.fromCharCode(icon!.codePoint),
        style: TextStyle(
          inherit: false,
          color: iconColor,
          fontSize: iconSize,
          fontFamily: icon!.fontFamily,
          package: icon!.fontPackage,
        ),
      ),
    );
```

Does this same patch solve your issue by any chance?
