### ISSUE TITLE
[Android] Element.widget - Null check operator used on a null value. 

### ISSUE THREAD

**Issue by bswhite1** [flutter/flutter#98937]
Several hundred crashlitics reports from many android users when we updated to 2.10.0
Other than it probably is related to text, I can't narrow it down further.

See crash log below.

I believe this is the root-cause of the crash reports we have been getting, and does not appear to be null safe.
From framework.dart
abstract class Element extends DiagnosticableTree implements BuildContext
  Widget get widget => _widget!;
  Widget? _widget;
  

<details>
  <summary>Logs</summary>

```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Null check operator used on a null value. Error thrown Instance of 'ErrorDescription'.
       at Element.widget(Element.java:3203)
       at ProxyElement.widget(ProxyElement.java:5094)
       at InheritedElement.widget(InheritedElement.java:5201)
       at Element.dependOnInheritedElement(Element.java:4177)
       at Element.dependOnInheritedWidgetOfExactType(Element.java:4185)
       at MediaQuery.maybeOf(MediaQuery.java:892)
       at MediaQuery.boldTextOverride(MediaQuery.java:924)
       at Text.build(Text.java:525)
       at StatelessElement.build(StatelessElement.java:4827)
       at ComponentElement.performRebuild(ComponentElement.java:4754)
       at Element.rebuild(Element.java:4477)
       at StatelessElement.update(StatelessElement.java:4834)
       at Element.updateChild(Element.java:3501)
       at SingleChildRenderObjectElement.update(SingleChildRenderObjectElement.java:6291)
       at Element.updateChild(Element.java:3501)
       at SingleChildRenderObjectElement.update(SingleChildRenderObjectElement.java:6291)
       at Element.updateChild(Element.java:3501)
       at RenderObjectElement.updateChildren(RenderObjectElement.java:5787)
       at MultiChildRenderObjectElement.update(MultiChildRenderObjectElement.java:6445)
       at Element.updateChild(Element.java:3501)
       at SingleChildRenderObjectElement.update(SingleChildRenderObjectElement.java:6291)
       at Element.updateChild(Element.java:3501)
       at ComponentElement.performRebuild(ComponentElement.java:4780)
       at Element.rebuild(Element.java:4477)
       at StatelessElement.update(StatelessElement.java:4834)
       at Element.updateChild(Element.java:3501)
       at RenderObjectElement.updateChildren(RenderObjectElement.java:5787)
       at MultiChildRenderObjectElement.update(MultiChildRenderObjectElement.java:6445)
       at Element.updateChild(Element.java:3501)
       at ComponentElement.performRebuild(ComponentElement.java:4780)
       at Element.rebuild(Element.java:4477)
       at StatelessElement.update(StatelessElement.java:4834)
       at Element.updateChild(Element.java:3501)
       at ComponentElement.performRebuild(ComponentElement.java:4780)
       at Element.rebuild(Element.java:4477)
       at ProxyElement.update(ProxyElement.java:5108)
       at Element.updateChild(Element.java:3501)
       at ComponentElement.performRebuild(ComponentElement.java:4780)
       at StatefulElement.performRebuild(StatefulElement.java:4928)
       at Element.rebuild(Element.java:4477)
       at StatefulElement.update(StatefulElement.java:4960)
       at Element.updateChild(Element.java:3501)
       at SingleChildRenderObjectElement.update(SingleChildRenderObjectElement.java:6291)
       at Element.updateChild(Element.java:3501)
       at ComponentElement.performRebuild(ComponentElement.java:4780)
       at Element.rebuild(Element.java:4477)
       at StatelessElement.update(StatelessElement.java:4834)
       at Element.updateChild(Element.java:3501)
       at SingleChildRenderObjectElement.update(SingleChildRenderObjectElement.java:6291)
       at Element.updateChild(Element.java:3501)
       at ComponentElement.performRebuild(ComponentElement.java:4780)
       at StatefulElement.performRebuild(StatefulElement.java:4928)
       at Element.rebuild(Element.java:4477)
       at StatefulElement.update(StatefulElement.java:4960)
       at Element.updateChild(Element.java:3501)
       at ComponentElement.performRebuild(ComponentElement.java:4780)
       at StatefulElement.performRebuild(StatefulElement.java:4928)
       at Element.rebuild(Element.java:4477)
       at StatefulElement.update(StatefulElement.java:4960)
       at Element.updateChild(Element.java:3501)
       at ComponentElement.performRebuild(ComponentElement.java:4780)
       at StatefulElement.performRebuild(StatefulElement.java:4928)
       at Element.rebuild(Element.java:4477)
       at StatefulElement.update(StatefulElement.java:4960)
       at Element.updateChild(Element.java:3501)
       at ComponentElement.performRebuild(ComponentElement.java:4780)
       at StatefulElement.performRebuild(StatefulElement.java:4928)
       at Element.rebuild(Element.java:4477)
       at BuildOwner.buildScope(BuildOwner.java:2659)
       at WidgetsBinding.drawFrame(WidgetsBinding.java:882)
       at RendererBinding._handlePersistentFrameCallback(RendererBinding.java:363)
       at SchedulerBinding._invokeFrameCallback(SchedulerBinding.java:1144)
       at SchedulerBinding.handleDrawFrame(SchedulerBinding.java:1081)
       at SchedulerBinding._handleDrawFrame(SchedulerBinding.java:995)
```

```
```
</details>
<details>
<summary>Versions</summary>

[✓] Flutter (Channel stable, 2.10.0, on macOS 12.2.1 21D62 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.63.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

```
```

</details>

**Comment by maheshmnj** [comment]
Hi @bswhite1, Thanks for filing the issue. Is this exception reproducible locally ?  if so can you please share the output of `flutter run -v`.  Also does this reproduce only on android or ios too?

**Comment by bswhite1** [comment]
We have not seen it locally, only on crashlitics. Our app is android only at this point.

**Comment by maheshmnj** [comment]
Thanks for the info leaving this issue open for further investigation from the team. In case you have any further error logs or crash reports, please feel free to add them.

**Comment by goderbauer** [comment]
Unfortunately, with the information in here there isn't much we can do about this crash. We would need some way of reproducing it.

`_widget` does get nulled out correctly when the Element is unmounted. At that point it is illegal to interact with the element anymore, so the code you point to is fine.
