### ISSUE TITLE
issue on video decoder 

### ISSUE THREAD

**Issue by adarsh904** [flutter/flutter#98980]
```
Failed to initialize decoder: OMX.qcom.video.decoder.avc
W/MediaCodecRenderer(28477): android.media.MediaCodec$CodecException: Error 0xfffffff4
W/MediaCodecRenderer(28477): at android.media.MediaCodec.native_configure(Native Method)
W/MediaCodecRenderer(28477): at android.media.MediaCodec.configure(MediaCodec.java:2127)
W/MediaCodecRenderer(28477): at android.media.MediaCodec.configure(MediaCodec.java:2043)
W/MediaCodecRenderer(28477): at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter$Factory.createAdapter(SynchronousMediaCodecAdapter.java:50)
W/MediaCodecRenderer(28477): at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1121)
W/MediaCodecRenderer(28477): at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1027)
W/MediaCodecRenderer(28477): at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:585)
W/MediaCodecRenderer(28477): at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1455)
W/MediaCodecRenderer(28477): at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:713)
W/MediaCodecRenderer(28477): at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:981)
W/MediaCodecRenderer(28477): at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:810)
W/MediaCodecRenderer(28477): at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:978)
W/MediaCodecRenderer(28477): at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:482)
W/MediaCodecRenderer(28477): at android.os.Handler.dispatchMessage(Handler.java:102)
W/MediaCodecRenderer(28477): at android.os.Looper.loop(Looper.java:246)
W/MediaCodecRenderer(28477): at android.os.HandlerThread.run(HandlerThread.java:67)
E/MediaCodecVideoRenderer(28477): Video codec error
E/MediaCodecVideoRenderer(28477): com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, avc1.64001F, -1, null, [1280, 720, 25.0], [-1, -1])
E/MediaCodecVideoRenderer(28477): at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1034)
E/MediaCodecVideoRenderer(28477): at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:585)
E/MediaCodecVideoRenderer(28477): at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1455)
E/MediaCodecVideoRenderer(28477): at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:713)
E/MediaCodecVideoRenderer(28477): at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:981)
E/MediaCodecVideoRenderer(28477): at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:810)
E/MediaCodecVideoRenderer(28477): at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:978)
E/MediaCodecVideoRenderer(28477): at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:482)
E/MediaCodecVideoRenderer(28477): at android.os.Handler.dispatchMessage(Handler.java:102)
E/MediaCodecVideoRenderer(28477): at android.os.Looper.loop(Looper.java:246)
E/MediaCodecVideoRenderer(28477): at android.os.HandlerThread.run(HandlerThread.java:67)
E/MediaCodecVideoRenderer(28477): Caused by: android.media.MediaCodec$CodecException: Error 0xfffffff4
E/MediaCodecVideoRenderer(28477): at android.media.MediaCodec.native_configure(Native Method)
E/MediaCodecVideoRenderer(28477): at android.media.MediaCodec.configure(MediaCodec.java:2127)
E/MediaCodecVideoRenderer(28477): at android.media.MediaCodec.configure(MediaCodec.java:2043)
E/MediaCodecVideoRenderer(28477): at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter$Factory.createAdapter(SynchronousMediaCodecAdapter.java:50)
E/MediaCodecVideoRenderer(28477): at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1121)
E/MediaCodecVideoRenderer(28477): at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1027)
E/MediaCodecVideoRenderer(28477): ... 10 more
E/ExoPlayerImplInternal(28477): Playback error
E/ExoPlayerImplInternal(28477): com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.64001F, -1, null, [1280, 720, 25.0], [-1, -1]), format_supported=YES
E/ExoPlayerImplInternal(28477): at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:558)
E/ExoPlayerImplInternal(28477): at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal(28477): at android.os.Looper.loop(Looper.java:246)
E/ExoPlayerImplInternal(28477): at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(28477): Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, avc1.64001F, -1, null, [1280, 720, 25.0], [-1, -1])
E/ExoPlayerImplInternal(28477): at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1034)
E/ExoPlayerImplInternal(28477): at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:585)
E/ExoPlayerImplInternal(28477): at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1455)
E/ExoPlayerImplInternal(28477): at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:713)
E/ExoPlayerImplInternal(28477): at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:981)
E/ExoPlayerImplInternal(28477): at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:810)
E/ExoPlayerImplInternal(28477): at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:978)
E/ExoPlayerImplInternal(28477): at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:482)
E/ExoPlayerImplInternal(28477): ... 3 more
E/ExoPlayerImplInternal(28477): Caused by: android.media.MediaCodec$CodecException: Error 0xfffffff4
E/ExoPlayerImplInternal(28477): at android.media.MediaCodec.native_configure(Native Method)
E/ExoPlayerImplInternal(28477): at android.media.MediaCodec.configure(MediaCodec.java:2127)
E/ExoPlayerImplInternal(28477): at android.media.MediaCodec.configure(MediaCodec.java:2043)
E/ExoPlayerImplInternal(28477): at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter$Factory.createAdapter(SynchronousMediaCodecAdapter.java:50)
E/ExoPlayerImplInternal(28477): at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1121)
E/ExoPlayerImplInternal(28477): at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1027)
E/ExoPlayerImplInternal(28477): ... 10 more
```

**Comment by maheshmnj** [comment]
Hi @adarsh904, When filing issues please try to fil, all or some of the information requested in the issue template, pasting only a partial error log wouldn't make this issue actionable. To investigate this issue further, please update the issue description clearly describing the issue along with the output of `flutter doctor -v` and a minimal and complete sample code (if required)
