### ISSUE TITLE
[google_maps_flutter] android 12, map corrupted after return from a screen which is loading android keyboard

### ISSUE THREAD

**Issue by Aidamir** [flutter/flutter#99199]
## Steps to Reproduce

1. Start android 12 emulator or attach device running android 12 
2. Execute `flutter run` on the code from repository [https://github.com/Aidamir/flutter_gmap_corruption](url)  or create your own project from the code samples below. Don't forget to put your google API_KEY to manifest.xml before running.
3. Press floating button at the bottom of the map, You will see the page with single TextField
4. Tap to the TextField to show android keyboard 
5. Press return button on the top left of the page, you will see the white screen or somehow patially rendered map. 
6. If you do not see corrupted map repeat steps 2 - 4 again 3- 5 times until you see corrupted map.

https://user-images.githubusercontent.com/8030331/155834701-5da55fed-d28e-4898-bf4f-baa9ce8fd80c.mp4

**Expected results:** 
When return to the map screen,  it should be in the same state as when you left it. 
**Actual results:** 
When return to the map screen, you see corrupted map.

Here is also [stackoverflow post](https://stackoverflow.com/questions/71250136/flutter-google-maps-corrupts-after-return-from-a-screen-containing-input)
<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:mytest/input_page.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  CameraPosition initialCameraPosition = const CameraPosition(target: LatLng(40.7384685, -73.9890675), zoom: 0.0);
  void _moveToInputPage() {
    Navigator.push(
      context,
      MaterialPageRoute(builder: (context) => const InputPage())
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: const Center(
          child: GoogleMap(
        initialCameraPosition: CameraPosition(target: LatLng(40.7384685, -73.9890675), zoom: 0.0)
      )),
      floatingActionButton: FloatingActionButton(
        onPressed: _moveToInputPage,
        child: const Icon(Icons.arrow_forward),
      ),
    );
  }
}
```
 input_page.dart
```dart
import 'package:flutter/material.dart';

class InputPage extends StatefulWidget {
  const InputPage({Key? key}) : super(key: key);

  @override
  _InputPageState createState() => _InputPageState();
}

class _InputPageState extends State<InputPage> {
  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () {
        FocusManager.instance.primaryFocus?.unfocus();
      },
      child: Scaffold(
          appBar: AppBar(
            title: const Text("Input Page"),
          ),
          body: Center(
            child: Container(
              color: Colors.grey[300],
              child: const TextField(
//   Enable autofocus to see corrupted map every time.
//              autofocus: true,
              ),
            ),
          )),
    );
  }
}
```
</details>

<details>
  <summary>Logs</summary>
[log.gz](https://github.com/flutter/flutter/files/8146167/log.gz)

```

```

```
archi@eagle:~/prj/flutt/flutter_gmap_corruption$ flutter analyze
Analyzing flutter_gmap_corruption...                                    
No issues found! (ran in 1.5s)
```

```
archi@eagle:~/prj/flutt/flutter_gmap_corruption$ flutter doctor -v
[✓] Flutter (Channel stable, 2.10.2, on Ubuntu 20.04.4 LTS 5.16.10-051610-generic, locale ru_RU.UTF-8)
    • Flutter version 2.10.2 at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (7 дней назад), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/archi/Android/Sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /opt/android-studio-2021.1.1/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /opt/android-studio-2021.1.1/android-studio
    • Flutter plugin version 64.1.2
    • Dart plugin version 211.7798
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] Android Studio
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[☠] IntelliJ IDEA Ultimate Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
     

[✓] VS Code (version 1.64.2)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 96.0.4664.93

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```
I don't think these issue crash with IDEA can affect of the bug somehow IDEA is working fine.
Thanks.

</details>

**Comment by maheshmnj** [comment]
Hi @Aidamir, Thanks for filing the issue. Thi issue looks similar to https://github.com/flutter/flutter/issues/90556 (closed). Could you please try using hybrid composition with the latest maps plugin and see if that fixes the issue for you?

> To use [Hybrid Composition](https://flutter.dev/docs/development/platform-integration/platform-views) to render the GoogleMap widget on Android, set AndroidGoogleMapsFlutter.useAndroidViewSurface to true.

```dart
if (defaultTargetPlatform == TargetPlatform.android) {
  AndroidGoogleMapsFlutter.useAndroidViewSurface = true;
}
```

**Comment by Aidamir** [comment]
Hi @maheshmnj. Thank you. Yes, this code completely solves the isuue.
