### ISSUE TITLE
Error in KeyEventManager: null check operator used on a null value

### ISSUE THREAD

**Issue by stx** [flutter/flutter#99196]
Similar to https://github.com/flutter/flutter/issues/93318. @dkwingsmt FYI

Seen on Crashlytics production on Android 9 Intel Gemini Lake Chromebook. I have no reproduction.

```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Null check operator used on a null value. Error thrown Instance of 'ErrorDescription'.
       at KeyEventManager._convertRawEventAndStore(KeyEventManager.java:902)
       at RawKeyboard.handleRawKeyEvent(RawKeyboard.java:695)
       at KeyEventManager.handleRawKeyMessage(KeyEventManager.java:818)
       at BasicMessageChannel.setMessageHandler.<fn>(setMessageHandler.java:77)
       at BasicMessageChannel.setMessageHandler.<fn>(setMessageHandler.java:76)
       at _DefaultBinaryMessenger.setMessageHandler.<fn>(setMessageHandler.java:377)
       at _DefaultBinaryMessenger.setMessageHandler.<fn>(setMessageHandler.java:374)
```

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 2.10.1, on macOS 12.1 21C52 darwin-arm, locale en-US)
    • Flutter version 2.10.1 at /Users/james/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (2 weeks ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/james/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 98.0.4758.109

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

**Comment by dkwingsmt** [comment]
https://github.com/flutter/flutter/pull/99200 might be a fix.

**Comment by darshankawar** [comment]
Labeling it based on the error report and potential fix.
