### ISSUE TITLE
Scrollable.dart Exception => Failed assertion: line 662 pos 12: '_hold == null': is not true

### ISSUE THREAD

**Issue by MohammadDesouky** [flutter/flutter#99210]
I created a notification listener widget which contains a page view as the child, I was trying to scroll via drag this I canceled this dragging by releasing my finger and then tapping again on the list. I got this crash and the list now isn't scrollable!

```
======== Exception caught by gesture ===============================================================
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 662 pos 12: '_hold == null': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      ScrollableState._handleDragCancel (package:flutter/src/widgets/scrollable.dart:662:12)
#3      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
#4      DragGestureRecognizer._checkCancel (package:flutter/src/gestures/monodrag.dart:491:7)
#5      DragGestureRecognizer.didStopTrackingLastPointer (package:flutter/src/gestures/monodrag.dart:389:9)
#6      OneSequenceGestureRecognizer.stopTrackingPointer (package:flutter/src/gestures/recognizer.dart:392:9)
#7      DragGestureRecognizer._giveUpPointer (package:flutter/src/gestures/monodrag.dart:402:5)
#8      DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:321:7)
#9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:94:12)
#10     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:139:9)
#11     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:539:8)
#12     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:137:18)
#13     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:123:7)
#14     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:439:19)
#15     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:419:22)
#16     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:322:11)
#17     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
#18     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
#19     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#20     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#24     _invoke1 (dart:ui/hooks.dart:170:10)
#25     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:331:7)
#26     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
(elided 5 frames from class _AssertionError and dart:async)
Handler: "onCancel"
Recognizer: HorizontalDragGestureRecognizer#733c8
  start behavior: start
====================================================================================================
```

**Comment by danagbemava-nc** [comment]
Hi @MohammadDesouky, thanks for filing the issue. 

Please provide a complete minimal reproducible code sample as well the output of flutter doctor -v. 

Thank you

**Comment by MohammadDesouky** [comment]
Hello!

Ok.

**Comment by MohammadDesouky** [comment]
full app
```
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() {
  runApp(const App());
}

class App extends StatelessWidget {
  const App({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return _Test();
  }
}

class _Test extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _State();
}

class _State extends State<_Test> {
  @override
  Widget build(BuildContext context) {
    final controller = PageController(initialPage: 1);
    return MaterialApp(
        home: Container(
            color: Colors.white,
            child: Scaffold(
              appBar: AppBar(
                title: const Text('_drag == null'),
              ),
              body: Center(child: NotificationListener<UserScrollNotification>(
                onNotification: (notification) {
                  if (notification.direction == ScrollDirection.idle) {
                    setState(() {
                      controller.jumpToPage(1);
                    });
                  }
                  return false;
                },
                child: Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: PageView(
                      controller: controller,
                      scrollDirection: Axis.horizontal,
                      children: const [
                        Text("Row0",textAlign: TextAlign.center,),
                        Text("Row1",textAlign: TextAlign.center,),
                        Text("Row2",textAlign: TextAlign.center,),
                      ]),
                ),
              ),
              ),
            )));
  }
}

```
flutter doctor -v result :


```
flutter doctor -v
[✓] Flutter (Channel stable, 2.10.1, on macOS 12.2.1 21D62 darwin-x64, locale en-EG)
    • Flutter version 2.10.1 at /Users/mohammaddesouky/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (3 weeks ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc2)
    • Android SDK at /Users/mohammaddesouky/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0-rc2
    • Java binary at: .../Android/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] Android Studio (version 2021.1)
    • Android Studio at .../Android/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] IntelliJ IDEA Community Edition (version 2021.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (2 available)
    • iPhone 11 Pro (mobile) • 9B8D7FC0-869B-489A-8999-5E390705996B • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 98.0.4758.109

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
Drag and move, then before reaching the next/previous page quickly release your finger and tap to cancel the scroll
you will get the exception and the PageView won't scroll again.
Recorded video might help, how to reproduce the issue:

https://user-images.githubusercontent.com/5509571/155981305-714b0016-ddcb-4bff-8fe3-a62b820a5bd9.mp4

**Comment by danagbemava-nc** [comment]
Hi @MohammadDesouky, there's a similar issue reported in https://github.com/flutter/flutter/issues/14452. 

Kindly follow up there for more information. 

Closing from here as duplicate. 

Thank you
