### ISSUE TITLE
How to replace the root route in Flutter Web

### ISSUE THREAD

**Issue by cdprete** [flutter/flutter#99220]
Hi.
I'm using the version 3.2.4 of the AutoRoute library and Flutter 2.10.2 and I've the necessity to replace the root route with another one which is not an initial route.
The scenario is the following:
- a user gets the login page (root route)
- he/she logs in and he/she gets into the application (new route X)
- he/she can press the back button of the browser to go back at the login view an, if wanted, he/she can then press the forward button to go back to the view pointed by the route X completely ignoring the login.
I've tried with 
```
context.router.popUntilRoot();
context.router.replace(ContactsViewRoute());
```

but I can still go back.
Is there any way to prevent this?
I suppose the issue is in Flutter itself since AutoRoute simply calls the functions provided by Flutter (but, I could be wrong, of course).

**Comment by darshankawar** [comment]
@cdprete 
I suggest you to follow-up in the dedicated third party plugin you are using to get a solution. If not, StackOverflow is another platform where you can ask this question.
I'll close it for now as this is more of a general question. If you disagree or think this is a genuine bug in routing, please provide a complete minimal reproducible code sample without 3rd party plugin that shows the issue and I'll reopen it.

**Comment by cdprete** [comment]
Although the view doesn't render, there is the exact same issue with the Skeleton application.
As said, the "sample_item" route is not rendered, but still the buttons of the browser allow to go back and fort.
The only change I did is to replace line 30 in `sample_item_list_view.dart` with `Navigator.pushNamedAndRemoveUntil(context, SettingsView.routeName, (route) => false);`.

Moreover, I get tons of errors in the console of the type 
```
Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/navigation/history.dart:328:14
_userProvidedRouteName != null
is not true
    at Object.throw_ [as throw] (http://localhost:54344/dart_sdk.js:5067:11)
    at Object.assertFailed (http://localhost:54344/dart_sdk.js:4992:15)
    at _engine.SingleEntryBrowserHistory.new.onPopState (http://localhost:54344/dart_sdk.js:170504:59)
```

**Comment by darshankawar** [comment]
@cdprete 
Please provide your `flutter doctor -v` and a complete minimal reproducible code sample without 3rd party plugins and complete error log.

**Comment by cdprete** [comment]
Hi @darshankawar 
Here the requested output: 
```
flutter doctor -v
[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.19044.1526], locale it-CH)
    • Flutter version 2.10.3 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (4 days ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Cosimo Damiano Prete\AppData\Local\Android\sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: C:\Program Files\jdk-17\bin\java
    • Java version OpenJDK Runtime Environment (build 17+35-2724)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31911.196
    • Windows 10 SDK version 10.0.22000.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    X FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1426:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1861:10)
      #15     runZonedGuarded (dart:async/zone.dart:1849:12)
      #16     runZoned (dart:async/zone.dart:1780:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:205:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:309:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[√] VS Code (version 1.63.2)
    • VS Code at C:\Users\Cosimo Damiano Prete\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.29.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1526]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 98.0.4758.102
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 99.0.1150.30

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```
The demo is here https://github.com/cdprete/github_flutter_issue_99220
Sorry for the delay :)

**Comment by darshankawar** [comment]
@cdprete 
What are the exact steps to replicate the behavior you are reporting ? Can you also provide actual vs expected results ?

**Comment by cdprete** [comment]
@darshankawar 
The steps are described in the README of the demo project.

Actual result:
- you can press the next and then back arrows of the browser

Expected result:
- the arrows should be disabled since there should be no history
