### ISSUE TITLE
Flutter web renderer (not CanvasKit): Nested Y Axis rotation causes a child widget to disappear

### ISSUE THREAD

**Issue by doradsoft** [flutter/flutter#99233]
While nesting two `Transform` widgets, a child widget (I.E. a picture) is disappearing in some cases. 

It happens with `Animation` and `AnimatedBuilder` as well.

Conditions for reproducing:
* Wide screen resolution only.
* Flutter Web with HTML web renderer only (Not Android nor Flutter Web with `CanvasKit`)
* Flutter 2.10.2

Minimal reproduce:

1. Create new folder `flutter_web_bug`
2. Open terminal inside that folder and execute `flutter create .`
3. Replace `./lib/main.dart` contents with the following code
4. Open terminal and execute `flutter run -d chrome --web-renderer html`

       import 'dart:async';
       import 'dart:math';
       
       import 'package:flutter/material.dart';
       
       void main() {
         runApp(const MyApp());
       }
       
       class MyApp extends StatelessWidget {
         const MyApp({Key? key}) : super(key: key);
       
         @override
         Widget build(BuildContext context) {
           return const MaterialApp(
             title: 'Flutter web bug',
             home: MyHomePage(title: 'Flutter web bug'),
           );
         }
       }
       
       class MyHomePage extends StatefulWidget {
         const MyHomePage({Key? key, required this.title}) : super(key: key);
       
         final String title;
       
         @override
         State<MyHomePage> createState() => _MyHomePageState();
       }
       
       class _MyHomePageState extends State<MyHomePage> {
         double angle = 0.0;
         @override
         void initState() {
           super.initState();
           Timer.periodic(const Duration(milliseconds: 20), (timer) {
             setState(() {
               angle += 0.01;
             });
           });
         }
       
         @override
         Widget build(BuildContext context) {
           return Scaffold(
               appBar: AppBar(
                 title: Text(widget.title),
               ),
               body: Center(
                 child: Transform(
                     transform: Matrix4.identity()
                       ..setEntry(3, 2, 0.001)
                       ..rotateY(pi * angle),
                     alignment: Alignment.center,
                     child: Align(
                         alignment: Alignment.center,
                         child: Container(
                             color: const Color(0xffaaffff),
                             child: Transform(
                                 alignment: Alignment.center,
                                 transform: Matrix4.identity()..rotateY(pi),
                                 child: Image.network('https://docs.flutter.dev/assets/images/dash/dash-fainting.gif'))))),
               ));
         }
       }
  

Demonstration:

[![HTML web renderer bug][1]][1]

I tried [SO](https://stackoverflow.com/questions/71280250/flutter-web-renderer-not-canvaskit-nested-y-axis-rotation-causes-a-child-widg) first, but as there wasn't a magic solution there, it now seems more like a bug.

  [1]: https://i.stack.imgur.com/uUl4y.gif

**Comment by danagbemava-nc** [comment]
Issue is reproducible on `stable` and `master` using the code sample provided by author. 

This occurs with only the `html` renderer and it seems to occur when the app is in full-screen mode. 

<details>
<summary>videos</summary>

| HTML | Html (Full Windowed) | CanvasKit (Full Windowed) | 
| -- | -- | -- | 
| <video src="https://user-images.githubusercontent.com/88313112/155970357-7e5a08ef-23be-43bd-a41f-ebad35e2868f.mov" /> | <video src="https://user-images.githubusercontent.com/88313112/155970610-8fc02a30-382e-4a14-91f5-729eaa306a41.mov" /> | <video src="https://user-images.githubusercontent.com/88313112/155970796-83aecb5a-6780-4150-8659-b6c832882950.mov" /> |


</details>

<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.10.2, on macOS 12.2 21D49 darwin-arm, locale en-GB)
    • Flutter version 2.10.2 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (9 days ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1426:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1861:10)
      #15     runZonedGuarded (dart:async/zone.dart:1849:12)
      #16     runZoned (dart:async/zone.dart:1780:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:205:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:309:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (3 available)
    • M2007J20CG (mobile) • 5dd3be00 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)     • macos    • darwin-arm64   • macOS 12.2 21D49 darwin-arm
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 98.0.4758.109

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel master, 2.11.0-0.0.pre.697, on macOS 12.2 21D49 darwin-arm, locale en-GB)
    • Flutter version 2.11.0-0.0.pre.697 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fc2a0847fb (67 minutes ago), 2022-02-28 01:01:17 -0500
    • Engine revision 05d1b5a66b
    • Dart version 2.17.0 (build 2.17.0-150.0.dev)
    • DevTools version 2.11.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 213.5744.122

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (3 available)
    • M2007J20CG (mobile) • 5dd3be00 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)     • macos    • darwin-arm64   • macOS 12.2 21D49 darwin-arm
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 98.0.4758.109

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by doradsoft** [comment]
@danagbemava-nc - thanks for polishing my issue.
I just wanted to add that in certain cases it does reproduce in `CanvasKit`. I'll try to make a minimal reproduce.

**Comment by doradsoft** [comment]
Issue still persists.
