### ISSUE TITLE
Flutter Web App Error [_binaryMessenger != null || ServicesBinding.instance != null] [White Screen Error] 

### ISSUE THREAD

**Issue by sahq-azhar** [flutter/flutter#99268]
Getting this issue with Flutter 
Tried Flutter 2.10/2.10.1 and 2.11.0-0.1.pre beta versions still getting the same error

```console
Error: Assertion failed: file:///C:/Flutter%20Folder/beta/flutter/packages/flutter/lib/src/services/platform_channel.dart:397:7
_binaryMessenger != null || ServicesBinding.instance != null
"Cannot set the method call handler before the binary messenger has been initialized. This happens when you call setMethodCallHandler() before the WidgetsFlutterBinding has been initialized. You can fix this by either calling WidgetsFlutterBinding.ensureInitialized() before this or by passing a custom BinaryMessenger instance to MethodChannel()."
    at Object.throw_ [as throw] (http://localhost:58637/dart_sdk.js:5388:11)
    at Object.assertFailed (http://localhost:58637/dart_sdk.js:5310:15)
    at platform_channel.MethodChannel.new.setMethodCallHandler (http://localhost:58637/packages/flutter/src/services/restoration.dart.lib.js:1639:98)
    at Function.registerWith (http://localhost:58637/packages/flutter_dtmf/dtmf_web.dart.lib.js:52:15)
    at Object.registerPlugins (http://localhost:58637/packages/call_crm/generated_plugin_registrant.dart.lib.js:37:25)
    at main (http://localhost:58637/web_entrypoint.dart.lib.js:36:35)
    at main.next (<anonymous>)
    at runBody (http://localhost:58637/dart_sdk.js:42986:34)
    at Object._async [as async] (http://localhost:58637/dart_sdk.js:43017:7)
    at main$ (http://localhost:58637/web_entrypoint.dart.lib.js:35:18)
    at http://localhost:58637/main_module.bootstrap.js:19:10
    at Array.forEach (<anonymous>)
    at window.$dartRunMain (http://localhost:58637/main_module.bootstrap.js:18:32)
    at <anonymous>:1:8
    at Object.runMain (http://localhost:58637/dwds/src/injected/client.js:8707:21)
    at http://localhost:58637/dwds/src/injected/client.js:23873:19
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:58637/dwds/src/injected/client.js:3487:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:58637/dwds/src/injected/client.js:11518:12)
    at Object._asyncStartSync (http://localhost:58637/dwds/src/injected/client.js:3451:20)
    at main__closure3.$call$body$main__closure (http://localhost:58637/dwds/src/injected/client.js:23885:16)
    at main__closure3.call$1 (http://localhost:58637/dwds/src/injected/client.js:23812:19)
    at StaticClosure._rootRunUnary (http://localhost:58637/dwds/src/injected/client.js:3849:18)
    at _CustomZone.runUnary$2$2 (http://localhost:58637/dwds/src/injected/client.js:12877:39)
    at _CustomZone.runUnaryGuarded$1$2 (http://localhost:58637/dwds/src/injected/client.js:12813:14)
    at _ForwardingStreamSubscription._sendData$1 (http://localhost:58637/dwds/src/injected/client.js:12403:19)
    at _ForwardingStreamSubscription._add$1 (http://localhost:58637/dwds/src/injected/client.js:12349:15)
    at _ForwardingStreamSubscription._add$1 (http://localhost:58637/dwds/src/injected/client.js:12682:12)
    at _MapStream._handleData$2 (http://localhost:58637/dwds/src/injected/client.js:12743:12)
    at _ForwardingStreamSubscription._handleData$1 (http://localhost:58637/dwds/src/injected/client.js:12708:20)
    at tear_off.<anonymous> (http://localhost:58637/dwds/src/injected/client.js:1392:45)
    at StaticClosure._rootRunUnary (http://localhost:58637/dwds/src/injected/client.js:3849:18)
    at _CustomZone.runUnary$2$2 (http://localhost:58637/dwds/src/injected/client.js:12877:39)
    at _CustomZone.runUnaryGuarded$1$2 (http://localhost:58637/dwds/src/injected/client.js:12813:14)
    at _ControllerSubscription._sendData$1 (http://localhost:58637/dwds/src/injected/client.js:12403:19)
    at _ControllerSubscription._add$1 (http://localhost:58637/dwds/src/injected/client.js:12349:15)
    at _SyncStreamController._sendData$1 (http://localhost:58637/dwds/src/injected/client.js:12197:32)
    at _SyncStreamController.add$1 (http://localhost:58637/dwds/src/injected/client.js:12078:15)
    at tear_off.<anonymous> (http://localhost:58637/dwds/src/injected/client.js:1450:48)
    at StaticClosure._rootRunUnary (http://localhost:58637/dwds/src/injected/client.js:3849:18)
    at _CustomZone.runUnary$2$2 (http://localhost:58637/dwds/src/injected/client.js:12877:39)
    at _CustomZone.runUnaryGuarded$1$2 (http://localhost:58637/dwds/src/injected/client.js:12813:14)
    at _ControllerSubscription._sendData$1 (http://localhost:58637/dwds/src/injected/client.js:12403:19)
    at _ControllerSubscription._add$1 (http://localhost:58637/dwds/src/injected/client.js:12349:15)
    at _SyncStreamController._sendData$1 (http://localhost:58637/dwds/src/injected/client.js:12197:32)
    at _SyncStreamController.add$1 (http://localhost:58637/dwds/src/injected/client.js:12078:15)
    at _GuaranteeSink.add$1 (http://localhost:58637/dwds/src/injected/client.js:23352:25)
    at HtmlWebSocketChannel_closure1.call$1 (http://localhost:58637/dwds/src/injected/client.js:23637:149)
    at _EventStreamSubscription_closure.call$1 (http://localhost:58637/dwds/src/injected/client.js:17865:26)
    at StaticClosure._rootRunUnary (http://localhost:58637/dwds/src/injected/client.js:3855:16)
    at _CustomZone.runUnary$2$2 (http://localhost:58637/dwds/src/injected/client.js:12877:39)
    at _CustomZone.runUnaryGuarded$1$2 (http://localhost:58637/dwds/src/injected/client.js:12813:14)
    at _CustomZone_bindUnaryCallbackGuarded_closure.call$1 (http://localhost:58637/dwds/src/injected/client.js:13014:25)
    at invokeClosure (http://localhost:58637/dwds/src/injected/client.js:1281:26)
    at WebSocket.<anonymous> (http://localhost:58637/dwds/src/injected/client.js:1300:18)
```

**Comment by danagbemava-nc** [comment]
Hi @sahq-azhar, please provide a complete minimal reproducible code sample so that we may verify this. 

Thank you

**Comment by pvsvamsi** [comment]
@danagbemava-nc This error is coming if we launching flutter on chrome (flutter run -d chrome). We are not getting this error in case of Android launch. 

We are calling WidgetsFlutterBinding.ensureInitialized() under main
```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
```

**Comment by sahq-azhar** [comment]
I resolved this by checking the dependencies on pubspec.yaml file.

In my case flutter_dtmf was creating this issue.

**Comment by danagbemava-nc** [comment]
Hi @pvsvamsi, kindly file a new issue and provide all the relevant information to reproduce the issue. 

@sahq-azhar given that you have resolved this issue on your own, I'm going to close this issue as solved. 

Thank you
