### ISSUE TITLE
Failed assertion: 'elapsedInSeconds >= 0.0': is not  true

### ISSUE THREAD

**Issue by vixez** [flutter/flutter#99274]
## Steps to Reproduce

Since upgrading to Flutter 2.10 (not sure if it was on 2.10.0, but this is definitely on 2.10.2), I often see this error.
This mostly happens when I'm popping an item from the navigation stack, but has also happened with other random `AnimationController`s for example when using a `Tween` with `CurvedAnimation`.

**Expected results:** 
The page should navigate back or the animation should play.

**Actual results:** 
The app freezes and becomes unresponsive, hot reload still works.

Probably same as https://github.com/flutter/flutter/issues/99232

<details>
<summary>Stacktrace</summary>

```dart
_AssertionError._doThrowNew (errors_patch.dart:51)
_AssertionError._throwNew (errors_patch.dart:40)
AnimationController._tick (animation_controller.dart:822)
Ticker._tick (ticker.dart:238)
SchedulerBinding._invokeFrameCallback (binding.dart:1144)
SchedulerBinding.handleBeginFrame.<anonymous closure> (binding.dart:1057)
_LinkedHashMapMixin.forEach (compact_hash.dart:539)
SchedulerBinding.handleBeginFrame (binding.dart:1055)
SchedulerBinding._handleBeginFrame (binding.dart:974)
_rootRunUnary (zone.dart:1442)
_CustomZone.runUnary (zone.dart:1335)
_CustomZone.runUnaryGuarded (zone.dart:1244)
_invoke1 (hooks.dart:170)
PlatformDispatcher._beginFrame (platform_dispatcher.dart:286)
_beginFrame (hooks.dart:104)
```

</details>

<details>
  <summary>Logs</summary>

```
[+3594 ms] I/ViewRootImpl@839334e[MainActivity](20474): ViewPostIme pointer 0
[        ] I/MSHandlerLifeCycle(20474): isMultiSplitHandlerRequested: windowingMode=1 isFullscreen=true isPopOver=false isHidden=false skipActivityType=false isHandlerType=true this: DecorView@fda19a9[MainActivity]
[        ] I/MSHandlerLifeCycle(20474): isMultiSplitHandlerRequested: windowingMode=1 isFullscreen=true isPopOver=false isHidden=false skipActivityType=false isHandlerType=true this: DecorView@fda19a9[MainActivity]
[  +11 ms] I/MSHandlerLifeCycle(20474): isMultiSplitHandlerRequested: windowingMode=1 isFullscreen=true isPopOver=false isHidden=false skipActivityType=false isHandlerType=true this: DecorView@fda19a9[MainActivity]
[   +8 ms] I/MSHandlerLifeCycle(20474): isMultiSplitHandlerRequested: windowingMode=1 isFullscreen=true isPopOver=false isHidden=false skipActivityType=false isHandlerType=true this: DecorView@fda19a9[MainActivity]
[  +10 ms] I/MSHandlerLifeCycle(20474): isMultiSplitHandlerRequested: windowingMode=1 isFullscreen=true isPopOver=false isHidden=false skipActivityType=false isHandlerType=true this: DecorView@fda19a9[MainActivity]
[   +5 ms] I/MSHandlerLifeCycle(20474): isMultiSplitHandlerRequested: windowingMode=1 isFullscreen=true isPopOver=false isHidden=false skipActivityType=false isHandlerType=true this: DecorView@fda19a9[MainActivity]
[   +8 ms] I/MSHandlerLifeCycle(20474): isMultiSplitHandlerRequested: windowingMode=1 isFullscreen=true isPopOver=false isHidden=false skipActivityType=false isHandlerType=true this: DecorView@fda19a9[MainActivity]
[   +9 ms] I/ViewRootImpl@839334e[MainActivity](20474): ViewPostIme pointer 1
[        ] I/MSHandlerLifeCycle(20474): isMultiSplitHandlerRequested: windowingMode=1 isFullscreen=true isPopOver=false isHidden=false skipActivityType=false isHandlerType=true this: DecorView@fda19a9[MainActivity]
[   +4 ms] I/IMM_LC  (20474): hsifw() - flags=0, caller=android.view.inputmethod.InputMethodManager.hideSoftInputFromWindow:1846 android.view.inputmethod.InputMethodManager.hideSoftInputFromWindow:1815 io.flutter.plugin.editing.TextInputPlugin.hideTextInput:404 io.flutter.plugin.editing.TextInputPlugin.access$300:37 io.flutter.plugin.editing.TextInputPlugin$1.hide:111 
[        ] I/IMM_LC  (20474): hideSoftInputFromWindow - mService.hideSoftInput
[        ] I/flutter (20474): [2022-02-28 14:36:03 - INFO - navigation] Navigation going back to: incentives
[sentry] [info] Tracing is disabled and this 'startTransaction' returns a no-op.
[ +794 ms] I/ViewRootImpl@839334e[MainActivity](20474): ViewPostIme pointer 0
[        ] I/MSHandlerLifeCycle(20474): isMultiSplitHandlerRequested: windowingMode=1 isFullscreen=true isPopOver=false isHidden=false skipActivityType=false isHandlerType=true this: DecorView@fda19a9[MainActivity]
[        ] I/MSHandlerLifeCycle(20474): isMultiSplitHandlerRequested: windowingMode=1 isFullscreen=true isPopOver=false isHidden=false skipActivityType=false isHandlerType=true this: DecorView@fda19a9[MainActivity]
[   +8 ms] I/MSHandlerLifeCycle(20474): isMultiSplitHandlerRequested: windowingMode=1 isFullscreen=true isPopOver=false isHidden=false skipActivityType=false isHandlerType=true this: DecorView@fda19a9[MainActivity]
[  +25 ms] I/MSHandlerLifeCycle(20474): isMultiSplitHandlerRequested: windowingMode=1 isFullscreen=true isPopOver=false isHidden=false skipActivityType=false isHandlerType=true this: DecorView@fda19a9[MainActivity]
[   +7 ms] I/MSHandlerLifeCycle(20474): isMultiSplitHandlerRequested: windowingMode=1 isFullscreen=true isPopOver=false isHidden=false skipActivityType=false isHandlerType=true this: DecorView@fda19a9[MainActivity]
[   +7 ms] I/ViewRootImpl@839334e[MainActivity](20474): ViewPostIme pointer 1
[        ] I/MSHandlerLifeCycle(20474): isMultiSplitHandlerRequested: windowingMode=1 isFullscreen=true isPopOver=false isHidden=false skipActivityType=false isHandlerType=true this: DecorView@fda19a9[MainActivity]
[ +362 ms] I/ViewRootImpl@839334e[MainActivity](20474): ViewPostIme pointer 0
[        ] I/MSHandlerLifeCycle(20474): isMultiSplitHandlerRequested: windowingMode=1 isFullscreen=true isPopOver=false isHidden=false skipActivityType=false isHandlerType=true this: DecorView@fda19a9[MainActivity]
[  +41 ms] I/MSHandlerLifeCycle(20474): isMultiSplitHandlerRequested: windowingMode=1 isFullscreen=true isPopOver=false isHidden=false skipActivityType=false isHandlerType=true this: DecorView@fda19a9[MainActivity]
[  +22 ms] I/MSHandlerLifeCycle(20474): isMultiSplitHandlerRequested: windowingMode=1 isFullscreen=true isPopOver=false isHidden=false skipActivityType=false isHandlerType=true this: DecorView@fda19a9[MainActivity]
[   +6 ms] I/ViewRootImpl@839334e[MainActivity](20474): ViewPostIme pointer 1
[        ] I/MSHandlerLifeCycle(20474): isMultiSplitHandlerRequested: windowingMode=1 isFullscreen=true isPopOver=false isHidden=false skipActivityType=false isHandlerType=true this: DecorView@fda19a9[MainActivity]
```

```
[+13861 ms] I/flutter ( 9752): [2022-02-28 16:02:29 - FATAL - default] App crash
[        ] I/flutter ( 9752): 'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 822 pos 12: 'elapsedInSeconds >= 0.0': is not true.
[        ] I/flutter ( 9752): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
[        ] I/flutter ( 9752): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
[        ] I/flutter ( 9752): #2      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:822:12)
[        ] I/flutter ( 9752): #3      Ticker._tick (package:flutter/src/scheduler/ticker.dart:238:12)
[        ] I/flutter ( 9752): #4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
[        ] I/flutter ( 9752): #5      SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1057:11)
[        ] I/flutter ( 9752): #6      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:539:8)
[        ] I/flutter ( 9752): #7      SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1055:17)
[        ] I/flutter ( 9752): #8      SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:974:5)
[        ] I/flutter ( 9752): #9      _rootRunUnary (dart:
[+2469 ms] D/Sentry  ( 9752): onEvent fired for EnvelopeFileObserver with event type 8 on path: /data/user/0/app.getdriven.driver.staging.debug/cache/sentry/outbox for file 69e5afa4-19a6-4ea6-8d6a-8a783bc8c41a.
[        ] D/Sentry  ( 9752): Processing Envelope with 1 item(s)
[  +37 ms] I/flutter ( 9752): ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
[        ] I/flutter ( 9752): The following assertion was thrown during a scheduler callback:
[        ] I/flutter ( 9752): 'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 822 pos 12:
[        ] I/flutter ( 9752): 'elapsedInSeconds >= 0.0': is not true.
[        ] I/flutter ( 9752): 
[        ] I/flutter ( 9752): Either the assertion indicates an error in the framework itself, or we should provide substantially
[        ] I/flutter ( 9752): more information in this error message to help you determine and fix the underlying cause.
[        ] I/flutter ( 9752): In either case, please report this assertion by filing a bug on GitHub:
[        ] I/flutter ( 9752):   https://github.com/flutter/flutter/issues/new?template=2_bug.md
[        ] I/flutter ( 9752): 
[        ] I/flutter ( 9752): When the exception was thrown, this was the stack:
[        ] I/flutter ( 9752): #2      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:822:12)
[        ] I/flutter ( 9752): #3      Ticker._tick (package:flutter/src/scheduler/ticker.dart:238:12)
[        ] I/flutter ( 9752): #4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
[        ] I/flutter ( 9752): #5      SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1057:11)
[        ] I/flutter ( 9752): #6      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:539:8)
[        ] I/flutter ( 9752): #7      SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1055:17)
[        ] I/flutter ( 9752): #8      SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:974:5)
[        ] I/flutter ( 9752): #12     _invoke1 (dart:ui/hooks.dart:170:10)
[        ] I/flutter ( 9752): #13     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:286:5)
[        ] I/flutter ( 9752): #14     _beginFrame (dart:ui/hooks.dart:104:31)
[        ] I/flutter ( 9752): (elided 5 frames from class _AssertionError and dart:async)
[        ] I/flutter ( 9752): 
[        ] I/flutter ( 9752): 
[        ] I/flutter ( 9752): This exception was thrown in the context of a scheduler callback. When the scheduler callback was _registered_ (as opposed to when the exception was thrown), this was the stack:
[        ] I/flutter ( 9752): #2      SchedulerBinding.scheduleFrameCallback (package:flutter/src/scheduler/binding.dart:523:49)
[        ] I/flutter ( 9752): #3      Ticker.scheduleTick (package:flutter/src/scheduler/ticker.dart:253:47)
[        ] I/flutter ( 9752): #4      Ticker.start (package:flutter/src/scheduler/ticker.dart:162:7)
[        ] I/flutter ( 9752): #5      AnimationController._startSimulation (package:flutter/src/animation/animation_controller.dart:745:42)
[        ] I/flutter ( 9752): #6      AnimationController._animateToInternal (package:flutter/src/animation/animation_controller.dart:612:12)
[        ] I/flutter ( 9752): #7      AnimationController.reverse (package:flutter/src/animation/animation_controller.dart:494:12)
[        ] I/flutter ( 9752): #8      TransitionRoute.didPop (package:flutter/src/widgets/routes.dart:261:18)
[        ] I/flutter ( 9752): #9      LocalHistoryRoute.didPop (package:flutter/src/widgets/routes.dart:669:18)
[        ] I/flutter ( 9752): #10     _RouteEntry.handlePop (package:flutter/src/widgets/navigator.dart:2896:16)
[        ] I/flutter ( 9752): #11     NavigatorState._flushHistoryUpdates (package:flutter/src/widgets/navigator.dart:3860:22)
[        ] I/flutter ( 9752): #12     NavigatorState.pop (package:flutter/src/widgets/navigator.dart:4902:7)
[        ] I/flutter ( 9752): #13     NavigationService.goBack (package:gd_ui/src/services/service_navigation.dart:106:36)
[        ] I/flutter ( 9752): #14     AppRoutes.goBack (package:gd_ui/src/routes/app_routes.dart:350:24)
[        ] I/flutter ( 9752): #15     RegularSnappingHeaderBackArrow.build.<anonymous closure> (package:gd_ui/src/ui/headers/regular_snapping_header.dart:666:30)
[        ] I/flutter ( 9752): #16     ClearInkWell.build.<anonymous closure> (package:gd_ui/src/ui/other/clear_inkwell.dart:37:18)
[        ] I/flutter ( 9752): #17     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
[        ] I/flutter ( 9752): #18     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:608:11)
[        ] I/flutter ( 9752): #19     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
[        ] I/flutter ( 9752): #20     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:267:7)
[        ] I/flutter ( 9752): #21     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
[        ] I/flutter ( 9752): #22     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:443:20)
[        ] I/flutter ( 9752): #23     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:419:22)
[        ] I/flutter ( 9752): #24     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:322:11)
[        ] I/flutter ( 9752): #25     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
[        ] I/flutter ( 9752): #26     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
[        ] I/flutter ( 9752): #27     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
[        ] I/flutter ( 9752): #28     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
[        ] I/flutter ( 9752): #32     _invoke1 (dart:ui/hooks.dart:170:10)
[        ] I/flutter ( 9752): #33     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:331:7)
[        ] I/flutter ( 9752): #34     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
[        ] I/flutter ( 9752): (elided 5 frames from class _FrameCallbackEntry and dart:async)
```

```
No issues found! (ran in 14.7s)
```

```
[✓] Flutter (Channel stable, 2.10.2, on macOS 12.0.1 21A559 darwin-x64, locale
    en-GB)
    • Flutter version 2.10.2 at /Users/glennruysschaert/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (10 days ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/glennruysschaert/Library/Android/sdk
    • Platform android-31, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.64.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (3 available)
    • SM S908B (mobile) • R5CT1359BMA • android-arm64  • Android 12 (API 31)
    • macOS (desktop)   • macos       • darwin-x64     • macOS 12.0.1 21A559
      darwin-x64
    • Chrome (web)      • chrome      • web-javascript • Google Chrome
      98.0.4758.109

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @vixez 

Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can use to verify this? Also, what version of flutter were you on prior to 2.10?

Thank you

**Comment by vixez** [comment]
@danagbemava-nc 
This is part of a very large Flutter project, and has no specific code to trigger it. It just sometimes happens.
The navigation issue is about 1 of 20 times, I guess.

Going back looks like this
```
  /// Go back a screen, or go back until a certain route.
  void goBack({
    String? goBackUntil,
    Object? data,
  }) async {
    GlobalKey<NavigatorState> navigator = _getBackNavigator();

    if (!navigator.currentState!.canPop()) {
      return;
    }

    if (goBackUntil != null) {
      return navigator.currentState!.popUntil((route) {
        return route.settings.name == goBackUntil;
      });
    }

    return navigator.currentState!.pop(data);
  }
```

**Comment by vixez** [comment]
@danagbemava-nc 

I got it during verbose logging now:

```
[+13861 ms] I/flutter ( 9752): [2022-02-28 16:02:29 - FATAL - default] App crash
[        ] I/flutter ( 9752): 'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 822 pos 12: 'elapsedInSeconds >= 0.0': is not true.
[        ] I/flutter ( 9752): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
[        ] I/flutter ( 9752): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
[        ] I/flutter ( 9752): #2      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:822:12)
[        ] I/flutter ( 9752): #3      Ticker._tick (package:flutter/src/scheduler/ticker.dart:238:12)
[        ] I/flutter ( 9752): #4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
[        ] I/flutter ( 9752): #5      SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1057:11)
[        ] I/flutter ( 9752): #6      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:539:8)
[        ] I/flutter ( 9752): #7      SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1055:17)
[        ] I/flutter ( 9752): #8      SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:974:5)
[        ] I/flutter ( 9752): #9      _rootRunUnary (dart:
[+2469 ms] D/Sentry  ( 9752): onEvent fired for EnvelopeFileObserver with event type 8 on path: /data/user/0/app.getdriven.driver.staging.debug/cache/sentry/outbox for file 69e5afa4-19a6-4ea6-8d6a-8a783bc8c41a.
[        ] D/Sentry  ( 9752): Processing Envelope with 1 item(s)
[  +37 ms] I/flutter ( 9752): ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
[        ] I/flutter ( 9752): The following assertion was thrown during a scheduler callback:
[        ] I/flutter ( 9752): 'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 822 pos 12:
[        ] I/flutter ( 9752): 'elapsedInSeconds >= 0.0': is not true.
[        ] I/flutter ( 9752): 
[        ] I/flutter ( 9752): Either the assertion indicates an error in the framework itself, or we should provide substantially
[        ] I/flutter ( 9752): more information in this error message to help you determine and fix the underlying cause.
[        ] I/flutter ( 9752): In either case, please report this assertion by filing a bug on GitHub:
[        ] I/flutter ( 9752):   https://github.com/flutter/flutter/issues/new?template=2_bug.md
[        ] I/flutter ( 9752): 
[        ] I/flutter ( 9752): When the exception was thrown, this was the stack:
[        ] I/flutter ( 9752): #2      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:822:12)
[        ] I/flutter ( 9752): #3      Ticker._tick (package:flutter/src/scheduler/ticker.dart:238:12)
[        ] I/flutter ( 9752): #4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
[        ] I/flutter ( 9752): #5      SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1057:11)
[        ] I/flutter ( 9752): #6      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:539:8)
[        ] I/flutter ( 9752): #7      SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1055:17)
[        ] I/flutter ( 9752): #8      SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:974:5)
[        ] I/flutter ( 9752): #12     _invoke1 (dart:ui/hooks.dart:170:10)
[        ] I/flutter ( 9752): #13     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:286:5)
[        ] I/flutter ( 9752): #14     _beginFrame (dart:ui/hooks.dart:104:31)
[        ] I/flutter ( 9752): (elided 5 frames from class _AssertionError and dart:async)
[        ] I/flutter ( 9752): 
[        ] I/flutter ( 9752): 
[        ] I/flutter ( 9752): This exception was thrown in the context of a scheduler callback. When the scheduler callback was _registered_ (as opposed to when the exception was thrown), this was the stack:
[        ] I/flutter ( 9752): #2      SchedulerBinding.scheduleFrameCallback (package:flutter/src/scheduler/binding.dart:523:49)
[        ] I/flutter ( 9752): #3      Ticker.scheduleTick (package:flutter/src/scheduler/ticker.dart:253:47)
[        ] I/flutter ( 9752): #4      Ticker.start (package:flutter/src/scheduler/ticker.dart:162:7)
[        ] I/flutter ( 9752): #5      AnimationController._startSimulation (package:flutter/src/animation/animation_controller.dart:745:42)
[        ] I/flutter ( 9752): #6      AnimationController._animateToInternal (package:flutter/src/animation/animation_controller.dart:612:12)
[        ] I/flutter ( 9752): #7      AnimationController.reverse (package:flutter/src/animation/animation_controller.dart:494:12)
[        ] I/flutter ( 9752): #8      TransitionRoute.didPop (package:flutter/src/widgets/routes.dart:261:18)
[        ] I/flutter ( 9752): #9      LocalHistoryRoute.didPop (package:flutter/src/widgets/routes.dart:669:18)
[        ] I/flutter ( 9752): #10     _RouteEntry.handlePop (package:flutter/src/widgets/navigator.dart:2896:16)
[        ] I/flutter ( 9752): #11     NavigatorState._flushHistoryUpdates (package:flutter/src/widgets/navigator.dart:3860:22)
[        ] I/flutter ( 9752): #12     NavigatorState.pop (package:flutter/src/widgets/navigator.dart:4902:7)
[        ] I/flutter ( 9752): #13     NavigationService.goBack (package:gd_ui/src/services/service_navigation.dart:106:36)
[        ] I/flutter ( 9752): #14     AppRoutes.goBack (package:gd_ui/src/routes/app_routes.dart:350:24)
[        ] I/flutter ( 9752): #15     RegularSnappingHeaderBackArrow.build.<anonymous closure> (package:gd_ui/src/ui/headers/regular_snapping_header.dart:666:30)
[        ] I/flutter ( 9752): #16     ClearInkWell.build.<anonymous closure> (package:gd_ui/src/ui/other/clear_inkwell.dart:37:18)
[        ] I/flutter ( 9752): #17     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
[        ] I/flutter ( 9752): #18     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:608:11)
[        ] I/flutter ( 9752): #19     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
[        ] I/flutter ( 9752): #20     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:267:7)
[        ] I/flutter ( 9752): #21     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
[        ] I/flutter ( 9752): #22     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:443:20)
[        ] I/flutter ( 9752): #23     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:419:22)
[        ] I/flutter ( 9752): #24     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:322:11)
[        ] I/flutter ( 9752): #25     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
[        ] I/flutter ( 9752): #26     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
[        ] I/flutter ( 9752): #27     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
[        ] I/flutter ( 9752): #28     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
[        ] I/flutter ( 9752): #32     _invoke1 (dart:ui/hooks.dart:170:10)
[        ] I/flutter ( 9752): #33     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:331:7)
[        ] I/flutter ( 9752): #34     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
[        ] I/flutter ( 9752): (elided 5 frames from class _FrameCallbackEntry and dart:async)
```

**Comment by danagbemava-nc** [comment]
Hi @vixez, we will need a minimal reproducible sample for this issue to be actionable.

**Comment by vixez** [comment]
@danagbemava-nc 
I tried to create a sample with the progress_indicators package, as it seems to happen there, but can't get any consistent results.
It looks like this is the same issue https://github.com/flutter/flutter/issues/43501 here

Especially
> Sometimes, but this happens much less frequently, flutter freezes entirely too, i.e. becomes entirely unresponsive. I can see our native Android code continues to run, but can not click on anything in the app UI, even back button doesn't work.

Seems like upgrading to Flutter 2.10 caused this to happen at seemingly random moments for me now.

**Comment by danagbemava-nc** [comment]
Kindly update this thread when you are able to find a reproducible sample so we can take this forward. 

Thank you

**Comment by huyu456** [comment]
I have the same problem
`
When the exception was thrown, this was the stack: 
#2      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:822:12)
#3      Ticker._tick (package:flutter/src/scheduler/ticker.dart:238:12)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
#5      SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1058:11)
#6      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:539:8)
#7      SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1056:17)
#8      SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:975:5)
#12     _invoke1 (dart:ui/hooks.dart:169:10)
#13     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:248:5)
#14     _beginFrame (dart:ui/hooks.dart:103:31)
(elided 5 frames from class _AssertionError and dart:async)

This exception was thrown in the context of a scheduler callback. When the scheduler callback was _registered_ (as opposed to when the exception was thrown), this was the stack: 
#2      SchedulerBinding.scheduleFrameCallback (package:flutter/src/scheduler/binding.dart:521:49)
#3      Ticker.scheduleTick (package:flutter/src/scheduler/ticker.dart:253:47)
#4      Ticker.start (package:flutter/src/scheduler/ticker.dart:162:7)
#5      AnimationController._startSimulation (package:flutter/src/animation/animation_controller.dart:745:42)
#6      AnimationController._animateToInternal (package:flutter/src/animation/animation_controller.dart:612:12)
#7      AnimationController.animateTo (package:flutter/src/animation/animation_controller.dart:531:12)
#8      new DrivenScrollActivity (package:flutter/src/widgets/scroll_activity.dart:633:9)
#9      ScrollPositionWithSingleContext.animateTo (package:flutter/src/widgets/scroll_position_with_single_context.dart:181:43)
#10     PageController.animateToPage (package:flutter/src/widgets/page_view.dart:201:21)
#11     _TransformerPageViewState.onChangeNotifier (package:flutter_swiper_null_safety/src/transformer_page_view/transformer_page_view.dart:590:12)
#12     ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:308:24)
#13     IndexController.next (package:flutter_swiper_null_safety/src/transformer_page_view/index_controller.dart:30:5)
#14     _SwiperTimerMixin._onTimer (package:flutter_swiper_null_safety/src/swiper.dart:369:18)
(elided 5 frames from class _FrameCallbackEntry, class _RawReceivePortImpl, and class _Timer)
====================================================================================================
`

**Comment by vixez** [comment]
Since it is an assert, I hope it won't freeze release apps.

**Comment by danagbemava-nc** [comment]
> Since it is an assert, I hope it won't freeze release apps.

@vixez, it likely will not do that

> I have the same problem

@huyu456 can you provide a complete minimal reproducible code sample that we can use to verify this?

**Comment by huyu456** [comment]
> > Since it is an assert, I hope it won't freeze release apps.
> 
> @vixez, it likely will not do that
> 
> > I have the same problem
> 
> @huyu456 can you provide a complete minimal reproducible code sample that we can use to verify this?

environment: Flutter 2.8.1+ Dart 2.15.1+card_swiper: ^2.0.1
code: 
```
import 'package:card_swiper/card_swiper.dart';
import 'package:flutter/material.dart';

const APPBAR_SCROLL_OFFSET = 100;

class HomePage extends StatefulWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  List images = [
    "http://i.miaosu.bid/data/f_94153397.png",
    "http://i.miaosu.bid/data/f_94153397.png",
    "http://i.miaosu.bid/data/f_94153397.png",
  ];
  double appBarAlpha = 0.0; // AppBar opacity

  _onScroll(offset) {
    double alpha = offset / APPBAR_SCROLL_OFFSET;
    if (alpha < 0) {
      alpha = 0;
    } else if (alpha > 1) {
      alpha = 1;
    }
    setState(() {
      appBarAlpha = alpha;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Stack(
        children: [
          MediaQuery.removePadding(
              context: context,
              removeTop: true,
              child: NotificationListener(
                onNotification: (scrollNotification) {
                  if (scrollNotification is ScrollUpdateNotification &&
                      scrollNotification.depth == 0) {
                    _onScroll(scrollNotification.metrics.pixels);
                    return true;
                  }
                  return false;
                },
                child: ListView(
                  children: [
                    SizedBox(
                      height: 160.0,
                      child: Swiper(
                        itemBuilder: (BuildContext context, int index) {
                          return Image.network(
                            images[index],
                            fit: BoxFit.cover,
                          );
                        },
                        autoplay: true,
                        itemCount: images.length,
                        scrollDirection: Axis.horizontal,
                        pagination:
                        const SwiperPagination(alignment: Alignment.bottomCenter),
                        control: const SwiperControl(),
                      ),
                    ),
                    Container(
                      child: const Text('content1'),
                      height: 500.0,
                    ),
                    Container(
                      child: const Text('content2'),
                      height: 500.0,
                    )
                  ],
                ),
              )),
          Opacity(
            opacity: appBarAlpha,
            child: Container(
              height: 80,
              decoration: const BoxDecoration(color: Colors.white),
              child: const Center(
                child: Padding(
                  padding: EdgeInsets.only(top: 20),
                  child: Text(
                    'home',
                    style: TextStyle(fontSize: 24.0),
                  ),
                ),
              ),
            ),
          )
        ],
      ),
    );
  }
}
```

**Comment by danagbemava-nc** [comment]
Hi @huyu456, can you try to provide a sample without the card_swiper package? We wouldn't know for sure if it is a bug with flutter with that package present

**Comment by huyu456** [comment]
@danagbemava-nc Sorry, this error cannot be reproduced if you do not use this plug-in.
