### ISSUE TITLE
`flutter doctor` crashes on macos

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#9929]
## Steps to Reproduce

`flutter upgrade`
`flutter doctor`

## flutter doctor

```
encountered exception: NoSuchMethodError: The method 'contains' was called on null.
Receiver: null
Tried calling: contains("/")

#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      getExecutablePath (package:process/src/interface/common.dart:30)
#3      LocalProcessManager.canRun (package:process/src/interface/local_process_manager.dart:99)
#4      AndroidStudio._init (package:flutter_tools/src/android/android_studio.dart:276)
#5      AndroidStudio.AndroidStudio (package:flutter_tools/src/android/android_studio.dart:54)
#6      AndroidStudio.AndroidStudio.fromMacOSBundle (package:flutter_tools/src/android/android_studio.dart:74)
#7      AndroidStudio._allMacOS.<anonymous closure> (package:flutter_tools/src/android/android_studio.dart:184)
#8      MappedListIterable.elementAt (dart:_internal/iterable.dart:413)
#9      ListIterator.moveNext (dart:_internal/iterable.dart:342)
#10     WhereIterator.moveNext (dart:_internal/iterable.dart:437)
#11     List.List.from (dart:core-patch/array_patch.dart:46)
#12     Iterable.toList (dart:core/iterable.dart:347)
#13     AndroidStudio._allMacOS (package:flutter_tools/src/android/android_studio.dart:186)
#14     AndroidStudio.allInstalled (package:flutter_tools/src/android/android_studio.dart:143)
#15     AndroidStudio.latestValid (package:flutter_tools/src/android/android_studio.dart:133)
#16     AppContext.putIfAbsent (package:flutter_tools/src/base/context.dart:46)
#17     androidStudio (package:flutter_tools/src/android/android_studio.dart:17)
#18     javaPath (package:flutter_tools/src/android/android_studio.dart:49)
#19     AndroidWorkflow._findJavaBinary (package:flutter_tools/src/android/android_workflow.dart:37)
#20     AndroidWorkflow.validate (package:flutter_tools/src/android/android_workflow.dart:148)
<asynchronous suspension>
#21     Doctor.diagnose (package:flutter_tools/src/doctor.dart:116)
<asynchronous suspension>
#22     _doctorText.<anonymous closure> (package:flutter_tools/executable.dart:287)
#23     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#24     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#25     _rootRun (dart:async/zone.dart:1120)
#26     _CustomZone.run (dart:async/zone.dart:1001)
#27     runZoned (dart:async/zone.dart:1465)
#28     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#29     _doctorText (package:flutter_tools/executable.dart:287)
<asynchronous suspension>
#30     _createLocalCrashReport (package:flutter_tools/executable.dart:262)
<asynchronous suspension>
#31     _handleToolError (package:flutter_tools/executable.dart:217)
<asynchronous suspension>
#32     run.<anonymous closure> (package:flutter_tools/executable.dart:144)
<asynchronous suspension>
#33     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#34     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#35     _rootRun (dart:async/zone.dart:1120)
#36     _CustomZone.run (dart:async/zone.dart:1001)
#37     runZoned (dart:async/zone.dart:1465)
#38     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#39     run (package:flutter_tools/executable.dart:113)
<asynchronous suspension>
#40     main (package:flutter_tools/executable.dart:66)
<asynchronous suspension>
#41     main (file:///Users/mit/dev/github/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#42     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#43     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by crasm** [comment]
Getting this on linux as well for `flutter run`. 

- - - - - - - - 

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run

## exception

NoSuchMethodError: NoSuchMethodError: The method 'contains' was called on null.
Receiver: null
Tried calling: contains("/")

```
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      getExecutablePath (package:process/src/interface/common.dart:30)
#3      LocalProcessManager.canRun (package:process/src/interface/local_process_manager.dart:99)
#4      AndroidStudio._init (package:flutter_tools/src/android/android_studio.dart:276)
#5      AndroidStudio.AndroidStudio (package:flutter_tools/src/android/android_studio.dart:54)
#6      AndroidStudio.AndroidStudio.fromHomeDot (package:flutter_tools/src/android/android_studio.dart:96)
#7      AndroidStudio._allLinuxOrWindows (package:flutter_tools/src/android/android_studio.dart:207)
#8      AndroidStudio.allInstalled (package:flutter_tools/src/android/android_studio.dart:143)
#9      AndroidStudioValidator.allValidators (package:flutter_tools/src/android/android_studio_validator.dart:23)
#10     Doctor.validators (package:flutter_tools/src/doctor.dart:55)
#11     Doctor.workflows (package:flutter_tools/src/doctor.dart:68)
#12     Doctor.canLaunchAnything (package:flutter_tools/src/doctor.dart:143)
#13     FlutterCommand.findAllTargetDevices (package:flutter_tools/src/runner/flutter_command.dart:223)
<asynchronous suspension>
#14     RunCommand.verifyThenRunCommand (package:flutter_tools/src/commands/run.dart:205)
<asynchronous suspension>
#15     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:156)
<asynchronous suspension>
#16     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:262)
<asynchronous suspension>
#18     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#19     Future.Future.sync (dart:async/future.dart:208)
#20     CommandRunner.run (package:args/command_runner.dart:109)
#21     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:157)
#22     run.<anonymous closure> (package:flutter_tools/executable.dart:140)
<asynchronous suspension>
#23     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#24     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#25     _rootRun (dart:async/zone.dart:1120)
#26     _CustomZone.run (dart:async/zone.dart:1001)
#27     runZoned (dart:async/zone.dart:1465)
#28     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#29     run (package:flutter_tools/executable.dart:113)
<asynchronous suspension>
#30     main (package:flutter_tools/executable.dart:66)
<asynchronous suspension>
#31     main (file:///home/crasm/code/clone/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#32     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

## flutter doctor

```
encountered exception: NoSuchMethodError: The method 'contains' was called on null.
Receiver: null
Tried calling: contains("/")

#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      getExecutablePath (package:process/src/interface/common.dart:30)
#3      LocalProcessManager.canRun (package:process/src/interface/local_process_manager.dart:99)
#4      AndroidStudio._init (package:flutter_tools/src/android/android_studio.dart:276)
#5      AndroidStudio.AndroidStudio (package:flutter_tools/src/android/android_studio.dart:54)
#6      AndroidStudio.AndroidStudio.fromHomeDot (package:flutter_tools/src/android/android_studio.dart:96)
#7      AndroidStudio._allLinuxOrWindows (package:flutter_tools/src/android/android_studio.dart:207)
#8      AndroidStudio.allInstalled (package:flutter_tools/src/android/android_studio.dart:143)
#9      AndroidStudio.latestValid (package:flutter_tools/src/android/android_studio.dart:133)
#10     AppContext.putIfAbsent (package:flutter_tools/src/base/context.dart:46)
#11     androidStudio (package:flutter_tools/src/android/android_studio.dart:17)
#12     javaPath (package:flutter_tools/src/android/android_studio.dart:49)
#13     AndroidWorkflow._findJavaBinary (package:flutter_tools/src/android/android_workflow.dart:37)
#14     AndroidWorkflow.validate (package:flutter_tools/src/android/android_workflow.dart:148)
<asynchronous suspension>
#15     Doctor.diagnose (package:flutter_tools/src/doctor.dart:116)
<asynchronous suspension>
#16     _doctorText.<anonymous closure> (package:flutter_tools/executable.dart:287)
#17     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#18     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#19     _rootRun (dart:async/zone.dart:1120)
#20     _CustomZone.run (dart:async/zone.dart:1001)
#21     runZoned (dart:async/zone.dart:1465)
#22     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#23     _doctorText (package:flutter_tools/executable.dart:287)
<asynchronous suspension>
#24     _createLocalCrashReport (package:flutter_tools/executable.dart:262)
<asynchronous suspension>
#25     _handleToolError (package:flutter_tools/executable.dart:217)
<asynchronous suspension>
#26     run.<anonymous closure> (package:flutter_tools/executable.dart:144)
<asynchronous suspension>
#27     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#28     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#29     _rootRun (dart:async/zone.dart:1120)
#30     _CustomZone.run (dart:async/zone.dart:1001)
#31     runZoned (dart:async/zone.dart:1465)
#32     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#33     run (package:flutter_tools/executable.dart:113)
<asynchronous suspension>
#34     main (package:flutter_tools/executable.dart:66)
<asynchronous suspension>
#35     main (file:///home/crasm/code/clone/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#36     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by crasm** [comment]
I checked out 6337a0553cdd318c35b84b00f124cd6c5d0697d2, removed the update code in [`packages/flutter_tools/lib/src/commands/upgrade.dart`](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/upgrade.dart#L30-L50), ran `git clean -fdx; flutter upgrade` and the error still pops up.
