### ISSUE TITLE
ReOrderableListView with an html child containing a link <a tag>

### ISSUE THREAD

**Issue by jaredgreener** [flutter/flutter#99291]
Please see the following example where an html widget containing an a tag ([<a href="">Link</a>](url)) produces an error while inside a ReorderableListView. As soon as you remove the a tag from the html, it functions properly.

**Expected results:** 

No Error...

**Actual results:**

<details>
<summary> console log </summary>

```

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
'package:flutter/src/semantics/semantics.dart': Failed assertion: line 3023 pos 16: 'node.parent == null || !node.parent!.isPartOfNodeMerging || node.isMergedIntoParent': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      SemanticsOwner.sendSemanticsUpdate (package:flutter/src/semantics/semantics.dart:3023:16)
#3      PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1098:24)
#4      RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:502:21)
#5      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#6      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#7      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#8      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
#9      SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:862:7)
(elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
====================================================================================================


```
</details>

<details>
<summary>Code sample</summary>

```
import 'package:flutter/material.dart';
import 'package:flutter_html/flutter_html.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key}) : super(key: key);
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> with SingleTickerProviderStateMixin, WidgetsBindingObserver{

  final ScrollController reorderScrollController = ScrollController();

  Widget renderWidget(int index){

    return Container(
        key: ValueKey(index),
        padding: const EdgeInsets.fromLTRB(8,5,8,5),
        child: Html(
          data: "Today's lesson will be streamed via the following link:<div><br></div><div><a href='https://www.apple.com'>Streaming Link</a><b><u></u></b><br></div>",
          shrinkWrap: true,
          onLinkTap: (url, context, attributes, element) {
          },
        )
    );
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      color: Colors.white,
      child: ReorderableListView(
        scrollController: reorderScrollController,
        onReorder: (int oldIndex, int newIndex){

        },
        children: [
          renderWidget(1),
        ],
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
[  +27 ms] DevFS: Created new filesystem on the device
(file:///Users/grogreener/Library/Developer/CoreSimulator/Devices/C4F33958-956E-4650-85DC-35C2B77B952C/data/Containers/Data/Application/CB33AF94-C863-45CD-8489-62A0A6107594/tmp/testing3FhENU/testing/)
[   +3 ms] Updating assets
[ +169 ms] Syncing files to device iPhone 12 Pro...
[   +2 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[        ] Processing bundle.
[   +3 ms] <- recompile package:testing/main.dart 7add0849-b037-4fd3-8aa0-868cf9d11bed
[        ] <- 7add0849-b037-4fd3-8aa0-868cf9d11bed
[   +3 ms] Bundle processing done.
[  +22 ms] 
           ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
           The following assertion was thrown during a scheduler callback:
           'package:flutter/src/semantics/semantics.dart': Failed assertion: line 3023 pos 16: 'node.parent ==
           null || !node.parent!.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
           
           Either the assertion indicates an error in the framework itself, or we should provide substantially
           more information in this error message to help you determine and fix the underlying cause.
           In either case, please report this assertion by filing a bug on GitHub:
             https://github.com/flutter/flutter/issues/new?template=2_bug.md
           
           When the exception was thrown, this was the stack:
           #2      SemanticsOwner.sendSemanticsUpdate (package:flutter/src/semantics/semantics.dart:3023:16)
           #3      PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1098:24)
           #4      RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:502:21)
           #5      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
           #6      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
           #7      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
           #8      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
           #9      SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:862:7)
           (elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
           ════════════════════════════════════════════════════════════════════════════════════════════════════
[   +2 ms] 
           Another exception was thrown: Bad state: Future already completed
[  +37 ms] Updating files.
[        ] DevFS: Sync finished
[   +1 ms] Syncing files to device iPhone 12 Pro... (completed in 73ms)
[        ] Synced 0.0MB.
[   +1 ms] <- accept
[   +6 ms] Connected to _flutterView/0x128016220.
[   +6 ms] Flutter run key commands.
[   +2 ms] r Hot reload. 🔥🔥🔥
[   +1 ms] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] 💪 Running with sound null safety 💪
[        ] An Observatory debugger and profiler on iPhone 12 Pro is available at: http://127.0.0.1:51725/i8lQ7wcPKPg=/
[  +69 ms] The Flutter DevTools debugger and profiler on iPhone 12 Pro is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:51725/i8lQ7wcPKPg=/



grogreener@GreenerM1 testing % flutter doctor -v
[✓] Flutter (Channel stable, 2.10.2, on macOS 12.0 21A344 darwin-arm, locale en-US)
    • Flutter version 2.10.2 at /Applications/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (10 days ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at /Users/grogreener/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[☠] IntelliJ IDEA Ultimate Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1426:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1861:10)
      #15     runZonedGuarded (dart:async/zone.dart:1849:12)
      #16     runZoned (dart:async/zone.dart:1780:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:205:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:309:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] Connected device (2 available)
    • iPhone 12 Pro (mobile) • C4F33958-956E-4650-85DC-35C2B77B952C • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 98.0.4758.109

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.


```

</details>

**Comment by darshankawar** [comment]
@jaredgreener 
Thanks for the report. Although I do see the same exception log, but you are using `flutter_html` which is 3rd party plugin. Is it possible to recreate this without using that plugin or maybe using [flutter_markdown](https://pub.dev/packages/flutter_markdown) which is first party Flutter plugin and confirm if the behavior persists with it ?
