### ISSUE TITLE
AnimatedScale hit test miss

### ISSUE THREAD

**Issue by cedvdb** [flutter/flutter#99302]
Having an animated scale with an inkwell makes hit test miss

Repro repository:

https://github.com/cedvdb/flutter_repros/tree/animated_scale_hit_test   <= branch animated_scale_hit_test

Then run:

`flutter test`

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const ScaledCard(
      key: ValueKey('tap-me'),
    );
  }
}

class ScaledCard extends StatelessWidget {
  const ScaledCard({
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return AnimatedScale(
      scale: 1.05,
      duration: const Duration(seconds: 1),
      child: Card(
        child: InkWell(
          onTap: () {},
          child: const Text('tap me'),
        ),
      ),
    );
  }
}
```

test

```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:flutter_repros/main.dart';

void main() {
  testWidgets('Counter increments smoke test', (WidgetTester tester) async {
    // Build our app and trigger a frame.
    await tester.pumpWidget(const MyApp());

    await tester.pumpAndSettle();
    await tester.tap(find.byKey(const ValueKey('tap-me')));
    await tester.pumpAndSettle();
  });
}

```

**Comment by darshankawar** [comment]
With code sample provided above and passing `warnIfMissed: true` to `await tester.tap(find.byKey(const ValueKey('tap-me'))`, I see below console log:

<details>
<summary> test console log </summary>

```

Warning: A call to tap() with finder "exactly one widget with key [<'tap-me'>] (ignoring offstage widgets): ScaledCard-[<'tap-me'>]" derived an Offset (Offset(400.0, 300.0)) that would not hit test on the specified widget.
Maybe the widget is actually off-screen, or another widget is obscuring it, or the widget cannot receive pointer events.
The finder corresponds to this RenderBox: RenderTransform#3c3f4
The hit test result at that offset is: HitTestResult(HitTestEntry#92664(TextSpan(debugLabel: (englishLike bodyMedium 2014).merge(blackMountainView bodyMedium), inherit: false, color: Color(0xdd000000), family: Roboto, size: 14.0, weight: 400, baseline: alphabetic, decoration: TextDecoration.none, "tap me")), RenderParagraph#5d129@Offset(396.0, 296.0), RenderPointerListener#8576d@Offset(396.0, 296.0), RenderSemanticsAnnotations#7fb55@Offset(396.0, 296.0), RenderMouseRegion#fda2b@Offset(396.0, 296.0), RenderSemanticsAnnotations#73456@Offset(396.0, 296.0), RenderSemanticsAnnotations#5c783@Offset(396.0, 296.0), _RenderInkFeatures#a4b31@Offset(396.0, 296.0), RenderCustomPaint#2f34d@Offset(396.0, 296.0), RenderPhysicalShape#b0697@Offset(396.0, 296.0), RenderPadding#5e775@Offset(400.0, 300.0), RenderSemanticsAnnotations#c4eb1@Offset(400.0, 300.0), RenderSemanticsAnnotations#164fb@Offset(400.0, 300.0), RenderRepaintBoundary#637b0@Offset(400.0, 300.0), RenderIgnorePointer#844a3@Offset(400.0, 300.0), RenderAnimatedOpacity#7e95e@Offset(400.0, 300.0), RenderRepaintBoundary#3b555@Offset(400.0, 300.0), _RenderFocusTrap#4e46d@Offset(400.0, 300.0), RenderSemanticsAnnotations#5fdbe@Offset(400.0, 300.0), RenderOffstage#fba6a@Offset(400.0, 300.0), RenderSemanticsAnnotations#fe366@Offset(400.0, 300.0), _RenderTheatre#3acb1@Offset(400.0, 300.0), RenderSemanticsAnnotations#207d6@Offset(400.0, 300.0), RenderAbsorbPointer#ecf36@Offset(400.0, 300.0), RenderPointerListener#c66db@Offset(400.0, 300.0), RenderCustomPaint#a08d4@Offset(400.0, 300.0), RenderSemanticsAnnotations#d3a75@Offset(400.0, 300.0), RenderSemanticsAnnotations#22d37@Offset(400.0, 300.0), RenderSemanticsAnnotations#a26bc@Offset(400.0, 300.0), RenderSemanticsAnnotations#aeccf@Offset(400.0, 300.0), HitTestEntry#71cb5(RenderView#1af07), HitTestEntry#9cf1e(<AutomatedTestWidgetsFlutterBinding>))
#0      WidgetController._getElementPoint (package:flutter_test/src/controller.dart:956:25)
#1      WidgetController.getCenter (package:flutter_test/src/controller.dart:839:12)
#2      WidgetController.tap (package:flutter_test/src/controller.dart:273:18)
#3      main.<anonymous closure> (file:///Users/dhs/Documents/NCFlutter/testdemo/test/widget_test.dart:19:18)
<asynchronous suspension>
#4      StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:125:47)
<asynchronous suspension>
To silence this warning, pass "warnIfMissed: false" to "tap()".
To make this warning fatal, set WidgetController.hitTestWarningShouldBeFatal to true.


```

</details>


The warning log doesn't occur if we pass `warnIfMissed: false` .

@cedvdb Is this a correct interpretation of the behavior you reported ? What's the expected result are you looking for after running the test ?

**Comment by cedvdb** [comment]
Yes it's not a miss despite the warning

**Comment by darshankawar** [comment]
Thanks for the update.

<details>
<summary> stable, master flutter doctor -v </summary>

```

[✓] Flutter (Channel stable, 2.10.2, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.10.2 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (2 days ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • iPhone 12 Pro Max (mobile)                     •
      A5473606-0213-4FD8-BA16-553433949729 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • iPad Pro (12.9-inch) (4th generation) (mobile) •
      AD9F1B85-B622-485E-97E8-E4AC866D5770 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)                                • macos
      • darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)                                   • chrome
      • web-javascript • Google Chrome 98.0.4758.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.


[✓] Flutter (Channel master, 2.11.0-0.0.pre.715, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 2.11.0-0.0.pre.715 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8b95cd6f35 (4 hours ago), 2022-02-28 16:31:12 -0800
    • Engine revision 615a60512c
    • Dart version 2.17.0 (build 2.17.0-150.0.dev)
    • DevTools version 2.11.1

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • iPhone 12 Pro Max (mobile)                     •
      A5473606-0213-4FD8-BA16-553433949729 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • iPad Pro (12.9-inch) (4th generation) (mobile) •
      AD9F1B85-B622-485E-97E8-E4AC866D5770 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)                                • macos
      • darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)                                   • chrome
      • web-javascript • Google Chrome 98.0.4758.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.


```

</details>
