### ISSUE TITLE
[Android] Flutter application showing over lock screen

### ISSUE THREAD

**Issue by fregmented** [flutter/flutter#99329]
## Steps to Reproduce

1. Run flutter application
2. Click power button to off the screen
3. Click power button to on the screen
4. Still accessible to application without credential

**Expected results:** 
Lock screen to request credential.
**Actual results:** 
Application without credential.

<details>
  <summary>Logs</summary>

```
```

```
Analyzing estimationzill...                                             

   info • The import of 'package:kakao_flutter_sdk/common.dart' is unnecessary because all of the used elements are also provided by the import of
          'package:kakao_flutter_sdk/user.dart' • lib/main.dart:17:8 • unnecessary_import
   info • Unused import: 'package:firebase_crashlytics/firebase_crashlytics.dart' • lib/main.dart:26:8 • unused_import
   info • 'backwardsCompatibility' is deprecated and shouldn't be used. This property is obsolete and is false by default. This feature was deprecated after v2.4.0-0.0.pre. •
          lib/main.dart:40:13 • deprecated_member_use
   info • Avoid `print` calls in production code • lib/main.dart:53:3 • avoid_print
   info • Use key in widget constructors • lib/main.dart:59:7 • use_key_in_widget_constructors
   info • The value of the field '_fcmToken' isn't used • lib/main.dart:68:15 • unused_field
   info • The value of the local variable 'android' isn't used • lib/main.dart:147:30 • unused_local_variable
   info • Prefer const with constant constructors • lib/main.dart:206:20 • prefer_const_constructors
   info • Use key in widget constructors • lib/main.dart:240:7 • use_key_in_widget_constructors
   info • SizedBox for whitespace • lib/main.dart:276:14 • sized_box_for_whitespace
   info • Use key in widget constructors • lib/main.dart:285:7 • use_key_in_widget_constructors
   info • SizedBox for whitespace • lib/main.dart:418:18 • sized_box_for_whitespace
   info • Unused import: 'package:flutter/material.dart' • test/widget_test.dart:8:8 • unused_import
   info • Unused import: 'package:estimationzill/main.dart' • test/widget_test.dart:11:8 • unused_import

14 issues found. (ran in 7.4s)
```

```
[✓] Flutter (Channel stable, 2.10.2, on Mac OS X 10.15.7 19H1715 darwin-x64, locale ko-KR)
    • Flutter version 2.10.2 at /Volumes/DATA2/sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (10일 전), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Volumes/DATA2/sdk/Android
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Users/hanwoollee/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7935034/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/hanwoollee/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7935034/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[☠] IntelliJ IDEA Ultimate Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1426:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1861:10)
      #15     runZonedGuarded (dart:async/zone.dart:1849:12)
      #16     runZoned (dart:async/zone.dart:1780:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:205:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:309:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] IntelliJ IDEA Ultimate Edition (version 2021.3)
    • IntelliJ at /Users/hanwoollee/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/213.5744.223/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.64.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • SM F926N (mobile) • adb-R3CRB0PTXTN-CedXeO._adb-tls-connect._tcp. • android-arm64  • Android 12 (API 31)
    • macOS (desktop)   • macos                                         • darwin-x64     • Mac OS X 10.15.7 19H1715 darwin-x64
    • Chrome (web)      • chrome                                        • web-javascript • Google Chrome 98.0.4758.109

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

```

</details>

<details>
  <summary>pubspec.yaml</summary>

```yaml
name: estimationzill
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.1.0+310

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  android_intent_plus: ^3.1.0
  firebase_core: ^1.12.0
  firebase_messaging: ^11.2.6
  flutter_local_notifications: ^9.2.0
  fluttertoast: ^8.0.8
  get: ^4.6.1
  http: ^0.13.4
  pigeon: ^1.0.17
  prefs: ^3.4.0+01
  url_launcher: ^6.0.18
  video_player: ^2.2.18
  webview_flutter: ^3.0.0
  permission_handler: ^9.0.1
  flutter_naver_login:
    git:
      url: https://github.com/syonkr/flutter_naver_login.git
  kakao_flutter_sdk: ^0.9.0
  sign_in_with_apple: ^3.3.0
  firebase_crashlytics: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
```

</details>

Video in link
https://drive.google.com/file/d/1KIVxzXFzqNfsvxtD7PuouOqybUjdmvd5/view?usp=sharing

**Comment by danagbemava-nc** [comment]
Hi @fregmented, does this issue occur with the default `flutter create` app? 
If it does not can you provide a complete minimal reproducible code sample that we may use to verify this?

**Comment by fregmented** [comment]
Hi @danagbemava-nc. I can't reproduce this issue using template application. 
I'm not sure reproduce it, I'll try to reproduce with non product code.

**Comment by danagbemava-nc** [comment]
Please update this thread when you're able to come up with a minimal sample. 

Thank you
