### ISSUE TITLE
Invalid argument(s): Expected a library reference to be valid but was \null`.`

### ISSUE THREAD

**Issue by gisborne** [flutter/flutter#99321]
This trying to compile a fairly simple Flutter project for MacOS, on my M1 Mac.

Seems like a compiler problem?

Stacktrace:
```
Unhandled exception:
Invalid argument(s): Expected a library reference to be valid but was \null`.`
#0 BinaryPrinter.writeLibraryReference (package:kernel/binary/ast_to_binary.dart:987:7)
#1 BinaryPrinter.writeLibraryDependency (package:kernel/binary/ast_to_binary.dart:1129:5)
#2 BinaryPrinter.writeLibraryDependencies (package:kernel/binary/ast_to_binary.dart:1111:7)
#3 BinaryPrinter.visitLibrary (package:kernel/binary/ast_to_binary.dart:1051:5)
#4 Library.accept (package:kernel/ast.dart:557:38)
#5 BinaryPrinter.writeLibraryNode (package:kernel/binary/ast_to_binary.dart:451:10)
#6 BinaryPrinter.writeLibraries (package:kernel/binary/ast_to_binary.dart:756:9)
#7 BinaryPrinter.writeComponentFile.<anonymous closure> (package:kernel/binary/ast_to_binary.dart:595:7)
#8 Timeline.timeSync (dart:developer/timeline.dart:163:22)
#9 BinaryPrinter.writeComponentFile (package:kernel/binary/ast_to_binary.dart:577:14)
#10 FrontendCompiler.writeDillFile (package:frontend_server/frontend_server.dart:705:13)
#11 FrontendCompiler.recompileDelta (package:frontend_server/frontend_server.dart:809:13)
<asynchronous suspension>
the Dart compiler exited unexpectedly.
the Dart compiler exited unexpectedly.
```

**Comment by darshankawar** [comment]
> the Dart compiler exited unexpectedly.

Could be a compiler issue as it exited abruptly. Can you provide `flutter doctor -v` along with a minimal code sample that shows this log ? Does it occur everytime you try to compile ?

**Comment by gisborne** [comment]
`flutter clean` fixed it. Can’t now reproduce. If I do, I’ll post the 1flutter doctor -v` output, also.

**Comment by darshankawar** [comment]
`flutter clean` might have suppressed the underlying cause of the issue, but anyways, since you can't replicate it now, I'll close for now. If you see the same error again, please post `flutter doctor -v` and steps that leads to this error.
