### ISSUE TITLE
Height of special characters like ♀,♂ is not consistent with font weights

### ISSUE THREAD

**Issue by eripe970** [flutter/flutter#99393]
I would like to use special characters like ♀ and ♂ in a text widget. It looks like they are cropped/cut off no matter if I changed the height in the text style, they are correctly displayed if I change the fontWeight to >= 600.  Is this a bug or is it by design? 

## Steps to Reproduce
1. Create a project and add the sign to the default text widget. 

**Expected results:** 

```
Text(
              'You have pushed the ♀ button this many times:',
              style: TextStyle(height: 3, fontWeight: FontWeight.w300),
            ),
```
<img width="432" alt="Skärmavbild 2022-03-02 kl  13 59 58" src="https://user-images.githubusercontent.com/1668861/156366641-ef9f2706-bc39-40b1-a893-46a53bd1102d.png">

```
Text(
              'You have pushed the ♀ button this many times:',
              style: TextStyle(height: 3, fontWeight: FontWeight.w600),
            ),
```
<img width="439" alt="Skärmavbild 2022-03-02 kl  14 02 01" src="https://user-images.githubusercontent.com/1668861/156366651-98b3dbee-afd6-4e92-a29f-b969e67b63e0.png">

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel stable, 2.10.2, on macOS 12.2.1 21D62 darwin-arm, locale sv-SE)
    • Flutter version 2.10.2 at /Users/erik/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (11 days ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/erik/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
```

</details>

**Comment by eripe970** [comment]
Thanks! This was from iOS. Tried on Android and there it seems to work good! (See attached screenshot from an app I'm building where I have the issue). 

![Screenshot_20220302-150705](https://user-images.githubusercontent.com/1668861/156377378-8c63f710-353b-4a1d-aa7a-b2267367d9a6.jpg)

**Comment by jason-simmons** [comment]
This appears to be originating in Skia's `SkScalerContext_Mac`.

I can get these characters to render as intended by patching `SkScalerContext_Mac::Offscreen::getCG` to set `point.y = 0` for an affected glyph ID before calling `CTFontDrawGlyphs`.

I'm not sure why the positioning needs adjustment for these characters though.  The glyphs are taken from the AppleColorEmoji font, and it looks like that font contains both bitmap and outline glyphs.  Possibly that is affecting the calculation?

Interestingly the same cropping is happening when Chrome on my MacBook renders these characters in the title of the issue on this page.

@bungeman

**Comment by danagbemava-nc** [comment]
Reproducible on `stable` and `master`.
It seems to only affect `iOS`.

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            // const Text(
            //   'You have pushed the ♀ button this many times:',
            //   style: TextStyle(height: 3, fontWeight: FontWeight.w300),
            // ),
            const Text(
              'You have pushed the ♀ button this many times:',
              style: TextStyle(height: 3, fontWeight: FontWeight.w600),
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

```
</details>


<details>
<summary>screenshots</summary>

### FontWeight.300

| macOS | chrome (canvaskit) | chrome(html) | ios | android | 
| -- | -- | -- | -- | -- |
| <img width="636" alt="Screenshot 2022-03-03 at 06 22 05" src="https://user-images.githubusercontent.com/88313112/156510152-ca73bbba-8487-40dd-aabe-4c8f80087a21.png"> | <img width="612" alt="Screenshot 2022-03-03 at 06 23 17" src="https://user-images.githubusercontent.com/88313112/156510174-54a0b97c-d11b-4cc6-92d9-cd33e9ae1fe6.png"> | <img width="612" alt="Screenshot 2022-03-03 at 06 24 03" src="https://user-images.githubusercontent.com/88313112/156510188-6758614a-1c92-4bf7-bee4-847f2bb98be8.png"> | ![Simulator Screen Shot - iPhone 13 - 2022-03-03 at 06 26 17](https://user-images.githubusercontent.com/88313112/156510202-c3b4cb2c-fb1f-4042-95ff-10a0ef88de5a.png) | ![Screenshot_1646289136](https://user-images.githubusercontent.com/88313112/156510215-afd60d79-851e-4a7f-828b-47d93e9fcc72.png) |

### FontWeight.600

| macOS | chrome (canvaskit) | chrome(html) | ios | android | 
| -- | -- | -- | -- | -- |
| <img width="636" alt="Screenshot 2022-03-03 at 07 25 31" src="https://user-images.githubusercontent.com/88313112/156518509-ca640ff9-ed9e-433f-aa6d-b5eab0f77780.png"> | <img width="612" alt="Screenshot 2022-03-03 at 07 29 37" src="https://user-images.githubusercontent.com/88313112/156518533-fd45d965-6fb1-4030-9015-7460dec18ee9.png"> | <img width="666" alt="Screenshot 2022-03-03 at 07 30 47" src="https://user-images.githubusercontent.com/88313112/156518558-d576b054-9400-40a4-9ed2-412fcf2093ca.png"> | ![Simulator Screen Shot - iPhone 13 - 2022-03-03 at 07 10 53](https://user-images.githubusercontent.com/88313112/156518610-f726b97c-648d-4124-a85e-e186c50d7061.png) | ![Screenshot_1646293030](https://user-images.githubusercontent.com/88313112/156518679-34db2a17-2861-4481-bbd6-4a27354e59cc.png) |

</details>

<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.2.1 21D62 darwin-arm, locale en-GB)
    • Flutter version 2.10.3 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (14 hours ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1426:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1861:10)
      #15     runZonedGuarded (dart:async/zone.dart:1849:12)
      #16     runZoned (dart:async/zone.dart:1780:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:205:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:309:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • 304CA91D-8D77-4AAE-A50F-ECFC57AFD011 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 12.2.1 21D62 darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 99.0.4844.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel master, 2.11.0-0.0.pre.751, on macOS 12.2.1 21D62 darwin-arm, locale en-GB)
    • Flutter version 2.11.0-0.0.pre.751 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 21797cbb03 (3 hours ago), 2022-03-02 23:16:22 -0500
    • Engine revision 121376d39a
    • Dart version 2.17.0 (build 2.17.0-164.0.dev)
    • DevTools version 2.11.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 213.5744.122

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • 304CA91D-8D77-4AAE-A50F-ECFC57AFD011 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 12.2.1 21D62 darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 99.0.4844.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by bungeman** [comment]
This is probably an issue in the underlying font (Apple Color Emoji) or just CoreText, depending on how you look at it. Skia will not draw a glyph outside its actual bounds. If Skia did allow a glyph to draw outside its bounds other parts of Skia would not work properly and there would be no way to properly handle damage rectangles (handle partial re-draw) or know when a glyph should actually be drawn (is it on the screen or not). On macOS and iOS CoreText is used as the back-end for drawing glyphs, and it appears the CoreText always reports a glyph's bounds based on the bounds of the outline in the `glyf` table, even if it will not draw using that outline (like drawing out of `sbix`, `COLR`, or `SVG ` tables). Note that this doesn't just affect Flutter, I'm currently looking at this issue in Chrome Canary 101.0.4919.0 on macOS 11.6.4 and the ♀ and ♂ as displayed in the original report also have this same issue. As for font weight 600 changing things, I think this has to do with fake bolding. When trying to fake bold Skia goes and looks for a glyph outline and then tries to embolden it. Note that this should have been recently fixed (color glyphs aren't drawn from a single outline) so on newer versions of Skia I expect that the 600 change will go away.

Note that other apps like Safari just let CoreText draw where ever it wants and so can end up with strange redraw and pop-in issues from fonts where the `glyf` outline has significantly different bounds from the color glyph representation. The real fix for this is for CoreText to properly report the bounds of a glyph.

In any event, I'll go take a look at the font itself and see if I can dig up the various bounds. It looks like in Apple Color Emoji either the paths or the bitmap for these glyphs were added without considering the effect that would have on the other (and in most apps this brokenness would actually initially look fine, but lead to issues later).
