### ISSUE TITLE
engine update with window-java dependency breaks custom build on android

### ISSUE THREAD

**Issue by dvc94ch** [flutter/flutter#99404]
since https://github.com/flutter/engine/pull/29585 my flutter build is broken. The issue seems to be that a dependency on `androidx.window:window-java` deprecated featrues [0] was introduced that are not available in the maven repository builds. Not sure what gradle does here, guessing building everything from source.

```
x build -p helloworld --platform android --arch arm64
package helloworld
root_dir /home/dvc/cloudpeer/cross/examples/flutter
target_dir /home/dvc/cloudpeer/cross/target
downloading flutter engine for android-arm64-debug
building classes.dex
[2022-03-02T15:04:31Z INFO  maven] downloading com.google.guava:listenablefuture:9999.0.0-empty-to-avoid-conflict-with-guava
[2022-03-02T15:04:31Z INFO  maven] artifact not found com.google.guava:listenablefuture:9999.0.0-empty-to-avoid-conflict-with-guava pom
[2022-03-02T15:04:31Z INFO  maven] selected org.jetbrains.kotlinx:kotlinx-coroutines-core 1.6.0-native-mt (latest 1.6.0-native-mt) (release 1.6.0-native-mt)
[2022-03-02T15:04:31Z INFO  maven] selected androidx.loader:loader 1.1.0 (latest 1.1.0) (release 1.1.0)
[2022-03-02T15:04:31Z INFO  maven] selected androidx.annotation:annotation 1.3.0 (latest 1.4.0-alpha02) (release 1.4.0-alpha02)
[2022-03-02T15:04:31Z INFO  maven] selected androidx.fragment:fragment 1.4.1 (latest 1.5.0-alpha03) (release 1.5.0-alpha03)
[2022-03-02T15:04:31Z INFO  maven] selected org.jetbrains.kotlinx:kotlinx-coroutines-android 1.6.0-native-mt (latest 1.6.0-native-mt) (release 1.6.0-native-mt)
[2022-03-02T15:04:31Z INFO  maven] selected androidx.lifecycle:lifecycle-common 2.4.1 (latest 2.5.0-alpha03) (release 2.5.0-alpha03)
[2022-03-02T15:04:31Z INFO  maven] selected androidx.core:core-ktx 1.7.0 (latest 1.9.0-alpha01) (release 1.9.0-alpha01)
[2022-03-02T15:04:31Z INFO  maven] selected androidx.tracing:tracing 1.0.0 (latest 1.1.0-beta01) (release 1.1.0-beta01)
[2022-03-02T15:04:31Z INFO  maven] selected androidx.lifecycle:lifecycle-livedata-core 2.4.1 (latest 2.5.0-alpha03) (release 2.5.0-alpha03)
[2022-03-02T15:04:31Z INFO  maven] selected org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm 1.6.0-native-mt (latest 1.6.0-native-mt) (release 1.6.0-native-mt)
[2022-03-02T15:04:31Z INFO  maven] selected org.jetbrains.kotlin:kotlin-stdlib-jdk8 1.6.10 (latest 1.6.20-RC) (release 1.6.20-RC)
[2022-03-02T15:04:31Z INFO  maven] selected androidx.customview:customview 1.1.0 (latest 1.2.0-alpha01) (release 1.2.0-alpha01)
[2022-03-02T15:04:31Z INFO  maven] selected androidx.versionedparcelable:versionedparcelable 1.1.1 (latest 1.1.1) (release 1.1.1)
[2022-03-02T15:04:31Z INFO  maven] selected org.jetbrains:annotations 23.0.0 (latest 23.0.0) (release 23.0.0)
[2022-03-02T15:04:31Z INFO  maven] downloading com.google.guava:listenablefuture:9999.0.0-empty-to-avoid-conflict-with-guava
[2022-03-02T15:04:32Z INFO  maven] artifact not found com.google.guava:listenablefuture:9999.0.0-empty-to-avoid-conflict-with-guava pom
[2022-03-02T15:04:32Z INFO  maven] downloading com.google.guava:listenablefuture:9999.0.0-empty-to-avoid-conflict-with-guava
[2022-03-02T15:04:32Z INFO  maven] artifact not found com.google.guava:listenablefuture:9999.0.0-empty-to-avoid-conflict-with-guava jar
[2022-03-02T15:04:32Z INFO  maven] selected androidx.savedstate:savedstate 1.1.0 (latest 1.2.0-alpha01) (release 1.2.0-alpha01)
[2022-03-02T15:04:32Z INFO  maven] selected androidx.lifecycle:lifecycle-common-java8 2.4.1 (latest 2.5.0-alpha03) (release 2.5.0-alpha03)
[2022-03-02T15:04:32Z INFO  maven] selected androidx.lifecycle:lifecycle-viewmodel 2.4.1 (latest 2.5.0-alpha03) (release 2.5.0-alpha03)
[2022-03-02T15:04:32Z INFO  maven] selected androidx.annotation:annotation-experimental 1.2.0 (latest 1.2.0) (release 1.2.0)
[2022-03-02T15:04:32Z INFO  maven] selected androidx.core:core 1.7.0 (latest 1.9.0-alpha01) (release 1.9.0-alpha01)
[2022-03-02T15:04:32Z INFO  maven] selected androidx.arch.core:core-common 2.1.0 (latest 2.1.0) (release 2.1.0)
[2022-03-02T15:04:32Z INFO  maven] selected androidx.collection:collection 1.2.0 (latest 1.2.0) (release 1.2.0)
[2022-03-02T15:04:32Z INFO  maven] selected androidx.window:window 1.0.0 (latest 1.0.0) (release 1.0.0)
[2022-03-02T15:04:32Z INFO  maven] selected androidx.viewpager:viewpager 1.0.0 (latest 1.1.0-alpha01) (release 1.1.0-alpha01)
[2022-03-02T15:04:32Z INFO  maven] selected org.jetbrains.kotlin:kotlin-stdlib-jdk7 1.6.10 (latest 1.6.20-RC) (release 1.6.20-RC)
[2022-03-02T15:04:33Z INFO  maven] selected io.flutter:flutter_embedding_debug 1.0.0-ab46186b246f5a36bd1f3f295d14a43abb1e2f38
[2022-03-02T15:04:33Z INFO  maven] selected androidx.arch.core:core-runtime 2.1.0 (latest 2.1.0) (release 2.1.0)
[2022-03-02T15:04:33Z INFO  maven] selected androidx.lifecycle:lifecycle-runtime 2.4.1 (latest 2.5.0-alpha03) (release 2.5.0-alpha03)
[2022-03-02T15:04:33Z INFO  maven] selected androidx.window:window-java 1.0.0 (latest 1.0.0) (release 1.0.0)
[2022-03-02T15:04:33Z INFO  maven] selected org.jetbrains.kotlin:kotlin-stdlib 1.6.10 (latest 1.6.20-RC) (release 1.6.20-RC)
[2022-03-02T15:04:33Z INFO  maven] selected org.jetbrains.kotlin:kotlin-stdlib-common 1.6.10 (latest 1.6.20-RC) (release 1.6.20-RC)
[2022-03-02T15:04:33Z INFO  maven] selected androidx.concurrent:concurrent-futures 1.1.0 (latest 1.1.0) (release 1.1.0)
[2022-03-02T15:04:33Z INFO  maven] selected androidx.activity:activity 1.4.0 (latest 1.5.0-alpha03) (release 1.5.0-alpha03)
[2022-03-02T15:04:33Z INFO  maven] selected androidx.lifecycle:lifecycle-viewmodel-savedstate 2.4.1 (latest 2.5.0-alpha03) (release 2.5.0-alpha03)
Warning in /home/dvc/cloudpeer/cross/target/x/maven/androidx.window-window-1.0.0.aar:classes.jar:androidx/window/layout/SidecarCompat$DistinctSidecarElementCallback.class:
Type `androidx.window.sidecar.SidecarInterface$SidecarCallback` was not found, it is required for default or static interface methods desugaring of `androidx.window.layout.SidecarCompat$DistinctSidecarElementCallback`
Error: Missing class androidx.window.extensions.WindowExtensions (referenced from: androidx.window.extensions.layout.WindowLayoutComponent androidx.window.layout.SafeWindowLayoutComponentProvider$windowLayoutComponent$2.invoke())
Missing class androidx.window.extensions.WindowExtensionsProvider (referenced from: androidx.window.extensions.layout.WindowLayoutComponent androidx.window.layout.SafeWindowLayoutComponentProvider$windowLayoutComponent$2.invoke())
Missing class androidx.window.extensions.layout.DisplayFeature (referenced from: androidx.window.layout.WindowLayoutInfo androidx.window.layout.ExtensionsWindowLayoutInfoAdapter.translate$window_release(android.app.Activity, androidx.window.extensions.layout.WindowLayoutInfo))
Missing class androidx.window.extensions.layout.FoldingFeature (referenced from: androidx.window.layout.FoldingFeature androidx.window.layout.ExtensionsWindowLayoutInfoAdapter.translate$window_release(android.app.Activity, androidx.window.extensions.layout.FoldingFeature) and 1 other context)
Missing class androidx.window.extensions.layout.WindowLayoutComponent (referenced from: androidx.window.extensions.layout.WindowLayoutComponent androidx.window.layout.ExtensionWindowLayoutInfoBackend.component and 5 other contexts)
Missing class androidx.window.extensions.layout.WindowLayoutInfo (referenced from: void androidx.window.layout.ExtensionWindowLayoutInfoBackend$MulticastConsumer.accept(androidx.window.extensions.layout.WindowLayoutInfo) and 2 other contexts)
Missing class androidx.window.sidecar.SidecarDeviceState (referenced from: int androidx.window.layout.SidecarAdapter$Companion.getRawSidecarDevicePosture(androidx.window.sidecar.SidecarDeviceState) and 7 other contexts)
Missing class androidx.window.sidecar.SidecarDisplayFeature (referenced from: java.lang.Boolean androidx.window.layout.SidecarAdapter$translate$checkedFeature$1.invoke(androidx.window.sidecar.SidecarDisplayFeature) and 10 other contexts)
Missing class androidx.window.sidecar.SidecarInterface$SidecarCallback (referenced from: androidx.window.sidecar.SidecarInterface$SidecarCallback androidx.window.layout.SidecarCompat$DistinctSidecarElementCallback.callbackInterface and 5 other contexts)
Missing class androidx.window.sidecar.SidecarInterface (referenced from: androidx.window.sidecar.SidecarInterface androidx.window.layout.SidecarCompat.sidecar and 7 other contexts)
Missing class androidx.window.sidecar.SidecarProvider (referenced from: androidx.window.sidecar.SidecarInterface androidx.window.layout.SidecarCompat$Companion.getSidecarCompat$window_release(android.content.Context) and 1 other context)
Missing class androidx.window.sidecar.SidecarWindowLayoutInfo (referenced from: java.util.List androidx.window.layout.SidecarAdapter$Companion.getSidecarDisplayFeatures(androidx.window.sidecar.SidecarWindowLayoutInfo) and 3 other contexts)
Compilation failed
Exception in thread "main" java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
	at com.android.tools.r8.internal.oO0.a(SourceFile:92)
	at com.android.tools.r8.R8.main(R8.java:4)
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
	at Version.fakeStackEntry(Version_3.1.51.java:0)
	at com.android.tools.r8.internal.oO0.a(SourceFile:68)
	at com.android.tools.r8.internal.oO0.a(SourceFile:28)
	at com.android.tools.r8.internal.oO0.a(SourceFile:27)
	at com.android.tools.r8.R8.b(R8.java:32)
	at com.android.tools.r8.R8.a(R8.java:1389)
	at com.android.tools.r8.internal.oO0.a(SourceFile:84)
	... 1 more
Caused by: com.android.tools.r8.internal.b: Missing class androidx.window.extensions.WindowExtensions (referenced from: androidx.window.extensions.layout.WindowLayoutComponent androidx.window.layout.SafeWindowLayoutComponentProvider$windowLayoutComponent$2.invoke())
Missing class androidx.window.extensions.WindowExtensionsProvider (referenced from: androidx.window.extensions.layout.WindowLayoutComponent androidx.window.layout.SafeWindowLayoutComponentProvider$windowLayoutComponent$2.invoke())
Missing class androidx.window.extensions.layout.DisplayFeature (referenced from: androidx.window.layout.WindowLayoutInfo androidx.window.layout.ExtensionsWindowLayoutInfoAdapter.translate$window_release(android.app.Activity, androidx.window.extensions.layout.WindowLayoutInfo))
Missing class androidx.window.extensions.layout.FoldingFeature (referenced from: androidx.window.layout.FoldingFeature androidx.window.layout.ExtensionsWindowLayoutInfoAdapter.translate$window_release(android.app.Activity, androidx.window.extensions.layout.FoldingFeature) and 1 other context)
Missing class androidx.window.extensions.layout.WindowLayoutComponent (referenced from: androidx.window.extensions.layout.WindowLayoutComponent androidx.window.layout.ExtensionWindowLayoutInfoBackend.component and 5 other contexts)
Missing class androidx.window.extensions.layout.WindowLayoutInfo (referenced from: void androidx.window.layout.ExtensionWindowLayoutInfoBackend$MulticastConsumer.accept(androidx.window.extensions.layout.WindowLayoutInfo) and 2 other contexts)
Missing class androidx.window.sidecar.SidecarDeviceState (referenced from: int androidx.window.layout.SidecarAdapter$Companion.getRawSidecarDevicePosture(androidx.window.sidecar.SidecarDeviceState) and 7 other contexts)
Missing class androidx.window.sidecar.SidecarDisplayFeature (referenced from: java.lang.Boolean androidx.window.layout.SidecarAdapter$translate$checkedFeature$1.invoke(androidx.window.sidecar.SidecarDisplayFeature) and 10 other contexts)
Missing class androidx.window.sidecar.SidecarInterface$SidecarCallback (referenced from: androidx.window.sidecar.SidecarInterface$SidecarCallback androidx.window.layout.SidecarCompat$DistinctSidecarElementCallback.callbackInterface and 5 other contexts)
Missing class androidx.window.sidecar.SidecarInterface (referenced from: androidx.window.sidecar.SidecarInterface androidx.window.layout.SidecarCompat.sidecar and 7 other contexts)
Missing class androidx.window.sidecar.SidecarProvider (referenced from: androidx.window.sidecar.SidecarInterface androidx.window.layout.SidecarCompat$Companion.getSidecarCompat$window_release(android.content.Context) and 1 other context)
Missing class androidx.window.sidecar.SidecarWindowLayoutInfo (referenced from: java.util.List androidx.window.layout.SidecarAdapter$Companion.getSidecarDisplayFeatures(androidx.window.sidecar.SidecarWindowLayoutInfo) and 3 other contexts)
	at com.android.tools.r8.internal.il1.a(SourceFile:14)
	at com.android.tools.r8.internal.il1.a(SourceFile:22)
	at com.android.tools.r8.internal.X71.b(SourceFile:9)
	at com.android.tools.r8.shaking.y.a(SourceFile:1367)
	at com.android.tools.r8.shaking.y.a(SourceFile:1176)
	at com.android.tools.r8.R8.a(R8.java:1329)
	at com.android.tools.r8.R8.a(R8.java:155)
	at com.android.tools.r8.R8.c(R8.java:1)
	at com.android.tools.r8.R8.a(R8.java:1388)
	at com.android.tools.r8.internal.oO0.a(SourceFile:24)
	... 4 more
Error: `"java" "-cp" "/home/dvc/cloudpeer/cross/target/x/maven/com.android.tools-r8-3.1.51.jar" "com.android.tools.r8.R8" "/home/dvc/cloudpeer/cross/target/x/maven/androidx.loader-loader-1.1.0.aar" "/home/dvc/cloudpeer/cross/target/x/maven/androidx.annotation-annotation-1.3.0.jar" "/home/dvc/cloudpeer/cross/target/x/maven/androidx.fragment-fragment-1.4.1.aar" "/home/dvc/cloudpeer/cross/target/x/maven/org.jetbrains.kotlinx-kotlinx-coroutines-android-1.6.0-native-mt.jar" "/home/dvc/cloudpeer/cross/target/x/maven/androidx.lifecycle-lifecycle-common-2.4.1.jar" "/home/dvc/cloudpeer/cross/target/x/maven/androidx.core-core-ktx-1.7.0.aar" "/home/dvc/cloudpeer/cross/target/x/maven/androidx.tracing-tracing-1.0.0.aar" "/home/dvc/cloudpeer/cross/target/x/maven/androidx.lifecycle-lifecycle-livedata-core-2.4.1.aar" "/home/dvc/cloudpeer/cross/target/x/maven/org.jetbrains.kotlinx-kotlinx-coroutines-core-jvm-1.6.0-native-mt.jar" "/home/dvc/cloudpeer/cross/target/x/maven/org.jetbrains.kotlin-kotlin-stdlib-jdk8-1.6.10.jar" "/home/dvc/cloudpeer/cross/target/x/maven/androidx.customview-customview-1.1.0.aar" "/home/dvc/cloudpeer/cross/target/x/maven/androidx.versionedparcelable-versionedparcelable-1.1.1.aar" "/home/dvc/cloudpeer/cross/target/x/maven/org.jetbrains-annotations-23.0.0.jar" "/home/dvc/cloudpeer/cross/target/x/maven/androidx.savedstate-savedstate-1.1.0.aar" "/home/dvc/cloudpeer/cross/target/x/maven/androidx.lifecycle-lifecycle-common-java8-2.4.1.jar" "/home/dvc/cloudpeer/cross/target/x/maven/androidx.lifecycle-lifecycle-viewmodel-2.4.1.aar" "/home/dvc/cloudpeer/cross/target/x/maven/androidx.annotation-annotation-experimental-1.2.0.aar" "/home/dvc/cloudpeer/cross/target/x/maven/androidx.core-core-1.7.0.aar" "/home/dvc/cloudpeer/cross/target/x/maven/androidx.arch.core-core-common-2.1.0.jar" "/home/dvc/cloudpeer/cross/target/x/maven/androidx.collection-collection-1.2.0.jar" "/home/dvc/cloudpeer/cross/target/x/maven/androidx.window-window-1.0.0.aar" "/home/dvc/cloudpeer/cross/target/x/maven/androidx.viewpager-viewpager-1.0.0.aar" "/home/dvc/cloudpeer/cross/target/x/maven/org.jetbrains.kotlin-kotlin-stdlib-jdk7-1.6.10.jar" "/home/dvc/cloudpeer/cross/target/x/maven/io.flutter-flutter_embedding_debug-1.0.0-ab46186b246f5a36bd1f3f295d14a43abb1e2f38.jar" "/home/dvc/cloudpeer/cross/target/x/maven/androidx.arch.core-core-runtime-2.1.0.aar" "/home/dvc/cloudpeer/cross/target/x/maven/androidx.lifecycle-lifecycle-runtime-2.4.1.aar" "/home/dvc/cloudpeer/cross/target/x/maven/androidx.window-window-java-1.0.0.aar" "/home/dvc/cloudpeer/cross/target/x/maven/org.jetbrains.kotlin-kotlin-stdlib-1.6.10.jar" "/home/dvc/cloudpeer/cross/target/x/maven/org.jetbrains.kotlin-kotlin-stdlib-common-1.6.10.jar" "/home/dvc/cloudpeer/cross/target/x/maven/androidx.concurrent-concurrent-futures-1.1.0.jar" "/home/dvc/cloudpeer/cross/target/x/maven/androidx.activity-activity-1.4.0.aar" "/home/dvc/cloudpeer/cross/target/x/maven/androidx.lifecycle-lifecycle-viewmodel-savedstate-2.4.1.aar" "/home/dvc/cloudpeer/cross/target/x/debug/android/java/io/flutter/plugins/GeneratedPluginRegistrant.class" "--lib" "/opt/android-sdk/platforms/android-31/android.jar" "--output" "/home/dvc/cloudpeer/cross/target/x/debug/android" "--pg-conf" "/home/dvc/cloudpeer/cross/target/x/debug/android/proguard-rules.pro"` exited with nonzero exit code.
```
I'm using the following proguard rules:
```
-keep class io.flutter.embedding.android.FlutterActivity
-keep class androidx.core.app.CoreComponentFactory
-keep class io.flutter.plugins.GeneratedPluginRegistrant
```

- [0] https://github.com/androidx/androidx/blob/androidx-main/window/sidecar/sidecar/api/current.txt

**Comment by maheshmnj** [comment]
Hi @dvc94ch, Thanks for filing the issue. Please share the output of `flutter doctor -v`  and the complete output of `flutter run -v` in a text file.

**Comment by dvc94ch** [comment]
never mind actually. that doesn't fix anything. I have absolutely no clue what the problem is.

**Comment by dvc94ch** [comment]
so added some proguard rules and it seems to work:
```
cat assets/proguard-rules.pro
-keep class io.flutter.embedding.android.FlutterActivity
-keep class androidx.core.app.CoreComponentFactory
-keep class io.flutter.plugins.GeneratedPluginRegistrant

-dontwarn androidx.window.extensions.**
-dontwarn androidx.window.extensions.embedding.**
-dontwarn androidx.window.sidecar.**
```
although this feels more like a hack than a solution
