### ISSUE TITLE
webview_flutter: ^3.0.1 | Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.

### ISSUE THREAD

**Issue by PawanFyers** [flutter/flutter#99468]
We are using `webview_flutter: ^3.0.1` in our application. & when we rotate our device we get this error form the WebView plugin.

## Steps to Reproduce

1. Open the Webview with some url & then try to rotate the device on Android 11 (Android API 30) / Flutter 2.8.1

**Expected results:** 
The webview loads without any issue, from Portrait mode to Landscape mode.

**Actual results:** 
When we rotate the device from Portrait to Landscape mode we see a white screen with below Exception

<details>
<summary>Error Log</summary>

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
E/flutter (10364):      at android.view.ViewGroup.addViewInner(ViewGroup.java:5235)
E/flutter (10364):      at android.view.ViewGroup.addView(ViewGroup.java:5064)
E/flutter (10364):      at android.view.ViewGroup.addView(ViewGroup.java:5004)
E/flutter (10364):      at android.view.ViewGroup.addView(ViewGroup.java:4976)
E/flutter (10364):      at io.flutter.plugin.platform.SingleViewPresentation.onCreate(SingleViewPresentation.java:190)
E/flutter (10364):      at android.app.Dialog.dispatchOnCreate(Dialog.java:419)
E/flutter (10364):      at android.app.Dialog.show(Dialog.java:313)
E/flutter (10364):      at android.app.Presentation.show(Presentation.java:257)
E/flutter (10364):      at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:95)
E/flutter (10364):      at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:48)
E/flutter (10364):      at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView(PlatformViewsController.java:212)
E/flutter (10364):      at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:107)
E/flutter (10364):      at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
E/flutter (10364):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/flutter (10364):      at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:178)
E/flutter (10364):      at io.flutter.embedding.engine.dart.DartMessenger.lambda$handleMessageFromDart$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:206)
E/flutter (10364):      at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter (10364):      at android.os.Handler.handleCallback(Handler.java:938)
E/flutter (10364):      at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (10364):      at android.os.Looper.loop(Looper.java:223)
E/flutter (10364):      at android.app.ActivityThread.main(ActivityThread.java:7656)
E/flutter (10364):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter (10364):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/flutter (10364):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter (10364): , null, null)
E/flutter (10364): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter (10364): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
E/flutter (10364): <asynchronous suspension>
E/flutter (10364): #2      TextureAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1061:18)
E/flutter (10364): <asynchronous suspension>
E/flutter (10364): #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:771:5)
E/flutter (10364): <asynchronous suspension>
E/flutter (10364): #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:191:7)
E/flutter (10364): <asynchronous suspension>
E/flutter (10364): 
```
</details>

<details>

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.0.1 21A559 darwin-arm, locale en-IN)
    • Flutter version 2.8.1 at /Users/pawanshahani/fvm/versions/2.8.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 months ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/pawanshahani/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 98.0.4758.109

! Doctor found issues in 1 category.
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @PawanFyers, thanks for filing the issue. 

Please provide a complete minimal reproducible code sample and the output of `flutter run -v` that shows the error you're experiencing. 

Can you also upgrade to the latest stable version to see whether or not you still experience this issue? 

Thank you
