### ISSUE TITLE
Access to XMLHttpRequest  has been blocked by CORS Flutter web

### ISSUE THREAD

**Issue by hiteshsapra** [flutter/flutter#99471]
Hello team.

Any one help me then below CORS policy issue in flutter web google map. We are using below the plugging for our project. 
  1. google_maps_flutter: ^2.1.1
  2. google_maps_flutter_web: ^0.3.2+1  

## Steps to Reproduce

1. implement Google map 
2. Add Polyline in map
3. Android iOS working fine Flutter web getting error

## Logs

<details>
<summary>Logs</summary>

Access to XMLHttpRequest at 'https://maps.googleapis.com/maps/api/directions/json?origin=22.3038945%2C70.80215989999999&destination=22.0346698%2C71.203148&mode=driving&avoidHighways=false&avoidFerries=true&avoidTolls=false&key=key' from origin 'https://ging9.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
main.dart.js:6302 Uncaught Error
    at Object.K7 (main.dart.js:6364:24)
    at aaE.$1 (main.dart.js:87587:53)
    at a4q.qn (main.dart.js:43525:33)
    at aG3.$0 (main.dart.js:42939:11)
    at Object.C9 (main.dart.js:5331:40)
    at an.n2 (main.dart.js:42858:3)
    at Object.b76 (main.dart.js:5431:8)
    at axf.$1 (main.dart.js:43013:9)
    at aFy.$1 (main.dart.js:46862:21)
    at bqh (main.dart.js:4132:17)

</details>

## doctor --verbose
[✓] Flutter (Channel stable, 2.10.0, on macOS 11.6 20G165 darwin-x64, locale en-GB)
    • Flutter version 2.10.0 at /Users/baps/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f105a6ca7 (4 weeks ago), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2

## Issue Image

![Screenshot 2022-03-03 at 2 40 38 PM](https://user-images.githubusercontent.com/87641143/156535187-80824623-d2e3-4568-9acf-c071b69be474.png)

**Comment by darshan-9spl** [comment]
I have the same issue, please help us with how to deal with this issue.

**Comment by hiteshsapra** [comment]
@maheshmnj  One more thing you have idea of CORS?
There are two way 
one is API call via our server and this CORS policy we can manage. but 
Think two is if we are use some plugging and that plugging is now allow CORS that time what i can do?

Than was my question. also Re: this i was added related plugging.

I hope you see this plugging list and close question.

**Comment by yjbanov** [comment]
@maheshmnj was right to close the issue. This issue tracker is to track bugs in Flutter itself. However, it seems the bug is elsewhere. We acknowledge that this bug may be serious for your application. We cannot help unless there's a clear description where the problem is in Flutter. In other words, there's no change in our code or documentation that we can make that will make this bug go away.

I recommend the following steps: try searching the internet for answers related to CORS errors in Google Maps. Perhaps there's something in the Google Maps help pages. If you are suspecting that the issue might be in the Google Maps plugin, try isolating the issue and provide a description that shows the bug in the plugin, ideally with a small app that reproduces it (for example, provide stack traces that are not obfuscated, either from `--debug` or `--profile` build). Then we can send it to our plugins team for evaluation.

**Comment by ditman** [comment]
@hiteshsapra can you please provide a minimal repro "lib/main.dart" so we can reproduce the issue locally? Screenshots are not good enough. We have our own Google Maps API Key, so no need to include yours.

**Comment by ditman** [comment]
From your screenshot it seems you're attempting to use the `directions` API (manually, from a normal request?). This issue needs way more information to be actionable.

This is almost sure related to your problem:

* https://github.com/googlemaps/google-maps-services-js/issues/59#issuecomment-399626833
