### ISSUE TITLE
flutter doctor --android-licenses fails on Windows

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#9954]
## Steps to Reproduce

On Windows:

```
flutter upgrade
flutter doctor --android-licenses
```

## command

flutter doctor --android-licenses

## exception

ProcessException: ProcessException: The system cannot find the file specified.

  Command: C:\Users\m\AppData\Local\Android\sdk\tools\bin\sdkmanager --licenses

```
#0      AndroidWorkflow.runLicenseManager (package:flutter_tools/src/android/android_workflow.dart:182)
<asynchronous suspension>
#1      Doctor.diagnose (package:flutter_tools/src/doctor.dart:111)
<asynchronous suspension>
#2      DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:26)
<asynchronous suspension>
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:210)
<asynchronous suspension>
#4      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:156)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#6      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:262)
<asynchronous suspension>
#7      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#8      Future.Future.sync (dart:async/future.dart:208)
#9      CommandRunner.run (package:args/command_runner.dart:109)
#10     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:157)
#11     run.<anonymous closure> (package:flutter_tools/executable.dart:140)
<asynchronous suspension>
#12     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#13     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#14     _rootRun (dart:async/zone.dart:1120)
#15     _CustomZone.run (dart:async/zone.dart:1001)
#16     runZoned (dart:async/zone.dart:1465)
#17     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#18     run (package:flutter_tools/executable.dart:113)
<asynchronous suspension>
#19     main (package:flutter_tools/executable.dart:66)
<asynchronous suspension>
#20     main (file:///c:/Users/m/dev/github/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#21     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

## flutter doctor

```
[✓] Flutter (on Microsoft Windows [Version 10.0.14393], channel master)
    • Flutter at c:\Users\m\dev\github\flutter
    • Framework revision e4546584d1 (18 minutes ago), 2017-05-10 08:45:36 +0200
    • Engine revision cbbf956fcb
    • Tools Dart version 1.23.0-dev.11.11

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at C:\Users\m\AppData\Local\Android\sdk
    • Platform android-25, build-tools 25.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1)
    • Dart plugin version 171.4424
    • Flutter plugin version 13.1

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)

```

```

**Comment by mit-mit** [comment]
Works great now, thanks!
