### ISSUE TITLE
Generate Flutter Docset for API search/navigation

### ISSUE THREAD

**Issue by Solido** [flutter/flutter#9955]
Docsets is a common format to export documentation of an API.

A lot of powerful tools exist that integrate docsets into any dev tools from intellij to studio code on any platform : Dash, Zeal, Velocity.

Currently all main programming and language are supported, you'll even find Darlang, Polymer, AngularDart.

Having Flutter supported consist to publish to dartdocs.org and here's the current script 
https://github.com/astashov/dartdocs.org/blob/master/update_flutter.sh

Having this corrected will offer a huge support for the discovery of the API and learning curve.

ps: And I'm so tired to switch between intellij and my browser looking for docs ;)

**Comment by Skylled** [comment]
I'm in favor of this, because I like to be able to work offline (riding passenger in a vehicle), and I can't do that and have the Flutter docs available to reference.

**Comment by sethladd** [comment]
In the meantime, you can generate the docs:

```
git clone the alpha branch of flutter
cd flutter
dev/bots/docs.sh
```

Do that with a network connection first, it may want to download some dependencies.

Let us know if that works!

**Comment by Solido** [comment]
Currently docs have been updated to https://www.dartdocs.org/documentation/flutter/0.0.27-dev/index.html and so Flutter is available to Dash. 

Flutter doctor would not tell what's the last version is but having access to 0.0.27 docs is really helpful.

To be fair this feature is way underestimated on how it helps with the Flutter learning curve.

**Comment by sethladd** [comment]
> Flutter doctor would not tell what's the last version

Would you be willing to mock up what flutter doctor should print out? an example would help. Thanks!

**Comment by Solido** [comment]
Here's my Flutter output, how can I check the version number I'm working on ? 
`
[✓] Flutter (on Mac OS X 10.12.5 16F73, locale en-FR, channel master)
Flutter at /Users/robbie/Install/flutter
Framework revision 3db402ec98 (11 hours ago), 2017-06-15 23:01:25 -0700
Engine revision f741647d49
Tools Dart version 1.24.0-dev.6.7
`

As you may see I'm on master to benefits the last commits but I've no idea on what version I'm.
It's master and commit 3db402ec98 but how this rely to 

Official docs (see page footer)
`Flutter •  Dart • cc license • 2017-06-15 01:01 • 6f77b4a9a76e57c4e6d23e61ba59a0cdd80d22b7`

DartDocs (page footer)
`flutter 0.0.27-dev •  Dart • cc license`

This is just for convenience knowing what documentation numbers I'm reading when using Dash.

My point is just I've no idea how far my current workflow is from the last published docs on DartDocs.

Thanks !

**Comment by sethladd** [comment]
Thank you! can you please:

* Open a new issue which states that our docs.flutter.io doesn't make it clear which version it's using.

* Open a new issue which states that it's not easy to find the version number from flutter doctor's output?

Much appreciated.

(meanwhile, we probably want to stop generating docs on dartdocs.org for Flutter. I believe there's an issue to delete those docs, or at least redirect over to docs.flutter.io)

**Comment by Solido** [comment]
Ah ! so there's no change to have this bug resolved and have Flutter doc inside Dash ?
You must have some serious reasons do not do this since nearly all large adoption publish to docset tools ? I'm really insisting on this :)

OK for opening issues.

**Comment by sethladd** [comment]
@Solido we should generate a .zip of our API docs on every alpha build. That's what this issue is about. Would that be sufficient for Dash integration?

Meanwhile, you brought up some good points about other aspects of our docs, which I don't want to lose, and thus we should open separate issues.

**Comment by Solido** [comment]
The dash lead dev have build a parser for dartdocs.org. Any package published get translated to DocSet and is available to all tools. It mean than intellij, VSCode or even Alfred on MacOS get instant search on the Flutter API.

I'm working on complex stack and using this tools I've access to ALL my techs documentations, from Groovy to SpringFramework, Dart collections, etc and it's very painful for me to have to open a website and type some words in a search box since I'm searching a LOT (Flutter is kinda complex :D ).

I'm not aware of the full process but I've talked to the lead dev of Dash. They wrote a parser for Dart and any documentation published to DartDocs is parsed to docsets and published to all tools as package. 

To give you an idea how I use it in my case it's bind to Alfred, VsCode and Intellij. Pressing Alt+Space from any where and tapping elevation drive me straight to the Flutter docs `flutter material AppBar elevation`

It is difficult for me to be able on one side to find any class/methods/fields/ StackOverflow questions in Spring/Java/Scala/Javascript/Haskell Frameworks and not be able to do the same using Flutter. Having to open a website and tap in the search field to find so docs is overkill.

You should be able to generate docs and publish when you deploy new alpha/beta once every weeks, it would be more than enough but I'm not aware of the full publication process/difficulties. I'm stubborn on the benefits would overcome problems.

Have a quick look here to see why all devs from java to react are using DocSets tools.
https://youtu.be/8j8q-yorAKo?t=1m48s

PS: App is available on IOS/Android yes it means offline documentation.

**Comment by sethladd** [comment]
Thanks! Agreed, we need to build a .zip of the docs on every alpha release and put it at a known download URL.

**Comment by MaskyS** [comment]
Any progress on this? :)

**Comment by indiealexh** [comment]
If the dart package docs system could auto generate the packages that would be awesome.

**Comment by papakay** [comment]
Could not download Flutter documentation in Dash.

Please see the attachment for the error details.
<img width="691" alt="screen shot 2018-05-14 at 9 42 51 am" src="https://user-images.githubusercontent.com/5013738/39986994-507108d0-575b-11e8-9913-12e7634ebac7.png">

**Comment by xster** [comment]
We can basically in https://github.com/flutter/flutter/blob/master/dev/bots/docs.sh#L32 insert another line that just packs the whole thing in a zip and host it in the same directory in firebase. 

The tricky bit was generating the .docset via https://twitter.com/kapeli/status/983853760459034624 which seems to work for Dash's maintainer but doesn't work for me for some reason. I didn't dig more into it.

**Comment by ooglek** [comment]
I'd love to see this working!

**Comment by imWildCat** [comment]
@xster It does not work for me either.

It is very annoying that `dartdocset` is not open sourced

**Comment by imWildCat** [comment]
![image](https://user-images.githubusercontent.com/2396817/42182859-9ebb9c46-7e37-11e8-9831-85cbaa7bec09.png)

Hello guys, I've successfully build a docset of flutter using `dashing`. Any suggestions for the location to upload this docset? It is 658.6MB before compression.

**Comment by imWildCat** [comment]
RE: https://github.com/Kapeli/Dash-User-Contributions/issues/1638

@filiph @bjornbjorn @maksimr

I've created a probably correct version of flutter docset: https://drive.google.com/file/d/1cEtXuAkSctAk6AUoVfZAWRVStfBhEqPT/view

```
MD5 (flutter-0.5.6-pre.75.tgz) = c151a3fec08f2a0eda97f530701c7294
SHA1: e7e2890d2091d392a947dc4fdc959b5eac0fbf03  flutter-0.5.6-pre.75.tgz
```
Source code for `dashing`:
```json
{
    "name": "flutter-doc-dev",
    "package": "flutter",
    "index": "index.html",
    "selectors": {
       
        "#exceptions span.name a": {
            "type": "Exception"
        },

        "body > main > div.col-xs-12.col-sm-9.col-md-8.main-content > h1": {
            "requiretext": " library",
            "type": "Library",
            "regexp": " library",
            "replacement": ""
        },

        "body > main > div.col-xs-12.col-sm-9.main-content > h1": {
            "requiretext": " class",
            "type": "Class",
            "regexp": " class",
            "replacement": ""
        },

        "body > main > div.col-xs-12.col-md-8.main-content > h1": {
            "requiretext": " function",
            "type": "Function",
            "regexp": " function",
            "replacement": ""
        },

        "body > main > div.col-sm-9.col-md-8.main-content > h1": {
            "requiretext": " typedef",
            "type": "Type",
            "regexp": " typedef",
            "replacement": ""
        },

        "body > main > .col-xs-12.col-sm-9.col-md-8.main-content > h1": {
            "requiretext": " enum",
            "type": "Enum",
            "regexp": " enum",
            "replacement": ""
        },

        "body > main > .col-md-8.main-content > h1": {
            "requiretext": " constant",
            "type": "Constant",
            "regexp": " constant",
            "replacement": ""
        },

        "body > main > div.col-xs-12.col-sm-9 > h1": {
            "requiretext": " method",
            "type": "Method",
            "regexp": " method",
            "replacement": ""
        },

        "body > main > .col-xs-12.col-sm-9.col-md-8 > h1": {
            "requiretext": " property",
            "type": "Property",
            "regexp": " property",
            "replacement": ""
        },

        "body > main > .col-xs-12.col-md-8 > h1": {
            "requiretext": " constructor",
            "type": "Constructor",
            "regexp": " constructor",
            "replacement": ""
        },

        "body > main > .col-xs-12.col-sm-9.main-content > h1": {
            "requiretext": "operator ",
            "type": "Operator",
            "regexp": "operator ",
            "replacement": ""
        }

        
    },
    "ignore": [
        "ABOUT"
    ],
    "icon32x32": "",
    "allowJS": false,
    "ExternalURL": ""
}
```

Please feel free to contribute it to the Dash docset repository.

**Comment by mathieujobin** [comment]
it works, thank you so much, downloaded, decompressed, moved to my docset folder and restarted Zeal. Thank you

**Comment by MoSala7** [comment]
Thanks it works fine ...
but it cant be updated :(

**Comment by FlutterIODev** [comment]
> RE: [Kapeli/Dash-User-Contributions#1638](https://github.com/Kapeli/Dash-User-Contributions/issues/1638)
> 
> @filiph @bjornbjorn @maksimr
> 
> I've created a probably correct version of flutter docset: https://drive.google.com/file/d/1cEtXuAkSctAk6AUoVfZAWRVStfBhEqPT/view
> 
> ```
> MD5 (flutter-0.5.6-pre.75.tgz) = c151a3fec08f2a0eda97f530701c7294
> SHA1: e7e2890d2091d392a947dc4fdc959b5eac0fbf03  flutter-0.5.6-pre.75.tgz
> ```
> Source code for `dashing`:
> 
> ```json
> {
>     "name": "flutter-doc-dev",
>     "package": "flutter",
>     "index": "index.html",
>     "selectors": {
>        
>         "#exceptions span.name a": {
>             "type": "Exception"
>         },
> 
>         "body > main > div.col-xs-12.col-sm-9.col-md-8.main-content > h1": {
>             "requiretext": " library",
>             "type": "Library",
>             "regexp": " library",
>             "replacement": ""
>         },
> 
>         "body > main > div.col-xs-12.col-sm-9.main-content > h1": {
>             "requiretext": " class",
>             "type": "Class",
>             "regexp": " class",
>             "replacement": ""
>         },
> 
>         "body > main > div.col-xs-12.col-md-8.main-content > h1": {
>             "requiretext": " function",
>             "type": "Function",
>             "regexp": " function",
>             "replacement": ""
>         },
> 
>         "body > main > div.col-sm-9.col-md-8.main-content > h1": {
>             "requiretext": " typedef",
>             "type": "Type",
>             "regexp": " typedef",
>             "replacement": ""
>         },
> 
>         "body > main > .col-xs-12.col-sm-9.col-md-8.main-content > h1": {
>             "requiretext": " enum",
>             "type": "Enum",
>             "regexp": " enum",
>             "replacement": ""
>         },
> 
>         "body > main > .col-md-8.main-content > h1": {
>             "requiretext": " constant",
>             "type": "Constant",
>             "regexp": " constant",
>             "replacement": ""
>         },
> 
>         "body > main > div.col-xs-12.col-sm-9 > h1": {
>             "requiretext": " method",
>             "type": "Method",
>             "regexp": " method",
>             "replacement": ""
>         },
> 
>         "body > main > .col-xs-12.col-sm-9.col-md-8 > h1": {
>             "requiretext": " property",
>             "type": "Property",
>             "regexp": " property",
>             "replacement": ""
>         },
> 
>         "body > main > .col-xs-12.col-md-8 > h1": {
>             "requiretext": " constructor",
>             "type": "Constructor",
>             "regexp": " constructor",
>             "replacement": ""
>         },
> 
>         "body > main > .col-xs-12.col-sm-9.main-content > h1": {
>             "requiretext": "operator ",
>             "type": "Operator",
>             "regexp": "operator ",
>             "replacement": ""
>         }
> 
>         
>     },
>     "ignore": [
>         "ABOUT"
>     ],
>     "icon32x32": "",
>     "allowJS": false,
>     "ExternalURL": ""
> }
> ```
> 
> Currently I am too busy to refine it so that it could get a good quality for publishing to the Dash docset repo.
> Please feel free to contribute it to the Dash docset repository.
> 
> Preview:
> 
> <img alt="image" width="254" src="https://user-images.githubusercontent.com/2396817/42189788-db138428-7e51-11e8-9dca-e35025a67bba.png">
> 
> <img alt="image" width="239" src="https://user-images.githubusercontent.com/2396817/42189823-002cf1b8-7e52-11e8-988e-46c34a0d760e.png">

from where you downloade the flutter (html pages) folder ?

**Comment by FlutterIODev** [comment]
I hope you find a good job,

Thanks for your replay :)

**Comment by imWildCat** [comment]
@FlutterIODev 

Good news, I've generated the docs of version `0.8.2` for you:
https://drive.google.com/open?id=11BoHcGefNXcfYttH4XfgEuTcLEwBb-IE

In addition, I also generated the `.docset` with the `dashing` config I provided before: https://drive.google.com/open?id=1iTgp6YWVOy8lFz1OMSvzO8ob9zfLoDnW
Please note that this version of docset may not work perfectly.

**Comment by gspencergoog** [comment]
OK, I've submitted a PR for review to generate a zip file of our docs whenever we generate our documentation, and upload it to the docs.flutter.io site.  What else needs to happen to make it available in Dash?  And is there a way to make documentation sets available in IDEs on other platforms, as it appears that Dash is macOS only?

**Comment by imWildCat** [comment]
@gspencergoog My pleasure. A PR is opened: #24374.

Please note that the `dashing.json` does not support the `version` field according to https://github.com/technosophos/dashing/blob/master/dashing.go#L52-L70

**Comment by gspencergoog** [comment]
Thanks, I'll remove the version then and just put it into the feed xml file.

**Comment by gspencergoog** [comment]
OK, this has merged, but we're having some issues with our docs site deployment, so bear with us until that's ironed out. I'll post here (and close this issue) once the docset and zip file are actually available.

**Comment by imWildCat** [comment]
Cheers! 

I could keep updating my personal docset builds until the official docset is deployed. In addition, I will also help to improve the dashing.json after getting a job : )

**Comment by cmpeguerog** [comment]
Hi @imWildCat. 
Im getting this error when trying to build the docs for the new release but im getting the next error.
```
ProcessException: The system cannot find the file specified.
Command: flutter
#0      _ProcessImpl._runAndWait (dart:io/runtime/binprocess_patch.dart:488:7)
#1      _runNonInteractiveProcessSync (dart:io/runtime/binprocess_patch.dart:633:18)
#2      Process.runSync (dart:io/runtime/binprocess_patch.dart:66:12)
#3      main (file:///D:/Projects/Flutter/flutter/dev/tools/dartdoc.dart:43:41)
<asynchronous suspension>
#4      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

```
Info: 
OS: Windows 10.
Flutter 1.0.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5391447fae (6 days ago) • 2018-11-29 19:41:26 -0800
Engine • revision 7375a0f414
Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

**Comment by gspencergoog** [comment]
Looks like the flutter command isn't in your path.  If you really need to build the docs locally (you shouldn't need to in most cases), try running the dev/bots/docs.sh script on Linux or macOS.

**Comment by mupkoo** [comment]
I added the feed and installed the docset, but I think that I don't have the complete docs. Here is a screenshot

<img width="255" alt="Screen Shot 2019-03-23 at 2 51 44" src="https://user-images.githubusercontent.com/1788571/54859513-bacb0f80-4d16-11e9-8f24-6bfb645a3166.png">

and if I search for IconButton for example, I get no results

**Comment by gspencergoog** [comment]
Yes, there was an issue generating docsets for the stable release, which we have since fixed, but we haven't generated a new release yet.  You can use the docs for the master channel until the next stable release:

 https://master-api.flutter.dev/offline/flutter.xml

**Comment by mupkoo** [comment]
Thanks for the reply

**Comment by MrAlek** [comment]
@gspencergoog Seems like it wasn't fixed for the 1.5.4 release, https://docs.flutter.io/offline/flutter.xml gives a 404. The master docs work though.

**Comment by shyndman** [comment]
@gspencergoog Is the generator code online somewhere? I'd love to fill in some of the gaps.

**Comment by gspencergoog** [comment]
Sure, it's in https://github.com/flutter/flutter/blob/master/dev/bots/docs.sh#L49

The docs themselves are generated by dartdoc from this script: https://github.com/flutter/flutter/blob/master/dev/tools/dartdoc.dart

The Docset is generated using Dashing from the HTML that dartdoc generates.

**Comment by gspencergoog** [comment]
The config for Dashing is in https://github.com/flutter/flutter/blob/master/dev/docs/dashing.json

And we do some post-processing on it: https://github.com/flutter/flutter/blob/master/dev/docs/dashing_postprocess.dart

**Comment by shyndman** [comment]
Excellent! Thank you Greg. :)
