### ISSUE TITLE
[tool_crash] FileSystemException: Creation of temporary directory failed, OS Error: Permission denied, errno = 13

### ISSUE THREAD

**Issue by spiralw** [flutter/flutter#99601]
## Command
```
flutter run -d chrome
```

## Steps to Reproduce
1. make /tmp directory not writable
2. run `flutter run` command
3. it crashes

## Logs
FileSystemException: Creation of temporary directory failed, OS Error: Permission denied, errno = 13
```
#0      _Directory.createTempSync (dart:io/directory_impl.dart:181:7)
#1      ForwardingDirectory.createTempSync (package:file/src/forwarding/forwarding_directory.dart:28:21)
#2      LocalFileSystem.systemTempDirectory (package:flutter_tools/src/base/file_system.dart:221:47)
#3      ForwardingFileSystem.systemTempDirectory (package:file/src/forwarding/forwarding_file_system.dart:33:49)
#4      new ResidentRunner (package:flutter_tools/src/resident_runner.dart:1017:24)
#5      new ResidentWebRunner (package:flutter_tools/src/isolated/resident_web_runner.dart:105:8)
#6      DwdsWebRunnerFactory.createWebRunner (package:flutter_tools/src/isolated/resident_web_runner.dart:64:12)
#7      RunCommand.createRunner (package:flutter_tools/src/commands/run.dart:519:31)
<asynchronous suspension>
#8      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:646:35)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1165:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
```
```
[✓] Flutter (Channel master, 2.11.0-0.0.pre.683, on KDE neon User - Plasma 25th Anniversary Edition 5.11.0-46-generic, locale en_US.UTF-8)
    • Flutter version 2.11.0-0.0.pre.683 at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter
    • Framework revision fd71de13fd (8 days ago), 2022-02-25 16:06:15 +0200
    • Engine revision 1012ac4b5a
    • Dart version 2.17.0 (build 2.17.0-141.0.dev)
    • DevTools version 2.11.0

[!] Android toolchain - develop for Android devices
    • Android SDK at /opt
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

    ✗ No valid Android SDK platforms found in /opt/platforms. Directory was empty.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code (version 1.63.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • KDE neon User - Plasma 25th Anniversary Edition 5.11.0-46-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 98.0.4758.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

```

**Comment by iapicca** [comment]
dupe?
https://github.com/flutter/flutter/issues/99531
https://github.com/flutter/flutter/issues/96568

**Comment by spiralw** [comment]
doesn't look like a duplicate based on the stack trace (or at least not crashing at the same location)

**Comment by danagbemava-nc** [comment]
Hi @spiralw, is there any reason you need to make the `/tmp` directory not writable?

**Comment by spiralw** [comment]
no, that was an error. I made /tmp writable again to fix the issue

**Comment by danagbemava-nc** [comment]
Since this has been resolved on your end, I feel it is safe to close this issue. 

Closing as solved. 

Thank you

**Comment by spiralw** [comment]
well, ideally it shouldn't crash, and instead print a proper error
