### ISSUE TITLE
App works in debug mode, but doesn't in release mode. (error 2234)

### ISSUE THREAD

**Issue by FriedEgg09** [flutter/flutter#99635]
`flutter doctor -v`:

```
[√] Flutter (Channel stable, 2.10.2, on Microsoft Windows [Version 10.0.22000.527], locale fi-FI)
    • Flutter version 2.10.2 at C:\Users\rasmu\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (2 weeks ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\rasmu\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31624.102
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.64.2)
    • VS Code at C:\Users\rasmu\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.36.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.527]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 98.0.4758.102
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 98.0.1108.62

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
exit code 0

```

debug console output:
```
Launching lib\main.dart on Windows in release mode...
lib\main.dart:1
CUSTOMBUILD : error : Unable to read file: [C:\Users\rasmu\OneDrive\Ty]()´┐¢p´┐¢yt´┐¢\Coding\flutter\munakas\.dart_tool\flutter_build\ca4c2596fc825820b65c296e57598299\app.dill [[C:\Users\rasmu\OneDrive\Ty]()öpöytä\Coding\flutter\munakas\build\windows\flutter\flutter_assemble.vcxproj]
  ../../third_party/dart/runtime/vm/dart_api_impl.cc: 2234: error: Dart_ExitScope expects there to be a current isolate. Did you forget to call Dart_CreateIsolateGroup or Dart_EnterIsolate?

[C:\Program]() Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: Custom build for '[C:\Users\rasmu\OneDrive\Ty]()öpöytä\Coding\flutter\munakas\build\windows\CMakeFiles\01a6b2f882c164504c1543e6348d4ff4\flutter_windows.dll.rule;[C:\Users\rasmu\OneDrive\Ty]()öpöytä\Coding\flutter\munakas\build\windows\CMakeFiles\9772091a2d4a28c93d25d04683244275\flutter_assemble.rule' exited with code 1. [[C:\Users\rasmu\OneDrive\Ty]()öpöytä\Coding\flutter\munakas\build\windows\flutter\flutter_assemble.vcxproj]
Exception: Build process failed.
#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      _runBuild (package:flutter_tools/src/windows/build_windows.dart:311:5)
<asynchronous suspension>
#2      buildWindows (package:flutter_tools/src/windows/build_windows.dart:77:5)
<asynchronous suspension>
#3      WindowsDevice.buildForDevice (package:flutter_tools/src/windows/windows_device.dart:62:5)
<asynchronous suspension>
#4      DesktopDevice.startApp (package:flutter_tools/src/desktop_device.dart:123:7)
<asynchronous suspension>
#5      FlutterDevice.runCold (package:flutter_tools/src/resident_runner.dart:501:33)
<asynchronous suspension>
#6      ColdRunner.run (package:flutter_tools/src/run_cold.dart:71:28)
<asynchronous suspension>
#7      AppDomain.launch.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:621:9)
<asynchronous suspension>
#8      AppDomain.launch (package:flutter_tools/src/commands/daemon.dart:619:5)
<asynchronous suspension>
#9      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:571:15)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#16     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#18     main (package:flutter_tools/executable.dart:94:3)
<asynchronous suspension>
2

Exited (sigterm)
```
Ask for more information. I don't know if this is the right place, but I ask anyway.

(In paths "Työpöytä" means desktop.)

**Comment by FriedEgg09** [comment]
Maybe the problem is that my flutter project path contains characters like "ä" and "ö". Comment if I'm right.

**Comment by darshankawar** [comment]
@FriedEgg09 
`[C:\Users\rasmu\OneDrive\Ty]()´┐¢p´┐¢yt´┐¢` 

What does these symbols represent ?  Is it same as `[C:\Users\rasmu\OneDrive\Ty]()öpöytä\Coding\` ? If so, why are different
It is probably unable to read the file from the path `[C:\Users\rasmu\OneDrive\Ty]()´┐¢p´┐¢yt´┐¢\Coding\flutter\munakas\` which is why the error is `unable to read file`. 

Can you try to probably try to fix the name / path with English letters and try again to see if it helps ?

**Comment by FriedEgg09** [comment]
How can I change the project path? Isn't they the way that the files for example build files are then trying to build the app in old folders? Or can I just move the folder and files update automatically?

**Comment by darshankawar** [comment]
> [C:\Users\rasmu\OneDrive\Ty]()´┐¢p´┐¢yt´┐¢

@FriedEgg09 What does the symbols represent actually ? Where are they coming from ?
Although the error seems to be coming from Dart itself but it does indicate that it is unable to read the file located at the path mentioned that starts with above.

Also, can you provide `flutter run --release --verbose` logs ?

**Comment by FriedEgg09** [comment]
The symbols are there because of characters like "ä" and "ö", idk why. `flutter run --release --verbose` causes an error:
```
flutter : The term 'flutter' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ flutter run --release --verbose
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (flutter:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

I tried to change the path and it worked correctly, but put warning to debug console:
```
[C:\Program]() Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(513,5): warning MSB8028: The intermediate directory (flutter_wrapper_app.dir\Debug\) contains files shared from another project (flutter_wrapper_app.vcxproj).  This can lead to incorrect clean and rebuild behavior. [[C:\flutter\munakas\build\windows\flutter\flutter_wrapper_app.vcxproj]()]
[C:\Program]() Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(513,5): warning MSB8028: The intermediate directory (flutter_wrapper_plugin.dir\Debug\) contains files shared from another project (flutter_wrapper_plugin.vcxproj).  This can lead to incorrect clean and rebuild behavior. [[C:\flutter\munakas\build\windows\flutter\flutter_wrapper_plugin.vcxproj]()]
[C:\Program]() Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(513,5): warning MSB8028: The intermediate directory (url_launcher_windows_plugin.dir\Debug\) contains files shared from another project (url_launcher_windows_plugin.vcxproj).  This can lead to incorrect clean and rebuild behavior. [[C:\flutter\munakas\build\windows\plugins\url_launcher_windows\url_launcher_windows_plugin.vcxproj]()]
```

**Comment by darshankawar** [comment]
> flutter : The term 'flutter' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
> At line:1 char:1
> + flutter run --release --verbose
> + ~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (flutter:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException

From where are you trying to run the command ? CMD or powershell ? If powershell, what's the version of it ? Can you confirm if you are using latest version of it ?

**Comment by FriedEgg09** [comment]
I tried in cmd `10.0.22000.527` and from powershell inside VSCode I get `5.1.22000.282`

**Comment by darshankawar** [comment]
Thanks for the update.

> CUSTOMBUILD : error : Unable to read file: [C:\Users\rasmu\OneDrive\Ty]()´┐¢p´┐¢yt´┐¢\Coding\flutter\munakas\.dart_tool\flutter_build\ca4c2596fc825820b65c296e57598299\app.dill [[C:\Users\rasmu\OneDrive\Ty]()öpöytä\Coding\flutter\munakas\build\windows\flutter\flutter_assemble.vcxproj]
>   ../../third_party/dart/runtime/vm/dart_api_impl.cc: 2234: error: Dart_ExitScope expects there to be a current isolate. Did you forget to call Dart_CreateIsolateGroup or Dart_EnterIsolate?

Are you saying this error doesn't occur anymore after changing the path ?

`but put warning to debug console:` Does the app compile and build in release mode now apart from the warnings you mentioned ?

**Comment by FriedEgg09** [comment]
It works now in release mode, but in debug mode the warning is still there. And I noyiced too, that I cant update flutter without these commandline-tools, because i need to run the upgrade with `--force`.

**Comment by darshankawar** [comment]
@FriedEgg09 
When you run `flutter upgrade` does it give you any message in the console ? Probably you have some uncommitted local changes that might be prohibiting to upgrade.

**Comment by FriedEgg09** [comment]
It says:
```
[flutter] flutter upgrade
Your flutter checkout has local changes that would be erased by upgrading. If you want to keep these changes, it is recommended that you stash them via "git stash" or else commit the changes to a local branch. If it is okay to remove local changes, then re-run this command with "--force".
exit code 1
```
But i tried to `git stash` and nothing changed. I also tried to commit and pull and push, but didn't work. And when I look to source control page, it says `0 changes`. I will try to solve the commandline tool problem when you aren't answered yet.

**Comment by darshankawar** [comment]
> [flutter] flutter upgrade
> Your flutter checkout has local changes that would be erased by upgrading. If you want to keep these changes, it is recommended that you stash them via "git stash" or else commit the changes to a local branch. If it is okay to remove local changes, then re-run this command with "--force".
> exit code 1

Is that coming from vscode powershell when you run `flutter upgrade` or using cmd too ?

**Comment by FriedEgg09** [comment]
It comes when I run `flutter upgrade`, but I can't put `--force` to it, because I can only run the command with command palette.

**Comment by darshankawar** [comment]
@FriedEgg09 
It seems like a path or location issue to me. Can you try below solutions and see if they work for you ?

https://github.com/flutter/flutter-intellij/issues/3657#issuecomment-513812084

https://github.com/flutter/flutter-intellij/issues/3657#issuecomment-554706884

**Comment by FriedEgg09** [comment]
Neither of them worked. And I checked that the SDK is in the place that the command  `flutter doctor -v` said. Isn't there any manual way to upgrade it?

**Comment by darshankawar** [comment]
Can you try following:

```
git clean -xfd
git stash save --keep-index
git stash drop
git pull
flutter doctor -v
```

**Comment by FriedEgg09** [comment]
Here's the console session (bash):
```
rasmu@LAPTOP-O67QHH52 MINGW64 /c/flutter/munakas (main)
$ git clean -xfd
Removing .dart_tool/
Removing .flutter-plugins
Removing .flutter-plugins-dependencies
Removing .idea/
Removing .packages
Removing android/.gradle/
Removing android/app/src/main/java/
Removing android/gradle/wrapper/gradle-wrapper.jar
Removing android/gradlew
Removing android/gradlew.bat
Removing android/local.properties
Removing android/munakas_android.iml
Removing build/
Removing ios/Flutter/Generated.xcconfig
Removing ios/Flutter/flutter_export_environment.sh
Removing ios/Runner/GeneratedPluginRegistrant.h
Removing ios/Runner/GeneratedPluginRegistrant.m
Removing lib/generated_plugin_registrant.dart
Removing munakas.iml
Removing windows/flutter/ephemeral/

rasmu@LAPTOP-O67QHH52 MINGW64 /c/flutter/munakas (main)
$ git stash save --keep-index
No local changes to save

rasmu@LAPTOP-O67QHH52 MINGW64 /c/flutter/munakas (main)
$ git stash drop
No stash entries found.

rasmu@LAPTOP-O67QHH52 MINGW64 /c/flutter/munakas (main)
$ git pull
Already up to date.
```
and `flutter doctor -v` (I still can't do it with command line):
````
[√] Flutter (Channel stable, 2.10.2, on Microsoft Windows [Version 10.0.22000.556], locale fi-FI)
    • Flutter version 2.10.2 at C:\Users\rasmu\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (3 weeks ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\rasmu\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31624.102
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.65.2)
    • VS Code at C:\Users\rasmu\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.36.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.556]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 99.0.4844.51
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 99.0.1150.30

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
exit code 0
```

**Comment by darshankawar** [comment]
@FriedEgg09 
So If I understand correctly the current issue you are facing is, you are unable to upgrade while trying to run `flutter channel upgrade`  and you currently need to use `flutter upgrade --force` ?

**Comment by FriedEgg09** [comment]
Because I cannot use commandlinetools I have to do it with VSCode commandpalette but by that way there are only `flutter upgrade` option. The problem is that I can't use the commandlinetools.

**Comment by darshankawar** [comment]
@FriedEgg09 
From your `flutter doctor -v`, it seems you don't have commandline tools installed as pointed out:

```
[!] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\rasmu\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
```

Try to install them as instructed and then run using commandline tools and see if it helps.

**Comment by FriedEgg09** [comment]
Here's the result:
```
C:\Users\rasmu>C:\Users\rasmu\AppData\Local\Android\sdk\tools\bin\sdkmanager.bat --install "cmdline-tools;latest"

ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.
```

**Comment by darshankawar** [comment]
@FriedEgg09 
I think this is now getting into more of a general error since your original issue you reported has been resolved.

For the latest error you are getting, please try to search over internet for the solutions already present and kindly don't just provide the error you are getting. One similar issue is this which can help you : https://stackoverflow.com/questions/64359564/error-java-home-is-not-set-and-no-java-command-could-be-found-in-your-flutter

Closing from here, as the latest error you are reporting is more of a config issue at your end.
