### ISSUE TITLE
[!] Error installing gRPC-Core

### ISSUE THREAD

**Issue by biad-iritie** [flutter/flutter#99662]
I'm new with Flutter and I'm in China, I want to install the package **cloud_firebase** to my project but the installation stuck every time on gRPC-Core and I have one issue with **flutter doctor**
flutter doctor -v =>
<img width="965" alt="Screenshot 2022-03-07 at 3 54 54 PM" src="https://user-images.githubusercontent.com/29154008/156990306-dc81cc5e-1133-4fca-aba0-2f7534880c46.png">

how to solve this ? 👆🏾 HTTP Host Availability

<details>
<summary> log </summary>

```

And my main issue is the installation of **cloud_firebase**, this is the error 
`-> Installing gRPC-Core (1.28.2)
 > Git download
 > Git download
     $ /usr/bin/git clone https://github.com/grpc/grpc.git /var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l --template=
     --single-branch --depth 1 --branch v1.28.2
     Cloning into '/var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l'...
     Note: switching to 'e122aae3cecae0e6be11b62fbe81eda55e662a02'.
     
     You are in 'detached HEAD' state. You can look around, make experimental
     changes and commit them, and you can discard any commits you make in this
     state without impacting any branches by switching back to a branch.
     
     If you want to create a new branch to retain commits you create, you may
     do so (now or later) by using -c with the switch command. Example:
     
       git switch -c <new-branch-name>
     
     Or undo this operation with:
     
       git switch -
     
     Turn off this advice by setting config variable advice.detachedHead to false
     
     Updating files: 100% (8203/8203), done.
     $ /usr/bin/git -C /var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l submodule update --init --recursive
     Submodule 'third_party/abseil-cpp' (https://github.com/abseil/abseil-cpp.git) registered for path 'third_party/abseil-cpp'
     Submodule 'third_party/benchmark' (https://github.com/google/benchmark) registered for path 'third_party/benchmark'
     Submodule 'third_party/bloaty' (https://github.com/google/bloaty.git) registered for path 'third_party/bloaty'
     Submodule 'third_party/boringssl-with-bazel' (https://github.com/google/boringssl.git) registered for path 'third_party/boringssl-with-bazel'
     Submodule 'third_party/cares/cares' (https://github.com/c-ares/c-ares.git) registered for path 'third_party/cares/cares'
     Submodule 'third_party/envoy-api' (https://github.com/envoyproxy/data-plane-api.git) registered for path 'third_party/envoy-api'
     Submodule 'third_party/gflags' (https://github.com/gflags/gflags.git) registered for path 'third_party/gflags'
     Submodule 'third_party/googleapis' (https://github.com/googleapis/googleapis.git) registered for path 'third_party/googleapis'
     Submodule 'third_party/googletest' (https://github.com/google/googletest.git) registered for path 'third_party/googletest'
     Submodule 'third_party/libuv' (https://github.com/libuv/libuv.git) registered for path 'third_party/libuv'
     Submodule 'third_party/protobuf' (https://github.com/google/protobuf.git) registered for path 'third_party/protobuf'
     Submodule 'third_party/protoc-gen-validate' (https://github.com/envoyproxy/protoc-gen-validate.git) registered for path 'third_party/protoc-gen-validate'
     Submodule 'third_party/udpa' (https://github.com/cncf/udpa.git) registered for path 'third_party/udpa'
     Submodule 'third_party/zlib' (https://github.com/madler/zlib) registered for path 'third_party/zlib'
     Cloning into '/private/var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l/third_party/abseil-cpp'...
     Cloning into '/private/var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l/third_party/benchmark'...
     Cloning into '/private/var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l/third_party/bloaty'...
     Cloning into '/private/var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l/third_party/boringssl-with-bazel'...
     Cloning into '/private/var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l/third_party/cares/cares'...
     fatal: unable to access 'https://github.com/c-ares/c-ares.git/': LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443 
     fatal: clone of 'https://github.com/c-ares/c-ares.git' into submodule path '/private/var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l/third_party/cares/cares' failed
     Failed to clone 'third_party/cares/cares'. Retry scheduled
     Cloning into '/private/var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l/third_party/envoy-api'...
     Cloning into '/private/var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l/third_party/gflags'...
     Cloning into '/private/var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l/third_party/googleapis'...
     Cloning into '/private/var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l/third_party/googletest'...
     Cloning into '/private/var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l/third_party/libuv'...
     Cloning into '/private/var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l/third_party/protobuf'...
     Cloning into '/private/var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l/third_party/protoc-gen-validate'...
     Cloning into '/private/var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l/third_party/udpa'...
     Cloning into '/private/var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l/third_party/zlib'...
     Cloning into '/private/var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l/third_party/cares/cares'...
     Submodule path 'third_party/abseil-cpp': checked out 'b832dce8489ef7b6231384909fd9b68d5a5ff2b7'
     Submodule path 'third_party/benchmark': checked out '090faecb454fbd6e6e17a75ef8146acb037118d4'
     Submodule path 'third_party/bloaty': checked out '73594cde8c9a52a102c4341c244c833aa61b9c06'
     Submodule 'third_party/googletest' (https://github.com/google/googletest.git) registered for path 'third_party/bloaty/third_party/googletest'
     Submodule 'third_party/libFuzzer' (https://chromium.googlesource.com/chromium/llvm-project/llvm/lib/Fuzzer) registered for path 'third_party/bloaty/third_party/libFuzzer'
     Submodule 'third_party/re2' (https://github.com/google/re2) registered for path 'third_party/bloaty/third_party/re2'
     Cloning into '/private/var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l/third_party/bloaty/third_party/googletest'...
     Cloning into '/private/var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l/third_party/bloaty/third_party/libFuzzer'...
     fatal: unable to access 'https://chromium.googlesource.com/chromium/llvm-project/llvm/lib/Fuzzer/': Failed to connect to chromium.googlesource.com port 443: Operation timed out
     fatal: clone of 'https://chromium.googlesource.com/chromium/llvm-project/llvm/lib/Fuzzer' into submodule path '/private/var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l/third_party/bloaty/third_party/libFuzzer' failed
     Failed to clone 'third_party/libFuzzer'. Retry scheduled
     Cloning into '/private/var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l/third_party/bloaty/third_party/re2'...
     Cloning into '/private/var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l/third_party/bloaty/third_party/libFuzzer'...
     fatal: unable to access 'https://chromium.googlesource.com/chromium/llvm-project/llvm/lib/Fuzzer/': Failed to connect to chromium.googlesource.com port 443: Operation timed out
     fatal: clone of 'https://chromium.googlesource.com/chromium/llvm-project/llvm/lib/Fuzzer' into submodule path '/private/var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l/third_party/bloaty/third_party/libFuzzer' failed
     Failed to clone 'third_party/libFuzzer' a second time, aborting
     Submodule path 'third_party/boringssl-with-bazel': checked out '1c2769383f027befac5b75b6cedd25daf3bf4dcf'
     Submodule path 'third_party/cares/cares': checked out 'e982924acee7f7313b4baa4ee5ec000c5e373c30'
     Submodule path 'third_party/envoy-api': checked out '0487bbb43c3e8b54c7332f74ba7344d8265774f7'
     Submodule path 'third_party/gflags': checked out '28f50e0fed19872e0fd50dd23ce2ee8cd759338e'
     Submodule 'doc' (https://github.com/gflags/gflags.git) registered for path 'third_party/gflags/doc'
     Cloning into '/private/var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l/third_party/gflags/doc'...
     Submodule path 'third_party/gflags/doc': checked out '8411df715cf522606e3b1aca386ddfc0b63d34b4'
     Submodule path 'third_party/googleapis': checked out '80ed4d0bbf65d57cc267dfc63bd2584557f11f9b'
     Submodule path 'third_party/googletest': checked out 'c9ccac7cb7345901884aabf5d1a786cfa6e2f397'
     Submodule path 'third_party/libuv': checked out '15ae750151ac9341e5945eb38f8982d59fb99201'
     Submodule path 'third_party/protobuf': checked out 'fe1790ca0df67173702f70d5646b82f48f412b99'
     Submodule 'third_party/benchmark' (https://github.com/google/benchmark.git) registered for path 'third_party/protobuf/third_party/benchmark'
     Submodule 'third_party/googletest' (https://github.com/google/googletest.git) registered for path 'third_party/protobuf/third_party/googletest'
     Cloning into '/private/var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l/third_party/protobuf/third_party/benchmark'...
     Cloning into '/private/var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l/third_party/protobuf/third_party/googletest'...
     Submodule path 'third_party/protobuf/third_party/benchmark': checked out '5b7683f49e1e9223cf9927b24f6fd3d6bd82e3f8'
     Submodule path 'third_party/protobuf/third_party/googletest': checked out '5ec7f0c4a113e2f18ac2c6cc7df51ad6afc24081'
     Submodule path 'third_party/protoc-gen-validate': checked out 'c0a080f4bea50bc087cdd8551143ee538cf3459e'
     Submodule path 'third_party/udpa': checked out 'db4b343e48c1264bb4d9ff491b059300701dc7c7'
     Submodule path 'third_party/zlib': checked out 'cacf7f1d4e3d44d871b605da3b647f07d718623f'
     Submodule path 'third_party/cares/cares': checked out 'e982924acee7f7313b4baa4ee5ec000c5e373c30'
     Failed to recurse into submodule path 'third_party/bloaty'

[!] Error installing gRPC-Core
[!] /usr/bin/git -C /var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l submodule update --init --recursive

Submodule path 'third_party/abseil-cpp': checked out 'b832dce8489ef7b6231384909fd9b68d5a5ff2b7'
Submodule path 'third_party/benchmark': checked out '090faecb454fbd6e6e17a75ef8146acb037118d4'
Submodule path 'third_party/bloaty': checked out '73594cde8c9a52a102c4341c244c833aa61b9c06'
Submodule path 'third_party/boringssl-with-bazel': checked out '1c2769383f027befac5b75b6cedd25daf3bf4dcf'
Submodule path 'third_party/cares/cares': checked out 'e982924acee7f7313b4baa4ee5ec000c5e373c30'
Submodule path 'third_party/envoy-api': checked out '0487bbb43c3e8b54c7332f74ba7344d8265774f7'
Submodule path 'third_party/gflags': checked out '28f50e0fed19872e0fd50dd23ce2ee8cd759338e'
Submodule path 'third_party/gflags/doc': checked out '8411df715cf522606e3b1aca386ddfc0b63d34b4'
Submodule path 'third_party/googleapis': checked out '80ed4d0bbf65d57cc267dfc63bd2584557f11f9b'
Submodule path 'third_party/googletest': checked out 'c9ccac7cb7345901884aabf5d1a786cfa6e2f397'
Submodule path 'third_party/libuv': checked out '15ae750151ac9341e5945eb38f8982d59fb99201'
Submodule path 'third_party/protobuf': checked out 'fe1790ca0df67173702f70d5646b82f48f412b99'
Submodule path 'third_party/protobuf/third_party/benchmark': checked out '5b7683f49e1e9223cf9927b24f6fd3d6bd82e3f8'
Submodule path 'third_party/protobuf/third_party/googletest': checked out '5ec7f0c4a113e2f18ac2c6cc7df51ad6afc24081'
Submodule path 'third_party/protoc-gen-validate': checked out 'c0a080f4bea50bc087cdd8551143ee538cf3459e'
Submodule path 'third_party/udpa': checked out 'db4b343e48c1264bb4d9ff491b059300701dc7c7'
Submodule path 'third_party/zlib': checked out 'cacf7f1d4e3d44d871b605da3b647f07d718623f'
Submodule path 'third_party/cares/cares': checked out 'e982924acee7f7313b4baa4ee5ec000c5e373c30'
Submodule 'third_party/abseil-cpp' (https://github.com/abseil/abseil-cpp.git) registered for path 'third_party/abseil-cpp'
Submodule 'third_party/benchmark' (https://github.com/google/benchmark) registered for path 'third_party/benchmark'
Submodule 'third_party/bloaty' (https://github.com/google/bloaty.git) registered for path 'third_party/bloaty'
Submodule 'third_party/boringssl-with-bazel' (https://github.com/google/boringssl.git) registered for path 'third_party/boringssl-with-bazel'
Submodule 'third_party/cares/cares' (https://github.com/c-ares/c-ares.git) registered for path 'third_party/cares/cares'
Submodule 'third_party/envoy-api' (https://github.com/envoyproxy/data-plane-api.git) registered for path 'third_party/envoy-api'
Submodule 'third_party/gflags' (https://github.com/gflags/gflags.git) registered for path 'third_party/gflags'
Submodule 'third_party/googleapis' (https://github.com/googleapis/googleapis.git) registered for path 'third_party/googleapis'
Submodule 'third_party/googletest' (https://github.com/google/googletest.git) registered for path 'third_party/googletest'
Submodule 'third_party/libuv' (https://github.com/libuv/libuv.git) registered for path 'third_party/libuv'
Submodule 'third_party/protobuf' (https://github.com/google/protobuf.git) registered for path 'third_party/protobuf'
Submodule 'third_party/protoc-gen-validate' (https://github.com/envoyproxy/protoc-gen-validate.git) registered for path 'third_party/protoc-gen-validate'
Submodule 'third_party/udpa' (https://github.com/cncf/udpa.git) registered for path 'third_party/udpa'
Submodule 'third_party/zlib' (https://github.com/madler/zlib) registered for path 'third_party/zlib'
Cloning into '/private/var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l/third_party/abseil-cpp'...
Cloning into '/private/var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l/third_party/benchmark'...
Cloning into '/private/var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l/third_party/bloaty'...
Cloning into '/private/var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l/third_party/boringssl-with-bazel'...
Cloning into '/private/var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l/third_party/cares/cares'...
fatal: unable to access 'https://github.com/c-ares/c-ares.git/': LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443 
fatal: clone of 'https://github.com/c-ares/c-ares.git' into submodule path '/private/var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l/third_party/cares/cares' failed
Failed to clone 'third_party/cares/cares'. Retry scheduled
Cloning into '/private/var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l/third_party/envoy-api'...
Cloning into '/private/var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l/third_party/gflags'...
Cloning into '/private/var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l/third_party/googleapis'...
Cloning into '/private/var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l/third_party/googletest'...
Cloning into '/private/var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l/third_party/libuv'...
Cloning into '/private/var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l/third_party/protobuf'...
Cloning into '/private/var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l/third_party/protoc-gen-validate'...
Cloning into '/private/var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l/third_party/udpa'...
Cloning into '/private/var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l/third_party/zlib'...
Cloning into '/private/var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l/third_party/cares/cares'...
Submodule 'third_party/googletest' (https://github.com/google/googletest.git) registered for path 'third_party/bloaty/third_party/googletest'
Submodule 'third_party/libFuzzer' (https://chromium.googlesource.com/chromium/llvm-project/llvm/lib/Fuzzer) registered for path 'third_party/bloaty/third_party/libFuzzer'
Submodule 'third_party/re2' (https://github.com/google/re2) registered for path 'third_party/bloaty/third_party/re2'
Cloning into '/private/var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l/third_party/bloaty/third_party/googletest'...
Cloning into '/private/var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l/third_party/bloaty/third_party/libFuzzer'...
fatal: unable to access 'https://chromium.googlesource.com/chromium/llvm-project/llvm/lib/Fuzzer/': Failed to connect to chromium.googlesource.com port 443: Operation timed out
fatal: clone of 'https://chromium.googlesource.com/chromium/llvm-project/llvm/lib/Fuzzer' into submodule path '/private/var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l/third_party/bloaty/third_party/libFuzzer' failed
Failed to clone 'third_party/libFuzzer'. Retry scheduled
Cloning into '/private/var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l/third_party/bloaty/third_party/re2'...
Cloning into '/private/var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l/third_party/bloaty/third_party/libFuzzer'...
fatal: unable to access 'https://chromium.googlesource.com/chromium/llvm-project/llvm/lib/Fuzzer/': Failed to connect to chromium.googlesource.com port 443: Operation timed out
fatal: clone of 'https://chromium.googlesource.com/chromium/llvm-project/llvm/lib/Fuzzer' into submodule path '/private/var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l/third_party/bloaty/third_party/libFuzzer' failed
Failed to clone 'third_party/libFuzzer' a second time, aborting
Submodule 'doc' (https://github.com/gflags/gflags.git) registered for path 'third_party/gflags/doc'
Cloning into '/private/var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l/third_party/gflags/doc'...
Submodule 'third_party/benchmark' (https://github.com/google/benchmark.git) registered for path 'third_party/protobuf/third_party/benchmark'
Submodule 'third_party/googletest' (https://github.com/google/googletest.git) registered for path 'third_party/protobuf/third_party/googletest'
Cloning into '/private/var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l/third_party/protobuf/third_party/benchmark'...
Cloning into '/private/var/folders/t6/1mgl_06j2274g00f5x3w2v780000gp/T/d20220306-27837-cdi47l/third_party/protobuf/third_party/googletest'...
Failed to recurse into submodule path 'third_party/bloaty'


/usr/local/Cellar/cocoapods/1.11.2_2/libexec/gems/cocoapods-1.11.2/lib/cocoapods/downloader.rb:144:in `rescue in execute_command'
/usr/local/Cellar/cocoapods/1.11.2_2/libexec/gems/cocoapods-1.11.2/lib/cocoapods/downloader.rb:141:in `execute_command'
/usr/local/Cellar/cocoapods/1.11.2_2/libexec/gems/cocoapods-downloader-1.5.1/lib/cocoapods-downloader/base.rb:166:in `block in executable'
/usr/local/Cellar/cocoapods/1.11.2_2/libexec/gems/cocoapods-downloader-1.5.1/lib/cocoapods-downloader/git.rb:154:in `target_git'
/usr/local/Cellar/cocoapods/1.11.2_2/libexec/gems/cocoapods-downloader-1.5.1/lib/cocoapods-downloader/git.rb:115:in `update_submodules'
/usr/local/Cellar/cocoapods/1.11.2_2/libexec/gems/cocoapods-downloader-1.5.1/lib/cocoapods-downloader/git.rb:102:in `block in clone'
/usr/local/Cellar/cocoapods/1.11.2_2/libexec/gems/cocoapods-1.11.2/lib/cocoapods/downloader.rb:175:in `block in ui_sub_action'
/usr/local/Cellar/cocoapods/1.11.2_2/libexec/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/Cellar/cocoapods/1.11.2_2/libexec/gems/cocoapods-1.11.2/lib/cocoapods/downloader.rb:174:in `ui_sub_action'
/usr/local/Cellar/cocoapods/1.11.2_2/libexec/gems/cocoapods-downloader-1.5.1/lib/cocoapods-downloader/git.rb:99:in `clone'
/usr/local/Cellar/cocoapods/1.11.2_2/libexec/gems/cocoapods-downloader-1.5.1/lib/cocoapods-downloader/git.rb:67:in `download!'
/usr/local/Cellar/cocoapods/1.11.2_2/libexec/gems/cocoapods-downloader-1.5.1/lib/cocoapods-downloader/base.rb:82:in `block in download'
/usr/local/Cellar/cocoapods/1.11.2_2/libexec/gems/cocoapods-1.11.2/lib/cocoapods/downloader.rb:159:in `block in ui_action'
/usr/local/Cellar/cocoapods/1.11.2_2/libexec/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/Cellar/cocoapods/1.11.2_2/libexec/gems/cocoapods-1.11.2/lib/cocoapods/downloader.rb:158:in `ui_action'
/usr/local/Cellar/cocoapods/1.11.2_2/libexec/gems/cocoapods-downloader-1.5.1/lib/cocoapods-downloader/base.rb:80:in `download'
/usr/local/Cellar/cocoapods/1.11.2_2/libexec/gems/cocoapods-1.11.2/lib/cocoapods/downloader.rb:110:in `download_source'
/usr/local/Cellar/cocoapods/1.11.2_2/libexec/gems/cocoapods-1.11.2/lib/cocoapods/downloader.rb:77:in `download_request'
/usr/local/Cellar/cocoapods/1.11.2_2/libexec/gems/cocoapods-1.11.2/lib/cocoapods/downloader/cache.rb:256:in `download'
/usr/local/Cellar/cocoapods/1.11.2_2/libexec/gems/cocoapods-1.11.2/lib/cocoapods/downloader/cache.rb:239:in `block in uncached_pod'
/usr/local/Cellar/cocoapods/1.11.2_2/libexec/gems/cocoapods-1.11.2/lib/cocoapods/downloader/cache.rb:266:in `in_tmpdir'
/usr/local/Cellar/cocoapods/1.11.2_2/libexec/gems/cocoapods-1.11.2/lib/cocoapods/downloader/cache.rb:238:in `uncached_pod'
/usr/local/Cellar/cocoapods/1.11.2_2/libexec/gems/cocoapods-1.11.2/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
/usr/local/Cellar/cocoapods/1.11.2_2/libexec/gems/cocoapods-1.11.2/lib/cocoapods/downloader.rb:42:in `download'
/usr/local/Cellar/cocoapods/1.11.2_2/libexec/gems/cocoapods-1.11.2/lib/cocoapods/installer/pod_source_installer.rb:118:in `download_source'
/usr/local/Cellar/cocoapods/1.11.2_2/libexec/gems/cocoapods-1.11.2/lib/cocoapods/installer/pod_source_installer.rb:69:in `install!'
/usr/local/Cellar/cocoapods/1.11.2_2/libexec/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:563:in `install_source_of_pod'
/usr/local/Cellar/cocoapods/1.11.2_2/libexec/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:514:in `block (2 levels) in install_pod_sources'
/usr/local/Cellar/cocoapods/1.11.2_2/libexec/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:86:in `titled_section'
/usr/local/Cellar/cocoapods/1.11.2_2/libexec/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:513:in `block in install_pod_sources'
/usr/local/Cellar/cocoapods/1.11.2_2/libexec/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:496:in `each'
/usr/local/Cellar/cocoapods/1.11.2_2/libexec/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:496:in `install_pod_sources'
/usr/local/Cellar/cocoapods/1.11.2_2/libexec/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:255:in `block in download_dependencies'
/usr/local/Cellar/cocoapods/1.11.2_2/libexec/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/Cellar/cocoapods/1.11.2_2/libexec/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:254:in `download_dependencies'
/usr/local/Cellar/cocoapods/1.11.2_2/libexec/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:162:in `install!'
/usr/local/Cellar/cocoapods/1.11.2_2/libexec/gems/cocoapods-1.11.2/lib/cocoapods/command/install.rb:52:in `run'
/usr/local/Cellar/cocoapods/1.11.2_2/libexec/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/usr/local/Cellar/cocoapods/1.11.2_2/libexec/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run'
/usr/local/Cellar/cocoapods/1.11.2_2/libexec/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
/usr/local/Cellar/cocoapods/1.11.2_2/libexec/bin/pod:23:in `load'
/usr/local/Cellar/cocoapods/1.11.2_2/libexec/bin/pod:23:in `<main>'`

```

</details>

I have already set the variables to use a mirror site the fact I'm in China. 

Please I need have help, I'm stuck for a while.

THANKS

**Comment by darshankawar** [comment]
@biad-iritie 
For `HTTP Host Availability` issue, this was fixed recently and should be available on latest master, so switch and upgrade to latest master to see the fix. https://github.com/flutter/flutter/issues/98170

Regarding `gRPC-Core` and `cloud_firestore`, check this similar issue and underlying comments and see if it helps to resolve the issue: https://github.com/FirebaseExtended/flutterfire/issues/2533
If not, please open the issue in dedicated repo.

Closing from here.

**Comment by biad-iritie** [comment]
Ok, thanks
