### ISSUE TITLE
Flutter web service worker caches error response

### ISSUE THREAD

**Issue by ikenox** [flutter/flutter#99671]
`flutter_service_worker.js` seems to cache the response even if the response is 4XX/5XX error.
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/build_system/targets/web.dart#L669

And, the service worker caches the response during the resource's hash is identical.
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/build_system/targets/web.dart#L616

As a result, the service worker still uses the cache of the error response after the error is recovered, because the target resource's hash is not changed.
Is it expected behavior? Or, should the cacheing strategy be improved?

## Steps to Reproduce

1. Request to some static resource e.g. `.js` file
1. The request failed with an error
     - In my case it is 401 Basic Authentication failure, but I think the same thing will occur in other situation e.g. CDN is down.
1. The error response is cached by flutter service worker
1. Recovered from the error
1. Request to the target resource again

**Expected results:** 

The resource file is loaded successfully

**Actual results:** 

The cached error is still returned by the service worker

**Comment by danagbemava-nc** [comment]
Hi @ikenox, thanks for reporting this. 

Can you provide a complete minimal reproducible code sample that we can use to verify this? 

Please also provide the output of `flutter doctor -v` as well. 

Thank you

**Comment by ikenox** [comment]
@danagbemava-nc 

Thank you for replying.

## reproducible code

I created a repository for it. `README.md` explains the reproducing steps. 
https://github.com/ikenox/flutter-issue-99671

## flutter doctor -v

```
[✓] Flutter (Channel stable, 2.10.3, on macOS 11.6 20G165 darwin-x64, locale ja-IS)
    • Flutter version 2.10.3 at /usr/local/Caskroom/flutter/2.10.3/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (5 days ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/naoto.ikeno/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[!] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.4)
    • IntelliJ at /Users/naoto.ikeno/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-1/212.5712.43/IntelliJ IDEA.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 99.0.4844.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

**Comment by danagbemava-nc** [comment]
Issue is reproducible on `stable` and `master` using the sample and steps in https://github.com/ikenox/flutter-issue-99671

Repo attached below for easy access.

<details>
<summary>screenshots</summary>

### This screenshot was taken after about 5 refreshes

<img width="1440" alt="Screenshot 2022-03-08 at 07 08 39" src="https://user-images.githubusercontent.com/88313112/157186045-f648ca6e-199b-4f4a-8928-07c127f6d991.png">


### This was taken after clearing the browser cache

<img width="1440" alt="Screenshot 2022-03-08 at 07 21 02" src="https://user-images.githubusercontent.com/88313112/157186969-cf520cc2-6491-4904-bac9-8274aabf6a73.png">

</details>

<details>
<summary>logs from poetry run uvicorn server:app</summary>

`Without clearing browser cache`

```
INFO:     Started server process [88078]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     127.0.0.1:49298 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:49298 - "GET /flutter_service_worker.js?v=3444730724 HTTP/1.1" 200 OK
INFO:     127.0.0.1:49300 - "GET /favicon.png HTTP/1.1" 200 OK
INFO:     127.0.0.1:49298 - "GET /main.dart.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:49302 - "GET /index.html HTTP/1.1" 200 OK
INFO:     127.0.0.1:49300 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:49302 - "GET /assets/AssetManifest.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:49300 - "GET /assets/NOTICES HTTP/1.1" 200 OK
INFO:     127.0.0.1:49302 - "GET /assets/FontManifest.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:49298 - "GET /assets/FontManifest.json HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:49298 - "GET /assets/fonts/MaterialIcons-Regular.otf HTTP/1.1" 500 Internal Server Error
INFO:     127.0.0.1:49300 - "GET /assets/packages/cupertino_icons/assets/CupertinoIcons.ttf HTTP/1.1" 200 OK
INFO:     127.0.0.1:49308 - "GET /manifest.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:49360 - "GET / HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:49360 - "GET /assets/fonts/MaterialIcons-Regular.otf HTTP/1.1" 500 Internal Server Error
INFO:     127.0.0.1:49360 - "GET /flutter_service_worker.js?v=3444730724 HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:49421 - "GET / HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:49421 - "GET /flutter_service_worker.js?v=3444730724 HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:49421 - "GET / HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:49421 - "GET /flutter_service_worker.js?v=3444730724 HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:49421 - "GET / HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:49421 - "GET /flutter_service_worker.js?v=3444730724 HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:49421 - "GET / HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:49421 - "GET /flutter_service_worker.js?v=3444730724 HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:49511 - "GET / HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:49511 - "GET /flutter_service_worker.js?v=3444730724 HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:49511 - "GET / HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:49511 - "GET /flutter_service_worker.js?v=3444730724 HTTP/1.1" 304 Not Modified
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [88078]
```

`clearing browser cache after about page 3 reloads`

```
INFO:     Started server process [88929]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     127.0.0.1:55258 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:55258 - "GET /flutter_service_worker.js?v=238104097 HTTP/1.1" 200 OK
INFO:     127.0.0.1:55258 - "GET /favicon.png HTTP/1.1" 200 OK
INFO:     127.0.0.1:55264 - "GET /manifest.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:55259 - "GET /main.dart.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:55266 - "GET /index.html HTTP/1.1" 200 OK
INFO:     127.0.0.1:55268 - "GET /icons/Icon-192.png HTTP/1.1" 200 OK
INFO:     127.0.0.1:55258 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:55268 - "GET /assets/NOTICES HTTP/1.1" 200 OK
INFO:     127.0.0.1:55258 - "GET /assets/AssetManifest.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:55258 - "GET /assets/FontManifest.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:55259 - "GET /assets/fonts/MaterialIcons-Regular.otf HTTP/1.1" 500 Internal Server Error
INFO:     127.0.0.1:55268 - "GET /assets/packages/cupertino_icons/assets/CupertinoIcons.ttf HTTP/1.1" 200 OK
INFO:     127.0.0.1:55298 - "GET / HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:55298 - "GET /assets/fonts/MaterialIcons-Regular.otf HTTP/1.1" 500 Internal Server Error
INFO:     127.0.0.1:55298 - "GET /flutter_service_worker.js?v=238104097 HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:55298 - "GET / HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:55298 - "GET / HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:55298 - "GET /flutter_service_worker.js?v=238104097 HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:55298 - "GET /flutter_service_worker.js?v=238104097 HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:55395 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:55395 - "GET /favicon.png HTTP/1.1" 200 OK
INFO:     127.0.0.1:55404 - "GET /manifest.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:55396 - "GET /flutter_service_worker.js?v=238104097 HTTP/1.1" 200 OK
INFO:     127.0.0.1:55396 - "GET /icons/Icon-192.png HTTP/1.1" 200 OK
INFO:     127.0.0.1:55395 - "GET /main.dart.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:55406 - "GET /index.html HTTP/1.1" 200 OK
INFO:     127.0.0.1:55396 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:55396 - "GET /assets/NOTICES HTTP/1.1" 200 OK
INFO:     127.0.0.1:55406 - "GET /assets/AssetManifest.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:55406 - "GET /assets/FontManifest.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:55395 - "GET /assets/fonts/MaterialIcons-Regular.otf HTTP/1.1" 200 OK
INFO:     127.0.0.1:55396 - "GET /assets/packages/cupertino_icons/assets/CupertinoIcons.ttf HTTP/1.1" 200 OK
^CINFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [88929]
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.2.1 21D62 darwin-arm, locale en-GB)
    • Flutter version 2.10.3 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (6 days ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us
      know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1426:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1861:10)
      #15     runZonedGuarded (dart:async/zone.dart:1849:12)
      #16     runZoned (dart:async/zone.dart:1780:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:205:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:309:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure>
      (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure>
      (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.65.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.2.1 21D62 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 99.0.4844.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

```
[✓] Flutter (Channel master, 2.11.0-0.0.pre.818, on macOS 12.2.1 21D62 darwin-arm, locale en-GB)
    • Flutter version 2.11.0-0.0.pre.818 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b5d3c43280 (3 hours ago), 2022-03-07 19:57:36 -0800
    • Engine revision 0fed94d050
    • Dart version 2.17.0 (build 2.17.0-182.0.dev)
    • DevTools version 2.11.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 213.5744.122

[✓] VS Code (version 1.65.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.2.1 21D62 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 99.0.4844.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

[flutter-issue-99671.zip](https://github.com/flutter/flutter/files/8203567/flutter-issue-99671.zip)

**Comment by shreykinshu** [comment]
I am a beginner plss tell me how to start with this

**Comment by danagbemava-nc** [comment]
Hi @shreykinshu, kindly see our [contributor guide](https://github.com/flutter/flutter/blob/master/CONTRIBUTING.md) on how to get started. There's a nice video tutorial on there that you can watch to get started. You may also want to join the discord channel, (the link can be found on [this wiki page](https://github.com/flutter/flutter/wiki/Chat)) so that you can ask for help if you're stuck.

**Comment by dacianf** [comment]
Hey there,

I'm a new contributor here and I just started working on this issue.
