### ISSUE TITLE
[tool_crash] RangeError: RangeError (index): Invalid value: Valid value range is empty: 0

### ISSUE THREAD

**Issue by harshrocks** [flutter/flutter#99762]
## Command
```
flutter --no-color pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
RangeError: RangeError (index): Invalid value: Valid value range is empty: 0
```
#0      _StringBase.[] (dart:core-patch/string_patch.dart:260:41)
#1      LocalizationsGenerator._isValidGetterAndMethodName (package:flutter_tools/src/localizations/gen_l10n.dart:1048:13)
#2      LocalizationsGenerator.loadResources (package:flutter_tools/src/localizations/gen_l10n.dart:1073:12)
#3      generateLocalizations (package:flutter_tools/src/localizations/gen_l10n.dart:68:9)
#4      GenerateLocalizationsTarget.build (package:flutter_tools/src/build_system/targets/localizations.dart:56:5)
#5      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:839:27)
<asynchronous suspension>
#6      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:606:16)
<asynchronous suspension>
#7      generateLocalizationsSyntheticPackage (package:flutter_tools/src/dart/generate_synthetic_packages.dart:58:30)
<asynchronous suspension>
#8      PackagesGetCommand._runPubGet (package:flutter_tools/src/commands/packages.dart:133:7)
<asynchronous suspension>
#9      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:176:5)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1165:27)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[✓] Flutter (Channel beta, 2.11.0-0.1.pre, on Microsoft Windows [Version 10.0.19043.1526], locale en-IN)
    • Flutter version 2.11.0-0.1.pre at C:\flut\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b101bfe32f (3 weeks ago), 2022-02-16 07:36:54 -0800
    • Engine revision e355993572
    • Dart version 2.17.0 (build 2.17.0-69.2.beta)
    • DevTools version 2.10.0-dev.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\HP\AppData\Local\Android\sdk
    • Platform android-31, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.31729.503
    ✗ The current Visual Studio installation is incomplete. Please reinstall Visual Studio.

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.64.2)
    • VS Code at C:\Users\HP\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.34.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1526]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 98.0.4758.102
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 99.0.1150.30

[☠] HTTP Host Availability (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ HandshakeException: Connection terminated during handshake
    • 

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: malformed
**Version**: 1.0.0+5
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
audio_session-0.1.6+1
device_info-2.0.3
file_picker-4.2.7
firebase_core-1.10.5
firebase_core_web-1.5.2
firebase_messaging-10.0.9
firebase_messaging_web-2.2.4
flutter_local_notifications-8.2.0
flutter_plugin_android_lifecycle-2.0.5
fluttertoast-8.0.8
geocoding-2.0.1
geolocator-7.7.1
geolocator_android-2.1.0
geolocator_apple-1.2.2
geolocator_web-2.0.6
google_maps_flutter-2.1.1
image_picker-0.8.4+4
image_picker_for_web-2.1.4
just_audio-0.7.5
just_audio_web-0.3.2
location-4.3.0
location_web-3.1.1
open_file-3.2.1
path_provider-2.0.8
path_provider_android-2.0.9
path_provider_ios-2.0.7
path_provider_linux-2.1.4
path_provider_macos-2.0.4
path_provider_windows-2.0.4
permission_handler-8.3.0
record-3.0.2
record_web-0.2.1
shared_preferences-2.0.11
shared_preferences_android-2.0.9
shared_preferences_ios-2.0.8
shared_preferences_linux-2.0.3
shared_preferences_macos-2.0.2
shared_preferences_web-2.0.2
shared_preferences_windows-2.0.3
url_launcher-6.0.17
url_launcher_android-6.0.13
url_launcher_ios-6.0.13
url_launcher_linux-2.0.2
url_launcher_macos-2.0.2
url_launcher_web-2.0.5
url_launcher_windows-2.0.2

**Comment by harshrocks** [comment]
Fixed it by prepending @ to the key for .arb key.
{
"@mykey":"somevalue"
}


Author -- https://github.com/Stinox22
