### ISSUE TITLE
java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by Kingbrow** [flutter/flutter#99789]
## What happened

(please describe what you were doing when this exception occurred)

I wrote this command below :)

```dart
  const int printableCharsStartIndex = 32;
  const int charLength = 1114111 - printableCharsStartIndex;
  final List<int> charCodes = List.generate(charLength, (index) => index+printableCharsStartIndex);
  final String chars = String.fromCharCodes(charCodes);
  print(chars.split(''));
  FlutterClipboard.copy(chars.split('').toString()).then((value) {
  print('DONE !');
  });
```

## Version information

Android Studio `Bumblebee | 2021.1.1 Patch 1` • Flutter plugin `io.flutter 64.1.2` • Dart plugin `211.7798`

Error getting Flutter sdk information.

## Exception

null

```
java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor62.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.execution.process.ProcessHandler$2.invoke(ProcessHandler.java:246)
	at com.sun.proxy.$Proxy34.onTextAvailable(Unknown Source)
	at com.intellij.execution.process.ProcessHandler.notifyTextAvailable(ProcessHandler.java:220)
	at com.intellij.execution.process.ColoredProcessHandler.coloredTextAvailable(ColoredProcessHandler.java:63)
	at io.flutter.utils.MostlySilentColoredProcessHandler.coloredTextAvailable(MostlySilentColoredProcessHandler.java:77)
	at com.intellij.execution.process.AnsiEscapeDecoder.processTextChunk(AnsiEscapeDecoder.java:100)
	at com.intellij.execution.process.AnsiEscapeDecoder.escapeText(AnsiEscapeDecoder.java:64)
	at com.intellij.execution.process.ColoredProcessHandler.notifyTextAvailable(ColoredProcessHandler.java:52)
	at com.intellij.execution.process.BaseOSProcessHandler$SimpleOutputReader.onTextAvailable(BaseOSProcessHandler.java:156)
	at com.intellij.util.io.BaseOutputReader.sendText(BaseOutputReader.java:206)
	at com.intellij.util.io.BaseOutputReader.processInput(BaseOutputReader.java:190)
	at com.intellij.util.io.BaseOutputReader.readAvailableBlocking(BaseOutputReader.java:137)
	at com.intellij.util.io.BaseDataReader.readAvailable(BaseDataReader.java:68)
	at com.intellij.util.io.BaseDataReader.doRun(BaseDataReader.java:158)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.io.BaseDataReader.lambda$start$0(BaseDataReader.java:51)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.OutOfMemoryError: Java heap space
```

__Originally posted by @MAlazhariy in https://github.com/flutter/flutter-intellij/issues/6032__

**Comment by Kingbrow** [comment]
> ## What happened
> 
> 
> 
> (please describe what you were doing when this exception occurred)
> 
> 
> 
> I wrote this command below :)
> 
>                           const int printableCharsStartIndex = 32;
> 
>                           const int charLength = 1114111 - printableCharsStartIndex;
> 
>                           final List<int> charCodes = List.generate(charLength, (index) => index+printableCharsStartIndex);
> 
>                           final String chars = String.fromCharCodes(charCodes);
> 
>                           print(chars.split(''));
> 
>                           FlutterClipboard.copy(chars.split('').toString()).then((value) {
> 
>                             print('DONE !');
> 
>                           });
> 
> 
> 
> 
> 
> ## Version information
> 
> 
> 
> Android Studio `Bumblebee | 2021.1.1 Patch 1` • Flutter plugin `io.flutter 64.1.2` • Dart plugin `211.7798`
> 
> 
> 
> Error getting Flutter sdk information.
> 
> 
> 
> ## Exception
> 
> 
> 
> null
> 
> 
> 
> ```
> 
> java.lang.reflect.InvocationTargetException
> 
> 	at jdk.internal.reflect.GeneratedMethodAccessor62.invoke(Unknown Source)
> 
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 
> 	at com.intellij.execution.process.ProcessHandler$2.invoke(ProcessHandler.java:246)
> 
> 	at com.sun.proxy.$Proxy34.onTextAvailable(Unknown Source)
> 
> 	at com.intellij.execution.process.ProcessHandler.notifyTextAvailable(ProcessHandler.java:220)
> 
> 	at com.intellij.execution.process.ColoredProcessHandler.coloredTextAvailable(ColoredProcessHandler.java:63)
> 
> 	at io.flutter.utils.MostlySilentColoredProcessHandler.coloredTextAvailable(MostlySilentColoredProcessHandler.java:77)
> 
> 	at com.intellij.execution.process.AnsiEscapeDecoder.processTextChunk(AnsiEscapeDecoder.java:100)
> 
> 	at com.intellij.execution.process.AnsiEscapeDecoder.escapeText(AnsiEscapeDecoder.java:64)
> 
> 	at com.intellij.execution.process.ColoredProcessHandler.notifyTextAvailable(ColoredProcessHandler.java:52)
> 
> 	at com.intellij.execution.process.BaseOSProcessHandler$SimpleOutputReader.onTextAvailable(BaseOSProcessHandler.java:156)
> 
> 	at com.intellij.util.io.BaseOutputReader.sendText(BaseOutputReader.java:206)
> 
> 	at com.intellij.util.io.BaseOutputReader.processInput(BaseOutputReader.java:190)
> 
> 	at com.intellij.util.io.BaseOutputReader.readAvailableBlocking(BaseOutputReader.java:137)
> 
> 	at com.intellij.util.io.BaseDataReader.readAvailable(BaseDataReader.java:68)
> 
> 	at com.intellij.util.io.BaseDataReader.doRun(BaseDataReader.java:158)
> 
> 	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
> 
> 	at com.intellij.util.io.BaseDataReader.lambda$start$0(BaseDataReader.java:51)
> 
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
> 
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 
> 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
> 
> 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
> 
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 
> 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
> 
> 	at java.base/java.lang.Thread.run(Thread.java:829)
> 
> Caused by: java.lang.OutOfMemoryError: Java heap space
> 
> ```
> 
> 
> 
> __Originally posted by @MAlazhariy in https://github.com/flutter/flutter-intellij/issues/6032__

**Comment by maheshmnj** [comment]
Hi @Kingbrow, Thanks for filing the issue. Please share a minimal and complete code sample along with the output of `flutter doctor -v` along with the complete error logs, Also note that if the exception is due to this `FlutterClipboard` then it should be filed in its dedicated repository Because it is a third party plugin.

>
>  FlutterClipboard.copy(chars.split('').toString()).then((value) {
  print('DONE !');
  });
