### ISSUE TITLE
Selecting text works only paragraph by paragraph

### ISSUE THREAD

**Issue by ThiemoImgraben** [flutter/flutter#99819]
## Use case

Selecting text works only paragraph by paragraph in the markdown widget.

## Proposal

I want to be able to select all text in the markdown widget, no matter if there are several paragraphs.

![flutter_markdown](https://user-images.githubusercontent.com/79262968/157440286-bb38e4d2-a3f1-4b60-a854-2bbe9220f915.gif)

**Comment by danagbemava-nc** [comment]
Hi @ThiemoImgraben, please provide a complete minimal reproducible code sample so that we can verify this. 

Please also provide your `flutter doctor -v` as well as the version of `flutter_markdown` you're using. 

Thank you

**Comment by ThiemoImgraben** [comment]
@danagbemava-nc - I added the required content.

**Comment by danagbemava-nc** [comment]
Hi @ThiemoImgraben, I seem to be able to select both paragraphs at once, with the sample you provided, although the text selection overlay doesn't look good. See video below

https://user-images.githubusercontent.com/88313112/158326512-1c26f16c-aae9-4e88-9cc0-01f9500fa5e0.mp4

**Comment by ThiemoImgraben** [comment]
Hi @danagbemava-nc , sorry for not describing my problem in detail. The bug occurs only on the web.

**Comment by danagbemava-nc** [comment]
Hi @ThiemoImgraben, it seems to work just fine on web for me as well, weird text selection overlay and all

https://user-images.githubusercontent.com/88313112/158532209-4d882e36-5746-427e-93d4-e41ca2e5ea4e.mov

**Comment by ThiemoImgraben** [comment]
Hey @danagbemava-nc , please take a look again.

**Comment by danagbemava-nc** [comment]
Thanks @Curvel, I can now reproduce the issue. This issue is not specific to the web and it does reproduce on mobile as well. The behavior on android is the same as the behavior on iOS.

<details>
<summary>videos</summary>

| ios | web | 
| -- | -- |
| <video src="https://user-images.githubusercontent.com/88313112/159249551-eda9200a-0581-4111-b4c8-b532073163ac.mov" /> | <video src="https://user-images.githubusercontent.com/88313112/159249563-33784d30-5fea-42bc-80c7-9c114d8cb75c.mov" />

</details>


<details>
<summary>complete sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_markdown/flutter_markdown.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    var text = '''
Lorem ipsum dolor sit amet, 
consectetur adipiscing elit, 
sed do eiusmod tempor incididunt 
ut labore et dolore magna aliqua. 
            
Ut enim ad minim veniam, 
quis nostrud exercitation ullamco 
laboris nisi ut aliquip ex ea 
commodo consequat.
            ''';

    return Scaffold(
      body: Center(
        child: MarkdownBody(
          data: text,
          selectable: true,
        ),
      ),
    );
  }
}

```
</details>

<details>
<summary>flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.2.1 21D62 darwin-arm, locale en-GB)
    • Flutter version 2.10.3 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (3 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1426:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1861:10)
      #15     runZonedGuarded (dart:async/zone.dart:1849:12)
      #16     runZoned (dart:async/zone.dart:1780:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:205:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:309:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.2.1 21D62 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 99.0.4844.74

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

```
[✓] Flutter (Channel master, 2.13.0-0.0.pre.166, on macOS 12.2.1 21D62 darwin-arm, locale en-GB)
    • Flutter version 2.13.0-0.0.pre.166 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6af40a7004 (35 hours ago), 2022-03-19 19:15:23 -0400
    • Engine revision 900e3c0917
    • Dart version 2.17.0 (build 2.17.0-222.0.dev)
    • DevTools version 2.11.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 213.5744.122

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.2.1 21D62 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 99.0.4844.74

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by idealclover** [comment]
Any updates here~?

**Comment by idealclover** [comment]
flutter 3.3 supports SelectionArea, which maybe can fix this issue

**Comment by ArthurREGNARD** [comment]
Any updates ?

**Comment by Abid-Hasan** [comment]
Any updates?

**Comment by lff5** [comment]
Any updates?

**Comment by muthuspark** [comment]
Any updates?

**Comment by kokihoon** [comment]
Any updates?

**Comment by wl1395182472** [comment]
flutter_markdown uses many single widget to draw this markdown , maybe it causes this
solve this maybe change its underlying logic , so it upgrades so slow?

also , i found that selection is sense of cleavage one by one on whole widget

**Comment by adrianjagielak** [comment]
As a workaround I've created a flutter_markdown package fork with necessary changes allowing markdown widgets to be wrapped in `SelectionArea`: https://pub.dev/packages/flutter_markdown_selectionarea

To use it just replace flutter_markdown dependency in your pubspec.yaml with
```yaml
flutter_markdown_selectionarea: ^0.6.14+2
```
and then change all imports from
```dart
import 'package:flutter_markdown/flutter_markdown.dart';
```
to
```dart
import 'package:flutter_markdown_selectionarea/flutter_markdown.dart';
```
and then you will be able to make multiple paragraphs selectable by using `SelectionArea` widget:
```dart
SelectionArea(
  child: MarkdownBody(data: text),
)
```

Related issue: [Support selecting text using SelectionArea #107073](https://github.com/flutter/flutter/issues/107073)

**Comment by evannorstrand-mp** [comment]
@adrianjagielak - have you submitted an MR/PR to fix the issue in the original package?

**Comment by wjkoh** [comment]
It can be quite challenging to select text on iOS Safari. As shown in the screenshot below, when attempting to select text, two selections appear - one attributed to Flutter and the other to iOS. This interruption can make it difficult for users to accurately select the desired text.

![IMG_1935](https://github.com/flutter/flutter/assets/1053445/7fa3573b-6b27-4e84-9674-06d9818bf39e)

**Comment by MonolithFoundation** [comment]
The markdown widget are so basic, but I can really hardly make flutter's markdown to work.

@flutter can flutter team please watch this issue and make it higher priority?

Markdown is so foundamental before you spread flutter you need at least beat reactjs

**Comment by Justus-M** [comment]
Same issue here on web and desktop. within hours of releasing an update that uses flutter_markdown, I received a customer complaint that they cannot select the text.

<img width="660" alt="Screenshot 2024-05-06 at 10 46 47" src="https://github.com/flutter/flutter/assets/37046316/866403be-8cb3-4fbd-8f93-6f728593d213">

**Comment by Shashankocean** [comment]
Just wrap the **MarkdownBody** widget inside **SelectionArea** widget.

```
SelectionArea(
      child: MarkdownBody(
          data: message['ai_response'],
          styleSheet: MarkdownStyleSheet(
              code: GoogleFonts.getFont('Fira Code'),
              tableBorder:
                  TableBorder.all(color: primaryColor, width: 0),
              tableColumnWidth: IntrinsicColumnWidth(),
              tableCellsPadding:
                  EdgeInsets.only(bottom: 10, left: 10),
              tableHeadAlign: TextAlign.start)),
    ),
```

**Comment by bryantwilliam** [comment]
I found work arounds for the following issues:

# Including new lines when selecting and copy/pasting
```Dart
SelectionArea(
  // SelectionTransformer.separated allows for new lines to be copied and
  // pasted.
  child: SelectionTransformer.separated(
    child: Markdown(data: data),
  ),
);
```

`SelectionTransformer`: https://gist.github.com/bryantwilliam/62a2b4cbd390a0e62612b3ea85c7f5e9

# Double new lines in the markdown
```Dart
/// Using \u200B from https://stackoverflow.com/a/76543385, this allows for
/// double new lines to be shown in the markdown.
String _replaceNewlines(String input) {
  final codeBlockPattern = RegExp(r'(```[\s\S]*?```)', multiLine: true);
  final matches = codeBlockPattern.allMatches(input);
  int lastMatchEnd = 0;
  final buffer = StringBuffer();

  for (final match in matches) {
    buffer.write(input
        .substring(lastMatchEnd, match.start)
        .replaceAll('\n\n', '\n\u200B\n'));
    buffer.write(match.group(0));
    lastMatchEnd = match.end;
  }

  buffer
      .write(input.substring(lastMatchEnd).replaceAll('\n\n', '\n\u200B\n'));
  return buffer.toString();
}

SelectionArea(
  // SelectionTransformer.separated allows for new lines to be copied and
  // pasted.
  child: SelectionTransformer.separated(
    child: Markdown(data: _replaceNewlines(data)),
  ),
);
```

Also waiting for https://github.com/flutter/flutter/pull/155481

**Comment by bryantwilliam** [comment]
I found another discovery.
`\n` by itself doesn't work inside the markdown widget unless there are 2 spaces before it like `  \n`.

Here's my fix...

## Before:
![image](https://github.com/user-attachments/assets/099c91da-d326-44a8-8aa6-8a9059ebbbab)
`data: "Testing123 test123\nTesting123 test123  \nTesting123 test123\n\nTesting123 test123  \n\nTesting123 test123\n\n\nTesting123  \n\n\nTesting123 test123"`

## After:
![image](https://github.com/user-attachments/assets/ba6f157a-39bf-483c-ad42-433641c05846)

`data: _fixMarkdownSingleNewLines("Testing123 test123\nTesting123 test123  \nTesting123 test123\n\nTesting123 test123  \n\nTesting123 test123\n\n\nTesting123  \n\n\nTesting123 test123")`

```Dart
  String _fixMarkdownSingleNewLines(String data) {
    final codeBlockPattern =
        RegExp(r'```.*?```', dotAll: true); // Matches code blocks
    final nonCodeBlocks = <String>[];
    final codeBlocks = <String>[];

    // Split data into segments of code blocks and non-code blocks
    final matches = codeBlockPattern.allMatches(data);
    int lastMatchEnd = 0;

    for (final match in matches) {
      // Add text before the code block as a non-code block
      if (match.start > lastMatchEnd) {
        nonCodeBlocks.add(data.substring(lastMatchEnd, match.start));
      }
      // Add the code block itself
      codeBlocks.add(data.substring(match.start, match.end));
      lastMatchEnd = match.end;
    }

    // Add any remaining non-code block text
    if (lastMatchEnd < data.length) {
      nonCodeBlocks.add(data.substring(lastMatchEnd));
    }

    // Process non-code blocks: Replace `\n` with `  \n`
    final processedNonCodeBlocks = nonCodeBlocks.map((block) {
      return block.replaceAll('\n', '  \n');
    }).toList();

    // Combine processed non-code blocks and code blocks back together
    final buffer = StringBuffer();
    int codeIndex = 0, nonCodeIndex = 0;

    for (final _ in matches) {
      if (nonCodeIndex < processedNonCodeBlocks.length) {
        buffer.write(processedNonCodeBlocks[nonCodeIndex++]);
      }
      if (codeIndex < codeBlocks.length) {
        buffer.write(codeBlocks[codeIndex++]);
      }
    }

    // Add any remaining non-code block
    if (nonCodeIndex < processedNonCodeBlocks.length) {
      buffer.write(processedNonCodeBlocks[nonCodeIndex]);
    }

    return buffer.toString();
  }
```

**Comment by bryantwilliam** [comment]
For anyone who runs into this issue in the future. Using `SelectionTransformer` like I explained in my previous comment, in combination with this temporary fix here https://github.com/flutter/flutter/issues/160292 for another `\n` issue, makes markdown behave perfectly for selecting multiple lines of text.

`"Testing123 test123\nTesting123 test123  \nTesting123 test123\n\nTesting123 test123  \n\nTesting123 test123\n\n\nTesting123  \n\n\nTesting123 test123"`
![image](https://github.com/user-attachments/assets/9b431b70-846b-4109-b5eb-ecf70a9841a4)
Gets pasted as:
```
Testing123 test123
Testing123 test123
Testing123 test123

Testing123 test123

Testing123 test123

Testing123

Testing123 test123
```
