### ISSUE TITLE
[tool_crash] RPCError

### ISSUE THREAD

**Issue by sp-saurabhinfosys** [flutter/flutter#99810]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=chrome --start-paused --dart-define=flutter.inspector.structuredErrors=true --devtools-server-address=http://127.0.0.1:9100 lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
RPCError
```
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1718:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2225:21)
#2      VmService.getIsolate (package:vm_service/src/vm_service.dart:1958:7)
#3      FlutterVmService.getIsolateOrNull (package:flutter_tools/src/vmservice.dart:903:20)
#4      FlutterVmService.findExtensionIsolate (package:flutter_tools/src/vmservice.dart:868:51)
<asynchronous suspension>
#5      FlutterResidentDevtoolsHandler._waitForExtensionsForDevice (package:flutter_tools/src/resident_devtools_handler.dart:181:7)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:473:21)
<asynchronous suspension>
#7      FlutterResidentDevtoolsHandler._devicesWithExtensions (package:flutter_tools/src/resident_devtools_handler.dart:171:41)
<asynchronous suspension>
#8      FlutterResidentDevtoolsHandler.hotRestart (package:flutter_tools/src/resident_devtools_handler.dart:248:54)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.10.2, on Microsoft Windows [Version 10.0.19044.1526], locale en-US)
    • Flutter version 2.10.2 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (3 weeks ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\SI 04\AppData\Local\Android\sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 99.0.4844.51
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 99.0.1150.30

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 8962f6dc68ec8e2206ac2fa874da4a453856c7d3
### Plugins
cloud_firestore-3.1.10
cloud_firestore_web-2.6.10
devicelocale-0.5.0
firebase_auth-3.3.9
firebase_auth_web-3.3.9
firebase_core-1.13.1
firebase_core_web-1.6.1
firebase_storage-10.2.9
firebase_storage_web-3.2.10
flutter_plugin_android_lifecycle-2.0.5
google_maps_flutter-2.1.2
google_maps_flutter_web-0.3.2+1
image_picker-0.8.4+10
image_picker_for_web-2.1.6
image_picker_web-2.1.0
path_provider-2.0.9
path_provider_android-2.0.12
path_provider_ios-2.0.8
path_provider_linux-2.1.5
path_provider_macos-2.0.5
path_provider_windows-2.0.5
shared_preferences-2.0.13
shared_preferences_android-2.0.11
shared_preferences_ios-2.1.0
shared_preferences_linux-2.1.0
shared_preferences_macos-2.0.3
shared_preferences_web-2.0.3
shared_preferences_windows-2.1.0
sqflite-2.0.2
stripe_android-2.3.0
stripe_ios-2.3.0
url_launcher-6.0.20
url_launcher_android-6.0.15
url_launcher_ios-6.0.15
url_launcher_linux-3.0.0
url_launcher_macos-3.0.0
url_launcher_web-2.0.9
url_launcher_windows-3.0.0

**Comment by danagbemava-nc** [comment]
Hi @sp-saurabhinfosys, can you tell us what you were doing when you run into this issue?

**Comment by sp-saurabhinfosys** [comment]
i was just running my web app and just refreshing it.

**Comment by danagbemava-nc** [comment]
Hi @sp-saurabhinfosys, does this crash occur frequently for you?
