### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'trim') happens after reload

### ISSUE THREAD

**Issue by siva2204** [flutter/flutter#99893]
## Steps to Reproduce

i'm working on flutter web, everything works fine on initial load and on subsequent reloads, type error is poping up in my console and this freezes my app

1. run `flutter build web`, host it some where
2. open the site and reload again

**Expected results:** 
app shouldn't throw exception on second reload 
**Actual results:** 
it should work similar to first reload
<details>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
Exception: TypeError: Instance of 'minified:y9': type 'minified:y9' is not a subtype of type 'minified:o0'
main.dart.js:32469     at Object.c (https://dalal.pragyan.org/web/main.dart.js:4423:3)
main.dart.js:32469     at Object.bgP (https://dalal.pragyan.org/web/main.dart.js:5053:18)
main.dart.js:32469     at n6.bHy [as a] (https://dalal.pragyan.org/web/main.dart.js:5048:3)
main.dart.js:32469     at n6.bHO (https://dalal.pragyan.org/web/main.dart.js:5020:10)
main.dart.js:32469     at b_L.$2 (https://dalal.pragyan.org/web/main.dart.js:61727:20)
main.dart.js:32469     at Na.UV (https://dalal.pragyan.org/web/main.dart.js:101776:80)
main.dart.js:32469     at $async$Ov (https://dalal.pragyan.org/web/main.dart.js:101751:29)
main.dart.js:32469     at https://dalal.pragyan.org/web/main.dart.js:48117:23
main.dart.js:32469     at eu.q (https://dalal.pragyan.org/web/main.dart.js:48118:6)
main.dart.js:32469     at Object.bc9 (https://dalal.pragyan.org/web/main.dart.js:7010:17)
```

```
main.dart.js:8259 Uncaught TypeError: Cannot read properties of null (reading 'trim')
    at Interceptor.trim$0 (main.dart.js:83676:27)
    at ClientCall__sanitizeMetadata_closure.call$2 (main.dart.js:194598:78)
    at ConstantStringMap.forEach$1 (main.dart.js:85067:11)
    at Object.ClientCall__sanitizeMetadata (main.dart.js:48821:16)
    at ClientCall.onConnectionReady$1 (main.dart.js:194295:44)
    at ClientChannelBase_createCall_closure.call$1 (main.dart.js:194681:10)
    at Object._rootRunUnary (main.dart.js:11439:18)
    at StaticClosure.<anonymous> (main.dart.js:213862:16)
    at _CustomZone.runUnary$2$2 (main.dart.js:89014:39)
    at _Future__propagateToListeners_handleValueCallback.call$0 (main.dart.js:87294:51)
wrapException @ main.dart.js:8259
Error__throw @ main.dart.js:13546
call$0 @ main.dart.js:89148
_microtaskLoop @ main.dart.js:11189
_startMicrotaskLoop @ main.dart.js:11195
call$1 @ main.dart.js:86199
invokeClosure @ main.dart.js:8462
(anonymous) @ main.dart.js:8481
childList (async)
call$1 @ main.dart.js:86209
_scheduleAsyncCallback @ main.dart.js:11209
_rootScheduleMicrotask @ main.dart.js:11482
scheduleMicrotask$1 @ main.dart.js:89048
_asyncCompleteWithValue$1 @ main.dart.js:87169
_asyncComplete$1 @ main.dart.js:87165
complete$1 @ main.dart.js:86285
_asyncReturn @ main.dart.js:10821
(anonymous) @ main.dart.js:57105
(anonymous) @ main.dart.js:10849
call$2 @ main.dart.js:86316
_asyncStartSync @ main.dart.js:10813
loadFontIfNecessary$body @ main.dart.js:57111
loadFontIfNecessary @ main.dart.js:57008
GoogleFonts_inter @ main.dart.js:48774
(anonymous) @ main.dart.js:223795
holder.<computed> @ main.dart.js:145
build$1 @ main.dart.js:114565
build$0 @ main.dart.js:175583
performRebuild$0 @ main.dart.js:175523
performRebuild$0 @ main.dart.js:175613
rebuild$0 @ main.dart.js:175446
_firstBuild$0 @ main.dart.js:175518
_firstBuild$0 @ main.dart.js:175605
mount$2 @ main.dart.js:175515
inflateWidget$2 @ main.dart.js:175274
updateChild$3 @ main.dart.js:175195
performRebuild$0 @ main.dart.js:175535
performRebuild$0 @ main.dart.js:208867
rebuild$0 @ main.dart.js:175446
_firstBuild$0 @ main.dart.js:175518
mount$2 @ main.dart.js:175515
mount$2 @ main.dart.js:208798
inflateWidget$2 @ main.dart.js:175274
updateChild$3 @ main.dart.js:175195
performRebuild$0 @ main.dart.js:175535
rebuild$0 @ main.dart.js:175446
_firstBuild$0 @ main.dart.js:175518
mount$2 @ main.dart.js:175515
mount$2 @ main.dart.js:204756
inflateWidget$2 @ main.dart.js:175274
updateChild$3 @ main.dart.js:175195
performRebuild$0 @ main.dart.js:175535
rebuild$0 @ main.dart.js:175446
_firstBuild$0 @ main.dart.js:175518
mount$2 @ main.dart.js:175515
mount$2 @ main.dart.js:204756
inflateWidget$2 @ main.dart.js:175274
updateChild$3 @ main.dart.js:175195
_rebuild$0 @ main.dart.js:170294
call$0 @ main.dart.js:170256
buildScope$2 @ main.dart.js:175007
attachToRenderTree$2 @ main.dart.js:170229
call$0 @ main.dart.js:170205
_rootRun @ main.dart.js:11425
(anonymous) @ main.dart.js:213859
run$1$1 @ main.dart.js:89009
runGuarded$1 @ main.dart.js:88945
call$0 @ main.dart.js:89130
_rootRun @ main.dart.js:11429
(anonymous) @ main.dart.js:213859
run$1$1 @ main.dart.js:89009
call$0 @ main.dart.js:89113
call$0 @ main.dart.js:86259
invokeClosure @ main.dart.js:8460
(anonymous) @ main.dart.js:8481
setTimeout (async)
_TimerImpl$2 @ main.dart.js:86228
_TimerImpl$ @ main.dart.js:10801
Timer__createTimer @ main.dart.js:10793
_rootCreateTimer @ main.dart.js:11485
createTimer$2 @ main.dart.js:89053
Timer_Timer @ main.dart.js:11401
scheduleAttachRootWidget$1 @ main.dart.js:169974
call$0 @ main.dart.js:114540
_rootRun @ main.dart.js:11429
(anonymous) @ main.dart.js:213859
run$1$1 @ main.dart.js:89009
_runZoned @ main.dart.js:11546
runZoned @ main.dart.js:11523
_ @ main.dart.js:213894
call$0 @ main.dart.js:197296
_rootRun @ main.dart.js:11429
(anonymous) @ main.dart.js:213859
run$1$1 @ main.dart.js:89009
_runZoned @ main.dart.js:11546
runZoned @ main.dart.js:11523
_ @ main.dart.js:213894
HydratedBlocOverrides_runZoned @ main.dart.js:49591
(anonymous) @ main.dart.js:21734
(anonymous) @ main.dart.js:10849
call$2 @ main.dart.js:86316
call$1 @ main.dart.js:86304
runUnary$2$2 @ main.dart.js:89282
call$0 @ main.dart.js:87294
_Future__propagateToListeners @ main.dart.js:11128
_completeWithValue$1 @ main.dart.js:87153
complete$1 @ main.dart.js:86291
_asyncReturn @ main.dart.js:10821
(anonymous) @ main.dart.js:211206
(anonymous) @ main.dart.js:10849
call$2 @ main.dart.js:86316
call$1 @ main.dart.js:86304
runUnary$2$2 @ main.dart.js:89282
call$0 @ main.dart.js:87294
_Future__propagateToListeners @ main.dart.js:11128
_completeWithValue$1 @ main.dart.js:87153
complete$1 @ main.dart.js:86291
_asyncReturn @ main.dart.js:10821
(anonymous) @ main.dart.js:197636
(anonymous) @ main.dart.js:10849
call$2 @ main.dart.js:86316
call$1 @ main.dart.js:86304
runUnary$2$2 @ main.dart.js:89282
call$0 @ main.dart.js:87294
_Future__propagateToListeners @ main.dart.js:11128
_completeWithValue$1 @ main.dart.js:87153
complete$1 @ main.dart.js:86291
_asyncReturn @ main.dart.js:10821
(anonymous) @ main.dart.js:196675
(anonymous) @ main.dart.js:10849
call$2 @ main.dart.js:86316
call$1 @ main.dart.js:86304
runUnary$2$2 @ main.dart.js:89282
call$0 @ main.dart.js:87294
_Future__propagateToListeners @ main.dart.js:11128
_completeWithValue$1 @ main.dart.js:87153
complete$1 @ main.dart.js:86291
_asyncReturn @ main.dart.js:10821
(anonymous) @ main.dart.js:196642
(anonymous) @ main.dart.js:10849
call$2 @ main.dart.js:86316
call$1 @ main.dart.js:86304
runUnary$2$2 @ main.dart.js:89282
call$0 @ main.dart.js:87294
_Future__propagateToListeners @ main.dart.js:11128
_completeWithValue$1 @ main.dart.js:87153
complete$1 @ main.dart.js:86291
_asyncReturn @ main.dart.js:10821
(anonymous) @ main.dart.js:195471
(anonymous) @ main.dart.js:10849
call$2 @ main.dart.js:86316
call$1 @ main.dart.js:86304
runUnary$2$2 @ main.dart.js:89282
call$0 @ main.dart.js:87294
_Future__propagateToListeners @ main.dart.js:11128
_completeWithValue$1 @ main.dart.js:87153
call$0 @ main.dart.js:87230
_microtaskLoop @ main.dart.js:11189
_startMicrotaskLoop @ main.dart.js:11195
call$1 @ main.dart.js:86199
invokeClosure @ main.dart.js:8462
(anonymous) @ main.dart.js:8481
childList (async)
call$1 @ main.dart.js:86209
_scheduleAsyncCallback @ main.dart.js:11209
_rootScheduleMicrotask @ main.dart.js:11482
scheduleMicrotask$1 @ main.dart.js:89303
_asyncCompleteWithValue$1 @ main.dart.js:87169
_asyncComplete$1 @ main.dart.js:87165
complete$1 @ main.dart.js:86952
call$1 @ main.dart.js:195560
call$1 @ main.dart.js:97656
invokeClosure @ main.dart.js:8462
(anonymous) @ main.dart.js:8481
Show 130 more frames
```

**Comment by danagbemava-nc** [comment]
Hi @siva2204 

Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Thank you

**Comment by siva2204** [comment]
thanks for your reply, its our implementation mistake, or its related to the pkg we're using, closing this issue
