### ISSUE TITLE
How do I use emulator using VS code

### ISSUE THREAD

**Issue by makinzm** [flutter/flutter#99892]
# My Enviroment

- MacOS : version 11.6.4
- VScode : version 1.65.0
- JAVA_HOME : "/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home"
- java version "1.8.0_221"
- Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
- Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)

## Steps to Reproduce

1. ``flutter devices``

```
# $ sdkmanager "system-images;android-32;google_apis_playstore;x86_64"
avdmanager create avd -n test -k "system-images;android-32;google_apis_playstore;x86_64"
# $ avdmanager create avd -n test -k "system-images;android-32;google_apis_playstore;x86_64"

$ flutter devices
3 connected devices:

sdk gphone64 x86 64 (mobile)         • emulator-5554                        •
android-x64    • Android 12 (API 32) (emulator)
iPod touch (7th generation) (mobile) • **** • ios
• com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
Chrome (web)                         • chrome                               •
web-javascript • Google Chrome ****
```
2. ``flutter run -d sdk\ gphone64\ x86\ 64``

I can run ``$ flutter run -d iPod\ touch`` but
```
$ flutter run -d sdk\ gphone64\ x86\ 64
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> Failed to query the value of task ':app:compileDebugKotlin' property 'compilerRunner$kotlin_gradle_plugin'.
   > Kotlin could not find the required JDK tools in the Java installation. Make sure Kotlin compilation is running on a JDK, not JRE.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11m 34s
```
How do I solve this failure?

I would appreciate it if you would teach me.

**Comment by danagbemava-nc** [comment]
Hi @makinzm, kindly check out this StackOverflow thread to see if you find a solution. 

https://stackoverflow.com/questions/55286542/kotlin-could-not-find-the-required-jdk-tools-in-the-java-installation

**Comment by makinzm** [comment]
@danagbemava-nc 

Thank you for your teaching me.

However, I become to not use ``sdkmanager`` command because I have to change ``JAVA_HOME="/Applications/Android Studio.app/Contents/jre/Contents/Home"`` :

```
$ sdkmanager
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more
```

Therefore, I have to change ``$JAVA_HOME`` every time I want to use ``sdkmanager`` . Is it ok...?

Anyway, I try ``flutter run -d sdk\ gphone64\ x86\ 64 `` now and succeed it after coding these lines:

```
$ cd /Library/Internet\ Plug-Ins/
$ sudo mv JavaAppletPlugin.plugin DELETED-JavaAppletPlugin.plugin
$ cd /Library/PreferencePanes/
$ sudo mv JavaControlPanel.prefPane DELETED-JavaControlPanel.prefPane

## delete this in .bash_profile
## delete this
#
# export JAVA_HOME="/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home"
# PATH=${JAVA_HOME}/bin:${PATH}
#
## add this
#
# export JAVA_HOME="/Applications/Android Studio.app/Contents/jre/Contents/Home"
# export PATH=$JAVA_HOME/bin:$PATH
#
# -> back

$ rm -rf ~/.gradle
$ flutter run -d sdk\ gphone64\ x86\ 64 
```


Thank you.

**Comment by danagbemava-nc** [comment]
> Therefore, I have to change $JAVA_HOME every time I want to use sdkmanager . Is it ok...?

I do not think that will be necessary. How did you install sdkmanager? Can you also provide the output of `flutter doctor -v`?

**Comment by makinzm** [comment]
This is a result:

```
$ flutter doctor -v
[✓] Flutter (Channel stable, 2.10.3, on macOS 11.6.4 20G417
    darwin-x64, locale ja-JP)
    • Flutter version 2.10.3 at /Users/mknzm/Applications/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (8 days ago), 2022-03-02
      11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK
    version 32.1.0-rc1)
    • Android SDK at /Users/mknzm/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google
      Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.11+0-b60-7590822)

[✓] VS Code (version 1.65.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome
      99.0.4844.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
$ which sdkmanager
/Users/HOGEHOGE/Library/Android/sdk/tools/bin/sdkmanager
$ sdkmanager -v
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more
$ which java
/Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
```

May the place be wrong?

**Comment by danagbemava-nc** [comment]
Kindly look in this thread to see if any thing in there fixes your issue. https://github.com/flutter/flutter/issues/56778

**Comment by makinzm** [comment]
Thank you for teaching me.

However, I can ``flutter doctor -v`` and `` flutter doctor --android-licenses``,
but I cannot use ``sdkmanager`` only.

So, this issue is not helpful for me, isn't it?

I couldn't find out this solution.

**Comment by danagbemava-nc** [comment]
HI @makinzm, the error message you get from running `sdkmanager` is the same error message that the users in that issue reported. 
It might not be specifically related to `flutter doctor --android-licenses` as there are others complaining about sdkmanager itself, like the user in this comment https://github.com/flutter/flutter/issues/56778#issuecomment-653635824. 

You can still try the solutions to see if they work for you
