### ISSUE TITLE
CircularProgressIndicator artefact at the bottom

### ISSUE THREAD

**Issue by ristiisa** [flutter/flutter#99916]
## Steps to Reproduce

When using CircularProgressIndicator with a small enough value (0.0001 for example in the sample below) an artefact is visible at the bottom of the widget.

![image](https://user-images.githubusercontent.com/514571/157694957-b7699a18-1391-444f-8638-b4689502fdeb.png)

https://dartpad.dev/?id=57d9c492753b53bd6cdfb2081d1f36f1
at the time of writing version in dartpad:
stable: Flutter 2.10.3 Dart SDK 2.16.1
beta: Flutter 2.11.0-0.1.pre Dart SDK 2.17.0-69.2.beta

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        backgroundColor: Colors.white,
        body: Center(child: Container(
          height: 500,
          width: 500,
          color: Colors.yellow,
          child: CircularProgressIndicator(
            color: Colors.red,
            value: 0.0001,
            strokeWidth: 25,
          )
        ))
      )
    );
  }
}
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @ristiisa, are you able to reproduce this issue outside of dartpad? If so, what platforms are you experiencing this on?

**Comment by ristiisa** [comment]
Yes, I can repro it under IOS (both physical device and simulator) with the following code:
```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        backgroundColor: Colors.white,
        body: Center(child: Transform.scale(
          scale: 16,
          child: Container(
            height: 25,
            width: 25,
            color: Colors.yellow,
            child: CircularProgressIndicator(
              color: Colors.red,
              value: 0.000001,
              strokeWidth: 5,
            )
          ),
        ))
      )
    );
  }
}
```

Unable to see the artefact under android though.

```
Flutter 2.10.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7e9793dee1 (12 days ago) • 2022-03-02 11:23:12 -0600
Engine • revision bd539267b4
Tools • Dart 2.16.1 • DevTools 2.9.2
```

**Comment by danagbemava-nc** [comment]
Issue is reproducible on `stable` and `master`. 

On iOS, macOS, and web(canvaskit), the artifact can be seen at the bottom, however, on android and web(HTML), the artefact is not seen nor is the value of the progress indicator.

On macOS and web(canvaskit), you may need to resize the window before you see the artefact. 

<details>
<summary>screenshots</summary>

| iOS | android | macOS | web(canvaskit) | web(HTML) | 
| -- | -- | -- | -- | -- |
| ![Simulator Screen Shot - iPhone 13 mini - 2022-03-15 at 06 28 41](https://user-images.githubusercontent.com/88313112/158324013-0b072024-4715-4296-a9a5-d6c7fb4e8024.png) | ![Screenshot_1647326937](https://user-images.githubusercontent.com/88313112/158324029-5696d39c-9a2a-4cc2-bffa-9ea38580bb79.png) | ![Screenshot 2022-03-15 at 06 51 25](https://user-images.githubusercontent.com/88313112/158324066-bbb59526-a0bf-455b-954c-4147d6a6dc1e.png) |  ![Screenshot 2022-03-15 at 06 54 06](https://user-images.githubusercontent.com/88313112/158324098-1aada765-5440-4fe1-9d4b-384ad41af1a6.png) | ![Screenshot 2022-03-15 at 06 56 21](https://user-images.githubusercontent.com/88313112/158324128-4a10c5ac-9a67-4992-9fbb-3bb05122f5f2.png)



</details>

<details>
<summary>complete sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        backgroundColor: Colors.white,
        body: Center(
          child: Transform.scale(
            scale: 16,
            child: Container(
              height: 25,
              width: 25,
              color: Colors.yellow,
              child: CircularProgressIndicator(
                color: Colors.red,
                value: 0.000001,
                strokeWidth: 5,
              ),
            ),
          ),
        ),
      ),
    );
  }
}

```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.2.1 21D62 darwin-arm, locale en-GB)
    • Flutter version 2.10.3 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (13 days ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1426:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1861:10)
      #15     runZonedGuarded (dart:async/zone.dart:1849:12)
      #16     runZoned (dart:async/zone.dart:1780:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:205:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:309:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (4 available)
    • M2007J20CG (mobile) • 5dd3be00                  • android-arm64  • Android 11 (API 30)
    • Nexus (mobile)      • 00008020-001875E83A38002E • ios            • iOS 15.3 19D50
    • macOS (desktop)     • macos                     • darwin-arm64   • macOS 12.2.1 21D62 darwin-arm
    • Chrome (web)        • chrome                    • web-javascript • Google Chrome 99.0.4844.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

```
[✓] Flutter (Channel master, 2.11.0-0.0.pre.885, on macOS 12.2.1 21D62 darwin-arm, locale en-GB)
    • Flutter version 2.11.0-0.0.pre.885 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 47acaac19e (5 hours ago), 2022-03-14 22:30:19 -0400
    • Engine revision 0cf0ea0e78
    • Dart version 2.17.0 (build 2.17.0-202.0.dev)
    • DevTools version 2.11.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 213.5744.122

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (4 available)
    • M2007J20CG (mobile) • 5dd3be00                  • android-arm64  • Android 11 (API 30)
    • Nexus (mobile)      • 00008020-001875E83A38002E • ios            • iOS 15.3 19D50
    • macOS (desktop)     • macos                     • darwin-arm64   • macOS 12.2.1 21D62 darwin-arm
    • Chrome (web)        • chrome                    • web-javascript • Google Chrome 99.0.4844.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>
