### ISSUE TITLE
[file_selector] latest package version results in an exception from calling `getSavePath`

### ISSUE THREAD

**Issue by GroovinChip** [flutter/flutter#99910]
The following code worked in the previous version of `file_selector` that did not contain an endorsed version of `file_selector_macos`:
```dart
final path = await getSavePath(
  suggestedName: fileName,
);
```
Using `file_selector: ^0.8.4`, `file_selector_macos: ^0.8.2`, and the code above, I now get the following exception:
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method getSavePath on channel plugins.flutter.io/file_selector_macos)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
<asynchronous suspension>
#1      DesktopAttachmentHandler.download (package:stream_chat_flutter/src/attachment/attachment_handler.dart:85:18)
<asynchronous suspension>
#2      DownloadMenuItem.onSelected.<anonymous closure> (package:stream_chat_flutter/src/context_menu_items/download_menu_item.dart:23:9)
<asynchronous suspension>
```
I believe [this commit](https://github.com/flutter/plugins/commit/77e841d5c88178f35428be0c3d274d0f05301c6d) may be the culprit.

I have tried using `file_selector` without `file_selector_macos`, given that macos is endorsed now, but there is no difference.

@stuartmorgan this might be of interest to you.

## Logs

<details>
<summary>Logs</summary>

```
groovinchip@reubens-mbp desktop_widgets % flutter doctor -v
[✓] Flutter (Channel stable, 2.10.2, on macOS 12.2.1 21D62 darwin-x64, locale
    en-US)
    • Flutter version 2.10.2 at /Users/groovinchip/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (3 weeks ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/groovinchip/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message
      below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle
      (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      InputStream.readString
      (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read
      (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer
      (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes
      (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml
      (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion
      (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage
      (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate
      (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure>
      (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure>
      (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1426:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1861:10)
      #15     runZonedGuarded (dart:async/zone.dart:1849:12)
      #16     runZoned (dart:async/zone.dart:1780:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks
      (package:flutter_tools/src/doctor.dart:205:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:309:47)
      #20     DoctorCommand.runCommand
      (package:flutter_tools/src/commands/doctor.dart:50:48)
      #21     FlutterCommand.verifyThenRunCommand
      (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure>
      (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure>
      (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure>
      (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure>
      (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand
      (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure>
      (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure>
      (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.65.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (5 available)
    • iPad (9th generation) (mobile)               •
      DC92F5C9-93D1-4C17-84E6-FB3435CE3AB8 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • iPad Air (4th generation) (mobile)           •
      0F31C6CF-E73B-4F9A-A2B9-6A3434441773 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • iPad Pro (11-inch) (3rd generation) (mobile) •
      F6D09A60-6242-4166-A47D-139A6D9C88FD • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)                              • macos
      • darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)                                 • chrome
      • web-javascript • Google Chrome 99.0.4844.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

**Comment by stuartmorgan** [comment]
Is the plugin listed in your GeneredPluginRegistrant.swift?

**Comment by maheshmnj** [comment]
Hi @GroovinChip, Thanks for filing the issue. I verified with the below code sample, I couldn't reproduce the exception and  


```yaml
  file_selector: ^0.8.4 
  file_selector_macos: ^0.8.2
```

I do see `file_selector` plugin registered in `macos/flutter/GeneratedPluginRegistrant.swift`, could you please confirm if this is the case for you?

```swift
//
//  Generated file. Do not edit.
//

import FlutterMacOS
import Foundation

import file_selector_macos

func RegisterGeneratedPlugins(registry: FlutterPluginRegistry) {
  FileSelectorPlugin.register(with: registry.registrar(forPlugin: "FileSelectorPlugin"))
}

```

Surprisingly adding `await` to `getSavedPath` never completes for me

<details>
<summary>code sample</summary>

```dart
import 'package:file_selector/file_selector.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        floatingActionButton: FloatingActionButton(
          onPressed: () async {
            final path = await getSavePath(
              suggestedName: '/Users/mahesh/Desktop/test_app/',
            );
            print('printing $path'); // control never reaches here
          },
          child: const Icon(Icons.file_copy_outlined),
        ),
        body: Container());
  }
}

```
</details> 
  

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.10.3 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (20 hours ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • 192.168.1.5:5555 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos            • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 99.0.4844.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by GroovinChip** [comment]
@stuartmorgan @maheshmnj No, when I use the latest plugin versions I only see `FileSelectorWeb` included in my `generated_plugin_registrant.dart` and `file_selector_macos` does not appear in my `MainFlutterWindow.swift`.

**Comment by stuartmorgan** [comment]
> `file_selector_macos` does not appear in my `MainFlutterWindow.swift`.

It shouldn't be it `MainFlutterWindow.swift`, it should be in `GeneratedPluginRegistrant.swift` (which is why that's the file we asked about above). Is it there?

**Comment by GroovinChip** [comment]
> > `file_selector_macos` does not appear in my `MainFlutterWindow.swift`.
> 
> It shouldn't be it `MainFlutterWindow.swift`, it should be in `GeneratedPluginRegistrant.swift` (which is why that's the file we asked about above). Is it there?

Apologies, I misread the name of the `.swift` file.

Yes, when using `file_selector: ^0.8.4` without using `file_selector_macos`, I do see `file_selector_macos` in the `GeneratedPluginRegistrant.swift` file.

**Comment by maheshmnj** [comment]
As of `file_selector: ^0.8.4` we don't need to depend on `file_selector_macos`, I did verify with or without `file_selector_macos` and I am unable to reproduce the exception, Could you please share a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) to investigate further?

**Comment by stuartmorgan** [comment]
> @maheshmnj strangely I also cannot reproduce this issue in a separate project, although I cannot get the file explorer to show at all.

Did you add the necessary entitlement to the new project's macOS runner?

**Comment by stuartmorgan** [comment]
For the original project: if the macOS host-side code is in the generated registrant, then I don't see why it wouldn't be handling messages. All I can suggest is to try running it under the native debugger with breakpoints to make sure the plugin's registration is definitely being called and setting the handler.

**Comment by maheshmnj** [comment]
> Did you add the necessary entitlement to the new project's macOS runner?

I didn't add this during my last triage, this was missing in the readme (fixed in `0.8.4+1`). After adding entitlements with read and write access, I can see the select path dialog

```
  <key>com.apple.security.files.user-selected.read-write</key>
  <true/>
```

https://user-images.githubusercontent.com/31410839/158313831-e701e227-0679-4d6c-9b16-3d2225b40ba7.mov

> Surprisingly adding await to getSavedPath never completes for me

This doesn't happen anymore and I see the selected  path getting logged to console based on this [code sample](https://github.com/flutter/flutter/issues/99910#issuecomment-1064844148)

@GroovinChip Please ensure that you have added the entitlements as mentioned in the readme.

**Comment by GroovinChip** [comment]
Okay, after adding the entitlement it works properly in my reproduction code (0.8.4 and 0.8.4+1). What I don't understand is why my original code produces that exception; the entitlement has been present there for some time.

For reference, my original code is in the `stream_chat_flutter` package, on our `desk_web_dev` branch where I am working on adding desktop (and web) support to `stream_chat_flutter`. [Here](https://github.com/GetStream/stream-chat-flutter/blob/desk_web_dev/packages/stream_chat_flutter/lib/src/attachment/attachment_handler.dart#L114) is a good example of my usage of the `file_selector` plugin, which produces the exception on the latest version _without_ using the `file_selector_macos` dependency. The `macos` runner for our sample app is found [here](https://github.com/GetStream/stream-chat-flutter/tree/desk_web_dev/packages/stream_chat_flutter/example/macos/Runner).

**Comment by stuartmorgan** [comment]
> What I don't understand is why my original code produces that exception

Have you tried running under the debugger in Xcode as I suggested above to see if the plugin registration code runs?

> the entitlement has been present there for some time.

The exception has nothing to do with entitlements. Seeing that exception means that the native code that would require entitlements isn't ever running.

**Comment by GroovinChip** [comment]
I'm actually not getting _any_ logs when I run via Xcode. I don't even see any exceptions caught. But the file system doesn't appear still. I'm going to try running a `pod update` in my `macos` runner - that sometimes fixes problems for me. Will report back shortly.

**Comment by GroovinChip** [comment]
Closing per the edit to my previous comment.
