### ISSUE TITLE
Native fatal exception: Unable to start activity ComponentInfo

### ISSUE THREAD

**Issue by subzero911** [flutter/flutter#99982]
The same to https://github.com/flutter/flutter/issues/37566 

I had received a report from crashlytics, seems like on certain devices an app crashes on startup.

![image](https://user-images.githubusercontent.com/12999702/157902490-c7cea7b2-243d-4e87-85a2-b57e4b9979d4.png)

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{ru.gosuslugi.culture/ru.notamedia.pushka.pushka.MainActivity}: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/ru.gosuslugi.culture-k5eiNIpRHIhGteidPzFN1w==/base.apk"],nativeLibraryDirectories=[/data/app/ru.gosuslugi.culture-k5eiNIpRHIhGteidPzFN1w==/lib/arm64, /system/lib64, /vendor/lib64]]] couldn't find "libflutter.so"
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2969)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3047)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1777)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:6861)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:450)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

```
Caused by java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/ru.gosuslugi.culture-k5eiNIpRHIhGteidPzFN1w==/base.apk"],nativeLibraryDirectories=[/data/app/ru.gosuslugi.culture-k5eiNIpRHIhGteidPzFN1w==/lib/arm64, /system/lib64, /vendor/lib64]]] couldn't find "libflutter.so"
       at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(FlutterLoader.java:315)
       at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:326)
       at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:206)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine(FlutterActivityAndFragmentDelegate.java:256)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:166)
       at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:459)
       at android.app.Activity.performCreate(Activity.java:7110)
       at android.app.Activity.performCreate(Activity.java:7101)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2922)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3047)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1777)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:6861)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:450)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

```
Caused by java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/ru.gosuslugi.culture-k5eiNIpRHIhGteidPzFN1w==/base.apk"],nativeLibraryDirectories=[/data/app/ru.gosuslugi.culture-k5eiNIpRHIhGteidPzFN1w==/lib/arm64, /system/lib64, /vendor/lib64]]] couldn't find "libflutter.so"
       at java.util.concurrent.FutureTask.report(FutureTask.java:123)
       at java.util.concurrent.FutureTask.get(FutureTask.java:193)
       at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(FlutterLoader.java:223)
       at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:326)
       at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:206)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine(FlutterActivityAndFragmentDelegate.java:256)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:166)
       at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:459)
       at android.app.Activity.performCreate(Activity.java:7110)
       at android.app.Activity.performCreate(Activity.java:7101)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2922)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3047)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1777)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:6861)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:450)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

```
Caused by java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/ru.gosuslugi.culture-k5eiNIpRHIhGteidPzFN1w==/base.apk"],nativeLibraryDirectories=[/data/app/ru.gosuslugi.culture-k5eiNIpRHIhGteidPzFN1w==/lib/arm64, /system/lib64, /vendor/lib64]]] couldn't find "libflutter.so"
       at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
       at java.lang.System.loadLibrary(System.java:1661)
       at io.flutter.embedding.engine.FlutterJNI.loadLibrary(FlutterJNI.java:123)
       at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:174)
       at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:166)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:780)
```

flutter doctor:
[√] Flutter (Channel unknown, 2.8.1, on Microsoft Windows [Version 10.0.19043.1586], locale ru-RU)
    • Flutter version 2.8.1 at C:\Users\subze\AppData\Roaming\fvm\current
    • Upstream repository unknown
    • Framework revision 77d935af4d (3 months ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at D:\Android_SDK
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.5)
    • Visual Studio at D:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31729.503
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] IntelliJ IDEA Community Edition (version 2020.1)
    • IntelliJ at D:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.3
    • Flutter plugin version 45.1.3
    • Dart plugin version 201.7223.43

[√] Connected device (4 available)
    • M2101K9AG (mobile) • cc706425 • android-arm64  • Android 11 (API 30)
    • Windows (desktop)  • windows  • windows-x64    • Microsoft Windows [Version 10.0.19043.1586]
    • Chrome (web)       • chrome   • web-javascript • Google Chrome 99.0.4844.51
    • Edge (web)         • edge     • web-javascript • Microsoft Edge 97.0.1072.55
• No issues found!

**Comment by maheshmnj** [comment]
Hi @subzero911, Thanks for filing the issue.

There is a similar issue describing this case https://github.com/flutter/flutter/issues/83596, Please follow up there for further updates, Closing this issue as a duplicate. If you disagree feel free to write in the comments and we will reopen it.

Thank you.
